### ISSUE TITLE
Horizontal separator doesn't appear between Pinned and unpinned tabs

### ISSUE THREAD

**Issue by KodusTheOnly** [zen-browser/desktop#100]
### What happened?

When creating a new tab, the horizontal divider doesn't appear to separate the pinned tabs and non pinned tabs.
Video below:
https://github.com/user-attachments/assets/374d183a-baf0-4fd4-8e65-0672548699d3

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.7

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
![Screenshot_20240729_011705](https://github.com/user-attachments/assets/9c92ce0c-f698-4b17-9696-cab08bc0e644)

this is because there's a tab in the middle that's "hidden", so the border is applied to a hidden tab, it will be fixed for the next release. Thanks!
