### ISSUE TITLE
Tabs disappear from the sidebar if current tab is closed

### ISSUE THREAD

**Issue by jackra1n** [zen-browser/desktop#1000]
### What happened?

- Open Zen browser
- Open at least a few links in a new tab
- Close current tab
- All other tabs except one disappear

Video example:

https://github.com/user-attachments/assets/f427ae0f-a31f-4e7a-9cc6-f485789a74ba

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.30

### Severity impact

High

### What platform are you seeing the problem on?

Linux

**Comment by jackra1n** [comment]
> I have several tabs by closing the browser instead. You can try `Ctrl+Shift+T` to see if you can reopen the closed tabs. In my case, it did not work.

I've had this bug a few times now and I was only able to reproduce it now. From what I noticed I don't think the tabs are being closed, they literally just disappear from the sidebar and re-appear when the window is closed.

**Comment by mauro-balades** [comment]
hmmm

**Comment by jackra1n** [comment]
Tried to get more info about this issue so what I noticed is that if the links that have been opened in a new tab, have been open that issue will not happen for that tab. Here 2 more videos I took: 

https://github.com/user-attachments/assets/e37e0909-6ee4-42e5-bf46-b4c2f87dbfbd


https://github.com/user-attachments/assets/2d16e02d-6cd7-4ccb-b258-5d2a10b78e1a

**Comment by jackra1n** [comment]
Just updated zen browser to 1.0.0-a.37 and the issue seems to be pretty much fixed. I will close this issue now
