### ISSUE TITLE
When multiple custom urls are specified as the home page, only the first opens properly

### ISSUE THREAD

**Issue by iSaluki** [zen-browser/desktop#1003]
### What happened?

- When multiple custom URLS are being specified as the homepage in `about:preferences#home` using the format `https://url1.com|https://url2.com` only the first one opens normally on browser start.
- The entire list of URLs should be opened as normal tabs in the default workspace, at browser launch.
- Any URLs after the first one get opened as **Hidden tabs**, which means it is more work to get them into my workspace properly.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.30 (64-bit) (flatpak)

### Severity impact

Low

### What platform are you seeing the problem on?

Linux

**Comment by iSaluki** [comment]
No clue why, but this only seems to occur if you only have the default workspace. If you add more workspaces, it works some of the time. With multiple workspaces it does seem to try and split startup tabs between workspaces sometimes.

**Comment by nikitimi** [comment]
In my case, I specified one custom URL, but it is not setting the URL as the default homepage.

**Take Note** _that I'm also using the multiple workspace_ BETA.

Here is my set-up:
![zen-homepage](https://github.com/user-attachments/assets/a8b5851f-cf1e-4d1a-9a37-be654e493a5b)

**Comment by nikitimi** [comment]
Upon clicking the Home button near the Refresh button, the custom URL take in effect.
I hope that we can see the Custom URL(s) in homepage and new windows are well.
