### ISSUE TITLE
Expand tabs on hover issue with tabs on the right

### ISSUE THREAD

**Issue by Deluwuta** [zen-browser/desktop#1008]
### What happened?

![image](https://github.com/user-attachments/assets/3c84b5c9-e454-4c4a-85c9-656d04aa95ba)

When using the "Expand tabs on hover" option with the tabs on the right, the tab bar starts to flicker when hovered and, when you move the mouse out of the collapsed bar, it expands without being positioned correctly. 

This error does not happen with tabs on the left.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.32

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by neurokitti** [comment]
yup got the same issue! lucky I don't use tabs on right but I did run into the issue.

https://github.com/user-attachments/assets/e6d02227-7b34-47d2-b275-2ba1f1234156

**Comment by mauro-balades** [comment]
This should be fixed
