### ISSUE TITLE
Zen doesn't open external links if no browser instances are running

### ISSUE THREAD

**Issue by AdilDevStuff** [zen-browser/desktop#1009]
### What happened?

I m having this issue that when all the instances of zen are closed and when I open any external link, it just opens the browser window with the last tab opened and no link. I have to open the link again to get the correct link working!

Im using flatpak version and this is a video of this bug/issue

https://github.com/user-attachments/assets/caeedc2b-5a0f-4ed6-858b-52c869791ba8

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.30

### Severity impact

Medium

### What platform are you seeing the problem on?

Linux

**Comment by mcmerdith** [comment]
This issue also occurs for me when opening an external link without the default profile open. As an example I use a different profile for school so when I only have my school profile open and launch an external link it opens my default profile without following the link. Experienced on Windows 11. Ideal experience would be the link opens in the most recently used profile

**Comment by diego-velez** [comment]
I'm also having this issue, but for me it doesn't open the link that I'm trying to open even if I already have a Zen instance open.

**Comment by EzeKoren** [comment]
I have the same issue as Diego, where clicking on a link doesn't open it in a running instance at all, and if there are no open Zen instances, the browser doesn't launch when clicking a link. I have a single profile (the default one), and I'm also using the Flatpak version 1.0.0-a.32 (64-bit) on Ubuntu 22.04 LTS.

**Comment by nettum** [comment]
Maybe this should be reported as an own issue, but I have a similar issue as @diego-velez and @EzeKoren.
When I click an external URL on slack it opens a new instance (but does not load the URL, just opens a new empty tab) even though I already have a running instance open. Seems like both browser windows uses the same profile (default).

```
> lsb_release -a && /home/marius/Programs/zen/zen --version
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy
Mozilla Zen 1.0.0-a.39
```

I downloaded the optimized portable zip from https://zen-browser.app/download

**Comment by cl3nn** [comment]
+1 :point_up:  same problem on Ubuntu 22.04.5 LTS.(wayland & Xorg)   Ubuntu 24.04.1 LTS (Xorg)  doesnt have this problem

**Comment by JSGRD22** [comment]
> When I click an external URL on slack it opens a new instance (but does not load the URL, just opens a new empty tab) even though I already have a running instance open. Seems like both browser windows uses the same profile (default).

same problem on deepin 23 with any external link redirect

**Comment by nettum** [comment]
So, after looking at the latest comments in #1988 and the [desktop file](https://github.com/zen-browser/desktop/blob/dev/AppDir%2Fzen.desktop) in the zen repo, I added `%u` to the desktop Exec entry: `Exec=/home/marius/Programs/zen/zen %u`

This solved it for me.
For the record I created that desktop file manually as this is not created by zen (at least not when I used the portable zip option to download)

**Comment by galaxi-the-son** [comment]
@nettum thank you ♥️♥️

**Comment by GiovanePS** [comment]
@nettum It works!! Thank u 🎉

**Comment by razvanbackpack** [comment]
@nettum's solution fixed it.

Sorry for necro-ing this, but it *still* happens. Just ran into it on linux, the only fix was the `%u` parameter.

**Comment by fbennassar** [comment]
@nettum Thank u man 👍
