### ISSUE TITLE
AppImage Support

### ISSUE THREAD

**Issue by maverick74** [zen-browser/desktop#101]
**Is your feature request related to a problem? Please describe.**
No, it's just that it's a lot more easier to try Zen Browser

**Describe the solution you'd like**
Support Linux's AppImage 

**Describe alternatives you've considered**
i just won't add any more flatpak repos beside the ones that come with the distro

**Additional context**
AppImage image allows one to download, run and share a program anywhere without having to install it! It's just that great for me.

Please consider it :)

**Comment by mauro-balades** [comment]
Absolutely!

**Comment by Samueru-sama** [comment]
Since you already release a zipped build that can be turned into an appimage, provided said build wasn't compile on a too new version of glibc, normally the glibc version of the oldest still supported ubuntu lts release is used for this. But if not possible people try the next version. 

If that's the case all that needs to be done is run appimagetool on the existing portable build and create the `AppRun` script which at the bare minimum is something like this: 

```
#!/bin/sh
CURRENTDIR="$(dirname "$(readlink -f "$0")")"
"$CURRENTDIR/path/to/zen" "$@"
```

And bundle an icon and a .desktop file.

Also I recommend you use this [appimagetool](https://github.com/probonopd/go-appimage) which makes an appimage with the static runtime and gets rid of the common libfuse2 dependency issue that affects many appimages.

**Comment by mauro-balades** [comment]
Honorable mention to: https://github.com/srevinsaju/Firefox-Appimage/tree/master

**Comment by gunir** [comment]
I made AppImage template for Floorp, it's really easy as long as you have tar.gz/bz:
https://github.com/gunir/Floorp-AppImage

**Comment by mauro-balades** [comment]
I've made the workflow for creating AppImages. It will be released today along with a.10!

I comment again once it's out.

**Comment by mauro-balades** [comment]
It's already out! https://github.com/zen-browser/desktop/releases/download/1.0.0-a.10/zen.AppImage

If it works, I'll add it to the downloads page

**Comment by mauro-balades** [comment]
What's wrong with it?

**Comment by mauro-balades** [comment]
Could you run it on the terminal?

**Comment by Samueru-sama** [comment]
> well... it just doesn't do anything. Does not load or open main with.
> 
> it's as if it didn't click on it!

Try to open it in the terminal

drop the appimage in $HOME and do this: 

```
chmod +x ./zen.AppImage
./zen.AppImage
```

**Comment by maverick74** [comment]
`chmod +x ./zen.AppImage`

returns nothing

`./zen.AppImage`
returns "illegal instruction (core dumped)" (or something similar...)


> edit: Worth mentioning that it works for me.

yeah... that part i assumed or you wouldn't be publishing it here!!! ahah

i have other appimages and they work well
(i'm on neon (ubuntu based) btw)

**Comment by Samueru-sama** [comment]
`illegal instruction (core dumped)`

iirc that error happens when you try to use a wrong architecture or your cpu doesn't support some compiler flags.

What are the specs of your PC?

**Comment by ptr1337** [comment]
> `illegal instruction (core dumped)`
> 
> iirc that error happens when you try to use a wrong architecture or your cpu doesn't support some compiler flags.
> 
> What are the specs of your PC?
> 
> Do you get that same error when trying the zipped build?

Yes, it seems to still use:
AES, x86-64-v3 in RUSTFLAGS. This seems to break for 2012 or earlier cpus.

**Comment by maverick74** [comment]
You really had to ask?!
yeah... it's kind of a living museum ahaha

`Operating System: KDE neon 6.0
KDE Plasma Version: 6.1.3
KDE Frameworks Version: 6.4.0
Qt Version: 6.7.2
Kernel Version: 6.2.0-32-generic (64-bit)
Graphics Platform: Wayland
Processors: 2 × Pentium® Dual-Core CPU E6600 @ 3.06GHz
Memory: 7.7 GiB of RAM
Graphics Processor: AMD CEDAR
Manufacturer: O.E.M
Product Name: O.E.M`

but hey... it's not a zx spectrum, so all good, right?! ahah



> Do you get that same error when trying the zipped build?

i didn't try the zipped build...

**Comment by Samueru-sama** [comment]
> Yes, it seems to still use: AES, x86-64-v3 in RUSTFLAGS. This seems to break for 2012 or earlier cpus.

I can tell you that yuzu (the emulator) used to make its appimage for x86-64 v2 and they still had many bug reports about it from sandy bridge users.

>You really had to ask?!

Yeah your CPU is very old, doesn't even support x86-64 v2. The zipped build will give you the same error.

**Comment by ptr1337** [comment]
> I can tell you that yuzu (the emulator) used to make its appimage for x86-64 v2 and they still had many bug reports about it from pre-sandy bridge users.

Yes, I know. I think there should be a generic build and maybe x86-64-v3 build.

**Comment by Samueru-sama** [comment]
> > I can tell you that yuzu (the emulator) used to make its appimage for x86-64 v2 and they still had many bug reports about it from pre-sandy bridge users.
> 
> Yes, I know. I think there should be a generic build and maybe x86-64-v3 build.

Also suyu (a fork of yuzu) experimented with making a x86-64 v3 appimage that never ended up being officially released, you could only get it if you went and digged the CI looking for it, and somehow somebody ended up trying that appimage on a sandy bridge PC and ended up in their discord asking for help lol.

It's up to the developer if they want to support anything older than haswell, my opinion here is neutral.

**Comment by ptr1337** [comment]
> > > I can tell you that yuzu (the emulator) used to make its appimage for x86-64 v2 and they still had many bug reports about it from pre-sandy bridge users.
> > 
> > 
> > Yes, I know. I think there should be a generic build and maybe x86-64-v3 build.
> 
> Also suyu (a fork of yuzu) experimented with making a x86-64 v3 appimage that never ended up being officially released, you could only get it if you went and digged the CI looking for it, and somehow somebody ended up trying that appimage on a sandy bridge PC and ended up in their discord asking for help lol.
> 
> It's up to the developer if they want to support anything older than haswell, my opinion here is neutral.

Well, it works.
On CachyOS we compiling all archlinux packages with x86-64-v3, x86-64-v4 and Zen4 Optimization - but we also have a detection at the installation time and applies it correctly, depending on the users cpu.

**Comment by maverick74** [comment]
well, i guess i'll have to quit on this...

but it will still be useful for others to be able to use the appimage :)

**Comment by Samueru-sama** [comment]
> well, i guess i'll have to quit on this...

I personally ended up getting one of those very cheap xeon combos in aliexpress with an E5-2640v4 + 16 GiB + Motherboard for 60 usd. I think there are even cheaper solutions but they are sandy/ivy bridge and only compatible with x86-64 v2 and wouldn't work here.

**Comment by ptr1337** [comment]
Should be fixed in A11 release.

**Comment by mauro-balades** [comment]
If you are getting errors with the appimage, please select a "generic" build in the downloads pages thanks!

**Comment by Samueru-sama** [comment]
@mauro-balades sorry to bother, but what does the specific build target specifically?

When other browser's do this they usually specify avx2 or sse4 for example.

**Comment by ptr1337** [comment]
> @mauro-balades sorry to bother, but what does the specific build target specifically?
> 
> When other browser's do this they usually specify avx2 or sse4 for example.

The generic one is build against the x86-64 generic target. The specific build is built against x86-64-v3 (avx/avx2)
