### ISSUE TITLE
can't install themes from theme store

### ISSUE THREAD

**Issue by 0ussamaBernou** [zen-browser/desktop#1010]
### What happened?

i navigate to https://www.zen-browser.app/themes i try to install a theme, i click install theme the button color changes and nothing happens.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.28

### Severity impact

Low

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
don't know how to get logs
```

**Comment by Arcensyl** [comment]
I'm having the same issue, the "Install theme" button just turns grey and does nothing. I'm also on Linux; I just installed the browser off of Arch's AUR.

**Comment by n7itro** [comment]
@Arcensyl @0ussamaBernou can you verify that you are on the latest version of Zen? (v32)

**Comment by Arcensyl** [comment]
@n7itro I should've checked that, apologies. The AUR package appears to be slightly behind, as I am running 1.0.0-a.31.

**Comment by Arcensyl** [comment]
@n7itro Okay, installing themes appears to work fine on v32. Sorry about that!

**Comment by 0ussamaBernou** [comment]
> @Arcensyl @0ussamaBernou can you verify that you are on the latest version of Zen? (v32)

i'm using the flatpak from the button in the repo readme and i installed the latest version.
output of running `flatpak info io.github.zen_browser.zen`
```bash

Zen Browser - A fast, beautifull browser

          ID: io.github.zen_browser.zen
         Ref: app/io.github.zen_browser.zen/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.0.0-a.28
     License: MPL-2.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 292.2 MB
     Runtime: org.freedesktop.Platform/x86_64/23.08
         Sdk: org.freedesktop.Sdk/x86_64/23.08

      Commit: 8afaf9fcf381684dee42a0fb371a599a936975e9d80c4df2e17d04760c77a029
      Parent: a2c35f251e5ca3c26d9e182dbaec010d40d80026a339881f6bae7782a3834761
     Subject: Update to version 1.0.0-a.30 (ae435f3d)
        Date: 2024-08-26 16:36:20 +0000
```
```bash
flatpak update io.github.zen_browser.zen 
Looking for updates…

Nothing to do.
```

**Comment by 0ussamaBernou** [comment]
I tried the app image and it's working great, I think the latest version is not pushed to flathub.
