### ISSUE TITLE
Unable to install themes from zen-browser themes store

### ISSUE THREAD

**Issue by benni347** [zen-browser/desktop#1014]
### What happened?

I can not install custom themes from the theme store tried:
- https://www.zen-browser.app/themes/5a007026-0801-4a5d-9740-f17dc1c3ff21
- https://www.zen-browser.app/themes/58649066-2b6f-4a5b-af6d-c3d21d16fc00

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.30

### Severity impact

Low

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
Please update to version 32!

**Comment by SalahAdDin** [comment]
I'm suffering the same issue in Linux, I'm using the aur version(1.0.0-a.31 (64-bit). I guess once the version is updated I won't have any problem.

Thank you!

**Comment by Mgldvd** [comment]
Same issue 1.0.0-a.34 (64-bit)

![image](https://github.com/user-attachments/assets/b17c5f6c-b359-468a-bb09-1fc129fbe678)

Thank you!

**Comment by NOCanoa** [comment]
@Mgldvd  server is down, will be back online  soon
