### ISSUE TITLE
Suggestion: Automatically launch Picture in Picture when changing to a different tab while video is playing

### ISSUE THREAD

**Issue by slrgt** [zen-browser/desktop#1016]
### What happened?

When watching a youtube video sometimes I have to leave the tab to search something on google or wikipedia and it would be great if the video could automatically launch in the Picture in Picture mode. This happens in the Arc browser and it would be great to have this in a firefox based browser like Zen

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

latest

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
Please use discussions for enhacements

**Comment by slrgt** [comment]
already suggest in #996 and already coming in the next official firefox release
