### ISSUE TITLE
Option to increase pinned tabs icon

### ISSUE THREAD

**Issue by thesoloist-1** [zen-browser/desktop#1018]
### What happened?

With the current vertical tabs sidebar, the pinned tabs are really small. An option to increase the size of the icons would be a great additional feature. Below is arcs version of pinned icons which has a larger background height and width to increase the pins size and also the current sidebar in zen.

![Screenshot 2024-08-28 at 12 58 16 PM](https://github.com/user-attachments/assets/35df3026-a2b3-48ca-8416-4a781772dc15)
<img width="139" alt="Screenshot 2024-08-28 at 12 53 40 PM" src="https://github.com/user-attachments/assets/043bdbe2-2f4c-4373-8cb7-66758d71d7a5">

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.32

### Severity impact

Low

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by mauro-balades** [comment]
Please use discussions for suggestions, if you want, you could try using 

https://www.zen-browser.app/themes/ad97bb70-0066-4e42-9b5f-173a5e42c6fc

**Comment by thesoloist-1** [comment]
That works perfect! Didn't see that in the themes store yesterday. Thank you.
