### ISSUE TITLE
Google.com sometimes doesn't respect the dark mode preferenc

### ISSUE THREAD

**Issue by nazmiyigitefe** [zen-browser/desktop#1019]
### What happened?

Sometimes both on my Mac and Windows device google.com doesn't respect my theme preference that I set on Zen Browser. It doesn't happens on Firefox and some others.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.32

### Severity impact

Low

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by mauro-balades** [comment]
You need to ctrl+R to fully reload google's cache
