### ISSUE TITLE
Suggestion: make Workspaces containers-like isolated from one another

### ISSUE THREAD

**Issue by Truleu** [zen-browser/desktop#1020]
### What happened?

The most important thing about workspaces in Arc for example is that they are isolated from one another, like the container tabs are in Zen and Firefox. If this is not possible it would be great if at least there was an option to bind a container to a workspace

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.32

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
Please use discussions to submit suggestions
