### ISSUE TITLE
Toggle Web Panels shortcut is the same as New Private Window shortcut

### ISSUE THREAD

**Issue by slrgt** [zen-browser/desktop#1021]
### What happened?

The default shortcut for Toggle Web Panels is the same shortcut as the default New Private Window

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

129.0.2

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
This has been fixed but unfortunately, it doesn't apply to new updates... you can manually remove it on the preferences page 👍🏽

**Comment by slrgt** [comment]
What shortcut was the web panel shortcut changed to?

**Comment by mauro-balades** [comment]
`Alt+P`
