### ISSUE TITLE
Compact Sidebar Expands across Profiles

### ISSUE THREAD

**Issue by xhlsa** [zen-browser/desktop#1022]
### What happened?

With two instances of the browser open at once, one set to Profile 1, the other Profile 2. If I expand the compact sidebar on Profile 2, the compact sidebar expands on Profile 1 as well. 

Personally, I would like these to be more independent. 

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.30

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by camillof** [comment]
+1 to this.

It isn't necessarily related to profiles, but to different windows.

My use case: I would like to have a private window running YouTube with compact mode enabled and a second window with compact mode disabled for ongoing work.
