### ISSUE TITLE
Sidebar collapses when right clicking tab

### ISSUE THREAD

**Issue by NyxErinys** [zen-browser/desktop#1024]
### What happened?

With `Expand Tabs on Hover` set and side bar set to normal mode, when you go to right click on a tab the sidebar collapses. This happens across Windows, Linux, and MacOS.

This seems to be a side effect of how Firefox handles the right-click context menu compared to chromium-based browsers and Safari. Firefox continues to check hover state even when the right-click context menu is open so when you mouse in on the menu it just doesn't hover anything on the page, meanwhile the other two lock the hover state of the page underneath when the menu is open.

While this seems like a Firefox thing I thought I'd report it here because it affects something zen specific (the Sidebar).

Quick clip showing the main issue and then showing how Zen (and Firefox) handle hover and right click
[Screencast from 2024-08-28 16-14-33.webm](https://github.com/user-attachments/assets/dcf1101c-8849-4fe4-b27a-790a58875382)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0.a.32-1

### Severity impact

Low

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
This has been fixed for the next release, thanks!
