### ISSUE TITLE
Devtools console not giving output 

### ISSUE THREAD

**Issue by tommdq** [zen-browser/desktop#1025]
### What happened?

I've been using Zen for a few weeks. Recently I discovered that my devtools console isn't giving output for some reason. I tried Firefox and it works just fine. Is there any config I'm missing that it's disabled by default in Zen? 
The console it's giving a "preview" output before pressing enter but after that it doesn't shows this preview output as Firefox does.
![Screenshot 2024-08-28 182954](https://github.com/user-attachments/assets/a7cab270-96af-4b61-88bc-fd192cbfc87b)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.29

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by ethanrusz** [comment]
This seems to be working correctly on the 1.0.0-a.30 (64-bit) Flatpak version.

![image](https://github.com/user-attachments/assets/9e66d8f1-526a-4f90-9d23-fb6dba91b6e1)

**Comment by tommdq** [comment]
> This seems to be working correctly on the 1.0.0-a.30 (64-bit) Flatpak version.
> 
> ![image](https://private-user-images.githubusercontent.com/35783974/362478855-9e66d8f1-526a-4f90-9d23-fb6dba91b6e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4OTEyNzQsIm5iZiI6MTcyNDg5MDk3NCwicGF0aCI6Ii8zNTc4Mzk3NC8zNjI0Nzg4NTUtOWU2NmQ4ZjEtNTI2YS00ZjkwLTlkMjMtZmI2ZGJhOTFiNmUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDAwMjI1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhOWIzNmIwN2JkODFlY2JjYzBiYmJkNjU1YWE4MmYyN2VhMjk1MjRmOWQ4ZDRiZGQ4NmZmNjdkZjlmMjQ2MTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.56u75NaxsTF4_CkwxbUuzDVa8ieM_WR5Y8Fib2eIYp8)
