### ISSUE TITLE
Checkboxes are almost invisible

### ISSUE THREAD

**Issue by KodusTheOnly** [zen-browser/desktop#103]
### What happened?

On websites+extension that has a checkbox, they're almost invisible.
Video below

https://github.com/user-attachments/assets/16426dff-b5af-4570-95a8-ca944576f280

https://github.com/user-attachments/assets/be1b3352-086e-4bbe-ae3a-e5efe9a59b1b

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.8

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
This has been fixed in version 25 (currenly building). Thanks!
