### ISSUE TITLE
Cannot start zen-browser

### ISSUE THREAD

**Issue by madonuko** [zen-browser/desktop#1032]
### What happened?

1. Click on any links / `flatpak run io.github.zen_browser.zen` / `xdg-open https://github.com`
![image](https://github.com/user-attachments/assets/c340c0f5-e0c8-40f6-af0f-5c393a5a6025)
2. Double click on `Default Profile` or `Start Zen Browser`
![image](https://github.com/user-attachments/assets/ef2d2b43-1595-4c10-b8fe-57ce32d3b48d)
3. `Restart Zen Browser` goes back to step 2
4. Click `Exit` to finally stop

This makes the browser absolutely unusable.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.27, 1.0.0-a.32

### Severity impact

High

### What platform are you seeing the problem on?

Linux

**Comment by ekorchmar** [comment]
Does starting with `--safe-mode` work? Is anything logged to the terminal if you run it from there?

**Comment by madonuko** [comment]
Tried `--safe-mode` already, and no, absolutely no logs

I think I tried like most reasonable arguments/flags already.

**Comment by HarryHeres** [comment]
I believe your profile got corrupted. Is it possible for you to create a new profile in the profile manager and see if that works out for you?

**Comment by mauro-balades** [comment]
remove the folder completly and try again

**Comment by madonuko** [comment]
Which folder?

**Comment by mauro-balades** [comment]
The profiles folder

**Comment by madonuko** [comment]
Any clue here? I even tried deleting the entire `.var/app/io.github.zen_browser.zen` but it's still stuck inside the choose user profile window.

**Comment by madonuko** [comment]
Yup, still facing the same issue on the latest version.

**Comment by mr-cheffy** [comment]
Delete the files though, it looks like it was corrupted

**Comment by madonuko** [comment]
> Delete the files though, it looks like it was corrupted

I have deleted basically everything…

**Comment by RayZ3R0** [comment]
> > Delete the files though, it looks like it was corrupted
> 
> I have deleted basically everything…

Which distro are you on?

**Comment by madonuko** [comment]
Fedora
