### ISSUE TITLE
[workspace] Dragging tab to open in a new window does not keep selected workspace

### ISSUE THREAD

**Issue by LaurenceJJones** [zen-browser/desktop#1034]
### What happened?

When using workspaces sometimes I want to take the current tab and open it in a new window, upon doing so it will open the tab in the default workspace instead of retaining the currently selected workspace.

Note: If you only have one tab open when trying to separate in a new window then the bug does not occur and the workspace is retained, if you have more than one it happens to any tabs no matter the index.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.32 (64-bit)

### Severity impact

Low

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
N/A
```

**Comment by Aditya-Raj-Tiwari** [comment]
same for mac

**Comment by lv042** [comment]
For me it won't even keep the website you had open before it will just give you the start page instead

**Comment by toolchild** [comment]
I tried Zen today and this bug made me come here.
The bug still persists.

This browser looks pretty neat and Brave doesn't do it for me anymore.
Zen is not an option for me due to the madness this bug will cause me on a daily basis.

I thought I leave this customer feedback.
