### ISSUE TITLE
Adjusting tab width in grid view

### ISSUE THREAD

**Issue by theshineagency** [zen-browser/desktop#1035]
### What happened?

In grid view, add a handle (possibly "...") that allows a user to grab the space between tabs and adjust the size of the tab in view so you could for example have 80/40 or 40/80 tab size.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.32

### Severity impact

Low

### What platform are you seeing the problem on?

macOS - Intel

**Comment by Shyboy-101** [comment]
### +1, from windows,a-35
