### ISSUE TITLE
With browser.tabs.closeWindowWithLastTab=false, pressing close tab shortcut multiple times quickly (Command+w) will create a new tab

### ISSUE THREAD

**Issue by aaronmurniadi** [zen-browser/desktop#1036]
### What happened?

Note:
- This happens only when there's only one tab open.

I'm using Zen Browser 1.0.0-a.32 (64-bit), MacOS, AArch64. 

Fresh install, no imports from other browsers, clean profile.

Recording:
- [Screen Recording 2024-08-29 at 17.21.28.webm](https://github.com/user-attachments/assets/1c7944f8-d33a-4698-8d04-e98eb4b63871)

This bug is not reproducible on Mozilla Firefox:
- [Screen Recording 2024-08-29 at 17.28.27.webm](https://github.com/user-attachments/assets/ffd14cc6-9424-4bb7-983d-fe8dc2f0d7cb)

(When the interface flickers, that's when I pressed Command+w)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.32

### Severity impact

Low

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by RayZ3R0** [comment]
Does this still happen on latest version? (a.14 as of this comment)

**Comment by Sutaai** [comment]
I confirm this is fixed on both Linux and Windows.
I did, however, notice it happen once on Linux, but I think it can be ignored, it happened once in a million attempts.
