### ISSUE TITLE
publishing on homebrew failed

### ISSUE THREAD

**Issue by onexbash** [zen-browser/desktop#1038]
### What happened?

Hi guys, 
I just created a new homebrew cask for the zen browser, but seems the merge checks are failing because it's not signed by Apple yet. 
Just wanted to let you know. 
My PR: https://github.com/Homebrew/homebrew-cask/pull/183732

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.32

### Severity impact

Low

### What platform are you seeing the problem on?

macOS - aarch64, macOS - Intel

**Comment by mauro-balades** [comment]
Please provide a valid version

**Comment by onexbash** [comment]
updated version.

**Comment by HarryHeres** [comment]
@mauro-balades @onexbash What about hosting a tap (basically a repo)? As far as I can tell, taps do not require any checks, as opposed to the casks themselves? If my idea is right, this could also mitigate the need to sign the application with a valid Apple Developer certificate, at least for now.

**Comment by HarryHeres** [comment]
@mauro-balades Can be closed for now as https://github.com/zen-browser/desktop/pull/1161 was merged.

**Comment by mauro-balades** [comment]
True, thanks!
