### ISSUE TITLE
Certain Firefox themes make Zens background transparent.

### ISSUE THREAD

**Issue by SomeDudeBrosky** [zen-browser/desktop#104]
### What happened?

The beige theme I use on Firefox (it enables on zen as they sync themes) causes zen to become transparent.
(honestly with a bit of blur this would be awesome, but sadly it's a bug)

Flatpak with Wayland compositor.

![Screenshot from 2024-07-29 15-29-58](https://github.com/user-attachments/assets/a4aa9fb0-aebf-4642-bc03-a2bee5788c71)

![Screenshot from 2024-07-29 15-28-53](https://github.com/user-attachments/assets/aad1b965-faab-4a9f-9e27-3b61103f6fbf)

![Screenshot from 2024-07-29 15-28-39](https://github.com/user-attachments/assets/1a4de2ee-c5c5-493a-aebc-afb57917b91f)

[Screencast from 2024-07-29 15-29-03.webm](https://github.com/user-attachments/assets/cbeddb61-9062-49b7-b480-f34d4216ab8b)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.7

### Severity impact

Medium

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
This will be fixed for the next release 👍🏽

**Comment by Skyyblaze** [comment]
@mauro-balades Could you actually make this bug a temporary option for all OSs until transparency gets properly implemented? With MicaForEveryone and BlurBehind it would actually be possible to make Zen "glass" on Windows.

**Comment by mauro-balades** [comment]
![image](https://github.com/user-attachments/assets/144ebe91-c712-4806-9c2b-0da5d4519576)

I could make builtin transparent themes

**Comment by SolsticeSpectrum** [comment]
I would actually love to see these elements have a frosted glass look on MacOS just like Safari
