### ISSUE TITLE
DRM Content isn't working in the latest update

### ISSUE THREAD

**Issue by ThePixelDude111** [zen-browser/desktop#1042]
### What happened?

Basically what the title says, even though drm is enabled in settings and widevine is always enabled. I tried turning it off and on but it didn't work too, and instead I get this error : "60072069. Open in updated Google Chrome"

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.32

### Severity impact

High

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
error code : (60072069. Open in updated Google Chrome)
```

**Comment by ThePixelDude111** [comment]
> [DRM doesnt work on ](https://docs.zen-browser.app/faq#why-cant-zen-browser-play-drm-protected-content) please check it out 👍🏽

Oh I see, didn't know that for sure, thanks for the help tho.

**Comment by ThePixelDude111** [comment]
I really hope that one day we can have drm content in zen, and maybe with enough support and donations we can have that.

**Comment by mauro-balades** [comment]
It's not only money, google decides who can have it and who doesn't...
