### ISSUE TITLE
Missing hotkey options

### ISSUE THREAD

**Issue by tgienger** [zen-browser/desktop#1046]
### What happened?

In the hotkey settings I have disabled the default Zen hotkeys to configure my own. In doing this I have noticed a couple options seem to be missing.

1. Reopen closed tab
2. Focus the address bar

Currently I have to set a 'search' hotkey to focus the address bar, but it's inefficient because it adds the search parameter and wont allow going directly to an address without first backspacing to a blank address bar.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.32

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by trevortylerlee** [comment]
Also dealing with this issue on Mac — CMD + Shift + t doesn't open the last closed tabs. A workaround for now is right clicking any tab and selecting "Reopen Closed Tab".

**Comment by slacksystem** [comment]
The reopen closed tag keybind missing is one of the few frustrations I have with the browser. It feels like such an essential keybind to most browser. Ctrl+Shift+T (or CMD+Shift+T) is just something folks expect to open the last closed tab at this point. It seems to me that if there can be "Reopen last session/window" keybinds, the more critical reopen tab ought to be there as well.
