### ISSUE TITLE
Mini Player On YouTube Not Working On Linux (Fedora 40)

### ISSUE THREAD

**Issue by IshanAsati** [zen-browser/desktop#1047]
### What happened?

the mini player is bugged so that i cant leave the webpage else it will disappear

https://github.com/user-attachments/assets/6d49a4ea-9559-4a42-a23d-e507dbced610

it is the same if i minimize the browser
### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.32

### Severity impact

Medium

### What platform are you seeing the problem on?

Linux

**Comment by Myouboku** [comment]
I'm trying to see if I can reproduce the issue, can you give more info on your installation ?
Is this from the .tar, Flatpak or AppImage ?

**Comment by IshanAsati** [comment]
I used Flatpak for installation

**Comment by Myouboku** [comment]
I tried to reproduce the bug but can't find anything wrong, the PiP window is still here, it doesn't stay on top of everything by default (Firefox doesn't either) but is still visible anyway

Envoyé depuis Proton Mail pour Android

-------- Message d'origine --------

**Comment by IshanAsati** [comment]
Ok, Thanks For your help
