### ISSUE TITLE
Branding is not applied everywhere

### ISSUE THREAD

**Issue by i-Moony** [zen-browser/desktop#1048]
### What happened?

I know that it is kinda not important right now, but I think that this issue should be raised not to miss it in the future.
The thing is that in many places Zen is still called Firefox and team behind it is called Mozilla. It's not very important.

BUT

The thing that is kinda important that links like Privacy Policy, End User Rights and Licensing Information lead to Mozilla's versions of these pages. It can cause legal trouble in the future (reallistically that's never gonna to happen but it's better to just swap them just in case).

You can check this by: Open Menu -> Help -> About Zen.
![image](https://github.com/user-attachments/assets/e0223bc7-0bab-412d-ab57-b062d9d1fb5d)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.32

### Severity impact

Low

### What platform are you seeing the problem on?

Linux, macOS - aarch64, macOS - Intel, Windows

**Comment by KjalaNIX** [comment]
about:debugging and about:privatebrowsing have Firefox Nightly logos instead of Zen's and running appwiz.cpl on Windows shows that Zen is detected as published by Mozilla and not Zen HQ. I can second this one.
![Uploading Screenshot 2024-08-29 at 21-59-00 Debugging - Runtime _ this-firefox.png…]()

**Comment by fgclue** [comment]
![image](https://github.com/user-attachments/assets/4d6ca9eb-2ca7-4505-a9cd-df3c5ecf4004)

**Comment by KjalaNIX** [comment]
> ![image](https://private-user-images.githubusercontent.com/87581499/362876979-4d6ca9eb-2ca7-4505-a9cd-df3c5ecf4004.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5Njc2MTksIm5iZiI6MTcyNDk2NzMxOSwicGF0aCI6Ii84NzU4MTQ5OS8zNjI4NzY5NzktNGQ2Y2E5ZWItMmNhNy00NTA1LWE5Y2QtZGYzYzVlY2Y0MDA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDIxMzUxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4ZjJlNjMwMTJmZjZiYzc3ZDc1NTlhNjhiNjJhNmZhNGI3YTU1N2JlMDkzMTFlYzcyMGYxYmRkOWE4NTk3ZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AJX6HibhfwBU2rdNlGpSU8aj8CN4HZtns_ITTElmo9M)

Totally!!!

**Comment by dmac-au** [comment]
I'm using the portable Linux version (flatpak is crashing with my NVIDIA GPU) and noticed today when the nightly is out of date, the link to download it goes to Mozilla Nightly.

At least it did for a20. I've now updated to a32

**Comment by mauro-balades** [comment]
Does this still happen?

**Comment by dmac-au** [comment]
> Does this still happen?

No it doesn't, it took me to the zen website the day after I upgraded to the newer version.
