### ISSUE TITLE
Slow Loading Speed On Sites

### ISSUE THREAD

**Issue by IshanAsati** [zen-browser/desktop#1049]
### What happened?

Whenever i search something on google or open a site it takes a decent amount of time, this isn't the case with firefox, i have also updated my drivers and os

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.32

### Severity impact

Medium

### What platform are you seeing the problem on?

Linux

**Comment by n7itro** [comment]
Is this still the case on the latest version?

**Comment by sudiplun** [comment]
I've facing same problem. 
version: **1.0.1.a.2**
