### ISSUE TITLE
New icon is kind of awkwardly small compared to other icons in taskbar, at least on Windows 11

### ISSUE THREAD

**Issue by mayemu** [zen-browser/desktop#105]
### What happened?

Not sure if this should be labeled as feature or bug because its not really either so I just put it as a low severity bug lol. Screenshots below

![oDvA8qmO8K](https://github.com/user-attachments/assets/9f28708c-dd9d-421f-8e17-760fb8b6be76)
![WvKAZftc6s](https://github.com/user-attachments/assets/7c20b19d-08ff-433b-8d34-6208816d3764)
Compared to other blob/square icons like Adobe and Element: 
![zen_uqmEIxIDmL](https://github.com/user-attachments/assets/d4a6d104-6ad1-4879-ad1c-cc27054aa84f)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Alpha build - 1.0.0-a.8 (2024-07-29)

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by NOCanoa** [comment]
daaam  now i cant unsee it xD

**Comment by NOCanoa** [comment]
Just checked the comit all the logos have alot off padding around it so technically  its the same pixel size but in practice it way smaller
![image](https://github.com/user-attachments/assets/3f48c087-57b9-47ef-b0ff-0a8b7eae9e79)

**Comment by mayemu** [comment]
I also would like to add that the blue shadow layer under the Z doesnt pick up well and creates weird pixel elements when viewed in the taskbar or start menu. You can compare that to the other icons in the screenshots above. I believe this may be due to the padding making the icon extra small, but also that thin small details like this seem to be mostly absent in modern icons for this reason as the other icons in the screenshot dont have anything like that. The closest would be the dashed lines around signal's icon but theyre still thicker than the Z's shadow. Just some food for thought! Could either make it bigger, further apart from the Z, or remove it to fix the pixel artifacts added. The dashed lines in the grid also basically don't pick up at all, theyre essentially invisible when in a taskbar/start menu.

**Comment by mauro-balades** [comment]
It'll be fixed for the next release 👍🏽
