### ISSUE TITLE
Zen does not set the 'About Zen Browser' window to floating

### ISSUE THREAD

**Issue by fgclue** [zen-browser/desktop#1053]
### What happened?

**Expected Behavior:**
The about window should be floating.

**Actual behavior:**
Window is not floating.

![Screencastfrom2024-08-2917-16-03-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/12ab5ec6-6c81-48b4-b7e8-a6cbc8b16d28)

P.S. I do not believe this is a Flatpak issue since OBS and some other programs do not have this problem.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a32 (64-bit), Flatpak

### Severity impact

Low

### What platform are you seeing the problem on?

Linux

**Comment by cprin21** [comment]
Floating on which desktop environment? This appears to be GNOME by the top panel. If you are using a GNOME extension for window tiling, consider checking out the window/client ID for that specific window and have it forced to float in your tiling extension.

**Comment by fgclue** [comment]
I'm using forge. The weird thing is that this works with firefox and also OBS, they can both float windows, I have OBS installed as a flatpak like zen.

**Comment by drod3763** [comment]
Forge comes with some exception rules by default. It probably has the about window set for Firefox out of the box, you'll need to set it manually for Zen.

**Comment by fgclue** [comment]
> Forge comes with some exception rules by default. It probably has the about window set for Firefox out of the box, you'll need to set it manually for Zen.

Thanks. I'll close this now.
