### ISSUE TITLE
Customize toolbar menu has confusing appearance

### ISSUE THREAD

**Issue by i-Moony** [zen-browser/desktop#1054]
### What happened?

![image](https://github.com/user-attachments/assets/d1aba8e0-0537-43f7-bc60-d5e5a58a4194)
In this image Overflow menu sign points to "blank" space right below the address bar. Hovewer I'm unable to drag any item here.

Here either Overflow menu is broken or the "blank" space is redundant.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.32

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by i-Moony** [comment]
Ok, I found out that the overflow menu IS the sign. But the space if redundant I think.
![image](https://github.com/user-attachments/assets/69492bde-0b15-4fff-8575-064829dda953)

**Comment by Shyboy-101** [comment]
![图片](https://github.com/user-attachments/assets/103246b3-62da-46f2-afa5-73b462067b9e)
It should've be like this.right?

**Comment by i-Moony** [comment]
Probably. Or just the background color as the rest of the browser. The current state is slightly strange and confusing.
