### ISSUE TITLE
flatpak not found trying to install

### ISSUE THREAD

**Issue by brekker23** [zen-browser/desktop#106]
### What happened?

Trying to install the flatpak on linux and it returns

error: Nothing matches io.github.zen_browser.zen in remote flathub

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

N/A

### Severity impact

Medium

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
https://github.com/flathub/flathub/pull/5449 it's still in progress

**Comment by brekker23** [comment]
got it thanks

**Comment by mauro-balades** [comment]
https://flathub.org/apps/io.github.zen_browser.zen it now works!
