### ISSUE TITLE
Close Split View shortcut causes window to glitch when not in split view

### ISSUE THREAD

**Issue by Aniket-Bhat** [zen-browser/desktop#1060]
### What happened?

Close Split View shortcut causes window to glitch when not in split/grid view

https://github.com/user-attachments/assets/c5446975-cf82-46c1-9f0b-904df416bbf6

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.32 (64-bit)

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
This is fixed for the next release 👍🏽
