### ISSUE TITLE
pin tab lost

### ISSUE THREAD

**Issue by youngxhui** [zen-browser/desktop#1062]
### What happened?

When I pin a tab, close the browser and reopen it, the pinned tab will be lost.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.32

### Severity impact

Medium

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by Ashley-Buckingham** [comment]
If it helps... I do find that if i quit using the right click -> quit option on the mac app dock then it loses all pinned tabs, if i quit using cmd+q then they are there when the app is reopened.

**Comment by kylescudder** [comment]
On the Arch [AUR](https://aur.archlinux.org/packages/zen-browser-bin) version they are lost regardless of how you close it, either Control + q or using i3 Super + Alt + q, both will not retain pinned tabs.

**Comment by Muko-Tabi** [comment]
It does not lose in my case, but it keeps moving the last pinned tab I was on before closing to the top

**Comment by adityapandeydev** [comment]
I also face the same issue as muko-tabi, and I think I also found what is happening, the tabs are getting pinned to the window instead of the profile, so once that window is closed and a new window is opened the pinned tabs are gone. Also on windows the pinned tabs will stay even if you close and reopen the app (if you have enabled the retain previous tabs feature in firefox settings) as long as you don't open a new window, after that firefox keeps track of that window and its tab to reopen upon startup and hence the pinned tabs don't come back. I am on version a-37.

**Comment by marcelovbcfilho** [comment]
I'm having a similar issue, but my pinned tabs keep changing from one workspace to another... I really prefer the old behavior were pinned tabs were global across workspaces.

**Comment by nsvrana** [comment]
On Zen 1.0.1-a5 on Windows. Similar problem here - if I open a new Window, the pins are gone.

**Comment by ViridityCorn** [comment]
I have also just experienced this on 1.1-a.7.
I think @adityapandeydev is spot on. My issue also arose by opening a new Zen window, which I closed last.
I hope this will be fixed soon, as this honestly makes me a bit afraid to spend to much time setting up Zen, when I know, it can all be lost so easily...

**Comment by jackgraddon** [comment]
Just thought I would pop in and say I am having this issue as well, on the latest 1.0.1-a.8 (aarch64). Using macOS Sequoia. It doesn't happen all the time, but I can't find a pattern for when it does or doesn't. It more often does reset my pinned tabs, but they do sometimes stick around.

**Comment by yoghurtlee-thu** [comment]
I've been bothered for quite a while ... #1350

**Comment by nsvrana** [comment]
Right now it is appears that pinned tabs are associated with individual windows. I think the behavior people are looking for is more like what we had in Arc, which is that pinned tabs are more like toolbar favorites where they are permanent across windows, and, even further, they're actually the same instance no matter how many windows you open. 

If you select TabA in Window2 and it was already open in Window1, TabA in Window1 becomes inactive, but remains open. If you make changes then select the tab in Windows1, those changes would be reflected there.

This is a core part of the pinned tab concept as implemented elsewhere which is missing from Zen.

**Comment by mr-cheffy** [comment]
I dont have a mac so I can't really see how pinned tabs work in arc, sorry...

Tabs (pinned or not) are window specific, therefor, if you close one window, session restore will just remember the last closed one.

If you could send a video or tutorial that shows how pinned tabs work on arc, I could work something out

**Comment by adityapandeydev** [comment]
Arc is available on windows as well. Also bookmarks aren't window specific. Arcs pinned tabs work like bookmarks.

**Comment by hb-robo** [comment]
@adityapandeydev The Arc Windows version is so behind the others that it wasn't even exposed to that recent Firebase vulnerability - the exposed functionality hadn't even been implemented yet. Arguably it's not a good representation of the browser today, anyway.

Also chiming in to show support for pinning tabs to spaces, specifically, and not windows. Alternatively, let me put the bookmark bar in the sidebar or something. I just need the top left of the screen to be reliable quick-access to properly daily drive Zen.

**Comment by adityapandeydev** [comment]
In the latest Version 1.0.2-b.1. The issue seems to be resolved.
