### ISSUE TITLE
Context menu translation languages to expand in future?

### ISSUE THREAD

**Issue by DavidGreen63** [zen-browser/desktop#1064]
### What happened?

I noticed that there was a context menu option for translation, and I thought this was a great idea.
![Screenshot 2024-08-30 132150](https://github.com/user-attachments/assets/d8d47514-45dc-4b1b-ab17-86eddf4b0644)
… at least until I discovered that the source language was not supported.
I am hoping that there will be plans to expand the scope of the languages that are available.
In the screen-shot above, I was trying to get Japanese translated into English, but it was not on the list, nor could it be added (yet?).

I did notice that the language list appears to be limited to languages that use an extended Latin alphabet, so I am wondering if this is a limitation preventing the use of pictographic and non-Latin script characters.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.32 (64-bit)

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by Anthonyy232** [comment]
Japanese doesn't seem to be supported by Firefox translate, which is kind of weird considering how popular the language is (especially in the West nowadays). They also don't support Chinese..

**Comment by DavidGreen63** [comment]
Thanks @Anthonyy232 for pointing that out. I didn't even realise that the translate function was part of Firefox. I thought it was a plug-in/extension function.
I looked at https://www.mozilla.org/en-US/firefox/features/translate/
which suggests that "And more languages are in development!", so maybe that will change when Firefox closes.

Interestingly, I am currently using Floorp, another Firefox fork, by the Japanese company Ablaze, and it has not added Japanese, so I guess it is Google Translate that will maintain its rule for the time being.

Ablaze recommended https://addons.mozilla.org/en-US/firefox/addon/traduzir-paginas-web/

**Comment by Anthonyy232** [comment]
Yes, it would be great if it was natively supported, especially since Firefox doesn't seem to be making any grounds on that front. For now -- TPW it is

**Comment by DavidGreen63** [comment]
I liked how the tiny Google Translate icon hovers near any selected text. It is a very handy implementation.

**Comment by DavidGreen63** [comment]
Indeed, the plug-in suggested by Ablaze is working very well, and have been using it since.
