### ISSUE TITLE
Pinned tab by workspace

### ISSUE THREAD

**Issue by jandroav** [zen-browser/desktop#1067]
### What happened?

I am expecting different pinned tabs by each workspace.

<img width="174" alt="image" src="https://github.com/user-attachments/assets/6080de55-b696-4b0b-bf12-732d2d7f1f40">

<img width="169" alt="image" src="https://github.com/user-attachments/assets/a82e33c3-f865-49d1-8d6c-f03ded20c610">

I think having a different set of pinned tabs per workspace makes totally sense. It makes workspaces session to be more different between each other.

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.32 

### Severity impact

Low

### What platform are you seeing the problem on?

macOS - aarch64

### Relevant log output

```shell
-
```

**Comment by Swissbite** [comment]
Had the same thought about the pinned tabs. I'm coming from Arc Browser, and this feature is great. I often have to switch context, and having different pinned tabs by context is a must.

**Comment by theuser18** [comment]
This would be a great addition!

**Comment by shayan15sa** [comment]
I came across this today, and i have used arc browser before, I thought it was a bug or something.
I'll be happy to see like a toggle in the settings for both features.

keep up the good work zen team.

**Comment by mauro-balades** [comment]
Pinned tabs are specifically done to stay independently of the workspace, sorry about that... it's that firefox's implementation of pinned tabs doesnt allow them to be hidden....

**Comment by shayan15sa** [comment]
oh ok. I'll try and see if i can do anything about ir.
thanks for responding
have a great one.
