### ISSUE TITLE
Title side bar icon and text no spacing

### ISSUE THREAD

**Issue by Jackiu1997** [zen-browser/desktop#1068]
### What happened?

Device
Windows 11

Scenario
In the left title side bar, there is no padding between icon and text. It is very wired, pls help to fix it.

![图片](https://github.com/user-attachments/assets/cc1465d7-fbb7-45ac-b9c5-64e605295d0c)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0

### Severity impact

Medium

### What platform are you seeing the problem on?

Windows

**Comment by Jackiu1997** [comment]
found way to reproduce, install super sleek ui in zen theme, then it will cause the issue.

**Comment by Jackiu1997** [comment]
> found way to reproduce, install super sleek ui in zen theme, then it will cause the issue.

Reinstalled serval times, actually it will happen very accidentlly. Maybe the root cause is migrate data from new edge.

**Comment by NOCanoa** [comment]
Should be fixed on latest version, u can reopen the issue if it persists.
