### ISSUE TITLE
Zen won't start - Couldn't load XPCOM

### ISSUE THREAD

**Issue by burnout426** [zen-browser/desktop#107]
### What happened?

Windows 11 23H2 64-bit + Zen 1.0.0-a.8 installed with "zen.installer.exe" from <https://github.com/zen-browser/desktop/releases/tag/1.0.0-a.8>. Also tried zen.win64.zip.

When I try to start Zen, I get the attached error dialog titled "Firefox" that says "Couldn't load XPCOM."

![zenxpcom](https://github.com/user-attachments/assets/f04f7ad5-17d1-45d2-90f0-ac5b15581590)

CPU: Intel Core i5 2520m: <https://www.intel.com/content/www/us/en/products/sku/52229/intel-core-i52520m-processor-3m-cache-up-to-3-20-ghz/specifications.html>. See "Extensions and technologies" at <https://www.cpu-world.com/CPUs/Core_i5/Intel-Core%20i5%20Mobile%20I5-2520M%20FF8062700840017%20(BX80627I52520M).html> for list of supported features ( SSE and AVX version support). 8GB RAM. Intel HD3000 GPU on CPU.

Firefox 128.0.3 (64-bit) loads fine.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.8

### Severity impact

Critical

### What platform are you seeing the problem on?

Windows

**Comment by A-Lamia** [comment]
Have the same issue.

**Comment by detyso** [comment]
I have the same error xpcom error

**Comment by nero-0** [comment]
It doesn't open here either

**Comment by mauro-balades** [comment]
Just to be clear, did it open on the previous versions?

**Comment by detyso** [comment]
Yea it open when I installed the first release of and  there was no error

**Comment by nero-0** [comment]
For me, no version after 1.0.0-a.4 opens

**Comment by burnout426** [comment]
Same here. a.4 is the last build that works for me.

a.6 and a.7 give me "The application was unable to start correctly (0xc0000142)".

a.8 gives me the XPCOM error.

In the changelog for a.6, it mentions "Updated CPU requirements for x86_64-v3", which I suspect is the culprit. But, I couldn't find what the requirements were before or what they are now. That's why I provided my CPU specs though.

**Comment by mauro-balades** [comment]
We are trying to solve it for 1.0.0-a.9

**Comment by mauro-balades** [comment]
Zen doesn't get that far, i've checked it, and we are trying to fix it by lowering CPU requirements but that would make it slightly slower because we are doing less precise optimizations

**Comment by burnout426** [comment]
>  we are trying to fix it by lowering CPU requirements but that would make it slightly slower because we are doing less precise optimizations

I was just testing Zen to see how it was progressing. I can't speak for others here, but if you want to require a newer processor than I have, I'm personally okay with it. I would just suggest that <https://get-zen.vercel.app/download> lists the system requirements (including the CPU requirements).

An alternative would be to provide regular builds and then optimized builds. More work for you though.

**Comment by burnout426** [comment]
I can confirm that that the generic, non-optimized build of 1.0.0-a.11 (64-bit) starts and runs fine with my CPU now.

**Comment by abh006** [comment]
I am trying to setup the project for the first time. I did `npm run init` and `npm run build` which completed successfully. But when I try to run `npm start` it throws the "Couldn't load XPCOM" error. 

I am running this on an M2 Air. Any idea what I could be doing wrong ?
