### ISSUE TITLE
src/gfx/wr/webrender/src/picture-rs.patch causes build failure on NixOS

### ISSUE THREAD

**Issue by Zh40Le1ZOOB** [zen-browser/desktop#1070]
### What happened?

I'm trying to build Zen Browser on NixOS, [this](https://github.com/Zh40Le1ZOOB/nixpkgs/tree/dc4668099719d5ff616dbd3057a42adfb4a60045/pkgs/by-name/ze/zen-browser) is my drv.

But I keep getting build failure:
```
error: failed to run custom build command for `webrender v0.62.0 (/build/source/engine/gfx/wr/webrender)`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.
Caused by:
  process didn't exit successfully: `/build/source/engine/obj-x86_64-pc-linux-gnu/instrumented/release/build/webrender-b970e3a2973cd0b8/build-script-build` (signal: 4, SIGILL: illegal instruction)
```

Then I discovered [this](https://github.com/zen-browser/desktop/blob/1.0.0-a.32/src/gfx/wr/webrender/src/picture-rs.patch) modification is the reason of build failure. If I remove it, build works fine.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.32

### Severity impact

Medium

### What platform are you seeing the problem on?

Linux

**Comment by fndov** [comment]
+1

**Comment by CactiChameleon9** [comment]
Out of interest @Zh40Le1ZOOB, without this patch does https://github.com/zen-browser/desktop/issues/34 re-occur?

**Comment by mauro-balades** [comment]
Is that the full error output?

**Comment by Zh40Le1ZOOB** [comment]
I'm so sorry that I was late to reply this. But seems problem disappears onec I bumped to 1.0.0-a.34. So I'll close this.
