### ISSUE TITLE
Prime Video Unavailable

### ISSUE THREAD

**Issue by AslamHabeeb** [zen-browser/desktop#1071]
### What happened?

I am unable to Stream Amazon Prime Video on Zen Browser
![Screenshot (209)](https://github.com/user-attachments/assets/e0253327-2477-4a14-a8dc-489c1218c5e9)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.32 (64-bit)

### Severity impact

High

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
Prime uses DRM content, please checkout https://docs.zen-browser.app/faq#why-cant-zen-browser-play-drm-protected-content
