### ISSUE TITLE
Embedded video is jerky

### ISSUE THREAD

**Issue by DutchPete** [zen-browser/desktop#1079]
### What happened?

The picture is jerky

https://github.com/user-attachments/assets/3e96e8ac-6df7-43bd-a484-39b01a6307a6

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.32 (64-bit)

### Severity impact

High

### What platform are you seeing the problem on?

Linux

**Comment by lucaspereirasouzat** [comment]
for me its working normaly

**Comment by mauro-balades** [comment]
This is fixed for the next release, i've enabled GPU by default. you could try https://github.com/zen-browser/desktop/issues/1130

**Comment by DutchPete** [comment]
I changed the 2 settings in `about:config` as per TomTruyen's suggestion in #1130 and that you implemented. I closed Zen, and relaunched it. The jerkiness is still there.

If you want you can check it on that [webpage](https://simplicius76.substack.com/p/last-of-the-wunderwaffen-f-16-blasted), scroll down about 80% on that page.
