### ISSUE TITLE
Web Panel URL Input Incorrectly Prepends "https://" to "file///" URLs

### ISSUE THREAD

**Issue by Hashnoob** [zen-browser/desktop#1081]
### What happened?

When attempting to add a local HTML file to a web panel using a file URL, Zen automatically prepends "https://" to the URL, preventing the file from loading properly.

file:///C:/zen/app.html

becomes

https://file///C:/zen/app.html

The file URL should be accepted as-is, allowing the local HTML file to load in the web panel.

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.32

### Severity impact

Medium

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
Fixed for the next release, thanks!
