### ISSUE TITLE
Clicking Zen Browser Support takes you to Mozilla website not the Zen Browser Website

### ISSUE THREAD

**Issue by sirinath** [zen-browser/desktop#1082]
### What happened?

Clicking

![image](https://github.com/user-attachments/assets/ed23362c-72bd-4ae5-8dc8-8d05ae93483a)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a32

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by Neintonine** [comment]
is there something like Zen Browser Support? You could link to the issues page here on GitHub, I guess.

**Comment by sirinath** [comment]
Better would be discussion page.

**Comment by PowerzinBR** [comment]
since zen is just an 'skin' for firefox, it makes sense, zen is based on firefox

**Comment by nocanoa** [comment]
continue https://github.com/zen-browser/desktop/issues/507
