### ISSUE TITLE
Cursore bug, on all pages

### ISSUE THREAD

**Issue by xr0m3oz** [zen-browser/desktop#1085]
### What happened?

If you click on any page with the cursor near the text, then in the position of clicking, it will remain and blink as if it were an input field. Although this behavior is on any site and in any area of ​​the text when clicked.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0 a32

### Severity impact

Low

### What platform are you seeing the problem on?

macOS - Intel

**Comment by mauro-balades** [comment]
Could you send a video to reproduce this?

**Comment by xr0m3oz** [comment]
https://photos.app.goo.gl/3TEj3DDjqJHwNGYh7

пн, 2 сент. 2024 г., 12:31 mauro 🤙 ***@***.***>:

**Comment by xr0m3oz** [comment]
[Запись экрана 2024-09-05 в 13.20.41.mov.zip](https://github.com/user-attachments/files/16887821/2024-09-05.13.20.41.mov.zip)

Click on text or near text or in youtube if full screen video, in left down conner cursor blinkin
@mauro-balades

**Comment by xr0m3oz** [comment]
@HarryHeres @mauro-balades @Swissbite @damianfijorek still actual 1.0.1-a.3 

Can you reproduce this bug on your side?
In original firefox good no this bug.

**Comment by Swissbite** [comment]
Version 1.0.1-a.3 (64-bit) - Linux

Cannot reproduce. There is no cursor showing somewhere near a text after clicking.

I'll try tomorrow on a Windows System.

**Comment by Swissbite** [comment]
Version 1.0.1-a.4 (64-bit) - Windows 11

Cannot reproduce. There is no cursor showing somewhere near a text after clicking.

**Comment by xr0m3oz** [comment]
what to do in such a situation? I don't use any third-party add-ons,
everything is stock.

вт, 24 сент. 2024 г., 08:58 David Daester ***@***.***>:

**Comment by xr0m3oz** [comment]
MacBook intel

вт, 24 сент. 2024 г., 09:11 Роман ***@***.***>:

**Comment by xr0m3oz** [comment]
1.0.1-a.12 This bug still exists.

https://photos.app.goo.gl/uLtBTBULsUJ2q24X8

Click near logo (if cursore not clicable)

@Swissbite

**Comment by salamijason** [comment]
I believe this is caret browsing? Try clicking F7 to turn it off.

**Comment by xr0m3oz** [comment]
> I believe this is caret browsing? Try clicking F7 to turn it off.

I did not even know what it is and that it can be disabled. Yes, it worked. It somehow turned on after some kind of update. And until that moment I thought it was a bug.

Thank you.

**Comment by xr0m3oz** [comment]
> Try clicking F7 to turn it off.

Yes, it worked.
