### ISSUE TITLE
Unable to pin the web panel

### ISSUE THREAD

**Issue by arildin** [zen-browser/desktop#1087]
### What happened?

When I have the side web panel open, it's acting more like a split view than a pop out window. There is no option to pin the web panel and it isn't doesn't float above the rest of the window's content. I have tried on a fresh computer and installed the browser and got the same result

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.32

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by Vistaus** [comment]
> I figured out what I was doing wrong, keep being awesome.

Would you be so kind to share how you managed to pin it? Because I can't seem to pin it either.

Edit: oh wait, there seems to be a bug. The - (minus) icon pins the sidebar, while it should be a pin icon as far as I understand.

**Comment by arildin** [comment]
> > I figured out what I was doing wrong, keep being awesome.
> 
> Would you be so kind to share how you managed to pin it? Because I can't seem to pin it either.
> 
> Edit: oh wait, there seems to be a bug. The - (minus) icon pins the sidebar, while it should be a pin icon as far as I understand.

Yeah, I started clicking around and noticed that while it was the minus sign, after clicking it, it started showing correctly
