### ISSUE TITLE
Non Flatpak builds don't use the native KDE file picker.

### ISSUE THREAD

**Issue by WasmachenDennSachenSo** [zen-browser/desktop#1088]
### What happened?

Self compiled build and .zip file in releases, don't respect the native (KDE Plasma 6) file picker in "save as" dialogs. The GTK file picker is used instead. The Flatpak uses the KDE file picker.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a32

### Severity impact

Low

### What platform are you seeing the problem on?

Linux

**Comment by jhc1993-846** [comment]
I worked around this issue by setting a config as shown in this [Reddit Post](https://www.reddit.com/r/kde/comments/1af9286/comment/ko8r5ih/).

Unsure if this can be fully solved, since I also encountered this issue in Mozilla's own builds of Firefox. Firefox is a GTK application after all...

**Comment by WasmachenDennSachenSo** [comment]
Yes, this worked for me. Thanks for this tip! Would it be problematic to set this flag by default?
