### ISSUE TITLE
When a New Password is Entered than the Currently Saved Offer to Update Password

### ISSUE THREAD

**Issue by sirinath** [zen-browser/desktop#1089]
### What happened?

The imported password from a previous browser is outdated. When I entered the new password this is not updated. I have to goto passwords and then edit the stored password

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a32

### Severity impact

Critical

### What platform are you seeing the problem on?

Windows

**Comment by salamijason** [comment]
Heylo, looks like this issue was posted a while back. Are you still getting this on the lastest version? (a17 as of this comment)

**Comment by salamijason** [comment]
No response in 3 days. Will be closing this issue. Please reopen if you are still facing the issue.
