### ISSUE TITLE
Bookmarks cannot be imported from MS edge due to an incorrect file type. 

### ISSUE THREAD

**Issue by iamenews** [zen-browser/desktop#1091]
### What happened?

Microsoft Edge exports bookmarks in HTML, but zen only accepts it in JSON. This means that in the setup or when you click the bookmark ribbon, you can't export your bookmarks. 

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Latest

### Severity impact

High

### What platform are you seeing the problem on?

Windows

**Comment by 0xGingi** [comment]
Bookmarks -> Manage Bookmarks -> Import and Backup -> Import Bookmarks from HTML
