### ISSUE TITLE
Check Update Button in settings, show up to date but not

### ISSUE THREAD

**Issue by xr0m3oz** [zen-browser/desktop#1094]
### What happened?

When you click on the check update button, it shows that a new version is installed. Although I have version 1.0.0-a.32 and already have version 33. But it is not seen by the browser check.

Add copy button after version in setting 👍 

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.32

### Severity impact

Low

### What platform are you seeing the problem on?

macOS - Intel

**Comment by DareDevil2000** [comment]
I think it's compiling and not pushed yet.

**Comment by xr0m3oz** [comment]
@xr0m3oz Just wait?

**Comment by mauro-balades** [comment]
You need to wait until it's released
