### ISSUE TITLE
Not possible to paste URLs and files in the Discord channel

### ISSUE THREAD

**Issue by DutchPete** [zen-browser/desktop#1095]
### What happened?

When I try to paste a URL in the Zen discord channel and nothing happens. Others can/do paste URLs, so you would think it is a problem on my side.
But when I try to paste the same URL in the Zen discord channel using Brave browser it works.

Trying to upload a file results in "upload failed".

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.32 (64-bit)

### Severity impact

Medium

### What platform are you seeing the problem on?

Linux

**Comment by salamijason** [comment]
Heylo, looks like this issue was posted a while back. Are you still getting these issues on the latest version? (a17 as of this comment)

**Comment by DutchPete** [comment]
@salamijason Nope, this issue no longer occurs.
Many thanks for following up.
