### ISSUE TITLE
Malicious CDN’s

### ISSUE THREAD

**Issue by chrede88** [zen-browser/desktop#1096]
### What happened?

I installed the Zen browser on my work laptop in order to check it out.
My machine was immediately isolated on the network with the explanation that the Zen browser was “contacting a number of malicious CDN’s”! Can someone comment on this?

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by cprin21** [comment]
If this is an issue on Zen Browser's end that's probably a high severity issue.

**Comment by NOCanoa** [comment]
@chrede88 can u provide more info?

**Comment by chrede88** [comment]
I don't really have much more info. The SOC at my job only mentioned that the browser contacted a lot of CDN's using unsigned executables. See screendump they send me.
![image](https://github.com/user-attachments/assets/8ab6eb07-c320-42a6-84ad-219b690912a4)

**Comment by LaurenceJJones** [comment]
> I don't really have much more info. The SOC at my job only mentioned that the browser contacted a lot of CDN's using unsigned executables. See screendump they send me. ![image](https://private-user-images.githubusercontent.com/9137189/363408437-8ab6eb07-c320-42a6-84ad-219b690912a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyMDAxNDIsIm5iZiI6MTcyNTE5OTg0MiwicGF0aCI6Ii85MTM3MTg5LzM2MzQwODQzNy04YWI2ZWIwNy1jMzIwLTQyYTYtODRhZC0yMTliNjkwOTEyYTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDFUMTQxMDQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmQ5NGRjYWUxM2IwMjE4YmM2NTAyMjFhMDQ1YzQ3ZGE2ZTZmNjljMDlhZjkyOTYwNDk3NTE3ODU4YmI5YjgzOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.zJ17cphrjw4YNTolFlPYk1Gl4MZEv1AJBKuTZuKxYuo)

Most likely when going through the setup it will attempt to see if there are other browers installed to port across your saved information (bookmarks and stuff) which other browsers do including firefox which zen is based on. I guess it made it more seriously for your SOC since the binary is not signed and looks like you just ran some malware.

**Comment by LaurenceJJones** [comment]
> > > I don't really have much more info. The SOC at my job only mentioned that the browser contacted a lot of CDN's using unsigned executables. See screendump they send me. ![image](https://private-user-images.githubusercontent.com/9137189/363408437-8ab6eb07-c320-42a6-84ad-219b690912a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyMDAxNDIsIm5iZiI6MTcyNTE5OTg0MiwicGF0aCI6Ii85MTM3MTg5LzM2MzQwODQzNy04YWI2ZWIwNy1jMzIwLTQyYTYtODRhZC0yMTliNjkwOTEyYTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDFUMTQxMDQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmQ5NGRjYWUxM2IwMjE4YmM2NTAyMjFhMDQ1YzQ3ZGE2ZTZmNjljMDlhZjkyOTYwNDk3NTE3ODU4YmI5YjgzOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.zJ17cphrjw4YNTolFlPYk1Gl4MZEv1AJBKuTZuKxYuo)
> > 
> > Most likely when going through the setup it will attempt to see if there are other browers installed to port across your saved information (bookmarks and stuff) which other browsers do including firefox which zen is based on. I guess it made it more seriously for your SOC since the binary is not signed and looks like you just ran some malware.
> 
> Right! That's probably some of it. But why is it reaching out to multiple CDN's at startup? 

Well we would need to know which CDN were attempted to be access as the term "malicious" in the title is hard to prove when you have very little information. (If your SOC is logging all procress access calls then most likely they will have this information)

I checked through the codebase and can't see any "known" CDNs refference anywhere (I searched for names that I know since I work for a cyber security company)

Once we have more information (domain names if possible) then the developers will be able to provide additional information.

**Comment by mauro-balades** [comment]
> > > > I don't really have much more info. The SOC at my job only mentioned that the browser contacted a lot of CDN's using unsigned executables. See screendump they send me. ![image](https://private-user-images.githubusercontent.com/9137189/363408437-8ab6eb07-c320-42a6-84ad-219b690912a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyMDAxNDIsIm5iZiI6MTcyNTE5OTg0MiwicGF0aCI6Ii85MTM3MTg5LzM2MzQwODQzNy04YWI2ZWIwNy1jMzIwLTQyYTYtODRhZC0yMTliNjkwOTEyYTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDFUMTQxMDQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmQ5NGRjYWUxM2IwMjE4YmM2NTAyMjFhMDQ1YzQ3ZGE2ZTZmNjljMDlhZjkyOTYwNDk3NTE3ODU4YmI5YjgzOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.zJ17cphrjw4YNTolFlPYk1Gl4MZEv1AJBKuTZuKxYuo)
> > > 
> > > 
> > > Most likely when going through the setup it will attempt to see if there are other browers installed to port across your saved information (bookmarks and stuff) which other browsers do including firefox which zen is based on. I guess it made it more seriously for your SOC since the binary is not signed and looks like you just ran some malware.
> > 
> > 
> > Right! That's probably some of it. But why is it reaching out to multiple CDN's at startup?
> 
> Well we would need to know which CDN were attempted to be access as the term "malicious" in the title is hard to prove when you have very little information. (If your SOC is logging all procress access calls then most likely they will have this information)
> 
> I checked through the codebase and can't see any "known" CDNs refference anywhere (I searched for names that I know since I work for a cyber security company but it's not a comprehensive list)
> 
> Once we have more information (domain names if possible) then the developers will be able to provide additional information.

I did not change any DNS settings as far as I know... Could it be possible because the app isn't signed?

**Comment by chrede88** [comment]
> > > > I don't really have much more info. The SOC at my job only mentioned that the browser contacted a lot of CDN's using unsigned executables. See screendump they send me. ![image](https://private-user-images.githubusercontent.com/9137189/363408437-8ab6eb07-c320-42a6-84ad-219b690912a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyMDAxNDIsIm5iZiI6MTcyNTE5OTg0MiwicGF0aCI6Ii85MTM3MTg5LzM2MzQwODQzNy04YWI2ZWIwNy1jMzIwLTQyYTYtODRhZC0yMTliNjkwOTEyYTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDFUMTQxMDQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmQ5NGRjYWUxM2IwMjE4YmM2NTAyMjFhMDQ1YzQ3ZGE2ZTZmNjljMDlhZjkyOTYwNDk3NTE3ODU4YmI5YjgzOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.zJ17cphrjw4YNTolFlPYk1Gl4MZEv1AJBKuTZuKxYuo)
> > > 
> > > 
> > > Most likely when going through the setup it will attempt to see if there are other browers installed to port across your saved information (bookmarks and stuff) which other browsers do including firefox which zen is based on. I guess it made it more seriously for your SOC since the binary is not signed and looks like you just ran some malware.
> > 
> > 
> > Right! That's probably some of it. But why is it reaching out to multiple CDN's at startup?
> 
> Well we would need to know which CDN were attempted to be access as the term "malicious" in the title is hard to prove when you have very little information. (If your SOC is logging all procress access calls then most likely they will have this information)
> 
> I checked through the codebase and can't see any "known" CDNs refference anywhere (I searched for names that I know since I work for a cyber security company but it's not a comprehensive list)
> 
> Once we have more information (domain names if possible) then the developers will be able to provide additional information.

Yes, I get that it's hard to say anything concrete with the very limited info I've provided. If I can get some more info, I'll relay it here.

**Comment by chrede88** [comment]
> > > > > I don't really have much more info. The SOC at my job only mentioned that the browser contacted a lot of CDN's using unsigned executables. See screendump they send me. ![image](https://private-user-images.githubusercontent.com/9137189/363408437-8ab6eb07-c320-42a6-84ad-219b690912a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyMDAxNDIsIm5iZiI6MTcyNTE5OTg0MiwicGF0aCI6Ii85MTM3MTg5LzM2MzQwODQzNy04YWI2ZWIwNy1jMzIwLTQyYTYtODRhZC0yMTliNjkwOTEyYTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDFUMTQxMDQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmQ5NGRjYWUxM2IwMjE4YmM2NTAyMjFhMDQ1YzQ3ZGE2ZTZmNjljMDlhZjkyOTYwNDk3NTE3ODU4YmI5YjgzOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.zJ17cphrjw4YNTolFlPYk1Gl4MZEv1AJBKuTZuKxYuo)
> > > > 
> > > > 
> > > > Most likely when going through the setup it will attempt to see if there are other browers installed to port across your saved information (bookmarks and stuff) which other browsers do including firefox which zen is based on. I guess it made it more seriously for your SOC since the binary is not signed and looks like you just ran some malware.
> > > 
> > > 
> > > Right! That's probably some of it. But why is it reaching out to multiple CDN's at startup?
> > 
> > 
> > Well we would need to know which CDN were attempted to be access as the term "malicious" in the title is hard to prove when you have very little information. (If your SOC is logging all procress access calls then most likely they will have this information)
> > I checked through the codebase and can't see any "known" CDNs refference anywhere (I searched for names that I know since I work for a cyber security company but it's not a comprehensive list)
> > Once we have more information (domain names if possible) then the developers will be able to provide additional information.
> 
> I did not change any DNS settings as far as I know... Could it be possible because the app isn't signed?

Possibly, this might the only thing that flagged it in the first place. But I can't say for sure.

**Comment by chrede88** [comment]
> > > > I don't really have much more info. The SOC at my job only mentioned that the browser contacted a lot of CDN's using unsigned executables. See screendump they send me. ![image](https://private-user-images.githubusercontent.com/9137189/363408437-8ab6eb07-c320-42a6-84ad-219b690912a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyMDAxNDIsIm5iZiI6MTcyNTE5OTg0MiwicGF0aCI6Ii85MTM3MTg5LzM2MzQwODQzNy04YWI2ZWIwNy1jMzIwLTQyYTYtODRhZC0yMTliNjkwOTEyYTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDFUMTQxMDQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmQ5NGRjYWUxM2IwMjE4YmM2NTAyMjFhMDQ1YzQ3ZGE2ZTZmNjljMDlhZjkyOTYwNDk3NTE3ODU4YmI5YjgzOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.zJ17cphrjw4YNTolFlPYk1Gl4MZEv1AJBKuTZuKxYuo)
> > > 
> > > 
> > > Most likely when going through the setup it will attempt to see if there are other browers installed to port across your saved information (bookmarks and stuff) which other browsers do including firefox which zen is based on. I guess it made it more seriously for your SOC since the binary is not signed and looks like you just ran some malware.
> > 
> > 
> > Right! That's probably some of it. But why is it reaching out to multiple CDN's at startup?
> 
> Well we would need to know which CDN were attempted to be access as the term "malicious" in the title is hard to prove when you have very little information. (If your SOC is logging all procress access calls then most likely they will have this information)
> 
> I checked through the codebase and can't see any "known" CDNs refference anywhere (I searched for names that I know since I work for a cyber security company but it's not a comprehensive list)
> 
> Once we have more information (domain names if possible) then the developers will be able to provide additional information.

I got the list of remote URLs from the IT department, it's attached here as a .csv file. At `12:10:00.489` a connection to `dr.dk` was established, this was 100% me, so everything before is likely the startup of ZEN.

[DeviceNetworkEventsExport_Extended_strip.csv](https://github.com/user-attachments/files/16918502/DeviceNetworkEventsExport_Extended_strip.csv)

At this point I'm not really sure there is any "malicious" cdn's on the list. But I don't have a good list to check against.

**Comment by mauro-balades** [comment]
haha no way!

let's analyze a bit where's connecting to...


1. It's used for tracking protection.. basically, it's a list of URL that it should block (https://www.reddit.com/r/waterfox/comments/fwc2sf/shavarservicesmozilla_and/)
2. updates.zen-browser.app, I think that's pretty explanatory (checking for updates)
3. t2.gstatic.com used by the sidebar, to get the icons of the initial websites on startup

and other mozilla services like addon updates, etc... But there's definitely nothing malicous about it haha
