### ISSUE TITLE
Cannot see list of installed Zen Themes

### ISSUE THREAD

**Issue by ExistentialAlex** [zen-browser/desktop#1097]
### What happened?

I was previously running 1.0.0-a32 and after upgrading to 1.0.0-a33 this afternoon I can no longer see the list of Zen Themes I have installed.

![image](https://github.com/user-attachments/assets/8a585611-39fb-4739-b38d-61d8320c52d1)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a33

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
They are under the theme store tab now, bellow the keyboard shortcuts

**Comment by TiLopes** [comment]
If you go to "Theme Store" and refresh they appear, but yeah this needs to be fixed since I was also wondering where did my themes go. Also don't know if it was fixed but it has happened before that themes would appear twice for some reason.

**Comment by TiLopes** [comment]
@mauro-balades The Theme Store is indeed broken.
Here's a video:

https://github.com/user-attachments/assets/9817319e-6457-44e8-a802-972b48342660

**Comment by mauro-balades** [comment]
The settings are, not the theme stire

**Comment by TiLopes** [comment]
Well whatever it is causing it is broken. Maybe the request is not going off when settings is opened?

**Comment by ExistentialAlex** [comment]
Thanks for this. Will the list of themes load automatically now? Or will I need to refresh each time?
