### ISSUE TITLE
What DNS settings are being used?

### ISSUE THREAD

**Issue by FearlessSpiff** [zen-browser/desktop#1098]
### What happened?

I use Adguard on my private server. My router sends the DNS of this server to the clients. So when I do a test on https://d3ward.github.io/toolz/adblock in Firefox I get 79% stuff filtered. When I do the same on the same machine in Zen Browser I get 4% result?!?

So I checked for DNS settings, but could only find Proxy settings. 

So how does Zen do DNS lookups? Or what am I doing wrong?

I am surprised and won't use Zen anymore although I really like it!

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.32 (64-bit)

### Severity impact

High

### What platform are you seeing the problem on?

Linux

**Comment by NOCanoa** [comment]
i get 99% (whit ublock)
can you check at about:preferences#privacy bottom, whitch mode is on?
![image](https://github.com/user-attachments/assets/60a227e8-0549-493a-aa2e-714ba859bf48)

**Comment by FearlessSpiff** [comment]
Thanks. This was it. Had to "Off" it. Now everything is ok. No idea if the default should be otherwise... Or if it should come up when searching for DNS in the settings.

**Comment by NOCanoa** [comment]
defaut should be on, since normaly the router dns is the ISP (not good).

**Comment by FearlessSpiff** [comment]
fair enough. thanks
