### ISSUE TITLE
"Tabs on the right" keep some UI in fullscreen mode.

### ISSUE THREAD

**Issue by damianfijorek** [zen-browser/desktop#1100]
### What happened?

1. Enable "Tabs on the right"
2. Enter fullscreen mode e.g. go to YouTube video and press `f`.

The `.5rem` border on the left remains visible.

TL:DR I'll try to make a PR with a fix.

I've fixed it with following `userChome.css`. I think the border on left should be implemented exactly the same as in `zen-browser-container.css` e.g. margin instead of padding. I would move the margin style there. It would be easier to maintain and `!important` won't be needed. Another benefit would be better themes compatibility e.g. it will work with Disable Rounded Corners.

```
@media (-moz-bool-pref: "zen.tabs.vertical.right-side") and (not (-moz-bool-pref: "zen.view.compact")) {
  #navigator-toolbox {
    order: 6;
  }

  #zen-sidebar-splitter {
    order: 5;
  }

  @media (-moz-bool-pref: "zen.view.sidebar-expanded") {
    #navigator-toolbox:is([zen-user-hover="true"]:hover, :not([zen-user-hover="true"])) {
      padding-left: 0;
      padding-right: 2x;
    }
  }

  :root:not([inDOMFullscreen="true"]):not([chromehidden~="location"]):not([chromehidden~="toolbar"]) {
    & #tabbrowser-tabbox #tabbrowser-tabpanels .browserSidebarContainer {
      margin-left: var(--zen-element-separation) !important;
      margin-right: 0 !important;
    }
  }
}


#tabbrowser-tabbox {
  padding-left: 0 !important;
}
```

`padding-left: 0 !important;` should be just removed from `vertical-tabs.css`. It's needed only in `userChome.css` to override current `vertical-tabs.css`. 

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.33

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by damianfijorek** [comment]
#614 is related.

**Comment by BionicBlade0** [comment]
Same as #1117.

**Comment by NOCanoa** [comment]
Should be fixed, u can reopen the issue if it persists.
