### ISSUE TITLE
Tabs bar extends to Close button

### ISSUE THREAD

**Issue by ItsLaguna** [zen-browser/desktop#1101]
### What happened?

The tabs bar extends to the level of the close browser button while "Tabs on the right" is enabled, on 1.0.0-a.32 this doesn't happen.

|  Before (1.0.0-a.32)  | Currently (1.0.0-a.33) |
| ------------- | ------------- |
|![1725042743813](https://github.com/user-attachments/assets/0bd9bd15-564c-4f84-a76c-a70882993e6d) | ![1725042922356](https://github.com/user-attachments/assets/fca3cc73-f8f3-42a6-88bc-a785cc95f3ce) |

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.33

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by bw8686** [comment]
Feature not a bug.

**Comment by ItsLaguna** [comment]
> Feature not a bug.

Then how does one turn off this "feature"?

**Comment by bw8686** [comment]
You wait for cheff to hopefully approve my theme to the theme store.

**Comment by mauro-balades** [comment]
Will do

**Comment by ItsLaguna** [comment]
@mauro-balades can this get reopened or at least can you tell me how to fix it?
It's still present on latest...
