### ISSUE TITLE
Sidebar Bug - Sidebar Changes Locations

### ISSUE THREAD

**Issue by AlTimofeyev** [zen-browser/desktop#1102]
### What happened?

I have been using Zen for the past couple of days (as of this post) and just now ran into this issue. The bug seems to have appeared a few minutes ago after I signed into Sync with my Mozilla account through the Settings. I don't have Firefox installed on my system to check if this is reproducible with Firefox and not just Zen.

# The Issue
The sidebar has suddenly changed locations from the left side of the screen to the right side. After logging into Sync with my Mozilla account through the Settings, I closed all tabs and restarted Zen. When Zen was opened again, the sidebar now appeared on the right side instead of the left side. BUT!! Opening the bookmarks toolbar from the sidebar forces the sidebar to change locations back to the left side of the browser.

### After Logging into Sync and Reloading Zen
<img width="1792" alt="Screenshot 2024-08-30 at 11 45 42" src="https://github.com/user-attachments/assets/bb27a7f4-72fb-4a01-b115-03273594ca4c">

### Expanding and Closing The Sidebar
<img width="1792" alt="Screenshot 2024-08-30 at 11 45 56" src="https://github.com/user-attachments/assets/a345d205-24f1-45a2-a364-2c06c40686cf">
<img width="1792" alt="Screenshot 2024-08-30 at 11 45 42" src="https://github.com/user-attachments/assets/4a60ac2c-1f6e-4b00-89e0-1cc153064045">

**This action does NOT break the sidebar**

### Expanding and Closing the Bookmarks in The Sidebar
<img width="1792" alt="Screenshot 2024-08-30 at 11 46 26" src="https://github.com/user-attachments/assets/1a898611-6ab1-4727-9b09-5124b2562223">
<img width="1792" alt="Screenshot 2024-08-30 at 11 46 40" src="https://github.com/user-attachments/assets/9269d52b-5e8b-4824-b75e-f20b50ae1c39">

**This action DOES break the sidebar**  
I don't know why this happens. Reloading Zen again will restore the sidebar location back the the right side of the browser.

# Possible Solution
Allow the user to decide which side of the screen to show the Sidebar (left or right) through the Settings menu, in *Look and Feel* section. Personally, I prefer the Sidebar on the left hand side of the browser.

# My System
• MacOS Sonoma 14.6.1
• Intel CPU
• Zen Browser Version 1.0.0-a.33 (64-bit)

[EDIT] : ~~If the Zen Browser website has the latest release from GitHub, when the Release is published on GitHub, then I might have Zen Browser version between **Alpha build - 1.0.0-a.31** and **Alpha build - 1.0.0-a.32**. Not sure about any automatic updates at the moment though.~~  
I just realized I could check the Browser version in Settings -> General -> Zen Browser Updates.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

[EDIT] : ~~1.0.0-a.31~~ 
Version 1.0.0-a.33 (64-bit)

### Severity impact

Medium

### What platform are you seeing the problem on?

macOS - Intel

**Comment by JVintimilla** [comment]
I just experienced the same issue using 1.0.0-a.33 (64-bit) in GNU/Linux. I deleted the '.zen/' directory located on my home folder, and the browser got fully restored. Granted, this is not a good solution. 
I'd also like to say that I signed into my Mozilla account 4 days ago, and this issue happened a few minutes before writing this post.

**Comment by grqphical** [comment]
I have been having the same issue with 1.0.0-a.33 (64-bit) on Windows. It only moves back to the right side when I use my keybinding to toggle it's location and even then I have to click it twice as Zen still thinks it's on the right.

https://github.com/user-attachments/assets/26f70fd9-a32b-433e-9c4c-7be657353d89

**Comment by jrruethe** [comment]
Same issue here

**Comment by mauro-balades** [comment]
This should be fixed, ill release today as a hotfix
