### ISSUE TITLE
Scroll not working when using an External Wireless Mouse

### ISSUE THREAD

**Issue by vikas70607** [zen-browser/desktop#1105]
### What happened?

I am using a Wireless mouse and scrolling is not working when using scroll button, I tried of FireFox too this issue is there too. But it works on Chrome, Brave and Edge

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.33

### Severity impact

Medium

### What platform are you seeing the problem on?

Windows

**Comment by NOCanoa** [comment]
If it is on firefox the there is not match we can do : /
btw i am using a wireless mouse, u mean normal scroling?
