### ISSUE TITLE
Tabs on the right button doesn't work

### ISSUE THREAD

**Issue by bengalbroy** [zen-browser/desktop#1109]
### What happened?

When I select 'tabs on the right' it stays on the left and doesn't move 

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0 -a.33

### Severity impact

Low

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by grqphical** [comment]
does it seem to change the width of the sidebar when you toggle the setting?

**Comment by bengalbroy** [comment]
> does it seem to change the width of the sidebar when you toggle the setting?

No, it does nothing when pressed.

**Comment by grqphical** [comment]
alright so it isnt related to #1102
