### ISSUE TITLE
Support for Passkeys (macOS)

### ISSUE THREAD

**Issue by bengiv** [zen-browser/desktop#111]
When trying to log in with a passkey on a website it just asks for a security key. 
In Firefox 122 the passkey feature was first introduced and should work(on macOS) with macOS 14 Sonoma or newer.
I would greatly appreciate if this feature could also be added to Zen

**Comment by NOCanoa** [comment]
Just to add I am using PassKeys on windows whit Bitwarden no problems.

**Comment by bengiv** [comment]
> Just to add I am using PassKeys on windows whit Bitwarden no problems.

How is it with windows 11 passkeys, because you can also store passkeys on windows 11 and also use your phones passkeys to sign in.

With Bitwarden being a browser extensions that that is why it works

**Comment by NOCanoa** [comment]
If it doesn't recognize a password manager extension then it just open the windows default passkeys blabla.

**Comment by bengiv** [comment]
![image](https://github.com/user-attachments/assets/9dfd0380-1d29-4cbe-957f-774a3f602cb4)
(Source: https://learn.microsoft.com/en-us/windows/security/identity-protection/passkeys/?tabs=windows)
this one?

**Comment by bengiv** [comment]
if so, its only a macOS problem then

**Comment by NOCanoa** [comment]
yeah

**Comment by bengiv** [comment]
yea, then its a macOS Problem

**Comment by NOCanoa** [comment]
Do you want to use a passmanager or apple built in?

**Comment by bengiv** [comment]
Apple, iCloud Passwords, Keychain or whatever its called, where Apple saves Passkeys by default

**Comment by NOCanoa** [comment]
Ahh ok, i ave no idea of apple stuff xD

**Comment by mauro-balades** [comment]
I think that should be Mozilla's job as anything related to security/sensible information should rather be handled by a company instead of a single developer. Hope you understand.

Im gonna close the issue but feel free to open it if you want!

**Comment by bdbch** [comment]
I think Firefox itself supports this right? Can't test it right now but last time I was using Passkeys I think it worked on there.

Does that have something to do with browser & system related keys that Zen (and also Floorp) don't have?

**Comment by bengiv** [comment]
Firefox has it
<img width="1772" alt="image" src="https://github.com/user-attachments/assets/3f38d522-e6a0-4ec8-a480-e4a355215816">
<img width="1772" alt="image" src="https://github.com/user-attachments/assets/2271a6c7-9b0c-4ad5-b989-8e29d54f4155">

**Comment by bengiv** [comment]
This is what happens in Zen
<img width="1772" alt="image" src="https://github.com/user-attachments/assets/44e6934c-176c-49b4-86a4-06887e090d90">

<img width="1772" alt="image" src="https://github.com/user-attachments/assets/9e537667-1409-471c-be0d-350c5c48c9a5">

**Comment by mauro-balades** [comment]
What firefox version is that?

**Comment by bengiv** [comment]
> What firefox version is that?

newest stable version

<img width="842" alt="image" src="https://github.com/user-attachments/assets/2e07c1de-c162-4143-a842-ef9e46da0225">

**Comment by raff** [comment]
It's possible that the issue is that while Zen supports passkeys (via Firefox) it doesn't tell the system that they are supported. If I look in my Macos settings I see this:
<img width="719" alt="Screenshot 2024-08-20 at 9 42 11 PM" src="https://github.com/user-attachments/assets/580445b5-21de-4165-9dab-8991cfe91cfc">
And I am pretty sure the first time I used in one of those two browsers I was asked if I wanted to enable it.
Having said that, I am not sure of where that information is (my guess is that is done similar to the way an application asks to use the network or other resources)

**Comment by MaxNeedsSnacks** [comment]
From what I remember, passkeys are a privileged intent that needs to be specifically requested from Apple [here](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_web-browser_public-key-credential), and most other browsers I tried that are forks of Firefox (e.g. Floorp) or Chrome (e.g. Arc) seem to have this same issue. Apparently it works if you use a password manager that doesn't interact with the native backend for passkeys (like... I think Bitwarden?), but in my case, I'm using Strongbox so I've ran into this countless times already ^^;

**Comment by raff** [comment]
Ok, I do use Bitwarden but I am getting the native password manager most of the times.

**Comment by tsuliwaensis** [comment]
This should be re-opened as a feature request. If Zen wants to be considered a first-class citizen like Safari, Chrome, and Firefox then it needs to have feature parity.

**Comment by 0xAdriaTorralba** [comment]
Any news on this?

**Comment by bjsho** [comment]
#437

**Comment by umgefahren** [comment]
It seems like support for iCloud Passkeys landed on FireFox 7 days ago: https://www.mozilla.org/en-US/firefox/122.0/releasenotes/

**Comment by jtdowney** [comment]
> It seems like support for iCloud Passkeys landed on FireFox 7 days ago: [mozilla.org/en-US/firefox/122.0/releasenotes](https://www.mozilla.org/en-US/firefox/122.0/releasenotes/)

122.0 was one year ago

**Comment by hamza221** [comment]
Friendly bump, I feel like this is a crucial feature for a browser

**Comment by ewanc26** [comment]
I would love this. Main reason I'm stuck using Safari, really.

**Comment by OlaAde** [comment]
Friendly bump

**Comment by solazio** [comment]
would be great to get this feature

**Comment by desmondfuller** [comment]
I would agree that since Firefox has this, having it on Zen would be great.

**Comment by DeadIndian** [comment]
1 year later, is this a thing now? I am looking for a way to add passkeys to zen.... I landed here while googling

**Comment by DeadIndian** [comment]
> I would agree that since Firefox has this, having it on Zen would be great.

i am on fedora kde btw, not ios.

**Comment by bjsho** [comment]
> 1 year later, is this a thing now? I am looking for a way to add passkeys to zen.... I landed here while googling

@DeadIndian see https://github.com/zen-browser/desktop/issues/437 closed as resolved; hence this one being closed as well. please note i originally created this issue 2 years ago for the macos not linux.
