### ISSUE TITLE
Tab bar remains open in compact mode after creating a new workspace

### ISSUE THREAD

**Issue by AQDuck97** [zen-browser/desktop#1110]
### What happened?

When you create a new workspace and are in compact mode, the tab bar will remain until you click on the workspace button at the top and exit the tab bar.

Creating new tabs, clicking on page, etc. does not hide it like it normally does.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.32

### Severity impact

Low

### What platform are you seeing the problem on?

Linux

**Comment by VSparl** [comment]
I also have this issue, but for me it just happens after opening a website from a specific link directly (i.e. when I enter a full link directly into the address bar). The top bar stays open until I hover over it and move my mouse away, then it disappears. My cursor is not focused on the address bar either, it just doesn't autohide.

**Comment by salamijason** [comment]
Heylo, looks like this issue was posted a while back. Are you still getting these issues on the latest version? (a17 as of this comment)

**Comment by AQDuck97** [comment]
> Heylo, looks like this issue was posted a while back. Are you still getting these issues on the latest version? (a17 as of this comment)

Nope, it seems to have been fixed at some point. 
I completely forgot that I made this issue, closing it now.
