### ISSUE TITLE
This sidebar became a nightmare

### ISSUE THREAD

**Issue by markox92** [zen-browser/desktop#1114]
### What happened?

This sidebar became a nightmare to work with it

https://github.com/user-attachments/assets/a95ffd2c-f81a-469e-af79-6c26bfda2cfa

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.33

### Severity impact

High

### What platform are you seeing the problem on?

Windows

**Comment by n7itro** [comment]
The workaround is to not use expand-on-hover.

**Comment by mauro-balades** [comment]
Hi, im sorry you feel stressed about the sidebar. Im working on fixing the right click issue, but for now, you can either have it always expanded or always collapsed. Sorry!
