### ISSUE TITLE
tab bar stuck on right side

### ISSUE THREAD

**Issue by neurokitti** [zen-browser/desktop#1115]
### What happened?

at some point my tab bar got stuck on the right side. the issue persisted even after opening and closing the browser. I'm on windows and even after reinstalling the issue popped up again soon after reinstalling.
![image](https://github.com/user-attachments/assets/e0947058-b4bd-49ee-becf-aa3cf6885677)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.33

### Severity impact

High

### What platform are you seeing the problem on?

Windows

**Comment by Royshare** [comment]
The same issue occurred with me on an ARM-based MacBook. I configured a hotkey to toggle the sidebar on and off, then it defaults back to the left side.

**Comment by minegameYTB** [comment]
same issue on linux

**Comment by souravsgithub** [comment]
yeah same on my ubuntu. It was on the left but when I signed in with my account after that it moved to the right and only when I open the bookmarks it open in the left side and then stays there until I close the browser then reopens. Then the issue persists.

**Comment by neurokitti** [comment]
as of a recent update the issue is fixed for me!

**Comment by kaerer** [comment]
still happening on mac 15.4 was happening on majove as well.
