### ISSUE TITLE
When the tab bar is on the right side and a streaming video is in full-screen, a vertical border can be seen on the left side

### ISSUE THREAD

**Issue by BionicBlade0** [zen-browser/desktop#1117]
### What happened?

When the tab bar is on the right side and a streaming video (say youtube video) is in full-screen, a vertical border can be seen on the left side.

Using Fedora Workstation 40.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.32 (64-bit)

### Severity impact

Medium

### What platform are you seeing the problem on?

Linux

**Comment by Myouboku** [comment]
I reproduced the issue on base Firefox, Fedora 40 (Gnome)

**Comment by HiroshiAhsan** [comment]
It's not a scroll bar visibility issue for zen browser which I think the firefox issue refers to.

You can see the left side border during video fullscreen mode in  zen browser when the tab bar is on the right side.

This doesn't happen when the tab bar is on the left side (default location).

**Comment by Myouboku** [comment]
Oh, you're right I had not noticed that, happens on a34 on Windows too, I'll check what's going on

**Comment by BionicBlade0** [comment]
Pull Request #1112

**Comment by BionicBlade0** [comment]
Fixed after 1.0.1-a.
