### ISSUE TITLE
Now Player sound icon is extremely hard to see

### ISSUE THREAD

**Issue by slrgt** [zen-browser/desktop#1119]
### What happened?

Its very hard to see which tab is playing audio because the Sound icon is extremely small and the opacity is very light

![zen_bB2g45XoX0](https://github.com/user-attachments/assets/91a88143-f2eb-4132-9aad-546f3c786a76)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.32

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by RayZ3R0** [comment]
Does this still happen on latest version? (a.14 as of this comment)

**Comment by salamijason** [comment]
no response in 2 weeks. will be closing issue. please reopen if the issue persists
