### ISSUE TITLE
Performance Traker

### ISSUE THREAD

**Issue by NOCanoa** [zen-browser/desktop#112]
Now:
https://github.com/zen-browser/desktop/blob/main/Performance.md

Here i will put all the scores I obtained whit https://web.basemark.com/ 

OS: win 11
CPU: i5 13600k

|           | score:  |max |CSS | HTML5 | Page load and Responsiveness | Resize Cap. |
|-----------|----|-----|-----|-------|------------------------------|-------------|
| 1.0.0-a.10 | 1660.89 | 2660 | 59% | 91% | 91% | 76% |
| 1.0.0-a.9 | 470 | |  why  | why  | why  | why  |
| 1.0.0-a.8 | 446.74  | | 59% | 91%   | 96%                          | 76%         |
| 1.0.0-a.7 | 1964.43 | | 59% | 91%   | 91%                          | 76%         |
| 1.0.0-a.6 | 1747.98 | | 59% | 91%   | 91%                          | 76%         |
| 1.0.0-a.4 | 470.49  | | 59% | 91%   | 97%                          | 76%         |
| 1.0.0-a.3 | 475.52  | |59% | 91%   | 97%                          | 76%         |

https://www.tablesgenerator.com/
```mermaid
  graph TD;
      A(mauro-balades) --> B{🤯};
      C(Fire Fox) --> B;
```

**Comment by mauro-balades** [comment]
![Chart Title](https://github.com/user-attachments/assets/75b969c3-fb5f-413a-b483-34eebbc32523)


[Line chart.csv](https://github.com/user-attachments/files/16440709/Line.chart.csv)

**Comment by mauro-balades** [comment]
```mermaid
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
```

**Comment by NOCanoa** [comment]
```mermaid
  graph TD;
    A[mauro-balades] -->B(Zen custom code)
    G-->B
    H(ptr1337/CachyOS)-->|AUR Pkg and Opt. flags|D
    E(Fire Fox-Code)-->C
    B --> C{Final code}
    D-->G(Perf. Testing)
    C-->D(Build)
    D--> F(Release)
    F-->I(mar)
    F-->L(Mac)
    F-->T(Linux)
    F-->V(Win install)
    V-->Z(Zip)
    V-->Z2(Intall.exe)
    I-->I1(windows.mar)
    I-->I2(linux.mar)
    I-->I3(macos.mar)
    T-->T1(zen.linux.tar.bz2)
    T-->T2(AUR)
    T-->T3(Flatpak)
    T-->T4(AppImage)
    L-->L1(zen.macos.dmg)
```
