### ISSUE TITLE
The Pull Down Title / URL / Search Bar in Full Screen is not Appearing When not in Full Screen

### ISSUE THREAD

**Issue by sirinath** [zen-browser/desktop#1121]
### What happened?

The pull down title / URL / search bar in full screen is not appearing when not in full screen.

In full screen this generally appears when you move the mouse to the top of the window.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a34

### Severity impact

Critical

### What platform are you seeing the problem on?

Windows

**Comment by sidsharths1245** [comment]
Yes this is also happening with me. If the browser is in compact mode and I put it in windowed mode the top bar doesn't appear when i hover my mouse on top.

**Comment by mauro-balades** [comment]
You could maybe increase the number of `--zen-element-separation`

**Comment by mauro-balades** [comment]
You could maybe increase the number of `--zen-element-separation`

**Comment by sidsharths1245** [comment]
@mauro-balades Can you please share the steps?

**Comment by mauro-balades** [comment]
For the next release, itll be more customizeable
