### ISSUE TITLE
zen broken macos aarch64 Version 1 a.34

### ISSUE THREAD

**Issue by syrabo** [zen-browser/desktop#1122]
### What happened?

If I start the aaarch64 package, then tell me macos: the app is defect / corrupt.

I have a mac mini with M2 and last macos.

Zen browser package for intel works.

Best Regards, Die,

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0 a.34

### Severity impact

Low

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by NOCanoa** [comment]
did yha read the docs?

**Comment by NOCanoa** [comment]
https://docs.zen-browser.app/guides/install-macos

**Comment by PowerzinBR** [comment]
as NOCanoa said, read the docs  - since zen lacks an official developer license it appears that error/warning, also some services may be not working as streaming services due to the lack of an license (this also happens in windows and linux)

**Comment by PowerzinBR** [comment]
the docs mentioned you need to run this command:

`xattr -c '/Applications/Zen Browser.app/'`

after that, open Zen from the applications folder
