### ISSUE TITLE
Theme Store Settings now hide

### ISSUE THREAD

**Issue by Mojas84** [zen-browser/desktop#1125]
### What happened?

How it now settings for Theme Store not visible??? See only this https://screenshotx.com/i/48edvh

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.34

### Severity impact

Critical

### What platform are you seeing the problem on?

Windows

**Comment by NOCanoa** [comment]
if u press f5 it should appear.

**Comment by Mojas84** [comment]
> if u press f5 it should appear.
THX OK

**Comment by vytorrennan** [comment]
same thing happening here, no zen theme settings anywhere to be found on the settings

**Comment by mauro-balades** [comment]
CTRL+R and it should reappear, it should be fixed for the next release.
