### ISSUE TITLE
Cannot access Zen-Browser website after update

### ISSUE THREAD

**Issue by vegaskyo** [zen-browser/desktop#1127]
### What happened?

After updating to version 1.0.0-a.33, I can no longer access Zen Browser's website, though I can still access it on other browsers.
![image](https://github.com/user-attachments/assets/49ec4b92-0c7f-47a4-a4d9-68793866d03f)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.33

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
Secure Connection Failed

An error occurred during a connection to www.zen-browser.app. Cannot communicate securely with peer: no common encryption algorithm(s).

Error code: SSL_ERROR_NO_CYPHER_OVERLAP

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.
```

**Comment by NOCanoa** [comment]
Website is being relaunched/moved host, just have to wait till dns is propagated.
