### ISSUE TITLE
Add a feature that let's you switch tabs with the scroll wheel

### ISSUE THREAD

**Issue by RevanthSurapaneni** [zen-browser/desktop#113]
I've been using Firefox with the sidebery extension for a while now, and one of the cool features it has is that you can move the scroll wheel up or down while hovering over the tab bar to switch tabs very quickly.

I've only recently tried zen, but it looks like this browser could greatly benefit from that feature.  While keyboard shortcuts like ctrl tab are useful, sometimes it's just easier to breeze through dozens of tabs with a single use of the scroll wheel.

I don't know how easy or hard it is to implement this feature,  but it'll certainly be great to see it in action.

**Comment by ThatOneCalculator** [comment]
+1 on this, one of the main things missing from Zen imo!

**Comment by guigirl42** [comment]
Just fyi, there's a standard Firefox switch for this, available via `about:config`

`toolkit.tabbox.switchByScrolling`

It works fine too in Zen.

**Comment by mauro-balades** [comment]
Should this solve the issue? Please let me know so I can do some cleaning up

**Comment by guigirl42** [comment]
Well i don't know what _other_ users think [ie, if they want a UI toggle within the _Settings_], but from my perspective i enabled this  `about:config` switch right at the beginning of my using Zen, & it works perfectly.

**Comment by ThatOneCalculator** [comment]
I think that this should definitely be an option in settings! Had no clue about this config lol

**Comment by RevanthSurapaneni** [comment]
> Just fyi, there's a standard Firefox switch for this, available via `about:config`
> 
> `toolkit.tabbox.switchByScrolling`
> 
> It works fine too in Zen.

this is a godsend thank u so much!
