### ISSUE TITLE
YouTube slow and unresponsive, lag is fixed when e.g. Brave is open in the background

### ISSUE THREAD

**Issue by danielwies** [zen-browser/desktop#1130]
### What happened?

When ONLY Zen is open and a youtube video is playing, if you for example jump to a specific time in the video it takes 1-2 sec before any audio is being played. Interestingly this works totally fine if I have my original browser (Brave) running in the background doing absolutely nothing. As soon as I close Brave it starts to lag again -> opening Brave again and it's fixed. This is reproducible for me every single time.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.32 (64-bit)

### Severity impact

High

### What platform are you seeing the problem on?

Windows

**Comment by PowerzinBR** [comment]
is brave using hardware optimization? this may happen because brave is managing some of your computer resources in a positively way, but i'm not sure so i can't confirm!

**Comment by TomTruyen** [comment]
I think by default in Firefox based browser GPU acceleration is off. You could try to enable it:

1. type `about:config` in the address bar.
2. in the search bar type `gfx.webrender.all` and set it to true.
3. in the search bar type `media.ffmpeg.vaapi.enabled` and set it to true.

Source: https://www.reddit.com/r/linux/comments/xcikym/tutorial_how_to_enable_hardware_video/

**Comment by mauro-balades** [comment]
Im enabling these by default for the next release 👍🏽
