### ISSUE TITLE
Connection errors

### ISSUE THREAD

**Issue by jimfr** [zen-browser/desktop#1132]
### What happened?

<img width="891" alt="image" src="https://github.com/user-attachments/assets/e10cd1da-615c-4556-b265-131e074e592c">

also, failed to check for updates:

<img width="727" alt="image" src="https://github.com/user-attachments/assets/54ad524c-757e-4826-b834-806acebeb198">

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

a.33

### Severity impact

Medium

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by NOCanoa** [comment]
u can visit site at https://zen-browser.app/

**Comment by jimfr** [comment]
Thanks, but still getting the "Failed to check for updates" error in About Zen

**Comment by jimfr** [comment]
thanks.  I hadn't seen this:
https://www.reddit.com/r/zen_browser/comments/1f5ksnt/comment/lktqhiu/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

**Comment by NOCanoa** [comment]
btw its working now

**Comment by jimfr** [comment]
thank you very much :)
