### ISSUE TITLE
White text on light background in private mode new tab screen when using light theme

### ISSUE THREAD

**Issue by kittybwained** [zen-browser/desktop#1136]
### What happened?

Private windows use white text on a light background on the new tab page. Furthermore, the background gradient seems to be blue no matter what accent color you chose, which is strange.

Screenshot: https://imgur.com/a/TFhhMuJ

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.34

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by khaled-0** [comment]
Adding to this
![image](https://github.com/user-attachments/assets/3fccc155-4e47-4047-98b7-44e9a2251423)
