### ISSUE TITLE
Arc like peek Feature request

### ISSUE THREAD

**Issue by EvanSunde** [zen-browser/desktop#1137]
### What happened?

Peek like feature from arc browser which allows us to quickly view the webpage without leaving the current tab.

link for reference: https://resources.arc.net/hc/en-us/articles/19335302900887-Peek-Preview-Sites-From-Pinned-Tabs
  

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.34

### Severity impact

Low

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
For enhancements, please use discussions, thanks!
