### ISSUE TITLE
Tabs from different workspace merging

### ISSUE THREAD

**Issue by spectrum705** [zen-browser/desktop#1138]
### What happened?

if I am on a pinned tab(last ones) and when i close it a tab from different workspace gets added to the current one.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.34 (64-bit)

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
Could you provide a video? I dont seem to be able to reproduce

**Comment by Alfenstein8** [comment]
I have the same issue. When I restart the browser tabs from all workspaces are merged even though it shows that i'm in "default workspace". When I choose "default workspace" or any other workspace it works as expected
![Peek 2024-09-02 15-50](https://github.com/user-attachments/assets/7006fa6f-4bb5-42b8-8546-95c8c929e81c)

**Comment by spectrum705** [comment]
https://github.com/user-attachments/assets/abdd0b96-62f4-400c-b7f4-0929fd9e6d89

 So i was on the last pinned tab and i closed it using ctrl+w. the first tab from another workspace came in to be current workspace.

**Comment by kristijanribaric** [comment]
Could you confirm whether it is still happening on the latest version?

**Comment by spectrum705** [comment]
hi, it doesnt seem to happen in the with the latest versions :)
