### ISSUE TITLE
Sidebery features or better integration

### ISSUE THREAD

**Issue by redrockvp** [zen-browser/desktop#114]
Currently I am making use of the Sidebery extension in regular Firefox, along with the ArcWTF user chrome customisations, as a way to have vertical tabs and group projects (Panels) and different components of those projects (The tree structure and folders). It is currently the best way I've found to manage my tabs, as when combined with Auto Tab Discard and Container Tabs, it essentially means you can just leave everything open, but have it neatly organized. 

I really like the direction that Zen browser is going, but I'm missing some key features that are currently stopping me from trying it out full time. I'd love to see some features from Sidebery make their way into the browser. 

I believe the only thing missing from Zen, at least at a high level, is a tree style tab layout. I see that Tab Groups are being worked on, but it would be great to have tabs nestable under other tabs, along with nestable groups. 

The alternative for me would be better support for Sidebery, as currently, its a bit awkward to try and use it on Zen, as its a sidebar extension. Ideally, I'd want to be able to move the unique Zen buttons, e.g. the Zen Sidebar etc, to another location, such as the top bar or hide them on the right side of the browser, as having a double sidebar is a little awkward. 

Thanks for your work so far :)

Reference: https://github.com/kikaraage/arcwtf

**Comment by Jak2k** [comment]
Maybe you could soft fork Sidebery for better integration (e.g. for split tabs) and apply some style tweaks…

Apart from stability, this is the only thing holding be back.

**Comment by guigirl42** [comment]
Another vote here for incorporating the brilliant `Sidebery` functionality in Zen, please. I use it _extensively_ in `Firefox Nightly` & `Floorp`, & miss all its magic very badly in Zen. 

**Note**; IMO the "urgency" for this request is increasing, as i feel quite worried about the well-being of the `Sidebery` Project. Afaict at https://github.com/mbnuqw/sidebery, there's been no more project activity [at least, per _Commits_] for **four months**, which is very unusual compared to the earlier frequent activity. It would be a terrible shame if this amazing AddOn became unmaintained then broke with ongoing Firefox development, but building it into browsers like `Floorp` & `Zen` would ameliorate any such loss a bit.

**Comment by GitMurf** [comment]
> I believe the only thing missing from Zen, at least at a high level, is a tree style tab layout. I see that Tab Groups are being worked on, but it would be great to have tabs nestable under other tabs, along with nestable groups.

I cannot support and emphasize this comment enough! I know so many people (like me) that would instantly switch to a new browser like Zen with just the ability to do nested grouped tabs! Almost every browser these days has a 1 level deep grouping but basically  none of them allow for multiple levels of grouping (tree like).

Keep up the amazing work and I REALLY hope nested groups / tree structure will come to Zen natively at some point as I think it would be a differentiator and game changer for so many people!!

**Comment by ChristinWhite** [comment]
This is the single most important issue keeping me from switching over from Firefox as my primary browser.

**Comment by guigirl42** [comment]
FWIW, here's a copy of what i also just posted in https://github.com/zen-browser/desktop/issues/231#issuecomment-2307924996:

>Just as a fyi for all we fans / hopers for putative Zen native nested tabs & groups... the Dev said this, less than a fortnight ago:

>https://l.opnxng.com/r/zen_browser/comments/1eqqzlt/the_one_feature_that_will_win_me_over/

   >[u/maubg](https://l.opnxng.com/user/maubg) [10d ago](https://l.opnxng.com/r/zen_browser/comments/1eqqzlt/the_one_feature_that_will_win_me_over/lhtlywh/?context=3)

   >Yes, tab groups/folders and trees are on the way!

   >[u/maubg](https://l.opnxng.com/user/maubg) [10d ago](https://l.opnxng.com/r/zen_browser/comments/1eqqzlt/the_one_feature_that_will_win_me_over/lhv19c4/?context=3)

   >Natively

>So, i am excited!

**Comment by Muko-Tabi** [comment]
To make easier to track the good Sidebery features:

1. Advanced Tree-Style Tab Management
   - Highly customizable tree structure for organizing tabs

2. Tab Grouping
   - Ability to create and manage groups of related tabs

3. Multi-Panel Support
   - Multiple panels to segregate different sets of tabs

4. Unified Sidebar
   - Integrate History, Recently Closed Tabs, and Bookmarks into a single, easily navigable sidebar

5. Enhanced Container Management
   - Set custom proxy settings for each Firefox Container
   - Define regex rules for automatic website-to-container assignment

6. Tab Search Functionality
   - Powerful search feature to quickly locate specific tabs

7. Tab Customization
   - Option to rename individual tab titles

8. Bulk Tab Actions
   - Perform actions like unloading, clearing cookies, and copying URLs on multiple tabs simultaneously using mouse gestures

9. Session Snapshot and Recovery
   - Create snapshots of the current browsing session, including pinned tabs
   - Restore entire sessions in case of unexpected crashes or closures

**Comment by guigirl42** [comment]
That's an excellent summary list! I would like to also add this, which i never see others talk about, but which i regard as a "secret superpower" of `Sidebery`:

- the amazing tab management capabilities with the mouse buttons [not only, but especially my yellow highlights in the pic]:

![image](https://github.com/user-attachments/assets/a49304a2-c1f6-4c94-ab79-aa8806b91a34)

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/891

 ~ This is an automatic operation to better enhancements requests organization.

**Comment by guigirl42** [comment]
https://github.com/zen-browser/desktop/discussions/891#discussioncomment-11288211
