### ISSUE TITLE
Toolbar does open fully when docked on right side.

### ISSUE THREAD

**Issue by adityapandeydev** [zen-browser/desktop#1144]
### What happened?

![Screenshot 2024-09-01 035034](https://github.com/user-attachments/assets/4da9de4e-5253-49c8-a8fb-775d935dd385)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.29

### Severity impact

Medium

### What platform are you seeing the problem on?

Windows

**Comment by NOCanoa** [comment]
can u update the browser?

**Comment by adityapandeydev** [comment]
If it's fixed in the new update, well and good. I couldn't see the fix in
the release notes of the newer updates so raised the issue. I cannot update
the browser right now. Sorry for that

**Comment by NOCanoa** [comment]
Release notes need some work xP

**Comment by LeMoonStar** [comment]
As per comments above and my own reproduction attempt, this issue has been resolved.
