### ISSUE TITLE
Chrome.css Settings for color Tabs Backround and Normal and used color for font

### ISSUE THREAD

**Issue by Mojas84** [zen-browser/desktop#1145]
### What happened?

Is possible add to chrome.css line with change color of fonts and tabs backround???

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.34

### Severity impact

High

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
Is this really a high priority and a bug?

**Comment by mauro-balades** [comment]
Is this really a high priority and a bug?

**Comment by Mojas84** [comment]
> Is this really a high priority and a bug?

No I not know where add on our github.... Medium maybe...

**Comment by Mojas84** [comment]
> Is this really a high priority and a bug?

I can you ask use sidebar atd font as on settings too same as firefox??

**Comment by mauro-balades** [comment]
High severity is when there's a vut with zen that prevents startup and there's no workaround, please use discussions for questions/enhancements
