### ISSUE TITLE
Add please for theme store change installed themes without uninstall all different

### ISSUE THREAD

**Issue by Mojas84** [zen-browser/desktop#1146]
### What happened?

Add please for theme store change installed themes without uninstall all different@!

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.34

### Severity impact

Critical

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
Is this really critical?

**Comment by mauro-balades** [comment]
1. For future enhancements, please use github discussions
2. You can click on "check for upadtes" on the theme preferences
3. Please use the correct label next time
