### ISSUE TITLE
setup: add more search engines please

### ISSUE THREAD

**Issue by tomByrer** [zen-browser/desktop#1147]
### What happened?

only 2 US-based mega-corp search engine choices in search engines

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.34 (2024-08-30)

### Severity impact

Medium

### What platform are you seeing the problem on?

Windows

### Additional Info

I'm testing Zen as part of my de-Googling effort, & DuckDuckGo is more or less MicroSoft Bing at the moment.  I usually use search.brave.com, but I understand others may want to avoid that also.  Folks may prefer/can only use search engines from their own country, use an AI-search engine as default, etc.

**Comment by mauro-balades** [comment]
We are already working on this, for future enhancements, please use suggestions

**Comment by SherkeyXD** [comment]
Maybe me can just customize it?
btw Bing plz

**Comment by NOCanoa** [comment]
@SherkeyXD if you realy need it u can do it manually 
![image](https://github.com/user-attachments/assets/0065ce2b-8bfc-41f1-8a34-c622be060c53)
verry eazy

**Comment by SherkeyXD** [comment]
> if you realy need it u can do it manually ![image](https://private-user-images.githubusercontent.com/158103554/363530534-0065ce2b-8bfc-41f1-8a34-c622be060c53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyMzg3OTAsIm5iZiI6MTcyNTIzODQ5MCwicGF0aCI6Ii8xNTgxMDM1NTQvMzYzNTMwNTM0LTAwNjVjZTJiLThiZmMtNDFmMS04YTM0LWM2MjJiZTA2MGM1My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMlQwMDU0NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YjE5OGQzNzZmMWExMzk3MWE3NDRhZDNhMmI5ZWJiZjBhOTgyYjhkNGQ3YjkyZDlmY2M0NjZkYmE4NjAwNjkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lLoRiuYVIL8mia3MBv0oI2B-0l395hq8dQ1WH_sT_24) verry eazy

That's what I want! tks
