### ISSUE TITLE
Update 1.0.0-a.9 failing to install in the 'About Zen' section

### ISSUE THREAD

**Issue by tomlmbl** [zen-browser/desktop#115]
### What happened?

<img width="842" alt="image" src="https://github.com/user-attachments/assets/b735c88d-17d7-430d-8d7e-7842ad0e29fa">

<img width="673" alt="Screenshot 2024-07-31 at 10 26 38" src="https://github.com/user-attachments/assets/57219df5-3c0a-4cca-867a-13557669d6a2">

The 'Download the latest version' link from the 'About Zen' window and the 'Update available - Download now' pop-up redirect to the Firefox Nightly download page

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.8

### Severity impact

Medium

### What platform are you seeing the problem on?

macOS

**Comment by k0ann** [comment]
Initally installed with the 1.0.0-a.8 DMG, and Gatekeeper bypassed for all versions of the app

**Comment by mauro-balades** [comment]
What does it show when you click on `Details`?

**Comment by tomlmbl** [comment]
'Details' redirects to the Nightly download page (https://www.mozilla.org/en-US/firefox/channel/desktop/#nightly)

**Comment by mauro-balades** [comment]
Ill look into this, let's see if it works later for alpha.10 and if it doesnt, try to re-download it again on top of it (it doesn't delete your data)

**Comment by tomlmbl** [comment]
OK I'm holding then, will let you know!

**Comment by tomlmbl** [comment]
Same error from alpha.8 to alpha.10, I reinstalled Zen with the .dmg, will let you know for the next update attempt (only having it on MacOS)

**Comment by mauro-balades** [comment]
It looks like the file is "undefined" 😰 

https://github.com/zen-browser/updates-server/blob/main/updates/browser/Darwin_aarch64-gcc3/alpha/update.xml#L4

**Comment by mauro-balades** [comment]
It should be fixed!

**Comment by tomlmbl** [comment]
Yes fixed on my side thanks!
