### ISSUE TITLE
I can not Login on Twitter (x.com)

### ISSUE THREAD

**Issue by mr-p1nk** [zen-browser/desktop#1151]
### What happened?

I'm trying to log into Twitter (x.com) but the animated login screen never loads, it won't even let me enter my username and password. I've tried opening an incognito tab but that doesn't work either.
In other browsers (Edge and Firefox) it does let me log in. I've only had this problem in this browser.

![Screenshot 2024-09-01 001848](https://github.com/user-attachments/assets/b98e36a3-b8d3-48c9-9b54-bb19538da5d9)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.34

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by srynprjl** [comment]
i also had this problem, but i solved this by turning off "Enhanced Tracking Protection" for the site then login in, then enabling it again after logged in

**Comment by bohaoy** [comment]
Interesting enough, I was able to solve it by overriding the user agent to chrome for x.com. Then I was able to sign in

**Comment by Dellrall** [comment]
I got this issue as well, when I checked the console to check for error, it shows this error.

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.x.com/1.1/jot/client_event.json. (Reason: CORS request did not succeed). Status code: (null).

![image](https://github.com/user-attachments/assets/02a73a37-c960-4c07-a2fd-fe799d4f81be)

**Comment by Dellrall** [comment]
Also the solution to this issue has been published before https://github.com/zen-browser/desktop/issues/1027#issuecomment-2316460335

**Comment by mauro-balades** [comment]
Yeah, turning off enhanced protection will help 👍🏽

**Comment by mr-p1nk** [comment]
I was able to log in by disabling "Enhanced Tracking Protection"
Thanks everyone for the help. 👍
