### ISSUE TITLE
Start up is extremely slow

### ISSUE THREAD

**Issue by OmriLeviGit** [zen-browser/desktop#1152]
### What happened?

The initial start up of zen is very slow. After opening a single window, additional windows open instantly.
This issue does not occur on firefox, and is reproducable both after computer restart and reinstalling.

I recorded a video comparing the two (that has to be uploaded as a zip fie), with opening several windows at the end.
[example.zip](https://github.com/user-attachments/files/16827667/start.up.video.zip)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.34

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
Yeah, you can just add an exception until I get the license key 👍🏽
