### ISSUE TITLE
MacOS with M3 processor cant open AARC64 latest but open AMD64 package successfully

### ISSUE THREAD

**Issue by snirt** [zen-browser/desktop#1153]
### What happened?

I tried to install the AARC64 package and got an error that the package is damage, tried the AMD64 and the browser started successfully. 
![image](https://github.com/user-attachments/assets/c165f7a0-3baf-4b8a-8602-6ae3e2272355)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.34

### Severity impact

Low

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by greeeen-dev** [comment]
M1 Air user here, I got the same problem but this is probably because the app isn't signed. You should be able to bypass the error using `xattr -dr com.apple.quarantine "/Applications/Zen Browser.app"` in Terminal

**Comment by mauro-balades** [comment]
Please refer to https://docs.zen-browser.app/guides/install-macos until the license key arives
