### ISSUE TITLE
Failed to update on mac

### ISSUE THREAD

**Issue by sameer1612** [zen-browser/desktop#1154]
### What happened?

<img width="842" alt="image" src="https://github.com/user-attachments/assets/921c3b1a-9544-4bd7-9278-5a9183244b7b">

Shows this failed to update. I have to manually download and reinstall the latest version. Happening in ad-hoc versions.

Yeah, I have bypassed gatekeeper for all versions.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.34 (64-bit)

### Severity impact

Low

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by mauro-balades** [comment]
Should be fixed now 👍🏽
