### ISSUE TITLE
Please add Irish language support

### ISSUE THREAD

**Issue by aindriu80** [zen-browser/desktop#1155]
### Add Irish Language
Can you please add Irish language support? I don't see it listed in the options.  

![Screenshot-4](https://github.com/user-attachments/assets/add06554-ca17-426c-9fe0-8f2bc7c69935)

Irish is on Firefox https://pontoon.mozilla.org/ga-IE/ can you pull from there?  - I see https://github.com/zen-browser/desktop/issues/703 regarding adding more languages.  There are also sites dedicated to translations, Mozilla is quite slow at accepted translations.

https://weblate.org/en/
https://explore.transifex.com/

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.34 (64-bit)

### Severity impact

Low

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
Sure, I just added it 👍🏽

**Comment by aindriu80** [comment]
Thanks very much !!
