### ISSUE TITLE
Double click on title bar to full screen, not working on mac OS Sequioa

### ISSUE THREAD

**Issue by JosephSanjaya** [zen-browser/desktop#1156]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

In macOS Sequoia, there’s a new feature that allows users to double-click the title bar to maximize the window to full screen. However, when using Zen Browser, this feature does not work as expected. As a result, I need to manually adjust the window size every time I use the browser.

Steps to Reproduce:

1. Open Zen Browser on a macOS Sequoia system.
2. Double-click the title bar.

Expected Behavior: The window should maximize to full screen.

Actual Behavior: The window does not change size, requiring manual adjustment.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a33

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by mithom** [comment]
in windows this does work, seems to be a macOs (or unix) specific issue. version 1.0.0-a34

**Comment by Hyp3rSon1X** [comment]
I have the same problem on naked Firefox (version: 131.0.3)
I'm on Sequioa, too.

So this could be a problem coming from upstream.

**Comment by salamijason** [comment]
Looks like this is likely a Firefox issue on Sequioa. Since devs are using Firefox's code, it'd be better to wait for Firefox to release a fix.

**Comment by dkarter** [comment]
It's been over a year.. I have a feeling Firefox will not fix this issue (at least not in this decade 😅) - maybe this is one of those things that Zen can help solve?

**Comment by FakieHeelflip** [comment]
This issue is still there. Wow. Thinking about to switch the browser...
