### ISSUE TITLE
Kaspersky Antivirus detected a malicious object in the Zen Browser

### ISSUE THREAD

**Issue by Gubiar** [zen-browser/desktop#1158]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![image](https://github.com/user-attachments/assets/7e05e836-cce9-4810-8eb7-ecd9fe307fb0)

Kaspersky Antivirus detected a malicious object in the Zen Browser application. The file identified was zen.exe located in C:\Program Files\Zen Browser. The threat was classified as a Trojan, specifically identified as PDM:Trojan.Win32.Generic, with a high threat level.

The antivirus performed several actions in response:

Detected and identified the Trojan.
Terminated the process associated with the malicious file.
Created backup copies of the object for further analysis.
Finally, deleted the infected file to mitigate the threat.
This issue needs to be investigated further as it poses a significant security risk to users.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.33

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
[pt-BR]

Hoje, 01/09/2024 11:48:04	Objeto malicioso detectado	Zen Browser	zen.exe	C:\Program Files\Zen Browser	5608	DESKTOP-PEO1DAV\Gustavo	Iniciador	Detectado: PDM:Trojan.Win32.Generic	Detectado	PDM:Trojan.Win32.Generic	Cavalo de Troia	Alto	Exatamente	zen.exe	zen.exe	C:\Program Files\Zen Browser	Processo	Análise de comportamento
Hoje, 01/09/2024 11:48:04	Processo encerrado	Zen Browser	zen.exe	C:\Program Files\Zen Browser	7772	DESKTOP-PEO1DAV\Gustavo	Iniciador	Encerrado: PDM:Trojan.Win32.Generic	Encerrado	PDM:Trojan.Win32.Generic	Cavalo de Troia	Alto	Exatamente	zen.exe	zen.exe	C:\Program Files\Zen Browser	Processo	
Hoje, 01/09/2024 11:48:04	Foi criada uma cópia de backup do objeto	Zen Browser	zen.exe	C:\Program Files\Zen Browser	7772	DESKTOP-PEO1DAV\Gustavo	Iniciador	Cópia de backup criada: PDM:Trojan.Win32.Generic	Cópia de backup criada	PDM:Trojan.Win32.Generic	Cavalo de Troia	Alto	Exatamente	zen.exe	zen.exe	C:\Program Files\Zen Browser	Processo	
Hoje, 01/09/2024 11:48:04	Foi criada uma cópia de backup do objeto	Zen Browser	zen.exe	C:\Program Files\Zen Browser	20120	DESKTOP-PEO1DAV\Gustavo	Iniciador	Cópia de backup criada: PDM:Trojan.Win32.Generic	Cópia de backup criada	PDM:Trojan.Win32.Generic	Cavalo de Troia	Alto	Exatamente	zen.exe	zen.exe	C:\Program Files\Zen Browser	Processo	
Hoje, 01/09/2024 11:48:09	Objeto excluído	Zen Browser	zen.exe	C:\Program Files\Zen Browser	5608	DESKTOP-PEO1DAV\Gustavo	Iniciador	Excluído(s): PDM:Trojan.Win32.Generic	Excluído(s)	PDM:Trojan.Win32.Generic	Cavalo de Troia	Alto	Exatamente	zen.exe	zen.exe	C:\Program Files\Zen Browser
```

**Comment by mauro-balades** [comment]
This has been reported infinite times https://github.com/zen-browser/desktop/issues/37, the checkboxes are for you just to click, please try to find tuplicates the next time. Thanks!
