### ISSUE TITLE
Zen is overriding text and border colors on webpages

### ISSUE THREAD

**Issue by xeroneon** [zen-browser/desktop#1159]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Zen is adding an orange-ish hue to some of my webpages, most notable is anything I am developing locally and github.com
![image](https://github.com/user-attachments/assets/344913d5-c40b-4695-be24-73f951a76a97)
![image](https://github.com/user-attachments/assets/ea2ac5eb-6de0-4fab-a626-47f060e14106)
The first image is of githubs tab bar using Zen, The second image is of the same thing but in firefox.

I searched around all the settings trying to figure out how to disable this but I can't find anything that could be influencing it other than my chosen accent color, which I have changed but it still seems everything has that orange-ish hue still.

I hope this is addressable since I would like to use this as my main browser but I can't until I can develop with it and be sure colors are showing up correctly

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.32 (64-bit)

### What platform are you seeing the problem on?

macOS - Intel

**Comment by NOCanoa** [comment]
for me on  windows looks the normal, may be a mac specific issues,
Could u also update the browser, and report back if anything changed?

**Comment by mauro-balades** [comment]
Do you have any extensions or userChrome.css that could affect this? Maybe in a new, empty profile?

**Comment by Kaedriz** [comment]
Do you have Dark Reader installed, as I too thought something was wrong with colors until I remembered that Dark Reader is ON by default on installation.

As this looks very similar to Dark Reader accent:
![image](https://github.com/user-attachments/assets/91e67098-76ad-4d3e-a52d-6d0b4c355c7f)

**Comment by xeroneon** [comment]
Sorry I just checked and it was Dark Reader causing this, I didn't know darkreader would do that to my site even though it's already all in black and set to dark mode
