### ISSUE TITLE
Proxy configuration

### ISSUE THREAD

**Issue by benzino77** [zen-browser/desktop#1162]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

It looks like "Automatic proxy configuration URL" is not working as expected.
The same configuration on Firefox work fine. On Zen it looks like it is not even loaded (CTRL+SHIFT+J console does not show the message "PAC file installed from file:///home/benzino/Dokumenty/proxy.pac" after pushing reload button - that message is shown on Firefox)

![image](https://github.com/user-attachments/assets/d01e348e-bda0-4990-ae3b-e7434362382d)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.28

### What platform are you seeing the problem on?

Linux

**Comment by NOCanoa** [comment]
Are u using flatpak Zen? what version (check in about zen)?
If u using Zen flatpak did u test using FF flatpak version also?

**Comment by benzino77** [comment]
> Are u using flatpak Zen? 

Yes.

> what version (check in about zen)?

```
flatpak list
Name                            Application ID                                  Version                             Branch                 Installation
Zen Browser                     io.github.zen_browser.zen                       1.0.0-a.28                          stable                 system
```

> If u using Zen flatpak did u test using FF flatpak version also?

No I haven't. I will install flatpak version of FF and give you a feedback.

**Comment by benzino77** [comment]
Good point! It doesn't work on flatpak FF neither.

**Comment by NOCanoa** [comment]
So it doesn't work in FF flatpak ,  we cant do anything about it :  /, u can use a different app type 
https://docs.zen-browser.app/guides/downloads

**Comment by benzino77** [comment]
It was a problem with flatpak permissions:

For FF the solution was:

```sh
sudo flatpak override org.mozilla.firefox --filesystem=/home/benzino/Documents/proxy.pac:ro;
```

and for zen:

```sh
sudo flatpak override io.github.zen_browser.zen --filesystem=/home/benzino/Documents/proxy.pac:ro;
```

It is also possible to use `faltseal` application:

![image](https://github.com/user-attachments/assets/307b24f9-be66-44db-b65f-e27c918a1ad4)


Thanks for point me to the right direction ;)

**Comment by iNikAnn** [comment]
Installed Zen v1.21.15b (Flatpak) on Ubuntu 26.04.

"Use system proxy settings" doesn't work. Traffic bypasses proxy completely.

**Fix:** Go to `Settings` -> `Privacy and security` -> `Connection and software security` -> `Proxy Settings`, select "Manual proxy configuration", enter host and port manually (e.g. 127.0.0.1:7890).
