### ISSUE TITLE
Theme Store Settings Page gets stuck when checking for updates to themes

### ISSUE THREAD

**Issue by neurokitti** [zen-browser/desktop#1165]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

when clicking on the "check for updates"  button it just gets stuck. it is either loading and doesn't have an icon or doesn't work

![image](https://github.com/user-attachments/assets/5e897a3c-407e-40f8-900c-fef679b2d89a)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.34

### What platform are you seeing the problem on?

Windows

**Comment by IAmJafeth** [comment]
Hi @neurokitti,

Thanks for reporting your issue! 
This should be fixed with the following changed: 668124e1d0f32b8c75e1c4be97b764b4156919f1

Please test it once 1.0.0-a.35 gets released and let us know if the issue persist

**Comment by mauro-balades** [comment]
Also, what themes do you have installed? If you have too many, it may simply come down to a slow internet connection

**Comment by neurokitti** [comment]
> Also, what themes do you have installed? If you have too many, it may simply come down to a slow internet connection

its not internet also the themes are all small so it wouldn't mater much anyway. it takes like no time to install them

**Comment by neurokitti** [comment]
> Hi @neurokitti,
> 
> Thanks for reporting your issue! This should be fixed with the following changed: [668124e](https://github.com/zen-browser/desktop/commit/668124e1d0f32b8c75e1c4be97b764b4156919f1)
> 
> Please test it once 1.0.0-a.35 gets released and let us know if the issue persist

i checked and the issue is still there on 1.0.0-a.35

**Comment by mauro-balades** [comment]
Could you check terminal output or logs?

**Comment by neurokitti** [comment]
how do i check that?

**Comment by n7itro** [comment]
> Could you check terminal output or logs?

> [!CAUTION]
> TypeError: version1 is undefined - [ZenThemeMarketplaceParent.sys.mjs:42:37](https://github.com/zen-browser/components/blob/36e62781e27c19fade2df4d6a63e9062862ce7b0/src/actors/ZenThemeMarketplaceParent.sys.mjs#L42)

**Comment by mauro-balades** [comment]
Oh... Ok, I'll fix it for the next release

**Comment by LeMoonStar** [comment]
This issue seems to have been fixed already and has been stale for a while now. I will therefor close it.

If this is in fact still an issue, please comment or re-open.
