### ISSUE TITLE
when editing workspace there are 2 rows of icons

### ISSUE THREAD

**Issue by neurokitti** [zen-browser/desktop#1166]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

when editing a workspaces icon it has 2 duplicate rows of icons. normaly there should only be 1
![Screenshot 2024-09-01 174521](https://github.com/user-attachments/assets/494de2be-b688-4986-beeb-7ba8bb053d27)

i closed and reopened zen and it worked normaly so i dont know how to reproduce it 

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.34

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
This has been fixed now
