### ISSUE TITLE
Can't reorganize tabs in compact mode 

### ISSUE THREAD

**Issue by SophiaOquias** [zen-browser/desktop#1168]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I can't reorganize tabs on compact mode. Every time I attempt to do so, the tab becomes its own window. 

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.30

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
Fixed, thanks!
