### ISSUE TITLE
Ctrl + t binding gets overriden by Ctrl + Tab

### ISSUE THREAD

**Issue by KrystofJan** [zen-browser/desktop#1170]
### Captchas

- [x] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I set the `Close Tab`  keyboard shortcut to `Ctrl + t` and `Show Next Tab` to `Ctrl + Tab`. Now when I try to open a new tab using the created shortcut it switches to the next tab. 

I tried to change the settings so that the previous `Close Tab` and `Show Next Tab` shortcuts are switched (meaning that `Close + t` -> `Show Next Tab` and `Ctrl + Tab` -> `Close Tab`), but the issue persists. 

It works fine when I try any shortcut that doesn't involve `t`, e.g. `Ctrl + 0` mapped to `Close Tab` works. 

Here are my settings:
![image](https://github.com/user-attachments/assets/cee11fbd-d995-4278-aa70-76947100418f)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.32

### What platform are you seeing the problem on?

Linux

**Comment by NOCanoa** [comment]
![image](https://github.com/user-attachments/assets/2a47afe1-1345-4fcb-bf3e-aebad37ca441)
If u check this does the issue still persist?

**Comment by KrystofJan** [comment]
yes

**Comment by MaximumMaxxx** [comment]
Happens on my computer too. Using Flatpak on linux

**Comment by MaximumMaxxx** [comment]
I found a weird partial solution. If you unbind everything related to firefox core in the zen settings it reverts to firefox default bindings and everything works as expected.

**Comment by mauro-balades** [comment]
We are working on this, ill close it for better organization
