### ISSUE TITLE
Extensions won't update

### ISSUE THREAD

**Issue by L041S** [zen-browser/desktop#1173]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

It seems that browser addons won't update automatically, even if we force the update in the addons page of Zen.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.32

### What platform are you seeing the problem on?

Linux

**Comment by NOCanoa** [comment]
u mean theme store ?

**Comment by L041S** [comment]
Sorry, addons is not the right term, I meant extensions that you install from mozilla website

**Comment by mithom** [comment]
the OP is talking about Extensions as he clarified, NOT about theme's

**Comment by sjclayton** [comment]
Can confirm this behaviour here as well.. on 1.0.0.a.34, also on Linux.

**Comment by guigirl42** [comment]
Oh no, i'd somehow not realised this problem til now, but yes it's true for me too: `Version 1.0.0-a.37 (64-bit)` in `ArchLinux KDE Plasma`.  

Examples of Firefox _AddOns / Extensions_ now **out of date** in my ZenBrowser: 

- `Bookmark search plus 2` -- `2.0.129` in **Floorp**, of 10 August 2024, but still only `2.0.128` of 8 August 2024 in **Zen**
- `Dark Reader` -- `4.9.89` in **Floorp**, of 28 August 2024, but still only `4.9.88` of 8 August 2024 in **Zen**
- `LibRedirect` -- `2.9.1` in **Floorp**, of 23 August 2024, but still only `2.9.0` of 8 August 2024 in **Zen**
- `Sidebery` -- `5.2.0.9` in **Floorp**, updated yesterday, but still only `5.2.0.8` of 13 August 2024 in **Zen**
- `Stylus` -- `1.5.51` in **Floorp**, of 23 August 2024, but still only `1.5.48` of 8 August 2024 in **Zen**
-  `Widevine Content Decryption Module provided by Google Inc` -- `4.10.2830.0` in **Floorp**, updated yesterday, but still only `4.10.2710.0` of 8 August 2024 in **Zen**

Zen is great, a marvellous project, & i love it despite acknowledging it's still only in alpha development phase. However, having out of date _AddOns_ is more than only inconvenient, IMO it's also an _actual security hazard_. 

Pls Dev, i know you now have a million enthusiastic users haranguing you for all their pet bugs & features, but i think this bug needs fixing with urgency.

**Comment by mauro-balades** [comment]
Im looking into it 👍🏽

**Comment by n7itro** [comment]
This should be fixed with the next update

**Comment by sjclayton** [comment]
@mauro-balades Should probably be re-opened, as I still cannot update any of my extensions (many are out of date) on 1.0.1-a on Linux, clicking 'Check for updates' in the dropdown in about:addons still says it can't find any updates when there are clearly many needed. 

Unless I have to reset my profile from scratch or something to make the fix mentioned above that's supposed to be in this version work... which I'd hope could be avoided, because that'd be a pain to have to do on any sort of a regular basis.

**Comment by sjclayton** [comment]
@mauro-balades Any idea when this will finally be dealt with?

**Comment by guigirl42** [comment]
Oh, look! Seems that it will be resolved in the next update... https://github.com/zen-browser/desktop/commit/8f7b8506a625f242d22a85a2621ca31937088ade

**Comment by guigirl42** [comment]
Oh no. I just don't understand. I've just excitedly updated to a3, but **_the AOs still do not update_**.  Yet, afaict from the Commit, the problem-solution _should have been included in this build_:

![image](https://github.com/user-attachments/assets/ed657ccc-61ce-4e87-be5e-66febaede77d)

**Comment by sjclayton** [comment]
> Oh, look! Seems that it will be resolved in the next update... [8f7b850](https://github.com/zen-browser/desktop/commit/8f7b8506a625f242d22a85a2621ca31937088ade)

That commit was from 1.0.1-a, look at the date (it says last week), 2 updates were released since then and when I got the issue re-opened is also after that commit.

**Comment by guigirl42** [comment]
> That commit was from 1.0.1-a

Ah, silly me, i got myself a bit over-excited for nothing & then misunderstood; t/y. 

Overall i am really pleased with today's update to `1.0.1-a.3`, but this ongoing _severe bug_ is really spoiling the party now. :cry:

**Comment by 4NXIE7Y** [comment]
Still broken on Version `1.0.1-a.5`.😢

https://github.com/user-attachments/assets/34d212b1-403f-4bf0-b220-603f9c90702e

**Comment by n7itro** [comment]
This issue should be fixed with https://github.com/zen-browser/desktop/commit/c9df1d8b993a1810b7b1db145f7fbe1161a302e6 and https://github.com/zen-browser/desktop/commit/576541c4f1ace0f3cfc619c41b3ac226ead5cefe . 

Please let me know whether it is fixed when the next update releases (`a-6`)

**Comment by guigirl42** [comment]
> Please let me know whether it is fixed when the next update releases (`a-6`)

Yay yay **YAY**, _yessss_, now **finally it works**! I'm so pleased about this fix, as obsolete AOs was the one primary bug with Zen that really had been disturbing me for a long time. Now it's great.

Thank you to the Dev/s for this latest lovely work! 💜🤗🎉 🥳
