### ISSUE TITLE
MacOS Window Buttons In Wrong Location

### ISSUE THREAD

**Issue by NathanielH-snek** [zen-browser/desktop#1178]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Not sure if this is an issue on my end or not but basically the tab sidebar is rendering over where the window buttons should be. 
![Screenshot 2024-09-02 at 4 10 06 PM](https://github.com/user-attachments/assets/4279ce69-e9c2-477a-9b8f-57f2a80bc45e). I do have userContent.css file but removing it doesn't affect this issue, neither does clearing the cache. 

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.34

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by NOCanoa** [comment]
its intended like that, but next release u will be able to have it normal again
