### ISSUE TITLE
Unable to Close Tabs with Keyboard Shortcuts for TikTok and Similar Websites

### ISSUE THREAD

**Issue by Ahmedbhf** [zen-browser/desktop#1180]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

A  bug prevents users from closing certain tabs, such as those for **TikTok**, **Instagram**, and **some media-heavy websites**, using standard keyboard shortcuts. This issue is not universal but consistently affects these specific websites. Additionally, **when the browser crashes during YouTube playback**, the issue persists, making it impossible to close these tabs with shortcuts.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.34

### What platform are you seeing the problem on?

Linux, Windows

**Comment by mauro-balades** [comment]
Does it happen in both linux and windows?

**Comment by Ahmedbhf** [comment]
In the case of Linux, this bug is rare and not worth addressing at this time, but on Windows, it occurs 100% of the time.

**Comment by salamijason** [comment]
Heylo, looks like this issue was posted a while back. Are you still getting these issues on the latest version? (a17 as of this comment)

**Comment by salamijason** [comment]
No response in 3 days. Will be closing this issue. Please reopen if you are still facing the issue.
