### ISSUE TITLE
Goes unresponsive and forces me to force quit the application

### ISSUE THREAD

**Issue by nmallik1029** [zen-browser/desktop#1184]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When attempting to login to my Gmail, through Youtube for example, I'm able to type for 3-4 seconds before the entire app freezes for a few seconds and windows prompts me to quit the application and sends a note to Microsoft. 
![Screenshot 2024-09-02 211800](https://github.com/user-attachments/assets/8f9444b2-25cc-4508-88f8-bc56b215785b)

Not really sure how else to explain so I attached a picture, not sure if it helps explain anything. 

Edit: I have seen last week that another user also created this issue but it was closed as "completed", so I'm not sure if that means that it was solved when it clearly wasn't. If it's being fixed sorry for the duplication.
### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

11.18.0

### What platform are you seeing the problem on?

Windows

**Comment by supersketchy** [comment]
Also have this issue, I am using win 1.0.0-a.35

**Comment by n7itro** [comment]
> Also have this issue, I am using win 1.0.0-a.35

Does this issue occur on the generic version of Zen?

**Comment by supersketchy** [comment]
Have not tested, I am using the specific version

**Comment by mauro-balades** [comment]
What other issue had this marked as resolved?

**Comment by supersketchy** [comment]
It seems to be fixed now
