### ISSUE TITLE
Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings. )

### ISSUE THREAD

**Issue by SmokeyPlayz** [zen-browser/desktop#1187]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

 i need hellp figuring this out, so i'm trying out this new browser called Zen and i wanted to try out something new like keepassxc (password manager) so the one problem i keep facing for the extension part is the integration part which I don't know how to enable for this browser my thing is endeavour OS the browser is (Zen Browser) problem I am facing is (KeePassXC-Browser has encountered an error: 
 Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings. )
![image](https://github.com/user-attachments/assets/94cdcd81-d8b2-4762-99c4-3436cf74bb0c)
 now on the right it's the desktop version and the left is Zen browser/ KeePassXC extension version, the reason I did this because every time I log in for some odd reason I will need to log in into discord again and also like my Gmail account again for Firefox and Zen which hopefully this password manager I heard was best and free can maybe solve that problem, but seems I ran into a little tight spot, off-topic, but I wish they added custom wallpapers XD.

(i downloaded this from the flat hub doing the Manuel install commands) since endeavour OS is Arch based I did it the Arch way if anyone who is reading this get wot I'm saying.
![Screenshot_03-Sep_03-12-43_9743](https://github.com/user-attachments/assets/168cdca6-38a4-4c34-ade9-4e4165ade3aa)
maybe someone knows a solution, btw please make it simple as possible Since I'm a new Linux user, Reason i chose Linux is because i'm doing cybersecurity and i believe Linux can help me get more deep into like certain tools that people use for cybersecurity since it's my challenging career i'm taking, As a college freshman.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.28

### What platform are you seeing the problem on?

Linux

**Comment by mithom** [comment]
i use this same application without any issues. out of security i also advice you to not enable all browser integrations, just having firefox enabled will work for the zen browser.

**Comment by mithom** [comment]
also, have you installed the keepassXC browser extension?

**Comment by mithom** [comment]
in te settings of the browser extension, have you linked your database? in the picture you posted you only have the general settings page open, try opening the hamburger icon to open the menu, and go to connected databases. There make sure you're connected

**Comment by sayhilel** [comment]
You can copy the native-messaging-hosts from ~/.mozilla to ~/.zen and then use custome browser integration in keepassXC pointing to ~/.zen/native-messaging-hosts

**Comment by SmokeyPlayz** [comment]
> You can copy the native-messaging-hosts from ~/.mozilla to ~/.zen and then use custome browser integration in keepassXC pointing to ~/.zen/native-messaging-hosts

How do I do that? Because I do not know how to.

**Comment by SmokeyPlayz** [comment]
![Screenshot_03-Sep_23-31-32_24906](https://github.com/user-attachments/assets/8cf4ed6b-b47e-432e-9970-7711d998a35c)

So when I log in this is wot I first see now I did do the ~/.zen/native-messaging-hosts part by going into the advanced setting's in the windows integrations page, But I don't think it did anything which mean I'm still stuck, now backing up to the connecting database I do sadly to say is that it is not connected which is not good, I'm not sure wot to do now since that is not connected in the first place, again I do state I am new to all of this Linux the password manager, I'm basically a level 1 newbie as I do say I never tried a password manager, and I do say when I logged into my laptop again tonight opened up discord once more, It shows once again the login screen which means I had to log in again by scanning the QR code which is quite jarring. Here I will provide more images to show wot I am currently seeing on my side of the screen
![image](https://github.com/user-attachments/assets/dcee8294-8a4f-4a55-95a1-29065aacf5f7)
First one is the desktop and other is the extension, 
![image](https://github.com/user-attachments/assets/df568eb6-62a8-4ffe-9515-465086292221)

here is the desktop version again,
![image](https://github.com/user-attachments/assets/3c992e62-750a-40f2-a23f-0d25c19ee5a1)
![image](https://github.com/user-attachments/assets/2e431558-f786-446a-a873-2558f80c7ef0)
![image](https://github.com/user-attachments/assets/38f5f135-e1d0-4640-a7b8-a4bb2d7d52e8)

**Comment by Mrcuve0** [comment]
I tried too establishing a connection using the procedure explained at https://github.com/keepassxreboot/keepassxc-browser/issues/1631#issuecomment-1153736766 but with no success.
I changed, of course, all the paths to point to the correct Zen's folder and added all the permissions with `flatpak override` to the correct binary + made executable the .sh script.

Additionally, I tried setting the flag "Use a custom browser configuration location" and set up the correct path to the `native-messaging-hosts` folder, but the conenction is not being established.

Can someone share they procedure if they were able to succeed? 
PS I'm trying connecting flatpak Zen with Flatpak KeepassXC

**Comment by SmokeyPlayz** [comment]
same here fr.

**Comment by SmokeyPlayz** [comment]
Looks like there is no solution sadly

**Comment by mauro-balades** [comment]
> ![Screenshot_03-Sep_23-31-32_24906](https://private-user-images.githubusercontent.com/80928946/364214091-8cf4ed6b-b47e-432e-9970-7711d998a35c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3ODQ4NTcsIm5iZiI6MTcyNTc4NDU1NywicGF0aCI6Ii84MDkyODk0Ni8zNjQyMTQwOTEtOGNmNGVkNmItYjQ3ZS00MzJlLTk5NzAtNzcxMWQ5OThhMzVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA4VDA4MzU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkMjc5YjQxNzQyMmFkMWRkZjEzZDgyMDRlNzA1ZmI4YWFkMmY0M2U0OGYyNzFlNjMyOTM4MDc0ZjJhMWVkNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vj1ibECQcp12CstMbENDgciZo-i4sKzKpDN81kNlWto)
> 
> So when I log in this is wot I first see now I did do the ~/.zen/native-messaging-hosts part by going into the advanced setting's in the windows integrations page, But I don't think it did anything which mean I'm still stuck, now backing up to the connecting database I do sadly to say is that it is not connected which is not good, I'm not sure wot to do now since that is not connected in the first place, again I do state I am new to all of this Linux the password manager, I'm basically a level 1 newbie as I do say I never tried a password manager, and I do say when I logged into my laptop again tonight opened up discord once more, It shows once again the login screen which means I had to log in again by scanning the QR code which is quite jarring. Here I will provide more images to show wot I am currently seeing on my side of the screen ![image](https://private-user-images.githubusercontent.com/80928946/364215252-dcee8294-8a4f-4a55-95a1-29065aacf5f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3ODQ4NTcsIm5iZiI6MTcyNTc4NDU1NywicGF0aCI6Ii84MDkyODk0Ni8zNjQyMTUyNTItZGNlZTgyOTQtOGE0Zi00YTU1LTk1YTEtMjkwNjVhYWNmNWY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA4VDA4MzU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzZGNkNDAxZGJjZmNkMTljZmE3ZmYyMGY4YjFlODIwOTc2NTFjM2EyNzIzYWExM2I2NzAyOTk4Nzc4NDc3MjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cIOcMGU56L9tfOGxmyzDh0vQ_VNW4PduCvjxuX-WteQ) First one is the desktop and other is the extension, ![image](https://private-user-images.githubusercontent.com/80928946/364215541-df568eb6-62a8-4ffe-9515-465086292221.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3ODQ4NTcsIm5iZiI6MTcyNTc4NDU1NywicGF0aCI6Ii84MDkyODk0Ni8zNjQyMTU1NDEtZGY1NjhlYjYtNjJhOC00ZmZlLTk1MTUtNDY1MDg2MjkyMjIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA4VDA4MzU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxNzgyNGVhYzQ0ZWNmNGVlZmRlNDcyNWQ5NDU5MTYwZGJiMDY1Yzg4ZjIyYmEwNGRhMWViNzkyMzkyYzJiYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Tll71C82ZdskZxB1_j-Jo-dpLslaTEHN7tV_7yPF9HA)
> 
> here is the desktop version again, ![image](https://private-user-images.githubusercontent.com/80928946/364215774-3c992e62-750a-40f2-a23f-0d25c19ee5a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3ODQ4NTcsIm5iZiI6MTcyNTc4NDU1NywicGF0aCI6Ii84MDkyODk0Ni8zNjQyMTU3NzQtM2M5OTJlNjItNzUwYS00MGYyLWEyM2YtMGQyNWMxOWVlNWExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA4VDA4MzU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhMzBkYTIyMGE3NDQxN2E5ZDY4ODk0NDA0ZDVhMjJhNzA4ODVkNjNkZmRjM2UxMWI4M2FkZWU3YTY3ODIxYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0NqaKI-Ahlnn3UmDl43a2J1GEzPYSiF_6zjXV1oBa4k) ![image](https://private-user-images.githubusercontent.com/80928946/364215893-2e431558-f786-446a-a873-2558f80c7ef0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3ODQ4NTcsIm5iZiI6MTcyNTc4NDU1NywicGF0aCI6Ii84MDkyODk0Ni8zNjQyMTU4OTMtMmU0MzE1NTgtZjc4Ni00NDZhLWE4NzMtMjU1OGY4MGM3ZWYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA4VDA4MzU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5NjQzZGUyNjcyMDgxZWJhZGJmMDY0YTI0MDYzYmNlZWZlYzVjODRiZmU3ZGEwMzBjNjAyM2Q1OTM5ZDRlZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BK4kJVoNAXEhtFCg51ZD6vdQACHmDXKFIQmvkZIzsoU) ![image](https://private-user-images.githubusercontent.com/80928946/364216056-38f5f135-e1d0-4640-a7b8-a4bb2d7d52e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3ODQ4NTcsIm5iZiI6MTcyNTc4NDU1NywicGF0aCI6Ii84MDkyODk0Ni8zNjQyMTYwNTYtMzhmNWYxMzUtZTFkMC00NjQwLWE3YjgtYTRiYjJkN2Q1MmU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA4VDA4MzU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkZGFiYWFlODA2MmZmMDg0NzRhYzY5NmI3YzRlMjcyZjg4Njk0ZmVlZDIyNjVlMmI0YTg1YWRjYzllNjQ5YjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Gzr6rX7JtiCrnsat5KCzwVsBLRo-17hzAr7EeWFmwhE)

I dont know about the app, but does it actually support `~` for the path?

**Comment by Mrcuve0** [comment]
Hi Mauro and thank you so much for your work!
I'll try to give you as much details as possible to help you 

Here's my configuration, following the procedure you can find here with all the path adjusted --> https://github.com/keepassxreboot/keepassxc-browser/issues/1631#issuecomment-1153736766

1. Granted the browser access to KeePassXC flatpak app and KDE runtime installations, and to the KeePassXC proxy socket: 
```
flatpak override --user \
  --filesystem={/var/lib,xdg-data}/flatpak/{app/org.keepassxc.KeePassXC,runtime/org.kde.Platform}:ro \
  --filesystem=xdg-run/app/org.keepassxc.KeePassXC:create io.github.zen_broswer.zen
```

2. Created a wrapper script that will launch the official keepassxc-proxy from KeePassXC flatpak, at a path accessible by the Firefox flatpak, e.g. 
```
~/.var/app/io.github.zen_browser.zen/data/bin/keepassxc-proxy-wrapper.sh
```
 This script requires Flatpak 1.12 or newer. 
```bash
#!/bin/bash

APP_REF="org.keepassxc.KeePassXC/x86_64/stable"

for inst in "$HOME/.local/share/flatpak" "/var/lib/flatpak"; do
    if [ -d "$inst/app/$APP_REF" ]; then
        FLATPAK_INST="$inst"
        break
    fi
done
[ -z "$FLATPAK_INST" ] && exit 1

APP_PATH="$FLATPAK_INST/app/$APP_REF/active"

RUNTIME_REF=$(awk -F'=' '$1=="runtime" { print $2 }' < "$APP_PATH/metadata")
RUNTIME_PATH="$FLATPAK_INST/runtime/$RUNTIME_REF/active"

exec flatpak-spawn \
    --env=LD_LIBRARY_PATH=/app/lib \
    --app-path="$APP_PATH/files" \
    --usr-path="$RUNTIME_PATH/files" \
    -- keepassxc-proxy "$@"
```
Then, make this script executable:
```
chmod +x keepassxc-proxy-wrapper.sh
```
3. Put the native messaging host json manifest to a the path where flatpaked Zen will look for it, e.g.
```
~/.var/app/io.github.zen_browser.zen/.zen/native-messaging-hosts/org.keepassxc.keepassxc_browser.json
```
 and edited its contents to launch the previously created wrapper, e.g. 
```json
{
    "allowed_extensions": [
        "keepassxc-browser@keepassxc.org"
    ],
    "description": "KeePassXC integration with native messaging support",
    "name": "org.keepassxc.keepassxc_browser",
    "path": "/var/home/<YOUR_USERNAME_HERE>/var/app/io.github.zen_browser.zen/data/bin/keepassxc-proxy-wrapper.sh",
    "type": "stdio"
}
```
(My path starts with /var/home/ instead of /home/ because I'm using Fedora Silverblue)

---

> I dont know about the app, but does it actually support `~` for the path?
Yes, when you enter `/var/home/username` or `/home/username`, at the next restart those will get substituted with `~ `, so I suppose it's intended behavior.

What I recall when giving a try to Floorp browser (which was Flatpak too), this "advanced" browser configuration wasn't necessary and the communication with KeepassXC was working with the exact same procedure highlighted above. There was no need to point to a custom path as Floorp was (I guess) directly recognized as a Firefox fork (indeed, it's path were exactly like firefox, with a `.firefox` folder, not a `.floorp` folder (like Zen does, with a `.zen` folder))

**Comment by Mrcuve0** [comment]
> i use this same application without any issues. out of security i also advice you to not enable all browser integrations, just having firefox enabled will work for the zen browser.

Hi @mithom! Were you able to establish a connection between KeepassXC and Zen? If yes, would you like to explain us your procedure? Thanks a lot!

**Comment by mauro-balades** [comment]
Sorry for not helping much, I have never heard of this app before….

**Comment by bl4xe** [comment]
mine works, I'm not sure if it's because I copy and pasted the extensions folder from the profile directory from my previous firefox install..

**Comment by salamijason** [comment]
Heylo, looks like this issue was posted a while back. Are you still getting these issues on the latest version? (a17 as of this comment)

**Comment by SmokeyPlayz** [comment]
Yea

**Comment by salamijason** [comment]
hmm thing is, dev himself says he doesn't know how to help cuz he's never heard of or used the app before. I'll send it off to him but no promises. :/
