### ISSUE TITLE
Focus on last accessed tab while restoring session

### ISSUE THREAD

**Issue by imreverse** [zen-browser/desktop#1192]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

While restoring session, the last accessed/opened tab should be focused, instead of the first tab. I've tested this on default profile.
Basically what is mentioned in this:
https://www.reddit.com/r/firefox/comments/fhdgbq/session_restore_also_automatically_go_to_the_last/

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.34 (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
This has now been fixed in version 39! Please update it to notice the changes
