### ISSUE TITLE
Theme setting not showing up in Look and Feel tab

### ISSUE THREAD

**Issue by HiroDane** [zen-browser/desktop#1193]
### Captchas

- [X] I have read the instructions.
- [ ] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

I have installed several themes from the Theme Store but I do not see the customization options for them that are supposed to show up in the Look and Feel tab of zen settings. This is not just for any specific themes, any and all themes do not show any customizable settings.
I am on Windows 10 if that is relevant.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.34 (64-bit) Windows

### What platform are you seeing the problem on?

Windows

**Comment by NOCanoa** [comment]
Reload page or click F5. fixed for next update

**Comment by HiroDane** [comment]
Thanks for the fix, excited for new update. 
Btw reloading doesn't work. The tab just doesn't show anything at all after refresh, completely blank.
