### ISSUE TITLE
Can't update to 1.0.0-a.35

### ISSUE THREAD

**Issue by nazmiyigitefe** [zen-browser/desktop#1194]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Both on my Windows and MacOS devices, I can't update to the latest version (1.0.0-a.35). Zen browser says that you're latest, but I'm not.

<img width="719" alt="Ekran Resmi 2024-09-03 16 23 19" src="https://github.com/user-attachments/assets/bfee57e4-4c75-46bc-afad-f030e824ee4f">

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.34

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by nazmiyigitefe** [comment]
What should I do for my MacOS device?

**Comment by NOCanoa** [comment]
still building
https://github.com/zen-browser/desktop/actions/runs/10682038862
