### ISSUE TITLE
Change Tab to Workspace shows workspaces twice

### ISSUE THREAD

**Issue by benni347** [zen-browser/desktop#1196]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I clicked a tab with the right mouse button and hovered over `Change Tab(s) to Workspace` and saw that the workspaces are listed twice.

<img width="535" alt="Screenshot 2024-09-03 at 16 05 23" src="https://github.com/user-attachments/assets/492c243b-b3ca-4333-86ec-9adceb4d4c0c">
<img width="325" alt="Screenshot 2024-09-03 at 16 05 33" src="https://github.com/user-attachments/assets/10f06d44-14f1-4abe-9c64-3cf6ded0bc00">

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.34

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by Masamas** [comment]
@mauro-balades 
Issue is still present for me on newest Version.
I tried creating a new Workspace and deleting it afterwards to maybe get the list to "regenerate" but had no success. Workspaces are still listed twice.

### Version

1.0.0-a.37
### What platform are you seeing the problem on?

macOS - aarch64

**Comment by jimfr** [comment]
Yes, agree with Masamas, still present in a.37 (macOS-aarch64).

**Comment by mauro-balades** [comment]
Could you send me the steps to reproduce in the format of a video? So I can visit better

**Comment by jimfr** [comment]
sorry, my bad, Firefox doesn't have it; Sideberry does.  I was used to
using it with Edge, I guess I'll just have to live without it.

Even though it's not in Firefox, I'd still like to see it in Zen, which is
now my daily driver (replacing Edge).

Thanks, and sorry again for the misinformation.

Jim

**Comment by HarryHeres** [comment]
@mauro-balades I will take a look onto this as I experience this issue as well on my Mac

**Comment by mauro-balades** [comment]
I'll check it out in a minute, looks good!
