### ISSUE TITLE
the .34 release will not open on M1 Mac Silicon. This was reported as fixed in .35, but as of 9/3/24, .35 is not available. At least to me. 

### ISSUE THREAD

**Issue by robinkaty** [zen-browser/desktop#1197]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

After downloading a.34 and installing, the error : “Zen Browser.app” is damaged and can’t be opened. You should move it to the Trash." still appears. I saw a note about .35 fixing this, but 34 still has the issue and .35 is not available. 

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-.a34

### What platform are you seeing the problem on?

macOS - aarch64

### Relevant log output

```shell
not seeing any logs when going through the console.app.
```

**Comment by onecrazygenius** [comment]
have you tried running `xattr -c '/Applications/Zen Browser.app/'` in iTerm? I had to do that with version a34 on my m2 air as the apple cert was just added so will be in next build

**Comment by NOCanoa** [comment]
a35 coming soon, sorry for confusion on the release note on www : /
https://docs.zen-browser.app/guides/install-macos

**Comment by robinkaty** [comment]
FYI: xattr -c '/Applications/Zen Browser.app/' did allow the app to run. Wonder why OSX just doesn't print a permission issue failed to allow app to run?
