### ISSUE TITLE
Zen crashes youtube github chatgpt etc.

### ISSUE THREAD

**Issue by vanishLLC** [zen-browser/desktop#1200]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

While watching youtube video or trying to get into chatgpt zen randomly crashes browser
![zen_XcgcQKbPLj](https://github.com/user-attachments/assets/88281363-8875-4b88-8740-7d266028bc33)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.33 

### What platform are you seeing the problem on?

Windows

**Comment by HarshK200** [comment]
The similar thing happens when trying to connect to a discord voice call.

OS: Ubuntu 22.04.4 LTS x86_64
Kernetl: 6.8.0-40-generic
CPU: AMD Ryzen 5 5500U with Radeon Graphics (12) @ 4.056GHz
GPU: AMD ATI 03:00.0 Lucienne

Steps to reproduce:
 just join a discord vc call in a server

**Comment by vanishLLC** [comment]
> The similar thing happens when trying to connect to a discord voice call.
> 
> OS: Ubuntu 22.04.4 LTS x86_64 Kernetl: 6.8.0-40-generic CPU: AMD Ryzen 5 5500U with Radeon Graphics (12) @ 4.056GHz GPU: AMD ATI 03:00.0 Lucienne
> 
> Steps to reproduce: just join a discord vc call in a server

Failed to reproduce using discord vc call

OS: Win 10 home 22h2
Cpu amd threadripper 2920x
GPU: Nvidia rtx 2080

**Comment by mauro-balades** [comment]
Could you check the logs or any terminal output?

**Comment by vanishLLC** [comment]
> Could you check the logs or any terminal output?

sure where does zen store error logs? or how can I access them

**Comment by HarshK200** [comment]
@vanishLLC it's probably specific to Linux distro build
Maybe try on a vm?

**Comment by vanishLLC** [comment]
> @vanishLLC it's probably specific to Linux distro build
> Maybe try on a vm?

Im not using linux. I am using win 10 so It’s not a linux only problem

**Comment by mauro-balades** [comment]
do you have any antivirus that could be accusing zen of something?

**Comment by vanishLLC** [comment]
@mauro-balades I only have Defender running in the background

**Comment by mauro-balades** [comment]
If you add zen as an exception, does it still happen?

**Comment by LifeAO** [comment]
OS: Arch Linux x86_64
Kernel: Linux 6.10.7-1-cachyos
APU: Intel Core i3-2367M
Zen Browser Version: 1.0.0-a.37 (Flatpak)
Using Betterfox: Yes (user.js)
Tested with Firefox: Yes, is working

I've got a similar issue, but more so just using Discord Voice calling.
Attempting to call and send audio output works normal, yet receiving audio crashes the tab. Browser's fine.

Terminal output running `flatpak run io.github.zen_browser.zen`:
```
[Parent 2, Main Thread] WARNING: Failed to enumerate devices of org.freedesktop.UPower: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
: 'glib warning', file /home/runner/work/desktop/desktop/engine/toolkit/xre/nsSigHandlers.cpp:187

** (zen-alpha:2): WARNING **: 00:47:07.866: Failed to enumerate devices of org.freedesktop.UPower: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown

[Parent 2, IPC I/O Parent] WARNING: process 119 exited on signal 11: file /home/runner/work/desktop/desktop/engine/ipc/chromium/src/base/process_util_posix.cc:335
```

Notably, it's often the `process_util_posix.cc:335` SIGSEGV that consistently pops up when the tab is refreshed.
**To reproduce**: Open Discord tab, go to Settings - Voice & Video - Mic Test, then "Let's Check".

I've tried testing WebRTC via [gum_test](https://mozilla.github.io/webrtc-landing/gum_test.html) and no issues there.
Tested YouTube, working fine aside from waiting to get the finished VA-API fix for HW Decode; no crash.
ChatGPT, with a prompt of generating long answers with odd formatting, characters, and emojis; all worked.
GitHub, as per typing this comment, has not crashed so far.

**Comment by mauro-balades** [comment]
`signal 11` is a `SIGSEGV`.. but anyways

It *may* be fixed by https://github.com/zen-browser/desktop/pull/1282 but the fix hasnt been released... Ill change it for version 38 and let's see if it worked 👍🏽

**Comment by LifeAO** [comment]
Oh, sorry. I did mean signal 11 as SIGSEGV, but how I placed it prob confused it with the file. My bad.

I forgot I initially tried `MOZ_LOG="FFmpegVideo:5`, but gave no output for the Discord issue.
Still, will patiently wait for the next release to see if it persists.
As for YT, I saw the pull and am eager to see it arrive! 👌
