### ISSUE TITLE
Request - Add shortcut to copy the URL

### ISSUE THREAD

**Issue by mmenendezg** [zen-browser/desktop#1201]
### Captchas

- [x] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

I think it would be useful to have a shortcut that allows us to directly copy the URL as in **Arc** or **Orion**. In those browsers the keyboard shortcut is `Cmd + Shift + C`.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.34 

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by Anthonyy232** [comment]
Maybe to add on to this, there could be an option for a copy URL button next to the link like in Arc? Of course, this would be optional and can be added in the customize toolbar section.

**Comment by astro648** [comment]
Requests should be made in discussions 
github.com/zen-browser/desktop/discussions

**Comment by NOCanoa** [comment]
⬆️
