### ISSUE TITLE
Right side margin for sidebar (if placed on right side) is missing

### ISSUE THREAD

**Issue by nbeerten** [zen-browser/desktop#1205]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The padding for the whole sidebar if placed on the right has disappeared, as well as the new tab button's left edge not being aligned with the active tab's left edge.
![ezgif-1-2841069ef1](https://github.com/user-attachments/assets/e3545220-02b3-4059-bad8-5e34ac1c9241)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.35

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
This should be fixed, thanks!
