### ISSUE TITLE
Tabs bar briefly flashes on opening new window

### ISSUE THREAD

**Issue by Doc-4** [zen-browser/desktop#1207]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

If you have the tab bar *not* in small mode and have browser compact mode enabled, opening a new window (not tab) results in the tab bar flashing quickly open and closed. This also happens in all other active windows at the same time. Switching the bar to small mode stops the bug.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.34

### What platform are you seeing the problem on?

Windows

**Comment by salamijason** [comment]
Hi, make sure this toggle is off:
![Image](https://github.com/user-attachments/assets/2d70ec87-a85b-410e-aa4a-4df6270674dc)
Please let us know if the issue is fixed.

**Comment by salamijason** [comment]
No response in 3 days. Will be closing this issue. Please reopen if you are still facing the issue.
