### ISSUE TITLE
Zen Sidebar broken if too many tab opened on the same time

### ISSUE THREAD

**Issue by ArmourG2** [zen-browser/desktop#1209]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When too many tabs are open, the lower functions disappear. 
This issue wasn't present in the previous version (1.0.0-a.34).  
_Note: This occurred in the portable version, so I can't confirm if it's exclusive to it._

https://github.com/user-attachments/assets/790e17b4-4613-46ff-be5f-e4fa4b579f66

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.35

### What platform are you seeing the problem on?

Windows

**Comment by supersketchy** [comment]
Have the same issue on Windows 11

**Comment by slrgt** [comment]
I have the same issue 
![zen_GAUtTuqP0y](https://github.com/user-attachments/assets/a339c4e8-642d-4b06-b5dd-8583dd5b2889)

**Comment by TheLouisXD** [comment]
x3, same issue on windows 11

**Comment by Kyziq** [comment]
Same issue here for the sidebar problem

**Comment by umarhamzy** [comment]
Have the same issue, and notice how the **new tab button is at the top, instead of being at the bottom of previous tab**.

**Comment by CatCubed** [comment]
Same thing happening on Linux, hopefully it'll get fixed soon

**Comment by Shyboy-101** [comment]
> Have the same issue, and notice how the **new tab button is at the top, instead of being at the bottom of previous tab**.
I think that's a better design on purpose,'cause ppl always need a fixed button to add new tabs from anywhere

**Comment by amjd** [comment]
More details on this: Facing a similar issue and it's not just limited to the tabs sidebar. Not able to scroll to the bottom of some websites either, such as WhatsApp web (the message box in a conversation is hidden) and Google Meet (the controls for mic, video, etc. are hidden). Even in GitHub issues, I can't see the entire comment text box and buttons are completely hidden.

**Comment by sudanchapagain** [comment]
+1

**Comment by umarhamzy** [comment]
> Have the same issue, and notice how the **new tab button is at the top, instead of being at the bottom of previous tab**.
> The same issue.BTW I think that's a better design **on purpose**,'cause ppl always need a fixed button to add new tabs from anywhere

I get what you're coming from, but I'm used to the traditional new tab button being below my tabs (or to the right in vertical layout). Would like someone to write a plugin that restores its behaviour and also make it so that it's a small button that doesn't span the entire width of the sidebar

**Comment by mauro-balades** [comment]
This has been fixed... ill release later today
