### ISSUE TITLE
In Mac.Os running 1.0.0-a.35 (64-bit)  Somona 14.6.1 (macosx) Have an issue with partially hidden address bar.

### ISSUE THREAD

**Issue by odinigella** [zen-browser/desktop#1210]
### Captchas

- [ ] I have read the instructions.
- [ ] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

![Screenshot 2024-09-04 at 10 52 06](https://github.com/user-attachments/assets/1a93c314-dbcf-4c70-81d3-5632d7453237)
It is a minor issue I have put up since install of this very good browser. But I cannot skin it, theme it away.
Tried searching for address bar related bugs. Forgive me if my error. cheers.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.35 (64-bit) 

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by NOCanoa** [comment]
Does it also happen on a new profile?

**Comment by odinigella** [comment]
Hi no, and I was able to find the reason after that. It was from the store a bookmarks addon. removing the add on / extension all back to normal. Sorry feel like a dunce. Cheers for the support. Another contribution on its way from my end. Thanks again.
Nigel

Nigel
***@***.***

Når sandhed og retfærdighed er forskellige fra, hvad der er lov, bedre er det at følge sandhed og retfærdighed.Bandamanna Saga

c.6When truth and fairness are different from what is law, better it is to follow truth and fairness.

Bandamanna Saga c.6

[image]

Disclaimer:This email and any attachments may contain privileged or confidential information and may be protected by copyright. You must not use or disclose them other than for the purposes for which they were supplied. The privilege or confidentiality attached to this message and attachments is not waived by reason of mistaken delivery to you. If you are not the intended recipient, you must not use, disclose, retain, forward or reproduce this message or any attachments. If you receive this message in error, please notify by return email and destroy and delete all copies.

Whilst I have virus scanning software and a wealth of other security measures and devices on my computers I do not represent that this communication (including any files attached) is free from computer viruses or other faults or defects. I am therefore not to be considered liable to you or to any other person for loss and damage (including direct, consequential or economic loss or damage) however caused and whether by negligence or otherwise which may result directly or indirectly from the receipt or use of this communication or any files attached to this communication. It is the responsibility of the person opening any files attached to this communication to scan those files for computer viruses.

Sent with [Proton Mail](https://proton.me/) secure email.
