### ISSUE TITLE
How do I update the Zen browser on Linux?

### ISSUE THREAD

**Issue by kamafozilov** [zen-browser/desktop#1217]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I installed the browser through Flathub, but the updates there are 13 days old. On GitHub, the changes are much more recent. Either you need to update the versions in your store, or please tell me how to update it myself.
![image](https://github.com/user-attachments/assets/c19b209f-6db3-4de3-ab73-34914dd7b1a0)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.28

### What platform are you seeing the problem on?

Linux

**Comment by m2x07** [comment]
download the latest .flatpakref file from the download page. That way i'm running 1.0.0-a.32, while the version on flathub shows 1.0.0-a.28

**Comment by kamafozilov** [comment]
> download the latest .flatpakref file from the download page. That way i'm running 1.0.0-a.32, while the version on flathub shows 1.0.0-a.28

should I uninstall first?
![image](https://github.com/user-attachments/assets/456cc3cb-e1cb-4319-bb2c-6a60253c508b)

**Comment by kamafozilov** [comment]
> download the latest .flatpakref file from the download page. That way i'm running 1.0.0-a.32, while the version on flathub shows 1.0.0-a.28

Your way doesn't work. I tried installing it through flatpakref after disabling the Zen browser, but it still downloads the current version from Flathub, so the version doesn't change. You can verify this using 'flatpak list'. 

The only solution seems to be using AppImage :(

![image](https://github.com/user-attachments/assets/e54ad142-c310-490d-9a89-e8a408c38e2f)

**Comment by NOCanoa** [comment]
Version on store is incorrect, wen a36 comes out this should all be automated !

**Comment by NOCanoa** [comment]
@kamafozilov  check in browser, hamburger menu -> Help -> about zen

**Comment by ulrichSchreiner** [comment]
Sorry, but there is no new version on flathub; yes there are newer ones thant a28, but all the PR's for the latest flathub versions stuck with build failures:

https://github.com/flathub/io.github.zen_browser.zen/pulls

**Comment by m2x07** [comment]
> > download the latest .flatpakref file from the download page. That way i'm running 1.0.0-a.32, while the version on flathub shows 1.0.0-a.28
> 
> Your way doesn't work. I tried installing it through flatpakref after uninstalling the Zen browser, but it still downloads the current version from Flathub, so the version doesn't change. You can verify this using 'flatpak list'.
> 
> The only solution seems to be using AppImage :(
> 
> ![image](https://private-user-images.githubusercontent.com/149860188/364338985-e54ad142-c310-490d-9a89-e8a408c38e2f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1NjYzODcsIm5iZiI6MTcyNTU2NjA4NywicGF0aCI6Ii8xNDk4NjAxODgvMzY0MzM4OTg1LWU1NGFkMTQyLWMzMTAtNDkwZC05YTg5LWU4YTQwOGMzOGUyZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNVQxOTU0NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNTM2ZTMwMjE4MTgxZTM2NTJlNmRkYmM3YWM0ODk1ZGYzZmYwY2I2YjNiZjIwZDU0ZGUyNzI2MWEzOWIwNTE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XR_bETGm4bk0yfB4TfD7DWxLz9T7EHTRLw7J5HZARBw)

Just to let you know, I rechecked. For me, `flatpak list` shows version `1.0.0-a.28`, but `flatpak run io.github.zen_browser.zen --version` shows `1.0.0-a.32`.
checking from browser, hamburger menu -> Help -> about zen also shows `1.0.0-a.32`. Not sure whats going on and what version i'm actually running. Installed by downloading the latest .flatpakref file from the site

**Comment by migtorr** [comment]
> Version on store is incorrect, wen a36 comes out this should all be automated !

We are at version a37 and still no flathub update
![Screenshot from 2024-09-06 18-15-37](https://github.com/user-attachments/assets/516065b3-a8aa-4358-8956-572541a577c0)

**Comment by NOCanoa** [comment]
@migtorr yes just cheked and flathub still on a.32, cheff will have a look over the weekend and see why its not working : /
