### ISSUE TITLE
Authentication on sites via a certificate (such as a Smart Card) does not work on Linux

### ISSUE THREAD

**Issue by derTuca** [zen-browser/desktop#1218]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Some of my country's government sites require authentication via a USB token (a Smart Card essentially) with a certificate). When I clicked login, I expected a prompt to choose my certificate, as I get on Firefox. Instead, I get redirected to the error page of no certificate provided.

The URL in question can be accessed by going [here](https://www.anaf.ro/anaf/internet/ANAF/servicii_online/inregistrare_utilizatori/!ut/p/a1/jZBNb8IwDIZ_C4ceqU0rKrZbB4IWDQnYECWXKu3SNBoklRs2jV-_lNNAG8ySJdt6Xn8BgwyY5h9KcquM5vsuZ1GeDJIoCUbBfBY_IEaI68lk6iIcOGD3E8BkhbgaPqXr4WzpgOh_evzDYrynn18CV_Nfw25AQIvxQgJruK37SlcGslSTkKq1xEnkjaDWcC3ySp1UKWAL7F7X20B39hm4cZdbXO5Ncf7xLtZFOHIbkqgECfKP5Mq1tU376KGHb8fyvXNp_NIcPPxNUpvWQnZJQnPYZKfn6iXts-LrM-59A8ilKQw!/dl5/d5/L2dBISEvZ0FBIS9nQSEh/) and clicking on "Autentificare certificat" at the top right.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.32

### What platform are you seeing the problem on?

Linux

**Comment by NOCanoa** [comment]
Are u sing flatpak version?
If so did u also test the flatpak version of Firefox?

**Comment by derTuca** [comment]
You are right, I was not testing against flatpak Firefox. Closing this, sorry.
