### ISSUE TITLE
Links always opening in default profile

### ISSUE THREAD

**Issue by kristijanribaric** [zen-browser/desktop#1221]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Clicking on an external link in another app always opens it in default profile, even if that profile isn't currently open.

Link should be opened in the last used profile.

Might be tied to #1009 

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.35

### What platform are you seeing the problem on?

Windows

**Comment by arunoruto** [comment]
I experience the same issue. I mostly notice it when I try to open links in Thunderbird, and a new Zen window opens up asking me to set it up. I am currently running the flatpack version `1.0.0-a.32`.

**Comment by smgoller** [comment]
I'm experiencing the same issue on MacOS. This is on version `1.0.0-a.37`.  Using the command-line, `open https://zen-browser.app` results in a new window opening with the default profile.

**Comment by NOCanoa** [comment]
That is expected behavior from ff, it always launches the links in the Profile u selected as default.
U can chose witch one is the default here(url): about:profiles 
For enhancement pls use Discussions section.
