### ISSUE TITLE
Closing any of the "pinned tab" through [CTRL+W] doesn't actually closes them, just removes from displaying it.

### ISSUE THREAD

**Issue by m2x07** [zen-browser/desktop#1222]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Pinned tabs are great. However, there is no way to properly close a pinned tab. Pressing `Ctrl+W` on keyboard makes it look like the tab has been closed, but is actually active and is just not displayed on the screen. Closing from the context menu by right clicking the tab does close the tab BUT ALSO UNPINS THE TAB. This way the tab remains active, and occupies the extra resources for the tab.

This issue can be recreated by pinning youtube.com, playing a video and then closing the tab.
It would be great if pinned tabs can be properly closed without UN-pinning them.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.32

### What platform are you seeing the problem on?

Linux

**Comment by JLBlk** [comment]
What you want, is to unload pinned tabs right? So stop them from taking up resources, but still have them pinned. There is a firefox extension to achieve that behavior if you dont want to wait for it to be implemented natively (if it ever will) 
https://addons.mozilla.org/en-US/firefox/addon/unload-tabs/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search

**Comment by mauro-balades** [comment]
This is a firefox feature, idk why they chose to do it that way,,,,

**Comment by m2x07** [comment]
> What you want, is to unload pinned tabs right? So stop them from taking up resources, but still have them pinned. There is a firefox extension to achieve that behavior if you dont want to wait for it to be implemented natively (if it ever will) https://addons.mozilla.org/en-US/firefox/addon/unload-tabs/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search

thanks, i'll check it out
