### ISSUE TITLE
Localisations are not working since 1.0.0-a.35

### ISSUE THREAD

**Issue by nazmiyigitefe** [zen-browser/desktop#1223]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

All localised texts are now English after the 1.0.0-a.35 update, on both of my MacOS and Windows devices.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.35

### What platform are you seeing the problem on?

Windows

**Comment by nazmiyigitefe** [comment]
![Ekran görüntüsü 2024-09-04 095227](https://github.com/user-attachments/assets/98d6f467-4d88-49d8-a36f-ec947562835c)

**Comment by fettpl** [comment]
The issue seems to be related to crowdin.com translation service:

<img width="370" alt="Zrzut ekranu 2024-09-4 o 12 03 20" src="https://github.com/user-attachments/assets/1eac4dd9-b6d8-48e5-87b3-10487aab9687">

**Comment by finduschicken** [comment]
The same thing's happening to me, I have the default language on Italian but it only displays in English

**Comment by Somnia1337** [comment]
Same, I stuck for a while and realized it's not a theme/extension thing, it's the update to a.35 that caused the problem.

**Comment by Goojoe** [comment]
I have the same problem

**Comment by Shyboy-101** [comment]
**### +1**

**Comment by nazmiyigitefe** [comment]
This issue has fixed by 1.0.0-a.37, but the browser still not fully localised. Like create tabs, or some other options are still English.

**Comment by mauro-balades** [comment]
Fully localization is yet to be supported, glad it got fixed on 37, thanks!

**Comment by realpixelcode** [comment]
> This issue has fixed by 1.0.0-a.37, but the browser still not fully localised. Like create tabs, or some other options are still English.

For me, the issue persists in `1.0.0-a.39`. 🤔

![image](https://github.com/user-attachments/assets/40bc6995-fd45-458b-a9a4-1c470266595d)

**Comment by Somnia1337** [comment]
@realpixelcode Yeah it was fixed in .37, but appears to be a problem **again** in .39

**Comment by nazmiyigitefe** [comment]
Yes, they are English again with .39.

**Comment by mauro-balades** [comment]
Yeah, itll be fixed in version 40

**Comment by realpixelcode** [comment]
> Yeah, itll be fixed in version 40

It is indeed fixed now :)
