### ISSUE TITLE
New tab button hover style in compact density

### ISSUE THREAD

**Issue by dayblox** [zen-browser/desktop#1224]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When in compact density (Customize Toolbar > Density > Compact) the NewTab button has broken hover styles.
![image](https://github.com/user-attachments/assets/093f2bb8-ad85-4442-b1b2-8fe5e60e50ce)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.35 (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by dror-g** [comment]
Same on Linux (ubuntu, i3wm).
