### ISSUE TITLE
Can't dispaly anyother language in interface except English, after updating to Version 1.0.0-a.35

### ISSUE THREAD

**Issue by Shyboy-101** [zen-browser/desktop#1226]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Bug Description
After updating from version 1.0.0-a.34 to a.35, the application interface no longer changes language when switching to another language. The interface remains in English.

Steps to Reproduce

    Update the application to version a.35.
    Go to the settings and switch the language to one other than English.
    Observe that the interface does not change to the selected language.

Expected Behavior
The application should display the interface in the selected language after changing the language settings.

Actual Result
The application interface remains in English regardless of the selected language.

Environment Information

    Previous Version: 1.0.0-a.34 (where everything worked correctly)
    Current Version: a.35
    Operating System:Windows 11

Screenshots
![image](https://github.com/user-attachments/assets/0bbd9509-c9f7-4fdf-ba1e-6623d1453aa3)
    Issue in Main Application:
![image](https://github.com/user-attachments/assets/1697e431-d6b9-4677-b8bd-4f411576cd90)
Issue in Language Switching:
Language Display in Bookmark GUI:
![image](https://github.com/user-attachments/assets/4e89f68b-6d0e-4299-a5d4-b2edd7d0cdf7)
Additional Notes
Interestingly, the language seems to be correctly displayed in the bookmark GUI, suggesting that the language switching functionality may be partially working but not fully implemented throughout the application.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.35

### What platform are you seeing the problem on?

Windows

**Comment by Shyboy-101** [comment]
comment if you have the same issue or not to clarify whether this problem exists solely on my device.

**Comment by ExistentialAlex** [comment]
I think this issue is also covering the same thing: https://github.com/zen-browser/desktop/issues/1223
