### ISSUE TITLE
"Whats new" on About Zen doesnt link to update logs

### ISSUE THREAD

**Issue by flmalte** [zen-browser/desktop#1227]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

"The whats new" button links to the landingpage https://zen-browser.app/ instead of https://zen-browser.app/release-notes or https://github.com/zen-browser/desktop/releases

<img width="730" alt="Screenshot 2024-09-04 at 11 22 25" src="https://github.com/user-attachments/assets/f16302a0-36dc-4ce2-9fe3-a0df4b9f86f3">

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.35

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by mauro-balades** [comment]
Ale, fixed for the next relwase
