### ISSUE TITLE
Pinned tabs margins to left/right are biger than to the top/bottom

### ISSUE THREAD

**Issue by JLBlk** [zen-browser/desktop#1229]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![image](https://github.com/user-attachments/assets/9bb62632-6f1c-47e2-a375-47f2c1c49ccf)
 
 The margins for the pinned tabs aren't consistent -> to the left/right a lot bigger than to the top/bottom (demonstrated in the pic by multiselecting pinned tabs).
 (No themes or extensions installed)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.35

### What platform are you seeing the problem on?

Windows

**Comment by Shyboy-101** [comment]
or may let me start a new issue

**Comment by JLBlk** [comment]
I don't know what you exactly mean. The 'pill button' setting doesnt have anything to do with the pinned tabs style. Both our images show the same layout/style. (Or are you referring to my SuperPins theme, if so it's broken with the latest a35 update)

**Comment by Shyboy-101** [comment]
Got it.Good issue for design btw.

**Comment by mauro-balades** [comment]
This is fixed for the next release!
