### ISSUE TITLE
Dynamic Theme doesn't apply 

### ISSUE THREAD

**Issue by theunknownsky** [zen-browser/desktop#123]
### What happened?

![image](https://github.com/user-attachments/assets/cbe67cf4-bac4-4db3-992f-843d69f2ac9d)

I tried to use the Dark Space Dynamic Theme but it's not working or the theme is not applied in the browser.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.8

### Severity impact

Medium

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
This is expected, firefox themes are 100%  supported yet, we are working on it 👍🏽
