### ISSUE TITLE
Tabs on the right doesn't work 

### ISSUE THREAD

**Issue by bengalbroy** [zen-browser/desktop#1231]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

On macOS the 'tabs on the right' button doesn't do anything when clicked. 

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.35

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by hannylicious** [comment]
I am also experiencing this issue. MacOS - Intel

**Comment by sizhky** [comment]
I'm experiencing this on MacOS M3

**Comment by salamijason** [comment]
Right sidebar has been fixed in the past few updates, could you check if you still get this issue in the latest version? 1.0.1-a.14

**Comment by hannylicious** [comment]
Seems to be working for me as expected! Huge thanks to the devs for hitting this up so quickly. Thank you.
