### ISSUE TITLE
Websites opened in sidepanel dont use extensions 

### ISSUE THREAD

**Issue by slrgt** [zen-browser/desktop#1234]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The websites opened in the side panel srent ysing the extensions so i cant make them dark mode with Dark Reader or use my password manager in there

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0 a.35

### What platform are you seeing the problem on?

Windows

**Comment by plandem** [comment]
confirm, 1Password is not working there as well

**Comment by mauro-balades** [comment]
Unfortunately, webpanels dont run extensions mainly because they arent attached to any tab... ill close this for now but so you know, im still looking into it

**Comment by default-student** [comment]
this becomes a problem when using adblock, as it kinda works a lil bit?
for example youtube music wont load in a webpanel when i have ublock origin installed
