### ISSUE TITLE
UI Overlap Issue: Browser UI Descends Below Windows Navbar When Multiple Tabs Are Opened

### ISSUE THREAD

**Issue by Ahmedbhf** [zen-browser/desktop#1235]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When opening multiple tabs in the Zen browser, the UI behaves unexpectedly, causing the browser window to move downwards. As a result, the browser UI, including tools and website content, becomes partially hidden below the Windows navbar. This also causes some website content to be cut off or not fully visible. The issue disrupts usability, as key browser tools and parts of websites are inaccessible.
![image](https://github.com/user-attachments/assets/1afbda0f-e7f0-4ea4-b785-8e21035e89c7)
![image](https://github.com/user-attachments/assets/5c1aacfa-2f99-44ed-8fa4-c2d184a3dbe9)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.35

### What platform are you seeing the problem on?

Windows

**Comment by badjuice** [comment]
This is a byproduct of the previous change made on the tabs sidebar (adding an anchored new tab button). The `+` button is pushing the other buttons, tabs and some page content further down.

Also, on this regard @mauro-balades, wouldn't it make more sense to have the `+` button on the bottom instead of the top of the tabs sidebar? I see that this was a recent change too since it used to be on the bottom before this last update.

**Comment by mauro-balades** [comment]
This is fixed, I'll release today

**Comment by mauro-balades** [comment]
> Also, on this regard @mauro-balades, wouldn't it make more sense to have the `+` button on the bottom instead of the top of the tabs sidebar?

just following firefox's design

**Comment by badjuice** [comment]
> > Also, on this regard @mauro-balades, wouldn't it make more sense to have the `+` button on the bottom instead of the top of the tabs sidebar?
> 
> just following firefox's design

Alright. Can it be made an option to pick where it is positioned? I am so used to it being on the bottom from my experience with other browsers and extensions. 😅

> This is fixed, I'll release today

Thanks <3
