### ISSUE TITLE
Pinned tabs container height

### ISSUE THREAD

**Issue by paulwyszynski** [zen-browser/desktop#1236]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

After last update: Version 1.0.0-a.35 (64-bit) pinned tabs container introduces a vertical scrollbar for pinned tabs.
Is it possible to set the height to remove the scrollbar? See screenshot.

![Screenshot 2024-09-04 at 6 26 06 PM](https://github.com/user-attachments/assets/9b3c6a6d-cc64-4e11-84ab-3f858ef3e7bd)
 

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.35 (64-bit)

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by NocFA** [comment]
Yes, I noticed this today on the new release, very ugly, reverted back to the last release, hoping this isn't an active design choice.

**Comment by xmaxcooking** [comment]
here to upvote this. same experience. pinned tabs container has an unnecessary max height in compact mode.

**Comment by xmaxcooking** [comment]
> Yes, I noticed this today on the new release, very ugly, reverted back to the last release, hoping this isn't an active design choice.

if it.. please.. at least 50% of the height.

**Comment by JLBlk** [comment]
U can disable it with css
```
#vertical-pinned-tabs-container {
      max-height: none !important;
}
```

**Comment by mauro-balades** [comment]
> Yes, I noticed this today on the new release, very ugly, reverted back to the last release, hoping this isn't an active design choice.

It was... But ig ill remove it for the next release...

**Comment by paulwyszynski** [comment]
Thanks so much!
