### ISSUE TITLE
Facebook Messenger crashing in sidebar

### ISSUE THREAD

**Issue by Minekokos** [zen-browser/desktop#1238]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Facebook Messenger crashes when updating site (after any kind of button interaction) - it sends me back to *welcome* page of messenger - only happens in sidebar, otherwise it works fine

![Zen_issue](https://github.com/user-attachments/assets/9c917226-df92-407e-a5e0-223bd98d27bb)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.35

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
Could you please translate?

**Comment by mauro-balades** [comment]
You seem to have the "Mobile User Agent" enabled... Maybe try to disable it, and if it doesnt work, we'll reopen... although im 99% sure it's that

**Comment by Minekokos** [comment]
Yes, mobile user agent was on and that was the problem, thanks for helping
me.

st 4. 9. 2024 v 23:56 odesílatel mauro 🤙 ***@***.***> napsal:
