### ISSUE TITLE
A part of the tab list and the corner border is showing/clipping in Fullscreen

### ISSUE THREAD

**Issue by Dadangdut33** [zen-browser/desktop#124]
### What happened?

Tt seems that when you fullscreen a video the corner and tab list clips into it. 

Here is a screenshot:
![image](https://github.com/user-attachments/assets/e314f8dd-b249-4489-b6b0-4d6f2aa9eb03)
![image](https://github.com/user-attachments/assets/b26dd117-00ea-4a8f-a694-c22cb7ada1dd)

It might not look that clear in the screenshot but you should be able to reproduce it easily by watching a video on youtube in fullscreen. You can see in the left part there is the tab list sticking out, and in the bottom and top part of the right section you can see the corner thing.

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.10 (64-bit)

### Severity impact

Medium

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
For these kinds of visual bugs,.please use the low priority (used for visual bugs). Thanks, I'll work on it now

**Comment by Dadangdut33** [comment]
sorry, i didn't notice that the severity description was in the issue page

**Comment by mauro-balades** [comment]
This will be fixed for the next release, thanks!

**Comment by Dadangdut33** [comment]
Thank you very much for the fix! 

The tab list on the left seems to be fixed but when you are fullscreen you can still see that the content got cut because of the round corner of the page.

(just like in the screenshot previously)
![](https://private-user-images.githubusercontent.com/57717531/354112432-b26dd117-00ea-4a8f-a694-c22cb7ada1dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2NTkwNzMsIm5iZiI6MTcyMjY1ODc3MywicGF0aCI6Ii81NzcxNzUzMS8zNTQxMTI0MzItYjI2ZGQxMTctMDBlYS00YThmLWE2OTQtYzIyY2I3YWRhMWRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAzVDA0MTkzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyN2FlZDQwMGNiOWNjODY3MmQxZDE3ODg3YmExZTU1NjdjYzg1MTBlMGIxYTAyMDYwZWM4YzZhZTY0MTRiMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IluSfudD4e9yOCQN6ZF4uHtSUkKkze-mgz_-Wgk7qw0)


Is it possible to fix that?

**Comment by mauro-balades** [comment]
yeah, ill work on it too 👍🏽
