### ISSUE TITLE
“Zen Browser.app” is damaged and can’t be opened. You should eject the disk image.

### ISSUE THREAD

**Issue by trendespresso** [zen-browser/desktop#1245]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Download Apple Silicon DMG. Attempt to open Zen. Cannot. Please advise :)

<img width="544" alt="Screenshot 2024-09-05 at 01 34 14" src="https://github.com/user-attachments/assets/74935789-fbcc-4ec3-8b7d-33181bfb03df">

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.35

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by 3kh0** [comment]
Please follow this guide on their documentation website and see if you run into the same issue.

https://docs.zen-browser.app/guides/install-macos

**Comment by trendespresso** [comment]
@3kh0 That fixed it for me! Thank you very much!

Perhaps a link to such should be visible either on the zen-browser.app website or on this repo somewhere? Would never have found that otherwise. Cheers

**Comment by kth8** [comment]
@trendespresso that guide is outdated, you should install Zen Browser using [homebrew](https://github.com/zen-browser/desktop?tab=readme-ov-file#installation) which automatically disables gatekeeper via https://github.com/zen-browser/desktop/blob/main/Casks/zen-browser.rb#L20

**Comment by trendespresso** [comment]
@kth8 I don't have homebrew installed since I've had way too much malware take advantage of its kernel access.

**Comment by NOCanoa** [comment]
App is signed, so no need for all the workarounds 🚀🚀
