### ISSUE TITLE
New tab position inconsistent across compact sidebar and expanded sidebar

### ISSUE THREAD

**Issue by umarhamzy** [zen-browser/desktop#1246]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The new tab button is located below the pins and above the pins separator line in expanded mode, whereas it's located below the separator line in compact mode.
![image](https://github.com/user-attachments/assets/03d38b7a-e9e4-42c6-8d4c-47439bfa0993)
_New tab button appears below the line in compact sidebar._

![image](https://github.com/user-attachments/assets/d95b7b3f-0aac-479f-9078-ac040dd94b04)
_New tab button appears above the line in expanded sidebar._

**Related Issue**: I also just noticed another issue related to tab position, this happened when I switched to a different workspace to write this issue.
![image](https://github.com/user-attachments/assets/91fdbffd-3612-4243-97e5-437ff61ca5a3)
The tab appears glued to the separator line above. However, it seems fine when I switch back to my other workspace. As seen in the second screenshot.

**Suggestion**: Put the new tab button below, the last tab like other browsers, and make it so that upon closing the last tab, it creates a new tab, instead of jumping to last pinned tab.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.37

### What platform are you seeing the problem on?

Windows

**Comment by chriskirknielsen** [comment]
Seconded, having the New Tab button at the top in Compact mode is very confusing for me, and it wasn't like this until recently. Can we at least have it as an option in the Look & Feel settings? Thanks!
