### ISSUE TITLE
Small sidebar display bug

### ISSUE THREAD

**Issue by Yasunaii** [zen-browser/desktop#125]
### What happened?

If the sidebar is minimized, a message appears incorrectly when Zen starts up.

I didn't read the message but it seems to me that it's the pop-up that indicates that the browser will reopen with the tabs from the previous session.

![image](https://github.com/user-attachments/assets/ff4fe4c5-f543-4fee-b859-16eea4f9bafb)

### Version

Ver 1.0.0-a.10 (64bit)

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
Fixed for the next release!
