### ISSUE TITLE
Weird rounded-edge effect when zen is in windowed mode in Gnome

### ISSUE THREAD

**Issue by minegameYTB** [zen-browser/desktop#1254]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

when zen browser is set to window mode, there's a rounded-edge effect that looks badly rendered on gnome.
![Capture d’écran du 2024-09-05 12-56-43](https://github.com/user-attachments/assets/d42560cb-e0f0-4842-b0f9-f362e77a1464)

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a37

### What platform are you seeing the problem on?

Linux

**Comment by daudix** [comment]
Same for bottom corners with `widget.gtk.rounded-bottom-corners.enabled` set to `true`.

![image](https://github.com/user-attachments/assets/cd39f331-18ca-4093-bd70-8493ffb8e460)

**Comment by mauro-balades** [comment]
This is fixed for the next release, thanks!
