### ISSUE TITLE
Sidebar tabs get shrinked when closing multiple tab

### ISSUE THREAD

**Issue by ilhamprabuzakys** [zen-browser/desktop#1257]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Sidebar tabs get  shrinked when closing multiple tab.

The problem occur in both of compact and normal mode.

Compact Mode :
![Thursday_19-15-38_2024-09-05](https://github.com/user-attachments/assets/b93d1491-46de-4a67-abd7-fcf0520312e9)

Normal Mode :
![Thursday_19-16-00_2024-09-05](https://github.com/user-attachments/assets/920fec93-274b-44db-a7cf-6a41cf293a17)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.37 (64-bit)

### What platform are you seeing the problem on?

Linux

**Comment by MegadronA03** [comment]
https://github.com/user-attachments/assets/04bf1918-e3ba-4791-9639-41f5895d7326

for me it usually happens when I close tab with a mouse wheel

**Comment by NOCanoa** [comment]
Any themes/extension that could influence this?

**Comment by spectrum705** [comment]
not sure, but i am using Catppuccin (v1.0.0) theme

**Comment by NOCanoa** [comment]
if u make a new profile does it also happen?

**Comment by MegadronA03** [comment]
> if u make a new profile does it also happen?

sometimes, currently bug not appears anymore. (edit: I thought that was different issue)
