### ISSUE TITLE
tab title padding changes with change in number of tabs

### ISSUE THREAD

**Issue by spectrum705** [zen-browser/desktop#1258]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

when i close the many new tabs the other tab's titles padding change. 

https://github.com/user-attachments/assets/68e681b1-22b8-46f4-94aa-a5b942d65b40

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

a 37

### What platform are you seeing the problem on?

Windows

**Comment by NOCanoa** [comment]
Any themes/extension that could influence this?

**Comment by NOCanoa** [comment]
https://github.com/zen-browser/desktop/issues/1257 continue here
