### ISSUE TITLE
Remember sidebar width on app relaunch

### ISSUE THREAD

**Issue by bdbch** [zen-browser/desktop#126]
First of – great work not only on Zen but also on Surfer. It's fascinating how suddenly Firefox has some kind of renaissance with indie browsers. Keep it coming.

**Is your feature request related to a problem? Please describe.**
Currently whenever you close the browser and restart, the sidebar's width is reset to the minimum width. While I find the collapsed sidebar nice and minimal I kinda miss a bit more info about a tab and prefer the "Arc" look.

However since the sidebar width resets everytime, I have to always reapply the size of the sidebar. Would be nice if this could somehow be stored.

**Describe the solution you'd like**
Store the sidebar width on change so it can be restored to that after collapse or an app restart.

**Describe alternatives you've considered**
No alternatives

**Additional context**
No additional context

**Comment by mauro-balades** [comment]
This isn't as easy as I thought it would be 😅.

It will be done for alpha.12 but not for .11 unfortunately, thanks for the suggestion!

**Comment by bdbch** [comment]
All good. Any insights on what you tried yet? I'll try to setup the project again later on my Win PC or Macbook and could also look into it.

**Comment by mauro-balades** [comment]
It turned out to be quite an easy fix!

https://github.com/zen-browser/desktop/commit/d60d4e888afdfaf5b203d9e25cb6a2b0121a1e94

This will be applied for the next release!

**Comment by bdbch** [comment]
Great work!
