### ISSUE TITLE
Tab bar in compact mode restricts use of forward/back button when visible

### ISSUE THREAD

**Issue by BionicBlade0** [zen-browser/desktop#1262]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Tab bar (when on left side (default location)) in compact mode restricts use of forward/back button (on top of the tab bar) when visible.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.37 (64-bit

### What platform are you seeing the problem on?

Windows

**Comment by Thanaen** [comment]
![zen-compact-hover-issue-3](https://github.com/user-attachments/assets/5e9754b0-e7ec-43ec-aad1-184697e32e9a)

**Comment by mally8** [comment]
same issue as [#1143 ](https://github.com/zen-browser/desktop/issues/1143)

**Comment by BionicBlade0** [comment]
Should I close it?
