### ISSUE TITLE
Tabs bar regression

### ISSUE THREAD

**Issue by MyrikLD** [zen-browser/desktop#1264]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

After version 1.0.0-a.35 I have problems when scrolling quickly using mouse wheel (MX Master 3). On scroll tab bar remains in place until the scrolling speed decreases.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.35

### What platform are you seeing the problem on?

Linux

**Comment by Buri** [comment]
I do have the same issue, 1.0.0-a.37 @ Linux, using both mouse wheel and touchpad

**Comment by mauro-balades** [comment]
This should be fixed for the next release, please do let me know if it didnt work
