### ISSUE TITLE
Browser partially rendered when invoked from taskbar

### ISSUE THREAD

**Issue by wealstarr** [zen-browser/desktop#1266]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When browser is minimized and than invoked from the taskbar, a major part of the browser is just gray. When I click some links inside the browser, buttons on the toolbar, it instantly goes away.
![Fullscreen capture 04-09-2024 185611_censored](https://github.com/user-attachments/assets/7ea24a3e-dec6-4640-82f0-f84647d4f41b)

Please NOTE: the part that doesn't get rendered and only shows as blank gray, it's position and size changes everytime. Sometimes it's just on the bottob, sometime on the top right corner and mostly on the right side of the screen.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

a.35

### What platform are you seeing the problem on?

Windows

**Comment by wealstarr** [comment]
Any update on this ?

**Comment by NOCanoa** [comment]
haven't experienced it ( on windows), currently we doing the mac and windows license stuff, but we didn't forget u 😉

**Comment by wealstarr** [comment]
@NOCanoa Thank you for the response. I tried to live with it but it's very frequent. Especially effects the websites that run as apps, youtube, spotify, Telegram etc.

This is the only thing preventing me from switching completely from Mercury. I hope you have this on your to-do list. I would check out and test again when the new Zen release appears.

Thank you again and kind regards

**Comment by mauro-balades** [comment]
Could you send output from the terminal?

**Comment by salamijason** [comment]
Heylo, looks like this issue was posted a while back. Are you still getting these issues on the latest version? (a17 as of this comment)

If you are, please follow [these instructions](https://docs.zen-browser.app/guides/live-editing) and send the output from the console.

**Comment by salamijason** [comment]
No response in 3 days. Will be closing this issue. Please reopen if you are still facing the issue.
