### ISSUE TITLE
OpenH264 Video Codec not installing 

### ISSUE THREAD

**Issue by xAdvitya** [zen-browser/desktop#1269]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

stuck on "installed shortly" tried installing OpenH264 and related dependencies 
![image](https://github.com/user-attachments/assets/db5fdfee-fc28-436d-bffa-6cc9d2e4e796)

![image](https://github.com/user-attachments/assets/0acac494-de26-4cf3-8e1c-d453aeccf5d0)

firefox works just fine.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.28

### What platform are you seeing the problem on?

Linux

**Comment by NOCanoa** [comment]
can u provide a link so I can test?

**Comment by xAdvitya** [comment]
@NOCanoa link for ?

**Comment by NOCanoa** [comment]
The site u getting the error.

**Comment by xAdvitya** [comment]
linkedin, reddit and twitter 
I've tested it on these three, youtube works fine
