### ISSUE TITLE
Allow the sidebar to be wider

### ISSUE THREAD

**Issue by bdbch** [zen-browser/desktop#127]
**Is your feature request related to a problem? Please describe.**
It's weird to set a maximum width to the sidebar that is so small. On 2560 screen-width there's a lot of screen estate that could be used to show more information about a tab.

**Describe the solution you'd like**
Just add a few more pixels to the max-width of the sidebar.

**Describe alternatives you've considered**
No alternatives considered

**Additional context**
No additional context

**Comment by mauro-balades** [comment]
![Screenshot_20240802_164759](https://github.com/user-attachments/assets/9dae442e-1f6f-4f02-b5e7-b73789bb6bfa)

for the next release, this will be possible by changing this value in `about:config`!

**Comment by bdbch** [comment]
Awesome!
