### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by fe2-Nyxar** [zen-browser/desktop#1273]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I tried to log in with my Mozilla account but i got disconnected immediately after the login

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
What version are you on?

**Comment by fe2-Nyxar** [comment]
nvm it's working now for :D
