### ISSUE TITLE
Incorrect Tab Highlighted after closing a tab in split view

### ISSUE THREAD

**Issue by Hwks-9026** [zen-browser/desktop#1275]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

After opening a tab at the end of my list and putting it into a split view group, closing that tab will simply highlight the tab above it instead of the last tab in the group. This is disorienting because the highlighted tab is not even on the screen.

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0

### What platform are you seeing the problem on?

Linux

**Comment by NOCanoa** [comment]
Can u show some screenshots?

**Comment by mauro-balades** [comment]
Please provide a some more information and a proper version, im going to close this right now as no answer has been given
