### ISSUE TITLE
Sidebar video popout causes uncloseable black box

### ISSUE THREAD

**Issue by rexxDigital** [zen-browser/desktop#1283]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When clicking the "Pop out this video" button when using youtube in the sidebar all that gets created is a black box with the button elements but no video, this box cannot be closed without closing the browser

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.37

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
yeah, the sidebar's PIP function is still being worked on, this is a duplicate, but thanks!

**Comment by b-rhodes** [comment]
I couldn't find what ticket this was a duplicate of, so I'm commenting here.
It is worth noting that this is also present on Windows, however, I could close the grey window by right-clicking it and selecting close window.
