### ISSUE TITLE
Windows 11 - Zen can't create user after installation

### ISSUE THREAD

**Issue by ivanodapice** [zen-browser/desktop#1286]
### Captchas

- [X] I have read the instructions.
- [ ] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![photo_2024-09-06_16-27-36](https://github.com/user-attachments/assets/e8ba9d44-2195-4297-94b3-4027d1d6a486)
^ After installing zen alpha a.35 - optimized - setup wizard - standard
![photo_2024-09-06_16-27-39](https://github.com/user-attachments/assets/9373c951-2937-45af-92d4-e598f0d0b7e5)
^ this is the error 
![photo_2024-09-06_16-27-29](https://github.com/user-attachments/assets/8777edba-2d86-4dd9-ac52-8bfe3e1f7dee)
^ profile folder

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.35

### What platform are you seeing the problem on?

Windows

**Comment by NOCanoa** [comment]
![image](https://github.com/user-attachments/assets/3540d277-4042-4f4c-8aae-2831834fd8e6)
does this not work?

**Comment by mauro-balades** [comment]
Does it have the necessary permissions? Try running in administrative
