### ISSUE TITLE
Theme filter gets forgotten when you go back to the theme store

### ISSUE THREAD

**Issue by thibaultmol** [zen-browser/desktop#1288]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Currently if you filter for 'utility' for example, click on theme, then press the back button. it will have forgotten that you're filtering on 'utility'. This is quite confusing UX

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.32 

### What platform are you seeing the problem on?

Linux

**Comment by NOCanoa** [comment]
This is the desktop repo, so issues related to WWW pls [here](https://github.com/zen-browser/www)

**Comment by NOCanoa** [comment]
And I just tested it and works for me 🤷‍♂️

**Comment by thibaultmol** [comment]
Still repro on my end.
Can't you move the issue btw? https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository
