### ISSUE TITLE
Add shortcut to toggle the tabs sidebar

### ISSUE THREAD

**Issue by bdbch** [zen-browser/desktop#129]
**Is your feature request related to a problem? Please describe.**
Currently I think (didn't find a keyboard shortcut) I have to always click on the collapse button to toggle the sidebar. It would be nice if we could find a shortcut that is not conflicting with any other browser features. Arc went a pretty weird route there conflicting their shortcut with the Save shortcut. (Ctrl+S / Command+S on Mac)

**Describe the solution you'd like**
I'd like to see a new shortcut binding that can be customized which can be used to toggle the collapsed sidebar.

**Describe alternatives you've considered**
No alternatives considered

**Additional context**
- See Arc's toggling sidebar

**Comment by mauro-balades** [comment]
What shortcut would you like?

**Comment by bdbch** [comment]
I'm not sure. I first thought about `Shift+Ctrl+S` but that's also a possible keybind for *Save as*.

Maybe `Alt+S` - Alt keys are weird but are not that prone to conflicts.

**Comment by bdbch** [comment]
Another one that could work is `Shift+Ctrl+Y` - I think that one is rarely used.

**Comment by mauro-balades** [comment]
From 1 to 10, how much would you use this feature? Because if used a lot, it would be convinient to have it close to the CTRL button, but if not, better have it somewhere it doesnt disturb

**Comment by bdbch** [comment]
I myself would use it pretty often as I prefer the labeled (wider) sidebar which can be toggled open/closed similar to how Arc is doing it.

Arc however has this weird conflict with native shortcuts which really trips me up when using webapps like Codesandbox.

CTRL itself would be to open I think. I mean if this can be added to options, I would also be fine with a default shortcut that could have conflicts as long as I am able to change it to something else.

**Comment by mauro-balades** [comment]
This is now released! Thanks!

**Comment by bdbch** [comment]
What's the default shortcut for that? :)

**Comment by mauro-balades** [comment]
It depends, checkout the preferences page

**Comment by jean** [comment]
Broken at the moment, see https://github.com/zen-browser/desktop/issues/1313#issuecomment-2336481309
