### ISSUE TITLE
New tab button's right click menu don't have container entries

### ISSUE THREAD

**Issue by fervflow** [zen-browser/desktop#1291]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When you right click in the new `new tab` button, the menu do not show the options to open a new tab in a new container as it did before, I do not remember well the previous new tab menu but it was very complete and had a lot of options including the containers tabs.

Yes, I have the containers extension installed.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.37 (64-bit)

### What platform are you seeing the problem on?

Linux

**Comment by NOCanoa** [comment]
https://github.com/zen-browser/desktop/issues/1211

**Comment by fervflow** [comment]
I swear I searched, except in the closed issues.

**Comment by mauro-balades** [comment]
It's ok!
