### ISSUE TITLE
FlatHub update

### ISSUE THREAD

**Issue by lorebored** [zen-browser/desktop#1293]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The package you can find in flathub is very outdated, the last version is 16 days old, please fix. The last version is 1.0.0-a.28

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.28

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
This has been reported many times, it'll be updated shortly with the next release
