### ISSUE TITLE
CSS is stolen from bmFtZQ's edge-frfox

### ISSUE THREAD

**Issue by aspizu** [zen-browser/desktop#1295]
The files in `src/browser/base/content/zen-styles` are stolen from https://github.com/bmFtZQ/edge-frfox

**Comment by shettytejas** [comment]
@aspizu, the project that you have mentioned is distributed under an [MIT License](https://github.com/bmFtZQ/edge-frfox?tab=MIT-1-ov-file#readme) which enables anyone to use any part of the software whole and/or the source code as they please :smile: It won't be considered as stealing in my honest opinion.

**Comment by mauro-balades** [comment]
No it isn't? Only got the icons from them, but the rest of the styles is originally done by me 👍🏽

**Comment by aspizu** [comment]
> No it isn't? Only got the icons from them, but the rest of the styles is originally done by me 👍🏽

Lies. also you need to include their MIT license in its entirety. I don't see their LICENSE in about:license in the browser or in your LICENSE file.

**Comment by aspizu** [comment]
> @aspizu, the project that you have mentioned is distributed under an [MIT License](https://github.com/bmFtZQ/edge-frfox?tab=MIT-1-ov-file#readme) which enables anyone to use any part of the software whole and/or the source code as they please 😄 It won't be considered as stealing in my honest opinion.

Its stealing if you don't include their license, not even credit them anywhere.

**Comment by mauro-balades** [comment]
> > No it isn't? Only got the icons from them, but the rest of the styles is originally done by me 👍🏽
> 
> Lies. also you need to include their MIT license in its entirety. I don't see their LICENSE in about:license in the browser or in your LICENSE file.

Huh, are you saying k copied the entire project?

**Comment by aspizu** [comment]
There are major parts of the CSS code taken from their project, I just want you to reproduce their license so that they get credit for the work they did.

**Comment by mauro-balades** [comment]
For example?

**Comment by aspizu** [comment]
For example:

https://github.com/bmFtZQ/edge-frfox/blob/7872d6424c79f8384820494b9cfddc054f67525d/chrome/global/popup.css#L67

https://github.com/zen-browser/desktop/blob/163668d0314dd31b52512c5fc4a85790d8344229/src/browser/base/content/zen-styles/zen-popup.css#L74

**Comment by mauro-balades** [comment]
Again, is it just the icons?

**Comment by aspizu** [comment]
its more than just icons, its clearly visible. add their license to this repo and about:license

**Comment by aspizu** [comment]
you guys can't just ignore this.
