### ISSUE TITLE
User.js can not be applied 

### ISSUE THREAD

**Issue by hydroakri** [zen-browser/desktop#1297]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I am using [arkenfox](https://github.com/arkenfox/user.js/) the privacy enhanced user.js.
But I noticed that some options will not be applied as expect.
Behave may similar as #202 

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.32 flatpak version

### What platform are you seeing the problem on?

Linux

**Comment by KaiserCalm** [comment]
@hydroakri I'm curious as to why you closed this issue as it seems like a pretty good bug report.

**Comment by hydroakri** [comment]
Because I found it is not to blame for the Zen browser

**Comment by ypurpl** [comment]
> Because I found it is not to blame for the Zen browser

do you know what caused it?
