### ISSUE TITLE
Tab bar slow to refresh / respond when exiting fullscreen video

### ISSUE THREAD

**Issue by sjclayton** [zen-browser/desktop#1298]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

**What happens:**

When exiting out of fullscreen mode watching a video, the tab bar is empty and takes a full second or more to show the currently open tabs. This happens both when using the mouse or keyboard to leave fullscreen.

**What should happen:**

When exiting fullscreen playback the tab bar should display all open tabs instantly. As the delay in updating the tab bar makes things feel very laggy and creates a poor UX.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0.a.37

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
This is a known issue and wont be fixed problably... Since it's being calculated by an interval... but ill look into it

**Comment by Ansis100** [comment]
Why is it so random, though? Sometimes the tabs render instantly, other times they have a delay.
Are the tabs somehow "unrendered" after a certain amount of time of fullscreen?
