### ISSUE TITLE
Missing min/max window buttons

### ISSUE THREAD

**Issue by NightWatchman** [zen-browser/desktop#1299]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

On my Manjaro Arch Linux system, KDE Plasma, Wayland, I have no minimize or maximize buttons, only a close button.

![Screenshot_20240907_001934](https://github.com/user-attachments/assets/ad9db8e4-8003-4d35-81a4-23faa2b582d9)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.32 (64-bit)

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
Any themes installed? Do other apps have this problem as well?

**Comment by NightWatchman** [comment]
I changed to the default KDE Plasma theme (breeze) to be sure, and it doesn't seem to matter what the theme is.

I also remembered that I had customized the toolbar in the window decorations control panel, and I figured that was probably causing it to happen, but I reverted to the default on there and it didn't seem to have any effect.

**Comment by mauro-balades** [comment]
Does it still happen on version 37?

**Comment by AverageTurtle** [comment]
Hey, I'm also having this issue! I recently switched to arch with KDE Plasma 6(wayland) as my desktop. This issue doesn't appear with any other application and I am essentially using defaults for everything.

**Comment by NightWatchman** [comment]
> Does it still happen on version 37?

I'm currently using `v1.0.0-a.39` and it's still happening.

**Comment by ItsLaguna** [comment]
I just experienced this when doing a portable install (having the AppImage and creating a folder with it same name + .home, so ZenBrowser.home)
If I boot it normally without said folder, they're back.

**Comment by ItsLaguna** [comment]
This is still an issue in Version 1.0.1-a.19.

Opening the AppImage in portable mode causes min/max buttons to be missing, but funnily enough, opening a link from Vesktop opens it with them (and on my second screen instead of the main one).
