### ISSUE TITLE
need more error messages for downloads

### ISSUE THREAD

**Issue by Yasunaii** [zen-browser/desktop#130]
### What happened?

I wanted to install a file on my computer from google drive and it told me "failed to download" so I tried again without understanding why, I switch to edge and it tells me that I have more space on my computer it would be handy to have messages that find the reasons in case we are not attentive like me x)

### Version

Ver 1.0.0-a.10 (64bit)

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
This should likely be submited into bugzilla for firefox to implement this, I dont really want to touch that part of the browser in case they change it
