### ISSUE TITLE
Erro while in npm build

### ISSUE THREAD

**Issue by hugo-loiola12** [zen-browser/desktop#1301]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

Hi, i tried the build with npm and I am using fedora 40. I searched but cound't find any solution.

ERROR: Could not find libclang to generate rust bindings for C/C++. Please install the necessary packages, run `mach bootstrap`, or use --with-libclang-path to giv.
00:00:05  Config object not found by mach.
00:00:05 *** Fix above errors and then restart with "./mach build"

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0.a37

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
you need to run `npm run init` first
