### ISSUE TITLE
Weird highlighting/mouse effects in github code files.

### ISSUE THREAD

**Issue by Jerakin** [zen-browser/desktop#1302]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The mouse graphics are incorrect. Mouse input caret is in the wrong place and highlighting is incorrect.

## Highlighting
Here I am highlighting "create_system" and the yellow highlights are shown wrong.
![image](https://github.com/user-attachments/assets/7ef807a1-af76-4f50-badd-1604f3565915)

Here is the same in Firefox.
![image](https://github.com/user-attachments/assets/3b82a48a-09e9-49a5-85cf-7b0a58cf5d28)

[File tested](https://github.com/Insality/shooting_circles/blob/adf3c089605fe726d751ddcc87e840b828e364e3/systems/health/health.lua)

## Mouse Pointer
Zen (not at the end of the highlight)
![image](https://github.com/user-attachments/assets/b8ddaf2f-069e-4269-b533-8c3f5b238fb3)

Firefox
![image](https://github.com/user-attachments/assets/3ff3948a-6b73-4330-ace1-dfff6f895160)

[File tested](https://github.com/zen-browser/desktop/blob/main/src/browser/app/profile/better-fox.js)

| System| Information |
|---|---|
| OS Name|Microsoft Windows 10 Home	
|Version|10.0.19045 Build 19045|
| | |
|Processor |12th Gen Intel(R) |
|GPU| AMD Radeon RX 7900 XT|

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.37 (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by NOCanoa** [comment]
I am trying to reproduce it but for me all is normal,
do u have any extensions activated?

**Comment by mauro-balades** [comment]
This is actually a known github issue, I cant really do anything about it, sorry

**Comment by Jerakin** [comment]
> I am trying to reproduce it but for me all is normal, do u have any extensions activated?

Only extension is Bitwarden Password Manager.


> This is actually a known github issue, I cant really do anything about it, sorry... but it also happens to me on any browser

On any browser? That's so odd. I tried Firefox and Chrome and it didn't happen on them for me. I didn't know it was an known issue on githubs sides. I tried to search the web for an answer but found nothing. Do you remember where you read that? Might be a good idea to add it so that people know why it's happening.

**Comment by dinoallo** [comment]
To me, this issue is also reproducible, but only with `Zoom text only` enabled. However, on vanilla Firefox, I can no longer reproduce this.
