### ISSUE TITLE
"Require device sign in to fill passwords" is not working

### ISSUE THREAD

**Issue by ayush-bhattacharya** [zen-browser/desktop#1304]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

So as the title gives us an idea about the issue... The option that triggers the devices to sign in to autofill the passwords at websites is not working quite literally. The passwords were auto-filled without device sign-in consent, even though the settings were set accordingly. This can be a major security issue.

Could you look into this and fix the bug?

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.37

### What platform are you seeing the problem on?

Windows

**Comment by NOCanoa** [comment]
I am sorry, but I can understand your issue, can u explain in a different way?

**Comment by mauro-balades** [comment]
What do you mean with `device sign-in consent`? Where do you consent that?
