### ISSUE TITLE
Wrong project website on flathub

### ISSUE THREAD

**Issue by RealVishy** [zen-browser/desktop#1305]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The project website link on the flathub page is invalid.
![image](https://github.com/user-attachments/assets/ca288d68-da02-4984-aad0-7e1d5cfcd1f6)

https://flathub.org/apps/io.github.zen_browser.zen

It should be using the https://zen-browser.app/ link instead.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.32

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
This will be fixed shortly
