### ISSUE TITLE
Video stop streaming when you go back on the timeline

### ISSUE THREAD

**Issue by strooplab** [zen-browser/desktop#1307]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

This issue happened in every stream video it played, when you go back in the timeline, the video brakes up and the only way to fix it is moving forward a bit in the timeline, or waiting until video is back to normal.

https://github.com/user-attachments/assets/86b4975b-9814-4906-a77b-1048e1059584

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
Does it happen also with firefox?

**Comment by Winens** [comment]
I have the same issue. I use zen browser on flatpak  but Firefox on my host has the same problem too. Also on some movie sites, when i go forward the whole video player turns into black and even if i refresh the page or restart the browser it doesnt help.

**Comment by NOCanoa** [comment]
@Winens  Movie site is normaly related to DRM ,https://docs.zen-browser.app/faq#why-cant-zen-browser-play-drm-protected-content
