### ISSUE TITLE
Automatic re-application of an uninstalled theme at launch

### ISSUE THREAD

**Issue by marko19914** [zen-browser/desktop#1308]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

During trying out some Firefox themes while on version a32 my Zen browser got stuck on a theme like Dracula dark. The theme gets replied at launch even if the theme itself is deleted in addons menu. This behaviour got synced to firefox as well. But even if I turn off sync, the re-application of the theme still happens. Only place this re-theming doesn't happen is in Zen's work profile I created before ver a32.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a37

### What platform are you seeing the problem on?

Linux

**Comment by NOCanoa** [comment]
If u press delete theme does it get deleted in your chrome folder?

**Comment by marko19914** [comment]
> If u press delete theme does it get deleted in your chrome folder?

Where is this chrome folder? can you give me an example url

**Comment by marko19914** [comment]
It seems it doesn't, but deleting theme folders in chrome does nothing. The weird dark theme still gets reapplied

**Comment by mauro-balades** [comment]
Try to delete the theme from the add-ons page, also, could you send a screenshot?

**Comment by marko19914** [comment]
They are all deleted, I was removing folders which remained.
Screenshot of what?

**Comment by marko19914** [comment]
![image](https://github.com/user-attachments/assets/2ec059af-2209-4994-9aa5-1ac1f07580a9)

**Comment by marko19914** [comment]
That's the theme which is already deleted a long time ago, which gets reapplied all the time

**Comment by mauro-balades** [comment]
Could you show us the addons page?

**Comment by marko19914** [comment]
![image](https://github.com/user-attachments/assets/5a17ffd8-5860-4cda-a6c4-b071e3f0cd6a)

**Comment by mauro-balades** [comment]
Select the Dark theme instead of `system auto`... it's not fully supported yet

**Comment by mauro-balades** [comment]
What about your `Zen Themes` page?

**Comment by marko19914** [comment]
> Select the Dark theme instead of `system auto`... it's not fully supported yet

I'd like to have Light theme when my desktop is in light theme and dark when in dark. That's why this one is chosen.

**Comment by marko19914** [comment]
![image](https://github.com/user-attachments/assets/ca179d19-36ee-4fe8-9e82-97b7c35654b8)
![image](https://github.com/user-attachments/assets/ce2ca429-7583-454f-bf5b-16194179d20c)
![image](https://github.com/user-attachments/assets/0129ec56-99ed-485e-a434-b7460e42fcf6)

**Comment by marko19914** [comment]
I need to note, that the theme changes irregardless of which theme was applied on the previous launch. Copying css file from the unaffected browser profile, deosn't change anything.

**Comment by marko19914** [comment]
It seems, I figured out what was wrong. I somehow had Nord theme extension installed which was doing the theme change. Should have tried to start a profile without the add-ons, to see if it can be caused some weird extension.
