### ISSUE TITLE
Sidebar opens when taking a screenshot while in compact mode

### ISSUE THREAD

**Issue by diego-velez** [zen-browser/desktop#1309]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When using the browser in compact mode and trying to take a screenshot, the sidebar opens up covering the page, and not letting you see exactly what you're trying to screenshot.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.37

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
This is expected, screenshots only affect the webview

**Comment by diego-velez** [comment]
> This is expected, screenshots only affect the webview

It is? Because when I'm in compact mode with the sidebar hidden, and I try to take a screenshot using the browser itself, it opens the sidebar while going to select the area I want to screenshot.

**Comment by Anthonyy232** [comment]
If I understand what's being said correctly, this is pretty terrible if by design. If the sidebar isn't already open when taking the screenshot.. why open it?
