### ISSUE TITLE
Conteiners for web panel

### ISSUE THREAD

**Issue by NOCanoa** [zen-browser/desktop#131]
### What happened?

In web side panel, wold it be possible to use the containers like in normal tab.

### Version

1.0.0-a.10

### Severity impact

Enhancement

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
No because web panels aren't linked to a tab. And containers need a tab to work

**Comment by NOCanoa** [comment]
so that means each web panel is his own browser instance?
does that bean extencion cant interact whit the web panel?

**Comment by Muko-Tabi** [comment]
Would like for this feature to be in Zen as well since I used to it in Floorp. Thanks in advance.
