### ISSUE TITLE
Browser internal borders

### ISSUE THREAD

**Issue by Car0lina5** [zen-browser/desktop#1310]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The borders on the inside of the browser look like they should? The roundness looks really weird even when it's not full screen.

![RDT_20240907_1419573100659539913470511](https://github.com/user-attachments/assets/93f0e199-5076-4693-86d3-2bcb3261180d)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.37

### What platform are you seeing the problem on?

Windows

**Comment by NOCanoa** [comment]
any themes instaled?working as expected for me.

**Comment by Car0lina5** [comment]
Thanks for reminding me! It was a theme store add-on called "Better Letterboxing".
