### ISSUE TITLE
Missing languages

### ISSUE THREAD

**Issue by MacBeibhinn** [zen-browser/desktop#1311]
### Captchas

- [x] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Not sure if it is a bug or just not yet supported, I couldn't find any other issues when searching about the languages available, but I cannot find certain languages supported by default in Firefox, more specifically Gàidhlig (Scottish Gaelic), but others I've noticed too.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.37

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
Languages are still a work in progress, thanks!
