### ISSUE TITLE
Why zen browser doesn’t export history to other browsers; is it some kind of a lock in?

### ISSUE THREAD

**Issue by sameer1612** [zen-browser/desktop#1312]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Why zen browser doesn’t export history to other browsers; is it some kind of a lock in? 

I’m on a mac. And none of the other browsers show zen in their list of available browsers to import history from, including the Firefox one. 

Is something wrong with my machine or is it a general problem? 

I do need to sync zen with safari which I use on my phone. 

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

37

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by mauro-balades** [comment]
That's because other browser are trying to search for `.firefox`, `.opera`, ... But they did not add support for `.zen`... There's nothing I can do really... Sorry. But you can export and import them by files, iirc
