### ISSUE TITLE
The What's New link takes to the website instead of release note

### ISSUE THREAD

**Issue by Suman2023** [zen-browser/desktop#1315]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

On the About Zen browser the What's New link takes us to the main website but i think it can go to something like https://github.com/zen-browser/desktop/releases/tag/1.0.0-a.37 which is a valid place to see the release notes if any until there is a official page designed for the same.

I am not sure if this is an enhancement or a miss to add the correct url.

![image](https://github.com/user-attachments/assets/40df57b7-6e6c-4a36-92c3-e374a353edcb)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.37

### What platform are you seeing the problem on?

Windows

**Comment by NOCanoa** [comment]
this is more and enhancement (so next time in discussions pls ), btw https://zen-browser.app/release-notes ,
But yeah a couple off those links need updating xD.

**Comment by NOCanoa** [comment]
@mauro-balades 
Update links some are going to moz

**Comment by n7itro** [comment]
https://github.com/zen-browser/desktop/blob/79c0402c70380040e6dbacd2f22533ed12b8a39d/src/browser/app/profile/zen-browser.js#L124-L125

The preferences appear to be set correctly in the source, but they somehow aren't applying

**Comment by Suman2023** [comment]
Is it because of the app.update.url.details? That is set to the download page. @n7itro

**Comment by n7itro** [comment]
> Is it because of the app.update.url.details? That is set to the download page.

That's not it, since the What's New button doesn't even refer to the download page.

When I look in `about:config`, `releaseNotesURL.aboutDialog` is just set to https://zen-browser.app instead of what it should be according to https://github.com/zen-browser/desktop/issues/1315#issuecomment-2336653199

**Comment by Suman2023** [comment]
Yes that seems to the issue for some reason its not taking the `releaseNotesURL.aboutDialog` . I have tried using a local user.js in zen and it does use the one for user.js. This is what i used: user_pref("app.releaseNotesURL.aboutDialog", "https://www.zen-browser.app/release-notes");. Does that mean while build something is not being configured properly?

**Comment by mauro-balades** [comment]
What's new is overriden by surfer https://github.com/zen-browser/surfer/blob/main/src/commands/patches/branding-patch.ts#L381. Ill fix the links
