### ISSUE TITLE
The scaling is broken on Linux i3WM

### ISSUE THREAD

**Issue by skignes** [zen-browser/desktop#1316]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

On the zen desktop Application on Arch Linux. I now use it as my browser but i got a pretty bad problem. When i go into full screen on my i3WM desktop and go back to normal the zen browser is still in full screen. It works the same as if i got my zen browser on my secondary monitor and then i put my browser on my primary monitor, but it is still with the scale of the secondary one. I am not sure if the AUR on Arch Linux is up to date and maybe this is resolved but i put it there.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Mozilla Zen 1.0.0-a.32

### What platform are you seeing the problem on?

Linux

**Comment by NOCanoa** [comment]
Aur is normally pretty up to date, btw its at a37 xD

**Comment by mauro-balades** [comment]
Could you show us a video or screenshot?

**Comment by skignes** [comment]
So it is when i am on a desktop and i am in full screen on i3, after that i change the zen window into another desktop, it is there that the scaling is broken, so this is what i get before :
![Screen_normal](https://github.com/user-attachments/assets/e3b3b667-13f7-48f5-892c-25a84dfcd2b5)
And this is after :
![Full_screen](https://github.com/user-attachments/assets/ee47c9fa-0b2e-4654-8671-3ad0ad963188)
So for personal reason i obstructed the Tabs and the Drive. But this is it. Thanks You
