### ISSUE TITLE
M1 mac arm version will not open on my laptop, mac os states it is broken

### ISSUE THREAD

**Issue by Astrid-dG** [zen-browser/desktop#1318]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I downloaded it and tried to use it, but Mac OS stated it was broken and should be sent to the bin. I downloaded it twice to check. M1 Mac Book Pro using Sonoma 14.5. 

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0 or latest download

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by n7itro** [comment]
This issue will be fixed soon. In the meantime, refer to our macOS [install guide](https://docs.zen-browser.app/guides/install-macos)
