### ISSUE TITLE
Video not streaming

### ISSUE THREAD

**Issue by devlev1980** [zen-browser/desktop#1320]
### Captchas

- [X] I have read the instructions.
- [ ] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

Video not streaming when i go to udemy.com in Windows and MacOS(arm 64)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0

### What platform are you seeing the problem on?

macOS - aarch64, Windows

### Relevant log output

```shell
Video not streaming when i go to udemy.com in Windows and MacOS(arm 64)
```

**Comment by sjclayton** [comment]
Could be related to #433

**Comment by mauro-balades** [comment]
Udemy uses DRM content, unfortunately, it's not supported in Zen

https://docs.zen-browser.app/faq#why-cant-zen-browser-play-drm-protected-content
