### ISSUE TITLE
All pages are closed after I close browser

### ISSUE THREAD

**Issue by Teddy-HS** [zen-browser/desktop#1321]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

All pages are closed after I close browser and it did not open again when I restart browser.
I think it is a needed action that ask people to choose close or not for all pages in current windows in settings.
Edge and Arc browser will restore my pages after I re-open their browser (if I closed that "main window") so that I can do more work on their browser without worry my page discard

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by mauro-balades** [comment]
![image](https://github.com/user-attachments/assets/3fbf8ccf-6168-46d8-bafa-64350a4e1070)

make sure you have this enabled
