### ISSUE TITLE
Multi-Account Containers

### ISSUE THREAD

**Issue by adhamfarrag** [zen-browser/desktop#1324]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Thanks for your great work here. 

This issue is mainly about tabs and [Firefox Multi-Account Containers](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/). When I installed Zen for the first time and synced my Firefox account and the extension worked as expected. Mainly: 

- Container colors worked as expected.
- When I click right, it shows me the container menu. 

![signal-2024-09-08-192232_002](https://github.com/user-attachments/assets/912fee93-ee9d-4ba7-94c4-60d08a50a392)

Then, I tried to install the some Zen utility extensions, and I lost the ability to select containers unless I open a new tab, then from the tab menu I select the container i want. 

![2024-09-08 at 8  10 49@2x](https://github.com/user-attachments/assets/39aef68d-b193-40a1-9fc1-3acbc5b0bd18)

I tried to remove all utility extensions to test what's causing this behavior, failed to achieve that and noticed the following:

- Installed Zen on a Linux VM, and the the extension context menu worked as expected.
- When I reinstalled some of the extensions, it remembered my settings, and I'm not sure how this works of it extensions have the ability to overrwrite some behaviors regarding how tabs work ?
- When you reinstall the extension, it loads my containers, but also shows wants me to login to my Firefox account.
- Not sure if relevant or not. Tried to test Firefox Nightly on macOS, the top bar worked as expected, but not the sidebar. It doesn't have any context menu. 

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.37

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by mauro-balades** [comment]
This is being worked on, thanks!
