### ISSUE TITLE
Sidebar auto wide on warning

### ISSUE THREAD

**Issue by Karuto2k7** [zen-browser/desktop#1325]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![image](https://github.com/user-attachments/assets/e7455fb6-4bdf-42e2-b9c1-2002497406f1)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.37 (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
This has been fixed for the next release (40). Thanks!
