### ISSUE TITLE
Picture in picture go bellow other tabs when switching applications when it should be above any app

### ISSUE THREAD

**Issue by sadiki-o** [zen-browser/desktop#1326]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When using Picture-in-picture mode it should always be above other tabs, but when i switch applications it goes bellow for some reason

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.23 (64-bit)

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
To make them stay at the top, right click into it an check "stay on top"

**Comment by Anthonyy232** [comment]
Think it would make sense to make this default behavior though

**Comment by default-student** [comment]
Very much so. Its a default on Chrome atleast.
