### ISSUE TITLE
Pinned tabs do not keep their position after closing/reopening Zen

### ISSUE THREAD

**Issue by DutchPete** [zen-browser/desktop#1327]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I have Discord as a pinned tab. I have 7 other pinned tabs, and the Discord one is in position #3. However, when I close Zen and relaunch it, Discord is in position #1. Any idea why this could be? The other pinned tabs don't move. 

Here is the workaround I found today:

I unpinned all my pinned tabs, then pinned them in the order I want to have them, which in this case means the Discord tab in position #3.

Then I quit Zen, relaunched it, and sure enough, all pinned tabs stayed in their place, incl. the Discord tab.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

a37

### What platform are you seeing the problem on?

Linux

**Comment by jerrwu** [comment]
I'm seeing this too, Windows 1.0.1-a.4

**Comment by DutchPete** [comment]
Yes, the issue is still there.

![image](https://github.com/user-attachments/assets/0f27e6f7-2cd6-4690-a61f-3a49e3ee2beb)

I am using the AppImage on Linux, which I just updated to 1.0.1-a.22. I unpinned and closed all the tabs in the screenshot, then opened and pinned them again: same problem.

**Comment by vraravam** [comment]
I have a similar experience of this on macos sequoia. Running the latest twilight build 1.0.1-t.22 (Firefox 133.0) (2024-11-30) (aarch64)

**Comment by salamijason** [comment]
This is quite strange. Could you check if this happens on b.2? Thank you

**Comment by DutchPete** [comment]
I am using 1.0.2-b.0 and the issue does not appear anymore. And, of course, in b.2 it does not appear either.
Many thanks for following up.
