### ISSUE TITLE
2 new tabs created when last tab closed

### ISSUE THREAD

**Issue by Waradu** [zen-browser/desktop#1332]
### Captchas

- [x] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

So I have "browser.tabs.closeWindowWithLastTab" disabled but if i close the last tab 2 new tabs are created instead of 1.

this is how it looks like after I closed the last tab:
![image](https://github.com/user-attachments/assets/ae5cb321-e218-41c1-a93c-aa94d3c729a8)

this is how the same thing looks in firefox:
![image](https://github.com/user-attachments/assets/c085665e-3d6b-4c8d-a219-b3eacc773c7f)

ofc its not a big thing but it annoys me.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.37

### What platform are you seeing the problem on?

Windows

**Comment by chriskirknielsen** [comment]
This is an especially common scenario in a private window if you close all tabs. It'll close one, show two, close them all again, you get one, close that, you get two… and it cycles that way. Maybe there could be an option "Close private window when all private tabs are closed"?

**Comment by gabors0** [comment]
The same is happening to me but it reopens 3 tabs, not 2? Also I'm not in a private window but the same thing happens there too.

**Comment by berezki** [comment]
Got the same issue, 3 new tabs are appeared when closing last one.

**Comment by andersmmg** [comment]
For me it usually opens 2, but sometimes 3. Haven't found any pattern yet as to when it does which, but it's very odd. I don't have this issue on the latest Firefox.

**Comment by bedxnta** [comment]
video preview of this bug:

https://github.com/user-attachments/assets/470c99ea-41b8-4d98-94bd-49d5a2f06306

**Comment by bedxnta** [comment]
UPDATE: It now opens 2 windows instead of 3 after the new update: 1.0.1-a (64-bit)

https://github.com/user-attachments/assets/3feef4a0-3dc1-4537-a3ba-4220d81c2550

**Comment by BVengo** [comment]
Came for the same issue. Someone else has also listed it here: https://github.com/zen-browser/desktop/issues/1036

**Comment by RayZ3R0** [comment]
Does this still happen on latest version? (a.14 as of this comment)

**Comment by gabors0** [comment]
> Does this still happen on latest version? (a.14 as of this comment)

No, seems to be fixed for me

**Comment by RayZ3R0** [comment]
Alright I'll be closing this issue then. Thanks for reporting
