### ISSUE TITLE
Unbinding default keybinds does not allow use in extension shortcuts

### ISSUE THREAD

**Issue by slacksystem** [zen-browser/desktop#1334]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

After checking the box in keyboard shortcuts to unbind the default keyboard shortcuts, and ensuring ctrl+w is not in my custom keybindings, trying to set one of my extension/add-on shortcuts errors. This seems to apply to all keyboard shortcuts (I have tested with ctrl+f and ctrl+a) but I will use control+w here to demonstrate the behavior.

Steps to reproduce:
1. Disable all default keybinds and any custom keybind using ctrl+w
2. Attempt to set an extension shortcut for an addon to ctrl+w
Expected behavior: 
The keybind is set successfully, as any other use of ctrl+w would have been disabled by step 1 above.
Actual behavior:
A red tooltip is shown saying "Can't override a Zen Browser shortcut".

Again I would like to emphasize this happens for many (likely all) different Zen Browser shortcuts, not just ctrl+w.

It's not possible to reproduce the bug on Firefox as firefox does not have the same (or maybe any) keyboard shortcut menu

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.35 (64-bit)

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
I am unsure where to look for logs, but if someone advises me, I will gladly edit them in here
```

**Comment by slacksystem** [comment]
I see that this has gone stale but it never got a reply from anyone, is this something that can be fixed?

**Comment by RayZ3R0** [comment]
> I see that this has gone stale but it never got a reply from anyone, is this something that can be fixed?

Does this still happen on latest version? (a.14 as of this comment)

**Comment by slacksystem** [comment]
I can test this tomorrow

**Comment by RayZ3R0** [comment]
did you?

**Comment by salamijason** [comment]
did you?

**Comment by slacksystem** [comment]
I'm so sorry, I apologize for not following up on this. The issue seems fixed on the current version. Closing this issue. Thanks for your patience.
