### ISSUE TITLE
Can we make the sidebar wider?

### ISSUE THREAD

**Issue by chlorine3545** [zen-browser/desktop#1335]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Hello there.

Might not strictly be a bug, but it's something I thought worth mentioning. From my perspective, the sidebar appears to be quite narrow compared to Arc's design.

<img width="1440" alt="截屏2024-09-09 11 15 40" src="https://github.com/user-attachments/assets/a95f5315-7b42-400a-8e94-56792d34a1f1">

So, how can we make it a little wider?

Thanks a lot!

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0 alpha 37

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by tux-arch** [comment]
Yes, you can make the sidebar wider!
Open your Zen profile folder (about:support > "Profile Directory").
In the chrome folder, create a userChrome.css file (if it doesn't exist) and add this:

```
@media (-moz-bool-pref: "zen.view.sidebar-expanded") {
  #navigator-toolbox:is(#navigator-toolbox[zen-user-hover="true"]:hover, #navigator-toolbox[zen-user-hover="true"]:focus-within, #mainPopupSet[zen-user-hover="true"]:has(> #appMenu-popup:hover) ~ toolbox, #navigator-toolbox[zen-user-hover="true"]:has([open="true"]:not(tab):not(#zen-sidepanel-button)), :not([zen-user-hover="true"])) {
    --zen-navigation-toolbar-min-width: 200px !important;
    width: 300px;
  }
}
```

Adjust the width: 300px to your preference.

**Comment by yoghurtlee-thu** [comment]
> Yes, you can make the sidebar wider! Open your Zen profile folder (about:support > "Profile Directory"). In the chrome folder, create a userChrome.css file (if it doesn't exist) and add this:
> 
> ```
> @media (-moz-bool-pref: "zen.view.sidebar-expanded") {
>   #navigator-toolbox:is(#navigator-toolbox[zen-user-hover="true"]:hover, #navigator-toolbox[zen-user-hover="true"]:focus-within, #mainPopupSet[zen-user-hover="true"]:has(> #appMenu-popup:hover) ~ toolbox, #navigator-toolbox[zen-user-hover="true"]:has([open="true"]:not(tab):not(#zen-sidepanel-button)), :not([zen-user-hover="true"])) {
>     --zen-navigation-toolbar-min-width: 200px !important;
>     width: 300px;
>   }
> }
> ```
> 
> Adjust the width: 300px to your preference.

Awesome. Thank you tux-arch, you really make my day :)

**Comment by ghost** [comment]
I reopen this issue COZ after updating to 1.0.1-a.13, the method above doesn't work anymore :(

**Comment by ghost** [comment]
Update: after updating to 1.0.1-a.14 (Don't know if it works on 13), you can resize the sidebar by (disabling compact mode and) dragging the bar edge directly! A clever and user-friendly design :)

**Comment by lamteteeow** [comment]
I am at 1.0.1-a.19 and I could resize the sidebar by first right click either on sidebar or toolbar, choose **Customize toolbar** then drag the bar edge directly as you said. 💯

**Comment by salamijason** [comment]
Yes you should be able to drag the sidebar to adjust its width.
