### ISSUE TITLE
Can't check for updates

### ISSUE THREAD

**Issue by CH1NRU5T** [zen-browser/desktop#1336]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When I want to preferences -> General -> Updates
And I press the button to `check for updates`
it shows `Failed to check for updates`

<img width="760" alt="Screenshot 2024-09-09 at 11 10 41 AM" src="https://github.com/user-attachments/assets/8590f8bc-4b90-47f8-b5a6-ff5bb792953b">

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.29

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by mauro-balades** [comment]
You have to manually download it again, sorry... You wont lose any data, but that version is so old, that the URL to update is already not existant...

Sorry, please checkout https://zen-browser.app/download
