### ISSUE TITLE
WEBP Files always automatically get downloaded to TEMP Folder instead of Downloads Folder.

### ISSUE THREAD

**Issue by Shazgul** [zen-browser/desktop#1337]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

WEBP Files always automatically get downloaded to TEMP Folder instead of Downloads Folder.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0 a37

### What platform are you seeing the problem on?

Windows

**Comment by DariusSlowik** [comment]
Applies also to PDF files downloaded from GDRIVE - Linux KDE.

**Comment by RayZ3R0** [comment]
Does this still happen on latest version? (a.14 as of this comment)

Also, You have to set them to Save File in settings or they'll download to temp and open the file *in* the browser.![Image](https://github.com/user-attachments/assets/8ca4907e-56a2-49aa-bb6f-94a5dab2ec42)

**Comment by DariusSlowik** [comment]
When I set, "Save" it saves in downloads but it doesn't open them via zen-browser. I want to have them saved by default in Downloads with other files and have them opened via zen... One excludes the other currently, so it is not so convenient.

**Comment by RayZ3R0** [comment]
This is how firefox does it though.. But yeah that would be more convenient. Maybe you can suggest this in https://github.com/zen-browser/desktop/discussions

**Comment by DariusSlowik** [comment]
Yeah... maybe I'll just wait for devs to mark it as a feature request here, or as a fix to current or future sprint.

**Comment by RayZ3R0** [comment]
> Yeah... maybe I'll just wait for devs to mark it as a feature request here, or as a fix to current or future sprint.

Feature requests are to be made in https://github.com/zen-browser/desktop/discussions not here. This is for bugs only

**Comment by DariusSlowik** [comment]
Created. #2428
