### ISSUE TITLE
Zen browser detected as a Trojan by Kaspersky software

### ISSUE THREAD

**Issue by bial654321** [zen-browser/desktop#1338]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![image](https://github.com/user-attachments/assets/3574e53c-f655-4964-b8a7-330617010cdb)

Is this normal? I saw there was another ticket for Windows detecting executable as a virus but I had no problems opening it. I was simply browsing and this popped up on my screen from Kaspersky software out of nowhere. I had to add Zen browser to exceptions. This never happened with original Firefox software

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.37 (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by ralcaidev** [comment]
Duplicated #37

**Comment by mauro-balades** [comment]
Please checkout https://github.com/zen-browser/desktop/issues/37
