### ISSUE TITLE
Remove padding around close button on Windows

### ISSUE THREAD

**Issue by bdbch** [zen-browser/desktop#134]
### What happened?

Currently **when in fullscreen*, there's a padding around the close button which makes it a bit harder to close the button.

Usually what I do on Windows is just move my mouse to the upper right corner & click but because of that padding, the close button actually ends a 1-2 pixels before the screen corner.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.10

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
Could you please provide a screenshot?

**Comment by bdbch** [comment]
https://github.com/user-attachments/assets/57726512-9bb1-4ef0-bf26-eda4e5376664

Hope this helps

**Comment by mauro-balades** [comment]
Fixed with https://github.com/zen-browser/desktop/commit/e32d9cad92fa9ac02b639f445c244d43e1de3652#diff-bedb1c979c745a55b5197745ecc7255d6861173c302e4af76eb62d7568feef90, thanks a lot!

**Comment by bdbch** [comment]
Thanks for the quick action! :)

**Comment by NOCanoa** [comment]
![image](https://github.com/user-attachments/assets/fd7bb27e-75f5-482b-bc00-1e9711d14300)
worse now, or is it only my end?

**Comment by mauro-balades** [comment]
ohhh ok, I see what you want

**Comment by mauro-balades** [comment]
NOW it's fixed, thanks a lot!
