### ISSUE TITLE
Vertical tabs very buggy/slow to scroll up/down with laptop touchpad

### ISSUE THREAD

**Issue by itstamimi** [zen-browser/desktop#1340]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

After the last update, it is very hard to scroll up/down the vertical tabs using the laptop touchpad. It works normally with a mouse wheel, the only issue is while using laptop touchpad.
Here you can see the bugged up scrolling
[Screencast_20240909_051018.webm](https://github.com/user-attachments/assets/71002201-0b95-4b61-9b69-ea90f60a4411)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.37 (64-bit)

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
Fixed! In the meanwhile, you can try disabling `toolkit.scrollbox.smoothScroll`... or just wait 3 hours for the next release
