### ISSUE TITLE
allowing home folder access nuked my browser data

### ISSUE THREAD

**Issue by ivanjx** [zen-browser/desktop#1342]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

in flatseal, i allowed home filesystem access and when i restarted it all the logins and extensions are gone.

![image](https://github.com/user-attachments/assets/635e2bec-7914-43d2-bb6a-0e2ef9fac20c)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0 a32

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
Probably firefox is just using a different home path now that you've allowed it... Please locate the old HOME path and just copy and paste them into the new profile location... Sorry about this!

Another solution would be to remove the home access again

**Comment by ivanjx** [comment]
if so then why not just enable home access by default?
