### ISSUE TITLE
Contribution guidelines & requirements

### ISSUE THREAD

**Issue by bdbch** [zen-browser/desktop#135]
### What feature would you like to see?

Not a browser feature directly - but I'd like to know what kind of Software I need to have installed to be able to setup the project locally.

I tried setting it up on my Windows machine and it seems that I had to have 7zip installed. After installing it after `winget install 7zip` and adding it to my PATH I was able to get further.

Would make sense for new people to help with contributing to the project.

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
Yeah, so appart from having the following requirements, mozilla will take care of everything else:

* 7z
* Python3
* Nodejs

**Comment by bdbch** [comment]
Now it's stuck on the unpack step. Any idea why it's stuck here?
![image](https://github.com/user-attachments/assets/8404e59f-9d49-40ed-9c1f-58bba1e927e1)

---

```
> zen-core@1.0.0 bootstrap
> surfer download && surfer bootstrap

00:00:00 'engine/' is empty, it...
00:00:00 Locating Firefox release 128.0.3...
00:00:00 Using cached download
00:00:00 Unpacking Firefox...
00:00:00 Unpacking C:\Users\xxx\Code\zen-desktop\.surfer\engine\firefox-128.0.3.source.tar.xz to C:\Users\xxx\Code\zen-desktop\engine
00:00:00 Unpacking Firefox source on Windows (7z)
```

**Comment by bdbch** [comment]
Still stuck on it (around 3h now) 😂 forgot that the process was running in the background.
I guess the extraction process is not even starting because my `engine` directory is still completely empty.

Do you use python for the extraction part too?

**Comment by mauro-balades** [comment]
Could you run it with `--verbose`?
