### ISSUE TITLE
Sluggish tab UI after minimizing full screen video

### ISSUE THREAD

**Issue by ThreeTheOG** [zen-browser/desktop#1353]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When I am on youtube, and watch a full screen video and exit full screen the tab bar is empty even though I have tabs, and reload after 1-2 seconds.

https://github.com/user-attachments/assets/87e6760b-0fe0-4320-8979-c745f2c9d936

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.35 (64-bit)

### What platform are you seeing the problem on?

Linux

**Comment by HeyItsJustFelix** [comment]
Noticed this was on linux, thought I should add that this problem also exists on Windows
