### ISSUE TITLE
Unable to watch media on streaming sites such as Netflix or Disney+.

### ISSUE THREAD

**Issue by tacolegs2004** [zen-browser/desktop#1356]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I am unable to watch TV shows or Movies on Netflix or Disney+. I looked into the privacy and security settings in Zen but couldn't find a cause for the errors. When I play something on Disney+, I get an error message saying, "Something went wrong. Please try again. If the problem persists, Visit the Disney+ Help Center (Error Code 83)." 

I opened the same sites in Firefox and they worked perfectly fine. I know this browser is primarily for programmers, but I'd like to be able to use this browser not only for web development but for everything else I usually do.

If you see this, thank you for reading.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by n7itro** [comment]
Duplicate issue and answered in the [faq](https://docs.zen-browser.app/faq#why-cant-zen-browser-play-drm-protected-content)
