### ISSUE TITLE
localisation broke again

### ISSUE THREAD

**Issue by Shyboy-101** [zen-browser/desktop#1357]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![image](https://github.com/user-attachments/assets/fb024930-edfa-402b-a99d-c397245f835b)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0 - a.39

### What platform are you seeing the problem on?

Version      Windows 11 Home Chinese Edition
Version      22H2
Install Date February 2, 2024
Operating System Version 22621.3007
Experience   Windows Feature Experience Pack 1000.22681.1000.0

---

Device Name      DESKTOP-7F0UUDG
Processor        Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz   1.50 GHz
Installed RAM    8.00 GB (7.77 GB available)
System Type      64-bit operating system, x64-based processor
Pen and touch    No pen or touch input is available for this display

**Comment by 1677883418** [comment]
Me too ! I like this browser,but localisation have problem,Windows and Linux(archlinux )
