### ISSUE TITLE
expand tabs on hover shifts the tab content

### ISSUE THREAD

**Issue by ivanjx** [zen-browser/desktop#1359]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

i'm not sure what just happen but this is what happens when i hover on the tabs to expand them:

[https://github.com/user-attachments/assets/5e7c8a71-c01b-46c0-b592-dc36df66a8a7](https://github.com/user-attachments/assets/5e7c8a71-c01b-46c0-b592-dc36df66a8a7)

i tried restarting the browser, disabling and enabling the hover feature but it still persist. does not happen on my laptop (same kernel, same os, same DE).

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0 a32

### What platform are you seeing the problem on?

Linux

### Relevant log output

*No response*

**Comment by mauro-balades** [comment]
This has been fixed in 36 iirc, please update the browser

**Comment by ivanjx** [comment]
@mauro-balades this seem to happen again on 1.0.1-a2

**Comment by ivanjx** [comment]
https://github.com/user-attachments/assets/56a194fc-886a-4922-861e-f41c4625c3d8

**Comment by mauro-balades** [comment]
In rewriting expand on hover, hope it fixes it

**Comment by ivanjx** [comment]
happening again on 1.0.1-a.5
