### ISSUE TITLE
Window border present in media full-screen mode

### ISSUE THREAD

**Issue by benedekfeke** [zen-browser/desktop#1362]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When I switch to full-screen, the border around the window, specifically the bottom and right border is still shown, hence the window is not full-screen.
![Screenshot (7)](https://github.com/user-attachments/assets/d8f42a40-c04b-4c7d-8b1f-42ab13e87855)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.39

### What platform are you seeing the problem on?

Windows

**Comment by BionicBlade0** [comment]
Issue #1110 and # #1100 could be related.

**Comment by gitartiman2499** [comment]
> Issue #1110 and # #1100 could be related.

nope it isn't this also happens with sidebar on the left and without compact mode

**Comment by kittybwained** [comment]
I got this too, I have tabs on the left and don't use compact mode.

**Comment by aimslut** [comment]
+1
just started happening to me after it updated to `1.0.0-a.39`, wasn't present before that
also i believe this broke all the themes on the zen theme page to do with border padding as none of them work for me anymore either

**Comment by sadmoonphoenix** [comment]
This is happening for me too, macOS 12, Zen version a39

**Comment by kittybwained** [comment]
In the meantime, I switched back to a 1.0.0-a37 portable version. Hope this can be fixed soon.

**Comment by mauro-balades** [comment]
This will be fixed in the next version

**Comment by bl4xe** [comment]
hope I'm not just adding unnecessary information here but only seeing people report on this who use Mac and Windows, I wanted to say I have the same issue using Arch Linux

**Comment by faab007nl** [comment]
It can be temporarily fixed by installing the No browser padding theme.
https://zen-browser.app/themes/680424a8-a818-406b-98c5-7726214e2a9f

**Comment by LarveyOfficial** [comment]
Adding the following to your userChrome.css will also fix the issue in fullscreen mode
`:root[sizemode="fullscreen"] #tabbrowser-tabpanels {
  padding: 0 !important;
}`

**Comment by oslohes123** [comment]
I see the border you're talking about, is there an option to disable the border entirely?

**Comment by BionicBlade0** [comment]
Yes, use the 'Remove Browser Padding' zen browser theme. That will resolve this issue as well.

**Comment by oslohes123** [comment]
I see it was a little confused at first, I think theme is maybe the wrong word, maybe mod wording for the site like zen-mods or smthn

**Comment by mauro-balades** [comment]
This has been fixed on 1.0.1-a that will be released today in some hours, thanks!

**Comment by BionicBlade0** [comment]
I agree.

**Comment by BionicBlade0** [comment]
> I see i was a little confused at first, I think theme is maybe the wrong word, maybe mod wording for the site like zen-mods or smthn

I agree.

**Comment by mauro-balades** [comment]
> > This has been fixed on 1.0.1-a that will be released today in some hours, thanks!
> 
> Just ran a system upgrade and was super happy to see the new release for zen browser but this hasn't been fixed for me..
> 
> ![image](https://private-user-images.githubusercontent.com/96691738/367766611-f37fa489-a1eb-45bd-87c2-12208fd1f804.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0OTQ0NzMsIm5iZiI6MTcyNjQ5NDE3MywicGF0aCI6Ii85NjY5MTczOC8zNjc3NjY2MTEtZjM3ZmE0ODktYTFlYi00NWJkLTg3YzItMTIyMDhmZDFmODA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDEzNDI1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhNTE0OTQxMTZhYjAwNmFkMDU0YTZhNmI2MjRkZjk1MWEzYzcwNDM4MGZkNDQyMGRjZTgyODA0NWYwMjMwOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Yg0hMjCIJQhFd1mnol8gy37_cRSHr7vh3su6kxcx2Hg)
> 
> ![image](https://private-user-images.githubusercontent.com/96691738/367766916-6b71d56f-54dc-4987-acb9-cac7847e0372.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0OTQ0NzMsIm5iZiI6MTcyNjQ5NDE3MywicGF0aCI6Ii85NjY5MTczOC8zNjc3NjY5MTYtNmI3MWQ1NmYtNTRkYy00OTg3LWFjYjktY2FjNzg0N2UwMzcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDEzNDI1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkOGM0ODMxZDg1NzI1ZTYzNDcxNWU4MjYzYTAyNzQ2ZmM1MzIwOThmZjIyYWZkN2U3ZDYzYTc2ZThkZWE1YzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Vtb2bVcGEZco_G4_Ly2KXefzTBRU0Fa-PgKi0cICrfs)

it hasnt been released yet, you are still on .39...

**Comment by Ein420** [comment]
this still is not fixed, not for me at least, any updates? I want to use fullscreen properly in compact mode, everything suggested here are just workarounds, not actual solutions
