### ISSUE TITLE
Keyboard shortcut binding fix

### ISSUE THREAD

**Issue by HarryHeres** [zen-browser/desktop#1363]
To have a better overview of the state of things, I'm creating an aggregated issue for it. 

Issues aggregated:
- #490 
- #376 
- #283

**Comment by BartekSmalec** [comment]
What about [Toggle Sidebar shortcut don't work on Windows 11](https://github.com/zen-browser/desktop/issues/1313) ?

**Comment by HarryHeres** [comment]
> What about [Toggle Sidebar shortcut don't work on Windows 11](https://github.com/zen-browser/desktop/issues/1313) ?

Yes, noticed that as well. Will try to take a look at that.

**Comment by mauro-balades** [comment]
@harryheres how's it going? Need any help?

**Comment by HarryHeres** [comment]
Nope, going well, just quite a few things to do. Still on it :)

**Comment by mauro-balades** [comment]
That's great!

**Comment by jeff-hykin** [comment]
(reposting, originally posted on the wrong thread)

Original:
> Not sure if you want this reported here or a new issue, but I believe currently webpages override built-in browser shortcuts.

> Ex: I'm cycling through workspaces with meta+shift+e, but then I hit a google spreadsheet tab, and then it gets trapped. I've got to make a new tab in order to continue cycling through workspaces.

> Notes
> - I bet it won't be a super-easy fix because the settings tab needs to capture user input when re-binding shortcuts
> - For MacOS, a fix (that I would also love for other reasons) could be to put the shortcut-actions in the top bar (the File,Edit,View,History,etc). If its in the top bar, then a MacOS system shortcut can be made to select the option, and it should take precedence over the webpage shortcuts.

Update:

> Ah I didn't realize what I was complaining about was actually standard behavior in Firefox, which probably added to the confusion. Maybe my thing is more of a feature request.

> To clarify what I meant:
> Expected behavior: CMD+R always reloads the page, unless focused on the bind-a-key in the settings panel
Actual behavior: CMD+R reloads except on pages, like Microsofts online-excel, where the webpage makes its own binding

**Comment by HarryHeres** [comment]
Continuing in [https://github.com/zen-browser/desktop/issues/1629](https://github.com/zen-browser/desktop/issues/1629)
