### ISSUE TITLE
Extension Doesn't Work

### ISSUE THREAD

**Issue by tsuliwaensis** [zen-browser/desktop#1366]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The add-on [Cookie AutoDelete](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete) doesn't work in Zen as it does in Firefox. It is missing several options that are present in FF but not Zen. It seems that the add-on doesn't recognize Zen as version 58+,

![Screenshot 2024-09-09 at 9 07 28 AM](https://github.com/user-attachments/assets/c671e0e4-35c3-42dc-8533-01d547fd692d)

![Screenshot 2024-09-09 at 9 07 41 AM](https://github.com/user-attachments/assets/1746c045-b6cb-422a-9dd3-b74fd6c30fa7)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.39

### What platform are you seeing the problem on?

macOS - Intel

**Comment by mauro-balades** [comment]
What version is zen's extension and what version is firefox's?

**Comment by tsuliwaensis** [comment]
I'm using 3.8.2 on Firefox and Zen

**Comment by Midou36O** [comment]
It doesn't work because zen reports firefox as Firefox 1

Vanilla firefox (don't mind the outdated version):
![image](https://github.com/user-attachments/assets/c10b69f2-9a4b-4c7d-84fa-8be8ac8a8b2e)

Zen browser:
![image](https://github.com/user-attachments/assets/c5ebe900-2b36-463c-aec3-91ef0b3a633c)

**Comment by tsuliwaensis** [comment]
Is the issue that the extension is not reading the version properly or is it Zen not reporting the version correctly?

**Comment by sistemforum** [comment]
i use zen browser too. i dont clear localdb indexed etc records.  where is the problem? zen browser or cookie autodelete plugin?

**Comment by RayZ3R0** [comment]
Does this still happen on latest version? (a.14 as of this comment)

**Comment by sistemforum** [comment]
yes it still happen on a.14. 

debug information writes on Cookie AutoDelete Extension::
- OS: x86-64 Windows (Please add OS version on paste)
- Browser Info: Firefox 1 (20241027221213)
- CookieAutoDelete Version: 3.8.2

**Comment by RayZ3R0** [comment]
That's odd, we'll look into it

**Comment by bejd** [comment]
Also experiencing this. For reference, here's the closed issue on CAD: https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/1644

> You'll need to ask Zen browser to change how they are returning the browser version.

**Comment by mr-cheffy** [comment]
Fixed for the next release, thanks!
