### ISSUE TITLE
Generally laggy

### ISSUE THREAD

**Issue by itsTyrion** [zen-browser/desktop#1368]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I'm just getting lag/stutter in general, be it in animations or when scrolling. Reproducible with a separate profile without extensions.
Am I just missing something?

https://github.com/user-attachments/assets/166d26f1-8292-4a91-a3dd-fe1ece6322cc

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.39

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
What extensions do you have?

**Comment by itsTyrion** [comment]
I can give you the list, but I can exactly reproduce the stutter seen in the video in a new, blank browser profile without any extensions or themes/components from the Zen store. 

I chose the `Optimized` installer.
I run Windows 11 22H2, most relevant specs are: Ryzen 5 5600, 16GB RAM (2x 8GB DDR-3200), GTX 1070

**Comment by JosueGalRe** [comment]
Are you using Windows Defender perhaps? Have you tried adding an exception for Zen in Windows Defender?

**Comment by Stryxus** [comment]
> I can give you the list, but I can exactly reproduce the stutter seen in the video in a new, blank browser profile without any extensions or themes/components from the Zen store.
> 
> I chose the `Optimized` installer. I run Windows 11 22H2, most relevant specs are: Ryzen 5 5600, 16GB RAM (2x 8GB DDR-3200), GTX 1070 edit: Anything I'm missing or can provide/do to narrow it down?

If you are using NVIDIA's Vsync Fast or Max Frame Rate, it will do this on any browser.

**Comment by mauro-balades** [comment]
Does it still happen if you install [https://zen-browser.app/themes/c6813222-6571-4ba6-8faf-58f3343324f6](https://zen-browser.app/themes/c6813222-6571-4ba6-8faf-58f3343324f6)?

**Comment by itsTyrion** [comment]
> If you are using NVIDIA's Vsync Fast or Max Frame Rate, it will do this on any browser. So, if you have them on, you need to disable them for the zen.exe

Dammit, I was THIS close to getting it while recording - I thought "it's almost like there's an FPS cap" - apparently, the nvidia drivers always detect Zen as being in the background and apply the `Background Application Framerate` cap to it. Thanks, nvidia?
