### ISSUE TITLE
compact mode hard to use while windowed

### ISSUE THREAD

**Issue by n7itro** [zen-browser/desktop#1371]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

If the browser is windowed, it's hard to make the top bar and the tab sidebar appear while in compact mode. The trigger is too small when windowed

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0.39

### What platform are you seeing the problem on?

Linux, Windows

**Comment by poeck** [comment]
For now, I believe the best approach is to implement shortcuts for toggling the sidebar and topbar when in windowed mode.

In my opinion, it would be great to introduce a preference option that, when enabled, automatically disables compact mode when switching to windowed mode and re-enables it when returning to fullscreen.

**Comment by clembu** [comment]
> In my opinion, it would be great to introduce a preference option that, when enabled, automatically disables compact mode when switching to windowed mode and re-enables it when returning to fullscreen.

I mostly use compact mode to have floating media windows with reduced chrome, so I fully disagree.

A bigger trigger zone also would simply make the top of the page (therefore most navigation bars) unusable, Right now I use the toggle-toolbar shortcut and it works fine.

**Comment by mauro-balades** [comment]
This has been fixed for the next release, thanks!
