### ISSUE TITLE
Dragging a tab to the web panels icons adds undefined to the icons

### ISSUE THREAD

**Issue by m3957** [zen-browser/desktop#1373]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When dragging a tab from the tab bar to the web panels, "undefined" text appears everywhere in the icons. I find it only does that when dragging on an icon, not on an empty space.

https://github.com/user-attachments/assets/6512ca45-e415-4dda-9639-1d3ea3554de3

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.39

### What platform are you seeing the problem on?

macOS - Intel

**Comment by mauro-balades** [comment]
I dont know why but i've found this funny... anyways, it has been fixed for the next release
