### ISSUE TITLE
There is a gray border in fullscreen video.

### ISSUE THREAD

**Issue by iWisp360** [zen-browser/desktop#1376]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

In the right side and down side there is a small gray bar.

![Screenshot from 2024-09-10 20-04-11](https://github.com/user-attachments/assets/f0c6f634-925c-4446-8f1a-a86f5adefb02)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0

### What platform are you seeing the problem on?

Linux

**Comment by sjclayton** [comment]
Same here, Linux also on version 1.0.0.a.39

**Comment by Obstidian** [comment]
#1362
