### ISSUE TITLE
Clicking "+" to open a new tab doesn't move/jump to the new created tab

### ISSUE THREAD

**Issue by itstamimi** [zen-browser/desktop#1377]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

If you click the "+" button in the vertical tabs area, it does open a new tab, however, it doesn't move to that new tab in the tab list, and you would have to manually scroll down until you reach the new tab, annoying if you have plenty of tabs. In firefox, once a new tab button is clicked, it jumps to that new one automatically.
Additionally, clicking CTRL+T will behave normally and supposed to be, by jumping into the new tab, the issue is when you click the new "+" button.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.39 (64-bit)

### What platform are you seeing the problem on?

Linux, Windows

**Comment by sjclayton** [comment]
@itstamimi

New tab button works as expected (focusing the newly created tab) for me here on a.39 on Linux running KDE Plasma.
