### ISSUE TITLE
Allow installation of unsigned extensions

### ISSUE THREAD

**Issue by mayemu** [zen-browser/desktop#138]
### What feature would you like to see?

Allowing the installation of extensions from a file that is not signed by Mozilla. 

### What platform are you seeing the problem on?

Windows

### Additional context

This is a feature that is only available on Firefox ESR, Developer, and Nightly additions. But as many Firefox forks are based on these versions (ie Floorp and Waterfox based on ESR), the installation of unsigned extensions came included. But as I assume this is built on the main build of Firefox, even using `xpinstall.signatures.required = false` in about:config does not allow for installing unsigned extensions. 

This is one of the things I miss from Floorp, and here are some of my use cases for this feature:
[Bypass Paywalls Clean by bpc-clone](https://github.com/bpc-clone/bypass-paywalls-firefox-clean)
[OldTwitter by dimdenGD](https://github.com/dimdenGD/OldTwitter)
[OldTweetDeck by dimdenGD](https://github.com/dimdenGD/OldTweetDeck)
I find these extensions to be very useful powerful tools, and the only reason Mozilla does not sign them is likely to avoid legal scrutiny with X (Twitter) or publishing companies.

Also, as an extension developer, this would be a very nice feature as Zen does not have an official development build I believe. So it would be nice to have this functionality to test extensions, especially to see how they work with Zen's unique sidebar experience!

As always, keep up the incredible work with the browser!

**Comment by mauro-balades** [comment]
Fixed with https://github.com/zen-browser/desktop/commit/741cfd7af437da25fd05de340b3548059b854f82, thanks a lot! It will be applied for the next release

**Comment by mayemu** [comment]
You are awesome man ❤️❤️
