### ISSUE TITLE
Close and minimize shifted to the left

### ISSUE THREAD

**Issue by mzomparelli** [zen-browser/desktop#1382]
### Captchas

- [ ] I have read the instructions.
- [ ] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

Whose idea was it to shift the close and minimize to the left? Put it back in the right corner where it's supposed to be. I have to stop using this browser because of that dumb decision. Let me know when you8 put it back where it goes.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.34

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
Could you send a screenshot? Its on the right by default... Do you have any themes or userChrome.css?

**Comment by mauro-balades** [comment]
Please do read the captchas before posting and try to be respectful.
