### ISSUE TITLE
It doesn't work on sonoma 14.6.1

### ISSUE THREAD

**Issue by fluo-re** [zen-browser/desktop#1383]
### Captchas

- [ ] I have read the instructions.
- [ ] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

![image](https://github.com/user-attachments/assets/b579d02d-ca00-4e4e-8169-cda5c75ab29e)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Macbook m2 Sonoma 14.6.1

### What platform are you seeing the problem on?

macOS - aarch64

### Relevant log output

```shell
00000000
```

**Comment by mauro-balades** [comment]
Any steps you did in order to get to this point?

**Comment by nickvisut** [comment]
FWIW it works fine for me on Macbook Pro M1 Pro Sonoma 14.6.1
