### ISSUE TITLE
Cannot Login Twitter

### ISSUE THREAD

**Issue by gitartiman2499** [zen-browser/desktop#1384]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I Cannot login normally in twitter it loads endlessly however when logging in with google it works, i have tried incognito with no extensions and it still did not work

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.39

### What platform are you seeing the problem on?

Windows

**Comment by Logghelias** [comment]
The issue lies with Enhanced Tracking Protection, accessed on this icon shown below. Disabling it will allow you to log in

![image](https://github.com/user-attachments/assets/2d260c0c-8d75-4df9-80d2-e56e3401ffe6)

**Comment by mauro-balades** [comment]
^^^
