### ISSUE TITLE
Styling issue with checkboxes in context menus

### ISSUE THREAD

**Issue by ogelbw** [zen-browser/desktop#1385]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When check boxes appear in the context menus (ie most of the right click menus) they overlap with icons or have multiple check marks.

See image below of the right click menu on a extension:
![image](https://github.com/user-attachments/assets/3d55dd5d-7362-4ae4-88e7-b5a882745d9c)

Further detail:
Desktop environment: Plasma 6.1.4
linux os: Arch Linux x86_64  
Theme icons used: [Plasma], breeze-dark [GTK2/3]  (I assume this is the actual cause)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.39

### What platform are you seeing the problem on?

Linux

**Comment by adam-adrian** [comment]
Can confirm this is a problem with GTK
