### ISSUE TITLE
Zen can't start in current virtual desktop.

### ISSUE THREAD

**Issue by pheotry** [zen-browser/desktop#1386]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

1. Close Zen in desktop 1.
2. switch to desktop 2 or other.
3. start zen.

Zen will start in desktop 1 but current desktop (2 or other).

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0 a-39

### What platform are you seeing the problem on?

Windows

**Comment by pheotry** [comment]
My OS is Win11 Pro 24h2 26100.1591

**Comment by MemQu** [comment]
I have the same issue, it hasn't been fixed as of a.14. 

I have to open zen twice to get it to open in the current desktop.
 
Windows version - 23H2 22631.4317
