### ISSUE TITLE
Text Selection and Copy-Paste Formatting Issue in Zen Browser

### ISSUE THREAD

**Issue by MeetMulik31** [zen-browser/desktop#1387]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When copying text from ChatGPT and pasting it into markdown, everything works properly in browsers like Brave and Google Chrome. However, in Zen Browser, there seems to be a problem with properly selecting and copying the text.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0

### What platform are you seeing the problem on?

Windows

**Comment by JosueGalRe** [comment]
Can you provide an example on this? Like screenshots or a video.

**Comment by mauro-balades** [comment]
Does it also happen in firefox?

**Comment by RayZ3R0** [comment]
Closing this issue due to lack of additional information and extended inactivity. Please feel free to reopen with more details if needed. Thank you for your report.
