### ISSUE TITLE
Blur is very laggy

### ISSUE THREAD

**Issue by FormalSnake** [zen-browser/desktop#139]
### What happened?

When scrolling on my website in chrome, it is smooth. When scrolling it in firefox it is good enough but in Zen its horrendous.
This is due to the progressive blur i have, which should be fixed imo.
My website: [FormalSnake.dev](https://www.formalsnake.dev/)
Another example: [jrhu.me](https://jrhu.me/)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.10

### Severity impact

High

### What platform are you seeing the problem on?

macOS

**Comment by mauro-balades** [comment]
Please use the correct tags next time

**Comment by mauro-balades** [comment]
Could you please verify this isn't a problem with firefox too?

**Comment by FormalSnake** [comment]
> Please use the correct tags next time

alright sorry :p

**Comment by FormalSnake** [comment]
> Could you please verify this isn't a problem with firefox too?

After investigation and testing, Firefox has the issue but its much better than in Zen, about 50% better.
It might just be that Zen has performance issues in general since its nightly.

**Comment by gunir** [comment]
Is it the fadein and fadeout effect ?

Firefox-based browsers are usually not as snappy as Chromium, they don't optimize for animation.

You should try a11, it was optimized to be on par with Firefox, if you use a newer hardware, use specific builds.

**Comment by FormalSnake** [comment]
> Is it the fadein and fadeout effect ?
> 
> Firefox-based browsers are usually not as snappy as Chromium, they don't optimize for animation.
> 
> You should try a11, it was optimized to be on par with Firefox, if you use a newer hardware, use specific builds.

alright, and no it is not the fade effects, its the blur. I confirmed this by removing the element in the inspector and then scrolling again.

**Comment by FormalSnake** [comment]
I just updated to a12 and the performance seems to be just as bad

**Comment by mauro-balades** [comment]
It's an issue with firefox, not zen, you should rather contact them
