### ISSUE TITLE
browser semi-randomly crashes when changing preferences of firefox multi account containers

### ISSUE THREAD

**Issue by eepsage** [zen-browser/desktop#1390]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

1. install the official firefox extension https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/
2. create a few containers
3. go to about:addons
4. click the multi account containers extension
5. go to "preferences"
6. change the option "container to open with keyboard shortcut 1" to a few different values
7. browser crashes on one of the changes

running debian 12 with sway, using the flatpak version

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.39

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
im not sure where to get a log but willing to provide if someone explains
```

**Comment by mauro-balades** [comment]
I dont seem to be able to reproduce, is there a way you could run it from the terminal and show it's output¿

**Comment by eepsage** [comment]
> I dont seem to be able to reproduce, is there a way you could run it from the terminal and show it's output?

```
$ flatpak run io.github.zen_browser.zen --log
Crash Annotation GraphicsCriticalError: |[0][GFX1-]: Wayland protocol error: error marshalling arguments for start_drag (signature ?oo?ou): null value passed for arg 1
 (t=23.5457) [GFX1-]: Wayland protocol error: error marshalling arguments for start_drag (signature ?oo?ou): null value passed for arg 1

Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Crash Annotation GraphicsCriticalError: |[C0][GFX1-]: CompositorBridgeChild receives IPC close with reason=AbnormalShutdown (t=20.9721) Exiting due to channel error.
Exiting due to channel error.
```

**Comment by mauro-balades** [comment]
You could disable wayland. Are you in flatpak, appimage or tar? Or do you know how to do it?

**Comment by eepsage** [comment]
> You could disable wayland. Are you in flatpak, appimage or tar? Or do you know how to do it?

disabled wayland in flatseal
![2024-09-28_14-37-38](https://github.com/user-attachments/assets/e0b22240-4904-48a3-861b-3293708ab780)

the browser no longer crashes, but now whenever my cursor exits the pop up listing containers (including when i click an option), a grey rectangle appears and my cursor changes into a dragging one. this grey rectangle persists until i click something and can't be captured on a screenshot.
![IMG_20240928_144126_861](https://github.com/user-attachments/assets/ebcb4a15-76a2-43b1-bcbe-ace0e3bdce82)

logs don't seem to have anything other than complaining wayland isn't accessible. unless i'm running the command wrong or something.

**Comment by eepsage** [comment]
ok, sorry, this is an issue of firefox on my setup somehow. didn't realize I was testing it on an old version of firefox ESR before, where it wasn't happening. it does happen on a more recent version of firefox.
