### ISSUE TITLE
Some websites backgrounds follow theme's one

### ISSUE THREAD

**Issue by iLiranS** [zen-browser/desktop#1392]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Some websites like LinkedIn sets the background of the website like this, which I guess, is related to the browser settings.
```css
background : var(--artdeco-reset-base-background-transparent)
```
And it just follows the theme for some reason.
I have tried messing with the config and all the settings to override it, nothing worked (except for 3rd party extension like dark reader to override background settings).
Demonstration where the background should be white.

Theme : dark
![image](https://github.com/user-attachments/assets/c77f4cb5-a28d-44c3-85db-94ffaaff35db)
Theme : Zen dream (brown theme color, if I change to blue for example, it will get blue)
![image](https://github.com/user-attachments/assets/62363d66-0917-4f8c-bddc-006b6a59ef22)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Version 1.0.0-a.39 (64-bit) 

### What platform are you seeing the problem on?

Windows

**Comment by Tanay-Kar** [comment]
I had the same problem . Managed to fix that by switching browser.tabs.allow_transparent_browser to false in about:config

**Comment by saminton** [comment]
This is still happening to me on Mac zen build 1.7.2b.

https://raindrop.io/

![Image](https://github.com/user-attachments/assets/3d71d4d7-54a6-460a-90fb-ab1cc88e98ed)

**Comment by mdeloughry** [comment]
This is still happening, take for example  [Laravel Forge](https://forge.laravel.com) can this ticket be reopened please?

<img width="1683" height="1066" alt="Image" src="https://github.com/user-attachments/assets/122d046d-a373-4b3e-8f61-e3b549217503" />

**Comment by iLiranS** [comment]
@DR-DinoMight as Tanay Kar suggested, go to `about:config` and turn `browser.tabs.allow_transparent_browser` to false.

**Comment by mdeloughry** [comment]
> [@DR-DinoMight](https://github.com/DR-DinoMight) as Tanay Kar suggested, go to `about:config` and turn `browser.tabs.allow_transparent_browser` to false.

Appreciate it! Helped me out so do appreciate that thanks!

I guess its just a shame that  people (some non-techie) have to go in to the "scary" config  screen to get the correct solution, so here's hoping it's fixed in the future.
