### ISSUE TITLE
Browser permanently softlocked me & i'm stuck on the ZEN logo.

### ISSUE THREAD

**Issue by ItzASecret** [zen-browser/desktop#1394]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Not sure what exactly I did to be honest, I randomly noticed that opening new tabs and dragging them to different monitors resulted in this screen. And instead of the dragged tab being on my other monitor, the website would just stay where it was despite the tab being a separate window now.

![image](https://github.com/user-attachments/assets/e285c999-dbe1-4475-bd5f-773685ba7f9d)

So I decided to restart the browser, but then the browser window wouldn't even open a tab, it was just this screen again, so now I'm just soft locked looking at this logo. 

Tried updating as well didn't work so I think I have to do a full uninstall. Loving the browser so far, but this is my second day using it and I've run into this issue. I also tried running as admin, but yeah that didn't do much either, nor did I expect it to.

The only thing I've done since the install is rename the default profile to Secret, install like 2-3 extensions ublock, sponsor block etc.. installed like two themes as well. imported my passwords. And I synced my Mozilla cloud thingy. It's really been under light use lol.

im on win 11

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Alpha build - 1.0.0-a.39 (2024-09-09) 

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
I'll make this my priority, don't worry

**Comment by ItzASecret** [comment]
note: the full reinstall did not work.

**Comment by Rian-yes** [comment]
It did once happen to me which was due to me changing sidebar settings in about:config, I resolved it by isolating the prefs.js in %AppData%\Roaming\zen\Profiles\<profile_name>-alpha\  in another folder so that it generates another one.
Well you did mention that you did a full uninstall so i don't think this method is useful.

**Comment by Spurkus** [comment]
This also happened to me. I tried Rian's strategy and it worked initially, but when I started using it, none of the tabs would even load.

**Comment by zo-world** [comment]
Got it working!

I followed @Rian-yes steps, produced @Spurkus results. Only thing found on my research that if hold SHIFT key as you open it. It launches in debug (troubleshoot) mode. After clicking around tabs, repeating open in debug mode. I have been able to successfully operate for the last hour or so on zen back again.

Imagine obviously not permanent fix, but a workaround ;) @mauro-balades  Thank you for such an amazing product, Chatbot AI on the sidebar has been a game changer for me.

**Comment by mauro-balades** [comment]
I still would like to have some terminal output, if anyone has it available, please tell me

**Comment by Rian-yes** [comment]
Well that's good that my method somewhat worked but this problem happened to me because i directly edited "zen.sidebar.data" in about:config and didn't properly check its structure (I don't have that much knowledge on how does the file affect the browser).

@Spurkus I had manually cut out parts of pref.js to find which setting had made a problem (I was experimenting with config settings before) , When i found that it was the zen.sidebar.data, i replaced that setting to default and put my original pref.js back.

@mauro-balades I don't know where the terminal output appears on the browser, Is it something Linux specific? Because I am on Windows 10.

**Comment by mauro-balades** [comment]
wait, you changed `zen.sidebar.data` directly?

**Comment by Rian-yes** [comment]
@mauro-balades yep my fault was experimenting tho i dont think my problem is related to @ItzASecret

**Comment by faw01** [comment]
having the same issue as this once i updated to version 1.0.1-a.10 (latest version as of 16/10/2024)

was not fixed with a reinstall or a clean uninstall and install, restart, running on debug mode, nothing

was working absolutely fine beforehand but now i stare into the abyss of zen

![image](https://github.com/user-attachments/assets/b299858b-7891-430d-9867-4f503d68a863)

**Comment by mr-cheffy** [comment]
What you can do is go to your profile directory in about:profiles. Make a backup of your prefs.js file. Delete it and start zen. After than, close zen and restore your backup. It should be working again

**Comment by faw01** [comment]
writing this on the zen browser, thanks a bunch mauro! 

that did the trick, although im not sure what caused this to happen - my extensions, history, mods are all there, tabs are gone but i can pin them again

**Comment by ahatherley** [comment]
i am having the same issue on linux, ubuntu, with both versions
I have found that with the portable installer, if i run it from the file, it works, but if i try pinning it, it gets stuck.

Any help please?

**Comment by zeyrie** [comment]
Having the same issue in macOS 15.1 Beta (24B5055e), I know in beta apps might not work properly, just commenting here for tracking, also unable to submit feedback from the details screen, as it opens the link within zen browser; 🤷🏼‍♂️

By the way, loving the fact that zen browser exist as an alternative for Arc browser( chromium browser ), keep up the work guys 🎆
<img width="1399" alt="image" src="https://github.com/user-attachments/assets/9714ce73-782e-49ed-b240-942751748498">

Zen browser details
<img width="763" alt="image" src="https://github.com/user-attachments/assets/f3a8c9e1-253a-41ea-915e-d66599eb4e83">

**Comment by RayZ3R0** [comment]
Does this still happen on latest version? (a.14 as of this comment)

**Comment by ethanling123** [comment]
I am on 1.0.1-a.16 and it just happened to me. Launching in debug mode didn't change anything. 

<img width="973" alt="image" src="https://github.com/user-attachments/assets/350ba4f8-ae7a-4e1d-adb0-be419daa0dcc">

<img width="644" alt="image" src="https://github.com/user-attachments/assets/d1386e1a-ae9a-4274-b592-67023e69e493">

**Comment by yofriadi** [comment]
is there anything we can do to make it work again in the meantime?
uninstalling didn't solve it

**Comment by RayZ3R0** [comment]
you need to move the prefs.js file to another folder, open Zen again, then add it back. This should have been fixed though, this is weird

**Comment by mr-cheffy** [comment]
@RayZ3R0 what should we do with this issue then?

**Comment by RayZ3R0** [comment]
> @RayZ3R0 what should we do with this issue then?

Why are you asking me 😭 wasn't this fixed?

**Comment by ItzASecretBoi** [comment]
Well at least we somewhat know where the problem lies & how to fix it. Probably has something to do with a corrupted preferences file or something

**Comment by pivoshenko** [comment]
Hey guys! I also faced this issue on MacOS after adding a new profile.
But then I just removed all configs from `~/Library/Library/Application Support/zen` and it helped.
I know it's a harsh solution but mb for someone that have nothing to lose, it can be helpful

**Comment by alejlatorre** [comment]
Finally I found something related to this. Definitely love Zen and the last 2 days I have been trying other options (I have been using OperaGX but I want something more minimalist with a good UI/UX. I didn't like Arc, Orion, Vivaldi or Brave). Unfortunately, I had this weird bug and reinstall a lot of times, a lot of versions, even I started to use the twilight version because that worked haha.

**Comment by Ighons** [comment]
Hi, guys. I am experiencing the same issue on Windows. The version is a.19. I’ve only been using it for a day, but it’s amazing! I absolutely love Zen X2.

**Comment by salamijason** [comment]
while this bug is still being tested and fixed, trying a new zen profile will likely mitigate the issue. Check [this](https://docs.zen-browser.app/guides/manage-profiles) for more info on how to move over your data.

**Comment by mr-cheffy** [comment]
If anyone keeps having this issue, PLEASE let me know by opening a new issues. Remember to try backing up your prefs.js, close zen, deleting it, open and close zen and restoring your prefs.js. Thanks!

**Comment by itsparser** [comment]
Hey i Still Having the same issue in the Zen 1.8.2b

**Comment by salamijason** [comment]
Hey @eenthiran have you tried what cheff suggested above?

> Remember to try backing up your prefs.js, close zen, deleting it, open and close zen and restoring your prefs.js.

Or trying a new [profile](https://docs.zen-browser.app/guides/manage-profiles).

If the issue persists, I'll reopen the issue.

**Comment by itsparser** [comment]
> Hey [@eenthiran](https://github.com/eenthiran) have you tried what cheff suggested above?
> 
> > Remember to try backing up your prefs.js, close zen, deleting it, open and close zen and restoring your prefs.js.
> 
> Or trying a new [profile](https://docs.zen-browser.app/guides/manage-profiles).
> 
> If the issue persists, I'll reopen the issue.

@salamijason yes, after deleting the profile it was working fine thanks
