### ISSUE TITLE
Core dumped

### ISSUE THREAD

**Issue by fer0li** [zen-browser/desktop#1396]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When I try to run zen on Linux it returns:
```
[1]    182106 illegal hardware instruction (core dumped)  zen
```

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.37

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
Please use the generic version, your cpu is not supported. thanks!
