### ISSUE TITLE
Can't create more than 8 Web Panel Tabs

### ISSUE THREAD

**Issue by Muko-Tabi** [zen-browser/desktop#1397]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

As per description, I can't create more than 8 Web Panel Tabs. The add button disappear after I have 8 of them.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.39

### What platform are you seeing the problem on?

Linux

**Comment by sortofsleepy** [comment]
Just wanted to bump this issue - 8 sites is pretty limited given how much space is still left over. 

Not sure if it was done for aesthetic reasons or for a different reason, but even if I shrink the browser window to the absolute minimum, there's definitely enough room for at least 2-3 more sites. 

EDIT - ah, ok, this will probably get lost in the ether; thought it might re-open things. In any case, I think the point still stands.
