### ISSUE TITLE
latest app not launching

### ISSUE THREAD

**Issue by samarthverma11** [zen-browser/desktop#1398]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

after installing the latest software i doesnt lauches the application itself and says the followng "the application was unable to start corrrectly (0xc0000142
![Capture](https://github.com/user-attachments/assets/72d85a9a-8537-4a09-97c5-c6fec7052ba5)
)"

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.39

### What platform are you seeing the problem on?

Windows

**Comment by n7itro** [comment]
Try the generic version of Zen

**Comment by mauro-balades** [comment]
Yeah, your CPU is not supported, please download the generic version
