### ISSUE TITLE
DragEvent.dataTransfer.files contains useless string objects instead of files

### ISSUE THREAD

**Issue by 0815fips** [zen-browser/desktop#1399]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Dragging files from Nautilus (Gnome file manager) into a website gives me a DragEvent containing a DataTransferItemList with exactly two string DataTransferItems as shown in the log below, no matter how many files are dragged in.

DragEvent.dataTransfer.files should contain the actual files.

Works fine on Chromium and Firefox.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.37 (64-bit)

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
DataTransferItemList { 0: DataTransferItem, 1: DataTransferItem, length: 2 }
​0: DataTransferItem { kind: "string", type: "text/x-moz-url" }
​​kind: "string"
​​type: "text/x-moz-url"
​​<prototype>: DataTransferItemPrototype { getAsString: getAsString(), getAsFile: getAsFile(), webkitGetAsEntry: webkitGetAsEntry(), … }
​1: DataTransferItem { kind: "string", type: "text/plain" }
​​kind: "string"
​​type: "text/plain"
​​<prototype>: DataTransferItemPrototype { getAsString: getAsString(), getAsFile: getAsFile(), webkitGetAsEntry: webkitGetAsEntry(), … }
​length: 2
​<prototype>: DataTransferItemListPrototype { add: add(), remove: remove(), clear: clear(), … }
main.js:12400:15
```

**Comment by mauro-balades** [comment]
Isn't it just this? https://developer.mozilla.org/en-US/docs/Web/API/DataTransferItem

**Comment by 0815fips** [comment]
### Did you even try it? In **Gnome** on **Ubuntu**?
Just go to https://snapdrop.net and see for yourself. If you drag files into the website, Zen will just try to open them. Same happens for my application, but I use preventDefault() and so, It logged the faulty DragEvent to the console, which you can see in the section "log output".

I attached files showing the console log for dragged text vs. files. Seems like it only tries to open the first file dragged in, therefore it always results in these two string in the event.

![dropping-files](https://github.com/user-attachments/assets/c2e9c801-d816-4cfb-ae47-db5e3e7d59db)
![dropping-text](https://github.com/user-attachments/assets/ef243820-4825-4f00-9f84-ec8a35feae78)

The html I added is straight from MDN. I just added the event itself to the console log. 

```<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <style>
    #drop_zone {
      border: 5px solid blue;
      width: 200px;
      height: 100px;
    }
  </style>
  <script>
    function dropHandler(ev) {
      console.log("File(s) dropped", ev);

      // Prevent default behavior (Prevent file from being opened)
      ev.preventDefault();

      if (ev.dataTransfer.items) {
        // Use DataTransferItemList interface to access the file(s)
        [...ev.dataTransfer.items].forEach((item, i) => {
          // If dropped items aren't files, reject them
          if (item.kind === "file") {
            const file = item.getAsFile();
            console.log(`… file[${i}].name = ${file.name}`);
          }
        });
      } else {
        // Use DataTransfer interface to access the file(s)
        [...ev.dataTransfer.files].forEach((file, i) => {
          console.log(`… file[${i}].name = ${file.name}`);
        });
      }
    }

    function dragOverHandler(ev) {
      console.log("File(s) in drop zone");

      // Prevent default behavior (Prevent file from being opened)
      ev.preventDefault();
    }

  </script>
</head>
<body>
  <div
  id="drop_zone"
  ondrop="dropHandler(event);"
  ondragover="dragOverHandler(event);">
  <p>Drag one or more files to this <i>drop zone</i>.</p>
</div>
</body>
</html>
```
