### ISSUE TITLE
Left toolbar won't disappear in 'Compact Mode'

### ISSUE THREAD

**Issue by onthejobtraining** [zen-browser/desktop#1400]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

This issue doesn't always occur but sometimes the left toolbar doesn't hide automatically when 'compact mode' is enabled. Here's a screen recording of the event:

https://github.com/user-attachments/assets/db5f4c6c-cf58-4fa0-b2d3-07de022e5b64

As you can see, the toolbar just won't go away, and I tried switching between compact and normal mode. The only way to fix this is to restart the browser, but it's not always viable.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.39

### What platform are you seeing the problem on?

Windows

**Comment by poeck** [comment]
It looks like the behavior you're describing is actually intended. In `about:preferences#zenCKS`, under the section **Compact Mode Actions**, you can assign a keybind for "Toggle Compact Mode Sidebar". Once set, this keybind will allow you to easily show or hide the sidebar while in compact mode.

**Comment by mauro-balades** [comment]
^^^
