### ISSUE TITLE
SPOTIFY SONGS NOT PLAYING.

### ISSUE THREAD

**Issue by subh2155** [zen-browser/desktop#1401]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

**_SPOTIFY SONGS NOT PLAYING._**YTREYERUHEUIJEGIENGEIONGEIHJGEHJTEHJEUTHEHYEUYHUHHEEUREDRHGNEHEUHGUEHGUEUHGEUGHEHGEDHGUEHNGEDUNHGEUHUEIHGIEUHERUIHUIEHEIUIHUEUIHEUHUEU

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0.39

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
SPOTIFY SONGS NOT PLAYING.UGPJGPLJGOJGKKDFHODFHJRHOIJJJJJJJJJJJJJJJJJJJJJJJJJJFDHFSDFDIJKFDHFOKHFOKHFKFODPKHKFHOPFKHOPHOPFHKFKHFHKFHFKOFDHFDHFHFOHKFHKFDHOFHKFDHKFOHKFDOKHFKHFOHFKDTHKFHKFDKHFDKFDKHFDKHFKFKJFD
```

**Comment by mauro-balades** [comment]
I'm just...
