### ISSUE TITLE
Wrong root directory shown in "About Profiles"

### ISSUE THREAD

**Issue by poeck** [zen-browser/desktop#1402]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

In the "About Profiles" tab, the application is displaying the following path as the root directory:

`/home/paul/.zen/vys9fzta.Default Profile`

However, the `/home/paul/.zen` directory does not exist on my system.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

130

### What platform are you seeing the problem on?

Linux

**Comment by JosueGalRe** [comment]
If you add a new profile, the .zen folder still not there? also, how did you install zen?

**Comment by poeck** [comment]
> If you add a new profile, the .zen folder still not there? also, how did you install zen?

Just tried adding a new profile, but the folder still doesn't exist. 

I installed Zen via flatpak.

Not sure if I was clear enough before, the profiles work great - it's just that the path is wrong and the `~/.zen` directory somehow doesn't exist.

**Comment by poeck** [comment]
I just tried to install it via AppImage and this actually created the `~/.zen` folder. Honestly not really familiar with flatpak (I think Zen was actually the first thing I ever installed with flatpak), but I assume it has something to do with the sandbox.

I'll leave it open for now, maybe there is some way to clarify that its a sandbox directory or display the actual path instead?

**Comment by Muko-Tabi** [comment]
This seems like a Firefox/Flatpak [issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1625111) more than a Zen issue

**Comment by poeck** [comment]
> This seems like a Firefox/Flatpak [issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1625111) more than a Zen issue

True, will close this issue here. Thanks everyone!
