### ISSUE TITLE
[blur][1.0.0.a.39-1] blury full screen on ultra wide screen

### ISSUE THREAD

**Issue by DrummyFloyd** [zen-browser/desktop#1403]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

seems to be an issue upon ultrawide screen like samsung G9
once i'm on full screen , the rendering is blurry.

![image](https://github.com/user-attachments/assets/6712134e-69d3-4857-b322-dea7eb7b52f3)
![image](https://github.com/user-attachments/assets/4e0d889f-8d04-4eeb-a775-6863bb25a695)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0.a.39

### What platform are you seeing the problem on?

Linux
EDIT: tested also on w11 23h2 , and the blur is present too

**Comment by lemon07r** [comment]
![image](https://github.com/user-attachments/assets/3641c9c6-76f2-4a9c-a462-322a68727623)
I have a double wild screen too, just a little different resolution and aspect ratio (32:10, 3840*1200). I don't have this issue on Windows. I think your issue might be linux specific. My fedora machine has kicked the bucket so I can't this myself sadly.

**Comment by swkoyo** [comment]
Same thing for me, 5120x1440 monitor and text is blurry on full screen. This isn't happening with firefox.

Zen
![2024-09-13T11:15:16,319809664+09:00](https://github.com/user-attachments/assets/987e1506-0d44-444e-bccc-123276539c72)

Firefox
![2024-09-13T11:15:26,958693391+09:00](https://github.com/user-attachments/assets/ea49b917-88e1-4698-b35b-39bdb5351a8f)

**Comment by DrummyFloyd** [comment]
> ![image](https://private-user-images.githubusercontent.com/12001338/367080637-3641c9c6-76f2-4a9c-a462-322a68727623.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMTA4MjUsIm5iZiI6MTcyNjIxMDUyNSwicGF0aCI6Ii8xMjAwMTMzOC8zNjcwODA2MzctMzY0MWM5YzYtNzZmMi00YTljLWE0NjItMzIyYTY4NzI3NjIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDA2NTUyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwOGY5MTU4Y2E0M2Q0YjkwZmJlMjVkYzBjZjg3NmMxMGVjZGIwNzA4ODVjNWQ3ZWRkMWU2MGFmMGVmOTE0ZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rdQg_fbMaNeNJ5EpYLMjte6rhwSNgHAyRj77Lss9LPQ) I have a double wild screen too, just a little different resolution and aspect ratio (32:10, 3840*1200). I don't have this issue on Windows. I think your issue might be linux specific. My fedora machine has kicked the bucket so I can't this myself sadly.

it could be linux, specific and or Wayland specific , but none of them happnd on Firefox =)

**Comment by hadiskeini** [comment]
Known issue, not just affecting Linux and there are a few tickets for it open like #440.

**Comment by mauro-balades** [comment]
Yeah, please try to not create a lot of duplicates...
