### ISSUE TITLE
nixpkgs: cannot be inited:

### ISSUE THREAD

**Issue by s0me1newithhand7s** [zen-browser/desktop#1408]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

how we get here:
1. instead of `package-lock.json` we have `pnmp-lock.yaml`
2. instruction says to use `npm` - that a lie due of 1

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.39

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
┏━ 1 Errors: 
┃ error: builder for '/nix/store/vnpb2f604yhag74k0d9wfqgs10474by1-zen-browser-1.0.0-a.39-npm-deps.drv' failed wi…
┃        last 10 log lines:
┃        > no configure script, doing nothing
┃        > Running phase: buildPhase
┃        >
┃        > ERROR: The package-lock.json file does not exist!
┃        >
┃        > package-lock.json is required to make sure that npmDepsHash doesn't change
┃        > when packages are updated on npm.
┃        >
┃        > Hint: You can copy a vendored package-lock.json file via postPatch.
┃        >
┃        For full logs, run 'nix log /nix/store/vnpb2f604yhag74k0d9wfqgs10474by1-zen-browser-1.0.0-a.39-npm-deps…
┣━ Dependency Graph:
┃ ┌─ ⚠ zen-browser-1.0.0-a.39-npm-deps failed with exit code 1 after ⏱ 0s in buildPhase
┃ ⏸ zen-browser-1.0.0-a.39
┣━━━ Builds         
┗━ ∑ ⏵ 0 │ ✔ 0 │ ⏸ 1 │ ⚠ Exited after 1 build failures at 22:05:12 after 2s
```

**Comment by JosueGalRe** [comment]
Can you provide more information on this? AFAIK there's no official Nix Flake for Zen

**Comment by s0me1newithhand7s** [comment]
> Can you provide more information on this? AFAIK there's no official Nix Flake for Zen

what do you need? this is my own `package.nix` for nixpkgs.

**Comment by JosueGalRe** [comment]
> > Can you provide more information on this? AFAIK there's no official Nix Flake for Zen
> 
> what do you need? this is my own `package.nix` for nixpkgs.

Sorry, can't you use pnpm for this? Or the issue is to replace npm in favor of pnpm in instructions?

**Comment by s0me1newithhand7s** [comment]
> > > Can you provide more information on this? AFAIK there's no official Nix Flake for Zen
> > 
> > 
> > what do you need? this is my own `package.nix` for nixpkgs.
> 
> Sorry, can't you use pnpm for this? Or the issue is to replace npm in favor of pnpm in instructions?

replacing it would be nice, bc for now i can just trow pnpm for drop-in npm replace.

**Comment by mauro-balades** [comment]
Sorry but I dont know anything about nix, I didnt even know there was a nix package. You should report it to whoever made it. Sorry...

**Comment by s0me1newithhand7s** [comment]
> Sorry but I dont know anything about nix, I didnt even know there was a nix package. You should report it to whoever made it. Sorry...

my guy, i'm trying to do nix package, and stubled across problem with building sequence. it's misleads, bc there is "pnpm-lock.yaml", not the "package-lock.yaml". all i ask here - clarification. nix ralated job will be on my shoulders, not yours.

**Comment by mauro-balades** [comment]
ahh, sorry.... Yeah, this project uses pnpm, not npm

**Comment by s0me1newithhand7s** [comment]
yep! now it's makes more sense. i'll try with pnpm tommorow and report back here. thanks for support me here.

**Comment by mauro-balades** [comment]
Please close the issue if it has been resolved

**Comment by s0me1newithhand7s** [comment]
> Please close the issue if it has been resolved
i close it rn, as zen marked as "not planned" in nixpkgs

**Comment by Dementor430** [comment]
It should be noted that Mozilla's "Mach" utility doesn't even have NixOS support yet. So even if you tried building it, there will be no way to do so cleanly without asking Mozilla to patch mach first. This is also unlikely as they want to deprecate Mach in the future.

**Comment by s0me1newithhand7s** [comment]
> It should be noted that Mozilla's "Mach" utility doesn't even have NixOS support yet. So even if you tried building it, there will be no way to do so cleanly without asking Mozilla to patch mach first. This is also unlikely as they want to deprecate Mach in the future.

but we have like 10+ firefox variants in nixpkgs xdxd

**Comment by Dementor430** [comment]
Ok, do you know a way to make it work? Cuz I would be happy to use zen :3
