### ISSUE TITLE
Issue with sudo-flix Extension on Zen Browser

### ISSUE THREAD

**Issue by Darknight92228** [zen-browser/desktop#1409]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I am encountering an issue where the sudo-flix extension is not functioning correctly on Zen Browser. After installation and enabling the extension, it fails to assist with finding/loading sources on the website https://pseudo-flix.pro/.

Steps to Reproduce:

	1.	Download the sudo-flix extension from this [link](https://github.com/sussy-code/browser-ext/releases/download/1.2.0/1.2.0-mwext-FIREFOX.xpi).
	3.	Install the extension on Zen Browser.
	4.	Enable the extension.
	5.	Visit https://pseudo-flix.pro/.
	6.	Attempt to search for or load sources.

Expected Behavior:
The extension should help load the necessary sources on the website.

Actual Behavior:
The extension does not seem to work, as it is unable to find or load the required sources.
![image](https://github.com/user-attachments/assets/afb4987b-9a23-4b7b-a8b6-988c8b187fef)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.39 (64-bit)

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by JosueGalRe** [comment]
Can you try the extension in a new profile?

**Comment by n7itro** [comment]
That extension and the website work for me on Zen v39. 
Are you sure this is not related to the recent denial of service attack on `sudo-flix`?

Could you try https://sudo-flix.rip instead of https://pseudo-flix.pro ?
