### ISSUE TITLE
Floating URL Bar text selection

### ISSUE THREAD

**Issue by CcMenta** [zen-browser/desktop#141]
### What happened?

When 'Floating URL Bar when focused' is enabled when you select the url bar think you still hold the mouse and instead of selecting the whole text it selects the part that you hover over in the url bar.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

alpha 11

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by IAmJafeth** [comment]
Same behavior happens on Linux AppImage version.

I am running Ubuntu 24.04 LTS, it happens in both Wayland and X11.

**Comment by IAmJafeth** [comment]
Still happening on a.13 version

**Comment by mauro-balades** [comment]
Moving to https://github.com/zen-browser/theme-components/issues/1
