### ISSUE TITLE
fullscreen video has black border

### ISSUE THREAD

**Issue by KorigamiK** [zen-browser/desktop#1410]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Open a youtube video, the border doesn't disappear around the video.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Mozilla Zen 1.0.0-a.39

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
This has been fixed for the next release, thanks!
