### ISSUE TITLE
Changed language but not effective

### ISSUE THREAD

**Issue by wentlwr** [zen-browser/desktop#1413]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I've changed language to Chinese(Simplified),but UI are still in English
![图片](https://github.com/user-attachments/assets/a1e46b6f-479e-47f9-afad-c3fa02f227da)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
no log
```

**Comment by nazmiyigitefe** [comment]
At [this issue](https://github.com/zen-browser/desktop/issues/1223) Mauro said that, it'll be fixed with 1.0.0-a.40.
