### ISSUE TITLE
Issues with binge due to outdated firefox

### ISSUE THREAD

**Issue by BVengo** [zen-browser/desktop#1414]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I get the following playback error on Binge when using this browser.

![image](https://github.com/user-attachments/assets/cb69864b-4570-4a41-9184-3eb9e4bc1361)

The error code states that it's typically caused by an outdated version of chrome or firefox.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.39 flatpak

### What platform are you seeing the problem on?

Linux

**Comment by ProbablyM-S** [comment]
its most probably drm protected and Zen is based on latest Firefox version. (they always keep it up to date)

**Comment by mauro-balades** [comment]
https://docs.zen-browser.app/faq#why-cant-zen-browser-play-drm-protected-content
