### ISSUE TITLE
Edges on expanded Videos

### ISSUE THREAD

**Issue by whynotmarc** [zen-browser/desktop#1417]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Pretty simple.
When expanding a video (on Youtube as an example) you can still see the browser edges on the bottom and on the right.

Saw it being mentioned in the comments of #1404 but since this is a bit more specific and I don't know if you would want to remove the full corners.

Attached a simple example here (this is an expanded video on Youtube):
<img width="1727" alt="image" src="https://github.com/user-attachments/assets/62181239-7c53-421f-a5ec-8ab48982a742">

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

 Alpha build - 1.0.0-a.39 (2024-09-09) Latest

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by whynotmarc** [comment]
> temporary fix in the meanwhile
> 
> ```css
> :root[ sizemode="fullscreen"] #tabbrowser-tabpanels {
>   padding: 0 !important;
> }
> ```

Which I would put where?

**Comment by mauro-balades** [comment]
This has been fixed for the next release, btw...



> > temporary fix in the meanwhile
> > ```css
> > :root[ sizemode="fullscreen"] #tabbrowser-tabpanels {
> >   padding: 0 !important;
> > }
> > ```
> 
> Which I would put where?

https://docs.zen-browser.app/guides/live-editing#step-4-edit-the-userchromecss-file

**Comment by whynotmarc** [comment]
Perfect, thank you.

> This has been fixed for the next release, btw...
> 
> > > temporary fix in the meanwhile
> > > ```css
> > > :root[ sizemode="fullscreen"] #tabbrowser-tabpanels {
> > >   padding: 0 !important;
> > > }
> > > ```
> > 
> > 
> > Which I would put where?
> 
> https://docs.zen-browser.app/guides/live-editing#step-4-edit-the-userchromecss-file
