### ISSUE TITLE
No icons in bookmark toolbar after import

### ISSUE THREAD

**Issue by jlitz** [zen-browser/desktop#1419]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

i imported bookmarks from html file   import says completed import stating number imported   but  no icons  appear in the  bookmark toolbar    i can add a bookmark   but no  imported abookmards icons ppear

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.39 

### What platform are you seeing the problem on?

Windows

**Comment by NOCanoa** [comment]
it might need some time to cache/load the favicons, and the add the correct version in your issue (ex: 1.0.0-a.39 )

**Comment by jlitz** [comment]
i ended up dragging them  in from the bookmark library
