### ISSUE TITLE
Video call, browser not supported

### ISSUE THREAD

**Issue by egayghost** [zen-browser/desktop#1420]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![image](https://github.com/user-attachments/assets/69059eff-a0e5-41d5-978f-2d9a5fa0c683)

Messenger.com or possibly others as well does not suport video call.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.39 (2024-09-09)

### What platform are you seeing the problem on?

Linux

**Comment by NOCanoa** [comment]
u know it wold help if u specified what app it is, and if it works in ff?

**Comment by egayghost** [comment]
> u know it wold help if u specified what app it is, and if it works in ff?

It's messenger.com tried others as well, seems like video calling is not supported atm.

**Comment by NOCanoa** [comment]
Did it work on ff vanila?

**Comment by egayghost** [comment]
> Did it work on ff vanila?

I'm kinda lost, what do you mean ff vanilla? 😅

**Comment by NOCanoa** [comment]
Normal Firefox Official from Mozila

**Comment by egayghost** [comment]
> Normal Firefox Official from Mozilla

I just checked and damn it does not as well :// 
base issue then...

**Comment by egayghost** [comment]
Did some reading and this should help out 

https://bugzilla.mozilla.org/show_bug.cgi?id=1896361

**Comment by lessload** [comment]
seem like it about gpu driver or drm or etc...

**Comment by egayghost** [comment]
> seem like it about gpu driver or drm or etc...

Nah, check the link I sent

**Comment by LifeAO** [comment]
It's been unsupported since Facebook/Meta launched end-to-end encryption many months ago to many regions over time.
@egayghost 's linked bug report is pretty much under Meta or maybe Mozilla's control.

Nothing much we can do, but wait for changes.

**Comment by Zimon-Kuhs** [comment]
Hello, just wanted to chip in and say that it doesn't seem to work when joining a video call using Teams (web version) either. Since it's at work I'm noticing this I can't share any solid details, but the page crashes when I press join. The preview, where you set mic on/off, camera on/off et.c. is fine, it's when proceeding to joining it crashes.

I understand it's not on Zen's end but rather Mozillas, but in case you need more fuel to the fire here's some. :wink:

**Comment by JTCorrin** [comment]
Just here to reiterate that video calls (for me via Teams) do not work very well.

**Comment by clutterskull** [comment]
Same issue with Teams, choppy video in, my video out is frozen or absent, audio is hitchy. I also would like to add that attempting a voice call from the Google Fi web interface crashes Zen. Both work ok in FF Dev Edition. Linux / Plasma

**Comment by LifeAO** [comment]
@Zimon-Kuhs , @JTCorrin , @clutterskull 

This bug report is about Meta/Facebook Messenger's unsupported video and voice call features on Firefox and Zen. Not a bug, but a problem within the Msgr itself.

The issues you all seem to be having is similar to crash reports that is often found on this Discord bug report ( #394 ) with other users reporting other platforms crashing involving video/voice calls. There are another similar active bug reports too, but is just Discord crashes.
I recommend tuning in from there.

**Comment by LeMoonStar** [comment]
Sadly we don't seem to be able to do anything about this issue. Facebook doesn't support either Zen nor Firefox (see comments above).
