### ISSUE TITLE
Moving Tabs when  'Expand Tabs on Hover' is on uses icons instead of icon+tab name

### ISSUE THREAD

**Issue by Luk45135** [zen-browser/desktop#1421]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Title
![screenshot-2024-09-13-13-42-49](https://github.com/user-attachments/assets/93c971ed-b0a5-409c-b334-c3dcde5d4b84)

I don't think reproducing on Firefox applies here.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.39

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
This has been fixed for the next release in https://github.com/zen-browser/desktop/commit/6ae26931b00498d9ef413566903dd2cc6800ce4e. Thanks!
