### ISSUE TITLE
New Language Support

### ISSUE THREAD

**Issue by crnobog69** [zen-browser/desktop#1423]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Can Serbian language be added (Serbian Cyrillic would be best)? I already have joined on Crowdin. I will translate it. Best regards!

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0

### What platform are you seeing the problem on?

Linux

**Comment by NOCanoa** [comment]
Is this language in native ff?

**Comment by mauro-balades** [comment]
No it isnt, sorry. It's not on the supported language list

**Comment by crnobog69** [comment]
> Is this language in native ff?
> 

It is

**Comment by crnobog69** [comment]
> No it isnt, sorry. It's not on the supported language list

I literally have Firefox on Serbian
