### ISSUE TITLE
New Tab doesn't work 

### ISSUE THREAD

**Issue by Arpit-Moga** [zen-browser/desktop#1425]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I was using zen for a week, and it was working perfectly , But suddenly when I tried to open a new tab today , it just showed like this 

![image](https://github.com/user-attachments/assets/d2f046dc-75e1-4110-9365-1fc6cc3b4fae)

I am not able to type anything , or open anything. I can use shortcuts like ctrl+n , ctrl+o , but I cant interact with the browser or use it anymore.

SYSTEM - Linux fedora 6.10.9-200.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Sun Sep  8 17:23:55 UTC 2024 x86_64 GNU/Linux

ZEN BROWSER VERSION - Downloaded latest flatpak from the store

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
What actions lead you to this?

**Comment by Arpit-Moga** [comment]
> What actions lead you to this?


Just opening the browser

**Comment by mauro-balades** [comment]
Could you try running from the terminal?

**Comment by Arpit-Moga** [comment]
> Could you try running from the terminal and send the output?

How to run from the terminal? I downloaded the flatpak from the store

**Comment by mauro-balades** [comment]
`flapak run io.github...` but with the correct id

**Comment by Arpit-Moga** [comment]
> flapak run io.github.zen_browser.zen

It still behaves like what I have mentioned earlier. On terminal , it show :

❯_: flatpak run io.github.zen_browser.zen
[Child 89, Main Thread] WARNING: Failed to create file monitor for /home/arpit/.var/app/io.github.zen_browser.zen/config/glib-2.0/settings/keyfile: Unable to find default local file monitor type: 'glib warning', file /home/runner/work/desktop/desktop/engine/toolkit/xre/nsSigHandlers.cpp:187

(/app/zen/zen:89): GLib-GIO-WARNING **: 17:59:39.057: Failed to create file monitor for /home/arpit/.var/app/io.github.zen_browser.zen/config/glib-2.0/settings/keyfile: Unable to find default local file monitor type

**Comment by mauro-balades** [comment]
Is that all?

**Comment by Arpit-Moga** [comment]
yes

**Comment by mauro-balades** [comment]
What about `flatpak run --command=sh io.github.zen_browser.zen`

**Comment by Arpit-Moga** [comment]
It seems to open a shell . What am I supposed to do with it ?

**Comment by mauro-balades** [comment]
No, sorry, try `flatpak run io.github.zen_browser.zen --safe-mode`

**Comment by Arpit-Moga** [comment]
It still behaves the same way . Here's the log:



❯_: flatpak run io.github.zen_browser.zen --safe-mode
Crash Annotation GraphicsCriticalError: |[0][GFX1-]: RenderCompositorSWGL failed mapping default framebuffer, no dt (t=6.24951) [GFX1-]: RenderCompositorSWGL failed mapping default framebuffer, no dt
[Child 91, Main Thread] WARNING: Failed to create file monitor for /home/arpit/.var/app/io.github.zen_browser.zen/config/glib-2.0/settings/keyfile: Unable to find default local file monitor type: 'glib warning', file /home/runner/work/desktop/desktop/engine/toolkit/xre/nsSigHandlers.cpp:187

(/app/zen/zen:91): GLib-GIO-WARNING **: 18:09:34.983: Failed to create file monitor for /home/arpit/.var/app/io.github.zen_browser.zen/config/glib-2.0/settings/keyfile: Unable to find default local file monitor type
