### ISSUE TITLE
"Delete Web Panel" closes the sidebar

### ISSUE THREAD

**Issue by TheBestUser01234567890** [zen-browser/desktop#143]
### What happened?

When I delete a web panel, it also closes the sidebar.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.11

### Severity impact

Low

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
Fixed for the next release 👍🏽
