### ISSUE TITLE
Media Decode error when streaming from 7Plus

### ISSUE THREAD

**Issue by DavidGreen63** [zen-browser/desktop#1431]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When attempting to stream content from provider 7Plus, the following message always appears on screen;

![364375822-a35eb7a0-5bb8-4c0f-ae91-645df299e942](https://github.com/user-attachments/assets/41768c27-9186-47a7-a3b3-0ef26ed9edcd)

This is not an issue with my main browser; Floorp (a Firefox fork maintained by Ablaze), nor with Firefox, which can play the same stream within seconds of Zen returning the aforementioned error message, which alludes to an incompatibility on the Client side, every time I have tried.

The setting of "Hardware acceleration" does not appear to have any impact on the issue.

And the error seems isolated to this provider, compared to what few other providers of streaming content that I have use.

My desktop is Win10Pro 22H2 19045.4894 on Intel NUC i7-9750H @ 2.6GHz 32GB RAM ← if relevant
"7plus" is an on-demand service of an Australian Free to Air Broadcaster.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.39 (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by NOCanoa** [comment]
That is looks like DRM issues to me.
https://docs.zen-browser.app/faq#why-cant-zen-browser-play-drm-protected-content

**Comment by DavidGreen63** [comment]
Well, that kind of puts this Zen setting in a different perspective
![Zen DRM Setting](https://github.com/user-attachments/assets/36a92eca-9f11-4100-806b-aec758c158dc)
So, if the setting had read "No DRM Support", then issue may not have been raised in the first place…
