### ISSUE TITLE
[Bug]: No Format button on leetcode.com

### ISSUE THREAD

**Issue by Rope-a-dope** [zen-browser/desktop#1432]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Just go to [leetcode](https://leetcode.com/problemset/), click any problem, you will see.It should has a format button like circled in the screenshot. Actually, FIrefox displays correctly with the format button.
![image](https://github.com/user-attachments/assets/af4a9fbf-c904-4676-9e54-56cc17bfef11)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.39 

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
Sorry but I coudn't get the format button to work even in chromium. It's likely a problem with theyr website...

**Comment by Rope-a-dope** [comment]
> Sorry but I coudn't get the format button to work even in chromium. It's likely a problem with theyr website...

I am so sorry to hear that. Did you try other browser like Chrome/Firefox/Brave/Edge? They all work fine.
