### ISSUE TITLE
Zen wont play videos on tv2.dk

### ISSUE THREAD

**Issue by micbanand** [zen-browser/desktop#1433]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

every video on https://play.tv2.dk wont play. seems to open them. but all is paused at 0:00:00

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Version 1.0.0-a.39 (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
Does it use DRM?

https://docs.zen-browser.app/faq#why-cant-zen-browser-play-drm-protected-content
