### ISSUE TITLE
Disney Plus support?

### ISSUE THREAD

**Issue by matt3r0p3rator** [zen-browser/desktop#1434]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Error code 83 on Disney Plus, checked on another browser if this is a system-wide issue, it wasn't and is centralized to Zen browser. The video does play on normal Firefox. Thanks in advance!!

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.39

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
https://docs.zen-browser.app/faq#why-cant-zen-browser-play-drm-protected-content please check this out
