### ISSUE TITLE
Fullscreen youtube has a padding on right and bottom edge

### ISSUE THREAD

**Issue by doongjohn** [zen-browser/desktop#1437]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![image](https://github.com/user-attachments/assets/8a1e2084-4c61-48de-b993-9fdad3e9f768)
There is a padding on right and bottom edge. (you need to open the image too see it if you are using the light github theme)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.39

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
This has been reported many times, please checkout https://github.com/zen-browser/desktop/issues/1428
