### ISSUE TITLE
Window Control Buttons are inside of the Default Workspace Indicator

### ISSUE THREAD

**Issue by timi2506** [zen-browser/desktop#1439]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Window Control Buttons are inside of the Default Workspace Indicator when having "Open Sidebar on hover" enabled and opening the sidebar via hover
<img width="254" alt="Screenshot 2024-09-14 at 11 57 40" src="https://github.com/user-attachments/assets/c4b9635c-f2cd-47b6-a627-a9bc67b0aae5">

https://github.com/user-attachments/assets/a57cb1b3-8a29-4de3-8444-8bb4870d115a

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Alpha build - 1.0.0-a.39 (2024-09-09)

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by mauro-balades** [comment]
You could enable `zen.themes.tabs.legacy-location` in the meantime

**Comment by timi2506** [comment]
worked thx :D
