### ISSUE TITLE
Crash Report on Intel Mac running Monterey 12.7

### ISSUE THREAD

**Issue by appelgriebsch** [zen-browser/desktop#144]
### What happened?

Downloaded and installed the Mac Intel version of Zen Browser and removed the "quarantine" attributes, but the browser failed to start (crash report attached).
[zen-crash-report.txt](https://github.com/user-attachments/files/16482530/zen-crash-report.txt)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0.a11

### Severity impact

High

### What platform are you seeing the problem on?

macOS - Intel

**Comment by mauro-balades** [comment]
When you run it from the terminal, what output do you get?

**Comment by appelgriebsch** [comment]
```
/Applications/Zen\ Browser.app/Contents/MacOS/zen
zsh: illegal hardware instruction  /Applications/Zen\ Browser.app/Contents/MacOS/zen
```

**Comment by appelgriebsch** [comment]
my proc doesn't support AVX2 AFAIR, so might be related to this....?!?

**Comment by mauro-balades** [comment]
Oh ok, it should be fixed for the next release

**Comment by mauro-balades** [comment]
>  my proc doesn't support AVX2 AFAIR, so might be related to this....?!?

Yeah that's exactly it

**Comment by appelgriebsch** [comment]
Thank you!

**Comment by mauro-balades** [comment]
.12 will fix this issue 👍🏽 

https://github.com/zen-browser/desktop/commit/b224616b435782967abc6188799c1090c1957249
