### ISSUE TITLE
YouTube Homepage Display Issue – Black Screen on Zen Browser

### ISSUE THREAD

**Issue by Darknight92228** [zen-browser/desktop#1440]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I am encountering an issue where the homepage of YouTube displays as a black screen when accessed using Zen Browser. The issue seems to occur consistently, even after refreshing the page. Other sections of YouTube, like the video playback and navigation options, appear to work fine, but the homepage itself remains blank (as shown in the attached screenshot).
<img width="1370" alt="image" src="https://github.com/user-attachments/assets/f90321b3-850a-421b-b2fd-fbd797752b6d">

Additional Information:
I have several extensions installed that may be related to the issue. Below is a list of the extensions:
'Improve YouTube!' 🎧 (for YouTube & Videos) 4.1096
AI Grammar Checker & Paraphraser – LanguageTool 8.11.8
Add-ons Search Detection 2.0.0
Augmented Steam 4.1.1
Bitwarden Password Manager 2024.8.1
CanvasBlocker 1.10.1 [DISABLED]
ClearURLs 1.26.1
Cookie AutoDelete 3.8.2
Cookie Quick Manager 0.5rc2
Decentraleyes 2.0.19 [DISABLED]
Disconnect 20.3.1.2 [DISABLED]
EPUBReader 2.0.13
Firefox Multi-Account Containers 8.1.3
FoxyTab 2.31
Gesturefy 3.2.13
Greasemonkey 4.13
Keepa - Amazon Price Tracker 4.19
Livemarks 3.8
Minimal Theme for Twitter / X 6.1.1
NeatDownloadManager Extension 1.9.9
Nightly Tester Tools 4.1resigned1
Open Multiple URLs 1.6.0
Proton Pass: Free Password Manager 1.22.3
Purple Ads Blocker 2.6.6
RYS — Remove YouTube Suggestions 4.3.60
Read Aloud: A Text to Speech Voice Reader 1.72.0
Return YouTube Dislike 3.0.0.17
Search by Image 7.1.0
Simple Translate 3.0.0
SponsorBlock for YouTube - Skip Sponsorships 5.7
SteamDB 4.5
Tab Backup 0.6.4
Tab Session Manager 7.0.1
Take Webpage Screenshots Entirely - FireShot 1.12.18
TinEye Reverse Image Search 2.0.4
User-Agent Switcher and Manager 0.5.0
Varia Integrator 1.1 [DISABLED]
Wayback Machine 3.2
Web Archives 6.1.1
YouTube Enhancer 1.26.0 [DISABLED]
sudo-flix extension 1.2.0
vidIQ Vision for YouTube 3.114.1
xBrowserSync 1.5.2 [DISABLED]

**### uBlock Origin 1.59.0**(additional filters)
! 2023-02-19 https://www.youtube.com
www.youtube.com##.eoui1uw7.css-1iwn9tw
www.youtube.com##.fb-stat-box-auth
www.youtube.com##.vidiq-demonetization-words
www.youtube.com##.vidiq-social-stats-upsell

! 2023-02-20 https://wordpress.com
wordpress.com##.is-clickable.is-card-link.is-compact.has-call-to-action.upsell-nudge.banner.card

! 2023-02-20 https://www.youtube.com
www.youtube.com##.vidiq-search-upsell.vidiq-general-upsell
www.youtube.com##.vidiq-search-queries-report-section.vidiq-search-section

! 2023-02-20 https://www.startpage.com
www.startpage.com##.css-mtj8kd

! 2023-02-20 https://www.youtube.com
www.youtube.com##ytd-message-renderer.ytd-live-chat-frame.style-scope

! 2023-02-28 https://smallseotools.com
smallseotools.com###domain-age-form > .m-auto.px305.text-center.my-2.d-block > .sq.new___s_
smallseotools.com##.sticky_ssb.my-2.mx-auto.d-block > .sq.new___s_ > .text-decoration-none.text-dark.clr_fff.d-inline-block.garammarly_carousal1 > .bg_2f3133.bg-white.border1 > .p-4.slide.carousel
smallseotools.com##.sticky_ssb.my-2.mx-auto.d-block > .sq.new___s_ > .text-decoration-none.text-dark.clr_fff.d-inline-block.garammarly_carousal1
smallseotools.com##.m-auto.px105.text-center.my-2.d-block
smallseotools.com###google-index-form > .m-auto.px305.text-center.my-2.d-block > .sq.new___s_
smallseotools.com##.side_area.ml-4 > .text-decoration-none.text-dark.clr_fff.d-inline-block.garammarly_carousal1

! 2023-03-04 https://www.youtube.com
www.youtube.com###dismissed > .ytd-feed-nudge-renderer.style-scope

twitter.com##article [data-testid="icon-verified"]:upward(article)
twitter.com##.css-ndbjc4n.r-ihabwwh.r-18u37iz.r-IwtjOep[data-testid="verified-badge"]

! 2023-04-26 https://www.wattpad.com
||static.wattpad.com/image/2021_House-Ad_Premium_02_300x600px_V1.png$image

! 2023-05-24 https://www.youtube.com
www.youtube.com##.ytd-rich-item-renderer.style-scope > .ytd-feed-nudge-renderer.style-scope

! 2023-05-24 https://kaas.am
kaas.am##.col-12.col-md-3

! 2023-06-09 https://manhwahub.net
||manhwahub.net/storage/images/banner/PRELOAD%20320x250.png$image
manhwahub.net##.top1
||manhwahub.net/storage/images/banner/CATFISH%20730x92.png$image

! 2023-06-18 https://mangapill.com
mangapill.com##.mb-3.container > .justify-between.items-center.flex
mangapill.com##div.container > .justify-between.items-center.flex

! 2023-06-19 https://www.1024tera.com
||s2.teraboxcdn.com/fe-opera-static/node-static-v4/fe-webv4-main/img/en-drainage.6071ba8a.png$image

! 2023-06-19 https://www.4funbox.com
||s2.teraboxcdn.com/fe-opera-static/node-static-v4/fe-webv4-main/img/en-drainage.6071ba8a.png$image

! 2023-07-15 http://bookszlibb74ugqojhzhg2a63w5i2atv5bqarulgczawnbmsb6s6qead.onion
||bookszlibb74ugqojhzhg2a63w5i2atv5bqarulgczawnbmsb6s6qead.onion/img/banners/scam-sites.png$image

! 2023-07-22 https://tellygossips.net
tellygossips.net##.main-conents center

! 2023-09-03 https://aquamanga.com
||players.radioonlinehd.net/ads/aquamangaradio.html$subdocument
aquamanga.com###radio_content

! 2023-09-03 https://www.moneycontrol.com
||charts.moneycontrol.co.in/mkt_sensex_graph.html?q=09031009$subdocument
www.moneycontrol.com##.mob-hide.nwidg300

! 2023-09-29 https://manhwaz.com
manhwaz.com###adsb

! 2023-09-30 https://manhwaz.com
||hz9x6ka2t5gka7wa6c0wp0shmkaw7xj5x8vaydg0aqp6gjat5x.com/b2a8zj6x8a6gk0wv5awh2ja7sn6x8stx/m7an6hw3a1zh9z0wjt3cxha8x7ajw5fnq6gja8stgbx/t6x0pb4an5ner6gja95ahs6fm/t0px8aj5fapw6faj5x8ajt.php$subdocument
||cdn.manhwaz.com/manga/7641/3/63d02ad5a310e.jpg$image
||hz9x6ka2t5gka7wa6c0wp0shmkaw7xj5x8vaydg0aqp6gjat5x.com/b2a8zj6x8a6gk0wv5awh2ja7sn6x8stx/m7an6hw3a1zh9z0wjt3cxha8x7ajw5fnq6gja8stgbx/t6x0pb4an5ner6gja95ahs6fm/t0px8aj5fapw6faj5x8ajt.php$subdocument
||hz9x6ka2t5gka7wa6c0wp0shmkaw7xj5x8vaydg0aqp6gjat5x.com/b2a8zj6x8a6gk0wv5awh2ja7sn6x8stx/m7an6hw3a1zh9z0wjt3cxha8x7ajw5fnq6gja8stgbx/t6x0pb4an5ner6gja95ahs6fm/b3sj6x0s0wj6faus8zxmbt.php$subdocument

! 2023-10-02 https://manhwaz.com
||hz9x6ka2t5gka7wa6c0wp0shmkaw7xj5x8vaydg0aqp6gjat5x.com/b2a8zj6x8a6gk0wv5awh2ja7sn6x8stx/m7an6hw3a1zh9z0wjt3cxha8x7ajw5fnq6gja8stgbx/t6x0pb4an5ner6gja95ahs6fm/5zin7foz9xka2x9askr5pd.php$subdocument
||hz9x6ka2t5gka7wa6c0wp0shmkaw7xj5x8vaydg0aqp6gjat5x.com/b2a8zj6x8a6gk0wv5awh2ja7sn6x8stx/m7an6hw3a1zh9z0wjt3cxha8x7ajw5fnq6gja8stgbx/t6x0pb4an5ner6gja95ahs6fm/5zi0fo1zj9sajtb0to0msa8.php$subdocument
||hz9x6ka2t5gka7wa6c0wp0shmkaw7xj5x8vaydg0aqp6gjat5x.com/b2a8zj6x8a6gk0wv5awh2ja7sn6x8stx/m7an6hw3a1zh9z0wjt3cxha8x7ajw5fnq6gja8stgbx/t6x0pb4an5ner6gja95ahs6fm/5zin7foz9xka2x9askr5pd.php$subdocument

! Title: Hide YouTube Shorts
! Description: Hide all traces of YouTube shorts videos on YouTube
! Version: 1.10.0
! Last modified: 2024-08-31 19:24
! Expires: 2 weeks (update frequency)
! Homepage: https://github.com/gijsdev/ublock-hide-yt-shorts
! License: https://github.com/gijsdev/ublock-hide-yt-shorts/blob/master/LICENSE.md

! Remove empty spaces in grid
www.youtube.com##ytd-rich-grid-row,#contents.ytd-rich-grid-row:style(display: contents !important)

! Hide all videos containing the phrase "#shorts"
www.youtube.com##ytd-grid-video-renderer:has(#video-title:has-text(/(^| )#Shorts?( |$)/i))
www.youtube.com##ytd-rich-item-renderer:has(#video-title:has-text(/(^| )#Shorts?( |$)/i))

! Hide all videos with the shorts indicator on the thumbnail
www.youtube.com##ytd-grid-video-renderer:has([overlay-style="SHORTS"])
www.youtube.com##ytd-rich-item-renderer:has([overlay-style="SHORTS"])
www.youtube.com##ytd-video-renderer:has([overlay-style="SHORTS"])
www.youtube.com##ytd-item-section-renderer.ytd-section-list-renderer[page-subtype="subscriptions"]:has(ytd-video-renderer:has([overlay-style="SHORTS"]))

! Hide shorts button in sidebar
www.youtube.com##ytd-guide-entry-renderer:has(yt-formatted-string:has-text(/^Shorts$/i))
! Tablet resolution
www.youtube.com##ytd-mini-guide-entry-renderer:has(.title:has-text(/^Shorts$/i))

! Hide shorts sections except on history page
www.youtube.com##:matches-path(/^(?!\/feed\/history).*$/)ytd-rich-section-renderer:has(#title:has-text(/(^| )Shorts( |$)/i))
www.youtube.com##:matches-path(/^(?!\/feed\/history).*$/)ytd-reel-shelf-renderer:has(.ytd-reel-shelf-renderer:has-text(/(^| )Shorts( |$)/i))

! Hide shorts tab on channel pages`
! Old style
www.youtube.com##tp-yt-paper-tab:has(.tp-yt-paper-tab:has-text(Shorts))
! New style (2023-10)
www.youtube.com##yt-tab-shape:has-text(/^Shorts$/)

! Hide short remixes in video descriptions and in suggestions beside the comments
www.youtube.com##ytd-reel-shelf-renderer:has(#title:has-text(/(^| )Shorts.?Remix.*$/i))

! Hide shorts category on homepage and search pages
www.youtube.com##yt-chip-cloud-chip-renderer:has(yt-formatted-string:has-text(/^Shorts$/i))

!!! MOBILE !!!

! Hide all videos in home feed containing the phrase "#shorts"
www.youtube.com##ytm-rich-item-renderer:has(#video-title:has-text(/(^| )#Shorts?( |$)/i))

! Hide all videos in subscription feed containing the phrase "#shorts"
m.youtube.com##ytm-item-section-renderer:has(#video-title:has-text(/(^| )#Shorts?( |$)/i))

! Hide shorts button in the bottom navigation bar
m.youtube.com##ytm-pivot-bar-item-renderer:has(.pivot-shorts)

! Hide all videos with the shorts indicator on the thumbnail
m.youtube.com##ytm-video-with-context-renderer:has([data-style="SHORTS"])

! Hide shorts sections except on history page
m.youtube.com##:matches-path(/^(?!\/feed\/history).*$/)ytm-rich-section-renderer:has(.reel-shelf-title-wrapper .yt-core-attributed-string:has-text(/(^| )Shorts( |$)/i))
m.youtube.com##:matches-path(/^(?!\/feed\/history).*$/)ytm-reel-shelf-renderer.item:has(.reel-shelf-title-wrapper .yt-core-attributed-string:has-text(/(^| )Shorts( |$)/i))

! Hide shorts tab on channel pages
! Old style
m.youtube.com##.single-column-browse-results-tabs>a:has-text(Shorts)
! New style (2023-10)
m.youtube.com##yt-tab-shape:has-text(/^Shorts$/)

! Hide short remixes in video descriptions and in suggestions below the player
m.youtube.com##ytm-reel-shelf-renderer:has(.reel-shelf-title-wrapper .yt-core-attributed-string:has-text(/(^| )Shorts.?Remix.*$/i))

! Hide shorts category on homepage
m.youtube.com##ytm-chip-cloud-chip-renderer:has(.yt-core-attributed-string:has-text(/^Shorts$/i))

! 2024-03-04 https://kayoanime.com
kayoanime.com##.tie-popup-container > .container-wrapper

! 2024-03-30 https://mangapill.com
mangapill.com##.lg\:col-span-1.col-span-4 > .justify-between.items-center.flex

! 2024-04-01 https://mangadex.org
mangadex.org##.mx-auto.sm\:\!-mt-8.\!-mt-16.flex-col.flex.my-2.p-2.bg-accent
mangadex.org##.header.flex-col.flex.my-2.p-2.bg-accent

 

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.39 (64-bit)

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by n7itro** [comment]
Does this issue still occur with all your addons disabled?

**Comment by lessload** [comment]
1. Your custom ublock rule may cause problem. lastest zen + ublock without custom rule test pass.
2. Youtube not allow user to use ads block. it will fail again in the future, developer should skip this issue.
