### ISSUE TITLE
Patreon link to Vercel

### ISSUE THREAD

**Issue by pinage404** [zen-browser/desktop#1441]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Hello,

I don't know where should i report this, sorry

Patreon https://www.patreon.com/zen_browser/about link to https://get-zen.vercel.app which is a dead

It should link to https://zen-browser.app

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

not relevant

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
Fixed, thanks!
