### ISSUE TITLE
Free Download Manager extension does not work on Linux

### ISSUE THREAD

**Issue by sandenbergmelo** [zen-browser/desktop#1444]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.

### What happened?

The [FDM Extension](https://addons.mozilla.org/pt-BR/firefox/addon/free-download-manager-addon/) is not working on linux.

It just keeps loading and never get ready:
![Captura de tela de 2024-09-14 18-01-48](https://github.com/user-attachments/assets/76a48d91-92c0-4988-ac35-48b229cb94b4)

On Windows it works fine:
![Captura de tela 2024-09-14 182433](https://github.com/user-attachments/assets/061f4cb8-d728-4021-a42b-4146a4cff4f6)

It also works normally in Firefox on Linux.

I tested it on Ubuntu 24.04, I don't know if it's working on other distros.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.39 (64-bit)

### What platform are you seeing the problem on?

Linux

**Comment by sandenbergmelo** [comment]
I tested and found that this error is only in the flatpak version.

**Comment by ProbablyM-S** [comment]
its FDM's limitation they don't support flatpak browser if you need a download manager which also supports flatpak browser use Varia (available on Flathub) and close this issue there's nothing they can do about it.

**Comment by sandenbergmelo** [comment]
Ok
