### ISSUE TITLE
Drizzle studio does not work

### ISSUE THREAD

**Issue by mrlectus** [zen-browser/desktop#1446]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

This is specifically not a zen issue, but just hoping someone could help here

![screenshot_2024-09-15T00:24:02](https://github.com/user-attachments/assets/ab0a24aa-3dd1-4e3d-8082-4c8ce318318a)

I get the page when running drizzle studio. It just keeps spinning same issue when I was using chrome but running that `mkcert --install` fixed it for chrome but not zen. I was wondering if you guys might have a solution that might help.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.39

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
Sorry, but this is specifically for zen's issues. Please ask the drizzle studio team for help. All I can say is, maybe reload?

**Comment by AK-Abex** [comment]
This is a Zen's issue, this is the only browser where it doesnt work. something wrong with zen, chrome based ones asks for permission to search for ports. In zen its not working
