### ISSUE TITLE
The browser does not go fullscreen properly

### ISSUE THREAD

**Issue by shahiljain** [zen-browser/desktop#1447]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When going full screen for videos the edges of the browser are still visible.
![image](https://github.com/user-attachments/assets/12369404-9d90-40a7-89ed-7d2544b17d3a)
A screenshot of YouTube

![zen_FJxeLWYiAB](https://github.com/user-attachments/assets/728184b2-95cc-4a9f-a28d-e8c78a9eec36)
A screenshot of Disney+ but can't see it since DRM

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.39

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
This has been fixed for the next release, please try to search for repeated issues next time
