### ISSUE TITLE
Download Page CSS padding issue

### ISSUE THREAD

**Issue by Arsenic-01** [zen-browser/desktop#1448]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

On laptop view, the download page "Select Architecture" section
The Download Zen Title gets cut most probably because of top-padding 
![BUG_ZEN](https://github.com/user-attachments/assets/c14ffda4-af87-4c39-a772-59f58fb990fd)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0

### What platform are you seeing the problem on?

Windows

**Comment by n7itro** [comment]
Please open an issue in the correct repository (zen-browser/www)
