### ISSUE TITLE
Clicking "Next" on "Choose your search engine" intro page does nothing

### ISSUE THREAD

**Issue by burnout426** [zen-browser/desktop#145]
### What happened?

Windows 11 23H2

The intro gets stuck on the "Choose your search engine" page. Clicking "Next" does nothing. You can hit esc to get out of the intro, but it will show up again the next time you start Zen because you weren't able to complete it.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.11 (64-bit) (generic build)

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
You can manually disable it by turning `zen.welcomeScreen.seen` into false in `about:config`, ill look into this

**Comment by burnout426** [comment]
The bottom right search (Wikipedia) is showing over the top edge of the "Next" button, so it might have something to do with that.

**Comment by mauro-balades** [comment]
Hope this fixes it (https://github.com/zen-browser/desktop/commit/76b2b55edae38219148a1c9644ad164e8fd53480)? Please feel free to reopen if you keep getting this issue after the new update

**Comment by burnout426** [comment]
Checked in 1.0.0-a.13 (64-bit) - generic on Windows 11 23H2. All good now and I can click the "Next" button. And, the "Next" button is no longer partially covered by the bottom right search engine.
