### ISSUE TITLE
Youtube videos have a weird bar in 2 sides

### ISSUE THREAD

**Issue by androidghosh** [zen-browser/desktop#1451]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

On fresh install, nothing changed. Youtube videos have a weird bar in 2 sides.

![image](https://github.com/user-attachments/assets/0164f8e3-de20-4094-891a-79ac8391a5cf)
on dark theme

![image](https://github.com/user-attachments/assets/5aa95f67-d5d4-4ba3-862a-9cec10c2daf0)
on light theme

happens with any video

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.39 (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
Please try to find duplicates before posting. The checkboxes arent there to verify you aren't a robot...

![image](https://github.com/user-attachments/assets/8cb3231a-d9d0-45c2-880e-fad33223f70d)

This has been fixed for the next release, im releasing today, so make sure you update!
