### ISSUE TITLE
Some Issue with v1.0.0-a40 (or 1.0.1-a)

### ISSUE THREAD

**Issue by adam-adrian** [zen-browser/desktop#1454]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Trying to pull and run newest build from https://github.com/zen-browser/desktop/actions/runs/10870741862 and found some issue:

(Tab)
- Close tab button is missing
- selected tab button is styled a bit weirdly, i think? especially with shadow
![](https://github.com/user-attachments/assets/f12c3827-1d5c-4318-920c-12679cff3e3e)
![](https://github.com/user-attachments/assets/cab72f0a-4a15-4adc-9dea-c24e6ed12ae0)
(Zen Dream and Galaxy theme)

- Also it didn't follow accent colour like previous version and no animation when opening new tab
(probably because reusing original Firefox code?)

 (Workspaces)

- 'Set Default Container' option doesn't work with user-created/modified container
(it just freeze the workspace menu and make it not opening anymore)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a40 (or 1.0.1-a)

### What platform are you seeing the problem on?

Linux

### Anyway

Very good job at many improvements!! especially the ability to toggle on/off Zen themes (or whatever it is called), it's very useful.
Again, Thank You So Much for the efforts of developing this browser~

**Comment by mauro-balades** [comment]
1.0.0-a isnt even released yet 😭 

but it is now fixed, thanks!
