### ISSUE TITLE
from test at https://amiunique.org/fingerprint for privacy. some value not like firefox make user easy to fingerprint.

### ISSUE THREAD

**Issue by lessload** [zen-browser/desktop#1456]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

from test value `25 - Screen available Height   XX%   1032` (pixel) .why it a bit lower than normal firefox. website can detect user are using Zen by that value. in normal firefox show as 1080 ( for display 1920x1080) 

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.39

### What platform are you seeing the problem on?

Windows

**Comment by NOCanoa** [comment]
because the browser has padding around the edges.

**Comment by lessload** [comment]
can seperate user Firefox vs Zen by `value kinda ehh`

**Comment by mauro-balades** [comment]
You can tune `zen.theme.content-element-separation` down to 0 in order to have the same height

**Comment by mauro-balades** [comment]
Can I close this then?
