### ISSUE TITLE
Close tab button missing

### ISSUE THREAD

**Issue by Muko-Tabi** [zen-browser/desktop#1457]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The close tab icon is missing

1.0.0-a.39:
![image](https://github.com/user-attachments/assets/19cb294c-52d7-4b80-bf2b-816977d0a7ea)

1.0.1-a:
![image](https://github.com/user-attachments/assets/9e7c8612-fd4c-4bab-b11c-bf919ff51479)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a

### What platform are you seeing the problem on?

Linux

**Comment by adam-adrian** [comment]
Already mentioned in #1454

**Comment by mauro-balades** [comment]
1.0.0-a isnt even released yet 😭 it is now fixed, thanks!
