### ISSUE TITLE
issues with fullscreen vids in youtube

### ISSUE THREAD

**Issue by salammahdi-pretty** [zen-browser/desktop#1458]
### Captchas

- [x] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.

### What happened?

when playing videos in fullscreen in youtube, the pezels associated with the browser itself are bothering me 
![WhatsApp Image 2024-09-15 at 17 19 45](https://github.com/user-attachments/assets/52e45a57-c884-45b0-b8d7-6dc0531fa1a3)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.39

### What platform are you seeing the problem on?

Linux

**Comment by lessload** [comment]
on windows too.

**Comment by LarveyOfficial** [comment]
Duplicate of  #1362

**Comment by salammahdi-pretty** [comment]
> Duplicate of #1362

oh i didn't see it
