### ISSUE TITLE
Console.log not printing out.

### ISSUE THREAD

**Issue by tnguyen2601** [zen-browser/desktop#1468]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Triggering a console.log per JS or in the Dev Console directly doesn't print. [Ticket #593](https://github.com/zen-browser/desktop/issues/593) was closed suggesting to be fixed already, but for me it doesn't work yet.
![grafik](https://github.com/user-attachments/assets/2808b025-a894-4b45-92b2-eb69797fa5e2)

I checked and `devtools.selfxss.count` is indeed 5
![grafik](https://github.com/user-attachments/assets/92e9ac20-4533-4a4c-ae5c-d27d15082528)

Windows 11

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.39 (64-Bit)

### What platform are you seeing the problem on?

Windows

**Comment by tnguyen2601** [comment]
> It seems like you edited the value... Could you try changing it to the default one?

Isn't 5 the default value? I opened `about:config` just to look into the value described in the other ticket.
This issue appeared on my Laptop. Here at my home PC, console.log works. The value of `devtools.selfxss.count` here is 5 too.

**Comment by kzakrzewski-photon** [comment]
![image](https://github.com/user-attachments/assets/a28f2e93-52b7-4162-b1ff-c77308f5cbd0)

I had the same problem but after changing `devtools.selfxss.count` to `5` - it just worked. I want to mention that I have never changed that value before. OS: Manjaro Linux

**Comment by mauro-balades** [comment]
This will be the new default next release, thanks!
