### ISSUE TITLE
语言适配问题

### ISSUE THREAD

**Issue by WHMyyds** [zen-browser/desktop#1469]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

在更新到最新版本中，在已经选择语言为``ZH-CN``后所有浏览器语言变成了``En-US``
值得注意的是，在之前的版本中，只有设置中显示语言为中文，其他地方（e.g.工具栏菜单）都显示为英文
![image](https://github.com/user-attachments/assets/0807b9e1-0af5-460e-b4bd-45467b726f4a)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a39

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
This has been fixed in the next version (released today). Thanks!
