### ISSUE TITLE
Unable to add site to sidebar

### ISSUE THREAD

**Issue by daddyhacker18** [zen-browser/desktop#147]
### What happened?

When you click the '+' and fill in the URL, the site doesnt get added to the sidebar.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.11

### Severity impact

Low

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
It has to be a valid URL for it to work (e.g. `https://google.com`), what website did you try to add?

**Comment by daddyhacker18** [comment]
That worked, thanks!
