### ISSUE TITLE
Opening a new window and then closing it makes more new tabs open

### ISSUE THREAD

**Issue by badjuice** [zen-browser/desktop#1470]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When a new windows is opened (`Shift +Enter` on address bar or `Ctrl + N`) and then closed, it opens 3 more new tabs instead of opening a single one (default behavior of keeping last tab of the window opened).

https://github.com/user-attachments/assets/e2e524a6-6029-4756-97a2-796a7073cfe6

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a39

### What platform are you seeing the problem on?

Windows

**Comment by Coops0** [comment]
More footage reproducing issue, I can get it to work the most when I open multiple links in new tabs, then close the parent tab.

https://github.com/user-attachments/assets/f8540806-9513-45ba-a4bd-5345e96a7fcf

**Comment by astro-ray** [comment]
This is still a problem for me

**Comment by badjuice** [comment]
> This is still a problem for me

I think this has been fixed as of the latest version so far
