### ISSUE TITLE
"Hide the default container indicator in the tab bar" doesn't work when opening container with shortcut or via link

### ISSUE THREAD

**Issue by LarveyOfficial** [zen-browser/desktop#1472]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When the new "Hide the default container indicator in the tab bar" setting is enabled in the workspaces setting, and workspace has a container set, if you open a container tab by using either a shortcut, or via opening a link as a new container tab, the container indicator is still present.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a

### What platform are you seeing the problem on?

Linux, Windows

**Comment by sjclayton** [comment]
I'm also experiencing this, 1.0.1-a on Linux.

**Comment by karlprieb** [comment]
Experiencing the same on 1.0.1-a.1 MacOS

**Comment by mauro-balades** [comment]
This has been fixed for the next release, thanks!
