### ISSUE TITLE
Bookmark or History URL Should Open in Default Container for Current Workspace

### ISSUE THREAD

**Issue by kristijanribaric** [zen-browser/desktop#1474]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Clicking on a bookmark or a URL from history currently opens a new tab without assigning it to the default container for the current workspace. Not really sure if this is a bug or a feature request.

### Context
With the release of version `1.0.1-a`, default containers were introduced for each workspace. This feature works well when opening a new tab and manually typing in a URL, as it correctly opens in the appropriate container. However, when clicking on a link from the history or bookmarks, the tab opens without using the assigned container for the workspace.

### Expected Behavior
- When clicking on a bookmark or history link, the URL should open in a new tab within the default container for the current workspace.
- This behavior should be consistent with how URLs are handled when typed in manually in new tabs.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a

### What platform are you seeing the problem on?

Windows

**Comment by Numline1** [comment]
This would be really cool to have implemented. Using the bookmarks bar is really problematic when it opens the pages without applying a Personal/Work containers for me. Thanks!

**Comment by alex3137** [comment]
I agree, I would really like that feature too.
