### ISSUE TITLE
Tabs are very small after the 1.0.1-a update

### ISSUE THREAD

**Issue by nazmiyigitefe** [zen-browser/desktop#1475]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

They're now very small with the new update (1.0.1-a), I tried with troubleshoot mode and all themes disabled, it doesn't matters.

<img width="233" alt="Ekran Resmi 2024-09-16 19 28 05" src="https://github.com/user-attachments/assets/4b9824d1-7f9c-4737-be2e-b19ce3be8e08">

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by mauro-balades** [comment]
You could get out of compact mode, resize and go back into it

**Comment by nazmiyigitefe** [comment]
Where may I resize it?
