### ISSUE TITLE
Tabs disappear in fullscreen

### ISSUE THREAD

**Issue by parmeniong** [zen-browser/desktop#1476]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

If I fullscreen the browser window, the tabs disappear. The only way to bring them back is to exit fullscreen mode or put my cursor at the top of my screen. After I take my cursor off the toolbar the tabs disappear again.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a

### What platform are you seeing the problem on?

Linux

**Comment by sjclayton** [comment]
Confirmed here also on Linux.

**Comment by parmeniong** [comment]
I just noticed that if I open Zen and fullscreen the window without clicking anywhere the tabs are visible, but if I then click anywhere inside the website that is open the tabs disappear. Although, the tabs seem to have an animation when that happens.

**Comment by mauro-balades** [comment]
This has been fixed for the next release, thanks! ill release today probably
