### ISSUE TITLE
Sidebar buttons pushed to left when collapsed

### ISSUE THREAD

**Issue by sjclayton** [zen-browser/desktop#1477]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Buttons in the sidebar appear to not be centered anymore when it's collapsed, something is maybe messed up with the padding??

![2024-09-16_13-34](https://github.com/user-attachments/assets/8ee994e2-2765-4b96-946b-2f84ae08a5a4)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a

### What platform are you seeing the problem on?

Linux

**Comment by greeeen-dev** [comment]
Probably some CSS is not being applied properly on the newest update for some reason.

In addition to your issue, tab buttons look like stock Firefox, the profile avatar isn't a circle anymore, and there's missing padding between the window buttons (the traffic lights) and navbar buttons on macOS.

I've reverted back to 1.0.0-a39 for the time being, hopefully this is fixed soon.

**Comment by mauro-balades** [comment]
Forgot to add an `align-items: center`... sorry

**Comment by sjclayton** [comment]
@mauro-balades 

A separate issue should probably be opened for the button theming consistency issue that @greeeen-dev  mentioned as well, as I am experiencing this too, it makes things look very disjointed, having the tab buttons themed differently than the rest of Zen, especially on hover.
