### ISSUE TITLE
Crunchyroll don't work on Zen

### ISSUE THREAD

**Issue by Yasunaii** [zen-browser/desktop#148]
### What happened?

When I open a video on crunchyroll the site gives me an error

![image](https://github.com/user-attachments/assets/7e9a3e79-b613-4595-9084-b25b13d4f42a)
Code : SHAK-6007-403-4035-403-4035-GENERIC
Session id : 75f76e11-c033-4ff9-b1c1-49889c9012e9
Center message : Damn! An error has occurred. Please try again ( for translation x) ) 

I get this pop-up telling me about DRM, but in my options it's enabled. 
![image](https://github.com/user-attachments/assets/01ec94b7-f2d9-4d1f-9a29-32ef941d058a)

I also tried to see if disabling them would do anything. It changes the error codes that don't find this option, I guess.
![image](https://github.com/user-attachments/assets/27defd71-7e20-4088-9901-1a7431c9a107)

I've never encountered this error on Firefox. However, I did encounter it during Arc's development a few months ago.

If you need logs, I don't know where to find them, so I'll just need instructions on how to send them ^^'.

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Version 1.0.0-a.11 (64-bit) on Windows 11

### Severity impact

Low, Medium

### What platform are you seeing the problem on?

Windows

**Comment by IAmJafeth** [comment]
It works for me, did not make any changes on my config

Zen Version: 1.0.0-a.13
Installation: Linux Specific tar.bz2

Specs:
OS: Ubuntu 24.04 LTS x86_64
Kernel: 6.8.0-39-generic
Resolution: 1080x1920, 1920x1080
DE: GNOME 46.0
CPU: 11th Gen Intel i9-11900K (16) @ 5.100GHz
GPU: NVIDIA GeForce RTX 3070 Ti
Memory:  31920MiB

![image](https://github.com/user-attachments/assets/40abc776-95e7-4df0-964a-1f805ff10392)

**Comment by Yasunaii** [comment]
> inux Specific tar

I think the difference comes from the OS version. I'm on Windows 11 at the moment

**Comment by Yasunaii** [comment]
> It works for me, did not make any changes on my config
> 
> Zen Version: 1.0.0-a.13 Installation: Linux Specific tar.bz2
> 
> Specs: OS: Ubuntu 24.04 LTS x86_64 Kernel: 6.8.0-39-generic Resolution: 1080x1920, 1920x1080 DE: GNOME 46.0 CPU: 11th Gen Intel i9-11900K (16) @ 5.100GHz GPU: NVIDIA GeForce RTX 3070 Ti Memory: 31920MiB
> 
> ![image](https://private-user-images.githubusercontent.com/45522320/355279713-40abc776-95e7-4df0-964a-1f805ff10392.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MTEyNTMsIm5iZiI6MTcyMjkxMDk1MywicGF0aCI6Ii80NTUyMjMyMC8zNTUyNzk3MTMtNDBhYmM3NzYtOTVlNy00ZGYwLTk2NGEtMWY4MDVmZjEwMzkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDAyMjIzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwM2NkY2NlMjAwZGI1Y2Q2ZDgxMzczNzdkM2JmOWNhZDEwZDllOWZhMGJhM2Y0ZDQwNWEwYzU2MjI1YTdjNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lY8dJEox0gXjlEKIhSR3MH6yPFqQuMOH8d-tm00zEXk)



I think the difference comes from the OS version. I'm on Windows 11 at the moment

**Comment by Yasunaii** [comment]
I'd like to add this conversation on zen's reddit as a reference 

https://www.reddit.com/r/zen_browser/comments/1esdxg5/hulu_not_working_in_zen_browser/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

**Comment by Yasunaii** [comment]
sorry bad button :-:

**Comment by mauro-balades** [comment]
Does crunchyroll use DRM?

**Comment by Yasunaii** [comment]
> Does crunchyroll use DRM?

Normally yes, I had posted an image in my first post showing this: 

https://i.imgur.com/H1E82GK.png

I put as much detail as possible in the first post, this evening I've just added a discussion on reddit which shows that there are indeed problems with windows drm while linux seems to be fine.

**Comment by mauro-balades** [comment]
This is because windows requires a license in order to run this streaming media. Sorry but I wont pay google 1000 euros a year for the license (Plus that you need to be a company, they need to validate you, etc etc). Maybe in the future, we'll see!
