### ISSUE TITLE
Zen says there is a browser update while using the latest version

### ISSUE THREAD

**Issue by Highlander214** [zen-browser/desktop#1480]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Zen keeps saying there is an update while the current latest version is already installed
Ive restarted Zen several times and it still appears
![image](https://github.com/user-attachments/assets/9b78c3b7-abe8-49e6-a4b3-762493cfbf14)
![image](https://github.com/user-attachments/assets/d7bca0e8-fa87-4126-856e-f632ca8ba7bb)
![image](https://github.com/user-attachments/assets/a663b7be-a302-4bdc-8710-c3d0153341f9)

### Reproducible?

- [] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
Im rebuilding a new version, let's see if it gets fixed with it

**Comment by Highlander214** [comment]
Yeah its not a high priority thing I just noticed it after updating earlier today

**Comment by mauro-balades** [comment]
Does it still happen?

**Comment by salamijason** [comment]
Heylo, looks like this issue was posted a while back. Are you still getting this on the lastest version? (a17 as of this comment)

**Comment by salamijason** [comment]
No response in 3 days. Will be closing this issue. Please reopen if you are still facing the issue.
