### ISSUE TITLE
Tab is partially overrided

### ISSUE THREAD

**Issue by TJNOV** [zen-browser/desktop#1483]
### Captchas

- [X] I have read the instructions.
- [ ] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

Tab is partially overrided
![图片](https://github.com/user-attachments/assets/99f045fa-4c1a-49f5-98a2-d55be74a5dc1)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a

### What platform are you seeing the problem on?

Windows

**Comment by TJNOV** [comment]
tab's shadows aren't very aesthetically pleasing under a bright theme

**Comment by mauro-balades** [comment]
This has been fixed, thanks!

remember to update
