### ISSUE TITLE
Menubar is overlayed on top of the url bar

### ISSUE THREAD

**Issue by that-ambuj** [zen-browser/desktop#1488]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![image](https://github.com/user-attachments/assets/6dd698b8-297c-44bf-af47-12bdea0202f7)

I'm currently facing this issue after an update. 

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a

### What platform are you seeing the problem on?

Linux

**Comment by that-ambuj** [comment]
Right clicking on the toolbar and disabling Menu bar temporarily fixed the issue.

**Comment by srynprjl** [comment]
![image](https://github.com/user-attachments/assets/71da29da-4fdc-465f-ac52-feba62573490)
![image](https://github.com/user-attachments/assets/df662234-dbef-41d3-b75a-175bb83d6f29)


same but mine  doesnt overlay on top of url bar

probably cause i have a theme & have legacy toolbar one
