### ISSUE TITLE
Remember sidebar width on toggle

### ISSUE THREAD

**Issue by bdbch** [zen-browser/desktop#149]
### What happened?

Related to #126

The sidebar width is currently not remembered when the sidebar is toggled via the "collapse sidebar" button.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.12

### Severity impact

Low

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by mauro-balades** [comment]
Fixed for the next release 👍🏽 https://github.com/zen-browser/desktop/commit/2d72365dbdd23b612fd4636a1d80af37b2356510

thanks!
