### ISSUE TITLE
url bar not showing

### ISSUE THREAD

**Issue by mbr67** [zen-browser/desktop#1490]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

the url bar is not showing on hover in compact mod.
sidebar is working fine on hover

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a

### What platform are you seeing the problem on?

Windows

**Comment by mbr67** [comment]
same in Zen 1.0.1-a.1

**Comment by onthejobtraining** [comment]
Can't reproduce the issue on my end. Url bar is being displayed perfectly on hovering on my end with compact mode enabled.

Screen recording of the issue? and have you restarted the browser?

**Comment by mbr67** [comment]
yes, i have restartet zen and even reinstall it, but bug is still there.

https://github.com/user-attachments/assets/f893fdfd-1054-46b0-87a6-b203379b1295

**Comment by mbr67** [comment]
url bar is showing on hover in fullscreen.

**Comment by onthejobtraining** [comment]
@mbr67

**Comment by onthejobtraining** [comment]
> yes, i have restartet zen and even reinstall it, but bug is still there.
> Zen.urlbar.not.showing.on.hover.17.09.2024_09.47.17_REC.mp4



> yes, i have restartet zen and even reinstall it, but bug is still there.

Go to Settings-Keyboard Shortcuts-Compact Mode Actions-Toggle compact mode toolbar and check the shortcut.

**Comment by mbr67** [comment]
this toggles the toolbar and it doesn't autohide any more

**Comment by onthejobtraining** [comment]
> this toggles the toolbar and it doesn't autohide any more

I am still unable to reproduce your issue, so try to create a new profile with and see if the issue persists on the new profile

**Comment by mbr67** [comment]
Edition	Windows 11 Pro
Version	24H2
Installed on	‎12/‎06/‎2024
OS build	26120.1542
Experience	Windows Feature Experience Pack 1000.26100.18.0
