### ISSUE TITLE
Side bar doesn't overflow and add a scrollbar when there are alot of items

### ISSUE THREAD

**Issue by tv2-thomas** [zen-browser/desktop#1491]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

After the new update my sidebar (not compacted) doesn't overflow and give a scrollbar. Instead it just keeps compacting the list to the point where they are unreadable. See screenshot attached.

I have tried to minimize and close the browser completely. Also tried disabling most of the theme addons I know about, but I can't find a consistent list of which are installed.

![image](https://github.com/user-attachments/assets/4166cb09-17b7-4ebe-9c12-3685b5527c55)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.1

### What platform are you seeing the problem on?

macOS - aarch64

### Relevant log output

```shell
Unsure where
```

**Comment by DaitiDay** [comment]
Same, super annoying

**Comment by yzu1103309** [comment]
Ran into the same problem after update.
I hope that this can be fixed soon 'cause it's really annoying

**Comment by Truleu** [comment]
I just updated to 1.0.1-a.1 today and faced this same issue, it's super ugly and not functional. There's no scroll anymore

**Comment by Nesewebel** [comment]
I thought my tabs went invisible earlier today, seems like 300+ tabs were just too much to squeeze in...
![image](https://github.com/user-attachments/assets/d4b38a86-5c3f-4d3b-b9eb-6b1b5c287a23)

**Comment by powerfulparadox** [comment]
Can confirm for me also. Windows 11, light mode.

![Screenshot 2024-09-17 204304](https://github.com/user-attachments/assets/4a82a4d0-2ee8-4713-a464-e66e678f2b88)
![Screenshot 2024-09-17 204349](https://github.com/user-attachments/assets/9a7cc5a2-567d-45d4-a00c-fec84421a33b)

**Comment by mauro-balades** [comment]
This is fixed, please remember to update once I release it.

The release will be available in like 10 minutes

Thanks!
