### ISSUE TITLE
Sidebar expansion keybind doesn't work

### ISSUE THREAD

**Issue by A-Z-X-R** [zen-browser/desktop#1494]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Well, I tried to setup ctrl+s to expand the sidebar. I did this on both Mac and Windows.
Expected result: sidebar expands and I get to manage my tabs.
The result: I opened the bookmarks sidebar?? Am I missing something? the sidebar that gets loaded looks like the sideberry addon I used months ago and shows bookmarks and nothing else

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a3.9(64-bit) 

### What platform are you seeing the problem on?

macOS - Intel, Windows

**Comment by A-Z-X-R** [comment]
Is this getting addressed or what? Or did I just mess up on my part? Anyone?

**Comment by salamijason** [comment]
Heylo, looks like this issue was posted a while back. Are you still getting this on the lastest version? (a17 as of this comment)

This keybind here works fine for me ![Image](https://github.com/user-attachments/assets/0c2777da-3174-4475-a82a-701d65a42bba)

**Comment by salamijason** [comment]
No response in 3 days. Will be closing this issue. Please reopen if you are still facing the issue.
