### ISSUE TITLE
Bookmarks are opening in a new tab (instead of the current tab)

### ISSUE THREAD

**Issue by stripedgoat** [zen-browser/desktop#1496]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When I click on a bookmark, it actually opens in a new tab, instead of opening in the current tab that I'm in.

If this is intentional: We should have bookmarks open in the current tab. The middle click is opening them in a new tab anyway.

Thank you!

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1a-1

### What platform are you seeing the problem on?

macOS - Intel

**Comment by bhaumik-tripathi** [comment]
Hey @stripedgoat, this is the default way in which bookmarks/history tabs are opened in firefox , and hence the same in Zen.
If you want to open the bookmark in new tab, you can right click on the button and click "Open in New Tab" to open in new tab.
If you want to open bookmarks in new tabs by default, change the settings as following:-
1. Go to `about:config` in your address bar.
2. Search for in `browser.tabs.loadBookmarksInTabs` in the search bar.
3. Change the value from `false` to `true`.

You can now check that the desired behavior is achieved without restarting the browser. It is much appreciated to look for solutions online before creating a issue.
Thanks

**Comment by salamijason** [comment]
What that guy said :D
