### ISSUE TITLE
Poor visibility of active tabs in 1.0.1-a

### ISSUE THREAD

**Issue by iihmsunn** [zen-browser/desktop#1498]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Since the 1.0.1 update I can't see which tab is currently selected unless I increase screen brightness to high level and look really hard. I didn't notice this issue before. Can't remember how it used to be but there was probably a stronger color or border or something like that.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a

### What platform are you seeing the problem on?

Linux

**Comment by sjclayton** [comment]
Having the similar but opposite happen here also on 1.0.1-a on Linux, my active tab is now brighter and almost looks like it's not styled at all unlike it was before, almost looks like the Firefox default styling to me.

**Comment by iihmsunn** [comment]
I tried changing both gnome themes and zen themes and nothing changed so not sure what could be the difference. Also running linux, AUR version on one PC and flatpak on another having the same thing

**Comment by sjclayton** [comment]
@iihmsunn 

Yeah it's really odd, especially for something to be causing seemingly two related yet opposite issues. I am also running the package from the AUR here.

**Comment by iihmsunn** [comment]
this got fixed for me in 1.0.1-a.2
