### ISSUE TITLE
[proposal] A more Zen-ish logo? 

### ISSUE THREAD

**Issue by Donnnno** [zen-browser/desktop#150]
Hi, I stumbled on this browser yesterday, and it looks neat!

But there's a thing bugging me a bit, the kinda generic Z logo 🙃. So that got me started on thinking about how to give it more of a zen feel and more character. 

After some tinkering, I came up with this:

![design-1](https://github.com/user-attachments/assets/238ab7ea-1b9e-4613-aed9-45cfe1a5a6f2)
I went for some rounded, and curvy shapes, giving it a more friendly, but also calming look.

With an alternate icon for the alpha, for example: 

![design-2](https://github.com/user-attachments/assets/f3991b27-0d9a-48ae-be35-24d6d945ae0e)

If you're wondering how it looks as the actual icon, i've tested that out too:
![Screenshot 2024-08-04 170454](https://github.com/user-attachments/assets/1a514716-a97e-455e-8fcf-27b7aaa45524)
![Screenshot 2024-08-04 171449](https://github.com/user-attachments/assets/edd40f12-82fd-4766-a4bd-3d856f94df3e)

If there are any questions, feedback or other thoughts, please let me know!

**Comment by bdbch** [comment]
Funny I had a similar idea for the Z.

In general I'd like something that fits the "Zen" name.

![image](https://github.com/user-attachments/assets/0e6a462d-6886-44f4-b504-5f269826fa84)

---

<img width="802" alt="image" src="https://github.com/user-attachments/assets/777c35ef-4d6a-4b5b-9e8e-255809dace54">

I tried with multiple ripples but that looked weird.

**Comment by Donnnno** [comment]
Oh! I was tinkering with that shape too! But the 1/4th circle wave looked a bit off.

![Screenshot 2024-08-04 172442](https://github.com/user-attachments/assets/d82305c8-6409-4620-b8d8-ac726b139ab7)

**Comment by TheBestUser01234567890** [comment]
> Oh! I was tinkering with that shape too! But the 1/4th circle wave looked a bit off.
> 
> ![Screenshot 2024-08-04 172442](https://private-user-images.githubusercontent.com/31142286/354912548-d82305c8-6409-4620-b8d8-ac726b139ab7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3OTQxNTEsIm5iZiI6MTcyMjc5Mzg1MSwicGF0aCI6Ii8zMTE0MjI4Ni8zNTQ5MTI1NDgtZDgyMzA1YzgtNjQwOS00NjIwLWI4ZDgtYWM3MjZiMTM5YWI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA0VDE3NTA1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlZjgwMWU4M2E0ZDIxNDA4ZDU0ZmEyYzVhYmIwZDRiOThjMTM1YWY2YjI0YTliNDE1NDZhYjc5YmJjZTY0Y2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mQSEgF2RICTk-Axc6nOwcP_1UGSrr_XHBLstJuIbEBw)

I think 2 and 5 are really good.

**Comment by bdbch** [comment]
Some more ideas:
<img width="856" alt="image" src="https://github.com/user-attachments/assets/af1f4fca-4b60-4cca-a134-ae745d826dce">

**Comment by mauro-balades** [comment]
oh my... so many great options!

**Comment by NOCanoa** [comment]
i like the first one alpha version and the last one 0.0

**Comment by mauro-balades** [comment]
I dont want to let anyone down, they all look very good

**Comment by Donnnno** [comment]
Don't worry about letting me down haha, take your time and think about it :)
And if you have any feedback, just let us know :-)

**Comment by Donnnno** [comment]
While, I'm at it. More food for thought. ;)

Iterating a bit on the first designs 
![image](https://github.com/user-attachments/assets/1011d8a2-08a1-4039-bf82-070f5750e08c)

**Comment by TheBestUser01234567890** [comment]
> While, I'm at it. More food for thought. ;)
> 
> Iterating a bit on the first designs ![image](https://private-user-images.githubusercontent.com/31142286/354925333-1011d8a2-08a1-4039-bf82-070f5750e08c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NTA5NDIsIm5iZiI6MTcyMjg1MDY0MiwicGF0aCI6Ii8zMTE0MjI4Ni8zNTQ5MjUzMzMtMTAxMWQ4YTItMDhhMS00MDM5LWJmODItMDcwZjU3NTBlMDhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDA5MzcyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1YzQ1ZTkzN2RkMWFiOWYyYjI1YTAxMmQ2OWJmY2JhODE4OTk4ZDc0OTNkOTdhYjJiMTA2YmNkZWNiMmNjMGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9oMoNH0p3cqX02bgDvqGC-Cq1FGdXasHno_j58XYov4)

3, 4, 7, and 8 look the best.

**Comment by mauro-balades** [comment]
id like more neutral colors, like in this one https://github.com/zen-browser/desktop/issues/150#issuecomment-2267583521

**Comment by mauro-balades** [comment]
https://github.com/zen-browser/desktop/discussions/168

**Comment by Donnnno** [comment]
Poll time! 👀

Also I would think about the shape first, colors can be edited more easily after that :)

**Comment by IAmJafeth** [comment]
Hey @Donnnno could you please share a PNG with transparent background of your logo?
I want to add it to my Zen right now and start using it <3

**Comment by Donnnno** [comment]
Tweaked some stuff.
Monochrome works pretty good in my opinion.

<img width="512" alt="monochrome" src="https://github.com/user-attachments/assets/dc5cf1be-ad94-41fd-bf49-01dbcef05e42">

<img width="512" alt="wordmark" src="https://github.com/user-attachments/assets/fa8f7bee-1fdd-479f-9bff-6c7b549e8f7a">



<img width="512" alt="app-icon" src="https://github.com/user-attachments/assets/3a090587-7679-44b7-b71f-5f7faf44183d">

**Comment by mauro-balades** [comment]
We've talked about this in DMs but I wonder if the middle bar could blend in a bit more to make it look more like a Z?

instead of living so much whitespace

**Comment by Donnnno** [comment]
Presenting the new logo: 
https://github.com/user-attachments/assets/cb5e71ed-b7b3-4dd3-9237-c1dc88d24a07

https://github.com/user-attachments/assets/2820156d-82b8-48ad-a461-53e39b09aeac

**Comment by win98se** [comment]
Hijacking this issue - the new icon in Windows executable seems to be 256\*256 only, however it needs to be in 16\*16, 32\*32 and 48\*48 as well.
![image](https://github.com/user-attachments/assets/4e09a83c-e938-442f-bfde-133c506cacc8)
![image](https://github.com/user-attachments/assets/c9c4e14d-822a-4b9f-b3ec-7b28a53a6f99)

**Comment by Donnnno** [comment]
@win98se thanks for reporting. I'm having some difficulty understanding the ico format. The version before that, the resolution was actually too low. But I'll look at it again :-)

**Comment by Donnnno** [comment]
A fix is on the way: 
![image](https://github.com/user-attachments/assets/f59975e6-190d-41b3-bd44-ba4fd62685d6)

**Comment by win98se** [comment]
> A fix is on the way

It looks much better now on 1.0.0-a.26. Thank you!

**Comment by takenotice** [comment]
I would love an alternate colored logo like the teal above. With my desktop in dark mode the b&w icon gets lost.

**Comment by Donnnno** [comment]
> I would love an alternate colored logo like the teal above. With my desktop in dark mode the b&w icon gets lost.

Check out the branding assets!
https://zen-browser.app/branding-assets 
(There's also a github repo with the ico files for Windows)
