### ISSUE TITLE
Broken features/UI after 1.0.1-a.1 update

### ISSUE THREAD

**Issue by DaitiDay** [zen-browser/desktop#1504]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Here is a list of what I found to be broken after 1.0.1-a.1 update.
- The tabbar doesn't overflow, there is no scrollbar and opening tabs just maked them shink with the icon disappearing
- Updating made more than half of my pinned tab disappear
- The 'Expand sidebar' button cannot be disable even after checking the box in the settings
- Using the Audio TabIcon Plus theme when I hover over a tab with an audio source playing the tab icon disappears (I'm going to look into this since I'm the author of the theme, but this behavior is kinda weird and I don't think it's/should be theme-related)
- Enabling the `Use legacy toolbar position` works, but the alignment of the various elemens is not right. For what I can see:
    - The `Go back one page` button is too close to the left window border
  ![image](https://github.com/user-attachments/assets/13d41055-af2f-4bd0-91cd-5def1f74e34c)
  Furthermore, but this might be personal preferences/opinions even though I think they should be taken into consideration:
    - The workspace button is much wider that the tabs
    - The top-border of the workspace button should be aligned with the top of the web page
  ![image](https://github.com/user-attachments/assets/c08939b7-43c8-4423-b32c-c5c720826f29)

I'll update this issue if I find out some other "problems".

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.1

### What platform are you seeing the problem on?

Windows

**Comment by YelehaUwU** [comment]
Fullscreen has browser borders in compact mode after this update.

**Comment by DaitiDay** [comment]
In private mode there is this below the tabs
![image](https://github.com/user-attachments/assets/7ac0ce98-3478-4f86-9006-16ffe4460778)

**Comment by DaitiDay** [comment]
The loading animation is not centered in the tab container:
All to the left: 
![image](https://github.com/user-attachments/assets/dfa475d6-316e-44fc-b31a-5f8ca4c8f664)
All to the right:
![image](https://github.com/user-attachments/assets/e4535c20-2a01-445a-a9d6-b645278358a4)

**Comment by mauro-balades** [comment]
All fixed I think, thanks! Releasing today

**Comment by DaitiDay** [comment]
Super quick, great work! 😄
