### ISSUE TITLE
Middle Click To Scroll (Auto Scrolling) in Web Panel Not Working

### ISSUE THREAD

**Issue by ido1901** [zen-browser/desktop#151]
### What happened?

When viewing a website/pdf in web panel, middle click to scroll (auto scrolling) doesn't work. It works fine anywhere else, in normal tabs and in split view.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.12

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
Have you tried enabling it on the settings page?
