### ISSUE TITLE
tab-rendering-issue

### ISSUE THREAD

**Issue by coderstarrer** [zen-browser/desktop#1511]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![Screenshot 2024-09-17 162553](https://github.com/user-attachments/assets/f84873a2-aece-425b-929c-ed0267b61b40)
It only happened after it got updated to the latest version
if i open more tabs it becomes invisible

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.1(64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by itsTyrion** [comment]
>  if i open more tabs it becomes invisible

uh yeah pretty much
![{CBAB6CF6-D0D8-49B1-BA5E-66E8C39F00A7}](https://github.com/user-attachments/assets/c410b982-6c87-420d-8454-49bf73f1e8da)

**Comment by jfftck** [comment]
I am getting the same issue on Linux, so I doubt it is platform dependent.

**Comment by tinemuz** [comment]
Yes, same issue as well 
![image](https://github.com/user-attachments/assets/55d309f2-5bc6-45c1-8bff-9249e119aa1c)

**Comment by mauro-balades** [comment]
This has been fixed, sorry about that... The build is building right now for the update
