### ISSUE TITLE
Left, Bottom, and Right borders visible when in full screen mode

### ISSUE THREAD

**Issue by auppal12** [zen-browser/desktop#1513]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When any video is played in full screen mode; left, bottom, and right side border is still visible.
![Screenshot 2024-09-17 160512](https://github.com/user-attachments/assets/da0dfb3f-ced1-4dc2-9790-6bd8ea8bf26a)
 

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.1

### What platform are you seeing the problem on?

Windows

**Comment by perrylets** [comment]
I had a worse problem before, now I have this version of the problem

**Comment by tushyagupta81** [comment]
Same issue but happens only in compact mode. It is fine in normal mode

**Comment by mauro-balades** [comment]
This has now been fixed, thanks! Please remember to update
