### ISSUE TITLE
Zen core dumped on me?

### ISSUE THREAD

**Issue by melroy89** [zen-browser/desktop#1514]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I downloaded the AppImage (optimized and fast version) for Linux.

I made the AppImage executable. And executing the appimage gives me:

```sh
 ./zen-specific.AppImage 
Illegal instruction (core dumped)
```

Now, I also tried the zip file. Same error!

```sh
./zen
Illegal instruction (core dumped)

# Or: 
./zen-bin 
Illegal instruction (core dumped)
```

That is not good.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Alpha build - 1.0.1-a.1

### What platform are you seeing the problem on?

Linux (Linux Mint 22)

### Relevant log output

```shell
Illegal instruction (core dumped)
```

**Comment by mauro-balades** [comment]
Please download the generic version, your CPU is not supported

**Comment by melroy89** [comment]
This was the normal download from your site?

Sorry but could you reopen? I think you need to be very clear about what platform do you mean with "optimized"??
I'm just running 64-bit amd64 platform.
