### ISSUE TITLE
Strange small font size on tabs since 1.0.1-a.2

### ISSUE THREAD

**Issue by PikachuEXE** [zen-browser/desktop#1518]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

It looks like this now
![2024-09-18 14_34_09-New Issue · zen-browser_desktop — Zen Browser](https://github.com/user-attachments/assets/4ab142c4-b0a0-4292-9db8-083556b79eaa)

The font size was normal when I used [1.0.1-a.1 (2024-09-16)](https://github.com/zen-browser/desktop/releases/tag/1.0.1-a.1) earlier today (I check update almost daily)

`1.0.1-a.1`:
![2024-09-18 14_41_55-Strange small font size on tabs since 1 0 1-a 2 · Issue #1518 · zen-browser_desk](https://github.com/user-attachments/assets/78313e44-10b4-4e17-9eb0-415a168f556f)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.2

### What platform are you seeing the problem on?

Windows

**Comment by gitartiman2499** [comment]
same its weird

**Comment by coderstarrer** [comment]
You can fix it by putting
`.tab-text {
	font-size: 12px !important;
}

#vertical-tabs-newtab-button {
	font-size: 12px !important;
}`

in your userChrome.css file

**Comment by PikachuEXE** [comment]
See https://github.com/zen-browser/desktop/issues/1524 for workaround

**Comment by mauro-balades** [comment]
This has been fixed for the next release, thanks!
