### ISSUE TITLE
Bookmarks gets rendered on top of everything

### ISSUE THREAD

**Issue by Rhelvetican** [zen-browser/desktop#1519]
### Captchas

- [ ] I am not filing an enhancement request.
- [ ] I have searched existing issues and avoided creating duplicates.
- [X] I have read the instructions.

### What happened?

![image](https://github.com/user-attachments/assets/687e5298-1727-48d1-8111-87454de0b674)

It should be rendered below the side panel.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.2

### What platform are you seeing the problem on?

Windows

**Comment by RayZ3R0** [comment]
Hello, @Rhelvetican Does this still happen in latest version a.14?

**Comment by Rhelvetican** [comment]
@RayZ3R0 Nope :)

**Comment by RayZ3R0** [comment]
Will be closing the issue then, thanks for reporting!
