### ISSUE TITLE
Permission requests do not work on sites

### ISSUE THREAD

**Issue by julienallexandre** [zen-browser/desktop#1520]
### Captchas

- [X] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.

### What happened?

Here's a simple example of outlook notifications.

https://github.com/user-attachments/assets/cb2aaa11-5e63-4b08-8592-1c5cb8f901e0

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.2

### What platform are you seeing the problem on?

macOS - Intel

**Comment by ulrichSchreiner** [comment]
requesting the permission generates an error. when testing with the example from mozilla dev-network

https://mdn.github.io/dom-examples/to-do-notifications/

after clicking the "Enable notification" you get the following in the JS console

~~~
Failed to get subsystem status for purpose 
Object { rejected: true, message: Error }
​
message: Error: Attempt to postMessage on disconnected port
​​
columnNumber: 14
​​
fileName: "moz-extension://6156a1ac-7235-41e9-8304-717e3c3fb5fe/extension-utils.js"
​​
lineNumber: 72
​​
message: "Attempt to postMessage on disconnected port"
​​
stack: "sendPortMessageWithReply/<@moz-extension://6156a1ac-7235-41e9-8304-717e3c3fb5fe/extension-utils.js:72:14\nsendPortMessageWithReply@moz-extension://6156a1ac-7235-41e9-8304-717e3c3fb5fe/extension-utils.js:58:12\n@moz-extension://6156a1ac-7235-41e9-8304-717e3c3fb5fe/extension.js:247:12\n@moz-extension://6156a1ac-7235-41e9-8304-717e3c3fb5fe/extension-utils.js:130:57\n"
~~~

**Comment by RayZ3R0** [comment]
Does this still happen on latest version? (a.14 as of this comment)

**Comment by ulrichSchreiner** [comment]
i use 1.0.1-a.14 on arch.

the permission request does still not work for me.

**Comment by RayZ3R0** [comment]
Alright, we'll look into it. #2093 is a similar issue. I think this issue can be moved to that as its newer

**Comment by RayZ3R0** [comment]
Its being fixed, probably next update. Closing this
