### ISSUE TITLE
Catppuccin theme different on Windows

### ISSUE THREAD

**Issue by beeb** [zen-browser/desktop#1521]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Installed [the catppuccin theme](https://zen-browser.app/themes/e3eec307-7c64-4cbd-a0c5-3447cd45a840) by @mauro-balades but couldn't find a repo for it so I'm reporting here and tagging them.

The theme does not affect the background color of the window like it does on Ubuntu.

![image](https://github.com/user-attachments/assets/ac16a31c-f273-4037-94f5-e388e3c9c80d)

On Windows, the background is plain grey and doesn't have the blueish tint from the catppucin theme. On Ubuntu this is not a problem.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.2

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
You have the "doable toolbar theming" option enabled. Please disable it on the look and feel preferences

**Comment by beeb** [comment]
I didn't find the option you mention but I did find the option below and it fixes it when I check it:

![image](https://github.com/user-attachments/assets/70e299ff-48b5-4ce1-8892-8ca98c85e976)

**Comment by beeb** [comment]
Hey there @mauro-balades . The option I mentioned above was removed and the bug is now present again (on both Ubuntu and Windows for me).
