### ISSUE TITLE
wrong UI position.

### ISSUE THREAD

**Issue by onlyibra** [zen-browser/desktop#1523]
### Captchas

- [X] I have read the instructions.
- [ ] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

So I found the wrong UI position on the exit (X) button and the screenshot button in compact mode:

1. 
<img width="98" alt="Cuplikan layar 2024-09-18 182432" src="https://github.com/user-attachments/assets/a27d0ee3-b5a6-47c9-8ea5-ceb5d226099a"> that is the exit button, it just goes through the screen

2. 
<img width="70" alt="Cuplikan layar 2024-09-18 182535" src="https://github.com/user-attachments/assets/bf73acba-997c-47a2-9812-50849d704ac9"> it also happen with screenshot button

they are OK in not-compact mode, it only happen in compact mode.

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.2

### What platform are you seeing the problem on?

Windows

**Comment by tushyagupta81** [comment]
I have the same issue in non-compact mode too
