### ISSUE TITLE
[Minor bug]: Zen Mods still called 'Themes' in Mods settings and when uninstalling

### ISSUE THREAD

**Issue by enoversum** [zen-browser/desktop#1525]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Just a minor oversight, I would say, and nothing major, but just for completion. Zen's Mod page is still reading 'Uninstall theme', and the popup is still asking if I want to uninstall a theme when I do so. Should be renamed to 'Mods'. Just for your backlog of small, joyful things to do for this wonderful little browser 😊.

![image](https://github.com/user-attachments/assets/4a511ac5-4e20-4171-bd08-b5152b31ff3d)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.2

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
Fixed, thanks!
