### ISSUE TITLE
Scrolling screenshots on PDFs do not work

### ISSUE THREAD

**Issue by JSGRD22** [zen-browser/desktop#1526]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Normally, the screenshot tool can take scrolling screenshots. The "save full page" button will also take a scrolling screenshot of the entire page. However, this does not work when opening a PDF in the browser: screenshots are limited to the visible area, and "save full page" only captures the visible area. It would be very helpful if scrolling screenshots are possible on PDFs too.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.1

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
Does it still happen?

**Comment by JSGRD22** [comment]
> Does it still happen?

Still happens on a.4. I think it happened in a.5 too but I can't check rn because I reverted to a.4 due to the keyboard shortcut bug.

**Comment by JSGRD22** [comment]
This remains unfixed in a.10

**Comment by RayZ3R0** [comment]
Does this still happen on latest version? (a.14 as of this comment)

**Comment by JSGRD22** [comment]
Still happens on a.15

**Comment by RayZ3R0** [comment]
Hmm i think this is how firefox does it too right? Can't do anything about that then. Maybe you can suggest this in https://github.com/zen-browser/desktop/discussions since this is more of a feature request

**Comment by salamijason** [comment]
No response in 1 week, will be closing this issue. Please reopen in discussions as an Idea since its a firefox issue
