### ISSUE TITLE
Problems with compatibility in websites

### ISSUE THREAD

**Issue by OffShur3** [zen-browser/desktop#1527]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I'm having trouble connecting to some websites due to compatibility issues.
This seemed strange to me because Zen is supposedly updated to the most recent version of Firefox
I have the recently updated alpha 2 version, but it's still in the same state. I even tried with userAgents, in private modes, and even deleting the data in the .zen folder and everything is still the same
To reproduce go to the website deezer.com. Although it also happens with some YouTube videos.
I also tried new and old versions of Firefox but these websites work normally on them.

![imagen](https://github.com/user-attachments/assets/bb4dc177-517d-4552-825c-1690f4fd70e9)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.2

### What platform are you seeing the problem on?

Linux

**Comment by julienallexandre** [comment]
I have the same problem with the Twitch website
