### ISSUE TITLE
Sidebar mobile agent

### ISSUE THREAD

**Issue by YelehaUwU** [zen-browser/desktop#1536]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The sidebar ignores the mobile checkbox, I have to manually disable the mobile agent after the tab is created.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.2

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
This has been fixed for the next release, thanks!
