### ISSUE TITLE
Grid exiting

### ISSUE THREAD

**Issue by YelehaUwU** [zen-browser/desktop#1539]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

After exiting a gridview containing 6 or more tabs, the UI got glitched on all tabs.
![image](https://github.com/user-attachments/assets/c2dd7418-87dd-4f8e-9a6e-fd996c80c67e)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.2

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
This should be fixed for the next release, thanks!

**Comment by mr-cheffy** [comment]
Does this still happen?

**Comment by YelehaUwU** [comment]
Unable to reproduce for a long time.
