### ISSUE TITLE
Let web side panel be active in backround

### ISSUE THREAD

**Issue by NOCanoa** [zen-browser/desktop#154]
### What feature would you like to see?

I wold like to be able to have a button option to have one of the wen side panel not go " to sleep" because now if i have yt music playing and hide it then music stops : ( 

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
It already stays active once you close it, what's your issue reall?

**Comment by NOCanoa** [comment]
if i have yt music playing and i close it the music stops, cant keep it to stay active in a.11 it stayed active

**Comment by mauro-balades** [comment]
https://github.com/user-attachments/assets/6e16f50d-60fc-44e2-afa6-ad372a5e5dfe

**Comment by NOCanoa** [comment]
btw thats yt not yt music, but its because yt music on mobile needs sreen to stay active so i changed to disable mobile user agent now it works xD

**Comment by NOCanoa** [comment]
when i close and open its goes to the default scree how can i change it it does to the last used?

**Comment by mauro-balades** [comment]
https://github.com/user-attachments/assets/aa4a63a1-00bc-4723-ab4d-c5d0fb27dfe7
