### ISSUE TITLE
Unable to Type Full Reddit Comment in Zen Browser - Letters Disappear After First Input

### ISSUE THREAD

**Issue by expertmanofficial** [zen-browser/desktop#1540]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When typing a comment under any Reddit post using Zen Browser, only the first letter of the comment is displayed. After that, subsequent letters erase themselves as soon as they are typed. For example, when trying to type the word "Good," only the letter "G" appears, and the rest are automatically removed. This issue occurs across multiple Reddit posts and persists after clearing cache and cookies. Other browsers, like Firefox, do not have this problem.

**Steps to Reproduce:**

    1.Open Zen Browser and navigate to any Reddit post.
    2.Click on the comment field to type a reply.
    3.Start typing a word (e.g., "Good").
    4.Observe that only the first letter appears, and subsequent letters are erased.

**Expected Behavior:**
The comment box should allow typing full words without erasing any characters.

**Actual Behavior:**
Only the first letter of a word is typed, and the rest of the letters erase themselves.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.1

### What platform are you seeing the problem on?

Linux

**Comment by sjclayton** [comment]
I cannot reproduce this in 1.0.1-a2 on Linux... works like it should for me.

**Comment by expertmanofficial** [comment]
> I cannot reproduce this in 1.0.1-a.2 on Linux... works like it should for me.

@sjclayton I am on Linux Mint, 20.3, Cinnamon, running it on Lenovo ThinkCentre 90z. Happens to me still.

To make more clear, sometimes I suspect that the rest isn't erased, but rather is same the text is same color as the field's black background.

I'm using black theme.

Happens same when trying to write Reddit posts's content, but doesn't happens with titles.

**Comment by mauro-balades** [comment]
Does it happen on any other site?

**Comment by onthejobtraining** [comment]
I am having issues with formatting text on reddit site, maybe the issues are related. for example we use ` ` to put something in code but it won't work on zen on reddit site specifically.

**Comment by expertmanofficial** [comment]
no, bot, shut up. It's not stale.

**Comment by RayZ3R0** [comment]
Does this still happen on latest version? (a.14 as of this comment) haven't encountered this

**Comment by salamijason** [comment]
No response in 2 weeks, will be closing this issue. Please reopen if issue persists.
