### ISSUE TITLE
How to scroll thru all tabs via mouse scroller?

### ISSUE THREAD

**Issue by Dean-Corso** [zen-browser/desktop#1541]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I would like to know whether its possible to scroll thru all tabs right away instead of choosing and enable any of them manually? Lets say I have open tons of tabs 100+ and now I would like to run thru them on the sidebar via mouse scroller + strg (ctrl) button to jump from selected one to next above or below etc. So a function like that I'm using as standard function in listview controls too. So is it possible to add such an function in any next release?

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.2 (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by JSGRD22** [comment]
https://docs.zen-browser.app/faq

You can enable this feature by changing a setting in the browser’s configuration. Here’s how:

1. Open the `about:config` page. This page contains advanced settings for the browser.
2. Search for `toolkit.tabbox.switchByScrolling`.
3. Toggle the setting to `true` by double-clicking on it.

Once this setting is enabled, you can hover your mouse over the tab bar and use your mouse wheel to scroll through the tabs, making it easier to navigate between them.

**Comment by Dean-Corso** [comment]
Super info @JSGRD22 and thank you! Maybe its a bad idea to hide this feature instead to show it up to the user directly in main setup window. Only setting point I see is "Ctrl+Tab cycles through tabs in recently used order" I do not prefer using it. Only problem I still have is that ZEN using a small border around the window (left & right) where the mouse pointer scrolling does not work (total left & right position) and I have to move it to inside a little.
