### ISSUE TITLE
Misaligned Padding across window 

### ISSUE THREAD

**Issue by tanaybhomia** [zen-browser/desktop#1542]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The padding across the window is improper , the padding on the left side is slightly misaligned when compared to the right border window padding. 

Left Side padding 
![image](https://github.com/user-attachments/assets/389fbfff-0dce-4663-be89-228b5bbba06b)

Right side padding 
![image](https://github.com/user-attachments/assets/e2c96681-725c-444c-a5d8-f50fceba8e89)

Same goes with the Top and bottom padding 

I have also tried disabling various extensions, Just for info these are the extensions which i am using. 

![image](https://github.com/user-attachments/assets/ce8f89c4-1f95-4381-b8d7-100aa2734b6f)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.2 (64-bit)

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
This has been fixed for the next release, thanks!
