### ISSUE TITLE
Strange behaviours in Customize Toolbar when modifying vertical tab space

### ISSUE THREAD

**Issue by JSGRD22** [zen-browser/desktop#1543]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Customize Toolbar is now able to add buttons to the vertical tab space. However, there are a number of significant bugs and peculiar behaviours that prevent this from being effectively utilised.

- The entire vertical tab space becomes blank but can still be interacted with when opening the Customize Toolbar function. Everything on it turns invisible.
- Moving any button to and from this space pins it to the centre-bottom. However, when the vertical tab space is expanded, the hitbox of the button spans its entire width.
- One would expect the space at the bottom with a bunch of buttons to be the focal point of this feature, but instead, they cannot be interacted with at all. New buttons are placed directly inside the tab space instead.
- Moving any button to and from this space also displaces the tabs at the top downwards by a certain degree, leaving a blank space between the workspaces button and the pins/new tab button. This seems to only be fixed on browser restart.

I am aware that this customization feature is still being worked on and some of these behaviours could be known and are likely to change in the next few releases.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.2

### What platform are you seeing the problem on?

Windows

**Comment by thesuzerain** [comment]
I was able to reproduce this on Mac OS as well. 

<img width="1507" alt="Screenshot 2024-09-21 at 1 58 40 AM" src="https://github.com/user-attachments/assets/4238b218-cbbe-406a-96e3-f38753fd102d">

**Comment by sek0n** [comment]
I'm still getting this, as well as rclicking on the tab barin an empty area isnt giving the "reopen closed tab" option anymore either.

![image](https://github.com/user-attachments/assets/45415cb4-aa13-4fb3-b179-4d0983c9ca6d)
![image](https://github.com/user-attachments/assets/15542319-c33d-4cf7-b35c-5741227f4a82)
