### ISSUE TITLE
Inconsistent spacing above and below sidebar in compact mode.

### ISSUE THREAD

**Issue by umarhamzy** [zen-browser/desktop#1545]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![image](https://github.com/user-attachments/assets/3ec58de3-db7e-4146-a857-6fac2feada5e)

As you can see above, there's a missing margin top at the top of the sidebar in compact mode (both when expanded and not expanded).

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.2 (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
This has been fixed, thanks!
