### ISSUE TITLE
Can't use 1Password desktop integration

### ISSUE THREAD

**Issue by drafolin** [zen-browser/desktop#1546]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Hi there,

I'm using Zen Browser, and trying to use the 1password desktop integration. As a standalone, the 1password extension works fairly well, if we put aside a few glitches here and there.

Thing is, 1Password web doesn't unlock whenever 1P desktop does, which it should.

I am running Arch (btw), using gnome/gdm and wayland.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1.a.2-1

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
# From the extension console:

💫 Looking for desktop app com.1password.1password background.js:1220:214654
📤 Sending <NmRequestAccounts> message to native core <3338843819> background.js:1220:216851
Received <BrowserVerificationFailed> from the native core background.js:1220:216405
```

**Comment by mdatla** [comment]
https://github.com/zen-browser/desktop/issues/1462

**Comment by drafolin** [comment]
@mdatla totally. Didn't find it cuz i was specifically looking for 1password and apparently github's issue search doesn't search in issue bodies.
