### ISSUE TITLE
Smaller icons and gaps

### ISSUE THREAD

**Issue by NandiyaLive** [zen-browser/desktop#155]
### What feature would you like to see?

Can we reduce the icon sizes, collapsed vertical tabs width and gaps? Then there will be more space to view a webpage.
Brave Browser is a good reference for the sizes.

![image](https://github.com/user-attachments/assets/f669e2ee-62be-4f04-88c4-5f0b0d05f101)

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
Im not planning on doing this but you certainly can by adding a `chrome/userChrome.css` file inside your profile's directory with the following content:

```css
#navigator-toolbox {
   min-width: 45px;
}
```
