### ISSUE TITLE
messenger on sidebar is bugged

### ISSUE THREAD

**Issue by Yapper27** [zen-browser/desktop#1550]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![image](https://github.com/user-attachments/assets/1eb4bd73-e19c-4291-9ee9-1546d49fda7c)
![image](https://github.com/user-attachments/assets/bcf7ec7c-f8de-41c4-baf6-48ce0d66c8fc)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1

### What platform are you seeing the problem on?

Windows

**Comment by Yapper27** [comment]
facebook work fine

**Comment by Boy-With-Uke** [comment]
Have u tried diabling Mobile User Agent ?

**Comment by mauro-balades** [comment]
^
