### ISSUE TITLE
Can't middle click to open a link a new tab / cant open a tab using ctrl + t

### ISSUE THREAD

**Issue by vanishLLC** [zen-browser/desktop#1553]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Hello! I've noticed a few days ago that I can't open new tabs without right clicking normally I used ctrl T and click middle button to open new tabs/ links in a new tab but As I said it stopped working clicking the "+" icon at the top left don't work either the only way I have managed to open a new tab was via right clicking -> new tab Is there any fix?

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.2

### What platform are you seeing the problem on?

Windows

**Comment by unsigned57** [comment]
I also encountered this problem, but I solved it after reinstalling.

**Comment by ewen-lbh** [comment]
I'm encountering the same issue, and reinstalling did not fix it

**Comment by onthejobtraining** [comment]
@vanishLLC

That's weird because Ctrl+T is working fine on my windows to open a new tab, and to open links on a new tab I use ctrl+left click. And to open links on a new window, I use shift+right click. Have you tried testing on a separate profile with default settings?

**Comment by vanishLLC** [comment]
@onthejobtraining chaning profile to deafult worked! Its weird tho why is sudenlly stopped working

**Comment by sjclayton** [comment]
@vanishLLC 

Pretty sure this can be closed now, if you're no longer having this issue... Seems like this is no longer an issue as of 1.0.1-a.8
