### ISSUE TITLE
Compact Mode Bugs

### ISSUE THREAD

**Issue by whopastoo** [zen-browser/desktop#1555]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

So when you use zen browser In compact mode and minimize the tab the search bar disappears, I explain this pretty well in the video. Secondly the tab bar is really annoying to use on a dual monitor setup simply because if my tab bar is on the right side and I use my left monitor it can be hard to grab the tab bar. I love the look of compact mode but it can be a hassle sometimes.

https://github.com/user-attachments/assets/c853e7cd-bb42-4c67-8145-fd5aa7ae5506

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.2 (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
All of these has been fixed for the next update, thanks!
