### ISSUE TITLE
Pinned tabs do not stay visible across workspaces

### ISSUE THREAD

**Issue by ccalhoun1999** [zen-browser/desktop#1557]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Starting a couple days ago, my pinned tabs dissapear when switching workspaces. When returning to the workspace they were created in, they re-appear. This also has a cascading side-effect where I cannot re-organize the uppermost tabs when the pinned tabs are hidden (seemingly because they are overlapping with the hidden pinned tabs). I am also unable to "ctrl-tab" to reach the pinned tabs when they are not visible.
To the best of my knowledge, Firefox does not have workspaces so I cannot reproduce this issue there.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.2 (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by LifeAO** [comment]
This is a feature added into version `1.0.1-a`: "Added preference for separate pinned tabs per workspace"

You may have it enabled. The toggle can be found in:
Link: `about:preferences#zenWorkspaces`
or `Settings/Preferences > Workspaces > 'Allow workspaces have their own pinned tabs' ON/OFF`

![Screenshot_20240920_180215](https://github.com/user-attachments/assets/eb87cd8f-dcef-47ab-9442-a122df182e6d)
