### ISSUE TITLE
F11 sidebar compact mode doesnt want to come out

### ISSUE THREAD

**Issue by NOCanoa** [zen-browser/desktop#156]
### What happened?

A video should explain, the side bar bug in full full screen f11 is back

https://github.com/user-attachments/assets/702c210b-1142-449a-8e2a-359f1a9bea63

As seen it side bar sometimes comes from the top or from the side or not at all.

this is in new profile 
![image](https://github.com/user-attachments/assets/f448f50d-498a-49db-96b0-c9abe5a6c3f1)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.12-opt

### Severity impact

Medium

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
Fixed with https://github.com/zen-browser/desktop/commit/9968d550aec0a71f120f77a106b46535b9de7cd6
