### ISSUE TITLE
Sharing option not available

### ISSUE THREAD

**Issue by julienallexandre** [zen-browser/desktop#1561]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

It is not possible to share via sms and other channels, as is the case with all browsers.

Zen :
<img width="1440" alt="no share zen" src="https://github.com/user-attachments/assets/9a5d7a36-cbf5-4993-8636-d8ebf23ce92c">

Firefox : 
<img width="1440" alt="share firefox" src="https://github.com/user-attachments/assets/eeef5e75-80cd-4737-90ad-ac373560139b">

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.2

### What platform are you seeing the problem on?

macOS - Intel

**Comment by mauro-balades** [comment]
What Firefox version is this?

**Comment by julienallexandre** [comment]
> What Firefox version is this?

130.0.1

**Comment by julienallexandre** [comment]
When will this feature be available? @mr-cheff

**Comment by mr-cheffy** [comment]
Does it still happen?

**Comment by julienallexandre** [comment]
> Does it still happen?

Yes, still no sharing option
