### ISSUE TITLE
[macOS] Cmd+C in DevTools toggles Compact mode, doesn't copy to clipboard

### ISSUE THREAD

**Issue by chriskirknielsen** [zen-browser/desktop#1563]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I was editing a page in DevTools and wanted to copy the updated CSS, so like I usually do, I highlight the block of new code and hit `Cmd+C` to copy it, only this toggled Compact Mode instead, and my clipboard contents were unchanged.

I verified my shortcuts and Compact Mode is set to `Ctrl+Cmd+C` — which does not work, I can file a new bug if unreported/unrelated. I can confirm this does not happen when copying from a regular web page, like typing this here, I can select all, and `Cmd+C` correctly copied my text and does not toggle Compact Mode.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.2

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by NOCanoa** [comment]
Keyboard short cuts are being worked on!

**Comment by HarryHeres** [comment]
Please follow progress in [https://github.com/zen-browser/desktop/issues/1629](https://github.com/zen-browser/desktop/issues/1629)
