### ISSUE TITLE
Add a toggle to change Vertical Tabs (and Sidebar) position to the right side of the browser.

### ISSUE THREAD

**Issue by Iron56716** [zen-browser/desktop#157]
### What feature would you like to see?

It would be great if Zen Browser allowed an option to change the location of the Vertical Tabs and Sidebar to the right side, as it would be an better option for many people (including me) as many people like me are more used to it in the right (like Edge, Floorp). 

The attached screenshot shows the Sidebar on the right side on Floorp browser (based on Firefox ESR).
![Screenshot 2024-08-04 221810](https://github.com/user-attachments/assets/ef9f7bfd-53ff-4834-bd1e-bfb1aae7e27e)
![Screenshot 2024-08-04 222200](https://github.com/user-attachments/assets/32c4c5ad-71d0-4a77-ad07-ec8065e9c9bb)

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
Thanks for this suggestion! Its going to be available in version .15!

https://github.com/zen-browser/desktop/commit/fc5bd615f473e494deab52fc52e2423efc5636eb

**Comment by knowler** [comment]
This doesn’t seem to be working unless I toggle the `zen.tabs.vertical.right-side` value in `about:config`. I can see the “Tabs on the right” in the context menu when right clicking, but toggling it doesn’t have any effect.

**Comment by astatine** [comment]
I'm sorry, but was this fully implemented? I can move the tab column to the right, but how do I do that to the Sidebar?

Ideally, I would like the tab column to be on the left, and the Sidebar to be on the right.

**Comment by Kagukara** [comment]
The Zen Sidebar still doesn't have an option for moving it to the right. Can this issue be reopened as only 1/2 of the enhancements the op asked for have been implemented? Also saves on making a duplicate issue.
- OS: Arch Linux
- Version:  1.0.0-a.32

**Comment by mauro-balades** [comment]
Right click on the sidebar and click on "more to the right"

**Comment by Kagukara** [comment]
> Right click on the sidebar and click on "more to the right"

This is all the options I get, the tab bar is already on the right, but the Zen Sidebar is not. Right clicking on the Zen Sidebar does nothing.
![image](https://github.com/user-attachments/assets/882a94f6-902c-4959-92d4-d47ad1b7881e)

**Comment by arrzdev** [comment]
I have the tabs stuck on the right side even tho zen.tabs.vertical.right-side is set to false, I also get weird animations when hiding it as I get animations on the left even tho the tabs are on the left.

On MacBook Pro M3

**Comment by JairoMartinezA** [comment]
Changing the value using about:config works for me.

    zen.tabs.vertical.right-side -> true

**Comment by Kagukara** [comment]
> Changing the value using about:config works for me.
> 
> ```
> zen.tabs.vertical.right-side -> true
> ```
> Comment: https://github.com/zen-browser/desktop/issues/157#issuecomment-2385860239

The Zen Sidebar is still on the right, setting it in about:config still does nothing.

![image](https://github.com/user-attachments/assets/b046af43-1c83-49a0-a713-55cbf040c199)

**Comment by Kagukara** [comment]
@Iron56716 Would you be able to reopen this issue if possible? As a new one cannot be made about this when creating a new issue due to:
> I have searched existing issues and avoided creating duplicates.

Would be nice if @mauro-balades would do it.

**Comment by JairoMartinezA** [comment]
Sorry @Kagukara,

In my case, my concern was more related to the tabs' position, but you are right! the sidebar still opens on the left side.
