### ISSUE TITLE
ChatGPT not working

### ISSUE THREAD

**Issue by Pranit-DC** [zen-browser/desktop#1573]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

ChatGPT site does not works after update
![Screenshot 2024-09-21 143839](https://github.com/user-attachments/assets/690e3e04-9cac-40f8-91c3-b183c576045c)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.2

### What platform are you seeing the problem on?

Windows

**Comment by n7itro** [comment]
Can you confirm that this issue occurs without any Firefox add-ons enabled?

**Comment by LAUCHGeorge** [comment]
fyi this is a firefox issue

**Comment by RayZ3R0** [comment]
Its a firefox experimental feature, nothing to do with zen. Closing
