### ISSUE TITLE
Exit button padding

### ISSUE THREAD

**Issue by nazmiyigitefe** [zen-browser/desktop#1583]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Exit button is looks really weird, it's at right a lot.

![Ekran görüntüsü 2024-09-21 162445](https://github.com/user-attachments/assets/f08c2ad1-019b-491d-a459-533dbd5b1b54)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1.a32

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
This has been fixed, thanks!
