### ISSUE TITLE
Toolbar doesn´t get themed in Zen Auto Theme on Light Mode

### ISSUE THREAD

**Issue by davidbecker808** [zen-browser/desktop#1586]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Toolbar doesn´t get themed in Zen Auto Theme on Light Mode.
On Light Theme or Zen Dream it does get themed when enabling Theming for the Toolbar.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a2

### What platform are you seeing the problem on?

Windows

**Comment by n7itro** [comment]
Currently, that option is only for website appearance. If you want to suggest this as a feature, please go to [discussions](https://github.com/zen-browser/desktop/discussions)

**Comment by davidbecker808** [comment]
Hi, sorry for maybe bothering you, i just want to add a few pictures to make it clearer, because i think you missunderstood my bug report:
![grafik](https://github.com/user-attachments/assets/22cf4da6-6e3c-4e05-b1aa-a3a5cb511fa1)
Thats the option i meant
![grafik](https://github.com/user-attachments/assets/eac3934e-65b5-47f0-8a62-7667645a322a)
Thats with the Light Theme ^
![grafik](https://github.com/user-attachments/assets/3724c9c6-46af-456d-9354-0c1d62de02a2)
And thats with the auto Theme ^

If thats really not supported currently i am sorry for bothering you, and maybe the option in the settings ist missleading ^^ but just wanted to clarify :) Thanks for your hard work.

**Comment by RayZ3R0** [comment]
Does this still happen on latest version? (a.14 as of this comment)

**Comment by salamijason** [comment]
No response in 2 weeks, will be closing this issue. Please reopen if issue persists.
