### ISSUE TITLE
"New Tab Button", "Ctrl+T", Doesn't work on windows

### ISSUE THREAD

**Issue by BatmiBoom** [zen-browser/desktop#1588]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Since last update there are a number of buttons that doesn't work.

https://github.com/user-attachments/assets/c7555c78-8723-4d3e-9480-cb69a2b55bcd

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

I cannot check the version because I cannot open settings

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
What's the name of your workspaces?

**Comment by onthejobtraining** [comment]
https://github.com/zen-browser/desktop/issues/1553

Also, you can open settings by visiting 'about:preferences'

**Comment by BatmiBoom** [comment]
With 'about:preferences' I can enter settings. Also in private mode, everything works fine!

I don't understand the question about workspaces.

**Comment by mauro-balades** [comment]
Could you open your profile directory and under zen-workspaces, send me the Workspaces.json file?

**Comment by onthejobtraining** [comment]
@BatmiBoom

**Comment by BatmiBoom** [comment]
[Workspaces.json](https://github.com/user-attachments/files/17106741/Workspaces.json)

Its blank!

**Comment by BatmiBoom** [comment]
I solved it, but I don't understand why it was happening. I create a new workspace, set that workspace as default, rename the `default (alpha)` workspace to be main workspace, remake that one the default, and it started to work. The workspace.json keeps beign empty after doing all that

**Comment by RayZ3R0** [comment]
Does this still happen on latest version? (a.14 as of this comment) 

Also, it seems it was fixed? Will be closing this then. Do reopen if this still happens.
