### ISSUE TITLE
Can't split tab, if one of the tabs has been previously split

### ISSUE THREAD

**Issue by pleist** [zen-browser/desktop#1592]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I split 2 tabs, then I create a new tab, close one of the splitted tabs whilst in the new tab, then I go to any website in the new tab, and try to select the current tab and the previous splitted tab and try to split them, it doesn't let me to split them.

Video in discord https://discord.com/channels/1088172780480114748/1094002792735191150/1287151297686016037

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1.-a.2

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
This has been fixed, thanks!
