### ISSUE TITLE
Browser not working on Crunchyroll

### ISSUE THREAD

**Issue by brodriro** [zen-browser/desktop#1596]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![image](https://github.com/user-attachments/assets/b9dab5d9-68dd-446a-aabc-b3a30f08e995)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.2

### What platform are you seeing the problem on?

macOS - Intel

### Relevant log output

```shell
XHRPOST
https://cr-license-proxy.prd.crunchyrollsvc.com/v1/license/widevine
[HTTP/2 403  256ms]

![image](https://github.com/user-attachments/assets/24cf9257-b1fa-4897-bb3e-7daf9a66a045)
```

**Comment by mauro-balades** [comment]
Please check for duplicates before posting https://docs.zen-browser.app/faq#why-cant-zen-browser-play-drm-protected-content
