### ISSUE TITLE
Keyboard Shortcuts - Close Tab or Window with Pre-Defined Shortcut not working on Mac

### ISSUE THREAD

**Issue by bmdev88** [zen-browser/desktop#1599]
### Captchas

- [ ] I have read the instructions.
- [ ] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

Using the File - Close Tab or Close Window Shortcut (CMD+W | Shift CMD+W) does not work on Mac
![CleanShot 2024-09-22 at 09 55 23](https://github.com/user-attachments/assets/fac05a4e-c283-49a8-a371-6acf352c41d4)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.2 (64-bit)

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by mauro-balades** [comment]
This is a known issues that has been duplicated hundred of times. We are working on it
