### ISSUE TITLE
Condensed Vertical Tabs not working in Compact Mode

### ISSUE THREAD

**Issue by webhubquintal** [zen-browser/desktop#160]
### What happened?

![image](https://github.com/user-attachments/assets/71901d6c-1005-433c-ab4e-1117152aefee)

Expanded Vertical Tabs work fine and run smoothly in Compact Mode.

A suggestion, In normal Condensed Tabs, there is no direct way to close a tab, if you could navigate that problem as well, that would be amazing.

Also, great to see that the issue of compact mode hiding top portion of sites has been fixed, great work dev.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a12

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
Fixed for the next release, thanks! 👍🏽
