### ISSUE TITLE
Compact mode window controls

### ISSUE THREAD

**Issue by Derbosik** [zen-browser/desktop#1601]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The window buttons for exiting, minimizing and hiding the app are going a bit out of the screen when in compact mode.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

a2/latest release

### What platform are you seeing the problem on?

Windows

**Comment by jlnalber** [comment]
I have the same issue. Mostly, the close button is halfway outside the window.

**Comment by RayZ3R0** [comment]
Does this still happen on latest version? (a.14 as of this comment)

**Comment by Just-A-Guy-Simp** [comment]
Unfortunately, I'm having this issue as well :( Except it's when I un-compact them. A lot of stuff gets pushed off screen.
I am on the latest version.

https://github.com/user-attachments/assets/1cb53256-eec6-43df-be59-5ad22286ec22

**Comment by RayZ3R0** [comment]
> Unfortunately, I'm having this issue as well :( Except it's when I un-compact them. A lot of stuff gets pushed off screen. I am on the latest version.
> zen_5yxzzNnFDi.mp4

There's been a new update, a.17 please update to that and see if it still happens please
