### ISSUE TITLE
Browser doesn't open links properly

### ISSUE THREAD

**Issue by LovecraftianGodsKiller** [zen-browser/desktop#161]
### What happened?

Whenever I click on a link it either gets downloaded as s file and then views it or it just open the browser and does absolutely nothing.

I don't mind manually copying and pasting links, but there are some links that I can't copy.

Is this a bug or is it intentional?

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.12

### Severity impact

Critical

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
What links where you opening? Where they downloadable files?

**Comment by zabulonian** [comment]
I can echo this bug, and add some more details: 
When Zen browser is set as default browser, clicking on a URL in an external application (in this case, tested with Flatpak versions of Telegram and Vesktop), will launch a new, fresh instance of Zen browser (even if one is already running), on the default start page. This new instance also will not load the clicked URL, it just acts as though you opened the browser and did nothing else. This does not happen when Firefox is the default browser - in that case it functions as expected: the URL is loaded in an existing instance of the browser, OR, if the browser is not running, firefox is launched and the URL is loaded.

**Comment by mauro-balades** [comment]
It's probably an issue with the desktop file 

https://github.com/zen-browser/flatpak/blob/main/io.github.zen_browser.zen.desktop#L10

**Comment by LovecraftianGodsKiller** [comment]
> What links where you opening? Where they downloadable files?

They were just normal links, like links to a github page, a spotify artist's page, etc.

**Comment by mauro-balades** [comment]
It should be fixed with https://github.com/flathub/io.github.zen_browser.zen/pull/3/

note that it takes some hours for flathub to update the packages as they do it in batches

**Comment by LovecraftianGodsKiller** [comment]
I just tested the latest test build linked in the flatpak repo above (ran this command `flatpak install --user https://dl.flathub.org/build-repo/121305/io.github.zen_browser.zen.flatpakref`) and the same think keeps happening.

**Comment by mauro-balades** [comment]
That's a test build, could you please try with the official one?

**Comment by IAmJafeth** [comment]
This happened to me until I updated the desktop file to: 
https://github.com/zen-browser/flatpak/blob/main/io.github.zen_browser.zen.desktop#L10

as Mauro said.

in mi distro this is located at `~/.local/share/applications/zen.desktop`

**Comment by mauro-balades** [comment]
did you turn it to `true`?

**Comment by reinchek** [comment]
[solved] Hi, i had same issue on Fedora 40, and yes: it's a .desktop issue. 
This is the flatpak generated desktop file:
```
[Desktop Entry]
Version=1.0
Type=Application
Name=Zen Browser
Comment=Zen Browser. Your browser, your way.
Categories=Network;WebBrowser;
Icon=io.github.zen_browser.zen
Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=launch-script.sh io.github.zen_browser.zen
Terminal=false
MimeType=x-scheme-handler/http;x-scheme-handler/https;
X-Flatpak=io.github.zen_browser.zen
```

I just resolved putting the "%u" at the end of Exec line. like this:
```
Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=launch-script.sh io.github.zen_browser.zen %u
```

Thanks, i really like Zen Browser (i'm coming from floorp, and I noticed less ram consumption, good job)

**Comment by zabulonian** [comment]
I'd like to confirm what reinchek reported also fixed the issue for me

**Comment by SVTA-OP** [comment]
> [solved] Hi, i had same issue on Fedora 40, and yes: it's a .desktop issue. This is the flatpak generated desktop file:
> 
> ```
> [Desktop Entry]
> Version=1.0
> Type=Application
> Name=Zen Browser
> Comment=Zen Browser. Your browser, your way.
> Categories=Network;WebBrowser;
> Icon=io.github.zen_browser.zen
> Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=launch-script.sh io.github.zen_browser.zen
> Terminal=false
> MimeType=x-scheme-handler/http;x-scheme-handler/https;
> X-Flatpak=io.github.zen_browser.zen
> ```
> 
> I just resolved putting the "%u" at the end of Exec line. like this:
> 
> ```
> Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=launch-script.sh io.github.zen_browser.zen %u
> ```
> 
> Thanks, i really like Zen Browser (i'm coming from floorp, and I noticed less ram consumption, good job)

I'm not able to even start the browser after modifying the .desktop file, the app refuses to start. It only starts if i use the `flatpak run` command.

**Comment by zabulonian** [comment]
There was an update today, after which I also can no longer get it to run.
Having said that, I think it is unrelated to the .desktop file, as the
update reset the change I had made.

**Comment by reinchek** [comment]
[solved] Hi, same for me. After the update to _Mozilla Zen 1.0.0-a.13_ the browser stopped working. 
Now, the problem was that there isn't the `launch-script.sh` file. I modified the .dekstop file, in "Exec=" line, as follow:

```
/usr/bin/flatpak run --branch=stable --arch=x86_64 io.github.zen_browser.zen %u"
```

I'm on Fedora 40.

**Comment by SVTA-OP** [comment]
> [solved] Hi, same for me. After the update to _Mozilla Zen 1.0.0-a.13_ the browser stopped working. Now, the problem was that there isn't the `launch-script.sh` file. I modified the .dekstop file, in "Exec=" line, as follow:
> 
> ```
> Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 io.github.zen_browser.zen %u
> ```
> 
> I'm on Fedora 40.

I found the .desktop file in `/var/lib/flatpak/app/io.github.zen_browser.zen/current/active/files/share/applications` but changing the Exec line did no difference. I then made a copy of the .desktop file and tried to launch it, didn't work.

I'm also on Fedora 40.

**Comment by mauro-balades** [comment]
Can we close this now?

**Comment by a-johanes** [comment]
I am on Ubuntu 22.04. I fixed my issue by upgrading the Flatpak to version >= [1.14.3](https://github.com/flatpak/flatpak/releases/tag/1.14.3). 
```
sudo add-apt-repository ppa:flatpak/stable && sudo apt update && sudo apt install flatpak
 ```
this update my Flatpak to 1.14.10.

My Ubuntu is running on Wayland and I install Zen browser using Flatpak. The application I used is setting the `GDK_BACKEND=x11` env var. This breaks the `gio open` (not sure why) and fail to open the link in the Zen browser.

if you are curious to debug yourself, You can try to run `strace`.
```
strace -f -e execve -s 500 -v -o trace.log your_program
```
read the `trace.log` and try to run the open link part using the same env vars as logged. Hope this helps.

**Comment by Swissbite** [comment]
Thank you, for the hint with %u, @reinchek Had the issue on the portable version on Ubuntu, when adding to the KDE starter.

**Comment by belous-dp** [comment]
I use just the binary file, the same problem appeared first. Fixed by creating proper .desktop file. I placed it in `.local/share/applications/zen.desktop`:
```
#!/usr/bin/env xdg-open
[Desktop Entry]
Terminal=false
Type=Application
Name=Zen Browser
Exec=/home/dpb/Downloads/zen.linux-x86_64/zen/zen %u
Icon=zen.png
MimeType=text/html;text/xml;application/xhtml+xml;x-scheme-handler/http;x-scheme-handler/https;application/x-xpinstall;
StartupWMClass=zen-alpha
```
To make icon works I had to copy `zen.linux-x86_64/zen/zen/browser/chrome/icons/default/default128.png` to `~/.icons/zen.png`

Maybe that will come in handy

**Comment by sleepundefined-dev** [comment]
this happened to me on macOS

**Comment by kuzyatm** [comment]
How to fix this type of error on Windows?

**Comment by alkasadist** [comment]
```
[Desktop Entry]
Version=1.0
Name=Zen Browser
Comment=Browse the World Wide Web
GenericName=Web Browser
Keywords=Internet;WWW;Browser;Web;Explorer
Exec=/home/alkasadist/Programs/zen/zen --new-tab %u
Terminal=false
X-MultipleArgs=false
Type=Application
Icon=/home/alkasadist/Programs/zen/browser/chrome/icons/default/default128.png
Categories=GNOME;GTK;Network;WebBrowser;
StartupNotify=true
StartupWMClass=zen-browser
```

Adding `%u` to `Exec` field still works in Fedora 42.
If your Zen icon has switched to a standard Wayland icon, consider adding
`StartupWMClass=zen-browser` to your .desktop file.
