### ISSUE TITLE
When spaming Ctrl+w, tabs from other workspaces open and close

### ISSUE THREAD

**Issue by jlnalber** [zen-browser/desktop#1614]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I use multiple workspaces. Say, I have the default one and workspace A. When I am in the default workspace, I can use Ctrl+w for closing the current tab. When I do this multiple times, I will end up with no tabs left. Zen then opens a new tab, which is fine. But when I spam Ctrl+W, Zen falsely opens tabs from workspace A, although stating that I'm still in the default workspace. This is surely not intended and really annoying, since I'm closing random tabs.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.2

### What platform are you seeing the problem on?

Windows

**Comment by JSGRD22** [comment]
In the meantime, here's a safer alternative for quickly closing large numbers of tabs: hold Ctrl (select tabs) or Shift (select in between) to select multiple tabs from the tab list, and press Ctrl+W. This will instantly close all the selected tabs.

**Comment by jlnalber** [comment]
I was thinking the same. Because my bug only appears when spamming Ctrl+W, so when there is only a very short period of time between opening and closing. I guess that's a bug wort to look into!

**Comment by RayZ3R0** [comment]
Does this still happen on latest version? (a.14 as of this comment)

**Comment by JSGRD22** [comment]
Fixed on my end.

**Comment by RayZ3R0** [comment]
Alright, will be closing this then. Should be fixed for OP too. Reopen if this still happens please, thank you
