### ISSUE TITLE
Usefull icons hidden/removed from the taskbar

### ISSUE THREAD

**Issue by MannixMD** [zen-browser/desktop#1618]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Why did those icons have been remove/hidden in the version 1.0.1-a.3 ??? Give us ability to show/hide them 

![btns](https://github.com/user-attachments/assets/2f298157-5554-4b65-a392-884f47e556ef)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.3

### What platform are you seeing the problem on?

Windows

**Comment by MannixMD** [comment]
Never mind I'm blind you can use Customize Toolbar to bring them back

**Comment by onthejobtraining** [comment]
> Never mind I'm blind you can use Customize Toolbar to bring them back

Don't forget to close your issues it's it's not an issue.  The option is at the bottom.
