### ISSUE TITLE
App menu button

### ISSUE THREAD

**Issue by quxer** [zen-browser/desktop#1619]
### Captchas

- [ ] I have read the instructions.
- [ ] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

After update button was moved to the left side and it is impossible to move it back to the right side of the top bar. Every other button is moveable, but this one isn't. If this change is made for mac users, then let windows users move it back, next to minimize button.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.3

### What platform are you seeing the problem on?

Windows

**Comment by sjclayton** [comment]
Same here on 1.0.1-a.3 in Linux.

This needs to be able to be re-positioned... seems very out of place, also the left padding of the button doesn't even line up with the left padding of the tabs in the sidebar when the bar is collapsed, very poor UI design, and seems like these UI decisions are all catered towards users that either use compact mode or an expanded sidebar.

**Comment by chriskirknielsen** [comment]
Same on MacOS with 1.0.1-a.3 FWIW:
<img width="240" alt="MacOS top-left window controls with the Zen settings menu stuck against them." src="https://github.com/user-attachments/assets/704107f7-38dd-4d67-bcf7-4ebcf070b350">

**Comment by DZL1943** [comment]
+1

**Comment by DZL1943** [comment]
1.0.1-a.4 fixed

**Comment by quxer** [comment]
This is changed in version 1.0.1-a.4, now button is moveable to other sections.

**Comment by quxer** [comment]
Changed position isn't saved after restart of the browser.

**Comment by sjclayton** [comment]
> Changed position isn't saved after restart of the browser.

@quxer 

Position changes save just fine for me in Linux, maybe there is something different with how the position gets saved for Windows.

**Comment by mauro-balades** [comment]
It is now on the right side, thanks!
