### ISSUE TITLE
Feature Request: Built-in adblocker

### ISSUE THREAD

**Issue by GuiMar10** [zen-browser/desktop#162]
### What feature would you like to see?

title

### What platform are you seeing the problem on?

Windows

**Comment by Donnnno** [comment]
Shipping it with uBlock Origin wouldn't be a bad idea :)

**Comment by mayemu** [comment]
he said hes working on a built in one based on ghostery in a reddit comment sometime earlier

**Comment by cyrneko** [comment]
I think uBlock Origin would be optimal.

Highly supported, most efficient on Firefox, popular and customizable. There's a reason it's the first choice in LibreWolf and alike.

**Comment by mayemu** [comment]
yea, mullvad does as well. i definitely agree. ublock is miles ahead of ghostery in its content blocking abilities and really is an undisputed requirement to browse the web safe and privately. even brave users will disable brave shield for it, so i think developing a ghostery based adblock would be efforts better towards other features

**Comment by cyrneko** [comment]
I believe Arc also bundles uBlock Origin, so that's another browser to add to the list of references.

**Comment by mayemu** [comment]
ghostery is also redundant with [firefox's total cookie protection](https://blog.mozilla.org/security/2021/02/23/total-cookie-protection/). 

arkenfox has a full guide to necessary and redundant extensions here: https://github.com/arkenfox/user.js/wiki/4.1-Extensions#-dont-bother and they are kind of the utmost authority on firefox browser security. ghostery is also listed under redundant extensions as is most "privacy" extensions because ublock literally does everything they all do but miles better. bundling with ublock and maybe skip redirect would be best for user experience imo!

**Comment by mauro-balades** [comment]
Does Arc bundle uBlock?

**Comment by GuiMar10** [comment]
Ye

**Comment by mauro-balades** [comment]
Doesn't it have to comply with Manifest Version 3?

**Comment by GuiMar10** [comment]
Not for now, but they're working on a native alternative for uBlock

**Comment by Magnusretrotech** [comment]
Just use ublock or adguard, why does there have to be an intergrated version?

**Comment by freebritney132** [comment]
There's no reason to make a native ad blocker since ublock origin is blazing based, and if another adblocker is chosen I will dox all the developers and harass them for the next 25 years as a prank.

**Comment by cyrneko** [comment]
> There's no reason to make a native ad blocker since ublock origin is blazing based, and if another adblocker is chosen I will dox all the developers and harass them for the next 25 years as a prank.

that's the most compressed cringe I've ever read on GitHub

**Comment by mauro-balades** [comment]
> There's no reason to make a native ad blocker since ublock origin is blazing based, and if another adblocker is chosen I will dox all the developers and harass them for the next 25 years as a prank.

I've decided to go for Firefox's built in adblocker 😬

**Comment by cyrneko** [comment]
Firefox's built-in one?

Are you simply extending the tracker protection with new lists that also block ads? :thinking:

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/888

 ~ This is an automatic operation to better enhancements requests organization.
