### ISSUE TITLE
400 bad request at sites after version 1.0.1-a.2

### ISSUE THREAD

**Issue by Vyslik** [zen-browser/desktop#1620]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I downloaded the update, wanted to sign in to something for school and I have passwords on Proton pass. The proton pass was signed out with some error message. When I clicked "Sign in" it showed "error 400 bad request". Tried on firefox it works fine, tried other browsers like opera GX, worked too so it must be something with the Zen background things.
![Snímek obrazovky 2024-09-23 125257](https://github.com/user-attachments/assets/88476d2a-95c6-416e-b135-b6c9cb77c395)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.3

### What platform are you seeing the problem on?

Windows

**Comment by onthejobtraining** [comment]
has this been fixed?

**Comment by Vyslik** [comment]
> has this been fixed?

No, even after the new update. Some don't have problem like me, but on discord there was a guy with the same problem like me.

**Comment by onthejobtraining** [comment]
> [ZEN-1662 400 bad request at sites after version 1.0.1-a.2](https://linear.app/zen-browser/issue/ZEN-1662/400-bad-request-at-sites-after-version-101-a2)

try creating a new profile by going to `about:profiles` and see if the exists there as well.

**Comment by Vyslik** [comment]
> > [ZEN-1662 400 bad request at sites after version 1.0.1-a.2](https://linear.app/zen-browser/issue/ZEN-1662/400-bad-request-at-sites-after-version-101-a2)
> 
> try creating a new profile by going to `about:profiles` and see if the exists there as well.

WTH, this works fine, but can I make somehow the 1:1 my profile, I don't want to lost all my stuff.

**Comment by onthejobtraining** [comment]
> > > [ZEN-1662 400 bad request at sites after version 1.0.1-a.2](https://linear.app/zen-browser/issue/ZEN-1662/400-bad-request-at-sites-after-version-101-a2)
> > 
> > 
> > try creating a new profile by going to `about:profiles` and see if the exists there as well.
> 
> WTH, this works fine, but can I make somehow the 1:1 my profile, I don't want to lost all my stuff.

Yeah, you can simply copy and paste the contents of the main profile folder but that can possibly also copy the same issue to the new profile. I think this could be a network/dns/ad block issue, try to find out what exactly is causing the issue, has to be some setting here or there.

**Comment by Vyslik** [comment]
> > > > [ZEN-1662 400 bad request at sites after version 1.0.1-a.2](https://linear.app/zen-browser/issue/ZEN-1662/400-bad-request-at-sites-after-version-101-a2)
> > > 
> > > 
> > > try creating a new profile by going to `about:profiles` and see if the exists there as well.
> > 
> > 
> > WTH, this works fine, but can I make somehow the 1:1 my profile, I don't want to lost all my stuff.
> 
> Yeah, you can simply copy and paste the contents of the main profile folder but that can possibly also copy the same issue to the new profile. I think this could be a network/dns/ad block issue, try to find out what exactly is causing the issue, has to be some setting here or there.

I did this thing, copied the main things like history, passwords etc. and it did the same issue. I created new account that is synced with mozzila account so it's almost everything I need except history. I have also synced the extensions so I have all extensions like before, but now it's just okay and everything work like it used to, so I think the extensions are not the problems.

**Comment by onthejobtraining** [comment]
History should also be synced automatically actually, that's weird.

**Comment by Vyslik** [comment]
Tbh it's the smallest thing imo

**Comment by Vyslik** [comment]
I did this thing, copied the main things like history, passwords etc. and it did the same issue. I created new account that is synced with mozzila account so it's almost everything I need except history. I have also synced the extensions so I have all extensions like before, but now it's just okay and everything work like it used to, so I think the extensions are not the problems.

**Comment by Vyslik** [comment]
Fixed!! Found out that it has to do something with my profile folder, maybe some update corrupted something in my profile folder so I just had to make new profile. So I'm closing this issue, thanks.
