### ISSUE TITLE
Tabs padding is not correct

### ISSUE THREAD

**Issue by nazmiyigitefe** [zen-browser/desktop#1621]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

In tabs section, left and top padding is not seems like correct
<img width="222" alt="Ekran Resmi 2024-09-23 13 57 57" src="https://github.com/user-attachments/assets/2b8d7424-93b2-468f-b00c-7c5454461aa3">

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a3

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by nazmiyigitefe** [comment]
Also, the search bars padding and pinned extensions are not ok as well
<img width="1115" alt="Ekran Resmi 2024-09-23 14 02 10" src="https://github.com/user-attachments/assets/351444f1-6429-4884-a05a-1a6ab452374f">

**Comment by 51ddh4r7h-A** [comment]
yeah this update is kinda messed up
Also why did they remove the "New Tab" or "+" button??

**Comment by nazmiyigitefe** [comment]
You may edit it with right clicking the tabs section and with customize toolbar button

**Comment by 51ddh4r7h-A** [comment]
I didn't know we can do that, nice got it 👍

**Comment by micheal-earl** [comment]
I have this same problem. The left padding of the compact mode sidebar seems to have vanished.
![image](https://github.com/user-attachments/assets/0a490383-a2b3-41b8-a4a5-d13772f4b8c4)

**Comment by 51ddh4r7h-A** [comment]
yeah same here
![image](https://github.com/user-attachments/assets/473a29fd-f0cd-4712-bc80-598c8898c79b)

**Comment by nazmiyigitefe** [comment]
Still persists in 1.0.1-a.5
![Ekran görüntüsü 2024-09-25 133911](https://github.com/user-attachments/assets/da9130c4-228a-42db-b340-d6116640a73b)

**Comment by 51ddh4r7h-A** [comment]
Yeah its just a huge turnoff, so until this gets resolved i'm using brave as my primary zen will be secondary

**Comment by RayZ3R0** [comment]
Does this still happen on latest version? (a.14 as of this comment)

**Comment by salamijason** [comment]
No response in 2 weeks, will be closing this issue. Please reopen if issue persists.
