### ISSUE TITLE
cmd + L does not work anymore after update

### ISSUE THREAD

**Issue by vine-mxm** [zen-browser/desktop#1622]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Hi,
i've just updated Zen Browser, but now the keyboard shortcut CMD+L does not work anymore. 

the shortcut is not mapped to anything else and it's not captured by other programs (on safari, arc and firefox works fine). 
this happens to me on two different Macs on both M architecture and Intel (one is brand new) so i don't think it's something on my side. 

Is this a known issue? or is there anywhere where i can set the shortcut myself? in the shortcut menu i cannot find the corresponding actions. 

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.3

### What platform are you seeing the problem on?

macOS - aarch64, macOS - Intel

**Comment by xriu** [comment]
cmd + actions are not working properly since update.

**Comment by nazmiyigitefe** [comment]
Yes that's right, but if you set them again from about:preferences#zenCKS they will work again.

**Comment by vine-mxm** [comment]
just found out that is working with ctrl+L, i'll use this until a fix is released

**Comment by maxsteenbergen** [comment]
Looks like most if not all keyboard shortcuts got cleared.

@nazmiyigitefe Which entry would map to the Cmd+L action? From the descriptions, I wouldn't be able to guess.

**Comment by nazmiyigitefe** [comment]
It should be "Search the Web"

**Comment by maxsteenbergen** [comment]
I had that one, but that's not an immediate replacement though. Cmd+L only focused the address bar, "Search The Web" presets it to your search engine

**Comment by bangoim** [comment]
Not working here as well.

**Comment by mauro-balades** [comment]
This should be fixed, thanks!

**Comment by vine-mxm** [comment]
can confirm it's fixed! thanks
