### ISSUE TITLE
Window Closing, Fullscreen, and Minimize buttons are no longer adapted

### ISSUE THREAD

**Issue by Mathc0** [zen-browser/desktop#1623]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Since the new update on Windows, the buttons in the upper right-hand corner are no longer sized correctly. Before the update, they were square, like in the standard Firefox interface, but now they're classic rectangles, similar to those in Windows 7 or 8.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.3 (64 bits)

### What platform are you seeing the problem on?

Windows

**Comment by RayZ3R0** [comment]
Should be fixed in the newer updates, will be closing this. Please reopen if this still persists.
