### ISSUE TITLE
Bookmarks and addons not showing

### ISSUE THREAD

**Issue by TakenMC** [zen-browser/desktop#1626]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I recently tried to enable full compact mode since before i only hid tabs but when I enabled it it broke my bookmark bar and pinned addons

![image](https://github.com/user-attachments/assets/f4060737-d80a-456f-ae14-82ccd16a6738)

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.3

### What platform are you seeing the problem on?

Windows

**Comment by flick9000** [comment]
Me too!

**Comment by KyleDL101** [comment]
+1

**Comment by sek0n** [comment]
Still getting this after the new update as well. Also cant right click on an empty part of the tab bar and reopen closed tab anymore.

![image](https://github.com/user-attachments/assets/15ff9790-3698-49c5-981d-1a810205c44f)
![image](https://github.com/user-attachments/assets/8a080845-469b-446a-a4f8-b103d408de68)

**Comment by johnrmeyer** [comment]
Also having the same issue.

**Comment by LazerCuber** [comment]
+1

**Comment by Aosneg** [comment]
Had the similar problem today. I accidentally checked "never show" on bookmark toolbar and then I couldn't restore it. But I went to about:config and found `browser.toolbars.bookmarks.visibility` which was set to `never`. I set it to `always`, relaunched my browser and it works just fine.

**Comment by LazerCuber** [comment]
> Had the similar problem today. I accidentally checked "never show" on bookmark toolbar and then I couldn't restore it. But I went to about:config and found `browser.toolbars.bookmarks.visibility` which was set to `never`. I set it to `always`, relaunched my browser and it works just fine.

Tried but failed, the icons are not showing

**Comment by onthejobtraining** [comment]
Have you tried disabling your zen mods and check?

**Comment by CrimsonProtogen** [comment]
It's been happening to me too, and I have also tried with no mods enabled.

One thing I did notice, is that if you go to the Toolbar editor, hit default and then undo, the pinned addons will come back (but not the addons icon, only the pinned ones), but only for that one session the browser is open. Once you close it and reopen it, the pinned addons are gone again

**Comment by DrHibbertMD** [comment]
didn't have any issue with the extensions button in the previous update, but this one got rid of it as well as the ability to install new ones, the fix for me though was finding "browser.uiCustomization.state" in about:config, then moving "unified-extensions-button" to just after "downloads-button"

**Comment by CrimsonProtogen** [comment]
I just tried that (it took a while I apologize) but that didn't work. But it seemed as though there was another update and that seems to have fixed it for now.

**Comment by RayZ3R0** [comment]
Its fixed right? Will be closing this then. Please reopen if it still happens.
