### ISSUE TITLE
Default Container Tabs per Workspace

### ISSUE THREAD

**Issue by xGihyun** [zen-browser/desktop#163]
### What feature would you like to see?

Set a default container tab on each workspace. For example, opening a new tab on the "Personal" workspace will have the "Personal" container tab by default.

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
ohhh nice, ill look into it!

**Comment by talon-likeaclaw** [comment]
I'm gonna piggyback on this enhancement since it's somewhat related, would it be possible to also add keyboard shortcuts to open a new tab as a specific container type?

**Comment by xGihyun** [comment]
@talon-likeaclaw For this case, I personally use [Multi-account Containers](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search), then you can do `Ctrl` + `Shift` + `1` (or any other number based on your keybinds on the addon preferences) and it would open that specific container. It's the best workaround I've found so far, the only downside I could think of is that you need to remember which shortcut is for which container, which isn't that bad, but having this issue resolved would reduce that cognitive load since the containers would be automatically assigned per workspace while also having shortcuts from Multi-account Containers to open a different container if you need to.

**Comment by talon-likeaclaw** [comment]
@xGihyun Wow awesome, that is exactly what I was looking for! Thanks a ton!

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/887

 ~ This is an automatic operation to better enhancements requests organization.
