### ISSUE TITLE
Browser layout bug

### ISSUE THREAD

**Issue by Nufzy** [zen-browser/desktop#1633]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

For some reason layout is off. I installed the same profile to the second windows system I have. Somehow nighttab removed itself and after I installed it back and restarted the browser a couple of times this happened. It just launched like that and not fixing itself even though I reinstalled it and made sure the profiles are deleted on the fresh install.

![Screenshot 2024-09-23 141719](https://github.com/user-attachments/assets/97407d0a-c6b2-4ca8-99b1-091e6dd7103d)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.3

### What platform are you seeing the problem on?

Windows

**Comment by onthejobtraining** [comment]
Could you point out what exactly is the issue here?

**Comment by Nufzy** [comment]
When I installed the browser first time, layout of the buttons on the borders was different. Why my workspace button is on the bottom and new tab button even lower? Profile button is also not in the right place, 3 dot menu was on the right corner, now it is on the left corner.

**Comment by onthejobtraining** [comment]
> When I installed the browser first time, layout of the buttons on the borders was different. Why my workspace button is on the bottom and new tab button even lower? Profile button is also not in the right place, 3 dot menu was on the right corner, now it is on the left corner.

This is a design choice on the new update. You can change a few things by right clicking on the toolbar and selecting customise toolbar at the bottom.
![image](https://github.com/user-attachments/assets/d47b9a22-bd8e-4b89-95a3-3ac0ccb79d8f)

You can close the issue as it's not a bug.

**Comment by Nufzy** [comment]
Uh, I see. I thought this way because it seems completely unintuitive for me, I'm not sure if I will get use to it. Thank you anyway!

**Comment by onthejobtraining** [comment]
> Uh, I see. I thought this way because it seems completely unintuitive for me, I'm not sure if I will get use to it. Thank you anyway!

Yeah, there was a new update today and you'll be able to change the position of the 3dot button as well, try **customize toolba**r like I showed above.

**Comment by Nufzy** [comment]
I'm sorry to bother you again, but how can I return the addons button?

![image](https://github.com/user-attachments/assets/12d27573-f1d7-4538-bbb6-2f6ed9d1865c)

**Comment by onthejobtraining** [comment]
That is very weird because I am unable to reproduce this bug on my windows

https://github.com/zen-browser/desktop/issues/1643 apparently creating a new profile by going to `about:profiles` fixed the issue for someone, maybe try that.

**Comment by onthejobtraining** [comment]
Also, have you tried disabling zen mods or other css that you may have applied to the browser?

**Comment by Nufzy** [comment]
I'm sorry, apperantely it was extensions. I tried to turn them on and off and it wasn't working. For some reason it worked right now. I created new profile and it was "private mode highlighting" which made it hidden. Now it is "hide plugins". I'm really sorry to bother you for this stupid reason. I'll do my best to solve it again next time. Thank you!

**Comment by onthejobtraining** [comment]
Thanks for finding out the culprit mods 😆
