### ISSUE TITLE
Sidebar icons and workspaces aren't showing properly

### ISSUE THREAD

**Issue by nashinwalker** [zen-browser/desktop#1634]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Sidebar icons and workspaces aren't showing properly. They are overlaying.
![image](https://github.com/user-attachments/assets/90847732-b259-44a1-bdda-c398d65858d0)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.3

### What platform are you seeing the problem on?

Windows

**Comment by sjclayton** [comment]
@nashinwalker 

Are you using the mod - Uniform Workspace Button...? If so it may be the issue, try turning it off.

**Comment by MisterHighping** [comment]
Same for me. Removing Uniform Workspace Button and restarting helped!

**Comment by nashinwalker** [comment]
> @nashinwalker
> 
> Are you using the mod - Uniform Workspace Button...? If so it may be the issue, try turning it off.

Thanks
