### ISSUE TITLE
Empty "new tab" incorrectly created when closing existing tab

### ISSUE THREAD

**Issue by neogeographica** [zen-browser/desktop#1635]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Only reproducible on Linux apparently:

0) Workspaces feature must be enabled in preferences.
1) Right-click on any link or bookmark and open its page (let's call it foo.com) in a new window.
2) A new window is created with one tab, showing foo.com.
3) In that foo.com tab, middle click on one or more links in the displayed page to open those links as tabs "in the background".
4) Remain on the foo.com tab... don't switch to any of the other tabs yet.
5) In the tab sidebar click the "x" on the foo.com tab to close it.
6) A new empty "New Tab" tab will be created at the bottom of the tab list.

What I would expect is for that new tab to NOT be created.

I hit this with some regularity since this is a not-uncommon browsing pattern for me: open some homepage or other kind of "top-level page" in a new window, while reading it middle-click on various links that I want to check out when I am done with the top-level page, then close the top-level page.

Note: The new tab is **not** created when I close the foo.com tab, if one of the following is true:
* If in step 0, the workspaces feature is disabled.
* Or if on step 4 I instead look at (activate / switch-to) at least one of the other opened tabs before closing the foo.com tab.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a

### What platform are you seeing the problem on?

Linux

**Comment by neogeographica** [comment]
Also FWIW, I have two workspaces configured. I haven't tried replicating this behavior when only having a single workspace.

**Comment by onthejobtraining** [comment]
Unable to replicate this on Windows version either.

**Comment by neogeographica** [comment]
Tested it with a single workspace now, same behavior (on Linux).

**Comment by salamijason** [comment]
Could not replicate on latest version (1.0.1-a.16 as of this comment), are you still getting this issue?

**Comment by stilic** [comment]
Could replicate this issue with a single workspace in a single Zen window.

**Comment by salamijason** [comment]
Really bizarre, could you send a screen recording so we can verify what exactly is happening?

**Comment by stilic** [comment]
> Really bizarre, could you send a screen recording so we can verify what exactly is happening?

I close the only tab I have and it's opening a new tab instead of closing the window itself.
It only happens when the workspaces feature is enabled.

**Comment by salamijason** [comment]
Tried to replicate on windows again with and without workspaces enabled and still couldn't get it. Will verify if this is only a Linux bug.

**Comment by salamijason** [comment]
A recording would really help bro

**Comment by stilic** [comment]
> A recording would really help bro

I described the behavior already.
It also happens when closing the only tab with Ctrl-W.

**Comment by salamijason** [comment]
Yes, I understand you've described the behavior already but a video will be miles better. 

To verify whether this is an issue, we'd have to be able to recreate and diagnose the bug.

**Comment by stilic** [comment]
> Yes, I understand you've described the behavior already but a video will be miles better.
> 
> To verify whether this is an issue, we'd have to be able to recreate and diagnose the bug.

I explained how to reproduce the issue.
Do you really want me to record a video? Did you tried what I described?

**Comment by onthejobtraining** [comment]
>  I explained how to reproduce the issue. Do you really want me to record a video? Did you tried what I described?

Yes, they really want you to record a video. It shouldn't be much difficult. @salamijason asked for a screen recording of the bug from you, not a bathroom selfie. You could have saved a lot of your time and theirs by simply sharing a screen recording instead of repeating the same thing under every post.

**Comment by salamijason** [comment]
> Tried to replicate on windows again with and without workspaces enabled and still couldn't get it. Will verify if this is only a Linux bug.

@Stilic As seen from my previous responses, I have already tried to replicate it multiple times but was unable to. Thus why I asked for a recording. 

We needa figure out if it's a os specific bug, profile bug, or even a bug at all and a recording would be the best and most straight forward way to convey the issue you're facing.

**Comment by stilic** [comment]
https://github.com/user-attachments/assets/b2f6bba0-dcf4-42ed-94f6-26a27fb5ef71

**Comment by salamijason** [comment]
@Stilic The behavior in the video is intentional. There needs to be at least one tab in a workspace.

But, the video you sent does not seem to match up with your initial step-by-step recollection of the bug.

> Workspaces feature must be enabled in preferences.
    Right-click on any link or bookmark and open its page (let's call it foo.com) in a new window.
    A new window is created with one tab, showing foo.com.
    In that foo.com tab, middle click on one or more links in the displayed page to open those links as tabs "in the background".
    Remain on the foo.com tab... don't switch to any of the other tabs yet.
    In the tab sidebar click the "x" on the foo.com tab to close it.
    A new empty "New Tab" tab will be created at the bottom of the tab list.


Could you please verify which is the bug you're talking about?

**Comment by stilic** [comment]
> @Stilic The behavior in the video is intentional. There needs to be at least one tab in a workspace.
> 
> But, the video you sent does not seem to match up with your initial step-by-step recollection of the bug.
> 
> > Workspaces feature must be enabled in preferences.
> > Right-click on any link or bookmark and open its page (let's call it foo.com) in a new window.
> > A new window is created with one tab, showing foo.com.
> > In that foo.com tab, middle click on one or more links in the displayed page to open those links as tabs "in the background".
> > Remain on the foo.com tab... don't switch to any of the other tabs yet.
> > In the tab sidebar click the "x" on the foo.com tab to close it.
> > A new empty "New Tab" tab will be created at the bottom of the tab list.
> 
> Could you please verify which is the bug you're talking about?

It's not the same bug.
And shouldn't it close the browser anyway if you close every tab in the default workspace?

**Comment by salamijason** [comment]
1) are you still getting the bug you mentioned in your original post?

2) Nope, dev said intentional behavior is to not close the window.

**Comment by salamijason** [comment]
you can also check these
![image](https://github.com/user-attachments/assets/7e5ceaea-a6e4-40cf-b4c5-305451a1a3b3)
![image](https://github.com/user-attachments/assets/3ab40ded-31d0-4443-aa90-048a2091e5cf)

**Comment by stilic** [comment]
> 1. are you still getting the bug you mentioned in your original post?
> 
>     2. Nope, dev said intentional behavior is to not close the window.

No. It was a misunderstanding from me actually.
I didn't encounter that bug.

**Comment by stilic** [comment]
> you can also check these ![image](https://private-user-images.githubusercontent.com/90419732/384694232-7e5ceaea-a6e4-40cf-b4c5-305451a1a3b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyNDkxMTksIm5iZiI6MTczMTI0ODgxOSwicGF0aCI6Ii85MDQxOTczMi8zODQ2OTQyMzItN2U1Y2VhZWEtYTZlNC00MGNmLWI0YzUtMzA1NDUxYTFhM2IzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEwVDE0MjY1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmMDU3MGY1NzIzZTRmYzc3NzRhMGY0ZmIxMzFkMGYyYWM3MjYwZTEyYzc1ZDJjNDVkZmRjZjQyOWUwZjE0MjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NY2VokLkjRvH8YIXQ4c7cTdbfVXcDsegzMCEPE2QEP0) ![image](https://private-user-images.githubusercontent.com/90419732/384694257-3ab40ded-31d0-4443-aa90-048a2091e5cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyNDkxMTksIm5iZiI6MTczMTI0ODgxOSwicGF0aCI6Ii85MDQxOTczMi8zODQ2OTQyNTctM2FiNDBkZWQtMzFkMC00NDQzLWFhOTAtMDQ4YTIwOTFlNWNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEwVDE0MjY1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxNGQyMTQ4Y2FmOGNjZGJhN2Y0ZTQ0ZTBjMjkwYTE4NTA0YjQ5OTk5YjdiZjAzNzQ1ZDM1YmZiZGYwYzY0MmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IcjbLlfIy5YgqQOoCL4qqkEhObxnsyhpeaP8Ztr9MnI)

Thanks for the tip!
