### ISSUE TITLE
Pin tabs by drag & drop doesn't work

### ISSUE THREAD

**Issue by nashinwalker** [zen-browser/desktop#1639]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

You can drag a tab and drop it in the pinned tabs section in Arc. However, this doesn't work in the Zen browser.
![image](https://github.com/user-attachments/assets/a8a03738-cf06-41e3-9304-6e16587854dd)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.3

### What platform are you seeing the problem on?

Windows

**Comment by BrhmDev** [comment]
This should be a feature request, you can make one in https://github.com/zen-browser/desktop/discussions
