### ISSUE TITLE
Can't customize toolbar

### ISSUE THREAD

**Issue by jimfr** [zen-browser/desktop#164]
### What happened?

I can't seem to customize the toolbars any more. I get the screen that I've attached. 
![image](https://github.com/user-attachments/assets/c754f163-7d17-4de9-a0ea-81997f4d7e2a)

Also, fyi, I tried installing a.13, but it looks like a.12 (and "About Zen" still says a.12)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.12

### Severity impact

High

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by jimfr** [comment]
Medium severity, but I can't seem to change the label.

**Comment by jimfr** [comment]
Fixed in a.13 - thank you so much!

**Comment by mauro-balades** [comment]
No problem! Please use low priority next time, high severity is for when zen can't even be launched

**Comment by jimfr** [comment]
Yes, will do.  I tried to change it to low or medium, but couldn't figure
out how.
