### ISSUE TITLE
No new tab button 

### ISSUE THREAD

**Issue by coderstarrer** [zen-browser/desktop#1640]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![Screenshot 2024-09-23 182610](https://github.com/user-attachments/assets/ef241bb9-d362-44d8-b540-fa7e5801bed3)

there is no new tab button

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.3(64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by somefosterkid** [comment]
No sure what happened, but I noticed this today as well. In the mean time, I was able to get the new tab button back by moving it in the customize toolbar page. It was at the bottom of the side bar in there, but wasn't visible in the regular ui

**Comment by coderstarrer** [comment]
Yeah,the bug is quite weird

**Comment by sjclayton** [comment]
Affected on 1.0.1-a.3 in Linux as well.

**Comment by Megafrox** [comment]
> No sure what happened, but I noticed this today as well. In the mean time, I was able to get the new tab button back by moving it in the customize toolbar page. It was at the bottom of the side bar in there, but wasn't visible in the regular ui

Can confirm that this works, although it shouldn't be hidden by default.

**Comment by Stilic** [comment]
Has this issue on Arch Linux.

**Comment by Stilic** [comment]
Has this issue on Arch Linux on the same version.

**Comment by mauro-balades** [comment]
I've fixed it, releasing today. Thanks!
