### ISSUE TITLE
Hide tab bar and hide top bar use the wrong icons in the settings menu

### ISSUE THREAD

**Issue by BredMan0** [zen-browser/desktop#1642]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Hide tab bar and hide top bar use the wrong icons in the settings menu.
![zen_ZstDndxqwf](https://github.com/user-attachments/assets/063950a0-4d0e-4a7c-96fd-0177a39c643a)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.3

### What platform are you seeing the problem on?

Windows

**Comment by JSGRD22** [comment]
I think the intended depiction is how the browser will look in compact view. It can be a little confusing though

**Comment by BredMan0** [comment]
That makes sense.
