### ISSUE TITLE
Extension logo disappered

### ISSUE THREAD

**Issue by ADIOR-enigma** [zen-browser/desktop#1643]
### Captchas

- [x] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

after the update the extension logo has disappeared

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

current

### What platform are you seeing the problem on?

Windows

**Comment by fmitesh007** [comment]
after udate im facing lot of bugs this is one of them also im not able to add new extensions/plugins from firefox store 
also the new tab buttun isnt aligned well i cant drag that buttun where it supposed to be its in the bottom or in the Top bar cant add it in side bar where the tabs are shown

**Comment by onthejobtraining** [comment]
@ADIOR-enigma Unable to reproduce the issue on my windows. Maybe some extension or zen mod is clashing on your browser. Have you tried creating a fresh profile and see if the issue happens there as well?

**Comment by fco-pires** [comment]
While I noticed other bugs in version 1.0.1-a.3 on macOS, this was not one of them. But oddly enough, in version 1.0.1-a.4 this bug appeared (contradicting the release notes). I have no active zen mods.

**Comment by EmanuelBonilla** [comment]
current release on linux i can't see the extensions buttons. 
1.0.1-a.4

**Comment by ADIOR-enigma** [comment]
> While I noticed other bugs in version 1.0.1-a.3 on macOS, this was not one of them. But oddly enough, in version 1.0.1-a.4 this bug appeared (contradicting the release notes). I have no active zen mods.
> 
> Edit: Creating a clean profile solved the problem for me.

Do you mean fresh reinstall

**Comment by fco-pires** [comment]
> > While I noticed other bugs in version 1.0.1-a.3 on macOS, this was not one of them. But oddly enough, in version 1.0.1-a.4 this bug appeared (contradicting the release notes). I have no active zen mods.
> > Edit: Creating a clean profile solved the problem for me.
> 
> Do you mean fresh reinstall

No. You can create a new profile through the account button on the top toolbar. In the menu that appears, you can create a new profile using the + button, or you can click the gear button to manage profiles (create, rename, delete, etc.).

**Comment by fleuquer** [comment]
I'm using Fedora and I have the latest version 1.0.1-a.4. But the extension buttons don't appear, and there are also empty spaces that I can't remove where the buttons used to be.

**Comment by ADIOR-enigma** [comment]
> I'm using Fedora and I have the latest version 1.0.1-a.4. But the extension buttons don't appear, and there are also empty spaces that I can't remove where the buttons used to be.

Creating a clean profile solved the problem for me.
