### ISSUE TITLE
Workspace indicator shows when sidebar collapsed with icon strip disabled

### ISSUE THREAD

**Issue by sjclayton** [zen-browser/desktop#1645]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

There is a weird highlight, that may have something to do with the active workspace indicator showing when the icon strip option is disabled in settings and the sidebar is collapsed, see below.

![2024-09-23_13-08](https://github.com/user-attachments/assets/2c55aab3-39e3-48f2-a1e8-ed026462d1bd)

This is not necessary to show, as there could only ever be one workspace active.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.3

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
This has been done on purpose, thanks!

**Comment by sjclayton** [comment]
> This has been done on purpose, thanks!

Why? What is the purpose of having that indicator displayed?
