### ISSUE TITLE
Side Tab Bars incosistent bug

### ISSUE THREAD

**Issue by rudy0Z** [zen-browser/desktop#1646]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![Screenshot 2024-09-23 225113](https://github.com/user-attachments/assets/bc8c6392-7996-477c-9a63-c14f3552ff02)

So I think the browser updated itself automatically and now the side bar is no more with the sliding out and pushing away the websites and making inconsistent layout

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.3

### What platform are you seeing the problem on?

Windows

**Comment by onthejobtraining** [comment]
Can't reproduce the issue on my end. Have you tried disabling your zen mods? Looks like some settings/changes on your end are interfering with the browser here.

**Comment by onthejobtraining** [comment]
@rudy0Z

**Comment by rudy0Z** [comment]
> Can't reproduce the issue on my end. Have you tried disabling your zen mods? Looks like some settings/changes on your end are interfering with the browser here.

yes I've disabled all zen mods for the time being and it's very random to reproduce. Doesn't get stuck everytime but the side tab bar do push the website for a brief moment and then returns normal. 
didnt use to happen before yesterday

**Comment by mr-cheffy** [comment]
This shoud've had been fixed, thanks!
