### ISSUE TITLE
Crash on start ( 0xc0000142 )

### ISSUE THREAD

**Issue by llebedev** [zen-browser/desktop#1655]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When running the EXE in both the portable version and the installer, I get the error 0xc0000142
![2024-09-24 003542](https://github.com/user-attachments/assets/a0771412-3be3-4304-8fea-ab2e35aade16)

CPU : Intel core i7 3610QE

GPU: Intel HD Graphics 4000

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.3

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
Please download the generic version, your cpu is not supported. Thanks!
