### ISSUE TITLE
Emoji icon missing in workspace

### ISSUE THREAD

**Issue by azzamsa** [zen-browser/desktop#1656]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The name of the emoji I put in the workspace is missing.

![image](https://github.com/user-attachments/assets/a6181e72-faba-40b5-a46e-709311df8b4f)

![image](https://github.com/user-attachments/assets/f54b459a-d9a8-4960-953e-ce4ec5e1e28b)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.3

### What platform are you seeing the problem on?

Linux

**Comment by n7itro** [comment]
Fixed with `1.0.1-a.6`
