### ISSUE TITLE
Facebook and Instagram Reels don't play properly

### ISSUE THREAD

**Issue by zabulonian** [zen-browser/desktop#166]
### What happened?

Most reels will glitch, with playback being choppy and repeating sections over and over. 
Using the flatpak, version 1.0.0-a.11. I am aware the flatpak has newer versions, but ``flatpak update`` is not currently serving them to me.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.11

### Severity impact

Medium

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
This should be fixed for the next release
