### ISSUE TITLE
Side Panels Don't Always Grab Correct Website Icon

### ISSUE THREAD

**Issue by Nitrousoxide** [zen-browser/desktop#1660]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I have created a couple of side-panel pages for https://mail.google.com/chat/u/0/#chat/home 

and an internal self-hosted webpage where all my services are located, which is not accessible to the internet at large.

Google Chat's side panel grabs gmail's icon rather than the google chat icon that displayed when the page is fully loaded.  Likewise, Zen/Firefox can correctly load my self-hosted website and correctly grabs the website icon (a frosted donut) but has an empty icon in the side panel.

I don't know if they are grabbing from some central repository for icons of websites, or what, but ideally it should load the page and grab that page's icon to display it directly from the source if possible.

<img width="555" alt="image" src="https://github.com/user-attachments/assets/b438a98e-133e-4322-9df6-93ca813e6274">

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.4

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by mr-cheffy** [comment]
This should be fixed now, thanks!
