### ISSUE TITLE
Google Sign-In Not Supported on Zen Browser

### ISSUE THREAD

**Issue by baddymaster** [zen-browser/desktop#1661]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

<img width="1142" alt="Screenshot-Zen" src="https://github.com/user-attachments/assets/58489be3-b907-4169-8e7d-9f7d61aacd9e">

Logging into Google accounts via Google's Sign-In page does not seem to be supported on Zen Browser. I have replicated this issue on two separate machines and each time I try and log in, I simply get the "This browser or app may not be secure." error message shown above. This is not an issue on the latest version of Firefox on the same machines. 

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.4 (64-bit)

### What platform are you seeing the problem on?

macOS - aarch64, macOS - Intel

**Comment by JSGRD22** [comment]
Cannot replicate on Windows

**Comment by RayZ3R0** [comment]
Does this still happen on latest version? (a.14 as of this comment)

**Comment by baddymaster** [comment]
Yes, still happening as of version a.17!

**Comment by train013** [comment]
Yep
![image](https://github.com/user-attachments/assets/15b18ffd-c84a-4e99-9a3a-a6dd16cf211a)

**Comment by salamijason** [comment]
I had this issues a while back. Try using the [Chrome Mask](https://addons.mozilla.org/en-US/firefox/addon/chrome-mask/) addon and see if it helps! Let me know how it goes.

**Comment by salamijason** [comment]
No response in 1 week. For the sake of keeping the roadmap clean, I'll be closing this issue but please reopen if you still get this issue. Thank you.

**Comment by baddymaster** [comment]
I don't think Chrome Mask or any other extension should be the workaround to solve such a fundamental problem. However after testing with Chrome Mask, I can report that the problem still persists and Google returns the same error as before.

**Comment by salamijason** [comment]
> fundamental problem

The fundamental problem is caused by google prioritizing functionality on chromium. I get this issue often when logging into drive sync but Chrome Mask usually fixed it. I'll work on verifying this bug with other members of the team. Thanks for the input!

**Comment by salamijason** [comment]
I asked another member of the team who's on linux and re-logs into google everyday (cuz he clears cookies) and he says he's never experienced the issue. Further, a member on the dev team said this:

![image](https://github.com/user-attachments/assets/930372af-7265-416e-857e-015085726188)
![image](https://github.com/user-attachments/assets/cbeb144b-7bed-4d83-89d3-3d0c0664dda0)

Really is a bummer but we'll just have to deal with it. :/

**Comment by baddymaster** [comment]
That's really strange. I tried signing in to the same webpage today with both Zen and Firefox - the error persists on Zen (with or without Chrome Mask) and I'm able to sign in on Firefox without using any specific workaround. So I don't know if this really is a Chrome vs non-Chrome issue.
