### ISSUE TITLE
New Tab button is missing at the end of tab list

### ISSUE THREAD

**Issue by tgrothe** [zen-browser/desktop#1662]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Previously, the New Tab button was always at the end of the tab list. Now I have to add it manually and can only insert it at the beginning of the tab list.

This issue may relate to https://github.com/zen-browser/desktop/issues/1617

![grafik](https://github.com/user-attachments/assets/813ea4a0-68a4-4bf6-b1a3-2650f781e73b)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.3

### What platform are you seeing the problem on?

Windows

**Comment by LaixiLiu** [comment]
Create a new profile at `about:profiles`,and set it as the default profile.restart zen and change the profile into the initial profile you used, and the new tab button will appear again.This method works for me.

**Comment by win98se** [comment]
Mine appears at the most bottom of the vertical tab bar.

**Comment by wentlwr** [comment]
![图片](https://github.com/user-attachments/assets/2b717d64-7e8b-4c42-afea-8dd67b58a862)
i missed all of new tab button

**Comment by tgrothe** [comment]
> Create a new profile at `about:profiles`,and set it as the default profile.restart zen and change the profile into the initial profile you used, and the new tab button will appear again.This method works for me.

This doesn't bring the button back below the open tabs.

> i missed all of new tab button

You can customize the toolbar, but the new tab button will always appear above the tabs.

> Mine appears at the most bottom of the vertical tab bar.

This seems to be the default behavior (in a.4 ...)

**Comment by keiothic** [comment]
is it possible to be below the tabs again instead of all the way down like before? Some of us really do prefer it this way 
![image](https://github.com/user-attachments/assets/d9c66639-9a73-4cb6-bf7d-37d0127ad93d)

**Comment by kolemcraeatGroupBy** [comment]
There's a mod/theme that is supposed to do this: https://github.com/zen-browser/theme-store/pull/320

but people are saying the "official location" is right below the tabs, so... it seems a lot of us have a bug? Cause mine only shows either at the very top above the pinned tabs or at the very bottom of the screen. I am on a.5 which is the most recent.

**Comment by wentlwr** [comment]
> is it possible to be below the tabs again instead of all the way down like before? Some of us really do prefer it this way ![image](https://private-user-images.githubusercontent.com/6967348/370530962-d9c66639-9a73-4cb6-bf7d-37d0127ad93d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyODQ2OTcsIm5iZiI6MTcyNzI4NDM5NywicGF0aCI6Ii82OTY3MzQ4LzM3MDUzMDk2Mi1kOWM2NjYzOS05YTczLTRjYjYtYmY3ZC0zN2QwMTI3YWQ5M2QucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjVUMTcxMzE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDYzYTdiODQ0NTVkMTViOWY4Y2FkNWQ5ZjU1YjNhMWFmYWFmOGE5M2Y3MTIyMWFmNDRhYzEyMzY5ZjExNThlOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.SxNvvfXI92FncaP5RFf2DN0Upzk_Ci5zo-6Ryplbz14)

+1

**Comment by Dean-Corso** [comment]
The question is why it's not possible to move the + (new tab) button below in customize window. I also would prefer having more than just one + button for new tab the user can set anywhere. I would set them on top of all tabs and next to URL bar on right side. Having a choice to use symbols multiple times would be good.

Why does the + button now showing the "New Tab" string? Before it was showing just the + without any string and it was middle align what I do prefer. Just show the "+" alone again without any string after so all know that it makes a new tab and it looks annoying of course. Also there is a displaying but when you hold down left mouse on "+ New Tab" to get the in build container menu to see. The problem happens not in case of using right mouse click.
![TabM_2024-09-26_010412](https://github.com/user-attachments/assets/186d8ba6-03ee-4c90-a564-b1d2e3db1e9c)

**Comment by darkvergus** [comment]
while this is not the best implementation especially on expanded since you won't have the text but both on expanded and smaller sidebar works fine.

`#newtab-button-container {
    order: 999;
    display: block !important;
    border-top: 0 !important;;
    width: 100%;
}

#newtab-button-container::before {
    display: none !important;
}

#tabbrowser-arrowscrollbox:has(tab)::after {
    content: '';
    display: block;
    width: 100%;
    height: 1px;
    background: var(--zen-colors-border);
    margin-top: var(--space-small);
}

#vertical-pinned-tabs-container {
    padding-bottom: var(--space-small);
}`


add it to userChrome.css

**Comment by mr-cheffy** [comment]
This is a design choice, but will add this feature in the future. THanks!
