### ISSUE TITLE
Bookmarks not correctly displaying

### ISSUE THREAD

**Issue by Scepty-SSB** [zen-browser/desktop#1663]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The bookmarks toolbar doesn't correctly display my bookmarks anymore. Currently, if the toolbar displays at all, the bookmarks themselves are invisible. It appears to be more than just a graphical error, considering I can't click on them either.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.4

### What platform are you seeing the problem on?

macOS - aarch64

### Relevant log output

```shell
n/a
```

**Comment by fco-pires** [comment]
The same happened to me, but creating a clean profile resolved this and other problems.

**Comment by Scepty-SSB** [comment]
Interesting. That method didn't work for me.

**Comment by Scepty-SSB** [comment]
Appears to have been fixed on 1.0.1-a.5
