### ISSUE TITLE
Keyboard shortcuts are not being saved

### ISSUE THREAD

**Issue by notSagyo** [zen-browser/desktop#1664]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When modifying any shortcut in the settings page, they're not being saved, no matter what I try or how I leave the preferences page.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.4

### What platform are you seeing the problem on?

Windows

**Comment by Jusoaresg** [comment]
I notice that you need to press esc to save.

**Comment by drizzl4** [comment]
@Jusoaresg 

It works, thanks!

**Comment by notSagyo** [comment]
> I notice that you need to press esc to save.

Thanks! For anyone having this issue, in the meantime you have to press esc to save every single shortcut, as doing it only once won't save all.
