### ISSUE TITLE
NULL text on right click of compact hover sidebar

### ISSUE THREAD

**Issue by Anthonyy232** [zen-browser/desktop#1667]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![image](https://github.com/user-attachments/assets/45e13983-9488-4a0e-b334-ec02e5d5274d)

Text appears as such after right clicking on compact mode hover sidebar. Doesn't seem intended

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Version 1.0.1-a.4 (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by LeMoonStar** [comment]
Hey! When trying to reproduce this, I cannot find this menu option (and therefor also no unintended "NULL"). I assume this might be fixed by now.

Can you confirm this?

**Comment by Anthonyy232** [comment]
Should be
