### ISSUE TITLE
CMD+Q don't quit after the new update

### ISSUE THREAD

**Issue by ocean-mars** [zen-browser/desktop#1669]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Cmd+Q don't quit the app, also custom keyboard shortcut don't work (set shortcut & ESC to save), but even after saving it doesn't work

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.4

### What platform are you seeing the problem on?

macOS - Intel

**Comment by AleksZakirov** [comment]
another one that stopped working is CMD + F to search on page. Instead it makes zen go full screen.

**Comment by rustermi** [comment]
@AleksZakirov at least CMD+F can be fixed by removing the keyboard shortcuts like so:
<img width="1094" alt="image" src="https://github.com/user-attachments/assets/e0077bbc-fa6e-4db9-a73a-c1a886beb867">

**Comment by kalvinpearce** [comment]
A workaround that seems to work for me is to remove the keyboard shortcuts in the Zen settings > Keyboard Shortcuts page for each of the affected shotcuts. E.g. I got quit to work like this: 
<img width="787" alt="image" src="https://github.com/user-attachments/assets/b2a2e958-e7f7-49db-b4bd-6154219d4434">

**Comment by mauro-balades** [comment]
Please follow the discussion here, thanks! https://github.com/zen-browser/desktop/issues/1629
