### ISSUE TITLE
Open all bookmarks in New Window

### ISSUE THREAD

**Issue by jimfr** [zen-browser/desktop#167]
### What feature would you like to see?

I know that Firefox doesn't have it, but many browsers do.  When I right-click on a bookmarks folder (from the toolbar or sidebar), I can open all bookmarks.  I'd love one additional item: Open all bookmarks in New Window.

### What platform are you seeing the problem on?

macOS

### Additional context

Thanks for an absolutely awesome browser.  It's now the only browser I use.

**Comment by jimfr** [comment]
Shift-click on a bookmarks folder works - that's good enough for me

**Comment by mauro-balades** [comment]
:)
