### ISSUE TITLE
Spotify playback working sometimes, not all the time

### ISSUE THREAD

**Issue by amethyze** [zen-browser/desktop#1671]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When I play a song in Spotify, it starts skipping to the next one, and the next one, and so on until after a random amount of songs, it starts playing that song. 

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.4 (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by onthejobtraining** [comment]
Spotify will not work properly on Zen unless Zen pays the price for the DRM license.

**Comment by onthejobtraining** [comment]
https://github.com/zen-browser/desktop/issues/1401

https://github.com/zen-browser/desktop/issues/472

Also, please actually search for your issues on issues tab before falsely clilcking on the 

- [ ]  I have searched existing issues and avoided creating duplicates.
