### ISSUE TITLE
Ability to change shortcut for 'New private windows' disappeared and 'New Window' is duplicated in keyboard shortcut setting.

### ISSUE THREAD

**Issue by lillytoo** [zen-browser/desktop#1673]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![image](https://github.com/user-attachments/assets/92126d1e-1ee5-4a0b-8529-fa542e64e4fe)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.4 (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by samwick07** [comment]
Lost ability to add custom shortcuts. Newly added shortcuts are lost upon settings close. Existing custom shortcuts have been lost too.
