### ISSUE TITLE
Top bar hides on traffic lights hover in compact mode

### ISSUE THREAD

**Issue by amtoaer** [zen-browser/desktop#1674]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

See the GIF below; due to this bug, it's difficult to click the buttons.
![20240924151102_rec_](https://github.com/user-attachments/assets/c2e882e4-2514-4dd3-9bc6-84d14a332c3f)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.4

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by salamijason** [comment]
Heylo, looks like this issue was posted a while back. Are you still getting this on the lastest version? (a17 as of this comment)

**Comment by salamijason** [comment]
No response in 3 days. Will be closing this issue. Please reopen if you are still facing the issue.
