### ISSUE TITLE
cant add extensions or plugins

### ISSUE THREAD

**Issue by fmitesh007** [zen-browser/desktop#1675]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Cant add extensions or plugins. Also, there are a lot of UI glitches recently i Donna is this only with me, but I'm facing a problem with moving new tab button in sidebar also I can't see the extensions' logo that usually available on toolbar I tried to manually bring it back but failed.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.4

### What platform are you seeing the problem on?

Windows

**Comment by onthejobtraining** [comment]
Create a new profile by going to `about:profiles` and check if the issues persists.

**Comment by NanKillBro** [comment]
Me too. the extension logo is disappearing and I cannot bring it back. However, in the new profile, the extension logo is still here, weird. Now it annoys me a lot because I do not want to create a new profile and I can't use my extension like normal.

**Comment by gaam24** [comment]
I on click "Restore Defaults" on Customize Toolbar and it also disappeared for me.

**Comment by onthejobtraining** [comment]
Disable your zen mods/extensions https://github.com/zen-browser/desktop/issues/1633#issuecomment-2371586100

**Comment by gaam24** [comment]
Still the same, after removing all zen mods and extensions. Only new profile fix this

**Comment by gaam24** [comment]
I think I found a temporary solution, at least it worked for me
1. Click to profile and go to settings
2. Open folder of root directory
3. Edit prefs.js file and remove line `user_pref("browser.uiCustomization.state","...");` and save.
4. Restart browser

**Comment by mauro-balades** [comment]
This has been fixed, building right now

**Comment by gaam24** [comment]
a okey, thanks
