### ISSUE TITLE
Custom keybinding for switching workspace not working

### ISSUE THREAD

**Issue by tortoise10h** [zen-browser/desktop#1677]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

After customizing keybinding for switching workspaces like this 
![image](https://github.com/user-attachments/assets/2345b91c-af07-40b6-8c2f-d601bbd92cd1)

- Pressing `Cmd+1` (`2`, `3`, ...) doesn't switch workspace
- Pressing `Cmd + e`  doesn't move forward (but the `shift + cmd + e` does move backward)
- Bonus: `Cmd + ,` doesn't work also

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.4

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by jurienhamaker** [comment]
+1
Almost none of my keybinds work anymore (Tab switching doesn't work either)

**Comment by tortoise10h** [comment]
All the custom bindings work again now on version `1.0.1-a.5`

- About the `Cmd + ,` to go to setting it doesn't work by default, instead we have to remove the keybinding here, to make it work (that's weird but it works)
![image](https://github.com/user-attachments/assets/7c90df11-6f0f-46d9-a908-e01f515be599)
- To make the custom keybindings as above to work, we also have to remove the existing duplicate keybindings for tab 
![image](https://github.com/user-attachments/assets/f64788e1-efd3-42f2-b038-af7b42231fe3)


Glad to be able to config the keybinding for workspace movement, it makes my workflow faster !

**Comment by jurienhamaker** [comment]
However this does not work for windows @tortoise10h 

I rebinded all "select tab" to "ctrl+shift+<number>" to bind "Select workspace" to any "ctrl+<number>". 
But the shortcuts wont save at all

**Comment by tortoise10h** [comment]
@jurienhamaker for now, if you want to save the custom shortcut, try this steps
1. Change the shortcut as you want
2. Press `ESC` 

Do that per every shortcut not in a batch. It tried it and it works on mac, not sure on Window

**Comment by jurienhamaker** [comment]
@tortoise10h thanks that worked!

**Comment by tortoise10h** [comment]
Great!!
