### ISSUE TITLE
Keyboard shortcuts for switching to specific tabs are broken

### ISSUE THREAD

**Issue by sjclayton** [zen-browser/desktop#1679]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The Firefox default keyboard shortcuts for quickly switching tabs using `Alt + [1 through 0]` are no longer working.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.4

### What platform are you seeing the problem on?

Linux

**Comment by jurienhamaker** [comment]
+1
Almost none of my keybinds work anymore (Workspace switching doesn't work either)

**Comment by paulwyszynski** [comment]
same on Mac OS. Can't change shortcuts, and default ones are not all working

**Comment by sjclayton** [comment]
Still an issue as of 1.0.1-a.5

**Comment by sjclayton** [comment]
Resolved as of 1.0.1-a.5

**Comment by sjclayton** [comment]
Resolved in 1.0.1-a.5
