### ISSUE TITLE
Command + Q doesn't work

### ISSUE THREAD

**Issue by the-shoemaker** [zen-browser/desktop#1680]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Since the newest update cmd + q, cmd + , and many more don't work anymore on macOS.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.4

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by Nitrousoxide** [comment]
cmd + f (which should be find/search the page) also instead goes fullscreen on mac.

**Comment by the-shoemaker** [comment]
> cmd + f (which should be find/search the page) also instead goes fullscreen on mac.

I fixed that, by deleting the f11 shortcut for full-screen, which doesn't really make sense, it's all behaving very oddly. Also, you can get cmd + w and t back by double-clicking in the box to select the small "w" and replacing it with a large "W" by pressing shift. Somehow that works on a few of the basic browser shortcuts, but not everything.

**Comment by vitusli** [comment]
Same, basically all my shortcuts for mac are 

a) gone, I had to set them up again 
b) There are many new options for shortcuts but really important like tab switching are gone

Probably just a temporary bug. I love your work and really appreciate every feature you add. Thank you so much.

**Comment by chriskirknielsen** [comment]
Just chiming in that `Cmd+Q` does _something_ for me (**Cmd+Q Catcher** extension enabled notifies me of the attempt), however when disabling the extension, indeed, nothing happens. Additionally, as reported above, `Cmd+F` goes fullscreen instead of search, and `Cmd+,` does not open settings. I use shortcuts a lot, but so far, those are the ones that stand out.

**Comment by the-shoemaker** [comment]
> Same, basically all my shortcuts for mac are
> 
> a) gone, I had to set them up again b) basically no one works anymore, also not the ones I set up again (except for the most basic like cmt+t and cmd+w, cmd+opt+arrows do work)
> 
> There are many new options for shortcuts since the last update but really important like space and switch tab switching are gone. Probably just a temporary bug. I love your work and really appreciate every feature you add. Thank you so much.

I also noticed that some shortcut boxes seem to be duplicated, so there are for example 2 full-screen options.

**Comment by neonfuz** [comment]
I'm pretty sure the cause of all of these bugs is Zen treating Cmd as Ctrl. They did it in an update. This is not how macos apps are supposed to work, they are supposed to be able to handle ctrl and cmd separately. On firefox you can do cmd+m to minimize, and ctrl+m to mute, without collisions. I really hope zen browser fixes this and returns macos keyboard functionality to how every other app works on macos.

**Comment by neonfuz** [comment]
I also noticed websites are capturing cmd when that does not happen on firefox on macos. For example, go to tiktok and try to close the tab with cmd+w. On the latest zen version this does not work, but on firefox for macos it does.

**Comment by mauro-balades** [comment]
Please follow the discussion here https://github.com/zen-browser/desktop/issues/1629, it might get fixed for the next release. Thanks!
