### ISSUE TITLE
Showing Bookmark Sidebar while Tabs are on the right moves them to the left

### ISSUE THREAD

**Issue by Kayinnasaki** [zen-browser/desktop#1681]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Launching the bookmark sidebar swaps tabs to the left and also breaks the interface a bit when you put them back the close/minimize/maximize buttons end up padded far out of the way). Seemed to happen with or without mods from the store installed.

Also relatedly, I really miss the button that instantly owned the bookmark sidebar. Not having that as a widget I can add feels like a real downgrade as I pretty much never want that menu

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.4

### What platform are you seeing the problem on?

Windows

**Comment by onthejobtraining** [comment]
Could you please share a screen recording of the issue? It would be easier that way.

**Comment by Kayinnasaki** [comment]
Sure thing

https://github.com/user-attachments/assets/fcff9dbb-cd31-4f7b-aaa6-87b0de567ced

The "goes back to the right and messed up the OS window buttons" wasn't happening this time. Instead, it just refused to move back until I restarted it.

**Comment by sudanchapagain** [comment]
it does the opposite for me, when i have it on the left and when opening bookmarks it shifts it to the right.

**Comment by LeonKohli** [comment]
I have had the same problem yesterday, it was default small on the left side and when clicked to expand it would expand to shift the to right side.

**Comment by sudanchapagain** [comment]
Yes, i had closed GitHub but reopened to say this. I didn't realize why it wasn't expanding, so came to see any new issues here. I just saw it going to the right and ignored that it had expanded but on the right. I assumed that the expand button was swapped out for changing place of the bar.

Somehow my keybinds were also reset, so key press combination wasn't helpful too.

**Comment by Kayinnasaki** [comment]
Fixed, as of 1.0.1-a.8
