### ISSUE TITLE
Missing "Enter Full Screen" keyboard shortcut on macOS

### ISSUE THREAD

**Issue by benface** [zen-browser/desktop#1682]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I would like to change this shortcut because it's conflicting with the "Find on page" one that I am used to and that I tried setting:

![CleanShot 2024-09-24 at 11 51 20@2x](https://github.com/user-attachments/assets/64b272a4-4f3e-46c4-b58e-f51d16593249)

Unfortunately, the only keyboard shortcuts related to "full screen" I could find are these, which seem like they're the same but don't actually work:

![CleanShot 2024-09-24 at 11 52 22@2x](https://github.com/user-attachments/assets/7ddf3a86-8fa8-4d35-ae1c-a89bfcc53628)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.4 (64-bit)

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by enmyj** [comment]
+1. Not to be dramatic but this is sort of a showstopper for me - I almost never want full screen and regularly want "find on page"

**Comment by mitgr81** [comment]
> +1. Not to be dramatic but this is sort of a showstopper for me - I almost never want full screen and regularly want "find on page". The defaults for these two actions definitely shouldn't be the same

It's not just you 😁 I came here to find a bug report for this or to create one if necessary.  `CTRL-CMD-F` is one that I see commonly enough to recommend.

**Comment by mitgr81** [comment]
Update: the issue for me was solved in `1.0.1-a.5` likely with https://github.com/zen-browser/desktop/issues/1629

**Comment by LeMoonStar** [comment]
> Update: the issue for me was solved in `1.0.1-a.5` likely with [#1629](https://github.com/zen-browser/desktop/issues/1629)

Closing as this has been fixed.
If this is incorrect, please comment or re-open this issue.
