### ISSUE TITLE
Three dots in drop-down menu not working properly

### ISSUE THREAD

**Issue by jlnalber** [zen-browser/desktop#1683]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Since 1.0.1-a.4, the three dots button can be moved to the drop-down menu. However, clicking on the three dots in the drop-down menu opens the three dots menu, but ultimately closes it again. I guess that is because the drop-down menu automatically closes and therefore the three dots menu as well.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.4

### What platform are you seeing the problem on?

Windows

**Comment by onthejobtraining** [comment]
Could you share a screen recording, because I'm not able to reproduce the issue.

**Comment by DrHibbertMD** [comment]
https://github.com/user-attachments/assets/c6c4f4bd-ce05-40bd-a13f-c6d988d6288c

**Comment by DrHibbertMD** [comment]
https://github.com/user-attachments/assets/adc7ef65-eb6e-49fb-9a37-de4bf1d793c9

**Comment by DrHibbertMD** [comment]
https://github.com/user-attachments/assets/1f8f40be-4ac0-4f9e-a422-92cf2626e1b9

**Comment by salamijason** [comment]
i believe the three dot menu is no longer draggable so this issue has no reason to occur. Thank you for pointing it out when you did, though!
