### ISSUE TITLE
Automatic appearance setting doesn't work

### ISSUE THREAD

**Issue by Donnnno** [zen-browser/desktop#169]
### What happened?

![image](https://github.com/user-attachments/assets/fbb89e69-9050-4624-9b70-92f6d0224a2e)

I'm currently using Windows 11, it does seem to work on Firefox tho.

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a13 (64-bit)

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
Appearance is based on what theme you have, not on windows theme. You can change Zen's theme in the plugins page. Automatic themes are not yet supported

**Comment by mauro-balades** [comment]
Yeah 🤣

Appearance is for the website appearance, not the browsers btw. Firefox making bad design decisions

**Comment by sjaramillo10** [comment]
I was extremely confused by this! 'System theme — auto' is working nicely 👌
