### ISSUE TITLE
Can't customize Zen compact mode shortcuts

### ISSUE THREAD

**Issue by rafsrs** [zen-browser/desktop#1693]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

After updated the zen browser my custom keyboard shortcuts for compact mode disappeared and when I try to change the shortcut it appears to change, but when I try to use it, it doesn't. This are Happening with the following shortcuts I've tested: 'Toggle floating toolbar', 'Toggle floating sidebar' and 'Toggle Compact Mode'.

I've tried to use the following shortcuts: Cmd+E, Cmd+R, Cmd+D.
Obs: I removed the original associations with these shortcuts.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.4

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by ahmedYasserM** [comment]
Same thing here

**Comment by kamm3r** [comment]
im on linux.
too be real the whole keyboard shortcuts customization is broken at least for me.

might be related to the issue:
when i have changed a shortcut to my prefer one and click on the search field or switch to other tab, the shortcut that i changed is this await for input to change until i manually press escape.

**Comment by yusufipk** [comment]
I am using Arch Linux and experiencing the same issue. I am currently on version 1.0.1-a.5. In previous versions, I was able to customize the shortcuts.

Also while the default shortcut for compact mode works for me, the other default shortcuts do not work at all. I cannot change the default keybindings, and the shortcuts for "floating toolbar" and "floating sidebar" do not function.

**Comment by yusufipk** [comment]
It is fixed for me after the update. Now it works properly and warns to save the shortcut.

**Comment by rafsrs** [comment]
It are now working for me after removing used keys combination in another shortcut and saving the new shortcut with the ESC button.
