### ISSUE TITLE
Remove borders on the browser

### ISSUE THREAD

**Issue by kralion** [zen-browser/desktop#1694]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

There should be an option to utilize the **entire screen** without **any borders** in the browser, as there is currently an approximate **4px border** present on every tab and page I visit. In earlier versions, the browser filled the entire screen, providing a kind of 'Zen Mode' that was excellent for focused browsing. However, these new versions has introduced the border, which detracts from that immersive experience.

![image](https://github.com/user-attachments/assets/63ec9c67-7d68-4ec2-91c7-de235eac49c3)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.4

### What platform are you seeing the problem on?

Windows

**Comment by win98se** [comment]
Do you have [this utility](https://zen-browser.app/themes/680424a8-a818-406b-98c5-7726214e2a9f) installed and updated to latest?

**Comment by mauro-balades** [comment]
change `zen.theme.content-element-separation` in `about:config` to 0

**Comment by Sostay** [comment]
> change `zen.theme.content-element-separation` in `about:config` to 0

![图片](https://github.com/user-attachments/assets/e2143d95-cc7e-4bfc-9adf-f2285b121644)

It seems that one pixel is missing at the top. How can I increase it?

**Comment by kralion** [comment]
It's working fine , close the issue
