### ISSUE TITLE
Misaligned new tab and menu buttons

### ISSUE THREAD

**Issue by Prokid64** [zen-browser/desktop#1695]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The menu and new tab icons are misaligned on the sidebar. 

![menu_new_tab_misaligned](https://github.com/user-attachments/assets/0023c76c-3d84-4418-8754-3b072cc33595)

1. The web icon is misaligned with the tab container.
2. The tab icon is misaligned with the sidebar.
3. The tab icon is misaligned with the three-dot menu icon.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.4

### What platform are you seeing the problem on?

Windows

**Comment by sjclayton** [comment]
Happens with any button placed in that position, seems padding in this browser is something the dev just can't figure out.
