### ISSUE TITLE
Windows window decorations are not aligned to the top corner

### ISSUE THREAD

**Issue by bdbch** [zen-browser/desktop#1696]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I think we had this issue previously in one of the pre-alpha versions.

Basically the Windows window decorations (minimize, maximize and close) have a top margin now which leads to more misclicks when trying to closing maximized windows.

![image](https://github.com/user-attachments/assets/12813994-1be0-420b-a447-f5006561b42d)

You can see it in this screenshot - my cursor is above the maximize/close button but they don't react. I think the Windows default is that those decorations **should** end at the top border of the window to allow users to quickly close/minimize a window by just slamming their mouse in the upper right corner of the screen.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.4 (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by NOCanoa** [comment]
Fixed, let me know if u still have the issue.
