### ISSUE TITLE
Cant change to keyboard shortcuts

### ISSUE THREAD

**Issue by MRJonas343** [zen-browser/desktop#1699]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

If I try to change a deafult keyboard shortcut, it fails, and I even lost the default shortcut, 

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1

### What platform are you seeing the problem on?

Windows

**Comment by ahmedYasserM** [comment]
I have the same problem on arch linux, event `alt+tabNumber` doesn't work

**Comment by thyeun** [comment]
Some of the shortcut key not working also, as an example ```Ctrl + H``` with version 1.0.1-a.4

**Comment by KorigamiK** [comment]
bad code was pushed smh, 
maybe this is the culprit? 
https://github.com/zen-browser/desktop/pull/1648

**Comment by MisterHighping** [comment]
He already wrote on reddit that is fixing it. Give him some time. Still an alpha I guess. :D 
https://www.reddit.com/r/zen_browser/comments/1fofg9f/woah_sorry_about_that_folks/

**Comment by ahmedYasserM** [comment]
I didn't know that he is working on this bug, I really appreciate his awesome effort @MisterHighping

**Comment by 0PandaDEV** [comment]
This is a dupplicate https://github.com/zen-browser/desktop/issues/1715

**Comment by RayZ3R0** [comment]
Duplicate and probably fixed. If not fixed, reopen please, thank you.
