### ISSUE TITLE
Some modifier key + Click link should open the new tab in a vertical split on the right.

### ISSUE THREAD

**Issue by alexleduc76** [zen-browser/desktop#170]
### What feature would you like to see?

I'm not sure what the shortcut should be, but it would be great to be able to quickly open a link to a vertical split on the right.

It would also be nice to be able to split the current tab with a shortcut and the view on the right would be the default tab content, instead of needing to open 2 URLs in separate tabs and then grouping them in a split view.

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
A shortcut release has been applied for the next release (17), see how that feels!

**Comment by NicoNekoru** [comment]
Did this end up getting implemented? I can't seem to figure out where this can be changed/any documentation on it.

**Comment by yankydoo** [comment]
which modifier key was implemented? I can't find anything in the docs https://docs.zen-browser.app/user-manual/split-view#creating-split-view
