### ISSUE TITLE
Keyboard Shortcuts

### ISSUE THREAD

**Issue by bmdev88** [zen-browser/desktop#1701]
### Captchas

- [ ] I have read the instructions.
- [ ] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

The Keyboard Shortcuts are really annoying - the concept of the browser, the user experience and the performance is really impressive, but the behavior of the Keyboard Shortcuts are the worst i've ever seen....

In Version 3 i was able to handle the keyboard shortcuts - in v4 a complete new design of the Keyboard Shortcut Functionality is delivered - WHY???

None of the settings before are working anymore - and what is much more worse, the new settings are not "saved" - so it is again not working...

I'm not sure if this is Best-Practise in Software Design and Development - but please check again the capabilities of Keyboard Shortcuts... Do you test the Releases?

Sorry to say - but this is one part that i most unlike!!

Keep fingers crossed that you will manage it!

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

﻿Version 1.0.1-a.4

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by bmdev88** [comment]
***@***.***

From: linear[bot] ***@***.***>
Date: Tuesday, 24. September 2024 at 20:41
To: zen-browser/desktop ***@***.***>
Cc: Bernsteiner, Martin ***@***.***>, Author ***@***.***>
Subject: Re: [zen-browser/desktop] Keyboard Shortcuts (Issue #1701)

ZEN-1727 Keyboard Shortcuts<https://linear.app/zen-browser/issue/ZEN-1727/keyboard-shortcuts>

**Comment by KorigamiK** [comment]
This is a regression that's too much to handle, take me back man

**Comment by ivanjx** [comment]
i can no longer open history (ctrl + h) and bookmars (ctrl + b) which is critical. i am pinning to a3.

**Comment by mauro-balades** [comment]
This should now be fixed in the latest version, no?

**Comment by ivanjx** [comment]
those two that i use work fine on a5. not sure about the others.

**Comment by RayZ3R0** [comment]
Does this still happen on latest version? (a.14 as of this comment)

**Comment by salamijason** [comment]
No responses in one week. Will be closing this issue. Please reopen if anyone is still encountering problems.
