### ISSUE TITLE
browser.tabs.closeWindowWithLastTab creates one extra tab

### ISSUE THREAD

**Issue by LAUCHGeorge** [zen-browser/desktop#1704]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When having browser.tabs.closeWindowWithLastTab on false it creates a second tab when all tabs get closed, see:
https://github.com/user-attachments/assets/0ed03901-6948-48de-9656-a6962d22d5be

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.4

### What platform are you seeing the problem on?

Windows

**Comment by salamijason** [comment]
Hi! Looks like this was posted a while ago. I just tried to recreate what you did and I was unable to get the same issue. Are you still getting this on the latest version? (a17 as of this comment)

**Comment by LAUCHGeorge** [comment]
> Hi! Looks like this was posted a while ago. I just tried to recreate what you did and I was unable to get the same issue. Are you still getting this on the latest version? (a17 as of this comment)

I have noticed quite recently, that this issue does not happen anymore, didn't think to report that here, sorry about that.

**Comment by salamijason** [comment]
All good! Glad the issue's gone.
