### ISSUE TITLE
Bug flex space

### ISSUE THREAD

**Issue by myamusashi** [zen-browser/desktop#1707]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When I update from 1.0.1-a.2 to 1.0.1-a.4 I get a flexible space bug that I don't want, and this cannot be removed.
![image](https://github.com/user-attachments/assets/c1709344-17d6-4f71-acad-eac07b9b66fa)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.4

### What platform are you seeing the problem on?

Linux

**Comment by ocean-mars** [comment]
Had this on last update, just open "Customize Toolbar" & remove it.

**Comment by myamusashi** [comment]
I've done it, and the flex space always pops up. But yeah, I already solved it by creating a new profile. Maybe i close this one
