### ISSUE TITLE
Galaxy and Dream Theme are gone. How do I get them back?

### ISSUE THREAD

**Issue by Eff0rtly** [zen-browser/desktop#1709]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Let's bring back the two themes.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.4

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
no log
```

**Comment by darkvergus** [comment]
pretty sure they have been removed in 1.0.1-a.3

![image](https://github.com/user-attachments/assets/5fa66099-f7ee-4c6e-bd0e-b267a386f97a)

**Comment by cyrneko** [comment]
> I upgraded directly from 1.0.2 to 1.0.4

...they're not there anymore nonetheless?

**Comment by Eff0rtly** [comment]
> > I upgraded directly from 1.0.2 to 1.0.4我直接从 1.0.2 升级到 1.0.4
> 
> ...they're not there anymore nonetheless?...尽管如此，他们已经不存在了？ That is **intended behavior.**这是**有意为之的行为。**

Dude, I really like those two themes.

**Comment by cyrneko** [comment]
They're not coming back if I had to guess, with every theme you add you need to test the whole layout with every theme.

PS: I'm not a dude.

**Comment by n7itro** [comment]
They might be added back as Zen Mods.

**Comment by JSGRD22** [comment]
As far as I know those themes add a gradient of sorts to the browser, you can try installing SuperGradient from the theme store and customising the gradient colours and zones to achieve a similar effect.

**Comment by KarimElsayad247** [comment]
I was sad when they were gone, but tbh they seemed more trouble than worth.

**Comment by tomassasovsky** [comment]
Sucks that they removed them - It's def not a good user experience to update your browser and see things that you configure one way change, especially if you can't set it back with ease. I know this is an alpha, but it's just very annoying to have that happen again and again... Are there any plans to make this into a Zen Mod?

**Comment by cyrneko** [comment]
> Sucks that they removed them - It's def not a good user experience to update your browser and see things that you configure one way change, especially if you can't set it back with ease. I know this is an alpha, but it's just very annoying to have that happen again and again... Are there any plans to make this into a Zen Mod?

Well, FWIW:
1. This was mentioned as a breaking change in the changelog
2. Due to it's alpha status, everything is to be considered **experimental** until a 1.0 Stable release (at which point some level of API stability should be given). This also means that every setting, every theme, every change is done to see how well it works in real-life usage and may get removed when it doesn't work out - like in this case by tripling the UI Testing Workload.

**Comment by n7itro** [comment]
BTW, the Supergradient mod has a preset for Galaxy and Dream

**Comment by Eff0rtly** [comment]
> BTW, the Supergradient mod has a preset for Galaxy and Dream
> 
> Is this close to the original? If not, I will add the original to https://zen-browser.app/themes

Although the mod adds this, it can't be used in conjunction with the rest of the theme to show off the unique and beautiful gradient.

**Comment by Eff0rtly** [comment]
> BTW, the Supergradient mod has a preset for Galaxy and Dream
> 
> Is this close to the original? If not, I will add the original to https://zen-browser.app/themes

In the old days when these two themes were not removed with that mod you could do beautiful gradients

**Comment by Eff0rtly** [comment]
> BTW, the Supergradient mod has a preset for Galaxy and Dream
> 
> Is this close to the original? If not, I will add the original to https://zen-browser.app/themes

I still want you to add dream and galaxy back.

**Comment by n7itro** [comment]
> Although the mod adds this, it can't be used in conjunction with the rest of the theme to show off the unique and beautiful gradient.

Can you clarify what you mean? 
I want to make sure this is still possible if I add it as a Zen Mod (CSS) instead of a Firefox Theme (JSON)

**Comment by Eff0rtly** [comment]
> > Although the mod adds this, it can't be used in conjunction with the rest of the theme to show off the unique and beautiful gradient.
> 
> Can you clarify what you mean? I want to make sure this is still possible if I add it as a Zen Mod (CSS) instead of a Firefox Theme (JSON)

Yes please make a Zen mod

**Comment by n7itro** [comment]
@Eff0rtly what do you mean with "can't be used in conjunction with the rest of the theme"

**Comment by Eff0rtly** [comment]
> @Eff0rtly what do you mean with "can't be used in conjunction with the rest of the theme"

I'm not a native English speaker, so I have to use translation software to say what I want to say

Sometimes it's not translated accurately.

**Comment by n7itro** [comment]
In what way could those two themes be used in conjunction?

**Comment by Eff0rtly** [comment]
> In what way could those two themes be used in conjunction?这两个主题可以以何种方式结合使用呢？

I mean zen Galaxy or zen dream with SuperGradient mod enabled at the same time.

**Comment by 0x6e7a6f** [comment]
I want the Galaxy Theme back too... 🥲

**Comment by n7itro** [comment]
> I want the Galaxy Theme back too... 🥲

Try the Supergradient mod
