### ISSUE TITLE
can't change shortcuts

### ISSUE THREAD

**Issue by nlsnmlna** [zen-browser/desktop#1710]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

can't change shortcuts on their own and always comes back as default

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.5

### What platform are you seeing the problem on?

Windows

**Comment by JSGRD22** [comment]
Same here on Windows

**Comment by ocean-mars** [comment]
Last update had same issue on macOS, But it's fixed, so please don't don't do anything to macOS build's keyboard shortcut, only problem on macOS is, after setting F13 as Close Tab, it doesn't work insstead "F" closes the tab

**Comment by bmdev88** [comment]
same here on mac

**Comment by BinQiAkira** [comment]
same here on windows

**Comment by 0PandaDEV** [comment]
This is a dupplicate https://github.com/zen-browser/desktop/issues/1715
