### ISSUE TITLE
The new updates version is garbadge

### ISSUE THREAD

**Issue by Macgregor01** [zen-browser/desktop#1711]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The new updated version is garbage.  I went nuts for 4 hours trying to fix what I though was user error. I was sure i messed up a setting somehow, just to find out that my problem was ADDED BY DESIGN!!!!???? gahhhh!!!!
I downgraded to v1.0.1.a and love it again.
Stop messing with the UI and not give people the options to put it back to how they had it before..
Stop improving it!! Your not making it better.

I do not plan to update ever...

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1a5

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by ocean-mars** [comment]
I'm also on macOS, & new update fixed many bugs, I don't get what you mean, maybe you broke something with userChrome

**Comment by LifeAO** [comment]
Zen Browser is in alpha development. Design and internals are bound to change. Better to talk about what's not liked and describe it for the devs to go over.

**Comment by bmdev88** [comment]
we do not like the always changing behavior of functionality like the Keyboard Shortcuts.

Even it is an Alpha version - most likely the basics of a browser should be stable (like open a Tab with a Shortcut...).

**Comment by NeuWasFlaggedAgain** [comment]
lol, this guy created a fuming issue about bleeding-edge software, and didn't even describe what the issue was. consider touching grass, my guy.

---

it's not the end of the world. do note: the major developers of zed don't owe you squat. if you want a stable browser with snail-paced development, go back to google (or stay here and be more constructive :)

**Comment by mauro-balades** [comment]
Great issue report, ill think about it long and hard
