### ISSUE TITLE
Many new bugs after the latest big update. 

### ISSUE THREAD

**Issue by Sounak008** [zen-browser/desktop#1712]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

1. The toolbar is attatched to the right side (i changed its position). Why isnt it floating like before?
2. The toolbar dissapears like that in the vid in compact mode
3. The weird blank space at the right side issue.
4. Lastly, the top bar appearing in new tab page is bad

Had to downgrade for these toolbar problems. Very annoying. Please fix them ASAP 🙏 

https://github.com/user-attachments/assets/89e69348-227a-42f7-be86-bf7bc177fa77

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Alpha build - 1.0.1-a.3 (2024-09-22)

### What platform are you seeing the problem on?

Linux

**Comment by ocean-mars** [comment]
Why are you on Version "Alpha build - 1.0.1-a.3 (2024-09-22)"?

**Comment by bmdev88** [comment]
I think the Version Alpha build - 1.0.1-a.3 was the latest "Stable" one - I have the same issue with the sidebar - suddenly, it appears on the right side, and I've not figured out how to move it back to the left side...

Was also on a4-Version and today on a5-Version - but none of them brings a better user experience... instead more issues in regards to the keyboard shortcuts..

**Comment by Sounak008** [comment]
> I think the Version Alpha build - 1.0.1-a.3 was the latest "Stable" one - I have the same issue with the sidebar - suddenly, it appears on the right side, and I've not figured out how to move it back to the left side...
> 
> Was also on a4-Version and today on a5-Version - but none of them brings a better user experience... instead more issues in regards to the keyboard shortcuts..

oh so I see, the issues are with having the bar at the left side. They probably did not test it for the right side. I can't use it at the left side, my screen has a black spot there 😢

**Comment by mauro-balades** [comment]
I believe all/most have been fixed, thanks!

**Comment by Sounak008** [comment]
> I believe all/most have been fixed, thanks!

Oh! thanks! I will then get the latest one
