### ISSUE TITLE
Keyboard Shortcuts not working after the new update!

### ISSUE THREAD

**Issue by marsattackswins** [zen-browser/desktop#1713]
### Captchas

- [x] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I had already set customizable shortcuts for switching Workspaces and toggling compact mode on and off, the new update broke that and I cannot even set new shortcuts and I have to use the default ones

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.5 

### What platform are you seeing the problem on?

Windows

**Comment by Abhik555** [comment]
same issue here

**Comment by ocean-mars** [comment]
Shortcuts work on macOS after the new update, But zen don't recognize F13, F14, F15 keys

**Comment by bmdev88** [comment]
It's the same issue here again. Please try to keep the settings and capabilities. Just make sure that the Keyboard Shortcuts work on all the Operating Systems you support with exactly the type of Keyboard Functions that are available on those systems.

Meta is not a Key on macOSX - whereas the Control key is mapped to Command.... totally confused???

**Comment by sjclayton** [comment]
Seems fixing things requires you to reset all the shortcuts you previously had set... so in order to fix the problem, seems it requires breaking things again that were already working... 😞

**Comment by Selfousse** [comment]
Same on linux

**Comment by 0PandaDEV** [comment]
This is a dupplicate https://github.com/zen-browser/desktop/issues/1715

**Comment by marsattackswins** [comment]
@0PandaDEV Please note that #1715 is having issues on a MacOS system, I am having issues on a Windows system. Totally not a duplicate.

**Comment by 0PandaDEV** [comment]
No, there are also a few reports about windows in that issue

**Comment by marsattackswins** [comment]
@0PandaDEV I did not see those sadly! I'll go ahead and close this issue.
