### ISSUE TITLE
Keyboard Shortcut resets to default after relaunch

### ISSUE THREAD

**Issue by ocean-mars** [zen-browser/desktop#1715]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

After quiting and reopening the app, Keyboard Shortcut resets to default. Also after setting F13 as Close Tab, it doesn't work insstead "F" closes the tab, F13 don't work as keyboard shortcut. but because everything resets to default, F13 doesn't matter now anyway, please fix it.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.5

### What platform are you seeing the problem on?

macOS - Intel

**Comment by bmdev88** [comment]
same issue here - and it is even more worse as we do not have the correct key mapping on MacOSX again - what is "Meta" on Mac Keyboard?

![CleanShot 2024-09-25 at 06 47 05](https://github.com/user-attachments/assets/c384075d-7305-4b4b-b0f7-b7cdfb5780aa)

**Comment by Kuttesch** [comment]
I have the same problem on Windows 11 23H2 , but I also can't change the default shortcuts / they don't work after changing them to something other than the default.

**Comment by Highlander214** [comment]
Same is occurring on Windows 10 22H2, they reset on relaunch.

**Comment by thelazyoxymoron** [comment]
Related: https://github.com/zen-browser/desktop/issues/1629

**Comment by 0PandaDEV** [comment]
Also happening for me after updating to alpha.5

**Comment by sjclayton** [comment]
Experiencing this on 1.0.1-a.5 on Linux as well, no modifications to any shortcuts are persisting between launches.

**Comment by Tim-OuY** [comment]
Shortcuts is a disaster, to be honest.

**Comment by doubleOZ** [comment]
same here. deleted and made a new profile, issue persists but ctrl + <number> seems to work now.

**Comment by huynguyentan-eh** [comment]
Same here, after custom the keybindings, everything works fine for a while then suddenly they are all reset to default keybindings without any notice :|

**Comment by mauro-balades** [comment]
do they update once you reload the preferences page?

**Comment by huynguyentan-eh** [comment]
Yes, I did press `ESC` after changing each shortcut and can use it "for a while" (like switching workspaces, and use normally) then suddenly they all comeback to default

**Comment by paulwyszynski** [comment]
Same issue on Macbook M1. Shortcuts are reset to default.

**Comment by sjclayton** [comment]
> You also need to press "esc" to save them

@mauro-balades 

Doesn't matter if you press `ESC` to save them, they don't end up getting saved... restart Zen and they are all gone again.

**Comment by ocean-mars** [comment]
> do they update once you reload the preferences page? You also need to press "esc" to save them

did esc to save, & reloading the preferences page doesn't reset, relaunching the app reset shortcuts

**Comment by Kuttesch** [comment]
> Yes, I did press `ESC` after changing each shortcut and can use it "for a while" (like switching workspaces, and use normally) then suddenly they all comeback to default

Same here, at first it worked on one PC (Windows 10) but not on the other (Windows 11). After a restart of both PCs it shortly worked on the second one, but now it does not work on either.

**Comment by fanesz** [comment]
same here, also when i try to change the "New Tab" shortcut to `ctrl + n`, it always create a new window instead. But when I change to other shortcut (for example `ctrl + t`), it work perfectly.

**Comment by fanesz** [comment]
same here, also when i try to change the "New Tab" shortcut to `ctrl + n`, it always create a new window.
But when I change to other shortcut (for example `ctrl + t`), it work perfectly.

**Comment by JonnyLoughlin** [comment]
It seems to happen whenever a new Zen window is launched.  

```
1. Change shortcut and test to see that the new one works after hitting esc.
2. Open up new window, (regular or private)
3. Refresh the shortcut page
```
Shortcuts are then reset to default

Linux 6.10.10-arch1-1 x86_64
Mozilla Zen 1.0.1-a.5

**Comment by diego-velez** [comment]
I'm having the same issue, I changed the keymap and saved with esc, put after relaunch they reset to default. Previously, they worked fine, but after an update they got reset, and they keep resetting. This is happening on Linux.

**Comment by mauro-balades** [comment]
Update: this will be fixed on the next release, thanks

**Comment by hjasond** [comment]
Thank you @mauro-balades! Can you confirm if this also fixes the macOS cmd key being mapped to a "meta" key in the shortcuts settings?

**Comment by paulwyszynski** [comment]
@mauro-balades cmd+q for close and cmd + ; for settings are also not working

**Comment by ocean-mars** [comment]
> @mauro-balades cmd+q for close and cmd + ; for settings are also not working. Would be nice to fix too 🙂

Check which version you're on, This issue was solved on last update

**Comment by mauro-balades** [comment]
I looked into this, it's fixed for the next release, thanks!

**Comment by paulwyszynski** [comment]
I'm on Alpha build - 1.0.1-a.5. After restarting Zen it works again. Thx.

**Comment by NOCanoa** [comment]
Can i close?

**Comment by paulwyszynski** [comment]
A wait, actually after remapping some other shortcuts, it stopped working for me...

**Comment by JonnyLoughlin** [comment]
> A wait, actually after remapping some other shortcuts, it stopped working for me...

Keymaps are being cleared whenever a new Zen window opens. A fix is in the next patch.

**Comment by d-kja** [comment]
I'm still having the same problem on win 11 with the latest version, it keeps resetting after relaunch

**Comment by paulwyszynski** [comment]
I guess we have to wait for the new release.

**Comment by vitusli** [comment]
I am having the same issues meantioned here. I miss a lot of the 'old' shortcuts as well like switching workspaces and jumping back and forth in tabs. anyone else is missing them? I miss them on all my machines.

**Comment by fanesz** [comment]
> I am having the same issues meantioned here. I miss a lot of the 'old' shortcuts as well like switching workspaces and jumping back and forth in tabs. anyone else is missing them? I miss them on all my machines.

+1

**Comment by plundration** [comment]
> I am having the same issues meantioned here. I miss a lot of the 'old' shortcuts as well like switching workspaces and jumping back and forth in tabs. anyone else is missing them? I miss them on all my machines.

+1

I am having this same issue and now can't access next tab and previous tab shortcuts.

**Comment by jovark** [comment]
> > I am having the same issues meantioned here. I miss a lot of the 'old' shortcuts as well like switching workspaces and jumping back and forth in tabs. anyone else is missing them? I miss them on all my machines.
> 
> +1
> 
> I am having this same issue and now can't access next tab and previous tab shortcuts.

+1

**Comment by DaitiDay** [comment]
> I am having the same issues meantioned here. I miss a lot of the 'old' shortcuts as well like switching workspaces and jumping back and forth in tabs. anyone else is missing them? I miss them on all my machines.

I like to also add the 'Open Settings' shortcut back.

**Comment by EuCaue** [comment]
> > I am having the same issues meantioned here. I miss a lot of the 'old' shortcuts as well like switching workspaces and jumping back and forth in tabs. anyone else is missing them? I miss them on all my machines.
> 
> +1
> 
> I am having this same issue and now can't access next tab and previous tab shortcuts.

+1 here

**Comment by Kuttesch** [comment]
In my case the problem mysteriously went away after a few browser restarts, a few Windows restarts and some try's of setting the shortcuts.

**Comment by cmcallister** [comment]
I'm on **macOS Sonoma 14.6.1** and am having trouble regardless of restart or not. Setting `Toggle Floating Toolbar`/`Sidebar`/`Compact Mode` simply does not seem take effect;  same for `Toggle Split View Horizontal`/`Vertical`/`'Grid` as well as `Close Split View`.

**Comment by mauro-balades** [comment]
This has been fixed, thanks a lot!
