### ISSUE TITLE
bad padding between Web panels and the Browser tabs 

### ISSUE THREAD

**Issue by tanaybhomia** [zen-browser/desktop#1716]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![image](https://github.com/user-attachments/assets/87808889-0fe5-4fc2-869d-95db1936dcdb)

There is essentially no padding on the web panels while the browser window looks great. although there is a bit of bottom padding on the Web Panels but is not on the top and the left side of it

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.4 (64-bit)

### What platform are you seeing the problem on?

Linux

**Comment by KarimElsayad247** [comment]
I would add that this is only an issue in compact mode, otherwise it looks ok in normal mode

Normal: 
![image](https://github.com/user-attachments/assets/942ae797-f4d7-4a29-b950-5079ec67e02c)

Compact
![image](https://github.com/user-attachments/assets/45d95fe7-6f9b-4587-9072-4c3e6a11e1de)

**Comment by mr-cheffy** [comment]
This has been fixed, thanks a lot!
