### ISSUE TITLE
Expanding tabs on hover makes the website layout "jump"

### ISSUE THREAD

**Issue by Sajito** [zen-browser/desktop#1718]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I have enabled "Expand tabs on hover". Since version 1.0.1-a.4 the page content visually jumps a bit, when hovering over the tab bar.

https://github.com/user-attachments/assets/3ab687a4-c885-4eb8-9763-8d17a3169524

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.5

### What platform are you seeing the problem on?

Linux

**Comment by sjclayton** [comment]
@Sajito 

This isn't just since 1.0.1-a.4 - it's been doing that for a while...

**Comment by Sajito** [comment]
It was working perfectly fine on multiple devices with 1.0.1-a.3. I know it existed before, but - at least from my pov - it's a regression since 1.0.1-a.4.

**Comment by KarimElsayad247** [comment]
I think it's related to this same problem of "Search in page" tab making the content jump as well.

https://github.com/user-attachments/assets/89d63d51-664d-4cab-8d43-b9de44874888

**Comment by yvvki** [comment]
This is a regressing issue from #957.

**Comment by mateuszkozakiewicz** [comment]
The issue is not fixed in `1.0.1-a.6` even though changelog say it is
Additionally in `1.0.1-a.6` the sidebar itself shifts downwards when expanding there are some weird separators at the top

**Comment by XInTheDark** [comment]
I can confirm, the website still shifts slightly upon expanding. And the separators have also appeared

https://github.com/user-attachments/assets/3c65ebd5-9437-4599-991b-8bf6c901daa9

**Comment by Microwave-WYB** [comment]
This is a big problem... I can never just click on the tab I wanted to click. I must wait for the tab panel to expand, then find the tab again, move my cursor there and click.

https://github.com/user-attachments/assets/48d2123f-827d-42c4-ac47-f79829a78b7a

**Comment by yvvki** [comment]
> This is a big problem... I can never just click on the tab I wanted to click. I must wait for the tab panel to expand, then find the tab again, move my cursor there and click.

@Microwave-WYB I think this is a separate issue of glitching tabs, the layout "jump" has since been fixed in 1.0.1-a.7.

**Comment by Microwave-WYB** [comment]
Good call. I should open a separate issue.

**Comment by mateuszkozakiewicz** [comment]
The issue is back again with the newest update ;)

**Comment by Sajito** [comment]
This was fine with `1.0.1-a.17`, but broke again with `1.0.1-a.18`.

**Comment by Sajito** [comment]
Not relevant anymore, because the expand on hover functionality has been removed.
