### ISSUE TITLE
Zen Sidebar Top Buttons option doesn't persist

### ISSUE THREAD

**Issue by damian-ds7** [zen-browser/desktop#1719]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Whenever I uncheck the option in the right click menu it always gets checked again on browser restart. The issue also occurs when all mods are disabled.

https://github.com/user-attachments/assets/d7d57f7c-c069-469e-98d7-3e2df785ddba

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.5

### What platform are you seeing the problem on?

Linux

**Comment by neogeographica** [comment]
Seen this behavior on macOS as well.

**Comment by neogeographica** [comment]
Seems like this option itself is now gone in 1.0.1-a.6. The only way to sort of approximate it might be to use "customize toolbar" to move/remove the individual buttons from up there (but that still leaves the blank space that contained them).

**Comment by damian-ds7** [comment]
As far as I'm aware the option still is gone from the menu and it's impossible to fill the blank space between tabs and the window edge
