### ISSUE TITLE
Compact mode description and image doesnt align

### ISSUE THREAD

**Issue by RABINGG** [zen-browser/desktop#1720]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![image](https://github.com/user-attachments/assets/dea787e7-5f74-414b-93d8-99592d08a6ca)
The images of Hide **Tab** Bar and Hide **Top** bar should be swapped

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.5

### What platform are you seeing the problem on?

Windows

**Comment by sjclayton** [comment]
@mauro-balades 

Your logic is clearly completely backwards compared to the way anyone else looks at this diagram... or else people wouldn't think it looks like it's wrong.
