### ISSUE TITLE
[Bug]: Sidebar glitch when it set up to right and window is resizing

### ISSUE THREAD

**Issue by Glitchy-Sheep** [zen-browser/desktop#1721]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I think this bug happened somewhere between a2 and a3.
When a sidebar is set up to be on the right any window resize event cause strange expanding (as you can see below).

There is a video of how to reproduce it:

[output.webm](https://github.com/user-attachments/assets/7595083e-a141-4ae6-bbd9-d8f7cbaa615b)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.5

### What platform are you seeing the problem on?

Windows

**Comment by lbrdt** [comment]
This also happens when opening developer tools, and switching tabs (Inspector/Network/Console) inside devtools.


![zen_GXM5BlcvIL](https://github.com/user-attachments/assets/14da2c3e-2eee-4a59-80f5-5552009bf698)

**Comment by DjilaanK** [comment]
Hello, I wanted to add that the same also happens when coming out of a fullscreen video, when tabs on the right and in compact mode.
[https://github.com/zen-browser/desktop/issues/2574](url)

**Comment by salamijason** [comment]
Hey! Do let us know if you're still getting this bug on b.2.

**Comment by Glitchy-Sheep** [comment]
> Hey! Do let us know if you're still getting this bug on b.2.

It's totally fine on latest releases, love you guys, thank you for your hard work!
