### ISSUE TITLE
Requesting Native Tab syncing on Zen

### ISSUE THREAD

**Issue by spectrum705** [zen-browser/desktop#1722]
### Captchas

- [ ] I have read the instructions.
- [ ] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

It'd be very useful if we had a robust and native Tab syncing for Zen separate from firefox sync. I just lost all my tabs, pinned and opened ones today out of the blue.  I noticed Zen just for workspace sync so maybe this could be implemented the same way? Please look into it.
Thank you

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.5 (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
Sorry but having a native sync for zen would require lots of money and resources, without mentioning the safety issues. It's better to leave it to mozilla, sorry
