### ISSUE TITLE
Grid exiting #1539 continuing

### ISSUE THREAD

**Issue by YelehaUwU** [zen-browser/desktop#1723]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The issue is still ongoing, even on macos.
There is also the ctrl+option+u shortcut being unfunctional on mac.

#1539

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

a5

### What platform are you seeing the problem on?

macOS - aarch64, Windows

**Comment by mauro-balades** [comment]
Yeah, shortcuts are still being worked on, you can just set them and that'll fix it

**Comment by YelehaUwU** [comment]
I'm not only talking about shortcuts.. 😄
