### ISSUE TITLE
"New tab" icon changes place when hovering when "Expand Tabs on Hover" is enabled

### ISSUE THREAD

**Issue by Yasand123** [zen-browser/desktop#1724]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

This is not a bug per se, but it's not an enhancement request either. It's more of complaint about an oversight or poor design.

When you have `Expand Tabs on Hover` enabled and hover over the `Open new tab` icon at the bottom, it expands the tabs area and the new tab icon moves to the right. This is not good because it means you basically have to do 2 steps to open a tab, the most common action you do in a browser. And it also means that sometimes you can overshoot and the mouse cursor would exit the expanded tab area since the open tab icon is moved to the the edge which collapses it.

A better way to approach this, at least for now, is to make it so when the tab area is expanded, the new tab icon would be on the left which would match its position when the tab area is collapsed. While this does move the sidebar icon, the open tab action as as I said earlier should have priority since it's the most used action. Chances are you are probably wanting to open a new tab vs side bar 9 times out of 10.

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.5

### What platform are you seeing the problem on?

Linux, macOS - aarch64, macOS - Intel, Windows

**Comment by heydoyouknowme0** [comment]
You can just change it's position using edit toolbar 
![screenshot-2024-09-25-09-53-38](https://github.com/user-attachments/assets/2b79f40d-cf3b-4ed6-a5aa-0573b85a6e20)
