### ISSUE TITLE
Default container not set when opening a website from outside of Zen

### ISSUE THREAD

**Issue by snipcola** [zen-browser/desktop#1725]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I've created a workspace and set a default container for it.
When I open a website from outside of Zen it will not set the default container.

Demonstration:
https://github.com/user-attachments/assets/1455ba44-1957-425f-b49b-20b4c5e37391

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.5

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by swingstuhisback** [comment]
Hello sexy

**Comment by snipcola** [comment]
Little update, I noticed sometimes I can't reproduce the issue. It is bizarre.
Here's an example where I can still encounter the issue:
![000331 Terminal 2024-09-29 00 31 38](https://github.com/user-attachments/assets/b0a82485-2852-4438-9cae-1487a08b8953)

**Comment by kristijanribaric** [comment]
Fixed with https://github.com/zen-browser/components/pull/52
