### ISSUE TITLE
WebGL unsupported

### ISSUE THREAD

**Issue by micahcjohnson** [zen-browser/desktop#1729]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

WebGL doesn't seem to be supported, despite being enabled in about:config.

First noticed trying to open a project in Figma. It gave this error:
![image](https://github.com/user-attachments/assets/fad7453a-a0c2-40c1-964b-7b18e509f753)

Then went to the [Aquarium demo](https://webglsamples.org/aquarium/aquarium.html) and was met with this error:
![image](https://github.com/user-attachments/assets/5008d39e-510c-404d-9d27-b5661803dd1b)

I found the existing issue #332, but it had been closed.

I'm not sure where to find log output, but am happy to provide that if relevant. Thanks

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.5

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by greeeen-dev** [comment]
Maybe you might've set both of these configs to true? I was able to replicate your issue on my M1 MacBook Air this way.
<img width="708" alt="image" src="https://github.com/user-attachments/assets/6c1a49ff-0caf-4ae5-9a80-351fad00f897">

Of course, there's probably many possible reasons WebGL isn't working for you, this is just one of the possibilities.

**Comment by micahcjohnson** [comment]
I haven't manually changed any configs. Also, I don't see those in the list anywhere.

**Comment by mauro-balades** [comment]
What value do you have in about:config for `webgl.disabled`?

**Comment by micahcjohnson** [comment]
> What value do you have in about:config for `webgl.disabled`?

It's set to `false`.

Are there any other configs to check?

**Comment by n7itro** [comment]
Try setting `webgl.force-enabled` to `true` and/or enabling hardware acceleration

**Comment by micahcjohnson** [comment]
> Try setting `webgl.force-enabled` to `true` and/or enabling hardware acceleration.
> 
> Also, restart Zen after making these changes

`webgl.force-enabled` did the trick for me. Thanks!

Happy to close this issue, but also wondering why it didn't work out of the box and if that'd be something worth looking into.

**Comment by n7itro** [comment]
WebGL is enabled by default, but it might have detected some compatibility issues. That's why you had to force enable it

**Comment by Gukkey** [comment]
This issue is occurring again at Version 1.9.1b (64-bit) 

![Image](https://github.com/user-attachments/assets/86a81a3a-c53c-457e-ad4d-571b2faa15b3)

**Comment by Nanome203** [comment]
> This issue is occurring again at Version 1.9.1b (64-bit)
> 
> ![Image](https://github.com/user-attachments/assets/86a81a3a-c53c-457e-ad4d-571b2faa15b3)

Same for version 1.10.3b

EDIT: i fixed this by upgrading graphic driver.
