### ISSUE TITLE
Automatically enable Picture-in-picture when swapping tabs

### ISSUE THREAD

**Issue by stripedew** [zen-browser/desktop#173]
### What feature would you like to see?

A great feature of browsers like Arc is that you can enable a setting which allows the browser to automatically enable PiP when you switch between tabs. A use case scenario would be:

1. Watching a video on YouTube or another PiP supported player page
2. When pressing on another tab, the player automatically enables PiP
3. (Optional) Coming back to the tab with the video returns the video into main page player

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
This will be done by firefox by the next release, so we just have to wait until they release it, thanks!
