### ISSUE TITLE
Workspace button brings up the on-screen keyboard on empty tabs

### ISSUE THREAD

**Issue by astro-ray** [zen-browser/desktop#1736]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When on-screen keyboard is turned on, empty tabs when you click on the workspace button, it brings up the on-screen keyboard. Since editing profiles have been moved, this behaviour is undesirable.

[Screencast from 2024-09-25 20-09-03.webm](https://github.com/user-attachments/assets/0aff0d6a-0820-4069-8562-7b578aa4a4d8)

OS: Fedora 40
DE; Gnome 46

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.5

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
This is because it's focusing on the newtab URL bar... Is that the problem?

**Comment by astro-ray** [comment]
Yes.
Is that an intended behavior?

**Comment by mauro-balades** [comment]
It is... If the tab is a newtab, it focuses the URL bar... Sorry!
