### ISSUE TITLE
Close Split View shortcut is not working on mac

### ISSUE THREAD

**Issue by samhuss** [zen-browser/desktop#1738]
### Captchas

- [X] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

Split view shortcuts work perfectly for all directions (H,V,G), but the shortcut for splitting the view doesn't work:  Ctrl+Opti+U

I'm using sidebery extension to manage all the tabs so I'm totally depending on the shortcuts to open and close the split views. 

I Tried to change the key bindings and add new one from  "settings -> Keyboard shortcuts" but the new shortcut was never saved.
I know that there are some issues with key bindings on mac but this one is different than the Cmd and Ctrl issue. 

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.5 (64-bit)

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by samhuss** [comment]
---- temporary fix
One solution that let the default shortcuts work was to add a new keyboard of type "Unicode Hex Input" that disables the the special characters with Alt key, doing so let the shortcut "Ctrl+Option+U" works

However, I can't stick to this keyboard as it disabled the cursor movement with the Alt key and Arrow right and left "Alt+Left Arrow" so I'm no longer able to select any text using the keyboard.

**Comment by samhuss** [comment]
---- temporary fix
One solution that let the default shortcuts work was to add a new keyboard of type "Unicode Hex Input" that disables the the special characters with Alt key, doing so let the shortcut "Ctrl+Option+U" works

However, I can't stick to this keyboard layout as it disabled the cursor movement with the Alt key and Arrow right and left "Alt+Left Arrow".

What I see as a quick fix is to fix the problem of saving the keyboard shortcuts, whenever I change those key bindings to anything else then restart I find the default key bindings back again.

**Comment by XavierEduardo99** [comment]
It isn't working on Microsoft Windows 11 also. I'm not sure if this is any help, but my keyboard layout is: US-International

**Comment by stoicAlchemist** [comment]
This is still happening after some updates. I would suggest adding a contextual menu item to close the split as a workaround and maybe even keep it for mouse users, right now I don't have a way to close splits without closing the involved tabs.

**Comment by esrid** [comment]
here for the same issues @stoicAlchemist just posted above. 
somehow instead of closing the split it open the source code of the current page.

**Comment by salamijason** [comment]
Are you guys still getting this issue on b.2?

**Comment by stoicAlchemist** [comment]
Yeah, I just checked, closing splits shortcuts just shows the code of the page on Mac

**Comment by salamijason** [comment]
Thank you all for the input. Looks like this issue is being further expounded on in #3698 so I'll be closing this issue. Please direct any further developments to that issue post, thank you!
