### ISSUE TITLE
bookmarks sidebar not resizable

### ISSUE THREAD

**Issue by lazymonkey2** [zen-browser/desktop#174]
### What happened?

I put the bookmarks sidebar on the right of the browser window.
I have notices that it's not resizable (instead in firefox 128 it is resizable).
please make it resizable.
thanks.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.13 (64-bit)

### Severity impact

Medium

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
It is re-sizeable, is this what you mean?

![Screenshot_20240809_225317](https://github.com/user-attachments/assets/4f1bca9c-10e1-4b4e-8c7f-b2ae36ba2a3a)

**Comment by lazymonkey2** [comment]
it is resizable when it's on the left (default), but it's not when it's on the right (select "Move sidebar to right" in the drop down menu of the sidebar)

**Comment by mauro-balades** [comment]
This shoud've had been fixed already, please feel to reopen if that's not the case
