### ISSUE TITLE
Settings conflicting with firefox.

### ISSUE THREAD

**Issue by bvgross** [zen-browser/desktop#1741]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I don't know if it's a feature or a bug, but zen browser is using the same configuration files (I assume) of firefox... So, when I make changes to one of the browsers the other gets it applied to it too. That's bad because the needs I have when using one of them are not the same when using the other (especially extensions).

I'm on fedora 40, using firefox from official repositories and zen browser via flatpak from flathub.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.5

### What platform are you seeing the problem on?

Linux

**Comment by goosethedev** [comment]
The Flatpak version is completely isolated and only have access to the XDG Downloads dir. Zen configs are stored at `$HOME/.var/app/io.github.zen_browser.zen/.zen` while Firefox configs are at `$HOME/.mozilla`. What configs seem to be shared in your case?
