### ISSUE TITLE
Position of an add-on popever

### ISSUE THREAD

**Issue by ZhenyaGoroh** [zen-browser/desktop#1746]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![image](https://github.com/user-attachments/assets/09512e15-19d1-4b71-854c-05b0952caf15)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.5

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
Is the application maximized?

**Comment by ZhenyaGoroh** [comment]
> Is the application maximized?

Yes

**Comment by mauro-balades** [comment]
And what happened to the tabs list?

**Comment by yyanezh** [comment]
It seemed to be fixed, thx!
