### ISSUE TITLE
HTML Form Element Input - value not set on input type="date"

### ISSUE THREAD

**Issue by RABIGA7OR** [zen-browser/desktop#1752]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

HTML input type="date" not setting the set default value. Input type="time" works just fine in showing the preset value.

Microsoft Edge (Chromium):
![grafik](https://github.com/user-attachments/assets/92951601-be5f-4805-89f1-098dded2d4ca)

Firefox:
![grafik](https://github.com/user-attachments/assets/a50d16f8-02f0-41ae-98bc-cfa99e1a9e99)

Zen Browser:
![grafik](https://github.com/user-attachments/assets/e17423c6-133b-4e5c-a38e-d958651ffb8b)

It's the same website, but on Zen it just doesn't fill this value by default for some reason.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.5

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
Could you send the website's link?

**Comment by RABIGA7OR** [comment]
Unfortunately it's an internal site at work.

However now that I test it again on my personal PC the issue is gone. Might only be an issue on my work computer then for whatever reason.

Will need to check again at my work PC when I am back at work on the 7th of October.

**Comment by RABIGA7OR** [comment]
Actually I was able to test this today. I can't explain it but the issue has been resolved. The issue doesn't appear on my work PC anymore.
