### ISSUE TITLE
Icons in sidebar broken

### ISSUE THREAD

**Issue by EranNL** [zen-browser/desktop#1753]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

So I was trying Zen browser and after some time, I reopened my browser and two things happened:
1. 
<img width="217" alt="image" src="https://github.com/user-attachments/assets/164c0e65-b031-49d0-ad58-06b4064f68b9">
The tabs are gone. With a mod (Minimal sidebar) I removed all icons but these and the history icon. When restarting the browser, both the history icon (in the middle) and the setttings icon (currently a D) were gone. Nothing happens when I press the D, the leftmost button does work. 

2. All hotkeys did not work anymore (cmd + r for refresh, cmd + , for settings, etc).

I tried to re-install the browser completely, and after a re-install the hotkeys work again, but not these tabs. Even without mods (because mods could have broken this) it does not work. 

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.5 

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by clay-risser** [comment]
I'm facing the same issue. I'm also on macOS aarch64.

**Comment by clayrisser** [comment]
I'm facing this exact same issue. I'm also on macOS aarch64.

**Comment by clayrisser** [comment]
Below are some screenshots for more context.
 
<img width="290" alt="Screenshot 2024-10-01 at 3 11 08 PM" src="https://github.com/user-attachments/assets/d6a7fcba-2493-451c-9de2-94554a73868a">
<img width="236" alt="Screenshot 2024-10-01 at 3 11 13 PM" src="https://github.com/user-attachments/assets/964c3d5c-4f96-4718-8200-164e8b5127e9">
<img width="401" alt="Screenshot 2024-10-01 at 3 10 51 PM" src="https://github.com/user-attachments/assets/543ece50-de9b-4719-b7aa-7b8f8be22b0d">
<img width="236" alt="Screenshot 2024-10-01 at 3 10 57 PM" src="https://github.com/user-attachments/assets/05d34e30-2328-4f16-a45f-7c504ed207d8">

**Comment by EranNL** [comment]
Sorry, I feel so stupid. My "issue" is intended behaviour. I think all icons were reset in an update, because the "D" in my screenshot is the name of the workspace ("Default"). The history icon could be added again when clicking "Customize toolbar":

![image](https://github.com/user-attachments/assets/fbb7b28c-efdc-446e-8bb3-cf706f0b3c96)

**Comment by clay-risser** [comment]
I ended up just manually moving things around to the original position.

**Comment by salamijason** [comment]
Heylo, looks like this post was made a while back. Are you still getting this issue? (latest ver a.17 as of this comment)

**Comment by EranNL** [comment]
@salamijason No, it was kinda my mistake. The UI changed without me knowing, which also changed my icons and I thought that was a bug, because nothing happened when I clicked on the D. Turns out I had to use the right mouse button and the D was the first letter of the Default workspace. This issue can be closed, but I think it would be nice to get a heads up when UI changes :)

**Comment by salamijason** [comment]
Totally agreed! For a while now, the dev and contribution team have added sections to the release notes that includes info on ui and theme changes! (Example is from release a18) 
![image](https://github.com/user-attachments/assets/4379ecc9-abe4-4be6-b1d5-5dd89588f083)
