### ISSUE TITLE
Improve PIN Tab Behavior: Reset to Registered URL on Double Click

### ISSUE THREAD

**Issue by TheoD02** [zen-browser/desktop#1754]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

**Description:**

The PIN tab feature in Zen is very useful! However, the current behavior keeps the tab on the current URL, even after navigating away from the initially pinned page. 

### Current Behavior:
- When I pin a tab (e.g., set it to `https://google.fr`), the tab is correctly pinned.
- If I navigate to a different page within the pinned tab (e.g., perform a Google search or go to another website), the PIN feature keeps the tab on the current page instead of resetting to the registered URL when double clicked.

### Expected Behavior:
- After pinning a tab to `https://google.fr`, I would like the following behavior:
  1. Clicking on the pinned tab should load the original, registered URL (`https://google.fr`).
  2. While I can navigate away to other pages within the tab, double-clicking the pinned tab should return it to the base registered URL (similar to how Arc Browser handles this behavior).

This feature would greatly enhance the user experience by allowing easier navigation back to the pinned URL.

### Example:
1. Pin a tab to `https://google.fr`.
2. Navigate away to another page.
3. On clicking the pinned tab, it loads the initial pinned URL (`https://google.fr`), regardless of the current page.
4. If already on the pinned tab, double-clicking returns to the original registered URL.

This would align with how Arc Browser manages pinned tabs and would be an awesome addition to Zen! 

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.5

### What platform are you seeing the problem on?

Windows

### Video

https://github.com/user-attachments/assets/afedd44a-c6e9-414e-b657-76f76cae0e6e

https://github.com/user-attachments/assets/eca6d31d-9719-4edc-afee-ea58c416512d

**Comment by n7itro** [comment]
Related to https://github.com/zen-browser/desktop/discussions/1453

**Comment by mauro-balades** [comment]
^

Also, issues are for bug reports, not enhancements
![image](https://github.com/user-attachments/assets/0a9cb770-137b-468c-9bb2-c5f831d3ff16)

this isnt just a bot detection method
