### ISSUE TITLE
Closing the last tab of a window doesn't close the window

### ISSUE THREAD

**Issue by infiniwave** [zen-browser/desktop#176]
### What happened?

In any window, closing the last tab results in a blank tab appearing, which needs to be closed again, instead of closing the window.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.13

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by SVTA-OP** [comment]
I have the same issue and believed it to be intentional.

**Comment by mauro-balades** [comment]
Fixed for .16!

**Comment by ahmed2m** [comment]
Shouldn't this be an option in the settings or something? it is in Vivaldi. I find it useful that closing all the tabs would just open a new blank tab (or the default new tab) and closing that (using the close tab shortcut) would just re-open the empty default tab and so on and if I wish to close the window or the app I would execute the respective shortcut or click on the UI elements designated to that.

I find giving the choice to the user would just make the browser more flexible. So many people already hate this default behavior from Chrome and the likes and install this extension: https://chromewebstore.google.com/detail/dont-close-window-with-la/dlnpfhfhmkiebpnlllpehlmklgdggbhn?hl=en

**Comment by sarojregmi200** [comment]
@ahmed2m  I believe what you said is absolutely true. I operate gen in a more minimal way so I generally have the top bar and the sidebar hidden and I have found myself closing a tab and closing the entire browser which ofc I have to reopen.

I can understand why some may want this behavior, And due to those conflicting opinions I believe it's good to give a option in the settings to control this behavior. 

> @mauro-balades Sorry to ping you but since this is a closed issue, It is not in your radar I guess. and + the above comment by > ahmed2m is about 3 weeks old.

**Comment by mauro-balades** [comment]
The reason it doesn't close is because it would delete the workspace you are in, as a workspace requires at least 1 tab

**Comment by ludos1978** [comment]
my reason for closing the last tab is that i want the screen space freed and it's pretty much os(x) standard. apps that keep something open should keep that in a menu bar icon. (from my experience)
