### ISSUE TITLE
System-wide Adguard(with Adguard Browser Assistant) not working

### ISSUE THREAD

**Issue by ScathachSkadi** [zen-browser/desktop#1760]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I have downloaded the Adguard browser assistant(legacy mode, not the adblocker, the one that is made to be used with the macOS system-wide program) to use with Zen Browser. The extension detects Adguard is installed, but it does not block any ads. It should work on any type of browser with legacy mode. I am not sure if I am the only one experiencing this, or if there is any way to fix it. If it is not a thing that Zen could fix, I think we should tell Adguard to make Zen supported(like Arc).

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.5 

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by n7itro** [comment]
This is a problem with the Adguard Assistant. I don't expect Adguard to provide support for dated and obsolete software... may I ask why you're using this over their browser extension, the Adguard DNS or uBlock Origin ?

**Comment by ScathachSkadi** [comment]
1. It works on Firefox but not on Zen(which is why I made this post in the first place)
2. I need it so I don't have to install a bunch of userscripts with tampermonkey because system wide adguard is good enough for me and I need tampermonkey to block ads that ublock origin can't. System wide adguard supports having userscripts.
3. Why do I have to install two ad blockers when I have one installed on my system?

**Comment by jhnsmth** [comment]
I also had this issue and resolved it by adding Zen browser to the list of filter applications. You can do it navigating to  Settings -> Network -> General -> Applications..., then press `+` and select `Zen Browser.app` Hope this helps

**Comment by ScathachSkadi** [comment]
Holy shit that worked! Thanks, I completely forgot about it!

**Comment by GollyJer** [comment]
Thanks @jhnsmth!
For those using the newest Adguard app for Windows...
Settings > Network > `List of filtered applications` button. > Add `zen.exe`. 💪
