### ISSUE TITLE
Disable clowsing with last tab

### ISSUE THREAD

**Issue by iuvi7** [zen-browser/desktop#1761]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Hello!

I installed Zen Browser to my mum cuz we like it a lot, but it was take for us around hour to find how to disable it for shutting down after closing last tab

Maybe it possible to make slider to switch it off\on in main settings than use search engine -> read article -> go -> about:config -> set browser.tabs.closeWindowWithLastTab to false\true

It will definetley improve experience and fix this "bug"

Thank you and sorry if we wrote it in a wrong place :)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a5 (64-bit)

### What platform are you seeing the problem on?

Linux, macOS - aarch64, macOS - Intel, Windows

**Comment by iuvi7** [comment]
> [ZEN-1773 Disable clowsing with last tab](https://linear.app/zen-browser/issue/ZEN-1773/disable-clowsing-with-last-tab)

it ask me to create account or log in to read this link\article

**Comment by ZhenyaGoroh** [comment]
> > [ZEN-1773 Disable clowsing with last tab](https://linear.app/zen-browser/issue/ZEN-1773/disable-clowsing-with-last-tab)
> 
> it ask me to create account or log in to read this link\article

I think that this is just a link for developers

**Comment by iuvi7** [comment]
Yes. It is still relevant. + In newest version somewhy empty tab opens when i close last one. Why? Empty memory consumption, sadly :(

**Comment by salamijason** [comment]
It was said before by the dev that closing the last tab shouldn't close the browser and that the new tab being created was intentional. Sorry for the confusion.
