### ISSUE TITLE
Passkeys not working on Linux

### ISSUE THREAD

**Issue by MartinGamesCZ** [zen-browser/desktop#1763]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I have setup a Passkey for my google account. When I login in another browser, I see dialog that says to authenticate using passkey on my phone. I expected that to happen.
![image](https://github.com/user-attachments/assets/206a3829-6363-41a0-bb0a-b1a455e704d6)
![image](https://github.com/user-attachments/assets/16dfeced-1810-4485-a709-3acf6b81b06d)

Instead, I got this:
![image](https://github.com/user-attachments/assets/a709c29d-8c42-4893-b482-05bf9c2affc8)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.5 (64-bit)

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
Duplicate of https://github.com/zen-browser/desktop/issues/437

**Comment by MartinGamesCZ** [comment]
Firefox said If this is working how it should, where can i select the device for authentication? I don't get anything on my phone

**Comment by kwiniarski97** [comment]
It's not duplicate of [#437](https://github.com/zen-browser/desktop/issues/437) as by [your comment](https://github.com/zen-browser/desktop/issues/437#issuecomment-2748304905) @mr-cheffy. That issue is only for macos.

I still stumble across this issue on Fedora 43 and Zen 1.18.2b

**Comment by mr-cheffy** [comment]
I think this one now just falls under Firefox. Does it happen with ff as well?

**Comment by kwiniarski97** [comment]
Yes it does. I have found a flag in `about:config` that seems to fix it.
`security.webauth.webauthn_enable_softtoken`
Maybe it should be enabled by default?

**Comment by mr-cheffy** [comment]
Seems like you can just have one of them enabled:

<img width="1024" height="446" alt="Image" src="https://github.com/user-attachments/assets/bb709e38-b688-4f37-8b70-cb864bb1edb6" />
