### ISSUE TITLE
Can not open local (LAN) IP

### ISSUE THREAD

**Issue by kuspoes** [zen-browser/desktop#1764]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Zen can't open (Unable to connect) local IP in LAN, but Safari/Duckduckgo Browser/Arc Browser/Firefox can open it smoothly.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a5

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by cunc** [comment]
If you are using macOS 15.0 or above, try to check the setting to Local Network in Privacy & Security.

**Comment by kuspoes** [comment]
thanks you

**Comment by EvansMatthew97** [comment]
~The application doesn't show under Local Network for me, so there is nothing to toggle. Is there a specific way to get it to display? Thanks~

Never mind, I restarted my laptop and when I tried again it showed the notification to allow access.

**Comment by nerdyinu** [comment]
is this resolved? zen doesnt show under Local Network for me as @EvansMatthew97 has mentioned. restart doesnt work for me.

**Comment by tata32000** [comment]
I also have the same issue as @nerdyinu, restart does not work for me.

**Comment by futurmat** [comment]
Same problem for me. Any solution for that? Re-installed, re-started the computer, but no notification.
