### ISSUE TITLE
not an issue but feature request.

### ISSUE THREAD

**Issue by rifqilubis** [zen-browser/desktop#1765]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

Why the switch to previous and next tab been deleted?
it was such a good feature. Will it get back?

before the update, i can switch between tabs. 

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.4 (64-bit)

### What platform are you seeing the problem on?

Linux

**Comment by KarimElsayad247** [comment]
Are you talking about the Ctrl + tab shortcut? If so, it was a bug with the previous update that broke shortcuts. please update to 1.0.1-a.5 and check again.

**Comment by mauro-balades** [comment]
![image](https://github.com/user-attachments/assets/3dfc4778-0eee-45bb-a2cb-3d38e46919b9)

sorry but feature requests can be done at the discussions panel, not issues.
