### ISSUE TITLE
Crash when downloading anything

### ISSUE THREAD

**Issue by TobiasRV** [zen-browser/desktop#1769]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When I try to download anything the browser crash
I'm on windows 11 Pro version 23H2

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Version 1.0.1-a.5 (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
Are you sure no any antivirus is performing this operation?

**Comment by TobiasRV** [comment]
When I download it using other browsers I don't have this issue

**Comment by TobiasRV** [comment]
I imagine this is not a very frequent bug because I didn't see any post addressing it, I don't know if there is any log file I can see to have better insight on the problem

**Comment by 5l4y3r-burrito** [comment]
using 1.12.10b i am unable to download the popular mobile game NIKKE on my desktop. download button works instantly on firefox but it is not possible to download with zen browser. the website serves a .wg.intl.exe miniloader that will not show the download beginning until you eventually give up and try to close the browser and it won't close, instead prompting if you want to cancel 30 failed downloads (or how ever many times you clicked download expecting it to show the download starting pop up on the downloads button in zen browser)

after further testing i have discovered it is not zen browser but private browsing, also occurs on firefox. i happened to be using private zen and non private firefox. this post from 5 years ago confirms it: https://support.mozilla.org/en-US/questions/1263810
