### ISSUE TITLE
[Suggestion] Always show context-navigation buttons

### ISSUE THREAD

**Issue by xllifi** [zen-browser/desktop#1774]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

Reload and bookmark buttons are too useful to be absent if either back or forward buttons are disabled. Please consider removing/disabling only disabled buttons.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.5

### What platform are you seeing the problem on?

Windows

**Comment by n7itro** [comment]
How exactly are you disabling the back or forward buttons?

**Comment by xllifi** [comment]
This is seemingly fixed on 1.0-a.17. Probably because is fixed in Firefox as well. (I didn't know such buttons existed on Firefox when writing this report)
