### ISSUE TITLE
[Suggestion] Making addons like Tampermonkey work in the sidepanel

### ISSUE THREAD

**Issue by MannixMD** [zen-browser/desktop#1778]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

Can we make addons like Tampermokey work in the sidepanel. Other addons like ublock, bitwarden and stylus work fine but this one doesn't. Is that a conscious decision by a dev team or just a bug??

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.5

### What platform are you seeing the problem on?

Windows

**Comment by n7itro** [comment]
Tampermonkey works in the web sidepanel for me on `1.0.1-a.5`
![image](https://github.com/user-attachments/assets/ba901bbe-64c4-46e1-9d5b-7a90db917ec3)

**Comment by MannixMD** [comment]
What i meant is that the scripts you can install/add in that addon does not work in the sidepanel pages

**Comment by mauro-balades** [comment]
For feature requests, use discussions, please
