### ISSUE TITLE
Windows 7 os 32 bits 

### ISSUE THREAD

**Issue by trimechee** [zen-browser/desktop#1783]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Hello, thank you for this new amazing awesome fantiastic web browser! 💯 🥇

So, a few weeks ago my laptop broke down and I went back to using my old asus eee pc windows 7 os 32 bits intel atom N2600 cpu, thank God I found several compatible and updated web browsers for windows 7 os because surely there are still millions of solid machines that still use windows 7 os which is lighter than windows 10/11, and I recently discovered Zen-browser which seems very promising exceptional, I went to the Zen site browser check if there is a version for windows 7 os and i see it has 2 versions for windows os : optimized version for modern devices and generic version compatible with older devices and with great hope i click on generic version to download it and install it but unfortunately Zen browser does not work on my windows 7 os 32 bits.....

i was sad and i went my way because there are web browsers based on firefox like firefox esr, r3dfox, luminafox, superfox, mercury-Win7.....

and now I find today this article from a famous French site that speaks of Zen Browser with glowing terms and this article says Zen browser is compatible too with old machines......:

https://www.clubic.com/actualite-538319-zen-browser-le-navigateur-qui-se-sert-de-firefox-pour-rendre-internet-plus -sur-et-plus-style.html

which gave us hope that Zen browser in its future stable version could be compatible with windows 7 os 32 bits, so I would just like to ask a question of hope : will the future stable version of Zen browser be compatible with windows 7 os machines please ?

Thanks a lot :)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Alpha build - 1.0.1-a.5 

### What platform are you seeing the problem on?

Windows

**Comment by trimechee** [comment]
We should make workspace in Linear site to see windows 7 version of Zen  ?

**Comment by greeeen-dev** [comment]
Probably sure the "compatible too with old machines" refers to hardware, not software. Zen Browser uses Firefox 130 as its base, and Firefox 130 [does not support anything below Windows 10](https://www.mozilla.org/en-US/firefox/130.0/system-requirements/).

**Comment by itpropro** [comment]
Windows 7 is neither supported by Microsoft nor by third party vendors anymore and using it is a severe security risk. Zen should not support legacy OS' and thereby binding development resources that are better invested elsewhere.

**Comment by trimechee** [comment]
Yes Mr @itpropro , your words are logical if everyone is rich like you and lives in the West rich by the wealth accumulated by plundering the wealth of the natives, and if everyone is not all students in difficulty or people who are refugees, victims of war .....

yes windows seems secure and requires us to use antivirus, its antimalware service, activate TPM by default, and adds security layer measures that weigh down the laptop as if a student's laptop is that of a company's computer with industrial secrets, and it weighs down the laptop, noisy fan and I noticed it myself on my windows 10 laptop .....

on my windows 10 laptop, I disabled antivirus, antimalware, security settings and I have no virus problem, a secure dns like cira dns, quad9 dns, dns0, we do not click on shady links, unknown programs, and we has no virus, it's been years I have no virus, that's enough with this legend secure os so no virus, recently chrome has had security flaws, recently windows os has had security flaws and there are even old security flaws not resolved, so anti viruses can't always detect recent security flaws and modern os has security flaws ....

now I use my eee pc made in 2012 and it is light, fast boot and I have no virus, and it will be good not to be egocentric  and gorget the  interest of millions people still using windows 7 , This helps attract more users to Zen Browser and keep them loyal when they become rich. google microoft doesn't support windows 7 so this is opportunity to to win users who loves windows 7 , if our grandmother has an old laptop, we want to offer an old laptop to an orphaned child, these people don't have the right to use a recent browser?! so offer them your money a windows 11 laptop, i purposely mentioned several browsers based on firefox and which are compatible with windows 7 os, so if Zen browser team is generous enough to support windows 7 os, then the job is made easier by r3dfox web browser for windows 7 based on the latest version of firefox


I remind you Mr @itpropro  you the rich developer and businessmen that there are millions of people who live on less than a dollar a day, there are charities that distribute old computers, so OS not supported and you want to add also web browser not supported?

your choice that Zen abandon windows 7 risks causing ecological disaster if everyone throws away their old PC, windows 7 abandoned for business reasons to push people to buy new laptops, the pirate is not going to bother developing a virus for old windows 7 machines but develops sophisticated viruses undetectable by your darling modern OS , my windows 7 machine is solid functional, why force us to throw our machine in the trash? we use windows 7 mstly t watch some videos, my windows 7 machine has no fan, it's comfortable, my previous modern laptop broke down with a noisy fan which is an ecological disaster and destroyed my nerves, 

imagine windows 7 machines are infected by a botnet and are used to infect your computer and your company's computers, so modern web browser allows to minimize this risk, r3dfox is developed by a single person, Zen browser is developed by 30 people according to the clubic article, what is the problem if r3dfox cooperates with zen browser for the benefit of millions of people unable to buy a modern laptop?

**Comment by trimechee** [comment]
@greeeen-dev , you are green developer and of course you love to keep ou planet green and avoid ecological disater if people throw ther windows 7 laptops, chromium doesn't support windows 7 but supermium , yandex, catsxp, thorium legacy....browsers stil support windows 7 os , windows vista , xp ....with recent chromium kernel, and r3dfox, luminafox use recent firefox kernel for windows 7 os, and firefox esr for windows 7 will update soon to recent kernel, and mozilla says recently that firefox esr will keep support windows 7 , so there is no problem and good idea to keep planet green that if Zen support windows 7 machines

**Comment by trimechee** [comment]
@itpropro , you are german, imagine the nazis return to power and we see far right fascist parties or people in germany, suppose the usa and russia invade germany like in the years 40s and the german people become poor and unable to buy modern laptops with modern os and are forced to use windows xp, windows 7 os machines , are you going to tell the Zen browser team not to support windows 7 os?

if you tell me it's impossible, then i tell you germany can no longer buy cheap russian gas and energy is VERY VERY expensive IN GERMANY  and the german economy is seriously affected like volwagen which suffers from competition from chinese cars and the nazis came after a serious economic crisis, so if Zen browser supports windows 7 OS, it's for your own interest and the interest of the german people

**Comment by trimechee** [comment]
@itpropro SAYS 3(and their very dated system architectures), my windows 7 machine from year  support HD streaming video , and famous developer says machines from years 1990 are best in productivity from moderne machines bacause modern systemhave  complicated too much the tasks....and developer has  proved that modern windows 10 or windows 11 had trouble distributing tasks across the multiple cores of the cpu and opening a simple windows lag freeze while a single core xp or windows 7 machine was faster than a windows 10 machine, I saw the comparison tests in a famous video tweet from this developer, so let's be modest please, my windows 7 machine may be faster and more reliable than your modern machine with multiple cores and heavy mechanisms and security layers

**Comment by trimechee** [comment]
hein what ?!!! @itpropro , i am reading your bio : "I am Jan-Henrik, a Microsoft Azure MVP" !!

you are a microsoft employee ?! microsoft has abandoned windows 7 users, please let Zen and other softwares help people who have windows 7 os, and tell microsoft to let laptop manufacturers install light linux os distro , entry level machines are too weak to support heavy windows 11 os,  and please tell microsoft to make a simple light os for weak machines, using windows os on a low-power machine affects the prestige of windows, windows has focused on competing with linux and has forgotten apple and its mac os which are microsoft's real competitor on high-end machines.....

a service like ssdp discover can put our security at risk according to the FBI, microsoft should find solutions how to enable and disable ssdp and teach users the dangers of this protocol rather than focusing on making TPM mandatory and encouraging people to migrate to windows 11 which destroyed the performance and speed of my sister's computer

**Comment by greeeen-dev** [comment]
@trimechee Firstly, I don't think you need to bring stuff about fascism and Nazis into this conversation. Secondly, just because my nickname is "Green" doesn't imply I make the greenest choices in life (I try to where I can though), it's just my nickname and nothing more.

> but supermium , yandex, catsxp, thorium legacy....browsers stil support windows 7 os , windows vista , xp ....with recent chromium kernel

This is **Chromium**, not **Firefox**. They are completely different browsers. Just because some Chromium browsers support Windows 7 doesn't mean Firefox browsers will do, because **they run completely different code**.

Zen is based on Firefox, and it would need a complete rewrite if it were to use Chromium as its base instead for this very reason.

> and mozilla says recently that firefox esr will keep support windows 7

This is **115 ESR**, not **128 ESR**. The latter does NOT support Windows 7.

To provide Windows 7 support, the dev team would either need provide a Firefox 115 ESR-based version for Windows 7 users, or spend a lot of time trying to bring Windows 7 support to Firefox 128 ESR or 130's code. Like @itpropro said, it is much better off putting more resources into making Zen better rather than trying to support legacy systems which will probably be affected by some unpatched security vulnerability. Besides, both of my "solutions" I proposed would take way too much development time from fulfilling feature requests and patching bugs.

Either upgrade to a Windows 10-compatible system or install Linux on your system (Fedora or Mint should do).

> and developer has proved that modern windows 10 or windows 11 had trouble distributing tasks across the multiple cores of the cpu and opening a simple windows lag freeze while a single core xp or windows 7 machine was faster than a windows 10 machine

In that case, one can also assume Windows 7 is also plagued by the same problem. You're comparing a single-core Windows 7 system to a multi-core Windows 10/11 system, of course Windows 7 isn't going to struggle with "distributing tasks across the multiple cores" because it only has one core to work with. This comparison proves nothing and should have not been made.

> I saw the comparison tests in a famous video tweet from this developer, so let's be modest please, my windows 7 machine may be faster and more reliable than your modern machine with multiple cores and heavy mechanisms and security layers

You cannot rely on social media like Twitter/X as your primary source of information. Before making such claims, please do actual research on reputable resources instead of saying something is factual because you found it on social media. In almost all cases, a system running Windows 10 WILL outperform a system with less resources running Windows 7.

> please tell microsoft to make a simple light os for weak machines

"Microsoft Azure MVP" ≠ "Microsoft Employee".

An MVP is a person that's recognized for their skills, experience, etc. and is NOT an employee unless they explicitly state that they are. MVPs do NOT have any control over what Microsoft does and what Microsoft focuses on.



TL;DR: Time is better spent working on actual features instead of supporting an unsafe OS. Stop making completely illogical claims and either use Linux or upgrade your system.

**Comment by K4sum1** [comment]
They're not going to do it

![image](https://github.com/user-attachments/assets/dec177aa-1f65-4c2a-8fd9-aad624278635)

**Comment by mauro-balades** [comment]
Wtf is going on

**Comment by greeeen-dev** [comment]
dont ask me

**Comment by mauro-balades** [comment]
@trimechee what are you on haha.

If you want to use zen, dont use an OS that has been deprecated for an insane amount of years.

Also, yeah. I secretly work at mozilla and all of this is just to get specifically *your* information.

**Comment by greeeen-dev** [comment]
> Also, yeah. I secretly work at mozilla and all of this is just to get specifically _your_ information.

crazy 🤯🤯🤯

**Comment by mauro-balades** [comment]
crazy how crazy people can do crazy stuff

**Comment by n7itro** [comment]
https://www.nimh.nih.gov/health/statistics/schizophrenia

**Comment by itpropro** [comment]
> @itpropro , you are german, imagine the nazis return to power and we see far right fascist parties or people in germany, suppose the usa and russia invade germany like in the years 40s and the german people become poor and unable to buy modern laptops with modern os and are forced to use windows xp, windows 7 os machines , are you going to tell the Zen browser team not to support windows 7 os?
> 
> if you tell me it's impossible, then i tell you germany can no longer buy cheap russian gas and energy is VERY VERY expensive IN GERMANY and the german economy is seriously affected like volwagen which suffers from competition from chinese cars and the nazis came after a serious economic crisis, so if Zen browser supports windows 7 OS, it's for your own interest and the interest of the german people



> > Also, yeah. I secretly work at mozilla and all of this is just to get specifically _your_ information.
> 
> crazy 🤯🤯🤯

What happened here? Thanks for trying to reason with this person, but I don't think it's possible.
I only stated the obvious fact, that the Zen team is very small and has limited resources and should focus on their core product instead of supporting legacy systems and now I am a Nazi suddenly...
Sometimes I can't believe what people drag to technical conversations about a technologies and programs, especially as we all want to support the project (at least that's what I thought).
And no, I am neither working for Microsoft, nor am I a Nazi, couldn't be further away from that wtf...

**Comment by n7itro** [comment]
@trimechee you along with the people of Germany should switch to Linux if you wish to use Zen Browser on older devices. I hope this resolves your issue!

**Comment by itpropro** [comment]
@mauro-balades, can you please lock this thread, we can be sure that there is nothing productive coming out of it.

**Comment by ProbablyM-S** [comment]
This is hilarious!

**Comment by trimechee** [comment]
@mauro-balades , this is bug, generic version says it is compatible with old devices and my device is old and Zen doesn't work in my laptop , @itpropro , i didn't say you are nazi ?!! i said imagine because of economic crises in germany, extrems political party neo nazy comes back = war.....

clubic say Zen team has 30 persons, if you say right  Zen team is very small and has limited resources, so i remember r3dfox developer is alone, supermium browser developer is alone and they support windows 7 os , Zen team is generous

**Comment by trimechee** [comment]
Mr @K4sum1 , i open tis issue thinking of you, the great R3dfox is enough but i said to myself maybe a big team like Zen can help you keep the support for windows 7 and so you will have less workload, tests, bugs to fix.....

well it doesn't matter, R3dfox and supermium and catsxp are largely enough for our needs on windows 7 os, thanks again for your generosity in making a windows 7 version that even the behemoths and rich microsoft and google refused to do :) even mozilla does not use the latest firefox kernel for windows 7, r3dfox is really exceptional .....

@itpropro  here is the interest of Zen for windows 7 OS: supermium is compatible with windows 7 and keeps the manifest v2 which is rare, Zen can make a windows 7 manifest v2 legacy version because mozilla has not certified 100% that it will keep the manifest v2

**Comment by trimechee** [comment]
@mauro-balades , you guarantee me that i will not have drivers problems with linux distro? i can use microsoft word necessary for my studies in linux distro ? sorry but  i will not uninstall my original windows 7 os for a distro that may not support my old hardware, and mozilla supports windows 7 with firefox esr and mozilla recently made the decision to extend the support of windows 7 os with firefox esr, you oppose the decision of your employer Mozilla?

**Comment by mauro-balades** [comment]
Hi, employee from Mozilla here.

Firefox ESR in windows 7 is extremely unsafe, and it's also using a very old version of Firefox.

My recommendation as a Mozilla employee AND a Microsoft secret agent? Use a better pc. You can find really cheap PCs out there that have windows 10

**Comment by n7itro** [comment]
The developer is being very generous by not supporting Windows 7, as they are reducing the risk of malware on your device

**Comment by trimechee** [comment]
@mauro-balades many old machines are better than modern machines, my modern laptop broke down while my old eee pc from 2012 that I used a lot did not break down, and a scientific test showed that a single core windows xp or windows 7 machine is faster than a modern multi core machine because windows modern os has trouble managing the many
multi cores to open a simple window, let's respect the "OS that has been deprecated for an insane amount of years."

I don't have any viruses on my Windows 7 OS, unlike modern machines, Intel has released some amazing new CPUs, but Intel acknowledged problems with high-end CPUs in the summer, AMD is looking at all this and may compete with Intel's new formidable CPUs by lowering prices or with new models, I can't buy a laptop right now, I have to wait for the outcome of the battle between Intel and AMD, Intel is having financial difficulties, I need to know if Intel will be able to withstand the crisis or not before buying an Intel laptop.....

Haha, money question? i am student, if i have money, i will buy new modern laptop, but if you support windows 7, maybe you will have donations lol, or a windows 7 user will remember that you supported windows 7 and when he becomes rich, he will give you a nice gift and a lot of money, you never know lol

firefox kernel or firefox esr is old but secure, ther is no doubt, mozilla does not joke with corporate security, it says firefox esr is more stable than classic firefox, famous floorp, waterfox use firefox esr

catsxp, supermium, r3dfox, yandex, thorium legacy ...support windows 7, why should i give you money and not them lol? are you not rich enough? you are a developer, i guess you have a big salary, would you like to buy a ferrari  ?

**Comment by mauro-balades** [comment]
Whoever told you ESR is more secure than latest is living a lie.

This is getting stupid now
