### ISSUE TITLE
Can't load localhost:3000

### ISSUE THREAD

**Issue by Xe** [zen-browser/desktop#1787]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I tried to load http://localhost:3000 to develop a next.js app and it just loads infinitely. It loads fine in Chrome.

I can reproduce this on Firefox.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.5

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by mauro-balades** [comment]
I can't really do anything with this information... All I can say is, check the logs to see for any errors or try removing cache...
