### ISSUE TITLE
Sidebar information message improperly displayed

### ISSUE THREAD

**Issue by infiniwave** [zen-browser/desktop#179]
### What happened?

When the sidebar is collapsed, any information messages that usually pop up at the top of the page are squished in the sidebar.
![image](https://github.com/user-attachments/assets/4318beda-8931-40a3-a9a4-73f7fc5cfde1)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.13

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by infiniwave** [comment]
Related issue: The page extends past the bottom of the window briefly when switching to a window that has an information message.

https://github.com/user-attachments/assets/6da6d0d8-9c74-4a09-ad24-3f6365fa0cf3

**Comment by mauro-balades** [comment]
This should be fixed for version 16
