### ISSUE TITLE
Add new tab cant be placed under tab

### ISSUE THREAD

**Issue by NaufalF22** [zen-browser/desktop#1790]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

I want to place new tab like this 
![browser-4](https://github.com/user-attachments/assets/8fec694e-77b8-484a-be99-9906325793d6)
But somehow my new tab button just straight to the botton like this
![image](https://github.com/user-attachments/assets/7b5ada13-e99c-4d07-bf8f-640751888429)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.5 (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by JoshCodeStuff** [comment]
I second this. Can we have the option to move the new tab button back under the tabs instead of the bottom? This is incredibly annoying.

**Comment by abdo0nasser** [comment]
up

**Comment by JoshCodeStuff** [comment]
This has been fixed in the latest update. I believe it can be closed for now.
