### ISSUE TITLE
Container tab indicator for default container being shown when tabs dragged between windows

### ISSUE THREAD

**Issue by sjclayton** [zen-browser/desktop#1792]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When dragging a tab between two windows, both with the same workspace currently active, once the tab is moved to the second window, it is displaying the indicator for the workspaces default container, enough though the workspace it moved from is the same as the workspace it got moved to. 

Before moving the tab from the original window it does not have an indicator for the default container type. I do have the `Hide default container indicator` option enabled in settings.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.5

### What platform are you seeing the problem on?

Linux

**Comment by sjclayton** [comment]
Still an issue as of 1.0.1-a.12 (haven't checked a.14 yet)

**Comment by salamijason** [comment]
Hey! Thanks for the bug report. Could you provide a screen recording of the issue you're getting? would help with us trying to verify what's happening. Thank you!

**Comment by salamijason** [comment]
No response in 3 days, will be closing this issue. Please reopen if you are still facing this issue.

**Comment by rsenna** [comment]
Leaving this here because _I keep forgetting it after reinstalling Zen_, and it's **surprisingly** hard to find again:

> ⚠️ Attention
>
> If you want to show the current "Firefox Multi-Account Containers" name in the URL bar, as Zen originally did by default:
> 1. Go to `about:config`
> 2. Set `zen.urlbar.show-contextual-id` to **`true`**
