### ISSUE TITLE
Zen follows system color theme instead of chosen

### ISSUE THREAD

**Issue by kzhe2059** [zen-browser/desktop#1798]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![image](https://github.com/user-attachments/assets/6adb3ec8-fa73-4fb7-9b94-fdb539b11e93)
After selecting blue color theme, the accent colors are still orange, based on the system accent color. Firefox seems to always use blue.

This is on GNOME, Fedora

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.5 (64-bit)

### What platform are you seeing the problem on?

Linux

**Comment by salamijason** [comment]
Are you still getting this bug on 1.0.1-a.14? Could you please try again on the latest ver and let me know how it goes?

**Comment by mr-cheffy** [comment]
Could you please try disabling it with turning `widget.non-native-theme.use-theme-accent` to false in about:config? Thanks

**Comment by salamijason** [comment]
No response in a week. Will be closing this issue. Please reopen if you are still facing the issue.
