### ISSUE TITLE
Tab bar: misaligned icons and hover background

### ISSUE THREAD

**Issue by tomlmbl** [zen-browser/desktop#180]
### What happened?

<img width="59" alt="Screenshot 2024-08-07 at 16 52 17" src="https://github.com/user-attachments/assets/11710301-f3fc-465b-9d19-45995e1956a4">

<img width="181" alt="Screenshot 2024-08-07 at 16 54 41" src="https://github.com/user-attachments/assets/b746d6f2-f2af-40af-954d-0c6a9ca84c9e">

Misaligned elements with the latest update

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.14

### Severity impact

Low

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by mauro-balades** [comment]
Fixed with https://github.com/zen-browser/desktop/commit/246a6d60dad1874b17e634f8844d88c154f227ac, thanks!
