### ISSUE TITLE
Randomly entered auto hide

### ISSUE THREAD

**Issue by CrossScarDev** [zen-browser/desktop#1803]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I swapped to another workspace and when I swapped back to the one with zen in it my url bar and tab bar were missing. I then realized that I could see them when hovering over the edge of the window but this is really annoying when needing to quickly navigate tabs.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Mozilla Zen 1.0.1-a.2

### What platform are you seeing the problem on?

Linux

**Comment by onthejobtraining** [comment]
Update to the latest version ?

**Comment by CrossScarDev** [comment]
ohh I somehow entered compact mode. closing.
