### ISSUE TITLE
Website download for macOS (Apple Silicon) is not working

### ISSUE THREAD

**Issue by rosmur** [zen-browser/desktop#1806]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Download speed is always very slow and seems to stall/fail before completing

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

latest

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by salamijason** [comment]
I believe all macOS downloads are fine now. If you do have more issues, please direct them to the [website repo](https://github.com/zen-browser/www) or send us a message on the discord server. Thank you!
