### ISSUE TITLE
zen.view.sidebar-expanded.max-width doesn't work

### ISSUE THREAD

**Issue by Axenide** [zen-browser/desktop#1807]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I made some CSS to make the max-width of the Zen Sidebar wider, and suggested adding it to the Theme Store, but I was told that Zen has `zen.view.sidebar-expanded.max-width` in `about:config`.

The thing is that I tried modifying it and nothing happens, even after restarting the browser. It's value says `400` but clearly the maximum by default is `720px`.

I tried changing it and it doesn't work, am I doing something wrong or is it really a bug?

Thanks!

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Mozilla Zen 1.0.1-a.3

### What platform are you seeing the problem on?

Linux

**Comment by n7itro** [comment]
It works for me on the latest stable version (a.7)

**Comment by Axenide** [comment]
> It works for me on the latest stable version (a.7)

I just tested, I guess this was a confusion. I mean the Zen Sidebar, the web panels.

**Comment by mr-cheffy** [comment]
It's referring to the tab's sidebar, not the website panel. Sorry for the confusion
