### ISSUE TITLE
Zen modifications are not showing

### ISSUE THREAD

**Issue by Kapciusek** [zen-browser/desktop#1808]
### Captchas

- [x] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I installed a few modifications and clicked "check for updates" and the modifications disappeared from the list. When I go to the store and go to the modification I had installed, I can still uninstall and install it as if the zen modifications tab itself did not show the installed modifications.

screen of zen modifications:
![Zrzut ekranu 2024-09-30 020827](https://github.com/user-attachments/assets/3ede24e1-e1c6-42c4-93ad-448a79699814)

screen of example modification:
![{54870623-A70B-40C3-9440-6074D2004BF5}](https://github.com/user-attachments/assets/8a1636c3-6aaa-4590-86bf-303f11a005ae)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.5

### What platform are you seeing the problem on?

Windows

**Comment by 51ddh4r7h-A** [comment]
I got the same issue here on fedora 40, to get around this go to `about:profiles` and change to default profile instead of the alpha and it seems to work.

**Comment by adam-adrian** [comment]
Uninstall \[Floating Findbar\](https://zen-browser.app/themes/4ce2b68c-84f1-4296-b145-4e590ad7a19e)
