### ISSUE TITLE
Blank space when closing tabs

### ISSUE THREAD

**Issue by tomlmbl** [zen-browser/desktop#181]
### What happened?

<img width="521" alt="Screenshot 2024-08-07 at 16 56 50" src="https://github.com/user-attachments/assets/95c251f6-4761-452d-b380-a01812b90496">

Tabs aren't stacking on top properly anymore

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.14

### Severity impact

Low

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by mauro-balades** [comment]
Hmm this is weird, are you sure you dont have any userChrome.css enabled?

**Comment by mauro-balades** [comment]
Fixed with https://github.com/zen-browser/desktop/commit/d3287ce216ec52b7a4201a9c929fb8f283766453 thanks!
