### ISSUE TITLE
Updating to 1.0.1-a.6 cleared all tabs (Including pinned ones)

### ISSUE THREAD

**Issue by elcharitas** [zen-browser/desktop#1812]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

It's weird, I updated and restarted my browser and just like that all my tabs disappeared.

![Screenshot 2024-09-30 at 08 06 59](https://github.com/user-attachments/assets/ab0e2a6e-511b-408e-a457-ecc15e7c0eb3)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.6

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by onthejobtraining** [comment]
Go to history-recently closed windows. Can you find your lost window there?

**Comment by elcharitas** [comment]
> Go to history-recently closed windows. Can you find your lost window there?

You're right, it is there 🤔

**Comment by elcharitas** [comment]
Any particular reason why pinned tabs do not get pinned across all windows?

**Comment by onthejobtraining** [comment]
They shouldn't be, that's just how it's designed. Workspaces are just like separate windows afterall.

**Comment by RayZ3R0** [comment]
Seems to be fixed. Closing. Pinned tabs persisting across all workspaces is not planned for now

**Comment by SalahAdDin** [comment]
It is happening today with the latest version!!!

**Comment by Gamedirection** [comment]
I seem to loose all my tabs once a week or so, even pinned tabs. Is there a tool or way I can restore my tabs more easily?

**Comment by SalahAdDin** [comment]
> I seem to loose all my tabs once a week or so, even pinned tabs. Is there a tool or way I can restore my tabs more easily?

Not yet.
