### ISSUE TITLE
The default keyboard shortcuts for switching workspaces and toggle to compact mode aren't working

### ISSUE THREAD

**Issue by LanceStark** [zen-browser/desktop#1813]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The following shortcuts do not seem to work on MacOS:
- Switching from one workspace to another
- Collapsing the panel to enter compact mode or to open it

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

14.5

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by polskiTran** [comment]
I also have this issue on Mac. So close from being an Arc replacement...

**Comment by LeMoonStar** [comment]
Hey! This seems to be a duplicate of #1629 and was fixed in version [1.0.1-a.10](https://zen-browser.app/release-notes#1.0.1-a.10) (October 15). Feel free to try again in a current version of Zen!

**Comment by k-soomro** [comment]
I still have this issue on  Mac Sonoma. My workspace switching shortcuts don't work. I have Zen 1.7.2b.

EDIT: The previous workspace shortcut works. The next workspace shortcut doesn't work. Pressing `CMD+OPT+E` opens the Network developer console.
