### ISSUE TITLE
Back to tab from picture-in-picture opens the tab in current workspace instead of the original tabs workspace

### ISSUE THREAD

**Issue by RABINGG** [zen-browser/desktop#1815]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### Steps to reproduce:
1. Open a video in a workspace and get into pip.
2. Change to another workspace
3. Now click on back to tab in pip

### Expected:
Video should open in the videos workspace

### Reality:
Opens in the current workspace. Also sometimes this bugs out the sidebar (I have enabled expand on hover) to stay expanded but floating. Restarting solves this

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.6 (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by salamijason** [comment]
Could not replicate on latest windows version of the browser (1.0.1-a.16 as of this comment), are you still having this issue?

**Comment by salamijason** [comment]
Have not gotten a response in three days and will mark this as completed. If you still do get this issue, please reopen this issue.
