### ISSUE TITLE
Missing tab on vertical tab

### ISSUE THREAD

**Issue by an4k1n** [zen-browser/desktop#182]
### What happened?

Open new tab from Extension option, close it using X button on Vertical tab. Try to open again, it is not appear on the vertical tab, but appear and can be access using List All tabs

![Screenshot 2024-08-07 235701](https://github.com/user-attachments/assets/6a421b15-706c-4ae8-b160-4322d87aa5c3)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

a14

### Severity impact

Medium

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
This should be fixed now
