### ISSUE TITLE
The vertical tab bar is gone

### ISSUE THREAD

**Issue by litaniecontrelapeur** [zen-browser/desktop#1820]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The vertical tab has disappeared after updating to a6 version

![image](https://github.com/user-attachments/assets/54029caa-8a4a-4dc2-91f5-2a2e409d04bd)

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.6

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
I've done a quick fix, it will be released in like 1 hour... Sorry about that!
