### ISSUE TITLE
Workspaces with to names that are to long can't be edited using the GUI

### ISSUE THREAD

**Issue by Tygo-van-den-Hurk** [zen-browser/desktop#1821]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When a name is too long, then the triple-dot icon isn't showing up. See this example:

![github-issue-zen-browser](https://github.com/user-attachments/assets/14bf7dcd-7c60-473c-9bf8-6864275508f7)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.5 (64-bit)

### What platform are you seeing the problem on?

Linux

**Comment by RayZ3R0** [comment]
@Tygo-van-den-Hurk Does this still happen on latest version? (a.14 as of this comment)

**Comment by Tygo-van-den-Hurk** [comment]
No it doesn’t! Great! I guess I’ll close the issue then. I’m sorry for wasting your time.
