### ISSUE TITLE
Active tab not restored when Zen is relaunched

### ISSUE THREAD

**Issue by sjclayton** [zen-browser/desktop#1822]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

If the active tab is any other tab than the first tab, and you close Zen when re-opening the tab that gets restored is always the next tab (the one below) and not the tab that was active when Zen was exited.

**Expected Result:**

The tab that was active when Zen is closed is still active when Zen is re-opened.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.6

### What platform are you seeing the problem on?

Linux

**Comment by sadaisystems** [comment]
Same!

**Comment by sjclayton** [comment]
Still an issue as of 1.0.1-a.8

**Comment by RayZ3R0** [comment]
Does this still happen on a.14 or above?

**Comment by sjclayton** [comment]
@RayZ3R0 

Yes, the behaviour still happens on a.14

**Comment by RayZ3R0** [comment]
I have tried reproducing this on linux mint, didn't get this issue. Can you do a screen recording and send please

**Comment by salamijason** [comment]
No response in 2 weeks. For the sake of keeping the roadmap clean, I'll be closing this issue but please reopen if you still get this issue. Thank you.
