### ISSUE TITLE
Spotify player doesn't work properly

### ISSUE THREAD

**Issue by kralion** [zen-browser/desktop#1826]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I want to listen music on spotify and it doesn't work, it autoplays but kinda buggy, Its better to you guys to **try by yourself**

I am on windows 11, with UBlockOrigin extension.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.7 

### What platform are you seeing the problem on?

Windows

**Comment by NOCanoa** [comment]
https://docs.zen-browser.app/faq#why-cant-zen-browser-play-drm-protected-content
