### ISSUE TITLE
Alignment/padding issues and shifting elements

### ISSUE THREAD

**Issue by chlumpchatkupt** [zen-browser/desktop#1829]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### Issue
Various UI elements are misaligned or have uneven padding. The change in alignment/padding after tabs are expanded or the URL bar is selected causes UI elements (e.g., tabs, URL text, etc.) to shift.

### Observed behavior
![zen 1](https://github.com/user-attachments/assets/e31d598c-f50a-4a6e-9607-3e55332b14b2)
- Tab icon is not horizontally centered.
- URL bar is not vertically centered.
- After the tabs are expanded, padding on top is added, and some UI elements are vertically or horizontally shifted.

<img width="715" alt="zen 2" src="https://github.com/user-attachments/assets/a9a90ee8-82cf-484c-af34-cb07274e8f94">
- After the URL bar is selected, padding is added to the top and bottom of the URL bar, causing the text to shift downward.

### Expected behavior
Proper alignment and no shifting of UI elements.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.7

### What platform are you seeing the problem on?

macOS - Intel

**Comment by RayZ3R0** [comment]
Were some these fixed on latest version? (a.14 as of this comment)

**Comment by kwilcz** [comment]
Only partially, but still the expanding sidebar is misaligned:
![zen_BfRdRSbFbq](https://github.com/user-attachments/assets/b66ce194-0e52-4afe-be8e-889b3635c2ed)
![image](https://github.com/user-attachments/assets/5d36d897-eab9-4b9d-8046-f00c3ee7114c)
