### ISSUE TITLE
Per workspace bookmarks

### ISSUE THREAD

**Issue by ConercaoAlpha** [zen-browser/desktop#183]
### What feature would you like to see?

I'm not sure if this is possible, but if you could have a different set of bookmarks per workspace that would be great.

For example, on workspace 1 you'd have Bookmark A, Bookmark B etc on the bookmark bar. On Workspace2, you wouldn't have Bookmarks A and B, but C, D etc etc

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/885

 ~ This is an automatic operation to better enhancements requests organization.
