### ISSUE TITLE
"Маkе the toolbar themed with the accent color" option does nothing

### ISSUE THREAD

**Issue by pakhrom** [zen-browser/desktop#1834]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.

#### "Маkе the toolbar themed with the accent color" option in "Look and Feel" settings does nothing since 1.0.1-a6. 
After enabling the option the toolbar and the tab bar still use the default gray colors instead of the themed ones.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a6

### What platform are you seeing the problem on?

Windows

**Comment by jlnalber** [comment]
I have the same issue and now the browser looks... A bit off...

**Comment by alejandrolacasa** [comment]
Same issue here! Still present in 1.0.1-a8. 😞
