### ISSUE TITLE
Cannot disable tab unloader

### ISSUE THREAD

**Issue by sjclayton** [zen-browser/desktop#1835]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Despite the checkbox for the tab unloader not being checked, tabs are still being unloaded according to the time that is set. 

![2024-10-01_01-01](https://github.com/user-attachments/assets/3b74b2de-a5c2-494d-9a0f-6149f2ec9aa5)

**Expected Result:**

Tab unloader does not unload tabs if it is disabled.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.7

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
I've looked into this and fixed it for the next release, thanks!

Try disabling it and restarting in the meantime...
