### ISSUE TITLE
Side Panel websites unable to ask for permissions

### ISSUE THREAD

**Issue by gotham13** [zen-browser/desktop#1838]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Unable to give permissions to websites added in side panel . /

![Screenshot 2024-10-01 at 12 12 51 PM](https://github.com/user-attachments/assets/e6c89636-903a-4a60-91d9-3b29929a5040)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.7 (64-bit)

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by salamijason** [comment]
dup of this issue, will be moving there https://github.com/zen-browser/desktop/issues/2051
