### ISSUE TITLE
Top Windows control buttons overlap with the top bar buttons when Zen is resize to a lower width while title bar is turn off.

### ISSUE THREAD

**Issue by IAmJafeth** [zen-browser/desktop#184]
### What happened?

When resizing Zen's windows to a lower width there is a point were the Window Manager buttons  ![image](https://github.com/user-attachments/assets/2ebcb828-25a9-488d-b2ab-d074f3e0f871) overlap with other Top Bar icons.

I attempted to recreate the issue on Firefox, however, Firefox's Window Manager buttons are not on the same row as the rest of the icons on the top bar due to horizontal tabs.

### Zen's Top Bar
![image](https://github.com/user-attachments/assets/e2970442-f449-4900-a3ef-8cb96cb3ae14)
[Screencast from 2024-08-07 17-06-33.webm](https://github.com/user-attachments/assets/1e0343a3-f46c-4fb8-b8f9-961a30b36923)

### Firefox's Top Bar
![image](https://github.com/user-attachments/assets/621919bf-b0ef-41e4-ad95-41f3377adc8d)
[Screencast from 2024-08-07 17-06-14.webm](https://github.com/user-attachments/assets/c3e6f0bf-25bf-481e-ad97-c090238fdfb8)

### Temporary Fix
I see that enabling the **Title Bar** (bottom left on the image below), in the "Customize Tool Bar" section fixes this error, as the Window Manager buttons are displaced to the OS Native Title Bar
![image](https://github.com/user-attachments/assets/04ccc49f-50a1-4055-858f-d691b948750c)
![image](https://github.com/user-attachments/assets/5b6b94b0-a2d6-428c-ba10-48a7d8c0f22c)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.15

### Severity impact

Low

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
Woah, this is trully a hard one to fix 😥

**Comment by NOCanoa** [comment]
is this still a thing?

**Comment by mauro-balades** [comment]
yeah
