### ISSUE TITLE
Current tab breaks when closing Picture in Picture from other workplace

### ISSUE THREAD

**Issue by capsey** [zen-browser/desktop#1840]
### Captchas

- [X] I have read the instructions.
- [ ] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I opened a Picture in Picture of a YouTube video, switched to another workspace and then clicked on "Back to tab" button on the PiP window. Instead of current workspace changing to the one the YouTube tab is in, the current tab in the other workspace suddenly changed to the YouTube tab with current tab disappearing. It goes back to normal when manually changing the workspace.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.6

### What platform are you seeing the problem on?

Windows

**Comment by salamijason** [comment]
Could not replicate on the latest version on windows (a.15 as of this comment), are you still getting this issue?

**Comment by salamijason** [comment]
No response in 3 days, will be closing this issue. Please reopen if you are still facing this issue.

**Comment by capsey** [comment]
Sorry for late response. Yes, I no longer experience the issue, must have been fixed as some point between updates. Thank you
