### ISSUE TITLE
small bug in the UI

### ISSUE THREAD

**Issue by Gautierpicon** [zen-browser/desktop#1841]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Hello, I just found this little bug between the icons that are not aligned the same: 
<img width="294" alt="image" src="https://github.com/user-attachments/assets/56d4521a-c545-4ebc-9cbf-51c8e09691d0">
<img width="655" alt="image" src="https://github.com/user-attachments/assets/64b6e8d9-5201-4a08-8a95-4e951f4d45d4">
I'm not an expert, so I'm not sure what I'm saying, but it seems to me that the ‘normal’ icons are slightly lower than the workspace icon (sorry, my icons are far away, so it's not obvious, but maybe you can see better on the 2nd photo).

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.7

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by salamijason** [comment]
Hey there have been lots of updates to workspace icons recently. are you still getting this issue?

**Comment by GautierPicon** [comment]
no, it seems to have been rectified 👍
