### ISSUE TITLE
Widevine is not supported, I cant watch shows.

### ISSUE THREAD

**Issue by DarkmayGOD** [zen-browser/desktop#1842]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Hello, why the browser does not have Widevine? I have DRM turned on, and still can't watch shows. I even tried to run console script, and still Widevine is not supported.

Script: 

navigator.requestMediaKeySystemAccess("com.widevine.alpha", [{
  "initDataTypes": ["cenc"],
  "audioCapabilities": [{ "contentType": "audio/mp4; codecs=\"mp4a.40.2\"" }],
  "videoCapabilities": [{ "contentType": "video/mp4; codecs=\"avc1.42E01E\"" }]
}]).then(function() { console.log("Widevine is supported"); }).catch(function() { console.log("Widevine is not supported"); });

(idk the version of the browser, if you can tell where to get it, I couldn't find it.)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1

### What platform are you seeing the problem on?

Windows

**Comment by ThatOneUnoriginal** [comment]
As said in the [FAQ](https://docs.zen-browser.app/faq) of the browser, acquiring such a license requires the payment of large fees (at least $5,000). This means that DRM-protected media unfortunately cannot be played in Zen Browser for the foreseeable future. Use a browser that has a Widevine license, such as [Mozilla Firefox](https://www.mozilla.org/firefox/), when streaming DRM-protected content.

**Comment by DarkmayGOD** [comment]
Oh okay, thank you!
