### ISSUE TITLE
Websites can suppress and replace every shortcut

### ISSUE THREAD

**Issue by Sajito** [zen-browser/desktop#1843]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Currently it's possible for a website to trap and suppress each and every keypress, like <kbd>ctrl</kbd>+<kbd>w</kbd> or <kbd>ctrl</kbd>+<kbd>n</kbd>.

I couldn't find a a list of shortcuts, that a website should be allowed to trap, but there are some shortcuts, which I'd expect to always work, like:

- Open new window
- Open new private window
- Open new tab
- Close tab

Not an exhaustive list, but at least some.

<details>

<summary>Simply use this html to reproduce.</summary>

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <div>
      You pressed:
      <span id="key_output"></span>
    </div>
    <script>
      const keys = new Set();

      document.addEventListener("keydown", (e) => {
        e.preventDefault();
        keys.add(e.key);
        updateKeys();
      });

      document.addEventListener("keyup", (e) => {
        e.preventDefault();
        keys.delete(e.key);
        updateKeys();
      });

      function updateKeys() {
        key_output.innerHTML = Array.from(keys)
          .map((key) => `<kbd>${key}</kbd>`)
          .join(" + ");
      }
    </script>
  </body>
</html>
```

</details>

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.7

### What platform are you seeing the problem on?

Linux

**Comment by nullXer0** [comment]
I am also experiencing this issue.
Platform: Fedora 40
Version: 1.0.1-a.7

**Comment by Sajito** [comment]
Rephrased the title, to better reflect the impact of this. A website really should not be able to prevent a user from opening new tabs or windows.

Two examples with the default shortcut for opening a new private window (that is <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>p</kbd>).
- Using the shortcut while having the comment-field here on github focused causes a switch to "Preview" instead of opening a private window.
- In linear, when viewing an issue, the shortcut is overridden and opens a command palette instead.

So far this is only inconvenient, but I can think of various ways to abuse this in malicious ways.

**Comment by Sajito** [comment]
I have never used the features to set or change Keyboard Shortcuts in zen browser, but apparently this issue is fixed by going into Settings -> Keboard Shortcuts and resetting to default.
Closing here.
