### ISSUE TITLE
Minor CSS issue for workspaces on small screens

### ISSUE THREAD

**Issue by clementpoiret** [zen-browser/desktop#1846]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![2024-10-01-At-05h42m26s](https://github.com/user-attachments/assets/ba3b3ae6-4281-4608-b8f0-1dad00a63bd6)

I tried searching if this has been reported before, I didn't find it. On my desktop computer, no issue. Same configuration on my laptop produces a small overlap. Minor issue :) 

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.7

### What platform are you seeing the problem on?

Linux

**Comment by salamijason** [comment]
Hey there has been a lot of updates to workspaces recently. Are you still getting the same issue on the latest ver? 1.0.1-a.14
