### ISSUE TITLE
Closing a tab leaves a blank space

### ISSUE THREAD

**Issue by jimfr** [zen-browser/desktop#185]
### What happened?

Close the second tab from the bottom.  Instead of "Daily American" moving up, a blank space remains.  This is immediately after a Zen restart, if that helps.
<img width="181" alt="image" src="https://github.com/user-attachments/assets/6ca3f425-ec94-401a-b0d6-9bd9927a9ffc">

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

a.15

### Severity impact

Low

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by jimfr** [comment]
"About Zen" says a.14, but I downloaded and installed a.15

**Comment by NOCanoa** [comment]
from where did you install it?
a.15 is still building will be out 3min lol

**Comment by jimfr** [comment]
from here: Zen Browser (zen-browser.app)
<https://www.zen-browser.app/release-notes>

[image: image.png]

**Comment by NOCanoa** [comment]
if you now go to about zen u can update to a.15
the release notes were publishes wile waiting for the build to complete

**Comment by jimfr** [comment]
OK, thanks.  I'll make sure to check About Zen next time.

**Comment by jimfr** [comment]
Fixed in (the real) a.15 :)
