### ISSUE TITLE
When setting shortcuts, there's an error with Splitview-related shortcuts.

### ISSUE THREAD

**Issue by red-crate** [zen-browser/desktop#1856]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

For example, I set Ctrl+F6 to Ctrl+F9 to match shortcuts like those in Vivaldi.
After that, the shortcuts work correctly, but when I reopen the settings screen, it shows completely different shortcuts assigned.
The shortcuts themselves still function as I set them.

I've attached a video link to help understand the issue.

https://youtu.be/W375tF6LYXM

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.7

### What platform are you seeing the problem on?

Windows

**Comment by sjclayton** [comment]
Since you said the shortcuts you assigned still work..

If you refresh the keyboard shortcuts page, do the shortcuts properly show up then?

**Comment by red-crate** [comment]
> Since you said the shortcuts you assigned still work..
> 
> If you refresh the keyboard shortcuts page, do the shortcuts properly show up then?

Yes.
https://youtu.be/Vq0-xm1PTnw

and when close → restart the browser, everything is same. ctrl + F9 will work for splitview and wrong value is there.
