### ISSUE TITLE
Split View tabs change on hover, even with the option disabled.

### ISSUE THREAD

**Issue by wellenfunktion** [zen-browser/desktop#1857]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Split tabs will change if you hover over them, even with the option that prevents that disabled, it's almost like it's on by default. Enabling the option does nothing.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1

### What platform are you seeing the problem on?

Linux, Windows

**Comment by sjclayton** [comment]
Duplicate of #1823

**Comment by wellenfunktion** [comment]
> Duplicate of #1823

you're right, sorry.
