### ISSUE TITLE
"Change tabs on hover" also affects regular tabs

### ISSUE THREAD

**Issue by KiKaraage** [zen-browser/desktop#1858]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Noticed this happened twice to me today, the first one was like two hours prior.

I enabled "Change tabs on hover" on Split View Settings after upgrading to -a.7, and I use "Hide sidebar" Compact Mode.

After I switched to this 'Substack' tab (from another tabs in the same workspaces, not related to two tabs I mentioned in this issue), I want to click the picture (to zoom it), but nothing happened. I tried to right-click the pic but I didn't found picture-related menus (Save image, opens image in a new tab, etc).

![Screenshot (21946)](https://github.com/user-attachments/assets/e717ddd6-51a2-4e84-974f-b049583c8b7b)

I hovered the tab list to look up _**which tab I actually interacted on**_ (without closing the context menu), and hovering on my selected tab does shown a glitch and I found the answer: _**It**_ was the 'Why We Need Ladybird' tab below the selected 'Substack' tab.
![Screenshot (21947)](https://github.com/user-attachments/assets/0e278296-d56c-4690-9f27-983896c2d8fb)

Realizing this was related to "Change tabs on hover", I go to Settings and disabled it. 
I went back to the 'Substack' tab and yeah it opens normally! (Right-clicking the picture does show the supposed context menu.)

![Screenshot (21948)](https://github.com/user-attachments/assets/993e0c4d-5365-4b6d-a034-42ce3540fe36)

I hope devs can figure out what's wrong and can fix it next update. 👍 

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.7

### What platform are you seeing the problem on?

Windows

**Comment by BrhmDev** [comment]
This is strange "Change tabs on hover" didn't work properly in 1.0.1-a.7 and was always enabled.
