### ISSUE TITLE
https://calendar.notion.so/ doesn't load, and when it does it shows "offline"

### ISSUE THREAD

**Issue by sidsharths1245** [zen-browser/desktop#1859]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

https://calendar.notion.so/ Just shows a blank white page, I have to close the tab and open it again for it load. But after it loads it says "offline" and i ma unable to do anything in the website. I checked and it is working perfectly in Edge and Chrome.

![image](https://github.com/user-attachments/assets/049faead-8331-4a39-9c71-88239a1ee6a2)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.7 (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by sidsharths1245** [comment]
If it is any help, this is what i see in the console in the developer tools when i try to load the page. 
![image](https://github.com/user-attachments/assets/3c0b0940-f9a6-4f91-bb12-e5700025ca27)

**Comment by BrhmDev** [comment]
Closed unless it's shown this is an issue specific to Zen and not all Firefox based browsers.

**Comment by sidsharths1245** [comment]
![Screenshot 2024-10-14 at 12-00-22 Oct 13 – 26 2024 · Notion Calendar](https://github.com/user-attachments/assets/74326228-bd41-4c96-b2b4-d9dff86f7338)
I checked it in Firefox and it doesn't have this issue
