### ISSUE TITLE
[BUG] Pinned tab icons are partially clipped to the right on a14 builds.

### ISSUE THREAD

**Issue by Rhelvetican** [zen-browser/desktop#186]
### What happened?

![image](https://github.com/user-attachments/assets/779b8770-79d5-4705-aaee-5e2b3e65bad7)
The image should explains my issue.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a14

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
Fixed on version 15 ✌️
