### ISSUE TITLE
"Select last tab" shortcut do not switch back and forth

### ISSUE THREAD

**Issue by morrolinux** [zen-browser/desktop#1864]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

If I'm on tab A and then switch to tab B, activating the "select last tab" shortcut brings me back to A as expected. The problem is that now, activating the "select last tab" shortcut again does nothing, when I'd expect it to bring me back to B, which has now become the new "last tab" before switching to A.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.7 (64-bit)

### What platform are you seeing the problem on?

Linux

**Comment by sjclayton** [comment]
I think you've misunderstood what last means in this context, it does not mean bring you back to the tab you were just on... it means go to the last tab in the list, just like there are shortcuts for switching to tab 1, 2, 3 and so on. 

So without knowing the ordering of Tab A and Tab B in your example, I cannot say that you are actually experiencing an issue. 

Hope this helps! 😁

**Comment by sjclayton** [comment]
Yes there is a way... 

In Settings, under General > Tabs make sure the first option `Ctrl+Tab cycles through tabs in recently used order` is checked, after this you can press `Ctrl + Tab` once to switch back and forth between the last tab and the most recent.
