### ISSUE TITLE
It does not load the video/movie in Private Mode

### ISSUE THREAD

**Issue by luckovics** [zen-browser/desktop#1868]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I can't watch a movie in private mode, it says wrong file(media) format or codec error. In normal mode, everything works.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1 a.7

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
The media could not be loaded either because the server or network failed or because the format is not supported. -error message
```

**Comment by luckovics** [comment]
The error occurs on a movie viewer page that contains playback links for a particular movie from other movie sharing sites
For example :https://mozicsillag1.me/film/38081-rambo-iv-jhon-rambo-2008-online
The first two links also give the error( I have not tried the other links) 
I have also experienced the playback error on other similar sites. -In private mode of course. 
In normal mode everything is perfect,and all movies play.

**Comment by n7itro** [comment]
Try changing some of the Enhanced Tracking protection settings, e.g. Tracking content

**Comment by luckovics** [comment]
As you advised, I changed the settings and then turned off the protection, but the same thing happened. In normal mode I can watch it with the protection on, in private mode I can't watch it with the protection on or off. I don't really use private mode, I was just trying it out as a curiosity.
