### ISSUE TITLE
Settings background doesn't change color when Night Theme is selected and switching to light mode

### ISSUE THREAD

**Issue by wyattwas** [zen-browser/desktop#1869]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When you select the Night Theme in dark mode and then switch to light mode, the background in the setting stays dark. You are unable to read the settings. When you switch to light mode when you have the Default Dark Theme or Colorful Dark Theme selected, this doesn't happen.
![Screenshot From 2024-10-02 13-54-45](https://github.com/user-attachments/assets/129bd920-3fc3-403c-bea6-1039e52b62d3)
![Screenshot From 2024-10-02 13-54-57](https://github.com/user-attachments/assets/92a3d4a7-eae9-4fed-b6c2-b7c6514cb2fc)
![Screenshot From 2024-10-02 13-55-07](https://github.com/user-attachments/assets/9fbe40af-48e6-4e65-8086-7a81e31aa912)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.7

### What platform are you seeing the problem on?

Linux, Windows

**Comment by nanoraptor** [comment]
Having the same problem here.
Version:1.0.1-a.7 (64-bit) (Generic/Non-Portable) (Windows)
