### ISSUE TITLE
Closed tabs are reopened on browser restart

### ISSUE THREAD

**Issue by jimfr** [zen-browser/desktop#187]
### What happened?

I thought this was fixed, but it's happening again.  With the last tab open being Inbox..., close a.15.  Restart the browser and see the three extra tabs that are reopened.
<img width="470" alt="image" src="https://github.com/user-attachments/assets/fc24c05f-67cc-4ff3-9874-7c7a8be28ba8">

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

a.15

### Severity impact

Low

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by mauro-balades** [comment]
This is firefox's issue, I think you just need to wait for the Session store cycle to run again. Let's see what happens in version 16

**Comment by jimfr** [comment]
OK, thanks.  Not seeing it on 129.0, but will keep an eye on it.

Awesome browser, btw.  So much better than FF that it's not funny!
