### ISSUE TITLE
Expand tabs on hover gets stuck in expanded state occasionally 

### ISSUE THREAD

**Issue by ell1010** [zen-browser/desktop#1871]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Sometimes when you move your mouse away from the tab area for it to shrink back down, it doesnt and stays expanded, blocking that section of the webpage and needing a browser reload to fix. only been happening since most recent update

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a7

### What platform are you seeing the problem on?

Windows

**Comment by Bruno1uno** [comment]
I have a simillar problem, when the "Expand tabs on hover" is enabled and I try to reorganize tabs while in the "expanded state" then the tab bar will not shrink again. The only way I found to fix this is by restarting browser.

Version: 1.0.1-a.7 (64-bit)

**Comment by cyclo9** [comment]
I also have the same problem, same version, and also found that restarting browser is the only way to fix it.

**Comment by HynDuf** [comment]
me too

**Comment by h-queiroz** [comment]
same

**Comment by famiu** [comment]
Having this same issue as well on Fedora Linux.

**Comment by akittas** [comment]
Same issue here since version a6 or a5, Windows 11

**Comment by ivanjx** [comment]
restarting the browser does not fix it for me

**Comment by cyclo9** [comment]
Haven't figured out the exact reproduction step, but I notice that this bug tends to occur after hovering over and swapping the order of some tabs.

**Comment by h-queiroz** [comment]
Another way I found to fix it, without needing to restart the browser, is to simply highlight any text and drag it to the tab area.

**Comment by superkillared** [comment]
same here on windows 10, 1.0.1-a7

**Comment by FlawlessCasual17** [comment]
Same here as well on Windows 11 x86_64 WIN32_NT 10.0.22631.2715 (23H2)
![image](https://github.com/user-attachments/assets/5759aaa4-cb4a-47c9-b8a5-6496c9024201)

**Comment by RABINGG** [comment]
> Another way I found to fix it, without needing to restart the browser, is to simply highlight any text and drag it to the tab area.

yup it works

**Comment by mr-cheffy** [comment]
Does this keep happening in version .8?

**Comment by h-queiroz** [comment]
> Does this keep happening in version .8?

For me, yes.

**Comment by kris3713** [comment]
> Does this keep happening in version .8?

Yes, it's still persistent.

**Comment by ivanjx** [comment]
.8 introduces new bugs:
- expand on hover shifts the whole tab content (again).
- ![image](https://github.com/user-attachments/assets/dfee2b5b-fe1a-44b4-bc8c-6f151552abe8)

**Comment by akittas** [comment]
Unfortunately this is still an issue in version 8. This makes it impossible to reorder tabs when using show tabs on hover, because when I try to reorder it always gets stuck in this state.

**Comment by YaYaTurre** [comment]
I am repeatedly having this problem as well. On Mac.

**Comment by mr-cheffy** [comment]
Expand on hover only hides when the mouse exists from the right side. Is that what this issue is referring about?

**Comment by ell1010** [comment]
no, sometimes when you move the mouse to the right out of the tab area, it doesnt hide but instead "freezes" in the expanded state

**Comment by akittas** [comment]
Unfortunately, problem persists in version 9

**Comment by yoshijulas** [comment]
This is a video showing the issue, I tried it on (1.0.1-t.10) and have this issue, and with (1.0.1-a.10) also.

https://github.com/user-attachments/assets/3bd5be8e-0f77-48f4-930b-caa46fe6c1f9

**Comment by yoshijulas** [comment]
> This is a video showing the issue, I tried it on (1.0.1-t.10) and have this issue, and with (1.0.1-a.10) also.

Looks like `zen-has-hover = "true"` updates even when its "stuck", but when moving a tab, it adds the attribute `movingtab=""`, which doesn't get removed even after clicking somewhere else, only until I drag some text and updates it and that removes the attribute of movingtab, and it's when starts working again.

**Comment by mr-cheffy** [comment]
Ohh... Ok, ill take a look into it

**Comment by ivanjx** [comment]
seems to be fixed on a.12

**Comment by giaaaacomo** [comment]
still happening in the latest stable build :[
