### ISSUE TITLE
icons in title bar shifts when turn on/off compact mode

### ISSUE THREAD

**Issue by alphatownsman** [zen-browser/desktop#1872]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

As shown in screen shots below, top left icons in the title bar shift left/right for a few pixels when turn on/off compact mode

<img width="619" alt="Screenshot 2024-10-02 at 16 41 18" src="https://github.com/user-attachments/assets/eab889c6-59a4-4acb-9be5-a1ae82957126">
<img width="619" alt="Screenshot 2024-10-02 at 16 41 08" src="https://github.com/user-attachments/assets/923006d1-56e8-4675-8f9c-be56644a0608">

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1a7

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by harryheres** [comment]
At the moment, #2170 is the best we can do. The layout will still shift a bit due to an UI splitter being moved from one side to another.
