### ISSUE TITLE
Impossible to move workspaces

### ISSUE THREAD

**Issue by Damglador** [zen-browser/desktop#1873]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Literally one of the issues leading me to leave Arc behind, less bad tho.

Seems like it's impossible to move workspaces on the bottom bar in the side panel around. Dragging doesn't work there and in editing mini-menu. The only workaround is to delete workspaces and add them back in the right order.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.7

### What platform are you seeing the problem on?

Linux

**Comment by nanoraptor** [comment]
Hey you tried right clicking on the sidebar and chosing to customize toolbar option. You can move your workspaces bar from there.

**Comment by Damglador** [comment]
> Hey you tried right clicking on the sidebar and chosing to customize toolbar option. You can move your workspaces bar from there. 

I was talking about workspaces themselves, not the bar. Arrangement of workspaces, if it makes it clearer.

**Comment by mr-cheffy** [comment]
Now you can, thanks!
