### ISSUE TITLE
My workspaces not saved into my account!

### ISSUE THREAD

**Issue by ertugruluyar-github** [zen-browser/desktop#1878]
### Captchas

- [X] I have read the instructions.
- [ ] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

I switched to my new laptop, I installed the Zen Browser from flathub, but my workspaces not get back and there is 6 workspaces tha I have and these have several tabs.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a7

### What platform are you seeing the problem on?

Linux

**Comment by kristijanribaric** [comment]
Workspaces sync is not yet implemented in this version. It should be introduced in the next build (it already is in Twilight build).

**Comment by ertugruluyar-github** [comment]
> Workspaces sync is not yet implemented in this version. It should be introduced in the next build (it already is in Twilight build).

Thank you, if it is sync come, I think other things that this browser giving is really good and effective. So, I am gonna switch right away fromGoogle Chrome.
is this feature available in this release: https://github.com/zen-browser/desktop/releases/tag/1.0.1-a.8

**Comment by kristijanribaric** [comment]
> Is this feature available in this release: https://github.com/zen-browser/desktop/releases/tag/1.0.1-a.8

Yes it is!

**Comment by ertugruluyar-github** [comment]
> > Is this feature available in this release: https://github.com/zen-browser/desktop/releases/tag/1.0.1-a.8
> 
> Yes it is!
> 
> If the sync works for you don't forget to close this issue

I'll try later in today, thanks again.
