### ISSUE TITLE
Blurry font bug reappeared

### ISSUE THREAD

**Issue by amagnolo** [zen-browser/desktop#1879]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

A behavior similar to that reported in closed issues #440 and #383 has reappeared in version 1.0.1-a.7.
The text is blurred but when I click and drag on it with the mouse (to select the text), it becomes clear.
This doesn't happen on firefox.

On newly loaded page (blurred):
![Screenshot from 2024-10-03 10-54-53](https://github.com/user-attachments/assets/3fd4aaeb-f5a4-4c33-9451-de14ba110c81)
After selecting text (clear):
![Screenshot from 2024-10-03 10-55-00](https://github.com/user-attachments/assets/63ba2ab3-c598-4d36-940e-29b5ea8bf0f2)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.7

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
What themes/mods do you have installed?

**Comment by amagnolo** [comment]
I'm sorry, I realized that [Super Url Bar](https://zen-browser.app/themes/d93e67f8-e5e1-401e-9b82-f9d5bab231e6) is the culprit. I'm closing this issue.
