### ISSUE TITLE
vietnamese typing

### ISSUE THREAD

**Issue by asphosmacy** [zen-browser/desktop#1884]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

so i am trying to type vietnamese on zen browser i have checked that input methods does work but is just zen not taking vietnamese input

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1.a.7-1

### What platform are you seeing the problem on?

Linux

**Comment by asphosmacy** [comment]
info: im on endearvour os 
input method: unikey 
output charset: unicode 
de: kde plasma 6(wayland)
package: zen-browser-bin

**Comment by salamijason** [comment]
Hey are you still getting this issue on the most recent version? 1.0.1.a-14

**Comment by CDzungx** [comment]
If the character is accented, it get duplicated at the first word when tying on the search bar. I think this relate to suggested links when typing. Because it wont happend when search engine is choosen.

https://github.com/user-attachments/assets/00aef050-437d-4da5-b31e-b42f5378bac6

**Comment by asmophacy** [comment]
> Hey are you still getting this issue on the most recent version? 1.0.1.a-14

i am on 1.0.1.a-17 but i cant test because im on hyprland after installing arch linux because i havent figured it out yet

**Comment by salamijason** [comment]
Cool, please give us an update once you have everything set up and figured out.

**Comment by salamijason** [comment]
No response in multiple weeks. Closing for now. Please reopen if you're still encountering the issue.
