### ISSUE TITLE
Missing "Undo close tab" keyboard shortcut

### ISSUE THREAD

**Issue by benface** [zen-browser/desktop#1886]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

There is an "Undo close window" shortcut, but no "Undo close tab". I would love to set it to Cmd+Z, like in Safari.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.7

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by sjclayton** [comment]
@benface 

There is the `Restore Last Closed Tab` shortcut option, which is the same as what you are wanting is it not?

**Comment by benface** [comment]
Oh thanks @sjclayton, I was looking for "undo" so I completely missed that... looks like it should do what I want, but it doesn't work. 😅 Nothing happens after I close a tab and try that shortcut. The "Undo close window" one works though!

**Comment by sjclayton** [comment]
Hmmm, odd -- it works fine on both my machines (Windows and Linux)... Did you try the default shortcut that exists for that option, or did you immediately reset it to your own? If you did try to change it, it needs to be saved by pressing `ESC` after changing it. If you're still having issues, it might be something macOS specific causing problems...

**Comment by benface** [comment]
Ok so it was the specific shortcut I set that didn't work, despite not conflicting with anything (well, it initially did, but I changed the one it conflicted with). So to summarize:
- "Shift+Cmd+Z" doesn't work (even after I changed "Redo", which was conflicting, to "Ctrl+Cmd+Z")
- But "Ctrl+Cmd+Z" does work :)

**Comment by mauro-balades** [comment]
Can I close?

**Comment by benface** [comment]
Sure, thank you!
