### ISSUE TITLE
AppImage not launching

### ISSUE THREAD

**Issue by AdilDevStuff** [zen-browser/desktop#189]
### What happened?

Launching appimage doesn't do anything, it just loads for a second and then nothing happens!

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0 a.15

### Severity impact

High

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
Could you run it from the terminal and send the output?

**Comment by AdilDevStuff** [comment]
> Could you run it from the terminal and send the output? Are you on an optimized build or a generic one?

Im on optimized one (i downloaded the specific one) and the output shows nothing, its blank...

**Comment by AdilDevStuff** [comment]
The generic one works, there might be something wrong with the specific one in my end or either in the appimage, idk!

**Comment by mauro-balades** [comment]
Probably your CPU is not supported or new enough for a Specific build, im gonna close this now if that's ok with you

**Comment by Samueru-sama** [comment]
>But flatpak works tho :)

The flatpak is very likely a generic build and there is no specific build, I think this a requirement with flatpak because yuzu had had this difference as well, their appimage was x86-64 v2 while the flatpak was x86-64 generic, and in that case there was a **9%** performance difference.

What CPU do you have?

**Comment by AdilDevStuff** [comment]
> > But flatpak works tho :)
> 
> The flatpak is very likely a generic build and there is no specific build, I think this a requirement with flatpak because yuzu had had this difference as well, their appimage was x86-64 v2 while the flatpak was x86-64 generic, and in that case there was a **9%** performance difference.
> 
> What CPU do you have?

I seee, i mean its all good, I just wanted to try the latest version and flatpak got updated so its good. As long as it works, it works lol

I have AMD A8-7600 tho, which is kinda old but yea..

**Comment by Samueru-sama** [comment]
> I have AMD A8-7600 tho, which is kinda old but yea..

Put this on the terminal and tell me the output `/lib/ld-linux-x86-64.so.2 --help | grep x86`

**Comment by AdilDevStuff** [comment]
> /lib/ld-linux-x86-64.so.2 --help | grep x86

`bash: /lib/ld-linux-x86-64.so.2: No such file or directory`

**Comment by mauro-balades** [comment]
Huh

**Comment by Samueru-sama** [comment]
> `bash: /lib/ld-linux-x86-64.so.2: No such file or directory`

What's your distro?

Where do you have `ld-linux-x86-64.so.2`? 

If you wonder why I ask, it is because your CPU should be compatible with x86_64 v3 and the specific appimage should have worked.

**Comment by mauro-balades** [comment]
Maybe it's under `/lib64`

**Comment by AdilDevStuff** [comment]
> Maybe it's under `/lib64`

`Usage: /lib64/ld-linux-x86-64.so.2 [OPTION]... EXECUTABLE-FILE [ARGS-FOR-PROGRAM...]
This program interpreter self-identifies as: /lib64/ld-linux-x86-64.so.2
  /lib/x86_64-linux-gnu (system search path)
  /usr/lib/x86_64-linux-gnu (system search path)
  x86-64-v4
  x86-64-v3
  x86-64-v2 (supported, searched)
  x86_64 (AT_PLATFORM; supported, searched)
  x86_64 (supported, searched)`
  
  Yea now it gave this

**Comment by AdilDevStuff** [comment]
> > `bash: /lib/ld-linux-x86-64.so.2: No such file or directory`
> 
> What's your distro?
> 
> Where do you have `ld-linux-x86-64.so.2`?
> 
> If you wonder why I ask, it is because your CPU should be compatible with x86_64 v3 and the specific appimage should have worked.

oh so okay, mine is not supported, gotcha!

**Comment by Samueru-sama** [comment]
> > Maybe it's under `/lib64`
> 
> ```
> This program interpreter self-identifies as: /lib64/ld-linux-x86-64.so.2
>   /lib/x86_64-linux-gnu (system search path)
>   /usr/lib/x86_64-linux-gnu (system search path)
>   x86-64-v4
>   x86-64-v3
>   x86-64-v2 (supported, searched)
>   x86_64 (AT_PLATFORM; supported, searched)
>   x86_64 (supported, searched)```
>   
>   Yea now it gave this
> ```

Okay what is going on.

Your CPU does not support x86_64 v3 as seen there. [but it should](https://en.wikipedia.org/wiki/Excavator_(microarchitecture))

**Comment by mauro-balades** [comment]
Yeah, you need -v3 for specific builds. Some people display this error as an illegal instruction some others simply just get stuck. You can use only generic builds

**Comment by AdilDevStuff** [comment]
> Yeah, you need -v3 for specific builds. Some people display this error as an illegal instruction some others simply just get stuck. You can use only generic builds

its fine ig

**Comment by Samueru-sama** [comment]
> Hey, so I tried generic appimage as well and its not working too! It gives this error when ran through terminal `execv error: No such file or directory`

That would be because you have [appimagelauncher installed](https://github.com/zen-browser/desktop/issues/312#issuecomment-2298624066)

**Comment by AdilDevStuff** [comment]
Yea i have it installed.
