### ISSUE TITLE
SplitView shortcuts not working when focused on google docs

### ISSUE THREAD

**Issue by tashengears** [zen-browser/desktop#1891]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I think the shortcuts for google docs are overriding the zen shortcuts

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.7

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by onthejobtraining** [comment]
Google docs most likely uses the same shortcut.

**Comment by BrhmDev** [comment]
This seems to be the intended behavior of Firefox shortcuts. You can right click tab > "split tab" or change the shortcut to avoid conflicts.
