### ISSUE TITLE
New tab shortcut doesn't work if on twitch tab

### ISSUE THREAD

**Issue by TheyCallMeTojo** [zen-browser/desktop#1893]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

If Twitch is loaded, the shortcut for new tab does not work while in that tab. Doesn't happen on other tabs. It doesn't matter what the shortcut is set to, it doesn't open while Twitch is loaded in current tab. 

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.7 (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by clembu** [comment]
As additional detail/corrective:

The twitch chat text input somehow captures `ctrl-t` as a shortcut to swap the last two characters.
It doesn't happen on my Opera GX nor on a fresh install of Mozilla Firefox.

Changing the "new tab" shortcut to something like `alt+ctrl+n` does make the conflict go away, so it's something to do with input fields and `ctrl+t`. Twitch's chat is the only instance of this I have found so far.

**Comment by BrhmDev** [comment]
This doesn't happen for me but most likely twitch calls `preventDefault()` on the keydown event. In this case the shortcut won't get triggered, which is intended behavior. If it's demonstrated the behavior is unintended, I can reopen the issue.
