### ISSUE TITLE
Web browser crashes whenever a live video is playing

### ISSUE THREAD

**Issue by mrbluegame** [zen-browser/desktop#1896]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

For some reason if i do many action at the same time while a twitch video is playing it quickly slows down and crash (example) I open the sidebar and move to different tabs quickly the browser quickly slows down it also lags very bad when i zoom in unlike other browsers i turned off all of my addons and i still had the same problems

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

131.0

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
sadly i do not know where to get the files would appreciate if anyone can show me how
```

**Comment by miyuki-ts** [comment]
> ### Captchas
> 
>     * [x]  I have read the instructions.
> 
>     * [x]  I have searched existing issues and avoided creating duplicates.
> 
>     * [x]  I am not filing an enhancement request.
> 
> 
> ### What happened?
> 
> For some reason if i do many action at the same time while a twitch video is playing it quickly slows down and crash (example) I open the sidebar and move to different tabs quickly the browser quickly slows down it also lags very bad when i zoom in unlike other browsers i turned off all of my addons and i still had the same problems
> ### Reproducible?
> 
>     * [x]  I have checked that this issue cannot be reproduced on Mozilla Firefox.
> 
> 
> ### Version
> 
> 131.0
> ### What platform are you seeing the problem on?
> 
> Windows
> ### Relevant log output
> 
> ```shell
> sadly i do not know where to get the files would appreciate if anyone can show me how
> ```

I have similar issue, on the lastest

> ### Captchas
> 
>     * [x]  I have read the instructions.
> 
>     * [x]  I have searched existing issues and avoided creating duplicates.
> 
>     * [x]  I am not filing an enhancement request.
> 
> 
> ### What happened?
> 
> For some reason if i do many action at the same time while a twitch video is playing it quickly slows down and crash (example) I open the sidebar and move to different tabs quickly the browser quickly slows down it also lags very bad when i zoom in unlike other browsers i turned off all of my addons and i still had the same problems
> ### Reproducible?
> 
>     * [x]  I have checked that this issue cannot be reproduced on Mozilla Firefox.
> 
> 
> ### Version
> 
> 131.0
> ### What platform are you seeing the problem on?
> 
> Windows
> ### Relevant log output
> 
> ```shell
> sadly i do not know where to get the files would appreciate if anyone can show me how
> ```

I have similar issue on the lastest zen browser, every live stream on twitch will lag for me, i tested with all mods and extensions off, same result. I don't have this issue non any other browser i tested on firefox and brave, google chrome and edge.
I use Zen Browser Version 1.0.1-a.16 (64-bit)

I am on windows 11 pro 64 bit.

This is my hardware https://pcpartpicker.com/user/Miyuki_/saved/#view=RKTqbv

**Comment by KakouMoses** [comment]
Ok, so it's not just Youtube videos (I was thinking that bc of Google)
