### ISSUE TITLE
Workspace is broken

### ISSUE THREAD

**Issue by Dadangdut33** [zen-browser/desktop#190]
### What happened?

It does not work anymore. When you switch workspace the tabs got carried on onto another workspace. Only the workspace name that change.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.15 (64-bit)

### Severity impact

High

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
Fixed with https://github.com/zen-browser/desktop/commit/1e368f6f0fe9d64757ae30c6843125de9ef59a41, sorry about that. It will be applied for .16. Thanks!

> Please use low priority next time for UI bugs

**Comment by Dadangdut33** [comment]
thanks, that wasnt just a ui bugs tho. I lost all my tabs because of this bruh 🗿

**Comment by mauro-balades** [comment]
How did you loose them? They are probably just hidden

**Comment by Dadangdut33** [comment]
yeah i had way too many i guess. it become somewhat impossible to recover them because when i close a tab it then just launch with the same opened tabs as before so i need to delete all the workspaces and create it new. Its okay though i remember most of the tabs that i need.

**Comment by mauro-balades** [comment]
Sorry about that 😔
