### ISSUE TITLE
Browser cannot search for text

### ISSUE THREAD

**Issue by theuser18** [zen-browser/desktop#1905]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?
When pressing ctrl+f to bring up the search box, entering in a search term always leads to a red box, indicating no text on the pages matches the search query. However this is not the case. At first glance, it looks like it cannot search any string larger than one character.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1 a7

### What platform are you seeing the problem on?

Linux

**Comment by thyeun** [comment]
i also using 1.0.1-a.7 but i'm not facing this issue, i can even search by chinese/japanese word/sentence.

**Comment by MisterHighping** [comment]
Are you using an adblocker? If so could it be that you didn't accept a cookie banner?
I am also not facing this issue but the same thing happend in the past with Firefox. The site looked fine but ublock did block the cookie banner and there was an overlay over the site so that CTRL + F didn't work.

**Comment by mauro-balades** [comment]
Could it be possible that the text is an image or that the website stated it shoudnt be searchable?
