### ISSUE TITLE
Sidebar suddenly not working as it sould

### ISSUE THREAD

**Issue by centrdev** [zen-browser/desktop#1908]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

My sidebar will no longer resize, the size is tuck and i can not add items to it. 

I have been using the latest release (Version 1.0.1-a.7 (64-bit) ) since it came out and the browser for a couple of weeks no, and never had this issue until now.

It just suddenly started and everything has been fin up until today 🤷‍♂️

Is there a way to clear the "app" cache? 

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Version 1.0.1-a.7 (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by salamijason** [comment]
Hi are you still getting this in the latest version 1.0.1-a.14? If so, could you also attach a screen recording?

**Comment by centrdev** [comment]
> Hi are you still getting this in the latest version 1.0.1-a.14? If so, could you also attach a screen recording?

hey, no, i resolved the issue by creating a new profile and copying over my data. that new profile did not have the issue
