### ISSUE TITLE
Language switching error

### ISSUE THREAD

**Issue by mikropsoft** [zen-browser/desktop#191]
### What happened?

![Ekran Görüntüsü (128)](https://github.com/user-attachments/assets/586b5aab-0d6f-4ba7-b7e0-cbfbc3bcee69)

Is this normal?

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0

### Severity impact

Medium

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
This is because we curently have no language servers, but we are planning on adding them in the future!
