### ISSUE TITLE
No known trackers to Zen detected on Google and YouTube (all settings are default)

### ISSUE THREAD

**Issue by weballin449** [zen-browser/desktop#1912]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![image](https://github.com/user-attachments/assets/f2b6232e-0425-4349-abf7-6c375cea693d)
same for Google. 

No extensions or settings modification was done

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Version 1.0.1-a.7 (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by coderstarrer** [comment]
Use Ublock Orgin

**Comment by salamijason** [comment]
Are you using it simultaneous with an adblocking or trackerblocking extension?

**Comment by ghost** [comment]
> Are you using it simultaneous with an adblocking or trackerblocking extension?

Nope. Completely default experience

**Comment by Richard-Woessner** [comment]
Can you try this on Firefox and how knowledgeable are you about your network. Any chance some network setup is blocking the trackers before it reaches zen?

Which is why testing it on Firefox would be helpful. It will determine if its zen or something else

**Comment by Richard-Woessner** [comment]
I also would like to add that in the current twilight build its blocking for me

<img width="614" alt="image" src="https://github.com/user-attachments/assets/7569258e-7633-48be-9359-b5c407f57742">

**Comment by ghost** [comment]
> Can you try this on Firefox and how knowledgeable are you about your network. Any chance some network setup is blocking the trackers before it reaches zen?
> 
> Which is why testing it on Firefox would be helpful. It will determine if its zen or something else

I will try it on Firefox within ~36 hours. 

I am not very knowledgeable about network setups but there have been no configuration changes in the networking (both device and router side). There is no kind of firewall for tracking domains

**Comment by salamijason** [comment]
Hey it's been about a month since the author last responded. Will be closing this issue now. Please reopen if issues persist.
