### ISSUE TITLE
Tab sidebar overlay on screenshot if Expand by hover is enabled

### ISSUE THREAD

**Issue by RABINGG** [zen-browser/desktop#1913]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

The sidebar get expanded and overlay on the webpage while taking screenshot. This only happens if sidebar on hover is enabled.
![image](https://github.com/user-attachments/assets/f7b6defc-9e6d-4453-8563-7feefd01ab1c)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.7

### What platform are you seeing the problem on?

Windows

**Comment by salamijason** [comment]
This is already an issue. https://github.com/zen-browser/desktop/issues/917

Though, this post has added that it happens in non-compact mode with expand on hover on. I will close this issue as the other one is already verified as a bug.
