### ISSUE TITLE
"Splitting" unloaded tabs results in empty slots

### ISSUE THREAD

**Issue by LeMoonStar** [zen-browser/desktop#1915]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Auto Unloading of tabs was introduced in a recent update.
When trying to "split tabs" with the current, loaded tab, and one or several other unloaded tabs, only the loaded tab is shown while the unloaded tabs result in an empty space. These tabs should probably be loaded and displayed instead.

## How to reproduce
1. Make sure auto unloading of tabs is enabled
2. Stay on one of the tabs and wait for the others to unload
3. Select the current, loaded tab, and at least one unloaded tab using CTRL in the tab list, right click and select "Split X Tabs"

![image](https://github.com/user-attachments/assets/9bff1acd-9cf8-4335-9be0-fa14592353fc)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.7

### What platform are you seeing the problem on?

Linux

**Comment by BrhmDev** [comment]
This is fixed in 1.0.1-a.8
