### ISSUE TITLE
h-screen (height: 100vh;) works only on full screen

### ISSUE THREAD

**Issue by gustawdaniel** [zen-browser/desktop#1917]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![image](https://github.com/user-attachments/assets/4db7815c-f79c-4629-86f8-f95184de7e3f)

I attaching 3 screenshots:
- 1 Zen Desk
- 2 Chrome
- 3 Firefox

On all screens I should see yellow background with 2 green bars (top and bottom).

In chrome and Firefox it works, but on zen desk works only on full screen, but by default no.

There is my code (tailwind)

```html
  <div class="flex justify-center bg-gray-100 h-screen">
    <div class="container flex flex-col justify-between bg-amber-100">
      <p class="bg-green-400">TOP</p>
      <p class="bg-green-400">DOWN</p>
    </div>
  </div>
```

I am using i3 with gaps poly-bar and i3-bar. I can reproduce problem both in tailing and floating windows.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.31 (64-bit)

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
I expect both TOP and DOWN green bars be visible like in Chrome or Firefox.

I experiencing problems with Zen Desk when I am using apps like chatgpt, telegram, whatsapp, where message input is sometimes not visible because of this bug, but this example mentioned before is allow to easily reproduce problem.
```

**Comment by mauro-balades** [comment]
You seem to be in a really old version. Could you try updating?

**Comment by gustawdaniel** [comment]
![image](https://github.com/user-attachments/assets/35606a97-6e34-46cd-b2b2-f11d9e074852)

Left 

> Mozilla Zen 1.0.0-a.31

Right

> Mozilla Zen 1.0.1-a.7

So this problem is solved now. Thanks.
