### ISSUE TITLE
Title bar does not align itself when the window is made smaller

### ISSUE THREAD

**Issue by nanoraptor** [zen-browser/desktop#1918]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![Github_issue](https://github.com/user-attachments/assets/b30e7657-c0ca-45ab-8870-5315aa63a5a3)
When I resize the window to a smaller size, the title bar does not configure itself properly. It's all messed up.
This only occurs in non compact mode. The title bar aligns itself properly when the zen browser is in compact mode

### Reproducible?
- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.8 (64-bit) (Generic/Non-portable)

### What platform are you seeing the problem on?

Windows

**Comment by nanoraptor** [comment]
Do note that I use the Generic non portable version

**Comment by RayZ3R0** [comment]
Does this still happen on latest version? (a.14 as of this comment)

**Comment by salamijason** [comment]
No response in 2 weeks, will be closing this issue. Please reopen if issue persists.
