### ISSUE TITLE
shortcuts formatted/displayed poorly

### ISSUE THREAD

**Issue by BaronAWC95014** [zen-browser/desktop#1919]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

when settings shortcuts in the settings, pressing "shift" or "option" or not affects the visual of the shortcut, which gets extremely confusing.

here i am pressing option S for a split tab, and it shows ß instead of S.

in other examples, a shortcut containing or not containing "shift" affects if a key displays in upper case or not.

<img width="727" alt="image" src="https://github.com/user-attachments/assets/b7ff82a7-83f5-4896-983e-564bb8dcae28">

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.7 (64-bit)

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by salamijason** [comment]
is this still an issue you're facing?

**Comment by BaronAWC** [comment]
i don't think so, it seems to be fixed.
