### ISSUE TITLE
There is no padding for the icons on the top left corner of the window

### ISSUE THREAD

**Issue by nanoraptor** [zen-browser/desktop#1920]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![Screenshot 2024-10-06 004906](https://github.com/user-attachments/assets/7daabca0-be74-4cf5-a344-3e4914be10fe)
As you can see in the red arrow, there is no padding on the top left corner for icons. But in the blue arrow there is (because I used a [zen mod](https://zen-browser.app/themes/180d9426-a020-4bd7-98ec-63f957291119). It would be beneficial If we would be able to raise feature request to the zen mod creators (they don't have specific github page devoted to the zen mod) or if this becomes inbuilt within the zen browser itself. I don't think this is an enhancement request as this should be the default behavior of the app anyways.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.7 (64-bit) (Generic version)

### What platform are you seeing the problem on?

Windows

**Comment by salamijason** [comment]
I believe this has been fixed since but could you please let me know if all is good on your end?

**Comment by salamijason** [comment]
No response in 3 days, will be closing this issue. Please reopen if you are still facing this issue.
