### ISSUE TITLE
not working on arch hyperland idk why

### ISSUE THREAD

**Issue by potatoboi120-forge** [zen-browser/desktop#1927]
### Captchas

- [ ] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

hi i use arch hyprland i just download it from flatpak and i run it from rofi first and didn't open i tried run it from terminal by flatpak run and said Wayland Proxy [0x7027c8357570] Error: StartProxyServer(): bind() error : Address already in use help pls i realy want to try zen

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

latest on october 6 2024

### What platform are you seeing the problem on?

Linux

### Relevant log output

Wayland Proxy [0x7027c8357570] Error: StartProxyServer(): bind() error : Address already in use

**Comment by potatoforge120** [comment]
nvm it was my fault
