### ISSUE TITLE
The search icon turns fat when anything is typed into the search bar

### ISSUE THREAD

**Issue by nanoraptor** [zen-browser/desktop#1929]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

https://github.com/user-attachments/assets/b7d87f7e-f8f0-4c74-ae5d-88587102a9b6

currently when I type anything on the search bar, the search icon in the address bar turns fat like it's about to be squeezed to death. The appearance of the pill shaped search icon is perfect as it is. It should not change its appearance while typing something. Please fix this. Also I can see there is some ui/ux shift when I start typing in the address bar (like the thickness of the bar itself changes) this should not happen as it does not provide a seamless experience.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.7 (64-bit) (Generic Version running on windows 10)

### What platform are you seeing the problem on?

Windows

**Comment by salamijason** [comment]
Bug could not be reproduced on latest version 1.0.1-a.14. Could you please try again on the latest ver and let me know how it goes? If it doesn't work, please attach a screen recording.

**Comment by salamijason** [comment]
No response in 4 days, will be closing this issue. Please reopen if you are still facing this issue.
