### ISSUE TITLE
Hindi script doesn't render correctly

### ISSUE THREAD

**Issue by iamkartiknayak** [zen-browser/desktop#1930]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Hindi language text doesn't render the same way other browser does. Tried it in Brave & Firefox.
The way it currently render this language is not readable.

**Zen:**
![image](https://github.com/user-attachments/assets/0291a92b-3df0-463d-9973-d17322c6a738)

**Firefox:**
![image](https://github.com/user-attachments/assets/6abdb78f-707c-4208-98e0-580f08a312e5)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.7

### What platform are you seeing the problem on?

Linux

**Comment by LeMoonStar** [comment]
Hey! Is this still the case for you in the newest version of Zen?

Trying this myself I cannot find any difference between Firefox and Zen - neither on Google Translate nor on DuckDuckGo.
<details><summary>Screenshots</summary>

![Screenshot from 2024-11-01 16-25-54](https://github.com/user-attachments/assets/6128101e-0b78-4b11-955c-02d0d11bc05e)
![Screenshot from 2024-11-01 16-26-07](https://github.com/user-attachments/assets/4d453428-f6b8-4127-b43a-3d1f45c08b12)
</details>

**Comment by kodebarista** [comment]
Looks like the issue has been fixed
