### ISSUE TITLE
Trademarked slogan in use for Zen Browser

### ISSUE THREAD

**Issue by wolfbeast** [zen-browser/desktop#1931]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

It was pointed out that you are prominently using the trademarked slogan "Your Browser, Your Way" for the Zen browser application.
Please be aware Pale Moon (which I am the owner of) has trademarked this as its core mission statement as it puts customization of the browser central. You may not use it for your browser as it directly conflicts with our use.
See the following resources:
https://www.palemoon.org/licensing.shtml
https://www.palemoon.org/branding.shtml

Please immediately discontinue use of the phrase in connection with this and any other browser products you may be publishing.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

all

### What platform are you seeing the problem on?

Linux, macOS - aarch64, macOS - Intel, Windows

### Relevant log output

```shell
irrelevant, this is a branding issue.
```

**Comment by RealmyTheMan** [comment]
Could you clarify in which jurisdiction the trademark is registered, and do you have any proof or link to the trademark existing?

**Comment by n7itro** [comment]
Also mention which nations the trademark applies to

**Comment by darkvergus** [comment]
To begin with theres no registration for Pale Moon under the EU trademark found here https://euipo.europa.eu/eSearch/#basic/1+1+1+1/100+100+100+100/palemoon
same goes for Moonchild Productions
https://euipo.europa.eu/eSearch/#basic/1+1+1+1/100+100+100+100/moonchild%20productions

and searching worldwide using https://www.tmdn.org/tmview/#/tmview/results?page=1&pageSize=30&criteria=C&offices=AL,AT,BA,BG,BX,CH,CY,CZ,DE,DK,EE,ES,FI,FR,GB,GE,GR,HR,HU,IE,IS,IT,LI,LT,LV,MC,MD,ME,MK,MT,NO,PL,PT,RO,RS,RU,SE,SI,SK,SM,EM,WO&territories=EUR&basicSearch=pale%20moon
there is one in the UK which from my understanding is not where you're located to begin with and seems to be a different thing. 

So i suggest you provide proof of your trademark.

**Comment by mauro-balades** [comment]
We might need a trademark serial number or a link to the mark from the USTPO.

**Comment by wolfbeast** [comment]
It's a **common law trademark**, i.e. ™ not ®. Pale Moon has been published globally for 15 years and the trademark claim on both the product names and this particular mission statement has existed for practically that entire time. If you need proof you can look up the history of the website on e.g. archive.org
First archive.org capture of the licensing page from 2015 https://web.archive.org/web/20151205220847/http://www.palemoon.org/licensing.shtml
I'm not sure what other "proof" aside from the claim and carrying/active use of the trademarks you require here.

As far as the jurisdiction is concerned, if you wish to file a legal claim it will have to be filed in Sweden where I reside. I'd prefer to avoid litigation.

Regional registration with a trademark and patent office is not necessary; it only provides easier proof of the trademark claim. The intent to register only exists insofar legally required. Our project could not possibly be required to register it in every possible region on the planet when it has already been clearly established as a common law trademark. An Internet browser is not nationally or regionally bound; the web is global.

**Comment by darkvergus** [comment]
Licensing is not a trademark

**Comment by wolfbeast** [comment]
> Licensing is not a trademark

The licensing page is just a vessel. It includes general legal information.

**Comment by mauro-balades** [comment]
Just because you write it in a html document does mean you trademarked it

**Comment by darkvergus** [comment]
My point stands, this is just licensing theres nothing here that proves you have the rights to the trademark unless you can show this is registered

**Comment by wolfbeast** [comment]
For those thinking the USPTO or ® is required, please look up common law trademark rights. Registration is not required.
e.g. top hit in my search engine: https://www.gerbenlaw.com/blog/an-overview-of-common-law-trademark-rights/ -- please read it.

**Comment by darkvergus** [comment]
Cool i'm glad you understand you're based on Sweden right? So this applies in Sweden, which from my understanding Zen Browser is not based on.

**Comment by wolfbeast** [comment]
Once again a web browser is not a regionally bound product. Our community is global. Our use of the browser is global. The trademark claims are therefore also global by context. e.g. you can't take the name "Opera" for a browser just because you're not in a location where they are headquartered.

**Comment by TheRealMG** [comment]
Common law trademark does not apply internationally.  i.e. not globally applicable. This is a flimsy claim. If you wanted to claim specifically for Sweden, you might have a case. However, you cannot claim common law trademark on something globally. Many places in the world do not even recognize common law trademark.

**Comment by darkvergus** [comment]
No they aren't because it falls under common law trademarks, which is regional based. Unless you provide a federal registration it is a common law trademarks

**Comment by TheRealMG** [comment]
The difference between not being able to use opera and this particular phrase, is that Opera is actually trademarked using the actual trademark system, not common law

**Comment by wolfbeast** [comment]
No, because "federal" only applies to the USA. the USPTO has no influence outside of the states.

**Comment by TheRealMG** [comment]
Exactly. And if you wanted to claim trademark on multiple jurisdictions, you would have to apply for trademark under each of those jurisdictions. You cannot claim common law globally

**Comment by wolfbeast** [comment]
You're effectively asking me to register in every regional and national office in the world? That's not how that works.

**Comment by TheRealMG** [comment]
And you're abusing common law trademark by not understanding how THAT works.

**Comment by darkvergus** [comment]
No one is asking you to do anything you're the one who doesn't understand how common law trademarks work

**Comment by RealmyTheMan** [comment]
This input might be unnecessary, but I don't think that the majority of people associate "Your browser your way" with Pale Moon. I have heard of Pale Moon before and I don't recall Pale Moon using it

**Comment by n7itro** [comment]
@wolfbeast Do note that there is no legal protection for unregistered trademarks in the trade mark law of the European Union.

**Comment by iamoverrated** [comment]
https://www.uspto.gov/trademarks/basics/what-trademark

Pale Moon is globally available and has been for well over a decade.  Unfortunately, they own the TM for "Your browser, your way" in the browser space.  You don't need to register a trademark, you only need to begin using it and append "tm" to whatever IP you're claiming to be your trademark.  This of course only applies to the US and not the EU.  I'm unfamiliar with the EU laws regarding trademarks or IP.

**Comment by darkvergus** [comment]
> https://www.uspto.gov/trademarks/basics/what-trademark
> 
> Pale Moon is globally available and has been for well over a decade. Unfortunately, they own the TM for "Your browser, your way" in the browser space. You don't need to register a trademark, you only need to begin using it and append "tm" to whatever IP you're claiming to be your trademark. This of course only applies to the US and not the EU. I'm unfamiliar with the EU laws regarding trademarks or IP.

again TM is for common law trademark which is region based aka works on his region thats it

**Comment by RayZ3R0** [comment]
The phrase "Your Browser, Your Way", is extremely generic, its too weak to even be considered for a trademark, and you do not even have a legal trademark so its even weaker.

**Comment by NOCanoa** [comment]
what is big thing about it its a slogan, and by tecnicality if it was "Your Browser. Your Way." it would be diferent so it woldent be trademaked by u corect ( from ur point of view)?

**Comment by TheRealMG** [comment]
> https://www.uspto.gov/trademarks/basics/what-trademark
> 
> Pale Moon is globally available and has been for well over a decade. Unfortunately, they own the TM for "Your browser, your way" in the browser space. You don't need to register a trademark, you only need to begin using it and append "tm" to whatever IP you're claiming to be your trademark. This of course only applies to the US and not the EU. I'm unfamiliar with the EU laws regarding trademarks or IP.

"If you want stronger, nationwide rights, you’ll need to apply to register your trademark with us." Even in the case you're trying to apply it as, common law isn't even nationwide within the US. It would be region-locked. They point this out in the very article you link to.

**Comment by iamoverrated** [comment]
> > https://www.uspto.gov/trademarks/basics/what-trademark
> > Pale Moon is globally available and has been for well over a decade. Unfortunately, they own the TM for "Your browser, your way" in the browser space. You don't need to register a trademark, you only need to begin using it and append "tm" to whatever IP you're claiming to be your trademark. This of course only applies to the US and not the EU. I'm unfamiliar with the EU laws regarding trademarks or IP.
> 
> again TM is for common law trademark which is region based aka works on his region thats it

Yeah, which is global at this point and includes the US.  Most major Linux distros have been including a copy of Pale Moon in their repos for over a decade (some even shipping as a pre-installed app).  It's ubiquitous in the US.  Just because the developer lives in Sweden doesn't mean they can't trademark a phrase associated with their product in the US. 

>"If you want stronger, nationwide rights, you’ll need to apply to register your trademark with us." Even in the case you're >trying to apply it as, common law isn't even nationwide within the US. It would be region-locked. They point this out in >the very article you link to.

You're taking that way out of context.  Common law trademarks do apply nationwide and are supported by the "Date Of First Use Anywhere vs. Date Of First Use In Commerce" clause.  Again, you don't need to register a TM with the US patent office.  You get broader protection and and an easier avenue for legal issues, but if this were to go to court, it basically falls under "Date of first use", which Pale Moon definitely has.

https://www.uspto.gov/trademarks/laws/dates-use

**Comment by wolfbeast** [comment]
I understand it perfectly fine. Common law trademark is established by using it in connection with your product or organization. Registration provides protection if there is a dispute where first-use is difficult to establish. That isn't the case here. We've used it for over a decade, and there's plenty of proof of use out there, also from third party content we have no control over. There are plenty of examples where common law has overthrown a later-registered trademark by proof of prior use.

We've published the browser in many regions, and claimed the associated trademarks in all the regions we've published. Our US presence is the largest of Pale Moon use globally, to the point where most of our online content uses US English.

I'm aware the mission statement is generic enough that others could reasonably be found to think it up as well. I'm just asking you to not use that particular phrase and say it in a different way, which has not been a problem for other organizations I contacted about this. Pale Moon's entire premise is built around its user customization which is why the phrase was chosen to begin with, to uniquely represent it.

**Comment by darkvergus** [comment]
Considering the owner of the project is based on EU the law applied is EU, which you have to apply for, and as before https://euipo.europa.eu/eSearch/#basic/1+1+1+1/100+100+100+100/palemoon

You have no registration.

**Comment by NOCanoa** [comment]
what other organizations have u contacted?

**Comment by darkvergus** [comment]
also for Pale Moon theres one in Ireland which is for drinks https://euipo.europa.eu/eSearch/#basic/1+1+1+1/100+100+100+100/pale%20moon
Is this you?

**Comment by n7itro** [comment]
> I understand it perfectly fine. Common law trademark is established by using it in connection with your product or organization. Registration provides protection if there is a dispute where first-use is difficult to establish. That isn't the case here. We've used it for over a decade, and there's plenty of proof of use out there, also from third party content we have no control over. There are plenty of examples where common law has overthrown a later-registered trademark by proof of prior use.

@wolfbeast the country that the developer of Zen Browser resides in does not recognize common law trademark protection, so common law trademark rights do not apply. The country operates under a "first-to-file" system, which means that trademark rights are acquired only through registration rather than mere use.

May I close this issue?

**Comment by mauro-balades** [comment]
https://github.com/Feodor2/Mypal/issues/3#issuecomment-910700441

Just to be clear, am I also gonna start getting death threats or what

**Comment by wolfbeast** [comment]
> what other organizations have u contacted?

OTTOMH: Vivaldi, Flashpeak (slimjet), The Browser Company (Arc)

> The country operates under a "first-to-file" system, which means that trademark rights are acquired only through registration rather than mere use.

That's unfortunate. In that case I'll have to file in that country (which is that) if I want to protect my rights there. But if you distribute it in countries where common law is recognized there'd still be a conflict.

> May I close this issue?

Obviously you don't need my permission to close it, since you already did so.

**Comment by darkvergus** [comment]
1. Let me see if you understand something, even if you file now, theres nothing that can be done since the phrase was already in use.
2. The distribution is done in wherever the server for download is located even if the user is in the US, so theres nothing that can be done.

**Comment by RealmyTheMan** [comment]
> > what other organizations have u contacted?
> 
> OTTOMH: Vivaldi, Flashpeak (slimjet), The Browser Company (Arc)
> 
> > The country operates under a "first-to-file" system, which means that trademark rights are acquired only through registration rather than mere use.
> 
> That's unfortunate. In that case I'll have to file in that country (which is that) if I want to protect my rights there. But if you distribute it in countries where common law is recognized there'd still be a conflict.
> 
> > May I close this issue?
> 
> Obviously you don't need my permission to close it, since you already did so.

This is insanely childish.

**Comment by wolfbeast** [comment]
@darkvergus if you're talking about entirely different product classes then there is no conflict, obviously.

**Comment by darkvergus** [comment]
glad we established that, theres no conflict end of discussion.

**Comment by n7itro** [comment]
@wolfbeast 
> In that case I'll have to file in that country (which is that)

We will not be disclosing personal information about the developer. Do note that he is not required to do so

> But if you distribute it in countries where common law is recognized there'd still be a conflict.

This is false. Trademark law only applies to where the developer is located. That is how laws work.

**Comment by wolfbeast** [comment]
> Trademark law only applies to where the developer is located. That is how laws work.

False. If you distribute your product elsewhere you must abide by the laws where you distribute the product to.

But I'm not here to provide legal education.

**Comment by NOCanoa** [comment]
@wolfbeast the slogan u refereing to is located where on zen?

**Comment by darkvergus** [comment]
It isn't, its on the main page which btw is not even in this repo. Hes a bit confused thats all.

**Comment by AMA2581** [comment]
Sue them like nintendo does

**Comment by mauro-balades** [comment]
It's a pretty cool slogan, I'll give you that

**Comment by n7itro** [comment]
@mauro-balades I suggest the thread is locked.

**Comment by RealmyTheMan** [comment]
> > Trademark law only applies to where the developer is located. That is how laws work.
> 
> False. If you distribute your product elsewhere you must abide by the laws where you distribute the product to.
> 
> But I'm not here to provide legal education.

what you sound like https://streamable.com/2i8xxt

**Comment by RayZ3R0** [comment]
The owner of zen didnt even know pale moon existed lmao 💀 the quote is just too generic, you cant even trademark something like that

**Comment by mauro-balades** [comment]
Look @wolfbeast. 

I honestly dont know what's going on, im not a lawyer. But I dont think you registered this phrase anywere and you cant really trademark something by just putting it in a html page. 

Id love to hear from you once you have the needed legal documents for that trademark and the slogan will stay as it is. 

For the future, please feel free to use the "GitHub Discussions" tab or join our discord. Thanks!

Again, im not a lawer. Peace ✌️ (TM)
