### ISSUE TITLE
Google meet

### ISSUE THREAD

**Issue by nuranibrahimli** [zen-browser/desktop#1935]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When i try to connect to the meeting on google meet my browser shutdown

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.7

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
Are you using the flatpack, appimage or tar version?

**Comment by nuranibrahimli** [comment]
I was using appimage. I have now downloaded flatpak. I will check again

**Comment by salamijason** [comment]
Are you still getting this bug on 1.0.1-a.14? Could you please try again on the latest flatpak ver and let me know how it goes?

**Comment by nuranibrahimli** [comment]
Yes, it is working.

**Comment by salamijason** [comment]
Great

**Comment by nuranibrahimli** [comment]
Hello. When I watch a video on Udemy, I want to link to the github codes in
the video. Permission screen is not showing in the popup for Github. It
looks incomplete above. But the allow part appears. I have created an issue
on Github about it.
