### ISSUE TITLE
Misaligned Sidebar Icons in Non-Compact Mode

### ISSUE THREAD

**Issue by nanoraptor** [zen-browser/desktop#1939]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

1)The alignment of icons above the sidebar changes when i switch between compact and non-compact mode. When I am in compact mode the icons aligns themselves correctly in the title bar. But when I am non compact mode the icons move a bit downwards and are not on the same horizontal level as the other title bar icons. This could somewhat be related to #1918 Idk

![376060241-8c5a40d3-8a3b-4bcd-956a-93a637aeddc5.png](https://github.com/user-attachments/assets/be6beab6-880c-4526-915b-9ca2134940bb)

2)The Workspace icon is also not aligned properly in compact mode.

https://github.com/user-attachments/assets/20ed1eed-8b18-493f-8b71-792c29d8a00e

See, those icons have inconsistent padding in compact vs non-compact mode. As you can see the icons are a bit lower in non compact mode and are perfectly leveled in compact mode. And you can see the state of the workspace icon as well.

3)In Private browsing mode. An unknown icon-like thing stays on the side bar
![image](https://github.com/user-attachments/assets/4e1666d8-ac9e-480a-b26f-a3b716c7b652)
Edit: I just found out that is my workspace button. The default behaviour must be that it should not be visible in private browsing mode/visible completely. 

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.8 (64-bit) (Generic/Non-Portable)

### What platform are you seeing the problem on?

Windows

**Comment by salamijason** [comment]
Are you still having issues with the alignment?

**Comment by salamijason** [comment]
No response in 3 days, will be closing this issue. Please reopen if you are still facing this issue.
