### ISSUE TITLE
Line separator Between Pinned and Non-Pinned tabs are not showing in non-compact mode

### ISSUE THREAD

**Issue by nanoraptor** [zen-browser/desktop#1940]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![image](https://github.com/user-attachments/assets/0af8271d-b742-4f75-935e-ef8eafe32bf9)
![image](https://github.com/user-attachments/assets/a9fafb22-c737-403c-84d0-fc691f7847b3)
The Line separator disappears in non-compact mode

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.7 (64-bit) (Generic/Non-Portable)

### What platform are you seeing the problem on?

Windows

**Comment by nanoraptor** [comment]
In the latest version, this issue is now solved. Many thanks to @mauro-balades

**Comment by mauro-balades** [comment]
No!
