### ISSUE TITLE
Tabs are loading off from memory

### ISSUE THREAD

**Issue by bhaumik-tripathi** [zen-browser/desktop#1947]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

After, the most recent update, the tabs in a window are getting off from the memory after a certain time, Means if I have five tabs open and I am working on one of them for long time, after a certain duration the other tabs are somehow loading off from memory, so on clicking them again, reload the pages rather than remembering them. This functionality is good for low memory usage but slows the workflow at times, I want to have the last 5 tabs visited to be always loaded in the memory. I think there should be some way to do it from `about:config` but not sure.
I have not checked the issue in firefox(left it using :) )

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.7 

### What platform are you seeing the problem on?

Linux

**Comment by yoshijulas** [comment]
There is an option to disable it or add more time, is in Settings -> Tab Managment -> Tab Unloader
