### ISSUE TITLE
The selected tab moves from one workspace to another.

### ISSUE THREAD

**Issue by LanceStark** [zen-browser/desktop#1949]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When you are on a tab in a defined workspace and switch to another workspace, the tab also changes workspaces.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.7

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by mauro-balades** [comment]
May I ask if the tab was pinned?

**Comment by LanceStark** [comment]
> May I ask if the tab was pinned?

The tab wasn't pinned. I'll try to screenshot the bug the next time it will appears. Let me know if you want some specific informations. i'm at your disposal.

**Comment by mauro-balades** [comment]
Thanks a lot!

Yeah, a screenshot/recording would be very useful

**Comment by kristijanribaric** [comment]
@LanceStark  any updates on this? 
Also try to update the browser to 1.0.1-a.8, it may be resolved as a side effect of workspaces rewriting.

**Comment by K4zoku** [comment]
I also have this issue, but I want it to be a feature. It would be great if, when you activate it, you could move the focused tab to a new workspace, and then turn it off to go back to the old workspace without bringing that tab back. It would be really convenient to use the browser this way just with the keyboard.

By the way, I also don't know the steps to reproduce this issue; it just happens randomly. The temporary fix is to restart the Zen browser.

Edit 2: I just found another temporary solution, which is to create a new workspace.

Edit 3: I am using 1.0.1-a.8

**Comment by mr-cheffy** [comment]
Ill move this issue into https://github.com/zen-browser/desktop/issues/2299
