### ISSUE TITLE
[Windows]-[UI Issue]-pinned tabs separator display issue

### ISSUE THREAD

**Issue by zJohnWick** [zen-browser/desktop#195]
### What happened?

I have noticed two issues regarding pinned tabs separator. 

Issue 1: Tabs separator only displays if I unpin, pinned tab. Tabs separator should be displayed when I pin, normal tab.
https://github.com/user-attachments/assets/7c64add2-1a9b-4390-828e-b5715b4dc07d

Issue 2: Pinned tabs automatically unpin when I close the browser. Pinned tabs should be stayed as pinned tabs even if I close the browser.
https://github.com/user-attachments/assets/b1243bc7-60b7-44ea-9891-8cfffa85651e

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Alpha build - 1.0.0-a.15 (2024-08-07)

### Severity impact

Medium

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
2. It's not that they aren't unpined, it's just an UI issue, will fix right away

**Comment by mauro-balades** [comment]
Both fixed with https://github.com/zen-browser/desktop/commit/1553348812557be77196b0d503949f470c2cd5a2, for the next release!

**Comment by zJohnWick** [comment]
Thank you.
