### ISSUE TITLE
Extensions must be disabled and re-enabled on every launch for them to work properly

### ISSUE THREAD

**Issue by juls0730** [zen-browser/desktop#1950]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When I close Zen Browser and re-open it, extensions that I have installed stop working, and arent in the extension dropdown. If I go to the extension page (or click on the extensions puzzle piece in the toolbar) and disable and re-enable every extension, they start to work as expected.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.5

### What platform are you seeing the problem on?

Linux

**Comment by sjclayton** [comment]
Not able to reproduce this, also on Linux using Zen 1.0.1-a.7

**Comment by juls0730** [comment]
ok, updating to the latest alpha with the Aur as opposed to the app image, it *seems* to have gone away, thanks
