### ISSUE TITLE
High CPU usage on some websites

### ISSUE THREAD

**Issue by pinage404** [zen-browser/desktop#1953]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Hello,

When some pages have focus (e.g. the home page of Zen Browser) it uses many CPU

When focusing other page, the CPU go back to normal usage

[Enregistrement d'écran_20241007_151140.webm](https://github.com/user-attachments/assets/9644d489-cb62-45f8-98a7-339e558e4eb0)

I have the same behavior with Firefox 131.0

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.6

### What platform are you seeing the problem on?

Linux

**Comment by pinage404** [comment]
When disabling the animation in the title, the CPU usage back to normal

This is maybe related to this issue https://bugzilla.mozilla.org/show_bug.cgi?id=759342

Maybe this issue is more an issue related to the website ?

**Comment by busybox11** [comment]
Can you confirm GPU acceleration is working properly and reporting as expected in `about:support`?

Had a similar issue when configuring my new Arch install and ended up needing some drivers and config tweaks to make everything work properly with Wayland - WebRender wasn't being utilized.

**Comment by mauro-balades** [comment]
Animation in the title?

**Comment by mauro-balades** [comment]
Oh, you mean the website's title?

**Comment by pinage404** [comment]
I'm talking about this animation 
![image](https://github.com/user-attachments/assets/aabd4d08-f1ea-48f4-a0ea-604f612d45d0)

**Comment by pinage404** [comment]
> Can you confirm GPU acceleration is working properly and reporting as expected in `about:support`?

I don't know what / how to check specifically

<details>

<summary>heaving screenshot</summary>

![image](https://github.com/user-attachments/assets/21661534-7af5-4c3e-8f2d-65fa742cd600)

</details>

**Comment by busybox11** [comment]
It is using WebRender which means HW Accel should be working. Try to check using radeontop if it does increase GPU usage when rendering this page. If that's not the case, means something is eating CPU anyway for web rendering.

**Comment by atharva-p** [comment]
> Can you confirm GPU acceleration is working properly and reporting as expected in `about:support`?
> 
> Had a similar issue when configuring my new Arch install and ended up needing some drivers and config tweaks to make everything work properly with Wayland - WebRender wasn't being utilized.

i've had this issue too (specially with apple dot com/iphone16) where it would try to animate, and then just give up and render without animating, and the RAM usage would shoot up drastically (more than 2GB extra). tried the same page on firefox, and firefox does not even try to animate (normal RAM usage). i am on linux mint

**Comment by pinage404** [comment]
On the left, Zen showing https://zen-browser.app

On the top right `radeontop` which seems stable

On the bottom right `nvtop` which show that about 30% of GPU is used when the animation is played

[Enregistrement d'écran_20241009_221757.webm](https://github.com/user-attachments/assets/2b12ca36-b4fa-4340-922e-b0c3540d6806)

**Comment by mauro-balades** [comment]
Ill move this issue to the website's repo then. THanks!

**Comment by busybox11** [comment]
I'm not sure this is a website issue as I can reproduce this behavior on my machine - it looks like more of a Firefox issue than a website issue. Comparing to Chrome, Firefox seems less performant on my machine.

![image](https://github.com/user-attachments/assets/a6fb247b-895d-419d-8839-8256e4e756e3)

This (awful, I'm sorry) graph roughly shows GPU usage on both browsers. 

Overall I've had far worse performance on almost all sites where it can make a difference with Firefox (and, by extension, Zen). Not sure if this is a bug at all.
