### ISSUE TITLE
Right-clicking in settings triggers all context menus

### ISSUE THREAD

**Issue by StRonKEA** [zen-browser/desktop#1954]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When I copy text, all the right-click menus become active when I right-click within the settings area to paste the copied text.

https://github.com/user-attachments/assets/4c0eab71-8362-47c9-89f1-81c69d31ae2f

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.7 (64 bit)

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
Are you sure this isnt because of a mod installed?

**Comment by StRonKEA** [comment]
> Are you sure this isnt because of a mod installed?

no mode is not installed

![Ekran görüntüsü 2024-10-07 200958](https://github.com/user-attachments/assets/e9c16eb9-4258-4872-a24d-3da85ba803c6)

**Comment by darkvergus** [comment]
these are extensions not mods you can find the mods in the settings

**Comment by StRonKEA** [comment]
I am aware of what extensions and mods entail. The installed extensions were shared merely for informational purposes. There are no mods installed. The sole modification I made to the browser was through extensions, yet even after a clean installation, I am facing the same issue.

**Comment by darkvergus** [comment]
But yes i can also confirm this happens when going into settings > Privacy & Permissions > selecting any permissions and right clicking on the select website textbox

**Comment by StRonKEA** [comment]
Thank you for checking and verifying

**Comment by RayZ3R0** [comment]
Does this still happen on latest version? (a.14 as of this comment)

**Comment by StRonKEA** [comment]
> Does this still happen on latest version? (a.14 as of this comment)

No, there is no such problem anymore

**Comment by RayZ3R0** [comment]
Alright, will be closing this issue then. Thanks for reporting
