### ISSUE TITLE
Slogan Suggestions

### ISSUE THREAD

**Issue by GOvEy1nw** [zen-browser/desktop#1955]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Just dropping you some alt slogan suggestions for you, if you are worried and want to change, because that guy irked me... Not saying these slogans are amazing by any means, but just wanted to show support.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
Suggestions:

Browse with Balance
Browsing, Perfectly Balanced
Effortless Browsing, Infinite Possibilities
Find Focus in Your Flow
Serenity in Every Tab
The Art of Seamless Surfing
Fast, Focused, and Fully Yours
Designed for You, Not Your Data
```

**Comment by mauro-balades** [comment]
ngl, I really like `Fast, Focused, and Fully Yours`
