### ISSUE TITLE
can click on the space around workspaces as if its a buton

### ISSUE THREAD

**Issue by neurokitti** [zen-browser/desktop#1959]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

https://github.com/user-attachments/assets/05344d54-a60c-44da-9ab9-6e604ccc96d9

you can click on the area around the workspaces. i don't think this is intended and if it is it doesn't do anything and is really anoying.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.7

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
I dont really get what's wrong sorry

**Comment by neurokitti** [comment]
> I dont really get what's wrong sorry

the issue is that you can click the area around the icons and its acts like a button but does not do anything. its not a major issue but its kinda funky.

**Comment by kristijanribaric** [comment]
What do you mean it "acts like a button"? If it doesn't do anything on click and the cursor doesn't change to a pointer, how exactly is it like a button?

**Comment by neurokitti** [comment]
> What do you mean it "acts like a button"? If it doesn't do anything on click and the cursor doesn't change to a pointer, how exactly is it like a button?


https://github.com/user-attachments/assets/0210b674-d2f2-4af6-bb83-800755f610b3

like the area around it acts like a button. it doesnt do anything. in this video i can click on it and it shifts the icons but im clicking on any of the icons. 

i know if you right click on that area it does the pop up but regular click just plays the litle animation as if it does somthing but it doesnt

**Comment by kristijanribaric** [comment]
Oh I see
Are you sure it's not caused by your custom userChrome? Please try creating another temporary profile and see if it's happening there

**Comment by neurokitti** [comment]
> Oh I see Are you sure it's not caused by your custom userChrome? Please try creating another temporary profile and see if it's happening there

I just checked and your right its an issue with one of my zen mods:
![image](https://github.com/user-attachments/assets/23acf344-be04-48d5-9a02-baae171c4efe)

mb
well new issue is that zen mods are still listed as themes in the buton lol it says "remove theme"
