### ISSUE TITLE
[Windows]-closed tabs appear again

### ISSUE THREAD

**Issue by zJohnWick** [zen-browser/desktop#196]
### What happened?

Issue: I closed few tabs and close the browser. Open the browser again and closed tabs appear again.
https://github.com/user-attachments/assets/f2b618fc-3e5a-40b0-966d-72a3db51ef4e

Expected Result: Closed tabs should not appear again. 

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Alpha build - 1.0.0-a.15 (2024-08-07)

### Severity impact

High

### What platform are you seeing the problem on?

Windows

**Comment by jimfr** [comment]
Also reported on Mac: https://github.com/zen-browser/desktop/issues/187
