### ISSUE TITLE
Installing a mod from the marketplace will not reload the mods list in browser settings

### ISSUE THREAD

**Issue by busybox11** [zen-browser/desktop#1961]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Title says it all.

1. Open the settings and go to the "Zen Mods" section
2. Then, install a mod from https://zen-browser.app/themes
3. Go back to the settings tab you opened

The newly-installed mod shouldn't appear until you manually refresh that settings tab.

Similarly, when you remove a mod from the website, it isn't automatically removed from the list, and will stay in the list even after being removed if you try turning it off and back on again without reloading.

https://github.com/user-attachments/assets/58ed1797-c673-4fd3-8fc2-41dec127d6bb

(Hope this isn't a duplicate, tried searching for a similar issue but didn't see one. Apologies if it is!)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.7

### What platform are you seeing the problem on?

Linux, macOS - aarch64

### Relevant log output

```shell
N/A
```

**Comment by mauro-balades** [comment]
This has been fixed in the next version, thanks a lot!

**Comment by busybox11** [comment]
Thanks to you for the hard work!

Has been awesome to use as a daily driver coming from a Mac with Arc to Linux with Zen!
