### ISSUE TITLE
Web panels displaying a blank screen when opened in split view.

### ISSUE THREAD

**Issue by TheJPMZ** [zen-browser/desktop#1962]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When attempting to open the web panel container in **split view**, the panel only displays a blank screen. This issue occurs regardless of the webpage or content attempted to be loaded into the panel. The problem occurs no matter what pages are loaded in split view. 

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.7 64 bits

### What platform are you seeing the problem on?

Windows

**Comment by RayZ3R0** [comment]
Tried to reproduce this, did not have this issue. Maybe it was fixed on the newer versions, please try again after updating. Reopen this issue if it still happens, thanks for reporting
