### ISSUE TITLE
Not really any bug report or an issue, just genuine question.

### ISSUE THREAD

**Issue by coffeescrpt** [zen-browser/desktop#1963]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Is there a way to get rid of cookies / usage  / history data from stored files (like a cleanup) only for a specified website? By doing so I wish to get rid completely of everything related to one service (auto-suggestion, usage data etc) but have got no clue how I could achieve it. I am sorry for wasting your time with such a question.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.7

### What platform are you seeing the problem on?

Windows

**Comment by sjclayton** [comment]
@coffeescrpt 

You can accomplish what you want by clicking the lock icon on the far left of the URL bar and choosing the option `Clear cookies and site data` when you're on the site you want to clear, and then close the tab for that site. 

If you revisit the same site you'll notice everything is reset, so you'd have to login again if it was a site you were signed into.

Hope this helps!! 😄

**Comment by coffeescrpt** [comment]
That works, thanks. I also found a way to do this using built in history manager within Mozilla (Using CTRL + SHIFT + H)
