### ISSUE TITLE
Closing Tabs opened from SidePanel renders the browser unusable 

### ISSUE THREAD

**Issue by MannixMD** [zen-browser/desktop#1966]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When you closed a tab from open a link open from sidepanel it breaks the browser rendering it unusable. You can't open new tab you just get a blank window. This started happening in 1.0.1-a.7 all the previous versions worked fine.

![broken](https://github.com/user-attachments/assets/e7423f2e-7bf0-43f5-af32-a4dd289f0507)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.7 

### What platform are you seeing the problem on?

Windows

**Comment by sjclayton** [comment]
I have also encountered this in Linux on 1.0.1-a.7
