### ISSUE TITLE
Persisting sessions or at least notifications from multiple web apps and loading at startup. 

### ISSUE THREAD

**Issue by mikedlr** [zen-browser/desktop#1968]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

I would like to have gmail, matrix etc load at startup and then send notifications to the desktop when they choose. I tried to set this up an it seems not to be a supported option. I thought the sidebar might be useful for this but it seems that apps only load after they are first used and also that some apps (gmail - non mobile version) need full screen acccess so don't fit there. 

What would be nice would be to have an ability to pre-load some tabs in the backgound and have that work with both mobile and desktop apps. 

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.7 (64-bit0

### What platform are you seeing the problem on?

Linux

**Comment by mikedlr** [comment]
BTW; apologies if this is the wrong place to put an enhancement request. The bug form talks about instructions but I couldn't find them. Reading the FAQ says to report enhancements in the bug tracker.

**Comment by mikedlr** [comment]
For firefox the feature that *almost* delivers this is pinned tabs but there are two issues
* configuration is quite limited and mostly done by pinning in a particular state
* pinned tabs can be lost (not checked with Zen yet) 
There are extensions like tab managers which help with this in firefox - https://superuser.com/questions/1825979/firefox-loses-pinned-tabs

**Comment by mikedlr** [comment]
Okay, google searching found me a bunch of stuff

* https://www.reddit.com/r/zen_browser/comments/1ffa7gk/permanently_pin_tabs/
* https://www.reddit.com/r/zen_browser/comments/1fyvd8x/about_pinned_tabs/


And most of the configuration limits (use a particular container / start at one particular URL etc.) seem to be under discussion. Great. There's [quite a bit more discussion](https://www.reddit.com/r/zen_browser/search/?q=pinned&type=link)  on the [Reddit sub](https://www.reddit.com/r/zen_browser/)  generally so it seems this is very much in progress. Great. Thanks.

**Comment by BrhmDev** [comment]
> BTW; apologies if this is the wrong place to put an enhancement request. The bug form talks about instructions but I couldn't find them. Reading the [FAQ says to report enhancements](https://github.com/zen-browser/docs/blob/9d68285b786aa8c668000f811d3075f81dd73e68/content/faq.md#where-do-i-recommend-features) in the bug tracker.

Seems like the faq is outdated, feature requests should be made in https://github.com/zen-browser/desktop/discussions
