### ISSUE TITLE
[Windows]-private window opens with two tabs

### ISSUE THREAD

**Issue by zJohnWick** [zen-browser/desktop#197]
### What happened?

Issue: When I open private window, it comes with two empty tabs and one tab unable to click also.
https://github.com/user-attachments/assets/d396ba8d-7143-4bc8-999c-731a410814e3

Expected Result: Private windows should open with one empty tab.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Alpha build - 1.0.0-a.15 (2024-08-07)

### Severity impact

High

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
This has been fixed for the next release, Thanks!.

Please use the appropriate tags next time, thanks

**Comment by zJohnWick** [comment]
Okay noted. Thanks
