### ISSUE TITLE
Resizing window doesn't work correctly with collapsed sidebar

### ISSUE THREAD

**Issue by nhumrich** [zen-browser/desktop#1971]
### Captchas

- [ ] I have read the instructions.
- [ ] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

If the browser sidebar is collapsed, resizes do not work correctly. Not only does the sidebar not correctly resize, but content on the page doesn't trigger a repaint either. In fact, if you shrink the window height, you can't even scroll to the bottom of the page because it is cut off.

This is especially frustrating when moving between vertical monitors to a horizontal monitor.

This only happens with a collapsed sidebar.

![Recording 2024-10-08 091935](https://github.com/user-attachments/assets/16dd2f0f-4793-471b-8484-1f62526eb30d)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.7 (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by nhumrich** [comment]
Edit: Originally, I had mentioned this was due to "compact mode", but that was incorrect. It's actually for a collapsed sidebar. I updated the post.

**Comment by BrhmDev** [comment]
Can't reproduce, is this still an issue in the newest version?

**Comment by neonfuz** [comment]
Yes can confirm it is still an issue

OS: MacOS Sequoia
Zen: 1.0.1-a.9

**Comment by nhumrich** [comment]
Just updated and is still an issue.
current version: 1.0.1-a.9 (64-bit)

**Comment by nhumrich** [comment]
Also still an issue on 1.0.1-a.10 (Firefox 130.0) (64-bit)

**Comment by mr-cheffy** [comment]
Any mods/userChrome.css?

**Comment by nhumrich** [comment]
This appears to be fixed in a.12

**Comment by salamijason** [comment]
bro its fixed?
