### ISSUE TITLE
Right sidebar shake/jitter

### ISSUE THREAD

**Issue by AndreaSoranzo** [zen-browser/desktop#1973]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

In compact mode, when the cursor hovers over the hidden sidebar on the right, the sidebar itself starts to shake and closes automatically when the cursor stops.

https://github.com/user-attachments/assets/68ad86ac-a182-4737-98a4-cb1e60069c8e

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.7

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
Fixed for the next release, thanks a lot!
