### ISSUE TITLE
"Welcome to Zen Browser" message pops up every time you open the browser [Twilight]

### ISSUE THREAD

**Issue by neurokitti** [zen-browser/desktop#1978]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

every time I open up the browser (the Twilight version) a tab pops up as if it was my first time:
![Screenshot 2024-10-08 213056](https://github.com/user-attachments/assets/5cafc59f-378b-4c36-83fb-16470dc71147)

I am not sure where i am supposed to put issues specificaly for the twilight version pls let me know!
### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.7 (Twilight)

### What platform are you seeing the problem on?

Windows

**Comment by BrhmDev** [comment]
Is this still an issue in twilight or stable?

**Comment by mr-cheffy** [comment]
This is because the browser is updated almost daily… you can disable automatic updates if you want

**Comment by neurokitti** [comment]
> This is because the browser is updated almost daily… you can disable automatic updates if you want

Wait so it's supposed to welcome you to zen every time it gets an update?
