### ISSUE TITLE
Major issue with zen sidebar disapering and not re-appearing on restart [Twilight]

### ISSUE THREAD

**Issue by neurokitti** [zen-browser/desktop#1979]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The side bar has a bug where the content does not render most of the time and if you try to pin the zen sidebar it will glitch out and stop rendering. its still there and can be adjusted but its not visable, it flickers into exisitance only in the opening and closing animation and it does not re-appear on restart. this appears to only be an issue on the twilight version though.

https://github.com/user-attachments/assets/e451d459-080f-4e94-b6c2-89ae4acfa4f6

at the end of the video i am trying to click the unpin buton which bring it back again but its hard to hit. i was able to get it working though after the recording ended.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.7 (Twilight)

### What platform are you seeing the problem on?

Windows

**Comment by BrhmDev** [comment]
Fixed after  1.0.1-a.8 release.
