### ISSUE TITLE
[Windows]-settings menu can be more compact

### ISSUE THREAD

**Issue by zJohnWick** [zen-browser/desktop#198]
### What feature would you like to see?

In my opinion, the settings menu icons and fonts, space for each setting is too much. It takes too much space to open. It can be more compact. 
![image](https://github.com/user-attachments/assets/303ba7dc-c719-4152-a254-bfec7fb0cca5)

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
We don't have any plans on changing this at the moment, if that's ok with you.

**Comment by zJohnWick** [comment]
yeah alright!
