### ISSUE TITLE
ALL pinned tabs eraised when reopening Zen [Twilight]

### ISSUE THREAD

**Issue by neurokitti** [zen-browser/desktop#1980]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

so essentialy if a tab was pinned before getting the update with the new pinned tabs feature it will disapear if the browser is closed.

this is also the case for closing a tab with ctrl + W when this is the pinned tab settings

![image](https://github.com/user-attachments/assets/d522142b-4e97-4bad-8148-b6c3cec48dfa)

this seems to stem from the issue that only tabs that have had there URL replaced with the curent one actualy save. if i try to use ctrl + W it just resets the tab to be blank and the title becomes null so esentialy all old tabs didnt have a original url to return to so it bugs out.

this goes for all the pinned tabs that have not been updated if the "restore pinned tabs to original pinned url on startup" is ticked becuase unless the tab is updated it has no saved original url.

this is what happend:
![Screenshot 2024-10-08 214348](https://github.com/user-attachments/assets/c1e1adbf-8073-4062-863b-babb37c4198a)
![Screenshot 2024-10-08 214422](https://github.com/user-attachments/assets/1823834d-8ef3-48a1-bb5b-5b67d340ea3a)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.7 (Twilight)

### What platform are you seeing the problem on?

Windows

**Comment by kristijanribaric** [comment]
Fixed for the next release. Thanks for comprehensive report!
