### ISSUE TITLE
[Bug] [Flathub] [Ubuntu 24.04] Zen Browser Not Opening After Installation

### ISSUE THREAD

**Issue by alamriku** [zen-browser/desktop#1982]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

- Operating System: Ubuntu 24.04
- Browser Version: Installed Zen Browser from Flathub
- Problem:
  - After installation, the Zen Browser icon appeared in the app list.
  - When I click the icon, the browser shows a loading indicator, but after a few minutes, nothing happens and the browser doesn’t open.

Steps Taken:

- Installed Zen Browser from Flathub (installation showed successful).
- Clicked on the Zen Browser icon from the apps list.
- Expected Behavior: Zen Browser should open normally. Actual Behavior: Browser doesn't open after clicking, just shows a loading on cursor for a while and then stops.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
ldconfig failed, exit status 256
```

**Comment by hiddenblue** [comment]
It 's better to download the appimage specific and upgrade manually. The appimage update moch more frequently. But you need to chmod +x for the appimage file and add a desktop shortcut for it.

**Comment by Samueru-sama** [comment]
> It 's better to download the appimage specific and upgrade manually. The appimage update moch more frequently. But you need to chmod +x for the appimage file and add a desktop shortcut for it.

Zen has an script that lets you install the AppImage. 

However I prefer using this: https://github.com/ivan-hc/AM

it installs the zen appimage by simply doing `am -i zen-browser` or `appman -i zen-browser` and also if you install appimageupdatetool you get delta updates when doing `am -u` (that is it doesn't download the entire appimage again).

**Comment by mr-cheffy** [comment]
This is actually a flatpak issue. Please report it to them, it happens to me on any application I install through it. Thanks!

You can still open it from the apps menu
