### ISSUE TITLE
Cant update browser because of "potential security issue".

### ISSUE THREAD

**Issue by Vatnar** [zen-browser/desktop#1986]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

It says ![image](https://github.com/user-attachments/assets/45f12b60-5c6a-4f7b-bab2-a0274cda1fe2)
I can't see how to fix this and i dont see it mentioned anywhere

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.5

### What platform are you seeing the problem on?

Windows

**Comment by salamijason** [comment]
Hey do you still get this now when trying to update?

**Comment by Vatnar** [comment]
> Hey do you still get this now when trying to update?

Yup, i decided to go back to firefox

**Comment by salamijason** [comment]
Could you try loading the site on a different browser? Trying to figure out if it's a site or browser issue.

**Comment by Vatnar** [comment]
> Could you try loading the site on a different browser? Trying to figure out if it's a site or browser issue.
Same message from my phone.

**Comment by salamijason** [comment]
If the issue persists not only on zen but also on your phone or other browsers, then it is likely not an issue from Zen's side but probably some type of firewall issue on your end!

**Comment by salamijason** [comment]
You can try to download the latest version of Zen from this GitHub repo instead of going to the Zen website.

**Comment by Vatnar** [comment]
> If the issue persists not only on zen but also on your phone or other browsers, then it is likely not an issue from Zen's side but probably some type of firewall issue on your end! 
> 
> 

It's not. Its firefox itself blocking it

**Comment by Vatnar** [comment]
https://zen-browser.app has a security policy called HTTP Strict Transport Security (HSTS), which means that Firefox can only connect to it securely. You can’t add an exception to visit this site.
