### ISSUE TITLE
Hydration errors from React server-side rendering in Remix apps

### ISSUE THREAD

**Issue by amatho** [zen-browser/desktop#1987]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When loading web pages built with [Remix](https://remix.run), and probably other kinds of React apps with server-side rendering, there are several hydration errors in the JavaScript console. To see an example, go to Remix's own website and open the developer tools. (Alternatively, go to a website [listed here](https://remix.run/showcase) if there are no errors on Remix's website.) This issue is not present in Mozilla Firefox.

Weirdly enough, the issue sometimes disappears when using Private Browsing.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.7

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by mr-cheffy** [comment]
This issue is not related to zen but rather related to Remix. Please report this error to them, they'll be able to help you better
