### ISSUE TITLE
Print tab Rendered incorrecly when web panel is open.

### ISSUE THREAD

**Issue by LND237** [zen-browser/desktop#1989]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![image](https://github.com/user-attachments/assets/b0f0c04e-1cff-4e8a-84dc-724d03a86041)
In this picture You can see the print tab is not loaded correctly when web panel is open and vice versa when I launch the web panel.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1

### What platform are you seeing the problem on?

Windows

**Comment by RayZ3R0** [comment]
Does this still happen in latest version?

**Comment by salamijason** [comment]
No response in 2 weeks, will be closing this issue. Please reopen if issue persists.
