### ISSUE TITLE
Close tabs to the left wording

### ISSUE THREAD

**Issue by eboye** [zen-browser/desktop#1996]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Wording for closing multiple tabs is wrong. Left and right in this context is not correct:

![image](https://github.com/user-attachments/assets/0dcf5067-4f59-4471-b609-048a2e513e94)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.7

### What platform are you seeing the problem on?

Linux

**Comment by nanoraptor** [comment]
It should be "close the tabs above/below" is that what you're saying?

**Comment by sjclayton** [comment]
> It should be "close the tabs above/below" is that what you're saying?

Pretty sure that's the way I'd interpret this, and seems like this should be the correct wording.

**Comment by eboye** [comment]
@nanoraptor yes, but maybe a more generic would be better before/after ??

**Comment by mr-cheffy** [comment]
We *can't* fix this because of how firefox handle's fluent languages. We might in the future but it's not something we can do currently. Really sorry…
