### ISSUE TITLE
Can't share screen

### ISSUE THREAD

**Issue by barqus** [zen-browser/desktop#1997]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I was unable to share my screen using Zen Browser until I installed Firefox and enabled sharing of both Firefox and Zen Browser

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.7

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by BrhmDev** [comment]
How is this specific to zen? Was there something broken in zen that did work in Firefox?

**Comment by salamijason** [comment]
Hey which program were you using to share your screen? Did you have trouble sharing the Zen browser window or the screen itself? Could you give us more detail and maybe a screen recording if possible?

**Comment by salamijason** [comment]
No response in 5 days, will be closing this issue. Please reopen if you are still facing this issue.
