### ISSUE TITLE
customizate secondary toolbar

### ISSUE THREAD

**Issue by Turhvjbufv** [zen-browser/desktop#200]
### What feature would you like to see?

![2024-08-09-16-23-34-955](https://github.com/user-attachments/assets/e4ffdde2-25ed-4900-baa6-d48138e5f349)
Allow customize which icons appear here(like toolbar customization)

### What platform are you seeing the problem on?

Windows

**Comment by AnTheMaker** [comment]
Yes, this would be great!!

**Comment by poiNt3D** [comment]
It would be great if the sidebar would be included on the customize page, when you right click it and choose 'customize'.

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/884

 ~ This is an automatic operation to better enhancements requests organization.
