### ISSUE TITLE
Linux Touchpad Smooth Scrolling

### ISSUE THREAD

**Issue by tranquil-tr0** [zen-browser/desktop#2000]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

In Zen Browser and Mozilla Firefox (no, this issue is not in both, paragraph 2 explains), scrolling on a touchpad is forced to be segmented, as would be expected behavior if the input device was a typical (not smooth scroll) mouse wheel. In Chromium browsers, this scrolling issue is not present (eg: scrolling is pixel-by-pixel at a normal speed in Brave Browser and Chrome).

However, in Mozilla Firefox, you can fix laptop smooth scrolling by passing `MOZ_USE_XINPUT2=1` when launching firefox, and can be made persistent as a setting by running `echo export MOZ_USE_XINPUT2=1 | sudo tee /etc/profile.d/use-xinput2.sh`. As I understand it, zen browser is based on Firefox, so I assume that the issue is the same as the one there.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.7

### What platform are you seeing the problem on?

Linux

**Comment by tranquil-tr0** [comment]
The issue is fixed in Wayland desktop compositor, and is limited to X11.

**Comment by mxmvncnt** [comment]
Maybe not fully related, but on Linux devices, the scroll speed on a touchpad under Wayland is very fast (This is a problem in upstream Firefox, I think it is caused by GTK3). To mitigate this, I have edited the values in about:config to the following:
- `mousewheel.default.delta_multiplier_x` to `20`
- `mousewheel.default.delta_multiplier_y` to `20`
- `mousewheel.default.delta_multiplier_z` to `20`

But those settings break mousewheel scrolling by making it 5x slower, to fix this:
- `mousewheel.min_line_scroll_amount` to `300`

To make the scrolling feel more natural, I also increase `apz.fling_friction` to `0.005`

This would need to be applied only for Linux and Wayland environments, not sure how feasable this is.

**Comment by tranquil-tr0** [comment]
@mxmvncnt (edited to add @-ing)
I am unable to verify whether what you said is true, since my delta multipliers all seem to be set to 100 and my scrolling isn't too fast, with the scrolling becoming very slow at 20 (on second thought, I've set mine to 70).
Also, the issue might be unrelated, since I would assume that the issue is caused by strange touchpad recognition in Wayland (I could totally be wrong) or from some kind of failure to recognize input (which might then be related).
P.S. Thanks for bringing up `apz.fling_friction` though, because that was my one issue with the browser after finally ditching X11 and the flatpak (since I initially didn't know how the portable package worked).

**Comment by RayZ3R0** [comment]
I think this is more of a linux issue, cuz I also had this problem in some apps with scrolling being weird. Is it alright now with what mxmvncnt suggested?

**Comment by tranquil-tr0** [comment]
I can't comment on mxmvcnt's solution, as I did not face the same issue. My solution to the original report was to move to Wayland, which isn't always possible but perhaps makes sense since in my experience the browser doesn't work great on older hardware (which would be a factor preventing on Wayland, it does for me) anyways (I have a roughly 14 year old desktop, on which Zen isn't exactly usable).
Edit: Zen isn't "unusable" (on the older device) but just slower, which I expect anyways since Firefox for some reason runs roughly at 70% the speed of chromium, so I assume it is some kind of a Gecko issue.
