### ISSUE TITLE
Bug/.. Feature Request? Middle-click closes pinned tabs instead of activating the new behavior.

### ISSUE THREAD

**Issue by Kayinnasaki** [zen-browser/desktop#2006]
### Captchas

- [ ] I have read the instructions.
- [ ] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

Middle click closes pins, while Ctrl+W behaves as expected with the new resetting URL behavior. This might be intentional but feels like a strange behavior mismatch. If this is intentional, it feels like something that should have an option associated with it?

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.8

### What platform are you seeing the problem on?

Windows

**Comment by sjclayton** [comment]
@kristijanribaric 

~~Seems like this did not work, as now middle clicking on a pinned tab does nothing, doesn't close or reset.~~

Running 1.0.1-a.9 on Linux

EDIT: It does work, but only if I first reset the pinned URL of each pinned tab manually after the update.

**Comment by kristijanribaric** [comment]
Yes, you have to either re-pin the tabs or click replace pinned url with current

**Comment by sjclayton** [comment]
> Yes, you have to either re-pin the tabs or click replace pinned url with current

Alrighty, I have a feeling this is going to be seen as a bug however.
