### ISSUE TITLE
Browser bottom padding misaligns

### ISSUE THREAD

**Issue by umarhamzy** [zen-browser/desktop#2007]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The bottom part of the browser misaligns when there's an overflow of tabs.
![image](https://github.com/user-attachments/assets/aefe3bd5-7f1d-46af-91fd-784a224fc98d)
![image](https://github.com/user-attachments/assets/bdd0f393-b9ed-4c3a-897b-1ac5f96f9c1d)

Here, you can see 2 workspaces, the above image shows misaligned bottom padding due to tab overflow, the bottom image is the proper bottom padding, without an overflow of tabs.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.8

### What platform are you seeing the problem on?

Windows

**Comment by BrhmDev** [comment]
Can't reproduce. Can you try disabling all mods? If that doesn't work create a new profile and see if it's still a problem.

**Comment by mr-cheffy** [comment]
This has been fixed for the next release, thanks a lot!

**Comment by umarhamzy** [comment]
Unfortunately, this doesn't appear to be fixed

**Comment by umarhamzy** [comment]
@mauro-balades unfortunately, this doesn't appear to be fixed.
