### ISSUE TITLE
With containers enabled, left-clicking on the new tab button brings up a squeezed visually bugged menu

### ISSUE THREAD

**Issue by umarhamzy** [zen-browser/desktop#2009]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Left-click menu
![image](https://github.com/user-attachments/assets/155d077b-a64d-4198-9b0f-ba7fa3d7616a)

Right-click menu
![image](https://github.com/user-attachments/assets/e3812386-5998-44df-bc94-9c3558aac051)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.8

### What platform are you seeing the problem on?

Windows

**Comment by sjclayton** [comment]
Cannot reproduce this on Linux running 1.0.1-a.8, appears as normal here.

**Comment by salamijason** [comment]
Bug could not be reproduced on latest version 1.0.1-a.14. Could you please try again on the latest ver and let me know how it goes?

**Comment by umarhamzy** [comment]
It's fixed with the latest version!
