### ISSUE TITLE
setup issue

### ISSUE THREAD

**Issue by Turhvjbufv** [zen-browser/desktop#201]
### What happened?

 When setting up zen, if you choose to not add it to start menu it still adds the zen-private-browser to there

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a15

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
Where did you choose it from?
