### ISSUE TITLE
Feature: Double-click to close tabs

### ISSUE THREAD

**Issue by ablazewicz** [zen-browser/desktop#2013]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

Zen Browser is great, but I miss one important feature I know from Vivaldi, namely the ability to close a tab with a double click. This would be very convenient, especially on laptops.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.8

### What platform are you seeing the problem on?

Linux, macOS - aarch64, macOS - Intel, Windows

**Comment by kristijanribaric** [comment]
For feature requests, please use [GitHub Discussions](https://github.com/zen-browser/desktop/discussions/new/choose)
