### ISSUE TITLE
Infinite redirection in https://ssh.cloud.google.com

### ISSUE THREAD

**Issue by SanjayBalaji** [zen-browser/desktop#2014]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I have updated to the latest version of the browser : Alpha build - 1.0.1-a.8 (2024-10-10) and found that when I started using Project IDX by google (clicked on one of the project that I am working on), it gets stuck to a white screen in the "Initializing Environment" stage with the url -  "https://ssh.cloud.google.com/devshell/gateway/oauth?authuser=0&state=xxxxxxxxxxxxxxxxxx", with xxxxxxxxxxxxxxx constantly changing every second.

I tried replicating this with other browsers and none of them had this issue. I was working on this project yesterday before updating zen browser and it was fine.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.8 (2024-10-10)

### What platform are you seeing the problem on?

Windows

**Comment by mr-cheffy** [comment]
It works for me, try disabling tracking protection or try going inside a new, fresh profile, see if that works
