### ISSUE TITLE
Sidebar is very thin making stuff not appear correctly

### ISSUE THREAD

**Issue by scanash00** [zen-browser/desktop#2015]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

So basically, the sidebar in compact mode is thin, and its like someone ate a part of it

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

latest

### What platform are you seeing the problem on?

Windows

**Comment by mr-cheffy** [comment]
This has been reported many times, it has been fixed for the next release, thanks!
