### ISSUE TITLE
Feature request: Provide a shortcut to open link in a split view

### ISSUE THREAD

**Issue by aohoyd** [zen-browser/desktop#2019]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

I would like to have a shortcut (`ctrl+click` e.g.) to open a link in a split view

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.7

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by kristijanribaric** [comment]
You clearly have not read the instructions, there is a line that says "For enhancement requests, please use GitHub Discussions."

**Comment by theherk** [comment]
I see this is closed as complete, but I don't have access to the Linear workspace to see what happened. Is there a shortcut for this, or is the feature forthcoming?

**Comment by lfilho** [comment]
@theherk https://github.com/zen-browser/desktop/discussions/9612 and https://github.com/zen-browser/desktop/discussions/2030
