### ISSUE TITLE
Shortcuts have stopped working

### ISSUE THREAD

**Issue by bhaumik-tripathi** [zen-browser/desktop#2024]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I have checked previous issues on shortcuts not working but non of them corresponded to me and everything was working fine for me till now. But the latest update from `1.0.1-a.7` to `1.0.1-a.8` has stopped the actions of `Ctrl+w` and `Ctrl+t` (these I use the most ) even after hover data on the new tab button still points to these shortcuts.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.8

### What platform are you seeing the problem on?

Linux

**Comment by bhaumik-tripathi** [comment]
`Ctrl+F` (find) is also not working.

**Comment by mauro-balades** [comment]
It works perfectly for me. Did you change them to something else?

**Comment by sjclayton** [comment]
Working fine here on Linux for me on 1.0.1-a.8, both `Ctrl-W` and `Ctrl-T` work as expected.

**Comment by bhaumik-tripathi** [comment]
I am sorry, I don't know but a complete restart fixed the issue, I did the restart from the prompt screen(Which says "To continue using zen, Restart") after the upgradation, seems like it didn't end well, doing the restart again manually fixed the issue.

**Comment by kuspoes** [comment]
⌘ + Q on Mac doesn't close window only blinking the Zen Menu, another shortut work smoothly. 

![ScreenRecording2024-10-13at21 53 43-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/2285d4ca-f2ec-4b3a-9787-18c51054cdab)
