### ISSUE TITLE
Side TABS

### ISSUE THREAD

**Issue by Jeetkunndo** [zen-browser/desktop#2027]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I dont Like Side Bar for my tabs, cant figure out a way to change it, so doesnt matter how amazing or secure is the browser if i cant  put my tabs where normally use it on every other browser, the browser sucks
dont try to  reinvent the  wheel tab on the side are anoying and confusing
![Screenshot](https://github.com/user-attachments/assets/786f0fb3-1f7f-4f66-bed5-3a1a38113b10)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.8

### What platform are you seeing the problem on?

Linux

**Comment by BrhmDev** [comment]
This should be a feature request, there is currently one open https://github.com/zen-browser/desktop/discussions/889 (although this is currently not planned)
