### ISSUE TITLE
Title: Window Size Not Retained After Reopening the Application

### ISSUE THREAD

**Issue by FrancisMorelli** [zen-browser/desktop#2029]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I’ve encountered an issue with window sizing in Zen Browser on my MacBook Air running macOS 15.0.1. I like to use the app fully expanded, filling my entire desktop space. However, after I close the app and reopen it, the window size is not retained as I left it. Instead, it reduces in size, leaving an empty vertical space on the right side of the screen.

The expected behavior is that the window should restore to the exact size and position as it was when I last used it, similar to how other apps function.

I hope this feedback helps improve the user experience.

Thank you!

![SCR-20241011-mrae](https://github.com/user-attachments/assets/95e89b4b-9f50-49e1-81ff-04dc2d31e93c)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.8 (aarch64)

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by mr-cheffy** [comment]
@HarryHeres Could you take a look at this if you have time?

**Comment by harryheres** [comment]
Will try during this weekend.

**Comment by harryheres** [comment]
So I haven't been able to reproduce this issue on 1.0.1-a.9. Are you running any window/desktop managers like AeroSpace, yabai or such? <br><br>Are you utilizing virtual desktops? Does it happen when it is the only app open? I know for example Messenger on my Mac forces other apps to do the same. <br><br>Are you running on the native screen or do you have any monitors connected?

**Comment by FrancisMorelli** [comment]
Hi @HarryHeres and @mauro-balades 

I'm on the latest version and the issue still persists.
I'm not using any window/desktop or virtual desktop. Furthermore, I'm running it on my macOS operating system.

I have attached a screenshot with evidence. This only happens with Zen.

I hope this feedback helps improve the user experience.

![SCR-20241015-kjva](https://github.com/user-attachments/assets/4f425411-f8fb-41c7-b90c-f31200b4da3d)

**Comment by harryheres** [comment]
Thank you for the update, though my question with other running apps and external monitors still stands :)

**Comment by FrancisMorelli** [comment]
@HarryHeres I do not use any external monitor.

I run lots of applications and this behavior only happens with Zen. :)

**Comment by harryheres** [comment]
Could you, please try if this also happens when Zen is the only application open? Just trying to see a pattern here 😁

**Comment by FrancisMorelli** [comment]
@HarryHeres 
After the latest Zen's update, I had not restarted my Mac. I've just did it.

So, after that, with no other apps open, I noticed that the behavior is not happening. I opened other apps and the behavior did not happen also.

I'm still going to test it further, and I'll give you more updates about it.

Best regards.
