### ISSUE TITLE
In compact mode, top toolbar hides when hovering over left side and shows tabs instead

### ISSUE THREAD

**Issue by LinuxJava7** [zen-browser/desktop#203]
### What happened?

In compact mode, when top toolbar is hovered, getting too close to the left side hides the top toolbar and shows the vertical tabs. This makes it difficult to close the window.

Here's a video showing what I mean.

[Screencast from 2024-08-09 15-28-59.webm](https://github.com/user-attachments/assets/6bba2a11-6c65-4647-acab-9a5cadd79332)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.15

### Severity impact

Low

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
How did that button even get there?

**Comment by LinuxJava7** [comment]
> How did that button even get there?

The close button? I only have a close button for my window buttons, and it's on the left side. The same thing happens if I move the window buttons to the right side, but it isn't as annoying since the back button is larger.

[Video with window buttons on right side](https://github.com/user-attachments/assets/51873a38-1f69-4da5-ac49-7e4b16ebfc25)

**Comment by mauro-balades** [comment]
Fixed for the next release in https://github.com/zen-browser/desktop/commit/2035706c2aceb32e4968a51af6f524e02d552c6d, thansk!
