### ISSUE TITLE
Help to boost browser performance 

### ISSUE THREAD

**Issue by SmokeyPlayz** [zen-browser/desktop#2031]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

So i been using Zen for quite some time now on my Main windows 11 desktop which is a **AMD Ryzen 5 4600G with Radeon Graphics**. But the thing is that it has a down side which is only having 8GB's of Ram and most stuff now days uses alot of memory which can decrease the performance and the speed of the browser. The reason i'm making this is because i need help for increasing my browser for this browser i don't have many extensions nor history or something basic i really want someone to respond to something that can possibly help me i do say my pc is optimised by Atlas OS which further tweaks from various of resources which i will not yap about it.  The image i provided is basically showing wot i have running in task manager without playing any video games or high memory software. 
![image](https://github.com/user-attachments/assets/ff342cb1-679a-4ea6-b500-40901162fcb7)

2nd image shows my performance and memory in task manager. if anyone know how to increase performance with speed etc (positivity) that will be lovely.
![Taskmgr_260lnLQQud](https://github.com/user-attachments/assets/93c156be-a290-4f58-b2a5-abdc4a4f1307)

Best regards,
	

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.8

### What platform are you seeing the problem on?

Windows

**Comment by BrhmDev** [comment]
This isn't a bug, you can ask for help on discord or reddit.
