### ISSUE TITLE
Couldn't load XPCOM

### ISSUE THREAD

**Issue by mrbluegame** [zen-browser/desktop#2037]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I open zen browser and it I get an error that says couldn't load XPCOM I don't know what else to do

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

131.0

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
sadly i do not know where to get the files would appreciate if anyone can show me how
```

**Comment by mr-cheffy** [comment]
Could you try using the generic version?

**Comment by ibay770** [comment]
Unable to access the workspace to try it out.
