### ISSUE TITLE
Unable to move back/forward button to other toolbars

### ISSUE THREAD

**Issue by mechtifs** [zen-browser/desktop#2042]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

I'd like to move back/forward button to `zen-sidebar-top-buttons` toolbar, however it's not possible to do so. Would like to see that become customizable as well :)
![image](https://github.com/user-attachments/assets/2c8ef1ee-51c5-440e-83a2-5910da5a74c4)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.8

### What platform are you seeing the problem on?

Linux

**Comment by sidsharths1245** [comment]
Are you not able to drag them there while editing toolbar?

**Comment by BrhmDev** [comment]
This can be done with: "right click toolbar" > "Customize toolbar...", next time make feature requests in https://github.com/zen-browser/desktop/discussions

**Comment by mechtifs** [comment]
> Are you not able to drag them there while editing toolbar?

Exactly. I can only re-arrange these buttons inside the top toolbar.

**Comment by mechtifs** [comment]
> This can be done with: "right click toolbar" > "Customize toolbar...", next time make feature requests in https://github.com/zen-browser/desktop/discussions

This **cannot** be done in the "Customize toolbar". It's impossible to drag back/forward button to toolbars other than the top one. Idk if this is intended or is a real bug :(
