### ISSUE TITLE
Cant compile zen

### ISSUE THREAD

**Issue by AndreaSoranzo** [zen-browser/desktop#2044]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When i try to run `pnpm run build` i get a  `error: could not compile style (lib)` 

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.8 

### What platform are you seeing the problem on?

Linux

**Comment by mr-cheffy** [comment]
I can't really help you with this little information, sorry. Please ask in a firefox forum, they'll be able to help you better. Or provide more info like a revelant log. Thanks!
