### ISSUE TITLE
Empty Zen Mods tab

### ISSUE THREAD

**Issue by DaitiDay** [zen-browser/desktop#2045]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The Zen Mods tab in settings is empty:
![image](https://github.com/user-attachments/assets/56dfc1d9-b185-4f31-a9bd-b39db4597b2c)

Furthermore, the update button does not work.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.8

### What platform are you seeing the problem on?

Windows

**Comment by mr-cheffy** [comment]
Did you have any mods installed?

**Comment by DaitiDay** [comment]
Yes

**Comment by neurokitti** [comment]
yeah i had this issue too i gave up and swaped to a diferent profile where it did work

**Comment by DaitiDay** [comment]
That's a temporary solution. The user shouldn't have to swap profile to fix a browser issue imo. I'll wait for an update that fixes the problem.

**Comment by mr-cheffy** [comment]
Chances are your themes storage got corrupted. Could you try removing the zen-themes.json file from your profile's directory? This has been fixed for the next release btw
