### ISSUE TITLE
Problem with tabbar and Bookmarks toolbar (only show on newtab)

### ISSUE THREAD

**Issue by baiyanglevi** [zen-browser/desktop#2047]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

1. enable "expand tabs on hover" or "don't Expand"
2. make Bookmarks toolbar only show on newtab 
3. make the first tab a random website and make the second tab New tab
Thus you can switch between them without moving the cursor (I know this is not intended and needed to fix)
4. quick left click on the tabs to switch, and **Newtabs are created constantly** (on Firefox there's no such problem)
this is not a userChrome problem because I tried to remove it, the problem doesn't disappear.
![图片](https://github.com/user-attachments/assets/1af0747b-5494-4392-90df-572340ec79f2)
Sometimes the new created newtab (focused) can't be closed. (Mozilla Firefox has this second problem, with costum css quick switch makes tabs unclosable)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.8

### What platform are you seeing the problem on?

Windows

**Comment by salamijason** [comment]
Yo, if you're still getting this, could we get a screenrecording?

**Comment by salamijason** [comment]
No response in 3 days, will be closing this issue. Please reopen if you are still facing this issue.
