### ISSUE TITLE
In Zen Browser there is no custom network options to add network speed 

### ISSUE THREAD

**Issue by kranthivakati** [zen-browser/desktop#2049]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

1.open the zen browser 
2.press control(ctrl) + shift +i / control(ctrl) +shift+ c  
3.navigate to network tab 
4.click on throttling 
5.here need to custom option 

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### What platform are you seeing the problem on?

Windows

**Comment by kranthivakati** [comment]
> [ZEN-1964 In Zen Browser there is no custom network options to add network speed](https://linear.app/zen-browser/issue/ZEN-1964/in-zen-browser-there-is-no-custom-network-options-to-add-network-speed)

i'm not using linear and i don't have the access also.

**Comment by BrhmDev** [comment]
Not a bug. Make feature requests at https://github.com/zen-browser/desktop/discussions

**Comment by kranthivakati** [comment]
ok thanks
