### ISSUE TITLE
Toolbar only partially shown in Compact Mode

### ISSUE THREAD

**Issue by frostNZ** [zen-browser/desktop#205]
### What happened?

When compact mode is enabled, only part of the left toolbar is shown when hovering over.
Screen resolution is 2256x1504

![image](https://github.com/user-attachments/assets/b0f389a5-d66f-4c40-b4a6-4257511da5ab)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.15

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
This has been fixed in version 16, thanks!
