### ISSUE TITLE
In the Zen sidebar, when clicking on the YouTube app, it navigates to YouTube. After clicking the mic symbol, the mic option is enabled, but the cancel (X) button is not functioning.

### ISSUE THREAD

**Issue by kranthivakati** [zen-browser/desktop#2053]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

1.open the app 
2.click on the sidebar 
3.click on youtube 
4.tap on the mic symbol 
5.click on the cancel x button 
expected : app should navigate to youtube screen 
actual : still in the same screen i.e mic screen.
note: *once refresh the page it will work fine*
https://github.com/user-attachments/assets/2aa7171f-c3fe-4ef6-a294-f530d47786f5

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0

### What platform are you seeing the problem on?

Windows

**Comment by Richard-Woessner** [comment]
Okay after investigating this issue and mentioning it in the discord, I will put what I found here.

First, the HTML returned on initial load and after a refresh are different
[Sidebar_YT_After_Reload.txt](https://github.com/user-attachments/files/17383728/Sidebar_YT_After_Reload.txt)
[Sidebar_YT_First_Load.txt](https://github.com/user-attachments/files/17383731/Sidebar_YT_First_Load.txt)


Things I've tried
- [x] Replace `browser.setAttribute('src', data.url)` with .loadURI
     - Some sources online said that this would be better because the code would do a more in depth request?
- [x] Place `browser.setAttribute('src', data.url)` after `browserContainers.appendChild(browser);`
     - Looking online some StackOverflow pages said that it could be because its cut off from loading the source because its being returned to append
     
I am trying to see what is the different logic for refreshing compared to initial load but I cant seem to find any that could cause a different result

**Comment by salamijason** [comment]
Ive just checked this and couldn't reproduce it. Are you still getting this issue? Make sure you're completely updated!

**Comment by salamijason** [comment]
No response in 3 days, will be closing this issue. Please reopen if you are still facing this issue.
