### ISSUE TITLE
On windows platform shortcut for "toggle floating sidebar" is not working 

### ISSUE THREAD

**Issue by kranthivakati** [zen-browser/desktop#2056]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

1.open the gen-browser.
2.press  alt+ctrl(control)+s. 
expected behaviour : browser should open the "toggle floating sidebar".
actual behaviour : typing this "ś" symbol.

https://github.com/user-attachments/assets/15ea8f0f-35dd-4948-9c9b-6585e8aa3365

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0

### What platform are you seeing the problem on?

Windows

**Comment by salamijason** [comment]
Hey. So the shortcut you mentioned, ctrl + alt + s, only works when you're in compact mode! Try going into compact mode first (ctrl + alt + c, or in the settings) and then try the sidebar shortcut again.
![Image](https://github.com/user-attachments/assets/b0b8aa28-7025-4107-9ec4-3709c2485bf2)
![Image](https://github.com/user-attachments/assets/c7f7650f-90eb-485f-9e4b-0184deff829f)
