### ISSUE TITLE
Split view some shortcuts are not working 

### ISSUE THREAD

**Issue by kranthivakati** [zen-browser/desktop#2057]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

1.open the browser .
2.create two tabs.
3.press  below commands .
close split view = alt+ctrl+u
toggle split view horizontal -alt+ctrl+h 
toggle split view grid- alt+ctrl+g 
expected : the commands should work as expected.
actual : not working as expected. 

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0

### What platform are you seeing the problem on?

Windows

**Comment by mr-cheffy** [comment]
What version is this happening on? What was the ending result? Could you please provide a recording or screenshot?

Thanks

**Comment by kranthivakati** [comment]
If I press those shortcuts it doesn't not working as expected!

**Comment by salamijason** [comment]
Bug could not be reproduced on latest version 1.0.1-a.14. Could you please try again on the latest ver and let me know how it goes? If it doesn't work, please attach a screen recording.
