### ISSUE TITLE
No arm64 linux build

### ISSUE THREAD

**Issue by bubu-bubu-85** [zen-browser/desktop#206]
### What feature would you like to see?

Hello, 
I want to install Zen on Asahi Linux , however, there are only X86_64 releases.
Could you add release for Arm64 please ?

Thanks by advance

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/883

 ~ This is an automatic operation to better enhancements requests organization.
