### ISSUE TITLE
Auto start popup gets stuck in compact mode (Windows)

### ISSUE THREAD

**Issue by dagadtwok** [zen-browser/desktop#2060]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When the compact mode is enabled, this little pop up gets stuck at the tab bar. 

![2024-10-13-01-42-39](https://github.com/user-attachments/assets/61aa6d76-4e10-4057-a897-2502fc0f1a12)
![2024-10-13-01-42-47](https://github.com/user-attachments/assets/1039bca0-e03c-4157-976c-b868a47f8c7c)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.8

### What platform are you seeing the problem on?

Windows

**Comment by salamijason** [comment]
Are you still getting this on the latest version 1.0.1-a.14?

**Comment by dagadtwok** [comment]
Haven't encountered this pop up since then. I'll reopen if the issue still exists.
