### ISSUE TITLE
Version 1.0.1-a.8 causing problems with inbox.com

### ISSUE THREAD

**Issue by cmwmlw** [zen-browser/desktop#2063]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

With the inbox.com email platform the screen layout is vertically oriented; the left column is for folders, the center column contains the messages within the current folder, the right column is a preview of the highlighted message from the center column.  With Zen versions 1.0.1-a.3, 1.0.1-a.5 and 1.0.1-a.7 there was no problem, everything worked and looked correct.  After updating to 1.0.1-a.8 the left column for the folders is now gone.  I have cleared the cache, deleted all the inbox.com cookies, closed and restarted the browser.  The problem still exists.  I even tried rebooting, but it made no difference.  On FireFox 131.0.2, the most current version, inbox.com works correctly.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.8

### What platform are you seeing the problem on?

Windows

**Comment by mr-cheffy** [comment]
Does this happen in a new, fresh profile?

**Comment by cmwmlw** [comment]
Not sure how this could be a a profile issue.  The sequence was I loaded a7 and got the update available popup, I dismissed it because I had something to do.  I spent maybe the next 2 hours using the browser, including sending and reading several emails using inbox.com.  I then went to Help/About to download and install a8, restarted Zen and that's when the problem started.  Basically is was working properly as a7, upgrade to a8, issue began.

**Comment by mr-cheffy** [comment]
Yeah, but could you try if it works in a new profile? Because maybe some settings got changed that leaded to this issue

**Comment by cmwmlw** [comment]
A new profile doesn't have the same issue.  Not even sure how something simple like a version upgrade could corrupt a profile, but it seems like it has.  That's not very encouraging.

**Comment by mr-cheffy** [comment]
Try disabling tracking protection

**Comment by cmwmlw** [comment]
I've used strict ETP in FireFox for years - same setting I have with Zen - and in all that time inbox.com has never lost the folders column.  I actually don't think there's anything for ETP to do; it has never blocked a single tracker on that site, based upon my experience it seems they don't use any.  The saga does continue though, only it veers off in a direction I didn't see coming...

When I loaded Zen last night there was an update to a10 available so I downloaded and installed that.  Once the browser restarted I checked inbox.com, the folders column was still missing (this was using my original profile).  I wanted to try one more time to get it back so I cleared the cache, site data and cookies.  Closed the browser and when I went back in there was no difference.  Frustrated, I decided to instead focus on fixing another issue I have with Zen; it seems to ignore the extension Auto Tab Discard.

I've been using this extension for years in FireFox and its derivatives, among them LibreWolf, Water Fox, Ghostery, Mercury, Floorp, Midori and others I've probably forgot.  The configuration is quite elaborate - there are a number of options -  so what I do is export the config json from FireFox and then import that into the other browser.  It's the exact same thing I did with Zen, only this browser ignores the exceptions list.  I have 4 tabs that auto-load on startup, none of which I want to hibernate.  Those are listed as exceptions, any other tab I load is not and will hibernate after 30 minutes (configurable setting).  With Zen ATD hibernates every tab, even the ones that are excluded.  And it does so in less than the 30 minutes, it seems to be ignoring the extension entirely.  Here is the sequence I used that night...

1)  Upgrade to a10
2)  Delete cookies, cache, site settings
3)  Restart browser, problem with inbox.com still exists
4)  Load FireFox, export Auto Tab Discard json, close FireFox
5)  Import ATD config into Zen

While I was waiting to find out if importing the known good configuration was going to fix the hibernation issue I decided to delete the second profile I had created while troubleshooting the inbox.com problem.  Sadly using the ATD config from FireFox didn't change anything, the excluded tabs were still hibernating.  Frustrated by all the problems I'm having with Zen I closed the browser.

The next day I came to the conclusion it wasn't worth investing any more time with this browser so I was going to delete it, before doing so I wanted to be sure I hadn't bookmarked anything I wanted to keep so I loaded Zen one final time.  Much to my surprise, I found the the folders panel was back!  Just as mysteriously as it stopped working, it just as mysteriously started again.  I guess it could break again at any moment, but for now it's functioning correctly.

The reason I listed the steps above was to give an indication of what I did that I hadn't done before, although I doubt it matters as I don't see how any of that could have solved the problem.  Zen has its own profile folder, I don't think loading FireFox overwrote anything Zen uses and fixed the profile.  For sure loading an extension config file didn't clear up a visual issue with an email website, so that's not it either.  I'm at a loss to understand what just happened, but happen it did.  Now if I can just figure out how to fix the ATD problem I'd be set...

**Comment by RayZ3R0** [comment]
Hello, does this issue still persist on a-14?

**Comment by cmwmlw** [comment]
> Hello, does this issue still persist on a-14?

Are you referring to the issue with auto tab discard extension?  I was on a12 for a bit and just upgraded to a15 tonight, let me try it for a few days and then I'll report back.

**Comment by cmwmlw** [comment]
Turns out I didn't need a few days to test.  Despite setting an exclusion on a tab it still hibernates, but now it's permanent.  Whereas before I could click on the tab and it would come back to life, now it's locked out completely.  Nothing happens when you try and access the tab, you can't even switch to it.  It wasn't ideal before but it was workable, the way it is now makes Zen unusable for me.  I'll try disabling the extension and see if the problem is the same.

**Comment by RayZ3R0** [comment]
Hmmm that's weird. Maybe its interfering with Zen's auto discard? cuz zen has that builtin

**Comment by cmwmlw** [comment]
I just searched about:config for "discard" and the only setting that seems even close to hibernating tabs is "image.mem.discardable", is that what you're referring to?

Before doing any more troubleshooting with Zen I decided to try it again on FireFox, just to see if maybe their source code was where the issue was and not Zen.  Using the exact same extension and configuration on FF version 132.0 everything works fine; tabs that are supposed to hibernate do, ones with an exclusion don't.

**Comment by RayZ3R0** [comment]
You dont really need the extension anymore though. Zen has built in tab discard, with shortcuts, ignore tabs, auto tab discard after certain time

**Comment by cmwmlw** [comment]
I would gladly use a builtin function over an extension any day.  All I really need is to set the amount of time before a tab hibernates, and have an exclusion list.  How can I configure those in Zen?

**Comment by salamijason** [comment]
There is a built in tab unloader function in Zen ![Image](https://github.com/user-attachments/assets/6cd1824a-0dc6-451a-ada4-1c9d0bd466fb)

**Comment by salamijason** [comment]
I assume that was the only issue left? I'll be closing this issue now. Please reopen if you still have any issues. Thank you.
