### ISSUE TITLE
Any *.google.com site keeps signing out when I close browser

### ISSUE THREAD

**Issue by opticSquid** [zen-browser/desktop#2064]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Any *.google.com site like www.google.com(google search), gemini.google.com keeps getting signed out of my google account when ever I close my browser. While youtube.com which despite being Google's product does not use *.google.com domain retains my session. I have been noticing this issues from version 1.0.1-a.7 but I thought this would be fixed in 1.0.1-a.8 but it still continues. I'm running Ubuntu 24.04 LTS. And ZEN Browser is installed as a flatpak in my system. 

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.8

### What platform are you seeing the problem on?

Linux

**Comment by sjclayton** [comment]
Cannot reproduce this on Arch Linux running Zen 1.0.1-a.8, all of my google.com services stay signed in on a restart of the browser. Maybe it's related to something with the flatpak, I have Zen installed via the AUR package here on Arch.

**Comment by opticSquid** [comment]
> Cannot reproduce this on Arch Linux running Zen 1.0.1-a.8, all of my google.com services stay signed in on a restart of the browser. Maybe it's related to something with the flatpak.

I don't know may be. Are you suspecting insufficient permissions of some kind. Do you want me check flatseal?

**Comment by sjclayton** [comment]
I'm not sure, I will try to install the flatpak and see if I have the same issue and let you know... Probably something the maintainer is going to have to sort out, if it is even a flatpak issue, it may still be something else.

**Comment by opticSquid** [comment]
> I'm not sure, I will try to install the flatpak and see if I have the same issue and let you know... Probably something the maintainer is going to have to sort out, if it is even a flatpak issue, it may still be something else.

ok

**Comment by atharva-p** [comment]
can you go to settings > privacy and security > cookies and site data > delete cookies and site data when zen browser is closed and see if it's unchecked? that could cause this. is it limited to only *.google.com?

**Comment by opticSquid** [comment]
> can you go to settings > privacy and security > cookies and site data > delete cookies and site data when zen browser is closed and see if it's unchecked? that could cause this. is it limited to only *.google.com?

yes

**Comment by salamijason** [comment]
Bug could not be reproduced on latest version 1.0.1-a.14. Could you please try again on the latest ver and let me know how it goes?

**Comment by salamijason** [comment]
No response in 4 days, will be closing this issue. Please reopen if you are still facing this issue.

**Comment by opticSquid** [comment]
> No response in 4 days, will be closing this issue. Please reopen if you are still facing this issue.

Sorry I did not notice before. I am still facing the same problem

**Comment by salamijason** [comment]
please respond to the other user's questions:

1) Is this toggle unchecked? 
![image](https://github.com/user-attachments/assets/5da2644f-686c-4a98-87e5-515e9dbf25db)

2) Does this only happen on google site? Have you tried other sites? github, instagram, etc.

**Comment by opticSquid** [comment]
> please respond to the other user's questions:
> 
> 1) Is this toggle unchecked? 
> ![image](https://github.com/user-attachments/assets/5da2644f-686c-4a98-87e5-515e9dbf25db)
> 
> 2) Does this only happen on google site? Have you tried other sites? github, instagram, etc.

1. Yes this toggle is unchecked.
2. Yeah it happens to only *.google.com sites. So, Youtube doesn't get effected.

**Comment by opticSquid** [comment]
> > please respond to the other user's questions:
> > 
> > 1) Is this toggle unchecked? 
> > ![image](https://github.com/user-attachments/assets/5da2644f-686c-4a98-87e5-515e9dbf25db)
> > 
> > 2) Does this only happen on google site? Have you tried other sites? github, instagram, etc.
> 
> 1. Yes this toggle is unchecked.
> 2. Yeah it happens to only *.google.com sites. So, Youtube doesn't get effected. 

Give me some time currently I'm in office. I will return home and validate the browser version and settings and will send you with screenshots

**Comment by opticSquid** [comment]
> > please respond to the other user's questions:
> > 
> > 1) Is this toggle unchecked? 
> > ![image](https://github.com/user-attachments/assets/5da2644f-686c-4a98-87e5-515e9dbf25db)
> > 
> > 2) Does this only happen on google site? Have you tried other sites? github, instagram, etc.
> 
> 1. Yes this toggle is unchecked.
> 2. Yeah it happens to only *.google.com sites. So, Youtube doesn't get effected. 

Give me some time currently I'm in office. I will return home and validate the browser version and settings and will send you with screenshots

**Comment by opticSquid** [comment]
> > > please respond to the other user's questions:
> > > 
> > > 1. Is this toggle unchecked?
> > >    ![image](https://private-user-images.githubusercontent.com/90419732/383174388-5da2644f-686c-4a98-87e5-515e9dbf25db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5MDYyMTksIm5iZiI6MTczMDkwNTkxOSwicGF0aCI6Ii85MDQxOTczMi8zODMxNzQzODgtNWRhMjY0NGYtNjg2Yy00YTk4LTg3ZTUtNTE1ZTlkYmYyNWRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDE1MTE1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1ZTQxYTkzZTE1ZTVkMzQ5YjUwY2ViYzNkOTMwYjU5MzQ0ZDQzMDU3MjhlNTk1ZTUyM2JkMmMyMzVjNTlmNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.x-zpkms6ZDZoFEs76hbZ9BgC5XYdDjDSm3oPWwPktcY)
> > > 2. Does this only happen on google site? Have you tried other sites? github, instagram, etc.
> > 
> > 
> > 
> > 1. Yes this toggle is unchecked.
> > 2. Yeah it happens to only *.google.com sites. So, Youtube doesn't get effected.|
> 
> Give me some time currently I'm in office. I will return home and validate the browser version and settings and will send you with screenshots

I'm on version: till 1.0.1-a.17
And yes the toggle is unchecked
![image](https://github.com/user-attachments/assets/63b994f7-2528-4ca7-9679-f1230895bb0d)

**Comment by salamijason** [comment]
This is really weird. I've never gotten issues with this. I use classroom.google and mail.google pretty often and have never needed to relogin. Could you try a new profile and let me know if you still get the issue on the new profile?

Instructions on creating new profiles here https://docs.zen-browser.app/guides/manage-profiles

**Comment by opticSquid** [comment]
> This is really weird. I've never gotten issues with this. I use classroom.google and mail.google pretty often and have never needed to relogin. Could you try a new profile and let me know if you still get the issue on the new profile?
> 
> Instructions on creating new profiles here https://docs.zen-browser.app/guides/manage-profiles

ok I will check

**Comment by cheeeebs** [comment]
Can you look at this and see if it is related?
https://www.reddit.com/r/firefox/comments/13us1uu/comment/k3aveu3

**Comment by opticSquid** [comment]
> Can you look at this and see if it is related? https://www.reddit.com/r/firefox/comments/13us1uu/comment/k3aveu3

seems quite related. Let me try once on my system then I will confirm. I'm currently out of station so, I can not confirm right away but I will let you know as soon as possible

**Comment by salamijason** [comment]
This is the wildest solution I've ever heard (from the reddit post's comments):
![image](https://github.com/user-attachments/assets/552d0f7d-2865-4b89-8dcb-8ea34e8fe9aa)

but it seems like it worked for them so I guess it's worth a shot. Let us know if it works for you!

**Comment by opticSquid** [comment]
> This is the wildest solution I've ever heard (from the reddit post's comments):
> ![image](https://github.com/user-attachments/assets/552d0f7d-2865-4b89-8dcb-8ea34e8fe9aa)
> 
> but it seems like it worked for them so I guess it's worth a shot. Let us know if it works for you!

Yeah I will be heading back home tomorrow. I will let you know

**Comment by opticSquid** [comment]
This solution doesn't make any sense but it works!... I'm surprised.. This is clearly a bug in firefox... All this day I thought it was something in zen browser. Sorry to bother you guys.. This is solved. Thank you everyone for helping me out. And specially thanks @cheeeebs for digging out this reddit thread and @salamijason for being so supportive through out. Thanks a lot guys. I'm keeping the issue open for some time if any one has to add anything. I will close the issue in a day or two
