### ISSUE TITLE
Enter Full Screen and Exit Full Screen is not working in zen browser shortcut( f11 button)

### ISSUE THREAD

**Issue by kranthivakati** [zen-browser/desktop#2074]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

1.open the zen browser 
2.press f11 button
expected behaviour : browser should enter into full screen mode .
actual behaviour: browser didn't responding and once full screen view is enabled then we can check exit full screen mode.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0

### What platform are you seeing the problem on?

Windows

**Comment by nanoraptor** [comment]
You're using version 1.0.0? In the latest version it is working fine tho.

**Comment by ben-mcginty** [comment]
I founds that on Windows, the key is mapped to 'f11', when manually remapping it maps it to 'F11' (note the upper-case 'F').
I think that this may be the issue.
I have also found the same issue with a myriad of other default keybindings.
![image](https://github.com/user-attachments/assets/c9525b11-8d76-46c3-9699-1d39d6f74a0f)
![image](https://github.com/user-attachments/assets/3af031d0-64ce-4589-895c-27e7fe1b32bb)

**Comment by nanoraptor** [comment]
> I founds that on Windows, the key is mapped to 'f11', when manually remapping it maps it to 'F11' (note the upper-case 'F'). I think that this may be the issue. I have also found the same issue with a myriad of other default keybindings

It's True. In order for the intended shortcut to work. We need to keep capslock on during the key recording. This is weird. This also causes conflict with actual "capital" keybindings.

**Comment by salamijason** [comment]
My shortcuts are set as follows:![Image](https://github.com/user-attachments/assets/4fe841a6-2943-4e69-9fc5-906962279fda)


Bug could not be reproduced on latest version 1.0.1-a.14. Could you please try again on the latest ver and let me know how it goes?

**Comment by ben-mcginty** [comment]
I've got it working, but I don't think it is the intended behavior. When pressing f11, it makes the window full screen, hiding the taskbar, but it doesn't make the webpage full-screen. In my screenshot below, Zen is on the left, with Microsoft Edge on the right. I think that Edge's implementation is better.
![image](https://github.com/user-attachments/assets/7c59ffaa-1cbc-4246-9eb8-2ae0615c3fbd)

**Comment by salamijason** [comment]
> but it doesn't make the webpage full-screen

If you want that behaviors, try compact mode (ctrl+alt+c). F11 hiding the taskbar only is intentional since we also have compact mode.
You can check the shortcuts and settings for it in about:preferences too.
