### ISSUE TITLE
Toggle Reader Mode(Windows) f9 shortcut button is not working.

### ISSUE THREAD

**Issue by kranthivakati** [zen-browser/desktop#2075]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

1.open zen browser
2.press f9 button 
expected behaviour :browser should be in Toggle Reader Mode.
actual behaviour: browser didn't responding for that button.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0

### What platform are you seeing the problem on?

Windows

**Comment by mr-cheffy** [comment]
The shortcut for this is CTRL+ALT+R

![image](https://github.com/user-attachments/assets/7af8563a-2cf2-47c9-8ed1-831f5d77cb0f)

You can change it in the settings, under the custom keyboard shortcuts section

![image](https://github.com/user-attachments/assets/094cd015-9e4f-40e6-ae18-e27663c66530)
