### ISSUE TITLE
Cannot enable Mozilla telemetry

### ISSUE THREAD

**Issue by AlexFullmoon** [zen-browser/desktop#2080]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Privacy policy on the website states that "you can opt-in to share telemetry data to Mozilla for the improvement of FireFox". However, there are no Data collection options in about:settings, and, it turns out, all telemetry-related options in about:config are disabled and *locked*.

Either telemetry is disabled due to it carrying Zen's debug information irrelevant to upstream Firefox, or this is a (misguided) attempt to improve end users' privacy. In both cases privacy policy on the website should be updated.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.8

### What platform are you seeing the problem on?

Windows

**Comment by nanoraptor** [comment]
Heck, I thought you wanted to turn on telemetry to mozilla by looking the title. I mean who in their right mind would do that. However, what you stated is correct if the option is removed from the browser then they should update the privacy policy in the website.

**Comment by AlexFullmoon** [comment]
>  I mean who in their right mind would do that.

The only way random user might help improve Firefox (aside from donation, and I'd hazard a guess neither of us donated) is to send bug reports and telemetry.

It's not Google, y'know.

**Comment by mr-cheffy** [comment]
This wont be implemented, as there's not really a priority and something that I would like to be in zen, you can edit the about config's if you feel like it. Sorry
