### ISSUE TITLE
Super Resulation Not Work - NVIDIA Graphic Card

### ISSUE THREAD

**Issue by MfiCore** [zen-browser/desktop#2082]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Hello, I have a 2K monitor. I always use the RTX Super Resolution mode on my NVIDIA graphics card to enhance the quality of web videos with 1080p or lower resolution. Normally, to enable this, I disable the "Use recommended performance settings" option in Firefox-based browsers and check the "Use hardware acceleration when available" box. After restarting the browser and opening videos in full screen, the NVIDIA Control Panel shows "active" under the RTX Video Enhancement section. This indicates that the video enhancement is working successfully and that the graphics card is processing the video. 

I'm not sure why this feature isn't working, but I've noticed that you've been pushing a lot of updates in a short amount of time. I hope this issue is resolved soon because, as you know, web videos are often heavily compressed. Modern AI-powered graphics cards can easily enhance these videos, allowing us to watch clear and sharp content on our 2K and 4K monitors. I hope this gets fixed as soon as possible.

Before you suggest anything, I have already anticipated possible solutions and tried the following:

- I reinstalled the browser. I tested both the alpha and twilight versions. It doesn’t work on either.
- I checked the GPU settings in **about:config** and the value is set to true. (gfx.webrender.overlay-vp-super-resolution)
- It works on Chrome.
- It works on Firefox (the original version, but I haven’t tested developer or nightly versions).
- It works on Edge (original beta and canary working).
- My NVIDIA driver is currently up to date.

Everything seems to be as it should, but it’s still not working. 
![zen_3bzW5LvTiH](https://github.com/user-attachments/assets/b7694ec7-4a1d-42c4-a0d5-9a0844530c48)
![zen_Ttrs7fDM4f](https://github.com/user-attachments/assets/af242788-0a35-4047-a0b3-042ddfe14739)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Twilight build - 1.0.1-a.8 (2024-10-13)  and  Alpha build - 1.0.1-a.8 (2024-10-10)

### What platform are you seeing the problem on?

Windows

**Comment by Robot-Inventor** [comment]
I thought this comment might be helpful: https://github.com/zen-browser/desktop/issues/1849#issuecomment-2395153344

**Comment by MfiCore** [comment]
Thank you for this solution. 
I am sending the error message before and after the about:support page. After the setting mentioned in about:config was applied, the issue was resolved. However, this is not a setting that a standard user would be able to find. For example, I learned about zen browser from a YouTube broadcaster. Developers need to take this into account and make it the default. When the setting I mentioned is configured in the Zen (Mozilla-based) settings, the browser's additional necessary config settings need to be changed.

Screenshots: 
Before solution: 
![zen_zvwfNpictE](https://github.com/user-attachments/assets/55a52bd5-bf36-4685-a477-2ac440bcc1f7)

need to change this setting (everyone can be double click false to true value:
![zen_zEvmQhSH8n](https://github.com/user-attachments/assets/a7dbd9ee-747a-4f04-83d0-1cedc0926fcf)

Restart your browser and check
![UdaFQpU2Ge](https://github.com/user-attachments/assets/b4a04e6d-1546-4acc-b5d3-d9e7bdca115f)

After that working to all videos when enter fullscreen or youtube cinematic preview

Solution from robot-inventor. 
https://github.com/zen-browser/desktop/issues/1849#issuecomment-2395153344

Quoted message is here
> I was experiencing the same issue.
> 
> When I checked `about:support`, I found that `VIDEO_HARDWARE_OVERLAY` was `Blocklisted by gfxInfo`. In my environment, setting `gfx.webrender.dcomp-video-hw-overlay-win-force-enabled` to `true` in `about:config` allowed VSR to work properly.

**Comment by PushaG** [comment]
Hey, i'm original poster of this issue that you found solution in. I'm glad that fix by Robot-Inventor helped you, but for me still nothing happens even though i have everything enabled. Interested to see if this is indeed universal solution but for some reason my installation just won't work.
