### ISSUE TITLE
Tabs not restored after computer restart - null text

### ISSUE THREAD

**Issue by mootw** [zen-browser/desktop#2083]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When i restarted my computer (after a zen browser update, i am not sure if this happens when i do a normal computer restart). This issue is not present in mainline firefox. The tabs i had open across multiple browser windows did not restore fully. They all are empty windows with the text "null" in the top left with a new tab. One browser window **did** restore its tabs successfully. The recently closed windows and recently closed tabs buttons also do not work (and are not greyed out either) on all of the 'broken' windows, however i am able to use the recently closed windows button on the main (and functional tab), to restore the other windows correctly.

![image](https://github.com/user-attachments/assets/41cba187-6187-49f5-9fe5-267d3ebb1272)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.8 (64-bit)

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
couldn't find any for today in journalctl
```

**Comment by mootw** [comment]
also to note, the window title is missing entirely (taskbar pictured)
![image](https://github.com/user-attachments/assets/af350ac4-8255-4d0e-b1dc-946d6b19a57f)

**Comment by mr-cheffy** [comment]
Looks like something got corrupted, could you try in a new profile?

**Comment by mootw** [comment]
just updated to `1.0.1-a.9` and did **not** see the same issue. i don't think the profile is the issue, but ill try it if i experience the issue again. closing the issue for now as it was likely a fluke and has no easy diagnosis. ill reopen again if i can find more information or can reproduce it!
