### ISSUE TITLE
Getting 0xc0000142 error while trying to open zen.exe

### ISSUE THREAD

**Issue by ZAR0X** [zen-browser/desktop#209]
### What happened?

I installed Zen browser and got this error [attached Image](https://github.com/user-attachments/assets/6355cfac-96a7-42a0-bfbb-d0a1bba18e06) while installing despite of that it install, but when I 
![Capture](https://github.com/user-attachments/assets/6355cfac-96a7-42a0-bfbb-d0a1bba18e06)
tried to run Zen browser same error appeared, I also tried portable version but again same error 
I am on Windows 10 Pro 
version - 22H2

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.15

### Severity impact

Medium, High

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
Should be fixed for version 16, generic builds, thanks!

https://github.com/zen-browser/desktop/actions/runs/10331122444

**Comment by pcc404** [comment]
I am having this issue with the version from https://zen-browser.app/download

**Comment by Dhyfer1** [comment]
@mauro-balades I also have the same problem. Any solution?

**Comment by Dhyfer1** [comment]
@mauro-balades I also have the same problem. Any solution?

**Comment by mauro-balades** [comment]
Use the generic version, your CPU is not supported
