### ISSUE TITLE
ZEN keeps disabling opened tabs

### ISSUE THREAD

**Issue by itstamimi** [zen-browser/desktop#2091]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Since last update, ZEN browser keeps disabling opened tabs, say you have 6 opened tabs, after some time (minutes sometimes) you would see some tabs are greyed out and disabled, once you click on it, it reloads.
How to disable this option? it seems some sort of auto memory saving, the issue is annoying if you have some replies in some forums and not yet posted, only to find out the tab is disabled, reloading it and it's all gone!
![Screenshot_20241014_005922](https://github.com/user-attachments/assets/81af0968-0394-47c4-89d5-a3d861176d54)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.8

### What platform are you seeing the problem on?

Linux

**Comment by sjclayton** [comment]
Go to Settings > Tab Management > Tab Unloader, and uncheck `Enable Tab Unloader`

Hope that helps! 😃

**Comment by itstamimi** [comment]
Perfect, thank you!
