### ISSUE TITLE
Can't get notification permission

### ISSUE THREAD

**Issue by iammohan01** [zen-browser/desktop#2093]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I just installed and configured with default configurations nothing changed.

Then i opened one.zoho.com. no Notification permission popup, 
so i tried to get Permission through console, getting error of "denied" straight away, 

then i looked into notification setting, "block new request" feature is enabled and i tried to disabled, and tried again to get notification permission, still getting denied access.

then i installed firefox and and opened same site, at initial page load asking notification permission.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.8 (aarch64)

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by themateus** [comment]
Same issue here.

Operating System: Fedora Linux 40
KDE Plasma Version: 6.2.0
KDE Frameworks Version: 6.7.0
Qt Version: 6.7.2
Kernel Version: 6.11.3-200.fc40.x86_64 (64-bit)

**Comment by MrinmoyHaloi** [comment]
same here. Websites can't ask for permissions. 
OS: Arch Liinux
KDE Plasma 6.2.0
Zen browser: 1.0.1-a.10

**Comment by dParikesit** [comment]
Same here.
OS: windows 11
Zen browser 1.0.1-a.12

**Comment by RayZ3R0** [comment]
Does this still happen in latest version?

**Comment by MrinmoyHaloi** [comment]
@RayZ3R0 yes it's still happening on latest update

**Comment by MrinmoyHaloi** [comment]
Notification and location permission both are not working
