### ISSUE TITLE
Web Panel reloads all widgets when toggled even when tab unloader is off

### ISSUE THREAD

**Issue by gi-yt** [zen-browser/desktop#2098]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Till the recent update (not sure which alpha it was before updating to a8, but it was on the same major release), the widgets/websites present in web panel remained as-is without refreshing or stopping the webpage, even when hidden.

However with the latest a8, this behaviour was changed to always refresh the pages every time the pane is hidden.

This does not work well with my usecase, wherein I use the pane to keep some chat apps like whatsapp and element open there. I know this is a niche usecase, but if its possible for you guys to atleast give a toggle to allow for this, it would be much appreciated

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.8

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
-
```

**Comment by gi-yt** [comment]
Interesting thing is that the thing only reloads once the panel is reopened, since I keep getting whatsapp notification sounds even when its closed

**Comment by sjclayton** [comment]
Duplicate of #2022

**Comment by gi-yt** [comment]
oh yes, thanks for linking to the original issue.
