### ISSUE TITLE
Browser crashes with abnormal RAM usage leading to SIGEGV

### ISSUE THREAD

**Issue by xi-ve** [zen-browser/desktop#2099]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

While using ZenBrowser (v1.0.1-a.8) AppImage on my Hyprland setup, the browser crashes with a segmentation fault (SIGSEGV). This happens after some time, and I've noticed the process uses a significant amount of RAM before the crash, eventually leading to a core dump. The issue seems to occur during normal browsing activity, and the logs point to a memory access violation in libc.so.6.

Details:
OS: Arch Linux 
Kernel: 6.11.3-zen1-1-zen
GPU Driver: NVIDIA 555.58.02
Desktop: Hyprland
Backend: Wayland

Logs:
Process 702492 (zen) of user 1000 dumped core.

Stack trace of thread 702624:
#0  0x00007babe13b63f4 n/a (libc.so.6 + 0x963f4)
#1  0x00007babe135d120 raise (libc.so.6 + 0x3d120)
#2  0x00007babd98d88e3 n/a (/tmp/.mount_ZenBrohNLgck/libxul.so + 0x6ed88e3)
ELF object binary architecture: AMD x86-64

ZenBrowser consumes a large amount of RAM before the crash. Below are the relevant memory details captured in the core dump logs:

VmPeak:    19699444 kB
VmSize:     4048696 kB
VmRSS:      844644 kB

At its peak, the browser consumed nearly 19 GB of virtual memory (VmPeak), which seems unusually high for typical browsing activities. The actual resident memory (VmRSS) was around 844 MB at the time of the crash.

Steps to Reproduce:
Launch ZenBrowser AppImage v1.0.1-a.8 on a Hyprland session (Wayland).
Browse for a while, and monitor memory usage.
Eventually, the browser crashes, memory usage increases rapidly before it crashes.

I can provide the full core dump or any other logs if needed for further investigation.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.8

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
[Parent 702492, Compositor] WARNING: Call to mmap failed: Bad file descriptor: file /home/runner/work/desktop/desktop/engine/ipc/chromium/src/base/shared_memory_posix.cc:515
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
[1]    702492 segmentation fault (core dumped)  .local/share/AppImage/ZenBrowser.AppImage
```

**Comment by RayZ3R0** [comment]
@xi-ve Does this still happen in latest version?

**Comment by xi-ve** [comment]
> @xi-ve Does this still happen in latest version?

Positive, issue persists.

**Comment by RayZ3R0** [comment]
That's odd, we'll look into it

**Comment by mr-cheffy** [comment]
Could you send the `run.txt` file after runing the following command?

```sh
WAYLAND_DEBUG=1 MOZ_LOG="Widget:5 WidgetWayland:5" strace -f ~/.local/share/AppImage/ZenBrowser.AppImage > run.txt 2>&1
```

**Comment by xi-ve** [comment]
> Could you send the `run.txt` file after runing the following command?
> 
> ```shell
> WAYLAND_DEBUG=1 MOZ_LOG="Widget:5 WidgetWayland:5" strace -f ~/.local/share/AppImage/ZenBrowser.AppImage > run.txt 2>&1
> ```

[run.txt](https://github.com/user-attachments/files/17608107/run.txt)

The browser was unable to run using this command, I am not sure if this was intended.

A run with elevated permissions resulted in a longer log.

[run.txt](https://github.com/user-attachments/files/17608146/run.txt)

I hope these are helpful, best regards.

**Comment by arunoruto** [comment]
With the `v1.0.1-a.18` version I am also getting kinda the same error:
```log
[Parent 2, IPDL Background] WARNING: failed to duplicate file descriptor: Bad file descriptor: file /home/runner/work/desktop/desktop/engine/ipc/chromium/src/base/shared_memory_posix.cc:543
[Parent 2, Main Thread] WARNING: Failed to enumerate devices of org.freedesktop.UPower: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
: 'glib warning', file /home/runner/work/desktop/desktop/engine/toolkit/xre/nsSigHandlers.cpp:187

** (zen-alpha:2): WARNING **: 18:24:55.591: Failed to enumerate devices of org.freedesktop.UPower: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown

[Parent 2, IPDL Background] WARNING: failed to duplicate file descriptor: Bad file descriptor: file /home/runner/work/desktop/desktop/engine/ipc/chromium/src/base/shared_memory_posix.cc:543
IPDL protocol error: SharedMemory::WriteHandle failed
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Crash Annotation GraphicsCriticalError: |[C0][GFX1-]: CompositorBridgeChild receives IPC close with reason=AbnormalShutdown (t=5Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Crash Annotation GraphicsCriticalError: |[C0][GFX1-]: CompositorBridgeChild receives IPC close with reason=AbnormalShutdown (t=816.681) Exiting due to channel error.
```
I am running Zen as a flake (still waiting for the PR to be finalized at nixpkgs). The update happened at the same time as a kernel update to `6.11.6/7`. I am also running an Nvidia GPU, but that hasn't been a problem for now.
I am also running nearly the same setup on my Laptop, where I am not experiencing those crashed (for now).
It usually happens when a video is running in the background and I try to work with other tabs.

**Comment by xi-ve** [comment]
I'd like to add that this issue is present on all NVIDIA drivers I have tested except this driver version: 565.57.01. (Which is the latest one of the 565 series)
The issue seems to be resolved on this version, nonetheless the issue appears on all previous versions for whatever reason.

**Comment by lorebored** [comment]
I have the same problem, also in a.19 with the flatpak . Have you find any solution?
![Screenshot From 2024-11-25 17-01-30](https://github.com/user-attachments/assets/e843e41f-de5d-4c42-a3cb-600366e0b603)
I'm on Fedora 41 with a ryzen 5 5500u with integrated gpu, so is not an nvidia-related problem

**Comment by mr-cheffy** [comment]
Ill move this into #2748
