### ISSUE TITLE
Double Click to close tab.

### ISSUE THREAD

**Issue by SVTA-OP** [zen-browser/desktop#210]
### What feature would you like to see?

I think this feature is available in Microsoft Edge with vertical tabs, and it's difficult to close tabs in a fly with vertical tabs since the close button is absent.

### What platform are you seeing the problem on?

Linux

**Comment by gunir** [comment]
Go to `about:config` and set:
browser.tabs.closeTabByDblclick	true

**Comment by rihards-simanovics** [comment]
> Go to `about:config` and set: browser.tabs.closeTabByDblclick true

Ohhhh thank youuuuu @gunir. This is amazing! Didn't knows it existed until I found this issue.

Do you think this could be exposed at some point in the UI? Having had that in Edge, where it's available through settings, is kind of annoying. Could we perhaps have a section in settings called "Power user" with these kinds of little optimisations in workflow? Most apps hide these things under accessibility, but I think sections like "Power user" make more sense!
