### ISSUE TITLE
"You need to have Zen Browser installed to install this theme, Download now!" the text appears

### ISSUE THREAD

**Issue by dursunator** [zen-browser/desktop#2102]
### Captchas

- [x] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

While in the zen browser, on the zen modes page, "You need to have Zen Browser installed to install
this theme, Download now!" the text appears.

Note: This problem does not happen all the time, but it can be annoying when it happens...
![image](https://github.com/user-attachments/assets/9b2e3777-261f-491f-aa77-d93f7508a5a9)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.8

### What platform are you seeing the problem on?

Windows

**Comment by mr-cheffy** [comment]
This should be fixed now, thanks!
