### ISSUE TITLE
minor visual bug in mods setting page

### ISSUE THREAD

**Issue by neurokitti** [zen-browser/desktop#2104]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![image](https://github.com/user-attachments/assets/15106ab9-15c2-4567-8292-9ce82241a956)

the circle portion of the toggle is slightly off lol 

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-8a

### What platform are you seeing the problem on?

Windows

**Comment by mr-cheffy** [comment]
@JosueGalRe can I asign this to you?

**Comment by JosueGalRe** [comment]
@mauro-balades sure
