### ISSUE TITLE
Can't load shortcuts after resetting them to defaults

### ISSUE THREAD

**Issue by ghost** [zen-browser/desktop#2106]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Hello there.

I just upgrade my Zen to 1.0.1-a.9 to test if problem #1629 has been fixed. Unfortunately, I've encountered a new problem. Upon clicking "Reset shortcuts to default" and then reopening Zen, all my shortcuts vanish completely.

<img width="854" alt="图片" src="https://github.com/user-attachments/assets/70deed2a-1768-43e2-8604-e419d9ab394a">

I checked dev console and found an error:

```txt
Error loading shortcuts file DOMException: Could not open `/Users/my-macbook-user-name/Library/Application Support/zen/Profiles/some-profile.Default (alpha)/zen-keyboard-shortcuts.json': file does not exist (NS_ERROR_FILE_NOT_FOUND)
```

So I moved a JSON file from a clean profile into the mentioned directory and it worked. However, after I clicked Reset btn it disappeared again.

Thank you.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.9

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by brettonlewis** [comment]
I'm on windows and I also have no visible keyboard shortcuts.

**Comment by mr-cheffy** [comment]
Is there any more errors in the logs? Could you send full output?

**Comment by londeril** [comment]
The same thing happens to me on Linux

**Comment by ghost** [comment]
> I'm on windows and I also have no visible keyboard shortcuts.

Hello @mauro-balades .

Unfortunately, all the logs I've found are this one, in browser dev console:

```txt
Error loading shortcuts file DOMException: Could not open `/Users/my-macbook-user-name/Library/Application Support/zen/Profiles/some-profile.Default (alpha)/zen-keyboard-shortcuts.json': file does not exist (NS_ERROR_FILE_NOT_FOUND) ZenKeyboardShortcuts.mjs:534:15
    loadObject chrome://browser/content/zen-components/ZenKeyboardShortcuts.mjs:534
```

I tried Console.app (macOS), however it was a total mess...

**Comment by mr-cheffy** [comment]
That error is expected, I'll need to check what prevents it from getting the default shortcuts

**Comment by ghost** [comment]
> That error is expected, I'll need to check what prevents it from getting the default shortcuts

It seems that when we click "Reset to default", Zen removes the JSON instead of replacing it with a default one, maybe.

**Comment by mr-cheffy** [comment]
Id like to move this into the original issue, that was it's easier to manage. thanks
