### ISSUE TITLE
Workspace icon chooser appears behind the workspace editing panel

### ISSUE THREAD

**Issue by kiriappeee** [zen-browser/desktop#2107]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

- Created a workspace
- Tried to choose an icon for it
- Icon picker rendered behind the panel where we enter in the icon details

The above happens when we try to edit it after creating it as well. It is independent of screen resolution

Screenshot attached below

![image](https://github.com/user-attachments/assets/0bcb4253-b22e-41b5-9de1-282adbaa4b75)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.9 (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by JSGRD22** [comment]
Does not happen on Linux, same issue on Windows in a.10

**Comment by mr-cheffy** [comment]
This is fixed now, thanks!
