### ISSUE TITLE
Only the browser icon appears when opening the browser

### ISSUE THREAD

**Issue by moochh** [zen-browser/desktop#2110]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

This is the only thing I see when opening the browser. It seems like keyboard shortcuts are working but nothing is happening visually. 

![Screenshot 2024-10-15 145539](https://github.com/user-attachments/assets/0cd13d80-98b6-4bd4-9de3-c13462b0366a)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.9

### What platform are you seeing the problem on?

Windows

**Comment by jadeezomg** [comment]
happens for me when I try to open my secondary profile

**Comment by TakenMC** [comment]
same here

**Comment by TakenMC** [comment]
i managed to fix this by opening my prefs.js file under the profile path and removing the zen keyboard shortcut version option which was at the bottom

**Comment by jadeezomg** [comment]
that worked for me too, thanks a lot mate

**Comment by mr-cheffy** [comment]
This should be fixed now without any actions, thanks!
