### ISSUE TITLE
Only the current workspace's icon shows up, the rest are dots.

### ISSUE THREAD

**Issue by MikayelB** [zen-browser/desktop#2115]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

After I updated to the latest version (1.0.1-a.9  64-bit), the workspace icons showed up as dots. I might be mistaken (though I hope I'm not), but I believe it's a bug not a feature. The only icon that shows up, is the workspace's that I'm in.

To reproduce: enable the check mark for "Display workspaces as an icon strip" in the browser settings.

OS: Fedora Linux
Package type: flatpak
Desktop Environment: Gnome 46 + Wayland

![Screenshot from 2024-10-15 12-09-32](https://github.com/user-attachments/assets/141fdadb-5565-415b-986e-71711f1f8001)
![Screenshot from 2024-10-15 12-00-09](https://github.com/user-attachments/assets/9f76a2d5-70aa-426c-8060-6bef808d5243)
![Screenshot from 2024-10-15 12-00-04](https://github.com/user-attachments/assets/853ec65b-702b-4a4d-b9d8-a9a3c7a985ff)
![Screenshot from 2024-10-15 12-09-44](https://github.com/user-attachments/assets/a3fc00b9-7112-4f1f-9bbb-0cec55649822)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.9

### What platform are you seeing the problem on?

Linux

**Comment by YaYaTurre** [comment]
Same...on Mac (aarch64)

Additionally, when the browser restarted upon the update, 3 out my 4 workspaces disappeared. It only reloaded the workspace that was active when it restarted. I don't really know how, but I eventually got the others to reappear.

**Comment by TheJPMZ** [comment]
This also occurs on Windows 11.

**Comment by mayhmemo** [comment]
This also occurs on Windows 10

**Comment by rubaboo** [comment]
I think I have something related: I only ever had a default workspace before, i.e. never tried the workspaces functionality. Now I have no workspaces button at all, can't create a new workspace. However, I think the way I lost that button is not due to an update, but because I dragged it off the toolbar (in "Customize Toolbar..."). Once dragged off, it becomes invisible and non-functional. I know it's there because when I hover over an empty space the cursor changes to the "grabby hand" and I can drag that invisible thing in and out of the toolbar. However, when in the toolbar, it's just an empty space, not clickable and not highlighted on hover.

**Comment by mayhmemo** [comment]
@rubaboo can you send a picture or screen record of this? Guess it would be helpful

**Comment by Nicholaiii** [comment]
![{83D57B4D-E598-4F6F-9A4D-DE8EB5D37855}](https://github.com/user-attachments/assets/e87b1d36-5c22-4a6c-a5c6-0692f32baa16)
Windows 11 23h2 (Atlas 0.4.0)

This worked fine until the recent update.

**Comment by mr-cheffy** [comment]
This is a preference. Go to settings > tab management > workspaces and click on "hide deactivated workspaces"

**Comment by mayhmemo** [comment]
@mauro-balades cannot find it on 1.0.1-a.9:

![image](https://github.com/user-attachments/assets/77af4d10-2c35-42eb-90dc-61e530a20bb9)
![image](https://github.com/user-attachments/assets/5fcf2fac-adff-429c-aeef-19600cdd9aab)

**Comment by mayhmemo** [comment]
> This is a preference. Go to settings > tab management > workspaces and click on "hide deactivated workspaces"

Note: referring to 1.0.1-a.10

**Comment by rubaboo** [comment]
> @rubaboo can you send a picture or screen record of this? Guess it would be helpful

Reproducible in a new profile. I opened a separate issue #2173.

**Comment by MikayelB** [comment]
> ent > work

are you on the same version?

![image](https://github.com/user-attachments/assets/2912b69a-15fa-4181-a102-76425b7c2730)

**Comment by MikayelB** [comment]
> > This is a preference. Go to settings > tab management > workspaces and click on "hide deactivated workspaces"
> 
> Note: referring to 1.0.1-a.10

Important note ⚠️ 
I guess it wasn't yet added to the settings on 1.0.1-a.9, since I couldn't find it

**Comment by BoscoDomingo** [comment]
![image](https://github.com/user-attachments/assets/67ab7323-a87e-4d50-9c63-97504a6705f1)
![image](https://github.com/user-attachments/assets/b1a1c4c8-490f-475c-a955-13cac95ff126)

New version of this? My workspaces now don't even show up unless I switch with the shortcut. Afterwards, all icons are back

**Comment by MightyCoderX** [comment]
this is still an issue for me, the setting mentioned above doesn't seem to exist, not even in flags
