### ISSUE TITLE
1.0.1-a.9 visual bugs

### ISSUE THREAD

**Issue by greeeen-dev** [zen-browser/desktop#2117]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

There's two visual bugs I've found on Zen Browser 1.0.1-a.9.

- Bug 1: Toolbar is not properly themed when light mode is enabled. Instead of using the green accent color I've set, it defaults to a gray color. This does not happen when dark mode is enabled.
  <img width="1440" alt="Screenshot 2024-10-15 at 10 43 07" src="https://github.com/user-attachments/assets/7ac6a6e8-9207-4f1a-820b-27201d6f40e3">

- Bug 2: The default background color (i.e. the background color of the `body` tag when there is no background attribute set) should be plain white, but in Zen Browser it is transparent, revealing the browser's background color. This is more visible with dark mode enabled:
  <img width="1440" alt="Screenshot 2024-10-15 at 10 50 47" src="https://github.com/user-attachments/assets/0776eafe-36d8-4cce-b704-78be24eeac8e">

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.9

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by myamusashi** [comment]
Same here 
![image](https://github.com/user-attachments/assets/1bfc87b4-521c-4621-a278-2dc7c99a3295)
Floating url bar
