### ISSUE TITLE
open zen browser and click on keyboard shortcuts there it showing reset to default button is not working.

### ISSUE THREAD

**Issue by kranthivakati** [zen-browser/desktop#2118]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

1.open the browser 
2.click on settings 
3.click on keyboard settings 
4.reset to default button is not working.
expected : it should show all the shortcuts.
actual: the button is not working.
![image](https://github.com/user-attachments/assets/308294af-5252-4133-8306-9226dd7a7302)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.9

### What platform are you seeing the problem on?

Windows

**Comment by sjclayton** [comment]
Related #2111
