### ISSUE TITLE
Dim unloaded tabs

### ISSUE THREAD

**Issue by LinuxJava7** [zen-browser/desktop#212]
### What feature would you like to see?

Sidebery has this feature where unloaded tabs are dimmed, this is pretty useful

![image](https://github.com/user-attachments/assets/cce8f1dd-3182-4811-aa88-a3a6b3eecada)

The bottom two tabs are unloaded.

### What platform are you seeing the problem on?

Linux

**Comment by GunGunGun** [comment]
This can be done by using userChrome.css, but would be great to be default:
```


#TabsToolbar #tabbrowser-tabs .tabbrowser-tab[pending] .tab-content:not(:hover) .tab-icon-image{
    opacity: 0.5;
}



```

**Comment by LinuxJava7** [comment]
> This can be done by using userChrome.css, but would be great to be default:
> 
> ```
> 
> 
> #TabsToolbar #tabbrowser-tabs .tabbrowser-tab[pending] .tab-content:not(:hover) .tab-icon-image{
>     opacity: 0.5;
> }
> ```

That didn't seem to do anything, adding it to my userChrome.css

By the way, I mean unloaded tabs, not inactive tabs, like tabs that aren't in memory.

**Comment by mauro-balades** [comment]
I think `pending="true"` is the correct way, but this is just targeting the tab's icon. Im gonna change it to add the opacity to the whole tab. Thanks @GunGunGun!

**Comment by mauro-balades** [comment]
![Screenshot_20240811_170138](https://github.com/user-attachments/assets/d52e2e19-fec8-4411-894c-a44e8601c441)
 

https://github.com/zen-browser/desktop/commit/650337f9b525f1100d6c80ae8f04ec4106e4a600
