### ISSUE TITLE
Editing or creating new worksspaces no longer shows icon picker

### ISSUE THREAD

**Issue by Scarlov** [zen-browser/desktop#2121]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

After the update, aside from workspaces now appearing as dots (except for the current one), there is no longer a list of icons to assign to any  workspace.

![image](https://github.com/user-attachments/assets/a655182d-5074-46ac-9a2c-9969000335f5)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.9

### What platform are you seeing the problem on?

Windows

**Comment by mayhmemo** [comment]
Hey @Scarlov, how you doing?
So, i tested it now on Windows 10. When clicking on the icon, the picker will appear, but there is another problem: it's opening behind the workspace editor modal as follows:

![image](https://github.com/user-attachments/assets/a2919410-c020-466b-b9d3-86b348639e8b)

**Comment by Scarlov** [comment]
Hey @mayhmemo , I have seen the issue you posted earlier and checked if that is the same thing here, but I couldn't find the menu behind it. I minimised the window to see if it maybe opens to the side or something but it was nowhere to be found hence I opened a new issue.

![image](https://github.com/user-attachments/assets/a4ad7387-1e5d-4838-ba09-274ddc8ab042)

**Comment by mayhmemo** [comment]
@Scarlov okay, so these are two different problems. Maybe because we use different tab styles? Anyway, guess i should open another issue lol

**Comment by Scarlov** [comment]
@mayhmemo That's what I believe as well. Also, I don't have any extensions installed that modify the tab toolbar behavior.

**Comment by nanoraptor** [comment]
> Hey @Scarlov, how you doing? So, i tested it now on Windows 10. When clicking on the icon, the picker will appear, but there is another problem: it's opening behind the workspace editor modal as follows:
> 
> ![image](https://private-user-images.githubusercontent.com/84481401/376597567-a2919410-c020-466b-b9d3-86b348639e8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMDY4MzIsIm5iZiI6MTcyOTAwNjUzMiwicGF0aCI6Ii84NDQ4MTQwMS8zNzY1OTc1NjctYTI5MTk0MTAtYzAyMC00NjZiLWI5ZDMtODZiMzQ4NjM5ZThiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDE1MzUzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4NDliMGViMjQ0YjA2ZDRiMDJjZDVmYjBjNjllMWE2YzZiYzk2MGYwYTgwY2Y5MTRjNWFlOWQ1MDg0ZWViNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Z7xrnwnmSvNBOttffPn8vDZjKS5P8eZYyRUGiJIb-Mo)

I'm on windows 10 as well. I have the same issue as the OP. The panel is not appearing at all!

**Comment by Scarlov** [comment]
@nanoraptor I'm on windows 11, so maybe it is the same issue but it manifests differently depending on the windows version?

**Comment by mayhmemo** [comment]
@Scarlov i'm windows 10 as nanoraptor, so the problem shouldn't diverge using that logic, only if he is using the same workspace layout as yours.
@nanoraptor can you confirm that?

**Comment by mr-cheffy** [comment]
We are working on it, sorry!

It should look like this

![image](https://github.com/user-attachments/assets/cddd934d-c11a-4dc2-a795-3cc80a4dcff9)
