### ISSUE TITLE
Scripts from Tampermonkey stopped working in 1.0.1-a.9

### ISSUE THREAD

**Issue by MannixMD** [zen-browser/desktop#2122]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The issue that has been fixed in 1.0.1-a.6 is back in 1.0.1-a.9. The scripts from Tampemonkey and similar add-ons stopped working in sidepanel pages.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.9

### What platform are you seeing the problem on?

Windows

**Comment by mr-cheffy** [comment]
What do you mean with "stoped working"? Could you send examples?

**Comment by MannixMD** [comment]
So basically the scripts you have installed/added in the Tampermonkey addon stopped executing on the pages opened in sidepanel. It was working fine from 1.0.6 to 1.0.8. I installed the newest update today(1.0.9) and noticed that they do not work anymore. You can install Tampermonkey addon and try it yourself by adding new script to a page or search and install one from internet. It will work fine in normal tab but if you open the same page in sidepanel it won't work.

**Comment by BrhmDev** [comment]
> What do you mean with "stoped working"? Could you send examples?

Extensions have stoppen working in web panel. I'm guessing you reverted the previous fix for it?

**Comment by mr-cheffy** [comment]
Oh, so it's just the sidebar? I'll close this issue then as we already have one assigned to myself on the linear app
