### ISSUE TITLE
CTRL+Z doesn`t work

### ISSUE THREAD

**Issue by Paro89** [zen-browser/desktop#2123]
### Captchas

- [ ] I have read the instructions.
- [ ] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

When I set the keyboard shortcut in question and try to run for restore the closed tab it doesn't work. It works once or twice and then it doesn't work again. I also tried reinstalling the browser, but to no avail.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.9

### What platform are you seeing the problem on?

Windows

**Comment by mayhmemo** [comment]
Can confirm this on Windows 10, 1.0.1-a.9.

Note that originally the Ctrl + Z shortcut is being used by "Undo" action, but the problem persist even making the shortcut available to use.

**Comment by mr-cheffy** [comment]
Does this still happen?

**Comment by Caio-Sc** [comment]
Ctrl + z only works sometimes for me. Most times it will not work

**Comment by mr-cheffy** [comment]
Could you expand a bit on this? Does it only happen when not focusing on an input?

**Comment by Caio-Sc** [comment]
Never mind, I changed Ctrl + Z to 'Restore last closed tab' and that's what is not working. Ctrl + Z for undoing text works fine. I noticed that if I go to the browser settings, select any of the menu options and press Ctrl + Z, it will restore my tabs, but not on any other pages.

**Comment by Paro89** [comment]
A me il comando CTRL+Z non funziona nemmeno cambiandolo nelle impostazioni delle scorciatoie del browser. Ho provato, ma non funziona in nessuna maniera.
