### ISSUE TITLE
Side Panel Resets Pinned Link URLs When Opened

### ISSUE THREAD

**Issue by bmlauze** [zen-browser/desktop#2124]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Pinned links unload and reset to original pinned url upon opening side panel.  

Steps to reproduce:
1. pin a URL (Wikipedia) to the side panel
3. load the pinned url in the side panel
![Capture](https://github.com/user-attachments/assets/f07d19f3-833e-40b3-8059-5af65e8027f4)

5. navigate away from the original url 
![Capture1](https://github.com/user-attachments/assets/3c00945a-5635-4c72-9cee-b56f818dc65e)

7. close the side panel
8. reopen panel
10. pinned link resets to original url
![image](https://github.com/user-attachments/assets/f31f5804-8ee7-4aee-b7bc-3042375d3c3b)

If the steps are reproduced with a youtube video, audio can still be heard when panel is collapsed.  Link is only reset when the panel is reopened.

Relevant settings
1.  the setting "Restore pinned tabs to their originally pinned URL on startup" is unselected

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.9

### What platform are you seeing the problem on?

Windows

**Comment by mayhmemo** [comment]
Guess this is already being discussed on https://github.com/zen-browser/desktop/issues/2022

**Comment by bmlauze** [comment]
Thanks! Marking closed as this is a duplicate.
