### ISSUE TITLE
Bitdefender detects zen.exe as a virus.

### ISSUE THREAD

**Issue by tufkubie** [zen-browser/desktop#2125]
### Captchas

- [X] I have read the instructions.
- [ ] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

I use the latest version of Bitdefender Total Security.
![3a](https://github.com/user-attachments/assets/a0e9d85f-73c6-42dd-85c0-4ca49642ef72)
![2a](https://github.com/user-attachments/assets/83504730-e98f-4c04-a8a9-122838fa5eb2)
![1a](https://github.com/user-attachments/assets/447e2e43-4a7c-4436-9910-8ebb68dc1d82)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

v1.0.1-a.9-optimized

### What platform are you seeing the problem on?

Windows

**Comment by Unchanged4352** [comment]
> ### Captchas
> 
>     * [x]  I have read the instructions.
> 
>     * [ ]  I have searched existing issues and avoided creating duplicates.
> 
>     * [ ]  I am not filing an enhancement request.
> 
> 
> ### What happened?
> 
> I use the latest version of Bitdefender Total Security. ![3a](https://private-user-images.githubusercontent.com/79758999/376610905-a0e9d85f-73c6-42dd-85c0-4ca49642ef72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMDQ1ODgsIm5iZiI6MTcyOTAwNDI4OCwicGF0aCI6Ii83OTc1ODk5OS8zNzY2MTA5MDUtYTBlOWQ4NWYtNzNjNi00MmRkLTg1YzAtNGNhNDk2NDJlZjcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDE0NTgwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwYzEyYWQ5NjYwZmZmMTVmZGI2OTdiMDU0ZTQ1NjQyNzJkY2NmMjgyYzNkZTM3YzY4MTM2NmVkYTYyYTM0ZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nuUCUzVCWchGhnehvtFs0876ySzROH227RmuKnYNT7I) ![2a](https://private-user-images.githubusercontent.com/79758999/376610916-83504730-e98f-4c04-a8a9-122838fa5eb2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMDQ1ODgsIm5iZiI6MTcyOTAwNDI4OCwicGF0aCI6Ii83OTc1ODk5OS8zNzY2MTA5MTYtODM1MDQ3MzAtZTk4Zi00YzA0LWE4YTktMTIyODM4ZmE1ZWIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDE0NTgwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3YjY3MDY1Mzg5NDk1MzU1NjE1NDNkMzJjNzg5NmFlZTQ0N2NjYTgxYzlhMzBhNWMzNzFkY2FlZTNlNDQzMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-LislCNMO8C9oWtCbCFL_d2R1pyxigPTP9ltj-FjH7k) ![1a](https://private-user-images.githubusercontent.com/79758999/376610918-447e2e43-4a7c-4436-9910-8ebb68dc1d82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMDQ1ODgsIm5iZiI6MTcyOTAwNDI4OCwicGF0aCI6Ii83OTc1ODk5OS8zNzY2MTA5MTgtNDQ3ZTJlNDMtNGE3Yy00NDM2LTk5MTAtOGViYjY4ZGMxZDgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDE0NTgwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjZTczOTVlZDRlMDMzYjEzMGZiOTFlNWY3NDljZTczNDc0YTUyMjlhMzZmN2MwNDhiZDMxZTNjNzMyMWNhY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XVHApOOk4AwEqpB3_y0VuBxQKyfVYaIXeAQSWe0B28A)
> ### Reproducible?
> 
>     * [x]  I have checked that this issue cannot be reproduced on Mozilla Firefox.
> 
> 
> ### Version
> 
> v1.0.1-a.9-optimized
> ### What platform are you seeing the problem on?
> 
> Windows
> ### Relevant log output
> 
> _No response_

#37

**Comment by Unchanged4352** [comment]
#37

**Comment by mr-cheffy** [comment]
> I have searched existing issues and avoided creating duplicates.

please search for duplicates. It's the first pinned issue there is. it saves me a lot of time, thanks!

**Comment by Unchanged4352** [comment]
> > I have searched existing issues and avoided creating duplicates.
> 
> please search for duplicates. It's the first pinned issue there is. it saves me a lot of time, thanks!

Actually i think u can make it box requires to be ticked
