### ISSUE TITLE
Logins do not work when using special characters

### ISSUE THREAD

**Issue by factor3** [zen-browser/desktop#2132]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

If I log into a website whose password contains special characters, the login fails

**Steps to reproduce the behavior:**

1. Select a website that requires a login. Make sure the password has characters like '_' or '@' in it
2. Enter your username and password
3. Go to another browser (like Chrome or Firefox), go to the same URL and enter the username and password

**Expected behavior**
You should be logged in to the site (in Zen) as well as in the (for example) Firefox browser

**Actual Behavior**
In Zen: You get a login failure -- even if you put in the correct password
In Firefox: You get logged in

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.8 (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by mr-cheffy** [comment]
Try disabling tracking protection or clearing data. Special characters have no effect on what's sent to the server. If it persists, id contact the website that's failing since it's probably on their side.

**Comment by factor3** [comment]
mauro-balades:

Are you talking about clearing data on the Zen browser??? If so, that did nothing. I didn't expect i to, because my access to the site was done *just after* installing the Zen browser. There was no "tracking" or "data" to be cleared!

As for the website  that's "failing": the website is Comcast!  And please note that, as I stated, the *Firefox browser* was able to log me in without problems, while the Zen browser kept failing the login. In fact, I deliberately used Firefox to log in because of Zen's Firefox- based nature. The fact is, when I log into my *Comcast* account  with Firefox I can log in. When I attempt to log into the same site with the same account with Zzen, I cannot.

This indicates (at least to me) that it is Zen, not the website, that has the problem.

Please do not keep this issue closed until you can run the test that I did, and show that Zen actually logs into a site that is using pecuial characters in the password.
