### ISSUE TITLE
Workspace icon is off centred

### ISSUE THREAD

**Issue by nanoraptor** [zen-browser/desktop#2133]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![Screenshot (143)](https://github.com/user-attachments/assets/8c1947b9-626a-49bb-981d-6724ec83190d)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.10 (64-bit) (Generic/Non-Portable)

### What platform are you seeing the problem on?

Windows

**Comment by hydro63** [comment]
Same here (i blured the page and user infromation):

![Screenshot 2024-10-17 215041](https://github.com/user-attachments/assets/18c7f84a-74d3-4548-8945-f7549719d6e4)

**Comment by mr-cheffy** [comment]
This has been fixed now, thanks!
