### ISSUE TITLE
Setting New tabs to "Firefox Home (Default)" does not carry over after relaunch

### ISSUE THREAD

**Issue by panic-canine** [zen-browser/desktop#2135]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When I open a new tab I am greeted by a blank page. I dislike this behavior, so attempted to change the appropriate setting: "New tabs" under "New Windows and Tabs" to "Firefox Home (Default)." This works, but confusingly, upon relaunching the browser this setting reverts to "Blank Page." This leads me to believe it's specified in prefs.js or someplace, but I cannot figure out what would control this.

I have installed Zen Browser through zen-browser-bin on the AUR.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1.a.9-1

### What platform are you seeing the problem on?

Linux

**Comment by salamijason** [comment]
heylo you still get this on the latest version? 1.0.1-a.14 as of Oct 30

**Comment by salamijason** [comment]
No response in 4 days, will be closing this issue. Please reopen if you are still facing this issue.

**Comment by panic-canine** [comment]
I apologize for my late response. I've just tested on 1.0.1.a.17-1 and am unfortunately still running into this issue.

**Comment by salamijason** [comment]
Hmm I see. Could you go to about:config (type it into your url bar) and search for `startup.homepage` and screenshot what you see there? Thank you!
![image](https://github.com/user-attachments/assets/fe75e6c4-7b8a-4316-8fad-545382f5133d)

**Comment by salamijason** [comment]
No response in 1 week. For the sake of keeping the roadmap clean, I'll be closing this issue but please reopen if you still get this issue. Thank you.

**Comment by Thomas-Philippot** [comment]
Hello facing the same issue on Arch Linux, both `Homepage and new windows` and `New Tabs` are set to `Firefox Home (default)` here is my `about:config` settings.

![Image](https://github.com/user-attachments/assets/73881449-efb8-4f67-a37a-089b079eaa4f)

When i open a new tab/window :

![Image](https://github.com/user-attachments/assets/1818a663-7eb7-48f7-ba0a-7826d97e5710)

My `about:home` page

![Image](https://github.com/user-attachments/assets/671cf482-2fa3-496c-ab1b-8692e641a62f)

**Comment by salamijason** [comment]
Oh that's strange. Could you try on a new profile? There were a couple changes to new tabs in recent updates and it could've messed with the settings. 

https://docs.zen-browser.app/guides/manage-profiles

**Comment by ghost** [comment]
Hi @salamijason 

I've the same issue as described by the other users in this thread. I'm on the latest zen-browser version (1.9b, 64-Bit), running on the latest Linux Fedora 41 (Gnome).

When I start the browser app, an empty tab is shown. Opening a new tab also shown an empty screen.
Instead I'd like to see the "**about:home**" page, as it is configured in the browser settings.

I tried creating a new profile. But that didn't really help. I had the same issue with the new profile as with the default profile.

Could this github issue be reopened and looked into again?
