### ISSUE TITLE
Streaming services aren't avaliable to use in this browser

### ISSUE THREAD

**Issue by Truchlo-S** [zen-browser/desktop#2138]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Streaming services such as Prime Video, Netflix, HBO Max, Disney+ aren't able to play videos in our browser.
I disabled any vpns, adblocks or whatnot just to be sure.
You can login to your streaming account, choose a movie/tv series to play, click play but immediately you get an error.
![obraz](https://github.com/user-attachments/assets/a3151398-832f-4090-937c-2920a4437976)
![obraz](https://github.com/user-attachments/assets/9d9a603e-e21e-4701-9dbc-f539dc1a502b)
Could we get a solution with drm/widevine working only on streaming pages or toggle, or do we have to install sus plugins for it to work? :/
I would prefer not to keep other browsers just for streaming.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.8

### What platform are you seeing the problem on?

Linux, Windows

**Comment by sjclayton** [comment]
Zen does not support DRM content currently on Windows or macOS (Support is available only on Linux)

See https://docs.zen-browser.app/faq#why-cant-zen-browser-play-drm-protected-content for more information.

This can be closed. Thanks!
