### ISSUE TITLE
Error getting location: User denied geolocation prompt

### ISSUE THREAD

**Issue by thepick** [zen-browser/desktop#214]
### What happened?

On the website https://onlinecompass.net/gps-coordinates, when toggling on "Location Services" on the web page, the message "Error getting location: User denied geolocation prompt" pops up. Other, similar websites can't access my location either since it appears the prompt to allow geolocation is blocked.
<img width="316" alt="Error getting location" src="https://github.com/user-attachments/assets/6f3f4fda-68d9-4501-84fa-9d5584bb0c8a">

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.16 (64-bit)

### Severity impact

Medium

### What platform are you seeing the problem on?

Windows

**Comment by thepick** [comment]
Nevermind! Allowing access to geolocation was toggled off by default in the settings. Toggling it on fixed the problem.

**Comment by dasturchioka** [comment]
How do we change the location manually? Like on Chrome or Brave we have Sensors in Developer mode. Can we do the same thing with Zen too?
