### ISSUE TITLE
Keyboard shortcuts broken

### ISSUE THREAD

**Issue by TakenMC** [zen-browser/desktop#2140]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I have noticed most of my keybinds are broken only ones that seem to be working rn are Ctrl+t and Crtl+w idk about others but I can't toggle compact mode, etc

I attched logs below where the default keybinds seem to fail to load

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.9

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
ZenThemeImporter: Initiating Zen theme importer ZenThemesImporter.mjs:45:13
ZenThemeImporter: Zen theme imported ZenThemesImporter.mjs:64:15
Error loading shortcuts file DOMException: Could not open `C:\Users\<redacted>\AppData\Roaming\zen\Profiles\l7q5nqrr.Main\zen-keyboard-shortcuts.json': file does not exist (NS_ERROR_FILE_NOT_FOUND) ZenKeyboardShortcuts.mjs:534:15
Zen CKS: Loading default shortcuts... ZenKeyboardShortcuts.mjs:553:11
Zen CKS: Migrating shortcuts from version 0 to 2 ZenKeyboardShortcuts.mjs:743:15
Zen CKS: Loading default shortcuts... ZenKeyboardShortcuts.mjs:553:11
Uncaught (in promise) TypeError: this[#key] is undefined
    getKeyName chrome://browser/content/zen-components/ZenKeyboardShortcuts.mjs:428
    migrate chrome://browser/content/zen-components/ZenKeyboardShortcuts.mjs:772
    migrateIfNeeded chrome://browser/content/zen-components/ZenKeyboardShortcuts.mjs:749
    init chrome://browser/content/zen-components/ZenKeyboardShortcuts.mjs:812
ZenKeyboardShortcuts.mjs:428:5
```

**Comment by sjclayton** [comment]
@TakenMC 

Should be fixed in a.10, try updating.

**Comment by TakenMC** [comment]
works fine now
