### ISSUE TITLE
Unable to open mods from zen mods page using vimium extension

### ISSUE THREAD

**Issue by nanoraptor** [zen-browser/desktop#2147]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

On pressing f or F using [vimium](https://addons.mozilla.org/en-US/firefox/addon/vimium-ff/) extension, It will list all the clickable elements in the webpage. But it is not showing the individual mod's page in the site. Ideally it should be near the preview image of the mod. But it is not there, perhaps the html is not encoded properly. Making a part of the image explicitly clickable in HTML will avoid this problem ig. 

![image](https://github.com/user-attachments/assets/32b9ec27-6786-4f5d-99cb-b5ea35252715)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.10  (64-bit) (Generic/Non-Portable)

### What platform are you seeing the problem on?

Windows

**Comment by nanoraptor** [comment]
Another issue that bothers me with the site is that if I click "Go Back" from the mod page it goes back to the first mod in the list of the first page irrespective of which mod was in selection previously. If I wanted to go back and click an extension which was previously below the extension I just viewed, I have to go down all the way to get back to where I was previously. This is pretty annoying!!!!!!
![image](https://github.com/user-attachments/assets/708cf252-628e-432e-9906-1cec0928ec5c)

**Comment by sjclayton** [comment]
@nanoraptor 

Issues pertaining to the Zen website should be filed over there --> https://github.com/zen-browser/www/issues
