### ISSUE TITLE
checkbox issue in web extension options

### ISSUE THREAD

**Issue by lazymonkey2** [zen-browser/desktop#215]
### What happened?

Hello, I'm usinf zen v1.0.0-a.16 (64-bit) on win10.
I have installed this extension:
https://addons.mozilla.org/en-US/firefox/addon/select-after-closing-current/

and when going to options I have noticed an issue with check boxes: when I click on a checkbox then it becomes invisible!
instead on firefox 129 it's working as expected.

see this screenshot (the third checkbox is checked)
![image](https://github.com/user-attachments/assets/022dc8a8-56e1-4786-8553-a6d1190825eb)

Changing themes seems to not affect the issue (tried zen dark and zen dream).

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.16 (64-bit)

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
Duplicate of https://github.com/zen-browser/desktop/issues/103
