### ISSUE TITLE
Firefox version shown incorrect

### ISSUE THREAD

**Issue by rubaboo** [zen-browser/desktop#2150]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Reading Release notes.
> Release notes for 1.0.1-a.10 🎉
...
About page will now display the firefox version used

Cool. Let's check it out.

**⋯ > Help > About Zen**
1.0.1-a.10 (Firefox **130.0**)

Uh-oh. Isn't that a bit old? Have to dig in and maybe rethink using Zen.

> Release notes for 1.0.1-a.8 🎉
...
This release brings Zen to Firefox v131.0.2, which patches a significant security vulnerability.

Ah, never mind then. Perhaps actually display the Firefox version next time? 😉

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.10

### What platform are you seeing the problem on?

Windows

**Comment by win98se** [comment]
It even says this [here](https://github.com/zen-browser/desktop#%EF%B8%8F-compatibility) -
> Zen is currently built using firefox version `131.0.3`! 🚀

Is the displayed version hardcoded? 🤔

**Comment by nazmiyigitefe** [comment]
Mauro said this about it:

<img width="858" alt="Ekran Resmi 2024-10-16 07 46 41" src="https://github.com/user-attachments/assets/75b8f4bc-7531-44fa-8e05-33e3fef04d19">

**Comment by win98se** [comment]
> Mauro said this about it:
> 
> <img alt="Ekran Resmi 2024-10-16 07 46 41" width="858" src="https://private-user-images.githubusercontent.com/71214979/376892740-75b8f4bc-7531-44fa-8e05-33e3fef04d19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNTU5NzYsIm5iZiI6MTcyOTA1NTY3NiwicGF0aCI6Ii83MTIxNDk3OS8zNzY4OTI3NDAtNzViOGY0YmMtNzUzMS00NGZhLThlMDUtMzNlM2ZlZjA0ZDE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDA1MTQzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyNzg3NzE2ZDE1YWIxMmJjOWIxZWZjZTNmMzQ2MzI4OWI3NzBjNDhmMmVjMzgwNTU4Mzk5ZjFkMzdlMGQ3OTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zRvn9ppP0WzObdbvZSk9qRXFIIAPVoWmKte60oYtxfI">

Yikes. I'm not in the Discord server yet.

**Comment by mr-cheffy** [comment]
Thanks! This has been fixed for the next release, thanks!
