### ISSUE TITLE
Browser not working on some websites

### ISSUE THREAD

**Issue by an-mra** [zen-browser/desktop#2151]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Hello, i updated today the browser to the latest version 1.0.1-a.10 (64-bit), and it stopped functioning properly.
For premise i live in China and i have to use vpn to access sites as Youtube, google and so on; until yesterday everything worked amazingly (tried to switch many servers, but the vpn is not the problem).
I tried to use another browser and everything works as usual, but not on this new version of Zen :( ; in general all the websites load slowly or not at all

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.10 (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by prochy-exe** [comment]
I had the same issue, messenger failed to load and also the zen browser site did, i fixed it by downgrading to a8, clear the temporary site data and cookies and updated back to a10 and now the problem is gone

**Comment by an-mra** [comment]
> I had the same issue, messenger failed to load and also the zen browser site did, i fixed it by downgrading to a8, clear the temporary site data and cookies and updated back to a10 and now the problem is gone

Thank you , let me try :)

**Comment by an-mra** [comment]
@prochy-exe  did everything but is still not working; i guess i will stick with a8 for now;
crazy the a8 works perfectly and super fast :( . 
I will try again, thank you for the help

**Comment by Eff0rtly** [comment]
I had the same issue

**Comment by bangoim** [comment]
I do not have to use VPN but some websites are not working for me either such as YouTube and Twitter.

**Comment by an-mra** [comment]
> I do not have to use VPN but some websites are not working for me either such as YouTube and Twitter.

yes especially Youtube ; tried also today to downgrade and upgrade but so far the issue has not been solved

**Comment by prochy-exe** [comment]
> > I do not have to use VPN but some websites are not working for me either such as YouTube and Twitter.
> 
> yes especially Youtube ; tried also today to downgrade and upgrade but so far the issue has not been solved

I just came back home from doms and upgraded my main pc to the latest version from a8 and i have no issues what so ever. I am not sure what the problem might be, both cases were on windows

**Comment by bangoim** [comment]
> I just came back home from doms and upgraded my main pc to the latest version from a8 and i have no issues what so ever. I am not sure what the problem might be, both cases were on windows

I use MacOS, so maybe that's it.

**Comment by Eff0rtly** [comment]
1.0.11 still

**Comment by mr-cheffy** [comment]
Does disabling tracking protection make it better?

**Comment by an-mra** [comment]
> Does disabling tracking protection make it better?

haven't thought about that ; i will try

**Comment by an-mra** [comment]
> Does disabling tracking protection make it better?

nope , still not working :( disabled the tracking protection , disabled all the extension , tried all the ( DNS over HTTPS ) options, still not working. no idea why, from the 1.0.9 above they all not working

**Comment by an-mra** [comment]
> Does disabling tracking protection make it better?

today i installed on my mac and it works perfectly , so i guess is a windows issue 🤷🏽‍♂️

**Comment by RayZ3R0** [comment]
@an-mra Hello, does this issue still happen on the latest version a.14 on windows?

**Comment by an-mra** [comment]
> @an-mra Hello, does this issue still happen on the latest version a.14 on windows?

Hello :) i haven't updated since last time haha; let me try now

**Comment by an-mra** [comment]
> @an-mra Hello, does this issue still happen on the latest version a.14 on windows?

Nope, still not working :(((

**Comment by an-mra** [comment]
went back to a.08

**Comment by novichiv** [comment]
@an-mra Could you please elaborate/provide logs(har)/any other kind of reproducible environment?
What is your VPN protocol and VPN client type?
Also: Please check if it's reproducible in Firefox (131.0.3)

**Comment by salamijason** [comment]
No response in 2 weeks, will be closing this issue. Please reopen if you still get the bug.

**Comment by TheSketty** [comment]
having same issue on gradio.app and all support.something.com websites, all of them are loading perfectly in another firefox browser or when using vpn

**Comment by itsmadson** [comment]
same issue on X.com and reddit.com

**Comment by Midnight95** [comment]
Can't open hypr.land website. Super annoying

**Comment by Reversean** [comment]
> Can't open hypr.land website. Super annoying

Same thing. I have issues with sites:

- [hypr.land](https://hypr.land/)
- [ii.clsty.link](https://ii.clsty.link/)

After long time i get message "The connection has timed out"

On original firefox both sites are loading initially very long, then work some time fine, then again connection hangs on uncertain time.

Both sites work excellent on any chromium-based browser without any problems.

Following Firefox guides and threads on various forums, I tried the following:

- open sites in private mode
- open sites in new browser profile
- set "No proxy" in connection settings (actually i don't have proxy, anyway tried)
- set "Off" in DNS over HTTPS settings 
- set "Increased Protection" in DNS over HTTPS settings
  - default
  - https://dns.comss.one/dns-query
  - https://dns.google/dns-query
  - https://doh.opendns.com/dns-query
- clear dns cache (did after any change in DoH settings)
- set "true" for network.dns.disableIPv6

**Platform:** linux 6.17.1.arch1-1

**Zen-browser version:** 1.16.4b-1 (bin-version from [aur](https://aur.archlinux.org/packages/zen-browser-bin))

**Comment by Reversean** [comment]
Could you please reopen issue?

**Comment by an-mra** [comment]
Hello everyone, i opened this issue long time ago, i couldn't access to github for long time, anyway after months and months i managed to make Zen work finally ; i will send screenshot tomorrow when i'll go back to work ( FYI there are some issue when the computer is managed by a corporation ) and i live in China (i'm pretty sure there might be some sort of blocking in the midst of everything as well) unfortunately it says that i don't have permission to reopen the issue;  i will update you tomorrow :)

**Comment by Reversean** [comment]
Hey, @an-mra! Are you still planning to send solution?

**Comment by an-mra** [comment]
> Hey, [@an-mra](https://github.com/an-mra)! Are you still planning to send solution?

Hi Reversean, sorry for delay, this is what worked for me; i dont't know why , but installing privacy tweaks helped to unblock it as well (even tho if i disable will still work); i would say right after i changed the https and dns started working again. 

<img width="787" height="688" alt="Image" src="https://github.com/user-attachments/assets/6edf114f-47ec-498b-9f45-090cc9bcf46b" />

<img width="811" height="276" alt="Image" src="https://github.com/user-attachments/assets/2cbcabf7-f172-439f-be56-d477aa3bfcb7" />

<img width="772" height="610" alt="Image" src="https://github.com/user-attachments/assets/bd3e8c22-302e-4f7c-b67c-0aad2160f714" />
