### ISSUE TITLE
Instructions on Installing the .tax.bz2 file on Linux

### ISSUE THREAD

**Issue by tanaybhomia** [zen-browser/desktop#2153]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I have seen that the zipped file version is on a better build than the flatpak source can we add instructions on installing that to the machine as a native app ?

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.9

### What platform are you seeing the problem on?

Linux

**Comment by LeMoonStar** [comment]
The archive is not an installer. Instead, it just provides all files you need to execute Zen.

You can copy these files to a location of your choice, add them to your path and do whatever you want to.

To make Zen integrate with your Desktop Environment, you need a `.desktop` file. You can find an example in the `AppDir` (From memory, the name might be slightly different - I can't easily check this on my phone) directory of this repository.

Alternatively, you can use the AppImage install script:  `bash <(curl https://updates.zen-browser.app/appimage.sh)`

This will take care of copying the files and creating the `.desktop` file for you.

Do note, that in both cases, updating is more complicated.

**Comment by tanaybhomia** [comment]
Thanks I will try this
