### ISSUE TITLE
Sidebar "Expands Tabs on Hover" option randomly resets to "Don't Expand Tabs by Default"

### ISSUE THREAD

**Issue by theovgl** [zen-browser/desktop#2156]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I selected the `Expands Tabs on Hover` option. But I've noticed that sometimes this setting randomly reverts to `Don't Expand Tabs by Default` without any clear trigger or action on my part.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.8 (aarch64)

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by Richard-Woessner** [comment]
Are you using compact mode

**Comment by Richard-Woessner** [comment]
Im trying to recreate it now

**Comment by Kodehawa** [comment]
This has happened to me too. It is quite random, and annoying.

**Comment by theovgl** [comment]
@Richard-Woessner no, I'm not using compact mode

I'm trying to reproduce it, but it seems to be very random and I cannot find what triggers it. If I find it, I may try to fix it

**Comment by Richard-Woessner** [comment]
Did either of you hit the toggle sidebar button? I'm looking around and I found this. I only ask because I wouldn't expect the toggle button to revert a setting like expand on toggle. Is this intended 

```
// ZenUIManager.js
  toggleExpand() {
    let expanded = !this.expanded;
    Services.prefs.setBoolPref('zen.view.sidebar-expanded', expanded);
    Services.prefs.setBoolPref('zen.view.sidebar-expanded.on-hover', false);
  },
```

**Comment by Kodehawa** [comment]
> Did either of you hit the toggle sidebar button? I'm looking around and I found this. I only ask because I wouldn't expect the toggle button to revert a setting like expand on toggle. Is this intended
> 
> ```
> // ZenUIManager.js
>   toggleExpand() {
>     let expanded = !this.expanded;
>     Services.prefs.setBoolPref('zen.view.sidebar-expanded', expanded);
>     Services.prefs.setBoolPref('zen.view.sidebar-expanded.on-hover', false);
>   },
> ```

It's probably this. I've hit that button by mistake a few times tbh.

**Comment by theovgl** [comment]
Oh yes I've just tried it, it seems to be related to this toggle.
I doubt it is intended though, the UI seems buggy when doing it.

I'll try to dig in the code and fix it 

https://github.com/user-attachments/assets/81a2a03f-3d8f-4be9-898e-0612cb40e2e5

**Comment by Richard-Woessner** [comment]
@theovgl okay let me know if you don't have the time to look at it. I'd be happy to tackle it too. Happy we possibly found the issue though

**Comment by theovgl** [comment]
Nice work @Richard-Woessner ! 🎉
I think we can close this issue, right ?

**Comment by Richard-Woessner** [comment]
Yessir @theovgl
