### ISSUE TITLE
closed tabs are not really closed

### ISSUE THREAD

**Issue by lazymonkey2** [zen-browser/desktop#216]
### What happened?

Hello,
with a.16 version I have an issue with closed tabs: they are not really closed.
I mean they disappears from the vertical tabs panel, but are still present if I click on "> List all tabs" button.
Also after restart they closed tabs are visible again in the vertical tabs panel.

![image](https://github.com/user-attachments/assets/02f64618-a378-4833-b041-31e5d922eeef)

In the screenshot I have closed the "Firefox" tab, and it's correctly not visible in vertical tabs panel.
But it is still visible in the popup list of tabs.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0 a.16

### Severity impact

Medium

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
Fixed with https://github.com/zen-browser/desktop/commit/c57db962f8e48b2594160d44c5e4ea7c96c2f70c, thanks!

> It will reflect on the next release
