### ISSUE TITLE
visual differences between old and new profiles

### ISSUE THREAD

**Issue by QW4D** [zen-browser/desktop#2161]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

on my old profile the isn`t settings button and new tab button and location of the new tab button is different
![изображение](https://github.com/user-attachments/assets/4f782ad7-89c1-4f01-b0d3-dafd99c370cd)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.10

### What platform are you seeing the problem on?

Windows

**Comment by QW4D** [comment]
also can`t select workspace icon in old profile

**Comment by mr-cheffy** [comment]
Ill move this issue to https://github.com/zen-browser/desktop/issues/1971
