### ISSUE TITLE
Pin tabs not 'pinned' in new windows opened

### ISSUE THREAD

**Issue by ishtpreetahuja** [zen-browser/desktop#2163]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Pinned tabs that stay as rectangles on the top of the side bar are not there on the windows newly created after the 1st one.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.10

### What platform are you seeing the problem on?

Windows

**Comment by BoscoDomingo** [comment]
Not sure if the same issue, but pinned tabs are not loaded upon opening the program (at least on Windows) and I have to manually load them. They are there, just grayed out.

**Comment by salamijason** [comment]
> Not sure if the same issue, but pinned tabs are not loaded upon opening the program (at least on Windows) and I have to manually load them. They are there, just grayed out.

@BoscoDomingo are you maybe using the SuperPins mod? It has a toggle for causing this exact behavior ![Image](https://github.com/user-attachments/assets/fa0dce03-9415-4bfa-923e-29b0efe38b79)

**Comment by salamijason** [comment]
@ishtpreetahuja Could you try again on the latest version of the browser? (1.0.1-a.14) If you're still getting the issue, could you provide a screen recording?

**Comment by jpumfrey** [comment]
@salamijason I am pretty certain this issue can be marked as resolved with the release of the new Zen Essentials which mr. workspaces is currently working on where pinned tabs will persist on top of every window instance.

mr. workspaces has included a preview on Discord of how we're expecting this to behave:
https://discord.com/channels/1088172780480114748/1275868858288177314/1300885015466610709
