### ISSUE TITLE
Vertical Tabs expand button is slow

### ISSUE THREAD

**Issue by Tuquilo9** [zen-browser/desktop#2165]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Hello!

I use a low-end laptop but it still can runs firefox with no problems. But when using Zen, when I click on the button to expand Vertical Tabs, it takes ~1s, but when I use the auto-expand option, it is instant when I hover over the vertical tabs (without delay).

(I'm sorry my english is bad)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.10 (Firefox 130.0) (64-bit)

### What platform are you seeing the problem on?

Linux

**Comment by kranthivakati** [comment]
can you share a video so that developer can easily identify the issue.

**Comment by Tuquilo9** [comment]
Of course !

https://github.com/user-attachments/assets/5125f666-ceee-439f-b990-3fcf4563e377

**Comment by Tuquilo9** [comment]
I don't know if it can help, but in Firefox Nightly, this button doesn't have the delay.

**Comment by mr-cheffy** [comment]
This is because the button does other things than just set a "hover" state. Ill look into ways of optimizing it more for low-end PCs. But ill close this as it's not really an issue, sorry.

**Comment by Tuquilo9** [comment]
This issue can be marked as done, it's now instant, thanks to all the contributors the browser is amazing!

**Comment by Tuquilo9** [comment]
This issue can be marked as done, it's now instant, thanks to all the contributors the browser is amazing!
