### ISSUE TITLE
Custom Wallpaper requesting.

### ISSUE THREAD

**Issue by SmokeyPlayz** [zen-browser/desktop#2166]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

This is isn't a actual bug but maybe a solution or a small feature that can be put to allow users to upload a custom wallpaper to they're "new tab" Page quite unfortunate that this browser this haven't yet added The custom wallpaper feature and also one more thing, can their be more performance settings or something to boost the browser Speed like the browser thorium i did use that one before this one but, For me i had some problems so when i heard about zen i just straight on installed it on my linux laptop then my windows 11 pc and as the sight is improving more perhaps there can be like mods to apply to help maybe lower the resources the browser use for the best user-friendly performance stability.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.10

### What platform are you seeing the problem on?

Windows

**Comment by kristijanribaric** [comment]
Hey there, issues are only for reporting bugs, please use Discussion page for feature requests.
