### ISSUE TITLE
Profile pics on threads.net not showing on mac OS sequoia 15.0.1

### ISSUE THREAD

**Issue by SpiderWithShoes** [zen-browser/desktop#2171]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Profile pictures do not show up. only text appears. 

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.10 (Firefox 130.0) 

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by busybox11** [comment]
No issue on my end. Could it be related to your extensions, or your privacy settings?

**Comment by RayZ3R0** [comment]
@SpiderWithShoes does this still happen in a.14, have you tried in a new profile?

**Comment by Richard-Woessner** [comment]
Working for me on mac version 1.0.1-t.19. Poster hasn't responded either. Closing
