### ISSUE TITLE
Workspaces button is lost after moving it out of sidebar

### ISSUE THREAD

**Issue by rubaboo** [zen-browser/desktop#2173]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Customize Toolbar, move the workspaces button to holding area.
Restart the browser. The button is now invisible. It can be dragged on and off the sidebar, but remains invisible and non-functional.

https://github.com/user-attachments/assets/17f0e1b8-fdad-41a3-8eac-7f8547e6ce81

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.10

### What platform are you seeing the problem on?

Windows

**Comment by flifloo** [comment]
I have the same problem with version 1.0.1-a.12 on Linux (AppImage)

**Comment by xGenius123** [comment]
I have the same issue but with the new tab button on version 1.0.1-a.12

**Comment by salamijason** [comment]
Bug could not be reproduced on latest version 1.0.1-a.14. Could you please try again on the latest ver and let me know how it goes?

**Comment by rubaboo** [comment]
I cannot reproduce it in the latest. Thanks.
