### ISSUE TITLE
Bitwarden addon: Right-click in text field doesn't show Bitwarden menu tab

### ISSUE THREAD

**Issue by ruvenistan** [zen-browser/desktop#2175]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

On sites with non-standard names for text fields, e.g. comments section at emptywheel.net, Bitwarden allows definition of custom fields. The user right-clicks in the form field, a menu appears, and the user can "Copy custom field name". While this works in Firefox, The Zen browser doesn't show this menu on any site.

o I'm using the Bitwarden Firefox addon. Version: 2024.9.1
https://addons.mozilla.org/en-US/firefox/addon/bitwarden-password-manager/

o I'm using Firefox 128.3.0esr (64-bit) on Debian Linux, testing branch

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.10 (Firefox 130.0) (64-bit)

### What platform are you seeing the problem on?

Linux

**Comment by ruvenistan** [comment]
OOPS: Please disregard above: I inadvertently found out how to fix the issue. I was fiddling with the autofill settings trying to document another "bug", but both went away when I changed some of the settings.

Sorry for the trouble.

**Comment by sjclayton** [comment]
If this is resolved for you, this issue can be closed. Thanks!

**Comment by ruvenistan** [comment]
Yes, the issue is resolved. Sorry for the trouble.
The Zen browser has been great! Now better without self-inflicted problems.
:-)
