### ISSUE TITLE
Inconsistent padding on toolbar buttons

### ISSUE THREAD

**Issue by ryan-griffin** [zen-browser/desktop#2176]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Example:
[Screencast From 2024-10-17 00-58-21.webm](https://github.com/user-attachments/assets/e3e37c9e-ac2e-45e5-b388-0f7c498dbd4c)

Toolbar buttons in the sidebar have the smaller padding but only when the sidebar is expanded.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.10

### What platform are you seeing the problem on?

Linux

**Comment by Richard-Woessner** [comment]
I found the issue. The `PanelUI-menu-button` child has a padding of 8 while the `unified-extensions-button` and the others have a padding of 6.

Ill look into it

<img width="1181" alt="image" src="https://github.com/user-attachments/assets/1587d574-f909-4c30-9697-06bec4fe32a1">

<img width="1169" alt="image" src="https://github.com/user-attachments/assets/4cdcf69c-558b-4342-b78d-4557be949be3">

**Comment by mr-cheffy** [comment]
This should be fixed now, thanks!
