### ISSUE TITLE
Duplicate Tab shortcut

### ISSUE THREAD

**Issue by RABINGG** [zen-browser/desktop#2178]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

Add a keyboard shortcut option for duplicate tab

PS: kind of a small bug. Duplicated tab shows the workspace default container indicator

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.10 (Firefox 130.0) (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by RayZ3R0** [comment]
I mean, that's what it should do right? you duplicated a tab in a workspace that has a default container, what else should it do. Also the duplicate tab shortcut is not a bug but a suggestions. Please go to https://github.com/zen-browser/desktop/discussions

**Comment by RABINGG** [comment]
> I mean, that's what it should do right? you duplicated a tab in a workspace that has a default container, what else should it do. Also the duplicate tab shortcut is not a bug but a suggestions. Please go to https://github.com/zen-browser/desktop/discussions

@RayZ3R0 
For shortcut I will open discusussion.

You misunderstood the PS I guess. Yah, its the expected behavior to duplicate tab should be in the same as default workspace container. But I disabled indicator for default workspace container but it shows when gets duplicated that's the bug I mentioned

**Comment by RayZ3R0** [comment]
Ah, can you screen record and show it please

**Comment by salamijason** [comment]
No response in 2 weeks. For the sake of keeping the roadmap clean, I'll be closing this issue but please reopen if you still get this issue. Thank you.
