### ISSUE TITLE
highlighting is off

### ISSUE THREAD

**Issue by Turhvjbufv** [zen-browser/desktop#218]
### What happened?

![image](https://github.com/user-attachments/assets/ec35fd75-f699-49c6-9185-9607a1f780e2)

edit: only reproduced on compact mode
### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0 a-16

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by n7itro** [comment]
This is fixed since version 23
