### ISSUE TITLE
Do not work hot reload: SSL_ERROR_RX_RECORD_TOO_LONG

### ISSUE THREAD

**Issue by utopiaeh** [zen-browser/desktop#2181]
### What happened?

My issue is as follows: I developed a web app using React and Qiankun, but the hot reload doesn’t work. Updates are only applied with a hard reload. In Chrome, everything works as expected, but I found that the error mentioned in the title only appears in the network log when using Zen Browser.

PS: I cleared all data and cache, but it didn’t help.

![shoot_2024-10-17 _13 24 Zen Browser](https://github.com/user-attachments/assets/73fb72d4-25b1-4e05-850d-163884160b47)
![shoot_2024-10-17 _13 27 Zen Browser](https://github.com/user-attachments/assets/d7b408f9-232f-49b2-8ed8-da1f9418e150)
![shoot_2024-10-17 _13 28 Zen Browser](https://github.com/user-attachments/assets/c8997945-13e5-486e-94d0-a837e9a38187)
![shoot_2024-10-17 _13 29 Zen Browser](https://github.com/user-attachments/assets/95058008-39bb-4e8e-bfb3-e6f6d006673b)

### Version

1.0.1-a.10 (Firefox 130.0) 

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by mr-cheffy** [comment]
This is an issue with your SSL, not with zen. I recomend you submit a bug report to the react team or Qiankun as it's not really anything we can do, sorry

**Comment by UtopiaEH** [comment]
> This is an issue with your SSL, not with zen. I recomend you submit a bug report to the react team or Qiankun as it's not really anything we can do, sorry

I don’t know what really happened, but I decided to check again today, and it started working. I was just playing around with it. **security.tls.version.max** /  **security.tls.version.min**

**Comment by utopiaeh** [comment]
If someone has the same problem, the attached screenshot shows how I fixed it on my side.
![shoot_2024-10-22 _12 22 Zen Browser](https://github.com/user-attachments/assets/02ca5b4e-bd7c-4ac0-b917-8a6709cc9106)
