### ISSUE TITLE
Vertical tab scroll bar non functional when selected and moved

### ISSUE THREAD

**Issue by blackm0th** [zen-browser/desktop#2182]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

Reproduction Steps:

1.) Open browser 
2.) Open enough tabs until a scroll bar appears in the vertical tab
3.) Hold left click on scroll bar and move it either up or down 

Result:
The browser window minimizes and gets moved with the cursor movement

Expected result:
The tab list will move in the direction of the mouse (either up or down)

Additional notes:

-I went into about:config and thickened the size of the scroll bar to ensure that the scroll bar was being selected and got the same result.    

-Hovering cursor over scroll bar and moving mouse wheel up or down does not cause the scroll bar to move up or down

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.10

### What platform are you seeing the problem on?

Linux, Windows

### Relevant log output

N/A

**Comment by RayZ3R0** [comment]
Does this issue persist on the latest versions like a-14?

**Comment by salamijason** [comment]
Please try using this zen mod https://zen-browser.app/mods/1207efa9-fce4-439f-a673-9d3c0e4e8820

**Comment by Brasonite** [comment]
I'm running version 1.0.1-a.19 (64-bit) on Windows 11 and this is happening to me as well. The mod fixed it, though.

**Comment by salamijason** [comment]
Looks like it was an issue long enough for someone to make a mod for it lol

**Comment by maklimcz** [comment]
im still suffering from this bug,
mod mentioned earlier works properly when tab list is on right side
