### ISSUE TITLE
Reset URL on close for pinned tabs no longer works

### ISSUE THREAD

**Issue by JSGRD22** [zen-browser/desktop#2185]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When pressing Ctrl+W to close a pinned tab, resetting URL to the original no longer works for any of the 3 options in settings that are supposed to do so.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.10

### What platform are you seeing the problem on?

Linux

**Comment by kristijanribaric** [comment]
There were some changes on the underlying implementation of pinned tab reset, please unpin and repin or click "Replace pinned URL with current" and try again, let me know if it works.

**Comment by JSGRD22** [comment]
Unpinning and repinning seems to work. Thanks for the response.
