### ISSUE TITLE
Laggy subtitles when using PiP for auto-open on tab switch

### ISSUE THREAD

**Issue by JSGRD22** [zen-browser/desktop#2186]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When using the Firefox Labs option "Picture-in-Picture: auto-open on tab switch" as intended, subtitles in the PiP player have lag delays of up to many (at least 5) seconds, where the subtitles will freeze for many seconds and then suddenly all appear at once. This behaviour does not occur when activating PiP normally, and the subtitles are updated in real time.

Not sure if this is relevant, but I am using Wayland on Linux in the flatpak version and have not tested this on anything else.

This issue is reproducible on Firefox, but it would be helpful to find a fix for it because PiP on tab switch seems to be a desired feature for new users coming from Arc.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.10

### What platform are you seeing the problem on?

Linux

**Comment by RayZ3R0** [comment]
That certain PIP is a Firefox feature. Can you try this in normal firefox and see if it still happens?

**Comment by RayZ3R0** [comment]
This is a firefox issue sadly, not sure if this can be fixed in Zen but you can do a suggestion in https://github.com/zen-browser/desktop/discussions as this is not really a zen bug.
