### ISSUE TITLE
Window becomes unresponsive inconsistently when the browser is restarted and a few tabs are opened

### ISSUE THREAD

**Issue by kahveciderin** [zen-browser/desktop#2193]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I sadly do not have an exact way of reproducing this issue as it seems to happen at random. Basically, when I restart the browser and launch a couple of tabs, sometimes the entire chrome of the browser plus the webview becomes unclickable. Clicking on any user interface element results in the browser just ignoring the clicks. Even after trying to quit the browser with cmd-q, the alert message for the quit confirmation using cmd-q is unclickable so one has to force quit the application.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.10

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by RayZ3R0** [comment]
has this happened recently with the latest versions?

**Comment by salamijason** [comment]
No response in 2 weeks, will be closing this issue. Please reopen if issue persists.
