### ISSUE TITLE
Local HTML Pages Open From The /run Directory (on Linux) Instead Of The File Path

### ISSUE THREAD

**Issue by jomanhattan** [zen-browser/desktop#2204]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### Issue
Zen Browser doesn't open the file, but a copy in the /run directory.

### Description
So, when I open an HTML file from ``home/{user}/index.html``, Zen Browser opens a copy of that HTML file at  ``/run/user/1000/doc/32d1b0b5/index.html ``. 

So, if I make some modifications on the HTML file (in the home user directory) in my text editor and refresh, I can't see the changes because it's a different file. 

### Configurations 
__OS__: Nobara Linux 40 (KDE Plasma) x86_64

__Kernel__: 6.11.3-200.fsync.fc40.x86_64

__Desktop Environment__: Plasma 6.2.0

__Zen Browser version__: 1.0.1-a.10 (Firefox 130.0) (64 bits)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.10 (Firefox 130.0)

### What platform are you seeing the problem on?

Linux

**Comment by mr-cheffy** [comment]
Try enabling the home directory access in the flatseal settings. This is a flatpak issue, because of their sandboxing

**Comment by jomanhattan** [comment]
Thanks! It worked! :)
