### ISSUE TITLE
"Pin to Toolbar" is overlapping the pin icon

### ISSUE THREAD

**Issue by ZWORX52** [zen-browser/desktop#2207]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I'm seeing the "Pin to Toolbar" text that shows up in the three dots popup in the (unified?) extension menu overlap its pin icon. I expected the text to not overlap. (On Firefox, this menu is displayed using system calls, i.e. not rendered manually and without icons, as far as I can tell.)
<img width="322" alt="Screenshot 2024-10-18 at 2 48 13 PM" src="https://github.com/user-attachments/assets/a173e9b4-d621-446a-9775-eeb490f84272">
I can provide logs if requested.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.10 (64-bit)

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by mr-cheffy** [comment]
This has been also reported at https://github.com/zen-browser/desktop/issues/177
