### ISSUE TITLE
[Twilight] Issues with workspace menus

### ISSUE THREAD

**Issue by neurokitti** [zen-browser/desktop#2209]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I'm on the twilight build and there are a few issues Ive noticed on the new features that may need to be fixed before release:

1) whatever variable stores the rearrange toggle does not get reset after clicking out of the menu.

https://github.com/user-attachments/assets/38aee55a-0720-4cfe-910c-1bfec33abbb3

2) you cannot drag a workspace into the last position in the menu.

https://github.com/user-attachments/assets/60642ad0-540f-4c28-8c88-d6f5aa59e6bf

2) the spacing between rows of icons in the icon selector are supper wide. (I saw this in the Dev Chanel on the discord server so it may already be a known issue.) also I note that there is no back option so the user would have to select the same icon as is already selected in order to exit which could be problematic if a full list of emojis is added.

![image](https://github.com/user-attachments/assets/ba147b5f-7af0-4b54-9348-f7593913f62b)

I have updated to the most recent version of twilight and checked that all of these still exist with custom CSS disabled but not with mods.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-t10

### What platform are you seeing the problem on?

Windows

**Comment by ilahazs** [comment]
the music startled me :scream:

**Comment by neurokitti** [comment]
lol
