### ISSUE TITLE
This is fine, I didn't need to see what my workspaces were anyway.

### ISSUE THREAD

**Issue by Rhennius** [zen-browser/desktop#2211]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![image](https://github.com/user-attachments/assets/7328f240-96f4-45f2-a16a-4da2f2ebe011)

The toolbar resize made workspaces even more difficult to manage. It was already not great that once a workspace is created you can't change its icon. Wasn't great that you could only choose from like four icons for workspaces, and if you don't choose an icon you just get a letter. Now I can't even see the letter unless it's the active workspace.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.10

### What platform are you seeing the problem on?

Windows

**Comment by Tanza3D** [comment]
has to be a bug right? it's insane that anyone would think making them unintelligible dots is a good idea

**Comment by ristomatti** [comment]
It's configurable though. The setting was "Hide unused workspaces" IIRC.

**Comment by JSGRD22** [comment]
> has to be a bug right? it's insane that anyone would think making them unintelligible dots is a good idea

It's a nice minimalistic design if you have less than 5 workspaces. The options is there to disable this feature in settings.

**Comment by mr-cheffy** [comment]
This can be disabled in the settings and it should be disabled by default. ![Image](https://github.com/user-attachments/assets/64a0c192-5693-4af9-b79f-33c57910a27e)
