### ISSUE TITLE
reordering tabs breaking tab sidebar

### ISSUE THREAD

**Issue by njko39** [zen-browser/desktop#2212]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

1. open few tabs
2. move tab

after that, multiple bugs start to appear. At first, right click menu on that tab open toolbar right click menu instead, X button to close tab does nothing. If continue to move tabs and use feature "close multiple tabs", some tabs disappearing, leaving empty space, it might be not possible to switch to some tab, it keeps scrolling tiny piece of tab bar instead of using full height, toolbar stops collapsing when moving cursor out of it and etc

![photo_2024-10-19_05-54-02](https://github.com/user-attachments/assets/90c04763-e4af-4ab6-96cc-046c12f0cc16)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.10 (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by Aditya137x** [comment]
Even I am facing similar issue on MacOS

**Comment by mr-cheffy** [comment]
This should be fixed in the next release (.12), thanks!
