### ISSUE TITLE
github artifacts cannot be downloaded

### ISSUE THREAD

**Issue by pixincreate** [zen-browser/desktop#2214]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

<img width="441" alt="image" src="https://github.com/user-attachments/assets/2063a1df-5fe3-4aff-aed1-ff990af7966d">

as you can see in the images, it stays the same forever.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.10 (64 bit)

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by nocanoa** [comment]
is this not a gh issue?

**Comment by pixincreate** [comment]
no, i cannot reproduce this in any of the browsers except zen. tested with brave and firefox, they all worked fine.

**Comment by nocanoa** [comment]
> no, i cannot reproduce this in any of the browsers except zen. tested with brave and firefox, they all worked fine.

can u send me a presise link where it ocurs for u so i can test.

**Comment by pixincreate** [comment]
https://github.com/juspay/hyperswitch/actions/workflows/cypress-tests-runner.yml

i could not download artifacts from here (we do not have failed tests running in here at present to publish artifacts, but yeah).

https://github.com/LawnchairLauncher/lawnchair/actions/runs/11566414912/artifacts/2115563607

latest lawnchair commit that produced GitHub artifact:

<img width="451" alt="image" src="https://github.com/user-attachments/assets/4dee096b-1ece-4ebd-9b30-6105f46c5f1b">

**Comment by pixincreate** [comment]
i can reproduce this behavior in almost every artifact download on github with zen but not with any other browser

**Comment by pixincreate** [comment]
okay, its not only limited to artifacts, but anything in releases as well:

https://github.com/LawnchairLauncher/lawnchair/releases/download/nightly/Lawnchair.Debug.14-dev.Nightly-CI_1551-f07c2b2.apk

<img width="458" alt="image" src="https://github.com/user-attachments/assets/2e8fffe7-d1de-404a-9424-b9c04ea46138">

**Comment by pixincreate** [comment]
and it eventually fails:
<img width="466" alt="image" src="https://github.com/user-attachments/assets/de197e75-0b42-40de-a39a-74e3ce236d9e">

**Comment by mr-cheffy** [comment]
What version are you on currently?

**Comment by RayZ3R0** [comment]
> okay, its not only limited to artifacts, but anything in releases as well:
> 
> https://github.com/LawnchairLauncher/lawnchair/releases/download/nightly/Lawnchair.Debug.14-dev.Nightly-CI_1551-f07c2b2.apk
> <img alt="image" width="458" src="https://private-user-images.githubusercontent.com/69745008/380965207-2e8fffe7-d1de-404a-9424-b9c04ea46138.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMDE3MDIsIm5iZiI6MTczMDIwMTQwMiwicGF0aCI6Ii82OTc0NTAwOC8zODA5NjUyMDctMmU4ZmZmZTctZDFkZS00MDRhLTk0MjQtYjljMDRlYTQ2MTM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDExMzAwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0NTYzMDczYTI1NWJkOGUwZjViYmJhYTJhMmNkZWNlYzRhMjQ0MDRhMjBiODRmYjAyNjA4NzZlZDdhY2ExNDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.czorhUUJ-TiWTG-aZXvyUjuFf5ue-PmL7jDeFrIkDkM">

Can you try downloading while using a vpn, just to see if it works

**Comment by pixincreate** [comment]
> What version are you on currently?

currently on `Version 1.0.1-a.12 (64-bit)`, yet to update to the latest as I've many tabs open in incognito that I do not want to close until existing tasks are completed.

> Can you try downloading while using a vpn, just to see if it works

I'm on VPN currently, still same:

<img width="103" alt="image" src="https://github.com/user-attachments/assets/0a8224e5-3949-463d-b5e4-1bcf19ba635d">

<img width="452" alt="image" src="https://github.com/user-attachments/assets/83cbf74d-80bf-4d41-8376-b992f1366892">


edit:

it took a while, and it actually downloaded!

<img width="434" alt="image" src="https://github.com/user-attachments/assets/18f666d2-71eb-4372-b7d7-7b61ae60676b">

do you think this is a DNS issue (i'm using maxed out NextDNS BTW)?

**Comment by nocanoa** [comment]
U can check ur next-dns logs lol

**Comment by nocanoa** [comment]
Did it work with VPN on or off?

**Comment by confiq** [comment]
Works on my machine ™ 

![Image](https://github.com/user-attachments/assets/3e39cb5b-4f96-419f-b8b9-6f19c5c43c53)

**Comment by pixincreate** [comment]
it worked with vpn turned on. with regards to nextdns, i use the default configs in here,not my configured one. probably a me issue caused by the dns!?

**Comment by nocanoa** [comment]
> it worked with vpn turned on. with regards to nextdns, i use the default configs in here,not my configured one. probably a me issue caused by the dns!?

Dont realy know if dns can even make a bug like that

but the legend "it was DNS" never dies
xD

**Comment by RayZ3R0** [comment]
> it worked with vpn turned on. with regards to nextdns, i use the default configs in here,not my configured one. probably a me issue caused by the dns!?

Yeah that's what I was thinking, could have been a network issue that blocked the download link. There have been some instances where raw.githubusercontent.com have been blocked. 

Should I close this issue if its fixed?

**Comment by pixincreate** [comment]
unless i connect to a vpn, i cannot download anything. yeah, can be closed i guess.

thanks for the support!
