### ISSUE TITLE
New browser profiles don't have rounded corners like the default profile.

### ISSUE THREAD

**Issue by marko19914** [zen-browser/desktop#2216]
This issue still persists for me. This profile's theming have essentially changed with the updates.
![image](https://github.com/user-attachments/assets/316ead4f-62e3-479f-a77f-f1617c073baa)
The auto theme is normal in Default Profile. Upper edge looks normal in light theme under non-primary profile.

_Originally posted by @marko19914 in https://github.com/zen-browser/desktop/issues/353#issuecomment-2354576013_

**Comment by mr-cheffy** [comment]
Make sure you have `widget.gtk.rounded-bottom-corners.enabled` enabled in about:config. Thanks!

**Comment by marko19914** [comment]
Thank you. Wouldn't have known otherwise!!
