### ISSUE TITLE
Auto hide for sidebar breaks when opening link from History panel in new tab

### ISSUE THREAD

**Issue by MannixMD** [zen-browser/desktop#2218]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When you open a History Panel and open any link in a new tab the auto hiding for sidebar stops working (it's stuck in the open state). Right click anywhere in the sidebar fixes the issue.

Steps to reproduce.
1. Open History Panel
2. Right click any link and select Open in a new tab

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.11

### What platform are you seeing the problem on?

Windows

**Comment by salamijason** [comment]
Hey, are you still getting the issue on the latest version of the browser? (1.0.1-a.14 as of oct 29) If so, could you send a screen recording of what you mean?

**Comment by MannixMD** [comment]
https://github.com/user-attachments/assets/5bd40a8e-1422-454f-bb27-96ece2a904b1

**Comment by salamijason** [comment]
Was able to reproduce on my end too. Looks like a bug! Thanks for pointing it out!
