### ISSUE TITLE
Bookmark bar resize

### ISSUE THREAD

**Issue by NOCanoa** [zen-browser/desktop#222]
### What feature would you like to see?

Currently when i have the book mark open, the side bar jumps down see pics (i have bookmark only visible in new tabs)
![image](https://github.com/user-attachments/assets/11cf2eee-e3bb-4dca-b1d8-710828002c4f)

https://github.com/user-attachments/assets/521fa7e9-b183-4127-b049-b97609de881c

so wold it be possible to move the bookmark bar to the right letting the side bar be at 100% always ?
![image](https://github.com/user-attachments/assets/e631f684-b3f2-49ea-8b6d-98f1f8b9d94e)

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
This is a setting on firefox, you must have it in "open just in newtabs". Right click on the bookmarks bar and set it to "always"
