### ISSUE TITLE
Resetting URL not working for pinned tabs

### ISSUE THREAD

**Issue by liamcamps** [zen-browser/desktop#2225]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When using the shortcut to close a pinned tab, the URL doesn't reset even though this setting is selected in tab management settings.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.11 (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by stripedgoat** [comment]
Try to unpin your tab, and pin it again. Then try navigating away in it and resetting the URL. It should work.

**Comment by mr-cheffy** [comment]
Yeah, that's the fix, sorry. We've recently changed the way pinned tabs work
