### ISSUE TITLE
Last seesion no longer being auto-restored

### ISSUE THREAD

**Issue by pradeda** [zen-browser/desktop#2226]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

After the last few updates Zen is no longer restoring last session once I re-open it after restarting the computer. If I close and open it without restarting it keeps the tabs.
Pin tabs are being kept in both cases as per settings.

If I do it manually it is restored correctly, for example, through the History tab.

But it used to do it automatically.

I only put the cache to be deleted upon closing the browser, everything else stays.

This worked up until 3 updates ago; not reproducible on Firefox / Mercury fork.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.11 (Firefox 131.0.3) (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by mr-cheffy** [comment]
![image](https://github.com/user-attachments/assets/55b46cbf-f079-4500-bb21-461ca517b254)

Do you have this enabled?

**Comment by potatovitch** [comment]
I changed profile and it worked again

**Comment by potatovitch** [comment]
maybe it's a problem with the default one

**Comment by pradeda** [comment]
> ![image](https://private-user-images.githubusercontent.com/91018726/378124215-55b46cbf-f079-4500-bb21-461ca517b254.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0MzY1NDYsIm5iZiI6MTcyOTQzNjI0NiwicGF0aCI6Ii85MTAxODcyNi8zNzgxMjQyMTUtNTViNDZjYmYtZjA3OS00NTAwLWJiMjEtNDYxY2E1MTdiMjU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIwVDE0NTcyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwY2QzYTU0ZGRkOGUzNjg0NDQ3YzZlMTI2OWRiOThlZGUwZGNjMjgwY2Y0ZTY3MzFjZTUxMjZmYmE4ZGIwNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qrBXToXH82ufQZp9HDv2AF-A-p9OwdDiSIrIoTBE4bs)
> 
> Do you have this enabled?

I had, turned it off and on again and now it seems to be working. Odd. As far as I'm concerned this can be closed then, un-checking and checking it seems to have fixed it.
