### ISSUE TITLE
Scrolling inside a bookmark folder on touchscreen cause unintentional drag action

### ISSUE THREAD

**Issue by Mitia99** [zen-browser/desktop#2227]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.

### What happened?

Scrolling inside a bookmark folder on touchscreen cause unintentional drag action

**Steps to reproduce** : scroll here with touchscreen
![Screenshot 2024-10-19 181226](https://github.com/user-attachments/assets/dafeee6c-a773-4f32-95b7-54d6e97dc38b)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.11 (Firefox 131.0.3) (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by RayZ3R0** [comment]
Hello, does this still happen in the latest version (a.14)?

**Comment by Mitia99** [comment]
> Hello, does this still happen in the latest version (a.14)?

Hi,

No fix was addressed in commits so probably yes.

**Comment by RayZ3R0** [comment]
Alright then, I'll be closing the issue. Reopen if it isn't fixed.
