### ISSUE TITLE
Top bar covers tab list in compact mode

### ISSUE THREAD

**Issue by Vincenzo160** [zen-browser/desktop#2229]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The Top bar covers the first tab in the side bar when in compact mode in the "Hide both" setting when a new tab is open.

**How to reproduce** : 
- Enable compact mode (Hide both) in settings and make sure to check "Briefly make the toolbar popup when switching or opening new tabs in compact mode"
- Select a "New Tab"
![output](https://github.com/user-attachments/assets/146c7a7c-9ab5-4a39-b5c2-86e2702cbc47)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.11 (Firefox 131.0.3)

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by mr-cheffy** [comment]
This is done by design, because the other way would cover the toolbar buttons. Sorry about that. It only happens on the new tab page because it auto-focuses on the URL bar
