### ISSUE TITLE
Previously closed tabs are still reopening after browser restart in a.16

### ISSUE THREAD

**Issue by jimfr** [zen-browser/desktop#223]
### What happened?

2-3 tabs that have been previously closed reopen when a.16 restarts.  You can also find them listed in the "List all tabs" section.  Sometimes, the "x" closes the erroneously reopened tabs, sometimes it doesn't.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

a.16

### Severity impact

Low

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by mauro-balades** [comment]
This is fixed in version 17 (currently building and being released)

**Comment by jimfr** [comment]
Thank you!

**Comment by jimfr** [comment]
Thanks.  On my system, though, in .a17, 3 New Tabs are opened everytime I
restart Zen.
[image: image.png]

**Comment by mauro-balades** [comment]
Sorry but I can't see the image

**Comment by jimfr** [comment]
Sorry, how's this?

[image: image.png]

**Comment by mauro-balades** [comment]
No, I just can't see the image if it's from a mail response

**Comment by jimfr** [comment]
How's this?
<img width="484" alt="image" src="https://github.com/user-attachments/assets/cbbe2c3d-ea53-498a-b4e2-f08a77eefa95">

**Comment by jimfr** [comment]
More info - it's not 3 NewTabs, a.17 appears to reopen the last three tabs that were closed before restarting.

**Comment by mauro-balades** [comment]
always these last 3 tabs? Could you prove it in a new profile?

**Comment by jimfr** [comment]
confirmed in a new profile.  Last 3 tabs that were closed.

Thank you!  (this is not a big deal, especially since I now never close Zen
:) )

**Comment by jimfr** [comment]
also, three old tabs show up in the List All Tabs list, even if those tabs
have been closed.

**Comment by mauro-balades** [comment]
Fixed for version 18 hopefully (currently building)

**Comment by jimfr** [comment]
FIXED!!!  Thank you very much!
