### ISSUE TITLE
[bug] screen flashes white on new tabs and before page loads

### ISSUE THREAD

**Issue by junguler** [zen-browser/desktop#2230]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

this just started happening today after i've updated zen, every time i start a new tab, go to settings or before a page loads the browser flashes a blinding white color

i've already changed everything i could to avoid this btw, here the steps:

- have set dark color shceme via the manage color option in settings
- in about:config have set layout.css.prefers-color-scheme.content-override to 0
- in about:config toolkit.legacyUserProfileCustomizations.stylesheets to true
- already have an extensive userContent.css that has changed everything i could do to dark mode

https://github.com/user-attachments/assets/305e8018-4f5e-4f2d-89e7-7e474a3dd589

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.11

### What platform are you seeing the problem on?

Windows

**Comment by mr-cheffy** [comment]
Sorry, it was a mistake from my side. I've fixed this, update should be available soon. Thanks!

**Comment by junguler** [comment]
thanks for the quick reply, i appreciate your work, have a great rest of your day/night

**Comment by realSilasYang** [comment]
Thank you for your timely, accurate, and detailed response to the issue! These are exactly what I wanted to propose.
