### ISSUE TITLE
F1 TV doesn't work

### ISSUE THREAD

**Issue by Luquatic** [zen-browser/desktop#2232]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Cannot watch F1 TV because I always receive the following error: "Sorry, we have encountered an error.

Please try again later (BM1200)"

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.11

### What platform are you seeing the problem on?

macOS - Intel, Windows

### Relevant log output

```shell
New Relic: A problem occurred when starting up session manager. This page will not start or extend any session.

ChunkLoadError: Loading chunk 860 failed.
(error: https://js-agent.newrelic.com/860.95a91211-1.237.1.min.js)
```

**Comment by mr-cheffy** [comment]
Likely due to [https://docs.zen-browser.app/faq#why-cant-zen-browser-play-drm-protected-content](https://docs.zen-browser.app/faq#why-cant-zen-browser-play-drm-protected-content), I contacted google to see what we can do, sorry
