### ISSUE TITLE
You can unload a tab in split.

### ISSUE THREAD

**Issue by neurokitti** [zen-browser/desktop#2236]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

when in split view you can unload tabs which leavs the ui blank.

![Screenshot 2024-10-19 201830](https://github.com/user-attachments/assets/c6b638e3-97e9-4bd9-845d-e36cc437b49b)

Im not sure what the best way to handle this is. eather just expanding the other tab to take up the space or leaving a border around where the unloaded tab should be.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-t10

### What platform are you seeing the problem on?

Windows

**Comment by RayZ3R0** [comment]
@neurokitti do you still have this issue in a-14
