### ISSUE TITLE
Setting a workspace to the same Icon as itself will result in no icon

### ISSUE THREAD

**Issue by neurokitti** [zen-browser/desktop#2237]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

https://github.com/user-attachments/assets/656ed2ab-c730-4dac-ac33-1025a1e773ae

setting a workspace to the same Icon as itself will result in no icon just the letter version.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-t10

### What platform are you seeing the problem on?

Windows

**Comment by Richard-Woessner** [comment]
Recreated on my end. Looking into it now

**Comment by mr-cheffy** [comment]
@Richard-Woessner should I asign this to you?

**Comment by Richard-Woessner** [comment]
@mauro-balades ya, I can handle this

**Comment by Richard-Woessner** [comment]
I added a PR to Zen-Components 

https://github.com/zen-browser/components/pull/64

**Comment by mr-cheffy** [comment]
Merged, thanks!
