### ISSUE TITLE
The Zen browser is completely unresponsive at the moment. Zen

### ISSUE THREAD

**Issue by Eff0rtly** [zen-browser/desktop#2239]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I'm unable to load any websites on the Zen browser, even with a VPN enabled. The Zen browser is completely unresponsive at the moment. This latest update completely broke the software. I had no choice but to roll back to an older version.

I'm unable to access websites like YouTube and Reddit. The pages are stuck loading indefinitely and display a security warning.

![QQ截图20241020151434](https://github.com/user-attachments/assets/3b50b6bc-19c6-40e9-bf41-51ba9599e405)
![QQ截图20241020151445](https://github.com/user-attachments/assets/346f2ece-4091-4d86-b278-e70bd9a7dfc0)
![QQ截图20241020151449](https://github.com/user-attachments/assets/2c54e5cb-3c8f-4716-904b-005caa94d21a)
![QQ截图20241020151453](https://github.com/user-attachments/assets/04d6c36c-2e9e-4fde-8716-c589956da5ad)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a-9 — 1.0.1-a-12 

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
no log
```

**Comment by sjclayton** [comment]
Have not had this issue with any version you mentioned, on Linux or Windows, currently on a.12 on both and I'm able to access both YouTube and Reddit, as well as any other site I visit with no unresponsiveness or noticeable slowdown.

**Comment by gdmhrogla** [comment]
I had a similar problem with the last update. Zen had no longer saved my proxy settings. I then had to click on “Use system proxy settings” again once. I am running on Windows10 if that is relevant.

**Comment by RayZ3R0** [comment]
@Eff0rtly do you still have this issue in a-14?

**Comment by Eff0rtly** [comment]
> @Eff0rtly do you still have this issue in a-14?

Yes, it's still having trouble loading web pages.
Now.I've stopped using Zen and switched back to Edge and Brave.

**Comment by Eff0rtly** [comment]
> @Eff0rtly do you still have this issue in a-14?

Yes, it's still having trouble loading web pages.
Now.I've stopped using Zen and switched back to Edge and Brave.

**Comment by gdmhrogla** [comment]
> [@Eff0rtly](https://github.com/Eff0rtly) do you still have this issue in a-14?

During the last update, Zen memorized my proxy settings.

**Comment by mr-cheffy** [comment]
This seems to be a proxy setting, try disabling it to the default

**Comment by Eff0rtly** [comment]
> This seems to be a proxy setting, try disabling it to the default这似乎是一个代理设置，请尝试将其禁用为默认值

"Then I won't be able to do things like watch videos on YouTube."

**Comment by Eff0rtly** [comment]
> This seems to be a proxy setting, try disabling it to the default

"Then I won't be able to do things like watch videos on YouTube."

**Comment by Richard-Woessner** [comment]
@Eff0rtly is this an issue for you still?

**Comment by Eff0rtly** [comment]
> @Eff0rtly is this an issue for you still?这对你来说仍然是一个问题吗？

**Comment by Eff0rtly** [comment]
no problem

**Comment by tijnsemmekrot** [comment]
Hello, Sort of experiencing the same issue. When using the Zen browser i can't go to the zen-browser.app website. This is possible using other webbrowsers. Not being able to go to the website also results in not being able to update the browser, using mods.

**Comment by syvys** [comment]
![Image](https://github.com/user-attachments/assets/2dc04431-61c0-450f-b168-be396370ce74)
after i change this set ,i can connect internet.
