### ISSUE TITLE
Adaptive Theme Colour

### ISSUE THREAD

**Issue by LinuxJava7** [zen-browser/desktop#224]
### What feature would you like to see?

There's an extension called [Adaptive Tab Bar Colour](https://github.com/easonwong-de/Adaptive-Tab-Bar-Colour), It changes the Firefox theme to match the website's theme. The extension seems to be broken on Zen but it would be nice to have this feature built in.
Here's an example from the extension's page.

![image](https://github.com/user-attachments/assets/784fe63e-b82f-4d43-99eb-fe2014116af1)

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/880

 ~ This is an automatic operation to better enhancements requests organization.
