### ISSUE TITLE
Tiktok in Zen Always Repeatedly Ask For Captcha

### ISSUE THREAD

**Issue by ilahazs** [zen-browser/desktop#2241]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Tiktok in Zen Always Repeatedly Ask For Captcha - Does Zen has some additional network configuration?

I've tried the troubleshoot mode and disable all zen-themes, but the problem still occur.

This is not happening to other browser like chrome.

https://github.com/user-attachments/assets/23f2b68b-f28b-4c87-9c4b-402aafa0479f

LOG : 

![image](https://github.com/user-attachments/assets/b5f129c1-c751-4238-b314-e7e814df8cac)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a12

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
There's no log from zen browser im using log from client console
```

**Comment by ilahazs** [comment]
Does anyone have the same problem? or it is just me :/

**Comment by chriskirknielsen** [comment]
I don't use TiKTok, but I was sent a link to one the other day and could not resolve the captcha, the slider would not move and it kept failing. I tried the audio option as well, both several times, to no avail. Then I dismissed the captcha modal and the page loaded fine — no idea what's going on, but I cannot confirm whether this is a Zen-only problem, Firefox problem, or TikTok problem.

**Comment by ilahazs** [comment]
> I don't use TiKTok, but I was sent a link to one the other day and could not resolve the captcha, the slider would not move and it kept failing. I tried the audio option as well, both several times, to no avail. Then I dismissed the captcha modal and the page loaded fine — no idea what's going on, but I cannot confirm whether this is a Zen-only problem, Firefox problem, or TikTok problem.

Same, the slider wont move

**Comment by obialethan** [comment]
@ilhamprabuzakys As of now, I use audio captchas as a workaround.

**Comment by astudentinearth** [comment]
Not specific to TikTok, but I sometimes get stuck in Cloudflare checks. I'm syncing all extensions with Firefox and it proceeds just fine there. Twitter login screen also refused to load in my case, but disabling Enhanced Tracking Protection allowed me in. I might check without any extensions to see if similar issues still arise

**Comment by ProbablyM-S** [comment]
Zen is too fast for them, ig 😂
