### ISSUE TITLE
Netflix Error

### ISSUE THREAD

**Issue by YelehaUwU** [zen-browser/desktop#2242]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Netflix returns Error E100 whenever a video in it is launched using Zen.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

a11

### What platform are you seeing the problem on?

macOS - aarch64, Windows

**Comment by sjclayton** [comment]
You are seeing this error because playback of DRM content in Zen is currently not possible on macOS / Windows.

See https://docs.zen-browser.app/faq#why-cant-zen-browser-play-drm-protected-content for more details.

This issue can be closed. Thanks!
