### ISSUE TITLE
extension sidebarAction cannot be resized

### ISSUE THREAD

**Issue by fuddl** [zen-browser/desktop#2245]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

## Steps to reproduce

1. Install an extension that uses the [sidebarAction API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/sidebarAction#example_add-ons) like [Sidebery](https://addons.mozilla.org/en-US/firefox/addon/sidebery/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search)
2. hover the right edge of the extensions' sidebar with the cursor.

## Expected result

The cursor should turn into a `cursor: col-resize` style. It should be possible to drag the right edge of the sidebar to resize it. Like in Firefox.

## Actual result

The sidebar has a fixed width of 213px.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.12 

### What platform are you seeing the problem on?

macOS - Intel

**Comment by salamijason** [comment]
Please try using this Zen Mod https://zen-browser.app/mods/1207efa9-fce4-439f-a673-9d3c0e4e8820

**Comment by salamijason** [comment]
Yeah, could you please let us know if you're still getting this issue? It looks like ur trying to get Sideberry to work. Have you tried [this](https://zen-browser.app/mods/39907934-59e9-4e42-89f0-a254d3c5e280) mod?

**Comment by fuddl** [comment]
I cannot longer reproduce this issue in `1.0.2-b.2 (Firefox 133.0.3) (aarch64)`
