### ISSUE TITLE
Opening CTRL+F (Find tool) when typing only letter(s)

### ISSUE THREAD

**Issue by ardavein** [zen-browser/desktop#2246]
### Captchas

- [x] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When i just even press a letter (when not typing on a message box), it opens the find tool (normally CTRL+F). For example, watching a movie, i can't press F (fullscreen shortcut on videos) to make the video fullscreen. It just opens the find tool instead. In the picture, i only pressed a. 
![image](https://github.com/user-attachments/assets/712b5e2b-c47e-4111-89d7-8b37fced71c6)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.12

### What platform are you seeing the problem on?

Windows

**Comment by WhoSowSee** [comment]
@ardavein Most likely, you have the 'Search text on the page as you type' mode enabled in your settings. You can find this setting in Settings -> General -> Web Browsing -> Search text on the page as you type.
