### ISSUE TITLE
No choice of light_vs_dark themes post update

### ISSUE THREAD

**Issue by Scarlov** [zen-browser/desktop#2247]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

After I updated today the theme picker has disappeared except for the colour picker.

![image](https://github.com/user-attachments/assets/e97fdf47-6801-48eb-b413-5f154b5cd9d0)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.12

### What platform are you seeing the problem on?

Windows

**Comment by heyimnel** [comment]
It's in the general settings now.
