### ISSUE TITLE
Closing pinned tab creates new tab unnecessarily when there is a single unpinned tab

### ISSUE THREAD

**Issue by SIVAH-AKASH** [zen-browser/desktop#2249]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Closing a pinned tab when there is a single unpinned tab opens a new tab automatically. However this doesn't occur if there are more than one unpinned tabs.

This seems unintended as I would expect a new tab to be created only if there's one pinned tab and no unpinned tabs.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.12

### What platform are you seeing the problem on?

Windows

**Comment by kristijanribaric** [comment]
I am able to reproduce this bug in `1.0.1-a.12` but it seems it is not present in the current Twilight build. Can you check in Twilight and conifrm?

**Comment by SIVAH-AKASH** [comment]
Thanks! I just checked the latest Alpha build (1.0.1-a.14) and can confirm it's resolved on my side as well.

**Comment by SIVAH-AKASH** [comment]
Thanks! I just checked the latest Alpha build (1.0.1-a.14) and can confirm it's resolved on my side as well.
