### ISSUE TITLE
Dimming inactive tabs is nice, but it should be an option?

### ISSUE THREAD

**Issue by jimfr** [zen-browser/desktop#225]
### What feature would you like to see?

An option to turn off dimming inactive tabs (I couldn't find one in about:config).  If turned off, it would be nice if there was an indicator of inactivity in the tab's tooltip.

### What platform are you seeing the problem on?

macOS

**Comment by mauro-balades** [comment]
100%, I didn't think that it could annoy people, im sorry. Ill add it for next release (18). Thanks!

**Comment by jimfr** [comment]
Thank you.  BTW, you are awesome.  It's so great to find a developer who
actually listens to users.  BTW, I'm ex-Apple system software in the 1980s,
just so you know my background.

**Comment by mauro-balades** [comment]
Thanks you for this feedback you are giving!!!

**Comment by mauro-balades** [comment]
You can now disable in version 18 (currently building), by going into the `about:config` and changing `zen.tabs.dim-pending` to `false`. Thanks!

**Comment by jimfr** [comment]
Thank you; works perfectly.
