### ISSUE TITLE
Logins STILL do not work when using special characters

### ISSUE THREAD

**Issue by factor3** [zen-browser/desktop#2250]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

If I log into a website whose password contains special characters, the login fails

**Steps to reproduce the behavior:**

1. Select a website that requires a login. Make sure the password has characters like '_' or '@' in it
2. Enter your username and password
3. Go to Firefox, go to the same URL and enter the username and password

**Expected behavior**
You should be logged in to the site (in Zen) as well as in the Firefox browser

**Actual Behavior**
In Zen: You get a login failure -- even if you put in the correct password
In Firefox: You get logged in

Note to mauro-balades:

I did clear the data and disabled tracking protection. The problem persists.

As for the website that's "failing": the website is Comcast! And please note that, as I stated, the Firefox browser was able to log me in without problems, while the Zen browser kept failing the login. In fact, I deliberately used Firefox to log in because of Zen's Firefox- based nature. The fact is, when I log into my Comcast account with Firefox I can log in. When I attempt to log into the same site with the same account with Zzen, I cannot.

This indicates (at least to me) that it is Zen, not the website, that has the problem.

Please do not close this issue until you can run the test that I did, and show that Zen actually logs into a site that is using special characters in the password. In particular, show that a password with the characters "_" and "@" can be logged into by Zen.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.8 (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by mr-cheffy** [comment]
Does it work with other sites that dont require special symbols? What if you change your password, does it still not work?

**Comment by factor3** [comment]
Actually:

   It appears to *not* work consistently with other sites that have special characters in my passwords. 

If I change the password to one without special characters, I can log in without problems.

**Comment by cheeeebs** [comment]
Can you send the link to the Comcast site? I want to try and reproduce this issue

**Comment by factor3** [comment]
To the login page:
https://login.xfinity.com/login

**Comment by mr-cheffy** [comment]
Maybe a shortcut is overriding a special character

**Comment by RayZ3R0** [comment]
@factor3 does this issue still happen in the latest version

**Comment by factor3** [comment]
Yes, it does.

I am using Version 1.0.1-a.14. I _believe_ that is the latest version.

I believe that Zen auto- upgrades. Is this correct? If not, and if this isn't the latest upgrade, then how do I upgrade it?

**Comment by RayZ3R0** [comment]
Yeah that is the latest version. Can you try testing this by making a new profile and see if it still happens?

**Comment by salamijason** [comment]
No response in 2 weeks. For the sake of keeping the roadmap clean, I'll be closing this issue but please reopen if you still get this issue. Thank you.

Also try testing it on a19 (latest as of this comment.)
