### ISSUE TITLE
Downloaded files does not save to the Downloads Folder

### ISSUE THREAD

**Issue by DevSnyco** [zen-browser/desktop#2253]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Downloading a file does not save the file at `~/Downloads`, but instead `/private/var/folders/gq/gk60pbf156z_gxwcrlw0sm8r0000gn/T` folder. How can I fix this?

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.12

### What platform are you seeing the problem on?

macOS - Intel

**Comment by mr-cheffy** [comment]
In the preferences page, go to the downloads section select the correct folder

**Comment by DevSnyco** [comment]
> In the preferences page, go to the downloads section select the correct folder

It is already set to `~/Downloads`.
<img width="715" alt="SCR-20241021-nmdd" src="https://github.com/user-attachments/assets/7b6f22ac-1c2f-4c26-9436-642dfe100985">

**Comment by Richard-Woessner** [comment]
I'm also on Mac, I'll look into this later

**Comment by Richard-Woessner** [comment]
I cant reproduce this. Can you send a video?

**Comment by YaYaTurre** [comment]
I am having the same issue on 1.0.1-a.12 (Firefox 131.0.3) (aarch64). This video shows the issue: https://sendgb.com/COV3b9WtmY1

**Comment by DevSnyco** [comment]
That is the same thing I am experiencing, thank you for the video @YaYaTurre

**Comment by DevSnyco** [comment]
> I cant reproduce this. Can you send a video?

At rare instances, it does save the file to `~/Downloads` if you manually right click something and select "Save as...", it saves it to `/private/var/folders/gq/gk60pbf156z_gxwcrlw0sm8r0000gn/T`

**Comment by Richard-Woessner** [comment]
Just from that I would assume it can't send over files from the temp folder. Probably something dealing with permissions this shouldn't be an issue on Mac though

**Comment by FlamenWolf** [comment]
Having the same issue. I'm on Linux Pop!OS using Zen version 1.0.1-a.12 (Firefox 131.0.3) (64-bit) and downloaded it from the Pop Shop. It keeps trying to save to run/user/1000 by default no matter where I change the default download. It has no problem downloading the file to the folder I manually select each time though.

**Comment by YaYaTurre** [comment]
Glad to see this is moving forward in the process. I really hope it is fixed soon. It is a major inconvenience for me. 

Let me know if you need more examples/videos/info.

**Comment by YaYaTurre** [comment]
And, as someone mentioned in the Zeneral chat, today, this only seems to happen with PDFs. I am not 100% sure, as this is mainly what I download, but I have succeeded with one or two other (non-PDF) downloads that went to the Downloads folder, as expected.

**Comment by salamijason** [comment]
Hello! This is for everyone in this thread! 

Have you all tried
- new profiles 
- reinstallations 
- updating to the latest version

Know it might be tedious but we needa verify this! One of us tried it on PopOs and couldn't recreate the issue

**Comment by YaYaTurre** [comment]
I have not done the above suggestions, yet, but I have learned something new about this problem. 

In my case (Mac), whether or not the file ends up in the Download folder depends on the setting I have selected for PDFs under Application. I normally have it set at, "Use macOS default application" (PDF Expert), and this results in the file going to the random folder.

However, if I switch that setting to "Save File", then it does successfully end up in the Download folder.

**Comment by salamijason** [comment]
@DevSnyco are you still getting this issue in the latest ver?

**Comment by DevSnyco** [comment]
> @DevSnyco are you still getting this issue in the latest ver?

i do not have a way to reproduce the issue, instead of auto-downloading, it opens the pdf in a new tab, upon clicking download it shows the download prompt, basically simulating the right-click and "Save As", so im not entirely sure if this issue is fixed.

but it doesnt bother me as much to keep this issue open. if no-one else experiencing it, im happy to close it

**Comment by DevSnyco** [comment]
@YaYaTurre are you still experiencing this issue?

**Comment by salamijason** [comment]
>  instead of auto-downloading, it opens the pdf in a new tab, upon clicking download it shows the download prompt

same. when i click on a pdf, it opens the pdf in the browser and also immediately downloads it into a temp folder. then if I actually wanna download, I just click the download button. i think it goes into the temp folder because its only supposed to exist on your computer for a bit and itll be gone after you close it.

unless someone else replies that theyve experience behavior completely different, i'll close this issue. thanks for pointing it out though? just yesterday i encountered it during normal use.

**Comment by YaYaTurre** [comment]
> @YaYaTurre are you still experiencing this issue?

I am still experiencing this issue in the way I described in my previous post i.e. it depends on what setting is chosen for handling PDFs in the Application sub menu of Zen settings. If it is set to open the PDF immediately upon downloading with the default application ("Use macOS default application"), then the issue occurs. The file is stored in a random folder and not Downloads.

This is not what happens in Firefox. There, I also have it set to "Use macOS default application", but the file is stored in the Downloads folder. I can send videos if needed.

**Comment by DevSnyco** [comment]
> This is not what happens in Firefox. There, I also have it set to "Use macOS default application", but the file is stored in the Downloads folder. I can send videos if needed.

I think it would be better if you send a video demonstrating the issue in Zen and intended response from Firefox.

**Comment by YaYaTurre** [comment]
Ok..here you go: https://sendgb.com/4n7F2sHpfu1

Thanks for looking into this.

**Comment by DevSnyco** [comment]
@salamijason 
> @DevSnyco are you still getting this issue in the latest ver?

yea, i just experienced it just now while downloading @YaYaTurre's video:
![SCR-20241103-svim](https://github.com/user-attachments/assets/fcb89552-2b9c-45f9-89e9-8cdffe450f91)

**Comment by DevSnyco** [comment]
This issue seems to have been resolved and I have verified it's fix at the current version of Twilight (`1.0.2-t.2`).
