### ISSUE TITLE
Restoring last closed tab doesn't work properly

### ISSUE THREAD

**Issue by JSGRD22** [zen-browser/desktop#2256]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Close a tab, then press the keyboard shortcut to reopen the tab. A random tab closed earlier is opened instead of the most recently closed tab.

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.12

### What platform are you seeing the problem on?

Linux

**Comment by sjclayton** [comment]
Works fine here, also on Linux running 1.0.1-a.12

**Comment by JSGRD22** [comment]
It’s also no longer broken for me now for some reason. Possibly a one-off from upgrading the browser in between sessions, I will close this for now
