### ISSUE TITLE
Some websites does not have a background

### ISSUE THREAD

**Issue by exigosss** [zen-browser/desktop#2257]
### Captchas

- [x] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.

### What happened?

Looks like some websites does not have a background resulting in totally not readable site.
Here is the example site that has the issue (I also attach the screenshot): [https://www.komputronik.pl/](url)
![image](https://github.com/user-attachments/assets/c72e08e5-d9ca-4e66-abc8-95548b50157c)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.12

### What platform are you seeing the problem on?

Windows

**Comment by Saksey1** [comment]
Hey!

Could this be one of your extensions?

This site looks fine on my end.
![Screenshot 2024-10-21 at 21-42-21 Sklep komputerowy - Komputronik Mamy to!](https://github.com/user-attachments/assets/fa46c2e8-f348-4ba7-86aa-a4456e4ac58f)

**Comment by exigosss** [comment]
Do you use light theme? It looks like the website reacts to the theme currently applied. Changing theme to light indeed makes the website look like it should but switching back to dark theme ends up with the issue I posted.
![image](https://github.com/user-attachments/assets/3668d9ac-52c5-4a5d-b560-ef78d9b60002)
![image](https://github.com/user-attachments/assets/a38c0fa1-6c19-4592-9192-5c9b5d198533)

**Comment by Saksey1** [comment]
Hey yeah I have dark mode on and its fine.
![{659A8DAA-CBB3-456C-839F-E2287F108317}](https://github.com/user-attachments/assets/e36f350c-a61c-4520-8ce4-f2f42cb64bc7)

have you tried reinstalling?

**Comment by exigosss** [comment]
Hmm, strangely enough, I set up entire new profile (about:profiles), set up every setting the same, installed the same extensions and Zen Mods and now it's working. Thank you for pointing it's working for you as I thought that it's a bug and just lived with that.

**Comment by tessamerrill** [comment]
I'm still facing this issue on 1.0.1-a.12 on Arch Linux. I've created a new profile, with the same Zen Mods and signed in (added extensions) however some websites still do not have a background. I've been testing on [DoorDash's website](https://doordash.com).

**Comment by nikolai-in** [comment]
![{762FFAB4-F028-48C4-8F0F-3464A0AB7B95}](https://github.com/user-attachments/assets/2f4bc6a7-d438-464d-b042-386346b57f3d)
Same here

**Comment by utopiaeh** [comment]
1.Go to: about:config
2.Switch: browser.tabs.allow_transparent_browser -> false
3.Restart browser
