### ISSUE TITLE
installation of unsigned extensions failed

### ISSUE THREAD

**Issue by prehonor** [zen-browser/desktop#2258]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

anyone of https://github.com/mdn/webextensions-examples can't be installed

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.12 (Firefox 131.0.3) (64 位)

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
nothing
```

**Comment by mauro-balades** [comment]
[Screencast from 2024-10-30 08-43-45.webm](https://github.com/user-attachments/assets/ec0566cc-8905-442c-a6da-422a9a0375d4)

It does let me use it. Please make sure you are doing it the correct way and please reopen if you'd like with a video to better visualize this problem. Thanks!

**Comment by mr-cheffy** [comment]
Heya! This will be fixed for the next version (16), thanks a lot!

**Comment by tsuliwaensis** [comment]
> Heya! This will be fixed for the next version (16), thanks a lot!

When will a16 release?

**Comment by yorunoken** [comment]
a16 has been released but this issue hasn't been resolved.
```
@yoru in ~ 
💜 zen-browser --version
Mozilla Zen 1.0.1-a.16
```

**Comment by tetrus93** [comment]
apparently due to security concerns, you have to set `xpinstall.signatures.required` parameter in "about:config" page to be `false` in order to install unsigned extensions
(obv also you need to be in latest version of browser too)
