### ISSUE TITLE
Default Keyboard shortcuts appear to be Windows shortcuts on a Mac on a.17

### ISSUE THREAD

**Issue by jimfr** [zen-browser/desktop#226]
### What happened?

First, thanks so much for Keyboard shortcuts!!!!!

<img width="606" alt="image" src="https://github.com/user-attachments/assets/fc6dcb89-d580-462a-b650-85249ade699b">

ctrl+Alt looks like Windows.  Can't make the shortcuts work on MacOS without changing them all

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

a.17

### Severity impact

Low

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by mauro-balades** [comment]
`CTRL` is actually a representation for `accel` that translates to `ctrl` on windows and linux and `cmd` for macos
