### ISSUE TITLE
Pages take a long time to load

### ISSUE THREAD

**Issue by shaqaruden** [zen-browser/desktop#2260]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When visiting many different pages like monday.com, github.com, businesscentral.dynamics.com, etc it takes a long time for them to load. Status bar shows. I have attempted to disable UBlock Origin but this. has not changed anything. Visiting the same pages in a portable version of Zen Browser yields the same result, but visiting the Firefox, Chrome, Edge all work fine and load the pages quickly.

![2024-10-21_08-16](https://github.com/user-attachments/assets/bd61469e-9ce8-405e-b197-210deb01a7bf)

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.12

### What platform are you seeing the problem on?

Windows

**Comment by RayZ3R0** [comment]
@shaqaruden Does this still happen in the latest version?

**Comment by shaqaruden** [comment]
Just tried using Zen browser again this week and no everything seems to load fine now. 👍

**Comment by RayZ3R0** [comment]
Aight, thats good. Will be closing this then
