### ISSUE TITLE
option to remember the last used site on the sidebar and open that only. 

### ISSUE THREAD

**Issue by spectrum705** [zen-browser/desktop#2261]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

rn when we repopen side bar it doesnt remember the last used site and resets to welcome page. can we have it soon in future so it always opens the last used site? (and also the size / site)  ??

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.12 (Firefox 131.0.3) (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by Richard-Woessner** [comment]
Ive been trying to recreate this issue but I either cant or I dont understand. It seems to be doing that for me

https://github.com/user-attachments/assets/3cfbc6fc-bb55-40ad-a114-e344cd0fa2d3


https://github.com/user-attachments/assets/7736c2ea-9ae6-4f88-ad83-870bb50fe982

**Comment by spectrum705** [comment]
check this video

https://github.com/user-attachments/assets/514faaa9-8cb4-4d62-a6fc-e02ca687814c

**Comment by RayZ3R0** [comment]
That is how the webpanel works for now. It will be improved soon, but this is not a bug. Use https://github.com/zen-browser/desktop/discussions for suggestions please
