### ISSUE TITLE
Header tabs 

### ISSUE THREAD

**Issue by esbtc** [zen-browser/desktop#2266]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Can the header of the tabs be moved to the top of the page in the zen browser?  And when will the Android version be released?

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Last

### What platform are you seeing the problem on?

Windows

**Comment by mr-cheffy** [comment]
Heya!

You can find the answer to both questions here: https://docs.zen-browser.app/faq#how-can-i-use-horizontal-tabs

Also, please use a forum for questions, this is for bug reports. Thanks!
