### ISSUE TITLE
Split views can no longer be freely resized

### ISSUE THREAD

**Issue by sjclayton** [zen-browser/desktop#2269]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Tabs that are placed in split view can no longer be resized freely, instead now it appears you must enter rearrange mode... this feels like a bug, however if for some reason this is intended behaviour, then it is totally not intuitive and very counter productive as it now requires extra steps to perform.

**Expected Result:**

Tabs are able to be freely resized by dragging their border like before.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.12

### What platform are you seeing the problem on?

Linux

**Comment by anatasiajp** [comment]
https://github.com/zen-browser/components/commit/e04d67db05553199accc9eece5d0239ed8d614fd

This PR caused above issue, and it's a bug and will get fixed soon.

**Comment by mr-cheffy** [comment]
It can only be resized on rearange mode now. Sorry

**Comment by LeMoonStar** [comment]
> It can only be resized on rearange mode now. Sorry

There is no real reason for that tho, right?
It is less intuitive and way more complicated.

There is a space/border between the tabs. Why not just allow dragging it? It's the most intuitive it can be and has no disadvantage I can think of.

**Comment by sjclayton** [comment]
> It can only be resized on rearange mode now. Sorry

@mauro-balades 

Why??! This makes absolutely zero sense... completely un-intuitive.

Doing this is just making user experience worse by making something that should be a simple operation, unnecessarily harder.

If you have no intention of changing the behaviour back, then at least provide a keyboard shortcut to toggle re-arrange mode then....

**Comment by mauro-balades** [comment]
Ok... Let me cook

**Comment by mr-cheffy** [comment]
Ok, it is now fixed...

The reason is was like this before is because it had a slight performance impact since the overlay was always there. I now fixed this to only appear WHEN splitting instead of only in rearrange mode. Sorry... I havent really thought well about the solution I did in the bast and I should be consider other solutions
