### ISSUE TITLE
Scrolling on the very far right of the browser (where the border is) doesn't scroll the page

### ISSUE THREAD

**Issue by TheRedXD** [zen-browser/desktop#2281]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When you go on the border padding, it doesn't let you scroll the page you're on. This should be fixed such that the scrolling is handled on the border as well, as it basically makes sure you can't miss the scroll unless you're specifically hovering over the sidebar.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.12

### What platform are you seeing the problem on?

Linux, Windows

**Comment by JayTheCoderX** [comment]
when scrolling on youtube I usually move my mouse to the right side so I don't make youtube automatically play every video I hover over while scrolling but now I have to move it precisely to the scroll bar instead of just to the right of the screen - really annoying- valve plz fix

**Comment by mr-cheffy** [comment]
This issue wont be resolved since the scrolling mechanic comes from the web view and it's on top of the browser's view, meaning there's not much I do from it, because it would be out of bounds.

An alternative would be to install https://zen-browser.app/mods/680424a8-a818-406b-98c5-7726214e2a9f

sorry

**Comment by JayTheCoderX** [comment]
> This issue wont be resolved since the scrolling mechanic comes from the web view and it's on top of the browser's view, meaning there's not much I do from it, because it would be out of bounds.
> 
> An alternative would be to install https://zen-browser.app/mods/680424a8-a818-406b-98c5-7726214e2a9f
> 
> sorry

Maybe it would be possible to like... mirror mouse interactions on the border to the rightmost part of the web view somehow
Also the mod just doesn't fix anything

Edit: this does fix it https://zen-browser.app/mods/753c7518-237d-480a-abfd

**Comment by berezki** [comment]
None of the suggested mods solves the problem now. Really annoying to aim exactly at scrollbar every time.
