### ISSUE TITLE
Workspaces "add" menu grows with too many workspaces

### ISSUE THREAD

**Issue by Hate9** [zen-browser/desktop#2285]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The workspaces menu with a large number of workspaces. This part is probably fine: 
![image](https://github.com/user-attachments/assets/d6e2a4cf-b03d-486e-9d3f-f39155905b56)

The workspaces menu "Add" submenu, clearly being resized incorrectly: 
![image](https://github.com/user-attachments/assets/8ad33e85-9891-4b60-834a-49a59b10987d)

(Scrolled down:)
![image](https://github.com/user-attachments/assets/d7d6ff99-d1ab-45a8-b6b4-aaa216dfd422)

As you can see, the buttons on the "Add" menu are pushed down by the list of workspaces in the *other submenu*, causing them to be pushed off the screen and requiring the user to scroll past a large amount of *empty space* to access these buttons.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.12

### What platform are you seeing the problem on?

Linux

**Comment by mr-cheffy** [comment]
This is expected, as it is how popups work. Sorry

**Comment by katedickey** [comment]
@mauro-balades 
You're right the popup can't be made smaller due to the previous screen making it that length, but the buttons don't need to be aligned to the bottom. They definitely weren't bottom aligned when I tweaked the workspaces flow a little bit ago.
