### ISSUE TITLE
Pinned tabs aren't loaded on startup

### ISSUE THREAD

**Issue by BoscoDomingo** [zen-browser/desktop#2289]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When starting up Zen, pinned tabs aren't loaded and instead you get sent to a New Tab.

Might be related to #2163

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.12 (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by BoscoDomingo** [comment]
A screenshot of what it looks like:
![image](https://github.com/user-attachments/assets/71a9ce30-0f26-49d2-877b-8edd32fb023e)

**Comment by cheeeebs** [comment]
Do you have the Super Pins mod? Turn off the load pinned tabs only when using them. The new behavior for unloaded pinned tabs is to add a new tab instead of loading them. 
![image](https://github.com/user-attachments/assets/0a828ae5-5167-4efb-a103-e80b1a5cf5dc)

**Comment by ztjuh** [comment]
I have the same issue.

**Comment by zhongjis** [comment]
I am having the same issue on macos. I do not have any zen mods installed.
currently on `Version 1.0.1-a.12 (64-bit) `
when ever restart the program. all pinned tabs are gone
installed using homebrew

**Comment by ztjuh** [comment]
1.0.1-a.12 as well here, installed from Flatpak on Linux

**Comment by BoscoDomingo** [comment]
> Do you have the Super Pins mod? Turn off the load pinned tabs only when using them. The new behavior for unloaded pinned tabs is to add a new tab instead of loading them. ![image](https://private-user-images.githubusercontent.com/70993528/379131812-0a828ae5-5167-4efb-a103-e80b1a5cf5dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMDk3MTAsIm5iZiI6MTczMDEwOTQxMCwicGF0aCI6Ii83MDk5MzUyOC8zNzkxMzE4MTItMGE4MjhhZTUtNTE2Ny00ZWZiLWExMDMtZTgwYjFhNWNmNWRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDA5NTY1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1MWYxZjM3MmQxNGI3OWU0MThjOTEzNjY2NDFhZTcxNzE2Yzk5Njg2YTRmY2YzN2Y3ODRmMzczYTQxOWQ3NzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bMMGqWovM33xTiiQt8Tv5RKtsaMaEExKKGRQKM-L5lY)

I indeed had that option marked (thought I had unchecked it, my bad). I'll test again

Edit: Yup, fixed

**Comment by salamijason** [comment]
@ztjuh @zhongjis are you both also using Super Pins? 

> Do you have the Super Pins mod? Turn off the load pinned tabs only when using them. The new behavior for unloaded pinned tabs is to add a new tab instead of loading them. ![image](https://private-user-images.githubusercontent.com/70993528/379131812-0a828ae5-5167-4efb-a103-e80b1a5cf5dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMDI5OTYsIm5iZiI6MTczMDIwMjY5NiwicGF0aCI6Ii83MDk5MzUyOC8zNzkxMzE4MTItMGE4MjhhZTUtNTE2Ny00ZWZiLWExMDMtZTgwYjFhNWNmNWRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDExNTEzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1ODZlYTE3ZTViNzE2ODk0ZDc4ZmM0OGFjODdkYTZkMWM0MGUyNjg2ZWE5OGFkOGNjMWE3ODJhMTAxZWE1MzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZKtXjuxKeHPrU4QfKm7TF8eu9eEPQt7TD9KzgLU05y0)

**Comment by ztjuh** [comment]
I don't have super pinned mods!

I have disabled `Zen Mods` for now, and see if it makes a difference.

**Comment by salamijason** [comment]
Alright, do let me know if your issue is fixed after doing so.

**Comment by ztjuh** [comment]
When I open a new window, the pinned tabs are gone, and when you restart both windows, depending on how you restart them (if you close the one without the pinned tabs first then they are still there, but if you close the one with the pinned tabs, they are gone after a restart)

**Comment by ztjuh** [comment]
Hmmm. I tried it another time, but this time the pinned tabs are still here, it's very inconsistent.

**Comment by ztjuh** [comment]
I'm on 1.0.1-a.14 (Firefox 131.0.3) (64-bit) now by the way, maybe it got fixed already?

**Comment by ztjuh** [comment]
But shouldn't the pinned tabs be in the new window as well?

**Comment by salamijason** [comment]
> But shouldn't the pinned tabs be in the new window as well?

This is something in works, I believe. Nothing official yet, though. Up to this point, pinned tabs have not synced across windows. 

It's a session store issue. Zen uses the last window as the last "session" perse, and only loads that last session on your next startup. This is why if you close the window with no tabs last, Zen saves that window as your most recent session. As of right now, it hasn't been fixed but there's also not a fix for it. I'll leave this issue open until a fix or feature comes out.

**Comment by salamijason** [comment]
How to avoid the issue for now:

Menu -> Exit,  instead
Don't close windows one by one

If you want to retrieve the lost tabs:
Go to profile folder
Go to sesssionstore-backups
And copy it somewhere else
Then replace one of those files with sessionstore.jsonlz4

https://docs.zen-browser.app/guides/manage-profiles

**Comment by zhongjis** [comment]
> @ztjuh @zhongjis are you both also using Super Pins?
> 
> > Do you have the Super Pins mod? Turn off the load pinned tabs only when using them. The new behavior for unloaded pinned tabs is to add a new tab instead of loading them. ![image](https://private-user-images.githubusercontent.com/70993528/379131812-0a828ae5-5167-4efb-a103-e80b1a5cf5dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMDI5OTYsIm5iZiI6MTczMDIwMjY5NiwicGF0aCI6Ii83MDk5MzUyOC8zNzkxMzE4MTItMGE4MjhhZTUtNTE2Ny00ZWZiLWExMDMtZTgwYjFhNWNmNWRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDExNTEzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1ODZlYTE3ZTViNzE2ODk0ZDc4ZmM0OGFjODdkYTZkMWM0MGUyNjg2ZWE5OGFkOGNjMWE3ODJhMTAxZWE1MzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZKtXjuxKeHPrU4QfKm7TF8eu9eEPQt7TD9KzgLU05y0)

nope. the issue persists with all zen mods disabled >_>

**Comment by salamijason** [comment]
@zhongjis Yikes, sorry to hear that. In the meantime, you could try to steps to avoid the issue in the future:

> Menu -> Exit, instead
Don't close windows one by one

And if you want to retrieve the lost tabs:

> Go to profile folder
> Go to sesssionstore-backups
> And copy it somewhere else
> Then replace one of those files with sessionstore.jsonlz4

**Comment by zhongjis** [comment]
> @zhongjis Yikes, sorry to hear that. In the meantime, you could try to steps to avoid the issue in the future:
> 
> > Menu -> Exit, instead
> > Don't close windows one by one
> 
> And if you want to retrieve the lost tabs:
> 
> > Go to profile folder
> > Go to sesssionstore-backups
> > And copy it somewhere else
> > Then replace one of those files with sessionstore.jsonlz4

will try and thanks for the reply XD
I think the main issue here is that I have `Startup -> Open previious windows and tabs` checked but it does not take effect.
this only happens on my Mac. not on Windows :) Feel free to let me know if you need any more details :)

**Comment by salamijason** [comment]
> only happens on my Mac. not on Windows

Hmm I see, then there has to be some type of unwanted behavior there. Alright, thank you for pointing out the issues. Will send to big dev cheff.
