### ISSUE TITLE
Allow "Hide Top Toolbar" to be enabled separately 

### ISSUE THREAD

**Issue by dheffer** [zen-browser/desktop#229]
### What feature would you like to see?

Would love to be able to hide the top toolbar without having full compact mode enabled. I like being able to see my tabs, but want to hide the address bar.

![Screenshot from 2024-08-11 16-45-25](https://github.com/user-attachments/assets/5ec9d215-4065-49e2-a3f4-3ce3bebad7b6)

### What platform are you seeing the problem on?

Linux

**Comment by Dadangdut33** [comment]
Sorry to comment here (should i make this a separate issue?) but while you are at this, is it possible to also add option just hide the bookmark section so we can see the bookmark only when hovering it?

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/879

 ~ This is an automatic operation to better enhancements requests organization.
