### ISSUE TITLE
Video playback not working on some sites

### ISSUE THREAD

**Issue by PH-RYDER** [zen-browser/desktop#2295]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

BBC iplayer video playback does not work. Audio is fine but no picture. On a previous version this would happen on Youtube sometimes. I am using Manjaro (6.11.4-2 kernel) Linux, KDE plasma (6.2.2) (Wayland). Problem does not exist on Firefox (131.0.3) 

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.12 (Firefox 131.0.3) (64-bit)

### What platform are you seeing the problem on?

Linux

**Comment by TruSoggy** [comment]
I have the same problem on Windows.
Also Disneyplus also doesnt work.

**Comment by gnc-07** [comment]
Probably because of DRM, see https://docs.zen-browser.app/faq#why-cant-zen-browser-play-drm-protected-content. 
The dev is working on it: https://www.reddit.com/r/zen_browser/comments/1gbpn1c/another_dev_update/

**Comment by gnc-07** [comment]
> I have the same problem on Windows. Also Disneyplus also doesnt work.

Probably because of DRM, see https://docs.zen-browser.app/faq#why-cant-zen-browser-play-drm-protected-content. 
The dev is working on it: https://www.reddit.com/r/zen_browser/comments/1gbpn1c/another_dev_update/

**Comment by glyndwr-io** [comment]
I'm also experiencing this issue, but I'm hesitant to blame it on DRM just yet. YouTube, Instagram, TikTok, Reddit and Vimeo all refuse to play. I haven't had the chance to continue testing to confirm but it seems to be all videos. Firefox and Chrome both seem to work just fine. I was previously on version 1.0.1-a.6 and it was also working fine then. Currently on NixOS. Would be happy to provide any additional info or tests to help resolve this.
