### ISSUE TITLE
Huge Graphics downgrade after version 1.0.1-a9

### ISSUE THREAD

**Issue by MemQu** [zen-browser/desktop#2296]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Motion mark score is halved.

I don't have the score from 1.0.1-a9, but I remember the scores were roughly equal with firefox.

Current comparison with firefox:
FF: 1028.39
Zen: 566.26

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a12

### What platform are you seeing the problem on?

Windows

**Comment by anatasiajp** [comment]
Can you test a9 again  ?

**Comment by MemQu** [comment]
a9 - 1020.96
a10 - 1041.40
a11 - 1058.30

I had not used the browser versions a10 and a11 for graphics intensive tasks.

I am using the optimized build.

**Comment by MemQu** [comment]
Reinstalling a12 improved performance to near firefox levels, but still slower. Within margin of error for Firefox, but I can tell the difference (hitching) when I run graphics.

Update to a14 has no changes from reinstalled a12 performance wise. 

Reinstalling Zen (with winget) after the updater updates it seems to make it better, but not as smooth as a9-a11
