### ISSUE TITLE
Tabs sometimes persist across workspaces

### ISSUE THREAD

**Issue by nh2seven** [zen-browser/desktop#2299]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When a tab is opened in the default or any empty workspace, it sometimes persists/transfers to another workspace when switching to it. I first noticed this issue in release **1.0.1-a.8**. 

For example, say I open Gmail in a tab in an empty workspace, and switch to workspace X, the tab persists across both workspaces and has inconsistent behavior. 

Can be reproduced at random, most often in empty workspaces. Currently this can be worked around by simply manually reassigning a tab to a workspace. 
Screenshots attached below for better depiction:
1. My usual LeetCode workspace (tools emoji)
![Screenshot_20241024_113312](https://github.com/user-attachments/assets/2c8eaa1a-8006-422c-af27-362f9367c637)

2. My default workspace (was empty with only the Zen home page before switching to it, network emoji)
![Screenshot_20241024_113324](https://github.com/user-attachments/assets/7063419a-6859-4911-91c4-3d99b7f1b835)

Note: Issue #1949 also mentions this same bug, for an older build of Zen (1.0.1-a.7).

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.12

### What platform are you seeing the problem on?

Linux (x86-64)

**Comment by kristijanribaric** [comment]
Did you manage to consistently reproduce this bug?

**Comment by nh2seven** [comment]
The issue is not consistently reproducible, it's just at random as I depicted earlier.

**Comment by nh2seven** [comment]
I believe this issue is resolved as of build 1.0.1-a.18. Tried reproducing it exactly as mentioned earlier, restarted the browser thrice just to be sure, and it seems like it's fixed. I don't know if I can rule it out entirely, but I'm 99% sure.

Additional info: This issue still existed in build 1.0.1-a17 and earlier, but recreating it was way less consistent in comparison to build 1.0.1-a.12 (mentioned in original issue post).

Edit: The issue is in fact, not resolved. It is just significantly less often that it occurs.

**Comment by YaYaTurre** [comment]
I am still having this issue in 1.0.1-a.19 (aarch64)

**Comment by nh2seven** [comment]
> I am still having this issue in 1.0.1-a.19 (aarch64)

If you could provide some more information/specifics, I'm sure it'll be useful.
Also, try restarting the browser because sometimes there's another underlying cause for this behavior (or so I've observed).

**Comment by YaYaTurre** [comment]
The scenario is the basically the same as you described when creating the issue: I am on a Workspace (A) with a specific tab open. I switch to another workspace (B) and the active tab from A moves to Workspace B. 

I have experienced this to varying degrees since I started with Zen a couple of months ago. My solution has always been to restart the browser, which seems to help. I figured over time it would be fixed, so I didn't worry about it.

And I haven't had the issue as often in the last few weeks; however, it just happened again, which is why I searched for a Github issue on this topic.

**Comment by chrisj-devel** [comment]
This happens to me relatively often - at least once a day in my experience. In my case it seems to have some sort of relation to having more than 2 workspaces.

The behaviour that I can observe is that: 
- A tab opened in workspace A will move to workspace B when switching to workspace B
- A tab opened in workspace B _won't_ move to workspace A when switching back to workspace A, and the original tab that incorrectly moved will be restored and active
- A tab opened in workspace A _won't_ move to workspace C, and vice versa. The issue only affects the workspace in the middle
- It happens randomly, and also seems to resolve randomly - a restart fixes it but also tends to lose tabs if I restart when it's happening

**Comment by YaYaTurre** [comment]
This is occurring more frequently for me now.

**Comment by paulsamoluk** [comment]
Same problem here, both Windows 11 and Linux. I pretty much always have to have a blank tab open just to prevent a "personal" tab bleeding over to my "Work" space. Not a huge deal, but sort of odd behavior.

**Comment by namquang93** [comment]
The case that happens to me feels like a feature. Whenever I have a Google Meet tab opened, the tabs always move when switching profile/workspace.

**Comment by mr-cheffy** [comment]
Does this still happen?

**Comment by YaYaTurre** [comment]
It seems to have been fixed! I have not had this problem since the first beta release. Thanks!

**Comment by thebiblelover7** [comment]
I still have it happen to me... Every once in a while, my tabs (not pinned) transfer from one workspace to another and it's very unpredictable.
