### ISSUE TITLE
Closed ballots return

### ISSUE THREAD

**Issue by Ryoma123456789** [zen-browser/desktop#230]
### What happened?

I set the browser to show me the tabs I left open, but when I reopen Zen this also brings up tabs I had previously closed.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.17 

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
This is fixed in version 18, that's currently building https://github.com/zen-browser/desktop/actions/runs/10348386661
