### ISSUE TITLE
white background change the color font

### ISSUE THREAD

**Issue by HypatiaG** [zen-browser/desktop#2300]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

when opening white background website the color font of the browser change to black make it invisible

https://github.com/user-attachments/assets/e3406180-bd17-4cc9-84d3-7d59501e6539

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.12

### What platform are you seeing the problem on?

Windows

**Comment by mr-cheffy** [comment]
What theme do you have installed? (dark, light or auto)

**Comment by HypatiaG** [comment]
sorry for late reply, its dark
