### ISSUE TITLE
Wondering for built-in "Tree style tab" or Chromium "group tabs"

### ISSUE THREAD

**Issue by khoadang06** [zen-browser/desktop#231]
### What feature would you like to see?

I'm just tried the zen browser and loved that built-in vertical tab, but if there are something like  built-in Tree style tab or group tabs, it would be perfect:)

### What platform are you seeing the problem on?

Windows

**Comment by guigirl42** [comment]
Ideally, full `Sidebery` integration, please.  :pleading_face:

**Comment by Ashad001** [comment]
yes plisss, other than that its awesome!!!!!

**Comment by AColtZz** [comment]
I'd love this as well 👍 and my friend who introduced me to Zen Browser!!!

**Comment by SegoCode** [comment]
Definitely almost all users of vertical tabs are looking for tree style tabs

**Comment by frandmb** [comment]
Something similar to Sidebery tab nesting should play very well with the split view

**Comment by lucascarrm** [comment]
Tab nesting please :)))

**Comment by GitMurf** [comment]
🚀 for tab nesting! That feature alone would have me switch to Zen in a heartbeat!

Similar request/discussiom here #378

**Comment by guigirl42** [comment]
Just as a fyi for all we fans / hopers for putative Zen native nested tabs & groups... the Dev said this, less than a fortnight ago:

https://l.opnxng.com/r/zen_browser/comments/1eqqzlt/the_one_feature_that_will_win_me_over/

>[u/maubg](https://l.opnxng.com/user/maubg) [10d ago](https://l.opnxng.com/r/zen_browser/comments/1eqqzlt/the_one_feature_that_will_win_me_over/lhtlywh/?context=3)

>Yes, tab groups/folders and trees are on the way!

>[u/maubg](https://l.opnxng.com/user/maubg) [10d ago](https://l.opnxng.com/r/zen_browser/comments/1eqqzlt/the_one_feature_that_will_win_me_over/lhv19c4/?context=3)

>Natively

So, i am excited!

**Comment by GitMurf** [comment]
> >Yes, tab groups/folders and trees are on the way!

@guigirl42 This has me excited! Thanks for sharing! I have been so shocked that virtually none of the million new browsers the last few years have implemented nested / tree structure tabs!

**Comment by guigirl42** [comment]
IKR! Once anyone has experienced the enormous tab management _sophistication_ of [for me] initially `Tree Style Tab`, then later the magnificent `Sidebery`, there's simply no going back! The idea of having this natively within Zen is just almost too delicious, haha.

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/878

 ~ This is an automatic operation to better enhancements requests organization.

**Comment by guigirl42** [comment]
https://github.com/zen-browser/desktop/discussions/891#discussioncomment-11288211
