### ISSUE TITLE
Web sidebar uses non-transparent favicon

### ISSUE THREAD

**Issue by Tc-001** [zen-browser/desktop#232]
### What happened?

The web sidebar seems to use a different favicon than regular tabs or bookmarks (probably the default favicon.ico). This means that it has a white border on most sites, that doesn't look as nice or legible especially in the dark theme or on high resolution displays.

Sidebar:
![image](https://github.com/user-attachments/assets/a0139d9b-2247-4e9d-8ae6-9839c7062359)

Tabs: 
![image](https://github.com/user-attachments/assets/b50f3572-5095-4169-8524-fb6ed85e7e7d)

Bookmarks:
![image](https://github.com/user-attachments/assets/e8f7337d-00ef-483f-8f56-1eb4ed6ce28c)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.17

### Severity impact

Enhancement

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
We are using Google's API for favicon and that's how they return the image. If you have s better alternative, please do tell me

**Comment by Tc-001** [comment]
There should be a built-in cache or tool to return them, like what is done for bookmarks.

If that fails, duckduckgo has a favicon API as well, and it seems to handle transparency correctly:
https://icons.duckduckgo.com/ip3/drive.proton.me.ico
(Although it seems to fail on whatsapp web, so not sure if it is right as well) https://icons.duckduckgo.com/ip3/web.whatsapp.com.ico

**Comment by mauro-balades** [comment]
Yeah, I think using the cached icon would be best. It already uses it in case the Google API fails

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/877

 ~ This is an automatic operation to better enhancements requests organization.
