### ISSUE TITLE
"This browser or device is reporting partial passkey support." bug

### ISSUE THREAD

**Issue by FixeQD** [zen-browser/desktop#2323]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![obraz](https://github.com/user-attachments/assets/8a6a7fe9-c2c2-4a1c-8751-73ee0addb8e1)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1.a.12-1

### What platform are you seeing the problem on?

Linux

**Comment by gumbarros** [comment]
I think this also happens on FF

**Comment by thatcomputerguy0101** [comment]
This does not occur on Firefox 132.0 for MacOS, but does occur on Zen 1.0.1-a.17 for MacOS, which reports being based on Firefox 132.0. Therefore, this seems to be a Zen problem?

**Comment by thatcomputerguy0101** [comment]
Seems like #437 has more info on this.

**Comment by younginc24273** [comment]
Keeps happening on Firefox 136.0 ( 64 bit ) on Linux Mint 21.3 Cinnamon Desktop 6.0.4 with  Linux Kernel: 5.15.0-134-generic x86_6

**Comment by nerdoc** [comment]
still on FF 150.0.3, Linux  6.17.0-121035 (KDE neon).
