### ISSUE TITLE
Closing last unpinned tab loads a pinned tab

### ISSUE THREAD

**Issue by JSGRD22** [zen-browser/desktop#2328]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When tabs are pinned and the last unpinned tab is closed, the closest pinned tab is loaded in the split second before a new tab is opened. This is annoying when I want to keep the pinned tabs closed to save resources.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.12

### What platform are you seeing the problem on?

Linux, Windows

**Comment by salamijason** [comment]
Hi! Are you still getting the issue? If so, could you send a screen recording?

**Comment by JSGRD22** [comment]
https://github.com/user-attachments/assets/6281401a-d8de-4d17-8563-0bebd2f25194

**Comment by JSGRD22** [comment]
Oh yeah, I should note that I am still on 1.0.1-a.12 right now. So ignore this if this issue is known to have been resolved in a later version. I will update and test it later.

**Comment by JSGRD22** [comment]
Update: this is fixed in the latest version
