### ISSUE TITLE
Tabs not saved when opening 2 instances of Zen Browser 

### ISSUE THREAD

**Issue by SarwinR** [zen-browser/desktop#2339]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

My tabs get lost when I open 2 instances of the browser and then close the one with the tabs. It appears to be saving the tabs from the remaining instance which contains no tabs hence saving nothing 😐.

### How to Reproduce
1. Open Zen Browser (Will load all the previous tabs)
2. Open another instance of Zen Browser (No tabs will be loaded)
3. Close the first instance (the one with loaded tabs)
4. Close the second instance (the one with no tabs)
5. Open Zen Browser (No tabs will be loaded!)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.12

### What platform are you seeing the problem on?

Windows

**Comment by va-tro** [comment]
Hi, @SarwinR, I have encountered the same issue on Linux machine. Have you found a solution to that bug

**Comment by SarwinR** [comment]
Hey @va-tro, sadly no. I just keep zen to a maximum of 1 instance and if I do go over that 1 instance, I make sure that I close the other unimportant ones first then the main one last.
