### ISSUE TITLE
Tabs action menu and details do not display after changing a tab to another workspace 

### ISSUE THREAD

**Issue by yhansy** [zen-browser/desktop#2343]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

After moving a tab from current workspace to another, tabs details and action menu are not displayed anymore.

- Before moving tab - action menu is also displayable
![ZEN_DEFAULT_DISPLAY](https://github.com/user-attachments/assets/940b6a56-4185-490e-b702-e6c81b437cfc)

- Moving tab to a random workspace
![ZEN_MOVE_TO_WORKSPACE](https://github.com/user-attachments/assets/c6fe453b-b5d7-40ab-9dcf-7359d9d7024e)

- Details are not displayed while hovered and action menu cannot be triggered
![ZEN_AFTER_MOVING](https://github.com/user-attachments/assets/6cfe6c69-d7e1-4012-a2cc-004b0374320b)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.13

### What platform are you seeing the problem on?

Windows

**Comment by piotr-sola** [comment]
Reproduced on 1.0.1-a.14

**Comment by JayMds** [comment]
Just saying i was about to report this one (Window 11 exe)

**Comment by thesamim** [comment]
Also seeing the issues in Windows 11.

**Comment by BuZZ-dEE** [comment]
I have this problem on EndeavourOS / Arch Linux with the Flatpak package version 1.0.1-a.17.

**Comment by salamijason** [comment]
Are you all still getting it on the a18?

**Comment by thesamim** [comment]
I am.

Additionally, move tab to container and change tab to workspace seem to have stopped working. I seem to remember that move tab to container would move it to the associated workspace. But I'm not sure. But change tab to workspace is broken: the tab does get moved to the new workspace, but it also stays in the old workspace.

**Comment by salamijason** [comment]
I'm unable to replicate the issue. Could you try creating a new profile and testing whether the bug happens there too? Thank you

**Comment by BoscoDomingo** [comment]
Same here. Still happening in a18. I also reset toolbar in case it had something to do with it. May be a mod causing it?

**Comment by thesamim** [comment]
@salamijason : seeing the behavior with new profile in .18 and .19

[This recording](https://www.dropbox.com/scl/fi/b8oqptyf2ee0wa348dum2/Zen-Loses-Right-Click.mp4?rlkey=pip71ub0dsousr2yzf4p6q6ay&st=859ng21l&dl=0) is on .18

**Comment by v1cferr** [comment]
> I'm unable to replicate the issue. Could you try creating a new profile and testing whether the bug happens there too? Thank you

## On version 1.0.1-a.19:

https://github.com/user-attachments/assets/09770f79-4927-4d0a-9bea-a6cd743fda87

**Comment by BoscoDomingo** [comment]
> > I'm unable to replicate the issue. Could you try creating a new profile and testing whether the bug happens there too? Thank you
> 
> ## On version 1.0.1-a.19:
> right-click-doesnt-work-when-change-tab-to-another-workspace.mp4

Can confirm this hack works for me

**Comment by siliconmeadow** [comment]
This issue is also happening to me on Arch Linux using 1.0.1-a.19. I created a new profile and confirmed the same thing happening.

**Comment by amatya-aditya** [comment]
@mauro-balades 
 
The issue persists for me as well on Windows 11 using latest update of zen. 
Moreover, when manually compact mode is turned off and on again, context menu is visible.

**Comment by mr-cheffy** [comment]
I know, if the issue is open, that means it hasn't got fixed

**Comment by salamijason** [comment]
Oh weird. I get this randomly too. Thanks for the recordings, though! Will send to big dev as bug.

**Comment by thesamim** [comment]
This is still happening with 1.0.2-t.3 (Firefox 133.0.3) (2024-12-17) (64-bit)
