### ISSUE TITLE
Workspace name gets shrinked when mouse is not over the sidebar

### ISSUE THREAD

**Issue by Smooth-E** [zen-browser/desktop#2346]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

After updating today I noticed that the workspace button at the bottom of the sidebar shrinks and hides the name of the workspace when I am not hovering over the sidebar. Here are some screenshots:

| Mouse over the sidebar (anywhere, e.g. selecting a tab) | Mouse over a webpage |
| --- | --- |
| ![Hovering over sidebar](https://github.com/user-attachments/assets/7e7bea57-b09d-4888-893c-4290c79263eb) | ![Default state](https://github.com/user-attachments/assets/67c29aab-99cb-40ab-bb2e-cb12e73f2322) |

Similar thing happens with sidebar in compact-sidebar mode (when tab names are not shown, the 🔄 switch): icon positioning is broken and changes when I hover over the tab strip.

| Mouse over the sidebar (tab-bar) | Mouse over a webpage |
| --- | --- |
| ![Moue over sidebar](https://github.com/user-attachments/assets/dc61cc75-3dfc-4b50-adfc-1efccca75b93) | ![Mouse over webpage](https://github.com/user-attachments/assets/9a0ee4dd-e158-4818-a2cd-99ba71fc8e9d) |

Enabling Zen Compact mode (when sidebar is hidden) does not affect this behavior.

Don't know whether to check "Not reproducible on Mozilla Firefox", because Firefox does not have a sidebar or workspaces.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.13

### What platform are you seeing the problem on?

Windows

**Comment by sjclayton** [comment]
Can confirm this as well, I updated to a.13 only on my Windows machine, and noticed this right away... haven't checked on Linux yet.

**Comment by DaitiDay** [comment]
Same here

**Comment by pinage404** [comment]
I reproduce the bug in `1.0.1-a.14` on Linux

It's really anoying : with compact tab bar, workspaces are not usuable

[Screencast with a demo](https://github.com/user-attachments/assets/7632ddb6-d3f3-4db4-96c0-5e406966e624)

Workaround solutions : 
* Options > Look and Feel > Sidebar and tabs layout > check Expand Tabs by Default
* Options > Tab Management > Workspaces > check Display workspaces as an icon strip

**Comment by MegadronA03** [comment]
https://github.com/user-attachments/assets/883931b2-bc27-4d34-ba73-fd906204beae

1.0.1-a.14

*I did check on new profile. Its the same thing.

**Comment by MegadronA03** [comment]
bug no longer appears in:
1.0.1-a.15 and 1.0.1-a.16

https://github.com/user-attachments/assets/f6ed020b-e73c-4658-bd9c-03e50f10df9b

**Comment by Smooth-E** [comment]
> bug no longer appears in: 1.0.1-a.15 and 1.0.1-a.16
> zen_OstiCr3uRR.mp4

Can confirm. I think, it is safe to close this issue.
