### ISSUE TITLE
Search bar does not work at sidebar

### ISSUE THREAD

**Issue by gumbarros** [zen-browser/desktop#2347]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![image](https://github.com/user-attachments/assets/69a553a9-bce0-4822-a70d-ae828cbd70b1)
![image](https://github.com/user-attachments/assets/498fe3b3-0272-4926-b078-d1a22e7f93d3)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.13

### What platform are you seeing the problem on?

Linux

**Comment by shadowash8** [comment]
Hi @gumbarros,

This issue appears to be related to the placement of the search bar. You can resolve it by right-clicking on the toolbar, selecting "Customize Toolbar," and then either moving the search bar to a different position or removing it altogether.

Closing this issue now. Thank you!
