### ISSUE TITLE
Broken theme support, no color picker

### ISSUE THREAD

**Issue by szpatrik5** [zen-browser/desktop#2348]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

1. The new a.13 update broke the compatibility with Firefox themes. If I use a theme icons and the url bar no longer getting colored by the theme.
2. Color picker won't showing up, you have to create a new profile to get it.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.13

### What platform are you seeing the problem on?

Windows

**Comment by mr-cheffy** [comment]
Yeah sorry, we are just moving away from firefox themes as we try to expand on new things. In order for the picker to appear, you need to have workspaces enabled too. Sorry!
