### ISSUE TITLE
Add Keyboard shortcut to focus on the navbar

### ISSUE THREAD

**Issue by Dadangdut33** [zen-browser/desktop#235]
### What feature would you like to see?

By default we can focus on the navbar by using the F6 key. It would be great if we could remap it using the custom keyboard shortcut function in zen

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/876

 ~ This is an automatic operation to better enhancements requests organization.
