### ISSUE TITLE
Pitch black transparent overlay on web panel

### ISSUE THREAD

**Issue by Domtastick** [zen-browser/desktop#2353]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

After the browser auto updated i've noticed that any website i try to open in the web panel has a very dark transparent black overlay on top of it that makes it unreadable.

Here's an image showcasing that:
![image](https://github.com/user-attachments/assets/c0670ee8-afde-48c7-9e5d-9e2bb799589d)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.13

### What platform are you seeing the problem on?

Windows

**Comment by Richard-Woessner** [comment]
Its happening to me to on Zen Twilight but I couldn't recreate it on my build from the Dev branch. Has this already been fixed @mauro-balades ?

**Comment by mr-cheffy** [comment]
Yes

**Comment by OwenD30** [comment]
Also happening for me, Linux (Fedora 40, Gnome 46), installed through FlatHub.

**Comment by LaserKaspar** [comment]
Had this issue on 1.0.1-a.13. Its fixed for me in 1.0.1-a.14.

**Comment by ashwinjadhav818** [comment]
This issue was fixed in [1.0.1-a.14](https://github.com/zen-browser/desktop/releases/tag/1.0.1-a.14) hence closing it

**Comment by shadowash8** [comment]
This issue was fixed in [1.0.1-a.14](https://github.com/zen-browser/desktop/releases/tag/1.0.1-a.14) hence closing it
