### ISSUE TITLE
Tab icons glitch when focusing browser window

### ISSUE THREAD

**Issue by XInTheDark** [zen-browser/desktop#2358]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When focusing the Zen browser window, from any other application, the tab icon flickers. Apparently the names of the individual tabs are repeatedly shown over the icons for a short time.

The sidebar also sometimes expands slightly.

The issue happens both when manually switching to the application, as well as when switching with AltTab.

**This happens only when the "Expand Tabs on Hover" option is selected in Look and Feel.**

Video recording:

https://github.com/user-attachments/assets/c7c91bf2-d17b-4fcb-87fc-3598c6af2c4e

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.14

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by RayZ3R0** [comment]
have you tried on a new profile?

**Comment by RayZ3R0** [comment]
Closing this as no response
