### ISSUE TITLE
Some UI elements don't respect color selector

### ISSUE THREAD

**Issue by Anthonyy232** [zen-browser/desktop#2359]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Some UI elements don't respect the new color picker. For example, the URL bar, a tab item on the tab side bar, and a blank page if new tab page is set to blank.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Version 1.0.1-t.14 (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by khan5ula** [comment]
Also experiencing this on Arch Linux on v. Mozilla Zen 1.0.1-a.14.

URL bar is now persistently pink and I can't change it via accent colors or themes.

**Comment by mr-cheffy** [comment]
Those are based on this color as we still havent found a solution to find the most dominant color:
![image](https://github.com/user-attachments/assets/e390f9ac-8db0-4027-8fe0-704a307bf3ab)
