### ISSUE TITLE
Privacy Concerns with Browser Startup Connections

### ISSUE THREAD

**Issue by albu-ali** [zen-browser/desktop#236]
### What happened?

Hi Zen-browser Team,

I wanted to bring something to your attention. I've been monitoring my DNS logs and noticed that the zen-browser is connecting to certain domains, including some Google domains, right at startup. This seems to go against the browser's privacy focus.

Since you all prioritize user privacy, I'm curious—are these connections essential for functionality? If not, they might need to be reconsidered.

Looking forward to your thoughts on this. Hopefully, it's something that can be addressed soon.

Thanks!
Albu-Ali

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.17 

### Severity impact

High, Enhancement

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
domains are zen browser connecting to when it startup
prod[.]remote-settings[.]prod[.]webservices[.]mozgcp[.]net
firefox[.]settings[.]services[.]mozilla[.]com
dualstack[.]n[.]sni[.]global[.]fastly[.]net
cdn[.]statically[.]io
push[.]services[.]mozilla[.]com
cdn[.]statically[.]io
content-signature-chains[.]prod[.]autograph[.]services[.]mozaws[.]net
firefox[.]settings[.]services[.]mozilla[.]com
push[.]services[.]mozilla[.]com
content-signature-2[.]cdn[.]mozilla[.]net
gstatic[.]com
```

**Comment by mauro-balades** [comment]
Heya! These connections are nothing to worry about. Most of them are just Firefox's security system, updates fetching, etc.

About Google, the sidebar uses Google's favicon API to get the website's favicon, but it doesn't harm anyone. We are moving to a cache only way of getting these favicons without having to interact with Google though. Zen is as private as it can get, there's nothing to worry about

**Comment by albu-ali** [comment]
I believe your browser genuinely cares about user privacy. However, some users might not be comfortable with their IP connecting to Google in any way.

**Comment by mauro-balades** [comment]
Nothing is logged in that static server, but I get it
