### ISSUE TITLE
Workspace gradient bugged in Expand on hover

### ISSUE THREAD

**Issue by RABINGG** [zen-browser/desktop#2360]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When expand on hover is enabled on sidebar the workspace gradient doesn't applies on expand state. Works fine on other options (expand on default and don't expand).

Minimised:
![image](https://github.com/user-attachments/assets/d5c1cb7c-7e41-4d4a-bd07-1a9caf9667e8)

Expanded On Hover:
![image](https://github.com/user-attachments/assets/aea8fc5a-a1f2-4237-830a-de82425ddbbc)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.14 (Firefox 131.0.3) (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by mr-cheffy** [comment]
This will be fixed for the next release, thanks a lot!
