### ISSUE TITLE
Colour picker manual HEX input issue 

### ISSUE THREAD

**Issue by enews** [zen-browser/desktop#2361]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

writing in HEX colours without the hashtag will still allow the user to input the colour, but it will make the colour black. Some programmes like PowerToys don't paste with the '#'. I'd suggest auto completing the hashtag or not allowing a user to input such colours as it can break their theme. 

https://github.com/user-attachments/assets/fadfa3c0-60da-442e-8cec-2dcea3c9bf91

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.14 (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by ViridityCorn** [comment]
For me, it seems the tab-bar becomes transparent when using "show only on hover" and an invalid hex code (or missing the #) in the gradient options

**Comment by mr-cheffy** [comment]
You need to add the # infront of the hex color. The input takes any css value, so it can be `red`, `rgb`, `hex`, etc
