### ISSUE TITLE
does not respect text-decorator

### ISSUE THREAD

**Issue by littleblack111** [zen-browser/desktop#2364]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I'm using nextjs(doesnt matter since i tested it in vanilla html / css and it presist), and the text-decorator css class does not seem to work. I'm applying text-decorator: none to <a> element and is using ::after for custom decorators.

other browsers(including firefox) seem to respect it, such as chromium

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.12 (Firefox 131.0.3) (64-bit)

### What platform are you seeing the problem on?

Linux

**Comment by mr-cheffy** [comment]
Could you send the html, expected image and actual result? Thanks

**Comment by littleblack111** [comment]
literally any \<a\>s with text-decoration:none

zen:
![Screenshot_2024-10-28-19-14-25](https://github.com/user-attachments/assets/e5257bfa-3ce7-404b-99ed-beef8ef83561)


expected/other browser(chromium in this case):
![Screenshot_2024-10-28-19-16-18](https://github.com/user-attachments/assets/b918f72a-bba3-44cd-b5f0-ab0fc9d63a70)
(sry the color is kinda weird becuz i clicked it)


the example html shown that i used text-decoration: none on both style property on html and css
```
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>hi</title>
    </head>
    <body>
        <a href="/" style="text-decoration: none">hi</a>
    </body>
    <style>
        a {
            text-decoration: none;
        }
    </style>
</html>
```
