### ISSUE TITLE
Arow keys no longer working

### ISSUE THREAD

**Issue by Ment0oz** [zen-browser/desktop#2365]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When watching a youtube video, I noticed I couldn't use the arrow keys to come back or go forward. This also affects other tabs and websites.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a14

### What platform are you seeing the problem on?

Windows

**Comment by mr-cheffy** [comment]
This is because sites like youtube are interfering with the shortcuts, this is a web standard, not much we can do, sorry.

**Comment by Ment0oz** [comment]
I get that, but it also affects the browser's frontpage
