### ISSUE TITLE
can't make tab bar smaller

### ISSUE THREAD

**Issue by Zenvote** [zen-browser/desktop#2366]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Tab bar used to be really small, which I liked, but after the latest update it got 10x bigger and even when I make it smaller its 5x bigger than before. 
![image](https://github.com/user-attachments/assets/f6b6b6d6-6b00-43ad-9233-f6e730f693a3)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1

### What platform are you seeing the problem on?

Windows

**Comment by appel** [comment]
Same issue here, using Zen 1.0.1-a.14 on Windows 11. Pinned tabs are now three icons in a row where it used to be one. I can drag to resize to make the tab bar bigger, but not smaller than 3.

![image](https://github.com/user-attachments/assets/7048c916-58ff-4bb8-8790-cce302cbc570)

For what it's worth, Compact Mode (or zen.view.compact) does not fix this issue, though I am using it as a workaround for now.

I'm using Zen exclusively on a monitor in portrait mode where I pin my most used sites, so I much preferred the previous slimmer tab bar. It would be great if we could resize the tab bar to fit a single pinned tab per row again.
