### ISSUE TITLE
Need capability to move tabs from one Workspace to another.

### ISSUE THREAD

**Issue by guigirl42** [zen-browser/desktop#237]
### What feature would you like to see?

Atm i've not been able to find an elegant way to move _existing_ tabs in [eg] `Workspace A`, to `Workspace B`, etc. 

I would like to be able to do this by **dragging & dropping, &/or via RMB context-menu** option.

Unless i'm not seeing a current option, so far i need to clumsily copy each tab's url from `Workspace A`, change to `Workspace B`, then paste it. That's inefficient even for _one_ tab, but highly problematic for _multiple_ tabs. 

### What platform are you seeing the problem on?

Linux

**Comment by lazymonkey2** [comment]
yes please, I'm also missing the ability to move tabs between workspaces.
thanks.

**Comment by KjalaNIX** [comment]
Man, I hope the browser maker sees this and actually implements it. Otherwise, workspaces in Zen are a half-baked feature as of right now.

**Comment by mauro-balades** [comment]
Good new! Literally just implemented this. I'm releasing the new version right now!

**Comment by KjalaNIX** [comment]
> Good new! Literally just implemented this. I'm releasing the new version right now!

GOATED!!!!

**Comment by guigirl42** [comment]
@mauro-balades Oh wow, thank you so much! :hugs:
