### ISSUE TITLE
After 1.0.1-a.14 update, website don't load. Switching profile fix the problem.

### ISSUE THREAD

**Issue by sj0n** [zen-browser/desktop#2370]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The browser shows onboarding screen after updating. After completing everything any website just refuse to load. Switching to a different profile fix the problem. I have the same extensions installed on new profile because I have firefox sync setup.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.14

### What platform are you seeing the problem on?

Windows

**Comment by salamijason** [comment]
Hey looks like you found the fix :D BUT if you do get it again, please screen record it and open another issue.
