### ISSUE TITLE
Blurred fonts in 1.0.1-a.14 

### ISSUE THREAD

**Issue by maxsteenbergen** [zen-browser/desktop#2375]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

This issue has been reported and fixed before, but now with 1.0.1-a.14 on a 5K iMac, fonts have become blurry again. 
The issue seems to become progressively worse with increasing window size as evidenced by this screenshot.

<img width="3312" alt="Screenshot 2024-10-28 at 14 17 30" src="https://github.com/user-attachments/assets/c3943342-93c2-442d-be49-094cce00ce09">

I disabled all zen mods to rule them out.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.14 

### What platform are you seeing the problem on?

macOS - Intel

**Comment by carabistouflette** [comment]
I got the same issue on Linux with hyprland. I got the problem when updating to a.13

**Comment by rrpolanco** [comment]
I'm running 1.0.1-a.14 on MacOS(arm) and there seems to be a rendering issues where the page flickers and the fonts indeed look blurry. Please fix this!

**Comment by maxsteenbergen** [comment]
I found that setting `zen.view.experimental-rounded-view` to `false` in about:config resolves the issue. Very likely it's the mix-blend-mode statement in zen-browser-container.css that's the culprit

![Screenshot 2024-10-28 at 16 23 53](https://github.com/user-attachments/assets/f519ffa5-11dc-48a1-baf8-e314463a2287)

**Comment by bernardodsanderson** [comment]
Nice fix @maxsteenbergen, worked for me!

**Comment by Redcupss** [comment]
Worked for me too as long as Super Url Background blur setting is switched off.

**Comment by shrimpwtf** [comment]
> zen.view.experimental-rounded-view

works as a temporary fix but now the corners are a bit ugly. better than blurry font though haha

**Comment by skegel13** [comment]
It's not as bad, but I've noticed this issue in Firefox, too, so I don't think it's completely related to Zen. For me, it happens with my ultra-wide (5120x1440). Firefox seems to do a better job of correcting it, but I still get a flash of the blurry fonts. Zen usually just stays blurry.

**Comment by nanolookc** [comment]
Not seeing this at firefox at all, checked on the same websites. zen.view.experimental-rounded-view fixed the issue, thanks!

**Comment by mr-cheffy** [comment]
Does this only happen in macos? Also, does anyone know how to use the browser's UI devtools?

**Comment by skegel13** [comment]
> Does this only happen in macos? Also, does anyone know how to use the browser's UI devtools?

For me, yes, only happening with my ultra-wide (5120x1440) in MacOS. The zen.view.experimental-rounded-view setting fixed it for me.

I can also inspect the browser chrome. Anything in particular you are looking for?

**Comment by skegel13** [comment]
Doing some more testing and I think it's a rendering issue with Firefox in general. The `zen.view.experimental-rounded-view` fixes blurring for most pages, but I'm guessing if whatever styling that's removing is being used on a page somewhere else, the blurriness comes back. For example, on MacOS with an ultrawide (5120x1440), I get blurry text on both Zen and Firefox when using Linear (linear.app). Zen can likely fix most pages by removing the specific styling in the browser chrome, but this seems like a larger Firefox issue in general.

**Comment by maxsteenbergen** [comment]
I will agree that this might originate from the original Firefox source. I can remember the same issue happening in stock Firefox several years back. That being said, given that disabling the experimental setting basically amounts removing one CSS rule that creates a new stacking context, it does give some clue. Maybe adding an `isolation: isolate;` rule somewhere in Zen's CSS is a more constructive fix?

**Comment by harryheres** [comment]
Can confirm (https://github.com/zen-browser/desktop/issues/707#issuecomment-2445323181), looking into this.

Unable to experience this on pure Firefox 132.0 (maybe a little, but definitely not as noticeable).

**Comment by ralphsun73221** [comment]
This issue was fixed before a14, but for some reason it started appearing again in a14, at least that's the case for me.

**Comment by limonkufu** [comment]
It seems like this is the same issue as this one coming back: https://github.com/zen-browser/desktop/issues/440

**Comment by mr-cheffy** [comment]
> I will agree that this might originate from the original Firefox source. I can remember the same issue happening in stock Firefox several years back. That being said, given that disabling the experimental setting basically amounts removing one CSS rule that creates a new stacking context, it does give some clue. Maybe adding an `isolation: isolate;` rule somewhere in Zen's CSS is a more constructive fix?

Adding `isolation: isolate;` to the browser element fixed it for you?

**Comment by maxsteenbergen** [comment]
I haven't been able to check it in this case, but it did work a while back in a different situation that had some rendering issues.

**Comment by nanolookc** [comment]
Also, have blurred fonts in devtools. Fix above doesn't work for that.

**Comment by maxsteenbergen** [comment]
@mauro-balades I'd love to take a deeper dive into this myself but I can't get Zen to build. The docs mention a dependency on Windows (mozbuild.exe) but I'm on macOS. Any chance on updating the docs to getting local build on Mac working, so I can help out?

**Comment by harryheres** [comment]
Update - happens only on external monitor for me when running a HiDPI resolution. On native Mac screen, it seems okay.  Removing `mix-blend-mode`does resolve this issue.

**Comment by ralphsun73221** [comment]
I just updated to a15, and I still need to set `zen.view.experimental-rounded-view` to `false` to avoid this issue.

**Comment by mr-cheffy** [comment]
@HarryHeres can I leave this to you?

**Comment by harryheres** [comment]
> @HarryHeres can I leave this to you?

Sure thing, on it already

**Comment by sladiri** [comment]
I got blurry fonts too. I am on Windows and using an 8K monitor. `zen.view.experimental-rounded-view=false` helps for me too.

**Comment by say4n** [comment]
This exists in 1.0.1-a.17 as well and the suggested workaround still works.

**Comment by harryheres** [comment]
Just an update - have a potential fix ready, just need to figure out the build issues on Mac.

**Comment by HarryHeres** [comment]
So, as I don't experience this on my Linux and cannot seem to build on Mac, could someone test out a simple change in https://github.com/zen-browser/desktop/pull/2699? 

It would be awesome if someone could test it before we merge this PR

**Comment by mr-cheffy** [comment]
I've disabled it by default for macos, until we fix this

**Comment by ShawakSaraf** [comment]
![image](https://github.com/user-attachments/assets/afe8e598-9fe5-4e0c-9f68-f3a1b32f0929)

**Version 1.0.1-a.17 (64-bit):** Text rendering is inconsistent. In the above image, some lines are rendered correctly and some are blurry.

**Comment by gautierlabarre** [comment]
I've noticed the same issue on a.17 if it's in fullscreen, and it's easily testable (for me) when I open the dev tools all the fonts on the dev tools are blurry, it tries to adapt and becomes good until I move the mouse, and it blurs as well. 

I tried the settings listed above at false (same issue) but I have the mods super url with blur, maybe it's related, I can test to disable it if you think it can help.
Also, I am on a 4k monitor and enabled the zoom on text (and text only)

**Comment by luisfscoelho** [comment]
It still happens on the a.19.

**Comment by rutger1140** [comment]
Just confirming the fix of `zen.view.experimental-rounded-view=false` works on Wayland / Ubuntu 24.10 / 5K display.

**Comment by thomasaldershof** [comment]
Setting `zen.view.experimental-rounded-view` to `false` does not fix this problem for me on Windows 11 / 5120x1440.

**Comment by littleblack111** [comment]
> Just confirming the fix of `zen.view.experimental-rounded-view=false` works on Wayland / Ubuntu 24.10 / 5K display.

hmm it was working for me too, then after a few updates not it doesn(im using arch btw) on hyprland(wayland compositor)

please fix this asap as it's really really annoying

**Comment by amagnolo** [comment]
Also reported in #2671 and #1276.

**Comment by 2q2code** [comment]
Also on arch/hyprland - the `zen.view.experimental-rounded-view=false` definitely improved it, but it's played with my eyes so I will need to come back to see if it is fixed. Horrible feeling when you feel you can't focus your eyes!

**Comment by neurokitti** [comment]
duplacate of https://github.com/zen-browser/desktop/issues/1276

**Comment by littleblack111** [comment]
ah again? regression is crazy

**Comment by victorallume** [comment]
Happening to me after update 1.9.1b (Firefox 136.0.1) (64-bit) on Linux/X. Only happens on full screen, and even then, there's exceptions (e.g. settings page will be blurry, when when I drag another window from another screen over the top, it sharpens up. Also, as I'm typing this, the main github page is blurry, but the text box I'm typing into is sharp.

**Comment by cristian-fleischer** [comment]
I'm experiencing the exact same issue as victorallume.
Text starts out blurry, but various events that probably trigger a re-render fix it. (hovering over the text, selecting it, moving the browser window, etc)

I can confirm `zen.view.experimental-rounded-view=false` fixes the issue on Wayland PopOS 24.04 Cosmic Desktop epoch

**Comment by sladiri** [comment]
For me `zen.view.experimental-rounded-view=false` fixes it only in full screen. (Gnome 48, AMD and Intel GPUs have both the same issue).

**Comment by Gensokian** [comment]
Sorry to re-open this; but i want to avoid creating a duplicate.
Im running Zen on a larger monitor (5120 x 1440) and once I start scrolling/interacting with any page the blur still happens
![Image](https://github.com/user-attachments/assets/0fc6e86e-dd64-4778-8326-a4909bd91b41)

Due to my bad eyesight I also need to run on 150% scale which combined with that blur makes the browser almost unusable*
![Image](https://github.com/user-attachments/assets/c6e6a1a3-c69f-410f-9b0d-03cd420774d9)

*There are three fixes:

1. Interact with the content so ZEN gets its things together
![Image](https://github.com/user-attachments/assets/78a963f5-1db5-40e6-9c2c-bc5310d27ad9)
2. Work with a "normal" sized Window
3. Use "zen.view.experimental-rounded-view=false"; but that does not completely fix the issue
![Image](https://github.com/user-attachments/assets/769baac7-9733-45a7-ae33-4b90bfd79a44)

**Comment by mr-cheffy** [comment]
@Gensokian Firefox 139 will fix the issue, we just have to wait

**Comment by littleblack111** [comment]
the defaults seem to make the text not blurry, however, it seems like we need a hack(browser { clip-path: polygon(0 0, 100% 0, 100% 100%, 0 100%); }) to make normal backdrop-blur work at the browser level, which makes the texts blurry again

**Comment by othyn** [comment]
@Gensokian I can confirm the exact same thing.

Fresh install. No Zen mods. No CSS tweaks.

The `zen.view.experimental-rounded-view = false` does **not** work for me, or any of the other proposed flags.

```
      Display: 5120 x 2160 (21:9) @ 120hz
   OS Scaling: 125%
  Zen Browser: 1.15.5b (flatpak) (Firefox 142.0.1) (64-bit)
           OS: Fedora 42 (Workstation Edition)
  Desktop Env: GNOME 48
Windowing Sys: Wayland
       Kernel: 6.16.7
```

Here is a video showing it, it's really bizarre. If you keep the **window** small, ~<2,000 pixels wide, its mostly fine. If however you go ~>2,000px wide on the **window** width, it suddenly stops rendering properly and goes all smeary/blurry. Even the devtools are affected.

What's weird is its _not_ the responsive page size. As you can see, I can make the page itself as wide as I want and its still always tack sharp. However, if I adjust the window width, that's what's causing it to go blurry. (due to size limits, had to be two videos)

https://github.com/user-attachments/assets/d83d69ee-38ee-401f-8906-d1de9d7fc56d

Fig 1. Showing the blur when the window width goes beyond ~2,000px wide, then being fine-ish again under 2,000px wide. The rendering issue also affecting devtools.

https://github.com/user-attachments/assets/454a73f1-e401-4969-a466-c6b79e84ef02

Fig 2. Showing the responsive page width not affecting the blur, but the blur occurring only when the window width goes beyond ~2,000px wide, then being fine-ish again under 2,000px wide. The rendering issue also affecting devtools.

Looks like the new issues are:
- https://github.com/zen-browser/desktop/issues/8421
- https://github.com/zen-browser/desktop/issues/8396
