### ISSUE TITLE
Zen browser feels like 25FPS

### ISSUE THREAD

**Issue by ufukbakan** [zen-browser/desktop#2376]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Everything in zen browser looks like have a performance cap.
Everything but everything is laggy.
Scrolling through pages,
Rendering pages,
rendering images,
rendering videos
Very poor performance compared to every other browser...

![image](https://github.com/user-attachments/assets/ac6b3dfd-64cf-4f02-a9c2-5ba9bff87511)

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.14 (Firefox 131.0.3) (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by ufukbakan** [comment]
scratches my eyes on a 144hz monitor

**Comment by anatasiajp** [comment]
Have you tried the native Zen instead of flatpak ? Looks like Zen can't use your NVIDIA GPU at all

**Comment by RayZ3R0** [comment]
> Have you tried the native Zen instead of flatpak ? Looks like Zen can't use your NVIDIA GPU at all

They're on windows..

> Everything in zen browser looks like have a performance cap. Everything but everything is laggy. Scrolling through pages, Rendering pages, rendering images, rendering videos Very poor performance compared to every other browser...

Did you install the optimized version of zen or the generic one

**Comment by zenless911** [comment]
> Did you install the optimized version of zen or the generic one

Similar problem here. I already reinstalled to clarify. Yes, I'm using the Optimized version, and it's still stuttering when scrolling. I also tried the UFO test site with my 120hz monitor, it just wouldn't keep up on some other tests, especially compared to other browsers.

The last version doesn't have this issue.

**Comment by Manut38** [comment]
To me this issue it feels like this issue was introduced in the latest a.14. I'm using the optimized build on Windows on two machines and it's very noticeable even when scrolling since two days.

**Comment by mr-cheffy** [comment]
Does it get better once you disable `zen.view.experimental-rounded-view` in about:config?

**Comment by Manut38** [comment]
@mauro-balades YES! It does. It still feels like its more laggy than previous builds but that might be just negative placebo by now 😁
But the big lag spikes that occurred all the time are gone when I disable this setting.
What does it do? The web view is still rounded, even when disabled, or does this toggle something different?
Thank you!

**Comment by anatasiajp** [comment]
> @mauro-balades YES! It does. It still feels like its more laggy than previous builds but that might be just negative placebo by now 😁 But the big lag spikes that occurred all the time are gone when I disable this setting. What does it do? The web view is still rounded, even when disabled, or does this toggle something different? Thank you!

Because  the previous version used to use a pseudo element as rounded corners, a pseudo element doesn't interract with browser view, but currently we moved to a real element approach.
