### ISSUE TITLE
Search on number keypress

### ISSUE THREAD

**Issue by floork** [zen-browser/desktop#2377]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When typing any number on the keyboard, it opens a quick find with the number I pressed

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.14

### What platform are you seeing the problem on?

Linux

**Comment by sjclayton** [comment]
@floork 

In Preferences, go to `General > Browsing` and make sure the option `Search for text when you start typing` is unchecked, this feature comes from Firefox.

**Comment by floork** [comment]
Sorry I didn't see that option and in firefox it was disabled!

Thanks for the help
