### ISSUE TITLE
Option for Pinned Tabs to appear in SINGLE Workspaces, or ALL Workspaces as now. 

### ISSUE THREAD

**Issue by guigirl42** [zen-browser/desktop#238]
### What feature would you like to see?

Afaict, atm all Pinned Tabs appear across ALL Workspaces. 

If possible, pls could we have an **option to have tabs be pinned per Workspace, rather than all Workspaces?** 

### What platform are you seeing the problem on?

Linux

### Additional context

I don't know if this is helpful or not wrt design for this feature request, but the fantastic Add-On `Sidebery` provides this capability [but atm `Sidebery` is not terribly compatible with Zen, so i only use it in `Firefox`, `Firefox Nightly`, & `Floorp`].

**Comment by Giuliopime** [comment]
This is the only reason why I'm not switching to zen right now, I need different pins for different workspaces. And I don't wanna use different profiles for that

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/875

 ~ This is an automatic operation to better enhancements requests organization.
