### ISSUE TITLE
The window remains open even when the last one is closed

### ISSUE THREAD

**Issue by aljustiet** [zen-browser/desktop#2380]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Before version 1.0.1.a.14-1, the window would close when I closed the last tab. Now, it stays open.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1.a.14-1

### What platform are you seeing the problem on?

Linux

**Comment by salamijason** [comment]
Hey what do you mean it stays open? Does it open a new tab? Is it completely blank? A screen recording would be helpful!

**Comment by aljustiet** [comment]
> Hey what do you mean it stays open? Does it open a new tab? Is it completely blank? A screen recording would be helpful!

https://github.com/user-attachments/assets/a29585d6-91d8-40b9-878d-481d9efcc980

**Comment by salamijason** [comment]
In about:config, what is `browser.tabs.closeWindowWithLastTab` set to?

**Comment by aljustiet** [comment]
> In about:config, what is `browser.tabs.closeWindowWithLastTab` set to?

true

**Comment by fskaeh** [comment]
I thought this behaviour was intentional (and hope it was because it's a change in the right direction in my opinion). When closing the last tab in a window, it opens a new tab.

**Comment by RayZ3R0** [comment]
Can you try reinstalling, and/or using a different profile to see if this issue still persists

**Comment by aljustiet** [comment]
> Can you try reinstalling, and/or using a different profile to see if this issue still persists

In another profile, closing the last tab opens the homepage.

**Comment by aljustiet** [comment]
> Can you try reinstalling, and/or using a different profile to see if this issue still persists

In another profile, closing the last tab opens the homepage.

**Comment by RayZ3R0** [comment]
> > Can you try reinstalling, and/or using a different profile to see if this issue still persists
> 
> In another profile, closing the last tab opens the homepage.

That's expected then. Did you set `browser.tabs.closeWindowWithLastTab` to true in the other profile?

**Comment by aljustiet** [comment]
> browser.tabs.closeWindowWithLastTab

![image](https://github.com/user-attachments/assets/80233a1f-0f42-4a3f-bc10-23221deb35f2)

**Comment by RayZ3R0** [comment]
That's odd then. We'll look into it

**Comment by mr-cheffy** [comment]
This is on purpose because it bring in a question: Should it remove the workspace or should workspaces have at least one tab?

**Comment by salamijason** [comment]
big dev said it's intentional soo.....

**Comment by aljustiet** [comment]
> This is on purpose because it bring in a question: Should it remove the workspace or should workspaces have at least one tab?

Can't you just change the default flag? I want to be able to close the workspace using Ctrl+W.

**Comment by salamijason** [comment]
What do you mean by "close the workspace"? Do you mean closing the window? Or have a workspace with no tabs at all?

**Comment by aljustiet** [comment]
> What do you mean by "close the workspace"? Do you mean closing the window? Or have a workspace with no tabs at all?

closing the window

**Comment by salamijason** [comment]
Hmm I do believe this is intentional. I haven't encountered many users take issue with this since not many want their browser window closed if they close all tabs (maybe they clean their tabs often and still wanna keep the window). 

If you want to close the window, might as well alt f4 or use the other quit window shortcut ctrl shift q.

**Comment by aljustiet** [comment]
> Hmm I do believe this is intentional. I haven't encountered many users take issue with this since not many want their browser window closed if they close all tabs (maybe they clean their tabs often and still wanna keep the window).
> 
> If you want to close the window, might as well alt f4 or use the other quit window shortcut ctrl shift q.

Since I use Hyprland, I should kill the window. But I'm used to close the windows with the ctrl+w for browsers, and I don't want to change this behavior.
