### ISSUE TITLE
Flickering/cut off context menus

### ISSUE THREAD

**Issue by StrongSand94191** [zen-browser/desktop#2385]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Whenever I right click to open the context menu, or click on an extension, or anything else that opens a menu thingy, it starts flickering, making it difficult to click. The menus are also cut off. If it would be helpful, I can provide a recording.

If it matters, I am using the Flatpak on NixOS.

This might be my fault because I haven't seen anyone else with this issue :3c

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.14

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
Gdk-Message: 16:02:17.879: Unable to load ew-resize from the cursor theme
Gdk-Message: 16:02:19.957: Unable to load ew-resize from the cursor theme
Gdk-Message: 16:02:20.407: Unable to load ew-resize from the cursor theme
Gdk-Message: 16:02:20.800: Unable to load ew-resize from the cursor theme
Gdk-Message: 16:02:22.642: Unable to load pointer from the cursor theme
[Parent 2, Main Thread] WARNING: ../gdk/wayland/gdkcursor-wayland.c:243 cursor image size (9x16) not an integermultiple of scale (2): 'glib warning', file /home/runner/work/desktop/desktop/engine/toolkit/xre/nsSigHandlers.cpp:187

(zen-alpha:2): Gdk-WARNING **: 16:02:22.785: ../gdk/wayland/gdkcursor-wayland.c:243 cursor image size (9x16) not an integermultiple of scale (2)
Gdk-Message: 16:02:22.829: Unable to load pointer from the cursor theme
Gdk-Message: 16:02:22.955: Unable to load pointer from the cursor theme
Gdk-Message: 16:02:23.346: Unable to load pointer from the cursor theme
Gdk-Message: 16:02:23.363: Unable to load pointer from the cursor theme
Gdk-Message: 16:02:23.623: Unable to load pointer from the cursor theme
```

**Comment by sjclayton** [comment]
Duplicate of #2384 - Please close this issue.

**Comment by StrongSand94191** [comment]
> Duplicate of #2384 - Please close this issue.

my bad, i accidentally closed my browser and i thought it didn't work the first time
