### ISSUE TITLE
Alert on security feature offering less protection

### ISSUE THREAD

**Issue by gautierlabarre** [zen-browser/desktop#2387]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Whenever i open zen, i get this alert at the bottom right part of the screen :

![image](https://github.com/user-attachments/assets/df2f6e8d-37f1-4389-9cae-1f028377250b)
I use an appimage (in .local/share/applications) and created the .desktop file before I saw you have a script for this here is the content if it can help 

```bash
[Desktop Entry]
Name=Zen browser
GenericName=Zen browser
Exec=/..../zen.AppImage
Terminal=false
Type=Application
Icon=/.../zenbrowser.png
StartupWMClass=zen-alpha
``` 

I use ubuntu 24.10

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

.14 (latest)

### What platform are you seeing the problem on?

Linux

**Comment by salamijason** [comment]
Hey this issue has come up before! Happens often on linux systems. The solution should be in the link.

**Comment by gautierlabarre** [comment]
Hi, sorry I did not see the part on apparmor, only the installation part.
<s>However, i'm still confused, I see a path for firefox, firefox-bin etc in the file I should create, should I replace all occurence of firefox with zen or a simple copy/paste would suffice as zen is based on firefox ?</s>

I managed to make it work, thanks

**Comment by simon-ami** [comment]
This worked for me too, had Claude help me and give me a summary at the end for others:


> Fix for "Security features may offer less protection" warning on Linux
> 
>   For Zen Browser AppImage installations:
> 
>   1. Find your Zen installation path:
> 
> ```
>   which zen  # or locate your zen.AppImage
> ```
> 
>   2. Create AppArmor profile:
> 
> ```
>   sudo nano /etc/apparmor.d/zen-local
> ```
> 
>   3. Add this content (adjust path to match your installation):
> ```
>   # This profile allows everything and only exists to give the
>   # application a name instead of having the label "unconfined"
>   abi <abi/4.0>,
>   include <tunables/global>
>   profile zen-local
>   /path/to/your/zen/{zen,zen-bin,updater}
>   flags=(unconfined) {
>       userns,
>       # Site-specific additions and overrides. See local/README for
>   details.
>       include if exists <local/zen>
>   }
> ```
>   4. Restart AppArmor:
> 
> ```
>   sudo systemctl restart apparmor.service
> ```
> 
>   Note: Replace /path/to/your/zen/ with your actual Zen installation directory (e.g., /opt/zen/ for system installs or the AppImage mount
>   path).
