### ISSUE TITLE
Linux Installer Choice Order

### ISSUE THREAD

**Issue by Heinrich-XIAO** [zen-browser/desktop#2389]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The Installer lists the options in the wrng order.
```
[i] (★^O^★) What would you like to do?
[i]   1) Install
[i]   2) Uninstall
[i]   0) Exit
Enter your choice (0-3): theuser'schoice
```

I'd expect it 0, 1, then 2.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

The one from https://updates.zen-browser.app/appimage.sh

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
[i] ╔════════════════════════════════════════════════════╗
[i] ║                                                    ║
[i] ║    (ﾉ◕ヮ◕)ﾉ*:･ﾟ✧  Zen Browser Installer            ║
[i] ║                                                    ║
[i] ║    CPU: AVX2 Not Supported (Generic Version)       ║
[i] ║    Status: Zen Browser Not Installed               ║
[i] ║    zsync: Not Installed (Needed for Updates)       ║
[i] ║                                                    ║
[i] ╚════════════════════════════════════════════════════╝
[i]
[i] (★^O^★) What would you like to do?
[i]   1) Install
[i]   2) Uninstall
[i]   0) Exit
Enter your choice (0-3): 1
```

**Comment by RayZ3R0** [comment]
That's.. not really a valid issue. Here's the reasoning behind 0 being Exit

- 0 is typically on the right of the keyboard, making it easily accessible
- In programming, 0 often represents termination or null
- Leaves 1-9 for primary actions
- Historical precedent from early computing systems

**Comment by Heinrich-XIAO** [comment]
but it still doesn't go from 0 to 3

**Comment by RayZ3R0** [comment]
It doesn't really need to, on your keyboard 0 is at the last. Closing this issue as this is not planned or needed
