### ISSUE TITLE
Pin issue 

### ISSUE THREAD

**Issue by TrapNouz** [zen-browser/desktop#2390]
### Captchas

- [X] I have read the instructions.
- [ ] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

sometime when i restart my browser the pins i saved just gone and i have to research all my pins again.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1

### What platform are you seeing the problem on?

Windows

**Comment by mr-cheffy** [comment]
Pinned tabs dont follow you every window. If you make a new window and close the original one, it will delete all tabs inside that one

**Comment by TrapNouz** [comment]
I didn't create a new window
