### ISSUE TITLE
Header editor addons can't use~

### ISSUE THREAD

**Issue by QQueng** [zen-browser/desktop#2396]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When use header eitor，The manager interface does not display anything

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

a14

### What platform are you seeing the problem on?

Windows

**Comment by shadowash8** [comment]
Hi @QQueng,

Thanks for reporting this! To help us investigate further, could you please provide some additional details:
1. Header Editor Add-On Details: Which header editor add-on(s) are you using? If possible, please include the version.
2. Logs: If there are any logs or console errors, could you attach those here? This could give us more insights into the issue.

These details will be helpful in identifying the cause. Thanks!

**Comment by QQueng** [comment]
no console errors，you can see add-ons detail in screenshot~ 
![PixPin_2024-10-30_18-33-42](https://github.com/user-attachments/assets/0aee5fa4-aacd-4853-a500-0bdd7cf8db0b)
![PixPin_2024-10-30_18-35-13](https://github.com/user-attachments/assets/fefdf81e-9272-47eb-94c2-aebd256379af)

**Comment by shadowash8** [comment]
Did you try using this extension on firefox?

**Comment by QQueng** [comment]
yeah，It works in all versions of Firefox and Zenbrowser 1.0.1a-7
