### ISSUE TITLE
Tab Unloader has impropper option name

### ISSUE THREAD

**Issue by DevSnyco** [zen-browser/desktop#2398]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

After updating to the latest version, I discovered a bug where the name does not show up properly for Tab Unloader.
<img width="575" alt="SCR-20241029-nntq" src="https://github.com/user-attachments/assets/6959e501-b281-451f-a62d-a481647efc40">

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.14

### What platform are you seeing the problem on?

macOS - Intel

**Comment by mr-cheffy** [comment]
Thanks! I dont know why, someone changed them...
