### ISSUE TITLE
Gradient texture disappears with the "hover floating-sidebar"

### ISSUE THREAD

**Issue by zewenn** [zen-browser/desktop#2401]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The new textured gradients recolour the floating sidebar (the one which appears on hover in compact mode: both) but it fails to apply the texture.
<img width="1566" alt="Screenshot 2024-10-29 at 10 12 35" src="https://github.com/user-attachments/assets/b998d2c3-d508-4515-bc3a-5f3347eb5cae">
*Here the texture is not applied*
<img width="1566" alt="Screenshot 2024-10-29 at 10 12 43" src="https://github.com/user-attachments/assets/838dedc6-8e45-45f8-be49-6e15b166dd32">
*Here it is*

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-t.13

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by neurokitti** [comment]
I tried this in the most recent twilight version and it works so the fix should come to the main app soon
