### ISSUE TITLE
Zen Mods randomly deactivates

### ISSUE THREAD

**Issue by zenless911** [zen-browser/desktop#2402]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

All my Mods just disappeared randomly. When I tried to reinstall one of them, all of them reappeared again. And when I tried only disabling (not uninstalling) one of them, it all disappears again.

https://github.com/user-attachments/assets/fca93a9a-9e8c-45d2-b7d5-a10ff92d0888

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Version 1.0.1-a.14 (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by RayZ3R0** [comment]
Can you try this in a new profile and see if it still persists

**Comment by StrongSand94191** [comment]
i am also experiencing this problem on 1.01-a.14 flatpak on NixOS wayland

**Comment by anatasiajp** [comment]
Can you name all your installed mods, I bilieve one broken mod caused this.

**Comment by zenless911** [comment]
> Can you name all your installed mods, I bilieve one broken mod caused this.

It's literally on the clip lol.
- Disable Rounded Corners v2.0.0
- Disable Status Bar v1.0.0
- No Sidebar Scrollbar v1.0.2
- Remove Browser Padding v1.0.2
- Floating History v1.0.0
- Floating URLbar v1.0.5
- Midnight (theme) v1.0.0

This happens on one of any mods I deactivate. Aside from that, I mainly report this because this happened randomly. I just happen to figure out that I just need to reinstall one mod to temporarily fix it and recreate the problem with just turning one mod on and off.

**Comment by UsuallySleebee** [comment]
Experiencing similar behavior. Tried with fresh profile on Linux and Windows with same outcome. 

Mod being used is the [Catppuccin theme](https://zen-browser.app/mods/e3eec307-7c64-4cbd-a0c5-3447cd45a840) Haven't figured out what triggers it but the only way to get the theme back is to switch out of dark mode and back into dark mode again on Firefox builtin theme settings.

**Zen Version:** 1.0.1-a.17

**Comment by salamijason** [comment]
Hey are you guys still getting the issue on ver a22? Would like to add that there were a couple mods a while back that were coded incorrectly and ended up screwing with the rest of the installed mods.

**Comment by salamijason** [comment]
No response in 2 weeks, will be closing this issue. Please reopen if you still get the bug.
