### ISSUE TITLE
Sidebar long and cannot be back to what it is

### ISSUE THREAD

**Issue by omrih4** [zen-browser/desktop#2403]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![image](https://github.com/user-attachments/assets/74d1ef75-83b0-48c4-97ab-1be44bdbe9e5)
The sidebar is suddenly like this, instead of being short with only icons and no tab names with no way to change it back

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.14

### What platform are you seeing the problem on?

Windows

**Comment by n7itro** [comment]
1. Right click the tab sidebar
2. Click `Customize Toolbar...`
3. Drag the `Expand Sidebar` button back to the sidebar
**=>** You can use this button to collapse the sidebar.

Alternatively, select `Don't Expand Tabs by Default` in the Look and Feel settings page. (`about:preferences#zenLooks`)
