### ISSUE TITLE
chmod issue while installing

### ISSUE THREAD

**Issue by RaphaelRibes** [zen-browser/desktop#2404]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Hello !

I'm trying to install Zen Browser on linux with this command `bash <(curl https://updates.zen-browser.app/appimage.sh)`. And it gives me the log output below. What did I do wrong ?

It worked when I installed it on my first laptop, I just changed to a newer one and now it's not working.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

latest

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
$ bash <(curl https://updates.zen-browser.app/appimage.sh)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 12497  100 12497    0     0   8839      0  0:00:01  0:00:01 --:--:--  8838
[i] ╔════════════════════════════════════════════════════╗
[i] ║                                                    ║
[i] ║    (ﾉ◕ヮ◕)ﾉ*:･ﾟ✧  Zen Browser Installer            ║
[i] ║                                                    ║
[i] ║    CPU: AVX2 Supported (Optimized Version)         ║
[i] ║    Status: Zen Browser Not Installed               ║
[i] ║    zsync: Installed (Needed for Updates)           ║
[i] ║                                                    ║
[i] ╚════════════════════════════════════════════════════╝
[i] 
[i] (★^O^★) What would you like to do?
[i]   1) Install
[i]   2) Uninstall
[i]   3) Check for Updates
[i]   0) Exit
Enter your choice (0-3): 1
[i] 
[w] Auto dedecting AVX2 support...
[w] Downloading Zen from https://github.com/zen-browser/desktop/releases/latest/download/zen-specific.AppImage
[i] 
[i] Installing Zen Browser...
######################################################################### 100.0%
[i] Install completed successfully!
chmod: cannot access '/tmp/ZenBrowser.AppImage': No such file or directory
```

**Comment by RayZ3R0** [comment]
Which Linux distribution is this on?

**Comment by RaphaelRibes** [comment]
Sorry I completely forgot, Ubuntu 24.04.1 LTS

**Comment by RaphaelRibes** [comment]
> Hey @RaphaelRibes 👋, I'm here to help you with any bugs, questions, or contributions you have. Let's tackle this issue together!
> 
> It seems like the installation script is trying to change the permissions of a file at `/tmp/ZenBrowser.AppImage`, but it cannot find the file at that location. This could be due to the file being downloaded to a different directory or not being downloaded at all.
> 
> Here are a few steps you can try to troubleshoot and resolve this issue:
> 
>     1. **Check the Download Location**: Ensure that the AppImage is being downloaded to the expected location. You can manually check the `/tmp` directory to see if the file is there.
> 
>     2. **Permissions**: Make sure you have the necessary permissions to write to the `/tmp` directory. You can try running the installation script with `sudo` to see if it resolves any permission issues.
> 
>     3. **Script Debugging**: If possible, modify the script to print out the actual path where the AppImage is being downloaded. This can help verify if the file is being placed in a different location.
> 
>     4. **Manual Download**: As a workaround, you can manually download the AppImage from the provided URL and place it in the `/tmp` directory, then run `chmod +x /tmp/ZenBrowser.AppImage` to set the executable permission.
> 
> 
> If these steps do not resolve the issue, it might be helpful to check if there are any similar issues reported or if there are updates to the installation script that address this problem.
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

I'm gonan try this first I

**Comment by RayZ3R0** [comment]
> Sorry I completely forgot, Ubuntu 24.04.1 LTS

You can try installing with this [https://pacstall.dev/](https://pacstall.dev/)

After you are done installing pacstall, do `pacstall -I zen-browser-specific-bin`

This will install the optimized version of Zen. it might be slightly slower in getting updates sometimes but its really good since flatpak has the generic version only.

**Comment by RaphaelRibes** [comment]
So Now, I'm pretty sure it's `chmod +x "${appimage_path}"` that doesn't work because there is nothing in /tmp. However, the url makes me download `zen-generic.AppImage` and not `ZenBrowser.AppImage` and in any cases, I have nothing in my /tmp xD.
Furthermore, I tried putting sudo before, and now it says `bash: /dev/fd/63: No such file or directory`...

I'm really confused... but thx @RayZ3R0 what you said worked so I'm fine with it XDDDD
