### ISSUE TITLE
cannot setup zen

### ISSUE THREAD

**Issue by Turhvjbufv** [zen-browser/desktop#241]
### What happened?

downloaded zen from website(performance one)(checked, even the compatible has the same problem), gets stuck on this screen
![image](https://github.com/user-attachments/assets/27d9c8a3-1b2f-4d1d-b61f-9992cf6d6155)
Pressing on the next button does nothing

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

idk, last current website version

### Severity impact

Critical

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
Yep, I do need to fix this but in the meantime, you can click on "esc" and set `zen.welcomeScreen.seen` to `true`. This happens because you added more search engines in the previous installation but ill fix it

**Comment by eagerestwolf** [comment]
I also had a similar problem with the setup. I have a DQHD monitor (5120x1440). Zen defaulted to maximized, and the buttons wouldn't work. I had to resize the window to make it smaller to get things to work. There seems to be an issue if the buttons aren't in the expected places.

**Comment by mauro-balades** [comment]
Could you send a screenshot?

**Comment by eagerestwolf** [comment]
Sure. The screenshot of the first step is just for reference on positioning. The next 2 are on the second step, I can't click the next button to continue. Sorry, they're big, but I have a big monitor.

![Screenshot from 2024-08-17 07-52-31](https://github.com/user-attachments/assets/abe3fdde-478b-4b11-8683-ab5616264818)
![Screenshot from 2024-08-17 07-52-56](https://github.com/user-attachments/assets/8b707bbd-3958-44a9-8c37-85564d367e70)
![Screenshot from 2024-08-17 07-54-11](https://github.com/user-attachments/assets/392713b2-6eb7-45d6-8d7b-f6b580fd2c10)

**Comment by mauro-balades** [comment]
This shoud've had been fixed a while ago
