### ISSUE TITLE
Issue with multiple tabs being highlited with ctrl + click

### ISSUE THREAD

**Issue by neurokitti** [zen-browser/desktop#2410]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

https://github.com/user-attachments/assets/afa17055-3f82-442f-bf5c-240be78bc089

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-14t

### What platform are you seeing the problem on?

Windows

**Comment by RayZ3R0** [comment]
Does this issue persist on other profiles? And does this always happen?

**Comment by neurokitti** [comment]
> Does this issue persist on other profiles? And does this always happen?

yes

**Comment by RayZ3R0** [comment]
Hmm that's odd, ctrl + click always only highlights the tab I clicked

**Comment by salamijason** [comment]
Ctrl + click always highlighted only the tabs that I clicked on too.

User has not replied in a couple weeks. Closing the issue now. Please reopen if issue persists.
