### ISSUE TITLE
Updates resets some settings to default

### ISSUE THREAD

**Issue by rbjnazz** [zen-browser/desktop#2412]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

e.g. keyboard shortcuts

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.14

### What platform are you seeing the problem on?

Windows

**Comment by mr-cheffy** [comment]
This was meerly a once time issue since shortcuts got a new system no, sorry. Please reopen if it keeps happening.
