### ISSUE TITLE
Workspace icon jumps in sidebar if not in strip mode

### ISSUE THREAD

**Issue by enoversum** [zen-browser/desktop#2413]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When workspaces are enabled and not shown as a strip, the icon jumps whenever the mouse is on the vertical tab bar, and the other workspaces are not accessible.

https://github.com/user-attachments/assets/d8824385-00af-4975-a06b-100a7e043954

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.14

### What platform are you seeing the problem on?

Windows

**Comment by RayZ3R0** [comment]
Can you try this in a new profile and see if it still happens?

**Comment by enoversum** [comment]
> Can you try this in a new profile and see if it still happens?

I could, and it does all the same. On my main profile, on a secondary one, and even on a new one with just one workspace.

**Comment by RayZ3R0** [comment]
Hmm, that's certainly odd then. We'll look into it

**Comment by enoversum** [comment]
Thanks, @RayZ3R0 ! Had this on two different computers (albeit with the same profile synced).

**Comment by mr-cheffy** [comment]
This has been fixed for the next release, thanks a lot!
