### ISSUE TITLE
Web Panel shows over tabs (not resizing the tab dynamically)

### ISSUE THREAD

**Issue by rbjnazz** [zen-browser/desktop#2414]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![zen](https://github.com/user-attachments/assets/d8788393-ee3e-4f2a-9457-180a9cf0d222)
web panel overlays on a tab google.com should be full see picture above

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.14

### What platform are you seeing the problem on?

Windows

**Comment by RayZ3R0** [comment]
That is the intended behaviour for now. Web panels will be improved soon so stay tuned. This is a not a bug, so closing
