### ISSUE TITLE
Ctrl + clik doesn't open link in new tab but previews it in current tab

### ISSUE THREAD

**Issue by hurricaane** [zen-browser/desktop#2415]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When opening link in new tab with ctrl + click, it opens the link in a modal inside the current tab

[Screencast from 2024-10-30 10-37-00.webm](https://github.com/user-attachments/assets/2fc2597c-ea48-41bd-b73e-2b91bc5bb985)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-t.14

### What platform are you seeing the problem on?

Linux

**Comment by hurricaane** [comment]
@dosu I can't find the setting related to "Zen Glance"

**Comment by hurricaane** [comment]
![Screenshot from 2024-10-30 11-12-19](https://github.com/user-attachments/assets/4d2b880c-abec-4a6f-8ae6-acdcecfe5c78)

Here is a picture of my `about:preferences` page. 
I installed zen twilight with the AppImage installer

**Comment by ashwinjadhav818** [comment]
The settings the bot mentioned can be found in `about:config` search it there.

**Comment by RayZ3R0** [comment]
> When opening link in new tab with ctrl + click, it opens the link in a modal inside the current tab
> Screencast.from.2024-10-30.10-37-00.webm

Please update your Zen Twilight, there is a new version. In settings, you can find an option to disable Glance. Do that and you can return it to normal. Alternatively, you can set zen glance to the other options like Alt + Click and ctrl + click will open in a new tab normally. Please reopen if you still need help.
