### ISSUE TITLE
add brave search engine to the mix

### ISSUE THREAD

**Issue by Turhvjbufv** [zen-browser/desktop#242]
### What feature would you like to see?

an option to have brave search in the setup screen

### What platform are you seeing the problem on?

Windows

**Comment by KjalaNIX** [comment]
I second this. Brave Search is good for a daily driver.

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/874

 ~ This is an automatic operation to better enhancements requests organization.
