### ISSUE TITLE
Black splash screen suddenly 

### ISSUE THREAD

**Issue by kiran-4444** [zen-browser/desktop#2420]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

PS: I'm enjoying this Zen browser and coming from Arc, this browser enabled me to sync between all my devices. But suddenly I'm getting this black splash screen. I even tried reinstalling but no luck.

![image](https://github.com/user-attachments/assets/cac4013e-2603-482c-91dd-fe5aa79eab93)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by salamijason** [comment]
Hi do you still get this issue on the latest version? (a.18 as of this comment)

**Comment by kiran-4444** [comment]
Yes, I just downloaded it and still no improvement.

**Comment by salamijason** [comment]
Looks like you'll need a new profile fix. Please follow the instructions on this [page](https://docs.zen-browser.app/guides/manage-profiles) and let me know if that resolves the issue.

**Comment by salamijason** [comment]
User has not replied in a couple weeks. Closing the issue now. Please reopen if issue persists.
