### ISSUE TITLE
Sidebar/Web Panel don't resize

### ISSUE THREAD

**Issue by tedbergstrand** [zen-browser/desktop#2427]
### Captchas

- [x] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.

### What happened?

After the recent update, the sidebar/web panel won't resize horizontally.

I tested this against the old version by uninstalling Zen Browser and reinstalling the old version. The sidebar resizes as expected. Then, I auto-updated and the sidebar resizing broke again.

Steps to reproduce:

Open Web Panel (Alt+P)
Try to Resize
Fail

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.14

### What platform are you seeing the problem on?

Windows

**Comment by RayZ3R0** [comment]
@tedbergstrand for resizing the webpanel you need to pin the web panel first. look at the top right of the web panel, there will be a pin icon (sometimes its a minimize icon, idk why), click that and you can resize then unpin

**Comment by tedbergstrand** [comment]
> @tedbergstrand for resizing the webpanel you need to pin the web panel first. look at the top right of the web panel, there will be a pin icon (sometimes its a minimize icon, idk why), click that and you can resize then unpin

Good to know, thanks. So that's a bug, right? The software shouldn't force an extra user action to allow resizing.  The Web Panel is the killer feature to me and this is a bad change.

There's already a global setting to make the unpinned Web Panel auto-hide when it loses focus. In my opinion, that's what the pin should affect. It should have no effect on whether or not I can resize my panel. In fact, I'd think that pinning something would prevent resizing, not the other way around.

**Comment by RayZ3R0** [comment]
Im not sure if its intended, but this is how it works for now. I think the web panel will be revamped by the devs so hopefully the experience with this will be better. Will be closing this issue then, thanks!

**Comment by tedbergstrand** [comment]
In case anyone else finds this problematic, I've found version 1.0.1-a.12 to be the best place to roll back to.

**Comment by Vistaus** [comment]
I too can't resize the web panel, though I am on Linux.

**Comment by RayZ3R0** [comment]
> I too can't resize the web panel, though I am on Linux.

Did you check my comment above? You have to use this for now
![image](https://github.com/user-attachments/assets/40e942bc-b09a-440a-b041-268ae1a1822d)

**Comment by Vistaus** [comment]
Yes, I have done that, but it still doesn't allow me to resize.

**Comment by Vistaus** [comment]
Solved it with the workaround in this comment: https://github.com/zen-browser/desktop/discussions/852#discussioncomment-10840960
