### ISSUE TITLE
Zen Glance (all bugs i found in my testing on twilight)

### ISSUE THREAD

**Issue by neurokitti** [zen-browser/desktop#2429]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

first main issue:
when swaping the triger method for glance it only takes effect in a tab after reload. this goes for both pinned and unpinned tabs.

https://github.com/user-attachments/assets/fa1466b3-9cf7-4720-9036-e0f7ae5b054c

in this vid i try using shift click and it does not work until tab is reloaded

second main issue:
Maintain click will drag links

https://github.com/user-attachments/assets/f20b8a99-4fb9-4be0-b994-139422452426

essentialy because you can drag links in some cases it will still be draged by your mouse after glance is opened and if you release the click it just essentialy draged the tab onto the curent page wich replaced the curent pages link

third main issue:
the meta triger option does not work on windows as the meta key is the windows key. there is nothing that can be done about this so i would seggest adding somthing that disables that option only on windows OS or maybe warns the user.

![image](https://github.com/user-attachments/assets/503835d2-4f67-41a1-9b85-9cc92ee08526)

(this is just so you dont get this issue sent like 12 times cuz people think its broken lol)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-t14

### What platform are you seeing the problem on?

Windows

**Comment by neurokitti** [comment]
https://github.com/user-attachments/assets/10e53220-2fb0-4bee-9d36-9d895bcd00ce

zen glance closes when you swap tabs. not saying this is a bug but it would be nice if it whould stay open

**Comment by RayZ3R0** [comment]
Alright, thanks for reporting!
