### ISSUE TITLE
"Zen Browser" is damaged and can't be opened

### ISSUE THREAD

**Issue by vingle** [zen-browser/desktop#243]
### What happened?

I downloaded the macos-aarch64.dmg from the site, opened, added to Applications, and got the below error:

<img width="248" alt="image" src="https://github.com/user-attachments/assets/efec591f-7373-4795-912e-135321062dfb">

Repeated the full process just in case there was an issue with the download. On OS 13.6.7, 2023 Mac M2.

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.18

### Severity impact

High

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by mauro-balades** [comment]
https://github.com/zen-browser/desktop/issues/53
