### ISSUE TITLE
new tab under tabs in tab bar even with setting off

### ISSUE THREAD

**Issue by neurokitti** [zen-browser/desktop#2432]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![image](https://github.com/user-attachments/assets/51cb0f37-a8ba-4eec-9368-87dc904dcd38)

i think this issue is recent but ive tried to get rid of the new tab under tabs in sidebar but it does not go away. 

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-14t

### What platform are you seeing the problem on?

Windows

**Comment by sprutxz** [comment]
Experiencing this issue too after the update. Kinda annoying since i like it turned off

**Comment by salamijason** [comment]
i get this too

https://github.com/user-attachments/assets/5161ade1-5396-4353-82d2-0274df2cc236

**Comment by salamijason** [comment]
latest twilight build as of this comment t16 doesn't seem to have this issue though so i assume it will be fixed.

**Comment by salamijason** [comment]
apparently still an issue in a16
