### ISSUE TITLE
Glance opens across multiple Zen Browser windows instead of active window

### ISSUE THREAD

**Issue by jpumfrey** [zen-browser/desktop#2433]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

# Issue Summary  
Glance preview opens in the first Zen Browser window instance instead of on the same screen where `Ctrl + Click` is triggered.

## Description  
The new glance feature generally works well. However, when using Zen Browser across multiple monitors, triggering glance (`Ctrl + Click`) on a secondary screen opens the preview in the first Zen Browser window instance, regardless of which monitor the action was initiated on. This means if the first Zen Browser window is minimized or on a different monitor, the preview is either hidden or shown in an unexpected location. The expected behavior would be for glance to open in the same window where `Ctrl + Click` was triggered.

## Steps to Reproduce
1. Open two Zen Browser windows on separate monitors.
2. Minimize the first Zen Browser window (or place it on a different monitor).
3. Use `Ctrl + Click` on a link in the second Zen Browser window.

## Observed Behavior  
Glance opens the preview in the first Zen Browser window instance, even if it’s minimized or located on another monitor.

## Expected Behavior  
Preview should open in the same Zen Browser window on the same monitor where `Ctrl + Click` is triggered, regardless of which instance is opened first.

## Screenshot  
![2024-10-31 11_00_30-Issues · zen-browser_desktop — Zen Browser](https://github.com/user-attachments/assets/68cfa91f-2d8f-4c3a-a532-71bdfb8aca47)

## Update 1 -  31/10/2024

The issue persists even after restarting Zen Browser. Additionally, the glance preview now opens on *both screens* when triggered on a secondary monitor. Closing the preview requires closing it individually on both instances. Expanding the preview works correctly, returning to the parent window.

## Update 2 - 31/10/2024

The issue affects all open Zen Browser windows. When glance is triggered with `Ctrl + Click`, the preview opens in *all* Zen Browser window instances, not just the active window where the action was initiated. This requires individually closing the preview in each instance. Expanding the preview works correctly, returning to the parent window.

![2024-10-31 11_31_44-Issues · zen-browser_desktop — Zen Browser](https://github.com/user-attachments/assets/37d9b55f-8e72-4e0c-9f87-4a523c1af7f2)

Note: I only opened multiple windows as a demonstration for the screenshot - I do in fact love using split views which is one of my favorite features.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.15

### What platform are you seeing the problem on?

Windows

**Comment by juampivallejo** [comment]
I can confirm this also happens on Linux (flatpak) on 1.0.1-a.16

**Comment by neogeographica** [comment]
Yeah, my experience on Linux (appimage) is that the glance popup appears on all windows (and has to be explicitly closed on each).

**Comment by ZARAEM** [comment]
> Yeah, my experience on Linux (appimage) is that the glance popup appears on all windows (and has to be explicitly closed on each).

Same experience on Windows, opens on every Zen Browser window

**Comment by Axenide** [comment]
Same from AUR.

**Comment by jpumfrey** [comment]
Version 1.0.1-a.17 resolves this issue, and more. 

The new method also fixes the issue using find (Ctrl + F) in the glance preview where it previously would appear on the window behind.
