### ISSUE TITLE
When the bookmark toolbar is displayed, it extends beyond the screen area 

### ISSUE THREAD

**Issue by array** [zen-browser/desktop#2434]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When the bookmark toolbar is displayed, it extends beyond the screen area and the entire Zen Browser comes out of the screen area.
And the bookmark toolbar will no longer be displayed, but the size of Zen Browser will not change, so you will not be able to press the close button, etc.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a15

### What platform are you seeing the problem on?

Windows

**Comment by sigilpunk** [comment]
I am also experiencing this issue. The toolbar acts as expected while in compact mode. Otherwise, the toolbar extends past the right side of the screen.
![image](https://github.com/user-attachments/assets/3d497ab7-df7b-4e29-8015-2d3343fff9d4)

**Comment by liamreed** [comment]
same problem, makes the browser unusable

**Comment by RayZ3R0** [comment]
Can you show a screenshot? or even better, a screen recording

**Comment by array** [comment]
![image](https://github.com/user-attachments/assets/4e7dee65-5f00-4103-a07d-478682ca5330)
Bookmark toolbar can't display.Right Click Menu hasn't Bookmark Toolbar section.

**Comment by array** [comment]
I have attached a screenshot of Zen Browser 1.0.1-a.16 with the bookmark toolbar displayed.
I did not take it halfway through, but the entire screen area.
![image](https://github.com/user-attachments/assets/285491c5-d076-4c27-9765-ce5c06076303)

**Comment by Swidilator** [comment]
To add to what others are saying, for me if I extend the window further onto my second monitor I make it wide enough to encompass my entire bookmarks bar, and the browser starts to look normal again. After that I can even resize the tab bar again, something that can't be done when the window is too small.
![image](https://github.com/user-attachments/assets/9f7e6f40-a9af-4459-972f-c246475eeab4)
![image](https://github.com/user-attachments/assets/82aa1297-abe3-4467-94f3-974bca4c9958)

**Comment by RebelFire** [comment]
https://github.com/user-attachments/assets/67ce113d-30a5-481b-9558-805a625b9572

Resolution: 2560x1440(32") but it happens on 1920x1080(32") monitor too. 
Version: 1.0.1-a.16 (Firefox 132.0) (64-bit)
I don't think its relevant but i tried to show bookmarks from shortcut and from menu.

**Comment by JustMarkJr** [comment]
Unfortunately, I'm having this issue as well. :(

https://github.com/user-attachments/assets/fc6df423-c55d-4726-9afd-42d5448bd7c4
