### ISSUE TITLE
Gradient color picker : issues on linux

### ISSUE THREAD

**Issue by wysh3** [zen-browser/desktop#2435]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

the color picker in the gradient is laggy and it doesn't even work in the latest update on linux

https://github.com/user-attachments/assets/dda97439-2504-4eba-84c1-998ff03ed89a

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.15

### What platform are you seeing the problem on?

Linux

**Comment by RayZ3R0** [comment]
Tried it, have the same issue on Linux Mint
