### ISSUE TITLE
Unloaded tabs can't be opened

### ISSUE THREAD

**Issue by DevSnyco** [zen-browser/desktop#2436]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

If a Tab is manually unloaded, it becomes unresponsive and cannot be opened.
https://github.com/user-attachments/assets/77447360-d1f2-4c9c-9074-b7526669d753

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-t.15 & 1.0.1-a.15

### What platform are you seeing the problem on?

Linux, macOS - Intel, Windows

**Comment by taroj1205** [comment]
For now, we can close the tab and reopen it (`ctrl+shift+t`) to get the tab back.
This issue is probably caused by updating firefox version from 131.0.3 to 132.0.

**Comment by wysh3** [comment]
it cannot be reopened if the tab gets unloaded automatically too

**Comment by kar731** [comment]
This can cause the browser to be softlocked. If you manually unload all tabs other then the currently loaded tab, and then close your currently loaded tab, you wont be able to use a lot of the browser until you restart.

**Comment by notquite28** [comment]
for now i have downgraded to the previous v14-2 and it works fine again.

**Comment by DevSnyco** [comment]
Bug remains in 1.0.1-t.16

**Comment by Davenchy** [comment]
I'm experiencing the same issue. After a while, the browser automatically unloads all tabs. As shown in the screenshot, no tabs are selected, all are unclickable, and the page is blank.

![zen--bug](https://github.com/user-attachments/assets/85c4a191-4ebc-488b-82ee-38d8906492a6)

**Comment by wysh3** [comment]
> I'm experiencing the same issue. After a while, the browser automatically unloads all tabs. As shown in the screenshot, no tabs are selected, all are unclickable, and the page is blank.
> 
> ![zen--bug](https://private-user-images.githubusercontent.com/19766186/381874711-85c4a191-4ebc-488b-82ee-38d8906492a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNjcxNjMsIm5iZiI6MTczMDM2Njg2MywicGF0aCI6Ii8xOTc2NjE4Ni8zODE4NzQ3MTEtODVjNGExOTEtNGViYy00ODhiLTgyZWUtMzhkODkwNjQ5MmE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDA5Mjc0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkNzdkNTQwNjhmYTc1ZGMzYzk4NjFhNDZkMjc0NTA3ODVjNTYxMDJkOTRjNmQ5YmJhNWNjZmM5YmUwMjYyZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wZbwkf0LokykMiDex2X6k7l5SgFWNuUwa-_c6lVGibo)

for now its better to turn off tab unloading and wait for the next update to fix it

**Comment by mr-cheffy** [comment]
Fixed for version 17, thanks!

**Comment by KingBain** [comment]
> Fixed for version 17, thanks!

is there a v17 release package to install ?

**Comment by KingBain** [comment]
noticed this is happening on 
1.0.1-a.15 (Firefox 132.0) (64-bit) too
