### ISSUE TITLE
Tabs inactive and unclickable after few minutes

### ISSUE THREAD

**Issue by dnyeldev** [zen-browser/desktop#2437]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The tabs that are opened for a few minutes are greyed out and unclickable (they just sit there). Even if I **right-click + Reload Tab**, they're still unclickable.
![image](https://github.com/user-attachments/assets/022a6d8c-44ff-4a9b-a14b-a1edfa0e9bba)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.15

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by dnyeldev** [comment]
> Hey @dnyeldev! I'm here to help you with any bugs, questions, or contributions. Let's tackle this issue together!
> 
> I found a similar closed issue regarding tab problems, which might be related to your situation. You can check out the [Tab issue](https://github.com/zen-browser/desktop/issues/1509) for more details [[1]](https://github.com/zen-browser/desktop/issues/1509).
> 
> Additionally, there have been recent changes in the codebase related to tab management and rendering that could affect tab interactivity. These changes include modifications to tab move animations, tab transition cleanup, and the handling of pinned tabs, which might be relevant to the issue you're experiencing [[2]](https://github.com/zen-browser/desktop/blob/dev/src/browser/components/tabbrowser/content/tabs-js.patch).
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

That issue is different

**Comment by maathimself** [comment]
I'm having this issue as well, wasn't happening on previous builds. Tabs go to sleep and won't wake, need to restart browser.

**Comment by kar731** [comment]
Duplicate of #2436

**Comment by salamijason** [comment]
Has been fixed in a18 which will be released soon (currently in testing)! Thank you!

https://github.com/zen-browser/desktop/issues/2459

**Comment by azinsharaf** [comment]
i have this issue in `a.19`.

**Comment by salamijason** [comment]
That's really weird. At this point, could you try a new profile? Instructions [here](moz-extension://34d6b09d-4c5f-40d8-bbdf-6c1a75a30655/index.html).
The bug shouldve been fixed a while back.
