### ISSUE TITLE
white flash when navigating

### ISSUE THREAD

**Issue by wysh3** [zen-browser/desktop#2438]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

there's a white flash of the buttons when clicked in the menus

https://github.com/user-attachments/assets/8f699ff9-0afd-452c-b81a-a9f87f6af7d9

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.15

### What platform are you seeing the problem on?

Linux

**Comment by DevSnyco** [comment]
Same issue here on macOS

**Comment by realSilasYang** [comment]
Same issue here on Windows 11

**Comment by DevSnyco** [comment]
Bug remains in `1.0.1-t.16`

**Comment by realSilasYang** [comment]
Bug remains in 1.0.1-a.17

**Comment by mr-cheffy** [comment]
This has been fixed for version 18! Thanks a lot!
