### ISSUE TITLE
weird padding issue on glance buttons

### ISSUE THREAD

**Issue by wysh3** [zen-browser/desktop#2442]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![image](https://github.com/user-attachments/assets/09005e03-6469-4d9f-8b99-25fb118bce04)

the buttons looks off centered 

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.15

### What platform are you seeing the problem on?

Windows

**Comment by RayZ3R0** [comment]
@wysh3 does this happen on a new profile?

**Comment by wysh3** [comment]
> @wysh3 does this happen on a new profile?

on windows yeah but not on linux

**Comment by RayZ3R0** [comment]
weird. Is this on a.16 too?
