### ISSUE TITLE
Glance opens the selected link across both regular and incognito sessions

### ISSUE THREAD

**Issue by wysh3** [zen-browser/desktop#2444]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

https://github.com/user-attachments/assets/f74835f3-fe32-4d34-8f4c-da1303418988

When you open Glance, it opens the selected link across both regular and private browsing session as well as a completely new window remaining persistent only on all Zen windows

the glance opened in private browsing session history gets recorded too

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.15

### What platform are you seeing the problem on?

Linux, Windows

**Comment by DannieBGoode** [comment]
it also happens if you have two instances of normal (not incognito) zen browser, when you do Glance in one, it also opens in the second one.

**Comment by BredMan0** [comment]
Same thing here.

https://github.com/user-attachments/assets/0df86b2f-efa2-4ace-8600-ce1d76ac9961
