### ISSUE TITLE
If not maximized, there are bugs in the ui display

### ISSUE THREAD

**Issue by wentlwr** [zen-browser/desktop#2445]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

If not maximized(such as Split screen),UI show bugs,Minimize, Maximize, and Close buttons are missing

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.15

### What platform are you seeing the problem on?

Windows

**Comment by wentlwr** [comment]
![PixPin_2024-10-31_13-23-49](https://github.com/user-attachments/assets/a0d80610-549c-47d2-b8ba-7e29d9aa2a9d)
![PixPin_2024-10-31_13-24-13](https://github.com/user-attachments/assets/d30051b4-4ed3-413d-85ed-15d2fda1ed55)
![PixPin_2024-10-31_13-25-00](https://github.com/user-attachments/assets/97e1f857-7d42-4331-8636-c4f65144bc09)

**Comment by GunGunGun** [comment]
I can reproduce this issue, but fixing UI isn't what I'm capable of. 

It looks like something related to Zen's added buttons from the left side and Zen's minimum width

**Comment by RayZ3R0** [comment]
Cannot reproduce this on linux, might be a windows-only bug

**Comment by GunGunGun** [comment]
Confirm, it's defo the issue of the width of Zen's Vertical Toolbar `#navigator-toolbox`, Zen doesn't use this size for Zen's minimum width

Removing the `#navigator-toolbox` fixed this issue, so we need to calculate `#navigator-toolbox`'s width, and add this to Zen's min-width.

![image](https://github.com/user-attachments/assets/bd1f02ab-2e6a-4bd5-8c75-7e7b375affef)

**Comment by mr-cheffy** [comment]
This is due to the bookmarks bar, I'm pushing the update, thanks!

**Comment by IdaEdz** [comment]
I can reproduce this on version 1.0.1-a.16 (Firefox 132.0) (64-bit) (Windows)...
Get a profile with a lot of bookmarks and fill up the whole row. The close button will always show after the last bookmark is shown.
Bookmarks need to trail-off if the window size is to low to show all of them.
