### ISSUE TITLE
Scroll bar is not at the end of screen.

### ISSUE THREAD

**Issue by komiljonov** [zen-browser/desktop#2446]
### Captchas

- [ ] I have read the instructions.
- [ ] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

usually i scroll pages to down faster with mouse itself.
In some browsers i need to move mouse to end of screen to right side. and click and move mouse to scroll.

But in zen (maybe even in firefox) i need to adjust my mouse to scroll bar to be srollable.

Maybe it's not important but many users use it brainless

![image](https://github.com/user-attachments/assets/c1166999-d21b-4e11-b176-c8979552760e)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.15

### What platform are you seeing the problem on?

Windows

**Comment by RayZ3R0** [comment]
Not really a bug but a suggestion. Moving to discussions. Also, this helps for people who have tabs on the right like me
