### ISSUE TITLE
sidebar can't be widen

### ISSUE THREAD

**Issue by wentlwr** [zen-browser/desktop#2447]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

sidebar can not be widen,so i can't close tab by close button,only by right-click-menu
![image](https://github.com/user-attachments/assets/f6b84882-44d1-4edc-a499-6b0592e5870a)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.15

### What platform are you seeing the problem on?

Windows

**Comment by shadowash8** [comment]
You can click the button on the top left of the screen as given below or press the keyboard shortcut `Alt + b`
![image](https://github.com/user-attachments/assets/b7144514-f7f1-4bc0-9ea3-18a522664961)

**Comment by salamijason** [comment]
As the user above mentioned, either use the toolbar button or the keybind: ![Image](https://github.com/user-attachments/assets/5ffa78c4-c0c7-4f64-9891-b8ff672c41b8)
