### ISSUE TITLE
Sound icon on tab looks weird.

### ISSUE THREAD

**Issue by bapungiri** [zen-browser/desktop#2448]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![image](https://github.com/user-attachments/assets/607b0113-6251-4f5f-b9bc-1a60b5ac133a)
Updated to 1.0.1-a.15 and the sound icon showing a video/audio is playing in the tab now looks like a black smeared spot. Muting functionality still works fine. I think this may have been because of over-correcting for lightness of that icon in previous releases. 

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.15

### What platform are you seeing the problem on?

Windows

**Comment by salamijason** [comment]
That's not how the default icon looks like. Might be a mod, please try disabling them and letting me know.

**Comment by conventoangelo** [comment]
![image](https://github.com/user-attachments/assets/6368e604-4845-462b-ac17-17fd55ca22aa)
![image](https://github.com/user-attachments/assets/2a786c84-b41b-48ce-83b1-b9b6c69f5399)

Can confirm this is still the case for light mode. Using Zen 1.0.1-a.19 on Windows 11. Zen Mods turned off and restarted Zen.

**Comment by amtoaer** [comment]
The same issue occurs on macOS using Zen 1.0.1-a.19 aarch64. It only happens if light or auto theme is enabled.

**Comment by salamijason** [comment]
Understood, will verify! Thanks for the info!

**Comment by salamijason** [comment]
Was able to recreate this on windows a.19. Thanks for the bug report!

![image](https://github.com/user-attachments/assets/d114e21b-971d-462d-8804-04051aa72d5c)
![image](https://github.com/user-attachments/assets/514ffe22-bba4-4d0b-95cf-dfdba5d3243b)

**Comment by conventoangelo** [comment]
I already know what's causing it. It is easily solvable by editing `userChrome.css` and changing the fill of the `tab-icon.overlay` to white. Will make a pull request sometime soon to fix this permanently (once I successfully build on Windows).
