### ISSUE TITLE
New Tab btn appears twice

### ISSUE THREAD

**Issue by ghost** [zen-browser/desktop#2449]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Hi there.

The thing is, after upgrading to 1.0.1-a.16, the "New Tab" btn appears under the last tab and at the bottom of the sidebar at the same time.

<img width="1466" alt="图片" src="https://github.com/user-attachments/assets/a3b1db42-a565-42f1-b97d-74e856bc3151">

It is just ... weird.

So is there any way to fix this? Thanks!

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.16

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by Davenchy** [comment]
The same problem besides the unclickable tabs after auto-unloading

![zen--bug](https://github.com/user-attachments/assets/b5d6c322-04e2-4540-8fe9-4c3d99c4804b)

**Comment by Renerick** [comment]
Why is there even need for this option? You can already click RMB > "Customize toolbar" and place this button wherever you want, above, below, in the corner etc, that's kinda huge customization feature of Firefox

**Comment by salamijason** [comment]
@chlorine3545 

Hi! One of the two buttons should be able to be dragged out using "Customize Toolbar"

The other button however, added when the toggle was added into the settings page, was stated to be fixed in a16 but I've seen some mixed responses. It's fixed for some people while it isn't for some others.

Could you quickly try it in a new profile and let me know if the issue persists? Thank you

**Comment by ghost** [comment]
Hi @salamijason , thanks for your reply.

Some good news for you: the toggle works well in a brand new profile. When I unchecked the checkbox, the New Tab btn under the last tab disappeared ;)

**Comment by salamijason** [comment]
@chlorine3545 

Awesome! Were you able to remove the other button as well?

**Comment by ghost** [comment]
> @chlorine3545
> 
> Awesome! Were you able to remove the other button as well?

Of course!

<img width="1466" alt="图片" src="https://github.com/user-attachments/assets/b6b0247c-ff2b-4061-b222-2d988992d3f7">
