### ISSUE TITLE
Error during install

### ISSUE THREAD

**Issue by Zoobdude** [zen-browser/desktop#245]
### What happened?

I am getting these two errors when trying to install the browser

<img width="334" alt="image" src="https://github.com/user-attachments/assets/d3235310-2146-4866-8c9f-c789e6b2824c">

<img width="338" alt="image" src="https://github.com/user-attachments/assets/c16e657f-e8c3-4305-a20f-e5de7be36a96">

I have tried re-installing

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.18

### Severity impact

High

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
Please checkout https://github.com/zen-browser/desktop/issues/73#issuecomment-2238017525
