### ISSUE TITLE
After changing the interface font, the password and security icon in the address bar are in the wrong position

### ISSUE THREAD

**Issue by lindongbin** [zen-browser/desktop#2452]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

the code in userChrome.css:
`* {
    font-family: "SL-Simplified" !important;
}`

![c4551d9a-5691-442d-a017-155a53067e9c](https://github.com/user-attachments/assets/84d072d9-d7a6-4c4c-9ce9-0d249be37fd9)

Any suggestions?

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.16

### What platform are you seeing the problem on?

Windows

**Comment by salamijason** [comment]
Are you still getting this as of the latest Zen version? (a22 as of this comment)

**Comment by lindongbin** [comment]
the same, this is the font:
[SL-Simplified-Regular.zip](https://github.com/user-attachments/files/18001185/SL-Simplified-Regular.zip)

maybe compact mode is a bit wrong
![QQ20241204-085607](https://github.com/user-attachments/assets/a1094c99-1438-4774-a925-f9e4ef14c6e6)

**Comment by lindongbin** [comment]
Cannot reproduce on beta version

**Comment by lindongbin** [comment]
![QQ_1733903264162](https://github.com/user-attachments/assets/5b2e356a-6487-4fa0-89e3-02bd0e4dea4d)

The password icon is still incorrect

**Comment by salamijason** [comment]
weird okay, will send it over to dev. thanks for the info!

**Comment by salamijason** [comment]
@lindongbin could you verify that this still occurs on 1.0.2-b.2? Thank you

**Comment by lindongbin** [comment]
The problem still exists.
I recreated a new configuration, created a new userchrome.css, with only one line of code: * { font-family: "SL-Simplified" !important; }.
In the custom toolbar, I selected compact (not supported). The password icon was obviously offset.
This is a Chinese font. The height of the address bar was stretched. 
![QQ20241215-165502](https://github.com/user-attachments/assets/113532dd-48fa-4a68-acd0-b1ff0c9babe1)

I changed to other Chinese fonts such as Songti, and the address bar was more compact.
![QQ20241215-165548](https://github.com/user-attachments/assets/b7d72fee-ab47-43d0-8a99-04274fcadb3e)

It seems to be caused by the height of the font.

**Comment by salamijason** [comment]
Strange, and you've checked if this also happens on firefox?

**Comment by lindongbin** [comment]
OK, it looks like official Firefox has this problem
![Screenshot_20241216-090532-499~2](https://github.com/user-attachments/assets/f9d18c8b-5a26-45ee-a9d7-566c94dbb332)
![Screenshot_20241216-090426-250](https://github.com/user-attachments/assets/24bc618d-d7ac-4392-98f4-e23bbfe1431a)
