### ISSUE TITLE
Default Ctrl+click glance trigger method conflicts with the default "open in a new tab" action shortcut

### ISSUE THREAD

**Issue by jmc-88** [zen-browser/desktop#2454]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

* **What happened:** glance works as advertised with Ctrl+click, but that is also bound to the "open in a new tab" action, so I get both the glance overlay _and_ a new tab opened.
* **What I expected to happen:** glance overlay shown, with no new tab opened.

Ideally, the glance trigger shouldn't *by default* conflict with existing shortcuts. Ctrl+click is a popular shortcut for opening links in a new tab.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.15

### What platform are you seeing the problem on?

Linux

**Comment by JSGRD22** [comment]
Could not reproduce on Linux, flatpak, a.15, glance works normally.

**Comment by urbanlutz** [comment]
Is there a way to remap the open in new tab shortcut?

**Comment by jmc-88** [comment]
> Is there a way to remap the open in new tab shortcut?

Not sure, but there is an option to remap the glance trigger, which is what I did as a workaround. But I'm talking about defaults here. :slightly_smiling_face: 

The ctrl+click shortcut for "Open Link in New Background Tab" is documented here: https://support.mozilla.org/en-US/kb/mouse-shortcuts-perform-common-tasks#w_links

> Could not reproduce on Linux, flatpak, a.15, glance works normally.

Did  you remap the glance trigger to something else, like Alt+click?

**Comment by chrboesch** [comment]
I confirm that the link will no longer appear in a new tab in the background after Ctrl+Click. And I get a couple of empty tabs.

**Comment by salamijason** [comment]
Just tested ctrl+clicking a tab with the keybind for glance set to ctrl and it works as it should (only the glance appears, no new tabs). Could you please verify if you're still getting this issue on a18?

**Comment by jmc-88** [comment]
Tried just now on 1.0.1-a.19: mapping glance to ctrl+click no longer results in the glance window _and_ a background tab being opened. (However, the point about this conflicting with the default "Open Link in New Background Tab" shortcut still stands.)

**Comment by salamijason** [comment]
Hmm yeah I agree that the glance keybind overwriting new tab by default isn't the best choice. Will ask dev about it.

**Comment by uncenter** [comment]
I like the glance feature but found it very frustrating ([as did this other user on Reddit, where I found the setting to change it](https://www.reddit.com/r/zen_browser/comments/1gphfjl/how_do_i_fix_the_ctrlclick_of_links_to_stop_being/)) that it interfered with my normal browser keybinds. I would suggest changing the default keybind for glance to Alt Click instead, which is how I have it bound now.
