### ISSUE TITLE
Glance animation is laggy, scrolling animation in Glance window is less smoother

### ISSUE THREAD

**Issue by seriaati** [zen-browser/desktop#2455]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Three issues I have noticed:
1. The opening and closing animation of Glance is laggy.
2. The windows expanding animation is laggy.
3. The scrolling animation in the Glance window is less smoother than it is in the main window. It feel like as if the frame rate is lower, but I can't back up this claim with any evidence.

Here are 2 videos that demonstrate the issues:
https://github.com/user-attachments/assets/7b38ac84-387c-48f8-a189-30cd5bb48931
https://github.com/user-attachments/assets/a382b671-77f7-4a6b-97fd-533ee82692e6

I'm comparing the smoothness of animations to the demonstration shown on the official website:
https://zen-browser.app/vids/glance.webm

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.16 (Firefox 132.0) (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by RayZ3R0** [comment]
Hmm, they felt like the same smoothness though? Couldn't really notice anything laggy other than the glance opening popup

**Comment by seriaati** [comment]
The scrolling part is probably a little bit difficult to see, but opening and closing the Glance window is noticeably laggy, you can even see the window opening in sort of slow motion; when expanding the Glance window, it kinda shakes the screen and is not as smooth as in the demo.
For got to mention that I am on Windows and the demo seems to be using a Mac.

**Comment by flexagoon** [comment]
@RayZ3R0 the opening animation is super jittery for me as well on Linux Flatpak

**Comment by seriaati** [comment]
This got significant improvements in the latest version (21), I could close this issue but I'm unsure if others still have issues.

**Comment by salamijason** [comment]
Hey, is it alright now on version a22?

**Comment by seriaati** [comment]
@flexagoon Glance animation is smooth for me on a22

**Comment by flexagoon** [comment]
> @flexagoon Glance animation is smooth for me on a22

It got better, but it's still noticeably jittery

**Comment by salamijason** [comment]
Alright, we'll wait until the next release to see if there's any improvement.

**Comment by salamijason** [comment]
How does it look on the latest beta? (b.2)

**Comment by seriaati** [comment]
Very smooth for me, seems like there were some more improvements.

**Comment by salamijason** [comment]
Cool, looks like we can close this issue now. Thank you for reporting!

**Comment by flexagoon** [comment]
@salamijason it actually got worse for me in b2 compared to a22

**Comment by salamijason** [comment]
@flexagoon oh weird, what platform are you on?

**Comment by flexagoon** [comment]
> @flexagoon oh weird, what platform are you on?

@salamijason I'm on Fedora Silverblue, Zen Browser installed through Flatpak
