### ISSUE TITLE
Cant find Color Picker anymore

### ISSUE THREAD

**Issue by Tokken749** [zen-browser/desktop#2456]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

In newest version, colorpicker (right click on taskbar) disappeared. 

![grafik](https://github.com/user-attachments/assets/785de215-fa6d-42cb-9011-bd2acaa981f2)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.16

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by RayZ3R0** [comment]
Can you try on a new profile or try reinstalling? Haven't seen this happen to anyone else

**Comment by Richard-Woessner** [comment]
Im on a M2 mac with 1.0.1-t.16 (Firefox 132.0) (2024-10-31) (aarch64) 

Its working for me, not sure what could cause this

**Comment by Richard-Woessner** [comment]
Can you enable workspaces and try again

<img width="1366" alt="image" src="https://github.com/user-attachments/assets/6c18cdf6-7021-4f25-801c-9e2fe8e277b8">

**Comment by Tokken749** [comment]
Thanks for your reply. Turning off workspace causes the missing color picker. After turning on color picker it back: 

<img width="1277" alt="Bildschirmfoto 2024-10-31 um 16 45 53" src="https://github.com/user-attachments/assets/26d2d54d-6870-4c27-9b5f-60302fa73fcd">

<img width="383" alt="Bildschirmfoto 2024-10-31 um 16 46 01" src="https://github.com/user-attachments/assets/6c9b2f1a-bae7-4a18-bbc9-2210ec9a2b9e">

**Comment by RayZ3R0** [comment]
Alright, will be closing this then since that's intended
