### ISSUE TITLE
Gradient color picker partly hidden

### ISSUE THREAD

**Issue by clementpoiret** [zen-browser/desktop#2457]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I am on Linux on a High-Res 16 inches screen. The color picker is partly hidden on the right.

![2024-10-31-At-09h55m43s](https://github.com/user-attachments/assets/f2437b35-41c4-4da4-b805-91f57a59b686)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.15

### What platform are you seeing the problem on?

Linux

**Comment by RayZ3R0** [comment]
I am also on linux, can't reproduce this. Can you try version a.16?

**Comment by clementpoiret** [comment]
Same thing on the latest a.16. Maybe a high-dpi issue?

**Comment by InterstellarOne** [comment]
I also have this issue on KDE Plasma Fedora 40. 
![Screenshot_20241031_214821](https://github.com/user-attachments/assets/c312ac90-0109-46ea-a37d-bd863cae01be)

I am using a 1920x1080 display.

**Comment by krisMG21** [comment]
I'm using zen in a 1366x768 res laptop. 
Actual version and the one when I used the color gradient a few days ago are working fine for me:

![Image](https://github.com/user-attachments/assets/803c67b9-9727-41f9-ba6c-306eda0c46f8)

OS: Windows 10

**Comment by sjclayton** [comment]
Issue present for me as well on a.17 on Linux.

**Comment by sjclayton** [comment]
Still an issue as of 1.0.1-t.20 on Linux... any hope for this being fixed??, as it makes using this mostly impossible, since if you assign custom colors there is no way to remove them.

**Comment by sjclayton** [comment]
Still present as of 1.0.2-t0... any response about this would be appreciated, thanks.

**Comment by clementpoiret** [comment]
As soon as the next version gets out, I'll try to check if I can patch it by myself and make a PR 👌

**Comment by clementpoiret** [comment]
I did not wait for the release, the fix was actually pretty simple :) 

EDIT:
In your `userChrome.css`, paste this CSS then restart Zen:

```css
#PanelUI-zen-gradient-generator .panel-viewcontainer,
#PanelUI-zen-gradient-generator .panel-viewstack {
  display: flex;
  flex-direction: column;
  width: 100%;
}
```

Can you please confirm it also fixes the issue for you?
