### ISSUE TITLE
Possibility to drag'n'drop links to the sidebar

### ISSUE THREAD

**Issue by Khnome** [zen-browser/desktop#246]
### What feature would you like to see?

Possibility to drag'n'drop links to Zen sidebar. It would extend sidebar functionality much more than the + icon on the bottom of it.
[Ekrano įrašas_20240813_200204.webm](https://github.com/user-attachments/assets/e8c7bd2b-0633-4d71-941c-7aec25750587)

### What platform are you seeing the problem on?

Linux

**Comment by MrAn0nym** [comment]
DnD to the tab list to open the link in a new tab would also be greatly appreciated :grin:

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/873

 ~ This is an automatic operation to better enhancements requests organization.
