### ISSUE TITLE
New update which I'm not sure what version (came out today) broke the browser

### ISSUE THREAD

**Issue by bigbanana80** [zen-browser/desktop#2460]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

After updating to the latest version (which it did automatically) the browser broke, and it's currently unusable, I'm not sure how to describe it but only 1/4 of any page loads and the settings page is completely broken.

![zen_5aAEcXoCcE](https://github.com/user-attachments/assets/41cdcb45-29b6-4463-b04d-7cdd28e8de68)

As you can see, even the windows buttons are gone. that's the browser and nothing appears or change when i maximize or minimize it or restart it.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

idk (latest, auto updated and i cant see the version since the browser is broken)

### What platform are you seeing the problem on?

Windows

**Comment by IdaEdz** [comment]
We can probably assume it is version 1.0.1-a.16.
It is related to the bookmarks.
If your bookmarks do not fill the entire length of the screen you will be able to see the close button.

**Comment by bigbanana80** [comment]
My bookmarks definitely do fill the entire length

**Comment by IdaEdz** [comment]
Exactly, try open a new profile with no bookmarks and you will see it working fine.
ofc this needs to be fixed.

(this is the second update today, I got a.15 just this morning and now a.16. Both with the same problem.)

**Comment by bigbanana80** [comment]
I can confirm you are right.
Hiding the bookmarks for now till it gets fixed.

**Comment by greeeen-dev** [comment]
I'm on 1.0.1-a.16, it looks like the issue only happens when the sidebar is expanded and compact mode is disabled

**Comment by 0skar2** [comment]
Not just that, but the ui elements seems to not resize correctly.

![zenmoment](https://github.com/user-attachments/assets/7edf8792-36f4-4881-83c5-9f7f6b1d5f48)

Notice the sidebar and lack of it's workspace/panel/add page buttons (that should be at the bottom), when resized to a small size.


And website contents dont resize correctly:

**Vanilla Firefox:**
![image](https://github.com/user-attachments/assets/057cb3b1-0a28-4617-815a-53777a43e3ca)

**Zen:**
![image](https://github.com/user-attachments/assets/c85c4ba0-9e68-488d-8297-9059f8455bbc)

browser version: 1.0.1-a.16
os: Fedora 41 KDE with kernel 6.11.5

**Comment by EmirLogas** [comment]
Same for me. This image is from the top right of the screen.
![image](https://github.com/user-attachments/assets/540f7f78-c45e-4900-be12-731012d26d71)

**Comment by kristoftorok** [comment]
Same issue here! :(

**Comment by bigbanana80** [comment]
After updating to version 1.0.1-a.17, i no longer have this issue.
