### ISSUE TITLE
Alt+Click Glance shortcut doesn't work occasionally 

### ISSUE THREAD

**Issue by ironcloudy** [zen-browser/desktop#2462]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Once switch shortcut to Alt+Click, Glance doesn't always work.

One way to reproduce the issue is to google search anything, Glance doesn't work on major site links, other links work.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.16

### What platform are you seeing the problem on?

Windows

**Comment by Venipa** [comment]
i think alt+click is already a set shortcut to download the link as a file.
ctrl+click should work better for now

**Comment by ironcloudy** [comment]
alt+click was originally set for opening link to a tab without going to the tab...it's useful in some occasions; would be nice to keep that as well.

**Comment by fanesz** [comment]
+1, I prefer the old ctrl+click, and zen glances on alt+click

**Comment by mr-cheffy** [comment]
![Image](https://github.com/user-attachments/assets/fd0ac2e6-2aac-4b11-bf08-21a8f0452de8)

You can change it here ^
