### ISSUE TITLE
Compact Mode Top Bar: Empty space between URL field and Reload button is not responsive to clicks

### ISSUE THREAD

**Issue by ironcloudy** [zen-browser/desktop#2463]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![Screenshot 2024-10-31 033609](https://github.com/user-attachments/assets/98909e8f-11ae-4ee5-866f-9b0c192f51df)
In Compact Mode, this space is not responsive to both single and double left mouse clicks.

While the empty space on the right does:
click hold+drag drags the window, double click to maximize or restored down window.
![Screenshot 2024-10-31 034351](https://github.com/user-attachments/assets/d655e08e-6a80-4ee6-81fd-7fe7db6e3bd7)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.16

### What platform are you seeing the problem on?

Windows

**Comment by salamijason** [comment]
Was able to reproduce on latest ver a.18 as well as t.18.

**Comment by LennartArnholdt** [comment]
same issue here. Although for me it sometimes works on the left side too. My top bar looks like this. 
![grafik](https://github.com/user-attachments/assets/2019baa8-55e5-4269-a009-f932d0956731)
It seems to be worse, when i make the browser windows more narrow, like half the screen size. Then its virtually impossible to drag the windows somewhere different or double click to fullscreen. My right side also works flawlessly

**Comment by LennartArnholdt** [comment]
still there

**Comment by syscat29** [comment]
Works just fine on 1.0.2-b.2 (Current release)

https://github.com/user-attachments/assets/15593a0b-b680-4555-8144-5cd1c6953e47

Please update to the latest release and report back if your issue persists

**Comment by mr-cheffy** [comment]
> Works just fine on 1.0.2-b.2 (Current release)
> Screen.Recording.2024-12-17.120902.mp4
> 
> Please update to the latest release and report back if your issue persists

@j14i Try doing dragging from the **first** separation, instead of the second, please. Because im not able to reproduce... I may be doing something wrong

**Comment by syscat29** [comment]
> > Works just fine on 1.0.2-b.2 (Current release)
> > Screen.Recording.2024-12-17.120902.mp4
> > Please update to the latest release and report back if your issue persists
> 
> @j14i Try doing dragging from the **first** separation, instead of the second, please. Because im not able to reproduce... I may be doing something wrong

https://github.com/user-attachments/assets/eb0921ca-f9ae-465b-a895-c9a89734db3c

**Comment by syscat29** [comment]
@ironcloudy Can we get an update on your issue? Does it persist in the current release (1.0.2-b.5)?

**Comment by ironcloudy** [comment]
@j14i 
Apology for the late reply. 
Yes, the new version has resolved the issue.

Thanks!
