### ISSUE TITLE
Missing reference to split view

### ISSUE THREAD

**Issue by mysticvortexscribe** [zen-browser/desktop#2466]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When I started Zen Browser the first time I was shown this message
<img width="825" alt="image" src="https://github.com/user-attachments/assets/b14b5308-e22b-4fb3-b214-6f5fdc87dbee">

but I cannot find anything about split views anywhere in the UI. That message really deserves at least a "...hit Cmd+Opt+G (Mac) or Ctrl+Alt+G (Windows/Linux)..."

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.16

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by salamijason** [comment]
Sending to discussions.
