### ISSUE TITLE
Icon not loading correctly on KDE after restarting system

### ISSUE THREAD

**Issue by brekker23** [zen-browser/desktop#247]
### What happened?

when restarting the system, I have my system set to reopen whatever was already open, and when it loads zen the icon for zen is the defualt icon for the wayland session. I am using the aur package and am on a.16. after closing zen and reopening it the icon is back to normal. Issue doesn't happen with any other apps for me

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

a.16

### Severity impact

Low

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
We do not manage the AUR version, sorry... but it should be fixed
