### ISSUE TITLE
Reddit translate button doesn't appear in zen-browser.

### ISSUE THREAD

**Issue by machadofguilherme** [zen-browser/desktop#2470]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The recently added translate language button on Reddit is not being displayed. In other browsers installed on my operating system the button is displayed normally.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.16 

### What platform are you seeing the problem on?

Linux

**Comment by Richard-Woessner** [comment]
Have you tried it on Firefox specifically or a chromium browser?

**Comment by machadofguilherme** [comment]
I tested it in Vivaldi and it works as expected.

**Comment by Richard-Woessner** [comment]
I cant see it on edge, and after reading about it, it seems like this is a rollout feature of reddit so its unrelated to Zen

**Comment by machadofguilherme** [comment]
On Zen:
![image](https://github.com/user-attachments/assets/9db56f94-ddaa-4e93-83bf-d4811c506de4)

On Vivaldi:
![image](https://github.com/user-attachments/assets/11db5105-64d8-4f71-881e-9b203765fb6b)

Wouldn't it be better to just take a look instead of turning your back?
