### ISSUE TITLE
New update made zen unstable on my pc

### ISSUE THREAD

**Issue by DasKing-SYSLOV** [zen-browser/desktop#2473]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Since the new update, every time I want to open a new tab, I have to do it two times, since it crashes the first time.

![Captura de pantalla 2024-10-31 091440](https://github.com/user-attachments/assets/0bec84a5-6a37-4c66-b0da-468950e3c85b)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.16

### What platform are you seeing the problem on?

Windows

**Comment by DasKing-SYSLOV** [comment]
I figured it out, for some reason, running zen in compatibility mode for Windows 8, and then running it back on Windows 10 mode did the trick.  I also disabled the workspaces, since I prefer doing everything at once, I don't know if this was the solution, but, one of these two things made it work properly.

**Comment by salamijason** [comment]
I don't think workspaces caused this issue. Most likely compatibility mode was screwing something up. Could you turn workspaces back on for just a moment and let me know if everything works okay?

**Comment by DasKing-SYSLOV** [comment]
Hey, sorry, been bussy with uni a lot.
Yeah, i tried, and workspaces work fine now, with a newer update, but running zen in compatibility mode for Windows 8, and then running it back on Windows 10 mode helped solve it that time.

**Comment by salamijason** [comment]
glad to hear it's fixed! Thank you for responding.
