### ISSUE TITLE
Pinned tabs can't be opened once you open them and close them all

### ISSUE THREAD

**Issue by stripedgoat** [zen-browser/desktop#2475]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When you open a pinned tab on a workspace (one or more), and you close them all, you can't open any pinned tab afterwards.

See the video below.

https://github.com/user-attachments/assets/029e49d2-aa23-48fe-b629-c6c953bc13ef

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

a.16

### What platform are you seeing the problem on?

macOS - Intel

**Comment by genesis224** [comment]
Same here whenever I close my browser unexpectedly or i restart my system. It wont open now afterwards.  even reload tab option doesnt work from the context menu.

**Comment by mr-cheffy** [comment]
This has been fixed in 17, please update. Thanks!
