### ISSUE TITLE
Autofill Addresses not working on some sites

### ISSUE THREAD

**Issue by ghost** [zen-browser/desktop#2478]
### Captchas

- [ ] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Autofill of addresses does not work on this webpage https://ocean.cognisantmd.com/intake/patients.html?linkRef=b370c3e3-01f1-42fe-ac43-f8861a4d3063#/online-booking.

Both Safari and Chrome will autofill addresses on the above webpage correctly.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.15 (Firefox 132.0) (aarch64)

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by salamijason** [comment]
Have you tried this on the latest version of the browser? a.18 as of this comment

**Comment by ghost** [comment]
The problem has not been resolved after the release of a.18

Cliff Gittens
Surrey, BC, Canada

**Comment by salamijason** [comment]
Do you have autofill issues with other sites as well? Or is it only this specific site? Could you also test it on Firefox? Since it's a pretty niche site, none of the issue handlers have accounts or details they can try logging in with.

**Comment by ghost** [comment]
I only have autofill issues with the doctor’s office mentioned in my
initial report.

I tested autofill in four browsers (Zen, Firefox, Safari, and Chrome) on
three websites: the doctor’s office
<https://ocean.cognisantmd.com/intake/patients.html?linkRef=b370c3e3-01f1-42fe-ac43-f8861a4d3063#/online-booking>,
my WordPress genealogy site <gittens.info>, and a test autofill site
<https://fill.dev/>.

Results:
- Doctor’s office: Autofill doesn’t work with Zen or Firefox.
- Genealogy site: Autofill works perfectly in all browsers.
- Test autofill site: Autofill works on most basic fields in all browsers.

Summary:
The only website with an autofill issue is the doctor’s office.  Maybe the
issue I reported is actually a problem with the Doctors Office website?

Thanks

Cliff Gittens
Surrey, BC, Canada

**Comment by salamijason** [comment]
Hmm yeah it looks like a Firefox issue actually since it worked on Chrome and Safari. Sorry about that! Zen devs build off of the original Firefox code so I'm not sure if they'll be able to help.
