### ISSUE TITLE
Misaligned Pin icon in Extensions menu

### ISSUE THREAD

**Issue by jimfr** [zen-browser/desktop#248]
### What happened?

Click on the three dots for an unpinned extension and the Pinned icon overlaps the text
<img width="360" alt="image" src="https://github.com/user-attachments/assets/abc88a99-f16e-48ab-bd85-868ed9dd4c75">

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

a.18

### Severity impact

Low

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by mauro-balades** [comment]
Duplicate of https://github.com/zen-browser/desktop/issues/177

**Comment by jimfr** [comment]
Still exists in a.28
