### ISSUE TITLE
Duplicate New Tab Buttons

### ISSUE THREAD

**Issue by artimanzero** [zen-browser/desktop#2485]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

There are 2 new tab buttons, I assume it should only have one new tab button?
![image](https://github.com/user-attachments/assets/25d1d74e-04d3-49bf-a49b-024c6a8a3c7b)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.16 (Firefox 132.0) (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by Richard-Woessner** [comment]
You can right click and remove it. So I wouldn't say this is a bug but something to be considered. I will ask the team

**Comment by salamijason** [comment]
https://github.com/zen-browser/desktop/issues/2449 
for more instructions on how to do so

**Comment by artimanzero** [comment]
Thank you, @Richard-Woessner i solved it
