### ISSUE TITLE
Don't prompt for primary password on browser startup

### ISSUE THREAD

**Issue by JSGRD22** [zen-browser/desktop#2487]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Every time the browser starts up, if a primary password is set, it will prompt for it even if there is no need to fill any login forms. This has been the case for a long time and is not a new problem. It would be helpful if this could be prevented.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.15

### What platform are you seeing the problem on?

Linux

**Comment by macabacus-nlm** [comment]
any chance you are using a desktop with autologin?  If you are using autologin on to your desktop, then the prompt you are getting might actually be your key ring.  When autologin puts you on your desktop, it has not unlocked the users key ring.  What desktop are you using? can you provide a screenshot of the prompt?
If at first you reboot your computer and very first open firefox, would it also prompt you for a password? (this would only be the case if firefox itself had saved passwords in it, so if your firefox does not save any sort of password anywhere in its configuration, then it would have no need to prompt you to unlock your key ring.)

**Comment by JSGRD22** [comment]
I am not sure whether my desktop has autologin. This is hyprland installed on fedora sway atomic, and I have not turned on anything specifically related to it. How do I check?

This is what the prompt looks like:
![image](https://github.com/user-attachments/assets/5dca9670-8c3d-48a4-b633-6ea9989d87fb)

I do know that firefox does not prompt me for a password on startup when master password is enabled. However, this firefox is installed by default layered in the OS, whereas zen browser is a flatpak.

**Comment by macabacus-nlm** [comment]
The easiest way to know if autologin (as I have described it) is happening is this:  When you turn on your computer from powered off, are you prompted for your password (or username and password) before you get to your desktop?   If you can turn on your computer from being all the way off, and in a moment or two or three you are finally greeted with your desktop and are now able to open applications _without_ needing to put in a password, then that implies you have autologin.  However, if you have to input a password before you can begin launching applications or opening files, etc, then the answer to my question is "no, you are not using autologin" and that would imply that my suggestion of a keyring not being unlocked is not the problem you are experiencing .

**Comment by JSGRD22** [comment]
I do not have autologin. I have to log in manually before booting up the window manager.

**Comment by salamijason** [comment]
Hey could you elaborate on what you're facing? Could it be related to this? 
![image](https://github.com/user-attachments/assets/ab8a255b-80be-4355-9331-8956b6a4641a)

**Comment by JSGRD22** [comment]
Yes, I have this option turned on. However, it should only prompt me for the primary password when I am performing authentication-related tasks, not when I open my browser for the first time.

**Comment by salamijason** [comment]
Hmm, I see. Thanks for the info!

**Comment by mr-cheffy** [comment]
https://support.mozilla.org/en-US/kb/firefox-keeps-asking-me-primary-password
