### ISSUE TITLE
Symbolic icons do not work correctly on tab bar in light mode.

### ISSUE THREAD

**Issue by Depraved7409** [zen-browser/desktop#249]
### What happened?

When opening a new tab or opening the settings page and stuff like that. The icons should be black to contrast against the light background but instead they are white, making them impossible to see in light mode. 

This only happens when that tab is not in focus. 

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.18 (64-bit)

### Severity impact

Low

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
Could you please provide a screenhot?

**Comment by Depraved7409** [comment]
![image](https://github.com/user-attachments/assets/ab3b23c0-8a86-4b44-9b49-ffa314c43cb2)


As you can see the unfocused new tab the icon and the text is light when it should be dark. And on the google tab the icon is displaying correctly but the text is not.

**Comment by Depraved7409** [comment]
Apologies for wasting your time. This was a user error and not at all related to the Zen Browser.

**Comment by mauro-balades** [comment]
oh.. Dont worry!
