### ISSUE TITLE
title bar buttons missing

### ISSUE THREAD

**Issue by KiraiEEE** [zen-browser/desktop#2492]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![image](https://github.com/user-attachments/assets/dbc618cb-7616-4f5d-8222-0815b44d50ba)

after clicking default profile to setup the theme and color it became like that u just need to hide tabs titles to see them

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.16

### What platform are you seeing the problem on?

Windows

**Comment by liamreed** [comment]
same issue again, bookmarks bar still breaks the window, the URL bar is way too wide now

**Comment by yunusemrekosif** [comment]
I think I found the issue. (Below-Picture 4) If you have more bookmarks than can fit horizontally on the screen and you have selected "Expand Tabs by Default" in the "How to Expand Tabs" settings, your close, maximize, and minimize buttons disappear. We can provide a temporary solution to this problem in two ways:

1-We can select the option to hide the bookmarks bar.
2-We can choose either the "Expand Tabs on Hover (Won't work on compact mode)" or "Don't Expand Tabs by Default" options.

This situation is shown in the images below.

My request to the dear developers is to fix this issue. I would like to see both the close, minimize, and maximize buttons as well as my bookmarks at the top.

1-Bookmarks off-Expand Tabs by Default
![1-Bookmarks off-Expand Tabs by Default](https://github.com/user-attachments/assets/eee2ef35-24ec-4cc7-805f-fa5136d99252)

2-Bookmarks off-Expand Tabs on Hover (Won't work on compact mode)
![2-Bookmarks off-Expand Tabs on Hover (Won't work on compact mode)](https://github.com/user-attachments/assets/064e12f7-8861-4182-abf3-3bcaa60c4f65)

3-Bookmarks off-Don't Expand Tabs by Default
![3-Bookmarks off-Don't Expand Tabs by Default](https://github.com/user-attachments/assets/4c9f3947-96a7-4b55-b7c3-36d5a23ccb97)

4-Bookmarks on Expand Tabs by Default
![1-Bookmarks on Expand Tabs by Default](https://github.com/user-attachments/assets/c043af4d-af7f-43f3-b7d7-de6e019dd96b)

5-Bookmarks on-Expand Tabs on Hover (Won't work on compact mode)
![2-Bookmarks on-Expand Tabs on Hover (Won't work on compact mode)](https://github.com/user-attachments/assets/9ccddac3-f81a-4865-b58d-2aa467e9872e)

6-Bookmarks on-Don't Expand Tabs by Default
![3-Bookmarks on-Don't Expand Tabs by Default](https://github.com/user-attachments/assets/18c4ea97-4f37-465d-852b-7241d3977d23)

**Comment by FlintyLemming** [comment]
I lost much more
![CleanShot 2024-11-01 at 13 10 11@2x](https://github.com/user-attachments/assets/8f2486b5-90e1-4fae-929d-4eafa93a6150)

**Comment by RayZ3R0** [comment]
Hello, this should be fixed in the new update a.17, do you guys still have this issue?

**Comment by KiraiEEE** [comment]
> Hello, this should be fixed in the new update a.17, do you guys still have this issue?

i reinstalled it and cleared appdata and same issue still , im on chrome till it get fixed xD

**Comment by macabacus-nlm** [comment]
Nice!  I had opened a duplicate ticket (I apologize, I thought I searched sufficiently).  I just updated to a.17 and this is now fixed.  thank you for an awesome fix.  thank you for an awesome browser!

**Comment by LeMoonStar** [comment]
> i reinstalled it and cleared appdata and same issue still , im on chrome till it get fixed xD

@KiraiEEE Other users confirmed this to be fixed. Are you sure you updated to the latest version of Zen (1.0.1-a.17)?

**Comment by RayZ3R0** [comment]
It is most probably fixed so I am closing this. Please reopen if this still happens
