### ISSUE TITLE
Excessive padding on the menu side of the Settings page

### ISSUE THREAD

**Issue by thestrike72** [zen-browser/desktop#2495]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![Screenshot From 2024-10-31 14-14-03](https://github.com/user-attachments/assets/a74c5624-6ea3-4a10-8682-71c87291b818)

The menu of the settings page should be less wide so that users do not have to horizontally scroll to view all of the settings. It could also be helpful if the menu collapsed when the viewing port has a smaller width so that it is usable with more window sizes. The biggest issue I have with the menu being this wide is that most of the used space is just padding and does not contain any content.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.16

### What platform are you seeing the problem on?

Linux

**Comment by RayZ3R0** [comment]
Does this still happen in a.17? there was a bug with window being weirdly expanded in a.16, should be fixed now

**Comment by salamijason** [comment]
No response in 2 days, will be closing this issue. Please feel free to reopen if you are still facing the issue.
