### ISSUE TITLE
glance opens on all windows instead of the active one

### ISSUE THREAD

**Issue by Venipa** [zen-browser/desktop#2497]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

after clicking on a link with the glance activator the glance feature activated on all open windows.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.16

### What platform are you seeing the problem on?

Windows

**Comment by jpumfrey** [comment]
This issue appears to be a duplicate of #2433, which I reported yesterday.
