### ISSUE TITLE
open settings page from additional window opens the settings in the first window.

### ISSUE THREAD

**Issue by Venipa** [zen-browser/desktop#2498]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

open settings page from additional window opens the settings in the first window.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.16

### What platform are you seeing the problem on?

Windows

**Comment by salamijason** [comment]
Intentional behavior
