### ISSUE TITLE
Ability to make the web panel wider

### ISSUE THREAD

**Issue by l4kr** [zen-browser/desktop#2503]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

Hi!
I would like the web panel to be wider. A lot of apps (including the preset ones) like Discord, Notion etc... would benefit greatly. 
Those tend to be some apps that I often check for a few seconds and I don't want to install a separate app for each an every one of them so the web panel is perfect for that. 

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.16

### What platform are you seeing the problem on?

macOS - aarch64, Windows

**Comment by RayZ3R0** [comment]
Web panel is still a work in progress and will probably be improved a lot more later. But for now, to resize web panel you have to click the Pin button (or minimize button) then resize and unpin if you need. 
![image](https://github.com/user-attachments/assets/acb92792-c68b-4459-b063-0b4e955bf097)
