### ISSUE TITLE
Crash when dragging an `<a>` element

### ISSUE THREAD

**Issue by gumbarros** [zen-browser/desktop#2504]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

https://github.com/user-attachments/assets/24fa5ce0-a312-4065-bab4-ed68dbcc97b7

When dragging an `<a>` element the browser crashes, this issue can also be repro at the same notification center of this demo:

https://prium.github.io/phoenix/v1.20.0/index.html?theme-control=true&navigation-type=vertical

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.16

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
Don't know where the logs are located. (tried both google and discord and did not found)
```

**Comment by gumbarros** [comment]
Can be repro in any `<a>` element, including the one below on GitHub

![image](https://github.com/user-attachments/assets/84a13fd8-5975-4806-a716-041087fed84e)

**Comment by gumbarros** [comment]
Sorry, this can be repro at firefox.

**Comment by negativems** [comment]
This still happens too often for me, not only with links but dragging images and text.

(Edit) Didn't see that this also happens in Firefox but apparently it was resolved a month ago.
https://bugzilla.mozilla.org/show_bug.cgi?id=1917854

Zen: 1.0.2-b.5
OS: Arch Linux (6.11.2-arch1-1)
DE/WM: bspwm (X11)

https://github.com/user-attachments/assets/eef418f9-b329-4bff-83d1-3874363ce379
