### ISSUE TITLE
Annoying border radius effect

### ISSUE THREAD

**Issue by gabsdotco** [zen-browser/desktop#2512]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Some pages display an unusual border radius on their corners. While there are a few sites, such as GitHub and even the browser settings pages, where this issue does not occur, many other sites consistently exhibit this strange border radius effect.

Below you can see what is on a few pages:

![image](https://github.com/user-attachments/assets/16359bb1-294d-498a-8028-98738fa8a3a8)
![image](https://github.com/user-attachments/assets/67082a93-47e3-43a9-b7da-0b459dd6d905)

Below you can see the expected visual effect:

![image](https://github.com/user-attachments/assets/e55f9112-2fbb-44ab-89fd-181a94f2fb5d)
![image](https://github.com/user-attachments/assets/a9f42b1f-749a-48ab-a604-edc7a1716eba)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.16

### What platform are you seeing the problem on?

Windows

**Comment by ilahazs** [comment]
how to completly disable rounded corner? I've installed the extension from theme-store but nothing changed :/

**Comment by RayZ3R0** [comment]
> how to completly disable rounded corner? I've installed the extension from theme-store but nothing changed :/

I dont think there is a way for now. Tried css too, no luck

**Comment by ander-710** [comment]
> how to completly disable rounded corner? I've installed the extension from theme-store but nothing changed :/

Go to `about:config` and change the value of `zen.theme.border-radius` to `0`

**Comment by RayZ3R0** [comment]
> > how to completly disable rounded corner? I've installed the extension from theme-store but nothing changed :/
> 
> Go to `about:config` and change the value of `zen.theme.border-radius` to `0`

That will remove every single rounded corner in the browser and make it horrifying

**Comment by iLiranS** [comment]
> how to completly disable rounded corner? I've installed the extension from theme-store but nothing changed :/

Try this in `userChrome.css` file :

    :root {
        --zen-border-radius: 0px !important;

    }

    & #tabbrowser-tabbox {
        padding: 0 !important;

        #tabbrowser-tabpanels {
            padding: 0 !important;


            .browserSidebarContainer {
                margin: 0 !important;
                border-radius: 0 !important;
                --zen-webview-border-radius: 0 0 0 0 !important;
                --zen-element-seperation: 0 !important;

            }
        }
    }

**Comment by RayZ3R0** [comment]
that will disable literally every single rounded corner the browser has 💀 looks horrifying

**Comment by iLiranS** [comment]
> that will disable literally every single rounded corner the browser has 💀 looks horrifying

He asked for a way to completely disable rounded corners 🤷‍♂️
Personally, I use it for compact mode view to get full-screen experience.

**Comment by RayZ3R0** [comment]
I'd rather have a few pixels of annoying corners than have my entire browser look horrible though lmao

**Comment by Spacellary** [comment]
Reproducing this here, for example in `minecraft.net` (you can see the issue in the rounded corner):

![image](https://github.com/user-attachments/assets/8c5fdd19-3cbc-4b8f-a064-9c738fcb3b05)

**Comment by gabsdotco** [comment]
Just an update on this one: I was configuring a new Zen Browser account on my Linux with an outdated version of the browser, and that issue wasn't happening. After I upgraded to the current version, the weird corner pixel appeared. So something recently introduced on newer versions.

(sorry, I forgot to take a screenshot)

**Comment by Spacellary** [comment]
Related:

The current implementation of this concept from https://github.com/bmFtZQ/edge-frfox for their `uc.tweak.rounded-corners` tweak works perfectly on the latest Beta/Dev version of Firefox for reference. Once the same issue was present there but it has long been resolved so it could be something to look into.

![screenshot](https://github.com/user-attachments/assets/a8080a9d-676f-497c-a753-f56a80b0ea79)

**Comment by Spacellary** [comment]
Feedback from:

Twilight build - 1.0.1-t.19 (2024-11-13 at 00:12:19)

**Issue persists.**

**Comment by ryanull24** [comment]
I am seeing the same (similar?) issue on a22
![image](https://github.com/user-attachments/assets/445aff55-e7b4-41d1-8d1b-c7f05817f62c)

Notice the purpleish border.
In a new container, that border is black, and I cannot figure out why is it a different color.

![image](https://github.com/user-attachments/assets/276d3ec1-cba2-4de4-8b16-6d65961fa50b)


I see it on every page - websites, settings, anything.

**Comment by utopiaeh** [comment]
Same problem:
**_1.11.5b (Firefox 137.0.2) (aarch64)_**

![Image](https://github.com/user-attachments/assets/427b9e00-cdf6-4285-8835-53d3c4a7d0e6)

**Comment by ghost** [comment]
For anyone looking for a solution, putting these two commands on userchrome.css seem to work. Have no idea why though:

```
#tabbrowser-tabpanels {overflow: -moz-hidden-unscrollable;}
#tabbrowser-tabbox * {border-radius: 10px}

```
Actually, I think we can use the "-zen-element-separation" variable as well, which is probably better.

```
#tabbrowser-tabpanels {overflow: -moz-hidden-unscrollable;}
#tabbrowser-tabbox * {border-radius: var(--zen-element-separation) !important}
```
