### ISSUE TITLE
Empty pinned new tab opening a url opens in a new page

### ISSUE THREAD

**Issue by darkvergus** [zen-browser/desktop#2513]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

having a new tab pinned and going to an url opens that url in a new tab instead of that tab.

https://github.com/user-attachments/assets/826ddb27-1ded-49c1-a2b6-7b8535ca6215

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a16

### What platform are you seeing the problem on?

Windows

**Comment by darkvergus** [comment]
@dosu its set to false

**Comment by salamijason** [comment]
yo are you still getting this? Honestly it looks a *bit* like intentional pinned tab behavior but will verify on our end.

**Comment by salamijason** [comment]
Just tested this on my mind, same behavior. Still verifying whether this is intentional or not.

**Comment by salamijason** [comment]
Hey just tested this on firefox and it does the same thing. Definitely a ff thing a not a zen thing. Probably intentional too. will be closing the issue now!

**Comment by darkvergus** [comment]
No it doesn't

https://github.com/user-attachments/assets/1110e953-2ced-471d-aa11-b42a2ac35b03
