### ISSUE TITLE
Can't move new tab toolbar 

### ISSUE THREAD

**Issue by genesis224** [zen-browser/desktop#2517]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I was wondering if this issue is just my OS itself or its really a bug and I just found this right now where I cant move around the new tab button when customizing my toolbar 

https://github.com/user-attachments/assets/1976ef3e-4746-4f90-ac20-c96b97c2e7d4

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.16

### What platform are you seeing the problem on?

Linux

**Comment by kenny-kvibe** [comment]
![image](https://github.com/user-attachments/assets/5ce6c578-717c-4956-bb19-75ada25388a7)
^ uncheck this

**Comment by RayZ3R0** [comment]
That is not removable with customize toolbar. There is an option in the settings for that as kenny-kvibe has shown, please use that
