### ISSUE TITLE
[BUG] glance-close focuses next-tab

### ISSUE THREAD

**Issue by kenny-kvibe** [zen-browser/desktop#2520]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Glance-opening a link starts normally but `closing it moves the focus to the next tab`
(just like clicking on the next tab).

I also tried with all 3 keybindings - same issue.
Overall glance seems like a great feature but I'll disable it for now.

---

Reproducing the issue:
- open 2 tabs and focus on `tab 1`
- glance a link in `tab 1`
- close glance in `tab 1`
- & on-close it auto-focuses `tab 2` (it does for me..)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.17

### What platform are you seeing the problem on?

Windows

**Comment by salamijason** [comment]
A more extensive report found here https://github.com/zen-browser/desktop/issues/2526

will be closing this and moving to above issue.
