### ISSUE TITLE
Glance issues - a.17

### ISSUE THREAD

**Issue by wysh3** [zen-browser/desktop#2526]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

1. open a glance 
>on closing it automatically shifts you to the next tab

2. open a glance
>close the tab using the middle click 
>tab closes not the glance 

3. open a glance 
>close the tab using the keyboard shortcut "ctrl+w" 
>tab closes but the padding doesn't restore

in all the above cases: 
>the tabbar in compact mode might not close and remain open
>the whole ui can become unresponsive 
>a restart would fix it 

all in one video :) 

https://github.com/user-attachments/assets/53391efe-77ea-4f74-a3ff-f58a3a317c3f

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.17

### What platform are you seeing the problem on?

Linux, Windows

**Comment by RayZ3R0** [comment]
https://github.com/user-attachments/assets/4e43aa37-4536-4cdb-9e48-0bd89bd92d41

yeah and the 3rd issue also breaks my browser until I restart

**Comment by salamijason** [comment]
another video of bug one that i was able to reproduce

 I get this too on windows a17

https://github.com/user-attachments/assets/91210230-db58-4aa7-b2ae-5debfae99a83

**Comment by tedbergstrand** [comment]
I believe this is the same bug as [#2459](https://github.com/zen-browser/desktop/issues/2459). At least Number 3.

**Comment by RayZ3R0** [comment]
Yeah, this one has more issues in one

**Comment by tedbergstrand** [comment]
Right, which means a single fix won't solve all the problems. Take a look at the new Twilight build that implies this bug is fixed. But it's not totally fixed because it's more than one bug.

**Comment by RayZ3R0** [comment]
yeah this fix is still in progress, not closed yet

**Comment by tedbergstrand** [comment]
Further demonstrating why individual bugs should have individual issues.

**Comment by Madekuji** [comment]
> ### What happened?
> 
>     1. open a glance
> 
> 
> > on closing it automatically shifts you to the next tab
> 
>     2. open a glance
> 
> 
> > close the tab using the middle click
> > tab closes not the glance
> 
>     3. open a glance
> 
> 
> > close the tab using the keyboard shortcut "ctrl+w"
> > tab closes but the padding doesn't restore
> 
> in all the above cases:
> 
> > the tabbar in compact mode might not close and remain open
> > the whole ui can become unresponsive
> > a restart would fix it
> 

I've tested the bugs filed in this issue on Zen Twilight version `1.0.1-t.22 (64-bit) (Windows)` and can confirm that they have been fixed.

https://github.com/user-attachments/assets/9a28e7fe-a599-43b5-badd-d47f6de877e9

**Comment by wysh3** [comment]
> > ### What happened?
> > ```
> > 1. open a glance
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > > on closing it automatically shifts you to the next tab
> > 
> > 
> > ```
> > 2. open a glance
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > > close the tab using the middle click
> > > tab closes not the glance
> > 
> > 
> > ```
> > 3. open a glance
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > > close the tab using the keyboard shortcut "ctrl+w"
> > > tab closes but the padding doesn't restore
> > 
> > 
> > in all the above cases:
> > > the tabbar in compact mode might not close and remain open
> > > the whole ui can become unresponsive
> > > a restart would fix it
> 
> I've tested the bugs filed in this issue on Zen Twilight version `1.0.1-t.22 (64-bit) (Windows)` and can confirm that they have been fixed.
> zen-2526-test-1.mp4

thanks for reminding 
I'm closing this issue
