### ISSUE TITLE
The fullscreen button and close button in glance both close the window.

### ISSUE THREAD

**Issue by Shockshwat** [zen-browser/desktop#2528]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I saw the changelog of a17 and thought something changed regarding the fullscreen button of glance so i decided to check it out when i discovered that close button and fullscreen button both do the same thing. I expected the fullscreen button to "seamlessly"(what i understood from the changelog) well fullscreen the tab.

Edit: I am on Zen browser and the attached video is showing corrupt for me, I tried to look at it using my smartphone and the video loads fine, I don't know if that's a bug or a configuration issue on my side but you face the same issue while trying to play the video please try loading it in another browser or smartphone.

https://github.com/user-attachments/assets/ae2a3927-7c16-4d44-9df2-91d534decde9

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.17

### What platform are you seeing the problem on?

Windows

**Comment by RayZ3R0** [comment]
https://github.com/user-attachments/assets/000c78cf-28e5-4942-bc79-f4e489e41243

That's not how its happening for me though, But yeah there are still a lot of bugs in glance, maybe it'll be fixed with those

**Comment by JSGRD22** [comment]
Similar issue here. However, for me it seems that the button hitboxes are actually not present at all, and attempting to click them just clicks outside the glance box and closes it. This is evident as the buttons are not highlighted when hovering over them.

**Comment by Shockshwat** [comment]
![image](https://github.com/user-attachments/assets/66fb7006-0a5e-4cb4-971d-2f226dac48a0)
Update with a18, Now the icons are missing too.

**Comment by JSGRD22** [comment]
Issue is no longer present
