### ISSUE TITLE
when opening a link in split view it forms a new tab

### ISSUE THREAD

**Issue by Realrubr2** [zen-browser/desktop#2529]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Hello Team Zen
i am having trouble when in splitview opening a link it is, opening in another tab,
i am not 100% sure if this is a feature or a bug. if it is a feature please ignore!

Greets Ramon,

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.01

### What platform are you seeing the problem on?

Windows

**Comment by salamijason** [comment]
Hey sorry for the late response, could you maybe send a screen recording of what you're facing?

**Comment by salamijason** [comment]
No response in a week. Closing for now. Please reopen if you're still encountering the issue.
