### ISSUE TITLE
Improve app logo

### ISSUE THREAD

**Issue by Anthonyy232** [zen-browser/desktop#253]
### What feature would you like to see?

The current app logo is pretty low quality on Windows. It would be nice to get a higher version one.
![image](https://github.com/user-attachments/assets/e374f61f-f0bb-4222-aa30-870412097121)

### What platform are you seeing the problem on?

Windows

**Comment by Erlendms** [comment]
Yeah, I originally custom versions in 32px, 64px, 256px, 512px and 1024px - but apparently Firefox can only accept one version when you build. But we went with the largest one, I don't know why it looks so poor there. 🤷🏻‍♂️ 

But here's the original files:

![zen-icon_mac_1024px](https://github.com/user-attachments/assets/a4fe8509-9486-42fa-ae2e-0ec42021b443)
![zen-icon_win_bg_dark](https://github.com/user-attachments/assets/749d4a05-faea-4792-bfa7-15a508e2bfa3)
![zen-icon_win_bg_light](https://github.com/user-attachments/assets/de75e4fe-c96b-45e3-a7db-1fe16e455ab7)
![zen-icon_win-dark_1024px](https://github.com/user-attachments/assets/3c85192a-dd19-43a5-9e17-d01e30163bd3)
![zen-icon_win-light_1024px](https://github.com/user-attachments/assets/d81603b5-9885-4203-8284-aa6aaa548c4c)
![zen-logo_banner_transparent](https://github.com/user-attachments/assets/59981468-06b6-40cc-b336-7837edeb7ea3)
![zen-logo_banner](https://github.com/user-attachments/assets/7dfe70b4-1b3f-42b9-9b0f-04a19fda71af)

**Comment by Anthonyy232** [comment]
Isn't building apps with SVG logos pretty standard?

**Comment by Donnnno** [comment]
Have you seen the new logo? @Anthonyy232 ? 
(we're working on fixing the low res issue btw)

![zen-black](https://github.com/user-attachments/assets/1fc7be7a-6a4e-4dd3-9aa6-a8dd4ddf9124)

**Comment by Erlendms** [comment]
> Have you seen the new logo? @Anthonyy232 ? 
> 
> (we're working on fixing the low res issue btw)
> 
> 
> 
> ![zen-black](https://github.com/user-attachments/assets/1fc7be7a-6a4e-4dd3-9aa6-a8dd4ddf9124)
> 

BTW, Are you making a Mac version of the icon as well? The one who's shipping now doesn't adhere to the standard. (Needs more padding and a shadow. You can steal them from my icon if you don't have them. ☺️) It appears much larger than any other icon in the dock in the current state.

**Comment by Donnnno** [comment]
Mac version according to Apple's guidelines is included in the latest versions 

![image](https://github.com/user-attachments/assets/cae5bf5e-76b8-40d8-8ed1-d2fb37ba817e)

**Comment by Erlendms** [comment]
Noice! Would love it if you shared the files for the other colours - if there isn't a way to do it in-app.
As I mentioned on Discord, I like your icon better than mine. 😎

**Comment by NOCanoa** [comment]
https://www.zen-browser.app/branding-assets 👀

**Comment by Donnnno** [comment]
@Erlendms of course! I'm in the process of exporting everything for Linux, Windows & MacOS. I'll let you know when I'm done.

@NOCanoa the branding assets have some old versions in there right now, on top of that, they're only PNG. So not super usable.

**Comment by Erlendms** [comment]
> https://www.zen-browser.app/branding-assets 👀

Yes, I know - but as you perhaps could tell from the comment below yours, those are only the Windows/Linux versions.

---

I don't know how things are on the Windows/Linux side, but for MacOS, PNG is the standard. (In 32px up to 1024px if I remember correctly.) Are SVGs or something used elsewhere?

**Comment by NOCanoa** [comment]
> @NOCanoa the branding assets have some old versions in there right now, on top of that, they're only PNG. So not super usable. 

In near future when you done its there nicely 👀
