### ISSUE TITLE
Deformed icons on bookmarks bar when in "Density mode" is set to "Touch"

### ISSUE THREAD

**Issue by Alessandro-Vecchio** [zen-browser/desktop#2531]
![Screenshot 2024-11-01 104011](https://github.com/user-attachments/assets/ddd29e93-3dce-4dec-a8d0-8e011a85f96f)
### Captchas

- [X] I have read the instructions.
- [ ] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

Icons should scale correctly when in "Density" mode
![Screenshot 2024-11-01 103657](https://github.com/user-attachments/assets/fd135c2b-333a-4b65-9e96-0e15fa4c93fa)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.17 (64 bit)

### What platform are you seeing the problem on?

Windows

**Comment by realpixelcode** [comment]
For me, the issue occurs even when “density mode” is disabled. My Zen version: `1.0.1-a.19 (Firefox 132.0.1) (64-Bit)`

![grafik](https://github.com/user-attachments/assets/4c4fe5ef-3cdc-45b0-af95-f2b652646ce6)

**Comment by Alessandro-Vecchio** [comment]
The bug has been fixed
