### ISSUE TITLE
No way to hide Bookmarks toolbar.

### ISSUE THREAD

**Issue by Shockshwat** [zen-browser/desktop#2532]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I don't think there is a way to hide bookmarks the native firefox way in Zen as of now. Firefox has a way to go to customize toolbar, and then turn off bookmark toolbar from there but Zen instead has Menu Bar setting which does nothing on my end. 
![image](https://github.com/user-attachments/assets/2403a92f-5865-4e64-b9bf-2ab3f1b0a31a)
![image](https://github.com/user-attachments/assets/e2396ce0-4fcf-4e18-8f78-e32ca4eda516)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.17

### What platform are you seeing the problem on?

Windows

**Comment by RayZ3R0** [comment]
Are you talking about the bookmark toolbar below the URL bar?

**Comment by Shockshwat** [comment]
@RayZ3R0 Yes the dotted highlighted area i showed here.
![image](https://github.com/user-attachments/assets/9e88a009-a4a9-46d1-a574-16ac8e03aeb7)
Edit: Well I fixed the issue thanks to dosubot's suggestion, but I still think this isn't the intended way.

**Comment by RayZ3R0** [comment]
> @RayZ3R0 Yes the dotted highlighted area i showed here. ![image](https://private-user-images.githubusercontent.com/71540383/382287258-9e88a009-a4a9-46d1-a574-16ac8e03aeb7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1NDIwODUsIm5iZiI6MTczMDU0MTc4NSwicGF0aCI6Ii83MTU0MDM4My8zODIyODcyNTgtOWU4OGEwMDktYTRhOS00NmQxLWE1NzQtMTZhYzhlMDNhZWI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAyVDEwMDMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1ZWU4NDhjMTI5ZjJhMmI1MzRlMTFjYjEyZWFiZTA1ZjBlYmU3NzUzZGQ0NjUyOGY2YmYwZDYwMGY1Y2I1M2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ggM5c7n6y_jUA03jyOJmwACfoPR20lMu6O69WffWv5Y) Edit: Well I fixed the issue thanks to dosubot's suggestion, but I still think this isn't the intended way.

You can actually use the shortcut ctrl + shift + B to open and close it

**Comment by CrossScarDev** [comment]
The three dots in the top right, then bookmarks, then show/hide bookmarks toolbar.

**Comment by Shockshwat** [comment]
Fixed with an update I think, Now you can right click on the toolbar and set its preference.
