### ISSUE TITLE
Glance when closed jumps to another tab and not to the original tab

### ISSUE THREAD

**Issue by Rics-Dev** [zen-browser/desktop#2535]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When openning a glance then closing it, instead of going to the tab where the user was, it goes to the next tab

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.17

### What platform are you seeing the problem on?

Linux

**Comment by sdtperera** [comment]
Same here on Windows 11.

**Comment by MarkTheStark** [comment]
Same here Windows 11, Version 1.0.1-a.17 (64-bit)

**Comment by h-queiroz** [comment]
Same on Windows 10.

**Comment by K0ntact** [comment]
This issue is mentioned at #2526.

**Comment by paulwyszynski** [comment]
Same on Mac.

**Comment by mithom** [comment]
this also breaks some tabs, for example if the tab it switches to was on the same domain, you'll be left with an unresponsive empty tab

**Comment by RayZ3R0** [comment]
Duplicate of #(I dunno man, no one checks for duplicates so there's a lot). Closing as it will be fixed in a18 soon.
