### ISSUE TITLE
Last pinned tab loads upon closing the last normal tab, and new tab auto-opens even when there's at least one tab already open

### ISSUE THREAD

**Issue by stripedgoat** [zen-browser/desktop#2540]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

https://github.com/user-attachments/assets/e5937bce-21f5-4384-bbff-108cf8c826fc

As you can see in the video, this behavior is not correct.

When there's at least one tab open, and you close the last regular tab, it's expected that the browser will jump to that tab that is open. But instead it loads the last pinned tab.

Also, when you close the last normal tab (in presence of at least one open tab), and then switch away from that workspace to another one, then back to the previous one, you get a new tab automatically even when there's at least one tab open.

We should be only getting a new tab automatically when there's no tabs left (pinned or unpinned).

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

a.17

### What platform are you seeing the problem on?

macOS - Intel

**Comment by Contade** [comment]
> We should be only getting a new tab automatically when there's no tabs left (pinned or unpinned).

I disagree. We should get a new tab automatically when there are no unpinned tabs, even if there are pinned tabs.

Maybe add both behaviors and have a toggle instead.

**Comment by stripedgoat** [comment]
> > We should be only getting a new tab automatically when there's no tabs left (pinned or unpinned).
> 
> I disagree. We should get a new tab automatically when there are no unpinned tabs, even if there are pinned tabs.
> 
> Maybe add both behaviors and have a toggle instead.

I meant, if there's not a single opened tab, then give us a new tab automatically. But if there's a tab already open, then just show that tab, instead of opening a new tab.
