### ISSUE TITLE
Can't disable double click for new tab

### ISSUE THREAD

**Issue by VuthMuul** [zen-browser/desktop#2545]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

A new behaviour of double clicking a blank space in the vertical tab bar was introduced and doesn't seem to be an option to disable this. There's already middle click for open new tab, and it was convenient being able to maximise the window by double clicking it since the whole bar acts as a title bar (it's still draggable even, so blocking double click is causing inconstant behaviour)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.17

### What platform are you seeing the problem on?

Windows

**Comment by neurokitti** [comment]
this feels more like an enhancement request not a bug idk

**Comment by salamijason** [comment]
This does feel like a request rather than a bug but having two buttons on the mouse (middle and double-left-click) do the same exact thing isn't ideal. 

Having an option to pick one of the two or disable them would be great.
