### ISSUE TITLE
Glance is launching links in main window and Glance window

### ISSUE THREAD

**Issue by tedbergstrand** [zen-browser/desktop#2546]
EDIT: For some reason this isn't happening to me anymore... Not sure what changed-- maybe the website. Either way, this doesn't seem to be a problem any longer.

### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Modifer + Click is launching the Glance and also launching the link in the main window.  This is observable with both Alt and Control on Windows. It doesn't happen with all links, but it happens with some. Specifically, I'm noticing this on ETrade.com at the moment.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.17

### What platform are you seeing the problem on?

Windows

**Comment by RayZ3R0** [comment]
Tried to reproduce, didnt happen to me

https://github.com/user-attachments/assets/d88d2709-2af0-42dc-80aa-66ba31acb490

**Comment by tedbergstrand** [comment]
> Tried to reproduce, didnt happen to me
> recording-2024-11-07-191115.1.mp4

Weird. The other day they were both changing-- but they're not today... 

But I'm getting a different bug now... When I close the glance window, it's moving forward a tab instead of staying on the current tab. I'm going to try t.18

Neither problem presents itself in t.18. I suppose this should be closed, Thanks @RayZ3R0

**Comment by RayZ3R0** [comment]
Yeah that was a bug which is going to be fixed soon on a18 too, just needs a few more bug fixes for the next release
