### ISSUE TITLE
Bookmarks toolbar items in the tab bar are broken after collapsing tab bar

### ISSUE THREAD

**Issue by VuthMuul** [zen-browser/desktop#2547]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

An update to Zen made the bookmarks toolbar show a `>` when there's not enough room for bookmarks - which works great when collapsed - but has added a bug where expanding again the bar is empty until resize, however the arrow remains (not clickable and nothing in there anyway) along with extra space and the whole tab bar is wider. This persists until the browser is restarted

Working as normal
![image](https://github.com/user-attachments/assets/b2ce4d3e-6d8b-417a-befd-33a0ead87a96)
Collapsed, reduces to overflow
![image](https://github.com/user-attachments/assets/154c32c3-81fd-415a-87b0-86cd46bb4b37)
Expanded, bookmarks are missing
![image](https://github.com/user-attachments/assets/852ed35f-7147-4f35-9942-5acc97373c16)
After resize they return but overflow remains and the bar is permanently wider too
![image](https://github.com/user-attachments/assets/56e436b1-533c-498e-8a6f-ea44518ee75b)
What my browser customisation looks like. Mods are disabled.
![image](https://github.com/user-attachments/assets/8fea2534-0237-4ce5-961f-9997d1a7cb69)

I find having the bookmarks toolbar nestled in the tab bar a great way to add a few bookmarks without taking up much space or requiring access to the menu. The overflow change is great (previously the bar just got cropped) but has some issues.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.17

### What platform are you seeing the problem on?

Windows

**Comment by Richard-Woessner** [comment]
Confirmed on nightly 1.0.1-t.17
