### ISSUE TITLE
Glance window breaks Zen if closed with CTRL + W shortcut on Windows

### ISSUE THREAD

**Issue by Tomveloper** [zen-browser/desktop#2551]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

After opening a Glance, closing it using the close tab shortcut, CTRL + W, closes it but it also breaks Zen and makes you unable to switch tab or open a new Glance.

Steps to reproduce:
1. Open a Glance.
2. Press CTRL + W to close the Glance.

I would expect (and want) the Glance to close without any issues, just like when you close it normally using the X button.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.17 (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by BredMan0** [comment]
This same issue happens on Linux too. 

https://github.com/user-attachments/assets/59453a0f-4ec4-4c34-b59e-a32635d568ed

**Comment by BredMan0** [comment]
Just checked, this issue has actually already been mentioned in #2526 too.

**Comment by Tomveloper** [comment]
> Just checked, this issue has actually already been mentioned in #2526 too.

Oh sorry, I saw the video and it didn't showcase the bug so I assumed they were talking about something else.

**Comment by beauwright** [comment]
I have this issue too on macOS aarch64

**Comment by Tomveloper** [comment]
> I have this issue too on macOS aarch64

It is fixed in Zen Twilight, the nightly version.
