### ISSUE TITLE
Expanded Tab Bar Crops Right Side Of Window - Including Window Buttons And Page Content

### ISSUE THREAD

**Issue by macabacus-nlm** [zen-browser/desktop#2552]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

On Linux, when tab bar is collapsed, the window looks normal.  However, when you expand the tab bar, the right side of the window gets cropped by the amount of space the tab bar takes.  You can no longer access window buttons, nor can you access anything on the web page being displayed.
Collapsed or minimized tab bar:
![zen-whoops1](https://github.com/user-attachments/assets/c044e959-2cb7-466c-96ee-5ef4446e4b6c)

Expanded or wide tab bar where this is now broken:
![zen-whoops2](https://github.com/user-attachments/assets/dce79203-7455-4b31-8644-3409fd15e740)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.16 (Firefox 132.0) (64-bit)

### What platform are you seeing the problem on?

Linux

**Comment by macabacus-nlm** [comment]
@dosu I did check those three other issues.  While they look a bit similar to what I am experiencing, they are not the same.  I am currently using the latest release of Zen Browser.

**Comment by macabacus-nlm** [comment]
to my knowledge I have not altered any of these values.  I disabled all mods as well and the problem was still reproducible.

**Comment by LeMoonStar** [comment]
If I understand correctly, this is the same issue as #2492. I will therefor close this as a duplicate.

If I am mistaken, please comment or re-open this issue.
Thank you a lot for your report!

**Comment by macabacus-nlm** [comment]
Confirmed.  This is a duplicate.  I apologize.  i thought I had looked sufficiently for this before opening a new ticket.  The fix provided by a.17 as referenced in the prior comment of issue #2492 has been resolved for me.  Thank you!
