### ISSUE TITLE
Window control buttons overlapping with toolbar on narrow windows when not in compact mode

### ISSUE THREAD

**Issue by LeMoonStar** [zen-browser/desktop#2557]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When not in compact mode, dragging the window to a narrow horizontal width, the window control buttons start to overlap with the symbols on the top toolbar.

### Fedora 40

https://github.com/user-attachments/assets/9c613ea5-f515-4d39-8d38-7d9ca7366683

![image](https://github.com/user-attachments/assets/df1725b4-8214-4eb5-a255-af6831f15841)

### Windows 11 on a friends computer
![image](https://github.com/user-attachments/assets/51c939a6-cde6-4107-9043-916db81d33b4)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.17

### What platform are you seeing the problem on?

Linux, Windows

**Comment by LeMoonStar** [comment]
> I found a similar issue that might be helpful:
> 
>     * [If not maximized, there are bugs in the ui display #2445](https://github.com/zen-browser/desktop/issues/2445)
>       The suggested solution for this issue was to adjust the width of the `#navigator-toolbox` in Zen's Vertical Toolbar. By removing the `#navigator-toolbox`, the issue was resolved, indicating that calculating its width and adding it to Zen's minimum width could prevent the overlap problem.
> 
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

@dosu That issue is related to a previous bug where the window controls disappeared completely. In this issue however, the buttons don't disappear, but instead overlap with the other icons in the toolbar.

**Comment by kwilcz** [comment]
Already fixed in new update: https://github.com/zen-browser/desktop/issues/2445#issuecomment-2449201619

**Comment by LeMoonStar** [comment]
> Already fixed in new update: [#2445 (comment)](https://github.com/zen-browser/desktop/issues/2445#issuecomment-2449201619)

No, it is not fixed yet - neither in the current release `1.0.1-a.17` - nor in the latest twilight build `1.0.1-t.18 (Firefox 132.0.1) (2024-11-07)` (today's build failed, that's why the date is from yesterday)

**Comment by LeMoonStar** [comment]
> Already fixed in new update: [#2445 (comment)](https://github.com/zen-browser/desktop/issues/2445#issuecomment-2449201619)

The quoted issue is not the same - it refers to the buttons being off-screen when the window is narrow. This issue however is about them overlapping with the toolbar when the window is narrow - a direct result of the "fix" for the aforementioned issue.
