### ISSUE TITLE
Inactive Tabs Freeze and Cannot Be Reopened

### ISSUE THREAD

**Issue by AhmedOsman101** [zen-browser/desktop#2559]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

**Describing the Bug**  
After opening multiple tabs in Zen Browser, inactive tabs automatically freeze after a set period. Previously, clicking on an inactive tab would reload and open it as expected. However, after the recent update, inactive tabs cannot be reopened by clicking on them in the sidebar. Instead, I must right-click and select "Duplicate Tab" to access the content.

**Steps to Reproduce**  
1. Open multiple tabs in Zen Browser.
2. Wait until some tabs become inactive.
3. Attempt to reopen an inactive tab by clicking on it in the tabs sidebar.

**Expected Behavior**  
Clicking on an inactive tab should reload and open it, as it did before the update.

**Observed Behavior**  
Clicking on inactive tabs does nothing. They remain inaccessible until duplicated.

**Environment**  
- **Operating Systems**: Windows 11 (laptop) and Linux Ubuntu (PC)  
- **Installation Method**: Flatpak on Linux

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.16

### What platform are you seeing the problem on?

Linux, Windows

**Comment by LeMoonStar** [comment]
This issue has already been reported in #2436 and has been fixed in Zen 1.0.1-a.17.
Please update and try again.

This issue will be closed as a duplicate. If you still experience this problem free to comment or re-open this issue.
