### ISSUE TITLE
Not using custom new tab page on first new tab or when closing all tabs

### ISSUE THREAD

**Issue by RetrogradeDev** [zen-browser/desktop#2561]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When closing all tabs, the new tab opening is the default new tab, not the tab created by a custom new tab extension (Casca).

Edit: the first tab when the browser starts up is also the default tab instead of the custom one.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.17

### What platform are you seeing the problem on?

Windows

**Comment by giaaaacomo** [comment]
same here. also, the start page only applies to the first workspace. when opening the second workspace it goes to the zen's default start page, but then opening a new tab follows the new tab rules. noticeably, changing the start pages in the settings is reverted to the default start page when reopening the settings

**Comment by CrossScarDev** [comment]
This isn't a bug and does exist on Mozilla Firefox. It is a limitation of being based off of Mozilla Firefox which has no official way of setting the default page on launch which is the page it is using in this scenario.

**Comment by RetrogradeDev** [comment]
Oh okay, I wasn't able to test it in Firefox because it just closes the windows when I close all tabs, instead of opening a new one.
