### ISSUE TITLE
Tab panel doesn't work after move some tab to another workspace

### ISSUE THREAD

**Issue by Irrisorr** [zen-browser/desktop#2562]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Tab tree doesn't work after move some tab to another workspace. Always right click will be disable after it and sometimes everything on tab tree will not work (including left click or expand the tab tree). 

Version:  1.0.1.a.17-1 (zen-browser avx2, arch linux / hyprland)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1.a.17-1

### What platform are you seeing the problem on?

Linux

**Comment by yhansy** [comment]
Same as https://github.com/zen-browser/desktop/issues/2343

**Comment by Irrisorr** [comment]
Still doesn't work properly
