### ISSUE TITLE
hotkey "Toggle side bar" doesn't work

### ISSUE THREAD

**Issue by Irrisorr** [zen-browser/desktop#2564]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

hotkey "Toggle side bar" doesn't work

Any key combination I put at "Toggle side bar" doesn't work.

Version: 1.0.1.a.17-1 (zen-browser avx2, arch linux / hyprland)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1.a.17-1

### What platform are you seeing the problem on?

Linux

**Comment by neurokitti** [comment]
![image](https://github.com/user-attachments/assets/d075050b-ac2c-4814-a52d-7db58beb1eff)

toggle sidebar width?

**Comment by Irrisorr** [comment]
@neurokitti nwm, I mixed up the categories, it was written there for a compact mod, thank you very much for the explanation that helped me, everything works in the end
