### ISSUE TITLE
Tabs dont react after not using for some time

### ISSUE THREAD

**Issue by Stevenzocker** [zen-browser/desktop#2566]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I have been watching youtube for about 20 minute and not using the other tabs in the window and when finished and wanting to go to those tabs neither do they react at all nor can I open new tabs and I have to restart the browser

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1.a.17-1

### What platform are you seeing the problem on?

Linux

**Comment by RayZ3R0** [comment]
Are you sure you are on a.17? because this was an issue from a.16 which was fixed. Can you try on a new profile or reinstall the browser?

**Comment by salamijason** [comment]
User has not replied in a couple weeks. Closing the issue now. Please reopen if issue persists.
