### ISSUE TITLE
cannot create workspaces

### ISSUE THREAD

**Issue by marcorossiIT** [zen-browser/desktop#2567]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I have no option to create a new workspace.  
Workspaces are enabled in settings.  
Tried re-enabling it on setting, re-opening Zen.  
on right click on a tab, on Change tab to workspace, i see Default and nothing else

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.14 (Firefox 131.0.3) (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by Irrisorr** [comment]
@marcorossiIT try right-clicking on the workspace icon itself, and a "+" should appear there

**Comment by marcorossiIT** [comment]
Thanks for your suggestion. I think my icon is missing tho
![image](https://github.com/user-attachments/assets/ba909c0f-45b6-4c74-81ad-ea9da20db5c1)

To be sure of it tho i downloaded the portable version. this is what it should be if i'm not wrong
![image](https://github.com/user-attachments/assets/ce9397b7-34c1-4c04-9134-b3e2aeef93b8)


This may be caused by an update, but i don't really like the idea of reinstalling zen, cuz i'd personalize everything again, and I was finally happy with it. I'll do it if that's the only way tho

**Comment by marcorossiIT** [comment]
Side note: i tried customizing the toolbar, i moved the workspaces selector out of the way, it sticks between the other buttons
![image](https://github.com/user-attachments/assets/afe6041e-26d2-4d56-bfbf-7a5c5f4f43ba)

This is something that just isn't there on my installation. while i can have this:
![image](https://github.com/user-attachments/assets/550e600d-eb0f-4413-86c9-10d613da3ee4)

**Comment by Irrisorr** [comment]
![изображение](https://github.com/user-attachments/assets/eecf4e60-75ea-40a1-8a89-ab23b3dd5723)
u really tried this? and after click on "+" to create new workspace

**Comment by marcorossiIT** [comment]
> ![изображение](https://private-user-images.githubusercontent.com/102664241/382437583-eecf4e60-75ea-40a1-8a89-ab23b3dd5723.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1OTE4MzIsIm5iZiI6MTczMDU5MTUzMiwicGF0aCI6Ii8xMDI2NjQyNDEvMzgyNDM3NTgzLWVlY2Y0ZTYwLTc1ZWEtNDBhMS04YTg5LWFiMjNiM2RkNTcyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMlQyMzUyMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOGUyMzMzNThmMmE2NTY0YTQ5YThhYjgxYjgwODg5ODBjZmExYmRhYjAzZWY5YjNkMGJmMzM3OWE0OGFjZmRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.nCf1z2L5bSRshEzoolZIY3CHti5KXEMB3qKD_vedw08) u really tried this? and after click on "+" to create new workspace

no i didn't, cause i don't have the workspace selector button anyhere:
![image](https://github.com/user-attachments/assets/4c8b2555-cb39-43d0-9979-2397af835165)

**Comment by marcorossiIT** [comment]
i tried migrating parts of profile to a new one, but i've been unsuccessful, so i reainstalled and solved the problem, even tho it's a hussle to do personalize and login again into everything..
