### ISSUE TITLE
Title bar does not lose focus after using URL bar in compact mode

### ISSUE THREAD

**Issue by JSGRD22** [zen-browser/desktop#2568]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When in compact mode, if the URL bar is interacted with, the title bar does not lose focus and stays in place until a button on the page is clicked. This is annoying. It would be better if clicking anywhere on the sidebar or the page would unfocus the URL bar and hide the title bar.

Additionally, if possible, make it like chromium where pressing esc again on the URL bar will unfocus it. I know the default firefox behaviour is different, but chromium's implementation of this quality-of-life feature feels much better.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.17

### What platform are you seeing the problem on?

Linux, Windows

**Comment by lamteteeow** [comment]
would be nice if this issue can be solved ^^ Thanks for all the good work!

**Comment by lamteteeow** [comment]
I actually found a hacky workaround, which is using **F6**.
**F6** (in other browsers/thunderbird) is used to move to next **main UI area** (usually titlebar-sidebar-mainwindow). Somehow, it was used to switch focus between the **main window** and the **title bar** only, which is perfect for my use case. However, I don't know how to modify the shortcut since it's not presented in the shortcut menu.

**Comment by JSGRD22** [comment]
Funnily enough, same day @lamteteeow commented (today) I was doing some research on this and found the same solution. I also realised that (after 10 years!) the pull request for pressing esc to return focus to the website was added into nightly 1 month ago and should be implemented in firefox 133. Either way, it’s a firefox issue and it seems to be getting fixed very soon, so I will close the issue.
