### ISSUE TITLE
Tabs Do Not Expand On Hover After Toggling Compact Mode

### ISSUE THREAD

**Issue by Espasant3** [zen-browser/desktop#2569]
### Captchas

- [x] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### Description:
If you enable compact mode and disable it if you have in the appearance settings selected that tabs expand on hover, when compact mode is disabled, the browser will behave as if it had it set to "do not expand tabs by default".
### Steps to reproduce:

  1.  Open Zen Browser.

  2.  Activate Compact Mode using keyboard shortcut or directly from settings.

  3.  Deactivate Compact Mode using keyboard shortcut or directly from settings.

  4.  Ensure that in Look and Feel settings, in the "Sidebar and tabs layout" section the option for tabs to expand on hover is selected.
  5. Try to expand a tab on hover and check the settings.

### Expected Behavior: 
Tabs should expand when the mouse hovers over them even if i have enabled and disabled the compact mode.

### Actual Behavior: 
After deactivating Compact Mode, the browser behaves as if the "do not expand tabs by default" option is selected, despite the appearance settings being configured to expand tabs on hover.

### Alternative solution:
It could be warned that the compact mode changes the usage settings and when it is activated that it automatically switches to the "do not expand tabs by default" behavior. It will also need to be warned in the settings in the "Sidebar and tabs layout" section in the same way that expanding tabs on hover option is reported doesn't work in compact mode.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.17

### What platform are you seeing the problem on?

Windows, Linux

**Comment by Espasant3** [comment]
@dosu i found this problem too in linux (i forgot at first to put it in the issue so i edited later) which led me to think that it was somehow different,  but it is true that the core problem is the same as the issue you just mentioned so it cannot be considered a new issue.

**Comment by peter34245** [comment]
Same issue

**Comment by Espasant3** [comment]
As for version 1.0.1-a.22, I can confirm that the bug still persists.
