### ISSUE TITLE
Toggle Web Panel Button causes toolbar to not retract in compact mode

### ISSUE THREAD

**Issue by neurokitti** [zen-browser/desktop#2570]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.

### What happened?

https://github.com/user-attachments/assets/b77d5b9f-498d-435a-a6a4-992bb715f1e3

when the web panel toggle is clicked while the toolbar is in compact mode.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Version 1.0.1-t.17 (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by Richard-Woessner** [comment]
Confirmed on Twilight 1.0.1-t.17.

Seems to be when the side panel button is active it keeps the topbar active
