### ISSUE TITLE
bug with icons jumping across tool bar when rearanging

### ISSUE THREAD

**Issue by neurokitti** [zen-browser/desktop#2571]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

https://github.com/user-attachments/assets/6f99c332-8fe0-48f2-8350-dedf2cf0683a

when draging icons to the left side it can show up on the right. its funky.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Version 1.0.1-t.17 (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by LeMoonStar** [comment]
I can confirm this happening on non-twilight 1.0.1-a.17 as well.
