### ISSUE TITLE
Unable to add perplexity.ai as default search engine

### ISSUE THREAD

**Issue by otteep** [zen-browser/desktop#2572]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I'm trying to add perplexity.ai as a default search engine. Right-clicking to add it does not work. It also does not work using the "Search Engines Helper" extension. It works with other search engines such as Brave Search and Ecosia.
<img width="1249" alt="Screenshot 2024-11-01 at 23 33 20" src="https://github.com/user-attachments/assets/2f93dee2-1814-47be-a45a-445e717c1aef">

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.17 

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by shadowash8** [comment]
Hello @otteep 
Right click also doesn't give me a option to add perplexity but you can try adding perplexity using settings.

**Comment by tedbergstrand** [comment]
Here's how to add Perplexity to be your main search:

1. Go to your Zen Settings.
2. Click Search on the sidebar
3. Go down to the bottom (Search Shortcuts)
4. Click Add
5. Enter the Following:
  - Search Engine Name: Perplexity
  - Engine URL: https://www.perplexity.ai/search?q=%s
  - Alias: @perplexity
![Screenshot 2024-11-02 081951](https://github.com/user-attachments/assets/983d6290-5d24-45ca-b0cf-f2b04534c6d7)
6. Click Add Engine
7. Go to the top of the Search Settings Page and change the dropdown to Perplexity.
 
![Screenshot 2024-11-02 082136](https://github.com/user-attachments/assets/14147a6d-4e0b-4c63-81bf-3449f02ae27b)

Note: you can change your Keyword to whatever you want. This is what lets you search with a non-default search engine. For example, if I switch my default to Perplexity, I can still Google Search by typing @google at the beginning of my search query.

**Comment by otteep** [comment]
Thank you! Did not notice that Zen has this function to add engines from this menu, Firefox 132.0 (aarch64) does not have it.
