### ISSUE TITLE
[bug] Layout issues with Compact Mode enabled & Tabs on Right

### ISSUE THREAD

**Issue by alphabitserial** [zen-browser/desktop#2574]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Enabling compact mode is fine at first, but upon resizing the window the browser layout & webpage are both broken – the container for tabs is incorrectly shown and pushes the website's contents out of view. Toggling compact mode off/on, or mousing over the right side of the window to show tabs & then hiding them temporarily resolves the issue until the window is resized again or a new tab is opened.

This screenshot is with compact mode disabled:
![image](https://github.com/user-attachments/assets/29fa8d53-c4cd-4fbb-abc0-08eaf699c57a)

This one demonstrates the issue:
![image](https://github.com/user-attachments/assets/ae48751e-0f2b-4c4f-82df-2a3459392aa1)

This is how it looks when everything is working normally:
![image](https://github.com/user-attachments/assets/829d7372-88b8-4be6-8c3c-65c9268d63f8)

Note: I do not have any Zen Mods installed, so they may be ruled out as a cause for this issue. As far as I can tell this only occurs when tabs are set to display on the right-hand side of the window.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.17 on Arch Linux (zen-browser-avx2-bin AUR package)

### What platform are you seeing the problem on?

Linux

**Comment by 0x57e11a** [comment]
> Updating to version 1.0.7 might resolve these issues, as it includes fixes for similar layout problems by adjusting CSS properties for better alignment and visibility [[1]](https://github.com/zen-browser/desktop/blob/dev/src/browser/base/content/zen-styles/zen-compact-mode.css).

and this is why we dont trust ai

**Comment by alphabitserial** [comment]
You know what, I've stopped using Zen since I learned that the underlying Firefox version was _downgraded_ a few releases ago with **no indication** in the release notes. Good reminder that this issue has had no developer activity after 1 month though. While I wish the best for the project in the future, I probably won't be checking on it unless it manages to survive long enough to become mature.

**Comment by 0x57e11a** [comment]
> You know what, I've stopped using Zen since I learned that the underlying Firefox version was _downgraded_ a few releases ago with **no indication** in the release notes. Good reminder that this issue has had no developer activity after 1 month though. While I wish the best for the project in the future, I probably won't be checking on it unless it manages to survive long enough to become mature.

![image](https://github.com/user-attachments/assets/e6466822-7bab-4e3e-95dd-8d8c18d543b9)

\>uses alpha build of a relatively-new open source project
\>said alpha build is unstable and not fully documented
\>complains

**Comment by mr-cheffy** [comment]
This should be fixed now 👍🏽
