### ISSUE TITLE
Sidebar does not appear when hovered

### ISSUE THREAD

**Issue by ilahazs** [zen-browser/desktop#2579]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

As you can see on the video below, sidebar does not appear anymore when I hover the left side of browser on compact mode.

How to fix this? Is there any settings that i missed? I already tried disabling zen themes.

But it works when I'm not maximizing the wnidow :/

Maximize Window

https://github.com/user-attachments/assets/0c81f7a4-adf1-46f2-89ad-ae2d9194157d

Not Maximize Window

https://github.com/user-attachments/assets/6f333276-19ff-4d75-bb93-ab67ccbc5f49

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a15

### What platform are you seeing the problem on?

Linux

**Comment by Richard-Woessner** [comment]
Working for me on Twilight 1.0.1-t.17 
What Distro of Linux are you using?

**Comment by ilahazs** [comment]
> Working for me on Twilight 1.0.1-t.17 What Distro of Linux are you using?

Thanks for the respond, I'm using MX Linux KDE.

I don't know why this happened. 

I've already fixed it by creating a new profile :/
