### ISSUE TITLE
Onboarding: allow me to select "system theme" instead of light or dark

### ISSUE THREAD

**Issue by jkjustjoshing** [zen-browser/desktop#258]
### What feature would you like to see?

On the "Make yourself at home" page, I have to pick light or dark mode. I have macOS set up to switch between modes at night and during the day, and I want my browser to match my system color scheme.

If this determines how the browser treats `prefers-color-scheme` media queries on websites, this is an even higher priority request. If websites will still honor my system setting then it's less urgent.

### What platform are you seeing the problem on?

macOS

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/872

 ~ This is an automatic operation to better enhancements requests organization.
