### ISSUE TITLE
REQUEST: I need the old switch to next tab in keyboard shortcuts

### ISSUE THREAD

**Issue by rbjnazz** [zen-browser/desktop#2581]
### Captchas

- [ ] I have read the instructions.
- [ ] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

The early version of Zen had the option in the keyboard shortcuts to switch to next tab.
Behavior: Switch to next tab then if the current tab is the last go to the first tab. 

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.17

### What platform are you seeing the problem on?

Windows

**Comment by salamijason** [comment]
I believe these will be added back soon since there were a couple PRs for it.
