### ISSUE TITLE
Only Create New Tabs When a URL is Loaded

### ISSUE THREAD

**Issue by lugenx** [zen-browser/desktop#2582]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

In Zen Browser, pressing `Cmd+T` immediately creates a new blank tab, even if no URL is entered. This results in empty tabs accumulating in the tab bar, leading to workspace clutter, especially when tabs are opened by habit but left unused.

**Expected Behavior:**
Adopt behavior similar to Arc Browser, where pressing Cmd+T opens a URL entry field, but no new tab is created unless a URL is entered and loaded. If the user exits the URL entry without typing anything, no tab should be added to the tab list.

**Benefits:**
This change would prevent empty tabs from building up, helping users maintain a cleaner, more organized workspace with only active tabs displayed.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.17 (Firefox 132.0)

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by Richard-Woessner** [comment]
Not technically an issue but a valid potential feature. Please consider mentioning this in the GitHub discussions or the discord
