### ISSUE TITLE
Sidebar hover and right click makes the sidebar dissapear

### ISSUE THREAD

**Issue by Shamatix** [zen-browser/desktop#2587]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

If I use the following options:
![image](https://github.com/user-attachments/assets/0f29623e-924f-4e9f-aebf-9d849f98d7a1)
![image](https://github.com/user-attachments/assets/b0b4f638-1154-4baf-87fe-488f352aa14d)

And I right click the sidebar it closes
https://i.imgur.com/Y5LoIiH.gif

There also is a more annoying thing 
if you hover your cursor a bit outside the window it closes the sidebar for a split second:
https://i.imgur.com/dpRpt08.gif

In Arc neither is the case:
https://i.imgur.com/beemw9M.gif

Makes it quite easier to use the sidebar in compact mode if it wouldn't "hide / be annoying" :p

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Version 1.0.1-a.17 (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by matthewtapps** [comment]
I keep my tabs on the right side of the screen, and have noticed that the popup text when hovering over a specific tab also interferes with the hover, so it becomes quite difficult to navigate (especially between essential tabs which are horizontally next to each other so moving the cursor from one to the next results in the hovered tab bar closing). This doesn't appear to happen for the tab hover popup text when the tabs are on the left, though.

I am interested in trying to contribute to the Zen browser project so if anyone can point me in the right direction for addressing some of these hover issues I am keen to take a look!
