### ISSUE TITLE
Copy the urls of a set of selected tabs

### ISSUE THREAD

**Issue by extropyst** [zen-browser/desktop#259]
### What happened?
When you want to share (or insert into a document for example) a set of URLs for certain tabs, it would be useful to be able to select them (with CTRL + SHIFT + CLICK), and once selected be able to copy the batch of tabs. So as not to have to copy them one by one, and thus save time on this type of recurring user tasks.

### What feature would you like to see?
Add a "Copy Selected Tabs" option to the context menu of selected tabs.

### What platform are you seeing the problem on?

Linux

### Additional context

I attach a screenshot with the place I am referring to.

![image](https://github.com/user-attachments/assets/e0f84152-0b39-4f9d-a055-069bc382a12f)

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/871

 ~ This is an automatic operation to better enhancements requests organization.
