### ISSUE TITLE
Video Emebeds fail to play

### ISSUE THREAD

**Issue by neurokitti** [zen-browser/desktop#2593]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

https://github.com/user-attachments/assets/51b77666-0678-43a6-b398-2c24894d5e8e

in all places there have been embeds from youtube it does this.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-t.17

### What platform are you seeing the problem on?

Windows

**Comment by Lqnk4** [comment]
I'm running into this issue as well, on Linux version 1.0.1.a.19-1
The issue occurs from video sources other than youtube as well
