### ISSUE TITLE
Scroll Bar not working in vertical tabs

### ISSUE THREAD

**Issue by VimYoung** [zen-browser/desktop#2596]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The scrollbar in the vertical tabs have became quite sleek and good, I generally use touchpad gestures for navigating if there are too many tabs. But I noticed that moving the tab list from scrollbar is not happening and rather changing the window size on linux. Following video shows the same (I tried scrolling 4-5 times in it).

https://github.com/user-attachments/assets/d8d7b429-2060-4c91-8d83-2a4a24d51277
**Also** there are 2 new tab buttons in the tab bar rather than one, it looks odd( if intentional).

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.17 

### What platform are you seeing the problem on?

Linux

**Comment by VimYoung** [comment]
Just noticed that clicking on scrollbar area on top and bottom of it brings the bar to that place. So, only dragging of the bar doesn't seems to work.

**Comment by Brasonite** [comment]
This is happening to me as well. I'm running version 1.0.1-a.19 (64-bit) on Windows 11. I can't drag or click the scrollbar.

**Comment by VimYoung** [comment]
Closing the issue, as I moved from gnome and doesn't use it anymore, my current wm doesn't have this issue.
