### ISSUE TITLE
Incorrect image for "Hide Tab Bar" and "Hide Top Bar" in Theme Settings

### ISSUE THREAD

**Issue by hzchng** [zen-browser/desktop#2597]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I noticed that there is a bug in UI where the image for both "Hide Tab Bar" and "Hide Top Bar"  options in Theme Settings are swapped, which is shown in the screenshot.

![image](https://github.com/user-attachments/assets/41cd2c4e-f6ea-48b5-b7e8-95bc2229b5a6)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.17

### What platform are you seeing the problem on?

Linux

**Comment by n7itro** [comment]
The images show what remains, not what gets hidden

**Comment by hzchng** [comment]
I see, understand. Thanks for clarifying.
