### ISSUE TITLE
Easier access to switch spaces and spaces rename

### ISSUE THREAD

**Issue by Anthonyy232** [zen-browser/desktop#260]
### What feature would you like to see?

Hi, would it be possible to get an option to change the switching of spaces to icons so it goes from two clicks to one click? Something like how ARC does it, or something else if you have something better in mind -- ease of access is ideal. This could be an option toggle in the settings or something for the current method or this method. I'm not sure if this is in your vision for the browser, just putting this out there.
![image](https://github.com/user-attachments/assets/af26b17b-6e97-4dda-af2d-c30be828f64a)

Also, any option to rename default space/delete default space? I like to have a home and a work space, but this is seems to be the limit I could change it to.
![image](https://github.com/user-attachments/assets/cc163605-0fa0-40c7-9c68-f8197a54cc13)

### What platform are you seeing the problem on?

Windows

**Comment by lazymonkey2** [comment]
please design it so that it works with many workspaces, like 20 or more.

**Comment by Anthonyy232** [comment]
I'm not really sure how that would be possible while maintaining a one click access functionality

**Comment by guigirl42** [comment]
I'm not a coder, but conceptually it [one click] would be possible IF it's possible to have _hovering_ over the Workspaces button then automagically pop-up a menu list of all extant Workspaces, for the user to then simply move her pointer down / along the list to click on her desired one.

**Comment by FabiKel** [comment]
That would be great. I use Sideberry and have the spaces at the top too. I think it is wasted _space_ to have a single big button to switch between workspaces.

![grafik](https://github.com/user-attachments/assets/74103073-5dd2-401b-ab08-45a882eba736)

**Comment by ChristinWhite** [comment]
I use the Horizontal workspaces option in Sideberry, similar to how [SigmaOS](https://sigmaos.com/) does it, which works really well for a lot of workspaces. That would be my preferred pattern, especially if #279 is implemented.

![CleanShot 2024-08-23 at 14 16 31@2x](https://github.com/user-attachments/assets/452c3978-707d-4949-92ad-c7f28332ddcf)

**Comment by Hate9** [comment]
Yeah, I'd ideally want this to work like it does in the above comment. That's also how it works in Opera and Floorp, and this feature is actually the only feature keeping me from switching to Zen from Floorp.

Alternatively, I'd also be fine with it working more like Simple Tab Groups (at least when it's used as a sidebar for vertical tabs), where you can click on the top to switch your tabs list to a list of your workspaces.

Either is fine, but the current option is definitely *very* lacking.

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/870

 ~ This is an automatic operation to better enhancements requests organization.
