### ISSUE TITLE
Can't see downloads in Toolbar

### ISSUE THREAD

**Issue by h2110100** [zen-browser/desktop#2603]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I should see downloads in tool bar but its not there, it doesn't show up in customizing toolbar nor when i finished downloading something. Also doesn't show up after I tried reset to default on the toolbar, discord link to video (in zen server) : https://discord.com/channels/1088172780480114748/1301915760884449341/1302115337919266851

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.17

### What platform are you seeing the problem on?

Windows

**Comment by ManuaL46** [comment]
I'm still seeing this same issue on version `1.7.2b`
I'm assuming this was fixed and has somehow broken again.
