### ISSUE TITLE
Information box glitch

### ISSUE THREAD

**Issue by adouche-dmg** [zen-browser/desktop#2605]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Hello, I recently installed Zen on my late 2011 MacBook Pro running macOS Catalina.
First, thank you for this amazing browser, it's much better than Safari.
I discovered a major bug : when an info box shows up, I can't interact with it. It seems like it glitched in the top bar. Here's a video :

https://github.com/user-attachments/assets/b38bef69-65cb-4e56-8576-291689e3bccf

Thank you for your help.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.17

### What platform are you seeing the problem on?

macOS - Intel

**Comment by RayZ3R0** [comment]
Do you have this in every website? Can you try using a new profile?

**Comment by adouche-dmg** [comment]
> Do you have this in every website? Can you try using a new profile?

Hello,
It does it most of the time. I just noticed that if I place my cursor somewhere behind the box, I can interact with it. It seems like the box is higher than expected ?
I've tried reinstalling Zen and creating new profile.

**Comment by adouche-dmg** [comment]
Hello, the problem disappeared after a complete reset of my computer, I reinstalled Zen and it no longer seems to happen.
