### ISSUE TITLE
Render flickering

### ISSUE THREAD

**Issue by kantum** [zen-browser/desktop#2610]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

CSS is doing something weird when scrolling. Does not happen on Firefox.

Full screen needed to see it well:

https://github.com/user-attachments/assets/2db37957-7abb-49a9-b850-2efea649e1e2

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.17 (Firefox 132.0)

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by mauro-balades** [comment]
Could you show a smaller and more precise image? This one is too generic and not in the range of scale

**Comment by kantum** [comment]
Somehow, this has been resolved 🤷‍♂️
