### ISSUE TITLE
Blury Webpages on a 32:9 window 

### ISSUE THREAD

**Issue by CocoPoops** [zen-browser/desktop#2611]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When loading webpages parts on the page get blurred when the browser windows in is a ratio of 32:9
![image](https://github.com/user-attachments/assets/25e13288-7b72-4b69-bbe4-da836aed0579)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1.a.17

### What platform are you seeing the problem on?

Linux

**Comment by FujiwaraChoki** [comment]
This issue is still appearing.
