### ISSUE TITLE
Semi-Transparent horizontal bar at the top of the new tab page.

### ISSUE THREAD

**Issue by extropyst** [zen-browser/desktop#262]
### What happened?

When you scroll to the bottom of the new tab page, a semi-transparent horizontal bar appears at the top of the page.

### What feature would you like to see?

Let this imperfection be corrected, as it is a distraction when it appears.

### Additional context

This happens when both the "Recent Activity" and "shortcuts" options are activated and more than 3 rows of shortcuts are added (3 or 4 rows).

I attached a screenshot where you can see what I mean.

![image](https://github.com/user-attachments/assets/c6a8fc4a-e621-4e0f-a47e-406124a2b09e)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.19

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
This is part of the design firefox is using, you can submit a bug report to them 👍🏽
