### ISSUE TITLE
Typo in Settings > Shortcuts (about:preferences#zenCKS) for Bookmark Tabs

### ISSUE THREAD

**Issue by 0xEddie** [zen-browser/desktop#2621]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I believe the third row in `History & Bookmarks` should say "Bookmark All Tabs" or something similar
![image](https://github.com/user-attachments/assets/61960ae5-f787-4745-8b3c-50a76b124c79)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.17

### What platform are you seeing the problem on?

Windows

**Comment by GunGunGun** [comment]
Actually both shortcuts mean bookmark this page, but the 2nd one with more customization (a dialog to change name and tagging).

**Comment by lamteteeow** [comment]
@GunGunGun for me it means "Bookmark all tabs into a folder".
