### ISSUE TITLE
FireFox PWA extension runtime is not recognized even after being installed 

### ISSUE THREAD

**Issue by tanaybhomia** [zen-browser/desktop#2623]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![image](https://github.com/user-attachments/assets/13a18309-fb7f-4273-aa93-b10104026782)
I am using the flatpak version of the app and the app details are above. I have already installed the extension and is working fine on the default firefox app but is not being recognized in the zen browser 
![image](https://github.com/user-attachments/assets/a93e98c1-94aa-427b-bf56-7e3880277976)
![image](https://github.com/user-attachments/assets/7bbd2019-c824-4c9e-ba97-a29f840a5b52)
I have also given all the file permission to the zen browser using flatseal but the extension is still not recognized. Please look into it as I dont want to basically run 2 browser all the time using all my ram. And one thing I noticed is that the extension runtime is recognized when running the app Image version of it. What can I do to resolve this ?

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1.a.17

### What platform are you seeing the problem on?

Linux

**Comment by CrossScarDev** [comment]
I'm pretty sure this is a bug with Firefox PWA, not Zen Browser.

**Comment by tanaybhomia** [comment]
But this extension is working fine with the base firefox.

**Comment by CrossScarDev** [comment]
Oh yeah, there seems to be a issue with all apps with connectors.

**Comment by tanaybhomia** [comment]
so this is a zen issue ?

**Comment by tanaybhomia** [comment]
The extension works without any problems on Beta versions

**Comment by fmarkulin** [comment]
This is still an issue

**Comment by Dev-in-the-BM** [comment]
I have the same problem

**Comment by Firnthon** [comment]
1.14.9b (Firefox 141.0) flatpak, Pop!_OS 22.04 LTS - issue can be observed. On Firefox 141.0 (64-bit) .deb installation addon is working.

**Comment by Lyokocentipoid** [comment]
I recently changed my Firefox from Snap to Flatpak. Now I can't use FirefoxPWA. I have also reinstalled the package

**Comment by Gitama-Senjou** [comment]
Guys flatpaks are sandboxed you need to share the path to the  pwafirefox extension on your system , i dont know where it is tho .

**Comment by onfaitr** [comment]
same problem with windows

**Comment by Dev-in-the-BM** [comment]
Why was this closed?
