### ISSUE TITLE
Multiple new tab button

### ISSUE THREAD

**Issue by aphelei** [zen-browser/desktop#2624]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

There are 2 new tab buttons

![image](https://github.com/user-attachments/assets/0773ba8d-c915-4684-86d8-185f25e6b4c7)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.17

### What platform are you seeing the problem on?

Linux

**Comment by RayZ3R0** [comment]
You can remove either one or both if you want. The top one is removed from the settings
![image](https://github.com/user-attachments/assets/d55a70da-868d-4aca-bf70-c536e024e272)
the bottom one can be removed by right clicking on the sidebar and customize toolbar, drop it in the overflow menu

**Comment by jessedobbelaere** [comment]
I also experienced two New Tab buttons since `1.0.1-a.16` or `1.0.1-a.17`. 
Not great that it is introduced suddenly, had to search on github, but at least they can be hidden indeed 👍 Fixed it for me!
