### ISSUE TITLE
last update (to 1.0.1-a.14) reset "How to expand tabs" setting

### ISSUE THREAD

**Issue by fautore** [zen-browser/desktop#2626]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Checked for other open issues and did not find any related issues.
Description:
Updated to new version (1.0.1-a.14).
After updating, the settings for "Sidebar and tabs layout" > "How to expand tabs" were reset to default "Expand Tabs by Default".
I do realize this is not a particularly pressing issue, but i suspect it might reset to default other settings but i couldn't notice since my zen settings are pretty much the default.

Issue is related to Zen directly, and as such is not reproducible on Firefox.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.14

### What platform are you seeing the problem on?

Windows

**Comment by GunGunGun** [comment]
Latest Zen is a17, sorry but we don't think we could afford to debug an older version

**Comment by fautore** [comment]
I'll close the issue,
feel free to re-open in case the problem arises again with newer versions.
thank you.
