### ISSUE TITLE
Vertical tab bar cut off when using compact mode

### ISSUE THREAD

**Issue by Flapperoo** [zen-browser/desktop#263]
### What happened?

With:
Enable Zen Browser's Compact Mode = On
Hide the top toolbar as well in Compact Mode = Off

The vertical tab bar is cut off:
![image](https://github.com/user-attachments/assets/dc2154f4-9f21-4dfb-a870-e4096a56c5cc)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.19

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by Anthonyy232** [comment]
Duplicate of https://github.com/zen-browser/desktop/issues/256

**Comment by mauro-balades** [comment]
Thanks anyways!
