### ISSUE TITLE
Tab name weird padding

### ISSUE THREAD

**Issue by wiraki** [zen-browser/desktop#2636]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The text and icons of tab is not properly aligned. See in the screenshot how the text is almost touching the bottom border of the active tab surrounding box:

![image](https://github.com/user-attachments/assets/22a95a92-0707-4550-9985-9b0a56efa0ac)

Using the flatpak on linux.

I tried disabling all the zen mods, closing and re-opening the browser etc., but I couldn't figure out what is causing it.

Thanks for your efforts!!

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.17

### What platform are you seeing the problem on?

Linux

**Comment by Richard-Woessner** [comment]
Hey @wiraki Im having trouble replicating this bug, can you send a screenshot of the entire browser?

**Comment by wiraki** [comment]
Hey, thanks for the quick reaction. Here's a screenshot, took the opportunity to show the zen mods in case it's helpful. Although as mentioned, turning them all off did not solve the issue.

![image](https://github.com/user-attachments/assets/d45ca1c8-4ebd-43fc-8f38-7884f510d5d6)

Now I just tried loading another profile with default settings, and the issue is gone there. So it must be some setting/customization in my profile that is causing it. Do you have any idea where I should look? 

Edit: now with the screenshot

**Comment by Richard-Woessner** [comment]
Okay I was trying to see why your tabs are so different from mine and I can see now you have a addon installed

https://zen-browser.app/mods/d8b79d4a-6cba-4495-9ff6-d6d30b0e94fe

Are you sure its turned off?

**Comment by wiraki** [comment]
Yes, here is the same with mods off.

![image](https://github.com/user-attachments/assets/0a7d74e8-d1f9-4f52-904f-65b6f97e5d0d)

**Comment by Richard-Woessner** [comment]
Okay so with the mod turned off it looks fine is that what you were asking?

**Comment by wiraki** [comment]
> Okay so with the mod turned off it looks fine is that what you were asking?

No, it doesn't. In my last screenshot, you can see that the icon and tab name is not centered vertically in the box that highlights which tab is selected. 

However, I found what is causing it:

1. Right click in empty UI space
2. Select "Customize Toolbar"
3. At the bottom, set density to "Compact"

It does say that it is not supported. I don't remember doing this, maybe it was a miss-click  while customizing other things. Switching back to other densities fixes it :+1:

**Comment by Richard-Woessner** [comment]
Ahh thank you and great job finding the issue. Definitely something we should consider. Thanks

**Comment by Richard-Woessner** [comment]
Moving this to Todo so we can remove Firefox compact mode, as we do not support it.

Thanks @wiraki
