### ISSUE TITLE
Twitch freezing in Zen

### ISSUE THREAD

**Issue by Halambic** [zen-browser/desktop#2638]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I'm experiencing an issue when playing a game on my primary monitor and watching a Twitch stream on my secondary monitor using Zen Browser. The stream frequently freezes, leaving only the audio playing. I'm forced to refresh the stream to restore the video, but after a while, the stream freezes again.

My OS is Windows 11

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.17

### What platform are you seeing the problem on?

Windows

**Comment by salamijason** [comment]
Hey are you still getting this issue on version a22 (the latest as of this comment)

**Comment by salamijason** [comment]
No response in 2 weeks, will be closing this issue. Please reopen if you still get the bug.
