### ISSUE TITLE
1.0.0-a.19 breaks bookmarks on Windows 11

### ISSUE THREAD

**Issue by mayemu** [zen-browser/desktop#264]
### What happened?
Ever since updating, the themed coloring on the bookmarks bar turned grey not matching the rest of the color theme, making it look very ugly

![kVNMkSt](https://github.com/user-attachments/assets/8b6f20f4-7d20-455c-b886-0a7c36177bff)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.19

### Severity impact

High

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
Fixed for version 20, currently building! Thanks
