### ISSUE TITLE
Zen-Components just went private.

### ISSUE THREAD

**Issue by mithom** [zen-browser/desktop#2640]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

i was browsing the zen-browser/components repository, and now i am receiving a 404 page, which means the repository most likely went private.
As this is an open source project, hiding the component code is very suspicious and would at least require an explanation.
I will be turning off automatic updates until this is resolved.
I sincerely hope this is an issue on my end, or an accident.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.a17

### What platform are you seeing the problem on?

Windows

**Comment by omove** [comment]
https://github.com/zen-browser/desktop/commit/ec65a6949659eb53f683d628d358c923fcd98a18 was right before you opened this issue, it moved the components into the main repo.

**Comment by mithom** [comment]
Okay did not see that, what a coïncidence, appologies for this issue then
