### ISSUE TITLE
Browser fails to reopen after restoring default shortcuts and restarting

### ISSUE THREAD

**Issue by Spoilt** [zen-browser/desktop#2643]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I have two profiles, let's call them A (default) and B.

1. I was adjusting settings on profile B.
2. Profile A had 2-3 tabs open.
3. I modified the first shortcut (Ctrl+Alt+T).
4. I clicked "Restore Default," then selected "Restart Now."
5. Only the profile B window closed.

After that, I tried to reopen profile B, but the browser wouldn't load—it only showed a black background with the Z logo.

To resolve the issue, I had to remove `zen-keyboard-shortcuts.json` from `AppData/Roaming/zen/Profiles/[profileB]/`.

Here is the broken shortcuts file for reference: [zen-keyboard-shortcuts.BROKEN.json](https://github.com/user-attachments/files/17623572/zen-keyboard-shortcuts.BROKEN.json)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.17

### What platform are you seeing the problem on?

Windows

**Comment by salamijason** [comment]
Yo sorry for not responding earlier, there have been hundreds of issues. Are you still getting this on the latest version of zen alpha?

**Comment by salamijason** [comment]
No response in 5 days, will be closing this issue. Please reopen if you still get the bug.
