### ISSUE TITLE
Left Active Window borders in Split View doesn't render correctly.

### ISSUE THREAD

**Issue by Spacellary** [zen-browser/desktop#2647]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Active Window borders on the left side in Split Vew won't render correctly. the side bar overlaps over it as can been seen in screenshot number 2.

1. Right window active: <br> ![zen_9fQJocJpNa](https://github.com/user-attachments/assets/845d9e14-e593-4445-a8f6-252d12f4517c)

2. Left window active: <br> ![zen_V2hCoOHwcZ](https://github.com/user-attachments/assets/169da51d-69e9-4072-a6af-9628dd08183f)

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

133.0b4 (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by Axenide** [comment]
This is actually happening only when the Tab Sidebar is expanded, both with split and normal views.

https://github.com/user-attachments/assets/8d1d1878-c599-4bc4-a357-9e57724dab81

**Comment by jltrapp-tamu** [comment]
Until this gets fixed, you can add this to your userChrome.css
```css
/* Fix left border being overwritten */
#zen-tabbox-wrapper {
    margin-left: 2px;
}
```

**Comment by maxthyron** [comment]
Same thing happens even without split view, the tabpanel seems to cut off the viewport.

Found [c5b6376](https://github.com/zen-browser/desktop/commit/c5b6376980d5c0e8eff59f4743fca47688968981#diff-d7c25fb86c99f9f34780397778df2a6248b948b1b973033e3cb170bd7a9e0f5cR16), but 1px is too small and not really the source, I think

And [c3b902a](https://github.com/zen-browser/desktop/commit/c3b902ae65243e93789eae24d9136bc791b53e7b#diff-5f8c218ca0d93825c6bde469da02e588901ced52df710d3f21b65c61d09f2c6cR48), which cuts the outline

So far my userChrome with fix for this looks like this and looks fine:

```
#tabbrowser-tabpanels[zen-split-view='true'] > [zen-split='true'], #zen-splitview-dropzone {
  margin: calc(var(--zen-split-column-gap) / 2) calc(var(--zen-split-row-gap) / 2 + 1px) !important;
}

:root:not([inDOMFullscreen='true']):not([chromehidden~='location']):not([chromehidden~='toolbar']) {
  & #tabbrowser-tabpanels {
    padding-left: var(--zen-element-separation) !important;
}
```

**Comment by Spacellary** [comment]
Feedback from:

Twilight build - 1.0.1-t.19 (2024-11-13 at 00:12:19)

**Seems to be fixed.** Waiting for others to share.

Right panel:

![zen_imxPBGIfmE](https://github.com/user-attachments/assets/56a7985c-4dc5-4e36-8132-1bd0ae05b908)

Left panels:

![zen_AjTz91MJL7](https://github.com/user-attachments/assets/25ce6996-3a46-4482-979f-fc45f8e63263)

![image](https://github.com/user-attachments/assets/0434c589-28b7-4902-97aa-8b6d757d3b36)

**Comment by Spacellary** [comment]
Feedback from:

Twilight build - 1.0.1-t.20 (Firefox 132.0.2) (2024-11-26) (64-bit)

Issue PERSISTS.

**Comment by salamijason** [comment]
was unable to recreate this in a22, fresh profile: ![Image](https://github.com/user-attachments/assets/136ceec9-bfd7-49e4-ba36-6690e9311d9b)

was unable to recreate this in twilight 1.0.2-t.0, fresh profile![Image](https://github.com/user-attachments/assets/ef71754c-1583-4d4d-9d71-50f41dad0ddc)


Please let me know if ya'll are still getting the issue.

**Comment by Axenide** [comment]
I'm not experiencing this issue anymore in either Stable or Twilight.

**Comment by Spacellary** [comment]
![zen_5vQjgfuDMP](https://github.com/user-attachments/assets/95009471-1237-4880-bbd3-df6f4d6027de)
![zen_cM44cPE5Pg](https://github.com/user-attachments/assets/a7fbbb49-09f5-4a84-bd16-081f428418b6)

### 1.0.2-t.0 (Firefox 133.0) (2024-12-10) (64-bit)

#### Seems to be fixed here.

**Comment by salamijason** [comment]
Understood, thanks for the info!
