### ISSUE TITLE
Sidebar sites with different containers.

### ISSUE THREAD

**Issue by DareDevil2000** [zen-browser/desktop#265]
### What feature would you like to see?

If it's possible to add the multi account features on the sidebar websites so I can open different websites in different containers.

### What platform are you seeing the problem on?

Windows

**Comment by legendboyAni** [comment]
I need this fast containers are the big part of why i use firefox or firefox based browser

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/868

 ~ This is an automatic operation to better enhancements requests organization.
