### ISSUE TITLE
Cannot watch anything on netflix

### ISSUE THREAD

**Issue by lavishyay** [zen-browser/desktop#2653]
### Captchas

- [x] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Whenever I try to watch something on netflix using Zen, I get an error saying "The title is not available to watch instantly. Please try another title" for all the shows, with the error code e100
![image](https://github.com/user-attachments/assets/55c54cae-c7ea-40ad-8d88-4ddab893f407)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.17

### What platform are you seeing the problem on?

Windows

**Comment by mogita** [comment]
Can confirm this is reproducible on macOS 15.0 with Zen Browser 1.0.1-a.17.

**Comment by neurokitti** [comment]
This Issue is due to DRM (Digital Rights Management) which controls access to copyrighted material. Zen Browser still needs approval so that DRM content will play in the browser. Google Controls this so if you want more information check out this: https://developers.google.com/widevine/drm/overview 

In essence this issue cant be fixed until Zen gets approval from Widevine and Google is not making it easy.

**Comment by Grace-coder311** [comment]
Was this bug ever resolved? I am having issues with Netflix on Zen. My netflix account works perfectly fine on Chrome


<img width="2476" height="1254" alt="Image" src="https://github.com/user-attachments/assets/913ecc16-1d81-4069-b9ad-9222f02e1620" />

**Comment by Puddle-11** [comment]
> Was this bug ever resolved? I am having issues with Netflix on Zen. My netflix account works perfectly fine on Chrome
> <img alt="Image" width="2000" height="1254" src="https://private-user-images.githubusercontent.com/74391976/494963617-913ecc16-1d81-4069-b9ad-9222f02e1620.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQ2MzYyMDUsIm5iZiI6MTc2NDYzNTkwNSwicGF0aCI6Ii83NDM5MTk3Ni80OTQ5NjM2MTctOTEzZWNjMTYtMWQ4MS00MDY5LWI5YWQtOTIyMmYwMmUxNjIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMjAyVDAwMzgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5MmZlNzZiNzdlMDNlOWEyZDFlNDFmYzQ3NjY3YTIyZmQwZGI3YmEyOTc0MjM3MzQwYTk5ZjM0MTdjM2E4MDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kbewRMffR050_hBoXk-jqg-kE1WVd_XIuSS9iS7IdyY">

im having the same error code + sometimes im getting the e100 error code. Iv enabled drm and changed as many settings as i can but its still not working, im assuming zen still hasnt been approved

**Comment by furtonb** [comment]
Same error code, same problem on my end. I'm on `Version 1.17.15b (64bit)` (latest build according to the settings at the moment). 
@neurokitti is there any news to share on the Widevine approval process (an ETA perhaps) ?
