### ISSUE TITLE
New tab created on shifting workspaces

### ISSUE THREAD

**Issue by wysh3** [zen-browser/desktop#2655]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

im on a pinned tab in a workspace but if shift workspaces back again it creates a new tab rather than staying on the same pinned tab

https://github.com/user-attachments/assets/39242037-4bfb-4580-9ff8-4cb62ae6a5ce

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.17

### What platform are you seeing the problem on?

Linux

**Comment by omarkily** [comment]
wth are you watching on yt?

**Comment by wysh3** [comment]
This was fixed
