### ISSUE TITLE
Tab Management Issue

### ISSUE THREAD

**Issue by Benilin-B-A** [zen-browser/desktop#2658]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

While performing the action, Ctrl+[Left CLick] on a link, the link is opened like a popup (like a picture in picture mode) and while closing this popup, the browser switches automatically to the next tab similar to the behavior when the current tab is closed.

It would be better to stay on the tab we were browsing on. The screencast of the issue is submitted below.

[Zen - Tab Handling.webm](https://github.com/user-attachments/assets/09938442-10c3-4816-b803-b6555ce43b4b)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.17

### What platform are you seeing the problem on?

Linux

**Comment by Benilin-B-A** [comment]
Is this a bug @dosu?

**Comment by Benilin-B-A** [comment]
What is the procedure for this to be filed as a requirement for future updates? @dosu

**Comment by JoseBritto** [comment]
Imo, the problem here is seeing the tabs pop out, it would be better if the tab popup did not open in this case. That way opening preview link looks seemless and converting the preview into a full tab would be seemless as well.

My proposal is to not show the tab popup when opening link preview, or when using the split view. Right now both opens it and it looks kinda off.

**Comment by kwilcz** [comment]
@Benilin-B-A already fixed in the next release.

**Comment by Benilin-B-A** [comment]
@kwilcz Great. Looking forward to it

**Comment by RayZ3R0** [comment]
Duplicate of #(I dunno man, no one checks for duplicates so there's a lot). Closing as it will be fixed in a18 soon. This feature is called glance, you disable or change the key from ctrl to something else from settings. Search for glance in settings
