### ISSUE TITLE
Make the sidebar independent.

### ISSUE THREAD

**Issue by DareDevil2000** [zen-browser/desktop#266]
### What feature would you like to see?

Is it possible to make the sidebar independent, like it will have its own search bar and there will be option to open a new tab in the sidebar from sidebar .

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/867

 ~ This is an automatic operation to better enhancements requests organization.
