### ISSUE TITLE
Add Arabic language to Translation

### ISSUE THREAD

**Issue by gam-phon** [zen-browser/desktop#2662]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Add Arabic language to Translation.
![CleanShot 2024-11-05 at 16 08 51@2x](https://github.com/user-attachments/assets/6110f3ad-67d2-47f8-9759-c69d7e4e509a)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.17

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by realSilasYang** [comment]
Call for Chinese too!

**Comment by cheeeebs** [comment]
This is a Firefox issue, go to Mozilla for feature suggestions on this since it's their tool.

**Comment by gam-phon** [comment]
@cheeeebs From where I can open this issue to Firefox? Do you have a link?

**Comment by BramLeisink** [comment]
I suggest going to the official Mozilla forum. This page might be a good page to start: https://connect.mozilla.org/t5/ideas/add-more-languages-to-firefox-translations/idi-p/7700

**Comment by gam-phon** [comment]
@BramLeisink Thanks
