### ISSUE TITLE
[Bug] Right Click Sidebar in Compact Mode.

### ISSUE THREAD

**Issue by greedjesse** [zen-browser/desktop#2663]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.

### What happened?

When 'Compact Mode' is enabled and either 'Hide Sidebar' or 'Hide Both' is selected, right-clicking the sidebar and hovering over the right-click menu causes the sidebar to slide out.

https://github.com/user-attachments/assets/91d08cb2-79e9-42d4-95db-e050cbafd324

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.17 (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by salamijason** [comment]
Was able to recreate this on a22 linux. Thanks for pointing this out!
