### ISSUE TITLE
[twilight] if a tab is pinned to essentials it can no longer be pinned regularly

### ISSUE THREAD

**Issue by neurokitti** [zen-browser/desktop#2667]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

https://github.com/user-attachments/assets/e2116417-cb06-49b2-98b4-e843337ad5c8

If you pin a tab to essentials it can no longer be pinned to regular pins as the pin button just pins it to esentials

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-t17

### What platform are you seeing the problem on?

Windows

**Comment by neurokitti** [comment]
fuck this shit its getting a rewrite

**Comment by neurokitti** [comment]
unfuck this shit apparently this may be the rewritten version idk at this point

**Comment by neurokitti** [comment]
@kristijanribaric

**Comment by neurokitti** [comment]
![image](https://github.com/user-attachments/assets/53de4042-9a57-4a05-82dd-75b927f0c5d2)

minor addition that doesn't deserve its own issue but this probably needs to be changed as now the setting is usless

**Comment by kristijanribaric** [comment]
Should be fixed by https://github.com/zen-browser/desktop/pull/2665

**Comment by neurokitti** [comment]
minor addition that doesn't deserve its own issue but this probably needs to be changed as now the setting is usless
