### ISSUE TITLE
Floating side panel is out of bounds

### ISSUE THREAD

**Issue by FabiKel** [zen-browser/desktop#267]
### What happened?

If the panel is not pinned, it is larger than the actual browser window. I have also tested it without any addons.

https://github.com/user-attachments/assets/d3d91c1a-7c56-4a9f-81da-0e86b7ec368f

I also noticed that the side panel opens again when you try to close it using the button in the table bar.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.19

### Severity impact

Medium

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
Fixed for next release 👍
