### ISSUE TITLE
Text rendering is blurry and glitchy on second monitor

### ISSUE THREAD

**Issue by radiosilence** [zen-browser/desktop#2671]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When Zen is open on my second monitor, on page load quite a lot of text is kinda blurry. Selecting the text or causing a redraw of it seems to make it rendered correctly.

Monitor is an Asus ProRes.

<img width="433" alt="Screenshot 2024-11-05 at 16 31 16" src="https://github.com/user-attachments/assets/da83c1d6-7d83-469d-bba4-2e44b070994c">

(Firefox in foreground, Zen in background)

https://github.com/user-attachments/assets/9b74f26e-8463-4750-8783-baf3354ed25c

Screenshot and video provided that demonstrate issue.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.17

### What platform are you seeing the problem on?

macOS - Intel

**Comment by radiosilence** [comment]
Oh thanks, @dosu

**Comment by RayZ3R0** [comment]
Shut up dosu bot. Those are very old issues.

**Comment by gkonuralp** [comment]
Same problem on an LG 4K monitor.

**Comment by filip-van-hoeckel** [comment]
Unfortunately same issue here.

**Comment by svengt** [comment]
Same issue here 👋 Version: 1.0.1-a.17 (Firefox 132.0) (aarch64)

**Comment by hricvladimir** [comment]
Same issue, on LG 4K monitor, on MacOS, the text is blurry. 1.0.1-a.17 (Firefox 132.0) (aarch64)

**Comment by loicfavory** [comment]
I have the same issue on my widescreen (5120x1440px) if I open zen in fluscreen.
If I split screen by using two apps side by side it's ok.

I installed Flatpak app on ubuntu 22.04 / 1.0.1-a.17 (Firefox 132.0) (64 bits)

**Comment by mackcoding** [comment]
I am also having this issue on 1.0.1-a.19. I am on PopOS (latest). Firefox does not have the issue, and neither does my Windows machine. I am on:

- Lenovo Thinkpad P16s Gen 2
- AMD Ryzen 7 Pro 7840u 
- Radeon 780m 
- X11 
- Latest drivers
- Gigabyte Monitor
- 3840x2160 resolution
- 60hz
- Scaling set to 125%
- HiDPI Daemon disabled

**Comment by mastazi** [comment]
Like @loicfavory I have a 5k widescreen, 5120X1440px, with 150% scaling. For me the exact point at which the screen becomes blurry is when the viewport goes over 2730 "css pixels" wide. This is about 75% of the width of the screen so about equivalent to 4K resolution in terms of "real pixels" see the two screenshots below, the viewport size is visible in the upper right corner, compare the characters being clear in one screenshots and blurry in the other one. 

One more thing that I have observed: whenever an element (`div`, `p`, etc) has some type of on `:hover` effect, it immediately stops being blurry when hovering with the mouse, as if the `:hover` state forced it to be redrawn in a non-blurry way

<img width="1222" alt="2024-11-25 12_25_54-Slashdot_ News for nerds, stuff that matters — Zen Browser Private Browsing" src="https://github.com/user-attachments/assets/98c6d688-a825-406d-b89e-f606af6fd81a">

<img width="1387" alt="2024-11-25 12_26_33-Slashdot_ News for nerds, stuff that matters — Zen Browser Private Browsing" src="https://github.com/user-attachments/assets/92e51576-862b-4fd8-a6e5-208f1fc09c10">

**Comment by mastazi** [comment]
I just wanted to add that this workaround resolved the issue for me: https://github.com/zen-browser/desktop/issues/2375#issuecomment-2441900369
TL:DR; in `about:config` search for `zen.view.experimental-rounded-view` and set it to `false`

**Comment by neurokitti** [comment]
duplacate of https://github.com/zen-browser/desktop/issues/1276
