### ISSUE TITLE
[Bug]: Auto Video Pause and Performance Issues in Zen Browser

### ISSUE THREAD

**Issue by Evren-os** [zen-browser/desktop#269]
### Description

While using Zen Browser (Alpha 19), I encountered significant performance issues and video playback disruptions. I had the following tabs open simultaneously:

- 1 Facebook tab
- 1 YouTube tab
- 3 Instagram tabs

Initially, videos were playing smoothly across all tabs, but suddenly, all video playback stopped. Despite the network being stable, videos became unplayable, appearing to be in a frozen state. Occasionally, audio continues to play, but without any sound output. Reloading the tabs temporarily resolves the issue, but it recurs shortly after.

In addition to the video playback problem, the browser experiences frequent performance degradation. Zen Browser occasionally hangs for several moments and sometimes crashes entirely. This issue has persisted across multiple versions of the browser, leading me to believe it may be related to the browser itself rather than my system configuration.

### Steps to Reproduce

1. Open the Zen Browser (Alpha 19).
2. Open multiple video-heavy tabs (e.g., Facebook, YouTube, and Instagram).
3. Start video playback in each tab.
4. Observe as video playback suddenly pauses across all tabs, with no videos being playable, and audio output may be inconsistent.

### Expected Behavior

Video playback should be smooth across multiple tabs without unexpected pauses, freezes, or audio issues. The browser should maintain stable performance, even with multiple tabs open.

### Actual Behavior

- Video playback pauses automatically and becomes unplayable in all tabs.
- Audio may continue without any sound output.
- Browser hangs, becomes unresponsive, and sometimes crashes.

### Additional Context

- Issue persists even after reloading the affected tabs.
- The problem occurs inconsistently but frequently, affecting the usability of the browser.
- System resources are not maxed out during the occurrence, indicating a potential software-related issue.

### Environment

- **OS:** Arch Linux (Kernel: `linux-zen`)
- **Zen Browser Version:** Alpha 19
- **Hardware:** AMD Ryzen 7 5700G (8C/16T), 16 GB RAM

### Notes

This issue has been observed across several previous versions of Zen Browser. Given the frequent hangs and crashes, it may be related to resource management or a specific issue with video handling across multiple tabs.

Please advise on any potential workarounds or fixes. I'm willing to provide additional logs or testing if needed.

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.19

### Severity impact

Medium

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
Is it still happending in version 24?

**Comment by Evren-os** [comment]
> Is it still happending in version 24?

I'm still in 22, lemme test it!

**Comment by marko19914** [comment]
Had a similar issue on Twitch yesterday (version a23). I experienced jitter - previous frame returning for a split second while watching a stream in 1080p.
Opened the same streaming Firefox 129.0.1. Everything was completely fine.

**Comment by mauro-balades** [comment]
> Had a similar issue on Twitch yesterday (version a23). I experienced jitter - previous frame returning for a split second while watching a stream in 1080p.

what OS are you in?

**Comment by marko19914** [comment]
`Desktop: GNOME v: 43.9 Distro: Debian GNU/Linux 12 (bookworm)`

**Comment by Stryxus** [comment]
Can confirm, this is happening under Windows 11, only when Hardware Acceleration is enabled. Using an RTX 3060Ti.

**Comment by marko19914** [comment]
Still happens, but is much lighter on version `1.0.0-a29`.

**Comment by Evren-os** [comment]
YouTube one is gone, at least for me

**Comment by marko19914** [comment]
I think, it might be related. The video doesn't always resume after pausing the video on YT or the stream on Twitch. Toggling the pause/play back and forth 3-4 times usually gets the video playing again.

**Comment by Evren-os** [comment]
> I think, it might be related. The video doesn't always resume after pausing the video on YT or the stream on Twitch. Toggling the pause/play back and forth 3-4 times usually gets the video playing again.

Ya, I faced this also in youtube

**Comment by n7itro** [comment]
Is this still happening in version 37?

**Comment by Evren-os** [comment]
> Is this still happening in version 37?

Not dealing with those issues anymore

**Comment by marko19914** [comment]
I don't see this issue on a37. Have had the version for half a day though - got released in flathub quite recently.

**Comment by marko19914** [comment]
Update: Had the bug in Instagram Stories today.
