### ISSUE TITLE
Workspaces are not syncing properly.

### ISSUE THREAD

**Issue by ealione** [zen-browser/desktop#2702]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Workspaces are not syncing. I can get the name and the icon to sync, but otherwise the tabs that I had open on each workspace are not there.
After restarting the browser, I had to log in to Mozilla again and this time even the tabs on this machine were not there any longer.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

v1.0.1-a.18

### What platform are you seeing the problem on?

Linux

**Comment by RealDishwash** [comment]
yeah the workspace sync doesn't sync tabs atm

**Comment by pawel-domanski** [comment]
On windows also :(

**Comment by ealione** [comment]
I see. Didn't know that was the intended behaviour for now :)
