### ISSUE TITLE
Essentials not caching icons when Reset. 

### ISSUE THREAD

**Issue by orbi-tal** [zen-browser/desktop#2704]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Essentials are not caching icons when they are Reset. This happens with Ctrl+W, middle mouse, and context menu option. Video is attached. 

https://github.com/user-attachments/assets/49048ba2-d288-44ea-ab94-a797cae69a7e

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1 t.18

### What platform are you seeing the problem on?

Windows

**Comment by Richard-Woessner** [comment]
Fixed
