### ISSUE TITLE
Bug in the Workspace theme color-picking UI

### ISSUE THREAD

**Issue by bapungiri** [zen-browser/desktop#2705]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The number of color anchors created within the theme picker of a workspace changes when we navigate back to this workspace from another one. For example, imagine I have three workspaces: W1, W2, and W3. Suppose the number of colors chosen in W1 is 5 and in W2 is 3. Now, let’s say I choose a single color for W3. If I then switch to W1 and return to W3, the number of colors in W3's theme picker automatically changes from 1 to 5. If I instead switch to W2 and return to W3, the number of colors changes from 1 to 3.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.17

### What platform are you seeing the problem on?

Windows

**Comment by neurokitti** [comment]
if im not mistaken this is a bug i just fixed so it should be coming to stable very soon!

let me know  if this is the issue you are facing:
https://github.com/zen-browser/desktop/pull/2681

**Comment by bapungiri** [comment]
Yeah seems like the same issue. Glad to hear it got fixed. Thanks.
