### ISSUE TITLE
the IDM extension occasionally fails

### ISSUE THREAD

**Issue by wtscse** [zen-browser/desktop#2706]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I have two configuration files，when I open two configurations at the same time, IDM  extension stops working on one of them. Also, I am using the portable version on Windows—can I change the configuration files to the root directory of the software instead of the C drive?"

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.17

### What platform are you seeing the problem on?

Windows

**Comment by orbi-tal** [comment]
Are you saying IDM isn't able to grab links on one profile when you open two?

**Comment by salamijason** [comment]
Could you try replicated this on other browsers? Might be an IDM limitation.

**Comment by salamijason** [comment]
No response in 1 week. For the sake of keeping the roadmap clean, I'll be closing this issue but please reopen if you still get this issue. Thank you.
