### ISSUE TITLE
Consider migrating to Codeberg

### ISSUE THREAD

**Issue by ThousandDemonDaggers** [zen-browser/desktop#271]
### What feature would you like to see?

Moving everything to [Codeberg](https://codeberg.org) would be great, as it is a libre, free, open-source, privacy-friendly and non-profit git platform from Germany, running the Gittea soft-fork [Forgejo](https://forgejo.org).
Instead, GitHub is closed source software owned by Microsoft, opposing to Zen Browser.

### What platform are you seeing the problem on?

Linux

### Additional context

* https://codeberg.org/Recommendations/Mirror_to_Codeberg
* https://nogithub.codeberg.page

**Comment by lazymonkey2** [comment]
no please keep using github.

**Comment by mauro-balades** [comment]
I'm going to keep suing GitHub, it's easier for me to manager and it's more mainstream

**Comment by VixiKitsune** [comment]
Rather than move to Codeberg, why not mirror it?

Hosting a competitor to big tech browsers exclusively on a big tech repo is a bit counter intuitive.

**Comment by gelbphoenix** [comment]
I would agree with @VixiKitsune. Also it seems like there are already some mirrors under the [Zen Browser organisation on Codeberg](https://codeberg.org/zen-browser). This repo is mirrored to [zen-browser/desktop: Welcome to a calmer internet, official back up repo - Codeberg.org](https://codeberg.org/zen-browser/desktop)
