### ISSUE TITLE
[Twilight] texture slider is not working

### ISSUE THREAD

**Issue by neurokitti** [zen-browser/desktop#2711]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

https://github.com/user-attachments/assets/34588dae-e976-4bb1-a168-97cec6658ee9

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-t18

### What platform are you seeing the problem on?

Windows

**Comment by RayZ3R0** [comment]
yep happens to me too on arch
