### ISSUE TITLE
[Twilight] Workspace strip not there in fresh install and on new profile

### ISSUE THREAD

**Issue by RayZ3R0** [zen-browser/desktop#2712]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I just installed twilight, and.. there is no workspace strip on the sidebar. At least, not a usable one. Its a small dot that can be dragged to overflow menu, which then becomes a line. I have found out how to fix this however. I have to create a few essential tabs, then use the shortcut to cycle workspaces to get back to default workspace. Note that however, at the beginning I did not have a workspace strip, but the place below the essential tabs showed "Default Workspace"

https://streamable.com/jaaefe

This is the workaround. I used the shortcut to cycle workspaces before closing and there it was.
https://github.com/user-attachments/assets/9a1cecdd-b5bf-4e63-ae13-71df520fdbc8

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-t.18 (Firefox 132.0.1) 

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
N/A
```

**Comment by mr-cheffy** [comment]
This has now been fixed, thanks!
