### ISSUE TITLE
Glance in a pinned tab shifts icons unnaturally to the left

### ISSUE THREAD

**Issue by MrPiggy105** [zen-browser/desktop#2714]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

No matter how wide the sidebar is, using Glance in a pinned tab shifts the icons unnaturally to the side because of the side tab in the preview, as seen below:
https://github.com/user-attachments/assets/3e19c618-cd02-45d1-b223-7b7601b09982
<img width="381" alt="Screenshot 2024-11-07 at 6 15 18 pm" src="https://github.com/user-attachments/assets/09e8c667-3cfe-41f2-962c-464a9ec6a4e4">

This is annoying if you have theming and/or better active tab mods:
<img width="202" alt="Screenshot 2024-11-07 at 6 11 09 pm" src="https://github.com/user-attachments/assets/d740b4de-0eb4-4bca-ac0b-8aea61b79646">

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.17

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by mr-cheffy** [comment]
This has been fixed in version 18, thanks!
