### ISSUE TITLE
Zen Browser won't open on MacOS Sequoï

### ISSUE THREAD

**Issue by Thomasdvrd** [zen-browser/desktop#2715]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![CleanShot 2024-11-07 at 09 46 32](https://github.com/user-attachments/assets/844d90df-4f52-4708-ae22-a3af5e611046)

When trying to launch Zen Browser, after having updating my Mac to MacOS SequoÏa 15.1, I get a black window with the Zen Browser logo on the middle. 

I tried restarting my computer, I tried uninstalling the app and re-installing it but nothing work

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.17 (Firefox 132.0)

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by patrikkaprinay** [comment]
I have the same issue, on MacOS 15.0. Can't get past this page, so it's currently totally unusable.

**Comment by lancewilhelm** [comment]
FWIW, I just installed Zen for the first time (1.0.1-a.17 (Firefox 132.0) (aarch64)) on Sequoia 15.1 with no issue. I'm on a Macbook Air M2.

**Comment by Thomasdvrd** [comment]
@patrikkaprinay 
I went on "'/Users/{username}/Library/Application Support/zen/Profiles'" and delete the profiles, then uninstall the app and reinstalling it and I was able to use Zen Browser again but I had to configure everything back again.

**Comment by pencilcheck** [comment]
This is very concerning. I am pondering if I should upgrade to squoia, this might be the deal breaker if it doesn't work on upgrade with existing profile.

**Comment by patrikkaprinay** [comment]
I got it working by deleting the whole "'/Users/{username}/Library/Application Support/zen'" folder while Zen was still installed, mounted the installator and replaced the application. Now it opens, but all data is erased, of course.

**Comment by Mao-Hao** [comment]
I encountered a similar issue. I'm using an M1 MacBook Air, and this is my first time using Zen. I found that opening the program takes much longer than I expected. Even when it does start successfully, the browser displays the following message:
 
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/d822f17b-30e3-43ed-8fc0-e55d0604d176">
I cannot new any tab or go to a web

**Comment by pencilcheck** [comment]
This is worrying, I was going to upgrade to sequoia but I think I will monitor this thread until zen fixes itself so upgrade will be a smooth experience.

**Comment by pencilcheck** [comment]
Reporting from sequoia 15.1, zen browser version 1.0.1-a.19 works without any issues
