### ISSUE TITLE
Glances after closes, select next tab.

### ISSUE THREAD

**Issue by chriztheanvill** [zen-browser/desktop#2717]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

After close glances, select the next tab. If is possible to only close glances.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.17 (Firefox 132.0) (64-bit)

### What platform are you seeing the problem on?

Linux

**Comment by mr-cheffy** [comment]
>  I have searched existing issues and avoided creating duplicates.
![image](https://github.com/user-attachments/assets/19d81380-b69d-4d66-9f18-66d6a455ac3e)
