### ISSUE TITLE
Choose your theme

### ISSUE THREAD

**Issue by bphd** [zen-browser/desktop#2727]
![Capture d’écran du 2024-11-07 16-51-13](https://github.com/user-attachments/assets/e5769457-3311-43c9-8895-b4a453885ad0)

Emm, no?

![Capture d’écran du 2024-11-07 16-56-21](https://github.com/user-attachments/assets/a3cf1551-e250-421b-b0aa-5b0cbd4dcd49)

What about that?

**Comment by ArikRahman** [comment]
Auto is nearly always mismatched on linux configurations, so I would like to preserve the choice to choose, although I see the use case with windows users changing their system theme depending on time of day.

**Comment by bphd** [comment]
Nope, not mismatched with WayLand since loooonnnngg

You can preserve the choice, but needs to put there "System theme --- auto"

**Comment by bphd** [comment]
> * this issue is still relevant to the latest version of the desktop repository

**Comment by bphd** [comment]
@dosubot that user don't exist, you better bump LeMoonStar

**Comment by bphd** [comment]
@mr-cheff Why is that not planned?
