### ISSUE TITLE
Incorrect display of tab mute button on macOS

### ISSUE THREAD

**Issue by lemon-sundae** [zen-browser/desktop#2728]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The tab mute button doesn't look right in zen-browser for macOS
<img width="48" alt="image" src="https://github.com/user-attachments/assets/37a6cbed-07b8-4bd5-b4ca-a973b330fc7b"><img width="43" alt="image" src="https://github.com/user-attachments/assets/4f3c4ac4-95d1-4bb9-b688-b645a1a06e5e">
<img width="45" alt="image" src="https://github.com/user-attachments/assets/5e9431ca-b446-44a7-b426-e3ec69f784d1"><img width="44" alt="image" src="https://github.com/user-attachments/assets/869c67c7-382c-4446-ab70-98a11bfb3875">
I have checked on a newly installed zen browser to make sure it is not caused by mods or themes.
macOS version is 15.1 (24B83)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.17

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by iLiranS** [comment]
Hi, this also happens on Windows. 
I think the solution might look like this :
```
@-moz-document url-prefix("chrome:") {

    .tab-icon-overlay {
        stroke: light-dark(white, black) !important;
        -moz-context-properties: fill, stroke !important;
    }
}
```

**Comment by lemon-sundae** [comment]
> Hi, this also happens on Windows. I think the solution might look like this :
> 
> ```
> @-moz-document url-prefix("chrome:") {
> 
>     .tab-icon-overlay {
>         stroke: light-dark(white, black) !important;
>         -moz-context-properties: fill, stroke !important;
>     }
> }
> ```

Yes, it worked.
Zen-browser added a strange list-style-image to .tab-icon-overlay, and my solution is to just remove it and do some change to the original overlay image.
```css
.tab-icon-overlay {
    list-style-image: none !important;
    border-color: /*some-color-you-like*/ !important;
    fill: /*some-color-you-like*/ !important;
}
```
