### ISSUE TITLE
Able to scroll the UI which brings space to the bottom of the screen and hides the addressbar 

### ISSUE THREAD

**Issue by Shockshwat** [zen-browser/desktop#2731]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

https://github.com/user-attachments/assets/6d710c71-5844-4354-8ed3-68578e4905f4

Kind of hard to explain in text, but if you open YT music (What i found in my case,) you are able to scroll the zen browser ui and hide the addressbar of the browser and reveal some hidden space under the browser.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.17

### What platform are you seeing the problem on?

Windows

**Comment by daqnal** [comment]
Can confirm this is bug affects the Linux release.

To quickly reproduce, scroll down on your tab bar when it's in compact or minimized mode, and it will expose space at the bottom.

**Comment by neurokitti** [comment]
ive checked and this seems to only take effect when there are too many tabs in the sidebar and with the UI is in minimized mode (idk the actual term lol)

**Comment by 3s0x** [comment]
I have the same problem under macOS 15.0 on the Apple M1 Pro. The problem seems to occur randomly. I can't manage to reproduce it.
There seems to be something to @neurokitti's approach. When I closed tabs (except for 5) it worked again. But when I reopen 20 tabs, the problem does not automatically reappear.

**Comment by egk2374** [comment]
I've seen this a few times on MacOS 14.5 M1 Pro. The most reliable cause for me seems to be scrolling in the tabs panel (collapsed view). That is causing this bug consistently for me regardless of how many tabs or what page is currently open.

**Comment by Nicholaiii** [comment]
Can confirm this issue on Windows too, happens only in compact mode.

EDIT: Started happening without compact mode now. I also have a scrollbar in the right side that scrolls the entire UI.

**Comment by egk2374** [comment]
Looks like at least scrolling in the tab bar doesn't do this anymore in the 1.0.1-a.18 build that I updated to this morning.

**Comment by Nicholaiii** [comment]
> Looks like at least scrolling in the tab bar doesn't do this anymore in the 1.0.1-a.18 build that I updated to this morning.

I have it on `1.0.1-a.19`.

**Comment by Shockshwat** [comment]
> Looks like at least scrolling in the tab bar doesn't do this anymore in the 1.0.1-a.18 build that I updated to this morning.

I even have it on twlight for that matter.

**Comment by Majoramari** [comment]
Same on linux 

[Screencast_20241123_181117.webm](https://github.com/user-attachments/assets/2c0be078-c411-436e-ad4e-8947165a4bae)

**Comment by Elaxor** [comment]
Caused by a mod.
https://github.com/anaarkei/zen-floating-findbar/issues/5
