### ISSUE TITLE
Downloads going to App Data folder instead of set folder

### ISSUE THREAD

**Issue by gillpeter** [zen-browser/desktop#2736]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

Downloads do not get saved in any set folder when you set them to auto-download. Instead they go to App Data on Windows 11.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.17

### What platform are you seeing the problem on?

Windows

**Comment by Richard-Woessner** [comment]
Duplicate of Issue #2253.
Thank you for reporting it they are working on it
