### ISSUE TITLE
Zen Sidebar opens on the left with vertical tabs on the right

### ISSUE THREAD

**Issue by iawaheed** [zen-browser/desktop#2738]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Zen Sidebar opens on the left even with vertical tabs on the right.

<img width="1720" alt="Screenshot 2024-11-08 at 9 43 26 AM" src="https://github.com/user-attachments/assets/c7ef7f32-26af-4ee2-aa8f-061828341ee9">

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.17

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by tomsik-radek** [comment]
You can drag the sidebar window where you like. However, I think the real issue here is if you pin it, it always goes to the left, at least for me on 1.0.1-a.17 on Windows
