### ISSUE TITLE
Installation Issue — [Alpha build - 1.0.0-a.19 (2024-08-14)]

### ISSUE THREAD

**Issue by curtisault** [zen-browser/desktop#274]
### What happened?

I tried installing the [current version of the release](https://github.com/zen-browser/desktop/releases/tag/1.0.0-a.19) and I am getting an error:

<img width="372" alt="image" src="https://github.com/user-attachments/assets/e489e717-1d9f-4c3e-b41f-f5e22fde3988">

<img width="440" alt="image" src="https://github.com/user-attachments/assets/f47005f4-3f9c-429e-ba1d-419efaf59092">

It appears to be an issue with signing the cert?

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.19

### Severity impact

Critical

### What platform are you seeing the problem on?

macOS - aarch64

### Relevant log output

```shell
assessment denied for zen.macos-aarch64.dmg
com.apple.message.domain: com.apple.security.assessment.outcome2
com.apple.message.signature2: bundle:UNBUNDLED
com.apple.message.signature3: zen.macos-aarch64.dmg
com.apple.message.signature5: UNKNOWN
com.apple.message.signature4: 3
com.apple.message.signature: denied:no usable signature
SenderMachUUID: BF7C4A48-7AE5-3C47-9121-C98B0A7E923C
```

**Comment by mauro-balades** [comment]
Please checkout https://github.com/zen-browser/desktop/issues/53. THanks!
