### ISSUE TITLE
If I choose to expand tabs by default, I can see a button on the bottom left that allows me to collapse/expand them.

### ISSUE THREAD

**Issue by M4rti21** [zen-browser/desktop#2744]
If I choose to expand tabs by default, I can see a button on the bottom left that allows me to collapse/expand them.

However, browsing through the keyboard shortcuts in the settings, I cannot find any that will trigger that action.

Is there any way to expand/collapse tabs through a keyboard shortcut?

_Originally posted by @victor-marino in https://github.com/zen-browser/desktop/discussions/995_

**Comment by victor-marino** [comment]
Thank you!

I assume this was added recently? As I couldn't find this last time I tried Zen browser.

Anyway, thanks a lot for reaching out, will give it another go!

**Comment by M4rti21** [comment]
Oh i just see it now, its at Keyboard Shortcuts > Other Zen Features > Toggle Sidebar's Width!
I think maybe the name should be changed to something like "Toggle Expand Sidebar" or something like that, also i think all the zen-specific keybinds should be more visible at the top of the keybinds list maybe?
