### ISSUE TITLE
Automatic Light/Dark theme does not switch automatically

### ISSUE THREAD

**Issue by kennethjyang** [zen-browser/desktop#2747]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I have set my theme to "automatic" expecting it will follow my system's light/dark mode, however Zen will stay dark even when the system theme is light.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.17

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by hwitdew** [comment]
Same problem. Hope can be solved soon.

**Comment by theherk** [comment]
Yeah, something is amiss with the theming. As far as I can tell, if you want light dark auto, you must set theme to "System Theme - Auto" in about:addons. However, that prevents any of the Zen Look and Feel settings from affecting the toolbars. Those only work with "Dark" in about:addons. And there appears to be no way to use any other theme. The bar is always one of:

- Zen Look and Feel if about:addons is set to dark.
- One single dark shade for any other dark theme or for System Theme - Auto if system is dark.
- One single light shade for any light theme or for System Theme - Auto if system is light.

**Comment by kennethjyang** [comment]
Looks to have been solved now

**Comment by theherk** [comment]
There is still something slightly different between dark mode and follow system with system in dark mode. But this is generally resolved.

**Comment by angrybacon** [comment]
I can reproduce with 1.7.4b (Firefox 134.0.2), same OS
