### ISSUE TITLE
Wrong color for bookmark bar

### ISSUE THREAD

**Issue by jumpyvi** [zen-browser/desktop#275]
### What happened?

By default, the bookmark bar (horizontal) is the wrong color (default firefox color).

This can be resolved by switching
 
```
:root[lwtheme] {
  toolbar,
  &[lwt-popup="light"] panel {
    color-scheme: light;
  }
  toolbar[brighttext],
  &[lwt-popup="dark"] panel {
    color-scheme: dark;
  }
```

to

```
:root[lwtheme] {
  toolbar,
  &[lwt-popup="light"] panel {
    color-scheme: light;
  }
  toolbar[brighttext],
  &[lwt-popup="dark"] panel {
    color-scheme: dark;
    background-color: #1a1e26;
  }
```

the inspector says it's at global-shared.css:112

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Flatpak

### Severity impact

Low, Enhancement

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
This has been fixed in version 20 but it's currenlt being built, thanks!
