### ISSUE TITLE
Zen Twilight: What's New hotlink in Settings not working

### ISSUE THREAD

**Issue by 12th-devs** [zen-browser/desktop#2753]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I am using Zen Twilight and have noticed an issue when clicking on the What's New in the settings to view the Release Notes, it loads a Page Not Found! page for the browser.
![Screenshot 2024-11-08 203807](https://github.com/user-attachments/assets/d8d8c86e-402d-455a-a5f4-499c40e63aac)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

t.18

### What platform are you seeing the problem on?

Windows

**Comment by LeMoonStar** [comment]
Hey! Can you provide me with the exact link you are being redirected to?

**Comment by 12th-devs** [comment]
https://zen-browser.app/release-notes/1.0.1-t.18/

![Screenshot 2024-11-09 095446](https://github.com/user-attachments/assets/66c9e4a2-e54a-4f87-ba08-50fa07603200)

**Comment by 12th-devs** [comment]
I would assume it's because the update has not been released for the stable build so the way it tries to navigate to the page is messed up because its looking at the current version to determine the URL.

**Comment by LeMoonStar** [comment]
Thank you! This does indeed seem to be a problem with Twilight, as the version string is `X.X.X-t.X` instead of `X.X.X-a.X` as is the case for the "stable" alpha build. The correct link would be `https://zen-browser.app/release-notes/1.0.1-a.18/` - do keep in mind there __are no release notes for Twilight__

**Comment by 12th-devs** [comment]
Yes I know it would just be nice to see this link deleted for twilight or navigate to something else, thanks so much! Have a good day.

**Comment by LeMoonStar** [comment]
> I would assume it's because the update has not been released for the stable build so the way it tries to navigate to the page is messed up because its looking at the current version to determine the URL.

The release notes are already published, see https://zen-browser.app/release-notes/1.0.1-a.18/ - The release has however been pushed back due to some update-related changes that still have to be done.

**Comment by LeMoonStar** [comment]
This is still an issue, please keep it open.

**Comment by 12th-devs** [comment]
mb I apologize, I'm pretty new to all this

**Comment by 12th-devs** [comment]
it is resolved, it now brings you to the zen homepage.
