### ISSUE TITLE
When I close glance view, it always switches to the next tab

### ISSUE THREAD

**Issue by Lovecrafx** [zen-browser/desktop#2754]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When I close glance view, it always switches to the next tab

https://github.com/user-attachments/assets/a5c74566-fbc9-40be-89fd-7bc0acc5f7cc

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.17 (Firefox 132.0)

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by aadityapageni** [comment]
I was about to open the same issue here. 
Edit: Same happens with closing split tab. When you have ( A | B ) C, when you close B, the view moves to C, can we have a checkbox, that enables view to A by default

Edit 2: Your issue might be fixed now, 
 
> Fixed glance changing to the next tab if the current tab isn't the last one[#2526](https://github.com/zen-browser/desktop/issues/2526)

**Comment by Lovecrafx** [comment]
> 我正要在这里打开同样的问题。 编辑：关闭拆分选项卡也会发生同样的情况。当你有 ( A | B ) C 时，当你关闭 B 时，视图移动到 C，我们可以有一个复选框，默认启用视图到 A
> 
> 编辑 2：您的问题现在可能已得到解决，
> 
> > 修复了如果当前选项卡不是最后一个选项卡则切换到下一个选项卡的问题 [#2526 ](https://github.com/zen-browser/desktop/issues/2526)

Thank you, I saw that the a18 version solves this problem, but I downloaded zen browser from Homebrew, and it is still the a17 version on Homebrew
