### ISSUE TITLE
Flatpak version still on .17

### ISSUE THREAD

**Issue by tanaybhomia** [zen-browser/desktop#2755]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I just installed the browser and the latest version is .18 but the flatpak ref is still on .17. And the update situation is also not great. I was not able to update the App Image version as well.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.17

### What platform are you seeing the problem on?

Linux

**Comment by gnc-07** [comment]
a.18 has not been released yet, therefore this issue should be closed. a.18 will be released tomorrow. Refer to this post by the dev today: https://www.reddit.com/r/zen_browser/comments/1gmvrbn/frequently_asked_questions_yall_might_get/

**Comment by tanaybhomia** [comment]
Sure Sure, Thnks for the info. I will close this
