### ISSUE TITLE
Zen browser keep getting crash when I use Gmail

### ISSUE THREAD

**Issue by Beeditor04** [zen-browser/desktop#2756]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

It is a very weird behavior but everytime I **CREATE** a new workspace, then **sign in my email**, the browser is just cracked. I even try again several times but its still the same issue
![image](https://github.com/user-attachments/assets/909e0b30-5a4f-4b00-9181-b3ef51eb1fd3)
![image](https://github.com/user-attachments/assets/392f0c10-0e86-41dd-af5c-28d766fc8368)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1

### What platform are you seeing the problem on?

Windows

**Comment by tomsik-radek** [comment]
I created a new Workspace and Gmail didn't crash. I'm on 1.0.1-a.17. What extensions are you running?

**Comment by Beeditor04** [comment]
> I created a new Workspace and Gmail didn't crash. I'm on 1.0.1-a.17. What extensions are you running?

here, in case we talk about addons this is my zen mods as well

![image](https://github.com/user-attachments/assets/450d6146-7daf-4806-96e6-72d65c2ec850)
![image](https://github.com/user-attachments/assets/c502d684-7313-40c5-9acd-66acb2dfbc78)

**Comment by cheeeebs** [comment]
@Beeditor04 try this [solution](https://www.reddit.com/r/firefox/comments/1f4wlzv/comment/ltmprdf/)

**Comment by Beeditor04** [comment]
> @Beeditor04 try this [solution](https://www.reddit.com/r/firefox/comments/1f4wlzv/comment/ltmprdf/)

nah removing passkeys is like unpluging the cable to prevent online hacking, for now my solution is just copy a whole gmail to the textbox (no typing) and Enter, but it's still annoying

**Comment by salamijason** [comment]
Hey any updates on this? Can you login without crashing?

**Comment by salamijason** [comment]
No response in 2 weeks, will be closing this issue. Please reopen if you still get the bug.
