### ISSUE TITLE
Unable to install Zen - AppImage, terminal, zip

### ISSUE THREAD

**Issue by Milziade** [zen-browser/desktop#2758]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I tried to run Zen from the AppImage (latest build, downloaded from the webpage), but it didn't open.
I tried from the terminal:
`bash <(curl https://updates.zen-browser.app/appimage.sh)`
but I get the following error:
`Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
This doesn't look like a squashfs image.
Failed to open squashfs image`
and then nothing happens.

Same problem applies if I try to run the generic version

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.17

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
Pop!_OS 22.04 LTS x86_64
CPU: AMD Ryzen 5 3500U

echo $XDG_SESSION_TYPE: wayland
```

**Comment by Milziade** [comment]
I can install Zen using flatpak (`flatpak install flathub io.github.zen_browser.zen`), but none of the methods mentioned by @dosu works, nor I'm able to locate and change the `QT_QPA_PLATFORM=wayland`

**Comment by tomsik-radek** [comment]
What version of GNOME is Pop22.04 running? I recommend you upgrade to 24.04.

I just spun up a Fedora 41 KDE VM, KDE 6.2.1, also on Wayland, and that works without any issues.

According to https://stackoverflow.com/questions/69994530/qt-qpa-plugin-could-not-find-the-qt-platform-plugin-wayland you might be missing a  dependency, affects Ubuntu 21 and 22.
`sudo apt install qtwayland5`

**Comment by LeMoonStar** [comment]
Hey! Thank you for the report.

A similar issue has been reported in #1670 - where it turned out to be an issue with appimagelauncher.
Can you take a look at that issue, and see if it helps you resolve the problem? Thank you!

**Comment by LeMoonStar** [comment]
> I can install Zen using flatpak (`flatpak install flathub io.github.zen_browser.zen`), but none of the methods mentioned by @dosu works, nor I'm able to locate and change the `QT_QPA_PLATFORM=wayland`

While using the flatpak is an option, please keep in mind the flatpak doesn't offer the optimized/specific version of Zen, so you are possibly missing out on performance!

**Comment by ThePiklOfTime** [comment]
I have a similar issue, but there are a few differences. Firstly I'm on fedora 41 kde 6.2.3 (wayland). For me the script trows out /dev/fd/63: line 170: /tmp/ZenBrowser.AppImage: cannot execute: required file not found, and doesn't install the image (even though it says it did). Appimagelauncher can't open it, gearlever doesn't want to work. Flatpak works no problem though. (version a18)
Edit: also none of the env variables and other stuff suggested on this thread seem to work. 
Edit2: Also the portable zip works too.

**Comment by LeMoonStar** [comment]
For everyone here: ***The Zen AppImage does not work with AppImageLauncher.*** see https://github.com/zen-browser/desktop/issues/2103#issuecomment-2412914361 for more details.

This issue is more than likely a duplicate of #2103, #1670, #312 and #189.

If you encounter this issue ***and do not use AppImageLauncher at all***, please comment or re-open this issuse.
Thank you for the report.

**Comment by Milziade** [comment]
Hello! I tried the @tomsik-radek solution, but my version of `qtwayland5` is already installed and update. GNOME version is 42.9
I also tried Gear Lever, but still Zen doesn't launch

I tried to run `QT_QPA_PLATFORM=wayland ./zen-specific.AppImage` and got 
`QSocketNotifier: Can only be used with threads started with QThread`
`execv error: No such file or directory` 
as result @dosubot
