### ISSUE TITLE
Password Manager Extension 'Dashlane' not working in zen anymore

### ISSUE THREAD

**Issue by arnolicious** [zen-browser/desktop#2759]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The browser extension for the password manager 'Dashlane' has stopped recognizing login inputs on all websites.
Thus breaking auto-login functionality and auomatic saving of new unknown logins.

This only became a problem 2-3 weeks ago, I do not exactly know which version it was, that broke this.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.17

### What platform are you seeing the problem on?

Windows

**Comment by tomsik-radek** [comment]
Just curious, if you try to save a login, what URL does it save as?

**Comment by LeMoonStar** [comment]
Hey! Thank you for the report.

Have you tried re-installing the extension? If that doesn't work, can you try creating a new Zen Profile and trying again in there?
I've had a similar problem with Bitwarden about a month ago, reinstalling the extension helped.

**Comment by arnolicious** [comment]
Oh wow, reinstalled it and it just works... can't believe it was so simple, and I didn't try that.

Well, thanks for the quick turn around!
