### ISSUE TITLE
missing top padding in compact mode

### ISSUE THREAD

**Issue by mayank99** [zen-browser/desktop#276]
### What happened?

When using compact mode with the url bar hidden, the top edge of the browser is missing the padding. I think this padding is meant to be the same on all four edges.

<img width="700" alt="" src="https://github.com/user-attachments/assets/4e6dc203-1ace-4a3d-9279-e78f51547880">

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.20

### Severity impact

Low

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by mauro-balades** [comment]
Fixed in https://github.com/zen-browser/desktop/commit/c4db4b2bd95edc889184d440215c778af87a5c8f, thanks!
