### ISSUE TITLE
UI bug

### ISSUE THREAD

**Issue by NotLinuxExpert** [zen-browser/desktop#2760]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Hello Zen Dev. 👋
I would report an issue, I'm just show you the issue from image since I don't know how to say
![Screenshot 2024-11-09 175109](https://github.com/user-attachments/assets/14e7dc98-0efb-4113-ada8-e1f8b052faf4)

From NotLinuxExpert.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.17

### What platform are you seeing the problem on?

Windows

**Comment by LeMoonStar** [comment]
Hey, thank you for the report!
However, this issue has already been reported in #2557 - I will therefor close this as a duplicate.
