### ISSUE TITLE
Can't customize multiple buttons on customize toolbar

### ISSUE THREAD

**Issue by kar731** [zen-browser/desktop#2778]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I had my side panel button on the bottom of the sidebar next to the workspace switcher. Post update you are unable to move it down there or anywhere else on the toolbar really. (this existed post-a.18)
![image](https://github.com/user-attachments/assets/afd7d23a-fad8-4943-9145-547d2ab15507)

In addition to this, there is also an inability to move the back and forward buttons to the far left side (visible when you are in non-compact mode and existed pre a.18)
![image](https://github.com/user-attachments/assets/10123f2d-7bda-4cd2-9018-3b8e41dcf22f)

This is reproducible by going into customize toolbar and trying to move those 3 buttons.

Also, the new tab "+" button that existed before isn't showing anymore.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.18

### What platform are you seeing the problem on?

Windows

**Comment by MrPiggy105** [comment]
looks like this has been fixed?
