### ISSUE TITLE
Did DRM accidentally get omitted from the 1.0.0-a.20 build?

### ISSUE THREAD

**Issue by guigirl42** [zen-browser/desktop#278]
### What happened?

Each night i stream ABC Australian news via https://iview.abc.net.au/show/abc-news-24/video/NS1413V001S00. For the past ~week that's worked fine in Zen, meaning several Zen alpha versions. However tonight it failed, 100% of the time. I wondered if possibly the new Zen alpha `a.20` might have accidentally disabled its DRM setting when Zen updated this morning, so i went to Settings to look. To my shock, i cannot now find DRM _anywhere_ there! 

I _presume_ Zen previously did include DRM, simply because as mentioned, that streaming site has worked fine in Zen since i began using it a week or ten days ago. 

That site _still_ works fine in both Firefox Nightly, & Floorp. 

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.20

### Severity impact

High

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
Yep, sorry. It has been enabled for version 21. Again, really sorry!

**Comment by mauro-balades** [comment]
I can push the release right now if you really need it

**Comment by guigirl42** [comment]
Hi. 

I just wanna congratulate you on your _fabulous_ responsiveness & helpfulness. Not only have you created a marvelous browser already, even though only still alpha, but i am so grateful for you terrific openness to the community. Thank you!

As to your kind offer, i would not want to burden you. Pls just keep going on your existing plans, & i shall just be extra happy then once the next version arrives.

**Comment by mauro-balades** [comment]
Thanks! Dont give up on it because of this stupid mistake!

It will be released as soon as I finish with the theme store, so one day or 2
