### ISSUE TITLE
unloaded pinned tabs do not show website icon

### ISSUE THREAD

**Issue by speedy1804** [zen-browser/desktop#2789]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![Screenshot 2024-11-10 031142](https://github.com/user-attachments/assets/76f94d2f-74d9-4b16-9d68-68e9fee84ce6)
As you can see, the website icons aren't shown. I don't know if this has anything to do with the latest update (1.0.1-a.18), as I've only been using pinned tabs since this update.

The way I handle my pinned tabs:
![Screenshot 2024-11-10 031939](https://github.com/user-attachments/assets/15b04a27-7d8e-4cbc-8285-f230873b1056)

### Steps to reproduce:
1. Open any website
2. Pin the opened website
3. Close the website

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.18

### What platform are you seeing the problem on?

Windows

**Comment by Onceisenoughyo** [comment]
Can reproduce, I have my pinned tab settings to close and reset the tab to its default state when using ctrl+w. It removes the icons.

https://imgur.com/a/FvEZwIB

**Comment by cheeeebs** [comment]
> Can reproduce, I have my pinned tab settings to close and reset the tab to its default state when using ctrl+w. It removes the icons.
> 
> https://imgur.com/a/FvEZwIB

Having this same issue.

**Comment by stripedgoat** [comment]
Same here!

**Comment by amtoaer** [comment]
Same here. It looks like this issue was fixed by this PR, which is included in the latest [Zen Twilight build](https://github.com/zen-browser/desktop/releases/tag/twilight):
+ #2853

**Comment by speedy1804** [comment]
this has been fixed with the beta release
