### ISSUE TITLE
Custom workspace icons

### ISSUE THREAD

**Issue by Viktini** [zen-browser/desktop#279]
### What feature would you like to see?

Coming over from Firefox with a Sidebery set-up and I will say, it's great. I feel it's helping me stop tab hoarding which Sidebery didn't really do so, thanks for that. :+1: 

One thing I would like is for the ability to add custom icons for the workspace. On Sidebery, I can choose one of their own icons and colours, as well as custom text/colours or an image. Simple Tab Groups gives you colour-changeable symbols or an image. On Vivaldi, I can choose any emoji. It'd be nice to have the ability to use a specified emoji or icon for the workspace, as I feel the emojis I have now are limited.

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/866

 ~ This is an automatic operation to better enhancements requests organization.
