### ISSUE TITLE
Blank space above top tab

### ISSUE THREAD

**Issue by spacey-sooty** [zen-browser/desktop#2796]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

After updating to a.18 there is a blank space above my top tab 
![image](https://github.com/user-attachments/assets/72bcafb3-bdde-4759-b2f2-f67cbe0b6202)
I expected this behaviour to remain the same as the previous version with the top tab being at the top of the bar. This only occurs in compact mode.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Mozilla Zen 1.0.1-a.18

### What platform are you seeing the problem on?

Linux

**Comment by NoobToolzz** [comment]
I have this issue on Windows and MacOS too. Expanding the tab bar fixes this, but obviously I'm not going to have it expanded the entire time.

**Comment by qiyuey** [comment]
Windows too

**Comment by Shreesh-o** [comment]
Same Issue on Windows

**Comment by bl4zee1g** [comment]
Same issue on Arch Linux 6.11.6-arch1-1, only difference is for me it doesn't even get fixed when expanding the sidebar like @NoobToolzz described it. Installed through Arch User Repository

**Comment by hisamafahri** [comment]
My guess is that the intention of the blank space is for the workspace icon if the workspace feature is on. And if the workspace feature is off (or doesn't have an icon?), the space is not removed properly. 

**Workspace feature ON**
<img width="174" alt="image" src="https://github.com/user-attachments/assets/0487933a-a5b2-4df0-ae80-5cac9d98407b">

**Workspace feature OFF**
<img width="171" alt="image" src="https://github.com/user-attachments/assets/1b022bda-3155-4806-bd5f-c138a320885c">

---

Additional notes: after updating to `Version 1.0.1-a.18`, I am not even sure why workspace icon suddenly appears in the tabs section and how to turn it off. 
Maybe related to: `Added a workspace indicator that will show the workspace name and icon` in the latest [release notes](https://github.com/zen-browser/www/blob/57222f4f4d73b2727bdf33473210953c78176620/src/lib/release-notes.ts#L1531).

**Comment by theafterglow** [comment]
I don’t use the compact mode and it still happened to me.
Windows 11 24H2

**Comment by darkvergus** [comment]
The issue happens because your default workspace does not have an icon. Add an icon to it an you will see it there.

**Comment by mateuszkozakiewicz** [comment]
> The issue happens because your default workspace does not have an icon. Add an icon to it an you will see it there.

The issue also appears when workspaces are disabled

**Comment by spacey-sooty** [comment]
The new update has replaced this with the icon of my current workspace

**Comment by theafterglow** [comment]
![resim](https://github.com/user-attachments/assets/e2ac2612-54fb-4cc3-829f-7f41c1b683fe)
the blank space is still there after updating, i resetted the ui again

**Comment by berkaykrc** [comment]
Still relevant to the latest version of the desktop 1.0.2-b.3

**Comment by SkyLLerGithub** [comment]
You used to be able to remove the workspace button with zen.workspaces.show-workspace-indicator set to false, afaik this worked all the way until 1.0.2-b.2. Recent update to 1.0.2-b.3 broke it and it now happens again.

**Comment by mr-cheffy** [comment]
Should be fixed now 👍🏽 
Please let me know if that's not the case and I should reopen
