### ISSUE TITLE
Unnecessary animation for Essentials when switching workspacecs

### ISSUE THREAD

**Issue by thestrike72** [zen-browser/desktop#2799]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When switching workspaces, all tabs, including essentials have a nice slide/fade in animation to show that they are changing. This is great! However, now that essentials don't change between workspaces, they should not have an animation but instead stay in place.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.18

### What platform are you seeing the problem on?

Linux

**Comment by JSGRD22** [comment]
This has been resolved
