### ISSUE TITLE
Picture in picture is blank when loaded from the sidebar

### ISSUE THREAD

**Issue by dmac-au** [zen-browser/desktop#280]
### What happened?

I have just downloaded Zen today and I love the Sidebar as it's something I use in Vivaldi as well. 

My problem is when I load YouTube in the sidebar, I want to be able to open the video in a Picture in picture window so I can close the sidebar or keep the pip window if I switch desktops, etc. 

The "Pop out this video" button is visible, but when I click it, the pip window is blank and the video is still playing inside the sidebar. 

![Screenshot_20240816_223214](https://github.com/user-attachments/assets/48cee46c-8b3e-49d2-8d47-09f471e58179)

The grey box in the screenshot has all of the normal PiP decorations (play/volume/etc) but you can't close it and it obviously isn't playing the video. Even pressing the close icon doesn't work and I have to ALT+F4 the window. 

I tried Disable Mobile UserAgent and same thing. 

I am running 1.0.0-a.20 (64-bit) Linux Specific on Fedora 40 and KDE Plasma 6.1. 

Happy to provide any other information if you need. 

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a20

### Severity impact

Medium

### What platform are you seeing the problem on?

Linux

**Comment by unoscar** [comment]
Same problem here

**Comment by InterstellarOne** [comment]
Same problem here. I have the same operating system, and am running Wayland. Things I know about the problem:

- You can close the windows by right clicking on then and clicking close. 
- Clicking on the sidebar pop-out button again causes the current window to disappear and a new one is created in the center of the screen, _Unless you first drag the current pop-out window to another monitor, in which case both instances start. You can repeat this indefinitely._ 
- The windows don't appear in a screen recording, so I assume this is an issue related to Wayland. 

[Demonstration video](https://drive.proton.me/urls/S78C9986NR#SU3OVKD8TzKQ)

**Comment by cmcallister** [comment]
I'm seeing this on **macOS Sonoma 14.6.1** for _any_ attempt to open picture-in-picture, both sidebar and regular tabs

**Comment by mauro-balades** [comment]
Does this still happen?

**Comment by danmac** [comment]
@mauro-balades I have just checked in the latest Alpha (1.0.1-a.7) and it now works fine. This is on Fedora running KDE Plasma

Thank you if you fixed it, or carry on if you didn't and it fixed itself.

**Comment by mauro-balades** [comment]
I did fix it, thanks!

**Comment by japser34** [comment]
I also have this (at some point it was fixed but later it happened again). I downloaded the Twilight version, there it doesn't happen. I copied all my settings to the nightly, it still didn't happen, but when I signed in, the picture-in-picture was blank again.

I use windows 11.
