### ISSUE TITLE
Pinned & Essentials tabs unable to be unloaded at all. 

### ISSUE THREAD

**Issue by TMCraze** [zen-browser/desktop#2800]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Setting the unload automatic timer to it's lowest (1 min) or even trying to manually unload the tab doesn't do anything. Unloading works normally for non-pinned/essential tabs. 

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.18

### What platform are you seeing the problem on?

Windows

**Comment by TMCraze** [comment]
@dosu so then how

**Comment by TMCraze** [comment]
@dosu so then how do I change change the pinned tab behaviour so that they at least unload, while still keeping the behaviour for essential tabs?

**Comment by TMCraze** [comment]
@dosu how can i do this in the program/browser itself?

**Comment by TMCraze** [comment]
@dosu suitable workaround for now

**Comment by blakegearin** [comment]
On `1.0.1-a.19` I'm not able to unload any tabs through right click > Unload Tab. Auto-unload is working for normal tabs but not pinned or essentials.

@dosu The workaround is not suitable because "Close Shortcut Behavior" is not present in settings.

**Comment by JSGRD22** [comment]
> On `1.0.1-a.19` I'm not able to unload any tabs through right click > Unload Tab. Auto-unload is working.

It's the opposite for me. I can use the right click menu to unload tabs easily, but auto-unload does not work for pinned and essential tabs.
(There is also the bug where the website icon disappears if I middle click the tab to unload it that has not been fixed yet, but using the right click menu does not have this problem.)

**Comment by blakegearin** [comment]
@dosu This is still occurring on `1.0.2-b.4` for macOS Sonoma `14.5` (23F79)

**Comment by mr-cheffy** [comment]
This is a feature, pinned tabs arent unloaded automatically. That's kind of their purpose

**Comment by blakegearin** [comment]
@mauro-balades They should be able to be manually unloaded if the option is present on the right click menu, which it currently is. Manually unloading appears to have inconsistent behavior across operating system versions and the type of tab (normal, pinned, essential).

I don't believe this issue should be closed until these bugs are addressed.

**Comment by JSGRD22** [comment]
Pinned and essential tabs can be unloaded manually through all official means without any problem in 1.0.2-b.5 on Windows. Does it behave differently on other operating systems?

**Comment by blakegearin** [comment]
For `1.0.2-b.5` on macOS Sonoma `14.5` I cannot manually unload any tabs. That's the behavior I've seen since `1.0.1-a.19`
