### ISSUE TITLE
Workspace Indicator when sidebar is collapsed feels redundant

### ISSUE THREAD

**Issue by thestrike72** [zen-browser/desktop#2801]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When the sidebar is expanded, I think the workspace indicator between the essentials and pinned tabs makes sense because it has the name of the workspace which the workspace icon strip doesn't, and it acts as visual separation between essentials and pinned tabs.

However, when the sidebar is collapsed, the workspace indicator provides no more information than the workspace icon strip, so it's only remaining purpose is to act as visual separation between the essentials and the pinned tabs. It's also aggravated by the fact that clicking the workspace indicator does nothing even though it looks like a button when the sidebar is collapsed I propose that instead, zen use a divider line or even nothing as the difference between essentials and container tabs is already obvious with essentials having a different background.

This relates to an actual bug with the workspace indicator, which is that it isn't centered when the sidebar is collapsed.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.18

### What platform are you seeing the problem on?

Linux

**Comment by jasiralavibiztripz** [comment]
It doesn't align well and takes up realestate.
Please add a toggle button somewhere in the settings and make it optional (so we can remove it).
Optionally you can make it visible on expanded sidebar and hide in compact mode.
