### ISSUE TITLE
Links to the FAQ or documentation are broken

### ISSUE THREAD

**Issue by timbrueckner** [zen-browser/desktop#2803]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I was trying out ZEN and worked my way up to the security settings. When I clicked on the `Learn more` link of the `Block dangerous and deceptive content` option, it opened a broken URL: `https://docs.zen-browser.app/faqphishing-malware`.

<img width="580" alt="image" src="https://github.com/user-attachments/assets/d101b7d3-b789-4c5b-8872-495cc6fe00fe">

**Update**:

There are other links broken as well. I recently found different `Learn more…` links within the settings. Also, the link to the `Zen Browser Help` from within the `About Zen` dialog is broken.

<img width="653" alt="image" src="https://github.com/user-attachments/assets/dff8b736-1fde-4d09-8742-3d9d55ed0b7f">

<img width="398" alt="image" src="https://github.com/user-attachments/assets/41f2ad69-d5e6-457f-908f-5884b93bf095">

<img width="384" alt="image" src="https://github.com/user-attachments/assets/d66fbe3e-d9af-4696-8e50-83b720d1b9f4">

It seems to be a general issue.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.18 (Firefox 132.0.1) (aarch64)

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by jpumfrey** [comment]
Confirming the broken links in settings reported in this issue are fixed in version 1.0.1-a.19
