### ISSUE TITLE
ui is broken after update

### ISSUE THREAD

**Issue by QW4D** [zen-browser/desktop#2804]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

there is no close tab button and profile button is on top, workspace indicator isn`t centered if "Display workspaces as an icon strip" is set
![image](https://github.com/user-attachments/assets/d6c099f7-46b1-4ff1-a357-47697874f71f)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.18

### What platform are you seeing the problem on?

Windows

**Comment by shanujha** [comment]
@QW4D : **Workaround**: Downgrading to `1.0.1-a.17` fixed it.

Same issue faced on my Windows computer as well. Same version `1.0.1-a.18`. I manually went to the [releases page](https://github.com/zen-browser/desktop/releases/tag/1.0.1-a.17) and downloaded `1.0.1-a.17`. 

Simply double-click the installer to install this version. No problem of conflicts or overwrites, the installer handles those.
So it was great that i didn't have to lose my opened and pinned tabs and my sign-in. The installer just replaced the browser files and it was done.

**Comment by bapungiri** [comment]
The issue "**missing close tab button**" persists on version a.19 (windows).

**Comment by QW4D** [comment]
there is no close tab button because of superpins mod bug, so it doesn't apply to this, but other issues are still here on a.19

**Comment by shanujha** [comment]
I have to seriously stay on a.17. No matter how many times i have updated, or reinstalled. this continues to be the same, and same is observed on the latest release of Zen Twilight, the pre-release version
