### ISSUE TITLE
Duplicate Workspace indicator on tab bar

### ISSUE THREAD

**Issue by veryloooong** [zen-browser/desktop#2805]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Previously on 1.0.1-a.17, the workspace indicator is at the bottom left of the tab bar, and can be left-clicked to select a workspace.
![image](https://github.com/user-attachments/assets/d2aa9528-a937-4f8d-9806-83697282dab2)

But when updated to 1.0.1-a.18, there is another workspace indicator at the top, which cannot be left-clicked, only right-clicked.
![image](https://github.com/user-attachments/assets/941aea82-900e-44fc-b90d-45717c428129)

I have tried to disable this using config flag `zen.workspaces.show-workspace-indicator` but it doesn't seem to work when the tab bar is collapsed.

I can remove the bottom indicator with the Firefox customise option, but the top indicator cannot be clicked, which is an annoyance.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.18

### What platform are you seeing the problem on?

Windows

**Comment by jasiralavibiztripz** [comment]
It doesn't align well and takes up realestate.
Please add a toggle button somewhere in the settings and make it optional (so we can remove it).
Optionally you can make it visible on expanded sidebar and hide in compact mode.

**Comment by iambpn** [comment]
**For Hot-Fix:**
Follow this [tutorial](https://www.userchrome.org/how-create-userchrome-css.html) to create userChrome.css file and add the above CSS it will hide the profile icon.
