### ISSUE TITLE
Workspace touchpad swap gesture wrong direction

### ISSUE THREAD

**Issue by iLiranS** [zen-browser/desktop#2808]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When using the laptop mouse gesture to swap workspaces, for example swapping "⬅️ direction" should go to the next workspace, instead it goes to previous one, and when swapping this direction ➡️, it should go to previous, and instead it's going to the next one.

**Edit :**  also, as mentioned below, when the swipe is "too harsh" it will skip in-between workspaces.
<br>
**SOLVED :** the snapping has been solved in the latest twilight version, you can also change the direction behavior in `about:config` search for `zen.workspaces.natural-scroll` and set to true

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.18

### What platform are you seeing the problem on?

Windows

**Comment by spywhere** [comment]
This is happens the same on macOS with 'natural' scrolling behavior where swiping right expected to go to the previous workspace and vise versa.

**Comment by Jan-DT** [comment]
it generally behaves a bit weird, for me it switches multiple workspaces even though I only swipe a tiny bit

**Comment by iLiranS** [comment]
> it generally behaves a bit weird, for me it switches multiple workspaces even though I only swipe a tiny bit

Yeah, it should be snapped to the next workspace instead.

**Comment by Taewan-P** [comment]
This happens to me as well. Switching between workspaces with the touchpad is a bit weird. It should be snapped for each workspaces. Also in some cases, it moves the opposite direction even though I am scrolling in the same direction.

edit: I do not use natural scrolling

https://github.com/user-attachments/assets/d8cf2fda-0b9f-49a8-9793-1149faa5173b

**Comment by JSGRD22** [comment]
This should be an option, whether to use natural scrolling or not when swiping workspaces.

**Comment by GregoireGaonach** [comment]
> This happens to me as well. Switching between workspaces with the touchpad is a bit weird. It should be snapped for each workspaces. Also in some cases, it moves the opposite direction even though I am scrolling in the same direction.
> 
> edit: I do not use natural scrolling
> Screen.Recording.2024-11-15.at.4.09.27.PM.mov

I have exactly the same weird opposite direction behavior on my side (1.0.1-a.19 (Firefox 132.0.1) (aarch64))

**Comment by sannidhyaroy** [comment]
I am on Fedora 40 and have the same issue.

**Comment by Taewan-P** [comment]
Just updated to the latest version.
Now it does snap, but the direction is fixed to natural scrolling users. I don't use natural scrolling, so the scroll direction should be opposite, but behaves like natural scrolling.

This should be an optional feature, like [JSGRD22](https://github.com/JSGRD22) said above.
