### ISSUE TITLE
Popup window bug

### ISSUE THREAD

**Issue by wcazbca** [zen-browser/desktop#2810]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I logged into github with Google account, that opened popup windows, where I logged into a Google account. After 2FA, I was successfully logged into GitHub, but the popup window did no close, it had content of one of my pinned tabs and was not able to close it, there were no buttons, and cmd+w was only showing homepage.
<img width="1499" alt="image" src="https://github.com/user-attachments/assets/7d341eb6-3a13-437e-97c3-6c4dac4eb44e">

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.18 (Firefox 132.0.1) (aarch64)

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by chadkoh** [comment]
Just a note: in order to close the popup window, go to Menu > Toolbars > Customize Toolbar and  check "Title Bar" which will give you the window controls. You can click the red X to close the window, then go back into Toolbar prefs and uncheck Title Bar to get ZB back to normal.

**Comment by MrPiggy105** [comment]
Ran into this yesterday. Command(/ctrl) shift w, _while focused on the window_, closes all tabs in that window. This is probably related to #2816 (although it's not a private window, it should still be ignored)

**Comment by tashilapathum** [comment]
This happaned to me as well. For me there was no problem closing the popup windows. This was happenning everytime a popup windows was opened and the process of the popup window has finished. I only had one pinned tab and only the default workspace. Also I'm a relatively new Zen user so most of the settings are defaults.

**Comment by CptnFizzbin** [comment]
ran into the same issue, #2985

**Comment by mr-cheffy** [comment]
Should be fixed now 👍🏽
