### ISSUE TITLE
pinned tab bug

### ISSUE THREAD

**Issue by rajath-2** [zen-browser/desktop#2813]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

when you switch workplaces the previously opened pinned tab doesnt open by default even if it was the last used tab in that workspace

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.18

### What platform are you seeing the problem on?

Windows

**Comment by universish** [comment]
https://github.com/zen-browser/desktop/issues/2872
