### ISSUE TITLE
Essentials URL not resetting on exit.

### ISSUE THREAD

**Issue by asidius** [zen-browser/desktop#2817]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When exiting the browser my Essentials tabs are not resetting to the original URL I pinned. 

I have confirmed "Restore pinned tabs to their originally pinned URL on startup" is checked.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.18

### What platform are you seeing the problem on?

Windows

**Comment by asidius** [comment]
Also, it is also not working for the normal pinned tabs.

**Comment by progamer63** [comment]
following what dosubot suggested in #2, right clicking the essential or pinned tab and clicking "replace pinned url with current" or "reset pinned tab" fixes the url
i have "restore pinned url to orignal" and close behavior set to "reset, unload, and switch to next tab"

**Comment by ugaugabuga** [comment]
**Restore pinned tabs to their originally pinned URL on startup** feature is actually broken for now. I've tested it along with all the solutions mentioned here, nothing worked.

**Comment by kristijanribaric** [comment]
Sorry guys, fixed!
