### ISSUE TITLE
video playback is completely broken

### ISSUE THREAD

**Issue by 4rtemis-4rrow** [zen-browser/desktop#2824]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

video playback is not working on any site, the frame at the current position is displayed, nothing else though, nor any audio

I tested this on youtube and jellyfin, same problem

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

latest, I had just updated like 5 minutes ago, and I'm using arch linux

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
nothing seems out of the ordinary in the logs
```

**Comment by 4rtemis-4rrow** [comment]
it's not working on local files either, I tried mp4, mkv, and webm, all completely broken, same issue

I actually did face this same bug before, it was fixed after updating, but since I'm on the latest release and there is nothing to update.... yeah

**Comment by andwond** [comment]
I got the same issue on Windows. I tried new clean profile, and playback worked initially. But when I close and reopen, the issue return.

**Comment by 4rtemis-4rrow** [comment]
new piece of info

playback did work, but only if the video was muted, tested on youtube, reddit, and jellyfin, so I'm guessing the issue is with audio playback? idk

given the info provided by @andywondering, it's obvious the issue isn't OS specific or config specific either, I'm surprised more people didn't report this

**Comment by towelieisprettychill** [comment]
my video playback works as expected. greetings from mac

**Comment by 4rtemis-4rrow** [comment]
fixed

turns out it wasn't caused by zen, it was caused by wireplumber

if you face this issue, remove `wireplumber` and install `pipewire-media-session` (archlinux package names, idk about other distros)

and idk what's causing it for @andywondering, so I suggest you open a new issue
