### ISSUE TITLE
1.0.1-a.18. ve önceki sürüm.

### ISSUE THREAD

**Issue by Charybdis-GZR** [zen-browser/desktop#2826]
### Captchas

- [ ] I have read the instructions.
- [ ] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

Hello, I am using Compact mode. Hide sidebar is active, but the sidebar is constantly stuck. This was also in the previous version, I thought it would not be in the new version, but I wanted to let you know because I saw that it is still stuck. It keeps hanging unless you hover the mouse over it, after a while it starts to get annoying. When it is stuck, the browser slides to the left, buttons like the settings button are not visible. Check the image here, this SS is taken from the full page.

![Ekran görüntüsü 2024-11-10 164450](https://github.com/user-attachments/assets/f541092e-ffb8-4678-98e6-e6d6a2c5214e)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.18.

### What platform are you seeing the problem on?

Windows

**Comment by KiKaraage** [comment]
Adding screen record for better context on this issue.
[screen-recorder-mon-nov-11-2024-12-23-17.webm](https://github.com/user-attachments/assets/8341dc58-55aa-4c8d-b171-8bfa419b021e)

**Comment by Charybdis-GZR** [comment]
@KiKaraage YES.
