### ISSUE TITLE
Both the close and fullscreen button of glance misbehavior

### ISSUE THREAD

**Issue by nftuoa** [zen-browser/desktop#2827]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.

### What happened?

While in the glance, the close button has a wrong highlighting and the fullscreen button simply doesn't work.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.
(Firefox does not have glance)
### Version

1.0.1-a.18

### What platform are you seeing the problem on?

Linux

**Comment by SuperAtraction** [comment]
Hello, I had the same problem, and the solution I found was to update the Zen Mods.

**Comment by nftuoa** [comment]
> Hello, I had the same problem, and the solution I found was to update the Zen Mods.

let me try that, thanks

**Comment by devosm** [comment]
> Hello, I had the same problem, and the solution I found was to update the Zen Mods.

I had the exact same issue and this solved it for me!
Maybe an auto update feature for Zen mods could be a good idea, or a notification that tells you to update Zen mods some time after updating the browser itself
