### ISSUE TITLE
Pinned tabs favicon disappears

### ISSUE THREAD

**Issue by justingallant1988** [zen-browser/desktop#2832]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The pinned tabs favicons disappear when using cmd + w.

https://github.com/user-attachments/assets/be561340-483d-44e3-9f81-ba620cddd8cb

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.18

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by jalzur** [comment]
Same as #2789 (but with essentials).

**Comment by mr-cheffy** [comment]
This has been fixed long time ago, thanks!
