### ISSUE TITLE
Netflix, disney... 

### ISSUE THREAD

**Issue by Hestranha** [zen-browser/desktop#2834]
### Captchas

- [X] I have read the instructions.
- [ ] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

Error en disney, al abrir una pelicula:
![imagen](https://github.com/user-attachments/assets/45f2e5f9-26b6-4528-acb1-fa3ce935297c)
Error en netflix, al abrir una pelicula:
![imagen](https://github.com/user-attachments/assets/fbd45516-1d9b-4983-9bf0-289b78b33760)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1a a.18

### What platform are you seeing the problem on?

Windows

**Comment by LeMoonStar** [comment]
Hey! Zen currently has no DRM license, so lots of streaming services such as Netflix, Disney or Spotify don't work as expected. I cannot tell you when or even if Zen will ever gain a DRM license. Please see our official [FAQ](https://docs.zen-browser.app/faq#why-cant-zen-browser-play-drm-protected-content).

Also: Please write GitHub issues in English, Zen is an international project, of which the majority can understand English. People have to be able to search, find and understand these issues without too much work. Thank you!

I will be closing this as not planned for now, as has been the case for any other DRM-Related issues. If you do have something to add, or think this issue has been wrongfully closed, please comment or re-open this issue.
