### ISSUE TITLE
(Request) Requesting for "+ new tab" button to be static and stable and doesnt go into hiding as scrolling or when multiple tabs are open.

### ISSUE THREAD

**Issue by ghost** [zen-browser/desktop#2835]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Requesting for "+ new tab" button to be static and stable and doesnt go into hiding as scrolling or when multiple tabs are open.

Only vivaldi currently has this issue but edge and brave has stable new tab button that doesnt goes away when scrolling.

I expect it to be stable regardless.

![Screenshot 2024-11-10 215304](https://github.com/user-attachments/assets/610b3787-2213-413a-be1d-4805f7db6adc)

![Screenshot 2024-11-10 215329](https://github.com/user-attachments/assets/cecf5faa-3a0d-4386-b075-9b132d8c9052)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.18

### What platform are you seeing the problem on?

Windows

**Comment by Damglador** [comment]
Having to scroll to the bottom each time I want to open a new tab drives me insane. There is another button for this on the bottom minipanel, but it's harder to hit, and ideally there shouldn't be a duplicate button for the same action almost in the same place.

**Comment by blakegearin** [comment]
In case anyone wasn't aware, you can move this button to the top as well if you want to avoid scrolling down.

Settings > Look and feel > Sidebar and tabs layout > Move the new tab button to the top

It's not static, but neither is Arc's and the keyboard shortcut (`Cmd + T`) is always an option.

@varnit-nigam Also worth noting, this issue doesn't follow the repo's guidelines. Issues are for bugs, not enhancement requests. It's a checkbox on the template and it was checked.

>  I am not filing an enhancement request.

**Comment by Damglador** [comment]
> In case anyone wasn't aware, you can move this button to the top as well if you want to avoid scrolling down.
> 
> Settings > Look and feel > Sidebar and tabs layout > Move the new tab button to the top

Somewhat better, but still would be nice to have it pinned as a big button at the bottom, at least as an option

**Comment by cheeeebs** [comment]
Update to 1.0.1 a.19, it has the button in customize toolbar.

**Comment by ghost** [comment]
> Having to scroll to the bottom each time I want to open a new tab drives me insane. There is another button for this on the bottom minipanel, but it's harder to hit, and ideally there shouldn't be a duplicate button for the same action almost in the same place.

Agreed. But as said before, it is not static. One has move around (I use zen for work so 100 to 200 tabs are normal) to get new tab. Vivaldi suffers same fate, and their team is ignorant on this, so they lost being an alternative but not edge and brave.

**Comment by ghost** [comment]
Stale? 

I dont know, should this be fresh?

**Comment by mr-cheffy** [comment]
>  I am not filing an enhancement request.
