### ISSUE TITLE
Odd Spacing on Tab Bar

### ISSUE THREAD

**Issue by soggyramennoodle** [zen-browser/desktop#2838]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Where an essential tab should be, there is a big empty space if the user doesn't have any essential tabs pinned. This creates an awkward blank space.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.18

### What platform are you seeing the problem on?

Windows

**Comment by darkvergus** [comment]
Its not that, its due to the fact your workspace doesn't have an icon.

**Comment by darkvergus** [comment]
Also duplicate of #2796
