### ISSUE TITLE
Workspaces missing (macOS) 

### ISSUE THREAD

**Issue by centuryboy774** [zen-browser/desktop#2845]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Work spaces are gone! On the windows 11 and Linux versions which I have used. The work spaces work and are shown. On MacOS their just gone. the space at the top where the workspace icon is suppose to to be shown to tell you which worksapce is missing. At the bottom there's no way to make new workspaces or even see them. Workspace as a whole are just gone. 

![MacOS](https://github.com/user-attachments/assets/89d3fae0-a682-4510-898b-0699e31d8342)
![Windows11](https://github.com/user-attachments/assets/6445c5ec-a7ff-4a4f-bf9d-3ae12b912d97)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.18

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by stefanosandes** [comment]
Yes, same problem here. In addition to this:  
-  All my essentials tabs are gone  
-  Workspaces are gone too (only the default remains)  
-  Many little windows (like popups) keep opening with no content, behind the main window, and I can't close them.

Image of the extra windows opened with Zen (main windows on the right):
![CleanShot 2024-11-10 at 17 07 05@2x](https://github.com/user-attachments/assets/c03a68db-c3d8-4511-bdef-039b2754ca9a)


macOs Sequoia 15.1

**Comment by centuryboy774** [comment]
Thank you for trying to help but weirdly enough after I opened zen it gave me the new start menu asking what search egine etc... then on after I went though that to see what was up the work spaces came back. I have no idea what happened but it's working now. I just uninstalled it and reinstalled it just in case. Not sure if I should close this issue or not. I am on macOs Sequoia 15.1 as @stefanosandes is!

**Comment by centuryboy774** [comment]
> Yes, same problem here. In addition to this:
> 
>     * All my essentials tabs are gone
> 
>     * Workspaces are gone too (only the default remains)
> 
>     * Many little windows (like popups) keep opening with no content, behind the main window, and I can't close them.
> 
> 
> Image of the extra windows opened with Zen (main windows on the right): ![CleanShot 2024-11-10 at 17 07 05@2x](https://private-user-images.githubusercontent.com/6722075/384722691-c03a68db-c3d8-4511-bdef-039b2754ca9a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyNzI2OTgsIm5iZiI6MTczMTI3MjM5OCwicGF0aCI6Ii82NzIyMDc1LzM4NDcyMjY5MS1jMDNhNjhkYi1jM2Q4LTQ1MTEtYmRlZi0wMzliMjc1NGNhOWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTBUMjA1OTU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjM0YmZjM2FiYWExZGQ1OTNmM2I4ZDIzZTA2OTBlYjBlMjA5YjkzYmI3YjEwMjM4MTBkOTU3M2IxN2Y1ZThkNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.k5RleKrGQCM3MaA8Wyly5gowPC6DjAbMOS_YnMVgRHM)
> 
> macOs Sequoia 15.1

Not sure if what happened to me will happen to you but mines working well now. I am also on macOs Sequoia 15.1
Weirdly enough mabye reinstalling it might fix it, how it fixed itself was strange.

**Comment by stefanosandes** [comment]
@centuryboy774 So, reinstalling solved some issues, but the extra window popup keeps appearing for me. I've disabled all extensions, unpinned and closed all the tabs, and removed all essentials, but it keeps appearing. This time it's just one window, and it is opening on github.com, one of my essentials that I've removed. I think this issue could be linked to the essentials feature.

**Comment by stefanosandes** [comment]
Update: This time, after removing all essentials, I'm able to close the extra window, and after restarting the browser, it doesn't appear anymore.
