### ISSUE TITLE
Issue Clicking on Buttons during Onboarding (Windows)

### ISSUE THREAD

**Issue by luke-monroe** [zen-browser/desktop#2849]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

During onboarding, on windows when I click on the buttons to set the theme colors, several of the buttons don't work unless I double click them (some of them did work with a single click). Similarly, one of the continue buttons required a double click to work. This is a problem as double clicking triggers the window to maximize or restore.

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.18

### What platform are you seeing the problem on?

Windows

**Comment by andrewpey** [comment]
Can confirm. Additionally:
- The window cannot be dragged or maximized manually.
- However, it does maximize when double-clicking on the unselectable colors  (those colors get selected when double-clicked).
- For colors that can be selected (starting from orange to the right), double-clicking does not maximize the window.
- The next screens are also affected: the "Back" button works only on double-click and the window maximizes.

Setup:
- Zen v1.0.1-a.22  
- Windows 11 22631.4541
- Two monitors:  
  - 2560 x 1440 (100% DPI, where Zen was open)  
  - 3840 x 2160 (150% DPI)  


https://github.com/user-attachments/assets/d214e273-f6dd-4264-896d-7a390838fe96

**Comment by luke-monroe** [comment]
This was fixed in the beta release
