### ISSUE TITLE
Pwa and chrome extension support 

### ISSUE THREAD

**Issue by kasrahacker** [zen-browser/desktop#285]
### What feature would you like to see?

Hi I'm using zen browser for around 3 days.  I just wanted to request pwa support and chrome extension support (like waterfox). This 2 features can make zen browser one of most compelet browsers.

### What platform are you seeing the problem on?

Windows

**Comment by n7itro** [comment]
Waterfox's implementation of Chromium extensions is buggy and native PWA's are being considered by the Mozilla team.

These features are not planned or feasible for the Zen team for the time being.

**Comment by tylrh** [comment]
Any news on this
