### ISSUE TITLE
Workspace icon appears next to three dot icon

### ISSUE THREAD

**Issue by Itstonmoy** [zen-browser/desktop#2850]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When workspace feature is turned off, and workspace button/icon is removed from tab bar or top bar, then workspace button automatically appear next to the (...) three dot menu icon. Then, it can't be removed. It disappears when I click 'customize toolbar' option. But again reappear if I reboot the browser.

Default workspace name and icon is still visible at the top of the tab bar if there is only one workspace or workspace featured is disabled. On new setup, blank space is appeared.

Video link to this issue: https://drive.google.com/file/d/1h8bqqjCmEM_eh6Oe9OlBqJU9f3t_Re4k/view?usp=sharing

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.18 (Firefox 132.0.1) (64-bit)

### What platform are you seeing the problem on?

Linux, Windows

**Comment by villekivela** [comment]
Seeing it on mac too
