### ISSUE TITLE
Url Select

### ISSUE THREAD

**Issue by Rexxyyy** [zen-browser/desktop#2858]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.

### What happened?

url select in zen: When every i try to click on url while on a website, it should select whole url but it wont. most of the time it goes to the beginning of the url (Unlike firefox stable), then i have to select whole website url again.
Attached issue video on youtube
[https://youtu.be/mDH9bznUbCw](url)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.18 (Firefox 132.0.1) 

### What platform are you seeing the problem on?

macOS - aarch64

### Relevant log output

```shell
i dont have log, but i uploaded video
```

**Comment by Rexxyyy** [comment]
This is no longer an issue in 1.0.1-a.22 (Firefox 132.0.2) aarch64-Mac OS .
Tnx.

**Comment by Rexxyyy** [comment]
1.0.2-b.0 (Firefox 133.0) arch64-Mac OS , issue is back

**Comment by mr-cheffy** [comment]
Should be fixed now 👍🏽 Please let me know if that's not the case and ill reopen
