### ISSUE TITLE
Using compact mode to adjust UI density

### ISSUE THREAD

**Issue by awwpotato** [zen-browser/desktop#286]
### What feature would you like to see?

It would be great if Zen could reduce the size of the navbar, buttons, etc when compact mode is enabled, like how Firefox does (Customize toolbar > Density > Compact).

### What platform are you seeing the problem on?

Linux

**Comment by NOCanoa** [comment]
This cold be a nice use case of the upcoming : [themes shop](https://www.zen-browser.app/themes)
Whitch will have alot of custumization themes for all sort of those things
