### ISSUE TITLE
Bug that the sidebar opens and closes when dragging the mouse left while the sidebar is hidden.

### ISSUE THREAD

**Issue by universish** [zen-browser/desktop#2867]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.

### What happened?

When “compact mode (C)” is active and “hide sidebar” is active in compact mode, or when “hide both (H)” is active and “expand sidebar” button is active (sidebar is wide), dragging the mouse to the left opens the vertical sidebar. Then it immediately hides and closes. If you move the mouse to the right as soon as you drag the mouse to the left and stop it anywhere above the sidebar, the sidebar is not hidden, it remains open. 
This does not happen when the “expand sidebar” button is inactive (when the sidebar is narrow). 

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Alpha build - 1.0.1-a.19

### What platform are you seeing the problem on?

Linux, Windows

**Comment by ilahazs** [comment]
You can fixed it by make the sidebar in regular mode more bigger than before.

In my case this problem occur when I had so much content inside sidebar (horizontally) like 7+ workspaces.

But after reducing the workspaces to 4, the problem disappear

**Comment by universish** [comment]
on fedora 41 appimage version and windows 11

**Comment by universish** [comment]
Your suggestion worked. I increased the sidebar width, turned compact mode off and on, turned Zen browser off and on, then narrowed the sidebar length to the minimum, and now I don't have this problem anymore. Interestingly, it's fixed.
Thanks.

**Comment by ilahazs** [comment]
> Your suggestion worked. I increased the sidebar width, turned compact mode off and on, turned Zen browser off and on, then narrowed the sidebar length to the minimum, and now I don't have this problem anymore. Interestingly, it's fixed. Thanks.

glad to hear that works, still it's a weird bug that dev need to fix

**Comment by universish** [comment]
This error sometimes persists in linux.
It also happens all the time in Windows.
That's why I'm bringing it up again. 
Because the error persists.

This topic has nothing to do with 3002.

**Comment by universish** [comment]
The problem was fixed with 1.0.2-b.0 (64 bit).
