### ISSUE TITLE
Pop-up windows have huge whitespace on the left side. 

### ISSUE THREAD

**Issue by Donnnno** [zen-browser/desktop#287]
### What happened?

When launching Bitwarden using their pop-out function, or when logging in (using control + shift + L), the window has a pretty weird empty block on the left side. 

![image](https://github.com/user-attachments/assets/31af7763-0481-4658-ae3a-cb7e3a269fd2)

![image](https://github.com/user-attachments/assets/a44422a2-1196-4db0-89b7-3449b62c51b7)
![image](https://github.com/user-attachments/assets/882ecb73-13c1-4b9b-bfda-388f07abd28c)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.20

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
Fixed, thanks!

**Comment by Donnnno** [comment]
faster than light ✨
