### ISSUE TITLE
Pinned tab deleted (unpinned) in window with pinned tab

### ISSUE THREAD

**Issue by universish** [zen-browser/desktop#2871]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.

### What happened?

More than one window was open. The first window had pinned tabs. Other windows had no pinned tabs. I closed the first window. Then I closed the other windows. When I opened the Zen browser again, there were no pinned tabs (unpinned). Pinned tabs disappear.
Clear history or close tabs settings are off. Tabs don't close, old tabs reopen every time I open the browser. But the pinned tabs did not open, nor were they fixed.
(No pinned tabs when opening other windows. I want pinned tabs to open in every window).

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Alpha build - 1.0.1-a.19

### What platform are you seeing the problem on?

Linux, Windows

**Comment by BoscoDomingo** [comment]
I can reproduce:

https://github.com/user-attachments/assets/7de919d1-6f90-4da5-b843-a79b30fad075

It even closed the window where I only had 1 pinned tab. When using Ctrl + Shift + T (reopen closed tab) all pinned tabs reappear in the correct place
