### ISSUE TITLE
When I open a new window, the pinned tab does not appear or is not pinned in the new window.

### ISSUE THREAD

**Issue by universish** [zen-browser/desktop#2872]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When I open a new window, the pinned tab does not appear or is not pinned in the new window.
I have pinned tabs. The first window opens with these tabs pinned. When I open more than one window, there are no pinned tabs in other windows. I want the pinned tabs to open in every window.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Alpha build - 1.0.1-a.19

### What platform are you seeing the problem on?

Windows

**Comment by universish** [comment]
on fedora 41 and windows 11

**Comment by TheTrueFerret** [comment]
i have the same issue, and when i close the windows without the pinned tabs and close the window with the pinned tabs.. fully closing zen browser.
all my pinned tabs are gone when reopening the browser, which is logical because it remembers the latest pinned tabs i guess.
but a very annoying issue

**Comment by TheTrueFerret** [comment]
it's probably to late... but it is still there in the latest release
