### ISSUE TITLE
Theme reset ater moving through workspaces

### ISSUE THREAD

**Issue by jandroav** [zen-browser/desktop#2873]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I set the default dark theme and then if I select any other workspace then the color goes purple in all workspaces. See video.

https://github.com/user-attachments/assets/2d4bcdc2-1e66-4f2e-800f-3356d6ba7dda

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.19

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by AlphaCraft9658** [comment]
The same thing happens with the new feature for changing the design colors. While I think different styles for different workspaces is a neat feature, it should be optional. I think a good compromise for that would be to have a checkmark to ask whether to apply the colors to all workspaces by default, and maybe there could also be some kind of selection to apply a color theme to multiple workspaces at once.
