### ISSUE TITLE
Pinned tab opens in Pop-up after 'pop-up close'

### ISSUE THREAD

**Issue by ramondeleonca** [zen-browser/desktop#2877]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When signing into Symbolab with a google account a pop-up opens with the Google authentication flow, when finished the pop-up 'tab' closes, leaving behind the same pop-up with the pinned tab open.

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.18 (Firefox 132.0.1) (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by lancewilhelm** [comment]
Still getting the same thing on 1.0.1-a.19 (Firefox 132.0.1) (aarch64), macos Sequoia 15.1, macbook air m2. Furthermore, the only way to close this window on macos is either via the keyboard shortcut or through the menu.
