### ISSUE TITLE
DRM Content

### ISSUE THREAD

**Issue by fernbacher** [zen-browser/desktop#288]
### What happened?

i cannot play DRM content and so i cannot access my subscription based video services.
![image](https://github.com/user-attachments/assets/999ce5ac-54c8-4a18-b9b2-0f13bcf02145)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.20 (64-bit)

### Severity impact

High

### What platform are you seeing the problem on?

Windows

**Comment by naomieow** [comment]
Can confirm on Linux as well

**Comment by mauro-balades** [comment]
This is fixed for next release, it will be available soon!
