### ISSUE TITLE
blank at the top of the tab

### ISSUE THREAD

**Issue by xenlsa** [zen-browser/desktop#2885]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

So I closed the workspace, and there was a blank space, and I wanted to be more compact.
![PixPin_2024-11-11_18-07-29](https://github.com/user-attachments/assets/5ac217ac-e955-47d5-8285-b793631bf2ed)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.19 

### What platform are you seeing the problem on?

Windows

**Comment by universish** [comment]
https://github.com/zen-browser/desktop/issues/2869
Issue repeated. Please close the issue.
