### ISSUE TITLE
Can't watch DRM content on Netflix

### ISSUE THREAD

**Issue by lntreter** [zen-browser/desktop#2886]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When i tried to watch Arcane season 2 on Netflix, this screen pops up.  

![Untitled111](https://github.com/user-attachments/assets/1bcaad36-e7f5-4c76-90a1-9abb2910e6cb)

I tried enable DRM but did not work.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.19

### What platform are you seeing the problem on?

Windows

**Comment by Tc-001** [comment]
https://docs.zen-browser.app/faq#why-cant-zen-browser-play-drm-protected-content

This won't be solved in the near future, if ever

**Comment by lntreter** [comment]
Thanks for reply and sorry for the unnecessary issue.
