### ISSUE TITLE
 Tab bar animation glitch: Erratic movement during hover state

### ISSUE THREAD

**Issue by dsincl12** [zen-browser/desktop#2891]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Current Behavior: When hovering over a hidden tab bar:

    New tab icon incorrectly shifts to the far left before settling in final position
    Existing tabs abruptly jump upward
    Results in visually disruptive animation

Expected Behavior:

    Smooth transition of tab elements
    New tab icon should move directly to its final position
    Existing tabs should maintain stable vertical position during animation

Visual Impact: The current animation creates a jarring user experience with unnecessary movement before elements reach their intended positions.

https://github.com/user-attachments/assets/cde122cf-458f-4d63-b356-86b6b0c5bb76

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.19

### What platform are you seeing the problem on?

Linux

**Comment by antikovt** [comment]
Adding to this: the tabbar has no collapse animation. It just jumps back in one frame once you remove the cursor.

Also the animation is disgusting when you have multiple Essentials, though I'm not sure how one would fix this
