### ISSUE TITLE
Weird gap between home button and tabs

### ISSUE THREAD

**Issue by thechief77** [zen-browser/desktop#2895]
### Captchas

- [x] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Like i said in the title, there is a weird gap that wasn't there before last update.
![resim](https://github.com/user-attachments/assets/28e9d407-2a36-4d48-b1d9-da5e531e734a)

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.19

### What platform are you seeing the problem on?

Windows

**Comment by universish** [comment]
https://github.com/zen-browser/desktop/issues/2869
Issue repeated. Please close the issue.
