### ISSUE TITLE
Pinned tabs showing as a list instead of a grid of icons

### ISSUE THREAD

**Issue by Zinnavoy** [zen-browser/desktop#2902]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Since today (so, since last update) my pinned tabs shows as a list of tabs instead of a grid of icons, although I didn't change any settings at all.

![{FA1B8916-8AB3-434E-9762-5776FB1DA45D}](https://github.com/user-attachments/assets/44e437ba-d5a4-49f9-9f73-43f6a4579873)

I don't see anything related to this in the Release Notes for this version so I think it was not intended, unless it is related to `Changed default layout of the browser, you might want to reset your layout to default` in which case I'd need to know how to reset the layout to default, I couldn't find any setting for this.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.19

### What platform are you seeing the problem on?

Windows

**Comment by jjguzme** [comment]
Hi, I'm getting the same exact issue, and I don't if this is part of a new feature, but I would like to have the options to choose between grid and list mode, any solutions for this? The only solution that I know is installing [superpins](https://zen-browser.app/mods/ad97bb70-0066-4e42-9b5f-173a5e42c6fc) extension.

**Comment by thiagotcx** [comment]
Try to add your pinned tabs how essentials tabs...
Right click and "Add to Essentials"

**Comment by plankobostjan** [comment]
I was having the same issue and what @thiagotcx suggested helped.

Does that mean that pinned tabs are getting replaced with essential tabs? If that's the case, then I think this should be noted somewhere and "Pin Tab" option should be removed from the menu.

**Comment by BoscoDomingo** [comment]
> I was having the same issue and what @thiagotcx suggested helped.
> 
> Does that mean that pinned tabs are getting replaced with essential tabs? If that's the case, then I think this should be noted somewhere and "Pin Tab" option should be removed from the menu.

No they are not. Pinned tabs are for workspaces and (I think) window-specific. Essentials are shared amongst workspaces and (I think) windows

**Comment by plankobostjan** [comment]
@BoscoDomingo thanks. I just noticed this myself.

For anyone wondering. It was mentioned in [this](https://github.com/zen-browser/desktop/issues/2910#issuecomment-2468993926) issue.
And also in the release notes for 1.0.1-a.18.
![image](https://github.com/user-attachments/assets/60313700-a0a9-466c-b47a-d39e5123faa3)

**Comment by johnvanham** [comment]
Aw no, I wanted to have different 'essential' (as was, pinned) tabs per workspace. I have two workspaces, one for work one for personal. Now the pinned tabs scroll also so I can't easily click into the apps I need. And essentials are across all workspaces. 

Can we request that essentials have a setting to make them be workspace specific? :-)

**Comment by BoscoDomingo** [comment]
> Can we request that essentials have a setting to make them be workspace specific? :-)

AFAIC that's what pinned tabs are for

**Comment by johnvanham** [comment]
> > Can we request that essentials have a setting to make them be workspace specific? :-)
> 
> AFAIC that's what pinned tabs are for

Sure, but now they take up a lot more room as they appear like normal tabs, plus they are contained within a small scroll area.

I've just found a mod which styles pinned tabs like they used to be (IE like essential tabs) which is great, however the scrolling is a problem as it looks like half my pinned tabs have disappeared until I remember they scroll.

**Comment by Zinnavoy** [comment]
Yea, I feel the same as @johnvanham. I had "essential" tabs per workspace (stuff like vercel ou sentry was pinned as grid in my work workspace and netflix and youtube music was pinned as grid in my personal). 

Although I like the idea of having "global" essencial tabs and "local" pinned tabs, there should be a option to make both of them grid style so we can lock some tabs at the top of the side bar.

**Comment by gillmourtunhira** [comment]
@Zinnavoy you can install Superpins mod, and enable them

**Comment by SearingEchoes** [comment]
Personally not the biggest fan of this change as well, it feels too bloated. Will have to get used to it I suppose.

**Comment by neurokitti** [comment]
I think this is more of an issue with the feature than a bug
