### ISSUE TITLE
List all Tabs slow to render

### ISSUE THREAD

**Issue by miranyx** [zen-browser/desktop#2905]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The list all tabs window is slow to render in with 1500 tabs. Takes around 10 seconds.
I would expect it to render in in sub second times.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.19

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by Richard-Woessner** [comment]
Thank you for bringing this up but I believe that right now that is alright for 1500 tabs. We can look into this in the future. Closing

**Comment by mr-cheffy** [comment]
How does normal Firefox render 1500 tabs?

**Comment by miranyx** [comment]
In Firefox when going over the Firefox view, View All open tabs, it is loaded instantly for 1700 tabs.

**Comment by cheeeebs** [comment]
Can you send a video recording?

**Comment by miranyx** [comment]
[Video](https://embed-video.foobar.vip/videos/2024-11-12_14-38-47.mp4)

**Comment by cheeeebs** [comment]
Try using `about:firefoxview` instead of the button.

**Comment by miranyx** [comment]
In zen that is also instant.

**Comment by cheeeebs** [comment]
Can you try also using the list all tabs button on Firefox? This may be a Firefox problem instead of a Zen issue.

**Comment by miranyx** [comment]
In Firefox still not instant but way faster than in Zen:
[Video](https://embed-video.foobar.vip/videos/2024-11-13_11-22-35.mp4)

**Comment by cheeeebs** [comment]
Seems this is legitimately a Zen problem, hope a dev can look into this. For now you can just pin/add as essential and use `about:firefoxview`.

**Comment by plutonium-239** [comment]
Commenting to open this up again
