### ISSUE TITLE
Some symbols not working properly on Word files

### ISSUE THREAD

**Issue by shirinqush** [zen-browser/desktop#2906]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Some symbols on word files not working properly. Black screenshor is Zen and white one is Safari. Firefox has same problem.
<img width="116" alt="SCR-20241111-qxbc" src="https://github.com/user-attachments/assets/dce10b32-a4b2-449c-93b1-bce9df7528f8"> <img width="122" alt="SCR-20241111-qxcn" src="https://github.com/user-attachments/assets/9535b7c4-ef23-4d1b-9210-a7563f2c0942">

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.19

### What platform are you seeing the problem on?

macOS - Intel

**Comment by Richard-Woessner** [comment]
Thanks for bringing this up but if Firefox has the same project it has more to do with the engine than zen. Closing
