### ISSUE TITLE
When you expand the sidebar, the toolbar also moves to the right.

### ISSUE THREAD

**Issue by universish** [zen-browser/desktop#2907]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Pressing the expand sidebar button (arrow to the right at the top, arrow to the left icon at the bottom) expands the sidebar. The icons at the top also move to the right. There is a gap between them.
If I fill in the gaps by adding new buttons with “Customize toolbar”, the problem persists. It shifts by 1 few millimeters. The more I increase the width of the sidebar, the more the toolbar buttons shift to the right and the more space is created in between.
My OSs: fedora 41 (appimage version zen-browser) and windows 11 (installed version zen-browser, not portable)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Alpha build - 1.0.1-a.19

### What platform are you seeing the problem on?

Linux, Windows

**Comment by universish** [comment]
![Ekran görüntüsü 2024-11-11 180925](https://github.com/user-attachments/assets/badccefe-3bdb-4a29-90f3-6ca726afb391)

![Ekran görüntüsü 2024-11-11 181018](https://github.com/user-attachments/assets/fe425c33-866d-4375-82b4-41f498eea52d)

![Ekran görüntüsü 2024-11-11 181042](https://github.com/user-attachments/assets/2090eebe-c703-4160-bb29-ccb1429c6c0f)

![Ekran görüntüsü 2024-11-11 181203](https://github.com/user-attachments/assets/9e3a1878-f25b-4f4e-b065-8fc45c78e1cf)

![Ekran görüntüsü 2024-11-11 181213](https://github.com/user-attachments/assets/d5e0e08b-f0c3-4e86-a8a1-d0f00852079b)

![Ekran görüntüsü 2024-11-11 181245](https://github.com/user-attachments/assets/b63a4d11-cec3-4de0-94c7-44253d911d52)

![Ekran görüntüsü 2024-11-11 181257](https://github.com/user-attachments/assets/3524e08c-5e6d-41fb-b111-b951b0b1fac2)

![Ekran görüntüsü 2024-11-11 182410](https://github.com/user-attachments/assets/ef7ce8d0-26d1-4b2c-acbb-0d2b751a6fd8)

**Comment by universish** [comment]
This issue was fixed with beta build version 1.0.2-b.0 (64 bit).

**Comment by universish** [comment]
Pardon. The problem persists when compact mode is disabled.
There is no problem when compact mode is on.

**Comment by mr-cheffy** [comment]
This is expected, thanks!
