### ISSUE TITLE
Pinned Tabs with only grid layout icons go away :c in the latest version

### ISSUE THREAD

**Issue by kattsushi** [zen-browser/desktop#2910]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Pinned Tabs with only icons go away :c in the last version the icons render as list instead a icon grid layout that was handy
now for more than 6 pinned tabs in the list generate a scroll bar 
![Screenshot 2024-11-11 at 9 40 32 a m](https://github.com/user-attachments/assets/e6ce5c2c-c4af-4c0c-a0ae-2816a8079bdd)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.19 (Firefox 132.0.1) (aarch64)

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by universish** [comment]
https://github.com/zen-browser/desktop/issues/2871

**Comment by MrPiggy105** [comment]
iT's noT A BuG it'S A FeAturE
Well... yes, it is a feature. Pinned tabs are now per-workspace and render as a list, in a separate section above regular temporary tabs. There are now 'essentials' pinned tabs but global across workspaces. This looks like the old pinned tabs. If you want to display the new pinned tabs in a grid, like essentials, the superpins mod can add that if you install it and change its settings.

**Comment by asm0dey** [comment]
The issue with essentials is that they are cross-workspace. I have 8 pinned tabs in my workspace, and they now have a scrollbar! Please return the old behavior or add a setting—I need them pinned in a workspace and do not have a scrollbar.

**Comment by asm0dey** [comment]
Still relevant

**Comment by mr-cheffy** [comment]
This is the new look of pinned tabs. If you want it to look like the old ones, you can install https://zen-browser.app/mods/ad97bb70-0066-4e42-9b5f-173a5e42c6fc/ and check the option to make them look like essentials. Thanks
