### ISSUE TITLE
[FEATURE REQUEST]  I want to be able to assign containers when creating new workspaces. Is this possible?

### ISSUE THREAD

**Issue by universish** [zen-browser/desktop#2912]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

edit: I didn't know that this feature is also available in zen-browser, and it's even more advanced and stable.

I want to be able to assign containers when creating new workspaces. 
Hover over the workspaces and right click. Then click on the “+” symbol next to “Other Workspaces | Beta” which is the “Create new workspace” button. Enter the workspace name. Select the workspace icon. Assign containers to the workspace with the feature I want to add. Then left click on “Create workspace (S)”. Everything is ready.
In the menu that opens after clicking on the “+” icon, the button “Select container to assign to workspace” should be added.

Note: For this feature to work, you need to install the Firefox Multi-Account Containers plugin. Then you create a container for your workspaces. For example, you should create a git container for git websites (e.g. github gitlab etc.). When you create a new workspaces you assign a container for workspaces and create workspaces. You also change the name of workspaces to git. Then you open github in this workspaces. It automatically runs in the container named git. 

I want to create a new workspaces with a menu similar to this:

![Ekran görüntüsü 2024-11-11 191859](https://github.com/user-attachments/assets/5e915986-c39f-4f28-a4c9-c67e3b50c0b8)

At the moment there is only the option “Enter workspace name” and the option to set the icon of the workspace. There is no “Assign container for workspace” option. It would be perfect if there was this option.
(This feature is not even in floorp. In fact, floorp doesn't even have the option to specify the name and icon when creating a workspace. In floorp you first create the workspace, then change the name, change the icon and choose the container).

![Ekran görüntüsü 2024-11-11 200710](https://github.com/user-attachments/assets/0d8735c2-ab68-4a94-a101-fc2591c54cfa)

![Ekran görüntüsü 2024-11-11 200729](https://github.com/user-attachments/assets/cec54292-4283-4d87-9bcf-0ce25adf79de)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Alpha build - 1.0.1-a.19

### What platform are you seeing the problem on?

Linux, macOS - aarch64, macOS - Intel, Windows

**Comment by universish** [comment]
![Ekran görüntüsü 2024-11-11 192327](https://github.com/user-attachments/assets/ffc084eb-a443-49c0-8958-19f7e0b4fbdc)

**Comment by universish** [comment]
![Ekran görüntüsü 2024-11-11 192429](https://github.com/user-attachments/assets/e8aac9c9-8a8b-4d2d-b0fc-00fee2d0481f)

**Comment by Fxxxlei** [comment]
This has already been working for a long time.

Right-click on the workspace switcher, click on the three dots near a workspace, hover over "Set Default Container", choose a container.

Btw, to my knowledge, this should be at most a discussion topic, not an issue.

**Comment by universish** [comment]
Hmm. 
Thanks.

 Sorry. I didn't know. He's working. I tried it. I like it very much. I am very glad that this feature is in zen-browser.
Congratulations to the developers. I applaud.

But the feature I want is this: I want to be able to assign containers when creating new workspaces. (This feature is not available in floorp).

That's why I'm changing the title.

**Comment by universish** [comment]
> Btw, to my knowledge, this should be at most a discussion topic, not an issue.

It's not labeled as a “Bug”, it's labeled as a “Feature”.
Therefore, such a title can also be created in the issue.

**Comment by cheeeebs** [comment]
Please move to GitHub Discussions. Issues are for bugs only.

**Comment by universish** [comment]
Ok.

https://github.com/zen-browser/desktop/discussions/2915
