### ISSUE TITLE
Integrate Betterfox

### ISSUE THREAD

**Issue by win98se** [zen-browser/desktop#292]
### What feature would you like to see?

Many Firefox-based browsers have integrated [Betterfox](https://github.com/yokoffing/Betterfox). Would like to ask, do you have plans to do it at some point? ;)

### What platform are you seeing the problem on?

Windows

### Additional context

Despite selecting `Windows` for the “What platform are you seeing the problem on?” option, this feature maybe would effect Linux and macOS as well.

**Comment by gunir** [comment]
Zen is using a modified version of Betterfox that's heavily tweaked for performance, it's better than using plain Betterfox.

Zen itself has implemented some exclusive tweaks like bytecode caching that even regular Firefox doesn't have: https://github.com/zen-browser/desktop/pull/219

**Comment by win98se** [comment]
Just saw [the credits](https://github.com/zen-browser/desktop/commit/5f9f555083ac53de8e1743018e73f0e86f2ae6e8) and [the respective file(s)](https://github.com/zen-browser/desktop/blob/main/src/browser/app/profile/better-fox.js). My apologies!

**Comment by SmokeyPlayz** [comment]
Funny I actually did this on my Windows 11, and it felt like everything is running smooth, but now I am not sure, but now everything seems to be running kinda slow. And each Zen update it like I have to reapply the user.js
