### ISSUE TITLE
Button to list all tabs is transparent / disappears 

### ISSUE THREAD

**Issue by Samuelgreger** [zen-browser/desktop#2923]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The list all tabs button does not have an icon in the menu to customize the toolbar. But the title of the button / functionality is displayed in in the customize toolbar menu. 

When dragged and dropped into the toolbar in any position the title can not be seen in the menu to customize the toolbar. This is normal, however the position where you dropped the button to is also not displaying anything. So the whole button is "lost" somewhere. It shows up in the customize toolbar menu when I click "Restore Defaults". Otherwhise the button is no where to be found.

![image](https://github.com/user-attachments/assets/0b5101df-08bb-4eda-98b0-07a90aeb11af)

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.1

### What platform are you seeing the problem on?

Windows

**Comment by MrPiggy105** [comment]
Seeing this on macOS too. (we should add the red line to the issue title or make a separate one)

**Comment by Samuelgreger** [comment]
I updated the issue description. The issue is a whole different one now. So i also updated the title of the issue.
