### ISSUE TITLE
Button list all tabs has a red line above it

### ISSUE THREAD

**Issue by Samuelgreger** [zen-browser/desktop#2927]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The Button to list all tabs has a red line above it.

![red line over button](https://github.com/user-attachments/assets/2c44f77f-ba2a-44ba-a340-4f8d9bb7934a)

In the following issue i have mentioned this and also appended the picture.
#2923 

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.19

### What platform are you seeing the problem on?

Windows

**Comment by MrPiggy105** [comment]
Can confirm. It turns grey when you hover
<img width="228" alt="Screenshot 2024-11-12 at 12 35 49 pm" src="https://github.com/user-attachments/assets/608f4d39-fcb9-4424-a552-06d7daaac459">

**Comment by LopesLs** [comment]
Idk why, but this button to list all tabs make the ui of the sidebar so strange.

**Comment by neogeographica** [comment]
Same here, macOS and Linux.

**Comment by johansvedberg** [comment]
This is making it impossible for me to use the sidebar expanded- just looks so weird.

**Comment by LopesLs** [comment]
> This is making it impossible for me to use the sidebar expanded- just looks so weird.

Same for me.

**Comment by dimgerasimou** [comment]
I can confirm. The same thing is reproducible on Arch Linux. It only happens with the expanded sidebar.

**Comment by vinugawade** [comment]
Same here on macOS Sonoma 14.6.1

**Comment by Samuelgreger** [comment]
The button now (1.0.2-b.1) does not display and gets "lost" like described here. #2923

**Comment by Samuelgreger** [comment]
The button now (1.0.2-b.1) does not display and gets "lost" like described here. #3664 Therefore this issue is obsolete.
