### ISSUE TITLE
Option for Zen Sidebar to be permanently visible, but collapsed.

### ISSUE THREAD

**Issue by guigirl42** [zen-browser/desktop#293]
### What feature would you like to see?

Before discovering the lovely Zen Browser only comparatively recently i've been using Floorp. It's been tricky for me to decide which one to make my default, as they're both great, despite also having differences. On balance, so far, i prefer Floorp's design for the **dedicated Web Panels Sidebar**, being similar to the venerable Vivaldi & Opera Presto designs, in that it's **always visible**, albeit collapsed. I use Web Panels a lot, & in Floorp i can get to them faster than in Zen, which needs some extra clicks. 

My request is for it to be an extra _option_, not a mandatory replacement for the current Zen method, as i appreciate that some users will prefer that. 

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
Always visible as in `pinned` or floating but always visible?

**Comment by scientiac** [comment]
Floating and Pinned as options would be great and it would be nice to have an option to increase/decrease the sidebar width because it looks too small on 4k monitors

**Comment by guigirl42** [comment]
> Always visible as in `pinned` or floating but always visible?

I hope some pics might help. 

This markup shows how i'd like to rearrange my Zen UI:

![image](https://github.com/user-attachments/assets/c283cff8-e144-4d39-b457-2e4e6babdbea)

This pic shows my actual Floorp UI, with my W/P visible but collapsed on the RHS [Floorp allows it to be either side]:

![image](https://github.com/user-attachments/assets/48b95a39-faf4-4daf-b367-c189d0a7f287)

This final pic shows the Guardian Australia Web-Panel opened after i've clicked it, in the Side-Panel:

![image](https://github.com/user-attachments/assets/4309c74f-7396-4e20-8e39-03d63d482fd6)

Does that make more / any sense?

**Comment by mauro-balades** [comment]
yep, ill look into it

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/865

 ~ This is an automatic operation to better enhancements requests organization.
