### ISSUE TITLE
Cannot remove container tab indicators

### ISSUE THREAD

**Issue by justingallant1988** [zen-browser/desktop#2930]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I have never had container tab indicators enabled. And they have never been showing. Today, out of nowhere they are visible, with no way to turn them off. I have disabled all mods, restarted and they persist.

https://github.com/user-attachments/assets/71c97508-647d-452c-8fba-981f97718098

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.19 

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by JSGRD22** [comment]
Try unpinning all the tabs, then opening new tabs with the same URLs. If the newly opened tabs do not have indicators, pin them instead, and they should not show indicators on subsequent use.

**Comment by justingallant1988** [comment]
You are right, this actually does resolve the issue. I suppose the question now surrounds the root cause of it happening in the first place and will it happen again...

**Comment by JSGRD22** [comment]
It often happens when there is a big update that changes how pinned tabs work, so hopefully it won’t happen again on its own.
