### ISSUE TITLE
Workspaces Indicator Issue

### ISSUE THREAD

**Issue by JoshCodeStuff** [zen-browser/desktop#2933]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Just updated to the latest version, and the "Default Workspace" indicator is now stuck at the top of the tab list with no way to remove it. I do not use workspaces and like to keep this icon hidden at all times for minimalism. It had been working fine to go into toolbar edit mode and drag it into the unused section, however that is no longer working.

![image](https://github.com/user-attachments/assets/ad9f4e5e-6c80-43f8-8655-8828b70b07aa)
![image](https://github.com/user-attachments/assets/5aaf24a0-b80e-4709-bd6b-9dc91a044063)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.19

### What platform are you seeing the problem on?

Linux

**Comment by JoshCodeStuff** [comment]
> I found a related issue that might be helpful:
> 
>     * [Cannot remove container tab indicators #2930](https://github.com/zen-browser/desktop/issues/2930)
>       This issue is about not being able to remove container tab indicators, similar to your problem with the "Default Workspace" indicator. There are no comments or solutions provided yet.
> 
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

To any real humans reading this: this issue is not related or helpful.

**Comment by cheeeebs** [comment]
You can use CSS to remove that for now. You can use this code. 
```
#zen-current-workspace-indicator {
    display: none !important;
}
```
Here's the guide for using custom CSS: https://docs.zen-browser.app/guides/live-editing.

You can also change `zen.workspaces.show-workspace-indicator` to **false** in `about:config` but this only works on expanded view right now.
