### ISSUE TITLE
Workspace emoji in list too small, cant read

### ISSUE THREAD

**Issue by KoNekoD** [zen-browser/desktop#2938]
### Captchas

- [ ] I have read the instructions.
- [ ] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

Workspace emoji in list too small, cant read

![image](https://github.com/user-attachments/assets/ddf0eb35-01e5-465d-9518-13725ffac9db)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
I suggest little increase the size of each emoji in list. What do you think?
```

**Comment by BoscoDomingo** [comment]
A search bar would also be quite welcome while we're at it

**Comment by KoNekoD** [comment]
> A search bar would also be quite welcome while we're at it

I think there's nothing wrong with the search bar

**Comment by BoscoDomingo** [comment]
> > A search bar would also be quite welcome while we're at it
> 
> I think there's nothing wrong with the search bar

What search bar? Right now there is none

**Comment by rRobis** [comment]
Maybe instead of emoji list, just let user input custom string of 1 character. That way user could input any letter or emoji from emoji picker

**Comment by bhdai** [comment]
> A search bar would also be quite welcome while we're at it

yeah i agree, manually searching those emoji is a pain

**Comment by lizclipse** [comment]
Something that's also frustrated me with this is that the ordering feels very odd, and I'm not quite sure what it's supposed to be. If it was ordered similarly to the built-in emoji picker (I'm on macOS so am not sure if other platforms order differently) then I could at least use prior knowledge on how it's sorted to jump to the place in the list where the emoji I'm after is.

**Comment by rihards-simanovics** [comment]
It would be nice to have a search bar like in most OS emoji selection and in Arc browser.

Windows:
![image](https://github.com/user-attachments/assets/d6eacf51-abb2-482c-b615-035425c0a161)

Arc Icons selection:
![image](https://github.com/user-attachments/assets/bc578b16-5ce1-4508-9a9c-a80780ab3d3b)

**Comment by neurokitti** [comment]
Im going to close this because I just finnished up a PR for this and it should be added in the coming days: https://github.com/zen-browser/desktop/pull/3963/files

if there are further issues i will reopen this issue.

**Comment by neurokitti** [comment]
for reference this is what it looks like. it has search and bigger icons.

https://github.com/user-attachments/assets/30576161-d33a-419e-adc6-0b5294c0f2dc

**Comment by rihards-simanovics** [comment]
> for reference this is what it looks like. it has search and bigger icons.
> Screen.Recording.2024-12-27.181236.mp4

Lovely, thanks, @neurokitti! had a look at the diff and got to love the emojis being stored in a single giant object 🤣 .
