### ISSUE TITLE
Zen gradient color is messing with some website's background color

### ISSUE THREAD

**Issue by Setsubou** [zen-browser/desktop#2948]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Not sure if this a bug or am I just missing a settings somewhere, but, my current theme gradient color would replace the background-color on some websites, making it unreadable.

For example,
![image](https://github.com/user-attachments/assets/57e6ed6d-dbd2-43c1-b2da-33f9a1203e9b)
This example website is from https://raytracing.github.io/books/RayTracingInOneWeekend.html

and this is my current gradient settings
![image](https://github.com/user-attachments/assets/dfbac0ee-c51c-474d-8e4e-7628144b41d6)

Tried on Firefox and that website renders just fine.

Thank you!

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.19

### What platform are you seeing the problem on?

Windows

**Comment by Fxxxlei** [comment]
In about:config `browser.tabs.allow_transparent_browser` allows pages to be transparent. You should uncheck that.
If you search on Reddit or even here, you should find a multitude of posts with the fix.

I don't know why it seems to be the default for some people, it wasn't for me.

**Comment by Setsubou** [comment]
Thanks, that fixes it :)
