### ISSUE TITLE
Adaptive Firefox Color Synced with Website Colors

### ISSUE THREAD

**Issue by scientiac** [zen-browser/desktop#295]
### What feature would you like to see?

Currently I am using an extension called "Adaptive Tab Bar Color" but when I installed it, it didn't work. It would be great to have better integration with that or a full featured in browser implementation of it.

### What platform are you seeing the problem on?

Linux

### Additional context

Adaptive Tab Bar Color: 
https://addons.mozilla.org/en-US/firefox/addon/adaptive-tab-bar-colour/

I have been using this configuration for my firefox browser to get a simple look with sidebery. It'd be great to have a sidebery integration as well.
https://gitlab.com/scientiac/tesseract.home.manager/-/tree/main/apps/graphical/firefox

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/864

 ~ This is an automatic operation to better enhancements requests organization.
