### ISSUE TITLE
Tab switches to the last tab when workspaces are changed

### ISSUE THREAD

**Issue by wysh3** [zen-browser/desktop#2950]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When switching between workspaces, the browser automatically switches to the last active tab. This behavior is unexpected when I'm on a pinned tab, as I would expect the focus to remain on the pinned tab, not the last tab.

https://github.com/user-attachments/assets/c8e3de36-af08-4a02-ae48-895a36116e0d

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.19

### What platform are you seeing the problem on?

Linux

**Comment by DaitiDay** [comment]
+1

**Comment by fpigeonjr** [comment]
confirmed on macOS 14.7.1 (23H222)
zen : 1.0.1-a.19 (Firefox 132.0.1) (64-bit)

**Comment by fpigeonjr** [comment]
unpinning Tabs solves the issue but defeats the purpose of pinning Tabs 😢
