### ISSUE TITLE
Inconsistent Tab Behavior When Dragging in Sidebar

### ISSUE THREAD

**Issue by imLymei** [zen-browser/desktop#2952]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### Description
When attempting to drag any essential tab, the selected tab locks on the X-axis, only moving vertically along the Y-axis. During this action, all essential tabs to the right become hidden. Upon release, the tab’s final position behaves unpredictably depending on the sidebar mode:

- **In Default Sidebar Mode**:
  - The tab may either move a single position in the dragged direction or jump all the way across in that direction.

- **In Compact Sidebar Mode**:
  - The tab either does not move at all or jumps to the far left or right, based on a seemingly random outcome.

### Expected Behavior
- Dragging to the left or right should reorder all essential tabs.
- Essential tabs to the right shouldn't become hidden.
- Dragging up and down should not be allowed for my essential tabs, as they are arranged in a single row.

### Screenshots
- **Dragging to the right**:
  ![image](https://github.com/user-attachments/assets/811bb4fc-369b-4572-a121-85c88847b119)

- **Dragging to the left**:
  ![image](https://github.com/user-attachments/assets/d962de82-65cd-44eb-afb7-575a8c890923)

- **Dragging up**: 
![image](https://github.com/user-attachments/assets/580b2c5f-c78d-45d8-993f-3733822dbdd5)

- **Dragging down**:
![image](https://github.com/user-attachments/assets/7968d967-bd0d-4c3d-b102-29ef878d597d)

Note that the dragging up and down behavior probably shouldnt be allowed since my essentials tabs are only a row wide

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

V1.0.1-a.19 (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by thibaultmol** [comment]
@dosu this isn't fixed in the latest version. still happening
