### ISSUE TITLE
Tab Duplication Across Workspaces 

### ISSUE THREAD

**Issue by wysh3** [zen-browser/desktop#2953]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

While working normally, I noticed that a tab is being duplicated across two workspaces. I’m unsure how to reproduce the issue, as it appears randomly. This is not the first time it has occurred.

https://github.com/user-attachments/assets/1d5c1858-1b90-4872-b0b7-019085713544

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.19

### What platform are you seeing the problem on?

Linux

**Comment by artur-rios** [comment]
This happened with me too
