### ISSUE TITLE
Black line at top of browser

### ISSUE THREAD

**Issue by asidius** [zen-browser/desktop#2956]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When scrolling on most websites or navigating UI elements a black line will flicker at the top of the browser window.

Sites I have experience the issue so far:
- reddit.com
- youtube.com
- x.com
- questlog.gg

The issue is still present even with Zen defaults, a new profile, all mods removed and no additional cusotm css.

Issue:

https://github.com/user-attachments/assets/e93f06a2-2ac9-4faf-af23-bcd68d628020

![Screenshot 2024-11-12 164228](https://github.com/user-attachments/assets/c7295ed9-4cec-4a4f-adda-73b6b3c160d5)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.19

### What platform are you seeing the problem on?

Windows

**Comment by Richard-Woessner** [comment]
I am unable to recreate this on mac 1.0.1-t.19. I will try to get someone to test it on windows

**Comment by shadowash8** [comment]
@Asidius do you have any zen mods or userChrome applied?

**Comment by asidius** [comment]
@ashwinjadhav818 No, I currently don't. I removed all mods and the userChrome and the issue is still there.

**Comment by asidius** [comment]
@ashwinjadhav818 I believe it is linked to screen fresh rate. I change my screen from 120Hz to 144Hz and it went away.

**Comment by asidius** [comment]
Sigh. Enabling Hardware Acceleration returned the issue.

**Comment by shadowash8** [comment]
Well that is weird, I'll move the issue to todo.
