### ISSUE TITLE
[BUG] [WORKAROUND AVAILABLE] Zen crashes on Linux when using Wayland

### ISSUE THREAD

**Issue by eagerestwolf** [zen-browser/desktop#296]
### What happened?

This is a known issue. It doesn't seem to affect me when using Firefox (either via Flatpak or Pacman); however, others report the issue is present in Firefox as well. The main reason for opening this issue is to track the upstream fix (apparently coming in FF 130), and to document the fix for Flatpak users, as the fix documented in a previous issues doesn't seem to work with Flatpak. I'm marking this issue as Low severity since it only really affects Linux and Wayland (and the problem is upstream anyway), feel free to override me if that seems off.

For reference, if you are a Linux user and you find that Zen is crashing randomly or repeatedly, you can try these steps to remedy the issue.

## If you installed Zen via a package manager (i.e. yay, paru, nix, etc.)

You can edit the menu file using an editor (such as [libre-menu-editor](https://codeberg.org/libre-menu-editor/libre-menu-editor)) and add `MOZ_ENABLE_WAYLAND=0` to the beginning of the command.

## If you installed Zen via Flatpak (i.e. GNOME Software, KDE Discover, `flatpak` command, etc.)

You can also try the environment variable above by running the following command, however your mileage may vary.

```sh
flatpak override --user --env MOZ_ENABLE_WAYLAND=0 io.github.zen_browser.zen
```

Alternatively, you can also go itnto [Flatseal](https://github.com/tchx84/Flatseal) and set an environment variable there. Just hit the plus icon next to `Variables` and enter `MOZ_ENABLE_WAYLAND=0`

If that doesn't work, you'll need to disable Wayland support entirely. Again, you can simply run the following command

```sh
flatpak override --user \
  --nosocket=wayland \
  --nosocket=fallback-x11 \
    io.github.zen_browser.zen
```

Or, using Flatseal, you can disable Wayland windowing system and Fallback to X11 windowing system under Socket.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.21

### Severity impact

Low

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
Working on this still...bear with me.
```

**Comment by mauro-balades** [comment]
THanks!

**Comment by bram-pkg** [comment]
I see this is closed as completed. Will it be fixed?

**Comment by mauro-balades** [comment]
With firefox 130

**Comment by bram-pkg** [comment]
Alright, thank you for the quick response :)

**Comment by mauro-balades** [comment]
Update: im updating to firefox 130 that should fix the issue

**Comment by Skidamek** [comment]
> Update: im updating to firefox 130 that should fix the issue

Just tested from latest github action (specific appimage) and i can confirm that this in fact fixes crashes! 
However seems like they introduced the same issue that steam has on wayland with this synchronization stuff
![image](https://github.com/user-attachments/assets/fcc1337f-d37b-49b3-8a33-8a0cd07f723f)
that how window can sometimes look like when opened with hardware acceleration turned on.

Resizing fixes it...

**Comment by ProggerX** [comment]
> > Update: im updating to firefox 130 that should fix the issue
> 
> Just tested from latest github action (specific appimage) and i can confirm that this in fact fixes crashes! However seems like they introduced the same issue that steam has on wayland with this synchronization stuff ![image](https://private-user-images.githubusercontent.com/67871298/364115903-fcc1337f-d37b-49b3-8a33-8a0cd07f723f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MDIzNDksIm5iZiI6MTcyNTYwMjA0OSwicGF0aCI6Ii82Nzg3MTI5OC8zNjQxMTU5MDMtZmNjMTMzN2YtZDM3Yi00OWIzLThhMzMtOGEwY2QwN2Y3MjNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDA1NTQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViMmFkMDJkMGYyMjJjNTVlN2ZmNDc0MWZhZjNlY2E0NDNiZjlhN2Y4MmFkZGQzNzM1N2I3NzI0OGNmNTdmNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UOeUVpLWnik6LXFaedMWxINaUlI7dF6tQTTVyy66sEw) That's how window can sometimes look like when opened with hardware acceleration turned on.
> 
> Resizing fixes it...

I have this problem in steam💀

**Comment by AryanshMahato** [comment]
Works really well after Zen has upgraded to Firefox 130. Not facing crashes anymore on NVIDIA and Wayland.

**Comment by mauro-balades** [comment]
Nice!

**Comment by ajs1998** [comment]
This issue seems to be back with version `1.10b`. Using Flatseal to disable Wayland for Zen worked. I also updated to the latest Nvidia driver, so I'm not sure which update broke this.

Here's my system info:

```
Operating System: Fedora Linux 41
KDE Plasma Version: 6.3.3
KDE Frameworks Version: 6.12.0
Qt Version: 6.8.2
Kernel Version: 6.13.7-200.fc41.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 20 × 13th Gen Intel® Core™ i5-13600K
Memory: 31.1 GiB of RAM
Graphics Processor 1: NVIDIA GeForce RTX 4060/PCIe/SSE2
Graphics Processor 2: NVIDIA GeForce RTX 4060/PCIe/SSE2
Manufacturer: Micro-Star International Co., Ltd.
Product Name: MS-7D25
System Version: 2.0
```


```
$ modinfo -F version nvidia
570.133.07
```

**Comment by tom-gora** [comment]
using sef-updating prebuilt binay (no flatpak) and experiencing the same issue. massive lag upon initial opening of the browser takes 2-3 minutes to calm down.

Noted: Crashes seem to get logged AFTER Ctrl-C sig is sent(?)
Log:

```bash
 zen-browser 
^CExiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Crash Annotation GraphicsCriticalError: |[C0][GFX1-]: CompositorBridgeChild receives IPC close with reason=AbnormalShutdown (t=5Exiting due to channel error.
Crash Annotation GraphicsCriticalError: |[C0][GFX1-]: CompositorBridgeChild receives IPC close with reason=AbnormalShutdown (t=55.3354) Exiting due to channel error.
Exiting due to channel error.
Crash Annotation GraphicsCriticalError: |[C0][GFX1-]: CompositorBridgeChild receives IPC close with reason=AbnormalShutdown (t=55.4648) Exiting due to channel error.
```

with x-wayland backend no issues whatsoever with slowdowns. GraphicsCriticalError still gets logged but no abnormal shutdowns happen (but ugly secondary border and extra padding gets rendered on the browser window). 

Noted: Crashes seem to get logged BEFORE Ctrl-C sig is sent(?)
Log:

```bash
MOZ_ENABLE_WAYLAND=0 zen-browser
ATTENTION: default value of option mesa_glthread overridden by environment.
libva info: VA-API version 1.22.0
libva info: Trying to open /usr/lib64/dri-nonfree/radeonsi_drv_video.so
libva info: Trying to open /usr/lib64/dri-freeworld/radeonsi_drv_video.so
libva info: Trying to open /usr/lib64/dri/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_1_22
libva info: va_openDriver() returns 0
ATTENTION: default value of option mesa_glthread overridden by environment.
ATTENTION: default value of option mesa_glthread overridden by environment.
Crash Annotation GraphicsCriticalError: |[G0][GFX1-]: RenderCompositorSWGL failed mapping default framebuffer, no dt (t=50.8429) [GFX1-]: RenderCompositorSWGL failed mapping default framebuffer, no dt
^CExiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.

```

System: Fedora 42
Zen: 1.11.5b (Firefox 137.0.2) (64-bit) (From tar release)
Desktop: WL-Roots (Hyprland)
EDIT: Forgot. Hardware all AMD, discreet GPU AMD Radeon RX 7700 XT (radeonsi, navi32, LLVM 20.1.2, DRM 3.61, 6.14.3-300.fc42.x86_64)


Did optimizations like disabling disk cache and using profile optimizer on browser databases. Helped a bit but initial kicking in still lags like crazy. Happens as well with troubleshooting mode with no extensions etc as well. Migrated to new profile and disabled all extensions manually to test. Same thing also happens. Really same thing with base FF :/
