### ISSUE TITLE
When sending a tab to a diferent workspace it losses right clickability

### ISSUE THREAD

**Issue by neurokitti** [zen-browser/desktop#2963]
### Captchas

- [ ] I have read the instructions.
- [ ] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

https://github.com/user-attachments/assets/c7e9d192-ba57-4330-9004-9014cf2e5fe1

when you use the drop down menu to send a tab to a different workspace the tab and all other tabs can no longer be right clicked but the menu right click still works. right clicking elsewhere in the UI causes it to work again but its inconsistent.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-t.19

### What platform are you seeing the problem on?

Windows

**Comment by tylerS0887** [comment]
Same Issue here

**Comment by 12th-devs** [comment]
Same issue on twilight


EDIT: On a very big side note, could you share some of your theme colors 😍

**Comment by artcens** [comment]
i thought this is a new bug, damn a month old issue ...
