### ISSUE TITLE
"Add to Essential" is not translated into turkish.

### ISSUE THREAD

**Issue by universish** [zen-browser/desktop#2967]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

"Add to Essential" is not translated into Turkish.
“Add to Essential” = "Gerekli Olanlara Ekle"

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.19

### What platform are you seeing the problem on?

Linux, macOS - aarch64, macOS - Intel, Windows

**Comment by kristijanribaric** [comment]
You can submit new translations using [this guide](https://docs.zen-browser.app/contribute/translation).

**Comment by universish** [comment]
https://github.com/zen-browser/desktop/issues/2868
@kristijanribaric can you fix this too please? I tried. But I couldn't correct the translation because I didn't have authorization.
