### ISSUE TITLE
Improve Workspace Picker

### ISSUE THREAD

**Issue by bdbch** [zen-browser/desktop#297]
### What happened?

Currently the Workspace Picker feels weird to me. I don't know why there is a separation of "Current Window" and "Other Workspaces". Couldn't we just have all of them in a flat list and highlight them with an active state instead?

It's annoying because everytime you switch workspaces, the workspace list reorders with the current workspace at the top.

![image](https://github.com/user-attachments/assets/fb85241c-ee0d-4d9f-8c53-18362b722e9a)

![image](https://github.com/user-attachments/assets/770b983a-cfd6-4626-96ae-ede22820f930)

![image](https://github.com/user-attachments/assets/9aef3410-21a3-4546-b57c-567d13218cba)

For me at least it's easier to find the correct workspace if one of the items doesn't move around in a list / get shifted to the first position.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.21

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by lazymonkey2** [comment]
yes, I agree with you. reordering workspaces makes it harder to use them.

**Comment by mauro-balades** [comment]
New update will contain an icon-strip workspace switcher, thanks!
