### ISSUE TITLE
Some hotkeys conflict so not working properly after open zen-browser for some time

### ISSUE THREAD

**Issue by marsjane** [zen-browser/desktop#2972]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Basically hotkeys work as expected when I just open the app, but after a while(not sure how long), then some hotkeys just work differently. They will open some page of the developer tool.
For example: alt+cmd+c
![Shot 2024-11-13 at 11 23 22@2x](https://github.com/user-attachments/assets/646ab7d9-ec0f-48f7-ac65-c96e94df9148)
it should toggle the compact mode, but it just shows me this:
![Shot 2024-11-13 at 11 21 54@2x](https://github.com/user-attachments/assets/eab2e111-670b-4b08-9d43-bb69d357f411)
Also, the Alt+cmd+e should forward workspace
![Shot 2024-11-13 at 11 24 58@2x](https://github.com/user-attachments/assets/27a829e2-e224-471f-b88a-61650c4714a2)

but it also open the developer tool and show me the Network page
![Shot 2024-11-13 at 11 23 58@2x](https://github.com/user-attachments/assets/166000f8-a97a-4004-8f99-20891a487d09)
I guess it should be related to hotkey conflict, because alt+cmd+q always works as expected

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.19 (Firefox 132.0.1) (aarch64)

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by marsjane** [comment]
oh yes I found someone else also mentioned this in another issue
https://github.com/zen-browser/desktop/issues/1629#issuecomment-2416366387

**Comment by salamijason** [comment]
Have reopened the original issue. Mb, haven't checked github for a bit.

**Comment by salamijason** [comment]
original: https://github.com/zen-browser/desktop/issues/991
