### ISSUE TITLE
Essentials not keeping favicon after restarting

### ISSUE THREAD

**Issue by gambithunt** [zen-browser/desktop#2976]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

After restarting the essential button loose their favicons, defaulting to a generic round shape.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by shadowash8** [comment]
This issue is the same as #2704, hence closing the issue
