### ISSUE TITLE
Few improvement from a new user

### ISSUE THREAD

**Issue by delta-whiplash** [zen-browser/desktop#298]
### What feature would you like to see?

Hello,
I recently switched from Brave/Sidekick and Arc Browser to Zen Browser, mainly for the split view feature.

The user experience is really good and polished, and the animations are very nice.

However, there are a few things that I think could be improved:

- The search bar position: it would be much better to have it floating at the top center or left/right, rather than at the bottom.
- "Show all downloads" should be a tab, not a window: this would help to better manage workflow focus.
- I know it's not possible for every project, but the main reason I switched from Brave in the past is the integrated uBlock Origin extension called Brave Shield: it would be great to have a similar "Zen Shield".
- It would also be nice to have an option to open a new tab with a centered floating search box, like on Arc Browser.
- A better way to "install" PWA apps like on chromium browsers (had to search a lot to find a way to install youtube)
- have the ram consumption of a tab when I move the mouse over it like on brave or chrome

Additionally, I wanted to mention that I found it quite challenging to find the shortcut for split tabs. It would be helpful if you could highlight this information on the website to make it more discoverable.

Thanks for your amazing work and I hope you'll continue on this way! 😊

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/863

 ~ This is an automatic operation to better enhancements requests organization.
