### ISSUE TITLE
macOS: Installing in user Applications directory results in Zen losing settings between restarts

### ISSUE THREAD

**Issue by milyrouge** [zen-browser/desktop#2982]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I have Zen installed in the user Applications directory. When quitting and restarting the browser, all settings are lost (workspaces, profiles, pinned tabs, essentials) and the Zen installation process pops up. Settings are saved in Application Support/zen, but a new profile seems to be created upon restart.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a19

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by intrepid-developer** [comment]
I'm also having this exact same issue. Once Zen is closed it loses everything, settings, extensions, profiles, etc.

I'm using the latest version of Zen, on the latest macOS. I'm on a M1 MacBook Pro.

<img width="662" alt="Image" src="https://github.com/user-attachments/assets/0ea7dd0d-a68a-4c1c-914e-3c4a5ed2bed3" />
