### ISSUE TITLE
Major: Popup windows don't close and instead open pinned/essential tab

### ISSUE THREAD

**Issue by CptnFizzbin** [zen-browser/desktop#2985]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Looks like popup windows don't close properly in Zen when there are pinned or essential tabs. I've created a minimal example that can trigger the issue here:
https://codepen.io/CptnFizzbin/pen/XWvOovb?editors=1011

Instead of closing when requested, the popup will instead redirect to one of the pinned/essential tabs. This is a major problem as a lot of authentication systems use a popup, and in the worse case, can cause a repeating loop of login attempts. While this issue exists, users are unable to use pinned or essential tabs if they frequent a website that uses popups during auth.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.19 (Firefox 132.0.1) (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by neurokitti** [comment]
yeah i have the same issue. it just swaps to one of the tabs i already have open

**Comment by CptnFizzbin** [comment]
#3008 identified that this a cross OS issue, and that the popup redirects to the first pinned tab.

**Comment by SalahAdDin** [comment]
Cause of this I lost all my pinned tabs!

**Comment by CptnFizzbin** [comment]
I've had to stop using pinned tabs as well while this issue unfixed

**Comment by CptnFizzbin** [comment]
can confirm this is still an issue in 1.0.1-a.22

**Comment by EtaoinWu** [comment]
This seems to have been fixed in twilight 1.0.1-t.22 (2024-12-04).

**Comment by EtaoinWu** [comment]
@neurokitti i see you closing this, have you confirmed that it works correctly in twilight now?

**Comment by SalahAdDin** [comment]
> @neurokitti i see you closing this, have you confirmed that it works correctly in twilight now?

It is working for me now.

**Comment by neurokitti** [comment]
> @neurokitti i see you closing this, have you confirmed that it works correctly in twilight now?

Yup
