### ISSUE TITLE
Zen hangs on startup

### ISSUE THREAD

**Issue by ArikRahman** [zen-browser/desktop#2986]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Zen does not proceed to browser on normal or safe mode. Every other firefox-based browser I use (Floorp, cachy-browser, firefox) works fine. Using CachyOS, zen-browser-avx2-bin install. Zen-browser was working just fine until today.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1.a.19-1

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
zen-browser --safe-mode                                                                                                                                                                 ─╯
Crash Annotation GraphicsCriticalError: |[0][GFX1-]: ManageChildProcess(vaapitest): process hangs
 (t=3.63189) [GFX1-]: ManageChildProcess(vaapitest): process hangs

Crash Annotation GraphicsCriticalError: |[0][GFX1-]: ManageChildProcess(vaapitest): process hangs
 (t=3.63189) |[1][GFX1-]: vaapitest: ManageChildProcess failed
 (t=3.63189) [GFX1-]: vaapitest: ManageChildProcess failed

Crash Annotation GraphicsCriticalError: |[0][GFX1-]: ManageChildProcess(vaapitest): process hangs
 (t=3.63189) |[1][GFX1-]: vaapitest: ManageChildProcess failed
 (t=3.63189) |[2][GFX1-]: RenderCompositorSWGL failed mapping default framebuffer, no dt (t=10.1259) [GFX1-]: RenderCompositorSWGL failed mapping default framebuffer, no dt
```

**Comment by ArikRahman** [comment]
I tried deleting the .cache profiles but that didn't fix anything. Still freezes on init.

**Comment by ArikRahman** [comment]
When I start zen-browser again, it repopulates the buggy profile on the cache:

╰─ ls                                                                                      ─╯
b2nas0o1.Arik

**Comment by ArikRahman** [comment]
It always seems so generate the .startup-incompelte file on the broken profile, even though I copied the default profile stuff into it which was working. How do i delete all config files and where are they? I deleted cache, did paru -Rns zen-browser-avx2-bin, but it always seems to remember that one darn profile. I'm getting pretty frustrated at this point.

**Comment by ArikRahman** [comment]
Ok I figured out the profiles are in .zen, I edited the profiles.ini to make it use "Default (alpha)" but that didn't work because of the spacing, but it's alright because the profile picker auto-adjusted. I deleted the Arik profile and that seemed to fix it.

**Comment by ArikRahman** [comment]
I will say to future troubleshooters, the profile functionality is broken and profiles.ini defaulting to a broken profile is not the best thing in the world.

**Comment by imulcei** [comment]
i've got the same problem as you, I can't do anything... I've reinstalled it, but it doesn't work. i'm mac OS Sequoia 15.1.
<img width="1440" alt="Capture d’écran 2024-11-19 à 01 45 55" src="https://github.com/user-attachments/assets/6dbd0e1c-2084-4963-8f77-cfd7f86a825a">

**Comment by dotjretion** [comment]
Using Windows right now, can confirm this issue exists here too. I have no idea how profiles are stored on Windows however and I can't seem to find a profiles.ini file, and so I'm quite lost. Hopefully this gets resolved soon.

EDIT[0]: I did some more digging and found where the profiles are stored on Windows. For anyone having a similar problem involving users on Windows in future, they're stored in `C:\Users\[username]\AppData\Local\zen\Profiles` in which you should see several users.

EDIT[1]: Disregard last edit. Whenever I try and reboot it just regenerates the folders should I delete them. `profiles.ini` is located at `C:\Users\[username]\AppData\Roaming\zen` and setting the profile back to Default (Alpha) fixes the issue.

![image](https://github.com/user-attachments/assets/dfed2eb6-97df-44dc-8338-4f5fbaeaea12)
