### ISSUE TITLE
Address bar should be focused when opening a new window

### ISSUE THREAD

**Issue by infiniwave** [zen-browser/desktop#299]
### What happened?

When opening a new window, the address bar is not focused. It should be focused so that you can start typing immediately.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.22

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
This is a duplicate issue, thanks!
