### ISSUE TITLE
Cant drag tabs to different workspaces

### ISSUE THREAD

**Issue by gambithunt** [zen-browser/desktop#2990]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

This is something I do often, dragging a tab from one workspace to another. This is most useful and more intuitive that copy pasting it across.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by Smooth-E** [comment]
Was this available before? If not, this seems like an enhancement request, which belongs in [GitHub discussions](https://github.com/zen-browser/desktop/discussions). For now it is possible to Shift-select a couple of tabs, right click on them and select "Move tab(s) to workspace".
