### ISSUE TITLE
Swaping Spaces via swiping is buggy

### ISSUE THREAD

**Issue by neurokitti** [zen-browser/desktop#2992]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

lol i didnt even notice this got added

when swiping between workspaces it often jumps multiple workpaces even with a single swipe. 

https://github.com/user-attachments/assets/8a8fc914-46fe-49bc-a68b-5c3bdf49fe8f

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-t19

### What platform are you seeing the problem on?

Windows

**Comment by neurokitti** [comment]
edit: it works its just overly sensitive so to swap a single workspace over it needs to be a supper small swipe

**Comment by JSGRD22** [comment]
I would like to elaborate on this issue that it is caused by a repeat of the workspace switch action on _release_. This means that sometimes, if you do a swipe, it switches workspaces immediately upon the gesture, but then does it again when you release.

**Comment by Smooth-E** [comment]
I would like to add that some kind of an animation for this would be nice to see which workspace is next / previous. This can be similar to how swiping right on the webpage displays an arrow before it goes back in history (Firefox feature).

**Comment by lancewilhelm** [comment]
Not to keep piling on, but having the option to toggle the swipe action in the preferences menu would be handy as well. For those looking for a temporary fix, in `about:config`, you can toggle the `zen.workspaces.swipe-actions` bool.

**Comment by sodapopcan** [comment]
I've noticed swiping within the pins section is SUPER sensitive... like, even a slight degree off of a perfect up or down swipe will change workspaces.  Meanwhile, swiping in the regular tab section doesn't work.

I personally don't care how this is resolved since there are going to be a ton of different opinions, but right now, the vast majority of the time I scroll my pinned tabs it changes workspaces on me.

**Comment by neurokitti** [comment]
I'm fixing this
