### ISSUE TITLE
Behaviour for Clicking "X" on Pinned Tab not Respecting Setting

### ISSUE THREAD

**Issue by r4yfon** [zen-browser/desktop#2994]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![image](https://github.com/user-attachments/assets/8e343f6f-338c-4e72-92be-9bcd1dc0b3ab)
https://github.com/user-attachments/assets/1118dec0-34b0-4cfa-94a0-33c72dc35a79

- I set the behaviour when closing pinned tabs to be "unload and switch to next tab", which works when I use the Ctrl+W keyboard shortcut
- But when I manually click on the "X" button in the sidebar, the tab gets closed instead

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.19

### What platform are you seeing the problem on?

Windows

**Comment by kristijanribaric** [comment]
X button was replaced with reset to pinned URL button in the upcoming  `1.0.1-a.20` release.
