### ISSUE TITLE
"Zen-split-view-modifier-header" is displayed instead of proper header in settings "Look and Feel" tab

### ISSUE THREAD

**Issue by leokostarev** [zen-browser/desktop#2996]
### Captchas

- [x] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When browser language is set to English (GB)
"Zen-split-view-modifier-header" is displayed in settings, seems like translation is missing

![image](https://github.com/user-attachments/assets/4d996184-c3af-4612-a747-9902fa3934e2)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.19 (Firefox 132.0.1)

### What platform are you seeing the problem on?

Windows

**Comment by 12th-devs** [comment]
I just created a pull request for it, I will keep you updated!

[Pull Request](https://github.com/zen-browser/l10n-packs/pull/98)

Edit: the pull request was already made 3 days ago, should have looked a bit harder, updated URL
