### ISSUE TITLE
Resetting URL on Pinned Tabs Clears Favicon

### ISSUE THREAD

**Issue by stevKalo** [zen-browser/desktop#2997]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When I have the tab management option of "Reset URL, Unload Tab, and Switch Tab" selected, closing my pinned tabs removes the favicon. And since there doesn't seem to be an option to rename/nickname pinned tabs or mark them with icons/emojis, I can't quickly open my pinned tabs when my sidebar is in its smaller display. I have confirmed that I am not clearing my cache on closing Zen, and that I still have caches for the sites I'm visiting

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.19

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by kristijanribaric** [comment]
Fixed in upcoming `1.0.1-a.20` release, thanks!
