### ISSUE TITLE
Private window text is almost illegible

### ISSUE THREAD

**Issue by infiniwave** [zen-browser/desktop#300]
### What happened?

![image](https://github.com/user-attachments/assets/2f1b3d54-0b73-40bf-904e-67bc3430d96d)
See image. The background color makes the text illegible.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.22

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by NOCanoa** [comment]
U mean the web page text not browser text?

**Comment by mauro-balades** [comment]
Duplicate
