### ISSUE TITLE
When using compact mode for the sidebar, sometimes there is a blank space left behind instead of the sidebar.

### ISSUE THREAD

**Issue by Rimnar-1** [zen-browser/desktop#3002]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When using compact mode for the sidebar, for certain actions, there is a blank space left behind where the side bar would be, and it looks like the content of the tab is moved to make space for the new blank space. the only times I've experience the issue is when opening a Glance pop-up window, uninstalling an extension and going from full screen to window mode. Also, this issue only happens when setting the sidebar to the right edge, if the side bar is set to the left, it does not happen.

If you hover over the blank space to pop up the sidebar, the issue gets fixed, but it happens again when you do any of the actions mentioned above.

https://github.com/user-attachments/assets/37b5ae7d-a92e-4698-afee-1a9a952672a1

In this screenshot you can see how the content in the tab is moved outside of the window, this happens in full screen mode too.

![Screenshot 2024-11-13 175628](https://github.com/user-attachments/assets/3ab52a1e-59b2-4321-ba27-d1c213682c1c)

This is what the same window looks like when it is fixed.

![Screenshot 2024-11-13 175642](https://github.com/user-attachments/assets/fe0b9199-4e45-4381-9bc6-52f4230a1a5b)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.19 (64 bit)

### What platform are you seeing the problem on?

Windows

**Comment by Nirose** [comment]
this seems similar to #2574 (with the expanded tabs)
