### ISSUE TITLE
Weird Pinned Tabs Behaviour

### ISSUE THREAD

**Issue by chefpenguino** [zen-browser/desktop#3003]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![image](https://github.com/user-attachments/assets/03ac2e8c-e653-4ffa-bb6c-7faa772c6cdd)

I have the 'Allow workspaces to have their own pined tabs' option disabled.

Even though I have it disabled - when i go to different workspaces, my pinned tabs do not persist. They stay pinned only per workspace.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.19

### What platform are you seeing the problem on?

Linux

**Comment by Fxxxlei** [comment]
I didn't know that option still existed, is it even supposed to do anything?

We now have both simultaneously: pinned tabs (per workspace) and essential tabs (everywhere).

**Comment by lextatic** [comment]
I have the exact same issue and I don't have that SuperPins mod. Started happening a few versions ago when some things in the base layout changed.

**Comment by Fxxxlei** [comment]
I was only implying this question before, but are you both correctly using Essential tabs instead of pinned tabs?

**Comment by chefpenguino** [comment]
> I didn't know that option still existed, is it even supposed to do anything?
> 
> We now have both simultaneously: pinned tabs (per workspace) and essential tabs (everywhere).

I did not notice this. I just started using essentials and the tabs now behave as expected. Thank you.
