### ISSUE TITLE
Option to disable middle click new tab

### ISSUE THREAD

**Issue by RABINGG** [zen-browser/desktop#3006]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

Provide an option to disable middle click new tab

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.19 (Firefox 132.0.1) (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by Smooth-E** [comment]
This is an enhancement request. This project uses [GitHub Discussions](https://github.com/zen-browser/desktop/discussions) for such tickets. Please, consider creating an entry there and closing this issue.

Also, the "I am not filling an enhancement request" check-mark (which I see you did not tick) is meant to remind you of this. If you are new to GitHub, it is good to know that usually ticks in sections like "Captcha" or "Agreements" are meant to stop people from submitting stuff not where it belongs (i.e. when project uses an external issue tracker or to prevent "asking for help" on an issue board).

**Comment by mr-cheffy** [comment]
> This is an enhancement request. This project uses [GitHub Discussions](https://github.com/zen-browser/desktop/discussions) for such tickets. Please, consider creating an entry there and closing this issue.
> 
> Also, the "I am not filling an enhancement request" check-mark (which I see you did not tick) is meant to remind you of this. If you are new to GitHub, it is good to know that usually ticks in sections like "Captcha" or "Agreements" are meant to stop people from submitting stuff not where it belongs (i.e. when project uses an external issue tracker or to prevent "asking for help" on an issue board).

Im gonna copy this answer to anyone that keeps sending enhancements haha
