### ISSUE TITLE
[Twilight] Spamming Reload button on pinned tabs blanks it out.

### ISSUE THREAD

**Issue by Shockshwat** [zen-browser/desktop#3009]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Basically title, spamming the button (Not fast but like 3-4 times) makes the tab go blank and show "New Tab" rather than the pinned one.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-t.19 

### What platform are you seeing the problem on?

Windows

**Comment by 12th-devs** [comment]
I was unable to recreate this on twilight. I update daily, have you updated today?

**Comment by Shockshwat** [comment]
Yes the problem seems to be fixed with today's update. Thanks!
