### ISSUE TITLE
Spotify web player skips songs.

### ISSUE THREAD

**Issue by notacodermadeaccountforreportissue** [zen-browser/desktop#3011]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Spotify web doesn't let me play songs also the songs that eventually play mute after some seconds. 
Opening in incognito without extension doesn't work.  
Other browser like chrome and even Firefox with same extension list work fine.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.19

### What platform are you seeing the problem on?

Windows

**Comment by blakegearin** [comment]
This is expected. You can read the [FAQ](https://docs.zen-browser.app/faq#why-cant-zen-browser-play-drm-protected-content) to learn more.

**Comment by GJRobert** [comment]
Hi, I wonder how much funding base do you expect to make DRM Widevine license available to Zen?

**Comment by mr-cheffy** [comment]
> Hi, I wonder how much funding base do you expect to make DRM Widevine license available to Zen?

We dont need funding for a license

**Comment by X-49** [comment]
> > Hi, I wonder how much funding base do you expect to make DRM Widevine license available to Zen?
> 
> We dont need funding for a license

So when will the problem be fixed? I would have switched to Zen from Edge a long time ago, but I really need a working web version of Spotify, I stay away from the electron version.
