### ISSUE TITLE
Flathub reports version as 1.0.0-a.15 instead of current

### ISSUE THREAD

**Issue by Tc-001** [zen-browser/desktop#302]
### What happened?

The flatpak version https://flathub.org/apps/io.github.zen_browser.zen (and linux stores that use the flatpak backend) show the app version as still at 1.0.0-a.15

This is visual only, as shown by the "Built about XX hours ago" in flathub, and the "About Zen" in the browser shows the correct version as well.

From a quick skim of flatpak docs, it seems you also need a metainfo file that list the version, it seems to be referenced but may not actually exist or is outdated.
https://docs.flatpak.org/en/latest/conventions.html#metainfo-files

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.21

### Severity impact

Low

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
I just haven't released these release notes (explained on the discord), but it's updated to the latest version.

**Comment by Tc-001** [comment]
This issue was more was about the version number itself being stuck, but I guess both are pulled from metainfo

**Comment by LeMoonStar** [comment]
The Problem still persists, as the changelog entry in the metainfo file doesn't get updated with every update.
Also, the manifest file is often being updated with the current version AFTER the release was published, which causes the version in Flathub to lack behind by one version.

This issue thus should not be closed.

As the changelog seems to always be a link to the website, with only the version in the URL changing, I recommend doing this automatically in the Github Action responsible for releases. This will make Flathub display the correct version, without any maintainer actively having to change the file manually.
