### ISSUE TITLE
ZEN deleted all my data

### ISSUE THREAD

**Issue by kociol21** [zen-browser/desktop#3022]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I tested ZEN Browser for couple days. Installed maybe 10 extensions, imported bookmarks, installed some ZEN Themes etc. nothing special. Today I closed ZEN normally. After couple hours, I reopened and the browser showed me "Welcome" screen. All my browser data is wiped clean - tabs, bookmarks, themes, settings - it basically reverted to factory defaults. 

ZEN is installed via Flatpak on Bazzite. I've not done anything I can think of to trigger this. Didn't reboot, didn't update app. Just closed browser, left PC idle and came after like 3 hours. 

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.19 (Firefox 132.0.1) (64-bit)

### What platform are you seeing the problem on?

Linux

**Comment by JSGRD22** [comment]
Check if it created a new profile or anything; does it still have an old profile with all your data inside?

**Comment by kociol21** [comment]
Upon inspecting about:profiles - it showed me that I have two profiles created - "default (alpha)" and "default". However "default (alpha)" was new and set as default. When I switched to the other one - it still greeted me with first setup screen, so both profiles were clean, there wasn't any with my data.

**Comment by flexagoon** [comment]
Do you have any permission overrides set for the flatpak?

**Comment by kociol21** [comment]
In Flatseal I gave Zen access to my whole home directory I think. (but that was like 2-3 days before this bug)

Also globally I gave all flatpaks read-only access to /.icons to fix cursor issue with some apps. 

But that's all I think. The only thing I may have done between closing Zen and launching it in broken state is changing my DNS servers in network manager, but I doubt it is relevant.

**Comment by mantissa7** [comment]
I have just had this. Zen crashed and when I reopened it my profiles were gone. I had the new `xxx (alpha)` profile in profiles.ini too, my previous profiles were still referenced in profiles.ini. Fortunately I just quit and reopened Zen and the profiles reappeared. 

MacOS 15.3
Zen 1.8.2b
