### ISSUE TITLE
Tab Action keyboard shortcuts missing

### ISSUE THREAD

**Issue by KorigamiK** [zen-browser/desktop#3030]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

These all existed till version 1.0.1.a.3.

![Screenshot_2024-11-10-11-42-41_10293](https://github.com/user-attachments/assets/331ef486-c8a8-486e-ae9c-f52e803c8e7c)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1.a.19-1

### What platform are you seeing the problem on?

Linux

**Comment by KorigamiK** [comment]
@dosu this issue is more general on all of the tab action shortcuts that were removed

**Comment by plundration** [comment]
So what is the solution then? These files were moved from a different repo, but that one has been deleted. What is the reason for deleting the shortcuts?

**Comment by KorigamiK** [comment]
> So what is the solution then? These files were moved from a different repo, but that one has been deleted. What is the reason for deleting the shortcuts?

Yeah this issue is probably just being overlooked too much after the rework

**Comment by KorigamiK** [comment]
@mr-cheff would love an update here thanks

**Comment by KorigamiK** [comment]
@mr-cheff you could look into this commit for reference, I think the shortcuts refactored here without tab actions being added:
https://github.com/seanpm2001/Zen-Browser_Components/commit/a97e7e65ed826e05c62f858c8100c2bb2b1da05a#diff-435c4b0468cda5d573c2ed9e50466bd19e24de7865e8b79d17ce9f3ff359de68L9

**Comment by mr-cheffy** [comment]
Duplicate of https://github.com/zen-browser/desktop/issues/1678

**Comment by mr-cheffy** [comment]
> you could look into this commit for reference, I think the shortcuts refactored here without tab actions being added:

Actions are taken from the default firefox's now, before, we invented them. But they have a weird way of doing those specific shortcuts for whatever reason...

**Comment by KorigamiK** [comment]
> Actions are taken from the default firefox's now, before, we invented them. But they have a weird way of doing those specific shortcuts for whatever reason...

I understand, I would love to contribute for this feature but I tried building it and I just couldn't finish the build on my laptop. If you need help testing or something please let me know :)
