### ISSUE TITLE
Visual Bugs and personal problem collection.

### ISSUE THREAD

**Issue by nastyanvr** [zen-browser/desktop#304]
### What feature would you like to see?

# Feedback and Suggestions for Zen Browser

Just to get started, I really like Zen and the approach you are taking, but there are a lot of things that need to be done to make it a good daily-use browser.

I have compiled a small collection of visual problems, bugs, and features I would like to see.

### 1. Signing / Certification

When installing and importing, both Windows and MacOS warn that the browser is not verified to be secure. This is a major issue since the browser is an application users rely on for their online presence and it needs to be perceived as "safe."

### 2. "About Us" Page

Consider creating an "About Us" page on the website. Share information about the founders, team members, and the reasons behind starting the project. Also, outline the goals of Zen.

### 3. Imprint on the Website

Adding an imprint on the website would significantly increase trust, as it provides more information about who is behind the browser. This could include a company or legal name, and an email contact option, not just Discord, to be fully GDPR-compliant.

I understand that this requires effort and resources, but it's important to recognize that this isn't just a random application used once a month. It's a gateway to the online world, and if it can't be trusted with personal information, it raises an immediate red flag.

### 1. Copy-Paste Text as Advertisement

Whether it's team members or random people, seeing the same copy-paste text on platforms like Reddit seems very odd to me.

### 2. Overall Public Appearance

Using language like "fuck you @ emm" in a Discord announcement doesn't look good. While it's fine to joke around in private, such language shouldn't appear on a Discord server that is directly linked to the Zen page.

![image](https://github.com/user-attachments/assets/0233ca8b-2fb3-48de-8e3f-aee7297a4726)

_#announcements on Mauro's little sweatshop Discord Server_ https://discord.com/channels/1088172780480114748/1094972995203768451/1194690609345200269

### 1. Symbol in URL Bar Acts Weird

When on a site that has an icon in the URL bar, such as Cookies:

![image](https://github.com/user-attachments/assets/da92d4a6-675d-40ff-ad1b-41641cf34bda)

If you delete everything in the URL bar, it turns into this:

![image](https://github.com/user-attachments/assets/cca71e5a-8d2f-46eb-a15f-212681dc3229)

### 2. Favicons on the Sidebar Are Misaligned

Many icons, like YouTube, are not aligned properly compared to others.

![image](https://github.com/user-attachments/assets/26ba3624-2442-4335-bcaf-b78ff665efd3)

All icons are 1-2px off on one side compared to the other.

### 3. Very Weird-Looking Hover Box

When hovering over some icons in the sidebar, the box around them looks very off.

![image](https://github.com/user-attachments/assets/2a542003-d1f4-47b1-a620-bca293bc7779)

### 4. Settings Page Behaving Weirdly on Specific Resolutions / Aspect Ratios

When using Zen in a smaller resolution, the settings page sometimes turns into this:

![image](https://github.com/user-attachments/assets/688dd3d8-add6-4dc2-978b-0ca2b388e26a)

### 5. Top Bar Behaving Weirdly with 4:3 Stretched Resolution

When using a 4:3 stretched resolution and having Zen in a smaller window, the top bar behaves strangely:

![image](https://github.com/user-attachments/assets/fba75818-f5ac-479b-acc5-0f3502f069f1)

### 6. Window Buttons Not Matching Windows 11

The window buttons seem different, and the maximize button is sharper than in default Windows 11 apps.

![image](https://github.com/user-attachments/assets/68559165-6051-473f-8662-ad5e7091fcbe)

### 7. Windows App Icon Is Low Resolution

The app icon in the taskbar is low-resolution to the point where I can count the pixels.

![image](https://github.com/user-attachments/assets/94fc383d-4a9f-4185-8750-f9cf3d01afb3)

### 8. Zen Installer Using Firefox Icon

A small detail, but it would look better if the installer used a Zen-specific icon rather than the default Firefox one.

![image](https://github.com/user-attachments/assets/3bf07144-2807-4f02-837f-9a3637841566)

### 9. Theme Shop Named Incorrectly

With the latest patch, the Theme Shop was introduced, but in the settings, it's still called "Theme Marketplace."

![image](https://github.com/user-attachments/assets/ff4cc144-cb94-4aa2-aaa8-ca61ecb9cb15)

### 10. Hover Animation Lag

When hovering over elements, the animation sometimes takes longer than usual or lags.

## Features I Would Like to See in the Future

1. Ability to fully customize the sidebar. While themes exist, I would love the option to customize it like the top bar in Firefox using the "Customize Toolbar" feature, and generally have more control over the sidebar.

2. Having uBlock Origin preinstalled.

3. Better keybind settings, including the ability to change the native Firefox keybinds rather than just disabling them.

4. An update page that automatically opens after installing an update, showing the latest features added and bugs that were fixed.

5. A feature where, when selecting text, a small pop-up appears allowing you to search that text on search engines, similar to how Opera does it, instead of needing to right-click and search.

6. Removing the default Firefox purple, as many users dislike it.

7. Finding sponsorships to cover certification costs without needing to monetize the user base, similar to how Ladybird is doing it.

8. Support for importing data from more browsers, like Floorp.

9. A better-looking history and bookmarks page.

10. Ability to change the Windows taskbar/app icon within Zen.

11. Fixing slow performance, as the browser often becomes unresponsive for a few seconds, and some websites report that the browser is outdated.

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
Fixed most issues, thanks!

**Comment by Wiibleyde** [comment]
![image](https://github.com/user-attachments/assets/50884dbc-0807-4443-938f-d5ce7f1a6f5e)
Hello I don't know if it's util here but here is a weird thing, I can add hardware and software information if you want !
