### ISSUE TITLE
Missing Downloads Button and No Download Popup Notification

### ISSUE THREAD

**Issue by ItsTatsuya** [zen-browser/desktop#3044]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

# Issue Detail
The Downloads button is missing from the toolbar in Zen Browser. Additionally, there is no popup or notification when a file is downloading. This makes it difficult to track or access ongoing downloads.

# Video Explaining the issue
https://github.com/user-attachments/assets/2ff0ddc4-2e9a-4815-ba76-ca384a5df7f6

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.19 (20241110213707)

### What platform are you seeing the problem on?

Windows

**Comment by Shockshwat** [comment]
Well for me the download button exists in the sidebar, Which i think you can move to the top when right clicking the sidebar and clicking customize toolbar.

**Comment by ItsTatsuya** [comment]
> Well for me the download button exists in the sidebar, Which i think you can move to the top when right clicking the sidebar and clicking customize toolbar.

For me, however, the Download button wasn’t in the sidebar or the overflow menu at all.

Update: Resetting the profile brought the button back to the sidebar, and I was able to drag it to its usual spot.

**Comment by JSGRD22** [comment]
You may close the issue if it has been resolved

**Comment by clembu** [comment]
"resetting the profile" shouldn't really be the solution here. There's still a bug somewhere, if the Downloads command isn't available in toolbar customization.
