### ISSUE TITLE
Switching tabs to a different workspace is causing the sidebar to freeze

### ISSUE THREAD

**Issue by oasido** [zen-browser/desktop#3046]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When I want to move a tab to a different workspace, I usually toggle the sidebar's visibility, and right click > Change Tab(s) to Workspace.
Upon doing that I've noticed that the sidebar is getting stuck and I am unable to close it.
Right now I am just relaunching the browser to fix it.

I am running Zen on openSUSE Tumbleweed and installed it through Flatpak (1.0.1-a.19)

Loving Zen so far!

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.19

### What platform are you seeing the problem on?

Linux

**Comment by Citizen-001** [comment]
Same thing happens on windows 11 22H2

**Comment by VSparl** [comment]
I'm on Windows 11 24H2 and have the same issue. It also occurs when selecting multiple tabs and moving them to another workspace, not just when you move them individually.

**Comment by gabenasci** [comment]
I have the same issue with latest alpha version 'zen-specific' on Linux (GNOME/Wayland), this happens on normal and compact mode for me.

When moving tabs to another workspace, I can't use the right click menu on any tabs in the sidebar, but I'm able to switch tabs/workspaces. This issue remains even if I toggle compact mode on/off, need to reopen browser to continue.

If I trigger this issue while in compact mode, the sidebar remains open (and unable to right click on tabs) until I restart the browser.

When this issue happens, I noticed the workspace switcher UI also gets cut out (might be unrelated).

![image](https://github.com/user-attachments/assets/7ab6f5ff-f956-4049-8f77-2daf13568b33)

`1.0.1-a.19 (Firefox 132.0.1) (64-bit)`

Mentioned this in #2980 as well.

**Comment by gabenasci** [comment]
I have the same issue with latest alpha version 'zen-specific' on Linux, this happens on normal and compact mode for me.

When moving tabs to another workspace, I can't use the right click menu on any tabs in the sidebar, but I'm able to switch tabs/workspaces. This issue remains even if I toggle compact mode on/off, need to reopen browser to continue.

When this issue happens, I noticed the workspace switcher UI gets cut out (might be unrelated).
![image](https://github.com/user-attachments/assets/7ab6f5ff-f956-4049-8f77-2daf13568b33)

**Comment by oasido** [comment]
Still relevant

**Comment by mr-cheffy** [comment]
> Still relevant

In version b5?

**Comment by oasido** [comment]
Sorry, this was fixed in b.4!
I updated my browser now & tested it.
