### ISSUE TITLE
window background totally messed up aafter setting theme color [ websites which doesn't specify a background color and uses default css i guess ]

### ISSUE THREAD

**Issue by janardannn** [zen-browser/desktop#3047]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I changed the toolbar's theme to something I liked and then noticed that some websites are having my theme colour as their primary background color which makes them very unusable
 
![extension settings page](https://github.com/user-attachments/assets/723db9fa-daac-4ec2-9b85-3a5a731f47e6)
![react based shopping website, myntra.com](https://github.com/user-attachments/assets/f360df23-9227-4847-81a2-4402071f9a9d)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.19 (Firefox 132.0.1)

### What platform are you seeing the problem on?

Windows

**Comment by 12th-devs** [comment]
Hey! Unless you use the blank new tab setting, consider changing the browser.tabs.allow_transparent_browser in about:config. If you use the blank new tab, you could consider an extension like the Dark Reader to set the background automatically. [Dark Reader Extention](https://addons.mozilla.org/en-US/firefox/addon/darkreader/) I hope this helps. Have a great day!


![Screenshot 2024-11-16 at 07-52-29 Advanced Preferences](https://github.com/user-attachments/assets/0873f716-c8c6-410a-b180-b0c56e68659a)
**Change this in about:config (enter about:config in URL bar to get to this page)**

**Comment by janardannn** [comment]
yup, that worked thanks. @Anoms12

**Comment by CritLoren** [comment]
> Hey! Unless you use the blank new tab setting, consider changing the browser.tabs.allow_transparent_browser in about:config. If you use the blank new tab, you could consider an extension like the Dark Reader to set the background automatically. [Dark Reader Extention](https://addons.mozilla.org/en-US/firefox/addon/darkreader/) I hope this helps. Have a great day!
> 
> ![Screenshot 2024-11-16 at 07-52-29 Advanced Preferences](https://private-user-images.githubusercontent.com/117039159/386846193-0873f716-c8c6-410a-b180-b0c56e68659a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MzY3OTcsIm5iZiI6MTczMTkzNjQ5NywicGF0aCI6Ii8xMTcwMzkxNTkvMzg2ODQ2MTkzLTA4NzNmNzE2LWM4YzYtNDEwYS1iMTgwLWIwYzU2ZTY4NjU5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOFQxMzI4MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Nzk2ODJkZjYyYTA3MzE1M2JjYzY2YWRkMjRiMmJhMWRjZTI1ZGIxYTBjZTMwOTZmNGZlMjYzNjQyZTEyMWU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.FN88kW2Q6gIBg4iQrsYT8EIyR2Aomn-Klq5IMAsgv2o) **Change this in about:config (enter about:config in URL bar to get to this page)**

oh curious, wonder how that got toggled. This fixed the issue for me
