### ISSUE TITLE
Spell Checker Not Working for Languages Other Than English in Zen Browser

### ISSUE THREAD

**Issue by FrancoStino** [zen-browser/desktop#3049]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### Issue Summary
The spell checker in Zen Browser does not work properly for languages other than English. For example, the Italian and Brazilian Portuguese spell checkers are not functioning.

### Steps to Reproduce
1. Open Zen Browser and go to a text input field.
2. Try typing in Italian or Brazilian Portuguese.
3. The spell checker highlights the error with the red line.

### Expected Behavior
The spell checker should not identify spelling errors in languages such as Italian and Brazilian Portuguese when you set.

### Actual Behavior
The spell checker only seems to work effectively in English. In other languages, it fails.

### Additional Information
- **Languages Affected**: Italian, Brazilian Portuguese, and possibly others.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Alpha build - 1.0.1-a.19

### What platform are you seeing the problem on?

Linux

**Comment by Riko07br** [comment]
It's a bit weird to get used to, but you need to install the spell check for that language
 - Type a random string of chars in a text input field
 - Right click on the "incorrect" word
 - Click on languages>add dictionaries
 - ctrl+f on the page that opens and search for the desired dictionary (eg. portuguese)
 - install it (remember the dictionaries are in the **right column**)
 - Go back to the text box and right click on the "incorrect" word
 - Click on languages and add check the new dictionary installed

**Comment by FrancoStino** [comment]
> It's a bit weird to get used to, but you need to install the spell check for that language
> 
>     * Type a random string of chars in a text input field
> 
>     * Right click on the "incorrect" word
> 
>     * Click on languages>add dictionaries
> 
>     * ctrl+f on the page that opens and search for the desired dictionary (eg. portuguese)
> 
>     * install it (remember the dictionaries are in the **right column**)
> 
>     * Go back to the text box and right click on the "incorrect" word
> 
>     * Click on languages and add check the new dictionary installed

thank you so much!

**Comment by tzinm** [comment]
@Riko07br many thanks for the detailed explanation. Solved the issue 🙂
