### ISSUE TITLE
sometimes i get workspace switch animation while opening/closing tab

### ISSUE THREAD

**Issue by spectrum705** [zen-browser/desktop#3051]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

sometimes i get workspace switch animation while opening/closing tab. it happens randomly so idk how to replicated it but it mostly happened when i used to open links in new tab, with ctrl + click

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.19 (Firefox 132.0.1) (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by oasido** [comment]
Do you mean the sidebar pops up for a brief second?
If so disable this: 
![image](https://github.com/user-attachments/assets/2106fae8-3e14-4537-a6e7-6070e3a66193)

**Comment by spectrum705** [comment]
oh okay, let me try

**Comment by spectrum705** [comment]
didnt fix, i still get that workspace switch animation .
this time i noticed it when i opened a link from sidebar chat.
