### ISSUE TITLE
Tabs crashing in Twilight due to extensions such as Bitwarden.

### ISSUE THREAD

**Issue by RabbyDevs** [zen-browser/desktop#3054]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Sometimes, randomly, tabs will crash, **this issue only occurs in _twilight_.**

Note: This happens even if I completely disable Zen Mods, and no I have not internally modded the browser.

Yummy spec information:
         Operating System: Windows 11 Pro 64-bit (10.0, Build 26100) (26100.ge_release.240331-1435)
                 Language: English (Regional Setting: English)
      System Manufacturer: Micro-Star International Co., Ltd.
             System Model: MS-7E06
                     BIOS: 1.C0 (type: UEFI)
                Processor: 13th Gen Intel(R) Core(TM) i7-13700K (24 CPUs), ~3.4GHz
                   Memory: 32768MB RAM
      Available OS Memory: 32538MB RAM
                Page File: 29056MB used, 23961MB available
              Windows Dir: C:\WINDOWS
          DirectX Version: DirectX 12
      DX Setup Parameters: Not found
         User DPI Setting: 96 DPI (100 percent)
       System DPI Setting: 96 DPI (100 percent)
          DWM DPI Scaling: Disabled
                 Miracast: Available, with HDCP
Microsoft Graphics Hybrid: Not Supported
 DirectX Database Version: 1.6.2
   Auto Super Res Version: Unknown
       System Mux Support: Mux Support Inactive - Ok
           Mux Target GPU: dGPU
           DxDiag Version: 10.00.26100.2161 64bit Unicode
           Card name: AMD Radeon RX 7900 XT
        Manufacturer: Advanced Micro Devices, Inc.
           Chip type: AMD Radeon Graphics Processor (0x744C)
 Device Problem Code: No Problem
 Driver Problem Code: Unknown
      Display Memory: 36670 MB
    Dedicated Memory: 20402 MB
       Shared Memory: 16268 MB
        Current Mode: 2560 x 1440 (32 bit) (165Hz)
         HDR Support: Not Supported
    Display Topology: Internal
 Display Color Space: DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
     Color Primaries: Red(0.660156,0.326172), Green(0.265625,0.579102), Blue(0.137695,0.112305), White Point(0.301758,0.353516)
   Display Luminance: Min Luminance = 0.500000, Max Luminance = 270.000000, MaxFullFrameLuminance = 270.000000
        Monitor Name: Dell S2722DGM (DP)
       Monitor Model: DELL S2722DGM
          Monitor Id: DEL4239
         Native Mode: 2560 x 1440(p) (59.951Hz)
         Output Type: Displayport External
Monitor Capabilities: HDR Not Supported
Display Pixel Format: DISPLAYCONFIG_PIXELFORMAT_32BPP
      Advanced Color: AdvancedColorSupported 
      Using DDisplay: Yes

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-t.19 (64-bit) (optimized)

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
I do not know how to get logs from Zen, if you are reading this and do know how to, please tell me.
```

**Comment by 12th-devs** [comment]
Enable dev tools for the browser in the three dot menu (top right) I'm not at my PC right now so I cannot tell you exactly but check all the items in there. It is a sub option. (You can also check the zen docs, link on website) After that do Ctrl+Shift+Alr+I to enable browser dev tools. Go to the console and copy any relevant log to the crash. I am also on Twilight so to confirm you are talking about the tab just becoming unclickable right?Hope this helps and you have a great day!

**Comment by RabbyDevs** [comment]
@Anoms12 ill go try it later tomorrow, but no I am talking about a full on tab crash, with the tab crash message.
![image](https://github.com/user-attachments/assets/ccec06d2-b517-4e66-9101-1ac7c3be1188)

**Comment by 12th-devs** [comment]
That's odd, I've never had this. Perhaps update Twilight? I update nightly.

**Comment by RabbyDevs** [comment]
@Anoms12 I've already tried that.

**Comment by RabbyDevs** [comment]
```
Promise resolved while context is inactive
2 [bootstrap-autofill-overlay.js:950](moz-extension://45567f4e-9622-4310-b1ea-59aa4273b7a2/content/bootstrap-autofill-overlay.js)
    sendExtensionMessage moz-extension://45567f4e-9622-4310-b1ea-59aa4273b7a2/content/bootstrap-autofill-overlay.js:950
Error: TelemetryStopwatch: key "WEBEXT_CONTENT_SCRIPT_INJECTION_MS" was already initialized [ExtensionTelemetry.sys.mjs:224:31](resource://gre/modules/ExtensionTelemetry.sys.mjs)
Error: TelemetryStopwatch: key "WEBEXT_CONTENT_SCRIPT_INJECTION_MS_BY_ADDONID" was already initialized [ExtensionTelemetry.sys.mjs:228:41](resource://gre/modules/ExtensionTelemetry.sys.mjs)
Error: TelemetryStopwatch: finishing nonexisting stopwatch. Histogram: "WEBEXT_CONTENT_SCRIPT_INJECTION_MS", key: "" [ExtensionTelemetry.sys.mjs:224:31](resource://gre/modules/ExtensionTelemetry.sys.mjs)
Error: TelemetryStopwatch: finishing nonexisting stopwatch. Histogram: "WEBEXT_CONTENT_SCRIPT_INJECTION_MS_BY_ADDONID", key: "{446900e4-71c2-419f-a6a7-df9c091e268b}" [ExtensionTelemetry.sys.mjs:228:41](resource://gre/modules/ExtensionTelemetry.sys.mjs)
Error: TelemetryStopwatch: finishing nonexisting stopwatch. Histogram: "WEBEXT_CONTENT_SCRIPT_INJECTION_MS", key: "" [ExtensionTelemetry.sys.mjs:224:31](resource://gre/modules/ExtensionTelemetry.sys.mjs)
Error: TelemetryStopwatch: finishing nonexisting stopwatch. Histogram: "WEBEXT_CONTENT_SCRIPT_INJECTION_MS_BY_ADDONID", key: "{446900e4-71c2-419f-a6a7-df9c091e268b}" [ExtensionTelemetry.sys.mjs:228:41](resource://gre/modules/ExtensionTelemetry.sys.mjs)
timerId not found for Glean timing_distribution contentScriptInjection [ExtensionTelemetry.sys.mjs:182](resource://gre/modules/ExtensionTelemetry.sys.mjs)
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. 2 [background.js:1](moz-extension://45567f4e-9622-4310-b1ea-59aa4273b7a2/background.js)
Promise resolved while context is inactive
[bootstrap-autofill-overlay.js:950](moz-extension://45567f4e-9622-4310-b1ea-59aa4273b7a2/content/bootstrap-autofill-overlay.js)
Error: TelemetryStopwatch: key "WEBEXT_CONTENT_SCRIPT_INJECTION_MS" was already initialized [ExtensionTelemetry.sys.mjs:224:31](resource://gre/modules/ExtensionTelemetry.sys.mjs)
Error: TelemetryStopwatch: key "WEBEXT_CONTENT_SCRIPT_INJECTION_MS_BY_ADDONID" was already initialized [ExtensionTelemetry.sys.mjs:228:41](resource://gre/modules/ExtensionTelemetry.sys.mjs)
Error: TelemetryStopwatch: finishing nonexisting stopwatch. Histogram: "WEBEXT_CONTENT_SCRIPT_INJECTION_MS", key: "" [ExtensionTelemetry.sys.mjs:224:31](resource://gre/modules/ExtensionTelemetry.sys.mjs)
Error: TelemetryStopwatch: finishing nonexisting stopwatch. Histogram: "WEBEXT_CONTENT_SCRIPT_INJECTION_MS_BY_ADDONID", key: "{446900e4-71c2-419f-a6a7-df9c091e268b}" [ExtensionTelemetry.sys.mjs:228:41](resource://gre/modules/ExtensionTelemetry.sys.mjs)
Error: TelemetryStopwatch: finishing nonexisting stopwatch. Histogram: "WEBEXT_CONTENT_SCRIPT_INJECTION_MS", key: "" [ExtensionTelemetry.sys.mjs:224:31](resource://gre/modules/ExtensionTelemetry.sys.mjs)
Error: TelemetryStopwatch: finishing nonexisting stopwatch. Histogram: "WEBEXT_CONTENT_SCRIPT_INJECTION_MS_BY_ADDONID", key: "{446900e4-71c2-419f-a6a7-df9c091e268b}" [ExtensionTelemetry.sys.mjs:228:41](resource://gre/modules/ExtensionTelemetry.sys.mjs)
timerId not found for Glean timing_distribution contentScriptInjection [ExtensionTelemetry.sys.mjs:182](resource://gre/modules/ExtensionTelemetry.sys.mjs)
Promise resolved while context is inactive
[bootstrap-autofill-overlay.js:950](moz-extension://45567f4e-9622-4310-b1ea-59aa4273b7a2/content/bootstrap-autofill-overlay.js)
Layout was forced before the page was fully loaded. If stylesheets are not yet loaded this may cause a flash of unstyled content. [index.js:1496:1](moz-extension://6b756714-ff62-42a8-9d8e-aa7c7e1f2fe6/inject/index.js)
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. [background.js:1](moz-extension://45567f4e-9622-4310-b1ea-59aa4273b7a2/background.js)
Could not find any MenuItem with id: root [background.js:1:930](moz-extension://45567f4e-9622-4310-b1ea-59aa4273b7a2/background.js)
Could not find any MenuItem with id: copy-password [background.js:1:930](moz-extension://45567f4e-9622-4310-b1ea-59aa4273b7a2/background.js)
ID already exists: autofill_noop [background.js:1:930](moz-extension://45567f4e-9622-4310-b1ea-59aa4273b7a2/background.js)
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. [background.js:1](moz-extension://45567f4e-9622-4310-b1ea-59aa4273b7a2/background.js)
Given tab is not restoring. [SessionStore.sys.mjs:6658:15](resource:///modules/sessionstore/SessionStore.sys.mjs)
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. [background.js:1](moz-extension://45567f4e-9622-4310-b1ea-59aa4273b7a2/background.js)
this.window.gBrowserInit is undefined [ext-browser.js:1148:9](chrome://browser/content/parent/ext-browser.js)
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. 3 [background.js:1](moz-extension://45567f4e-9622-4310-b1ea-59aa4273b7a2/background.js)
Use of nsIFile in content process is deprecated. 8 [NetUtil.sys.mjs:249:50](resource://gre/modules/NetUtil.sys.mjs)
stylesheets: fetch from cache returned non-css content-type application/x-unknown-content-type for moz-extension://c5cab1ab-2041-427d-9fab-77b5a658afd0/experiment.css, trying without cache. [stylesheet-utils.js:110:15](resource://devtools/server/actors/utils/stylesheet-utils.js)
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.
```

**Comment by 12th-devs** [comment]
@RabbyDevs I would try disable all of your extensions and see what that does. I'm not very good with crash logs yet but ChatGPT is pretty sure it's an extension based issue 🤷🏼‍♂️

**Comment by RabbyDevs** [comment]
It seems Bitwarden is the cause.

**Comment by RabbyDevs** [comment]
The most recent Twilight update has made this significantly better.

**Comment by RabbyDevs** [comment]
This was pretty much fixed with the most recent twilight update.
