### ISSUE TITLE
[Win10] [Generic] Substantial performance regression since a.22 on Sandy Bridge

### ISSUE THREAD

**Issue by BreadlyUwU** [zen-browser/desktop#306]
### What happened?

Hello and sorry in advance I'm coming with a potentially annoying issue,
A.21's generic build was snappy asf on my old Sandy Bridge desktop (Intel i5-2500) but since a.22 I've noticed a huge performance drop of the whole browser (huge browser loading time, difficulties to render web pages, even the settings need several seconds to load).

I somehow feel like this has to do with some recent changes with the compiler flags but I don't see what change in the recent commits could be the source of the problem, if this has nothing to do with flags something else is definitely generating an excessive CPU overhead. :|

I've downgraded to a.21 for the time being, but I would happily reinstall a.22 to collect additional info if I can help with it

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

a.22 generic

### Severity impact

Medium

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
Let's see if it's fixed in 23 with the changes i've made
