### ISSUE TITLE
side panel padding is wack

### ISSUE THREAD

**Issue by neurokitti** [zen-browser/desktop#3061]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![image](https://github.com/user-attachments/assets/be2f7587-63ae-4344-9072-64e087d034d3)

the padding between it and the sidebar is to big wearas the padding on the side with main webpage is a bit small

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-t19

### What platform are you seeing the problem on?

Windows

**Comment by mr-cheffy** [comment]
This has been fixed in version 20!
