### ISSUE TITLE
Zen crashes when trying to upload file to a website

### ISSUE THREAD

**Issue by TheJolman** [zen-browser/desktop#3079]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Upon clicking some `upload file` button (doesn't matter what website), Zen freezes for a short amount of time and then crashes, closing all windows. File picker window never appears.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.19 (Firefox 132.0.1)

### What platform are you seeing the problem on?

Linux

**Comment by Tobi-De** [comment]
This issue has not being fixed. It's quite annoying to not being able to upload file on any site on your browser.
(Leaving this comment hoping it will reopen the issue)
