### ISSUE TITLE
Tab/Folder per domain

### ISSUE THREAD

**Issue by ThousandDemonDaggers** [zen-browser/desktop#309]
### What feature would you like to see?

Incorporate the tabs belonging to the same domain into a single tab/folder.

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/862

 ~ This is an automatic operation to better enhancements requests organization.
