### ISSUE TITLE
Split tabs not saved correctly

### ISSUE THREAD

**Issue by Heinrich-XIAO** [zen-browser/desktop#3098]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When I closed zen forcefully with a split screen, or any tab arrangement other than normal, and then reopen it, it either didn't save the fact that there was a split screen or it ignored it and opened the tabs seperately.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.19

### What platform are you seeing the problem on?

Linux aarch64

**Comment by mr-cheffy** [comment]
This hasnt been implemented yet, and it has been reported hundreds of times
