### ISSUE TITLE
Add extensions to web panels

### ISSUE THREAD

**Issue by TCBombLMG** [zen-browser/desktop#310]
### What feature would you like to see?

Be able to add extensions to the side web panel for example Bitwarden with the plus or via drag and dropping it should open the default Firefox sidebar bitwarden display for example.
![image](https://github.com/user-attachments/assets/989b863a-9e46-438a-9df0-42422f71b2f0)

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
You can do this by copying the extension's URL (e.g. right click and click see page source) and add it as a normal site

**Comment by TCBombLMG** [comment]
@mauro-balades I might be being stupid but its not working, this is what I see.
![image](https://github.com/user-attachments/assets/17767da6-c97b-4cd3-bca6-70f27e3a21e5)

**Comment by TCBombLMG** [comment]
> @mauro-balades I might be being stupid but its not working, this is what I see. ![image](https://private-user-images.githubusercontent.com/178717534/358912510-17767da6-c97b-4cd3-bca6-70f27e3a21e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5OTEzODQsIm5iZiI6MTcyMzk5MTA4NCwicGF0aCI6Ii8xNzg3MTc1MzQvMzU4OTEyNTEwLTE3NzY3ZGE2LWM5N2ItNGNkMy1iY2E2LTcwZjI3ZTNhMjFlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOFQxNDI0NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMGFmNmEyMzk2NTg2OGM3ZDYzOWVlNzU5MzdjNTNlOTFhZDQzMmM4OTJjMzk5ZGFhM2IzMmIxMzJkNzZiYTljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PCHl2ABBiBBv1TdEpY-RasdlMRJqDjtaFMMYc1nXmEc)

Nvm, all I needed to do was copy the URL but from the "moz-extension".

Thank you @mauro-balades

**Comment by mauro-balades** [comment]
No problem!

**Comment by guigirl42** [comment]
> You can do this by copying the extension's URL (e.g. right click and click see page source) and add it as a normal site

Please can you explain how to do this? Specifically `what` do i right-click _on_, to see the page source?

I have a specific AddOn in mind, which i really wish to use as a Web Panel, but it is malfunctioning in Zen [albeit, works perfectly in Firefox, Firefox-Nightly, & Floorp] ... https://addons.mozilla.org/en-US/firefox/addon/bookmark-search-plus-2. By "malfunctioning" i mean that its icon is ghosted-out, & none of its correct context-menu actions are available [in Zen only]. So when i saw this current Issue, i hoped it might give me an indirect way to add it as a Web Panel... except i do not understand how to follow your instruction for _this_ AO.

**Comment by TCBombLMG** [comment]
> > You can do this by copying the extension's URL (e.g. right click and click see page source) and add it as a normal site
> 
> Please can you explain how to do this? Specifically `what` do i right-click _on_, to see the page source?
> 
> I have a specific AddOn in mind, which i really wish to use as a Web Panel, but it is malfunctioning in Zen [albeit, works perfectly in Firefox, Firefox-Nightly, & Floorp] ... https://addons.mozilla.org/en-US/firefox/addon/bookmark-search-plus-2. By "malfunctioning" i mean that its icon is ghosted-out, & none of its correct context-menu actions are available [in Zen only]. So when i saw this current Issue, i hoped it might give me an indirect way to add it as a Web Panel... except i do not understand how to follow your instruction for _this_ AO.

So first thing you do is download the extension then log in (if you have a login) then open up the extension by clicking the extension drop down menu.
When the extensions open, right-click inside the extension and it should come up with "save page as", "select all" and "view page source".
Open view page source, this opens a new tab.
In the URL bar you will see "view-source:moz-extension://54233423213324" copy from the "moz-extension" all the way to the end.
Paste that into the sidebar panel.

Hope this helps. :)

**Comment by guigirl42** [comment]
Many thanks... but unfortunately...

>first thing you do is download the extension then log in

It's already installed, & has/needs no login.

>open up the extension by clicking the extension drop down menu

As i mentioned before, [only in] Zen is this AO partially dysfunctional; see in the pic it's _ghosted out_, unlike all the others in the list:

![image](https://github.com/user-attachments/assets/9f892280-489b-429d-a8bd-9b2ce0ee9253)

In this partly broken state, ordinary left-clicks on it do _nothing_ at all. Right-clicks on it only bring up a severely abridged menu:

![image](https://github.com/user-attachments/assets/d6170947-e8de-425a-b198-43fdb6e22ad6)

For comparison, here's the identical view from `Nightly` [also works correctly in `Floorp`]:

![image](https://github.com/user-attachments/assets/877c6351-d2a7-4bd0-8938-9724c001c07f)

Still in `Nightly` atm, when i click that highlighted option, as described, it indeed opens the AO in a dedicated tab, whose url is:

![image](https://github.com/user-attachments/assets/9aa0cd82-6358-4e82-af1c-d5146e9b470a)

Obviously that's what i want to see in `Zen`, but i can't [& btw i can't just copy & paste that `Nightly` url because it's a different string with every installation]. 

Thus, i still feel bamboozled.

**Comment by TCBombLMG** [comment]
Hi,
That URL you posted a screenshot off is what you copy and paste into the "Inital URL" in the sidebar.

**Comment by guigirl42** [comment]
>That URL you posted a screenshot off is what you copy and paste into the "Inital URL" in the sidebar

No no no, i explained this in my last post. That url is NOT in Zen, it's in Firefox Nightly. in Zen i cannot display any url, coz in Zen [& _only_ Zen] that AO is partly broken. I even included explanatory pics. 

Probably there's a bigger question here, i suspect... why is Zen unable to properly support that AO, when Floorp & FF-Nightly can?
