### ISSUE TITLE
Appimaged Fails to Register Zen

### ISSUE THREAD

**Issue by jnnkB** [zen-browser/desktop#3100]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Appimaged fails to register this appimage.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.19

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
-> REGISTER /Applications/zen-specific.AppImage
squashfs based type 2 AppImage
Squashfs image uses (null) compression, this version supports only xz, zlib.
sqfs_open_image error: /Applications/zen-specific.AppImage
```

**Comment by krale777** [comment]
Not working in KDE Neon either.

**Comment by omove** [comment]
Appimage changed it's compression to zstd a few months ago, the daemon should add support for newer appimages soon according to the dev TheAssassin/AppImageLauncher#674

**Comment by jnnkB** [comment]
I'm not using AppImageLauncher though, but appimaged: https://software.opensuse.org/package/appimaged

**Comment by omove** [comment]
Oh sorry, I haven't heard of that one so I thought you just meant the regular AppImageLauncher daemon. It's still the same issue though, appimaged not supporting the compression is why it says "(null) compression, this version supports only xz, zlib." 
That packages revision history says the version hasn't been updated in over 3 years, the only thing its gotten was a gcc patch a few days ago https://build.opensuse.org/package/revisions/openSUSE:Factory/appimaged

**Comment by Samueru-sama** [comment]
The original [appimaged is archived](https://github.com/AppImageCommunity/appimaged) and development moved to [go-appimage](https://github.com/probonopd/go-appimage/releases/tag/continuous).

That one should already work with this AppImage.
