### ISSUE TITLE
About gfx.webrender.all

### ISSUE THREAD

**Issue by redactedontop** [zen-browser/desktop#3110]
Heya. I wanna preface this by saying I absolutely love this browser, just got it today yet I'm immediately daily driving (with my own little tweaks, of course).
Let me cut to the chase though: gfx.webrender.all is disabled by default. It improves performance by quite a bit, and I'd love to see it enabled.

Thanks,
Alex <3
PS: I'm on Windows 11, and using version 1.0.0.

**Comment by n7itro** [comment]
That preference force enables WebRender, which shouldn't be necessary.  What does it say under Composition in about:support?

**Comment by redactedontop** [comment]
Oh, it already said WebRender. Closing <3
