### ISSUE TITLE
if a tab is pinned then moved to essentials on startup its data is lost

### ISSUE THREAD

**Issue by neurokitti** [zen-browser/desktop#3112]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

https://github.com/user-attachments/assets/cda334c6-41a4-4fdb-acd8-a13fd541e6d8

if a tab is first pinned then moved directly from pinned into essentials it is tab info is lost when you restart the browser

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-t19

### What platform are you seeing the problem on?

Windows

**Comment by OsoBear** [comment]
I'm having the same issue. Last restart, multiple windows opened...and fortunately one of them had my essentials and open tabs. Then I made the mistake of adding an essential to a profile....and all essentials were lost. I love the browser...but this makes it challenging to use.

**Comment by neurokitti** [comment]
> I'm having the same issue. Last restart, multiple windows opened...and fortunately one of them had my essentials and open tabs. Then I made the mistake of adding an essential to a profile....and all essentials were lost. I love the browser...but this makes it challenging to use.

when it comes to common essentials i would recommend putting them in a folder of bookmarks as a backup if you lose them since the browser is still in alpha
