### ISSUE TITLE
Open in a new tab shortcut

### ISSUE THREAD

**Issue by Muizzyranking** [zen-browser/desktop#3119]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When I use the open in new tab shortcut, (Ctrl + mouse right click), it doesn't actually open in a new tab, rather, it opens a pop up and I do not want this behaviour. I sometimes have a lot of links to be opened in new tab and then I would have to use right click and open them in a new tab. 

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1

### What platform are you seeing the problem on?

Linux

**Comment by rritik772** [comment]
Are you talking about glance feature. You can change this feature in settings `settings -> look and feel -> Glance`

**Comment by Heinrich-XIAO** [comment]
This is possible with ctrl+shift+click

**Comment by Heinrich-XIAO** [comment]
I just realized that ctrl shift click actually does something different, it opens the tab AND sets the current tab to that tab. However, ctrl click only opens the new tab.
