### ISSUE TITLE
Can't launch AppImage

### ISSUE THREAD

**Issue by iTrooz** [zen-browser/desktop#312]
### What happened?

I downloaded https://github.com/zen-browser/desktop/releases/download/1.0.0-a.22/zen-generic.AppImage and https://github.com/zen-browser/desktop/releases/download/1.0.0-a.22/zen-specific.AppImage, and both fail like this:

```
$ ./zen-generic.AppImage
execv error: No such file or directory
```

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Alpha 1.0.0-a.22

### Severity impact

Critical (Browser is not usable in any capacity)

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
$ ./zen-generic.AppImage
execv error: No such file or directory
```

### More information about my system:
- Linux distribution: Arch Linux
- Output of `/lib/ld-linux-x86-64.so.2 --help | grep x86`:
```
Usage: /lib/ld-linux-x86-64.so.2 [OPTION]... EXECUTABLE-FILE [ARGS-FOR-PROGRAM...]
This program interpreter self-identifies as: /usr/lib/ld-linux-x86-64.so.2
  x86-64-v4
  x86-64-v3 (supported, searched)
  x86-64-v2 (supported, searched)
```

**Comment by maks-bondarenko** [comment]
same here, ubuntu 22.04

**Comment by Samueru-sama** [comment]
Do you have appimagelauncher installed? That's an issue with it.

[Relevant info](https://github.com/PCSX2/pcsx2/pull/11667#issuecomment-2282683087)

**Comment by damian-ds7** [comment]
Yeah it didn't work for me with appimagelauncher either. After uninstalling it worked fine, and if you're looking for appimage manager [gear lever](https://flathub.org/apps/it.mijorus.gearlever) works fine for me

**Comment by mauro-balades** [comment]
Can I close this?

**Comment by KeluDev-Code** [comment]
Oouu great! With **[gear lever](https://flathub.org/apps/it.mijorus.gearlever)** as appimage manager it works perfectly for me.
I think the issue can be closed

**Comment by rinormaloku** [comment]
Are there any alternatives to gear lever? I don't want to install flatpak on my system.

**Comment by Samueru-sama** [comment]
> Are there any alternatives to gear lever? I don't want to install flatpak on my system.

https://github.com/ivan-hc/AM

**Comment by thebobbyboy420** [comment]
i removed appimagelauncher and installed gearlever on kde 6.2 and its working now
