### ISSUE TITLE
DRM issues

### ISSUE THREAD

**Issue by ShaneTursam** [zen-browser/desktop#313]
### What happened?

I saw the other day you had closed a couple of bugs stating you left DRM out and it was supposed to be built back in by the next update. I did not see anything in your release notes stating it had been added back and I have sites like Crunchyroll, Netflix, and others having DRM issues. 

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.22

### Severity impact

Critical

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
DRM is not supported for windows because the license is very expensive and Google won't just give it to anyone

**Comment by mauro-balades** [comment]
It's not only 1000 euros per year, Google also needs to verify your company (you need to be at the same level as Microsoft or brave)

**Comment by v-127** [comment]
> It's not only 1000 euros per year, Google also needs to verify your company (you need to be at the same level as Microsoft or brave)

I highly doubt that becuase browsers like Waterfox can play DRM content on Windows and they are not like Microsoft or something precissely.

**Comment by netcore10** [comment]
Yeah this has put me off from this. Streaming is just a big thing for me, and if waterfox can do it, may as well stick there.

**Comment by GunGunGun** [comment]
https://docs.zen-browser.app/faq#why-cant-zen-browser-play-drm-protected-content
