### ISSUE TITLE
Tab list is cut off when unmaximized 

### ISSUE THREAD

**Issue by infiniwave** [zen-browser/desktop#314]
### What happened?

See attached video:

https://github.com/user-attachments/assets/62259a05-ef50-4bd0-a5d6-9c0cdc8611d5

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.22

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
You have to wait for it to update the max height. Does it fix it's self after a while?

**Comment by infiniwave** [comment]
No, I can only see the full tab list when I maximize it again

**Comment by infiniwave** [comment]
Opening/closing a tab doesn't force it to update either

**Comment by fezboy** [comment]
This is also happening for me. When the tab list is full (i.e. starts scrolling), the buttons at the bottom, and the bottom of the page view will get cut off by the bottom edge of the window. This is especially problematic on lower resolution monitors, where the bottom is cut off even with the window maximized.

(I included audio in the attached video so you can tell when I'm trying to scroll down to the part of the page that's cut off)

https://github.com/user-attachments/assets/0edb7f14-d920-4dcd-bb1c-9b55b4a3a347

**Comment by InterstellarOne** [comment]
I'm getting the same issue on Fedora Linux, but I have the window maximised all the time so I don't know why it starts to happen sometimes.

**Comment by devxan** [comment]
My window is usually maximized on Windows, but the buttons on the bottom of the tabs sidebar are not visible. 
![Arrow pointing at where icons should be on the tabs sidebar (the bottom right of the screen)](https://github.com/user-attachments/assets/d45cc855-5c3a-492b-8785-bab7d8dc2b6c "Arrow pointing at where icons should be on the tabs sidebar (the bottom right of the screen)")
I tried changing my Display scaling, the size of the window, restarting the browser, and toggling some Zen browser themes, but none of these solved the issue on the most recent version of the browser ([1.0.0-a.35](https://zen-browser.app/release-notes/1.0.0-a.35)). I had the same issue on previous versions, but that normally seemed to fix itself.

**Comment by emoveo-design** [comment]
getting a similar issue, even when unplugging external screen using macOS Sonoma M1 macbookPro.
height is ok on external screen, then i unplug the screen and when height is being recalculated to laptop resolution, the bottom of the page is not scrollable. I mean content of a webpage AND Zen's UI elements.
I'm using v.0.1-a.7

**Comment by yant0** [comment]
same issue, on full widht too

**Comment by yant0** [comment]
i think  this is fixed in 83b077d5f3de8704a0881d596ea010b896b0694a

dont have the issue anymore
