### ISSUE TITLE
Crashes everytime during google login

### ISSUE THREAD

**Issue by ress-rifu** [zen-browser/desktop#3140]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

While I go to login page of the google to login into gmail, the browser crashed every time.

https://github.com/user-attachments/assets/d28731aa-e188-43d8-b035-5a6c205f0f5a

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

v1.0.1-a.19

### What platform are you seeing the problem on?

Windows

**Comment by TJdhyani** [comment]
facing this same issue
