### ISSUE TITLE
Side Panels Theme Color Bleeding into Web Pages Without Specified Background Color (Transparent) in it's CSS.

### ISSUE THREAD

**Issue by nijin26** [zen-browser/desktop#3147]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![image](https://github.com/user-attachments/assets/721a1c00-a5e9-4083-b1d3-c380f013fd72)

When using the browser, the theme color of the side panels is spreading into the main content area of web pages that do not have a specified background color (or transparent). This issue causes the side panel's theme color to overlay the web page content, leading to a visually inconsistent and potentially distracting user experience.

Sites I am facing the issues are: 
- Google Meet
- Digital Ocean
- Pexels.com ...etc

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.19 (Firefox 132.0.1) (64-bit)

### What platform are you seeing the problem on?

Linux

**Comment by 12th-devs** [comment]
@nijin26 please search on the GitHub before you make a post. This is a common question with an easy fix.

**Comment by nijin26** [comment]
Hi @Anoms12, I had searched this repo with different keywords like "background", "theme color" etc. I didn't find any open issues or discussions related to it.

Could you please share the easy fix ?

EDIT: 
I got the solution from [reddit](https://www.reddit.com/r/zen_browser/comments/1gcsk2i/comment/ltwepen/). 

@Anoms12 Thanks for letting me know, it's a known issue. I have only gone through the github open issues.

**Comment by Bellisario** [comment]
I think this should be made as the default option for everyone...
