### ISSUE TITLE
Disabling Workspaces from Settings causes a gap to occur above tabs

### ISSUE THREAD

**Issue by sid3425** [zen-browser/desktop#3160]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

If the workspaces are disabled in the Linux version(Flatpak), there is a gap in place of the button above the tabs in both compact and normal mode, and Zen mods do not affect this behavior. Following are screenshots of the same:

With Zen mods "Better Active Tab", "Better Unloaded Tabs", and "Super Pins" enabled:
![Screenshot From 2024-11-22 16-05-57](https://github.com/user-attachments/assets/853d0f90-320d-42c3-a75b-da5cd79931b9)

With the above mentioned Zen mods disabled:
![Screenshot From 2024-11-22 16-06-24](https://github.com/user-attachments/assets/575c5b2c-5cd2-4e88-8405-f2e9b312dd56)

Compact mode:
![Screenshot From 2024-11-22 16-06-46](https://github.com/user-attachments/assets/f3a08763-1164-438d-a62f-6878acb7ed4e)

The issue also occurs on other profiles without any modifications whatsoever.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.19

### What platform are you seeing the problem on?

Linux

**Comment by emberrolland** [comment]
I also met this problem. Here is the [issue](https://github.com/zen-browser/desktop/issues/2862)

**Comment by mr-cheffy** [comment]
Should be fixed now
