### ISSUE TITLE
Essentials, bookmarks, and Firfox Sync profile are present in Incognito (Private) Mode

### ISSUE THREAD

**Issue by Smooth-E** [zen-browser/desktop#3168]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When starting a new Private Mode session (with Ctrl+Shift+P or with the "New Private Window" button) a lot of personal stuff is still there:
- All tabs in Essentials are present (though, you are logged out from all your accounts, tabs are loaded clean).
- The bookmarks toolbar is there with all your bookmarks. 
- In the bottom left corner there is your Firefox Sync profile picture. When you click on it, the pop-up says "Default (Alpha)", as it would in a non-incognito window. In the three-dot menu on the top right your Firefox Account is also listed as active. I do not remember, how it is on Firefox, though.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.19

### What platform are you seeing the problem on?

Windows

**Comment by maxtheaxe** [comment]
I'm not a contributor in any capacity, but I'll note that this is how Firefox has always worked, and honestly I'm not sure why it's an issue.

**Comment by imreverse** [comment]
Similar [issue](https://github.com/zen-browser/desktop/issues/2861). @maxtheaxe, I'm not sure about bookmarks or sync, but the pinned tabs (which I guess translates to essentials?) are not visible in Firefox's private window, while Zen loads the essentials and the pinned tabs.

**Comment by shadowash8** [comment]
@Smooth-E, Essentials being in private window has been removed in the twilight build (t.20) but bookmarks being in private window is supposed to be there as a feature as far as I know. It has been the same in firefox too.
