### ISSUE TITLE
Unable to see the list of open tabs with max pinned tabs in small window sizes

### ISSUE THREAD

**Issue by fabioatcorreia** [zen-browser/desktop#3171]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When the window is resized to have a small height (<500px) and the list of pinned tabs reaches the max height, it is not possible to see the list of open tabs.

<img width="869" alt="Screenshot 2024-11-23 at 10 21 16" src="https://github.com/user-attachments/assets/99c0c7aa-ff63-4db3-884b-d6b7023daf4c">

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.19

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by 12th-devs** [comment]
@fabioatcorreia  this is because the size of the pinned tab area is fixed (I think in pixels.) I would recommend opening a feature request to make the pinned tab area a percentage so that it only takes up part of the tab space no matter what.
