### ISSUE TITLE
Scrolling tabs with mouse wheel on Compact mode

### ISSUE THREAD

**Issue by mia-3d** [zen-browser/desktop#3172]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When Compact mode is off, you can go to the left corner of the screen and scroll up and down with no problem, but with Compact mode, scrolling in the corner does nothing, there is a small wall between where you can and can't scroll. I'm not sure if this is a bug or not, but I think this is completely counter-intuitive and should be changed, as you'd want to get to scrolling as convenient as possible (effortless and quick, without even having to look at the corner of the screen when Compact mode is off), and having to move slightly to the right to scroll is annoying. This also applies to trying to middle-click to open a new tab and right-clicking. It would be great to at least have the option of having the same corners in Compact mode as in Non-Compact mode. Thank you.
![Screenshot_2](https://github.com/user-attachments/assets/a93a36e2-da6c-4d24-9175-3cf8aec02a71)![Screenshot_1](https://github.com/user-attachments/assets/0cebf997-4e7b-444a-970e-66ffb219f8d3)

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.19 (Firefox 132.0.1) (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by jasonyang-ee** [comment]
#1126 Same issue basically. There's a boarder all around and causing scroll not working on boarder.

**Comment by mr-cheffy** [comment]
For feature requests, please use https://github.com/zen-browser/desktop/discussions
