### ISSUE TITLE
Workspace cycling should remember last active tab

### ISSUE THREAD

**Issue by CupCakeR** [zen-browser/desktop#318]
### What feature would you like to see?

When cycling through workspaces, the active tab should be the last active tab of that workspace. Currently, it just selects the first one.

### What platform are you seeing the problem on?

Linux

**Comment by enesbala5** [comment]
This is very important. Hope to see it resolved soon.

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/861

 ~ This is an automatic operation to better enhancements requests organization.
