### ISSUE TITLE
Zen Setting lost on update - expand tabs

### ISSUE THREAD

**Issue by MemQu** [zen-browser/desktop#3198]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

It's a minor annoyance - but zen resets expand tabs setting on update. A restart after setting the tab expansion behaviour in Look and Feel fixes it. I cannot say for sure, but I think I've been setting it for the last two updates. 

My setting - Compact mode + Don't expand tabs by default

I have this problem for both Linux (Manjaro) and Windows (Win 10+11)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1 - a.19

### What platform are you seeing the problem on?

Linux, Windows

**Comment by nsetyo** [comment]
In version a.20 the expand tabs settings on look and feel is missing

**Comment by MemQu** [comment]
> In version a.20 the expand tabs settings on look and feel is missing

[https://zen-browser.app/release-notes#1.0.1-a.20](https://zen-browser.app/release-notes#1.0.1-a.20)

They spun it out into a mod?

I see this in breaking changes: 

> Removed collapsible sidebar (mod will be available soon). This is due to the dificulty of maintaining it as we evolve the sidebar

I hope they bring the mod out soon- vertical tabs are ugly when expanded. Compact tabs was what sold me on Zen.

I'll wait for someone more knowledgeable to confirm and close this issue.
