### ISSUE TITLE
Lack of contrast between progress dots during on-boarding

### ISSUE THREAD

**Issue by quissberry** [zen-browser/desktop#32]
![image](https://github.com/zen-browser/desktop/assets/106037630/a1447797-ef2f-4be2-b563-c988557a582b)

During the on-boarding process when you make a profile, there are a set of five dots to indicate what stage you are on (I don't know the UI term for it). 
Even though they use different colors, for me, it's really difficult to tell them apart unless I look very closely. I think there should more contrast, perhaps beyond color and maybe the size of the dots .

EDIT: Personally, I think it is a problem for both dark and light modes.

**Comment by mauro-balades** [comment]
https://github.com/zen-browser/desktop/commit/2268515bb1cf7db879976a92a47e0792fdf55e0f done 👍🏽
