### ISSUE TITLE
Vertical tab bar not accessible after restarting in Compact Mode

### ISSUE THREAD

**Issue by RobertoRG900** [zen-browser/desktop#320]
### What happened?

I've encountered a bug in Zen Browser related to the Compact Mode and vertical tab bar functionality. Here are the details:

**Steps to Reproduce:**
1. Enable Compact Mode
2. Enter Full Screen mode
3. Close the browser
4. Reopen the browser

**Current Behavior:**
- The vertical tab bar does not appear when hovering over the left edge of the screen
- If Compact Mode is disabled to force the tab bar to show, it appears but without displaying any open tabs
- The browser is no longer in Full Screen mode upon reopening

**Expected Behavior:**
- The vertical tab bar should be accessible by hovering over the left edge of the screen
- All open tabs should be visible when the tab bar is displayed
- The browser should maintain its Full Screen state when reopened (optional)

**Workaround:**
The issue can be resolved by re-entering Full Screen mode after reopening the browser.

![Captura de pantalla_20240818_233615](https://github.com/user-attachments/assets/4bdfa18b-ad5c-4160-9734-d21ef2a86b8b)

![Captura de pantalla_20240818_233652](https://github.com/user-attachments/assets/f618e0ba-4855-4e48-a9ac-d39247c3dcc3)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.23

### Severity impact

Low

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
Fixed for the next release! 👍🏽
