### ISSUE TITLE
Potential Memory leak in Zen Browser

### ISSUE THREAD

**Issue by RABINGG** [zen-browser/desktop#3209]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

After sometimes from opening zen browser another instance of zen also running parallely. This been found upon trying to check for updates which displays this error.

> Zen Browser is being updated by another instance

Also closing the browser doesn't end the other process. The same update check error displays when multiple profiles are open.

![image](https://github.com/user-attachments/assets/61e55da3-b731-46a1-ab3e-50504bf5d255)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.19 (Firefox 132.0.1) (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by UndercoverNerd5** [comment]
I'm experiencing the same on brand new current gen hardware and on Windows 11 23H2. I have 2 tabs open and using almost 4GB of ram

**Comment by RABINGG** [comment]
@mr-cheff

**Comment by mr-cheffy** [comment]
Please send this to https://bugzilla.mozilla.org/home
