### ISSUE TITLE
'null' showing up on the top address bar

### ISSUE THREAD

**Issue by vraravam** [zen-browser/desktop#3218]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Just noticed that i got a 'null' showing up on the top to the left of the address bar.
Not sure how/when it appeared.
<img width="1127" alt="Screenshot 2024-11-27 at 13 03 09" src="https://github.com/user-attachments/assets/ce31bb05-879c-437f-9522-8462074a617c">

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-t.20 (Firefox 132.0.2) (2024-11-26) (aarch64)

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by gabenasci** [comment]
I have the same bug using the latest twilight version when I disable the URL bar in the sidebar (`zen.view.use-single-toolbar=false` in about:config). Every time I toggle compact mode, the "null" string is duplicated for each toggle.

![image](https://github.com/user-attachments/assets/15150a72-b539-49ec-b0e8-0db6bbfc2dd9)

Issue happens on fresh install with no Zen mods or browser extensions enabled - I'm on zen-specific twilight for Linux using GNOME on Wayland.

1.0.1-t.20 (Firefox 132.0.2) (2024-11-25) (64-bit)

**Comment by different55** [comment]
At least on my install of Zen, I just have one `null` and it seems to have taken place of the ⇄ button that collapses/restores the tab bar. Doesn't seem to be a way to set a keyboard shortcut for that action, so I don't think there's an easy workaround in the mean time.

**Comment by tangowithfoxtrot** [comment]
I also had a single `null` there. As a workaround, I removed the `widget-overflow-fixed-list` in my `browser.uiCustomization.state` userPrefs, rebooted, and it went away.

**Comment by ArchitektApx** [comment]
Same on a.21 see comments in https://github.com/zen-browser/desktop/issues/3237
