### ISSUE TITLE
Zen doesn't seem to respect system theme settings on windows

### ISSUE THREAD

**Issue by bytenekos** [zen-browser/desktop#3220]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

If I switch windows theme from dark to light mode, zen browser doesn't seem to update its theme. This sucks for me because I have an app that auto switches from light theme to dark theme and vice versa and sites don't update their theme thanks to that. I've checked that if I manually select "light theme" in settings it does update sites, but setting it to "auto" just always sets it to dark mode.

![image](https://github.com/user-attachments/assets/c2bfb57d-b99e-4b38-85d1-f963dd815ce8)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.19

### What platform are you seeing the problem on?

Windows

**Comment by bytenekos** [comment]
Sorry I'm blind, there's already an issue open for this 😅

**Comment by MoltenMonster** [comment]
@bytenekos which issue is it?

**Comment by bytenekos** [comment]
#2747 @Oneechan69
