### ISSUE TITLE
Sidebar buttons are bugged

### ISSUE THREAD

**Issue by hsvfan-jan** [zen-browser/desktop#3227]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

<img width="565" alt="Screenshot 2024-11-28 at 00 39 10" src="https://github.com/user-attachments/assets/6330ddce-4eeb-447d-be61-04512f3bd6d4">

They're too far to the right and not clickable anymore as the sidebar vanishes once you move the mouse to their position on the right. Also, the overlay of the URL bar is not intended

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.20

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by lamteteeow** [comment]
I think it might be the URL bar that got bug like mine actually...
![image](https://github.com/user-attachments/assets/9bc617ec-eb60-4380-8a57-4dc168b33337)

**Comment by dagadtwok** [comment]
Can confirm it also happens on a21 too.

**Comment by mr-cheffy** [comment]
Should be fixed now 👍🏽 

Please let me know if it's not the case
