### ISSUE TITLE
Imediet crash on Gnome (seems to be a wayland issue)

### ISSUE THREAD

**Issue by yotamguttman** [zen-browser/desktop#324]
### What happened?

Zen Browser crashes usually a 1-2 mins after launch. I tested the browser first on Windows and that was not an issue. On Gnome, it crashes after carrying out 1-2 actions, like opening another tab or searching for something and then pressing to open the link. it's impossible to use it at the moment on Linux.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.23 (64-bit)

### Severity impact

High

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
Crash Annotation GraphicsCriticalError: |[0][GFX1-]: Wayland protocol error: wp_linux_drm_syncobj_surface_v1@56: error 4: No Acquire point provided
 (t=8.83518) [GFX1-]: Wayland protocol error: wp_linux_drm_syncobj_surface_v1@56: error 4: No Acquire point provided
```

**Comment by mauro-balades** [comment]
This has been before, please checkout https://github.com/zen-browser/desktop/issues/77. It will be fixed in firefox 130
