### ISSUE TITLE
URL bar still appears in Compact Mode after all elements have been hidden

### ISSUE THREAD

**Issue by abhigyantrips** [zen-browser/desktop#3240]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

i used the Customize Toolbar option in Compact Mode to try and remove the user icon on the top-left. since then, i see the search bar as a floating element, even after everything else is hidden (see image).

![image](https://github.com/user-attachments/assets/b29e52d1-064f-4d2c-a61d-48a5d9a64e3c)

it still shows up normally when i hover over the top area.

![image](https://github.com/user-attachments/assets/44f24aef-7dd5-44ee-9bec-4ece8f0e7ce7)

but yeah even after i restored defaults under Customize Toolbar, the search bar is still there.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.20 (Firefox 133.0) (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by PoXel6** [comment]
> I found a related issue that might be helpful:

wasn't helpful.

I have the same exact issue
The search bar is just there.
![image](https://github.com/user-attachments/assets/446f42f9-f529-496a-9cb9-4a21575db1df)

**Comment by ghost** [comment]
bump, same issue

**Comment by accrrsd** [comment]
Same, after recent update, before it was OK

**Comment by abhigyantrips** [comment]
as mentioned in #3244, the issue is reproducible on macOS as well

**Comment by madjsmail** [comment]
Same, after recent update

**Comment by Ak22836685** [comment]
facing same issue any help yet?

**Comment by TheGhostHybrid** [comment]
Same issue. AppImage on Linux. The issue was not present when first setting up the browser, but after restarting to apply some changes, the problem emerged.

**Comment by RayZ3R0** [comment]
Version a20 is filled with some bugs, a21 is going to be released soon, please try that when it comes out. For now, I would suggest downgrading to a19 until a21 comes out, which should be very soon.

**Comment by lamteteeow** [comment]
Duplicate as bug #3229

**Comment by abhigyantrips** [comment]
upgraded to a21 and the URL isn't overlapping with the page anymore, but now the URL bar is peeking from the top at all times?

![image](https://github.com/user-attachments/assets/7d566ed9-63df-4f96-b7f4-8bfcb9373ead)

**Comment by astudentinearth** [comment]
@abhigyantrips I'm having the same issue. Manually updating fixed the overlapping but it's slightly visible, a few pixels are left behind.

**Comment by cswimr** [comment]
Can confirm the same peeking issue on `.a21`.
![image](https://github.com/user-attachments/assets/49efccfa-b978-478e-8d42-8d901befd18e)

**Comment by abhigyantrips** [comment]
also if i try to open the URL bar using `Ctrl+L` i can't see the actual text i'm typing.

https://github.com/user-attachments/assets/b1914e88-e59b-41bb-94e1-eac342b08d48

**Comment by abhigyantrips** [comment]
aaand this is fixed on my end in a.22. closing the issue now 👍🏽

**Comment by ghost** [comment]
> upgraded to a21 and the URL isn't overlapping with the page anymore, but now the URL bar is peeking from the top at all times?
> 
> ![image](https://private-user-images.githubusercontent.com/28886624/390775862-7d566ed9-63df-4f96-b7f4-8bfcb9373ead.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1MDcwNTYsIm5iZiI6MTczMzUwNjc1NiwicGF0aCI6Ii8yODg4NjYyNC8zOTA3NzU4NjItN2Q1NjZlZDktNjNkZi00Zjk2LWI3ZjQtOGJmY2I5MzczZWFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDE3MzkxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5OTYwNjk2OWVkNzJmNjZhMjQxYzkzNGY2YWZmMjUxZWY4YjUxOTBkMjNkODE3MWZiYTNlMTQ5MWViMjYyNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9bGrYuEp_V5tFAd-3G0IDZ4olzCK-p0jiZ8Wf1XxMwY)

How did you get a custom wallpaper for new tabs on zen browser?
