### ISSUE TITLE
Google Docs letters gibberish

### ISSUE THREAD

**Issue by ihatepolo** [zen-browser/desktop#3241]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Opened shared google docs file, everything worked fine. and then i updated zen browser to 1.0.1-a.20, opened the same google docs file, words turned to glitched letters. 

![Screenshot 2024-11-28 125623](https://github.com/user-attachments/assets/d1502bd2-32a5-4cc5-9bd4-cfcf4793fec1)

tried to recreate said bug.
> uninstalled zen browser and deleted cache
> installed zen browser prior version 1.0.1-a.20
> opened same google docs file, worked fine. flawless matter of fact
> updated browser to 1.0.1-a.20
> again, opened google docs file, same issue appeared. 

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.20

### What platform are you seeing the problem on?

Windows

**Comment by RayZ3R0** [comment]
Version a20 is filled with some bugs, a21 is going to be released soon, please try that when it comes out. For now, I would suggest downgrading to a19 until a21 comes out, which should be very soon.

**Comment by mr-cheffy** [comment]
Hi! Try disabling hardware acceleration and let us know if the problem persists, if not, please close the issue
