### ISSUE TITLE
Search bar being cutoff

### ISSUE THREAD

**Issue by keplerHaloxx** [zen-browser/desktop#3243]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![image](https://github.com/user-attachments/assets/c1a9420a-0d08-4943-807f-7bd7dff06f86)
The search bar is being cutoff and I cannot see any of the results. I turned off all mods and it still happens

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.20

### What platform are you seeing the problem on?

Windows

**Comment by TaQuangKhoi** [comment]
Same issue with `1.0.1-a.20`.

Back to 1.0.1-a.19 for continue to browsing

**Comment by keplerHaloxx** [comment]
> Same issue with `1.0.1-a.20`.
> 
> Back to 1.0.1-a.19 for continue to browsing

How can I rollback to that version?

**Comment by RayZ3R0** [comment]
Version a20 is filled with some bugs, a21 is going to be released soon, please try that when it comes out. For now, I would suggest downgrading to a19 until a21 comes out, which should be very soon.

> How can I rollback to that version?

https://github.com/zen-browser/desktop/releases/tag/1.0.1-a.19

**Comment by trlef19** [comment]
happens to `1.0.1-a.21` too

**Comment by RayZ3R0** [comment]
a.22 is releasing soon, it will fix this
