### ISSUE TITLE
Appearance on macOS Looks Strange

### ISSUE THREAD

**Issue by ghost** [zen-browser/desktop#3244]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Hi there. First, please allow me to express my congratulations on Zen soon entering its beta phase. I have been using this browser consistently, and it truly is a masterpiece.

Here's the issue: After upgrading to version 20, under compact mode, the appearance of the sidebar and the address bar looks odd; they are overlapping:

<img width="644" alt="图片" src="https://github.com/user-attachments/assets/402b3566-fa15-46e2-8ed4-b6556a990fde">

The classic macOS red, yellow, and green window buttons have also disappeared.

Is there any solution to this issue? Thank you!

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.20

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by kawaiier** [comment]
I have the same issue. It doesn’t overlap the sidebar, but it doesn’t autohide and appears transparent
![CleanShot 2024-11-28 at 11 17 09@2x](https://github.com/user-attachments/assets/44848b74-d120-4ca7-ac5e-ec6baa2076b4)

**Comment by BernhardRode** [comment]
<img width="1001" alt="Screenshot 2024-11-28 at 08 22 11" src="https://github.com/user-attachments/assets/a99535a3-e1fc-4952-85be-16d8586ccbbb">

When in Fullscreen and i go to the top with the mouse to reveal the menu, i get the same behavior.

**Comment by gautierlabarre** [comment]
I have the same issue on macos, same version. Also I used to have the left menu with only icons (taking less space on the screen) but now it opens the whole menu.
this button disappeared : 
<img width="72" alt="image" src="https://github.com/user-attachments/assets/7a715b34-2006-41b4-b1a1-15e14102bb4f">


I deactivated all zen mods to be sure.

Downgraded to a19 until it's fixed

**Comment by DanRioDev** [comment]
Can affirm this happens on Linux too
![image](https://github.com/user-attachments/assets/7886791c-0383-4744-80c6-c26e36ed5afd)

**Comment by RayZ3R0** [comment]
Version a20 is filled with some bugs, a21 is going to be released soon, please try that when it comes out. For now, I would suggest downgrading to a19 until a21 comes out, which should be very soon.

**Comment by patrick330602** [comment]
Just upgraded to a21 and the issue still exists:
<img width="293" alt="Screenshot 2024-11-28 at 17 31 50" src="https://github.com/user-attachments/assets/e88b6a11-aa92-413d-9dbe-70e585e7d747">

**Comment by patrick330602** [comment]
Also, if I enabled compact mode with hide both, it completely messed up the UI:
<img width="288" alt="Screenshot 2024-11-28 at 17 33 37" src="https://github.com/user-attachments/assets/3b2aaad1-a2b9-4c71-9e55-08e7f162c081">

**Comment by RayZ3R0** [comment]
yep, that has been looked into, a22 is releasing soon. Should fix everything
