### ISSUE TITLE
Cannot move windows by clicking on empty space

### ISSUE THREAD

**Issue by neonfuz** [zen-browser/desktop#3245]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Ever since updating to a.20 I cannot move windows by clicking on empty space in the top bar and dragging.

By empty space I mean for example, the space between the refresh button and the address bar.

This behavior worked on a.19 and earlier on non popup windows.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.20

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by RayZ3R0** [comment]
Version a20 is filled with some critical bugs due to upgrading firefox version to 133. a21 is going to be released soon, please try that when it comes out. Closing this for now, **do reopen** if this still happens in a21. For now, I would suggest downgrading to a19 until a21 comes out, which should be very soon.

**Comment by neonfuz** [comment]
@RayZ3R0
It is still happening on a21. I don't know if I have permissions to re-open this issue, but I could re-file it as a new issue if that works?

Also I noticed, it's only the left side I cannot drag from. Pretty much the entire empty area in this screenshot:
![Screenshot 2024-11-28 at 2 37 08 PM](https://github.com/user-attachments/assets/36c219da-1028-43b8-bdea-72745ab579b9)

The right side still works fine

**Comment by RayZ3R0** [comment]
> @RayZ3R0 It is still happening on a21. I don't know if I have permissions to re-open this issue, but I could re-file it as a new issue if that works?
> 
> Also I noticed, it's only the left side I cannot drag from. Pretty much the entire empty area in this screenshot: ![Screenshot 2024-11-28 at 2 37 08 PM](https://private-user-images.githubusercontent.com/2590830/390901816-36c219da-1028-43b8-bdea-72745ab579b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4MjgzMzUsIm5iZiI6MTczMjgyODAzNSwicGF0aCI6Ii8yNTkwODMwLzM5MDkwMTgxNi0zNmMyMTlkYS0xMDI4LTQzYjgtYmRlYS03Mjc0NWFiNTc5YjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjhUMjEwNzE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWFjZjllYjk5OGY1ZDQ2ZTc3ZTkyY2JiZTVmYzQ2OGJmMzZhOGVjN2ZhOGVlMjgyNWQxNzQ3OWE3ZGQ3NjhkMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.997-67_oRf3s4skMEhhAaKWoXU8Er6Xn8f1-alZuS20)
> 
> The right side still works fine

Update to a22, sorry for the inconvenience, but a22 should fix everything
