### ISSUE TITLE
Switched labels on settings

### ISSUE THREAD

**Issue by DanRioDev** [zen-browser/desktop#3248]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Noticed since a.19 at the settings screen the compact label and thumbs are switched from what they mean:

![image](https://github.com/user-attachments/assets/6e6da712-3f5e-43d2-95f5-65671b3d55ae)

![image](https://github.com/user-attachments/assets/aa466278-73b9-4e83-87b4-4a385c531b07)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.19

### What platform are you seeing the problem on?

Linux

**Comment by RayZ3R0** [comment]
That is intentional, Hide tab bar means its hiding the tab bar, so only top bar is visible. Hence why the top bar is the one shown in the image since tab bar is hidden. Same for the 2nd one. This has been like this for a long time, not just a19
