### ISSUE TITLE
null on the left side of the window control on Mac

### ISSUE THREAD

**Issue by patrick330602** [zen-browser/desktop#3249]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I upgraded to build 21 from build 20, the original null is gone but now null appears on the left side of the window control that cannot be removed
<img width="270" alt="Screenshot 2024-11-28 at 17 22 36" src="https://github.com/user-attachments/assets/839bf5c0-70f3-40d6-9297-903384c037de">

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.21

### What platform are you seeing the problem on?

macOS - Intel

**Comment by ArchitektApx** [comment]
Duplicate of https://github.com/zen-browser/desktop/issues/3237 & https://github.com/zen-browser/desktop/issues/3218

**Comment by RomainLanz** [comment]
> Duplicate of #3237 & #3218

That's not a duplicate.

The `null` shown on those issues is gone, there is a new one in this build.

**Comment by dfrnoch** [comment]
Well, maybe its time to revert back to a19

![Screenshot 2024-11-28 at 11 14 53](https://github.com/user-attachments/assets/86fdd653-a1a4-4f56-86b4-bd40e3c2c4e4)

**Comment by adokce** [comment]
i noticed this after i attempted to add a new profile. also, i think a adding new profile messed up dragging the browser window around the left side of the address bar. i can drag by holding on to sidebar or the right side of the address bar.
issue still there after removing other profiles. - maybe the bug was there anyway and i just didnt notice it before.

version: 1.01-a.21 (Firefox 133.0) (aarch64) - macOS Sonoma 14.7
...
Update: 1.0.1-a.22 (Firefox 132.0.1) fixed the issue

**Comment by Frederic-C** [comment]
Same problem, but didn't add any new profile.
I also have the problem of not being able to move the window, only a little zone of the top bar on the right can be dragged to move the window. It wasn't a bug on previous version.

1.0.1-a.21 (Firefox 133.0) (aarch64) - macOS Sequoia 15.1.1 (24B91)

**Comment by SangeloDev** [comment]
I've got the same issue, but when I try to restore the default toolbar layout. Everytime I do that, I get a few additional `null`s added to my toolbar.

![image](https://github.com/user-attachments/assets/01bf710c-3825-4c1f-8e00-24f0bd885543)

1.0.1-a.21 (Firefox 133.0) (aarch64) - macOS Sonoma 14.2 (23C64)

**Comment by LinaJesus** [comment]
The same happens when changing the compact view:
https://github.com/user-attachments/assets/0885993b-a19f-4c73-8b4a-ae6512ccc753

1.0.1-a.21 (Firefox 133.0) (aarch64) - macOS Sequoia 15.1 (24B83)

**Comment by RomainLanz** [comment]
Last update fixed the issue.

**Comment by liujip0** [comment]
I'm on version 1.0.1-t.22 (Firefox 133.0) (2024-11-28) (aarch64), and I still have the null problem on startup. 
![Screenshot 2024-11-28 at 19 56 32](https://github.com/user-attachments/assets/068713de-2fa1-49c8-8db5-1e9cf65fff1b)
I get more and more nulls when I touch any of the settings in Settings > Look and Feel > Theme Settings.
