### ISSUE TITLE
Tabs get thinner horizontally when closing many of them in succession

### ISSUE THREAD

**Issue by thepick** [zen-browser/desktop#325]
### What happened?

I had about 50 tabs open and started closing them rapidly in succession. With each click on the close buttons (x), the remaining open tabs to get thinner and thinner horizontally. Before long, it was just the icons showing despite the width of the original tab space staying consistent (see screenshot):
<img width="126" alt="Screenshot_7" src="https://github.com/user-attachments/assets/af0ab8b4-da7b-4930-84a3-4c079b3bfb4b">

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.23 (64-bit)

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
We know about this bug, I need to do some cleaning. It's a duplicate ✌️
