### ISSUE TITLE
Sidebar Problem

### ISSUE THREAD

**Issue by AhmetG-0033** [zen-browser/desktop#3250]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![sidebar](https://github.com/user-attachments/assets/3ab31f41-876c-4874-86ce-1dec1fda56c2)

In the latest update (a.20), there is no arrow icon to minimize the sidebar so i have to use extended sidebars with labels of all tabs which occupies much space on screen. I searched on settings much and i cant find another way to minimize it. Even if there is still a way to do it, this icon was convenience and way better

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.19

### What platform are you seeing the problem on?

Windows

**Comment by elementh** [comment]
So sad to see the feature being removed of core :(

**Comment by MemQu** [comment]
#3198 

(Related issue)

**Comment by AhmetG-0033** [comment]
> #3198
> 
> (Related issue)

Yes i saw they removed it but its really big mistake it was one of the best zen browser features and its awful to use the browser 7/24 with huge sidebar on the screen

**Comment by tangowithfoxtrot** [comment]
The removal of the minimizable sidebar is a huge bummer. The always-expanded sidebar looks horrible and wastes _more_ space than horizontal tabs, which negates the reason I preferred Zen.

**Comment by AhmetG-0033** [comment]
> The removal of the minimizable sidebar is a huge bummer. The always-expanded sidebar looks horrible and wastes _more_ space than horizontal tabs, which negates the reason I preferred Zen.

I think the developers will consider this because probably the most of user think like that included me

**Comment by Video-Nomad** [comment]
> > The removal of the minimizable sidebar is a huge bummer. The always-expanded sidebar looks horrible and wastes _more_ space than horizontal tabs, which negates the reason I preferred Zen.
> 
> I think the developers will consider this because probably the most of user think like that included me

I sure hope so. Sitting on an old browser version is not an option for a long time so I will have to switch browsers again...

**Comment by paru-de** [comment]
Adding my voice to this issue, I too miss this feature. For now I simply hide the sidebar but that's inconvenient when you want to switch back and forth quickly.

I could live with it being a mod but then you'd probably want to feature its existence somewhere prominent as this seems to be a very obvious setting missing from the base version.

**Comment by UtkuGARIP** [comment]
I use the translation tool when reading comments, I think it is a mistranslation. It says they _removed the ability to hide the side panel_. **If it's real, I'm off.** _So this browser is also baiting Google._

**Comment by matthewblott** [comment]
One of the good features was having two windows side by side but when too much real estate is taken up by the sidebar this is less feasible. Bad move.

**Comment by kuqquk** [comment]
In the release note for 1.0.1-a.20, it says 
> Removed collapsible sidebar (mod will be available soon). This is due to the dificulty of maintaining it as we evolve the sidebar

Also, they misspelled in 
> We are really *exited* for what's about to come

I really like Zen browser, hope this is temporary and everything will get back to 'normal' later. 🤞

**Comment by Video-Nomad** [comment]
> In the release note for 1.0.1-a.20, it says
> 
> > Removed collapsible sidebar (mod will be available soon). This is due to the dificulty of maintaining it as we evolve the sidebar
> 
> Also, they misspelled in
> 
> > We are really _exited_ for what's about to come
> 
> I really like Zen browser, hope this is temporary and everything will get back to 'normal' later. 🤞

My only question is - how is supporting a separate mod will be easier than having it as a core feature? The answer is - it won't be easier, so the mod support will most likely be very limited/unreliable and outdated when new sidebar features come out. So bugs, glitches and so on while we wait for the mod to be updated...

**Comment by gautierlabarre** [comment]
Yes i really hope the devs see that the feature is more used than they anticipated and decide to put back the option without a mod which will work for a few time and then be deprecated. 
This feature is one of the strength of zen (from my point of view) and i'm sincerely not sure i'll still be using zen if it's removed

**Comment by itsTyrion** [comment]
I've had the side bar auto collapse/expand on hover. one of THE zen features for me, only seen that in Edge previously. vertical tabs that expand on click can be had on FF nightly too

**Comment by shaduwu-code** [comment]
It was supposed to be improved, not removed

**Comment by CraftingDragon007** [comment]
I just switched to Zen browser, because I thought I'd get the same nice collapsible sidebar just like in Microsoft Edge whilst moving away from Microsoft Spyware. And now this. Why would they do this? It doesn't make any sense. If you have the bar expanded all the time, I could just as well use normal Firefox. I also don't see how a mod is gonna be a good enough replacement for a core feature.

**Comment by gautierlabarre** [comment]
Good news, apparently the devs are rollbacking this change here https://github.com/zen-browser/desktop/commit/66254e79d37327fb8ca95ff2f32b10e20da0ad7a

**Comment by MasterMong** [comment]
For me it like Dev remove my reason to use Zen browser.

**Comment by olig89** [comment]
Pretty crazy to remove it and say you'll add it as a mod "later".

If you're definitely going to remove it, at least have the mod ready to go and (potentially) guide users to it.

Any idea when the rollback will be implemented for non-twilight? Back to Floorp for now I guess...

**Comment by AhmetG-0033** [comment]
> Good news, apparently the devs are rollbacking this change here https://github.com/zen-browser/desktop/commit/66254e79d37327fb8ca95ff2f32b10e20da0ad7a

Oh finally the right decision🎉

**Comment by mateuszkozakiewicz** [comment]
The sidebar is not the tab bar as far as I understand, what was removed was the sidebar where you could open a smaller browser window like a split view, removal of this seems to be a mistake?

**Comment by paru-de** [comment]
Just updated to a22, thank you so much for rolling this change back so quickly, it's appreciated!

**Comment by kenny-kvibe** [comment]
thank you for the rollback on a22, I disabled upgrades just because of a20

**Comment by CraftingDragon007** [comment]
did they really remove it again in now beta

**Comment by gautierlabarre** [comment]
I'm using the beta release and it still works as expected for me.

**Comment by CraftingDragon007** [comment]
I'm using version 1.0.2-b.0 (64-bit) and can't find the settings option to re-enable the expand on hover sidebar

**Comment by CraftingDragon007** [comment]
It's still not fixed in 1.0.2-b.1 (64-bit). Am I the only one who's annoyed by this?

**Comment by kenny-kvibe** [comment]
As long as the tabs are collapsed/collapsable it's fine unlike the removal in 1.0.1-a20, glad they're back.

But a quick keydown-event to toggle-collapse the sidebar could be very useful, I think it can have the same logic as mousedown-event logic on the switch-button ![image](https://github.com/user-attachments/assets/ab29ae77-308a-46c1-84ee-a66097a7c587) excluding any hover/click transitions.

Anyway I just came to check if tabs are collapsable again, updated immediately, thanks :)

**Comment by CraftingDragon007** [comment]
> As long as the tabs are collapsed/collapsable it's fine unlike the removal in 1.0.1-a20, glad they're back.
> 
> But a quick keydown-event to toggle-collapse the sidebar could be very useful, I think it can have the same logic as mousedown-event logic on the switch-button ![image](https://github.com/user-attachments/assets/ab29ae77-308a-46c1-84ee-a66097a7c587) excluding any hover/click transitions.
> 
> Anyway I just came to check if tabs are collapsable again, updated immediately, thanks :)

Which version are you using? And can the tabs really expand on hover?

**Comment by olig89** [comment]
For what it's worth, the expand-on-hover tab functionality I want (which was previously removed without a viable replacement) is now covered by this [ZenMod](https://zen-browser.app/mods/bd92a9a0-1c00-4187-a66e-94c389fa5a59/).

**Comment by CraftingDragon007** [comment]
In a related issue the maintainer said that it would be to hard to support this functionality, meaning it won't be added back: https://github.com/zen-browser/desktop/issues/3522
