### ISSUE TITLE
Please back collapsable side bar !!!!!

### ISSUE THREAD

**Issue by egmtncakgn** [zen-browser/desktop#3256]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I unknowingly updated my browser with the pop up notification that came today I regret it so much please fix the side bar

![Ekran görüntüsü 2024-11-28 134411](https://github.com/user-attachments/assets/58d4173c-14c1-4b35-a8e2-524e828fafbc)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.21

### What platform are you seeing the problem on?

Windows

**Comment by gautierlabarre** [comment]
a lot of issues are related to the change made on a20, unfortunately you'll have to downgrade and pray for the devs to put back the feature (and not a mod please)

**Comment by RayZ3R0** [comment]
It will be added back permanently in the next update, won't be removed (At least that's what the main dev said)

**Comment by Video-Nomad** [comment]
> It will be added back permanently in the next update, won't be removed (At least that's what the main dev said)

66254e79d37327fb8ca95ff2f32b10e20da0ad7a Yep, seems to be the case. Good news!

**Comment by mertkont** [comment]
Oh, it is good to hear that I am not only one who have this issue! Thank you! I am following that topic.

**Comment by cimarronline** [comment]
Really glad to hear it's coming back! Thanks to the devs for being so responsive to feedback!

**Comment by eleochess** [comment]
Yesterday, I installed this browser and it was the goat. Now it's not anymore because of this issue. I'm glad to read that the collapse side bar is going to be back soon.

**Comment by Ritwik-Sh** [comment]
Its fixed in the latest update

**Comment by eleochess** [comment]
Now it's fixed. Thank you!

**Comment by mr-cheffy** [comment]
Done. It will stay on beta versions too!
