### ISSUE TITLE
New update broke Everything

### ISSUE THREAD

**Issue by ocean-mars** [zen-browser/desktop#3257]
### Captchas

- [x] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.

### What happened?

Even after removing all mods, it looks like this, even the window buttons are messed up
![Screenshot 2024-11-28 at 5 04 34 PM](https://github.com/user-attachments/assets/874b4dac-901b-4854-a339-cb953e12518f)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.21 

### What platform are you seeing the problem on?

macOS - Intel

**Comment by AhmetG-0033** [comment]
New update really sucks. Many bugs and removing of collapsable bars.. I still use old version and I don't think I'll be updating for a while

**Comment by Couleur-Share** [comment]
> New update really sucks. Many bugs and removing of collapsable bars.. I still use old version and I don't think I'll be updating for a while

Me too, it's really bad

**Comment by junguler** [comment]
the browser prompts me to download the new update but when i look at the actions page it hasn't finished building yet, this is a weird bug

as for not having access to collaps-able bars, didn't the update notes mention a new zen mod is being made available soon that gives back that functionality, just wait until that's out and then update

i too prefer the tab bar collapsed and i completely disable side bars and other stuff and make the browser as minimal as possible

i like to see an option to have the tab bar at the top and bottom of the browser too, i know floorp already has this but i don't like how that browser looks and prefer the overall look and feel of zen way better

**Comment by nodgear** [comment]
> the browser prompts me to download the new update but when i look at the actions page it hasn't finished building yet, this is a weird bug
> 
> as for not having access to collaps-able bars, didn't the update notes mention a new zen mod is being made available soon that gives back that functionality, just wait until that's out and then update
> 
> i too prefer the tab bar collapsed and i completely disable side bars and other stuff and make the browser as minimal as possible
> 
> i like to see an option to have the tab bar at the top and bottom of the browser too, i know floorp already has this but i don't like how that browser looks and prefer the overall look and feel of zen way better

it's not very smart to first remove the feature and then promise for a mod soon(tm)

**Comment by Morette** [comment]
don't know if this is showing for you, but for me after the update it is showing a null and I can't move the window freely
I'm using MACOS Sequoia

![image](https://github.com/user-attachments/assets/2d3e2acc-7d5f-4aad-a191-baf82bb40fb4)

**Comment by junguler** [comment]
> it's not very smart to first remove the feature and then promise for a mod soon(tm)

oh i agree and i said as much in my comment, not everyone reads the release notes tho so i wanted to let them know the same functionality is coming back

**Comment by brudermusscode** [comment]
I have downloaded this browser because of a Video I saw and loved the style of the collapsed sidebar. Why would you remove it in the first place, it's so good to have 😢

**Comment by ocean-mars** [comment]
> New update really sucks. Many bugs and removing of collapsable bars.. I still use old version and I don't think I'll be updating for a while

I've also downgraded to a19

**Comment by BrunoG1987** [comment]
Version a22 out with collapsed sidebar option back in
