### ISSUE TITLE
[Bug] Viewport renders over the URL menu?

### ISSUE THREAD

**Issue by antikovt** [zen-browser/desktop#3261]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I'm not sure how this could've been missed, and I'm not sure what setting I have that enables this, but the viewport renders over the url menu when the url bar is focused, making the browser barely usable. Mods are disabled.

I'll update if I find what causes this.

![image](https://github.com/user-attachments/assets/00987455-29a0-45fb-9911-34153fb376c7)
This is insane

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.20 (20241128040244)

### What platform are you seeing the problem on?

Windows

**Comment by wasawin** [comment]
I just updated and the url has the same problem. Try restarting.
Can you try restarting normally in about:profiles

**Comment by antikovt** [comment]
> Try restarting.
> Can you try restarting normally in about:profiles 

Same result unfortunately

**Comment by nihalsheikh** [comment]
facing the same issue, URL Bar is blur and appears on every page, even when I have set it to expand on hover mode(from browser settings not zen mod), and why is the sidebar in expand mode by default? also why is expand sidebar button missing?

![Screenshot)](https://github.com/user-attachments/assets/b98c61a1-71ac-4359-aeb5-7b175fabe6fc)

**Comment by 8BiToe** [comment]
I'm having this issue too

**Comment by antikovt** [comment]
Solved, I believe
