### ISSUE TITLE
Compact mode is not compact

### ISSUE THREAD

**Issue by alox92** [zen-browser/desktop#3264]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

hi , compact mode is not compact at all to wide and if i want to access to a button in the page that is near to it it activates by itself.

<img width="1441" alt="SCR-20241128-mhqo" src="https://github.com/user-attachments/assets/33691fc1-1cb6-4b31-9e8e-691e757afa4f">

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.21 (Firefox 133.0) (aarch64)

### What platform are you seeing the problem on?

macOS - aarch64

### Relevant log output

```shell
sry i don't know how to do that
```

**Comment by neurokitti** [comment]
this isnt exactly a bug. i mean yes you are right if you move close to the edge it does activate compact mode. but thats just how compact mode works. ill see if a delay option can be added though.
also when you say "compact mode is not compact at all to wide' what do you mean exactly?
