### ISSUE TITLE
I cant collapse my sidebar

### ISSUE THREAD

**Issue by Daniel10013** [zen-browser/desktop#3275]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Ilike to use the sidebar in the mode that i only see the page icon and not the title, but after the last update, i can't find the button to collapse the tabs letting only the icon
<img width="37" alt="361339523-b7346ade-a200-4622-924e-eda7cdca9a23" src="https://github.com/user-attachments/assets/b33e4f55-79fd-41a5-90e7-dedae812d577">
I cant find this button

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.21 

### What platform are you seeing the problem on?

Windows

**Comment by Luigi31415** [comment]
Got this as well 👍 
I got `null` in place of the icon now
Thanks for reporting

<img width="1193" alt="Screenshot 2024-11-28 at 9 26 32 pm" src="https://github.com/user-attachments/assets/929cc5df-e15b-4e83-b669-0826ea21d3d8">

**Comment by zmepe** [comment]
the new updates breaks it they said it in the changelog

**Comment by Jakllp** [comment]
![image](https://github.com/user-attachments/assets/701e6392-2ecd-46a8-8326-258edb138cdd)
It was removed in 20.
You can update to 22 which is basically .19

**Comment by Daniel10013** [comment]
Somehow i restarted to update on my settings, and it worked, thanks everyone :D
