### ISSUE TITLE
Tab expanding on hover doesn't work after disabling compact mode

### ISSUE THREAD

**Issue by Akagir** [zen-browser/desktop#3277]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![image](https://github.com/user-attachments/assets/2f8b8079-acda-46f2-ba7f-15d877298b0b)
After selecting "Expand Tabs on Hover", even once if i enable and disable back compact mode,the sidebar doesn't expands on hover anymore...

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.22

### What platform are you seeing the problem on?

Windows

**Comment by mr-cheffy** [comment]
It has been removed
