### ISSUE TITLE
Popup window not completely displaying in Zen, but fully displays in Fire Fox

### ISSUE THREAD

**Issue by ghost** [zen-browser/desktop#3281]
### Captchas

- [X] I have read the instructions.
- [ ] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

1. Went to Find A Grave website https://www.findagrave.com/memorial/39776109/crittenden
2. Then selected the Save To button
3. I was expecting to see a popup with a header bar and under it a selection of places where the content could be saved.  However, in Zen I only see the popup header bar and nothing else.  See image Using-Zen-Browser.png attached  
<img width="1217" alt="Using-Zen-Browser" src="https://github.com/user-attachments/assets/8217db22-f1fc-40a4-9c14-75cace067b1d">

4. When using Fire Fox the popup displays correctly.  See image Using-Fire-Fox-browser.png attached.

<img width="1280" alt="Using-FireFox-Browser" src="https://github.com/user-attachments/assets/40092c66-0b13-466a-9d1b-e38894f0c586">

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.22 (Firefox 132.0.1) (aarch64)

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by ghost** [comment]
***@***.*** <https://github.com/dosu>.*

*Does not finding any similiar threads have a impact on how the Bug Report
will be resolved?*

*Thanks*


Cliff Gittens
Surrey, BC, Canada

**Comment by nsetyo** [comment]
![image](https://github.com/user-attachments/assets/75aa1ef3-b83c-44a1-a0e1-398c87a6a688)

Mine is working fine

**Comment by ghost** [comment]
Setyo, @dosu

I reinstalled Zen and that resolved the problem I was having.  I guess I
should have tried the reinstall before filing the bug report, I will know
better next time.

Thank you for your assistance.

Cliff Gittens
Surrey, BC, Canada
