### ISSUE TITLE
Sidebar issue

### ISSUE THREAD

**Issue by Xhenzu** [zen-browser/desktop#3288]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The elements of the sidebar is really broken..sumo are covered within others elemnts ESPECIALLY AT THE BELOW..sumtimes pinned tabs get unpinned as well.
Also when i hover over a tab the close cross icon is there, but when hover over the cross icon another small cross appears to close which makes it ugly fr.

ill attach a screenshot
![image](https://github.com/user-attachments/assets/d2019f3b-fdf4-4d15-9b4b-c2a4de5dc658)
![image](https://github.com/user-attachments/assets/5dae89fc-0f47-4cba-b852-6e97e04ec42e)
![image](https://github.com/user-attachments/assets/ee79886c-c711-400d-b3f1-db8ad08ecf8f)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1.a.20

### What platform are you seeing the problem on?

Windows

**Comment by myrrhkhan** [comment]
experiencing the same on macOS as well, shows "null" on the top left corner
<img width="730" alt="image" src="https://github.com/user-attachments/assets/cc26ce39-a908-4fb7-9241-542104c443bd">

I typically use compact(?) mode where I only see the tab icons. I had that set, and after the update, I can't revert back to compact mode.

(I'm unsure if it's proper etiquette to share evidence of a seemingly similar issue in the same thread, or if I should've made my own issue or something, so let me know this is something I should change for future reference, thanks!)

**Comment by mtlaso** [comment]
Same as @myrrhkhan

**Comment by mathiesschou** [comment]
+1 to @myrrhkhan 
<img width="586" alt="Screenshot 2024-11-29 at 09 34 15" src="https://github.com/user-attachments/assets/4b2e1615-87fc-4e02-bc80-ec6cbb13443e">

**Comment by Rian-yes** [comment]
> ### Captchas
> 
>     * [x]  I have read the instructions.
> 
>     * [x]  I have searched existing issues and avoided creating duplicates.
> 
>     * [x]  I am not filing an enhancement request.
> 
> 
> ### What happened?
> 
> The elements of the sidebar is really broken..sumo are covered within others elemnts ESPECIALLY AT THE BELOW..sumtimes pinned tabs get unpinned as well. Also when i hover over a tab the close cross icon is there, but when hover over the cross icon another small cross appears to close which makes it ugly fr.
> 
> ill attach a screenshot ![image](https://private-user-images.githubusercontent.com/147889378/390943962-d2019f3b-fdf4-4d15-9b4b-c2a4de5dc658.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4NzA3NzEsIm5iZiI6MTczMjg3MDQ3MSwicGF0aCI6Ii8xNDc4ODkzNzgvMzkwOTQzOTYyLWQyMDE5ZjNiLWZkZjQtNGQxNS05YjRiLWMyYTRkZTVkYzY1OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOVQwODU0MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZWNjY2M5YzRkY2UwZmVhMTUyMjg5MmJhMWI5NGY5ZGE5ZTFmMDk5MDRkNTk1MWQ2YjljNGRlNTQyMGMyY2I3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Idl-FO8DkWhx6AqGA2UUzHKrLS4mv2X1nEr2zvQ23rM) ![image](https://private-user-images.githubusercontent.com/147889378/390944358-5dae89fc-0f47-4cba-b852-6e97e04ec42e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4NzA3NzEsIm5iZiI6MTczMjg3MDQ3MSwicGF0aCI6Ii8xNDc4ODkzNzgvMzkwOTQ0MzU4LTVkYWU4OWZjLTBmNDctNGNiYS1iODUyLTZlOTdlMDRlYzQyZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOVQwODU0MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYTdiMzk2YjBhZjkzMjM2MGJmY2Q4YTg0OTU4YWUyOTc1Yzk2MGM4ZjFmYWYxYTQ5ZGE4NjRiYzdhYzhjYmI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-O4QzsjFvgdALKQ_meLV5TSHaparMxjL6_ZwllLBkGo) ![image](https://private-user-images.githubusercontent.com/147889378/390944383-ee79886c-c711-400d-b3f1-db8ad08ecf8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4NzA3NzEsIm5iZiI6MTczMjg3MDQ3MSwicGF0aCI6Ii8xNDc4ODkzNzgvMzkwOTQ0MzgzLWVlNzk4ODZjLWM3MTEtNDAwZC1iM2YxLWRiOGFkMDhlY2Y4Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOVQwODU0MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNTg5NWY0NTUwMGFjMGJiODlmMzA4ZWYwNzVlMDhkZTQxY2ViNjI0OTFhM2E1NmU3YWQ0M2JmZWQ4Y2ZmNTE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.RHz6xAe2D81QTvyTPERdH5ees-16dM1xUR24mJh9cg0)
> ### Reproducible?
> 
>     * [x]  I have checked that this issue cannot be reproduced on Mozilla Firefox.
> 
> 
> ### Version
> 
> 1.0.1.a.20
> ### What platform are you seeing the problem on?
> 
> Windows
> ### Relevant log output
> 
> _No response_

the small x icon is due to Collapsed Tab X Button (v1.0.0) mod

**Comment by Lan0s** [comment]
+1 on macOS

<img width="295" alt="image" src="https://github.com/user-attachments/assets/a5636b48-1982-467f-9475-1f00429519e2">

**Comment by 12th-devs** [comment]
@Xhenzu Update to a.22, this version is the same as a.19, the dev coded the update around Firefox 132 not 133. But the released a.20 was on Firefox 133. So updating should fix your browser.

**Comment by neurokitti** [comment]
the null thing should be fixed and the issue with hovering over the X button is a mod. if the issue persists even with mods off and in the most recent version please let me know!
