### ISSUE TITLE
Linux ARM64 builds missing from latest release

### ISSUE THREAD

**Issue by Botspot** [zen-browser/desktop#3290]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I just checked the releases, and while https://github.com/zen-browser/desktop/releases/tag/1.0.1-a.21 has an ARM64 linux appimage, https://github.com/zen-browser/desktop/releases/tag/1.0.1-a.22 is missing it.
Where did it go? Have ARM64 linux releases been dropped, or will they be added back on later releases?

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

github

### What platform are you seeing the problem on?

Linux

**Comment by theofficialgman** [comment]
@Botspot the stable branch (which is what the "alpha" build tags are made from) does not yet have the arm64 linux/windows support. that currently (among other things https://github.com/zen-browser/desktop/compare/stable...dev) only exists in the dev branch (which is what the "twilight" build tags are made from).

stable (alpha): https://github.com/zen-browser/desktop/actions/workflows/build.yml
dev (twilight): https://github.com/zen-browser/desktop/actions/workflows/twilight-release-schedule.yml

**Comment by theofficialgman** [comment]
a previous stable (alpha) build was "more up to date" with dev but was rolled back due to other issues (they force pushed over the stable branch (removed commits), you can see that the tag for 1.0.1-a.21 is closer to dev than 1.0.1-a.22 is)

> Release notes for 1.0.1-a.22 🎉
> 
> If you encounter any issues, please report them on [the issues page](https://github.com/zen-browser/desktop/issues/). Thanks everyone for your feedback! ❤️
> 
> This build rolls back to version 1.0.1-a.19 due to the number of bugs and complains. Sorry!
