### ISSUE TITLE
During on-boarding, you cannot see the color you are selecting while using the color slider 

### ISSUE THREAD

**Issue by quissberry** [zen-browser/desktop#33]
![image](https://github.com/zen-browser/desktop/assets/106037630/9bc2f8bf-ee30-46c6-b6e5-b4d1b74d7d7d)

When using the color slider, you cannot actually see the color you are selecting because the slider button is blocking it. This makes it more difficult to get a more precise color and makes the whole slider cumbersome to use.

**Comment by mauro-balades** [comment]
Ill just move this together with: https://github.com/zen-browser/desktop/issues/33
