### ISSUE TITLE
Implementing features from Mercury

### ISSUE THREAD

**Issue by ThousandDemonDaggers** [zen-browser/desktop#330]
### What feature would you like to see?

Since it seems that Mercury adds some patches that Zen Browser maybe hasn't implemented yet, wouldn't be a good idea to implement them? Also, Mercury doesn't seem to be updated regularly anymore.

<hr>

## List of patches included in Mercury

 - Compiler modifications include [AVX](https://en.wikipedia.org/wiki/Advanced_Vector_Extensions), [AES](https://en.wikipedia.org/wiki/AES_instruction_set), [LTO](https://en.wikipedia.org/wiki/Interprocedural_optimization#WPO_and_LTO) and [PGO](https://en.wikipedia.org/wiki/Profile-guided_optimization).
 - Disable all telemetry and reporting.
 - Remove all debugging constructs and enable hardening by default.
 - Enable backspace to go back, and GPU acceleration by default.
 - Enable [Do Not Track](https://allaboutdnt.com/) and [Global Privacy Control](https://globalprivacycontrol.org/#about).
 - Disable Pocket, highlights, and suggested content on the new tab page.
 - Restore top bar to ~ESR78 state with home button and developer button.
 - Allow installing unsigned extensions.
 - Branding changes
 - Enable [JPEG XL](https://jpegxl.info/) by default
 - Implemented performance tweaks from [BetterFox](https://github.com/yokoffing/Betterfox).

&ndash; Some help in creating these patches came from [LibreWolf](https://librewolf.net/), [Waterfox](https://www.waterfox.net/), [FireDragon](https://github.com/dr460nf1r3/firedragon-browser), [PlasmaFox](https://github.com/torvic9/plasmafox), [Ghostery](https://github.com/ghostery/user-agent-desktop), and [GNU IceCat](https://www.gnu.org/software/gnuzilla/).

&ndash; Any other code/patches are written from scratch by [Alex313031](https://thorium.rocks/about).

## Patch URLs to use when rebasing.

https://gitlab.com/librewolf-community/browser/source/-/blob/main/patches/ui-patches/firefox-view.patch

https://gitlab.com/librewolf-community/browser/source/-/blob/main/patches/allow-JXL-in-non-nightly-browser.patch

https://gitlab.com/librewolf-community/browser/source/-/blob/main/patches/windows-theming-bug.patch

https://gitlab.com/librewolf-community/browser/source/-/tree/main/patches

https://github.com/ghostery/user-agent-desktop/blob/main/patches/0018-Ghostery-Theme.patch

<hr>

Source: [https://github.com/Alex313031/Mercury/blob/main/docs/PATCHES.md](https://github.com/Alex313031/Mercury/blob/main/docs/PATCHES.md)

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
Isnt JXL enabled already?

**Comment by n7itro** [comment]
> Isnt JXL enabled already?

Nope, this has been requested feature for a long time (https://connect.mozilla.org/t5/ideas/support-jpeg-xl/idi-p/18433)

**Comment by mauro-balades** [comment]
Oki, I think i've added all of them, thanks!
