### ISSUE TITLE
PLEASE HELP: Zen Remotly unusable and Twilight lost gradient

### ISSUE THREAD

**Issue by 12th-devs** [zen-browser/desktop#3302]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

@mr-cheff I am so sorry to mention you but, I wish there was a good way to explain this but, I have Zen Browser and Zen Twilight installed and daily drive them. I have gotten a bug in Zen Browser where (on Windows) when the browser is in full screen I am unable to use the right half of the screen. I suspect that it is something with the Zen devtools as I always put those on the left side of my screen while editing userChrome.css. But I am unable to find a solution, I have disabled all mods and custom CSS, I have also reinstalled but with no luck. I am currently writing this on Twilight (which is quite buggy right now, as to be expected) I have one big issue with Twilight and I could not find anything about it in the release notes on GitHub, my gradient is completely disabled and I do not know how to get it back, the option is completely gone in the right-click menu. I will check about:config next and see what I can find, I just figured I would let you know what is going on. 

@mr-cheff you are truly an amazing dev, any help from anyone is appreciated.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Version 1.0.1-t.22 (64-bit) & Version 1.0.1-a.22 (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by mr-cheffy** [comment]
Enable workspaces and please don't ping me. Could you show a screenshot of the half broken screen?

**Comment by 12th-devs** [comment]
No problem, it won't happen again, thanks for replying. That's the thing, I have four workspaces and have for months... I will show you my Twilight issue and Zen issue.

![Screenshot 2024-11-30 090608](https://github.com/user-attachments/assets/63105b96-6692-4de6-9d66-d7029847d4ad)
As you can see the theme option is completely gone but, I have four workspaces at the bottom, I will try disabling and re-enabling them but I feel that this is something that is a fairly big deal. Also in Twilight, nothing in the place the URL bar was is being displayed.

EDIT: I have disabled and re-enabled workspaces, but no luck 🫤

Here is a video of the Zen Browser issue, like I said earlier I feel like it is something with the browser dev-tools and how Windows snaps windows, but I would not fully know.

https://github.com/user-attachments/assets/2f52d6c3-6d41-4ce6-a389-c7d0d1bf6dc0


The video shows me snapping the window, and any time its in full screen you can see that anything I hover over becomes unresponsive. I was also clicking but there was no visual display. Any help is really appreciated, hopefully, one day I can contribute once I understand how to code more.

Thank you for this amazing project, have a great day or night!

**Comment by 12th-devs** [comment]
Well, I am lost. I created a test account for the theme color issue, and what do you know everything works fine, I can create a gradient and use it as it should. I have probably done something without me realizing, is there a file or about:config I could change to fix this? Or should I just start migrating to another profile?

Edit: what info or logs do you need to find the root cause?

**Comment by 12th-devs** [comment]
@mr-cheff I know you asked for me not to ping you but, my gradient in twilight is still gone with no way to get it back, as I have said workspaces are on. Is there an about:config setting I can change?
