### ISSUE TITLE
WebGL unsupported?

### ISSUE THREAD

**Issue by naomieow** [zen-browser/desktop#332]
### What happened?

WebGL doesn't seem to work. While playing D&D tonight, I found that my group's virtual tabletop, Foundry, would not load and reports that the browser does not seem to support WebGL.

https://webglsamples.org/ also reports that WebGL isn't supported - so it isn't a bug with Foundry.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.22

### Severity impact

Medium

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
In `about:config`, what's the value for `webgl.disabled`?

**Comment by mauro-balades** [comment]
It is supported, 
![Screenshot_20240820_101831](https://github.com/user-attachments/assets/d20f7901-907e-4992-b89c-3f21e9c5aef7). Come back if you are still having this problem

**Comment by naomieow** [comment]
> In `about:config`, what's the value for `webgl.disabled`?

The value for `webgl.disabled` is false.

**Comment by naomieow** [comment]
This is still an issue, and only happens with Zen, not base Firefox.
As I have already said, webgl is *enabled* in the browser
![image](https://github.com/user-attachments/assets/db01347b-4093-43a0-833a-8f1ca4aea8f2)
![image](https://github.com/user-attachments/assets/80667c2d-fdac-4ab8-b7ce-4277a7fd22ad)

Setting `webgl.force-enabled` to `true`, allows it to load webgl applications, but this is not an amazing workaround as it ignores the actual root cause of the problem.
![image](https://github.com/user-attachments/assets/7b581205-c013-41d9-a933-397b4b82829e)

**Comment by temportalflux** [comment]
Can confirm this is still an issue. It is currently preventing me from accessing Jira's Confluence whiteboards, assumingly because Jira pushed an update today requiring WebGL2 https://whiteboards-compatibility.atlassian.com/
