### ISSUE TITLE
Google Classroom acting funky

### ISSUE THREAD

**Issue by Frxncis-13** [zen-browser/desktop#3323]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Google classroom has the gradient effect on home page when selecting class
![Screenshot 2024-11-30 200034](https://github.com/user-attachments/assets/1620da98-6026-41c9-b1a5-70c0ccebf154)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1

### What platform are you seeing the problem on?

Windows

**Comment by 12th-devs** [comment]
Search around on Reddit or on here for pages having no background, I don't remember off the top of my head but it is an about:config settings

**Comment by Ducky07** [comment]
> I don't remember off the top of my head but it is an about:config settings

On MacOS, disabling **`browser.tabs.allow_transparent_browser`** helps with pages missing the background property.
If you want to change the default page background (if not specified by the website), it's under **`browser.display.background_color`**
I hope this helps!

**Comment by Frxncis-13** [comment]
thank you sincerely appreciate it
