### ISSUE TITLE
GsConnect Not working

### ISSUE THREAD

**Issue by atybdot** [zen-browser/desktop#3332]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The Gsconnect extension is not working,showiing error such as service failed or no device found.
but it is working on the firefox.
there could be two reasons 
1. I have flatpak build of zen and it does not have a access to gsconnect. while my firefox is a fedora package.
2. gsconnect firefox/chromium build does not work with flatpaks

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.22 (Firefox 132.0.1) (64-bit)

### What platform are you seeing the problem on?

Linux

**Comment by different55** [comment]
If GSConnect doesn't work with Flatpaks, and Zen is installed as a Flatpak, then that sounds like your issue, right? Does it work when installing Zen from a non-Flatpak source?

**Comment by atybdot** [comment]
I just tried running GSConnect with flatpak build of firefox.It's not working there either.
Looks like it's a gsconnect/flatpak issue rather than zen/firefox.
