### ISSUE TITLE
MacOS "Tabs on the right" option not functional

### ISSUE THREAD

**Issue by talon-likeaclaw** [zen-browser/desktop#334]
### What happened?

When opening the context menu in the Vertical Tab Bar and selecting "Tabs on the right" on my M3 Pro Macbook, nothing happens. However, when I perform the same action on my Windows 11 PC, it functions as expected. There is a check mark present on the option after selecting it on MacOS, but the Vertical Tab Bar remains on the left side.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.23

### Severity impact

Low

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by soumendrak** [comment]
Yes, Tab on right just suffixes the dropdown value with a check mark and nothing moves.
![image](https://github.com/user-attachments/assets/9b64608f-5537-4477-8a6f-d04562da61ff)

**Comment by mauro-balades** [comment]
Let's see for the next release if this is fixed, im not on mac so I can't really test it

**Comment by talon-likeaclaw** [comment]
@mauro-balades Still no luck as of version 1.0.0-a.28. I'll keep you updated in future versions!

**Comment by fpigeonjr** [comment]
confirmed

**Comment by arthurazs** [comment]
Here it works on normal mode. But when I switch to compact mode, the bar only appears on the left.

- Ubuntu 24.04 LTS (Linux ubuntu 6.8.0-31-generic #31-Ubuntu SMP PREEMPT_DYNAMIC Sat Apr 20 00:40:06 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux)
- Zen Browser Version 1.0.0-a.28

**Comment by ventsislav-georgiev** [comment]
I have the opposite issue. My tabs swapped on the right after some restart without me cliking on that option. I can't find a way to revert them back to normal.
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/9fec2066-1446-4d4c-98d4-6b27b811c672">

**Comment by ventsislav-georgiev** [comment]
Another note: enabling compact mode shows them on the left.

https://github.com/user-attachments/assets/b9c978d1-5fe4-421f-9b29-eb29e75f6aad

**Comment by ventsislav-georgiev** [comment]
More info: I've managed to "fix" my tabs stuck on the right only behavior by toggling the Sidebar. That magically moved the tab bar on the left again instantly. 🤷🏻‍♂️ 

Now changing the sidebar location seems to change the tabs location as well. Here is a video of this behavior:
https://github.com/user-attachments/assets/22a5630c-6744-4de8-83b0-e525a81273b0

This however no longer preserves after restarts. Now they are back to the left on start. 😄

**Comment by r-nl** [comment]
This issue still persists on a fresh install, it it stuck eternally on the left. On OSX, this also means the window controls are offset, which is subideal.

**Comment by mauro-balades** [comment]
I think both issues are fixed for the next release, we'll see

**Comment by talon-likeaclaw** [comment]
@mauro-balades Unfortunately the issue seems to persist on 1.0.1-a. Love the update though, great job!
