### ISSUE TITLE
Top Bar Padding Increasing in Compact Mode (Twilight)

### ISSUE THREAD

**Issue by zacaronii** [zen-browser/desktop#3348]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When compact mode is enabled in twilight v1.0.1-t.22, the padding on the top bar increases by a fairly large margin. I added several screenshots showing that this behavior is consistent across all of the different options available in compact mode. I tried enabling/disabling some other settings and disabling mods, but the behavior seems to be consistent no matter what I do.

![NoCompactTwilight2024-12-02_12-34-21](https://github.com/user-attachments/assets/82ee020a-b768-4c03-9a6e-61903ec26b7b)
![HideTabTwilight2024-12-02_12-35-01](https://github.com/user-attachments/assets/431d54e1-ea03-4d75-89c0-a0b2db99b700)
![HideTopTwilight2024-12-02_12-35-24](https://github.com/user-attachments/assets/f5514a53-3cc8-42b3-820c-24495be8af49)
![HideBothTwilight2024-12-02_12-35-44](https://github.com/user-attachments/assets/8daccd94-ca05-4c86-9c5b-0387cf472ece)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-t.22

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by DevSnyco** [comment]
same thing here

**Comment by 12th-devs** [comment]
Check and see if only the sidebar is being hidden?

**Comment by DevSnyco** [comment]
> Check and see if only the sidebar is being hidden?

yes, it gets fixed when compact mode gets turned off

**Comment by froggy-jpg** [comment]
off-topic question but how did you put searchbar into the tab bar?

**Comment by zacaronii** [comment]
I updated to 1.0.2-t.0 and I am no longer having this problem.
