### ISSUE TITLE
Moving tab across workspace and then right-clicking on it does not render a menu

### ISSUE THREAD

**Issue by NeelavaChatterjee** [zen-browser/desktop#3353]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

## Actual
When we move tabs across workspace, i.e., from workspace-A to workspace-B, right-clicking on any tabs does not give a menu.
## Expectation
When we move tabs across workspace, i.e., from workspace-A to workspace-B, right-clicking on any tabs renders a menu.

## Work Around
Right-click any where else other then the tab space, will give a menu and now go back and right click on the tabs and the menu will start rendering.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Mozilla Zen 1.0.1-a.19

### What platform are you seeing the problem on?

Linux

**Comment by froggy-jpg** [comment]
also experiencing the issue

**Comment by TheTrueFerret** [comment]
also experiencing this issue in the latest beta release 20

**Comment by neurokitti** [comment]
this is a repeat of the following issues:
https://github.com/zen-browser/desktop/issues/3046
https://github.com/zen-browser/desktop/issues/2980

thanks for reporting the bug! please check to see if its a repeat first though!

**Comment by neurokitti** [comment]
this is a repeat of the following issues:
https://github.com/zen-browser/desktop/issues/3046
https://github.com/zen-browser/desktop/issues/2980

thanks for reporting the bug! please check to see if its a repeat first though!
