### ISSUE TITLE
Workspace icon still shows on compact mode even when flag is disabled. 

### ISSUE THREAD

**Issue by enews** [zen-browser/desktop#3355]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When the hide workspaces config is enabled, it still shows in compact mode. Its okay in regular wide mode. 

![Screenshot 2024-12-03 141237](https://github.com/user-attachments/assets/a68469d8-7fc7-4abc-b129-4bf4c3945414)
![Screenshot 2024-12-03 141241](https://github.com/user-attachments/assets/88c839f5-eeb0-4e09-b459-59ba2c448f14)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

When the hide workspaces config is enabled, it still shows in compact mode. 

### What platform are you seeing the problem on?

Windows

**Comment by mr-cheffy** [comment]
There's no version provided. I'm going to assume it has been fixed already
