### ISSUE TITLE
When switch workspaces, the current-focused tab sometimes also show in the new workspace

### ISSUE THREAD

**Issue by marsjane** [zen-browser/desktop#3357]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I met this quite several times:
When I am in workspace A, and focused on a tab, then when I switch to another workspace B, the previously focused tab will also show in workspace B, so this tab would show in two workspaces simultaneously , which is puzzling. If I click to some other tabs then switch between workspaces the wrong tab shown in workspace B can disappear.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.22 (Firefox 132.0.1) (aarch64)

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by qu8n** [comment]
Same here. Also on MacOS aarch64.

**Comment by marsjane** [comment]
I found it is not only macos. Windows version has the same issue.

**Comment by JonneDatanen** [comment]
I had same issue right after updating, but closing all tabs and restarting Zen seemed to fix it

**Comment by marsjane** [comment]
it seems that this issue was fixed in the new beta version, so close it
