### ISSUE TITLE
closing tabs makes other tabs briefly smaller

### ISSUE THREAD

**Issue by n7itro** [zen-browser/desktop#337]
### What happened?

When quickly closing multiple tabs, the tab list shrinks noticeably. The tabs return to their original size after a few seconds.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-23.a

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
This is fixed for next release 👍🏽
