### ISSUE TITLE
The window control buttons are duplicated on top of each other

### ISSUE THREAD

**Issue by PhiNhat2211** [zen-browser/desktop#3395]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![issue](https://github.com/user-attachments/assets/a7e0ae7f-6fe8-4d58-92db-b9f6f6a97a8e)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-t22

### What platform are you seeing the problem on?

Windows

**Comment by gomster** [comment]
hi,
same for me here,  but I don't know if it's an error in setting up my css from the start that I've been using twilight or a general bug. The min,max,close dots are superimposed on those of my css ..I'll test with a clean profile .
![2024-12-04_210129](https://github.com/user-attachments/assets/810e93a0-a9ea-4101-9baf-30e2677abbb4) . thx for all

**Comment by PhiNhat2211** [comment]
> hi, same for me here, but I don't know if it's an error in setting up my css from the start that I've been using twilight or a general bug. The min,max,close dots are superimposed on those of my css ..I'll test with a clean profile . ![2024-12-04_210129](https://private-user-images.githubusercontent.com/39035251/392690822-810e93a0-a9ea-4101-9baf-30e2677abbb4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzODgyOTAsIm5iZiI6MTczMzM4Nzk5MCwicGF0aCI6Ii8zOTAzNTI1MS8zOTI2OTA4MjItODEwZTkzYTAtYTllYS00MTAxLTliYWYtMzBlMjY3N2FiYmI0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDA4Mzk1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0ZDYzZjRiODllMjVmZjI0MTlkNTVkYThkZjZkMGU2ZDc4NzRkYjRjODc1OTc2Mjg5NmRmOWIyN2RkMTdmZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XBdfAo2GAu2r87EtUln9Y8HeMjt7hOUsvxbrNTrmetU) . thx for all

I think  it's a bug. In my case, I thought it was caused by Zen mods, so I uninstalled everything, but the issue still. Hope it will be fixed soon

**Comment by Madekuji** [comment]
Same issue happens on my end, but it looks a whole lot weirder when the window is active:

https://github.com/user-attachments/assets/0c22fb4d-00b0-4397-baa0-24dcc7fa8e39

**Comment by PhiNhat2211** [comment]
> Same issue happens on my end, but it looks a whole lot weirder when the window is active:
> zen-3395-test-1.mp4

I noticed this issue occurring after the 1.0.1-t.22 (20241204024123) build. It seems like the default window control buttons are no longer hidden, and additional buttons are being added on top of them when hovered. My Zen Mods related to the window control buttons are now broken, previously they were working smoothly 🥲

**Comment by gomster** [comment]
> hi, same for me here, but I don't know if it's an error in setting up my css from the start that I've been using twilight or a general bug. The min,max,close dots are superimposed on those of my css ..I'll test with a clean profile . ![2024-12-04_210129](https://private-user-images.githubusercontent.com/39035251/392690822-810e93a0-a9ea-4101-9baf-30e2677abbb4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NjQxODgsIm5iZiI6MTczMzQ2Mzg4OCwicGF0aCI6Ii8zOTAzNTI1MS8zOTI2OTA4MjItODEwZTkzYTAtYTllYS00MTAxLTliYWYtMzBlMjY3N2FiYmI0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDA1NDQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjODZjYWVmZDQzYzMyZjRhMTc1YTBiMGU0NWE2YzM5NDgwZDdkNDkzZjFlMGY3ZjhhZDBjNTAxYzJmMzhmZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XpcesMneWUbouQNNc6J4hA0EhY2Sk8jX8nqLVOe5CvQ) . thx for all

after the last update, everything is back to normal 🤙🏼 - thx for the fix -NjoY
![2024-12-05_194157](https://github.com/user-attachments/assets/f95de09c-183f-40ee-81ec-8cbab1df9226)

**Comment by Delta427** [comment]
I had this bug too and got fixed with the last update... for 5 minutes or so. Now it's back.

I noticed that when opening a Private Window the bug doesn't appear. Also, when creating a new profile everything is normal until I re-open the browser again, then the bug comes back.

I tried disabling all themes and also all the add-ons... no changes.

**Comment by PhiNhat2211** [comment]
> I had this bug too and got fixed with the last update... for 5 minutes or so. Now it's back.
> 
> I noticed that when opening a Private Window the bug doesn't appear. Also, when creating a new profile everything is normal until I re-open the browser again, then the bug comes back.
> 
> I tried disabling all themes and also all the add-ons... no changes.

Gosh, it's really back after the latest update, fixed for only a few hours. I guess we'll have to wait and see

**Comment by Delta427** [comment]
latest updated fixed it again for me
