### ISSUE TITLE
Browser crashes when clicking on an extension on the toolbar.

### ISSUE THREAD

**Issue by quissberry** [zen-browser/desktop#34]
### Steps to reproduce

1. Install an extension on addons.mozilla.org which makes a pop-up when pressed on the toolbar (uBlock Origin, LibRedirect for example). If not by default, pin the extension to the toolbar
2. Left click on the extension  
Then browser crashes, and the Zen Browser Crash Reporter appears. 

### System information

OpenSUSE Tumbleweed, GNOME, Wayland 
Version: 0.0.0-a.1

(crash begins on "ExceptionHandler")
```
yly@localhost:~/Downloads/zen> ./zen-bin
JavaScript warning: chrome://browser/content/tabbrowser-tabs.js, line 1193: unreachable code after return statement
console.log: "ZenViewSplitter initialized"
console.log: "ZenWorkspaces initialized"
console.error: ({})
[GFX1-]: Invalid application version 0.0.0-a.1
ExceptionHandler::GenerateDump cloned child 136111
ExceptionHandler::WaitForContinueSignal waiting for continue signal... ExceptionHandler::SendContinueSignalToChild sent continue signal to child
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
```

**Comment by mauro-balades** [comment]
Fixed. Thanks a lot for these bug reports!
