### ISSUE TITLE
Hardware Decoding not working on twitch.tv

### ISSUE THREAD

**Issue by laxman20** [zen-browser/desktop#340]
### What happened?

When watching streams on www.twitch.tv, I am getting skipped frames.

I verified that hardware decoding was not working using the Resources flatpak app (https://flathub.org/apps/net.nokyan.Resources), which shows hardware decoding usage as a percentage. It was showing 0% while a video was streaming on twitch.tv

I can't reproduce the same on Firefox. Playback is smooth and Resources indicates that hardware decoding is working.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.23

### Severity impact

Medium

### What platform are you seeing the problem on?

Linux

#### Hardware Information:
- **Hardware Model:**                              Lenovo Yoga 7 14IRL8
- **Memory:**                                      16.0 GiB
- **Processor:**                                   13th Gen Intel® Core™ i5-1335U × 12
- **Graphics:**                                    Intel® Graphics (RPL-U)
- **Disk Capacity:**                               512.1 GB

#### Software Information:
- **Firmware Version:**                            LHCN21WW
- **OS Name:**                                     Aeon
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               46
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.10.5-1-default

**Comment by Stryxus** [comment]
This may be an part of a wider issue. On Windows, if I play any video with Hardware Acceleration enabled, the browser flickers randomly and sometimes the decoder fails, in Twitch's case, this results in a player error.

**Comment by DavidGreen63** [comment]
In regards to Video Streaming, I get the following message;
![Screenshot 2024-09-04 222657](https://github.com/user-attachments/assets/a35eb7a0-5bb8-4c0f-ae91-645df299e942)
This is not an issue with my main browser; Floorp (a Firefox fork maintained by Ablaze), which can play the same stream within seconds of Zen returning the aforementioned error message, which alludes to an incompatibility on the Client side, every time I have tried.

My desktop is Win10Pro 22H2 19045.4780 on Intel NUC i7-9750H @ 2.6GHz 32GB RAM ← if relevant
"7plus" is an on-demand service of an Australian Free to Air Broadcaster.

**Comment by mauro-balades** [comment]
This shoud've had got fixed. Does it still happen?

**Comment by DavidGreen63** [comment]
> This shoud've had got fixed. Does it still happen?

I'm not sure who this question was directed to, but in the last few minutes; but the issue is still present when watching a stream from 7plus. Ablaze Floorp, immediately before and after the Zen test is working fine. So that would be "yes" for me.

**Comment by laxman20** [comment]
> This shoud've had got fixed. Does it still happen?

Hi. I can confirm it is fixed now (I'm on version 1.0.0-a.39). Playback is smooth and Resources app is showing hardware decoding is happenning.

Thank you!
