### ISSUE TITLE
New URL in sidebar layout makes browser unusable

### ISSUE THREAD

**Issue by nanocryk** [zen-browser/desktop#3400]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

After updating to the latest version (using twilight install script), the content of the browser top bar has been moved inside the sidebar, showing as this new layout:
![image](https://github.com/user-attachments/assets/fce7c50b-5834-43a0-a05f-86b6ceed07ce)

Layout before (after I managed to downgrade back to t.19:
![image](https://github.com/user-attachments/assets/358fabf6-fe2f-4799-9301-d93d835b0dd9)

This causes a number of issues:
- "Expand Tabs on Hover (Won't work on compact mode)" is no longer available. Apparently it is volontary and a mod will be available in the future, but I don't find it nice for your users to roll this change without having said mod available (+ link to the mod when launching the browser after the update).
- URL bar doesn't show drop down on click.
- I can no longer switch between workspaces. Icon at the top only shows the 2nd workspace, and once I'm in this workspace there is no way to switch to the other workspaces (I can open the browser settings to switch to 1st workspace, but no way to switch to 3rd workspace)
- Top collapsing bar is just empty and is now useless.
- When going to "Customize toolbar", it shows up the normal layout with the URL and buttons at the top, but when exiting the URL and buttons go back to the sidebar.

Even without the workspace bug, I really dislike this new layout. The thin top bar with the URL and buttons was perfect for me. Please consider adding an option in "Look and Feel" menu to choose if you want the classic layout or URL in sidebar layout.

I have to downgrade the browser as it is unusable in this state.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-t.22

### What platform are you seeing the problem on?

Linux

**Comment by Lippiece** [comment]
I'm using zen.view.use-single-toolbar=false in about:config

**Comment by nanocryk** [comment]
With latest Twilight the URL bar is back on top, but just in case I used your config.
