### ISSUE TITLE
search bar 'jump' to sidebar when in compact mode in twilight

### ISSUE THREAD

**Issue by ryannewcomer** [zen-browser/desktop#3406]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

https://github.com/user-attachments/assets/74afc60e-1244-4ac4-b5bc-eb5578b44fef

as you can see, when compact mode is off, the search bar 'jump' back to the middle

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

 1.0.1-t.22

### What platform are you seeing the problem on?

Windows

**Comment by 12th-devs** [comment]
What is the issue here? That it is centered? I'm pretty sure this is supposed to be like this now.

**Comment by ryannewcomer** [comment]
is it? Then, is there a option that let me change the search bar to centered even in compact mode? Thanks

**Comment by 12th-devs** [comment]
Ohhh I though you where talking about it being centered, I do not thing so. If I find anything I will let you know.

**Comment by ryannewcomer** [comment]
ok, many thanks

**Comment by ryannewcomer** [comment]
Dosu, do you find anything?

**Comment by ryannewcomer** [comment]
this is fixed with the newest update. Thanks
