### ISSUE TITLE
1.0.1-a.22 is vunarable to few CVEs from ff 132

### ISSUE THREAD

**Issue by vavakado** [zen-browser/desktop#3408]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

There is a one high level CVE that was fixed only in ff 133.0 but the current 1.0.1-a.22 is based on ff 132.  

Also there is 9 moderate CVEs that were fixed in ff 133

https://www.mozilla.org/en-US/security/advisories/mfsa2024-63/

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.22

### What platform are you seeing the problem on?

Linux, macOS - aarch64, macOS - Intel, Windows

**Comment by Eveeifyeve** [comment]
This was one of the biggest issues that zen couldn't be on nixpkgs, read more in https://github.com/NixOS/nixpkgs/pull/347222#issuecomment-2508814428

**Comment by vavakado** [comment]
now with 1.0.2-b.0 i can probably close this
