### ISSUE TITLE
Set a keybinding to change to a specified workspace

### ISSUE THREAD

**Issue by Jusoaresg** [zen-browser/desktop#342]
### What feature would you like to see?

I'd like to request a feature that allows users to set custom keybindings for switching to specific workspaces in the browser. This functionality would greatly enhance productivity by providing a quick and convenient way to navigate between different workspaces without relying solely on the mouse.

### What platform are you seeing the problem on?

Linux

**Comment by albu-ali** [comment]
This will be great for people whose hands do not leave the keyboard (like me, maybe you, and most of Linux users)

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/860

 ~ This is an automatic operation to better enhancements requests organization.
