### ISSUE TITLE
KeePassXC browser integration broken.

### ISSUE THREAD

**Issue by T-O-R-U-S** [zen-browser/desktop#343]
### What happened?

KeePassXC extension doesn't seem to be able to connect to database. It can do this on regular Firefox as well as Mercury browser. Console logs are completely blank.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.23 (64-bit)

### Severity impact

Medium

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
[2, Main Thread] WARNING: Failed to read portal settings: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop: 'glib warning', file /home/runner/work/desktop/desktop/engine/toolkit/xre/nsSigHandlers.cpp:187

(zen-alpha:2): Gdk-WARNING **: 09:51:29.488: Failed to read portal settings: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop
```

**Comment by T-O-R-U-S** [comment]
Further info: This issue seems to be exclusive to the Flatpak version of Zen after further testing.

**Comment by T-O-R-U-S** [comment]
I'm reopening this with higher severity**

**Comment by wyattwas** [comment]
> Further info: This issue seems to be exclusive to the Flatpak version of Zen after further testing.

Can confirm that. When installing the Zen browser via Flatpak, connecting to a database is not working. After installing it via the AppImage, it seems to be fine,
