### ISSUE TITLE
这个浏览器看优爱腾等网页在线流媒体没有4K选项

### ISSUE THREAD

**Issue by kennylee60** [zen-browser/desktop#3435]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

这个浏览器看优爱腾等网页在线流媒体没有4K选项，真彩等都没有可以选的

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.22

### What platform are you seeing the problem on?

Windows

**Comment by mr-cheffy** [comment]
Please only issues in english as they are difficult to search for and understand at first sight for mantainers. Thanks!
