### ISSUE TITLE
[Bug] Portable version not portable

### ISSUE THREAD

**Issue by Aiakio** [zen-browser/desktop#344]
### What happened?

The portable version of Zen saves the Profile directory under `C:\Users\[Username]\AppData\`. The Profile folder should be saved right next to the executable somewhere. The fact that it's saved under `%AppData%` makes it not portable at all.

Not sure about security implications, but this could have some if you use it on a public computer or one that is not yours.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox or other Firefox forks that offer a portable version.

### Version

1.0.0-a.23

### Severity impact

Medium (?)

### What platform are you seeing the problem on?

Windows

**Comment by yoshinatsu** [comment]
True. I was really happy when I saw that this promising new browser offers a portable mode, but apparently only the program files are "portable", everything else goes to `%AppData%` just like standard Firefox.

**Comment by mauro-balades** [comment]
Yeah, this is just how firefox works, im not planning on changing how the system works

**Comment by nightson** [comment]
> Yeah, this is just how firefox works, im not planning on changing how the system works

But that makes Zen not portable at all....Some other Firefox based web browsers like Floorp have real portable mode but I prefer the UI design and performance of Zen. This is the only thing that prevents me from switching to Zen :(

**Comment by SlinkousArt** [comment]
I'm currently working on a way to make it work fully portable, right now I'm using a custom profile and editing profile.ini every time, but I'll make a better solution and possibly fork an PR
