### ISSUE TITLE
After the new twilight update "Toggle Sidebar's Width" hotkey is not there 

### ISSUE THREAD

**Issue by vavakado** [zen-browser/desktop#3440]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I find this a regression, i personally used to using alt-b (Toggle Sidebar's Width) hotkey with my workflow, so the lack of it in the newest version lowers my productivity.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-t.22

### What platform are you seeing the problem on?

Linux

**Comment by marco741** [comment]
This also happened on Mac OS

**Comment by vavakado** [comment]
this was added back in 1.0.2-b.2 so i will close
