### ISSUE TITLE
Logging on Google does not prompt security key popup to login

### ISSUE THREAD

**Issue by ianaqua42069** [zen-browser/desktop#3442]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I tried logging on Google, usually it'd pop up for me to use my fingerprint reader to login onto Google. While on Firefox stable, it prompts it. 

<img width="884" alt="Screenshot 2024-12-08 at 10 52 27 PM" src="https://github.com/user-attachments/assets/a4a37df5-37f9-48e0-9833-43eaf551ce90">

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.22

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by armyhaylenko** [comment]
duplicate of #437

**Comment by mr-cheffy** [comment]
duplicate of https://github.com/zen-browser/desktop/issues/437
