### ISSUE TITLE
Onboarding workflow kicks in even for existing profile

### ISSUE THREAD

**Issue by vraravam** [zen-browser/desktop#3448]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I used to use the 1.0.1 twilight builds. When I got a notification within the past 24 hrs that there was a new twilight build, it automatically downloaded when I went into the About window. This part is fine.

Once I clicked on the install and restart button, when Zen was restarted, it came up with the omboarding orange screen. I was able to use the Escape key to get out of that and continue using with the previously configured workspaces, tabs, etc - but, each time I quit Zen and start it up again, the same thing happens which gets irritating over time. Please fix

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-t.0 (Firefox 133.0) (2024-12-09) (aarch64)

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by vraravam** [comment]
Still present in 1.0.2-t.0 (Firefox 133.0) (2024-12-10) (aarch64)

**Comment by vraravam** [comment]
Found out that `zen.welcome-screen.seen` when set to `true` will ensure that this onboarding workflow is no longer run on the next restart of zen! Closing

**Comment by adhirajcs** [comment]
You can just finish the onboarding setup. It won't erase your existing data, it will just ask some questions and that's it.

**Comment by vraravam** [comment]
> You can just finish the onboarding setup. It won't erase your existing data, it will just ask some questions and that's it.

As a layman user, one would always worry if they chose a different option, whether it would "break" their setup - especially in a pre-existing profile.

**Comment by adhirajcs** [comment]
> > You can just finish the onboarding setup. It won't erase your existing data, it will just ask some questions and that's it.
> 
> As a layman user, one would always worry if they chose a different option, whether it would "break" their setup - especially in a pre-existing profile.

Fair but if you see the options, they are not breaking any setup except the toolbar option, which is something someone will if they are using Twilight version of Zen.
