### ISSUE TITLE
When using Flatpak, Native Messaging breaks entirely

### ISSUE THREAD

**Issue by T-O-R-U-S** [zen-browser/desktop#345]
### What happened?

Native messaging for extensions like KeePassXC breaks entirely -- stops them from working. Workaround is to avoid the Flatpak. Are the permissions configured correctly? Can the Zen flatpak read the `.mozilla` directory to see which apps are in `.mozilla/native-messaging-hosts/`?

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.23 (64-bit)

### Severity impact

Medium

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
> You cannot use the browser extension when the browser is in a flatpak or snap. It is impossible until they introduce a plug that let's that communication happen.

flatpak sandboxes it's apps, there's no config to disable it
