### ISSUE TITLE
Give us `new page` control back

### ISSUE THREAD

**Issue by nett00n** [zen-browser/desktop#346]
### What feature would you like to see?

Modern browsers forces us to use their `new tab` page, zen browser gives the option to use about:blank for new tab.
In Firefox i have to use [extension](https://github.com/methodgrab/firefox-custom-new-tab-page) to use my very own URL for each new page. It works for Zen too, but how about add this feature to main?

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/859

 ~ This is an automatic operation to better enhancements requests organization.
