### ISSUE TITLE
floating search box in compact mode is out of place

### ISSUE THREAD

**Issue by anispwyn** [zen-browser/desktop#3467]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

https://github.com/user-attachments/assets/e4b5cdd1-b2ac-429d-a170-6145b403a304

the video already demonstrate everything

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.0

### What platform are you seeing the problem on?

Windows

**Comment by Raiden0456** [comment]
1+ on this problem, also its not centered in full mode(non collapsed)

**Comment by ajnollola** [comment]
I have the same issue as well. I thought it may have been one of the Zen Mods I installed, as those can sometimes mess up some functionality, however, I removed all of them, and it is still out of place.

**Comment by ingoau** [comment]
I am experiencing this issue. I can confirm it is just with compact mode
![image](https://github.com/user-attachments/assets/01e08064-7389-4f6c-9654-a3769fd33791)
![image](https://github.com/user-attachments/assets/0e32a99d-cc63-4b00-896f-d42144237756)

**Comment by avisadius** [comment]
> I am experiencing this issue. I can confirm it is just with compact mode ![image](https://github.com/user-attachments/assets/01e08064-7389-4f6c-9654-a3769fd33791) ![image](https://github.com/user-attachments/assets/0e32a99d-cc63-4b00-896f-d42144237756)

![Image](https://github.com/user-attachments/assets/cc999a50-bc7a-4db1-a468-a920010a161b)

is this the way to turnoff the compact mode? if yes, my search bar still popping out from its place when I typing something

**Comment by ingoau** [comment]
This is fixed now

**Comment by avisadius** [comment]
> This is fixed now


https://github.com/user-attachments/assets/b09a105b-155e-4a5f-878e-0071aefec080

already updated, and I close then open again, yes it fixes, but I do close and open again its appear
no reboot yet, I'll record again after reboot

**Comment by avisadius** [comment]
https://github.com/user-attachments/assets/708b07f3-4ba1-4cc1-9592-611a668a3955

after reboot, use neofetch just to let you know it was rebooted, maybe I need reinstall :thinking:

**Comment by anispwyn** [comment]
> 2024-12-16.19-50-15.mp4
> 
> after reboot, use neofetch just to let you know it was rebooted, maybe I need reinstall 🤔

I don't think your issue is related, open another issue
