### ISSUE TITLE
Constant Restart Update / Download for the Browser

### ISSUE THREAD

**Issue by meiozei** [zen-browser/desktop#3468]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

New beta channel update will constantly tell you that an update is available or constantly needing to restart the browser to "update" (even though this is the current build) 
![image](https://github.com/user-attachments/assets/3ba53a1a-4250-433d-a685-e06492e0f3aa)
![image](https://github.com/user-attachments/assets/e14aaf63-c49a-47f0-86c4-d62ababab91f)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.0

### What platform are you seeing the problem on?

Windows

**Comment by Unchanged4352** [comment]
@mr-cheff

**Comment by mr-cheffy** [comment]
Should be fixed now, please dont ping me
