### ISSUE TITLE
Toolbar broken on 1.0.2-b.0

### ISSUE THREAD

**Issue by kgorol** [zen-browser/desktop#3469]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![image](https://github.com/user-attachments/assets/1de82396-6937-43e2-856c-0286ccfdc5f1)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.0

### What platform are you seeing the problem on?

Windows

**Comment by Video-Nomad** [comment]
Yep, windows accent color shows on the top of the toolbar if "Show accent color on title bars and window borders" is enabled in windows settings. Disabling the accent "fixes" it.

---
![E8CGXIwmMi](https://github.com/user-attachments/assets/fb2006e8-2110-4e92-8149-e816b9ff0aa6)

---
![image](https://github.com/user-attachments/assets/5bf1daa1-2c91-49f4-883d-271f301baee1)

**Comment by tashilapathum** [comment]
Enabling one of the default themes from Settings -> Extensions and Themes fixes the issue temporarily. It's back after reopening the browser.

**Comment by mr-cheffy** [comment]
This has been reported many times.

Ill try to fix it but for the meantime, it's the windows 11's theme preference "color themed titlebar"

**Comment by jenilradadiya98** [comment]
You can also fix this for now by disabling windows mica in about:config. I think this issue is started because of a patchfile introduced for showing windows accent colour.

I think it is this file that is causing this issue as I can't find any other way this may be possible.
https://github.com/zen-browser/desktop/blob/dev/src%2Fmodules%2Flibpref%2Finit%2FStaticPrefList-yaml.patch

**Comment by kgorol** [comment]
But this issue is still persistent on newest releases.

**Comment by Killjoyer** [comment]
Disabling this option in windows helped
![image](https://github.com/user-attachments/assets/07d39cb8-e2a8-46b4-8e68-2592919009de)

**Comment by jenilradadiya98** [comment]
> Disabling this option in windows helped
> ![image](https://github.com/user-attachments/assets/07d39cb8-e2a8-46b4-8e68-2592919009de)
> 

But this will turn of accent color for all other apps. If you just want to disable this for zen you can do it by turning off widget.windows.mica option in about:config menu will diable this overlay only for zen browser.

**Comment by Killjoyer** [comment]
> > Disabling this option in windows helped
> > ![image](https://private-user-images.githubusercontent.com/35293404/398877154-07d39cb8-e2a8-46b4-8e68-2592919009de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyOTk3MDIsIm5iZiI6MTczNTI5OTQwMiwicGF0aCI6Ii8zNTI5MzQwNC8zOTg4NzcxNTQtMDdkMzljYjgtZTJhOC00NmI0LThlNjgtMjU5MjkxOTAwOWRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI3VDExMzY0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkY2U2NDUwZmY0ZTI1MjMyY2I2ODBiNGMzNzNkNTNkNGFiZGU3N2JlNWVkNWMxNWFiZjUyZWQ2MTdmZTY3MGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1MHkQA7Iiz9MGQ_dQqFEhe9nNsFVzCcq_Nk8S3z3_qU)
> 
> But this will turn of accent color for all other apps. If you just want to disable this for zen you can do it by turning off widget.windows.mica option in about:config menu will diable this overlay only for zen browser.

Didn't work

**Comment by bubin7766** [comment]
Yeah the previous fix for disabling this no longer works and Zen has reverted back to using Mica and Accent colors regardless of the setting
