### ISSUE TITLE
Expand sidebar on hover

### ISSUE THREAD

**Issue by greed-d** [zen-browser/desktop#347]
### What feature would you like to see?

Right now, there is a button to toggle mode from expanded to icon only, I'd love if there was an option somewhere in settings to enable this feature

Currently I'm trying to make a shortcut to accomplish this feature but I don't seem to find the option

### What platform are you seeing the problem on?

Linux

### Additional context

It'd be great if it was something like sidebery or treestyletabs

https://github.com/user-attachments/assets/4cfd07e2-e711-4095-8631-fddc9204312c

**Comment by mauro-balades** [comment]
Added for the next release!
