### ISSUE TITLE
The entire URL doesn't get selected when clicking on the address bar

### ISSUE THREAD

**Issue by asuetin** [zen-browser/desktop#3473]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The default behavior in Firefox and Chromium browsers is that the entire URL gets selected when you click on the address bar. This doesn't happen in the latest version of Zen.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.0

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by Slusho64** [comment]
I agree this should behave like other browsers since it's what people expect, or at the very least there should be a copy URL button on the URL bar.

**Comment by iskandergaba** [comment]
Also reported on Windows in #3524.

In **my personal opinion**, this is a backwards step, trying to imitate Arc a little too hard. There was nothing wrong with the classic address bar, and a popup should not have been implemented in the first place.

**Comment by GRIMREAPER35487** [comment]
Yeah, lots of the recent changes with the browser as of late have just made it a worse overall experience. 

It feels like they are just changing things at this point to be different and no other reason.

**Comment by jwpincus** [comment]
Double checked this on MacOS. Can confirm issue on 1.0.2-b.0 (Firefox 133.0) (aarch64)

Tried against latest Firefox version 133.0.4 on MacOS. It doesn't use a floating URL bar, and when you click it highlights the url. So bug not present in FF.

**Comment by asuetin** [comment]
This has been fixed in 1.0.2-b1. Thanks, @mr-cheff !
