### ISSUE TITLE
Zen mods aren't downloading

### ISSUE THREAD

**Issue by RadNotRed** [zen-browser/desktop#3475]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Clicking Install Theme on a Zen Mod will not install it and will not show in the Zen Mods part of settings

https://github.com/user-attachments/assets/6c0329f7-e158-4f9b-8766-14e7ad2cc72d

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.0

### What platform are you seeing the problem on?

Linux

**Comment by amrbashir** [comment]
I had the same issue but I it is fixed for me now

**Comment by RayZ3R0** [comment]
Should be fixed now, was a website issue

**Comment by RadNotRed** [comment]
Fixed with website update
