### ISSUE TITLE
Missing shortcut/hotkey to collpase the side tab bar

### ISSUE THREAD

**Issue by amrbashir** [zen-browser/desktop#3483]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The latest release doesn't have a shortcut to collapse and expand the tab side bar, it can only be done through clicking the dedicated button, I mean this one

![image](https://github.com/user-attachments/assets/0c42a55a-2e8a-47b6-b570-f4d6da3a0276)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.0 (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by amrbashir** [comment]
The release notes mention that it removed expand on hover:
> - Removed collapsible sidebar expande on hover (mod will be available soon). This is due to the dificulty of maintaining it as we evolve the sidebar

I adjusted the issue to keep it only related to missing shortcut.

**Comment by Video-Nomad** [comment]
> The release notes mention that it removed expand on hover:
> 
> > * Removed collapsible sidebar expande on hover (mod will be available soon). This is due to the dificulty of maintaining it as we evolve the sidebar
> 
> I adjusted the issue to keep it only related to missing shortcut.

Fantastic. Another feature I used a lot removed and downgraded to a mod...

**Comment by michaelBelsanti** [comment]
For me, going into the Customize Toolbar menu and clicking Restore Defaults put it back.

**Comment by amrbashir** [comment]
I meant the keyboard shortcut, not the button

**Comment by AnhQuanTrl** [comment]
The hotkey is really convenient to switch between collapsed sidebar and full sidebar mode. I think this is a bug since it is not documented in the change log that the hot key is removed, only the hovering to expand feature.

**Comment by michaelBelsanti** [comment]
> I meant the keyboard shortcut, not the button

ah my bad, i didn't know there was a shortcut for it.

**Comment by wizzdom** [comment]
+1 on this. Never used the hover but I found the keyboard shortcut really handy.

The keybind itself seems to have been removed in [this commit](https://github.com/zen-browser/desktop/commit/3bf7a477a6abc21e8831a921c89a96b6f43d7a9b) though the underlying functionality might have been removed earlier.

It's such a shame this functionality was removed as this was one of the main reasons I migrated to zen from firefox.

**Comment by rrooddooxx** [comment]
please restore the keyboard shortcut :'(

**Comment by nijin26** [comment]
If that functionality is achievable using a "Expand Sidebar" button in the toolbar, then why should they remove the shortcut. It was one of the shortcut I've frequently used.

https://www.reddit.com/r/zen_browser/comments/1hb6uxc/why_expand_sidebar_shortcut_is_removed_while_its/

**Comment by realSilasYang** [comment]
WE WANT THE SHORTCUT BACK BADLY !!!

**Comment by nijin26** [comment]
Guys, the developer have commented about adding that shortcut back in recent reddit post.

https://www.reddit.com/r/zen_browser/comments/1hdxg25/zens_new_update_removed_my_favorite_keyboard/

**Comment by gomster** [comment]
the keyboard shortcut come back today in the last update, check in : preferences<keyboard shortcut<Other functions Zen

**Comment by rrooddooxx** [comment]
thanks for the fast response and update, love zen browser <3
