### ISSUE TITLE
Omnibox misaligned and when the address bar is clicked the url is not selected

### ISSUE THREAD

**Issue by litaniecontrelapeur** [zen-browser/desktop#3484]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![image](https://github.com/user-attachments/assets/7a5194f3-4857-4edd-845b-43ab0b33668b)

https://github.com/user-attachments/assets/bf3431e7-f9df-4e0b-aa3a-477ae17b1ea2

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.0

### What platform are you seeing the problem on?

Windows

**Comment by matdave** [comment]
I can't tell if it is a "design choice" or a bug, but I hate it. It's definitely a bug in compact mode as it goes out of the window.

**Comment by PraiseTheDuck** [comment]
Comment just to confirm the bug.

**Comment by sultaniman** [comment]
Same
<img width="1687" alt="Screenshot 2024-12-10 at 20 52 24" src="https://github.com/user-attachments/assets/78426ebb-e5fd-4d4d-b59b-c9b1cc319898">
