### ISSUE TITLE
Impossible to click back or forward when only the tob bar is hidden

### ISSUE THREAD

**Issue by litaniecontrelapeur** [zen-browser/desktop#3485]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

https://github.com/user-attachments/assets/1ac2d75d-14ae-4faa-8198-57ac5ef458cc

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.0

### What platform are you seeing the problem on?

Windows

**Comment by StepanAsk** [comment]
temp fix: https://imgur.com/8D9NLgl

**Comment by litaniecontrelapeur** [comment]
v1.0.2-b.1 still no solution
