### ISSUE TITLE
Toolbar still visible when it should be hidden

### ISSUE THREAD

**Issue by litaniecontrelapeur** [zen-browser/desktop#3488]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![image](https://github.com/user-attachments/assets/2890a1dc-8903-4081-a2ce-a685803b8521)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.0

### What platform are you seeing the problem on?

Windows

**Comment by showme032** [comment]
Same issue on MacOS version
