### ISSUE TITLE
Extension icon on the toolbar is in the wrong resolution   

### ISSUE THREAD

**Issue by quissberry** [zen-browser/desktop#35]
![image](https://github.com/zen-browser/desktop/assets/106037630/82d31826-ebe7-4ff9-b6fe-5bd58912071c)

Extension icons appear in a more flatter resolution than what it should be. 

System information: OpenSUSE Tumbleweed, GNOME, Wayland Version: 0.0.0-a.1

**Comment by mauro-balades** [comment]
Thanks a lot for this bug reports! I'll fix them ASAP. Btw, zen dream is experimental, it looks ugly right now

**Comment by mauro-balades** [comment]
Fixed in https://github.com/zen-browser/desktop/commit/df1c6af96a7dbb0de4e21e4cf59dbf69bc4071e4. Thanks a lot for these bug reports!
