### ISSUE TITLE
when i go into url bar the whole url should be selected

### ISSUE THREAD

**Issue by Likhith-18** [zen-browser/desktop#3505]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![image](https://github.com/user-attachments/assets/832cb19e-d168-45f3-bf43-0c62e1afd5f2)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Version 1.0.2-b.0 (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by tduarte** [comment]
I don't have the same issue with the opacity, it looks really different on my instance of Zen. But I do agree that an option or Zen Mod to change this behavior would be amazing.

**Comment by mr-cheffy** [comment]
This has already been fixed, thanks

**Comment by tduarte** [comment]
Just updated my build and it works as expected. Thank you @mr-cheff
