### ISSUE TITLE
Bookmarks no longer appear below search bar in any tabs other than new tab

### ISSUE THREAD

**Issue by Animaxer** [zen-browser/desktop#3508]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

After the update, bookmarks are no longer present in any tabs other than in the new tab
There are no settings that could change this.
Having the bookmarks bar would be very useful, please add an option for it to return or change it back completely.
Thank you
![image](https://github.com/user-attachments/assets/5f688703-b879-4cc5-b44c-69724b492c43)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.0

### What platform are you seeing the problem on?

Windows

**Comment by Espasant3** [comment]
I have the exact same issue on my Linux (x86 arch) with Ubuntu 24.04
