### ISSUE TITLE
Windows ARM64 Support

### ISSUE THREAD

**Issue by AdriRed** [zen-browser/desktop#351]
### What feature would you like to see?

I would like to see a native Windows ARM64 architecture version of Zen.

### What platform are you seeing the problem on?

Windows

### Additional context

Firefox already ships a Windows ARM64 version.

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/858

 ~ This is an automatic operation to better enhancements requests organization.
