### ISSUE TITLE
The full search line stretches to the end of the right side

### ISSUE THREAD

**Issue by FrigoreD** [zen-browser/desktop#3515]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Hi there! 
There is a problem with my search in compact mode. The full search line stretches to the end of the right side.
![изображение](https://github.com/user-attachments/assets/9faae9d8-428d-4ca9-91af-3c4f584a2ac0)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2

### What platform are you seeing the problem on?

Linux

**Comment by mr-cheffy** [comment]
This should be fixed now, thanks!
