### ISSUE TITLE
URL bar not centred

### ISSUE THREAD

**Issue by op-cs** [zen-browser/desktop#3516]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![image](https://github.com/user-attachments/assets/1e46bf67-bab5-4219-86d6-238e19ff631e)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.0

### What platform are you seeing the problem on?

Windows

**Comment by op-cs** [comment]
Is there anyway to get the default url bar functionality back, the floating url bar is very much not centered so it kind of is annoying to look at

**Comment by SehrGuterCode** [comment]
I think the floating URL bar is a feature, not a bug
![image](https://github.com/user-attachments/assets/28b935f2-57c3-4a18-9c3b-fd0b00f41e4c)

**Comment by op-cs** [comment]
> I think the floating URL bar is a feature, not a bug ![image](https://private-user-images.githubusercontent.com/101972908/394460642-28b935f2-57c3-4a18-9c3b-fd0b00f41e4c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4NjU2NjAsIm5iZiI6MTczMzg2NTM2MCwicGF0aCI6Ii8xMDE5NzI5MDgvMzk0NDYwNjQyLTI4YjkzNWYyLTU3YzMtNGExOC05YzNiLWZkMGIwMGY0MWU0Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMFQyMTE2MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MjUyM2M3NWM3MTBjZTI2YWI5NmViZTQ3NzA1MzRhODQ5MjE2YjU0ZDU3YmRiODE3YTE5OWJiNTFiN2NiYWY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-j8c0_WJJKP3yixjVLZUVKA1NBkY2r_UQH-iR2ObrmY)

Ah alright, still doesnt help that its not centered. If it was like arc (which I used before) then i would be fine with it but it very much isnt

**Comment by op-cs** [comment]
e.g. 
![image](https://github.com/user-attachments/assets/e135a16e-1dba-4bde-95d7-c219fdf4f82b)

**Comment by SehrGuterCode** [comment]
> > I think the floating URL bar is a feature, not a bug ![image](https://private-user-images.githubusercontent.com/101972908/394460642-28b935f2-57c3-4a18-9c3b-fd0b00f41e4c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4NjU2NjAsIm5iZiI6MTczMzg2NTM2MCwicGF0aCI6Ii8xMDE5NzI5MDgvMzk0NDYwNjQyLTI4YjkzNWYyLTU3YzMtNGExOC05YzNiLWZkMGIwMGY0MWU0Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMFQyMTE2MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MjUyM2M3NWM3MTBjZTI2YWI5NmViZTQ3NzA1MzRhODQ5MjE2YjU0ZDU3YmRiODE3YTE5OWJiNTFiN2NiYWY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-j8c0_WJJKP3yixjVLZUVKA1NBkY2r_UQH-iR2ObrmY)
> 
> Ah alright, still doesnt help that its not centered. If it was like arc (which I used before) then i would be fine with it but it very much isnt

![image](https://github.com/user-attachments/assets/5a8a7fe4-abe4-4256-b4a1-1526fc5e345c)
It's centered for me, so it's probably a bug

**Comment by op-cs** [comment]
> > > I think the floating URL bar is a feature, not a bug ![image](https://private-user-images.githubusercontent.com/101972908/394460642-28b935f2-57c3-4a18-9c3b-fd0b00f41e4c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4NjU2NjAsIm5iZiI6MTczMzg2NTM2MCwicGF0aCI6Ii8xMDE5NzI5MDgvMzk0NDYwNjQyLTI4YjkzNWYyLTU3YzMtNGExOC05YzNiLWZkMGIwMGY0MWU0Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMFQyMTE2MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MjUyM2M3NWM3MTBjZTI2YWI5NmViZTQ3NzA1MzRhODQ5MjE2YjU0ZDU3YmRiODE3YTE5OWJiNTFiN2NiYWY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-j8c0_WJJKP3yixjVLZUVKA1NBkY2r_UQH-iR2ObrmY)
> > 
> > 
> > Ah alright, still doesnt help that its not centered. If it was like arc (which I used before) then i would be fine with it but it very much isnt
> 
> ![image](https://private-user-images.githubusercontent.com/101972908/394461066-5a8a7fe4-abe4-4256-b4a1-1526fc5e345c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4NjU3ODksIm5iZiI6MTczMzg2NTQ4OSwicGF0aCI6Ii8xMDE5NzI5MDgvMzk0NDYxMDY2LTVhOGE3ZmU0LWFiZTQtNDI1Ni1iNGExLTE1MjZmYzVlMzQ1Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMFQyMTE4MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZmRiMjUwY2Q5NWE3Mzk0OTY0OWI0MWMyZjEzMmMwMTg4OWY2OGRiZjlhMzlkZDhiZWI3YzhjY2FlNTg3NmMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.298jTvsNC5rE3ub9GuReVuIan5SWjeUngGkFX9wADAc) It's centered for me, so it's probably a bug

could possibly be issue with aspect ratio in this case? laptop is an unconventional 1920*1200, though this should have been accounted for already.

**Comment by BowDown097** [comment]
I made CSS that reverts the URL bar if you wanna do that, should work fine. Look up userChrome.css to learn how to inject this into the browser: https://gist.github.com/BowDown097/68d9240d659c879149d7ea0f53f7cc2f

Also made some about:config preferences for it - defaults are more like the old URL bar, enabling ``zen.urlbar.breakout`` will make it more like the current URL bar, but still with some changes because it looks terrible back in the default position otherwise.

**Comment by abhigyantrips** [comment]
bump, the URL bar seems to be anchored relative to some other component that's not centered.

**collapsed toolbar mode:**

![image](https://github.com/user-attachments/assets/61f6d6db-dec9-49a2-96b7-6af68e869737)

**single toolbar (compact) mode:**
this seems to be centered but then there's an empty search bar in the left? i think expected behavior would be for that to disappear (or for the tabs sidebar to not open at all while changing the link)

![image](https://github.com/user-attachments/assets/62e28088-3790-475a-a578-42d6e45add1b)

**multiple toolbars (again, compact mode):**

![image](https://github.com/user-attachments/assets/905e054d-3237-41c5-a3f3-4d297a5ffe93)

in general it isn't looking great for compact mode

**Comment by Yaazor** [comment]
Having the same issue + idk if it's intended, but the fact that the URL text is not selected by default when clicked makes navigation somewhat counterintuitive bcz I need to CTRL+A before typing a new URL (or copying the current one)

**Comment by op-cs** [comment]
> I made CSS that reverts the URL bar if you wanna do that, should work fine. Look up userChrome.css to learn how to inject this into the browser: https://gist.github.com/BowDown097/68d9240d659c879149d7ea0f53f7cc2f
> 
> Also made some about:config preferences for it - defaults are more like the old URL bar, enabling `zen.urlbar.breakout` will make it more like the current URL bar, but still with some changes because it looks terrible back in the default position otherwise.

This works really great, have you thought maybe putting it onto the mod store since it is just css? I implemented the css as if it was a mod.

**Comment by op-cs** [comment]
> > I made CSS that reverts the URL bar if you wanna do that, should work fine. Look up userChrome.css to learn how to inject this into the browser: https://gist.github.com/BowDown097/68d9240d659c879149d7ea0f53f7cc2f
> > Also made some about:config preferences for it - defaults are more like the old URL bar, enabling `zen.urlbar.breakout` will make it more like the current URL bar, but still with some changes because it looks terrible back in the default position otherwise.
> 
> This works really great, have you thought maybe putting it onto the mod store since it is just css? I implemented the css as if it was a mod.

only issue I have now is that the theme of the bar is still solarized / beige when I do not want that. I have to use an external light mode firefox theme to get normal lightmode but this still doesnt apply to the url bar

**Comment by abhigyantrips** [comment]
i don't think anyone's facing this issue on the latest version?

**Comment by abhigyantrips** [comment]
i guess it's still dependent on the sidebar position to center itself, which i **assume** isn't intended.


https://github.com/user-attachments/assets/317f518e-bcba-488d-a219-c32e43d428a9

**Comment by check24-tkilian** [comment]
looks like I am going back to firefox after next broken release :/

**Comment by op-cs** [comment]
> looks like I am going back to firefox after next broken release :/

FYI they added an option in settings to bring back the old url bar. only problem is if you are using a normal lightmode theme the url bar is still solarised / beige.
