### ISSUE TITLE
Expand-on-hover gets glitched on the right sidebar

### ISSUE THREAD

**Issue by llocphann** [zen-browser/desktop#352]
### What happened?

When the sidebar expands on hover, it gets glitched and the buttons sometimes don't work.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.24

### Severity impact

Low

### What platform are you seeing the problem on?

Linux

**Comment by Kengetsu** [comment]
I also noticed this similar behavior but mine also had flickering when hovering. I'm on Windows with 1.0.0-a.24

**Comment by llocphann** [comment]
devs fixed on version 1.0.0-a.26
