### ISSUE TITLE
Expandable Vertical Tabs No Longer Available as of 1.0.2-b.0

### ISSUE THREAD

**Issue by Octa9821** [zen-browser/desktop#3522]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I am using the vertical tabs minimized and I like them being expandable on hover. This was an existing feature in the previous version. 

With the new update, that feature is missing from the settings, as you can see in this screenshot:

<img width="1422" alt="image" src="https://github.com/user-attachments/assets/afc175f6-09e5-4758-bf36-c06f7cd80f52">

I'm thinking this is a bug as I don't see why this feature would be removed.

Not reproducible on Firefox since it doesn't have vertical tabs. 

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.0

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by raash1d** [comment]
do you mean expandable on hover?

**Comment by Mukesh-Kalikaya** [comment]
I am also facing the same issue. I had to revert to the old version because the new one can't expand tabs on hover.

**Comment by MrPiggy105** [comment]
_pssst... you can still get the expand sidebar icon from the 'customise toolbar' menu and use that to collapse/expand it. There is also a setting in the look and feel section to use only the collapsed sidebar. Just not on hover, and no shortcut._

<img width="42" alt="Screenshot 2024-12-11 at 11 16 16 am" src="https://github.com/user-attachments/assets/44b57613-5260-4d3b-bf63-d3aa7bedbb9c">

<img width="1549" alt="Screenshot 2024-12-11 at 11 17 11 am" src="https://github.com/user-attachments/assets/3ddc553a-4348-40bd-88f0-e60b9fe66b43">

**Comment by Octa9821** [comment]
> do you mean expandable on hover?
yes, right. that's what i meant. i wrote on click by mistake, but i meant on hover in the initial posting. edited it now.

**Comment by Octa9821** [comment]
> _pssst... you can still get the expand sidebar icon from the 'customise toolbar' menu and use that to collapse/expand it. There is also a setting in the look and feel section to use only the collapsed sidebar. Just not on hover, and no shortcut._
> <img alt="Screenshot 2024-12-11 at 11 16 16 am" width="42" src="https://private-user-images.githubusercontent.com/100971521/394508277-44b57613-5260-4d3b-bf63-d3aa7bedbb9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4Nzk0OTksIm5iZiI6MTczMzg3OTE5OSwicGF0aCI6Ii8xMDA5NzE1MjEvMzk0NTA4Mjc3LTQ0YjU3NjEzLTUyNjAtNGQzYi1iZjYzLWQzYWE3YmVkYmI5Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMVQwMTA2MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zODZlOGJmMGVhODZmNWJlOWRkZWE1NTYzMjNiY2FjZmZkNzMzZGJlZDBjZDNkZDFkNzY2ODlkY2I4OTlhYTdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JHRKdsPIsf8T0FEXiirt9neAyjpkz0iX-5Pda8ejkFg"> <img alt="Screenshot 2024-12-11 at 11 17 11 am" width="1549" src="https://private-user-images.githubusercontent.com/100971521/394508466-3ddc553a-4348-40bd-88f0-e60b9fe66b43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4Nzk0OTksIm5iZiI6MTczMzg3OTE5OSwicGF0aCI6Ii8xMDA5NzE1MjEvMzk0NTA4NDY2LTNkZGM1NTNhLTQzNDgtNDBiZC04OGYwLWU2MGI5ZmU2NmI0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMVQwMTA2MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNThmM2Q1NmU5MjAxMjBkNDc3N2VhMjJiZTA3MmMxNTNlOTIyYTg1OTJmMzE4NmNlODYwNDlmNzE1NjVhZDEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.OsnDPsBmRLvVrSvbm5Siea8GD7KG0w5F6rX7VX8G6PE">

yeah sorry, i was referring to expandable on hover. that button doesn't help when you just wanna take a quick glance over the open tabs by simply throwing the cursor over to the side.

**Comment by MrPiggy105** [comment]
﻿Yeah they removed that sorry. I believe there is a mod that does it although I don’t know how well it works.

**Comment by bdbd2yy** [comment]
After today's update, I also noticed this issue. For someone accustomed to using a hover-to-expand sidebar workflow, this is really hard to adapt to.And I also chose to roll back to a previous version.

**Comment by raash1d** [comment]
For now, I have enabled the following to replicate similar behavior of expand on hover
1. Enabled multiple toolbars (Settings > Look and Feel > Multiple toolbars)
![image](https://github.com/user-attachments/assets/a9a54920-9620-4fbe-b752-c3b0d76ef64d)

2. Enabled compact mode (Settings > Look and Feel > Theme Settings)
![image](https://github.com/user-attachments/assets/f7d48a80-8234-45c2-a831-6ff745b55ea3)

Now if I take my mouse to the left, the tabs come in view expanded, simulating the expand-on-hover behavior. This is not ideal, but it is what I could work with.
![image](https://github.com/user-attachments/assets/ccddcc2a-5416-443d-b698-aff5fdd72b54)

@MrPiggy105 , can you link to where they announced this was going to be removed/discontinued? (I couldn't find it in the issues or discussion tabs)

**Comment by bdbd2yy** [comment]
Thank you for sharing! I found another potential fix in the discussion forum that might be closer to the original behavior: installing the "Sidebar Expand on Hover" Zen module. Disabling compact mode and choosing any Browser Layout allows the hover-to-expand functionality to work as before！

**Comment by MrPiggy105** [comment]
Here is a mod that (sketchily) implements this... it's a little weird but the creator will probably improve it. 
https://zen-browser.app/mods/bd92a9a0-1c00-4187-a66e-94c389fa5a59/

As for why? In the [release notes](https://zen-browser.app/release-notes/#1.0.2-b.0) under breaking changes they say it was becoming difficult to support.

**Comment by mateuszkozakiewicz** [comment]
This is a major feature should be supported even though difficult, especially since the mod does it better than original ever was.

**Comment by acdcbyl** [comment]
There is no doubt that this is a very useful feature. It would be a great shame if it was removed.

**Comment by DudeSjef** [comment]
The release notes of version 1.0.2-b.0 state the following:

> Removed collapsible sidebar expande on hover (mod will be available soon). This is due to the dificulty of maintaining it as we evolve the sidebar.

So unfortunately it seems to be removed on purpose.

There is a Zen mod called "Sidebar Expand on Hover" which replicates this feature, although I don't think that this is the mod the Zen team promised as the Author does not seem to be affiliated. It also does not work as well as the expandable sidebar used to work.

**Comment by Octa9821** [comment]
> For now, I have enabled the following to replicate similar behavior of expand on hover
> 
>     1. Enabled multiple toolbars (Settings > Look and Feel > Multiple toolbars)
>        ![image](https://private-user-images.githubusercontent.com/15528027/394589814-a9a54920-9620-4fbe-b752-c3b0d76ef64d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5NDI4MzEsIm5iZiI6MTczMzk0MjUzMSwicGF0aCI6Ii8xNTUyODAyNy8zOTQ1ODk4MTQtYTlhNTQ5MjAtOTYyMC00ZmJlLWI3NTItYzNiMGQ3NmVmNjRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjExVDE4NDIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjYjczMzU4Nzg4YjljOWYzZWU2MzM2NGRjMTc0MWMxM2IwNmJjNmY0ZjU2Nzk1MjNlMzM5YmU1ODA1NDhiODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qjdGpW0bjlBAL3NDls5x3pgM0ktnu_deYccUiCG42VM)
> 
>     2. Enabled compact mode (Settings > Look and Feel > Theme Settings)
>        ![image](https://private-user-images.githubusercontent.com/15528027/394590515-f7d48a80-8234-45c2-a831-6ff745b55ea3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5NDI4MzEsIm5iZiI6MTczMzk0MjUzMSwicGF0aCI6Ii8xNTUyODAyNy8zOTQ1OTA1MTUtZjdkNDhhODAtODIzNC00NWMyLWE4MzEtNmZmNzQ1YjU1ZWEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjExVDE4NDIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlZjBkZmVmNTE0MDIxZGI4MzViYmE0NjdlNmUzYTA3NGRjOTAxZGViMWU0ZDBjN2I5MzhhY2Y3Y2Q2ZmE1ZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.H8ldxdYJ55AEo08Y0Ca2RI6jTi493evL7G97crkOVvE)
> 
> 
> Now if I take my mouse to the left, the tabs come in view expanded, simulating the expand-on-hover behavior. This is not ideal, but it is what I could work with. ![image](https://private-user-images.githubusercontent.com/15528027/394591858-ccddcc2a-5416-443d-b698-aff5fdd72b54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5NDI4MzEsIm5iZiI6MTczMzk0MjUzMSwicGF0aCI6Ii8xNTUyODAyNy8zOTQ1OTE4NTgtY2NkZGNjMmEtNTQxNi00NDNkLWI2OTgtYWZmNWZkZDcyYjU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjExVDE4NDIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2ZTk4OTMwMTdhODhlYjI5YmNmM2M3Zjc0NDE0YWRlYzVhMmE0MTk5YjM5OTllMDhlYTMxMjgyODRlZjg5MjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.R2yi9BBIbz3POgtiBwTnzWH7wtEL1WlsSRrTktRMTYs)
> 
> @MrPiggy105 , can you link to where they announced this was going to be removed/discontinued? (I couldn't find it in the issues or discussion tabs)

yeah this is still terrible since now you can't glance over the tabs and just get a rough idea of what sites you have open based on the favicons. 
it's also a buggy mess as far as i can tell:

![image](https://github.com/user-attachments/assets/5d04a9a8-502a-4eeb-b394-b2bff7194148)

i'm going to wait a bit for a mod for this, hoping that someone would make one soon.

**Comment by CraftingDragon007** [comment]
Honestly it's not even a surprise, because we had the same problem already with 1.0.1-a.19. But back then it was added back in 1.0.1-a.22. It's still sad to see this feature go away, because many people (including me) only use/used Zen because of that feature. If they won't add it back again, I swear I'll just use Microsoft Edge again cause it also has this feature with vertical tabs. https://github.com/zen-browser/desktop/issues/3250

**Comment by sam-be** [comment]
> Thank you for sharing! I found another potential fix in the discussion forum that might be closer to the original behavior: installing the "Sidebar Expand on Hover" Zen module. Disabling compact mode and choosing any Browser Layout allows the hover-to-expand functionality to work as before！

With one exception, as far as I can tell - which is that when using the 'Sidebar Expand on Hover' mod with the collapsed layout, there is no 'x' appearing over the expanded tabs in order to close them.

This is a broader question I have with Zen Browser if not using full-size tabs. How are you supposed to close them?

**Comment by MrPiggy105** [comment]
> This is a broader question I have with Zen Browser if not using full-size tabs. How are you supposed to close them?

In response to that, it's not really great, you would have to right click and press 'close tab', go to the tab and use ctrl + w (or cmd + w on mac) install a mod which shows a small `(x)` on the top-right corner of collapsed tabs.

**Comment by MrPiggy105** [comment]
Haven’t tested it yet, but new update b2 readds the shortcut to expand the tabs.

**Comment by raash1d** [comment]
> Haven’t tested it yet, but new update b2 readds the shortcut to expand the tabs.

Oh well, if that's how it is going to be, then I would rather go back to Firefox. Vertical tabs and "click to expand" is already coming to it. It is there in the nightly builds already, should be released into beta and then stable very soon. I do hope Zen have figured out the "hover to expand".

@mr-cheff

**Comment by johnsonjamees** [comment]
It's a real shame that this feature was removed. This functionality was such a fundamental part of the whole vertical tabs experience, and I reckon a lot of users making the switch from Chromium-based browsers like Edge would have a hard time adapting to it. I had finally made plans to switch to Firefox-based browsers after Chrome introduced Manifest V3, but I guess I'll have to keep using Edge until the developers figure this out.

**Comment by CraftingDragon007** [comment]
> It's a real shame that this feature was removed. This functionality was such a fundamental part of the whole vertical tabs experience, and I reckon a lot of users making the switch from Chromium-based browsers like Edge would have a hard time adapting to it. I had finally made plans to switch to Firefox-based browsers after Chrome introduced Manifest V3, but I guess I'll have to keep using Edge until the developers figure this out.

Yes indeed, I'll also continue to use Edge if they won't add it back.

**Comment by mr-cheffy** [comment]
I'm not adding it back, sorry. It's too much to maintain

**Comment by johnsonjamees** [comment]
> There is a Zen mod called "Sidebar Expand on Hover" which replicates this feature,

Looks like this is broken in the latest beta release.

**Comment by vraravam** [comment]
> I'm not adding it back, sorry. It's too much to maintain

I was very hopeful that this feature would come back into the main / core browser. If this is not going to happen, can we at least get the mod to work correctly? (for now, for eg, after the sidebar auto-expands on hover, the text of the mod gets "hidden" in case of a website that's being viewed in light mode while the system theme is set to dark mode. If at least the background color of the expanded sidebar remains consistent with the background of the sidebar itself - that at least would suffice to repair the mod back to a working state.

btw - how can the community contribute to the mod's repo with PRs? Is there any documentation for that which might help reduce the pressure on maubg?

**Comment by opticSquid** [comment]
> I'm not adding it back, sorry. It's too much to maintain 

Ok can we create a issue for it.. may be we community can lend a hand in bringing it back

**Comment by opticSquid** [comment]
> > I'm not adding it back, sorry. It's too much to maintain 
> 
> Ok can we reopen the issue.. may be we community can lend a hand in bringing it back

**Comment by juand89** [comment]
Hey guys check VerticalFox repo https://github.com/christorange/VerticalFox
I've managed to make it work with Zen—just follow the instructions, that's it. Also, you need to have Sidebery installed. To be honest, it has a better look and feel than the original tab sidebar.
Also there is the zen mod and addon of sidebery for zen browser that displays same effect.

**Comment by LancerGM** [comment]
> Hey guys check VerticalFox repo https://github.com/christorange/VerticalFox I've managed to make it work with Zen—just follow the instructions, that's it. Also, you need to have Sidebery installed. To be honest, it has a better look and feel than the original tab sidebar. Also there is the zen mod and addon of sidebery for zen browser that displays same effect.

Hey, I'd really like to know how you made it work. I have VerticalFox working fine on Firefox, but on Zen, the old tab tar is still there, but empty. Also, the Sideberry tab bar is not expanding.

**Comment by vraravam** [comment]
> I have VerticalFox working fine on Firefox,

If you are on one of the latest FF nightlies, this "expand on hover" is now built into FF itself.
