### ISSUE TITLE
Bug: Floating URL Bar Disappears When Using Chinese Input Method

### ISSUE THREAD

**Issue by muhac** [zen-browser/desktop#3525]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

A Chinese input method (and possibly Japanese and Korean) has a pop-up window that allows the user to select candidate words. When inputting Chinese, the pop-up window jumps to the location where the URL bar originally was (top left or top center), causing the floating URL bar to disappear. After selecting (finalizing) the input words, the floating URL bar reappears, and this back-and-forth behavior continues.

\* The Windows recording is of poor quality – it can only capture the main window. It is provided for demonstration purposes.

https://github.com/user-attachments/assets/e1e142f5-1609-403e-a8de-9529d1200b14

There was no issue in the alpha version or with other traditional URL bars where the input area is located the same.

https://github.com/user-attachments/assets/7d99c713-d1d4-459f-ac7d-d2c75a55ff11

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.0

### What platform are you seeing the problem on?

Windows, macOS - aarch64

**Comment by ao-t** [comment]
settings -> firefox labs -> address bar: ...

**Comment by yhshzh** [comment]
> settings -> firefox labs -> address bar: ...设置 -> 火狐实验室 -> 地址栏：...

It works well for me, thank u bro😘
