### ISSUE TITLE
Round corners missing in Flatpak version

### ISSUE THREAD

**Issue by marko19914** [zen-browser/desktop#353]
### What happened?

Zen browser interface edge and corner look like this:
![Screenshot from 2024-08-20 20-13-28](https://github.com/user-attachments/assets/97376676-f481-440d-9af6-48398ac464a0)

While in Firefox the same corner looks like that:
![Screenshot from 2024-08-20 20-13-04](https://github.com/user-attachments/assets/83a9540d-9c82-490c-b05c-334f9e12e740)

Taking in account that in Windows interface the corner is round, these are also probably supposed to be round.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a23

### Severity impact

Low

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
System:
  Host: ****** Kernel: 6.1.0-10-amd64 arch: x86_64 bits: 64
    Desktop: GNOME v: 43.9 Distro: Debian GNU/Linux 12 (bookworm)
```

**Comment by nellfs** [comment]
I’m experiencing the same issue; Even when I enable `widget.gtk.rounded-bottom-corners.enabled` in `about:config`, Zen doesn’t round the corners. I’m also using GNOME, and I can confirm that it’s not just an issue with the Flatpak version, the portable version has the same problem. It seems to be more related to Zen’s overlay theme rather than the installation method.

OS: Arch Linux
Kernel Version: Linux 6.10.4-arch2-1
Desktop Enviroment: Gnome 46

Zen Browser Flatpak 
Version: 1.0.0-a.15

![image](https://github.com/user-attachments/assets/94174fc3-214d-4dff-b1cf-6fcb833a6c62)

**Comment by marko19914** [comment]
I think there was an issue with gnome extension "Dash to Dock" not being able to draw round corners on the dock on Arch based distros. Not sure if it is relevant. Probably not.

Just noticed that flating toolbar effect extends to the expected size of the window but it doesn't cover corner which are poking out :D
![Screenshot from 2024-08-21 00-53-39](https://github.com/user-attachments/assets/2f3156d0-ebf3-48fa-98de-e89e08f47a40)

**Comment by sound-friend** [comment]
same here. fedora 40, gnome 46, flatpak. also tried an arch distrobox (from AUR), same thing. would love rounded corners :3

**Comment by nimafanniasl** [comment]
Hey! I installed Zen from AUR and I don't have rounded corners as well :D

**Comment by ottergauze** [comment]
This is present on both the AppImage and Flatpak "Optimised" builds on KDE Plasma 6.1.3.

**Comment by marko19914** [comment]
Default profile Is now fine. Every other profile gets created doesn't really have rounded corners
![image](https://github.com/user-attachments/assets/316ead4f-62e3-479f-a77f-f1617c073baa)
The auto theme is normal in Default Profile. Upper edge looks normal in light theme under non-primary profile.

**Comment by marko19914** [comment]
@mauro-balades You asked to be pinged on discord. Theming is weird in secondary profiles, would be a synopsis.

**Comment by mauro-balades** [comment]
This has been fixed, thanks!
