### ISSUE TITLE
Close, Minimize and Fullscreen buttons not showing up in single titlebar mode

### ISSUE THREAD

**Issue by s-sannidhi** [zen-browser/desktop#3534]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

As the title says, sometimes, the buttons for close, minimize and full screen disappear in single titlebar mode and when its in double, it goes over to the right next to the reload button and the forward and back.

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.0

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by mr-cheffy** [comment]
Does this still happen?

**Comment by s-sannidhi** [comment]
Not anymore after the new patch

**Comment by mr-cheffy** [comment]
Great!
