### ISSUE TITLE
Font rendering broken when scaling PDFs

### ISSUE THREAD

**Issue by JSGRD22** [zen-browser/desktop#3537]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I am almost certain this has been reported before but could not find anything, so I am making this new issue.
Font rendering is broken at high magnification levels on PDFs.

This is a sample PDF on 250% scale.
![image](https://github.com/user-attachments/assets/3e06cd6d-fb16-42f7-b660-c55749c10863)

This is the same PDF on 550% scale.
![image](https://github.com/user-attachments/assets/ec4b1004-6111-4d37-a9f7-7fc0323d39d2)

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.0

### What platform are you seeing the problem on?

Windows

**Comment by dshan12** [comment]
I have the same exact issue I might need to change from the zen browser cause I need to use google docs and pdfs all the time for my work. Please fix this

**Comment by urbanlutz** [comment]
Same issue here. The same behavior is not present in Firefox.

**Comment by JSGRD22** [comment]
Duplicate of #3238. Thanks for pointing this out. I will close this issue to avoid spam.
