### ISSUE TITLE
zIndex window button

### ISSUE THREAD

**Issue by d-strygwyr** [zen-browser/desktop#3538]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

when opening the sidebar the control action (3 icons on top) does not work correctly

https://github.com/user-attachments/assets/3b304c4e-e2f2-4392-9e57-33f873cfaf9a

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.0

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by gnc-07** [comment]
I believe this is already fixed for the next version. Just to make sure you can try installing the latest twilight version and see if the issue still occurs there.
