### ISSUE TITLE
Tab and Bookmark Bars

### ISSUE THREAD

**Issue by Kengetsu** [zen-browser/desktop#354]
### What feature would you like to see?

# General Suggestions
- Add hover text to the icons on the tab bar so you know what each icon does. Probably not a issue when you've used the browser for a bit but as a new comer it took a bit to figure out which each of the buttons did, hover text would just make that process faster.
- Browser setting sync alternative. I use Firefox sync for all my firefox stuff but it causes problems when syncing to zen since I have a ton of extensions and customizations applied to firefox to achieve similar stuff to what zen is doing so having an alternative way to sync (even if it's something manual) would be nice since then I can have one set of configs for zen and the other for firefox.

# Tabs and Bookmark Suggestions
## Compact mode tab bar positioning
- It would be nice if we could move the tabs to the right side. I noticed there is a button for tabs on right but that doesn't seem to apply in compact mode.
- Bookmark window/tab would be great if this had an option to be attached to the tabs window that way you can cycle between them and would remove the issue that the tabs bar gets in the way when you click bookmarks since the bookmarks tab spawns under tab bar.
- Bookmark window/tab placement alternative functionality to what is specified above but it would be equally nice to have. If you could place the bookmark bar as a hover option on the right side of the screen similar to what can be done with the tab bar in compact mode. This would allow for left to be active tabs and right to be bookmarks.
- Ability to customize how bookmarks are opened either in-same tab (as is currently), as a new tab, or in a new window. 

## Zen Sidebar
- Ability to switch/move the placement of the sidebar. Specifically to the right side but maybe even top and bottom would be nice.
- I ABSOLUTELY love the window splitting functionality. If this could be expanded into the sidebar that would be awesome too.

## Window Splitting
- Add a right click option to unsplit windows without having to use the hotkey (please don't remove the hotkey but have both instead)
- Some way to change split windows like if I have a 2 window split and click one window then double click a different tab, can that window in the split be swapped with the clicked tab (don't close the switched window but instead just swap the one in the layout)
- Split window grouping or some sort of identifier in the tab bar that indicates which tabs are currently split. As it stands right now if you had like 20 tabs open and did a split view with the top tab and bottom tab there is no way of knowing which tab is in the view and potentially would need you to scroll through the list in order to get to the top tab or bottom one to get back into your view. 

I'm a newcomer for this browser but these were some of the features that immediately popped into my head that would be nice additions. 

### What platform are you seeing the problem on?

Windows

### Additional context

I'm currently coming from a Firefox installation using sidebery and some custom vertical tab code I wrote so that's where some of my suggestions are coming from as reference and i'm using compact mode with default expanded in zen to match a similar functionality.

**Comment by Furdox** [comment]
I wish the sidebar could be on the right
