### ISSUE TITLE
Tab Bar Hover Expansion Edge Detection Issue

### ISSUE THREAD

**Issue by Kengetsu** [zen-browser/desktop#355]
### What happened?

When the browser is in the expand on hover mode there is a bit of strange behavior depending on how far to the edge of the screen your hover is. Like if it's all the way to the edge the bar is a bit more compact and tabs don't have text but if you are a little more toward the center it looks correct. This only seems to apply while in full screen (assuming it's something to do with the code checking the edge of the actual screen)

https://github.com/user-attachments/assets/c6e222b3-8c4c-48c4-a81a-6252ea3ccd9a

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.24

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
We are aware, fixed for the next release. Thanks!
