### ISSUE TITLE
Missing options in "Show in compact view" in settings.

### ISSUE THREAD

**Issue by kuqquk** [zen-browser/desktop#3556]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Under `Settings -> Look and Feel -> Theme Settings -> Show in compact view`, there were some sketch plots showing "hide toolbar", "hide sidebar", and "hide both", now they are gone.

But you still can find these settings by right-click on the sidebar and under "compact mode".

![Screenshot 2024-12-11 094016](https://github.com/user-attachments/assets/0bf86803-ef37-464e-9114-aa1337fda657)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.0 (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by orangepancakes** [comment]
They deleted the option again as it already disappeared in one update and reappeared in another. Hopefully they will fix this as I don't see a reason to use Zen over Firefox without this option of having collapsed sidebar that expands on hover.

**Comment by Thalita-G** [comment]
I can still see the options in the context menu itself (when right-clicking the toolbar or sidebar). However, when using the single toolbar layout, the sidebar is always hidden regardless of the option you've chosen, whereas hiding and showing the toolbar still works. Other layouts seem to work fine with compact mode.

**Comment by RayZ3R0** [comment]
@kuqquk  Are you using single toolbar mode where the url bar is on the sidebar? If so then that is intentional

**Comment by kuqquk** [comment]
> @kuqquk Are you using single toolbar mode where the url bar is on the sidebar? If so then that is intentional

No, I'm using multiple toolbars. But in the latest version 1.0.2-b.2 (64-bit). The sketch plots are back.

The 'sketch plots' I mean are these three boxes:
![aa](https://github.com/user-attachments/assets/1ed93ea6-08db-4642-8f09-af0a3fbb57a1)

Thanks, anyway.

**Comment by ethylon** [comment]
Expanding on hover was very useful. Now I have to rely on the "Expand sidebar" button, which is very slow.

**Comment by mr-cheffy** [comment]
They are hidden when using single toolbar, because why would there be an option to hide the top bar if there's no top bar?
