### ISSUE TITLE
Tab Bar Compact Mode Issues

### ISSUE THREAD

**Issue by Kengetsu** [zen-browser/desktop#356]
### What happened?

There is a couple of issues when using the compact mode when the hover makes accessing certain parts of other UI difficult. Namely with the bookmarks and with the sidebar due to the location of some of the buttons. Not sure what is the best way to resolve this but potentially making the hover zone smaller?

Update: Just adding another case here, this also affects the dev tools bar in the case that you can't click on the element picker since it's too far to the left. Again easily worked around just inconvenient. 

https://github.com/user-attachments/assets/7fbdd22e-79c8-4347-9eda-3862cbc70aa1

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.24

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
This is fixed for the next release 👍🏽

**Comment by Kengetsu** [comment]
Not entirely sure what changed between a.26 and a.27 but I feel like the zone trigger issues have regressed from what was present in a.26. a.26 was a marked improvement to compact mode compared to what I originally reported in a.24 but now in the latest version I feel like it's taken a step back again. I would need to setup a second install to truly compare but just going by feeling after the update I seem to have more issues selecting things when they are in the far left corner.
