### ISSUE TITLE
Cannot click the "X" to close a window

### ISSUE THREAD

**Issue by NTICompass** [zen-browser/desktop#3571]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I am using `zen-browser-avx2` version `1.0.2.b.0` on Fedora 41, with KDE Plasma (Wayland).

Among other weirdness (like KDE showing a "wayland" icon in the toolbar when Zen is open, instead of using the pinned Zen icon, that's not the issue I'm reporting here), I cannot click the "X" in the upper-right of the window to close it.

When you hover over the buttons, I get a hover background for minimize/maximize, but not for close.  When I click on close, nothing happens.

Here is a video of the issue: https://youtu.be/veOZyipMIHM

I also noticed this same issue on Windows 11.  I tried going to "customize toolbar" and clicking "reset" and that didn't fix it.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.0

### What platform are you seeing the problem on?

Linux, Windows

**Comment by NTICompass** [comment]
UPDATE: This issue only happens when the sidebar is collapsed and is on the right.  Unchecking "tabs on the right" lets me click on the "X", so does expanding the (right-side) side bar or going to "single toolbar mode".

Could this be related to #3538?

**Comment by alepouna** [comment]
potentially related #2708

**Comment by mikidam14** [comment]
> UPDATE: This issue only happens when the sidebar is collapsed and is on the right. Unchecking "tabs on the right" lets me click on the "X", so does expanding the (right-side) side bar or going to "single toolbar mode".
> 
> Could this be related to #3538?

I can confirm that I managed to reproduce this behavior on Ubuntu 24.04.1 with GNOME (Wayland) (I am also on version 1.0.2-b.0 of Zen).

**Comment by mr-cheffy** [comment]
Ill move this into https://github.com/zen-browser/desktop/issues/3803
