### ISSUE TITLE
User Change Error

### ISSUE THREAD

**Issue by LorenzoColitta** [zen-browser/desktop#3579]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Hello,
I tried to switch to my alternate profile in Zen Browser, but it does not launch nor open in any way.

System Specs: 
Windows Version 23H2 (OS Build 22631.4460)
Windows Feature Experience Pack 1000.22700.1047.0
8 gb Ram
128 gb SSD
Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2

### What platform are you seeing the problem on?

Windows

**Comment by digiaust** [comment]
I'm also experiencing this issue. Clicking on the profile button brings up the window with all your profiles, but when clicking into another profile, it doesn't open. 

we've resorted to going to about:profiles and launching profiles from there, although, sometimes the "Launch this profile in a new window" button is missing from here as well until you completely quit zen and re-open.

**Comment by LorenzoColitta** [comment]
i do have launch this profile in a new window but when i click it it doesn't work

**Comment by justDeeevin** [comment]
Duplicate of #3495

**Comment by LorenzoColitta** [comment]
With an update, this issue as been resolved
