### ISSUE TITLE
"Private Browsing" text doesn't fit in collapsed sidebar.  Also, it's shown on the window twice.

### ISSUE THREAD

**Issue by NTICompass** [zen-browser/desktop#3580]
### Captchas

- [x] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.

### What happened?

When opening a Private Browsing window, the text "Private Browsing" appears twice.  Once next to the address bar and once in the sidebar/tabbar.

When the sidebar is collapsed, then the text doesn't fit and gets cut off on one side and spills out into the page on the other.

I tried removing the "account" icon from the sidebar thinking it would fix this, it didn't.

![Screenshot_20241211_102804](https://github.com/user-attachments/assets/4adb157e-8f90-4de1-a4c1-b2e579653fca)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.0

### What platform are you seeing the problem on?

Linux, Windows

**Comment by LorenzoColitta** [comment]
I have it too
