### ISSUE TITLE
Clicking search results in new floating URL doesn't openlinks

### ISSUE THREAD

**Issue by soratoyuki** [zen-browser/desktop#3581]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The new floating URL/search bar (which I strongly dislike but can't find a way to disable) doesn't seem to actually be operable. If I type in the first few letters of a website and then click on the search result, the floating bar collapses without opening the clicked result.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.0 (Firefox 133.0) (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by kittybwained** [comment]
This looks like a duplicate of #3540

**Comment by soratoyuki** [comment]
Oof it is. I did spend some time searching but missed that one, it seems.

**Comment by 12th-devs** [comment]
@soratoyuki dev is trying to clean out issues, do you care to comment on the related issue as a hotlink and close it as well? Please and thank you.
