### ISSUE TITLE
Address bar popping out

### ISSUE THREAD

**Issue by yoonthegoon** [zen-browser/desktop#3584]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

Zen Browser: 1.0.2-b.0 (20241210102946)
Firefox 133.0.3 (not reproducible on Firefox)
OS: macOS 15.1.1 24B91 arm64

After upgrading to 1.0.2-b.0, whenever I type in the address bar, it pops out <img width="1511" alt="image" src="https://github.com/user-attachments/assets/cc6b37c7-d6dc-4306-8a20-41d317e377eb" />

EDIT: Search also appears to not show suggested results from search engine used, even with "Suggestions from Zen Browser" and "Suggestions from sponsors" enabled. This may also be another skill issue on my part, but I haven't changed any settings of my own between upgrading versions.

I looked in settings under look and feel, appearance, and searched for address bar and for focus and was unable to find any settings relevant.
I've turned off all Zen Mods but the issue persists.
Searching for the issue online, I wasn't able to find anyone facing the same problem nor any setting to change this (though my search-fu skill has deteriorated over time).

I upgraded Firefox to test if this comes from there, but after doing so, I cannot reproduce the issue.

If this is simply a skill issue in being able to change a setting, please let me know.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.0 (20241210102946)

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by vesk4000** [comment]
I really hope that there's a fix/option for this soon, because the floating url bar just looks awful if you have the url bar at the top (multiple toolbar option). I really appreciate the work that the devs are doing all for free, but I'm just annoyed cause I got my browser to be exactly the way I wanted it, but then this update happened and kinda screwed with it. (It's really just this new floating url bar though, and the fact that I was shown the setup screens again, but that's not a big deal at all).

**Comment by yoonthegoon** [comment]
Glad I'm not the only one who faced both. Didn't think anyone else did as there weren't any issues on the matter before I opened this.

**Comment by Bazimek** [comment]
Ye it is really bad and it even do not select the URL when click inside the URL bar. Awfull

**Comment by miguelcollaco** [comment]
I'm also having the same issue, some little bugs are normal and understandable as the project is being maintained by a single dev, but this one needs to be fixed ASAP.

**Comment by aksdb** [comment]
Additionally it doesn't honor custom theme colors:
![image](https://github.com/user-attachments/assets/e0153d6e-f85c-473f-b88d-564a483b7097)
(That could be worth another ticket, though.)

**Comment by yoonthegoon** [comment]
Also highlighting my edit:

> EDIT: Search also appears to not show suggested results from search engine used, even with "Suggestions from Zen Browser" and "Suggestions from sponsors" enabled. This may also be another skill issue on my part, but I haven't changed any settings of my own between upgrading versions.

This may also be worth another issue, but I'll wait for this one to get attention first before I open a new one.

**Comment by LorenzoColitta** [comment]
#3539

**Comment by yoonthegoon** [comment]
duplicate of https://github.com/zen-browser/desktop/issues/3539

**Comment by yoonthegoon** [comment]
duplicate of https://github.com/zen-browser/desktop/issues/3539
