### ISSUE TITLE
Design problem

### ISSUE THREAD

**Issue by MrEsbens** [zen-browser/desktop#3589]
### Captchas

- [X] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.

### What happened?

I see thats my interface totally messed up with new update
![изображение](https://github.com/user-attachments/assets/d9a9e784-7a26-4704-8069-92b924f9db1a)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2

### What platform are you seeing the problem on?

Windows

**Comment by Anoms12** [comment]
> ### Captchas
> 
> - [X] I have read the instructions.
> - [x] I have searched existing issues and avoided creating duplicates.
> - [x] I am not filing an enhancement request.
> 
> ### What happened?
> 
> I see thats my interface totally messed up with new update
> ![изображение](https://github.com/user-attachments/assets/d9a9e784-7a26-4704-8069-92b924f9db1a)
> 
> 
> ### Reproducible?
> 
> - [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.
> 
> ### Version
> 
> 1.0.2
> 
> ### What platform are you seeing the problem on?
> 
> Windows
> 
> ### Relevant log output
> 
> _No response_

**Comment by 12th-devs** [comment]
@MrEsbens do you have any custom css?

**Comment by MrEsbens** [comment]
No

**Comment by 12th-devs** [comment]
Hmm... I've not seen this before, I'm assuming your on Zen and not twilight, can you try and reset the controls on the customize menu or try changing to single toolbar and back?

**Comment by acir-mandello** [comment]
I'm also seeing this issue after updating. My version is 1.0.2-b.0 (Firefox 133.0) (64-bit). The top bar is smaller than Windows 11 top bar and the bar still appears behind it.

![image](https://github.com/user-attachments/assets/395c9a8d-31e1-4675-ba21-6ab230f97b85)

**Comment by 12th-devs** [comment]
@lucent-acir @MrEsbens this issue should be fixed soon!

[https://www.reddit.com/r/zen_browser/comments/1hbn70p/comment/m1hnfqz/]()
