### ISSUE TITLE
Can't switch workspaces

### ISSUE THREAD

**Issue by pedro-abranches** [zen-browser/desktop#359]
### What happened?

Both the workspace button and the cycle workspaces shortcut stopped working.
All the tabs in workspaces other than default where in "hidden tabs," and upon opening them, they load in their respective workspaces, and I can't switch back to default.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.26

### Severity impact

High

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
Could you send a video?

**Comment by pedro-abranches** [comment]
Sure! https://drive.google.com/file/d/1rr_-5mDaSVoI53c0JpQd8uDbQo0o8jcY/view?usp=drive_link

**Comment by RealVishy** [comment]
> Sure! https://drive.google.com/file/d/1rr_-5mDaSVoI53c0JpQd8uDbQo0o8jcY/view?usp=drive_link
> 
> Here, I'm clicking on the workspace button and inputing the shortcut.

The drive link you shared doesn't give permission for others to view it. Perhaps you could attach the video directly to your comment?

**Comment by pedro-abranches** [comment]
Sorry! I couldn't get the video size to the attachment limit of 10mb without compromising too much quality. I've updated the link to allow viewership

**Comment by pedro-abranches** [comment]
Yes, the issue persists with 1.0.0-a.26. The workspace button doesn't work, and a second send to workspace button has appeared on the tab context menu:
![image](https://github.com/user-attachments/assets/04e0ef14-7060-4e72-bcd5-c8d28b192d25)
If I send a tab to another workspace, I can't go back

**Comment by mauro-balades** [comment]
What workspaces did you create? What names?

**Comment by pedro-abranches** [comment]
I created two, named "trabalho" and "estudo".

**Comment by pedro-abranches** [comment]
Upon
