### ISSUE TITLE
edit page bug

### ISSUE THREAD

**Issue by YuperTR** [zen-browser/desktop#3594]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![2024-12-11_21-32](https://github.com/user-attachments/assets/08b80ecb-2ac3-4759-9137-84bbbd56c87a)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

lastest

### What platform are you seeing the problem on?

Windows

**Comment by Nanito111** [comment]
i have the same problem
- Arch Linux x86_64 (Linux 6.12.4-arch1-1)
- Mozilla Zen 1.0.2-b.0
