### ISSUE TITLE
Illegal instruction (core dumped) when trying to run from Linux Lubuntu

### ISSUE THREAD

**Issue by GunGunGun** [zen-browser/desktop#36]
I tried to run `./zen -profile test` to test Alpha, but it can't run, is it compiled for musl and not gnu ?

**Comment by mauro-balades** [comment]
could you run with gdb and then show me the backtrace by runing `bt`?

```
gdb ./zen
>> r -profile test
...
>> bt
```

thanks!

**Comment by mauro-balades** [comment]
im looking into how to compile with musl instead of glib

**Comment by TheBestUser01234567890** [comment]
Same on linux mint.

GDB:

GNU gdb (Ubuntu 9.2-0ubuntu1~20.04.1) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./zen...
(No debugging symbols found in ./zen)
(gdb) r -profile test
Starting program: /home/linux-mint/SW/ZenBrowser/zen/zen -profile test
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGILL, Illegal instruction.
0x0000555555581550 in ?? ()
(gdb) bt
#0  0x0000555555581550 in ?? ()
#1  0x0000555555588a46 in ?? ()
#2  0x000055555558c456 in ?? ()
#3  0x000055555558c3a1 in ?? ()
#4  0x000055555558b5b1 in ?? ()
#5  0x0000555555583614 in malloc ()
#6  0x00007ffff7e40a6a in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007ffff7fe0b9a in call_init (l=<optimized out>, argc=argc@entry=3, 
    argv=argv@entry=0x7fffffffdf68, env=env@entry=0x7fffffffdf88)
    at dl-init.c:72
#8  0x00007ffff7fe0ca1 in call_init (env=0x7fffffffdf88, argv=0x7fffffffdf68, 
    argc=3, l=<optimized out>) at dl-init.c:30
#9  _dl_init (main_map=0x7ffff7ffe190, argc=3, argv=0x7fffffffdf68, 
    env=0x7fffffffdf88) at dl-init.c:119
#10 0x00007ffff7fd013a in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
#11 0x0000000000000003 in ?? ()
#12 0x00007fffffffe29a in ?? ()
#13 0x00007fffffffe2c1 in ?? ()
#14 0x00007fffffffe2ca in ?? ()
#15 0x0000000000000000 in ?? ()
(gdb) 

GDB screenshots:

![image](https://github.com/zen-browser/desktop/assets/98957578/5fddf113-dd0e-4f57-82c3-a4d95ff366a9)
![image](https://github.com/zen-browser/desktop/assets/98957578/8e8bf327-19c1-4a6f-8171-061e0810faff)

OS info:

OS: Linux Mint 20.3 x86_64
Kernel: 5.4.0-91-generic
Uptime: 9 mins
Shell: bash 5.0.17
Resolution: 1920x1080
DE: Cinnamon
WM: Mutter (Muffin)
Terminal: gnome-terminal

**Comment by mauro-balades** [comment]
Thanks a lot for this detailed response! It *should* be fixed with https://github.com/zen-browser/surfer/commit/083a459a23036cbfd01c21659e886d660bfc4f18. but imnot 100% sure. Ill close the issue and reopen if the problem persists. It will be applied for the next release

**Comment by TheBestUser01234567890** [comment]
Not completed. #39

**Comment by mauro-balades** [comment]
It *should* be fixed, you can download it here: https://get-zen.vercel.app/download

please tell me if it worked!

**Comment by GunGunGun** [comment]
> please tell me if it worked!

Yes it worked, this thread is now solved, thanks!

**Comment by mauro-balades** [comment]
☺️🚀

**Comment by GunGunGun** [comment]
This issue is back in alpha 7

**Comment by mauro-balades** [comment]
Should be fixed for 1.0.0-a.8 now 👍🏽

**Comment by mauro-balades** [comment]
please tell me if the error still exists

**Comment by TheBestUser01234567890** [comment]
> please tell me if the error still exists

yes, unfortunately

**Comment by mauro-balades** [comment]
What version?

**Comment by TheBestUser01234567890** [comment]
> What version?

a.8 I think

**Comment by mauro-balades** [comment]
could you try re-downloading?

**Comment by TheBestUser01234567890** [comment]
> could you try re-downloading?

Still the same

**Comment by mauro-balades** [comment]
could you please confirm if this  version works? https://github.com/zen-browser/desktop/actions/runs/10143769494/artifacts/1750937625

**Comment by GunGunGun** [comment]
Worked for me now, downloaded from release a8.

**Comment by mauro-balades** [comment]
🥳

**Comment by TheBestUser01234567890** [comment]
a10, doesn't work

**Comment by mauro-balades** [comment]
Alr peeps. .11 is now released with the fixes. If you are getting this error, please download the "generic" build on the downloads pages this will update the browser to a more generic build for older computers. You won't have this problem again after

**Comment by TheBestUser01234567890** [comment]
> Alr peeps. .11 is now released with the fixes. If you are getting this error, please download the "generic" build on the downloads pages this will update the browser to a more generic build for older computers. You won't have this problem again after

Tysm for the generic build, now it works
