### ISSUE TITLE
Windows Taskbar not visible when using Zen on Windows 10

### ISSUE THREAD

**Issue by sinchxn** [zen-browser/desktop#360]
### What happened?

The Windows 10 taskbar is set to auto-hide by default on my system. When using the Zen software, the taskbar does not appear as expected when I move the cursor to the bottom of the screen. Instead, the taskbar remains hidden until I either close the Zen window, minimize it, or switch to another application.
This behavior is inconsistent with the normal Windows 10 functionality, where the taskbar is designed to automatically show up when the cursor is positioned at the bottom of the screen, even when the taskbar is set to auto-hide.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.24

### Severity impact

High

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
Please use the correct label next time, it's easier to manage

**Comment by mauro-balades** [comment]
This is likely firefox's issue, please report this bug to them 👍🏽

**Comment by HyperKiko** [comment]
it seems that i had this issue because i was unknowingly in fullscreen mode, pressing f11 fixed it.
