### ISSUE TITLE
support for 1password integration with desktop app

### ISSUE THREAD

**Issue by tecandrew** [zen-browser/desktop#361]
### What feature would you like to see?

from their docs, 1password supports [Additional Browser integration with the desktop version of their 1Password](https://support.1password.com/connect-1password-browser-app/) **if the browser is code signed by Apple**. Zen currently doesn't have this afaik.

the alternative is to just Sign In on the browser extension as a _separate_ credential endpoint for users.

### What platform are you seeing the problem on?

macOS

### Additional context

What 1Password users currently see when attempting to install the extension into Zen

![image](https://github.com/user-attachments/assets/5d3080f8-eb34-4b5d-b409-2d6580a74a0b)

![image](https://github.com/user-attachments/assets/c48f00a2-052a-4853-917a-d657ad26c8df)

**Comment by cryptofyre** [comment]
+1, Only thing preventing me from using Zen full-time. Security key's don't work either on Windows.

**Comment by Anthonyy232** [comment]
+1, maybe support for Bitwarden (OSS) as well?

**Comment by cryptofyre** [comment]
1Password would like to support Zen, however it is currently not code signed in anyway. This is a primary influential factor right now, maybe with enough support this can be achieved? 

I'd love to donate if we can help assist the developmental efforts towards establishing a company presence code signature wise.

**Comment by soumendrak** [comment]
related issue: https://github.com/zen-browser/desktop/issues/319

**Comment by ChristinWhite** [comment]
This is the number one issue for me and the primary reason I'm still using Firefox as my current primary.

**Comment by HRKings** [comment]
Anyone wanting to try Zen out on Linux, you can use the following commands to enable 1Password desktop sync:
```shell
sudo mkdir /etc/1password
sudo touch /etc/1password/custom_allowed_browsers
echo "zen-bin" | sudo tee -a /etc/1password/custom_allowed_browsers
```
I don't think this will work with macOS, but I will leave this here for anyone searching for anything related to 1Password and Zen

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/856

 ~ This is an automatic operation to better enhancements requests organization.

**Comment by NicolasGB** [comment]
@HRKings  Thank you!!!

I was looking for this but i thought it wasn't possible for Linux.  Works like a charm

**Comment by zvictor** [comment]
> If you installed 1Password for Linux or your browser using a containerized package manager such as [Snap](https://support.1password.com/install-linux/#snap-store) or [Flatpak](https://support.1password.com/install-linux/#flatpak), the app won’t be able to communicate with 1Password in your browser.

That probably applies to AppImage as well, so that must be the reason why @HRKings workaround does not work for me.
I gotta wait for https://github.com/zen-browser/desktop/issues/78.

**Comment by martinjose** [comment]
> > If you installed 1Password for Linux or your browser using a containerized package manager such as [Snap](https://support.1password.com/install-linux/#snap-store) or [Flatpak](https://support.1password.com/install-linux/#flatpak), the app won’t be able to communicate with 1Password in your browser.
> 
> That probably applies to AppImage as well, so that must be the reason why @HRKings workaround does not work for me. I gotta wait for #78 first.

Unfortunately it looks like #78 is not going to be a thing that is natively supported by Zen. :/

Currently I'm just using the copr package for Zen-Browser based on the zipped archive.

**Comment by SmokeyPlayz** [comment]
> Anyone wanting to try Zen out on Linux, you can use the following commands to enable 1Password desktop sync:
> 
> ```shell
> sudo mkdir /etc/1password
> sudo touch /etc/1password/custom_allowed_browsers
> echo "zen-bin" | sudo tee -a /etc/1password/custom_allowed_browsers
> ```
> 
> I don't think this will work with macOS, but I will leave this here for anyone searching for anything related to 1Password and Zen

Yea, So I believe I am having the same problem but with KeePassXC now I tried this commands just by replacing the 1password with KeePassXC, but I'm not sure if it did anything because, After I press enter basically like nothing else happened I'm running Linux Endeavour OS, I am a new Linux user so if anyone see this please hopefully provide a solution, And the reason I came across this was because of this image 
![Screenshot_02-Sep_20-36-05_5069](https://github.com/user-attachments/assets/71fa8c50-13e0-4dd8-9368-422c913a52d0)
now on the right it's the desktop version and the left is Zen browser/ KeePassXC extension version, the reason I did this because every time I log in for some odd reason I will need to log in into discord again and also like my Gmail account again for Firefox and Zen which hopefully this password manager I heard was best and free can maybe solve that problem, but seems I ran into a little tight spot, off-topic, but I wish they added custom wallpapers XD.

**Comment by ItsReidar** [comment]
> > Anyone wanting to try Zen out on Linux, you can use the following commands to enable 1Password desktop sync:
> > ```shell
> > sudo mkdir /etc/1password
> > sudo touch /etc/1password/custom_allowed_browsers
> > echo "zen-bin" | sudo tee -a /etc/1password/custom_allowed_browsers
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I don't think this will work with macOS, but I will leave this here for anyone searching for anything related to 1Password and Zen
> 
> Yea, So I believe I am having the same problem but with KeePassXC now I tried this commands just by replacing the 1password with KeePassXC, but I'm not sure if it did anything because, After I press enter basically like nothing else happened I'm running Linux Endeavour OS, I am a new Linux user so if anyone see this please hopefully provide a solution, And the reason I came across this was because of this image ![Screenshot_02-Sep_20-36-05_5069](https://private-user-images.githubusercontent.com/80928946/363871067-71fa8c50-13e0-4dd8-9368-422c913a52d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0NjM1MjEsIm5iZiI6MTcyNzQ2MzIyMSwicGF0aCI6Ii84MDkyODk0Ni8zNjM4NzEwNjctNzFmYThjNTAtMTNlMC00ZGQ4LTkzNjgtNDIyYzkxM2E1MmQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDE4NTM0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3YmY1MDZiMjNlOTAxYzUyMzRjNDAzOWUxNTYyNjFhZDMzOWU3ZmI1M2M1YjEyOGQ3MzU3NTY3M2I3NjIxNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.AqVQcE_yeOv2pJ16UzENHRgfMhA5qMAmilllnu46uHE) now on the right it's the desktop version and the left is Zen browser/ KeePassXC extension version, the reason I did this because every time I log in for some odd reason I will need to log in into discord again and also like my Gmail account again for Firefox and Zen which hopefully this password manager I heard was best and free can maybe solve that problem, but seems I ran into a little tight spot, off-topic, but I wish they added custom wallpapers XD.

Tried this on macOS and it worked somehow!

**Comment by ChristinWhite** [comment]
> Tried this on macOS and it worked somehow!

That's interesting, what version of macOS and 1Password? I tried it and does not work on my end.

**Comment by martinjose** [comment]
On my macOS device, I installed Zen through homebrew and was able to get it working with 1PW using these steps.

https://1password.community/discussion/140735/extending-support-for-trusted-web-browsers

Hope it helps someone!

**Comment by Dat-Ngu** [comment]
I have the same issue on windows still no fix unfortunately.

**Comment by BENZORICH** [comment]
What about Windows?

**Comment by CaliInn-Li** [comment]
> What about Windows?

On Windows, you can connect Zen Browser to 1Password via the 1Password app: Settings -> Browser -> Connect to Other Browsers.

**Comment by PikachuEXE** [comment]
A Note: when I enabled it (some time ago, > 1 month)
It requires the Zen Browser binary to be inside C:\Program Files, D:\Program Files won't work and other locations also won't work (1P enforcement and could be changed now, try it)
