### ISSUE TITLE
`urlbar-background` alpha is too low

### ISSUE THREAD

**Issue by yoonthegoon** [zen-browser/desktop#3613]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Commit https://github.com/zen-browser/desktop/commit/54cb67b31657295dbbf44c3fb31b6399d283f4b6 for release `1.0.2-b.0` made a number of changes to the URL bar.

Although `1.0.2-b.1` added a preference to disable the new floating URL bar, it did *not* address the changed background, making searching with `'zen.view.use-deprecated-urlbar': true` very difficult on the eyes. \
This effect is even more painful when there is text behind the background, making it unclear which are parts of the search results and which are part of the page behind them.

<img width="448" alt="image" src="https://github.com/user-attachments/assets/f31bcba0-d368-4961-964c-e8260639b75f" />

https://github.com/zen-browser/desktop/blob/54cb67b31657295dbbf44c3fb31b6399d283f4b6/src/browser/base/content/zen-styles/zen-urlbar.css#L25-L28

https://github.com/zen-browser/desktop/blob/54cb67b31657295dbbf44c3fb31b6399d283f4b6/src/browser/base/content/zen-styles/zen-theme.css#L80-L83

converting from https://github.com/zen-browser/desktop/issues/3539

https://github.com/zen-browser/desktop/blame/52a607d0fb016dadc73099de71e8682438508d7c/src/browser/base/content/zen-styles/zen-urlbar.css#L25

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.1

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by anh-chu** [comment]
anyone got a fix?

**Comment by trinajstica** [comment]
I did this, in my profile in chrome folder I created userChrome.css and put this in:

#urlbar[open] > #urlbar-background{
  backdrop-filter: blur(50px);
}

**Comment by yoonthegoon** [comment]
> I did this, in my profile in chrome folder I created userChrome.css and put this in:
> 
> #urlbar[open] > #urlbar-background{ backdrop-filter: blur(50px); }

I wasn't able to get that working with my userChrome.css for some reason. It was only effective on settings pages (e.g. about:preferences, about:support, etc.), not any other web pages.

All together, the solution that worked for me is:

1. Go to `about:config`
2. Set `zen.view.use-deprecated-urlbar` to `true`
3. Set `toolkit.legacyUserProfileCustomizations.stylesheets` to `true`
4. Go to `about:support`
5. Go to the `Profile Folder`
  - On MacOS, click `Show in Finder`
  - On Windows, click `Open Folder`
6. In the profile folder, open or create and open folder `chrome`
7. Open or create and open `userChrome.css`
8. Paste the following, save, and restart Zen Browser
```css
@media (-moz-bool-pref: 'zen.view.use-deprecated-urlbar') {
  #urlbar[open] > #urlbar-background {
    background-color: var(--zen-branding-bg) !important;
  }
}
```

One thing to note about this solution, it's intended only to work if you enable `zen.view.use-deprecated-urlbar`. This is because I haven't got around to testing if this breaks for those who use the single toolbar layout.

<img width="405" alt="image" src="https://github.com/user-attachments/assets/81983316-ec63-4a78-8bee-884ae45d6aca" />

**Comment by mr-cheffy** [comment]
Shoudn't be a problem anymore 👍🏽
