### ISSUE TITLE
PLEASE Respect XDG User Paths

### ISSUE THREAD

**Issue by Swivelgames** [zen-browser/desktop#3619]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I understand this is likely coming from Mozilla, since they do the same thing, but we need to get ahead of this before Zen becomes too popular and it's too late. :cry: 

![image](https://github.com/user-attachments/assets/52c7285f-b245-43f2-9120-d4b650f32c85)

Please don't continue this trend. We already have enough applications that do not [respect XDG paths](https://specifications.freedesktop.org/basedir-spec/latest/). Home directories are cluttered enough.

> `$XDG_STATE_HOME` defines the base directory relative to which user-specific state files should be stored. If `$XDG_STATE_HOME` is either not set or empty, a default equal to `$HOME/.local/state` should be used.

Zen browser data should always be stored in `$XDG_STATE_HOME`, or `$HOME/.local/state/zen/*` if $XDG_STATE_HOME is not set on that particular machine.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.0 (Firefox 133.0)

### What platform are you seeing the problem on?

Linux

**Comment by mr-cheffy** [comment]
Please move to the issue linked above as it is a duplicate. THanks
