### ISSUE TITLE
Title bar auto-hides after update

### ISSUE THREAD

**Issue by kauht** [zen-browser/desktop#3623]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

After closing and reopening the browser when it asked to update, it made me go through the setup process again and just spammed through it pressing "continue", then I realized that my Title bar auto-hides/shrinks when my cursor isn't on it, and my URL bar is missing. I have tried looking through settings to find what changed and turning off and on some extensions to see if they were the issue but nothing has worked.
[![Image from Gyazo](https://i.gyazo.com/6050e9b86031e93c2262cbf2d4c275c4.gif)](https://gyazo.com/6050e9b86031e93c2262cbf2d4c275c4)

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Latest

### What platform are you seeing the problem on?

Windows

**Comment by ilmalsalam** [comment]
go setting and find "Layout" , its gonna show the selection that suits to you. such 
- Single toolbar
- Multiple toolbars
- Collapsed toolbar

**Comment by kauht** [comment]
> go setting and find "Layout" , its gonna show the selection that suits to you. such
> 
>     * Single toolbar
> 
>     * Multiple toolbars
> 
>     * Collapsed toolbar

Thank's so much, sorry for the useless post.
