### ISSUE TITLE
Flatpak build fails

### ISSUE THREAD

**Issue by ulrichSchreiner** [zen-browser/desktop#3624]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

In https://github.com/zen-browser/flatpak the SVG icon is now in the toplevel directory, so the code in

https://github.com/zen-browser/desktop/blob/dev/flatpak/io.github.zen_browser.zen.yml.template

~~~
- install -Dm0644 metadata/icons/io.github.zen_browser.zen.svg **${{FLATPAK_DEST}}/share/icons/hicolor/scalable/apps/${{FLATPAK_ID}}.svg**
~~~

now fails. you must remove the `icons` folder or move the icon to the given folder (in the remote repository)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2 b1

### What platform are you seeing the problem on?

Linux

**Comment by mr-cheffy** [comment]
Fixed, thanks!
