### ISSUE TITLE
How to unglitch search bar blur and make it normal?

### ISSUE THREAD

**Issue by iustinm1** [zen-browser/desktop#3628]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![image](https://github.com/user-attachments/assets/ccea0a5d-fc26-4c0b-baf9-09e190dc8a87)
i just want to make it how it was before yesterday's update, literally everyone is quitting and moving to another browser because the maintainers wanted to fuck the url bar when it was just perfect

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

latest

### What platform are you seeing the problem on?

Windows

**Comment by mr-cheffy** [comment]
> the maintainers wanted to fuck the url bar when it was just perfect

Wont deny that, im an evil person what can I say.

Remove the urlbar mod you have installed.
