### ISSUE TITLE
1.0.0-a.24 broken

### ISSUE THREAD

**Issue by ujuc** [zen-browser/desktop#363]
### What happened?

Hi, [1.0.0-a.24](https://github.com/zen-browser/desktop/releases/tag/1.0.0-a.24) is broken.

![image](https://github.com/user-attachments/assets/513f952d-13fa-4b45-ba7b-a7c6eb1c31b9)

Thanks

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.24

### Severity impact

Critical

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by mauro-balades** [comment]
https://github.com/zen-browser/desktop/issues/53
