### ISSUE TITLE
url bar is transparent and i cant find where to disable it

### ISSUE THREAD

**Issue by iustinm1** [zen-browser/desktop#3630]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![image](https://github.com/user-attachments/assets/5af8886f-be5b-4728-bc6d-a25cb57ad5c4)
![image](https://github.com/user-attachments/assets/4f3e8df3-450e-4e93-933e-e378eede0b58)
i have zen mods disabled yet i still encounter this, at least let us switch to the version before the url bar changes

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

latest

### What platform are you seeing the problem on?

Windows

**Comment by trinajstica** [comment]
put this in chrome/userChrome.css:

`#urlbar[open] > #urlbar-background{
  backdrop-filter: blur(28px);
}
`

**Comment by vesk4000** [comment]
I have the same issue, and it seems that everyone who's trying to use the regular (non-floating) url bar has the issue. I think there's a workaround [here](https://github.com/zen-browser/desktop/issues/3516#issuecomment-2532938566). (Note that you need to disable the deprecated URL bar option in `about:config`)

**Comment by domsch1988** [comment]
I can confirm this issue on the latest "stable" Update from Flathub on Linux
![image](https://github.com/user-attachments/assets/1fcad786-bd4d-4a03-8e33-4e6da1bed6e1)

Some additional datapoints: On "Internal" pages like Settings or about:config, the Blur is working. On Normal Webpages i get a kind of Blured outline Effect on the Sidebar 
![image](https://github.com/user-attachments/assets/0d51031c-f58f-4e29-8d7d-1068929f8c1e)

I don't exactly mind the floating, central URL bar, but it needs some background color and a MUCH bigger blur radius. Even when the Blur is working as intended, Text can be hard to read. Microsoft and Apple generally add a 60% Black or White Background color to Blured areas, and even that can be hard to read depending on background. If i have a "Light Mode" Browser, but am on a Dark Mode website, this becomes Unusable, even with Blur:
![image](https://github.com/user-attachments/assets/5d06b41a-88f4-465e-bf2e-3039fab7b08e)

**Comment by mr-cheffy** [comment]
https://www.reddit.com/r/zen_browser/s/MFfQKAdBj4
