### ISSUE TITLE
Pinned tabs not styled properly

### ISSUE THREAD

**Issue by ArtekMisiek** [zen-browser/desktop#3631]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Pinned tabs are not properly styled, few versions for now 
<img width="398" alt="Screenshot 2024-12-12 at 10 12 23" src="https://github.com/user-attachments/assets/ca44d851-8e67-446b-ad49-833692641528" />

i uninstalled all mods, uninstalled Zen browser, cleared cache in `/Users/username/Library/Caches` directory, reinstalled ZEN and it is till the same.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.1

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by ArtekMisiek** [comment]
i also have it on Windows 10

**Comment by JSGRD22** [comment]
Sorry, I might be a little blind but how are they not styled properly? If you’re referring to the fact that they look like normal tabs, it is an intentional change and the superpins mod allows you to achieve the old look.

**Comment by syscat29** [comment]
> Sorry, I might be a little blind but how are they not styled properly? If you’re referring to the fact that they look like normal tabs, it is an intentional change and the superpins mod allows you to achieve the old look.

Seconding this, this is how they look with [SuperPins](https://zen-browser.app/mods/ad97bb70-0066-4e42-9b5f-173a5e42c6fc). If that's what you want
![image](https://github.com/user-attachments/assets/1a4decf1-5f2e-462e-9080-6eaa5c536edc)

**Comment by ArtekMisiek** [comment]
@JSGRD22 @j14i 
thanks, didnt see that zen browser moved away from this look by default. It works with superpins
