### ISSUE TITLE
Bookmark control missing from AddressBar in a.24

### ISSUE THREAD

**Issue by jimfr** [zen-browser/desktop#364]
### What happened?

<img width="1029" alt="image" src="https://github.com/user-attachments/assets/5dd6c93f-30d7-4bbb-8336-22efe26ce417">
There is no longer a star in the right side of the address bar that allows one to turn on/off or modify a bookmark for a tab.  This was present in a.23 and is present in the latest Firefox

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

a.24

### Severity impact

Medium

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by jimfr** [comment]
Same issue in a.26

**Comment by jimfr** [comment]
no, I don't.  I tried a new Profile, with the same result.

**Comment by jimfr** [comment]
<img width="1727" alt="image" src="https://github.com/user-attachments/assets/1e7ecb64-f4fa-439e-bf58-826d02e3cd17">

**Comment by PanIntegralus** [comment]
Based on my usage, extensions that add any type of icon there also doesn't show up.

**Comment by jimfr** [comment]
Fixed in a.28.  Thank you!
