### ISSUE TITLE
The New Url Bar is so annoying

### ISSUE THREAD

**Issue by quirxsama** [zen-browser/desktop#3649]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I cannot find  (or it doesnt exists.) changing the new url bar thing. I dont want the new url bar in middle. Its good at top.
![resim](https://github.com/user-attachments/assets/a1eada46-ccf8-4eb4-afa4-c98b03b2f792)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2

### What platform are you seeing the problem on?

Linux

**Comment by BaconIsAVeg** [comment]
The number of incredibly poor design choices they've made recently have forced me back to Firefox.  From 'glances' that could only partially be disabled, to this new 'floating' url bar, to the flakiness of the side tab bar (why is the + new tab button shown twice?), just... no thanks.

**Comment by quirxsama** [comment]
I agree with you. I went back to the previous version and fixed things with a few mods

**Comment by litemotiv** [comment]
God i hate this floating bar so much. This is the first time i'm considering ditching Zen, which makes me feel sad. Some very poor UI decisions lately.

**Comment by zebra-f** [comment]
I don't mind it; in fact, I quite like it since I don't have to move my eyes that much. However, these types of changes should be optional. 
Empty top URL Bar looks weird/unfinished as we use the new popup window.

**Comment by AlphaNecron** [comment]
![image](https://github.com/user-attachments/assets/1a5a0ff3-5099-4f8b-aa1b-fcc024e208c1)
You can toggle these to revert to legacy behavior, albeit not guaranteed to be stable.

**Comment by Katharta** [comment]
The awful new floating address bar should have been an optional setting or Zen mod.

**Comment by trinajstica** [comment]
do this:
about:config
set zen.view.use-deprecated-urlbar to true
install "Cleaned URL bar" mod, and you are good to go zen again

**Comment by LaserKaspar** [comment]
Even when reverted, the Urlbar is transparent and you can't read its content... 

Kind of like here:
https://github.com/zen-browser/desktop/issues/3630

**Comment by signalno11** [comment]
This should have been added as a configuration option. I understand it's beta software, but making hard changes like this is just....ehhhhh

**Comment by nneto** [comment]
I actually loved the floating bar... and annoyed with the top bar visible while the floating bar is open in compact mode.

**Comment by nneto** [comment]
I think it would be better if the floating bar appeared only with Ctrl/Cmd+L and Ctrl/Cmd+K. When opening a new tab, the top bar is focused and then, when you start typing, it changes to the floating bar. I find that "jump" actually annoying.

**Comment by mr-cheffy** [comment]
https://www.reddit.com/r/zen_browser/s/MFfQKAdBj4

**Comment by garretlaxton** [comment]
Where?
![image](https://github.com/user-attachments/assets/71189e05-3f3b-45a9-9369-3b93679dfad4)

**Comment by stuartmaxwell** [comment]
Perhaps these settings are coming in the next version? I had to roll back to an older version to make the URL bar usable. I'll need to switch back to Firefox if this can't be fixed.

**Comment by ry444nn** [comment]
> do this: about:config set zen.view.use-deprecated-urlbar to true install "Cleaned URL bar" mod, and you are good to go zen again

Tried this and it still doesn't work

**Comment by ry444nn** [comment]
> Perhaps these settings are coming in the next version? I had to roll back to an older version to make the URL bar usable. I'll need to switch back to Firefox if this can't be fixed.

As i was using zen some stuff stopped working, like in my new tabs won't show my background and such (after the update these worked like before), do you have the same issue with the rollback ?
