### ISSUE TITLE
Middle click creates new tab

### ISSUE THREAD

**Issue by amkar1m** [zen-browser/desktop#365]
### What feature would you like to see?

It would be nice to have middle click function that opens a new tab (much like vivaldi). It makes adding tabs from any space in the vertical tabs much quicker and efficient!

### What platform are you seeing the problem on?

Windows

**Comment by soumendrak** [comment]
@amkar1m which version of Zen are you using?

**Comment by pirsonxyz** [comment]
I'm in Mozilla Zen 1.0.0-a.23 and middle click works as intended

**Comment by amkar1m** [comment]
@soumendrak @pirsonxyz I might be oblivious but I can't find middle click anywhere in the settings. Would you mind directing me there?

**Comment by amkar1m** [comment]
> ![image](https://private-user-images.githubusercontent.com/64155117/360063968-beb83caf-de61-4a0a-b808-15bc036bd0be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyODQ3NTMsIm5iZiI6MTcyNDI4NDQ1MywicGF0aCI6Ii82NDE1NTExNy8zNjAwNjM5NjgtYmViODNjYWYtZGU2MS00YTBhLWI4MDgtMTViYzAzNmJkMGJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDIzNTQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlYjBhMWQwNDAxNTE2ZTM1OTFjZTg5Y2Y1YTQ5NWM4YmY5OTAzNWUwYTJkNzBmY2EyZjRjOGUxY2U1YTUzYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X_zD83zMEcCmfRX_Gib4lO_e_FjD-HeinTMWCAPQY2U)
> 
> I think what they mean is middle mouse clicking this area should open a new tab. It does so on FireFox.
> 
> _Edit: changed pic_

exactly what I'm referring to

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/855

 ~ This is an automatic operation to better enhancements requests organization.
