### ISSUE TITLE
Will Zen-browser continue to provide portable app for Windows x64?

### ISSUE THREAD

**Issue by leic4u** [zen-browser/desktop#3652]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Continue to provide portable app for Windows x64. ( zen.win-specific.zip )

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.1

### What platform are you seeing the problem on?

Windows

**Comment by leic4u** [comment]
Why is there a specific zip package for Windows in the twilight release, while not in the beta release?😅

**Comment by leic4u** [comment]
Could anyone answer my question? 

@mr-cheff Sorry to bother you, I have been waiting for weeks and staying in a.22 for weeks too.

Could you please tell me the conclusion of this issue, so that I can decide whether to upgrade to exe package or not?

**Comment by mr-cheffy** [comment]
Not for now because they are too big to store them in our servers

**Comment by leic4u** [comment]
> Not for now because they are too big to store them in our servers

OK, thanks. I will upgrade to exe package. Wish the zip packages coming back soon.

**Comment by Naveed-SNR** [comment]
> Not for now because they are too big to store them in our servers

Can you please at least add them in the repo.
