### ISSUE TITLE
Feature: Syncing Workspaces

### ISSUE THREAD

**Issue by RealVishy** [zen-browser/desktop#366]
### What feature would you like to see?

This can be split into multiple issues depending on the difficulty of implementing them all.

- [ ] Syncing Workspaces between computers

- [ ] Sync Tabs in each workspace between computers

### What platform are you seeing the problem on?

Linux

### Additional context

I'd find it useful to sync the workspaces so i don't have to create them multiple times on different devices.

**Comment by bdbch** [comment]
Afaik Zen is using Mozilla's Firefox Sync service, don't know if this is possible to sync? Maybe there's a way with using a namespaced bookmark folder or something?

**Comment by cybik** [comment]
> Afaik Zen is using Mozilla's Firefox Sync service, don't know if this is possible to sync? Maybe there's a way with using a namespaced bookmark folder or something?

The point of the request might be "support self-hosted sync outside of Firefox Sync".

If it's not, my bad, I projected.

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/854

 ~ This is an automatic operation to better enhancements requests organization.

**Comment by ziscky** [comment]
For anyone on MacOS, simple workaround:
You can copy the profiles `~/Library/Application\ Support/zen/Profiles/` maintaining the names of the parent directories on the new installation.

**Comment by cybik** [comment]
> For anyone on MacOS, simple workaround: You can copy the profiles `~/Library/Application\ Support/zen/Profiles/` maintaining the names of the parent directories on the new installation.

This is quite literally not the point. The point is to *not* use file copy and file synchronization - which can lead to sync issues if you use more than one device at the same time.

**Comment by ziscky** [comment]
> > For anyone on MacOS, simple workaround: You can copy the profiles `~/Library/Application\ Support/zen/Profiles/` maintaining the names of the parent directories on the new installation.
> 
> This is quite literally not the point. The point is to _not_ use file copy and file synchronization - which can lead to sync issues if you use more than one device at the same time.

Yes this is a *simple workaround* for anyone migrating workspaces with dozens of tabs to more than one device. Using this with iCloud is also viable.

**Comment by arjs1000** [comment]
Is there currently a solution for syncing workspaces/tabs from two computers (one Windows and another Mac)? Is this possible with Mozilla's Firefox Sync in some form?
