### ISSUE TITLE
Only a single window decoration

### ISSUE THREAD

**Issue by artimanzero** [zen-browser/desktop#3660]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

There is only a single window decoration on zen browser, the minimize and maximize buttons are missing.
![Screenshot_20241212_191155](https://github.com/user-attachments/assets/97d2277a-4c3f-4ac4-882d-966a6c8bcfcc)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.1 (Firefox 133.0) (64-bit) Flatpak from Flathub

### What platform are you seeing the problem on?

Linux

**Comment by signalno11** [comment]
Is your system configured to have the minimize and maximum buttons? Zen listens to what the system sets.

**Comment by gitartiman2499** [comment]
> Is your system configured to have the minimize and maximum buttons? Zen listens to what the system sets.

yes, all my other apps have a minimize and maximize button

**Comment by artimanzero** [comment]
Mb i didn't have xdg-desktop-portal-gnome installed so sorry for bothering
