### ISSUE TITLE
Weird blue top bar when using a transparent theme color

### ISSUE THREAD

**Issue by ffigiel** [zen-browser/desktop#3668]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

If I set my workspace's theme to transparent or semi-transparent color (for example, `#aabbcc80`), I can see a weird blue bar at the top of the window, behind the workspace background color. I'm reporting this issue on 1.0.2-b.1 but I think it was present in b.0 as well.

**Examples**

Multiple toolbars
![image](https://github.com/user-attachments/assets/e76a30d9-2e41-4788-b17f-28b84e93807a)

Single toolbar
![image](https://github.com/user-attachments/assets/0a36d8df-1aa3-4d21-8490-79a5d549084f)

Fully transparent color
![image](https://github.com/user-attachments/assets/06ecbf26-ef0a-49e0-a39d-5a8b78d80727)

(By the way, hi and thanks for making this great browser!)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.1 (Firefox 133.0) (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by swebra** [comment]
Duplicate of #3546 I believe

**Comment by ffigiel** [comment]
Indeed, thanks for linking this! Although blue is not my theme color 🤔
