### ISSUE TITLE
Expanded sidebar visual glitch

### ISSUE THREAD

**Issue by Anthonyy232** [zen-browser/desktop#367]
### What happened?

Hi, there is a bug that makes the sidebar stutter

https://github.com/user-attachments/assets/da6958a0-ee9d-4dcb-b5b8-7b60231fc65c

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Version 1.0.0-a.26 (64-bit)

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by SlashScreen** [comment]
I have this issue too, was about to open an issue about it - Webpages can get a little jiggly too, so I would actually put this as medium severity since the text resizes and stuff (Reference page: Zen nightly homepage)

**Comment by mauro-balades** [comment]
Fixed for next version!
