### ISSUE TITLE
Hovering pinned tabs show a reset button

### ISSUE THREAD

**Issue by nneto** [zen-browser/desktop#3673]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I use compact mode with expanded sidebar. When I hover the pinned tabs, the button for "Reset tab to pinned URL" appears. This makes it harder to just click the tab trying to avoid this "reset button", not to mention the width jumping around. I believe the "Reset tab to pinned URL" should just be an option in the context menu.

![pinned-tabs](https://github.com/user-attachments/assets/0c8a20e8-10ac-410c-85a3-846f95efa3d2)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.1

### What platform are you seeing the problem on?

Linux

**Comment by mogita** [comment]
Alternatively it would be nice to have an option to disable the reset button.

**Comment by ihsanfansyuri** [comment]
You can hide the reset button using mods called `No pinned tab reset btn` in zen mods

**Comment by mogita** [comment]
> You can hide the reset button using mods called `No pinned tab reset btn` in zen mods

Thank you @ihsanfansyuri , this mod does the job.

**Comment by JSGRD22** [comment]
@nneto you may close the issue if the above solution works for you
