### ISSUE TITLE
Blue Top

### ISSUE THREAD

**Issue by DarKKnifey** [zen-browser/desktop#3675]
### Captchas

- [ ] I have read the instructions.
- [ ] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

the top of my screen is blue, why idk but its rather annoying
![Screenshot 2024-12-12 17058](https://github.com/user-attachments/assets/d739e68f-df16-4a07-b578-dab3fb04e8c9)
![Screenshot 2024-12-12 170125](https://github.com/user-attachments/assets/983aae56-40d4-40dd-be64-0c55351ffd4a)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.1 & 1.0.2-b.0

### What platform are you seeing the problem on?

Windows

**Comment by mr-cheffy** [comment]
God, please... Search for duplicates https://github.com/zen-browser/desktop/issues/3546
