### ISSUE TITLE
Topbar theme spacing

### ISSUE THREAD

**Issue by krauterbaquette** [zen-browser/desktop#3679]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The colored part of the top bar has a weird spacing, which looks like a visual bug, as the URL bar goes beyond the colored part, and the icons have no bottom padding.

![Top-bar spacing](https://github.com/user-attachments/assets/ea48a2c2-a6a7-4e3f-a6ec-d336570699a1)

Please correct me if i am wrong and this is expected.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.0 (Firefox 133.0)

### What platform are you seeing the problem on?

Windows

**Comment by Smooth-E** [comment]
Make sure to update to the latest version and let us know if the issue persist here. The latest version as of now is `1.0.2-b.1`.

**Comment by Smooth-E** [comment]
Also this is possibly a duplicate of #3677. Consider closing this issue and stating your experience in comment of #3677 if so.

**Comment by krauterbaquette** [comment]
This problem no longer exists in the current version (1.0.2-b.0 (Firefox 133.0))
