### ISSUE TITLE
Can't remove gap/border around the window.

### ISSUE THREAD

**Issue by kukorimam** [zen-browser/desktop#3685]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The "No Gaps" mod doesn't fix this problem.
Adding a CSS doesn't fix it either.

I had deleted the settings the the settings added to "about:config" after installing the "No Gaps" mod to see if reinstalling it will fix it. That didn't work the setting are not added when the mod is installed again.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.1

### What platform are you seeing the problem on?

Linux

**Comment by Peleret** [comment]
The "No Gaps" mod has been updated a few days ago.  
Try reinstalling it again.

**Comment by kukorimam** [comment]
Hi, I already did this and it works fine. Thank you.
