### ISSUE TITLE
Layout editor is broken with compact mode

### ISSUE THREAD

**Issue by pinage404** [zen-browser/desktop#3688]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Hello,

After upgrading from 1.0.1-a.19 to 1.0.2-b.1

I tryied to reset the layout in order to be sure to avoid broken state like some previous version had

When i go in the layout preference editor, it is broken
![image](https://github.com/user-attachments/assets/5452d170-e37e-49b3-8112-d5674e928a2e)

I use the compact mode

It is maybe related to this issue https://github.com/zen-browser/desktop/issues/3543

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.1

### What platform are you seeing the problem on?

Linux

**Comment by rohangdesign** [comment]
the right hand side of webpages is cut off for me in compact mode. 

<img width="1800" alt="Screenshot 2024-12-13 at 8 42 48 PM" src="https://github.com/user-attachments/assets/45646769-e1d7-4468-a877-222ddac152f8" />

**Comment by RayZ3R0** [comment]
Does this still happen on b.2? I am not getting this on linux

**Comment by pinage404** [comment]
When editing the layout with 1.0.2-b.2, it forces to expand the sidebar, so this not broken anymore
