### ISSUE TITLE
New preference to disable floating url bar is not present

### ISSUE THREAD

**Issue by Nanito111** [zen-browser/desktop#3689]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![image](https://github.com/user-attachments/assets/677eeff2-4ab3-4c55-913e-8072fa2fbcee)
The new preference to disable the new floating URL bar is not present in settings/preferences.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.1

### What platform are you seeing the problem on?

Linux

**Comment by cimarronline** [comment]
It's a new setting in about:config (zen.view.use-deprecated-urlbar).

**Comment by ypurpl** [comment]
yes, its nothing but an issue for me because I use compact with multiple toolbars instead of single
![image](https://github.com/user-attachments/assets/760589c8-7c82-4520-b7a5-51751086dd58)

Edit: found it `zen.view.use-deprecated-urlbar`, though it is broken
![image](https://github.com/user-attachments/assets/11da43fb-9185-4a3d-bac6-dfeb1a614118)

**Comment by vvirtues** [comment]
![image](https://github.com/user-attachments/assets/760589c8-7c82-4520-b7a5-51751086dd58)

**Comment by vvirtues** [comment]
is it in about:config? cant find it

**Comment by rohangdesign** [comment]
would love to be able to go back to a standard address bar - the floating one drives me nuts. 

Would also like to bring back the feature for the URL to automatically be selected / highlighted when you click into the address bar.

**Comment by Bazimek** [comment]
I think this change is atm only for the twilight version of the browser.

**Comment by Muhammad-Mohid-Khan** [comment]
> I think this change is atm only for the twilight version of the browser.

it is but its a option in about:config which is useless and buggy

**Comment by VoxelPrismatic** [comment]
I thought that it was a bug since it actually isn't centered with anything LOL
![image](https://github.com/user-attachments/assets/c3755d59-9b9a-4055-9551-08a39b5be8f2)

**Comment by romibi** [comment]
I'm very close to go back to normal firefox …
The split view and the workspaces are great but declaring having a normal url bar as "deprecated" is a nogo in my eyes …

**Comment by VoxelPrismatic** [comment]
When I click the URL bar, the text box should be right there. Do whatever in a new tab, but double-clicking to select a portion of the URL bar no longer works.

**Comment by erkkimon** [comment]
I strongly prefer the normal, non-floating address bar. I understand that some want to use the floating one, but for example I often need to copy parts of the URL and really would not like to click one spot and move the mouse to another spot to start selecting the URL part I need. So the ordinary URL bar behavior should definitely be available and not broken. I'm not against this feature, just noting that the old behavior definitely has benefits for some and both should be available imho.

**Comment by romibi** [comment]
https://zen-browser.app/release-notes/#1.0.2-b.2
> Added the very requested, very needed, feature rich, blazingly fast, innovative URL bar option we had in previous versions

Yay 🥳 
That changelog entry made me giggle 😄

**Comment by Muhammad-Mohid-Khan** [comment]
> https://zen-browser.app/release-notes/#1.0.2-b.2
> 
> > Added the very requested, very needed, feature rich, blazingly fast, innovative URL bar option we had in previous versions
> 
> Yay 🥳 That changelog entry made me giggle 😄

same lol elite trolls 😂

**Comment by ypurpl** [comment]
new question, i see the `float only when typing` but it only floats on ctrl L for me. though my problem's solved so not really a priority for me

**Comment by Nanito111** [comment]
I'm gonna close the issue now that the option is present in version `1.0.2-b.2` :)
