### ISSUE TITLE
Sidebery integration

### ISSUE THREAD

**Issue by ThinkSalat** [zen-browser/desktop#369]
### What feature would you like to see?

I use Sidebery to handle tab grouping and organization. It would be great to be able to replace the builtin tab sidebar with sidebery's sidebar. Additionally, it would be great to have a way to split tabs from the sidebery context menu.

### What platform are you seeing the problem on?

Windows

**Comment by ThinkSalat** [comment]
> The function to group tabs is planned for Zen, I think. To open tabs in split view from Sideberry is not a thing Zen can implement, this has to be implemented from the Sideberry developers.

I think it's possible to extend an extension - they're both open source. It might make more sense as a companion extension for sidebery

**Comment by guigirl42** [comment]
https://github.com/zen-browser/desktop/discussions/891#discussioncomment-11288211
