### ISSUE TITLE
Search bar moved 

### ISSUE THREAD

**Issue by KYCEHYLC** [zen-browser/desktop#3695]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Everything was normal but then, the search bar started appearing a lot lower than it should 

https://github.com/user-attachments/assets/b8c8982e-02b0-4e9e-bca5-eed5588ad26a

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.1

### What platform are you seeing the problem on?

Windows

**Comment by Muhammad-Mohid-Khan** [comment]
a new "feature" useless

**Comment by kristoftorok** [comment]
That's why I'm switching from this browser. :'D

**Comment by mr-cheffy** [comment]
https://www.reddit.com/r/zen_browser/s/MFfQKAdBj4
