### ISSUE TITLE
Zen Web panel customization

### ISSUE THREAD

**Issue by ThinkSalat** [zen-browser/desktop#370]
### What feature would you like to see?

I love the look and animations of the web panel, as well as toggling between floating and side by side viewing. I would love to be able to have that be its own sidebar, the way floorp does it. I often put my most used applications/communications there, so having instant access really important. Also, having notifications reflected in the favicons - for example a badge with the number or unread emails, or new messages, would be amazing. 

### What platform are you seeing the problem on?

Windows

**Comment by RealVishy** [comment]
Additionally, I'd like for the websites in the web panel to be movable/draggable in terms of order. Currently you cannot change their position

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/852

 ~ This is an automatic operation to better enhancements requests organization.
