### ISSUE TITLE
Some items in settings are extremely dim to see

### ISSUE THREAD

**Issue by androidghosh** [zen-browser/desktop#3705]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Can't see infos like these in settings. Even with completely default settings, there's something wrong with the contrast

![image](https://github.com/user-attachments/assets/3e35e3f3-3369-44e1-88ea-fc573c9bd777)

![image](https://github.com/user-attachments/assets/6b637c25-fd73-4158-aa18-1273cd7f7509)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.1

### What platform are you seeing the problem on?

Windows

**Comment by VoxelPrismatic** [comment]
Oops, I didn't catch this one in my latest #3727
But I did some digging and found a possible solution in the CSS so I'll keep that one open

**Comment by mr-cheffy** [comment]
Ill move this into https://github.com/zen-browser/desktop/issues/3727
