### ISSUE TITLE
The new "floating URL bar" feature is not very compatible with Chinese input methods

### ISSUE THREAD

**Issue by HuaYishu** [zen-browser/desktop#3710]
### Captchas

- [x] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.

### What happened?

Regarding `Zen Browser 1.0.2-b.0`, thank you very much for the many optimizations made in the appearance design of the software. However, the new feature "The URL bar will now be floating on the top of the page" is not friendly to Chinese input methods. When typing in English, characters are displayed in the floating URL bar, but when using Microsoft Pinyin for Chinese input, the cursor goes back to the original URL bar. After completing Chinese input, the cursor jumps back to the floating URL bar again. This constant switching is really frustrating, and I hope this can be optimized as soon as possible. Or please tell me how to turn off this setting; I couldn't find it on the "about:config" page.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.0

### What platform are you seeing the problem on?

Windows

**Comment by HuaYishu** [comment]
Thanks! It worked. To be honest, the "floating URL bar" is very cool, I like it very much, and I still hope that the developers can make it compatible.

**Comment by ClixTW** [comment]
Try this setting `設定 - Firefox實驗室 - 網址列：於輸入法未選字時就顯示搜尋引擎回傳的結果`

**Comment by HuaYishu** [comment]
謝謝！它起作用了
