### ISSUE TITLE
When I start typing the search bar is crooked in a strange way

### ISSUE THREAD

**Issue by GuyWithABird** [zen-browser/desktop#3711]
### Captchas

- [x] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

i just installed zen browser on aur and when i type search bar is get weird here is a photo.Also i tryed to install pn flatpak and it didnt do weird

![Ekran Görüntüsü_20241213_174520](https://github.com/user-attachments/assets/dcb7d760-7c8d-444d-9b0e-3c4e3b3dc677

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.0

### What platform are you seeing the problem on?

Linux

**Comment by Smooth-E** [comment]
Here is the image you attached. You forgot the closing `]` bracket or accidentally removed it.

![Ekran Görüntüsü_20241213_174520](https://github.com/user-attachments/assets/dcb7d760-7c8d-444d-9b0e-3c4e3b3dc677)

What are the versions of the browser in AUR and as Flatpak? Such behavior of the search bar is intended, as far as I understand and this is how it works in the latest version. Try updating your Flatpak version of then ad let us know whether the issue persists.

You can update installed Flatpak apps using the following command:
```sh
flatpak update
```

**Comment by GuyWithABird** [comment]
it doesnt show which version is flatpak using but it doesnt do weird thing on flatpak look, 
@
![Ekran Görüntüsü_20241213_204259](https://github.com/user-attachments/assets/96329a57-9ace-4866-bb19-70ba18323a11)

but the logo is updated i think its not old version

**Comment by GuyWithABird** [comment]
@Smooth-E and how i close the ] ?

**Comment by GuyWithABird** [comment]
Sorry im  not a master of these.

**Comment by thegarudauser** [comment]
![Uploading Ekran Görüntüsü_20241213_204259.png…]()

**Comment by GuyWithABird** [comment]
Yoo its it got better error got dissapered thx to zen browser developer tysm.

**Comment by Smooth-E** [comment]
> @Smooth-E and how i close the ] ?

You can click the three dots on the top right of your initial message box and select "Edit" there. Then change your picture embed string to the following:

```
![Ekran Görüntüsü_20241213_174520](https://github.com/user-attachments/assets/dcb7d760-7c8d-444d-9b0e-3c4e3b3dc677)
```

The last character here is the closing `)` (yeah, I mixed up the `] / )` characters in my previous messages 😅)
