### ISSUE TITLE
Previous Session and Tabs not restored by default

### ISSUE THREAD

**Issue by KorigamiK** [zen-browser/desktop#3713]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Before recent updates the previous session and tabs used to open just as were left off before I closed the browser. 

Now it makes me press ctrl+shift+T to restore the tabs and windows. 

Need fix asap 

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Mozilla Zen 1.0.2-b.0

### What platform are you seeing the problem on?

Linux

**Comment by mr-cheffy** [comment]
![image](https://github.com/user-attachments/assets/ae140795-4669-49f4-a161-3bfdf4dad63d)
Do you have this enabled?

**Comment by KorigamiK** [comment]
> Do you have this enabled?

Thanks, I'll close this. Maybe the update had reset that setting
