### ISSUE TITLE
URL search prompt box theme doesn't align with custom or default light theme

### ISSUE THREAD

**Issue by IAmTahazzot** [zen-browser/desktop#3715]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.

### What happened?

The theme of the URL search prompt _(box/ card)_ does not align with either the custom UI theme or the default light theme. The default light (white) theme does not seem to function correctly, which suggests there may be an issue with the default theming settings. I have the default light theme `enabled`.

## Browser Setup:

- Fresh installation
- No extensions or plugins enabled

## Issues Encountered:

1. Yellowish Flash on Startup: Upon launching the browser, there is a brief flash of a yellowish color background with zen new brand logo `#f2f0e3`, similar to the background of the Zen Browser app homepage.
2. URL search prompt theme mismatch: The URL search prompt box/card does not align with the default light (white) theme, nor does it match any custom theme applied.
3. Incorrect Default Light Theme: When the default light theme is selected without applying a custom theme, the primary or main theme appears yellowish rather than the expected white color, indicating a possible issue with the default theming.

## Screenshots

With light theme enabled and custom theme color from vertical tab bar `Change Theme Colors`

![Screenshot 2024-12-13 204057](https://github.com/user-attachments/assets/1713fe64-5e50-481f-95a9-937e9f4ff633)

With light theme enabled only

![Screenshot 2024-12-13 205959](https://github.com/user-attachments/assets/05b9198d-bd0d-4a37-858d-741fb6b8ab4f)

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.1 (Firefox 133.0) (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by IAmTahazzot** [comment]
> I found 1 discussion that might be helpful:
> 
>     * [Adjust color on homepage to match zen theme](https://github.com/zen-browser/desktop/discussions/826) - This thread discusses issues related to theme color mismatches, similar to the problems you're experiencing with the new tab prompt URL box and card theme.
> 
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._
> 
> Help Dosu learn! Give it feedback: [Great Response](https://app.dosu.dev/response-feedback/7d1ced39-3220-4d6c-8b60-dc5b79534b2c?feedback_type=great_response) | [Irrelevant Answer](https://app.dosu.dev/response-feedback/7d1ced39-3220-4d6c-8b60-dc5b79534b2c?feedback_type=irrelevant_answer) | [Incorrect Sources](https://app.dosu.dev/response-feedback/7d1ced39-3220-4d6c-8b60-dc5b79534b2c?feedback_type=incorrect_sources) | [Too Verbose](https://app.dosu.dev/response-feedback/7d1ced39-3220-4d6c-8b60-dc5b79534b2c?feedback_type=too_verbose) | [Hallucination](https://app.dosu.dev/response-feedback/7d1ced39-3220-4d6c-8b60-dc5b79534b2c?feedback_type=hallucination) | [Other](https://app.dosu.dev/response-feedback/7d1ced39-3220-4d6c-8b60-dc5b79534b2c?feedback_type=other)

That is **not equivalent** to this issue here

**Comment by VoxelPrismatic** [comment]
I believe the issue is that the URL completion popup is not actually aligned with where the URL bar is *supposed* to be.

![image](https://github.com/user-attachments/assets/e2209bf0-9432-459d-be94-644206495722)

Obviously, I can reproduce
- Linux
  - Ubuntu 24.04 (KDE Neon)
  - Wayland + X11 (occurs on both)
- Zen
  - v1.0.2-b.1 (Firefox 133.0) [x64]
  - Installed via Flatpak

EDIT: Nope, different bug

**Comment by Woutuuur** [comment]
The following issue is related to the beige URL bar pop-up: https://github.com/zen-browser/desktop/issues/3477, but this one is more comprehensive.

**Comment by VoxelPrismatic** [comment]
The issue I was referring to was the floating URL bar, which I did not know was a "feature." I thought it was a rendering bug because of various Linux woes.

**Comment by mr-cheffy** [comment]
Yeah, ill move this issue into https://github.com/zen-browser/desktop/issues/3477
