### ISSUE TITLE
Udemy video is not playing

### ISSUE THREAD

**Issue by ak9473** [zen-browser/desktop#3716]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

on udemy.com video is not playing. i don't know what's happening but i am getting this problem in this browser only. i tried twilight version also but i am getting the same problem. 
platform -- windows 11

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.1

### What platform are you seeing the problem on?

Windows

**Comment by mr-cheffy** [comment]
https://docs.zen-browser.app/faq#why-cant-zen-browser-play-drm-protected-content
