### ISSUE TITLE
How to adjust tab sidebar width?

### ISSUE THREAD

**Issue by Adish08** [zen-browser/desktop#3721]
### Captchas

- [x] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.

### What happened?

When using the right side, I am unable to set a custom size for the width of the side panel.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Latest Beta

### What platform are you seeing the problem on?

Windows

**Comment by Smooth-E** [comment]
Not reproducible for me on `1.0.2-b.1` on Windows 11. Dragging the edge of the sidebar that is attached to the right side of the screen I can adjust the width from the lowest possible to the widest possible of it (there is a pre-defined maximum width).

The issue description says *latest beta*. Make sure you are up to date.

**Comment by FadedAtlas** [comment]
@Smooth-E 
I struggle with the same problem, version 1.0.2-b.1 Windows 11.
I think that previous profile settings before update could cause this.

Also worth mentioning even when it's another bug, the space my side bar takes on the right, "cuts out" webpage and nav buttons on the left.
I literally don't have back button, only forward.

Edit:
"I think that previous profile settings before update could cause this."
I mean that this is probably bugged profile issue, not core package.
And I mean that setting everything from ground up in the new profile, would solve the problem.
But I'm not doing that today, maybe later.

**Comment by Adish08** [comment]
@Smooth-E PFA this Screen Recording:


https://github.com/user-attachments/assets/a9676bfc-c7fd-404f-9c2a-8254eff7f311

**Comment by Smooth-E** [comment]
@nickelberg @Adish08 sure, I encountered this issue some time after my initial comment as well. And I use the browser with almost default setting, so I think this is just a general bug somewhere.

**Comment by RayZ3R0** [comment]
I am not getting this on mine, can you try latest beta, which is now b.2

**Comment by seruxGC** [comment]
I found another issue where it is explained that this fixed-width behavior of the sidebar is normal. Here, it explains how it works.

https://github.com/zen-browser/desktop/issues/3735

**Comment by neurokitti** [comment]
this issue is because you have too many buttons in a row. you can right click on the sidebar then choose customize toolbar in order to rearrange items so there are not as many buttons in the sidebar
