### ISSUE TITLE
The address bar is not focused when opening a new window

### ISSUE THREAD

**Issue by BenoitAverty** [zen-browser/desktop#373]
### What feature would you like to see?

When I open a new tab with ctrl+t, the address bar is focused so I can immediately start typing the adress of the website I want to visit.

When I open a new window with ctrl+n it is not the case, so I need to grab my mouse or press f6 before I can type an address. Is it possible to have the behavior of a new tab on a new window as well ?

Thanks in advance.

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
This has been reported infinite times, please check before reporting. Thanks!
