### ISSUE TITLE
Compact mode bug (zIndex)

### ISSUE THREAD

**Issue by Frxncis-13** [zen-browser/desktop#3731]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I don't think the browser should do this, as this interferes with buttons. The refresh button and expand sidebar button. 

https://github.com/user-attachments/assets/1ae59be1-946e-45a2-9d29-769a456264bb

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.1

### What platform are you seeing the problem on?

Windows

**Comment by mr-cheffy** [comment]
This should be fixed now! Please let us know if it hasnt been fixed

**Comment by Frxncis-13** [comment]
It has been fixed thank you very much
