### ISSUE TITLE
unresizeble sidebar

### ISSUE THREAD

**Issue by lovitus** [zen-browser/desktop#3735]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![image](https://github.com/user-attachments/assets/54959f5e-11af-4eb2-aa72-bc789c4a4cd0)
---
![image](https://github.com/user-attachments/assets/71e3c138-f929-46bc-8b23-21ed34c374a2)

---
the sidebar is at fixed width,unable to adjust.
if pinned more plugin, the width would occupied all the display area

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

latest

### What platform are you seeing the problem on?

Windows

**Comment by rubaboo** [comment]
Another awesome at first look new feature—single toolbar mode. The only choices are to have the sidebar collapsed or to have it as wide as needed to fit all pinned extension buttons in a single row.

**Comment by Slusho64** [comment]
Part of the problem is that there shouldn't be so many buttons there. Pinned extensions especially need to be relocated. Having that row in the top left be a catch-all for nearly every button in the browser is leading to a very cluttered look and creating issues like this.

**Comment by lovitus** [comment]
The only reason I use Zen because it saves screen for immersive content display.
But after the update , the sidebar took half of my screen, I have to disable the entire sidebar but to use Vertical tabs or Sidebery instead .

I was very happy since zen first released.

**Comment by rubaboo** [comment]
@lovitus why close, you have a workaround, or gave up on Zen? :)

I agree there should be another "bar" or even a "grid" somewhere to display all pinned extensions and browser buttons. Currently I unpinned all the extensions and removed or hid in the overflow menu all the buttons, to keep the sidebar width reasonable.

**Comment by JSGRD22** [comment]
You can move pinned extensions and other browser buttons to the pop-up bookmarks bar in single toolbar mode by switching to multiple toolbar mode, using customise toolbar and switching back.

**Comment by rubaboo** [comment]
I don't get it. Where/How do I make the bookmarks bar popup? Once I switch back, it just disappears.

**Comment by JSGRD22** [comment]
The bookmarks bar will be set to "show only on new tab" by default when you switch back to single toolbar mode, press ctrl+shift+B to make it always show

**Comment by rubaboo** [comment]
IDK, ctrl+shift+B only works in Multiple toolbars mode for me. In single toolbar mode, no bookmarks bar visible in a new tab, nor does it popup when hitting ctrl+shift+B.

**Comment by JSGRD22** [comment]
it shouldn’t pop up, the icons should just be present when you hover over the top to show the bookmarks bar.

**Comment by rubaboo** [comment]
> You can move pinned extensions and other browser buttons to the pop-up bookmarks bar in single toolbar mode by switching to multiple toolbar mode, using customise toolbar and switching back.

Ok, I got it. Thank you for your patience.

It's not a "pop-up bookmarks bar" but a "slide-down bookmarks bar", and it only appears (slides down) in a new tab.

Unfortunately, most of the times I want to see my extensions and buttons while in a loaded tab, not in a new tab.

**Comment by JSGRD22** [comment]
They should appear in the loaded tab if your bookmarks bar is set to always show. The way I do it is if in a loaded tab the items are not showing, press ctrl+shift+B within the loaded tab. Then the icons should show upon reopening the bar, no matter whether you’re in a new tab or not.
