### ISSUE TITLE
side bar opens up when ctrl + tabbing (compact mode)

### ISSUE THREAD

**Issue by redrumthebum** [zen-browser/desktop#3741]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

every time i `ctrl + tab` from one tab to another, the sidebar opens up for a brief moment. it gets really tedious when i'm quickly going back and forth between tabs 😅

sidebar settings:
- compact mode enabled
- sidebar hidden

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.1

### What platform are you seeing the problem on?

Windows

**Comment by ihsanfansyuri** [comment]
Did you enable the option `Briefly make the toolbar popup when switching or opening new tabs in compact mode` in the settings? Try to disable it.

**Comment by redrumthebum** [comment]
> Did you enable the option `Briefly make the toolbar popup when switching or opening new tabs in compact mode` in the settings? Try to disable it.

oh, i didn't know there was an option for that! thank you! 😅
