### ISSUE TITLE
Options for keybinds to swap tabs missing

### ISSUE THREAD

**Issue by tommerty** [zen-browser/desktop#3745]
### Captchas

- [x] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.

### What happened?

A while ago I created the following issue regarding shortcuts to navigate between tabs: https://github.com/zen-browser/desktop/issues/580

It seems however now that these options have been removed. I'm assuming bug that this was an accidental regression

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.1 (Firefox 133.0) (64-bit)

### What platform are you seeing the problem on?

Linux, macOS - aarch64, Windows

### Relevant log output

```shell

```

**Comment by mr-cheffy** [comment]
>  I have searched existing issues and avoided creating duplicates.

Please, the checkboxes arent there to verify you are a robot... This issue is created ever single day

**Comment by tommerty** [comment]
Apologies @mr-cheff I could not find one, rest assured I didn't just check them without reading. Apologies for not finding any previous related issues

**Comment by mr-cheffy** [comment]
No need to apologise! It's that this issue has been flooded lately
