### ISSUE TITLE
Bookmarks Toolbar keeps reappearing on startup

### ISSUE THREAD

**Issue by p2js** [zen-browser/desktop#3746]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Every time I boot up Zen, the bookmarks toolbar reappears on new tab, despite my efforts to disable it. I don't think this should happen. 

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b1

### What platform are you seeing the problem on?

Windows

**Comment by 12th-devs** [comment]
Yeah, I've noticed this too, I can't find the setting to hind it, you could use some custom css to hide it in the meantime

**Comment by tommdq** [comment]
Got the same issue after updating to the last version. You can disable it by right clicking on the bookmark bar by clicking on _never show_

![image](https://github.com/user-attachments/assets/ad5f2be4-12b7-4998-9b22-3b1d1cb5723f)

**Comment by mikedlr** [comment]
I had similar problem on firefox sometimes. I think it's caused by one of the extensions I use. Do you have any extensions? Can you get it to happen in a new profile without any extensions?

**Comment by djorium** [comment]
> I had similar problem on firefox sometimes. I think it's caused by one of the extensions I use. Do you have any extensions? Can you get it to happen in a new profile without any extensions?

Try what he said
