### ISSUE TITLE
Buttons and search bar randomly move every update

### ISSUE THREAD

**Issue by Xerxes004** [zen-browser/desktop#3749]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I have updated 3 times in the past 2 weeks. Each time, the buttons are randomly placed at the top, the search bar gets moved to somewhere random, and now my addons and navigation controls are all smashed into the left side of the window above the tab bar. It also asks me to do the full color-theme selection every time the app updates.

This is not "zen" for me.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

latest

### What platform are you seeing the problem on?

Windows

**Comment by mr-cheffy** [comment]
![image](https://github.com/user-attachments/assets/0853123e-c2d4-44b8-a5b9-2cb925422213)

Selects single toolbar layout -> complains the UI is... in a single toolbar

**Comment by Xerxes004** [comment]
I didn’t select it, friend.

**Comment by mr-cheffy** [comment]
Select it then, it was on the on boarding page that opened after updating

**Comment by Xerxes004** [comment]
> Select it then, it was on the on boarding page that opened after updating

I did select it. It never goes away. Every time I open it asks me what theme I want. Do you guys just not care or what?

edit: to be clear, I did not select the compact theme, but I did select the color theme. It still just asks me every time I open the app.
