### ISSUE TITLE
Missing keyboard shortcut to collapse tab pane?

### ISSUE THREAD

**Issue by marcusprice** [zen-browser/desktop#3752]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Since upgrading to Version 1.0.2-b.1 (64-bit) on arch linux, the keyboard shortcut to collapse/uncollapse the tabs pane (the behavior from clicking on the left and right arrows) is missing. It works if I click the button, but I'd much rather have a keyboard shortcut for it.

Has this been removed, or am I just unable to find it? Want to note that I can enter/exit compact mode, but that's undesirable because I can't see and click on tabs while the tab pane is missing.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.1 (64-bit)

### What platform are you seeing the problem on?

Linux

**Comment by gomster** [comment]
keyboard shortcut come back after the last update on windows this day - is it same for you ?

**Comment by mr-cheffy** [comment]
This should be added now, thanks!
