### ISSUE TITLE
Dark Reader weird behavior

### ISSUE THREAD

**Issue by rauldipeas** [zen-browser/desktop#3753]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When Dark Reader is enabled, all white elements on the window became dark.
![image](https://github.com/user-attachments/assets/df4b5bbc-201b-4b5d-a9bd-1ade05ba793e)

When it's disable, everything works as it should be.
![image](https://github.com/user-attachments/assets/98326c84-c6e2-43d4-8857-bde8069a93fd)

Any idea on how to fix?

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.1

### What platform are you seeing the problem on?

Windows

**Comment by mr-cheffy** [comment]
It's because you have a mod installed that affects the text. Please try removing them and let us know if we the problem persists

**Comment by rauldipeas** [comment]
> It's because you have a mod installed that affects the text. Please try removing them and let us know if we the problem persists

Even when I disable all mods the behavior is the same.

**Comment by rauldipeas** [comment]
With all mods disabled.
![image](https://github.com/user-attachments/assets/37b18f07-fcb6-43da-b811-60dc2e5aeb56)

**Comment by rauldipeas** [comment]
> It's because you have a mod installed that affects the text. Please try removing them and let us know if we the problem persists

Why You not reopen the issue? It's clearly not solved.
