### ISSUE TITLE
Visual problems occur when playing embedded videos on websites presented in picture-in-picture mode in zen browser using it under GNU/Linux.

### ISSUE THREAD

**Issue by krafairus** [zen-browser/desktop#3758]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Visual problems occur when playing embedded videos on websites presented in picture-in-picture mode in the zen browser used in GNU/Linux.

I am currently using the latest version of zen browser on mx linux, 1.0.2-b.2 and this problem continues to occur, previously in previous versions the problem also occurs, but when I use firefox the problem does not occur and it never happens with Firefox, it is more of a visual problem.

Steps to reproduce it:

Open the browser.
Open the website "https://www.freecodecamp.org/espanol/news/aprende-a-programar-en-python-desde-cero-curso-completo-gratis/" or another website with an embedded youtube video.
Play the video.

After that, visual errors are evident.

System information:
  Kernel: 6.1.0-27-amd64 [6.1.115-1] arch: x86_64 bits: 64 compiler: gcc v: 12.2.0
    parameters: BOOT_IMAGE=/boot/vmlinuz-6.1.0-27-amd64 root=UUID=<filter> ro quiet splash
    init=/lib/systemd/systemd
  Desktop: KDE Plasma v: 5.27.5 tk: Qt v: 5.15.8 wm: kwin_x11 vt: 7 dm: SDDM
    Distro: MX-23.4_KDE_x64 Libretto September 15 2024 base: Debian GNU/Linux 12 (bookworm)
CPU:
  Info: model: Intel Core i3-1005G1 bits: 64 type: MT MCP arch: Ice Lake gen: core 10 level: v4
    note: check built: 2019-21 process: Intel 10nm family: 6 model-id: 0x7E (126) stepping: 5
    microcode: 0xC6
  Topology: cpus: 1x cores: 2 tpc: 2 threads: 4 smt: enabled cache: L1: 160 KiB
    desc: d-2x48 KiB; i-2x32 KiB L2: 1024 KiB desc: 2x512 KiB L3: 4 MiB desc: 1x4 MiB
  Speed (MHz): avg: 825 high: 1285 min/max: 400/3400 scaling: driver: intel_pstate
    governor: powersave cores: 1: 1217 2: 1285 3: 400 4: 400 bogomips: 9523
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
  Vulnerabilities:
  Type: gather_data_sampling mitigation: Microcode
  Type: itlb_multihit status: KVM: VMX disabled
  Type: l1tf status: Not affected
  Type: mds status: Not affected
  Type: meltdown status: Not affected
  Type: mmio_stale_data mitigation: Clear CPU buffers; SMT vulnerable
  Type: reg_file_data_sampling status: Not affected
  Type: retbleed mitigation: Enhanced IBRS
  Type: spec_rstack_overflow status: Not affected
  Type: spec_store_bypass mitigation: Speculative Store Bypass disabled via prctl
  Type: spectre_v1 mitigation: usercopy/swapgs barriers and __user pointer sanitization
  Type: spectre_v2 mitigation: Enhanced / Automatic IBRS; IBPB: conditional; RSB filling;
    PBRSB-eIBRS: SW sequence; BHI: SW loop, KVM: SW loop
  Type: srbds mitigation: Microcode
  Type: tsx_async_abort status: Not affected
Graphics:
  Device-1: Intel Iris Plus Graphics G1 vendor: Hewlett-Packard driver: i915 v: kernel arch: Gen-11
    process: Intel 10nm built: 2019-21 ports: active: eDP-1 empty: DP-1, DP-2, DP-3, DP-4, HDMI-A-1
    bus-ID: 00:02.0 chip-ID: 8086:8a56 class-ID: 0300
  Device-2: Cheng Uei Precision Industry (Foxlink) HP TrueVision HD Camera type: USB
    driver: uvcvideo bus-ID: 1-6:2 chip-ID: 05c8:03d2 class-ID: 0e02
  Display: x11 server: X.Org v: 1.21.1.7 with: Xwayland v: 22.1.9 compositor: kwin_x11 driver: X:
    loaded: modesetting unloaded: fbdev,vesa dri: iris gpu: i915 display-ID: :0 screens: 1
  Screen-1: 0 s-res: 1366x768 s-dpi: 96 s-size: 361x203mm (14.21x7.99") s-diag: 414mm (16.31")
  Monitor-1: eDP-1 model: BOE Display 0x0697 built: 2015 res: 1366x768 hz: 60 dpi: 112 gamma: 1.2
    size: 309x173mm (12.17x6.81") diag: 354mm (13.9") ratio: 16:9 modes: 1366x768
  API: OpenGL v: 4.6 Mesa 24.2.2-1~mx23ahs renderer: Mesa Intel UHD Graphics (ICL GT1)
    direct-render: Yes
Audio:
  Device-1: Intel Ice Lake-LP Smart Sound Audio vendor: Hewlett-Packard driver: snd_hda_intel
    v: kernel alternate: snd_sof_pci_intel_icl bus-ID: 00:1f.3 chip-ID: 8086:34c8 class-ID: 0403
  API: ALSA v: k6.1.0-27-amd64 status: kernel-api tools: alsamixer,amixer
  Server-1: PipeWire v: 1.0.0 status: active with: 1: pipewire-pulse status: active
    2: wireplumber status: active 3: pipewire-alsa type: plugin 4: pw-jack type: plugin
    tools: pactl,pw-cat,pw-cli,wpctl
Info:
  Processes: 214 Uptime: 1h 29m wakeups: 1 Memory: 7.45 GiB used: 2.99 GiB (40.1%) Init: systemd
  v: 252 target: graphical (5) default: graphical tool: systemctl Compilers: gcc: 12.2.0 alt: 12
  Client: shell wrapper v: 5.2.15-release inxi: 3.3.26
Boot Mode: UEFI

https://github.com/user-attachments/assets/471fd2ee-5cef-41d1-82f6-ff8f34d1fd85

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.2

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
[Parent 16817, Main Thread] WARNING: g_find_program_in_path: assertion 'program != NULL' failed: 'glib warning', file /home/runner/work/desktop/desktop/engine/toolkit/xre/nsSigHandlers.cpp:201

(zen-beta:16817): GLib-CRITICAL **: 22:49:46.317: g_find_program_in_path: assertion 'program != NULL' failed
libva info: VA-API version 1.18.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_17
libva info: va_openDriver() returns 0
```

**Comment by djorium** [comment]
Works perfectly fine on my machine, Try a different profile and tell me what happens please.

**Comment by krafairus** [comment]
> Works perfectly fine on my machine, Try a different profile and tell me what happens please.

jajja, I think it's a zen mods extension that causes this problem, I'll check what it is, in a new profile it works normally.


https://github.com/user-attachments/assets/49bff80e-3ae8-4240-80a1-55ec20239312

**Comment by krafairus** [comment]
> Works perfectly fine on my machine, Try a different profile and tell me what happens please.

It is a Firefox extension that I have installed that causes the problem, a thousand apologies, the extension has an option that causes the problem in the Firefox/Zen browser, apologies again, have a nice night. :)

![imagen](https://github.com/user-attachments/assets/7ff0f729-5a03-46d1-8152-c99380a5b603)

Zen Browser is good, thanks :)
By the way, I have noticed that sometimes, very strangely, the browser closes suddenly, it also presents problems when right-clicking, I used the appimage version, I reviewed the log and placed it in a new report, I will close this, thanks.

**Comment by djorium** [comment]
Thanks a lot for checking it out yourself and doing some testing, it's much appreciated when people make an effort!
