### ISSUE TITLE
Floating Web Panel Disappears When Clicking elsewhere on the Screen

### ISSUE THREAD

**Issue by NicoMel1907** [zen-browser/desktop#3759]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I am not sure if this is the developer's intention, but I would love for the web panel to stay on the screen even when I click somewhere else. Sometimes I need to quickly check something and copy and paste from the main window - or tab. However, the web panel disappears when I do that (calculations etc.)

I wanted to highlight this here because I remember being able to keep the web panel open occasionally, but not now.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.2 

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by djorium** [comment]
There's an option for that in the settings, plus you can click the pin button on it. 
![image](https://github.com/user-attachments/assets/8570a566-f122-4bfe-927d-7d254590a273)
