### ISSUE TITLE
this last update is GARBAGE!!! why would you do that to the address bar when you click once it moves to the center. and the new logo sucks. im probably going back to firefox 

### ISSUE THREAD

**Issue by jlewsi** [zen-browser/desktop#3762]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

not loving this last update !!! why would you do that to the address bar when you click once it moves to the center. and the new logo sucks. im probably going back to firefox 

![image](https://github.com/user-attachments/assets/056740b2-ef2c-4282-af23-96566bcede48)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b2

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
it was absolutely perfect before this
```

**Comment by tashilapathum** [comment]
The address bar is fixed in v1.0.2-b2. 

![image](https://github.com/user-attachments/assets/0cf534fb-878c-4623-8311-41be7b0b10e9)

Btw what do you mean by the new logo sucks? The old logo was a sick looking unique design of the letter 'Z' to represent the word 'Zen'. You know what's miles better than that? 3 circles. The reasoning is beyond our understanding.

**Comment by jlewsi** [comment]
Thankyou so much for fixing the address bar. I thought it was something you added. I mean, I was gonna figure out a way to deal with it, but it was bad. You could no longer double click on the line and copy, which I do often. 

Sorry for calling it garbage tho. This is by far the best browser I have ever used. Mine **is** starting to feel bloated and gets sluggish after it's been opened for a while. I end up having to close all windows and re-start it halgway through the day.

**Comment by ByAldon** [comment]
Please be nice. They are making this browser for free for people to use. They are doing their best to make the best privacy focused browser that exist. Don't be a brat.
And for being privacy focussed. If you wanna change browser, you are better of using https://floorp.app/en for now.
I have this one too but still have zen installed too as i have high hopes in the devs. Please keep up the great job!

**Comment by KorigamiK** [comment]
The dev doesn't seem to care to actually look into issues. Absolutely no feedback is being taken from github

**Comment by JSGRD22** [comment]
> The dev doesn't seem to care to actually look into issues. Absolutely no feedback is being taken from github

What about this. Get a list of what you want improved in the browser, code it yourself, and make a PR, I’m sure everyone would appreciate it. Our dear developer is very overworked, and seeing your enthusiasm about taking feedback and rectifying issues, he could definitely use your assistance.

**Comment by ByAldon** [comment]
> > The dev doesn't seem to care to actually look into issues. Absolutely no feedback is being taken from github
> 
> What about this. Get a list of what you want improved in the browser, code it yourself, and make a PR, I’m sure everyone would appreciate it. Our dear developer is very overworked, and seeing your enthusiasm about taking feedback and rectifying issues, he could definitely use your assistance.

Agreed. I am a developer myself but i am no where near building a browser like this. I have respect for the dev's they doing this for the people.

And because they do not respond does not mean they wont read.

**Comment by mr-cheffy** [comment]
Chill, it's a preference

**Comment by mr-cheffy** [comment]
> > > The dev doesn't seem to care to actually look into issues. Absolutely no feedback is being taken from github
> > 
> > 
> > What about this. Get a list of what you want improved in the browser, code it yourself, and make a PR, I’m sure everyone would appreciate it. Our dear developer is very overworked, and seeing your enthusiasm about taking feedback and rectifying issues, he could definitely use your assistance.
> 
> Agreed. I am a developer myself but i am no where near building a browser like this. I have respect for the dev's they doing this for the people.
> 
> And because they do not respond does not mean they wont read.

Yeah, people see 700 issues on gh, I dont respond for 1 day. This means I completly ignore github 👍🏽 

insane
