### ISSUE TITLE
URL bar missing on windows of different workspaces

### ISSUE THREAD

**Issue by daynardn** [zen-browser/desktop#3764]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When I switch to a new workspace in my DE, Hyprland, opening a new zen instance, the url bar in Single toolbar mode is missing. Opening a zen instance in the same window it shows up correctly. 

https://github.com/user-attachments/assets/692bbfe3-883e-4aef-b4ca-5cd52d8bf6e4

This issue appeared when I switched to the beta release with the side url bar (Single toolbar mode).

No mods on or user css, just the browser. I am running NixOS, and running from a flake of the flatpack. When I click on "New Tab" in the broken window, it lights up where the url bar should be but there is no bar there.

(PS. love the browser, I'm not here to hate)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.2

### What platform are you seeing the problem on?

Linux

**Comment by raphael-soares** [comment]
Same issue here, the workspace container takes over the url bar space


![image](https://github.com/user-attachments/assets/7d87ad9b-aa80-4856-8a64-35414a4b1b1e)

**Comment by daynardn** [comment]
Closing this issue, 1.0.2-b.4 seems to have patched this for me.

**Comment by raphael-soares** [comment]
Using 1.0.2-b.5 and still the same
![image](https://github.com/user-attachments/assets/e6e12d03-e01e-483a-9d6d-f41b73e95316)
