### ISSUE TITLE
Collapsed toolbar close tab shortcut

### ISSUE THREAD

**Issue by merdow** [zen-browser/desktop#3766]
### Captchas

- [ ] I have read the instructions.
- [ ] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

Previous versions had close "X" image to close tab.
But unfortunetely newer version doesn't have it.
I strongly recommend that bringing it back for better user experience.
Thanks for your work.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.2

### What platform are you seeing the problem on?

Windows

**Comment by mr-cheffy** [comment]
It was a mod you've installed. It never had the X
