### ISSUE TITLE
{BUG} Zen Browser theme's color breaks site White color scheme.

### ISSUE THREAD

**Issue by Adish08** [zen-browser/desktop#3768]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

These happens on so may sites, some Examples are:

https://www.pixelcut.ai/ 
![image](https://github.com/user-attachments/assets/17bc9044-d5b1-40aa-b717-a119f91f01c2)

https://samsung.com/
![image](https://github.com/user-attachments/assets/ab1d74bd-8013-416e-acf1-52eecc746b89)

And much more....

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b2

### What platform are you seeing the problem on?

Windows

**Comment by mr-cheffy** [comment]
Turn `browser.tabs.allow_transparent_browser` to false in about:config

>  I have searched existing issues and avoided creating duplicates.

This isnt there to verify you are a bot
