### ISSUE TITLE
Tab icons: mute Button shifts favicon to the left & mute icon is not really visible

### ISSUE THREAD

**Issue by bdbch** [zen-browser/desktop#377]
### What happened?

Right now the mute button will shift the favicon to the left by 2-3 pixels.

![image](https://github.com/user-attachments/assets/d95cf375-ac96-4716-934f-efb38e367938)

Also the mute button is not really visible. I can barely see it on that Youtube Music favicon. Should it be more solid?

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.26

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
This has been reported before 👍
