### ISSUE TITLE
Empty hoverable top bar in Single Toolbar mode

### ISSUE THREAD

**Issue by DontBlameMe99** [zen-browser/desktop#3773]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

There is a empty top bar which you can hover when using the "Single Toolbar" mode. It should not be there, since it is completely empty and useless. Pleae see the video for further clarification.

I have tried disabling all the zen mods, it did not change anything. I have also installed a new fresh version of Zen (and just enabled single toolbar mode) and I could reproduce the issue.

https://github.com/user-attachments/assets/0acafb1c-7ec5-43c5-b412-2c456271413c

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.2

### What platform are you seeing the problem on?

Linux

**Comment by djorium** [comment]
Does your CSS hide the exit buttons? and also it keeps bookmarks there...

**Comment by DontBlameMe99** [comment]
> Does your CSS hide the exit buttons? and also it keeps bookmarks there...

Yes my CSS hides some stuff in there. But as I said I tried it out with a fresh install of the browser and it still appeared. So I don't think that it has to do anything with my custom CSS.

**Comment by djorium** [comment]
Your CSS is hiding the Exit buttons that the bar was made to show, it has everything to do with custom CSS.

**Comment by LordPax** [comment]
if custom css is "userChrome.css", i didn't have custom css (except on Firefox), and have the exact same issue

**Comment by DontBlameMe99** [comment]
> Your CSS is hiding the Exit buttons that the bar was made to show, it has everything to do with custom CSS.

As I have already said, I have tried it with a NEW INSTALLATION which is DEFAULT and uses NO custom css. So it has nothing to do with that.

**Comment by djorium** [comment]
It still has everything to do with that dude 😭 
![image](https://github.com/user-attachments/assets/19350d0e-7af7-4205-9186-fec0a7b6daca)
used for **bookmarks** and **maximize/minimize/close buttons**

**Comment by djorium** [comment]
it will not go AWAY no matter what because its for the BOOKMARKS

**Comment by JSGRD22** [comment]
It's just how it is. But you can make the most of it by putting toolbar items and extension icons there where they otherwise wouldn't fit in the sidebar:
![image](https://github.com/user-attachments/assets/6b65e54f-25f2-4b5b-93f9-bbb93185999e)

**Comment by LordPax** [comment]
@djorium ok its use for bookmarks but i thinks you misunderstood something, if we don't have maximized/minimize/close button, it's not because of custom css, it's because we use a tailing window manager. Is there a way to hide this empty bar ?

**Comment by DontBlameMe99** [comment]
> @djorium ok its use for bookmarks but i thinks you misunderstood something, if we don't have maximized/minimize/close button, it's not because of custom css, it's because we use a tailing window manager. Is there a way to hide this empty bar ?

True that might be it (because of the tiling wm). Then it would just be amazing to have a way to hide it if there are no buttons (due to someone using a tiling wm).

**Comment by DontBlameMe99** [comment]
> it will not go AWAY no matter what because its for the BOOKMARKS

Even if the bookmark bar is hidden? (Yes it might still be for the (not present in a tiling wm) window decorations).
Again, it would be amazing if there would be a about:config option (or something similar) to hide that (for me) useless bar.

**Comment by JSGRD22** [comment]
Not a bug, you can suggest it in the discussions section and close this issue

**Comment by DontBlameMe99** [comment]
> It's just how it is. But you can make the most of it by putting toolbar items and extension icons there where they otherwise wouldn't fit in the sidebar: ![image](https://private-user-images.githubusercontent.com/73097618/396365968-6b65e54f-25f2-4b5b-93f9-bbb93185999e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0NDQyNDgsIm5iZiI6MTczNDQ0Mzk0OCwicGF0aCI6Ii83MzA5NzYxOC8zOTYzNjU5NjgtNmI2NWU1NGYtMjVmMi00YjViLTkzZjktYmJiOTMxODU5OTllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDEzNTkwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwZjBlNDNmNDM5MGE4ODg3NTI3NGY1YWYzYmQ2MDdiNzcwM2QyOGMwNTExNTE2MzYyODY4MGM4YTdhMzQ3YTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zGAXlXNnTI_BpoQYm2FT1LNpAsxvWnHsFPcm5gceh4U)

Thanks for this idea. Even though imo this is basically just recreating the single toolbar mode with compact mode enabled (except that the URL bar is now on the side and not in the mid). But maybe this is something I have to try out ._.

**Comment by DontBlameMe99** [comment]
> Not a bug, you can suggest it in the discussions section and close this issue

Yeah, thanks.

**Comment by DontBlameMe99** [comment]
@LordPax created a discussion at #3857.
