### ISSUE TITLE
Irrespective of theming in zen browser.

### ISSUE THREAD

**Issue by rishibose25** [zen-browser/desktop#3783]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

After updating Zen Browser to version 1.0.2-b.2, the browser doesn't follow OS theme. The issue occurs immediately after changing to Light theme in OS.
![screenshot-2024-12-15-11-15-55](https://github.com/user-attachments/assets/c26ac6e3-64b9-4939-8a30-125125dbaf0c)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.2 

### What platform are you seeing the problem on?

Linux

**Comment by mr-cheffy** [comment]
![image](https://github.com/user-attachments/assets/9228ad63-5689-460c-ad98-f598d6f45c35)

**Comment by rishibose25** [comment]
![screenshot-2024-12-16-11-52-46](https://github.com/user-attachments/assets/68a54048-5850-4299-a84e-acf2c422a8c8)

Now what?
