### ISSUE TITLE
TAB ordering - Selection of input with tab

### ISSUE THREAD

**Issue by OfficialAudite** [zen-browser/desktop#3784]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

So when you select an input field like username & password. And want to tab from username to password, it just does not work. Same thing with youtube, cant use arrow keys to skip forward.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.2 (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by mr-cheffy** [comment]
Could you send a video? It works for me

**Comment by OfficialAudite** [comment]
> Could you send a video? It works for me

https://github.com/user-attachments/assets/5c149a0b-c47f-4436-a806-329ecd5751ce

**Comment by OfficialAudite** [comment]
Solves itself once the OS is restarted.
