### ISSUE TITLE
[Bug] A floating URL bar turn back to the normal while typing Japanese

### ISSUE THREAD

**Issue by hiyama283** [zen-browser/desktop#3787]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Floating URL bar turn back to the Normal Behaviour while typing Japanese but Behaviour mode is "Always Floating".
https://streamable.com/sgrywf

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.2

### What platform are you seeing the problem on?

Windows

**Comment by ClixTW** [comment]
Try enabling this setting:  
`Settings - Firefox Labs - Address Bar: show results during IME composition`

**Comment by hiyama283** [comment]
> Try enabling this setting: `Settings - Firefox Labs - Address Bar: show results during IME composition`

Solved thank you
