### ISSUE TITLE
PWA Support

### ISSUE THREAD

**Issue by erffy** [zen-browser/desktop#379]
### What feature would you like to see?

If PWA support comes like in Chromium, I will switch from Chromium to Zen browser. 
Good luck to your team.

### What platform are you seeing the problem on?

Linux

**Comment by Himasnhu-AT** [comment]
Hey, I'm new to this repo. how can I contribute to it, lemme know.

**Comment by n7itro** [comment]
@Himasnhu-AT join the Discord to learn how to contribute.

Issue is duplicate of #298 and #285
