### ISSUE TITLE
Top bar is visible on fullscreen

### ISSUE THREAD

**Issue by BlueFox1616** [zen-browser/desktop#3792]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The top bar stills shows when on full-screen 
![Screenshot From 2024-12-15 20-09-17](https://github.com/user-attachments/assets/8a90bf49-766f-44a7-9109-fa52633a34d0)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Beta build - 1.0.2-b.2 (2024-12-14)

### What platform are you seeing the problem on?

Linux

**Comment by mr-cheffy** [comment]
It doesnt happen to me, make sure you have no mods

**Comment by BlueFox1616** [comment]
i disabled all mods still happens

**Comment by mr-cheffy** [comment]
Could you give more info? Like what layout is being displayed, if the tabs are on the right side, if compact mode is enabled, etc? Thanks
