### ISSUE TITLE
Floating while typing works one single time

### ISSUE THREAD

**Issue by RodsonMatos** [zen-browser/desktop#3793]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The url bar floating while typing option only works when the url bar is empty and for the very first time.

https://github.com/user-attachments/assets/77209739-af87-4831-b59a-8ad5c04dc044

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.2

### What platform are you seeing the problem on?

Linux

**Comment by djorium** [comment]
I believe thats because floating while typing happens when you **don't** click the URL bar

**Comment by da-crab** [comment]
You can set to "always floating" at the bottom of "look and feel" settings.

**Comment by Frederic-C** [comment]
I think it is the best behavior. Cliking the toolbar and getting the floating bar to appear, was the previous behavior and lot of people complains as it needs more clicks to be used.

**Comment by RodsonMatos** [comment]
> I believe thats because floating while typing happens when you **don't** click the URL bar

You're right. CTRL + L works correctly,

**Comment by djorium** [comment]
![4f3d7a08-d1ca-46c4-9540-c13e482c51f1](https://github.com/user-attachments/assets/bff0fa53-bfe8-4abd-a6ea-cb285859a814)

You can change this behavior here thank you.
