### ISSUE TITLE
Searchbar Misalignment in Collapsed Sidebar

### ISSUE THREAD

**Issue by AndorkaDominik** [zen-browser/desktop#3795]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

## Searchbar Misalignment in Collapsed Sidebar

When the sidebar is collapsed, the search widget in the custom toolbar appears `misaligned` or `cut off`, as shown in the attached image. 

#### Screenshot for reference:

This highlights the problem clearly and includes a note about the screenshot for developers to review.

![Képernyőfelvétel (467)](https://github.com/user-attachments/assets/95c88023-f75f-47a3-b501-17d9cf5d6f4d)

## Suggestion
Hovering over or clicking the `search icon` could temporarily `expand the search input field`.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.2 

### What platform are you seeing the problem on?

Windows

**Comment by mr-cheffy** [comment]
I dont think you are supposed to do that...

**Comment by djorium** [comment]
Neither do I

**Comment by neurokitti** [comment]
yeah no i dont think thats what your supposed to do.

**Comment by FantasticMrCat42** [comment]
neither do I

**Comment by nocanoa** [comment]
nEiThEr Do I
