### ISSUE TITLE
![image](https://github.com/user-attachments/assets/0853123e-c2d4-44b8-a5b9-2cb925422213)

### ISSUE THREAD

**Issue by Xerxes004** [zen-browser/desktop#3798]
![image](https://github.com/user-attachments/assets/0853123e-c2d4-44b8-a5b9-2cb925422213)

Selects single toolbar layout -> complains the UI is... in a single toolbar

_Originally posted by @mr-cheff in https://github.com/zen-browser/desktop/issues/3749#issuecomment-2544152435_

not solved.

**Comment by mr-cheffy** [comment]
Please dont make new issues, please comment in there
