### ISSUE TITLE
Floating URL bar off screen when tabs on right

### ISSUE THREAD

**Issue by abdmoh123** [zen-browser/desktop#3800]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When I enable tabs on right (single toolbar mode) in compact mode, the floating toolbar doesn't appear when I try typing.
When I switch the sidebar back to the left, the floating bar appears as normal. The floating bar also appears when I disable compact mode.
My guess is that the floating bar is displayed outside of my screen to the right, which is why it's invisible (see diagram below).

```
+----------------+
|                |       ___________
|                |       | search  |
|                |       ‾‾‾‾‾‾‾‾‾‾‾
|                |
+----------------+
```

Here is a real image:

![image](https://github.com/user-attachments/assets/96994cc0-def1-4975-94bc-98d541eb0882)

Also, when I disable the floating URL bar feature, the URL bar is cut off to the right.

![image](https://github.com/user-attachments/assets/79c0dfc0-0408-4516-96e7-45c1ef43c231)

I apologise in advance if this is a duplicate issue. I tried my best to see if anyone else made one before me, but I couldn't find any.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Version 1.0.2-b.2 (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by djorium** [comment]
Will be worked on.

**Comment by mr-cheffy** [comment]
Should be fixed now 👍🏽 Please let us know if it hasnt and ill reopen

**Comment by abdmoh123** [comment]
Yeah it's fixed now thanks. I prefered when the close/maximise/minimise buttons where in the floating sidebar but that's for another issue.
