### ISSUE TITLE
UI Bug still remaining after update 

### ISSUE THREAD

**Issue by DeepestFour** [zen-browser/desktop#3804]
### Captchas

- [X] I have read the instructions.
- [ ] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

Still dealing with an issue present in previous versions. The top of the browser is a different color than the rest of the browser. Small issue but was not the only one with this bug, since before the latest update. 

Seems to disappear when clicking off window,

![image](https://github.com/user-attachments/assets/406123b6-18a6-405b-a508-7020c93ad268)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.2

### What platform are you seeing the problem on?

Windows

**Comment by PHATWalrus** [comment]
![image](https://github.com/user-attachments/assets/5fdf9af9-0d6b-4ea3-957d-1d091322ed44)

**Comment by djorium** [comment]
Set windows.widget.mica to false in about:config

**Comment by DeepestFour** [comment]
and where do you do that?

**Comment by djorium** [comment]
in about:config just put "about:config" in the url bar and click enter

**Comment by DeepestFour** [comment]
thanks for the help, but unfortunately i still have the same issue :(

**Comment by djorium** [comment]
try going to windows settings> personalization> and disabling accent color on title bars or add a hex code to ur theme

**Comment by DeepestFour** [comment]
thanks a lot! it was the accent color on title bars setting! sorry, such a simple fix.
