### ISSUE TITLE
Bug in floating bar

### ISSUE THREAD

**Issue by Appaxaap** [zen-browser/desktop#3808]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

After the latest update there's a bug in floating search bar. I turned on Enable Zen Browser's compact mode and hide both. 

![image](https://github.com/user-attachments/assets/aa3e335c-1fbb-4ab6-9f5c-9aa2bec683bb)

This is what look like.

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.2

### What platform are you seeing the problem on?

Windows

**Comment by djorium** [comment]
what's the bug

**Comment by neurokitti** [comment]
Are you using any mods?

**Comment by Appaxaap** [comment]
> Are you using any mods? 

Yes, floating URL bar.

**Comment by Appaxaap** [comment]
> what's the bug

You can see a black color overlay that shows in floating URL bar.

**Comment by neurokitti** [comment]
> > Are you using any mods?
> 
> Yes, floating URL bar.

floating URL bar is now intigrated so disable the mod. let me know if that fixes it

**Comment by neurokitti** [comment]
also mods are made by the community and should not be reported on the main browsers issues page

**Comment by Appaxaap** [comment]
> > > Are you using any mods?
> > 
> > 
> > Yes, floating URL bar.
> 
> floating URL bar is now intigrated so disable the mod. let me know if that fixes it

Yep now it's fixed. And I'm sorry for reporting community mod in main browser issue page,
