### ISSUE TITLE
make `zen-components` open source

### ISSUE THREAD

**Issue by xjose97x** [zen-browser/desktop#381]
### What happened?

Any reason why `zen-components` is a private repository?

![image](https://github.com/user-attachments/assets/b30edd9c-4986-41c7-a902-4a581f105f3c)

https://github.com/zen-browser/desktop/tree/main/src/browser/base/content

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0

### Severity impact

Enhancement

### What platform are you seeing the problem on?

Linux, macOS - aarch64, macOS - Intel, Windows

**Comment by mauro-balades** [comment]
What licese should I use in order to avoid others copying? because it's an issue I had multiple times now

**Comment by mauro-balades** [comment]
Done, check it out in the org's repos!

**Comment by xjose97x** [comment]
> Done, check it out in the org's repos!

thanks @mauro-balades !

**Comment by win8linux** [comment]
Update: The license of the components repo is now CC-BY-SA.
https://github.com/zen-browser/components

**Comment by FedericoSchonborn** [comment]
> Update: The license of the components repo is now CC-BY-SA. [zen-browser/components](https://github.com/zen-browser/components)

Which one? https://wiki.creativecommons.org/wiki/License_Versions#License_Versioning_History

Is there a reason why the license text itself isn't included in the repository? Creative Commons makes it available at https://creativecommons.org/licenses/by-sa/4.0/legalcode.txt

**Comment by zekker6** [comment]
@xjose97x This link is just pointing to another repository and a commit there, it's not private. You can just click it to open the repository it is pointing to - https://github.com/zen-browser/components/tree/b5f536691a790822c43dbfab949a34b5e2218797

**Comment by win8linux** [comment]
> > Update: The license of the components repo is now CC-BY-SA. [zen-browser/components](https://github.com/zen-browser/components)
> 
> Which one? https://wiki.creativecommons.org/wiki/License_Versions#License_Versioning_History
> 
> Is there a reason why the license text itself isn't included in the repository? Creative Commons makes it available at https://creativecommons.org/licenses/by-sa/4.0/legalcode.txt

There's a PR in waiting for this:
https://github.com/zen-browser/components/pull/1

**Comment by Sharparam** [comment]
Also, why a creative commons license for software? [Creative Commons themselves recommend *against* using their licenses for software](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software).
