### ISSUE TITLE
3 reuqests 

### ISSUE THREAD

**Issue by spectrum705** [zen-browser/desktop#3812]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

1. please make it  so that increasing workspaces doesnt increase the width of the vertical bar. its a much needed request i guess 🥺

2. also when we open a new tab , it should be added at the top and everything else pushed down. rn it gets at the bottom most. 

3. position of sidepanel gets reset on every startup

thank you :)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.2 (Firefox 133.0.3) (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by mr-cheffy** [comment]
Hi! Unfortunately, this place isnt for feature requests. Please move this into a dicussion if you'd like to
