### ISSUE TITLE
Underutilized Discrete Graphics

### ISSUE THREAD

**Issue by MemQu** [zen-browser/desktop#3817]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I had filed an earlier issue:

#2296 

I got the performance back by uninstalling and reinstalling manually in that case. This error did not repeat on subsequent updates.

I have a NVIDIA card.

On update from alpha to beta, I experienced the same error. I did a reinstall and rebooted. I have run motionmark and got an acceptable benchmark of 1050. However, it does not capture the lag I feel with web graphics this update.

It runs like firefox on linux (terrible graphics performance) in the current beta stream.

I have compared with firefox on windows - no such lag there.

Let me know any next steps to help solve this problem.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.2

### What platform are you seeing the problem on?

Windows

**Comment by djorium** [comment]
Sorry i'm not entirely following, so it's laggy on normal firefox as well?

**Comment by MemQu** [comment]
> Sorry i'm not entirely following, so it's laggy on normal firefox as well?

No, normal firefox (on windows) is fine.

Zen (on windows) runs like firefox (on linux) (I've had similar lag issues with graphics there). This level of performance is terrible for a browser on windows.

**Comment by Zadeos** [comment]
I'm not sure if it's the same for you, but my performance tends to be horrible if I have hardware acceleration on for some reason when that's a non-issue for firefox. Turning it off makes performance tolerable.

**Comment by MemQu** [comment]
Problem fixed on 1.0.2-b.3 update. I hope this was intentional, because it is a bit taxing to have discrete graphics be improperly used every few updates.
