### ISSUE TITLE
Customize toolbar breaks layout when multiple windows are open

### ISSUE THREAD

**Issue by Numline1** [zen-browser/desktop#3819]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

If you have two windows open (eg. multiple workspaces), opening a "Customize toolbar" breaks the button layout on the second window. Restart of the browser fixes the problem.

Attached are two screenshots, window 1, where the layout stays ok, and window 2, where it breaks and overflows.

![image](https://github.com/user-attachments/assets/2a03e211-d071-4d6e-beb3-86adeb66c5ee)

![image](https://github.com/user-attachments/assets/8206cee9-c78a-4bc1-8aeb-f45dd2c659c9)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.2

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by mr-cheffy** [comment]
Thanks a lot! Fixed for the next release
