### ISSUE TITLE
Preview tabs on hoven

### ISSUE THREAD

**Issue by WeetHet** [zen-browser/desktop#382]
### What feature would you like to see?

I would love to be able to see the tab previews in a small popup when hovering over them. If that's not possible, at least a name would already be pretty much enough. This would simplify the navigation when using not expanded tabs and make navigating a bunch of tabs much easier

**Comment by mauro-balades** [comment]
This already exists by default 👍

**Comment by WeetHet** [comment]
Hmm, it didn't work for me, but restarting the browser helped
