### ISSUE TITLE
Bookmarks toolbar disables when customizing toolbar in any way

### ISSUE THREAD

**Issue by Slusho64** [zen-browser/desktop#3824]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Pinning/unpinning an extension or customizing the toolbar causes the bookmarks toolbar to disable itself. The bookmarks toolbar seems to disable itself constantly due to many other actions as well.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.2

### What platform are you seeing the problem on?

Windows

**Comment by mr-cheffy** [comment]
This will be fixed in the next release, thanks!
