### ISSUE TITLE
Top Bar UI Design Theme Mismatch

### ISSUE THREAD

**Issue by knightbaryon** [zen-browser/desktop#3826]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

As I show in the attachment below, Theme coloring creates a dashed image in the address bar. It was something that had never happened before. It started with the last two or three updates.

A thin black line covers part of the bar as we look at the address bar line (GitHub URL).

![image](https://github.com/user-attachments/assets/c297da20-3926-4b95-b147-4e0e2a784125)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.2

### What platform are you seeing the problem on?

Windows

**Comment by PribylIon** [comment]
This bug first appeared on 1.0.2-b.0 on my Windows laptop (Ryzen Framework if that helps)

**Comment by xDvusi** [comment]
Same issue here, although I use compact mode. The toolbar looks correct when using compact mode, but it seems this line is at the top of the background of Zen. I found you can cover it by using "Change Theme Colors" and choosing a color with no transparency / contrast.

Here's two screenshots that show the bar without compact mode and with compact mode when top bar not in use.

![Screenshot 2024-12-17 024226](https://github.com/user-attachments/assets/0dc6b7ee-9a41-4fd2-97ee-74d4a139cd11)
![Screenshot 2024-12-17 024249](https://github.com/user-attachments/assets/d0431a84-c3fe-441e-813b-fec9b4b013c1)

**Comment by JSGRD22** [comment]
This is likely the windows title bar showing. Try disabling “show accent color on title bar and window borders” in windows settings, or disable mica in about:config.

**Comment by mr-cheffy** [comment]
>  I have searched existing issues and avoided creating duplicates.

Come on, this is literally reported every 2 issues....

Please follow https://github.com/zen-browser/desktop/issues/3469#issuecomment-2538784130
