### ISSUE TITLE
Side bar color changes to an ugly green upon restart

### ISSUE THREAD

**Issue by ZetaIsLost** [zen-browser/desktop#3829]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

My side bar color is an ugly green, and themes dont help
I set the theme to dark and it fixes it until i restart
When I tab out of the browser it seems to be fixed, but when I tab in to it, it changes back to the ugly green

What it should be
![image](https://github.com/user-attachments/assets/71e68d04-d31c-4ae3-8ccc-5a5b564bb148)
What it is after restart/tab in
![image](https://github.com/user-attachments/assets/fcd29090-7eec-4e75-a35d-09400322ed20)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.2 (Firefox 133.0.3)

### What platform are you seeing the problem on?

Windows

**Comment by mr-cheffy** [comment]
I believe you've enabled mica, please disable it and tell me if it worked 👍🏽

**Comment by ZetaIsLost** [comment]
Yea that was it, thank you for your help
