### ISSUE TITLE
[Bug] Text on Websites blurry

### ISSUE THREAD

**Issue by AnTheMaker** [zen-browser/desktop#383]
### What happened?

Hey there! First of all - great job with Zen! It looks and feels amazing, like a younger sibling of Firefox!
I'm using it on Linux (Zorin OS 17), and it seems like the text on pretty much all websites is a bit blurry when browsing. Sometimes it gets more sharp when scrolling, but it's overall super weird.
Would be awesome if you could look into this!
Keep up the great work!
~ An

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.26

### Severity impact

High

### What platform are you seeing the problem on?

Linux

**Comment by camflan** [comment]
I have the same issue on macOS and none of the config changes have improved the situation. This (Zen) is only browser I have installed that has this behavior, including Firefox

**Comment by NOCanoa** [comment]
@camflan can u create a new user profile and check if it also looks like that

**Comment by n7itro** [comment]
Zen uses different font rendering preferences by default.
Can you try setting `gfx.font_rendering.cleartype_params.rendering_mode` to -1 or 2

**Comment by camflan** [comment]
This is what it looks like on a brand new user profile.

<img width="3120" alt="Screenshot 2024-08-21 at 3 33 17 PM" src="https://github.com/user-attachments/assets/acfa8d7d-ad18-4aff-9f02-0b5533c96c84">
<img width="1257" alt="Screenshot 2024-08-21 at 3 33 11 PM" src="https://github.com/user-attachments/assets/efcefeca-36eb-401f-be44-047b2aa3cb48">
<img width="957" alt="Screenshot 2024-08-21 at 3 33 01 PM" src="https://github.com/user-attachments/assets/7464b4d1-000d-4a79-8b98-ee148531882f">
<img width="1071" alt="Screenshot 2024-08-21 at 3 32 58 PM" src="https://github.com/user-attachments/assets/57f3a55f-98a1-4499-8e98-2e9da2982fc6">


It's weird. You can see in the last 2 where I've moved my mouse over some areas of the screen and they've sharpened up. Specifically if you look around the Tabs > "Ctrl+Tab" text

**Comment by camflan** [comment]
I've set these settings and I think it's improved. I'm still seeing random text that's fuzzy, but now most sites are rendered as expected,

<img width="1523" alt="Screenshot 2024-08-21 at 3 36 41 PM" src="https://github.com/user-attachments/assets/185149f3-b371-4edd-aa26-c24c1b22975d">
<img width="1523" alt="Screenshot 2024-08-21 at 3 36 33 PM" src="https://github.com/user-attachments/assets/b33a9ab4-2b53-4913-87d0-88852cd84418">

**Comment by mauro-balades** [comment]
did you restart?

**Comment by camflan** [comment]
> did you restart?

After setting the flags? Yes, several times

**Comment by octoxan** [comment]
The 

> > Sorry, selected the wrong severity label but can't seem to change it 😬
> > Also, it seems like setting `layout.paint_rects_separately` to **true** in `about:config` seems to make this issue occur less often... super strange - I don't have this issue on the same machine with stock Firefox.
> 
> Try to disable above config and set:
> 
> * gfx.font_rendering.cleartype_params.rendering_mode to 0
> * gfx.font_rendering.cleartype_params.gamma to -1
> 
> And let me know if this fix your issue.

These settings fixed it for me on macOS I think.

This is what I was seeing in Zen vs Firefox btw, both on DuckDuckGo.

Firefox:
![firefox-not-blurry](https://github.com/user-attachments/assets/22b36e6f-9751-45d6-92b2-4c82fa66a19d)

Zen:
![zen-blurry](https://github.com/user-attachments/assets/86f70a2a-1509-45ed-8a3d-bc8b606c9312)

**Comment by gunir** [comment]
Will be fixed next update.

**Comment by tilupe** [comment]
I still have this problem, even though I set the specified settings and restarted zen
![image](https://github.com/user-attachments/assets/b496b045-25cc-43b1-8a80-346930c523bf)

**Comment by Hyderman** [comment]
Downloaded zen today so I can't tell for before but the font is blurry at a certain windows size threshold, under it's not blurry.

I'm on linux/wayland

**Comment by mstcl** [comment]
Really enjoying Zen so far, sadly the font rendering is still not fixed (version 1.0.0.a.29-1, after the patch).

![2024-08-26_21-54](https://github.com/user-attachments/assets/439b05bb-9c9a-4638-b691-1f6cd0014102)

Left is Zen. Right is Firefox.

I've done the following and restarted but it still persists:

- `gfx.font_rendering.cleartype_params.rendering_mode` to 0
- `gfx.font_rendering.cleartype_params.gamma` to -1
- `layout.paint_rects_separately` to true

**Comment by rdvansloten** [comment]
Also occurring on the latest Windows build `1.0.0-a.34`. Making changes to the about:config settings listed above makes no discernible difference.

**Comment by EigoOda** [comment]
I'm using `1.0.0-a.35 (64-bit)`, but it didn't look fix yet.

**Comment by m-j-r** [comment]
Hi everyone who is having this problem - I upgraded to 1.0.0-a.39 (64-bit), but was still experiencing this issue, and could not find a fix.

I saw this though, from @NOCanoa:
> @camflan can u create a new user profile and check if it also looks like that

And creating a new profile finally resolved the problem - old profile still has the issue.

**Comment by m-j-r** [comment]
Ok, I was wrong 🙈 New profile is also not fixed.

Easiest place to see it is in the about:profiles screen

**Comment by Evthestrike** [comment]
I'm also getting this issue on a 4k monitor. Very annoying

**Comment by azinsharaf** [comment]
i am also getting it on a oled monitor. 
_1.0.1-a.19 (Firefox 132.0.1) (64-bit)_

blurry screen:
![image](https://github.com/user-attachments/assets/d3c8a165-744c-46f8-9846-50069bc69f45)

**Comment by rdvansloten** [comment]
It was fixed for a few updates but it's back since about 1-2 weeks. What happened

**Comment by FujiwaraChoki** [comment]
Getting same issue.

**Comment by FujiwaraChoki** [comment]
Any updates here? This issue is incredibly annoying...

**Comment by Sypheos** [comment]
This https://github.com/zen-browser/desktop/issues/2671#issuecomment-2529781863 fixed it for me

**Comment by shiedltv61** [comment]
I am having the same issue on the latest version on fedora 42. Windows is 100%, did we have any solution?

Sorry I haven`t checked the the https://github.com/zen-browser/desktop/issues/2671#issuecomment-2529781863 solution
