### ISSUE TITLE
Cannot unload multiple tabs manually

### ISSUE THREAD

**Issue by V0LDY** [zen-browser/desktop#3831]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

If I select manually multiple tabs and click on "Unload Tab" to unload them immediately the command doesn't work.

I suspect this happens because the browser automatically switches to one of the selected tabs when you try to select a group, and it's impossible to unload the tab that's being displayed so for some reason having your active tab among the selected group also prevents the other from unloading.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Latest

### What platform are you seeing the problem on?

Windows

**Comment by mr-cheffy** [comment]
You can't unload the tab you are currently on

**Comment by V0LDY** [comment]
> You can't unload the tab you are currently on

Yea I suspected that, the problem is that if I'm selecting multiple tabs I can't unload them at the same time, and I suspect that happens because the active tab is selected together with the others

**Comment by JSGRD22** [comment]
This used to work properly before beta, probably got changed

**Comment by V0LDY** [comment]
> This used to work properly before beta, probably got changed

I might be wrong, but maybe that's because it was possible to select multiple tabs excluding the active one?

**Comment by gomster** [comment]
yep same here after the last twilight update - (win 11 24h2) - it was functional just before -

**Comment by mr-cheffy** [comment]
Ok! Fixed for the next release, thanks!

**Comment by gomster** [comment]
> Ok! Fixed for the next release, thanks!

i comfirm that today it's ok for me - but , but ..maybe only on my install i can't unload more than 3 or 4 pinned/essentials in one shot ..I'll look at it a little better later. - thx for all
