### ISSUE TITLE
Links Open In Tab Group

### ISSUE THREAD

**Issue by thesoloist-1** [zen-browser/desktop#3832]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Tab groups are still in beta so I know this isn't urgent but just wanted to bring this to attention for future bug fixes. When clicking on a link within a website, the link opens inside the fist tab group (provided you have tab groups). It should be opening as a new tab below the groups. 

https://github.com/user-attachments/assets/cb682981-1617-4e07-97ea-81c131e2a2f6

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.2 

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by djorium** [comment]
Tab groups are pre-pre-pre-alpha don't make issues about them as it is being worked on by Firefox.

**Comment by thesoloist-1** [comment]
@djorium  > Tab groups are pre-pre-pre-alpha don't make issues about them as it is being worked on by Firefox.

Just realized this is not a tab group issue. This was only occurring with pinned tabs. If i clicked a link from a pinned tab, it opened the tab right after the pinned tabs which was placing it in the group below. Setting the config preference `browser.tabs.insertAfterCurrent` to false fixed that. Now links open after the very last tab as I wanted. All is good now.

**Comment by vsahishnu** [comment]
Hi @thesoloist-1 

If possible, can you let me know how you got Tab Groups in Zen? 
I went through the docs and roadmap but couldn't find how... 

PS: 
I am in 1.0.2-b.5. 
Also sorry if replying to closed issues is wrong...

**Comment by thesoloist-1** [comment]
> Hi @thesoloist-1
> 
> If possible, can you let me know how you got Tab Groups in Zen? I went through the docs and roadmap but couldn't find how...
> 
> PS: I am in 1.0.2-b.5. Also sorry if replying to closed issues is wrong...

I believe I had to activate it in about:config `browser.tabs.groups.enabled`

**Comment by vsahishnu** [comment]
Lovely, thanks. 
I thought it would've been in about:config too...

But I am still curious on how you got it to work similar to Arc? Like expanding/minimizing of the group and etc...
