### ISSUE TITLE
buggy text rendering in desmos graphing calculator

### ISSUE THREAD

**Issue by NevisaurusRex** [zen-browser/desktop#3833]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

On the desmos graphing calculator, https://www.desmos.com/calculator, the text for the axes does not render correctly. This does not occur on firefox, or on previous versions of zen.
![image](https://github.com/user-attachments/assets/c0eec628-e4f6-4ba6-9d33-30358fd06e6d)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b2

### What platform are you seeing the problem on?

Windows

**Comment by mr-cheffy** [comment]
![image](https://github.com/user-attachments/assets/c73d83f8-4671-4d78-a010-ba6ff252f577)

Weird, it does work for me

**Comment by NevisaurusRex** [comment]
It consistently does not work for me. I have tried restarting zen and restarting my laptop, but it persists.

**Comment by mr-cheffy** [comment]
Could you try in a new profile?

**Comment by NevisaurusRex** [comment]
The issue still persists in a new profile
![image](https://github.com/user-attachments/assets/0a6d8ad9-fdb2-41e6-a2aa-1c2590d24a6d)

**Comment by mr-cheffy** [comment]
What about disabling `gfx.canvas.accelerated` and `layers.gpu-process.enabled` in about:config?

**Comment by NevisaurusRex** [comment]
disabling ```gfx.canvas.accelerated``` works, thanks!
