### ISSUE TITLE
Why Zen creating this folder itself on starting?

### ISSUE THREAD

**Issue by grvptnk** [zen-browser/desktop#3835]
### Captchas

- [ ] I have read the instructions.
- [ ] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

![Screenshot From 2024-12-16 19-49-33](https://github.com/user-attachments/assets/46e4c306-7d32-4143-b0c8-526c8743a714)

This folder is autometically creating itself whenever i open zen browser. If i delete this and close zen browser. After opening Zen browser again it autometically creates itself. Please fix this issue it very annoying.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.2

### What platform are you seeing the problem on?

Linux

**Comment by heis2201** [comment]
See issue https://github.com/zen-browser/desktop/issues/3813

**Comment by djorium** [comment]
Duplicate of https://github.com/zen-browser/desktop/issues/3813
