### ISSUE TITLE
Apple Silicon DMG is damaged

### ISSUE THREAD

**Issue by figuernd** [zen-browser/desktop#384]
### What happened?

Attempting to open the Apple Silicon dmg results in an error from OSX saying the file is damaged and should be trashed.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Unknown - downloaded from Zen-browser.app which does not show version

### Severity impact

Critical

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by mauro-balades** [comment]
https://github.com/zen-browser/desktop/issues/53

Thanks!
