### ISSUE TITLE
URL Bar Overflow

### ISSUE THREAD

**Issue by oluwadaprof** [zen-browser/desktop#3842]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The URL bar exceeds the accented top actions bar including the tools looking out of proportion
![image](https://github.com/user-attachments/assets/f984f46e-8ce6-4465-a0fd-f21bc8cd2251)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.2

### What platform are you seeing the problem on?

Windows

**Comment by JSGRD22** [comment]
The top portion isn’t accented, that is the windows title bar showing, which is a known bug. Try disabling “show accent color on title bar and window borders” in windows settings, or disable mica in about:config.

**Comment by ThunderE75** [comment]
I am encountering the same issue, i had already disabled 'show accent color on title bar and window borders'

![image](https://github.com/user-attachments/assets/db75dd95-eb4e-494c-8e6f-8ba0f8baf01a)

i also have all the Zen Mods disabled & the issue persists 

![image](https://github.com/user-attachments/assets/0f55a6d3-f952-47db-b30d-c7cdb59aeb3c)

**Comment by syscat29** [comment]
What browser are you using? Beta or Twilight? Also what version

**Comment by ThunderE75** [comment]
i am using Zen beta 

![image](https://github.com/user-attachments/assets/43f2cd34-3a9d-4acf-92e3-97f590cbde68)

**Comment by mr-cheffy** [comment]
Please follow https://github.com/zen-browser/desktop/issues/3469#issuecomment-2538784130

>  I have searched existing issues and avoided creating duplicates.
