### ISSUE TITLE
Udemy stopped working

### ISSUE THREAD

**Issue by julianoventola** [zen-browser/desktop#3843]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I was about to start a course on udemy, the first video i can watch normally, but the second one does not load, i tried using Brave and it loaded normally, i didn't find a reason for that
![image](https://github.com/user-attachments/assets/e8569833-e370-4a38-acce-a3f12f9b04b6)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.1

### What platform are you seeing the problem on?

Windows

**Comment by julianoventola** [comment]
I tried again, and some videos can be loades, others don't, i'm putting the console log here, i'm not sure this will help
![image](https://github.com/user-attachments/assets/59ad2e62-17dd-476b-a1d5-af5f481a5a0e)

**Comment by djorium** [comment]
i'm on my phone so i cant test rn but could you check if it happens on normal firefox?

**Comment by djorium** [comment]
also try to see if it works with ur extensions disabled

**Comment by JSGRD22** [comment]
I heard udemy is protected by DRM which zen does not support, perhaps it applies to some videos?

**Comment by julianoventola** [comment]
> i'm on my phone so i cant test rn but could you check if it happens on normal firefox?

Using zen, it does not work and it's not blocking me from taking printscreens, and usually when it's working correctly i can not take screenshots 
Zen:
![image](https://github.com/user-attachments/assets/a5af8811-f9ab-433e-be20-fb3064edb372)

Firefox:
![image](https://github.com/user-attachments/assets/c48b01a0-04a1-4110-9d9f-5a9908e70dfe)

> also try to see if it works with ur extensions disabled
I disabled them and it did not work as well

> I heard udemy is protected by DRM which zen does not support, perhaps it applies to some videos?
Yes, but it's working for some videos, why are some specifics that are not?

**Comment by julianoventola** [comment]
i should not be able to take screenshots from udemy (at least i'm not able to do it and still see the video on Chrome/Firefox/Brave), but using zen, the first class loads normally and i'm be able to take ss from the class
Zen:
![image](https://github.com/user-attachments/assets/cd389a9d-7b3d-4d57-9aab-63ea1f47e94b)

**Comment by julianoventola** [comment]
All ss i sent today where using the last update
![image](https://github.com/user-attachments/assets/99cfc08d-5bd0-4792-b4b6-ac9e7a26573e)

**Comment by JSGRD22** [comment]
> it's not blocking me from taking printscreens

Sounds like an issue with DRM, which is not supported on Zen for windows and macOS. It may only apply on certain videos because of whatever the website did to implement DRM.

**Comment by JSGRD22** [comment]
> it's not blocking me from taking printscreens

Sounds like an issue with DRM, which is not supported on Zen for windows and macOS. It may only apply on certain videos because of whatever the website did to implement DRM.

**Comment by syscat29** [comment]
As of now Zen doesn't support DRM media playback, this will come later as it is a complicated process, for now your best option is using another browser for DRM media.

You can find more information in the docs - [Why can’t Zen Browser play DRM-protected content?](https://docs.zen-browser.app/faq#why-cant-zen-browser-play-drm-protected-content)
