### ISSUE TITLE
Android Developers page not working correctly

### ISSUE THREAD

**Issue by Sajito** [zen-browser/desktop#3845]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

It's nearly impossible to navigate the [Android Developers page](https://developer.android.com) using Zen browser.

Steps to reproduce:
- Open Android Developers Page (https://developer.android.com)
- Try to click "Develop" in the header navigation
  - URL changes, but no navigation happens

At the time of writing, there is a hero section about Android XR.
- Try to click on "Explore Android XR"
  - URL changes, but no navigation happens

Open any other documentation page, eg. https://developer.android.com/reference/kotlin/androidx/compose/runtime/package-summary
- Try to use the navigation on the left side
  - Nav items won't expand
  - Links don't work
- Try to click the Logo at the top of the page
  - Should navigate to the home page. URL changes, but no navigation happens

All of this is working perfectly fine in Firefox

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.2

### What platform are you seeing the problem on?

Linux

**Comment by PeterGion** [comment]
I'm having this issue on Windows too

**Comment by l6037600** [comment]
同样的问题

**Comment by namnq-sipher** [comment]
I have the bug too. When I open the [NDK Download website](https://developer.android.com/ndk/downloads), clicking to any download link doesn't open the TOS agreement popup to download the NDK.

![image](https://github.com/user-attachments/assets/c87e5d1a-64ef-4fb2-8a48-683f4f2f0607)

**Comment by l6037600** [comment]
1.0.2-b.4可以正常访问了👍

**Comment by namquang93** [comment]
Just an update, after upgrading to the latest version 1.0.2-t.5 (Firefox 133.0.3) (2024-12-23) (64-bit), the NDK download webpage is now working fine.

**Comment by Sajito** [comment]
Can confirm working with 1.0.2-b.5, didn't test in 1.0.2-b.4
