### ISSUE TITLE
"Welcome to Zen browser" opening at each launch

### ISSUE THREAD

**Issue by ethylon** [zen-browser/desktop#3847]
### Captchas

- [ ] I have read the instructions.
- [ ] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

Each time I start the browser, I have to go through the initial setup. Started happening after the automatic update this morning

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.2

### What platform are you seeing the problem on?

Windows

**Comment by syscat29** [comment]
Please try the following: ` about:config ` then search for ` zen.welcome-screen.seen ` and ` zen.welcomeScreen.seen ` and set both to ` true `

Restart your browser and report back

**Comment by ethylon** [comment]
I am unable to reproduce it this morning.\
I tried forcing `zen.welcome-screen.seen` to `false` to reproduce but it successfully switches back to `true` after.

`zen.welcomeScreen.seen` doesn't exist.

I think this is fixed. 👍
