### ISSUE TITLE
Tab bar gets stuck upon clicking 'Account' button

### ISSUE THREAD

**Issue by HatandClogs-main** [zen-browser/desktop#3856]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I have zen's compact mode enabled and I was exploring the browser a bit more that's when I clicked on the 'Account' button on bottom left of the tab bar and the tab bar got stuck like it won't go into hiding as it should in compact mode  if I am not moving my cursor there. The issue gets fixed when I restart the browser. Hope I am making myself clear and I just wanna say that I really enjoy using this browser.

https://github.com/user-attachments/assets/87304c4e-d400-41f0-8713-03627557517c

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-t.3

### What platform are you seeing the problem on?

Windows

**Comment by syscat29** [comment]
Confirmed by multiple users, let's keep track of it in #3864
