### ISSUE TITLE
Add option to hide top toolbar without hiding tabs

### ISSUE THREAD

**Issue by Salkcid** [zen-browser/desktop#386]
### What feature would you like to see?

It would be great if Zen had an option to hide top toolbar without hiding tabs

![image](https://github.com/user-attachments/assets/ff4c94a8-2706-4d65-a430-96cd856b460f)

### What platform are you seeing the problem on?

Windows

### Additional context

Vertical space is at a premium on a 15.6-inch 16:9 laptop screen, so having the option to increase it would be a valuable enhancement

**Comment by AnTheMaker** [comment]
Duplicate of #229
