### ISSUE TITLE
Display problem when sidebar is closed

### ISSUE THREAD

**Issue by julienallexandre** [zen-browser/desktop#3860]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Display problem when the sidebar is closed on the new tab page, the right border is missing and the display is broken.

https://github.com/user-attachments/assets/08ab4cff-99b8-4e30-957c-2863461894a9

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.2 (Firefox 133.0.3) (64 bits)

### What platform are you seeing the problem on?

macOS - Intel

**Comment by mr-cheffy** [comment]
Do you have any custom css or mods?

**Comment by julienallexandre** [comment]
> Do you have any custom css or mods?

Audio TabIcon Plus (v1.0.1)

even deactivated it's the same

**Comment by mr-cheffy** [comment]
And custom css?

**Comment by julienallexandre** [comment]
> And custom css?

No more

**Comment by julienallexandre** [comment]
Resolved c5adf540a68772d0d85dd20a5b39ed7c7686964c
