### ISSUE TITLE
Pinned and Essential tabs seem to not work properly

### ISSUE THREAD

**Issue by zplawecki** [zen-browser/desktop#3863]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I add a tab, pin it or mark it as essential, then I close browser and open it again. All the pinned / essential tabs are gone and I have to pin them again.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.2

### What platform are you seeing the problem on?

Windows

**Comment by mr-cheffy** [comment]
This has been reported before, it's fixed in the next update
