### ISSUE TITLE
History button cannot be clicked

### ISSUE THREAD

**Issue by zplawecki** [zen-browser/desktop#3864]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I've put history button on toolbar, toegether with tabs, new window, incognito mode and web panel buttons. Since last update, when I click on history, it doesn't open the list and the button itself gets "stuck" - cannot be clicked anymore untill I restart browser. It also changes color to lighter - it looks like it's clicked and pressed.
![Zrzut ekranu 2024-12-17 232452](https://github.com/user-attachments/assets/02e1d58b-415d-4ede-8583-b5ed1ef22f88)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.2

### What platform are you seeing the problem on?

Windows

**Comment by syscat29** [comment]
They seem to work just fine for me

https://github.com/user-attachments/assets/eb6ed28d-c23f-4036-95d1-4cfbce25049c

**Comment by blindmodz** [comment]
![zen_zPqOpH7DVc](https://github.com/user-attachments/assets/55ab475a-fee5-4bb5-8e7f-c383d504b2b4)
Mine is here and everytime that I click to open the history the browser freezes and have to restart it (opening history through the tree dot works fine)

**Comment by syscat29** [comment]
I know this may be annoying but can you try creating a new profile, configuring it similar to this one and checking if the button freezes?

**Comment by blindmodz** [comment]
Just tried and also happened (enabled compact mode and pinned the history, gets stuck and the only way to fix it is restarting browser or unpinning the History)

**Comment by syscat29** [comment]
Alr, just confirmed they get stuck in compact mode.

**Comment by neurokitti** [comment]
https://github.com/user-attachments/assets/e132ecb7-8150-4b8d-80d5-b43f8cfeb82c

im not experiencing the issue. is this still a problem for y'all on the latest update?

**Comment by syscat29** [comment]
Update: Still present in 1.0.2-b.5 when compact mode is set to hide the toolbar

**Comment by mr-cheffy** [comment]
Could anyone give it a try on twilight? I tried to send a patch that fixes this. Thanks
