### ISSUE TITLE
Spotify fails to play most tracks

### ISSUE THREAD

**Issue by djmtype** [zen-browser/desktop#387]
### What happened?

Trying to play particular tracks on https://open.spotify.com fails. Typically, the first 30 seconds plays, but then fails thereafter.

I do not have any ad-blocking extensions enabled, or modified security settings.

I suspect Zen browser may be facing the same DRM license issues like Thorium does? [https://github.com/Alex313031/thorium/issues/623](https://github.com/Alex313031/thorium/issues/623)

When I used Thorium, I tried all the suggested hacks but none worked with Spotify. 

BTW, there are no play issues with Firefox 129.0.2.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.26

### Severity impact

Low

### What platform are you seeing the problem on?

macOS - aarch64

### Relevant log output

```shell
There are too many script errors to list here; even using Spotify within Firefox. 



Content-Security-Policy warnings 2
Content-Security-Policy warnings 4
Partitioned cookie or storage access was provided to “https://www.google.com/recaptcha/enterprise/anchor?ar=1&k=6LfCVLAUAAAAALFwwRnnCJ12DalriUGbj8FW_J39&co=aHR0cHM6Ly9vcGVuLnNwb3RpZnkuY29tOjQ0Mw..&hl=en&v=hfUfsXWZFeg83qqxrK27GB8P&size=invisible&cb=1wvx5o3tjat2” because it is loaded in the third-party context and dynamic state partitioning is enabled.

Ignoring unsupported entryTypes: longtask. recaptcha__en.js:239:194
An AudioContext was prevented from starting automatically. It must be created or resumed after a user gesture on the page. 4 web-player.a2bda6db.js:1:758647
Cookie warnings 44
Failed to load ‘https://i.scdn.co/image/ab67616d0000e1a3dcdc199055b27ab30244893c’. A ServiceWorker intercepted the request and encountered an unexpected error. service-worker.js:1:30026
An AudioContext was prevented from starting automatically. It must be created or resumed after a user gesture on the page. web-player.a2bda6db.js:1:758647
```

**Comment by NOCanoa** [comment]
yeah, DRM killing the fun : /

**Comment by Logickin-Lambda** [comment]
I can still confirm this on the latest version of zen 1.9.1b on windows 11, and it can't play anything (or only the first 8 seconds of the tracks) other than their advertisements, while firefox plays them flawlessly. Have they really fixed, or it isn't fixed because of the DRM issue?

Please don't mark it completed if it can't be fixed due to the DRM issue since people would think this issue has been addressed.

**Comment by M0ze** [comment]
still doesn't work. Got zen today, love it, it's so cool. let's fix this...

**Comment by TunixR** [comment]
Same here. For me it does not work on my windows machine, but it does on my linux (Fedora 41) machine

**Comment by madebydor** [comment]
Same here, Spotify just skips songs and won't play. Same for YouTube.

**Comment by Kenja-Samyueru** [comment]
Ye im having the same issue here with the DRM not letting me get my full Spotify experience even with premium account.

**Comment by 23426356587** [comment]
Same issue

**Comment by mr-cheffy** [comment]
No need to keep saying "same issue", we know, https://docs.zen-browser.app/faq#why-cant-zen-browser-play-drm-protected-content
