### ISSUE TITLE
YouTube mini player bug.

### ISSUE THREAD

**Issue by donestrera** [zen-browser/desktop#3872]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I was playing a video on YouTube and when I clicked "i" on keyboard to enter the mini player the video had bugged and there was no buttons I can click on the video. Even after clicking another video it still did persist. It has been fixed only after refreshing the website.
<img width="1440" alt="Screenshot 2024-12-18 at 09 35 15" src="https://github.com/user-attachments/assets/b8f2d9c6-919a-45e1-bfc8-92d811df3c3e" />

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.2

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by djorium** [comment]
Try this please, if it doesn't work please try a new profile and let me know if the issue persists.
![image](https://github.com/user-attachments/assets/5b852866-b454-4c9c-a193-5576bf58da2a)

**Comment by LimaneGaya** [comment]
Just had this issue with Brave.
Might be just a Youtube issue?

![image](https://github.com/user-attachments/assets/56728296-edd2-481a-b455-1570711ffff2)

**Comment by neurokitti** [comment]
im pretty certain this isn't an issue with Zen browser itself. i checked and the issue isn't happening for me in YouTube on zen either.
