### ISSUE TITLE
Back and Forward buttons are still flipping

### ISSUE THREAD

**Issue by EmirOven** [zen-browser/desktop#3876]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I just downloaded Zen so I should be on the latest version, I saw an issue on this that was marked as completed (and marked as such on the roadmap as well) but the issue still occurs. As far as I can tell, it only happens when I click the "Expand Sidebar" button, and as such it fixes itself when I turn Expand Sidebar on and then off again.

https://github.com/user-attachments/assets/a92ac7c3-3d96-4dc8-a88a-ba8ad98e9574

I attached a video where the related issue occurs. Also, you weirdly cannot replace the buttons on the toolbar customization menu either, Zen simply doesn't allow you to change the place of those buttons for me. 

- Emir Öven

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.2

### What platform are you seeing the problem on?

Windows

**Comment by mr-cheffy** [comment]
How did you get to this point? Any steps to reproduce?

**Comment by EmirOven** [comment]
As I showed in the video, I just switched the layout using the Expand Sidebar button. It does not happen every time I do it, but it happens every 2-3 times maximum. To reproduce, click Expand Sidebar 2-3 times until you see the forward and back buttons switch around.

**Comment by mtsfer** [comment]
Same is happening here on 1.0.2-b.3. When expanding and colapsing the sidebar, the back and forward buttons flip positions.

**Comment by syscat29** [comment]
Please, create a new profile and check if the problem persists.

**Comment by EmirOven** [comment]
After updating to 1.0.2-b.3, the issue seems to be gone, and I can actually realign the buttons from the Customize Toolbar menu so I cannot reproduce or create a new profile to test right now, but as @mtsfer still has the issue on 1.0.2-b.3, it is best he tries with a new profile to check if the issue still persists after creating a new profile

**Comment by syscat29** [comment]
@mtsfer Can you please give an update on your issue? Does it persist in the current release (1.0.2-b.5) after cresting a new profile?

**Comment by mtsfer** [comment]
@j14i @FreeTurk Sorry for the late reply. After updating to 1.0.2-b.5, the issue is gone. Thanks!
