### ISSUE TITLE
Unable to change user profile when compact mode is on 

### ISSUE THREAD

**Issue by Demon1412** [zen-browser/desktop#3879]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Changing profile doesn't seems to work when compact mode is on , icon becomes unresponsive when clicked and have to close the window and turn off compact mode to change profile .

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.2

### What platform are you seeing the problem on?

Windows

**Comment by Demon1412** [comment]
https://github.com/user-attachments/assets/57b63df4-cc43-4aa5-996b-fe513cdedcdb

**Comment by syscat29** [comment]
Please follow #3864
