### ISSUE TITLE
Keyboard shortcuts for specific web panels

### ISSUE THREAD

**Issue by hommels** [zen-browser/desktop#388]
### What feature would you like to see?

I would love to be able to toggle specific Zen Sidebar web panels with keyboard shortcuts. This is one of the features that really sold me on using Floorp since it is such a big productivity booster. 

For reference: 
![image](https://github.com/user-attachments/assets/1d77b0f1-761a-44f9-93bd-b9d89c86d73d)

### What platform are you seeing the problem on?

Windows

### Additional context

Otherwise I just wanted to say I am really impressed by your work so far! It's great to see a lot of these new browser innovations coming together in such a well-designed and cohesive package. I'm excited to see where future development will take it.

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/851

 ~ This is an automatic operation to better enhancements requests organization.
