### ISSUE TITLE
Tab Unloader addon not working

### ISSUE THREAD

**Issue by MoltenMonster** [zen-browser/desktop#3882]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The addon https://addons.mozilla.org/en-US/firefox/addon/tab-unloader-we/ doesn't show a folder context menu option to load its links to unloaded tabs. It works just fine in Firefox:
![CleanShot 2024-12-18 at 05 48 50@2x](https://github.com/user-attachments/assets/3a0a4f2e-8eca-4bb7-adb3-84913d34e83a)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

BOTH: "1.0.2-t.3 (Firefox 133.0.3) (2024-12-18) (aarch64)" and "1.0.2-b.2 (Firefox 133.0.3) (aarch64)"

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by mr-cheff** [comment]
Hi!

I dont seem to be able to find this context menu item...

![Image](https://github.com/user-attachments/assets/1b8dd7f8-5db7-4bf1-89c0-a5f3e0ffecac)

**Comment by mr-cheffy** [comment]
This issue has been fixed for the next release along with https://github.com/zen-browser/desktop/issues/1366 (https://github.com/zen-browser/desktop/commit/47922537b7c4afa46e423cb84a52ddb17a911a9d). Thanks!
