### ISSUE TITLE
Ctrl + Shift + Alt + I not working

### ISSUE THREAD

**Issue by Dredragon-Austin** [zen-browser/desktop#3883]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

While I try making new theme i try use Ctrl + Shift + Alt + I but it not work

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0

### What platform are you seeing the problem on?

Windows

**Comment by nijin26** [comment]
I think it's not a bug. You have to enable it in `about:config`. Set `devtools.debugger.remote-enabled` as `true`. Then try out that shortcut.

It's mentioned in this doc. https://docs.zen-browser.app/guides/live-editing

**Comment by Dredragon-Austin** [comment]
ty

**Comment by harrobe123** [comment]
> I think it's not a bug. You have to enable it in `about:config`. Set `devtools.debugger.remote-enabled` as `true`. Then try out that shortcut.
> 
> It's mentioned in this doc. https://docs.zen-browser.app/guides/live-editing

i am trying to use this document to move the tab button down. i have the css code off of a reddit post made 5 months ago. i already  had a chrome file and so i just made a userchrome.css file but when i press ctrl+shift+alt+i after enabling this in the config it doesnt work still. i dont know why and really cant handle the new tab button being at the top. or the actual new tab if there is a way to edit that.
the code i have is:
`
#tabbrowser-tabs .tab-drop-indicator {
  order: 1;
}
#tabbrowser-tabs #vertical-pinned-tabs-container {
  order: 2;
}
#tabbrowser-tabs #tabbrowser-arrowscrollbox {
  order: 3;
}
#tabbrowser-tabs #newtab-button-container {
  order: 4;
}
/* Un-highlight the create new tab button */
#vertical-tabs-newtab-button {
      background: unset!important;
    }
`
