### ISSUE TITLE
expanded tab bar trigger has more threshold than compact. I can't get some things as it pops out

### ISSUE THREAD

**Issue by BosadBillaHun** [zen-browser/desktop#389]
### What happened?

The threshold for the tab bar in expanded mode to open is too much, as you can see in the video I cannot use the tools and nav bar (files tab).
In compact mode, it's fine no problem.

https://github.com/user-attachments/assets/0fd1e3e4-470b-45a1-9c86-8da5528c595a

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.24 (64-bit)

### Severity impact

Enhancement

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
This is fixed for the next release (tonight)

**Comment by Eff0rtly** [comment]
useless
