### ISSUE TITLE
Default Firefox Window Control buttons used instead of custom Zen icons

### ISSUE THREAD

**Issue by RetrogradeDev** [zen-browser/desktop#3893]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The default Firefox window control buttons (minimize, maximize, restore, close) are being displayed instead of the intended custom icons made of zen.

The css points to `chrome://browser/skin/window-controls/[action].svg`, which are the default firefox buttons, instead of the ones in `src/browser/themes/shared/zen-icons/`.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.2

### What platform are you seeing the problem on?

Windows

**Comment by syscat29** [comment]
Please provide a screenshot

**Comment by RetrogradeDev** [comment]
How it looks like now:
![image](https://github.com/user-attachments/assets/0f7048bc-c47d-413f-8c1c-3b6e7073c208)
For the ones made by zen, look at [https://github.com/zen-browser/desktop/tree/dev/src/browser/themes/shared/zen-icons](this).

**Comment by mr-cheffy** [comment]
We are not planning on doing this change unfortunately, sorry
