### ISSUE TITLE
Default shortcut for "Copy current URL" overridden by element inspector

### ISSUE THREAD

**Issue by JSGRD22** [zen-browser/desktop#3894]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The "Copy current URL" shortcut is set to "Shift+Ctrl+C" by default. However, firefox also has the same binding which opens devtools, and it overrides the new default shortcut.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.3

### What platform are you seeing the problem on?

Windows

**Comment by syscat29** [comment]
Give your browser a restart, that fixed it for me

**Comment by JSGRD22** [comment]
Yes, it fixed it, thank you
