### ISSUE TITLE
Scroll speed is much faster in zen than in any other app

### ISSUE THREAD

**Issue by UfukUstali** [zen-browser/desktop#3896]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The scroll speed is much faster in zen than in any other app.
I tried with two touch pads, mouse scroll wheel and the arrow keys.
A concrete measurement is when i was using the arrow keys same height would scroll out of view in between, 9-10 clicks in chrome and 6-7 in zen.

Considering i am writing this issue right after this, 1.0.2-b.3, release, that some changes have been made to the scroll behavior `Added a smoother scrolling experience by using msd physics and changing scroll values/offests (Disabled in macos)` and i just wasn't having this issue before relaunching zen, i think this is expected.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.3 (Firefox 133.0.3) (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by Beeditor04** [comment]
about:config -> search `mousewheel.default.delta_multiplier_y`, set the number to 100 (this is the default number)

**Comment by UfukUstali** [comment]
It was at 300 setting it to 100 fixed it, thanks.

**Comment by Lampe2020** [comment]
This should probably be a setting on `about:preferences`, so other people who wonder why Zen behaves so strangely easily can find it by searching for "scroll" in the settings.

**Comment by SephReed** [comment]
agreed.  I went to settings, and searched "scroll."  Then google, then got here.   Went from 200 -> 25, to get it to feel right.
