### ISSUE TITLE
Container and Workspace indicators arent followings prefs

### ISSUE THREAD

**Issue by kar731** [zen-browser/desktop#3898]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

zen.workspaces.show-workspace-indicator doesn't hide the workspace indicator in the latest update.

Also, if you duplicate an essential tab within a container, the duplicated tab will show the container indicator despite the option for hiding it being on.

https://cdn.discordapp.com/attachments/1302759683882225774/1319499473772351559/CleanShot_2024-12-19_at_18.58.06.mp4?ex=67662f25&is=6764dda5&hm=fc328e614f8f867b731d1646cfbd84ebee121367d9b50de43ec760f3b81dcb08&

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.3

### What platform are you seeing the problem on?

Windows

**Comment by sjclayton** [comment]
Same issues here on 1.0.2-b.3 on Linux

**Comment by mr-cheff** [comment]
This preference doesn't hide the indicator. It just hides the indicator created if the workspace has been implicitly inherited from the workspace

**Comment by mr-cheffy** [comment]
It'll be fixed in b.4
