### ISSUE TITLE
Side tab bar stucks (doesn't hides again) when we click on the Zen Account button multiple time

### ISSUE THREAD

**Issue by ayushpatel22** [zen-browser/desktop#3900]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

In Compact mode, clicking the Zen Account button (located at the bottom left of the side tab) multiple times in quick succession causes the side tab to freeze

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.3

### What platform are you seeing the problem on?

Windows

**Comment by syscat29** [comment]
Please use the search bar before opening an issue. Follow #3877
