### ISSUE TITLE
Video open Fullscreen

### ISSUE THREAD

**Issue by mehedi0two** [zen-browser/desktop#3906]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Video open in Fullscreen make popup website banner and slow animation.Please revert to old fullscreen open animation like previous version.
![Screenshot 2024-12-20 212453](https://github.com/user-attachments/assets/62223859-6517-471c-9e87-f6045b774d58)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Version 1.0.2-b.3

### What platform are you seeing the problem on?

Windows

**Comment by Martaaz26** [comment]
i have same problem. And when i click fullscreen it do some "wink" animation.

**Comment by mr-cheffy** [comment]
Done

**Comment by Martaaz26** [comment]
i still have that problem :(

**Comment by mehedi0two** [comment]
> i still have that problem :(

it fixed now in latest version.
