### ISSUE TITLE
Workspace Tabs are Shared

### ISSUE THREAD

**Issue by Proziam** [zen-browser/desktop#391]
### What happened?

I have multiple workspaces. If I close the last tab in workspace 1, it will bring a tab from workspace 2 to replace it.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.26

### Severity impact

Medium

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
Fixed for the next release!
