### ISSUE TITLE
GCP documentation site unusable in Zen

### ISSUE THREAD

**Issue by stevesea** [zen-browser/desktop#3910]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The GCP documentation site is unusable in Zen. For example, https://cloud.google.com/deploy/docs/overview

Clicking links in the left-nav or top-nav of the site, or clicking on links on pages (sometimes) updates the URI of the tab but does not re-draw the content of the window.  If I refresh the window, or open the URL bar and hit enter, the content will be re-drawn.

Also, many of the pages are rendered without the instruction tabs. 

Screenshot below shows this URI https://cloud.google.com/run/docs/deploying#service , rendered in Zen, Chrome, and Firefox: 
<img width="2273" alt="zen_gcp_docs" src="https://github.com/user-attachments/assets/7a9ae1d4-84f8-4eea-a3e3-e3b69961d0c5" />

extensions I have installed: 
* facebook container
* firefox multi-account containers
* privacy badger
* duckduckgo privacy essentials
* uBlock Origin
* 1password

disabling the extensions doesn't appear to affect the problem.
opening the in a private window doesn't appear to affect the problem.

operating system: macOS, aarch64, Sequoia 15.2

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.3

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by greeeen-dev** [comment]
Not sure why this is happening on Zen specifically but this seems to be a CSS issue on Google's end, not Zen's. There's a `display: none` for some reason:
<img width="455" alt="image" src="https://github.com/user-attachments/assets/9e8ac368-ab55-4c07-9dfd-063d0eee34d6" />

**Comment by mr-cheff** [comment]
> Not sure why this is happening on Zen specifically but this seems to be a CSS issue on Google's end, not Zen's. There's a `display: none` for some reason: <img alt="image" width="455" src="https://private-user-images.githubusercontent.com/41323182/397883380-9e8ac368-ab55-4c07-9dfd-063d0eee34d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5NjM0OTksIm5iZiI6MTczNDk2MzE5OSwicGF0aCI6Ii80MTMyMzE4Mi8zOTc4ODMzODAtOWU4YWMzNjgtYWI1NS00YzA3LTlkZmQtMDYzZDBlZWUzNGQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIzVDE0MTMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwZjY1ZTA5NDEyOGZlZjk0MTg0N2U2YWJiNzczNDM2YTgxYjM2NjVkZTI4ZmJmNDFkNWZkYzUzNGRmN2NlMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WBJY2fILVSLs5pHlyBuGS4CflWPFtpnM4r4evdiFJwQ">

Could it simply be a view port issue? Like the tabs only show on larger screens? Let me check

**Comment by mr-cheffy** [comment]
Hmm.. Upon further investigation, in other browsers, you can see the javascript running where as in zen, it gives Content-Security-Policy warnings...

**Comment by mr-cheffy** [comment]
Ok, disabling `dom.enable_web_task_scheduling` fixes the issue

**Comment by n7itro** [comment]
This issue will be fixed in the next release. It is caused by

https://github.com/zen-browser/desktop/blob/e003fa2a661b89108ccf0818652ba2ec306a5cc9/src/browser/app/profile/zen-browser.js#L251
