### ISSUE TITLE
anti ad blocker

### ISSUE THREAD

**Issue by zmepe** [zen-browser/desktop#3911]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

fix your fucking program it wasnt like this before the fucking newest update that you guys force down my fucking throat 
![8AC05608-C3A0-4ACB-B3F9-74B82BD279E0](https://github.com/user-attachments/assets/f7f617d0-458a-4b7d-a737-85fa14bdad23)
![{1124A69F-BEB3-436F-88DF-0DC34D183082}](https://github.com/user-attachments/assets/fcdbc592-ae03-4b7d-8007-44ea73649aec)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

newest one

### What platform are you seeing the problem on?

Windows

**Comment by gnc-07** [comment]
This has nothing to do with Zen so please calm down. It is a problem with uBlock, try this solution here, it worked for me: https://www.reddit.com/r/uBlockOrigin/comments/1hir4z6/comment/m30vhjh/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

**Comment by syscat29** [comment]
@zmepe You should do some research before yapping, closing this.

**Comment by greeeen-dev** [comment]
\>uses an adblocker
\>adblocker gets blocked by youtube
\>blames it on zen for no reason

:sob:

**Comment by zmepe** [comment]
[image: {FE848335-DF87-4DCB-8EF8-CA133F5EADBC}.png]ok mb for crashing out
but its not there anymore cuz i really wish to continue using zen but i
just cant with the anti ad block

**Comment by greeeen-dev** [comment]
~~Disable quick fixes filter for the time being, this fixes it (somehow):~~
<img width="497" alt="image" src="https://github.com/user-attachments/assets/e835ec3e-cb89-44c9-bc0c-806f34ecfd43" />

**UPDATE**: The filter has been fixed, click on the clock icon next to the text to force an update.

**Comment by zmepe** [comment]
thanks it works now i can continue using zen :D
