### ISSUE TITLE
Keyboard navigation problems after clicking on extensions. Compact mode + multiple toobars

### ISSUE THREAD

**Issue by MemQu** [zen-browser/desktop#3912]
### Captchas

- [X] I have read the instructions.
- [ ] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Clicking on extensions (pinned or dropdown) disables arrow keys, page down, page up, dome, end, tab, ctrl + tab, ctrl + shift + tab. (There may be more, but this makes the browser unusable by keyboard). Compact mode and multiple toolbars are enabled. I have created this issue since this problem has been in the previous version (b.2), and maybe earlier.

Refer to #2743 and #2615 for more detail.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.3

### What platform are you seeing the problem on?

Windows

**Comment by mr-cheffy** [comment]
Please try to not make duplicates, see the issues you've already found
