### ISSUE TITLE
Toolbar not visible in compact mode while typing

### ISSUE THREAD

**Issue by kalenmike** [zen-browser/desktop#3913]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

In compact mode set as  "Hide Tab Bar" (which is flipped, it actually hides the top bar) and URL Bar set as normal, I am not able to see the top bar input while typing if I access it via keyboard shortcuts while it is hidden.

1. Top bar is hidden in compact mode
2. URL Bar is set to "Normal"
3. Hit "CTRL-L" and start typing
4. Top bar recommendations show but the input line is hidden.

If the mouse is hovering over the top bar and it is visible when sending the keyboard shortcut everything works correctly. The keyboard shortcut is not triggering Zen to show the top bar correctly since the introduction of the floating URL bar.

## URL Bar Settings
![image](https://github.com/user-attachments/assets/f2f9aff4-5602-46fc-a112-7ac0204ca876)

## Compact View Settings
![image](https://github.com/user-attachments/assets/f563f9d6-b10d-490f-920c-47dc4400c7d6)

## Bug
![image](https://github.com/user-attachments/assets/ca599812-3fab-4a8f-90cc-4e132181053f)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.3

### What platform are you seeing the problem on?

Linux

**Comment by syscat29** [comment]
Alright, can confirm this happens on Windows at least

![](https://cdn.discordapp.com/attachments/1094002137408753704/1319816986988908574/image.png?ex=676756da&is=6766055a&hm=7654442d7c01586b343eb534c5054d7fbe6c4efbd956fa3ff16ce94c95992505&)

Edit: Confirmed  to happen on my linux (EndeavourOS w/ Gnome) instance too
![image](https://github.com/user-attachments/assets/bb0e5acf-2ed7-4e45-8c1e-b1cb73993173)

**Comment by Ghos3t** [comment]
I can confirm that this is happening in Windows Version 1.0.2-b.3 (64-bit) as well, this happens for both "Hide Top Bar" & "Hide Both" options for me, when the Zen URL bar is set to "Normal" mode. Currently I have set the Zen URL bar to "Floating only when typing" as a work around as this makes the URL bar float slightly lower, so pressing "CTRL+L" to bring up the URL bar and start typing does not hide the bar anymore. I kinda don't like the floating URL bar much so I hope this gets fixed at some point.

**Comment by mr-cheffy** [comment]
Ok, I can reproduce now, will take a look
