### ISSUE TITLE
Compact mode options not working as expected

### ISSUE THREAD

**Issue by pndmhs** [zen-browser/desktop#3915]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The compact mode options don't work as expected. When you try to hide the tab bar, it hides the top bar instead, and vice versa. However, the option to hide both works correctly.
[Screencast_20241221_084055.webm](https://github.com/user-attachments/assets/ce146104-fe5c-48e1-9e67-66e686ac6b46)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.3

### What platform are you seeing the problem on?

Linux

**Comment by mr-cheffy** [comment]
Fixed in the next release, thanks! 👍🏽
