### ISSUE TITLE
Can't change the language

### ISSUE THREAD

**Issue by MarcosMost** [zen-browser/desktop#392]
### What happened?

I'm not able to update or change the language in the browser. When I click on "Search for more languages" the browser shows this message: "Zen Browser can’t update your languages right now. Check that you are connected to the internet or try again." I can complete this process in Firefox just fine.

![Captura de tela de 2024-08-21 15-36-47](https://github.com/user-attachments/assets/23d59d96-1b09-4bd8-b5f0-2239e8746329)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.26

### Severity impact

Medium

### What platform are you seeing the problem on?

Linux

**Comment by NOCanoa** [comment]
We are currently figuring out what is the optimal way to make the languages available and have an accurate translation, currently only the defaut is available.
