### ISSUE TITLE
Closing window quits application 

### ISSUE THREAD

**Issue by cogumbreiro** [zen-browser/desktop#3922]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

**Context:**
I have currently 2 windows open. The first window has 33 tabs distributed among multiple workspaces. The second window is empty (0 tabs open).

**Problem:** When I try to close the second window with 0 tabs, I get a confirmation dialog warning me that I am about to close 33 tabs. Confirming the action quits the application, instead of closing the window.

How can I close this second window? Please, let me know how if you need any more information.

Thank you!

**Acknowledgements:** I love Zen. It quickly became my favorite browser I use. I am especially a big fan of the Workspace management, which has helped me tame my tab-opening compulsion :-) Keep up the great work!

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2

### What platform are you seeing the problem on?

Linux

**Comment by mr-cheffy** [comment]
How do you even have a window with 0 tabs? Could you send a video?

**Comment by neurokitti** [comment]
> How do you even have a window with 0 tabs? Could you send a video?

i think he just means the default new tab

**Comment by mr-cheffy** [comment]
@neurokitti Why would you close this issue?

**Comment by neurokitti** [comment]
> @neurokitti Why would you close this issue?

Lol mb I legit miss clicked

**Comment by cogumbreiro** [comment]
> > How do you even have a window with 0 tabs? Could you send a video?
> 
> i think he just means the default new tab

Yes, that is what I mean.

Here's a screenshot of the offending window. My workspaces have pinned tabs, which appear in both windows and cannot be "closed". I did check if any of my workspaces had any opened tabs other than the "default new tab" and there aren't any.

![Screenshot from 2024-12-22 19-11-08](https://github.com/user-attachments/assets/8e199d93-5dbd-433c-8add-b1e3c70ccad0)

**Comment by mr-cheffy** [comment]
It doesn't close the window because you still have 2 pinned tabs...

**Comment by cogumbreiro** [comment]
Here's a summary of the conversation:
- I must redact my initial statement: closing the new window does **not** quit the application. I think I must've got confused somehow.
- In my opinion, opening a new window should not inherit pinned tabs. This becomes really annoying upon closing a window with multiple Workspaces and pinned tabs, because it's quite challenging to understand what's actually being closed. There is currently no way to know which tabs and from what workspace.
- The closing window dialog would be more helpful. It would be great if the close multiple-tabs dialog listed the titles of the tabs and ideally workspaces. As it stands just displaying a number is unhelpful.
