### ISSUE TITLE
In compact mode, moving a tab to another workspace makes the sidebar stuck in visible state.

### ISSUE THREAD

**Issue by siswonugroho** [zen-browser/desktop#3924]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I use compact mode with sidebar hidden. I tried to move a tab from default workspace to new one I've created, and then these happened:
1. The sidebar stuck in visible state and didn't auto-hide, covering the web page.
2. Can't right click any tab from any workspace.

Right clicking the web page and then closing the context menu solves the problem, but only until the next time I move a tab again.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.3

### What platform are you seeing the problem on?

Windows

**Comment by neurokitti** [comment]
this is a repeat of the following issues:
https://github.com/zen-browser/desktop/issues/3046
https://github.com/zen-browser/desktop/issues/2980

thanks for reporting the bug! please check to see if its a repeat first though!
