### ISSUE TITLE
Right click close and tab hiding

### ISSUE THREAD

**Issue by techwoes** [zen-browser/desktop#393]
### What happened?

When you right click to close a tab in the left side panel and compact mode is on then the tab window hides and the right click menu is open. I think the side tab should remain open until the right click operation is complete.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0 - a26

### Severity impact

Low

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by mauro-balades** [comment]
We know about this and unfortunately, I can't really do much about it because the sidebar doesn't know if it's being "menued", sorry
