### ISSUE TITLE
Improve touch-screen experience

### ISSUE THREAD

**Issue by Makitoid** [zen-browser/desktop#3932]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Zen是一款非常好用的browser，，在这里感谢开发者和所有对该项目的贡献者
但是，它的触屏体验并不好e.g.无法拖动窗口，点击控制最小化和关闭等控制按钮

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1 b2

### What platform are you seeing the problem on?

Windows

**Comment by mr-cheffy** [comment]
Hey! Thanks a lot, but please make issues in english so they are easier to identify and fix. Thanks!
