### ISSUE TITLE
Zip download not working for Windows

### ISSUE THREAD

**Issue by aryan6969** [zen-browser/desktop#3934]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

From past many weeks, zip version of download for optimized version of Windows not working. Just now tried, even the generic version of zip download not working for Windows. Tried using Zen Browser, Chrome, Firefox, Brave, no browser is able to download zip of optimized version of Windows.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.3 (Firefox 133.0.3) (64-bit)

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
Nothing happens clicking on 'Download Zip' button while trying to download optimized version/Zip download/Windows.
```

**Comment by mr-cheffy** [comment]
This is expected while we are trying to find solutions to store such big amounts of files into our servers, sorry

**Comment by aryan6969** [comment]
Thanks for responding !

<img width="880" alt="image" src="https://github.com/user-attachments/assets/3939ba57-dd6f-4f87-b548-8c78bae45b91" />

I believe this is the file of my interest, I believed its zip archive, I changed extension to .zip however, I am not able extract files correctly. How to make use of portable zip version for windows.

**Comment by Mancubuss** [comment]
Frankly speaking, being able to download zip from github would be completely sufficient for me personally. I'd be happy to have it as an option.

**Comment by vladimmi** [comment]
> store such big amounts of files into our servers

Files are downloaded from github anyway.

**Comment by aryan6969** [comment]
I agree we can leverage storage provided by GitHub for these big files. For Windows, which file to use as portable installer, Winodws.mar, how to install from this '.mar' file.
