### ISSUE TITLE
Moving tabs to a new workspace disables right click in sidebar

### ISSUE THREAD

**Issue by Ghos3t** [zen-browser/desktop#3935]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When I selected multiple tabs in the sidebar and right clicked and selected "Move tabs to workspace" to move them to a different workspace, the tabs were successfully moved over to the other workspace but now I cannot right click on the tabs in the sidebar.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.3 (Firefox 133.0.3) (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by mr-cheffy** [comment]
Fixed in b4
