### ISSUE TITLE
Can't run on MacOS ARM Architecture (m1)

### ISSUE THREAD

**Issue by erezak** [zen-browser/desktop#3937]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I went through the "Run locally" instructions, and everything worked as expected.
However, the last step (npm start) returns the following:

```bash
> zen-core@1.0.0 start
> cd engine && ./mach run --noprofile

It looks like you tried to run a mach command from an invalid context. The run
command failed to meet the following conditions: 

  has_build_or_shell - Must have a build or a shell build.

Run |mach help| to show a list of all commands available to the current context.
```

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Compiling from main branch

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by mr-cheffy** [comment]
You need to build zen first. If you did, make sure it has successfully done so

**Comment by harryheres** [comment]
@mr-cheff This is actually an issue on Macs. Without any further actions the build fails missing the `TestAUSHelper` file which is part of the unit testing suite. Deleting the following from `toolkit/mozapps/update/tests/Makefile.in`:

```
ifeq (cocoa,$(MOZ_WIDGET_TOOLKIT))
	XPCSHELLTESTDIR = $(topobjdir)/_tests/xpcshell/toolkit/mozapps/update/tests/data/

libs::
	$(NSINSTALL) -D $(DIST)/bin/callback_app.app
	rsync -a -C $(srcdir)/macbuild/Contents $(DIST)/bin/callback_app.app
	$(NSINSTALL) -D $(DIST)/bin/callback_app.app/Contents/MacOS
	$(NSINSTALL) $(XPCSHELLTESTDIR)/TestAUSHelper $(DIST)/bin/callback_app.app/Contents/MacOS
	cp -R $(DIST)/bin/callback_app.app $(XPCSHELLTESTDIR)
endif
```

The build is successful with the following message: 

```
00:00:20 Packaging specialpowers@mozilla.org.xpi...
00:00:23 Packaging mozscreenshots@mozilla.org.xpi...
00:00:24 W 1008 compiler warnings present.
00:00:24 W Overall system resources - Wall time: 23s; CPU: 64%; Read bytes: 1471258624; Write bytes: 620453888; Read time: 16086; Write time: 287
00:00:24 W Swap in/out (MB): 992.078125/0.0
00:00:24 Your build was successful!
00:00:24 /usr/bin/make -C . -j10 -s -w package
```

However, if you notice the last line, the `package` script is run automatically for an unknown reason (to me). After further investigation, I suspect that the dynamic configuration is not loaded properly due to following output from surfer right at the start of the build process: 

```
00:00:00 Applying mozconfig...
00:00:00 Dynamic config 'brand not set, defaulting to 'unofficial'
00:00:00 Dynamic config 'buildMode not set, defaulting to 'dev'
00:00:00 Dynamic config 'buildMode not set, defaulting to 'dev'
00:00:00 Building config based on a dev mod
```

During the package process the unit test suite is ran without any issues, however it ends with a benchmark and nothing more. The browser instance used in the unit testing seems functional, however running `mach run` outputs the same message as in the original description of this issue.

**Comment by thatcomputerguy0101** [comment]
I don’t have the time to look into it right now, but this may be related to my problems with #3202.

**Comment by mr-cheffy** [comment]
> [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/91018726?s=64&amp;u=4f26487784a882d9053c0f2a180708d789c8738a&amp;v=4">@mr-cheff](https://github.com/mr-cheff) This is actually an issue on Macs. Without any further actions the build fails missing the `TestAUSHelper` file which is part of the unit testing suite. Deleting the following from `toolkit/mozapps/update/tests/Makefile.in`:
> 
> ```
> ifeq (cocoa,$(MOZ_WIDGET_TOOLKIT))
> 	XPCSHELLTESTDIR = $(topobjdir)/_tests/xpcshell/toolkit/mozapps/update/tests/data/
> 
> libs::
> 	$(NSINSTALL) -D $(DIST)/bin/callback_app.app
> 	rsync -a -C $(srcdir)/macbuild/Contents $(DIST)/bin/callback_app.app
> 	$(NSINSTALL) -D $(DIST)/bin/callback_app.app/Contents/MacOS
> 	$(NSINSTALL) $(XPCSHELLTESTDIR)/TestAUSHelper $(DIST)/bin/callback_app.app/Contents/MacOS
> 	cp -R $(DIST)/bin/callback_app.app $(XPCSHELLTESTDIR)
> endif
> ```
> 
> The build is successful with the following message:
> 
> ```
> 00:00:20 Packaging specialpowers@mozilla.org.xpi...
> 00:00:23 Packaging mozscreenshots@mozilla.org.xpi...
> 00:00:24 W 1008 compiler warnings present.
> 00:00:24 W Overall system resources - Wall time: 23s; CPU: 64%; Read bytes: 1471258624; Write bytes: 620453888; Read time: 16086; Write time: 287
> 00:00:24 W Swap in/out (MB): 992.078125/0.0
> 00:00:24 Your build was successful!
> 00:00:24 /usr/bin/make -C . -j10 -s -w package
> ```
> 
> However, if you notice the last line, the `package` script is run automatically for an unknown reason (to me). After further investigation, I suspect that the dynamic configuration is not loaded properly due to following output from surfer right at the start of the build process:
> 
> ```
> 00:00:00 Applying mozconfig...
> 00:00:00 Dynamic config 'brand not set, defaulting to 'unofficial'
> 00:00:00 Dynamic config 'buildMode not set, defaulting to 'dev'
> 00:00:00 Dynamic config 'buildMode not set, defaulting to 'dev'
> 00:00:00 Building config based on a dev mod
> ```
> 
> During the package process the unit test suite is ran without any issues, however it ends with a benchmark and nothing more. The browser instance used in the unit testing seems functional, however running `mach run` outputs the same message as in the original description of this issue.

Isn't this because PGO is enabled for macos?

**Comment by harryheres** [comment]
> > [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/91018726?s=64&amp;u=4f26487784a882d9053c0f2a180708d789c8738a&amp;v=4">@mr-cheff](https://github.com/mr-cheff) This is actually an issue on Macs. Without any further actions the build fails missing the `TestAUSHelper` file which is part of the unit testing suite. Deleting the following from `toolkit/mozapps/update/tests/Makefile.in`:
> > ```
> > ifeq (cocoa,$(MOZ_WIDGET_TOOLKIT))
> > 	XPCSHELLTESTDIR = $(topobjdir)/_tests/xpcshell/toolkit/mozapps/update/tests/data/
> > 
> > libs::
> > 	$(NSINSTALL) -D $(DIST)/bin/callback_app.app
> > 	rsync -a -C $(srcdir)/macbuild/Contents $(DIST)/bin/callback_app.app
> > 	$(NSINSTALL) -D $(DIST)/bin/callback_app.app/Contents/MacOS
> > 	$(NSINSTALL) $(XPCSHELLTESTDIR)/TestAUSHelper $(DIST)/bin/callback_app.app/Contents/MacOS
> > 	cp -R $(DIST)/bin/callback_app.app $(XPCSHELLTESTDIR)
> > endif
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The build is successful with the following message:
> > ```
> > 00:00:20 Packaging specialpowers@mozilla.org.xpi...
> > 00:00:23 Packaging mozscreenshots@mozilla.org.xpi...
> > 00:00:24 W 1008 compiler warnings present.
> > 00:00:24 W Overall system resources - Wall time: 23s; CPU: 64%; Read bytes: 1471258624; Write bytes: 620453888; Read time: 16086; Write time: 287
> > 00:00:24 W Swap in/out (MB): 992.078125/0.0
> > 00:00:24 Your build was successful!
> > 00:00:24 /usr/bin/make -C . -j10 -s -w package
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > However, if you notice the last line, the `package` script is run automatically for an unknown reason (to me). After further investigation, I suspect that the dynamic configuration is not loaded properly due to following output from surfer right at the start of the build process:
> > ```
> > 00:00:00 Applying mozconfig...
> > 00:00:00 Dynamic config 'brand not set, defaulting to 'unofficial'
> > 00:00:00 Dynamic config 'buildMode not set, defaulting to 'dev'
> > 00:00:00 Dynamic config 'buildMode not set, defaulting to 'dev'
> > 00:00:00 Building config based on a dev mod
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > During the package process the unit test suite is ran without any issues, however it ends with a benchmark and nothing more. The browser instance used in the unit testing seems functional, however running `mach run` outputs the same message as in the original description of this issue.
> 
> Isn't this because PGO is enabled for macos?

Will try to disable it tomorrow.

**Comment by harryheres** [comment]
Ok, with reverted #3202 the local build works. FYI @mr-cheff.

**Comment by mr-cheffy** [comment]
Yeah, we should only do pgo on release builds
