### ISSUE TITLE
browser scrolling sensitivity unnecessary

### ISSUE THREAD

**Issue by KorigamiK** [zen-browser/desktop#3938]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I think the recent update just messed up the scrolling behaviour on firefox that users had been accustomed, there's no document way to disable this change and i would like to get the previous behaviour back. 

Please take care of such changes in the release notes as this is a breaking change that deviates from normal firefox and should be marked appropriately as well.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Mozilla Zen 1.0.2-b.3

### What platform are you seeing the problem on?

Linux

**Comment by mr-cheffy** [comment]
It has been lowered for the next release, thanks!
