### ISSUE TITLE
Move tab to other window when compact mode sidebar

### ISSUE THREAD

**Issue by bphd** [zen-browser/desktop#3940]
### Captchas

- [ ] I have read the instructions.
- [ ] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

How

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

latest

### What platform are you seeing the problem on?

Linux

**Comment by bphd** [comment]
@mr-cheff It's resolved? When I try to move the tab it's still not able

**Comment by mr-cheffy** [comment]
This bug report is useless, uninformative and duplicated

**Comment by bphd** [comment]
> duplicated

To what
