### ISSUE TITLE
Zen Browser Udemy Issue

### ISSUE THREAD

**Issue by sercanatay** [zen-browser/desktop#3942]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![Screenshot 2024-12-22 210805](https://github.com/user-attachments/assets/121e5cd7-0a7e-42f9-a4ef-b7c9bad3ccc9)
i added photo for bug i don't know anything to solve issue

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.3 (Firefox 133.0.3) (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by sercanatay** [comment]
i tried reload page and restart system but noway i can't solve issue

**Comment by sercanatay** [comment]
i tried reload page and restart system but  i can't solve issue

**Comment by LimaneGaya** [comment]
I think this is because Udemy uses Widevine and [Zen Browser does not yet support it due to the needed licence](https://docs.zen-browser.app/faq#why-cant-zen-browser-play-drm-protected-content).

**Comment by sercanatay** [comment]
Hmm, Do you have any suggestions on how to solve this situation or can I solve it?

> I think this is because Udemy uses Widevine and [Zen Browser does not yet support it due to the needed licence](https://docs.zen-browser.app/faq#why-cant-zen-browser-play-drm-protected-content).

**Comment by LimaneGaya** [comment]
Not sure, as a regular user i'm also waiting for them to fix some video issues to completely switch to it.
