### ISSUE TITLE
Unable to connect to mozilla accounts

### ISSUE THREAD

**Issue by anispwyn** [zen-browser/desktop#395]
### What happened?

When try to login using mozilla accounts to allow sync and stuff

after login success, the account would disconnect immediately after login

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0.a.23

### Severity impact

Medium

### What platform are you seeing the problem on?

Linux

**Comment by NOCanoa** [comment]
what version exactly u runing?
1.0.0-a20 example

**Comment by anispwyn** [comment]
1.0.0.a.23-1

**Comment by NOCanoa** [comment]
have u tryed in the newer version we are on a.26 now

**Comment by anispwyn** [comment]
I will give it a try. it seems like the aur is outdated, thanks

**Comment by NOCanoa** [comment]
huh, give a sec i know who i can annoy xD

**Comment by ThatOneCalculator** [comment]
When installing from the AUR, you can `yay -S zen-browser-avx2-bin --editmenu` and edit the PKGBUILD to have the .26 version (and skip the first hash)

**Comment by anispwyn** [comment]
updated, re-login and it works now... cool

**Comment by Sophed** [comment]
Having this exact same issue on `1.0.0-a.28` on Linux, anyone else?

**Comment by anispwyn** [comment]
Try logout and login again

-------- Original Message --------
On 8/24/24 8:43 PM, Sophia wrote:
Having this exact same issue on 1.0.0-a.28 on Linux, anyone else?
