### ISSUE TITLE
Address Bar is off-center (MacOS)

### ISSUE THREAD

**Issue by AjayDextrous** [zen-browser/desktop#3950]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

<img width="1624" alt="Screenshot 2024-12-23 at 7 21 44 AM" src="https://github.com/user-attachments/assets/ee189de1-8c93-47a1-8008-0ec45a615cfe" />

As you can see, the floating address bar is off center

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-t.4 (Firefox 133.0.3) (2024-12-19) (aarch64)

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by daniilium** [comment]
I don't see

<img width="761" alt="image" src="https://github.com/user-attachments/assets/90cb78cc-2e1b-4514-aefb-aa7e364c956f" />

**Comment by AjayDextrous** [comment]
Now that I look at it, you're right. I still think it looks somehow weird. Perhaps it might be because its not vertically centered?
