### ISSUE TITLE
An option to enable middle click to paste

### ISSUE THREAD

**Issue by OncePunchedMan** [zen-browser/desktop#396]
### What feature would you like to see?

Librewolf has this neat feature which let you paste using the middle mouse button

![image](https://github.com/user-attachments/assets/76977c8f-941d-4864-a009-ebddfaba7fa7)

### What platform are you seeing the problem on?

Windows

### Additional context

It could be an option people can but don't have to enable. It's obviously disabled by default.

**Comment by n7itro** [comment]
This setting can be enabled in `about:config` with `middlemouse.paste`.
