### ISSUE TITLE
Extensions creating blank space when reopened

### ISSUE THREAD

**Issue by schembriaiden** [zen-browser/desktop#3966]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Since I updated to 1.0.2-b.4, the extensions are now creating a blank space on top of them if reopened more than once. This is also happening with a fresh install of the browser with just one extension installed.

![image](https://github.com/user-attachments/assets/73e4b672-53c4-4baa-9efa-55ac6215570a)

![image](https://github.com/user-attachments/assets/7496c95c-0e67-475b-908b-a236d9ee3b9b)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.4

### What platform are you seeing the problem on?

Windows

**Comment by kurukoseahmet** [comment]
Same thing happens in MacOS. 
Version: 1.0.2-b.4 (Firefox 133.0.3) (aarch64)
Platform: MacOS Sequoia 15.2

**Comment by Renkoto** [comment]
Same thing happens on Linux.
Version 1.0.2-b.4 (Firefox 1.3.3.0.3) (x86_64)
Platform: Arch Linux (using the tarball install)

**Comment by schembriaiden** [comment]
Seems to be fixed with 1.0.2-b.5
