### ISSUE TITLE
Add Option to Switch to Horizontal Tabs

### ISSUE THREAD

**Issue by albu-ali** [zen-browser/desktop#397]
### What feature would you like to see?

**Description:**

The zen browser uses vertical tabs by default, with no option to switch to horizontal tabs in the settings. This can be inconvenient for users accustomed to horizontal tabs in normal browser like firefox.

**Issue:**

- Vertical tabs are the default layout.
- No option to switch to horizontal tabs in the settings.

**Suggested Solution:**

- Add an option in the settings to switch between vertical and horizontal tab layouts.

And keep up the awesome work!

### What platform are you seeing the problem on?

Linux

**Comment by NOCanoa** [comment]
duplicate https://github.com/zen-browser/desktop/issues/158
