### ISSUE TITLE
Toolbar icons not centered properly on macOS

### ISSUE THREAD

**Issue by evqsx** [zen-browser/desktop#3973]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

As shown in the screenshot below, the Forward/Back/refresh buttons (at the top left corner, on the toolbar) are not centered correctly in macOS. 

<img width="1280" alt="Screenshot 2024-12-24 at 23 13 29" src="https://github.com/user-attachments/assets/c4cbec94-a3a7-4401-a9bd-5531dfcccad4" />

The centering does not take into account the macOS Close/Minimise/Maximise "traffic lights" and as a result looks unpleasant.

This is the "customize toolbar" view which also looks off.
<img width="1280" alt="Screenshot 2024-12-24 at 23 15 25" src="https://github.com/user-attachments/assets/5311089f-78e2-4141-aeaa-a00a64a0ea4e" />

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.4

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by Nishantdd** [comment]
Have you tried adding a flexible space right after the min/max buttons?

**Comment by evqsx** [comment]
<img width="1280" alt="Screenshot 2024-12-31 at 01 00 25" src="https://github.com/user-attachments/assets/997772c5-11c2-4902-9c57-de3fb36224fd" />

It then looks like this

**Comment by mr-cheffy** [comment]
Should be fixed in b6 👍🏽
