### ISSUE TITLE
Laggy Scrolling and UI after updating from 1.0.2-b3 to 1.0.2-b4 and b5

### ISSUE THREAD

**Issue by xXSalamanderXx** [zen-browser/desktop#3975]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The general user interface animations as well as scrolling have a **much lower frame-rate** after updating from beta 3 to betas 4 and 5.

This is especially noticable as my moniter is 144hz. It's feeling really stuttery and low frame rate throughout the entire browser.

I suspect this bug has been caused by the modifications made to scrolling multiplier implemented in 1.0.2-b4.

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b5

### What platform are you seeing the problem on?

Windows

**Comment by xXSalamanderXx** [comment]
My apologies. This was caused by a setting inside Nvidia Control Panel called "Background Application Max Frame Rate". I suggest people keep this option DISABLED if you use Nvidia graphics, as it will limit fps of applications even if you aren't playing a game.

**Comment by BoscoDomingo** [comment]
Just FYI I had the same issue (slow animations and janky behaviour). Disabling Background Application Max Frame Rate restored it back to normal.

Funny that it only affected Zen, though. Chrome and Firefox worked perfectly fine

Edit: Lagginess persists at startup, which is quite annoying. I've updated drivers and still there. It does go away after a bit
