### ISSUE TITLE
Theme bleeds into websites

### ISSUE THREAD

**Issue by ironcloudy** [zen-browser/desktop#3978]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

It seems the theme replaced some part of the site's CSS when browser.tabs.allow_transparent_browser is on
![Screenshot 2024-12-24 124834](https://github.com/user-attachments/assets/c9f4b4ff-8d73-4a3c-b599-e5fd71ae6e6d)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.5

### What platform are you seeing the problem on?

Windows

**Comment by xXSalamanderXx** [comment]
Hi, 

I found a fix for this today on reddit after experiencing the issue aswell.

Modify your about:config at - browser.tabs.allow_transparent_browser and set the value to FALSE.

You could also add `user_pref("browser.tabs.allow_transparent_browser", false);` into a user.js file in your zen profile directory folder. You can find the folder by going into about:profiles and opening the root directory folder.

**Comment by ironcloudy** [comment]
> Hi,
> 
> I found a fix for this today on reddit after experiencing the issue aswell.
> 
> Modify your about:config at - browser.tabs.allow_transparent_browser and set the value to FALSE.
> 
> You could also add `user_pref("browser.tabs.allow_transparent_browser", false);` into a user.js file in your zen profile directory folder. You can find the folder by going into about:profiles and opening the root directory folder.

Thanks, but that's more of a hack than a fix.
I think having the Zen team looking into the root of the issue is a better way to make sure things work the way they're intended to be.

**Comment by xXSalamanderXx** [comment]
I offered you a temporary solution. You can choose to take it or not, but I don't appreciate the tone and attitude of your responce. You type about:config in the url bar and change one value. Maybe that's too hard for you?

If you want a browser with zero bugs go and download firefox, leave the experimental beta browsers to people who can handle them.

**Comment by ironcloudy** [comment]
Not sure what tone and attitude you got from 2 simple sentences that are merely stating the facts and intention of this issue report. If people are looking for temporary solution, they'll go to Reddit like yourself. 
Reason people take time going to through official, and preferred by the Zen team, routes, is to be able to contribute as beta users,  and to make sure the issue is being pointed out, so the team can perfect the project. This is place should be professional, so lose your unconstructive emotion, if you can't, Reddit is always a better place for you to be

**Comment by xXSalamanderXx** [comment]
I provided you insight into the root cause of the issue. The problem is with Zen setting "browser.tabs.allow_transparent_browser" to true. But you tell me my answer is just a hack? 

All that the Zen devs need to do, is do what I just told you above. But you have the opportunity to fix it for yourself, in the span of 10 seconds of work.

Anyway, I think you don't understand where I am coming from. Let's just leave it at that, and Zen can change the about:config for you in a few days :)

**Comment by ironcloudy** [comment]
Both transparency settings aren't meant to make the content transparent, or disrupt the content CSS behavior. So your "problem" is actually a consequence of the actual issue. 
Zen team wants a good app out of box, which Cheff and the team is working hard on that. Your "fixing" it in 10s is irrelevant. User hack is just temporary, not a permanent solution of make things better, you would understand if you're actually experienced.

Please don't keep on with your emotional chat here. Take it to Discord if you will. Thanks

**Comment by xXSalamanderXx** [comment]
This is why I don't try help people on the internet.

I gave you an answer, you just sounded ungreatful and said you want root cause fixes. I'm not part of the Zen dev team, so don't treat me as such.

Whether the solution I brought up helps Zen or not, its still a fix and the bug is probably closely linked to it.

Take help where you can get it in life, instead of sounding ungreatful.

**Comment by ironcloudy** [comment]
I'm not here asking for help. I'm here to bring an issue to the team's attention. 
So excuse me with your seek-for-gratefulness issue.
Again, this is the place to let Zen team be aware of an issue, not for temporary fix.

Your mention on the transparency settings are perhaps related, and you could just lead and end with that. Then we can have further constructive conversation on the issue. Asking people to be grateful and careful with your fragility is an overstatement.

**Comment by xXSalamanderXx** [comment]
I'm sorry but you saying I'm the emotional one? Your seething and it shows.

Let's hope Zen gets to the bottom of it.

Merry Christmas.

**Comment by ironcloudy** [comment]
@xXSalamanderXx you definitely have a way to see everyone emote like yourself. Imaginary injection of emotion to plain logical statements is common. Not useful when trying to solve problem.

**Comment by xXSalamanderXx** [comment]
Good luck to you. Go and be constructive then. 

Because constantly replying to this thread with your argumentative attitude and insults isn't leading to your browser becoming opaque any time soon. Now go enjoy Christmas instead of wasting my time.

**Comment by ironcloudy** [comment]
Seeing everything as insult. Typical. Proving the point.

**Comment by ironcloudy** [comment]
Issue on Firefox side.
Close the issue for irrelevance to Zen development.
