### ISSUE TITLE
Flatpak random crashes

### ISSUE THREAD

**Issue by clintre** [zen-browser/desktop#398]
### What happened?

System Specs
Fedora 40 KDE Spin with Wayland
Kernel 6.10.5
Nvidia 4070 with 555.58 drivers

Ever since installing Zen Browser via Flatpak, it has random crashes. Even going through the initial setup crashed 3 times. I can run it, and it will run fine for 20 minutes or not even make it a few minutes. I tested other browsers installed via Flatpak, including Firefox and Chromium, with no issues.

To troubleshoot, I launched it from the command line to see what is happening. Below is the output after it crashed...

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.23

### Severity impact

Critical

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
flatpak run io.github.zen_browser.zen 
[Parent 2, Main Thread] WARNING: Failed to enumerate devices of org.freedesktop.UPower: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
: 'glib warning', file /home/runner/work/desktop/desktop/engine/toolkit/xre/nsSigHandlers.cpp:187

** (zen-alpha:2): WARNING **: 14:27:54.416: Failed to enumerate devices of org.freedesktop.UPower: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown

Crash Annotation GraphicsCriticalError: |[0][GFX1-]: Wayland protocol error: wp_linux_drm_syncobj_surface_v1@72: error 4: explicit sync is used, but no acquire point is set
 (t=668.454) [GFX1-]: Wayland protocol error: wp_linux_drm_syncobj_surface_v1@72: error 4: explicit sync is used, but no acquire point is set

Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
```

**Comment by mauro-balades** [comment]
Checkout https://github.com/zen-browser/desktop/issues/296
