### ISSUE TITLE
[BUG] Extension Expands Vertically on Each Usage

### ISSUE THREAD

**Issue by kodebarista** [zen-browser/desktop#3987]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The Zen browser extensions exhibits a bug where it expands vertically after each use. Over time, this results in the extension overflowing the screen height, making it practically impossible to use effectively

**Steps to Reproduce:**
- Open the Zen browser
- Click on a extension.
- Click somewhere else and click on the same extension.
- Repeat step 3.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.4 (Firefox 133.0.3)

### What platform are you seeing the problem on?

Linux

**Comment by kodebarista** [comment]
Here's an example of how it works.
I checked it multiple times with different extensions and the behavior was reproducible.
Exiting the browser resets and fixes the extension only to reproduce bug in next session

https://github.com/user-attachments/assets/1f90194b-1685-4895-afef-2e2a479d1db7

**Comment by schembriaiden** [comment]
This was fixed with 1.0.2-b.5, https://github.com/zen-browser/desktop/issues/3966

**Comment by kodebarista** [comment]
I'm running fedora and I don't see any updates in the Software center. I guess flatpak version is not yet updated to latest in flathub

**Comment by schembriaiden** [comment]
No its not: https://flathub.org/apps/io.github.zen_browser.zen

**Comment by schembriaiden** [comment]
Seems to be updated now so if you could close this issue that would be great :)
