### ISSUE TITLE
Unexpected text appears when selecting wallpapers and typing.

### ISSUE THREAD

**Issue by utopiaeh** [zen-browser/desktop#3988]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

https://github.com/user-attachments/assets/7e3e7cfd-1cc8-4082-8a3d-30bbf554deb7

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.5 

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by neurokitti** [comment]
![image](https://github.com/user-attachments/assets/b968af51-50f4-499c-b88f-59949537ab4f)

this is a firefox issue. thanks for the report though! please check first if possible!
