### ISSUE TITLE
Creating Workspaces on Linux

### ISSUE THREAD

**Issue by IsidisKaa** [zen-browser/desktop#399]
### What feature would you like to see?

Currently cannot find a way to create new workspaces. I also did not see any keyboard binding option to create one either.

### What platform are you seeing the problem on?

Linux

**Comment by n7itro** [comment]
Could you provide a screenshot of the browser window so we can better assess your problem

**Comment by n7itro** [comment]
Also, can you verify that you have workspaces enabled in the settings

**Comment by IsidisKaa** [comment]
I went to verify that the workspaces were enabled, they did show as having that button selected but when I unclicked and reclicked it, it looks like the option to add workspaces did add the "+" button to create new workspaces. So this one is solved I think.
