### ISSUE TITLE
Animation of popup round corners clipped by masks

### ISSUE THREAD

**Issue by ironcloudy** [zen-browser/desktop#3991]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Due to the back out easing animation, menus and popups grew bigger than the masks, resulting cropped corners to sharp, and back to designated dimension, with corners back to round. 

Only lasts fraction of a second, but feels like a mistake. Unless it's a design decision.

Suggest to animate the masks along with the menus and popups.

https://github.com/user-attachments/assets/942bc7eb-7486-4381-b5e2-725ca42e9051

<img width="130" alt="Screenshot 2024-12-25 at 4 50 42 AM" src="https://github.com/user-attachments/assets/a3d998f2-607c-45c9-b33c-096d764709e8" />

<img width="133" alt="Screenshot 2024-12-25 at 4 51 13 AM" src="https://github.com/user-attachments/assets/ab521403-6919-4dd9-9034-52e93149b464" />

<img width="273" alt="Screenshot 2024-12-25 at 4 51 01 AM" src="https://github.com/user-attachments/assets/5434edea-357b-4460-8224-a8f86c2675ad" />

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.5

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by mr-cheffy** [comment]
Ill move this into https://github.com/zen-browser/desktop/issues/4048
