### ISSUE TITLE
Custom colors do not work as they should with solid colors

### ISSUE THREAD

**Issue by litaniecontrelapeur** [zen-browser/desktop#3999]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![image](https://github.com/user-attachments/assets/7523544c-a2de-4acc-974d-d7cdc4dfacf5)

Shouldn't it work as indicated? If you put only one color it is because you want only that color, in solid, but the gradient remains.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.5

### What platform are you seeing the problem on?

Windows

**Comment by GJRobert** [comment]
Hi there, I can answer this: if you just one color of your Custom Color, please right-click or two-finger-tap on those 5 color dots above in the color wheel, to remove them one by one, then finally you should get your only solid Custom Color going.
