### ISSUE TITLE
Brwoser user interface turns to red when "System theme - auto" or third party themes are enabled. 

### ISSUE THREAD

**Issue by thairanaru** [zen-browser/desktop#40]
Browser user interface turns to red when "System theme - auto" or third party themes are enabled. Some elements like font color do change. 

![Screenshot from 2024-07-12 10-32-10](https://github.com/user-attachments/assets/db064642-7d46-4e11-abf0-a73fbba9774c)

**System information:**
Arch Linux, niri 
Zen Browser Version 1.0.0-a.1 (64-bit)

**Comment by mauro-balades** [comment]
*should be fixed*
