### ISSUE TITLE
Unable to view bookmarks toolbar

### ISSUE THREAD

**Issue by myrrhkhan** [zen-browser/desktop#4000]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

I previously had my bookmarks always visible. A few months ago, I stopped being able to see the bookmarks toolbar, but haven't had the chance to create an issue until now.

In Mozilla Firefox, I can enable viewing the toolbar via View -> Bookmarks toolbar (https://support.mozilla.org/en-US/kb/bookmarks-toolbar-display-favorite-websites), but here, that option no longer shows up:
<img width="353" alt="image" src="https://github.com/user-attachments/assets/cbca9fb7-9cff-4974-9e2a-64d5a8b830ac" />

If there is a new place to enable the bookmarks toolbar? Thanks!

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.5

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by GJRobert** [comment]
Hi there can you try clicking on the menu button of Firefox, then "Bookmarks", then see if you see a "Show/Hide Bookmark Bar" there?
<img width="321" alt="截圖 2024-12-26 18 30 42" src="https://github.com/user-attachments/assets/ee8fd2ef-4554-4def-b5e9-d3103a2ec193" />
<img width="346" alt="截圖 2024-12-26 18 31 46" src="https://github.com/user-attachments/assets/e44b2e68-cd76-461a-bfa5-655d5fb97473" />

**Comment by myrrhkhan** [comment]
there we go, I see it now, thanks!
