### ISSUE TITLE
Remove browser padding mod not working

### ISSUE THREAD

**Issue by wealstarr** [zen-browser/desktop#4005]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Zen mod [remove browser padding](https://zen-browser.app/mods/680424a8-a818-406b-98c5-7726214e2a9f/) has no effect.

Also, a question. How can I make this mod available for all users and new profiles without having to download and enable it one by one?

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2 B5 x64

### What platform are you seeing the problem on?

Windows

**Comment by mr-cheffy** [comment]
Please report it to the mod's author

**Comment by wealstarr** [comment]
Thank you for the response but the author doesn't exist on Github anymore. I think it's the main dev of Zen browser.

Any other options do I have?
