### ISSUE TITLE
Make profiles compatible with Firefox

### ISSUE THREAD

**Issue by Farseer2** [zen-browser/desktop#401]
### What feature would you like to see?

As it stands, attempting to copy a Firefox profile over to Zen doesn't work (Even if both are on the same version), and Zen refuses to open claiming the profile is much newer than the browser.

This happens as Firefox saves its version in the profile's `compatibility.ini` (In my case 129) and Zen compares it to its own version (In my case, 1.0.0-a26).

Fixing this or allowing an auto-import which would replace the version could make transitioning from Firefox to Zen much easier.

(After patching `compatibility.ini` to the correct Zen version, the profile loaded without any issue)

### What platform are you seeing the problem on?

Windows

**Comment by Braayy** [comment]
Can confirm that a simple copy works! All my sessions, history and everything works normally.

The only 2 things i needed to do was patch the `compatibility.ini` and delete my `userChrome.css` file, cuz it was hiding the tab bar on the vanilla firefox and so on zen too lol.

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/849

 ~ This is an automatic operation to better enhancements requests organization.
