### ISSUE TITLE
After using the Zen browser for some time, the arrow keys become unresponsive, making it impossible to move the cursor left or right, and a restart is necessary to fix the issue

### ISSUE THREAD

**Issue by xixixiaoyu** [zen-browser/desktop#4011]
### Captchas

- [x] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.

### What happened?

As mentioned in the title

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.5 (64 位) 

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by mr-cheffy** [comment]
Duplicate of #2743
