### ISSUE TITLE
Windows chrome not looking right

### ISSUE THREAD

**Issue by sguergachi** [zen-browser/desktop#4017]
### Captchas

- [x] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.

### What happened?

The title bar color theme breaks the UI theme, makes it look weird. Check out how the buttons in the title bar cross over, with the windows theme color awkwardly splitting the top. This only happens when the screen is in focus.

Using Win 11 24H2

![image](https://github.com/user-attachments/assets/7a0a7049-813a-4e50-8dee-b26e456b18cc)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.5 

### What platform are you seeing the problem on?

Windows

**Comment by sguergachi** [comment]
This is what it looks like when window is out of focus. Much better. This is what it's supposed to look like.
![image](https://github.com/user-attachments/assets/1a1c6009-a313-46b4-a7a1-39a74dc8778c)

**Comment by syscat29** [comment]
This is a known bug with windows and it's being worked on. For now, disable applying accent color to titlebars in personalization and it'll go away.

Also, please use the search bar before opening an issue this has been reported many times #3546 #3469 #3842 #3693
