### ISSUE TITLE
Respect "Select a container for each new tab" setting when opening a link from outside the browser

### ISSUE THREAD

**Issue by dewantawsif** [zen-browser/desktop#403]
### What feature would you like to see?

Title should be self explanatory

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/848

 ~ This is an automatic operation to better enhancements requests organization.
