### ISSUE TITLE
(Sidebar): The workspace icons are too small

### ISSUE THREAD

**Issue by mr-cheffy** [zen-browser/desktop#4042]

**Comment by lrodziewicz** [comment]
Have this been solved?
I'm running Zen Browser 1.10.1b on Linux (Wayland) and at 1440p they are way too small (see attached picture). Or is there some setting that I'm missing?

![Image](https://github.com/user-attachments/assets/40b128ed-8649-40c0-a7df-1eaeafc149f4)
