### ISSUE TITLE
The address bar will offset correct position when input in newtab.

### ISSUE THREAD

**Issue by pheotry** [zen-browser/desktop#4058]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![image](https://github.com/user-attachments/assets/2ea19cf0-fee4-42e0-bdad-6fded2662bed)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.5

### What platform are you seeing the problem on?

Windows

**Comment by different55** [comment]
Change this from Floating to Normal. It's a new feature.

<img width="333" alt="Screenshot 2024-12-30 at 8 41 16 PM" src="https://github.com/user-attachments/assets/4ae2023a-fc4e-4ed2-bacb-598d558b5e45" />
