### ISSUE TITLE
Zen installer still uses the Firefox installer icon

### ISSUE THREAD

**Issue by dewantawsif** [zen-browser/desktop#406]
### What happened?

Self-explanatory title

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.26

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by n7itro** [comment]
This will be fixed with the next release.

**Comment by mauro-balades** [comment]
Next next release. 28

**Comment by dewantawsif** [comment]
Alright 😂

**Comment by LouieTian0209** [comment]
I checked the latest release to date and the installer icon is still the Firefox one. How come this issue is closed? @n7itro @mauro-balades
