### ISSUE TITLE
Respect "Select a container for each new tab" setting when opening tab with CTRL + T shortcut

### ISSUE THREAD

**Issue by dewantawsif** [zen-browser/desktop#407]
### What feature would you like to see?

Self-explanatory title

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/847

 ~ This is an automatic operation to better enhancements requests organization.
