### ISSUE TITLE
Password manager isn't autofilling saved passwords / accounts

### ISSUE THREAD

**Issue by hydro63** [zen-browser/desktop#4073]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Whenever i try to log in to some account, it never autofills the passwords / usernames, even though i have all the accounts saved. I also checked the password manager and all the accounts and passwords are there. I've also disabled all the mods and it still doesn't work.
Example:
![Screenshot 2024-12-30 134659](https://github.com/user-attachments/assets/254a8475-c344-4937-a55e-a55a6a0a79cd)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.5

### What platform are you seeing the problem on?

Windows

**Comment by umarhamzy** [comment]
This is because password manager is set to off by default in a recent update, you can turn it back on and continue as you were or try a different service like Bitwarden

**Comment by hydro63** [comment]
Understandable, thank you and have a nice day
