### ISSUE TITLE
Unpinned sidebar displays wrong pin button icon on startup (Pin and unpin fixes this until restart)

### ISSUE THREAD

**Issue by stetide** [zen-browser/desktop#408]
### What happened?

When starting zen with an unpinned sidebar from the previous session the icon is the one for unpinning instead of pinning.

![Image](https://github.com/user-attachments/assets/a1995321-72fc-4a1f-b292-fdb9c0dfb783)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.26 (64-bit)

### Severity impact

Low

### What platform are you seeing the problem on?

Linux

**Comment by LeMoonStar** [comment]
Still the case on 1.0.1-a.17:

https://github.com/user-attachments/assets/c3dd4a59-7523-408d-90f8-e2f6e7d41646
