### ISSUE TITLE
All kinds of toolbar and extension issues on 1.0.2-b.5

### ISSUE THREAD

**Issue by trendespresso** [zen-browser/desktop#4086]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

After the browser auto-updated from b.2 to b.5 I'm experiencing all kinds of odd toolbar and extension behaviour.

Extensions, especially if pinned to the bottom of the tab column, often do not open but have their icon's background highlighted as if they are present, open, and in focus. Compact Mode also no longer works with neither the top address bar nor the side tab stack hiding after the cursor is moved outside the respective action area.

Also, when dragging pinned extensions from the top right of the address bar to the bottom left of the tab stack, the tab stack suddenly gets much wider, showing a snippet of each tab's title. However if the Settings are opened and the Look & Feel -> Browser Layout is toggled then the tab stack again shrinks to the expected icon-only size. Very unexpected behaviour.

Video of all of the above: https://vimeo.com/1043032246?share=copy

Is there a way to downgrade?

EDIT: I think this issue is related to Compact Mode. Just now I reset the entire Toolbar (via Right Click -> "Customise Toolbar..." -> Restore Defaults button) and slowly went step by step. There were no functionality issues opening the extensions until Compact Mode was enabled. The only aesthetic issue was the left side tab bar expanding in size when extensions are dragged into it, requiring the Settings -> Look & Feel -> Browser Layout toggling to rectify. Still, functionally the browser is fine. It's only when Compact Mode is subsequently enabled that extensions freeze and refuse to open.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.5

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by mr-cheffy** [comment]
This has been fixed in b6, thanks!
