### ISSUE TITLE
Compact non-vertical tabs

### ISSUE THREAD

**Issue by Stryxus** [zen-browser/desktop#409]
### What feature would you like to see?

I would like to see an option to have the tabs on the top bar but, inspired by the style Safari's compact mode provides. I am not particularily a fan of vertical tabs, now am I a fan of any kind of side bar which, vertical tabs needs.

### What platform are you seeing the problem on?

Windows

### Additional context

It would also be great if we had options to individually or/and globally set it so. The selected tab showing the page title and when you click on that tab, the search bar and current URL shows up within that tab.

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/846

 ~ This is an automatic operation to better enhancements requests organization.
