### ISSUE TITLE
Vertical space added to extensions' windows opened from toolbar

### ISSUE THREAD

**Issue by ruvenistan** [zen-browser/desktop#4090]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Vertical space is added to the top of extensions' windows such as Bitwarden, and uBlock Origin when they are opened from toolbar. The added space increases each time the extension is opened, such that the extension display info is pushed down the screen and cannot be accessed. The space can't be removed. It resets once the browser is restarted, but will increment again if the extension is re-opened.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.4 (Firefox 133.0.3) (64-bit)

### What platform are you seeing the problem on?

Linux

**Comment by syscat29** [comment]
This was fixed in 1.0.2-b.5
