### ISSUE TITLE
Mozilla Sync

### ISSUE THREAD

**Issue by LilaUraraka** [zen-browser/desktop#4091]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I have been having consistent issues with the sync, random, disconnects for no discernible reason, disconnecting when I go to look at my account page, and getting locked out of my account, causing me to not be able to sign in on any device. This has been an issue for a few updates now, and is a huge problem, especially for those who use sync daily. these screenshots are a few of what I am experiencing
![2024-12-12 14_28_31-](https://github.com/user-attachments/assets/333da8bf-63a1-450e-a252-e3185641531b)
![2024-12-31 00_55_33-Settings — Zen Browser](https://github.com/user-attachments/assets/006d623a-075f-4783-a4de-fbeda6c6f81a)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.5

### What platform are you seeing the problem on?

Windows

**Comment by syscat29** [comment]
Can you try creating a new profile and seeing if the issue persists? May sound weird but sometimes the profiles bug and weird stuff happens. I've recently installed zen many times and my sync works just fine, no disconnects or anything.

**Comment by LilaUraraka** [comment]
Worked perfectly

**Comment by luke-monroe** [comment]
Hard to tell if this is a Firefox thing or a Zen thing. What all are you backing up?

**Comment by syscat29** [comment]
Just the defaults, seeing as this was resolved i'm closing the issue.

![image](https://github.com/user-attachments/assets/ed66d8a7-f04b-4e3b-9633-1a84a057fe10)
