### ISSUE TITLE
Location bar is not focused when opening new window

### ISSUE THREAD

**Issue by eseiker** [zen-browser/desktop#414]
### What happened?

Opening new tab automatically focuses location bar, but on new window, it doesn't.
I consider it's a bug while the behavior should be aligned opening a tab whether on same window or new window,
Firefox does focus location bar when opening new window.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.27

### Severity impact

Low

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by mauro-balades** [comment]
This is now fixed for the next release!

**Comment by Oddward** [comment]
Does it actually focus the search bar on new tab? I just moved from Win 10 to Win 11 (new device) and neither of them have the text areas focused on new tabs, I always have to manually click it before being able to type

**Comment by Nebula-Developer** [comment]
When opening a new window (arch/hyprland) in 1.7.4b, the address bar does not focus when opening the window, but does when making a new tab. Is there a setting that I am missing?
