### ISSUE TITLE
Per window compact mode

### ISSUE THREAD

**Issue by iskaa02** [zen-browser/desktop#415]
### What feature would you like to see?

currently if compact mode is enabled on one window all other window will be enabled. compact mode should be manager by each window separately   

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/844

 ~ This is an automatic operation to better enhancements requests organization.
