### ISSUE TITLE
Better indication of private browsing window

### ISSUE THREAD

**Issue by eseiker** [zen-browser/desktop#416]
### What feature would you like to see?

It's hard to recognize whether it's private mode or not without an indicator.
![image](https://github.com/user-attachments/assets/f694806b-2258-4fb0-ba06-8c8976c15cea)

Most browsers with private browsing/incognito mode including Firefox show indicator icon on titlebar/toolbar or different colors on their private window, and I'd appreciate to see it also on Zen to find out which window is in private mode or not easily.
![image](https://github.com/user-attachments/assets/c4e6dff6-578c-489d-8c79-7b8da4190b6a)
![image](https://github.com/user-attachments/assets/da54b318-a604-4a7e-a28b-2973a4690d51)
![image](https://github.com/user-attachments/assets/52393baa-33c9-4872-80a6-7f31c83cb754)

### What platform are you seeing the problem on?

macOS

**Comment by eseiker** [comment]
I'm temporarily using this theme now
https://www.zen-browser.app/themes/58649066-2b6f-4a5b-af6d-c3d21d16fc00
https://github.com/danm36/zen-browser-private-browsing-toolbar-highlighting

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/843

 ~ This is an automatic operation to better enhancements requests organization.
