### ISSUE TITLE
Configurable address bar click behaviour

### ISSUE THREAD

**Issue by tusooa** [zen-browser/desktop#418]
### What feature would you like to see?

I want the cilck behaviour of the address bar to be configurable.

Namely, for {single,double,triple} clicks, make each of the following configurable:
- whether it selects all
- whether the selection is copied into primary selection (if the platform has one)

See https://blog.tusooa.xyz/2020/10/01/Fix-firefox-address-bar-clickSelectsAll-bug/ , which describes the configuration that:
- single click does not select all, selection not copied
- double click selects all, selection not copied
- triple click selects all, selection copied

### What platform are you seeing the problem on?

Linux

### Additional context

Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1621570 , which they refuse to fix.

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/842

 ~ This is an automatic operation to better enhancements requests organization.
