### ISSUE TITLE
A post of appreciation for all the cool devs maintaing and building this project!

### ISSUE THREAD

**Issue by greed-d** [zen-browser/desktop#419]
### What feature would you like to see?

Let me tell you about me, I'm an avid browser fan. I have tried every fork and every browser out there that is meant for customization, heck I've even tried dabbling into customizing firefox myself but nothing feels as cohesive and customizable as this one for a firefox fork. vivaldi is there with it's all bells and whistles but I don't like chromium so I've kinda strayed away from chromium forks

On the note, Zen is an amazing browser, the amount of customization provided may not be much in alpha stage but the cohesiveness is there which I felt is a great factor on browsing experience, the theme ecosystem is also great and as a guy who uses sidebar instead of horizontal tabs this is heaven ( although sometimes I miss the tree style tabs but meeh ). I see lots of promise in this project and would love to donate but international payment is very very hard from where I am.

I hope this project keeps on going, while adding more features and it's cohesiveness, once again kudos to devs

### What platform are you seeing the problem on?

Linux

**Comment by n7itro** [comment]
Make sure to join the Discord so you can personally express your gratitude to the developer!
