### ISSUE TITLE
Need to hover to absolute top of screen to show the address bar in compact bar

### ISSUE THREAD

**Issue by greed-d** [zen-browser/desktop#420]
### What feature would you like to see?

When using compact mode the sidebar shows pretty fast before going to the absolute edge to the screen, but same cannot be said for the address bar, I have to hover nearly to the border to show the address bar, is there an option to change this behavior on when to show address bar?

### What platform are you seeing the problem on?

Linux

### Additional context

https://github.com/user-attachments/assets/1f17836c-da74-4f0a-949a-b8420234f0e1

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/841

 ~ This is an automatic operation to better enhancements requests organization.
