### ISSUE TITLE
Arc style spaces

### ISSUE THREAD

**Issue by arian81** [zen-browser/desktop#421]
### What feature would you like to see?

Arc spaces are the only featur that I find missing from every other browser and since zen seems to be perfect candidate to bring that feature to open source world.

### What platform are you seeing the problem on?

macOS

**Comment by NOCanoa** [comment]
Isn't this the Workspaces feature, already implemented? Or do I mean the styling to switch between them?

**Comment by arian81** [comment]
> Isn't this the Workspaces feature, already implemented? Or do u mean the styling to switch between them?

Yes I was looking for similar styling and ergonomics.
