### ISSUE TITLE
Suggestions for toggling the space feature

### ISSUE THREAD

**Issue by ydivho12123** [zen-browser/desktop#422]
### What feature would you like to see?

Now the space switch needs to click to open a secondary menu to switch, and the embarrassing thing is,When using zen mode is to hide the side tab bar,Click to switch the secondary menu of the space,The sidebar will be directly hidden,And after the switch, it will pop up abruptly,This feeling is very discordant。

I hope you can add a toggle button,Add a new way like arc browser that directly displays all the space on the sidebar,Click to switch the space directly,Instead of opening a secondary menu,Of course, the original method can also be retained,Just add a toggle switch,Some people may prefer this secondary menu way。

At the same time, there is also a suggestion that when the hidden sidebar function is turned on, open the secondary menu of space switching and right-click the tab to open the secondary menu, do not hide the sidebar, which is very unintuitive.

Another commendable aspect is that the zen browser puts the switch space on the top, which is very scientific, because the fixed tab and the top tab are the most commonly used, the mouse will often move to the top of the sidebar to switch, and the switch space is also the most commonly used, the mouse can easily click on the most commonly used things at the top of the sidebar.

The arc browser places the switch space at the bottom of the sidebar, and you have to move back and forth between the top and bottom of the sidebar repeatedly, which is really the opposite of failure

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/840

 ~ This is an automatic operation to better enhancements requests organization.
