### ISSUE TITLE
Gentoo's Firefox Patches

### ISSUE THREAD

**Issue by ThousandDemonDaggers** [zen-browser/desktop#423]
### What feature would you like to see?

Zen should also add Gentoo's Firefox patches like [Cachy Browser](https://github.com/CachyOS/CachyOS-Browser-Settings) already does.

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/839

 ~ This is an automatic operation to better enhancements requests organization.
