### ISSUE TITLE
Virustotal flags the latest windows executable as potential malware 

### ISSUE THREAD

**Issue by CharlesBlue** [zen-browser/desktop#424]
### What happened?

Hi, I'm new to GitHub so please forgive me if my bug report isn't perfect.

When I downloaded the Zen-browser windows installer executeable, it was flagged as potential malware by Bkav Pro
W32.AIDetectMalware. 

With it being only 1 our of 56 engines used it is my experience that this is highly likely a false positive, but it may be a bit offputting for users who don't know much about the project & were on the fence about trying it out. 

This could cause new users to avoid installing the browser as they might see it as a security risk. 

![image](https://github.com/user-attachments/assets/85054f4a-2f32-436d-b8ea-c0188aadcead)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.26

### Severity impact

Low, Medium

### What platform are you seeing the problem on?

Windows

**Comment by NOCanoa** [comment]
And we are looking at the Win/Mac licenses so this will happen even less

**Comment by lin-zaw112** [comment]
Now Avira also flag as malware. 
I wanna check the product but I felt unsafe looking at this
![Screenshot 2024-08-24 074651](https://github.com/user-attachments/assets/f0a73482-2417-4a66-9524-7956c2cc93be)

**Comment by NOCanoa** [comment]
> Now Avira also flag as malware. 

I personally think avira is malware xP
