### ISSUE TITLE
Way to restore native theming to toolbar

### ISSUE THREAD

**Issue by ch4og** [zen-browser/desktop#426]
### What feature would you like to see?

Since `#navigator-toolbox` in zen-browser-ui.css is set to `transparent !important`, the native firefox toolbar theming does not work in Zen browser. If you uncheck this property, everything works as expected.

I wasn’t able to override this property with css since it’s set to `!important`

I would like to have a way to restore firefox theming

![D098ED1C-22C8-4D5C-A1FB-6F011817AACA](https://github.com/user-attachments/assets/2c0225ff-9dbc-49d4-985f-005f6299d937)
![E620CCEC-F0F2-436A-B1EA-5B8E2D1C8A44](https://github.com/user-attachments/assets/e6b2f9d3-6130-4155-a260-35c048c8c4fd)

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
Fixed for the next release

**Comment by mauro-balades** [comment]
It will still be `transparent !important` but you can now specify `--zen-navigator-toolbox-background` to change it.
