### ISSUE TITLE
Last-active tab focus when switching workspaces

### ISSUE THREAD

**Issue by bartenalles** [zen-browser/desktop#427]
### What feature would you like to see?

Current Behavior (v1.0.0-a.27):
When switching workspaces, Zen browser focuses on the first tab opened in that workspace.

Desired Behavior:
When switching workspaces, automatically focus on the last active tab in that workspace.

Rationale:
This would save time and hassle by not having to search for the last-used tab every time when switching workspaces.

### What platform are you seeing the problem on?

macOS

**Comment by kLabz** [comment]
Duplicate of #318

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/838

 ~ This is an automatic operation to better enhancements requests organization.
