### ISSUE TITLE
Tabs Not Appearing in Vertical Tab Bar 

### ISSUE THREAD

**Issue by albu-ali** [zen-browser/desktop#429]
### What happened?

![2024-08-22_12-18](https://github.com/user-attachments/assets/b68f57ff-4e8e-44ef-8410-68de01bc6956)
**Description:**

When opening new tabs, they do not appear in the vertical tab bar after a period of use. 

**Issue:**

- New tabs do not show up in the vertical tab bar.
- The vertical tab bar remains empty even after opening multiple tabs.

**Steps to Reproduce:**

1. Install the browser using Flatpak.
2. Open and use the browser with some add-ons enabled.
3. After a period of time, observe that new tabs start to not show on the vertical tab bar.

**Additional Information:**

- I have tried creating new profiles, but the issue reappears after one or two days.
- I have also tried disabling all add-ons manually and restarting the browser, but the problem still exists.
- When I disable all add-ons using the option in the `about:profiles` page, the issue is resolved. However, this solution is not useful for me as it disables all add-ons.
- This bug, along with the lack of an option to switch to horizontal tabs, makes me frequently switch back to other browsers like floorp.

**Add-ons Used:**

- NoScript
- uBlock Origin

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.26 (64-bit)

### Severity impact

High

### What platform are you seeing the problem on?

Linux

**Comment by NOCanoa** [comment]
Does the problem still happen I I only use Ublock and remove NoScript?

**Comment by albu-ali** [comment]
Yes, I try to disable both the Ublock and Noscript as I said above manual, the problem still happen even if I disable them
But when I disable add-ons with the option in about:profiles page the browser work without any issue!!!

**Comment by mauro-balades** [comment]
hm..

**Comment by gunir** [comment]
> But when I disable add-ons with the option in about:profiles page the browser work without any issue!!!

Interesting part, we should take note about this.

It looks like your Zen is corrupted, I think Disabling Addon using Restart with addons disabled also Clear Startup Cache of Zen, which solves your issue.

You can manually do that by:
- Opening `about:support`
- Clear Startup Cache

**Comment by albu-ali** [comment]
That's was smart, but didn't work. The issue still exist!

**Comment by albu-ali** [comment]
> It looks like your Zen is corrupted, I think Disabling Addon using Restart with addons disabled also Clear Startup Cache of Zen, which solves your issue.
I thought this would solve the issue, because it makes perfect sense

**Comment by Romaixn** [comment]
I have the same problem in Linux, after the latest update. Before all working great! I deleted all extensions but the problem persist.

**Comment by mauro-balades** [comment]
I think i've fixed it, for the next update 👍🏽  Fell free to reopen if the problem persists after updating

**Comment by albu-ali** [comment]
> I think i've fixed it, for the next update 👍🏽 Fell free to reopen if the problem persists after updating

Great!
 
Keep up the awesome work!

**Comment by albu-ali** [comment]
> I have the same problem on Linux, after the latest update. Before all working great! I deleted all extensions but the problem persists.

If you are OK with using the browser without add-ons just create new profile or go to the about:profiles page and run the browser without any add-on from there! 

Or maybe you can wait for the next update! it look like they fix the issue

**Comment by Romaixn** [comment]
It's fixed! Thanks @mauro-balades, it was very fast 🚀

**Comment by erhardtjoel** [comment]
I am having this same issue now with the most recent update.
