### ISSUE TITLE
Address bar icons hidden in a.27

### ISSUE THREAD

**Issue by XanderHess** [zen-browser/desktop#430]
### What happened?

With the latest update quite a few address bar icons - like the star to add/remove a bookmark for the current website - have been hidden by default. This also affects icons provided by addons like [Reload in Address Bar](https://addons.mozilla.org/en-US/firefox/addon/reload-in-address-bar/).

While I understand the idea of the "Zen" part meaning to show as little clutter as possible on the screen, I personally feel this is a usability downgrade.

Maybe we could have a toggle to switch between hiding the icons like it is currently, showing the icons like it was before the update and showing them only when hovering over the address bar.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0 a.27

### Severity impact

Medium

### What platform are you seeing the problem on?

Windows

**Comment by n7itro** [comment]
> While I understand the idea of the "Zen"

For the record, this is not intended

**Comment by mauro-balades** [comment]
Do these icons disappear always or just on `about:` pages?

**Comment by XanderHess** [comment]
> Do these icons disappear always or just on `about:` pages?

It happens on all pages that I have tested so far.

**Comment by IZxMD** [comment]
![image](https://github.com/user-attachments/assets/5a9dce83-2229-4fbc-b4f4-3331ebc6eb62)
Can confirm 1.0.0-a.27 (Non generic)

Windows 11 23H2, Build 22631.4037

**Comment by mauro-balades** [comment]
Fixed with https://github.com/zen-browser/desktop/commit/cf2435081ab7b17510a996690f0f45794daf4ff1, thanks!
