### ISSUE TITLE
Can't select another language

### ISSUE THREAD

**Issue by trump2583** [zen-browser/desktop#431]
### What happened?

![图片](https://github.com/user-attachments/assets/27203c28-e294-4ef9-98c0-05a5939188a8)
win 10
Version：1.0.0-a.27

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.27

### Severity impact

Medium

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
Translations are done yet 👍🏽
