### ISSUE TITLE
problem with udemy video playback

### ISSUE THREAD

**Issue by hesham-ayad** [zen-browser/desktop#433]
### What happened?

Video playback on Udemy is slower and more stuttery  than on Mozilla Firefox by a very significant margin, and when I skip ahead or back in the video it can seize up and the video stops but audio is still playing normally.

But on Mozilla Firefox Udemy's video playback is smooth and no hang ups when I skip ahead or back.

flatpak v1.0.0 | Ubuntu 24.04 LTS | gnome v.46 | wayland | Dell Inc. Latitude E5440

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0

### Severity impact

Medium

### What platform are you seeing the problem on?

Linux

**Comment by NOCanoa** [comment]
what is the version 1.0.0-a25(example) ?

**Comment by hesham-ayad** [comment]
I installed through software application.
1.0.0-a.15

**Comment by NOCanoa** [comment]
have u update? we are at a27

**Comment by hesham-ayad** [comment]
It seems 1.0.0-a.15 is latest version according to ubuntu software application.
![image](https://github.com/user-attachments/assets/13be83a4-d8dc-430b-88b2-fe993a361043)

**Comment by NOCanoa** [comment]
is it flatpak?

**Comment by hesham-ayad** [comment]
yep

**Comment by hesham-ayad** [comment]
It's 1.0.0-a.27 (64-bit)

**Comment by IZxMD** [comment]
Windows seems to be not in Scope of this Problem.
Win 23H2
Version a.27

udemy skipping, etc. works smooth.

**Comment by pc-v2** [comment]
I have problem with course video, some of the topics is loaded, some of other topics not

**Comment by NotBestLord** [comment]
I have this problem in most playbacks.
I use Linux flatpak, v 1.0.0-a.28

**Comment by shahtufail117** [comment]
Same here. Udemy Videos not playing on my Windows Latest as of date, with the latest browser, also tried Troubleshooting Mode and Reported the site. Videos not Streaming or playing, works on firefox 130 latest stable as of date.

**Comment by mohvn** [comment]
Udemy uses DRM content, that's why it's not working, it's explained here https://docs.zen-browser.app/faq#why-cant-zen-browser-play-drm-protected-content
