### ISSUE TITLE
Incredibly slow start when opening browser.

### ISSUE THREAD

**Issue by PushaG** [zen-browser/desktop#441]
### What happened?

Other browsers launch instantaneously while Zen takes more than 5 seconds just to open. Happens on latest version as well on previous versions.

https://github.com/user-attachments/assets/319f3856-608d-4574-af07-9b62fbbb677f

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.27

### Severity impact

Medium

### What platform are you seeing the problem on?

Windows

**Comment by vegaskyo** [comment]
> Are you sure it's not windows defender?

same here. what do you mean? So I need to disable windows defender?

**Comment by ch4og** [comment]
Add browser to exclusions of windows defender and it will start much faster

**Comment by PushaG** [comment]
> Are you sure it's not windows defender?

Can confirm that after adding exclusion in Windows defender the browser opens much faster. As far as i'm concerned issue is fixed.

**Comment by NOCanoa** [comment]
Noice, btw how did u do thay to the bottom bar?

**Comment by 4NXIE7Y** [comment]
> Are you sure it's not windows defender?

I can confirm the browser opening speed slowdown when not included in the Windows Defender exclusion list.
But excluding it won't be a security risk?

**Comment by ch4og** [comment]
> But excluding it won't be a security risk?

You always can compile from source if you don't trust binaries provided by developers (I don't think it's a case for anyone)

**Comment by nolombic** [comment]
I'm also experiencing EXTREMELY slow startups of Zen (over 90s).

I'm on Ubuntu 24.10 with Zen 1.0.2-b.4 (flatpak).

Default Firefox starts up just as one would expect.

I'm suspecting Zen might be becoming exponentially slower and slower to start up with the amount of workspaces you have (in my case 4 with custom container tab groups assigned to them).

[Bildschirmaufzeichnung vom 2024-12-24 16-13-29.webm](https://github.com/user-attachments/assets/291530c2-50bd-4ea1-8525-ebdf5e50b7b4)

Update now that the flatpak version is on 1.6: Issue fixed.
