### ISSUE TITLE
Make mouse back button close tab when unable to go back 

### ISSUE THREAD

**Issue by damian-ds7** [zen-browser/desktop#442]
### What feature would you like to see?

Currently, when I open a new tab or open a link in a new tab, pressing the back button has no effect. It would be a helpful feature to allow users to easily close tabs without needing to move the cursor to the tab bar.

### What platform are you seeing the problem on?

Linux

**Comment by legendboyAni** [comment]
closing a tab by pressing back button is not good it's gonna cause way more problem then it solves that's why no browser do that

**Comment by damian-ds7** [comment]
Arc does I'm pretty sure, although I used it for a day so not 100%.

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/835

 ~ This is an automatic operation to better enhancements requests organization.
