### ISSUE TITLE
Provide a simple way to close tabs when vertical tabs just show icons

### ISSUE THREAD

**Issue by theuser18** [zen-browser/desktop#443]
### What feature would you like to see?

Currently, when the sidebar is configured to only show icons, there is no way to close tabs without right clicking and selecting close from the list of options.

A more elegant solution might be to have an 'x' pop up on the top right of each tab icon.

### What platform are you seeing the problem on?

Linux

**Comment by bdbch** [comment]
Brave is doing something similar:

![image](https://github.com/user-attachments/assets/40f47e9d-5a6b-47d4-8a2a-f1d1830dea14)

**Comment by chriskirknielsen** [comment]
I'm very used to closing via that button in Firefox, and very lazy to use the keyboard shortcut, so much so that in Zen, I currently prefer to right-click a tab to close it instead.

It's a delicate balance with tabs that might be playing audio though… could be good to have a small popout with those controls but where does it go? Over other tabs in the Y axis, over the tab content on the X axis? 🤔

**Comment by sladiri** [comment]
I usually close tabs by middle-click. Works fine on Windows at least.

**Comment by codenius** [comment]
> I usually close tabs by middle-click. Works fine on Windows at least.

Providing double click as an option to close a tab would be great too. Especially on a laptop touch pad it is much more convenient than emulating middle click via three finger click.
It is offered this way in Vivaldi.

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/834

 ~ This is an automatic operation to better enhancements requests organization.

**Comment by NXSec** [comment]
Having a small pop up/hover menu would be nice. You could have a few minimal icons that could include Close tab, split/duplicate to new tab/window, etc. Would be a very nice addition because I LOVE the compact tabs. They just make the browser look SO clean.

**Comment by Ophitoxaemia** [comment]
Add my vote for this.
