### ISSUE TITLE
Expanding Tabs on Hover Misaligns Mouse with Icons

### ISSUE THREAD

**Issue by theuser18** [zen-browser/desktop#445]
### What happened?

Currently, Expand Tabs on Hover expands the tab bar, but does not take into account the mouse location of the user. This results in the user trying to select a tab when unexpanded, just for the position of the tab icon to change when it expands.

See the below video where I try to select a few tabs, just for them to "bounce" out of the way.

https://github.com/user-attachments/assets/0e3f16f1-5ec4-41af-8b6b-b4d2a7d1c3e8

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.27 flatpak

### Severity impact

Medium

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
This has been reported before, thanks!
