### ISSUE TITLE
Show release notes after update

### ISSUE THREAD

**Issue by Arturro43** [zen-browser/desktop#446]
### What feature would you like to see?

Currently, after updating, Zen shows https://www.zen-browser.app/welcome

It would be nice to change that to https://www.zen-browser.app/release-notes/latest

### What platform are you seeing the problem on?

Linux

### Additional context

EndeavourOS w/ 6.10.2 kernel, `zen-browser-bin` installed & updated using `yay`

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/833

 ~ This is an automatic operation to better enhancements requests organization.
