### ISSUE TITLE
Change icon

### ISSUE THREAD

**Issue by Bazixv13** [zen-browser/desktop#447]
### What feature would you like to see?

Option to change the browser icon directly in app to the one of the [branding assets](https://www.zen-browser.app/branding-assets)

### What platform are you seeing the problem on?

Linux

**Comment by Donnnno** [comment]
It would be cool to see indeed. There are probably some limitations depending on the different operating systems that might make it more difficult than it sounds.

For the time being you should be able to download the icons and choose one of them manually for your setup :)

I'm working on creating downloadable packs for Windows and MacOS as well btw.
