### ISSUE TITLE
Avoid killing the app by killing the last tab

### ISSUE THREAD

**Issue by anispwyn** [zen-browser/desktop#448]
### What feature would you like to see?

in vivaldi, there is this features where pressing ctrl+w would kill a tab, when it reached the last tab, it wont kill it cuz killing it basically kill the entire app

while this may sound dumb, it would be really useful for someone who have compact mode and some vim binding extension enabled (which hide vertical tabs)

i sometimes killed the last tab and have to reopen the browser all the time

would be nice to see this implemented, thanks!

### What platform are you seeing the problem on?

Linux

**Comment by ThibautPV** [comment]
See : [https://github.com/zen-browser/desktop/pull/380](https://github.com/zen-browser/desktop/pull/380)  ?

**Comment by anispwyn** [comment]
hmm, seems like i forgor to check pr, thanks
