### ISSUE TITLE
Wrong Taskbar Icon

### ISSUE THREAD

**Issue by xii69** [zen-browser/desktop#449]
### What happened?

Hey, just installed Zen from AUR and when I open it the opened-windows icon is different from Zen's one as you can see in the screenshot:
![Screenshot_20240822_204815](https://github.com/user-attachments/assets/a4854497-f259-4cf2-a392-7127897499e5)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.27

### Severity impact

Enhancement

### What platform are you seeing the problem on?

Linux

**Comment by xii69** [comment]
Also I forgot to add that clicking on Zen application opens `zen-bin` which uses this weird icon

**Comment by zynexiz** [comment]
Have the same issue here. Also the original icon disappear when the app starts and get replaced with Wayland icon. I can't pin this to the taskbar.

**Comment by xii69** [comment]
> Have the same issue here. Also the original icon disappear when the app starts and get replaced with Wayland icon. I can't pin this to the taskbar.

I found a solution for it, but it should be fixed anyway
If you want to fix the icon edit the Zen's `zen-browser.desktop` located in `/home/xii69/.local/share/applications/zen-browser.desktop` (change the username to yours) and in the file change the `StartupWMClass=Zen Browser` to `StartupWMClass=zen-alpha`, if it doesn't take effect just reboot your pc once.

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/832

 ~ This is an automatic operation to better enhancements requests organization.

**Comment by justOtto** [comment]
Tanks @xii69, that worked fine ... until the update. But it's a quick fix, that can be fixed again ... hopefully not forever.

**Comment by odeemi** [comment]
RemotingName has changed to `zen-beta` in `application.ini`. Means that in `zen-browser.desktop` should now be `StartupWMClass=zen-beta`.
