### ISSUE TITLE
Add profile name to title of window when using multiple profiles

### ISSUE THREAD

**Issue by jawshoeadan** [zen-browser/desktop#450]
### What feature would you like to see?

Right now, I have two profiles, one named work and one named personal. However, they are a little annoying to keep track of since both the profiles look exactly the same in the dock. What I'm proposing is that the text here says "Zen Browser (Work)" or "Zen Browser (Personal)" to help distinguish the two. Ideally, these would maybe have a different color-coded icon, but I understand that is probably more work.

<img width="184" alt="Screenshot 2024-08-22 at 10 56 10 AM" src="https://github.com/user-attachments/assets/27b9e8a1-57f7-4fb5-b4b3-b0937a3c673d">
<img width="179" alt="Screenshot 2024-08-22 at 10 55 59 AM" src="https://github.com/user-attachments/assets/3816d511-3a94-46ee-a592-6954f6b173a8">

### What platform are you seeing the problem on?

macOS

**Comment by mokshsinghji** [comment]
maybe also could help if it has the icon of the profile on the taskbar/dock. (for example like something that chrome or edge does)

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/831

 ~ This is an automatic operation to better enhancements requests organization.
