### ISSUE TITLE
[Bug] Missing ZenAvatarPath in profiles.ini causes ProfileMissingDialog

### ISSUE THREAD

**Issue by timon-schelling** [zen-browser/desktop#454]
### What happened?

Starting with no `ZenAvatarPath` set in profiles.ini causes `ProfileMissingDialog`.
I would expect there to be a fallback or a default value that is loaded instead.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.27

### Severity impact

Medium

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
Well… You need to have the profile avatar, it's requred. Whats the issue exactly?

**Comment by timon-schelling** [comment]
In my opinion a value in a configuration that can have a reasonable fallback like `ZenAvatarPath` should not cause the browser to not start at all or at least inform the user what exactly went wrong.

I have two usecases that do not work because of this missing fallback.

1. Importing a existing firefox profile folder.
2. Configuring Zen Browser with existing tooling around firefox, like declarative firefox profiles with home-manager or other dotfile managers.

I can understand if you don't want to deal with firefox compatibility actively.
But I would argue that this should be changed regardless because it could also effect Zen users that changed somthing in there profiles.ini manually.

If you don't see this as an issue feel free to close this.

Thanks for working on Zen-Browser, really enjoy using it :)

**Comment by timon-schelling** [comment]
This is still relevant for me.

**Comment by salamijason** [comment]
Since non of the devs have paid any attention to this issue, I assume they see it as a non-issue and will not be fixing this. thank you for your input, though!
