### ISSUE TITLE
NordVPN File Protection blocking zen installer

### ISSUE THREAD

**Issue by nocategory** [zen-browser/desktop#455]
### What happened?

Was interested in trying out Zen, as a new user I did not expect this:
![image](https://github.com/user-attachments/assets/84f88309-4e4d-4cdf-8e77-fa37cc3a75d5)
Already tried googling the threat name and... yeah nothing. Don't think that has anything to do with signing keys?

I'm aware NordVPN isn't an actual antivirus but I just thought this was worth mentioning.

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

latest

### Severity impact

Medium

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
It's could be because the app is not signed, im working on it 👍🏽
