### ISSUE TITLE
The sidebar doesn't show any icons in full-screen mode

### ISSUE THREAD

**Issue by Donnnno** [zen-browser/desktop#456]
### What happened?

![image](https://github.com/user-attachments/assets/95631787-af3b-4cca-826f-90adeb12c525)

![image](https://github.com/user-attachments/assets/05c4baa2-a97f-45c3-ad38-214c420bde62)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

a27

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by KarimElsayad247** [comment]
@Donnnno does this issue still exist for you on the most recent version?

**Comment by Donnnno** [comment]
It has been resolved, thanks for the reminder!
