### ISSUE TITLE
scrollbar not flush with right edge of screen

### ISSUE THREAD

**Issue by darthoctopus** [zen-browser/desktop#457]
### What happened?

when using mouse buttons to scroll up and down a long page in a maximised window, one has to manually seek the location of the scrollbar on the right side of the viewport, which is offset from the right side of the screen, rather than being able to click on the scrollbar when the mouse cursor is positioned on the right edge of the screen.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.24

### Severity impact

Medium

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
None, this is a GUI issue
```

**Comment by IAmJafeth** [comment]
Hi @darthoctopus,

I can confirm this behavior, it can be improve in the future. 

As a workaround you can use the [No browser padding](https://www.zen-browser.app/themes/680424a8-a818-406b-98c5-7726214e2a9f) from the Zen's Theme Store, this should remove the offset on the right side of the screen leading to better experience using scrollbar with the mouse cursor.

**Comment by BramLeisink** [comment]
Duplicate to https://github.com/zen-browser/desktop/issues/1126
