### ISSUE TITLE
Unable to delete a workspace

### ISSUE THREAD

**Issue by stele95** [zen-browser/desktop#458]
### What happened?

Opening a workspace menu and selecting a delete workspace action on any workspace that is not a default workspace results in opening that workspace with just a new tab and in the background opens a new tab in the default workspace.

Not sure where the logs are located, I can provide them later when you let me know where I can look for them

Here is a screen recording of what's happening
https://github.com/user-attachments/assets/85a0133e-c8dd-43d2-a610-d6f28105c595

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.27 (64-bit) linux specific

### Severity impact

High

### What platform are you seeing the problem on?

Linux

**Comment by eymerich** [comment]
I can add that for me on windows, if you restart the browser and retry the deletion it completes successfully.

**Comment by stele95** [comment]
Interesting note, I had "Open previous windows and tabs" checked. After disabling that and restarting the browser, I was able to delete workspaces

**Comment by mauro-balades** [comment]
this is fixed for next release 👍🏽
