### ISSUE TITLE
New created workspace cannot be delete unless you first restart the browser

### ISSUE THREAD

**Issue by eymerich** [zen-browser/desktop#459]
### What happened?

- Create a new workspace
- Click on "Delete Workspace" option of the workspace (may it be the current or not)
Workspace is activated and tabs (if any) are removed then a new empty tab is created, but, the workspace is not removed

- Close Zen browser
- Reopen Zen browser
- Click on "Delete Workspace" option of the workspace (may it be the current or not)
Workspace is correctly deleted.

I'm expecting the workspace is removed as consequence of "Delete Workspace" without the need to restart the browser.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.27 (64-bit)

### Severity impact

Medium

### What platform are you seeing the problem on?

Windows

**Comment by stele95** [comment]
I reported [the same issue a few minutes before you](https://github.com/zen-browser/desktop/issues/458), but for me it's still happening even after I restart the browser

**Comment by eymerich** [comment]
I'll close this in favor of your :)
