### ISSUE TITLE
Tabs won't Appear after Zen Crashed.

### ISSUE THREAD

**Issue by Ain-Dont-code** [zen-browser/desktop#460]
### What happened?

While I was trying to Sign in youtube the Browser Crashed, previously I had compact mode enable, when I open it again, tabs just wouldn't appear when houver my mouse over the left corner , that's when I notice that for some reason the compact tab menu was in top left corner in the screen and that I could only see and select the option menu in my screen.

![ZEN](https://github.com/user-attachments/assets/ab71768d-604e-45ba-be70-e53fc83aa271)

I apologize for the bad quality, after observing that I selected the option buttom and turned off the compact tab menu off and when I did that the tab menu was completly empty despite the fact I knew that twitter/X was open.

![Captura de tela 2024-08-22 192203](https://github.com/user-attachments/assets/2e7d9834-f3c3-4b64-9e7f-9529681ae8d6)

I apoligize in advance if I am doing something wrong or explaining my issue poorly, that is my first time using Github.

edit: The issue still persiste even after I reset my computer. 

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.24

### Severity impact

Medium

### What platform are you seeing the problem on?

Windows

**Comment by IAmJafeth** [comment]
Hi @Ain-Dont-code,

This error should be fixed with the following change: e808443631697243488b18840ad46f680ef37a3d
It will be available on next release 1.0.0-a.28.

I will keep this issue opened until this version get released to confirm the fix

**Comment by mauro-balades** [comment]
This should be fixed now, long ago
