### ISSUE TITLE
Autoclick into address bar

### ISSUE THREAD

**Issue by Naigaru** [zen-browser/desktop#463]
### What feature would you like to see?

Would it be possible to make it so that the browser is automatically clicked into the address bar and ready to type when you open it?

### What platform are you seeing the problem on?

Windows

### Additional context

Had this on my last browser and was just convenient to go from clicking the mouse then getting ready to type while the browser loads, but currently have to click into the address bar with Zen.

**Comment by Naigaru** [comment]
I am like 99% sure that the browser just updated like 2 hours ago and added / fixed this, so nevermind lol, thank you :)

**Comment by mauro-balades** [comment]
👍🏽
