### ISSUE TITLE
Disable animations

### ISSUE THREAD

**Issue by vunhatchuong** [zen-browser/desktop#465]
### What feature would you like to see?

I want an option to disable animations. Animations sometimes can be annoying and reducing performance cost is a good thing.

### What platform are you seeing the problem on?

Linux

**Comment by InspoOnU** [comment]
Same here. Could just follow Windows/macOS system settings like Firefox.

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/830

 ~ This is an automatic operation to better enhancements requests organization.
