### ISSUE TITLE
AppImage update option

### ISSUE THREAD

**Issue by eboye** [zen-browser/desktop#466]
### What feature would you like to see?

I would like to be able to update Zen installed as an AppImage without checking on the website. I know some AppImage apps have this option.

![image](https://github.com/user-attachments/assets/23ea4817-a7fd-41fc-8394-0f38e516579d)

It says that "Updates disabled by your organization"

And GearLevel doesn't notify me of new versions for some reason

![image](https://github.com/user-attachments/assets/878c37a6-2586-4b23-bf73-b4cdf96a7fc2)

### What platform are you seeing the problem on?

Linux

### Additional context

`Linux stupid-dragon 6.10.6-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 19 Aug 2024 17:02:39 +0000 x86_64 GNU/Linux`

**Comment by Samueru-sama** [comment]
Zen already has the zsync file released that lets you update it with [appimageupdate](https://github.com/AppImageCommunity/AppImageUpdate), which is the intended way for appimages to update. 

You can also use [AM](https://github.com/ivan-hc/AM) and simply do `am -i zen-browser` or `appman -i zen-browser`

**Comment by eboye** [comment]
@Samueru-sama thanks, didn't know about that one.
