### ISSUE TITLE
Very unclear as to how to use split view or how to select multiple tabs

### ISSUE THREAD

**Issue by SomeDudeBrosky** [zen-browser/desktop#47]
You have to do multiple steps, none of which are explained, and it is more time-consuming to do than just opening 2 windows.

**Comment by labatts** [comment]
I found the shortcuts, but didn't know about the ctrl click on the tabs feature until I saw it on a YouTube video. I think it is a wonderful feature, but it IS hard to discover. I think a skip-able first launch tutorial would help immensely.
