### ISSUE TITLE
Create a Dockerfile for the project for it to start easily locally.

### ISSUE THREAD

**Issue by SahilSinghTomar** [zen-browser/desktop#470]
### What feature would you like to see?

Create a dockerfile for easy local setup.

### What platform are you seeing the problem on?

Windows

### Additional context

I can solve this issue

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/828

 ~ This is an automatic operation to better enhancements requests organization.
