### ISSUE TITLE
Add Support for Trackpad Gestures

### ISSUE THREAD

**Issue by gordoncheong** [zen-browser/desktop#471]
### What feature would you like to see?

Something I found to be very convenient from the Arc Browser is the ability to switch Workspaces by two-finger swipes inside the vertical tab bar region using the trackpad. This allows switching between Workspaces to be quicker and more intuitive on laptops. 

### What platform are you seeing the problem on?

Windows

**Comment by junedabat** [comment]
There's also trackpad gestures on Firefox to go to the previous page or the next page that I found to be quite handy.
For some reason it doesn't work on Zen

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/827

 ~ This is an automatic operation to better enhancements requests organization.
