### ISSUE TITLE
Spotify playback is not working

### ISSUE THREAD

**Issue by Naveenv01** [zen-browser/desktop#472]
### What happened?

When tried to use spottily web player in zen the playback is not working 

Im having a Ubuntu 24 04 system I'm using  zen with appImage binary 

![image](https://github.com/user-attachments/assets/fe0e92bd-ed31-43dc-a040-d1db42a1c358)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.28

### Severity impact

High, Critical

### What platform are you seeing the problem on?

Linux

**Comment by NOCanoa** [comment]
DRM issue, we can't do anything about it until we have a license (very expensive :/ ).

**Comment by Naveenv01** [comment]
Is that same why the YouTube live stream is not working? Because I'm not be able to play live stream on YouTube

**Comment by yashptel** [comment]
> DRM issue, we can't do anything about it until we have a license (very expensive :/ ).

Does that mean we could never have it? That's absurd. I hope those antitrust lawsuits are including this as well. Google pretty much has the power to never let someone build a better browser against their will it seems :(

**Comment by NOCanoa** [comment]
> > DRM issue, we can't do anything about it until we have a license (very expensive :/ ).
> 
> Does that mean we could never have it? That's absurd. I hope those antitrust lawsuits are including this as well. Google pretty much has the power to never let someone build a better browser against their will it seems :(

if we get a sponsor that can pay that 🤷‍♂️
