### ISSUE TITLE
Apple Silicon Version of Zen Browser.app Cannot Be Opened After Installation

### ISSUE THREAD

**Issue by nbinding** [zen-browser/desktop#473]
### What happened?

I encountered an issue with the Apple Silicon version of Zen Browser.app after downloading and attempting to install it. 

Here’s a detailed account of what happened:

1. I downloaded the Apple Silicon version of Zen Browser from the official release page.
2. I dragged the downloaded .app file into the Applications folder as instructed.
3. When I double-clicked the Zen Browser icon in the Applications folder to open it, I received an error message stating: "Zen Browser.app" is damaged and can't be opened. You should move it to the Trash."

This error prevents me from launching the application entirely.

**Steps to Reproduce:**

1. Download the Apple Silicon version of Zen Browser.
2. Drag the .app file into the Applications folder.
3. Attempt to open the application from the Applications folder.

**Expected Behaviour:**
The application should open without any errors and be ready to use.

**Actual Behaviour:**
An error message appears, indicating that the application is damaged and cannot be opened.

**System Information:**

- Device: Apple Silicon Mac (e.g., M1/M2)
- OS: 14.6.1 (23G93)
- Version of Zen Browser: Filename has no version number, downloaded from https://www.zen-browser.app/download as of 2024-08-23 10:04 BST

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

N/A

### Severity impact

High

### What platform are you seeing the problem on?

macOS - aarch64

### Relevant log output

```shell
N/A
```

**Comment by JonasMerxbauer** [comment]
Hi, you need to follow these steps for MacOS installation: [https://docs.zen-browser.app/guides/install-macos](https://docs.zen-browser.app/guides/install-macos). The issue is caused because the developers don't have Developer License from Apple yet to sign the app

**Comment by nbinding** [comment]
It might be worth popping something on the download page that there's a process to install(?)

**Comment by NOCanoa** [comment]
> It might be worth popping something on the download page that there's a process to install(?)

Already on there just most people just skip it, but  shouldn't be a problem for long we just waiting for apple to respond.
