### ISSUE TITLE
Crash, suspecting due to dual GPU

### ISSUE THREAD

**Issue by kimjongbing** [zen-browser/desktop#474]
### What happened?

Playing a video causes the browser to crash. Does not happen on regular Firefox. Regular Firefox sometimes crashes because it too has an issue with detecting if the 2nd GPU is VFIO bound, but does not crash immediately when playing a video like Zen Browser.

Extra info:
OS: CachyOS Linux x86_64
Kernel: Linux 6.10.5-2-cachyos
DE: GNOME 46.4
WM: Mutter (Wayland)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox. 

### Version

1.0.0.a.19-1

### Severity impact

Medium

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
Crash Annotation GraphicsCriticalError: |[0][GFX1-]: More than 1 GPU from same vendor detected via PCI, cannot deduce device
 (t=0.283485) [GFX1-]: More than 1 GPU from same vendor detected via PCI, cannot deduce device

^BdCrash Annotation GraphicsCriticalError: |[0][GFX1-]: More than 1 GPU from same vendor detected via PCI, cannot deduce device
 (t=0.283485) |[1][GFX1-]: Wayland protocol error: wp_linux_drm_syncobj_surface_v1#58: error 3: Release or Acquire point set but no buffer attached
 (t=607.31) [GFX1-]: Wayland protocol error: wp_linux_drm_syncobj_surface_v1#58: error 3: Release or Acquire point set but no buffer attached

Exiting due to channel error.
Exiting due to channel error.
Crash Annotation GraphicsCriticalError: |[C0][GFX1-]: CompositorBridgeChild receives IPC close with reason=AbnormalShutdown (t=263.765) Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Crash Annotation GraphicsCriticalError: |[C0][GFX1-]: CompositorBridgeChild receives IPC close with reason=AbnormalShutdown (t=606.648) [GFX1-]: CompositorBridgeChild receives IPC close with reason=AbnormalShutdown
Exiting due to channel error.
fish: Job 1, 'zen-browser' terminated by signal SIGSEGV (Address boundary error)
```

**Comment by kimjongbing** [comment]
For comparison (and maybe it will help) if Firefox crashes (not Zen) this is the type of output I get:
`
AdapterDeviceID: NVIDIA GeForce RTX 4070 Ti/PCIe/SSE2
AdapterDriverVendor: nvidia/unknown
AdapterDriverVersion: 560.31.2.0
AdapterVendorID: 0x10de
Add-ons: %7B446900e4-71c2-419f-a6a7-df9c091e268b%7D:2024.7.1,uBlock0%40raymondhill.net:1.59.0,chrome-gnome-shell%40gnome.org:12,%7B6b733b82-9261-47ee-a595-2dda294a4d08%7D:24.8.12.1,sponsorBlocker%40ajay.app:5.7,%7B2e5ff8c8-32fe-46d0-9fc8-6b8986621f3c%7D:7.1.0,%7Bc84d89d9-a826-4015-957b-affebd9eb603%7D:0.10.4,%7Ba6c4a591-f1b2-4f03-b3ff-767e5bedf4e7%7D:0.5.0,%40clipboard-inserter:0.3.3resigned1,firefox-extension%40steamdb.info:4.5,%7B60f82f00-9ad5-4de5-b31c-b16a47c51558%7D:0.5rc2,firefoxpwa%40filips.si:2.12.1,2.0%40disconnect.me:20.3.1.2,gsconnect%40andyholmes.github.io:8,firefox%40tampermonkey.net:5.1.1,zotero%40chnm.gmu.edu:5.0.144,%7B84cbda23-345f-4e74-9695-9a52b9599dc0%7D:4.10.4,formautofill%40mozilla.org:1.0.1,pictureinpicture%40mozilla.org:1.0.0,webcompat%40mozilla.org:129.5.0,addons-search-detection%40mozilla.com:2.0.0,google%40search.mozilla.org:1.5,wikipedia%40search.mozilla.org:1.4,bing%40search.mozilla.org:1.7,ddg%40search.mozilla.org:1.5,firefox-compact-light%40mozilla.org:1.2
AvailablePageFile: 37195714560
AvailablePhysicalMemory: 11177381888
AvailableSwapMemory: 33043247104
AvailableVirtualMemory: 26882920448
BackgroundTaskMode: 0
BuildID: 20240814152237
ContentSandboxCapabilities: 119
ContentSandboxCapable: 1
ContentSandboxLevel: 4
CrashTime: 1724404892
DOMFissionEnabled: 1
DOMIPCEnabled: 1
DesktopEnvironment: gnome
EMCheckCompatibility: true
GpuSandboxLevel: 0
GraphicsCriticalError: |[0][GFX1-]: More than 1 GPU from same vendor detected via PCI, cannot deduce device
 (t=0.266718) 
GraphicsNumActiveRenderers: 2
GraphicsNumRenderers: 1
HeadlessMode: 0
InstallTime: 1723921657
IsWayland: 0
LastStartupWasCrash: 0
LinuxUnderMemoryPressure: 0
Notes: CachyOSFP(D00-L1000-W0000000-T01) Has dual GPUs.WR! WR+ EGL? EGL- GL Context? GL Context+ 
ProductID: {ec8030f7-c20a-464f-9b0e-13a3a9e97384}
ProductName: Firefox
RDDProcessStatus: Running
ReleaseChannel: release
SafeMode: 0
SecondsSinceLastCrash: 2220
StartupCacheValid: 1
StartupCrash: 0
StartupTime: 1724404588
SubmittedFrom: Client
TelemetryClientId: aaa103b9-1a7f-4836-aa62-cff4d92375ac
TelemetryEnvironment: {"build":{"applicationId":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","applicationName":"Firefox","architecture":"x86-64","buildId":"20240814152237","version":"129.0.1","vendor":"Mozilla","displayVersion":"129.0.1","platformVersion":"129.0.1","xpcomAbi":"x86_64-gcc3","updaterAvailable":false},"partner":{"distributionId":"archlinux","distributionVersion":"1.0","partnerId":null,"distributor":"archlinux","distributorChannel":"firefox","partnerNames":["archlinux"]},"system":{"memoryMB":32042,"virtualMaxMB":null,"cpu":{"count":16,"cores":8,"vendor":"AuthenticAMD","name":"AMD Ryzen 7 3700X 8-Core Processor","family":23,"model":113,"stepping":0,"l2cacheKB":512,"l3cacheKB":16384,"speedMHz":4426,"extensions":["hasMMX","hasSSE","hasSSE2","hasSSE3","hasSSSE3","hasSSE4A","hasSSE4_1","hasSSE4_2","hasAVX","hasAVX2","hasAES"]},"os":{"name":"Linux","version":"6.10.5-2-cachyos","locale":"en-US","distro":"Cachyos","distroVersion":"rolling"},"hdd":{"profile":{"model":null,"revision":null,"type":null},"binary":{"model":null,"revision":null,"type":null},"system":{"model":null,"revision":null,"type":null}},"gfx":{"D2DEnabled":null,"DWriteEnabled":null,"ContentBackend":"Skia","Headless":false,"EmbeddedInFirefoxReality":null,"TargetFrameRate":240,"adapters":[{"description":"NVIDIA GeForce RTX 4070 Ti/PCIe/SSE2","vendorID":"0x10de","deviceID":"NVIDIA GeForce RTX 4070 Ti/PCIe/SSE2","subsysID":null,"RAM":0,"driver":null,"driverVendor":"nvidia/unknown","driverVersion":"560.31.2.0","driverDate":null,"GPUActive":true}],"monitors":[{"screenWidth":1920,"screenHeight":1080},{"screenWidth":1920,"screenHeight":1080},{"screenWidth":1920,"screenHeight":1080}],"features":{"compositor":"webrender","hwCompositing":{"status":"available"},"gpuProcess":{"status":"unused"},"webrender":{"status":"force_enabled"},"wrCompositor":{"status":"blocked:FEATURE_FAILURE_DISABLE_RELEASE_OR_BETA"},"openglCompositing":{"status":"available"},"omtp":{"status":"unused"}}},"appleModelId":null,"hasWinPackageId":null},"settings":{"blocklistEnabled":true,"e10sEnabled":true,"e10sMultiProcesses":8,"fissionEnabled":true,"telemetryEnabled":false,"locale":"en-US","intl":{"requestedLocales":["en-US"],"availableLocales":["en-US"],"appLocales":["en-US"],"systemLocales":["en-US"],"regionalPrefsLocales":["en-US"],"acceptLanguages":["en-US","en"]},"update":{"channel":"release","enabled":false,"autoDownload":false,"background":false},"userPrefs":{"browser.shell.checkDefaultBrowser":true,"browser.search.region":"AU","browser.search.widget.inNavBar":false,"browser.urlbar.autoFill":true,"browser.urlbar.autoFill.adaptiveHistory.enabled":false,"browser.urlbar.dnsResolveSingleWordsAfterSearch":0,"browser.urlbar.quicksuggest.dataCollection.enabled":false,"browser.urlbar.suggest.quicksuggest.nonsponsored":false,"browser.urlbar.suggest.quicksuggest.sponsored":false,"gfx.webrender.all":true,"media.gmp-gmpopenh264.lastInstallStart":1718606967,"media.gmp-gmpopenh264.lastDownload":1718606967,"media.gmp-gmpopenh264.lastUpdate":1718606967,"media.gmp-widevinecdm.lastInstallStart":1719560458,"media.gmp-widevinecdm.lastDownload":1719560460,"media.gmp-widevinecdm.lastUpdate":1719560460,"media.gmp-manager.lastCheck":1724343251,"media.gmp-manager.lastEmptyCheck":1724343251,"network.trr.strict_native_fallback":false,"signon.rememberSignons":false,"widget.content.gtk-high-contrast.enabled":true},"sandbox":{"effectiveContentProcessLevel":4,"contentWin32kLockdownState":3},"addonCompatibilityCheckEnabled":true,"isDefaultBrowser":true,"defaultSearchEngine":"google-b-d","defaultSearchEngineData":{"loadPath":"[app]google@search.mozilla.org","name":"Google","origin":"default","submissionURL":"https://www.google.com/search?client=firefox-b-d&q="}},"profile":{"creationDate":19891,"firstUseDate":19891},"addons":{"activeAddons":{"chrome-gnome-shell@gnome.org":{"version":"12","scope":1,"type":"extension","updateDay":19891,"isSystem":false,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"This extension provides integration with GNOME Shell and the corresponding extensions repository htt","name":"GNOME Shell integration","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19891,"signedState":2,"signedTypes":"[2,0]","quarantineIgnoredByApp":false,"quarantineIgnoredByUser":false},"{a6c4a591-f1b2-4f03-b3ff-767e5bedf4e7}":{"version":"0.5.0","scope":1,"type":"extension","updateDay":19891,"isSystem":false,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Spoof websites trying to gather information about your web navigation to deliver distinct content yo","name":"User-Agent Switcher and Manager","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19891,"signedState":2,"signedTypes":"[2,0]","quarantineIgnoredByApp":true,"quarantineIgnoredByUser":false},"@clipboard-inserter":{"version":"0.3.3resigned1","scope":1,"type":"extension","updateDay":19892,"isSystem":false,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"A simple addon that inserts clipboard contents into the page. Uses icon made by Google from www.flat","name":"Clipboard Inserter","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19892,"signedState":2,"signedTypes":"[2,0]","quarantineIgnoredByApp":false,"quarantineIgnoredByUser":false},"sponsorBlocker@ajay.app":{"version":"5.7","scope":1,"type":"extension","updateDay":19901,"isSystem":false,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Skip sponsorships, subscription begging and more on YouTube videos. Report sponsors on videos you wa","name":"SponsorBlock for YouTube - Skip Sponsorships","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19891,"signedState":2,"signedTypes":"[2,0]","quarantineIgnoredByApp":true,"quarantineIgnoredByUser":false},"{2e5ff8c8-32fe-46d0-9fc8-6b8986621f3c}":{"version":"7.1.0","scope":1,"type":"extension","updateDay":19905,"isSystem":false,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"A powerful reverse image search tool, with support for various search engines, such as Google, Bing,","name":"Search by Image","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19891,"signedState":2,"signedTypes":"[2,1]","quarantineIgnoredByApp":true,"quarantineIgnoredByUser":false},"{60f82f00-9ad5-4de5-b31c-b16a47c51558}":{"version":"0.5rc2","scope":1,"type":"extension","updateDay":19908,"isSystem":false,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"An addon to manage (view, search, create, edit, delete, backup, restore) cookies.","name":"Cookie Quick Manager","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19908,"signedState":2,"signedTypes":"[2,0]","quarantineIgnoredByApp":true,"quarantineIgnoredByUser":false},"firefoxpwa@filips.si":{"version":"2.12.1","scope":1,"type":"extension","updateDay":19913,"isSystem":false,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"A tool to install, manage and use Progressive Web Apps (PWAs) in Mozilla Firefox","name":"Progressive Web Apps for Firefox","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19913,"signedState":2,"signedTypes":"[2,0]","quarantineIgnoredByApp":false,"quarantineIgnoredByUser":false},"2.0@disconnect.me":{"version":"20.3.1.2","scope":1,"type":"extension","updateDay":19917,"isSystem":false,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Make the web faster, more private, and more secure.","name":"Disconnect","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19917,"signedState":2,"signedTypes":"[2,0]","quarantineIgnoredByApp":true,"quarantineIgnoredByUser":false},"gsconnect@andyholmes.github.io":{"version":"8","scope":1,"type":"extension","updateDay":19919,"isSystem":false,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Share links with GSConnect, direct to the browser or by SMS.","name":"GSConnect","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19919,"signedState":2,"signedTypes":"[2,0]","quarantineIgnoredByApp":false,"quarantineIgnoredByUser":false},"firefox@tampermonkey.net":{"version":"5.1.1","scope":1,"type":"extension","updateDay":19928,"isSystem":false,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Change the web at will with userscripts","name":"Tampermonkey","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19928,"signedState":2,"signedTypes":"[2,0]","quarantineIgnoredByApp":false,"quarantineIgnoredByUser":false},"firefox-extension@steamdb.info":{"version":"4.5","scope":1,"type":"extension","updateDay":19935,"isSystem":false,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Adds SteamDB links and new features on the Steam store and community. View lowest game prices and st","name":"SteamDB","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19896,"signedState":2,"signedTypes":"[2,1]","quarantineIgnoredByApp":false,"quarantineIgnoredByUser":false},"{446900e4-71c2-419f-a6a7-df9c091e268b}":{"version":"2024.7.1","scope":1,"type":"extension","updateDay":19935,"isSystem":false,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"At home, at work, or on the go, Bitwarden easily secures all your passwords, passkeys, and sensitive","name":"Bitwarden Password Manager","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19891,"signedState":2,"signedTypes":"[2,1]","quarantineIgnoredByApp":true,"quarantineIgnoredByUser":false},"uBlock0@raymondhill.net":{"version":"1.59.0","scope":1,"type":"extension","updateDay":19936,"isSystem":false,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Finally, an efficient blocker. Easy on CPU and memory.","name":"uBlock Origin","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19891,"signedState":2,"signedTypes":"[2,1]","quarantineIgnoredByApp":true,"quarantineIgnoredByUser":false},"formautofill@mozilla.org":{"version":"1.0.1","scope":1,"type":"extension","updateDay":19949,"isSystem":true,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":null,"name":"Form Autofill","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19884,"quarantineIgnoredByApp":true,"quarantineIgnoredByUser":false},"pictureinpicture@mozilla.org":{"version":"1.0.0","scope":1,"type":"extension","updateDay":19949,"isSystem":true,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Fixes for web compatibility with Picture-in-Picture","name":"Picture-In-Picture","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19884,"quarantineIgnoredByApp":true,"quarantineIgnoredByUser":false},"webcompat@mozilla.org":{"version":"129.5.0","scope":1,"type":"extension","updateDay":19949,"isSystem":true,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Urgent post-release fixes for web compatibility.","name":"Web Compatibility Interventions","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19884,"quarantineIgnoredByApp":true,"quarantineIgnoredByUser":false},"zotero@chnm.gmu.edu":{"version":"5.0.144","scope":1,"type":"extension","updateDay":19954,"isSystem":false,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Save references to Zotero from your web browser","name":"Zotero Connector","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19947,"signedState":2,"signedTypes":"[2,1]","quarantineIgnoredByApp":false,"quarantineIgnoredByUser":false},"{84cbda23-345f-4e74-9695-9a52b9599dc0}":{"version":"4.10.4","scope":1,"type":"extension","updateDay":19954,"isSystem":false,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"An extension for checking if .git is exposed in visited websites","name":"DotGit","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19954,"signedState":2,"signedTypes":"[2,1]","quarantineIgnoredByApp":false,"quarantineIgnoredByUser":false},"{6b733b82-9261-47ee-a595-2dda294a4d08}":{"version":"24.8.12.1","scope":1,"type":"extension","updateDay":19955,"isSystem":false,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Japanese dictionary with Anki integration","name":"Yomitan","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19891,"signedState":2,"signedTypes":"[2,1]","quarantineIgnoredByApp":false,"quarantineIgnoredByUser":false},"{c84d89d9-a826-4015-957b-affebd9eb603}":{"version":"0.10.4","scope":1,"type":"extension","updateDay":19956,"isSystem":false,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Integrates MyAnimeList/AniList/Kitsu/Simkl/Shikimori into various sites, with auto episode tracking.","name":"MAL-Sync","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19891,"signedState":2,"signedTypes":"[2,1]","quarantineIgnoredByApp":false,"quarantineIgnoredByUser":false}},"theme":{"id":"firefox-compact-light@mozilla.org","blocklisted":false,"description":"A theme with a light color scheme.","name":"Light","userDisabled":false,"appDisabled":false,"version":"1.2","scope":4,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19891,"updateDay":19891},"activeGMPlugins":{"gmp-gmpopenh264":{"version":"2.3.2","userDisabled":false,"applyBackgroundUpdates":1},"gmp-widevinecdm":{"version":"4.10.2710.0","userDisabled":false,"applyBackgroundUpdates":1}}},"experiments":{"long-term-holdback-2024-h2-velocity-desktop":{"branch":"delivery","type":"nimbus-nimbus"},"csv-import-release-rollout":{"branch":"enable-csv-import","type":"nimbus-rollout"},"upgrade-spotlight-rollout":{"branch":"treatment","type":"nimbus-rollout"},"phc-rollout":{"branch":"rollout","type":"nimbus-rollout"},"highlighting-in-pdfs-rollout":{"branch":"treatment","type":"nimbus-rollout"},"recommend-add-ons-staff-pick-relaunch-treatment-a-rollout":{"branch":"treatment-a","type":"nimbus-rollout"},"extensions-migration-in-import-wizard-116-rollout":{"branch":"control","type":"nimbus-rollout"},"device-migration-q4-spotlights-remaining-population":{"branch":"treatment","type":"nimbus-rollout"},"disable-redirects-for-authretries":{"branch":"control","type":"nimbus-rollout"},"home-and-newtab-wallpapers-v2-rollout-global-relaunch":{"branch":"control","type":"nimbus-rollout"},"consolidated-search-configuration-row-desktop-relaunch":{"branch":"rollout","type":"nimbus-rollout"},"relay-integration-into-firefox-118-release-for-all-fxa-and-autofill-users":{"branch":"enable-relay-integration","type":"nimbus-rollout"},"tab-hover-preview-release-rollout":{"branch":"control","type":"nimbus-rollout"}},"services":{"accountEnabled":true,"syncEnabled":true}}
TelemetryServerURL: https://incoming.telemetry.mozilla.org
TelemetrySessionId: 23517a1d-e8a4-423f-9baa-192b2fd80b6e
Throttleable: 1
TotalPageFile: 67197181952
TotalPhysicalMemory: 33598713856
UptimeTS: 304.2166572
UtilityProcessStatus: Running
Vendor: Mozilla
Version: 129.0.1
useragent_locale: en-US
This report also contains technical information about the state of the application when it crashed.
`

**Comment by kimjongbing** [comment]
This also occurs on KDE with Zen Browser

```
Crash Annotation GraphicsCriticalError: |[0][GFX1-]: More than 1 GPU from same vendor detected via PCI, cannot deduce device
 (t=0.258389) [GFX1-]: More than 1 GPU from same vendor detected via PCI, cannot deduce device

Crash Annotation GraphicsCriticalError: |[0][GFX1-]: More than 1 GPU from same vendor detected via PCI, cannot deduce device
 (t=0.258389) |[1][GFX1-]: Wayland protocol error: wp_linux_drm_syncobj_surface_v1#53: error 5: explicit sync is used, but no release point is set
 (t=1441.68) [GFX1-]: Wayland protocol error: wp_linux_drm_syncobj_surface_v1#53: error 5: explicit sync is used, but no release point is set

Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Crash Annotation GraphicsCriticalError: |[C0][GFX1-]: CompositorBridgeChild receives IPC close with reason=AbnormalShutdown (t=1440.57) fish: Job 1, 'zen-browser' terminated by signal SIGSEGV (Address boundary error)
```

**Comment by mauro-balades** [comment]
Please checkout: https://github.com/zen-browser/desktop/issues/296
