### ISSUE TITLE
Extra gap on tabs while hovered (Expand Tabs on Hover + Tabs on the right)

### ISSUE THREAD

**Issue by KiKaraage** [zen-browser/desktop#476]
### What happened?

Using "Expand Tabs on Hover" while having "tabs on the right" on, results on about 100px extra horizontal gap in right side of the vertical tabs

In regular window mode
![image](https://github.com/user-attachments/assets/d0edb8a9-42ca-4050-b3cf-c40a26d62000)

In maximized window mode
![image](https://github.com/user-attachments/assets/763daba7-6b6d-4b18-bad9-c0b6d99f49ed)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.28

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by KarimElsayad247** [comment]
@KiKaraage can you verify that the problem is still there on recent version?

**Comment by HarryHeres** [comment]
> @HarryHeres is it fixed by this commit ?[71c20bdf986f1d8f4a57e61fe15335dff60cf537](https://github.com/zen-browser/desktop/commit/71c20bdf986f1d8f4a57e61fe15335dff60cf537)

I've been quite busy lately so didn't have time to test it

**Comment by KiKaraage** [comment]
> @KiKaraage can you verify that the problem is still there on recent version?

It's fixed! I like it now, it's so much better. The only problem left is just some adjusting stuff... 1px/2px gaps between collapsed and hovered state.

![image](https://github.com/user-attachments/assets/ffe7a28c-5575-447f-9a79-9fe1f416f97d)

4x zooms:
![image](https://github.com/user-attachments/assets/8a968b68-55e3-4d22-9be8-d489ffab2b2e)
![image](https://github.com/user-attachments/assets/47afd86c-bc48-4d20-84ba-75e3ebcc452e)
![image](https://github.com/user-attachments/assets/23ec1ba7-3171-4a98-80b2-759bce6e0984)
![image](https://github.com/user-attachments/assets/2dc8c853-8982-420d-ac90-9df01d6a4f34)
