### ISSUE TITLE
Unable to scroll to the end of the page on Mac

### ISSUE THREAD

**Issue by thelazyoxymoron** [zen-browser/desktop#478]
### What happened?

I've been using Zen browser as my daily driver for the past couple of days and noticed that after some reasonable time of usage, I'm unable to scroll completely to the end of the page. Restarting the browser fixes the issue temporarily.

I've not been able to measure the time interval when issue starts occurring, but I've been able to consistently reproduce this error every time I've had a longer browser session ongoing.

Attaching a video.

https://github.com/user-attachments/assets/b7cb01e6-0ee5-41bb-8e3b-f8c54e55b963

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.28 (64-bit)

### Severity impact

Medium

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by thelazyoxymoron** [comment]
This happens when I close down my lid, although not necessarily every time.

**Comment by thelazyoxymoron** [comment]
Bumping this. It's happening quite frequently now and I need to always quit the browser and reopen to get things working again.

**Comment by mauro-balades** [comment]
Does this still happen?

**Comment by thelazyoxymoron** [comment]
Confirming that I haven't come across this problem in recent versions.
