### ISSUE TITLE
Scrollbars overlaps rounded corners

### ISSUE THREAD

**Issue by SomeDudeBrosky** [zen-browser/desktop#48]
![Screenshot from 2024-07-12 16-28-25](https://github.com/user-attachments/assets/d94897d2-f8f0-4c94-82bd-71a8e1154a7f)

**Comment by SomeDudeBrosky** [comment]
Wayland, Linux, 1080p screen

**Comment by mauro-balades** [comment]
hmmmm, it seems to be the scrollbar causing the issue, not bing.com so please allow me to change the title

**Comment by mauro-balades** [comment]
Fixed in https://github.com/zen-browser/desktop/commit/bd0cf2ea8620f14c19aa4ff07027d1345257776f, thanks a lot!

**Comment by SomeDudeBrosky** [comment]
It is caused by the CSS of the page's background being an image instead of a solid color, raw CSS, or an SVG. This is clear, as the overlap is around the entire webpage and not just the side which contains the scrollbar. Along with this, other similar webpages (including my personal localhost) only have this issue when this is met. Please change the title back, as although an update in the rendering of the stylesheets may have fixed the issue, the scrollbar did not cause it, and changing bug report contents messes up documentation and is unprofessional.

**Comment by mauro-balades** [comment]
you are right, sorry for my mistake, it's fixed now
