### ISSUE TITLE
Adjust color on homepage to match zen theme

### ISSUE THREAD

**Issue by GameTec-live** [zen-browser/desktop#480]
### What feature would you like to see?

The landing/homepage/newtab page has the custom zen logo, but the colorscheme isnt matched.
In firefox its matched to the rest of the UI, when using zed, its still firefox colors and not matched to the theme
<img width="593" alt="{922AC6FF-B8BA-4B89-862F-477B2038161C}" src="https://github.com/user-attachments/assets/841c2f7f-2594-4125-9cc3-ff353949731c">
<img width="1131" alt="{A5191651-5C64-4A64-BF86-BB0446EDD002}" src="https://github.com/user-attachments/assets/c112f2a0-70b5-4658-b1b1-d6cad4594187">

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/826

 ~ This is an automatic operation to better enhancements requests organization.
