### ISSUE TITLE
reset keyboard shortcuts to default settings

### ISSUE THREAD

**Issue by lfelipessilva** [zen-browser/desktop#482]
### What feature would you like to see?

when you mess around the settings for the shortcuts you cannot reset it to default settings

i imagine just a button on the top right of the page to reset to default settings, like in the home settings page, where you have a "Restore default" button

### What platform are you seeing the problem on?

Linux

**Comment by lfelipessilva** [comment]
i can do this myself, just filling the issue for tracking

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/825

 ~ This is an automatic operation to better enhancements requests organization.
