### ISSUE TITLE
Mixed Grid Layout

### ISSUE THREAD

**Issue by Shirkit** [zen-browser/desktop#484]
### What feature would you like to see?

Hello,

First I'd like to congratulate you for your hard work on this awesome browser! I've been a FF user for 20 years, and been using Arc for around 1 year now. You managed here to bring a lot of cool features from modern browsers, nice!

So one of the features no browser has it the ability of mixed Layouts. Imagine a grid that allows half the tabs on vertical and half the tabs on horizontal. That would allow the tabs 1/2 to be mostly vertical and 3/4 mostly horizontal.

```
________________
| 1 | 2 | 3 | 3|
| 1 | 2 | 4 | 4|
▔▔▔▔▔▔▔▔▔
```

Anyways, that's one of the things I wish it could be implemented! Thanks for this awesome project!

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/824

 ~ This is an automatic operation to better enhancements requests organization.
