### ISSUE TITLE
"Paste and Go" right click option for the URL bar

### ISSUE THREAD

**Issue by tunalad** [zen-browser/desktop#485]
### What feature would you like to see?

In Firefox when you have something in the clipboard (URL or text), you have an option "paste and go" when right-clicking on the URL bar. Clicking it will either send you to the URL from the clipboard, or it will search if the text isn't a URL

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/823

 ~ This is an automatic operation to better enhancements requests organization.
