### ISSUE TITLE
Show sidebar when switching tabs with keybinds in compact mode.

### ISSUE THREAD

**Issue by CrynTox** [zen-browser/desktop#486]
### What feature would you like to see?

So I use keybinds to switch between tabs Alt+[1-9] (Note: this is different on Windows). I would like for the sidebar to show up when using those keybinds.
The most sane way I think it could work:
It shows up when someone presses the full keybind (Alt+1, Alt+2, Alt+3...) and it stays visible until Alt is released.

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/822

 ~ This is an automatic operation to better enhancements requests organization.

**Comment by c0d3-Astra** [comment]
i have issue these tabs switching key binds ,
but these keybinds works fine of firefox.
any idea what's the issue : using hyprland >> nothing bonded to alt
