### ISSUE TITLE
Temporary Containers

### ISSUE THREAD

**Issue by Eun** [zen-browser/desktop#487]
### What feature would you like to see?

It would be create to have a similar functionality that Temporary Containers (https://github.com/stoically/temporary-containers) offers.
It is possible to open a new tab/window in a new temporary container, no cookies and no history everything from zero, every time - meaning also the tracking is limited. This will obviously not counter finger printing but its a step into the right direction.

### What platform are you seeing the problem on?

macOS

**Comment by anatasiajp** [comment]
We can have this feature by creating a immutable container that automatically clear itself after closing, could cause some shut down performance issues.

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/821

 ~ This is an automatic operation to better enhancements requests organization.
