### ISSUE TITLE
Issue setting shortcuts on Linux and MacOS

### ISSUE THREAD

**Issue by vemonet** [zen-browser/desktop#490]
### What happened?

I tried to change shortcuts on Linux Ubuntu 22.04 (x11), and it did not work as expected!

Originally I just wanted to set a shortcut for `Toggle Compact Mode Sidebar` (the one with the tabs). Note there was already a default shortcut set (`ctrl+alt+c` I think) which did not work. And whatever key combination I tried to put it never worked (I tried with the `meta+d` or `meta+c` and others)

I tried to restart the zen browser to see if that was needed to get the shortcut to work but it did not help

Overall the interface to set the shortcut is prone to make a mess:
* it does not unfocus the "set shortcut boxes" when we click outside of them (there is no way to unfocus a shortcut box apart from clicking on another one or the checkbox to disable Zen default shortcuts)
* so when you want to `alt+tab` out of the tab you often end up redefining a shortcut you never wanted to touch
* there is no way to reset all shortcuts to default
* It seems like when you mistakenly define a shortcut it erase the previous action, messing up your ergonomy
* I lost the shortcut `ctrl+T` the default used to open a new tab (which was working before I fiddle with the shortcuts settings). And redefining it manually in the shortcut settings does not work anymore (not sure what to do to get it back I really need it 😢)
* I tried to reset the `ctrl+T` shortcut by checking and unchecking `Disable Zen Browser's default keyboard shortcuts` but it did not change (note that when it is checked I lose some shortcut like `ctrl+w` to close a tab, so it seems to work a bit)
* The default shortcut for "Toggle Web Panel" seems to be `Ctrl+Shift+P` (at least it was for me), which conflicts with the traditional firefox shortcut to open a new private window. Most long time firefox users are used to this shortcut, so it does not seems to be a wise default (also P = private which make sense, for Web Panel `ctrl+shift+W` seems more logical, can be done with one hand and does not conflict with popular shortcut afaik)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.27 (64-bit)

### Severity impact

Low

### What platform are you seeing the problem on?

Linux

**Comment by karlprieb** [comment]
Same thing happens in MacOS

**Comment by branbarh** [comment]
Having a similar issue on Windows. Using "ctrl+t" cycles through my tabs rather than opening a new one (even though I have "ctrl+t" set to open a new tab in the keyboard shortcut settings, with and without Zen's defaults disabled).

I have it set to alt+t for the time being, which works without issue.

**Comment by poeck** [comment]
> Having a similar issue on Windows. Using "ctrl+t" cycles through my tabs rather than opening a new one (even though I have "ctrl+t" set to open a new tab in the keyboard shortcut settings, with and without Zen's defaults disabled).
> 
> I have it set to alt+t for the time being, which works without issue.

Same  here, I'd love to make Ctrl+T open a new tab but I'm not able to override it.

**Comment by vemonet** [comment]
Not sure if I will have the time to work myself on this but here is some leads to figure out where the problem comes from:

- The change keyboard shortcut page at URL `about:preferences#zenCKS` seems to be handled by this script: https://github.com/zen-browser/desktop/blob/main/src/browser/components/preferences/zen-settings.js#L353 this is there we could improve the focus/unfocus of the shortcut fields 💡
- We can find all configs at URL `about:config`, including a JSON describing all `zen.keyboard.shortcuts`

In my case those 2 shortcuts are not working properly when defined:

## `openNewTab` does not work with `Ctrl+T`

I need to use `Alt+T`, I have checked and I do not use `Ctrl+T` in global system shortcut, so the problem does not seems to come from the system overriding the zen shortcut

When searching a bit we can find `openNewTab` here: https://github.com/zen-browser/components/blob/main/src/ZenKeyboardShortcuts.mjs#L15 but the lead kind of stop here, and hard to understand why it is not working just with `Ctrl+T` 

## `zenToggleCompactModeSidebar` and `zenToggleCompactModeToolbar` do not work with any shortcut 

`zenToggleCompactMode` works though! These shortcuts IDs are only called here: https://github.com/zen-browser/components/blob/main/src/ZenKeyboardShortcuts.mjs#L29 

So `gZenCompactModeManager.toggle()` seems to work, but not `gZenCompactModeManager.toggleSidebar()` and `gZenCompactModeManager.toggleToolbar()`

Those functions are defined here: https://github.com/zen-browser/desktop/blob/main/src/browser/base/content/ZenUIManager.mjs#L110

Fun fact: the implementation of `.toggle()` (the only function working) has a typo that do not create an error 😂 :

```ts
toggle() {
    this.preference = !this.prefefence;
  },
```

Toggle sidebar and toolbar functions are implemented differently by getting element by ID, and toggling an attribute on the element, maybe this is not the right way to go:

```ts
toggleSidebar() {
    let sidebar = document.getElementById('navigator-toolbox');
    sidebar.toggleAttribute('zen-user-show');
  },
```

**Comment by HarryHeres** [comment]
The keyboard shortcut binding is being reworked completely at the moment. Watch #283 and #376 for updates.

**Comment by HarryHeres** [comment]
Closing as this is being aggregated in #1363
