### ISSUE TITLE
Forgets tabs when I close and reopen the browser

### ISSUE THREAD

**Issue by clay-risser** [zen-browser/desktop#492]
### What happened?

When I close the browser and then reopen the browser, all the tabs I used (including tabs I pinned are gone).

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.28

### Severity impact

Medium

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by ochronus** [comment]
Plus one for this, and yes, I've unchecked the respective privacy setting, see the attachment
<img width="590" alt="ff" src="https://github.com/user-attachments/assets/8f128c93-9104-4fc3-afc7-1c4b09695ed9">

**Comment by ochronus** [comment]
Ok, solved!

Besides the setting above, I had to set "History" to "Remember history" --> beware, this will uncheck the "Open previous windows and tabs" setting in "General", so I had to check that again. Now it works.

Something more straightforward would be nice here.

**Comment by finnar-bin** [comment]
I just lost a lot of tabs I was using for work lol
I agree with the comment above. This should've been more straightforward.
