### ISSUE TITLE
unkown publisher

### ISSUE THREAD

**Issue by git-create-devben** [zen-browser/desktop#493]
### What happened?

Well, I'm new to zen I just download zen on my window now, but my window telling me zen publisher is unknown.... This is not a problem for me but incase non-tech person see this, they may have less privilege to continue , it'll be awesome to know the publisher

I may not report the best bug but am just trying to support with the little one i discover and I may delete this if am wrong. Thank you.

![image](https://github.com/user-attachments/assets/39a0273a-f88c-4bcf-90df-d431b9e7457b)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

latest version 

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by n7itro** [comment]
This will be solved when the developer receives sufficient funding for the Windows license ($100).

Feel free to donate at https://ko-fi.com/zen_browser
