### ISSUE TITLE
FR: Command Palette

### ISSUE THREAD

**Issue by wafe** [zen-browser/desktop#494]
### What feature would you like to see?

Suggestion: Improve accessibility of functions without relying on keyboard shortcuts

I find it challenging to memorize numerous keyboard shortcuts. It would be beneficial to have the ability to access all functions, such as "Split View Vertical", through a command palette-like interface similar to what VSCode offers.

This feature would:
1. Reduce the learning curve for new users
2. Improve accessibility for users who prefer not to use keyboard shortcuts

Could we consider implementing a searchable command palette to make all functions easily accessible without the need for memorizing keyboard shortcuts?

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/820

 ~ This is an automatic operation to better enhancements requests organization.
