### ISSUE TITLE
HDR playback does not work properly on macOS

### ISSUE THREAD

**Issue by miklosakos** [zen-browser/desktop#496]
### What happened?

Loading a video in HDR on YouTube, like Jacob + Katie Schwarz's [COSTA RICA IN 4K 60fps HDR (ULTRA HD)](https://www.youtube.com/watch?v=LXb3EKWsInQ) will start playing back in HDR, however the actual video looks like HDR content being played back on an SDR display.
This bug does not happen on Mozilla Firefox running on macOS.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.28 (64-bit)

### Severity impact

Medium

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by HarryHeres** [comment]
Same issue, will take a look into it and see if I can find the culprit. Confirming that HDR with normal Firefox works.

**Comment by HarryHeres** [comment]
Can confirm, one of the git patches in src folder is causing this. Pin-pointing this down further later today...

**Comment by mauro-balades** [comment]
I wonder what it could be

**Comment by HarryHeres** [comment]
Can confirm that the issue remains with the clip-path and overflow:hidden attributes (needed for rounded borders) of the content window. 

A temporary solution would be to use https://zen-browser.app/themes/c6813222-6571-4ba6-8faf-58f3343324f6.

I will try to implement a more permanent solution while enabling for having the same visual appearance.

**Comment by HarryHeres** [comment]
@mauro-balades I think this can get closed for now as we have a solution. I might get back to this later, but I think there are other issues with higher priority.
