### ISSUE TITLE
Corners CSS overlay

### ISSUE THREAD

**Issue by nwrenger** [zen-browser/desktop#497]
### What happened?

When visiting websites using this css class ```mix-blend-mode: difference;```  on a fixed element with full height and width will break/overlay over the rounded corners of the web view. Example visiting this website and looking at the navbar: [nwrenger.dev](https://nwrenger.dev/).

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.28

### Severity impact

Low

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by anatasiajp** [comment]
Try to install this theme to see if it is fixed ? 

https://www.zen-browser.app/themes/c6813222-6571-4ba6-8faf-58f3343324f6

**Comment by nwrenger** [comment]
Yeah, that'll fix it, but it's just a workaround that doesn't fully resolve the issue, as it completely removes the rounded corners.

**Comment by anatasiajp** [comment]
From some comments it looks like they will rewrite the rounded corners in the future, but it'll be much harder and safer, faster. For now you can use that theme.

**Comment by markox92** [comment]
Yeah that's what I don't like
![Screenshot 2024-08-23 234952](https://github.com/user-attachments/assets/3a8bb0b8-19ec-485c-9103-6155162f511b)

I have found just one **chrome style** for Firefox which does not have this problem and rounded corners is working good, all others have same problem.

**Comment by anatasiajp** [comment]
> Yeah that's what I don't like ![Screenshot 2024-08-23 234952](https://private-user-images.githubusercontent.com/159203552/361073564-3a8bb0b8-19ec-485c-9103-6155162f511b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0Njg4MzYsIm5iZiI6MTcyNDQ2ODUzNiwicGF0aCI6Ii8xNTkyMDM1NTIvMzYxMDczNTY0LTNhOGJiMGI4LTE5ZWMtNDg1Yy05MTAzLTYxNTUxNjJmNTExYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNFQwMzAyMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jN2MxMjVlNDQyNWE2MmRlMWM4YjlhMmUxODdjMTY5YWQ0NWQ1ZjU3NDIxMmJjZWExZGZiYzYzZmEwMTEzNDU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NB2WPEY0ZRFmZGHW0ENbtPlDWfkh0f_pXO3vHcy9y-A)
> 
> I have found just one **chrome style** for Firefox which does not have this problem and rounded corners is working good, all others have same problem.

Can you give the link of the working style ?

**Comment by markox92** [comment]
Sure https://github.com/amnweb/firefox-plus

**Comment by nwrenger** [comment]
Yes, the issue persists in the latest version, 1.0.1-a.22.

**Comment by mr-cheffy** [comment]
> Yeah that's what I don't like ![Screenshot 2024-08-23 234952](https://github.com/user-attachments/assets/3a8bb0b8-19ec-485c-9103-6155162f511b)
> 
> I have found just one **chrome style** for Firefox which does not have this problem and rounded corners is working good, all others have same problem.

It uses pseudo rounded corners, they woudnt work for split views. Mix blend mode is the best and most performant option we have currently... Ill try to investigate more

**Comment by mr-cheffy** [comment]
Ill come back to this issue after I see what firefox does, until then, ill close it down
