### ISSUE TITLE
How to make Zen browser the default browser in linux

### ISSUE THREAD

**Issue by Aslemammad** [zen-browser/desktop#498]
### What happened?

Hey, this browser is an exception. Thank you all for the hard work.

One thing I'm struggling with, is making it the default browser in my linux setup. I'm using xfce (Zorin distribution, installed with flatpack) and I do not find it in my default applications for the browser, which there I can find Chrome or Firefox itself. 

I can live with this but the fact that any link will be not opened in Zen itself, is a bit annoying. 

Again, Thank you all for this piece of art ❤️

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Mozilla Zen 1.0.0-a.26

### Severity impact

Low

### What platform are you seeing the problem on?

Linux

**Comment by ttaylor-st** [comment]
You *should* be able to use [xdg-settings](https://man.archlinux.org/man/xdg-settings.1):

```bash
xdg-settings set default-web-browser zen-browser.desktop
```

Alternatively, if you go to Settings > General in Zen, there should be an option under Startup, "always check if Zen is your default browser". Just below that, it'll tell you whether Zen is the default or not. If it's not, there will also be a "Make Default" button



![Screenshot of Zen Browser settings, showing "Startup" options and a notification that Zen Browser is not the default browser with a button to "Make Default...".](https://github.com/user-attachments/assets/2de0c57b-cba9-4964-97e4-074f334d77e7)

**Comment by Aslemammad** [comment]
This just worked with the command! Thank you so much!

**Comment by gxanshu** [comment]
@Aslemammad can you please share you zen-browser.desktop file, and its location.

Its not working for me somehow

**Comment by Aslemammad** [comment]
For sure, well, first I had to move it from the search to the desktop so the desktop file gets created! 

And then I did `cd ~/Desktop; # the command above`

But you are not able to have a desktop file, here's the content. 

```desktop
[Desktop Entry]
Name=Zen Browser
Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=launch-script.sh --file-forwarding io.github.zen_browser.zen @@u %u @@
Icon=io.github.zen_browser.zen
Type=Application
MimeType=text/html;text/xml;application/xhtml+xml;x-scheme-handler/http;x-scheme-handler/https;application/x-xpinstall;application/pdf;application/json;
StartupWMClass=zen-alpha
Categories=Network;WebBrowser;
StartupNotify=true
Terminal=false
X-MultipleArgs=false
Keywords=Internet;WWW;Browser;Web;Explorer;
Actions=new-window;new-private-window;profilemanager;
X-Flatpak=io.github.zen_browser.zen

[Desktop Action new-window]
Name=Open a New Window
Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=launch-script.sh --file-forwarding io.github.zen_browser.zen @@u %u @@

[Desktop Action new-private-window]
Name=Open a New Private Window
Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=launch-script.sh --file-forwarding io.github.zen_browser.zen --private-window @@u %u @@

[Desktop Action profilemanager]
Name=Open the Profile Manager
Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=launch-script.sh --file-forwarding io.github.zen_browser.zen --ProfileManager @@u %u @@
```

**Comment by tilupe** [comment]
I don't see any setting in the general setting.
Is it only for me? 
![image](https://github.com/user-attachments/assets/0623e864-9be3-4e09-99f2-8c0f5ba52152)

**Comment by Aslemammad** [comment]
It was not there for me too!

**Comment by lts20050703** [comment]
I don't see always check if Zen is your default browser either!

**Comment by ilhamprabuzakys** [comment]
Help me please, i'm using AppImage method.

![image](https://github.com/user-attachments/assets/2b1136bb-566d-48bd-81b1-99997f1f5ab2)

I got these error :
`> xdg-open https://github.com/Ulauncher/Ulauncher/issues/530`
`kf.kio.gui: "Could not find the program '/tmp/.mount_zen-spdDaFDK/zen'"`

**Comment by ilhamprabuzakys** [comment]
> Help me please, i'm using AppImage method.
> 
> ![image](https://private-user-images.githubusercontent.com/68785569/362251071-2b1136bb-566d-48bd-81b1-99997f1f5ab2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4NDI2ODgsIm5iZiI6MTcyNDg0MjM4OCwicGF0aCI6Ii82ODc4NTU2OS8zNjIyNTEwNzEtMmIxMTM2YmItNTY2ZC00OGJkLTgxYjEtOTk5OTdmMWY1YWIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDEwNTMwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2NjRiZmJiNTg1MjA5NWViZDUzMTQ3ODc1YmVmYjkxYWY3MDgxMjI0MDdhOGVhN2I2YjRhZGIzOGVmOGVlMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NsScwFQgfmu2tm0eN-z96yhb6AYyI82cTkb5rf6-lhA)
> 
> I got these error : `> xdg-open https://github.com/Ulauncher/Ulauncher/issues/530` `kf.kio.gui: "Could not find the program '/tmp/.mount_zen-spdDaFDK/zen'"`

Fixed by method :

```
xdg-mime default zen-browser.desktop x-scheme-handler/http
xdg-mime default zen-browser.desktop x-scheme-handler/https
xdg-mime default zen-browser.desktop text/html
xdg-settings set default-web-browser zen-browser.desktop
```

Make sure there's like this on Exec :

`Exec=/home/user/Downloads/Package/AppImage/zen-specific.AppImage %U`

**Comment by diegogzorrilla** [comment]
I'm using the flatpak and I don't have the option to make default in Settings > General. 

I try in about:config to force the check at startup. Now it asks and I select Set as Default, but it's not working.

**Comment by novakwh** [comment]
Note that the "set as default browser" option does not show up in Startup under settings in the flatpak version, and when I changed the configuration (in about:config) to get a prompt on opening the browser, accepting the request to make it my default didn't work, anyway. (I am using xfce, Tumbleweed.)

I was able to get Zen set as my default browser by choosing Other (in Default Applications) and then entering the flatpak run command. Still, the fact that the default browser check doesn't work seems like a bug that should not be closed.

**Comment by K0ntact** [comment]
> I'm using the flatpak and I don't have the option to make default in Settings > General.
> 
> I try in about:config to force the check at startup. Now it asks and I select Set as Default, but it's not working.

~You can set Zen flatpak as default browser by running `xdg-settings set default-web-browser io.github.zen_browser.zen.desktop`.~

Update 15/1/2025: The app's desktop entry was changed to `app.zen_browser.zen.desktop`. The new command is `xdg-settings set default-web-browser app.zen_browser.zen.desktop`

**Comment by diegogzorrilla** [comment]
> You can set Zen flatpak as default browser by running `xdg-settings set default-web-browser io.github.zen_browser.zen.desktop`.
That works, thank you @K0ntact

**Comment by diegogzorrilla** [comment]
> You can set Zen flatpak as default browser by running `xdg-settings set default-web-browser io.github.zen_browser.zen.desktop`.

That works, thank you @K0ntact

**Comment by Luks17** [comment]
Hello, I already set my zen flatpak as the default browser. However, it keeps asking on startup every time.

![2025-01-11_17-30-37](https://github.com/user-attachments/assets/21e38f27-28b7-47ec-bb21-cb7114f6eaa6)

**Comment by K0ntact** [comment]
@Luks17 You can go to `about:config` and set `browser.shell.checkDefaultBrowser` to `false` to disable default browser check.

**Comment by ryuheechul** [comment]
In my case (on NixOS with Gnome, Zen installed via Flatpak), nothing suggested above worked including `xdg-settings set default-web-browser app.zen_browser.zen.desktop`.
What worked though is by visiting _Settings (Gnome not Zen) > Apps > Default Apps > Web_ and select Zen Browser. Sharing this finding in case of someone else is in similar situation.

**Comment by Fish1** [comment]
> In my case (on NixOS with Gnome, Zen installed via Flatpak), nothing suggested above worked including `xdg-settings set default-web-browser app.zen_browser.zen.desktop`. What worked though is by visiting _Settings (Gnome not Zen) > Apps > Default Apps > Web_ and select Zen Browser. Sharing this finding in case of someone else is in similar situation.

I've installed zen with flatpak, and zen doesn't show in my default app list.

**Comment by 0genGH** [comment]
im on linux mint xfce and the command didnt work, i typed the flatpak name that is used to install and run on the terminal on the default web browser (since it normally doesnt show up) and the zen browser icon did show up but an error msg would appear when i tried to click some link on discord or smth
