### ISSUE TITLE
Color per Workspace

### ISSUE THREAD

**Issue by gcarrarom** [zen-browser/desktop#499]
### What feature would you like to see?

Similar to #163, it would be nice to be able to differentiate the workspace in use by the accent of the browser. It would be nice to have different colors for different workspaces for faster feedback.

### What platform are you seeing the problem on?

macOS

### Additional context

When I open a new Workspace, I would like it to be a long-lived "profile" of sorts. to which I'd like to be able to differentiate by container: #163 and by color.

**Comment by kLabz** [comment]
Current workaround I'm using is getting my workspace ids with browser UI inspector (ctrl+alt+shift+i) on `html` element (`zen-workspace-id` attribute), and then add rules to my `userChrome.css` using `[zen-workspace-id="57aded40-b55d-4074-8014-9b460e7140c3"]` selectors.

You should be able to redefine css variables to your needs to change accent color, etc.

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/819

 ~ This is an automatic operation to better enhancements requests organization.
