### ISSUE TITLE
Zen homepage listed as Firefox homepage in settings

### ISSUE THREAD

**Issue by SomeDudeBrosky** [zen-browser/desktop#50]
![image](https://github.com/user-attachments/assets/a609bd7b-4c05-47b8-90ab-6768a1f30b6f)

**Comment by mauro-balades** [comment]
Thanks a lot for these reports! This is fixed in https://github.com/zen-browser/desktop/commit/cfee3bf9c38b19ddf2796575c0f641e5a738c221 it'll apply in the next release!
