### ISSUE TITLE
Ability to use multiple profiles in one window via workspaces

### ISSUE THREAD

**Issue by ivial94** [zen-browser/desktop#500]
### What feature would you like to see?

One of the killer features for me in the Arc Browser is the ability to associate a profile with the workspace, which allows to isolate workspaces from each other and have different sets of configurations, extensions, history, favorites, cookies, etc in every workspace. Unlike vanilla Chrome or Firefox, switching between workspaces with different profiles happens without creating a new window, seamlessly and transparently, which allows me to not even care about extra window management.

I have 3 different Microsoft and Google accounts which I use for different purposes (two for work and one for own business), and I have 3 different workspaces, each one has exactly one logged in MS account. I also have different sets of extensions necessary for every workspace, and in some cases I have same extensions with different configurations, e.g. Bitwarden that uses different accounts based on the workspace I am currently in.

Currently in Zen browser I can use workspaces only as an organizational feature, where every workspace is like a container with different sets of tabs, but the sessions, cookies, extensions and browser preferences, etc. are shared between all of them.

I would like to have an ability to associate a workspace with different profile in the same way as it is done in Arc, to be able to use my workspaces as fully isolated (or not, if there are sibling workspaces associated with the same profile) environments and have a better browsing experience, and switch these workspaces in the same browser window.

### What platform are you seeing the problem on?

Windows

**Comment by weslley75** [comment]
Maybe if you used Firefox's Container Tabs in a way that each workspace always starts the tab with a separate container, it would probably work. I've tried to do this using Sideberry, it was a little buggy, but it worked almost the same.

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/818

 ~ This is an automatic operation to better enhancements requests organization.

**Comment by beratcmn** [comment]
I am using Zen partially, if I could use different accounts for different workspaces then I would definitely switch fully to Zen across all my devices.
