### ISSUE TITLE
Bookmark/History tab does not use theme colour

### ISSUE THREAD

**Issue by A2va** [zen-browser/desktop#501]
### What feature would you like to see?

I don't think it's very pretty
![image](https://github.com/user-attachments/assets/5164cc4f-236c-40e4-bbc6-059978fd5527)

EDIT: Removed language related thing because #531 

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/817

 ~ This is an automatic operation to better enhancements requests organization.
