### ISSUE TITLE
DRM Video Playback (Udemy)

### ISSUE THREAD

**Issue by siddharthp1997** [zen-browser/desktop#503]
### What happened?

When  I try to watch that are encrypted on udemy.com, it doesn't play. It shows a blank black screen. Non-encrypted videos play fine.

In this image, you can see that the video does not play.

<img width="1476" alt="Screenshot 2024-08-23 at 11 48 48 AM" src="https://github.com/user-attachments/assets/5af842da-85e1-4360-8b7e-6747944fcfe5">

In this image, you can see that the video is encrypted.

<img width="1452" alt="Screenshot 2024-08-23 at 11 49 30 AM" src="https://github.com/user-attachments/assets/b8f1bd96-8cf2-4e0f-b246-24385df2358a">

Similar video plays fine using the Firefox browser.

<img width="942" alt="Screenshot 2024-08-23 at 11 51 04 AM" src="https://github.com/user-attachments/assets/ecb04122-2182-4316-9752-2ba01fb30881">

Similar video plays fine using the firefox browser.
<img width="841" alt="Screenshot 2024-08-23 at 11 51 23 AM" src="https://github.com/user-attachments/assets/9e959cba-9155-4ef2-bec4-a06122ce878a">

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.28

### Severity impact

Critical

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by marcelovbcfilho** [comment]
I'm having the same issue with Primevideo and Crunchyroll. The DRM icon appear on the top, but the video refuses to start playing. On firefox works just fine.

**Comment by Jan540** [comment]
> Obs: The issue appear to be macOS exclusive, tested on my linux setup and the playback works just fine.

I am having the same issue on windows. No DRM content seems to work.

![image](https://github.com/user-attachments/assets/b618ed90-8284-474c-8b51-677195ff56fb)

**Comment by Krymancer** [comment]
I'm having the same problem with primevideo and crunchroll on windows.

**Comment by NathanGlasby** [comment]
I'm having the same issue with Netflix and Prime Video on Windows. Appears to be due to [this issue.](https://github.com/ungoogled-software/ungoogled-chromium/issues/1258#issuecomment-2114305561)

**Comment by siddharthp1997** [comment]
Consider adding a note in the README file that states in bold, "**Most DRM-protected content will not work on macOS and Windows.**" This can help inform users upfront about potential limitations and prevent additional users from raising the issue.

**Comment by indranildeveloper** [comment]
Are there any updates? I am currently not able to play udemy videos.

**Comment by Baspla** [comment]
No. As mentioned above. https://github.com/ungoogled-software/ungoogled-chromium/issues/1258#issuecomment-2114305561

**Comment by indranildeveloper** [comment]
Thanks! In Linux the video plays fine no issues. It looks like this is only present in Windows.

**Comment by furkanunsalan** [comment]
The issue seems to be present still in macOS too. I'm having problem on playing most of the Udemy videos.

**Comment by JandersonJean** [comment]
I'm also facing this problem
