### ISSUE TITLE
Too much RAM Consumption

### ISSUE THREAD

**Issue by subhashhhhhh** [zen-browser/desktop#504]
### What happened?

I've been using Zen Browser since yesterday and I've noticed that it's consuming unusually high amount of RAM. Almost 3GB ram on my 8GB M1 Air. 

<img width="414" alt="image" src="https://github.com/user-attachments/assets/affe2a22-db73-41ea-8b9b-9d8711ad96d5">

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.28

### Severity impact

Medium

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by thrzl** [comment]
Facing a similar issue on an 8GB M2 Macbook Air, Zen is using around 800MB of memory on a fresh open with only one DuckDuckGo tab open:
<img width="538" alt="image" src="https://github.com/user-attachments/assets/32af3ca7-56e9-4fe9-8a46-6d184b8d8bf6">

**Comment by n7itro** [comment]
@thrzl how much memory does stock Firefox use on your device with one tab open?

**Comment by subhashhhhhh** [comment]
> @thrzl how much memory does stock Firefox use on your device with one tab open?

not more than 1GB

![CleanShot 2024-08-24 at 15 34 41@2x](https://github.com/user-attachments/assets/e07b4e58-7b27-406c-9f2f-240016a4b940)

**Comment by thrzl** [comment]
> @thrzl how much memory does stock Firefox use on your device with one tab open?

Firefox actually also uses 800MB, and as more tabs are added, Firefox actually uses _more_ ram than Zen. I was unaware that Firefox itself used this much memory.

As a workaround I've installed Auto Tab Discard which helps a bit, but this still is preventing me fom using this browser as much as I'd like to.

**Comment by vunhatchuong** [comment]
![image](https://github.com/user-attachments/assets/f1d17bd7-6c84-4c4f-84b2-f29b993d559c)
Yeah this is a lot, I usually observe Firefox use max of 2GB with more tabs than I have right now.

**Comment by vunhatchuong** [comment]
A single Twitch stream tab hogs 2GB.

**Comment by IAmJafeth** [comment]
Hey @mauro-balades 

Can this be a kind of memory leak? my brother (the guy that we play overwatch with) reports this happens to him when he leaves Zen open all night, it reaches 5000mb.

But if he closes it and opens it again it get backs to normal (300mb)

**Comment by CarrotRub** [comment]
Also had the same issue and it seems that Zen does not really close tabs nor minimize their consumption of RAM while being inactive or even closed.
Also, on a clean open with only github opened, firefox uses 190MB whereas Zen uses more than 350MB and more CPU usage.

It is sad because Zen looked like a great alternative, and as @IAmJafeth proposed, it is probably a memory leak or lack of limit on inactive tabs but I hope it will be fixed soon.

**Comment by niutech** [comment]
What does `about:processes` and `about:memory` show?

**Comment by niutech** [comment]
@thrzl The single most memory consuming process from your report is web extensions:
```
{
    "process": "WebExtensions (pid 48502)",
    "path": "vsize",
    "kind": 2,
    "units": 0,
    "amount": 440066981888,
    "description": "Memory mapped by the process, including code and data segments, the heap, thread stacks, memory explicitly mapped by the process via mmap and similar operations, and memory shared with other processes. This is the vsize figure as reported by 'top' and 'ps'.  This figure is of limited use on Mac, where processes share huge amounts of memory with one another.  But even on other operating systems, 'resident' is a much better measure of the memory resources used by the process."
}
```

**Comment by lee-orr** [comment]
Over time - the memory use grows. I've eventually had it consume 40GB with just 10 tabs - all of which were static.

**Comment by niutech** [comment]
Does it help when you go to `about:memory` and click _Minimize memory usage_? Or when you install [Auto Tab Discard](https://addons.mozilla.org/en-US/firefox/addon/auto-tab-discard/) add-on?

**Comment by thrzl** [comment]
> @thrzl The single most memory consuming process from your report is web extensions:
> 
> ```
> {
>     "process": "WebExtensions (pid 48502)",
>     "path": "vsize",
>     "kind": 2,
>     "units": 0,
>     "amount": 440066981888,
>     "description": "Memory mapped by the process, including code and data segments, the heap, thread stacks, memory explicitly mapped by the process via mmap and similar operations, and memory shared with other processes. This is the vsize figure as reported by 'top' and 'ps'.  This figure is of limited use on Mac, where processes share huge amounts of memory with one another.  But even on other operating systems, 'resident' is a much better measure of the memory resources used by the process."
> }
> ```

This itself is questionable, as the only extensions I have are uBlock Origin, Auto Tab Discard, and an au2001's [iCloud Keychain](https://github.com/au2001/icloud-passwords-firefox) extension.

I also wanted to ask what unit the memory usage is being measured in here?

**Comment by lee-orr** [comment]
At least on my end - it's definitely part of the main process rather than one of the individual tabs:
```
Main Process (pid 22568)
Explicit Allocations

24,112.50 MB (100.0%) -- explicit
├──23,704.16 MB (98.31%) -- js-non-window
│  ├──23,347.38 MB (96.83%) -- zones
│  │  ├──23,336.88 MB (96.78%) -- zone(0x12306de00)
│  │  │  ├──22,966.69 MB (95.25%) -- strings
│  │  │  │  ├──22,926.52 MB (95.08%) -- string(length=333802, copies=22926, "First Name,Last Name,Office/Title,Organization (non-gov't),Public Official?,Public Office/Affiliation,Constitutional Sheriff?,Fake Elector?,Hand Count Activist?,ERIC Withdrawal?,ALEC?,January 6?,Role (delete after data entry),Activist?,National/Multi-State Activist?,States (separate w commas),County Name (separate w commas),County FIPS Code,City/County FIPS,Election Denier?,Election Subverter?,High profile/Priority?,Active?,AO/External Link 1,AO/External Doc Name 1,AO/External Link 2,AO/External Doc Name 2,Notes (do not delete/may edit),First pass data cleaning complete?,Final Quality Control Coding Complete?,Quality Control Check Initials,Final Map Recommendation,/r/nMike,Dunleavy,AK Governor,,Yes,Governor,No,No,,,,,,No,No,AK,,,,Yes,Yes,No,Yes,,,,,SUDC election denier,YES,NO,,,/r/nDavid,Eastman,AK State Representative,,Yes,State Legislature,No,No,,,,,,No,No,AK,Matanuska-Susitna,,,Yes,Yes,No,Yes,,,,,,YES,NO,,,/r/nChristopher,Kurka,Former candidate for AK Governor,,No,Candidate or Former Candidate,No,No,,,,,," (truncated))
│  │  │  │  │  ├──22,926.00 MB (95.08%) ── malloc-heap/two-byte
│  │  │  │  │  └───────0.52 MB (00.00%) ── gc-heap/two-byte
│  │  │  │  └──────40.16 MB (00.17%) ++ (106 tiny)
│  │  │  └─────370.19 MB (01.54%) ++ (26 tiny)
│  │  └──────10.50 MB (00.04%) ++ (2 tiny)
│  ├─────303.96 MB (01.26%) ++ gc-heap
│  └──────52.83 MB (00.22%) ++ (3 tiny)
└─────408.34 MB (01.69%) ++ (34 tiny)

Other Measurements

23,213.30 MB (100.0%) -- decommitted
├──23,196.80 MB (99.93%) -- heap
│  ├──23,038.01 MB (99.24%) ── decommitted
│  └─────158.80 MB (00.68%) ++ unused-pages
└──────16.50 MB (00.07%) ++ (2 tiny)

```

**Comment by niutech** [comment]
@lee-orr What is this `string(length=333802, copies=22926, "First Name,Last Name,Office/Title..." (truncated))`?

**Comment by lee-orr** [comment]
> @lee-orr What is this `string(length=333802, copies=22926, "First Name,Last Name,Office/Title..." (truncated))

One of the tabs I had open had a csv in a text editor - strange that it ended up so large since the csv was just sitting open. I'll investigate this further in case it's an issue with that web page, and see if the memory issue occurs without that page.

**Comment by AtTheZenith** [comment]
Yep, it's a memory leak, and like stated above, one process is responsible for it, probably is the extensions manager.
![image](https://github.com/user-attachments/assets/0b9f7535-3ff4-4b53-b1ac-992b72da4b49)

**Comment by niutech** [comment]
@AtTheZenith What does `about:memory` report? What if you open Zen in safe mode? (press and hold the Shift key and launch Zen)

**Comment by AtTheZenith** [comment]
> @AtTheZenith What does `about:memory` report? What if you open Zen in safe mode? (press and hold the Shift key and launch Zen)

1.2gb ram usage (in safe mode) under normal workload,
and surprisingly, i can't reproduce it anymore, 1.6gb ram in a normal window under normal workload, i can live with this.

**Comment by MariuszGaljanVT** [comment]
In my case, high memory consumption comes mainly from pinned tabs and Sidebar panels, which it would seem are never unloaded e.g. Meta's Messenger consumes about 300MB of RAM.

As @thrzl mentioned, Auto Tab Discard definitely helps here. For now, the best workaround I found was adding such memory intensive websites to **Immediately discard the following hostnames when their tab is not active** domain list.

I also noticed this extension does not work with Zen Sidebar panels, which are also kept in memory

**Comment by AtTheZenith** [comment]
i forgot to mention task killing the memory intensive program (that was consuming 3 out of 5 gb) kills my youtube tab

**Comment by Humam-Hamdan** [comment]
agreed, i have 16gb, when i let zen open and load thee moodle tabs is goes to 8gb of ram, it just crashed my whole system, needed to hard poweroff if, using the flatpak on ubuntu 24.04.01

**Comment by nneto** [comment]
At work, I have a machine with 32GB that was topped up while using Zen for some hours. Checking the System Monitor, there was one "Isolated Web Co" consuming over 20GB! I just installed it yesterday and was browsing the same webpages I used in Chrome, and with the same extensions I have installed and in sync with Firefox.

**Comment by greeeen-dev** [comment]
From what I've heard in their Discord server, this is normal behavior, and memory usage will decrease if you have more processes open:
<img width="494" alt="image" src="https://github.com/user-attachments/assets/d6fad072-2ff8-4e74-85dd-63bfec13a3a7">
<img width="297" alt="image" src="https://github.com/user-attachments/assets/4986e91d-40a1-47b6-bccd-265ef5f98ec6">

As for macOS though, it seems like a Firefox thing, I've experienced the same there too (MacBook Air M1)

**Comment by nneto** [comment]
> From what I've heard in their Discord server, this is normal behavior, and memory usage will decrease if you have more processes open: <img alt="image" width="494" src="https://private-user-images.githubusercontent.com/41323182/369103568-d6fad072-2ff8-4e74-85dd-63bfec13a3a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3NjcyMzQsIm5iZiI6MTcyNjc2NjkzNCwicGF0aCI6Ii80MTMyMzE4Mi8zNjkxMDM1NjgtZDZmYWQwNzItMmZmOC00ZTc0LTg1ZGQtNjNiZmVjMTNhM2E3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDE3Mjg1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyYjdhYzhkYzYxM2ZkMzQ2NTg2ODE0MWY5Nzg0M2I0YzZiOWJhZmZiYzRjMGIzZmEzODhkMjEzZmU3ODRhNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YjgwGcIdOegLqQEP9PFdITpseXvq_y7KraGBM2VkRe4"> <img alt="image" width="297" src="https://private-user-images.githubusercontent.com/41323182/369103603-4986e91d-40a1-47b6-bccd-265ef5f98ec6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3NjcyMzQsIm5iZiI6MTcyNjc2NjkzNCwicGF0aCI6Ii80MTMyMzE4Mi8zNjkxMDM2MDMtNDk4NmU5MWQtNDBhMS00N2I2LWJjY2QtMjY1ZWY1Zjk4ZWM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDE3Mjg1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxMDljNmU3ZWJhOWM3YTFiODI3MTQ1Y2RkNzVlODk2OTNmODAxYWM3Y2M4YTJiYjQwMDZjNjhiMzQwMThmMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DG9Vi67zBzDBsOHzmuAYYr9qiNazf0rjhN58FT9PJCc">
> 
> As for macOS though, it seems like a Firefox thing, I've experienced the same on that browser too so it's most likely not a Zen issue (MacBook Air M1)

In my case, it consumed so much RAM that vscode crashed for lack of memory

**Comment by piavgh** [comment]
![image](https://github.com/user-attachments/assets/2f74957b-6504-4619-a713-761e7e4a6a2e)

This is the memory usage on my Macbook (36 GB Ram)
- Zen has only 1 tab (Youtube video)
- Chrome has 13 tabs (1 Youtube video)

I often see meme about Chrome eating too much Ram, but now I see that Zen browser is eating even more

**Comment by niutech** [comment]
@piavgh What does `about:processes` show?

**Comment by piavgh** [comment]
> @piavgh What does `about:processes` show?

@niutech : how to navigate to that menu? I don't see about:processes anywhere

**Comment by niutech** [comment]
@piavgh Type it in the Zen Browser's address bar.

**Comment by piavgh** [comment]
> @piavgh What does `about:processes` show?

<img width="1321" alt="image" src="https://github.com/user-attachments/assets/4c4f1a6c-5e4e-4058-8e81-76926d87b2c8">

Here, sometimes it drops to 6xx MB, but most of the times, it's 8xx MB

**Comment by chenasraf** [comment]
From my experience it is almost definitely something to do with video playback or streaming, as this always reproduces for me (at some point) while watching YouTube videos

I tried to trace the Zen process while I could, hope this helps

Link: https://share.firefox.dev/4ertH72

![image](https://github.com/user-attachments/assets/7283b33f-d48b-4ac7-bf34-b2916f66f692)


These is my `about:processes` page, I took the screenshot too late, when I took the profile, Zen Browser (the main thread, NOT the YouTube one) was taking 110-130% CPU usage and RAM was at 1 GB

![SCR-20241001-nojh](https://github.com/user-attachments/assets/405905fb-36d1-435f-abcc-178861437b24)

**Comment by niutech** [comment]
For me it is GPU process which takes the most of RAM on fresh startup:
![Zen Browser about:processes](https://github.com/user-attachments/assets/111bae2e-db21-4583-9b07-b85fd3f9cb25)

**Comment by greeeen-dev** [comment]
Since RAM usage goes up as I keep Firefox/Zen open for longer, I'm starting to think it's the cache on RAM that's causing this...I'll check how RAM usage changes over time when `browser.cache.memory.enable` is set to false

**Comment by kahveciderin** [comment]
Exact same issue here, MacOS aarch64 with zen 1.0.1-a.10, fresh install. The memory usage reaches to around ~8-10gb with three tabs open.

I've actually had to troubleshoot such an issue on stock Firefox, and noticed that the issue was the Multi Account Containers extension. I've had that extension eat up to 5 gigabytes of memory alone, on regular Firefox. Maybe this might be relevant since as far as I can see, that extension is included in zen by default.

**Comment by kanielrkirby** [comment]
Same issue here, Macbook Pro M1 (8 GB RAM), and memory usage maxed out while running overnight saying it had a footprint of 80 GB. Never seen that before! I had to kill the process and then restart it and everything worked fine.

**Comment by mr-cheffy** [comment]
Yeah, some containers are known for doing memory leaks. Ill close this issue as it has been answered before

**Comment by kahveciderin** [comment]
@mauro-balades it's nice that this is known, however is there an issue to track when this is going to be fixed?

**Comment by thrzl** [comment]
Additionally, is there a way to disable the extension/feature in Zen?

**Comment by n7itro** [comment]
@thrzl yes, you can disable it in `about:addons`

**Comment by mr-cheffy** [comment]
> @mauro-balades it's nice that this is known, however is there an issue to track when this is going to be fixed?

It's mostly how bad extensions are done, I can't do much about it.

Nite: I said containers but I meant extensions/addons

**Comment by niutech** [comment]
@mauro-balades This issue is not done. The stock Zen Browser without any extra addons uses huge amount of RAM. My Zen instance shows 0 addons in `about:addons`, so there is nothing to disable. Zen should be slimmed down out-of-the-box in order to complete this issue.

**Comment by mr-cheffy** [comment]
What version are you on?

**Comment by niutech** [comment]
@mauro-balades Version 1.0.1-a.12. Upon fresh startup, without any web pages open, it takes whooping ~600 MB of RAM, from which the most memory-consuming process is the GPU:

![image](https://github.com/user-attachments/assets/5656cb5a-ec32-4507-be45-e2a342a5cf1b)

**Comment by Mil0dV** [comment]
@niutech can you compare with Firefox with the same version? I'd suggest comparing with no tabs open and e.g. 5-10 sites open in both. In about:memory you can dive into what's using memory. They gpu mem usage you see is prob webrender, but that should be more efficient than not using webrender.

I'd say that, unless settings were changed in one of the two, mem usage should be quite similar, and outside of Zen's control - it's quite an undertaking to change that would need to be done in firefox itself.

**Comment by n7itro** [comment]
@niutech 600mb is very little memory usage for a web browser. Especially if you have 8gb or more total ram

**Comment by mauro-balades** [comment]
I thought we where talking about zen using 6GB of ram kind of thing 😭

**Comment by niutech** [comment]
@Mil0dV Firefox 131.0.3 uses much less RAM on startup:

![Firefox processes](https://github.com/user-attachments/assets/b15d10a1-b244-4962-8e1f-287faf0284fa)

We are talking about the freshly opened web browser, without any website loaded. Using >0.5 GB of RAM just for this is way too much. Compare it to the latest Chromium, which takes <100MB upon fresh startup:

![Chromium processes](https://github.com/user-attachments/assets/163a6ac4-9990-4633-9771-af91cb97dd9a)

or Pale Moon, which takes <200 MB on startup:

![Pale Moon processes](https://github.com/user-attachments/assets/7cec0a94-13fb-4e13-ac60-508c84618dcf)

When we open multiple tabs in Zen, the RAM usage goes to the roof. There is room for improvement. Maybe incorporate some of the [Fastfox](https://github.com/yokoffing/Betterfox/blob/main/Fastfox.js) prefs, like [these ones](https://www.reddit.com/r/browsers/comments/14ppusv/comment/jrvrva3/)?

**Comment by thrzl** [comment]
I got the chance to try those prefs, and they work great for me. Memory usage does still increase a little over time, but by nowhere near as much as before.

**Comment by inoyakaigor** [comment]
I've just ran a portable version for win and even finish initial step but the browser already consumes 1.1+ GB:
![Снимок экрана 2024-11-07 141121](https://github.com/user-attachments/assets/db36e3da-d124-4d20-859e-2840dd78c80d)
while I tried make this screenshot the browser released a bit of memory:
![Снимок экрана 2024-11-07 141214](https://github.com/user-attachments/assets/85b3e3f7-7940-4c97-a923-c1e4b0ea1a92)

**Comment by niutech** [comment]
@mr-cheff Please reopen this as the RAM consumption is still an issue (see e.g. #3299).

**Comment by mr-cheffy** [comment]
There are already tons of issues created with this issue. Let's try to not duplicate but if you really need to, let me know

**Comment by VesperQuartz** [comment]
Mine is using 10GB of Ram

**Comment by Kae-Tempest** [comment]
Up to 23/24 GB of Ram, Ram most using with mediaplayer

**Comment by ShreyanshVishwakarma** [comment]
Mine used 3gb of ram, but after I restarted zen it now takes up 1gb with similar number of tabs.

**Comment by Coder-Harshit** [comment]
i dont get it ... what is the conclusion ?? ... is there some bug or not ... is there some kind of remedy to solve this memory consumption issue ?

please provide some kind of faster sleeker option at least if the end user want to minimize customisation and focus on performance (at least at some point in time)

**Comment by niutech** [comment]
@Coder-Harshit The issue is still unresolved IMO. The RAM usage is much higher than Firefox as a baseline. Some workaround is to use [Fastfox](https://github.com/yokoffing/Betterfox/blob/main/Fastfox.js) prefs, like [these ones](https://www.reddit.com/r/browsers/comments/14ppusv/comment/jrvrva3/), which seem to work, according to https://github.com/zen-browser/desktop/issues/504#issuecomment-2431782155.

**Comment by ShayBox** [comment]
![Image](https://github.com/user-attachments/assets/df61cc8d-c236-45f4-97fa-6cedd3698419)

26GB, happens nearly daily. This bug seems to scale with your ram capacity (64GB)

**Comment by ShayBox** [comment]
I have to switch browsers, I can't keep having my computer freeze because a web browser is using all my ram

![Image](https://github.com/user-attachments/assets/d1cb6ae2-1f2e-470c-868c-85119250b96e)

I have a single tab, I'm just watching YouTube.

**Comment by rabume** [comment]
I have around 20 tabs in diff workspaces, but not all are loaded. In brave or chrome, I never have this amount of ram usage.

![Image](https://github.com/user-attachments/assets/37a39876-f91f-4279-a653-184a03872e0d)

**Comment by rabume** [comment]
Why is this closed?

Even with this custom user.js

> [@Coder-Harshit](https://github.com/Coder-Harshit) The issue is still unresolved IMO. The RAM usage is much higher than Firefox as a baseline. Some workaround is to use [Fastfox](https://github.com/yokoffing/Betterfox/blob/main/Fastfox.js) prefs, like [these ones](https://www.reddit.com/r/browsers/comments/14ppusv/comment/jrvrva3/), which seem to work, according to [#504 (comment)](https://github.com/zen-browser/desktop/issues/504#issuecomment-2431782155).

It eats up 4.5GB with one yt tab. (And a lot of not loaded tabs).
After normal usage, I'm up to 10GB or more.

**Comment by NazikMGE** [comment]
Same issue.

![Image](https://github.com/user-attachments/assets/2691330a-c418-4969-a225-e73ab8274f1f)

**Comment by xTararAisx** [comment]
![Image](https://github.com/user-attachments/assets/06e7b908-8fed-46ed-b657-8c954713ff8c)

Same exact issue, 3 tabs opened, "Auto Tab Discard" on, this is ridiculous, I changed mainly because people said it was lighter than chrome, my *ss

**Comment by kahveciderin** [comment]
> ![Image](https://github.com/user-attachments/assets/06e7b908-8fed-46ed-b657-8c954713ff8c)
> 
> Same exact issue, 3 tabs opened, "Auto Tab Discard" on, this is ridiculous, I changed mainly because people said it was lighter than chrome, my *ss


i also experience performance issues, but hey no need to be rude to people trying to give us an awesome browser for free

**Comment by xTararAisx** [comment]
> > ![Image](https://github.com/user-attachments/assets/06e7b908-8fed-46ed-b657-8c954713ff8c)
> > Same exact issue, 3 tabs opened, "Auto Tab Discard" on, this is ridiculous, I changed mainly because people said it was lighter than chrome, my *ss
> 
> i also experience performance issues, but hey no need to be rude to people trying to give us an awesome browser for free

awesome? I must have missed that part, this feels like an alpha build which may not have been optimized yet, far from being "awesome", its beautiful, however im not planning on getting laid with the browser so yh, efficiency is what people is looking for at the end of the day

EDIT: im a dickhead, was dickhead mood, sorry

**Comment by kahveciderin** [comment]
> > > ![Image](https://github.com/user-attachments/assets/06e7b908-8fed-46ed-b657-8c954713ff8c)
> > > Same exact issue, 3 tabs opened, "Auto Tab Discard" on, this is ridiculous, I changed mainly because people said it was lighter than chrome, my *ss
> > 
> > i also experience performance issues, but hey no need to be rude to people trying to give us an awesome browser for free
> 
> awesome? I must have missed that part, this feels like an alpha build which may not have been optimized yet, far from being "awesome", its beautiful, however im not planning on getting laid with the browser so yh, efficiency is what people is looking for at the end of the day

i get the frustration but i don't think being rude to maintainers providing free software helps. let's try to keep things constructive and on-topic.

**Comment by xTararAisx** [comment]
> > > > ![Image](https://github.com/user-attachments/assets/06e7b908-8fed-46ed-b657-8c954713ff8c)
> > > > Same exact issue, 3 tabs opened, "Auto Tab Discard" on, this is ridiculous, I changed mainly because people said it was lighter than chrome, my *ss
> > > 
> > > 
> > > i also experience performance issues, but hey no need to be rude to people trying to give us an awesome browser for free
> > 
> > 
> > awesome? I must have missed that part, this feels like an alpha build which may not have been optimized yet, far from being "awesome", its beautiful, however im not planning on getting laid with the browser so yh, efficiency is what people is looking for at the end of the day
> 
> i get the frustration but i don't think being rude to maintainers providing free software helps. let's try to keep things constructive and on-topic.

You sound as fragile as woke chatgpt, I was stating a problem as others did, dont be so fragile and focus on "rudeness", focus on the issue some of us already left kindergarten, I even used * ffs

**Comment by Satyamaaan** [comment]
![Image](https://github.com/user-attachments/assets/7660c4d1-bb47-4498-ab35-7381febd7c4b)

By the way, I forcefully closed a process that was consuming 12 gigabytes of memory before taking this screenshot. Still it's consuming way too much memory. I had switched from ARC, which was facing the same memory usage issue there.

How is the community’s sentiment about this? I have faith in the ZEN development team; they will certainly fix this issue. However, it’s significantly hindering my daily workload, and I can’t continue using it. Is there any workaround for this problem? or just should I revert to Chrome?

**Comment by ShayBox** [comment]
> i get the frustration but i don't think being rude to maintainers providing free software helps. let's try to keep things constructive and on-topic.

I would normally agree, if the maintainers actually participated in these issues, acknowledged the issue, but if you haven't noticed, this issue is closed, and all the other ones. They're ignoring it, and us, that doesn't earn respect.

I've moved on, Firefox's built-in sidebar is better than Zens now anyway, I don't have to deal with it anymore, and never will.

**Comment by xDeFc0nx** [comment]
still an issue

**Comment by Blueflier** [comment]
the further i scrolled down the less hope i had in finding a fix ;-;

**Comment by Avroboros** [comment]
> EDIT: im a dickhead, was dickhead mood, sorry

Don't apologize and bend the knee. If a product markets itself as "lightweight" and a "better alternative" to other browsers, you have every single right to question and give shit to the quality of the product.

Also, from what I've been observing, this browser has a lot of fanboys who get butthurt over the most minor criticism given to this app. So the accountability should be even harsher. A better alternative my ass indeed.

**Comment by mr-cheffy** [comment]
Is it being marketed as lightweight?

**Comment by niutech** [comment]
It doesn't need to be lightweight like Pale Moon, it shouldn't be more
bloated than the OG Firefox.

**Comment by niutech** [comment]
There is now a meta issue #8932 for high RAM usage.

**Comment by gabriel-hsb** [comment]
For me it was the wappalizer extension. Disabled it and the RAM consumption got considerably lower.
Take a look at `about:processes`

**Comment by Borber** [comment]
In my practice, I've found that turning off GPU acceleration helps to reduce memory usage and free up

**Comment by niutech** [comment]
But it's like throwing the baby out with the bathwater. GPU
acceleration is helpful.

**Comment by merchako** [comment]
Acccording to CleanMyMac, Zen is using **12 GB** of memory for ~20 tabs. 

Meanwhile, Zen's `about:processes` says it's using **5 GB** of memory. What accounts for the difference?


<img width="424" height="714" alt="Image" src="https://github.com/user-attachments/assets/4a78f029-c63b-4525-9ace-e5f91c5caf8e" />

(The only extensions I have are Apple Passwords and Firefox Multi-Account Containers.)

**Comment by everyoneexe** [comment]
[memory-report.json.gz](https://github.com/user-attachments/files/23723129/memory-report.json.gz)

<img width="1141" height="699" alt="Image" src="https://github.com/user-attachments/assets/35bda1a9-d52b-4bfe-af38-1e5d7c1d5b85" />

 Zen uses 5.5 GB of memory for 9 tabs.

I noticed that CPU usage increases when I move the cursor, rising from 20% to 70%.

<img width="1592" height="62" alt="Image" src="https://github.com/user-attachments/assets/e3ebcd36-0e86-46c5-be57-360c4bc0dd66" />

ps: after disabled hardware acceleration:

[memory-report-after-disable.json.gz](https://github.com/user-attachments/files/23723574/memory-report-after-disable.json.gz)

<img width="1119" height="680" alt="Image" src="https://github.com/user-attachments/assets/97dcbbf1-e7e6-4484-8450-f50db5f61c13" />

system information:
```
Linux 6.17.8-1-cachyos
niri (Wayland)
```

**Comment by Aroshold** [comment]
A single open RTC stream gives +400MB increase in memory usage per minute

**Comment by linuxmobile** [comment]
Why is marked as closed?

**Comment by Aroshold** [comment]
> Why is marked as closed?

All performance issues have been moved into a separate metaissue
