### ISSUE TITLE
Change the "Search the web" shortcut functionality

### ISSUE THREAD

**Issue by malaow3** [zen-browser/desktop#506]
### What feature would you like to see?

When this is toggled, it first defaults to searching with Google instead of just searching the web OR navigating to a website. It would also be nice if this could open items in a new tab or be used to navigate to currently open tabs.

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/816

 ~ This is an automatic operation to better enhancements requests organization.
