### ISSUE TITLE
"Zen Browser Support" Link in settings leads to Firefox support page

### ISSUE THREAD

**Issue by LeMoonStar** [zen-browser/desktop#507]
### What happened?

The bottom of the menu on the settings page contains a link called "Zen Browser Support".
This Link still leads to `https://support.mozilla.org/1/firefox/{version}/{platform}/{Language}/preferences`, however containing the version string of Zen.

As Mozilla likely doesn't offer support for Zen, and the provided description of the Settings page doesn't match Zen, this link should probably be changed to point to this issue tracker or Zen's own website.

![image](https://github.com/user-attachments/assets/8ca59587-2364-43f0-8f80-6bc3a6c17094)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.28

### Severity impact

Low

### What platform are you seeing the problem on?

Linux

**Comment by DrLarck** [comment]
Hey! Wouldn't it preferable (at least for now) to redirect to the [Zen's FAQ](https://docs.zen-browser.app/faq) web page instead of Zen's website or Zen's Github Issues list?

**Comment by LeMoonStar** [comment]
@dosu Yes, this is still relevant.

**Comment by neurokitti** [comment]
on purpose. we don't want to make our own support page.
