### ISSUE TITLE
There is no way to change shortcuts for switching between different tabs?

### ISSUE THREAD

**Issue by pokhrelashok** [zen-browser/desktop#508]
### What feature would you like to see?

Currently Alt+number switches between tabs, and it doesn't look like there is a way to change that? I have my ctrl and alt keys swapped, so I would like to be able to change the shortcut to be ctrl+number instead. 

### What platform are you seeing the problem on?

Linux

**Comment by Inovvia** [comment]
Have you tried this extension - https://addons.mozilla.org/en-US/firefox/addon/addressable-tabs/

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/815

 ~ This is an automatic operation to better enhancements requests organization.
