### ISSUE TITLE
sfx for new tab/ keyboard

### ISSUE THREAD

**Issue by Scorpliet** [zen-browser/desktop#509]
### What feature would you like to see?

sound effects like opera gx does for keyboard taps and opening new tabs.

### What platform are you seeing the problem on?

Windows

**Comment by Scorpliet** [comment]
This can be lower priority, but the sfx really adds to the comfort of using a custom browser, additionally i got used to the sound

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/814

 ~ This is an automatic operation to better enhancements requests organization.
