### ISSUE TITLE
Installing uBlock Origin breaks Zen and causes it to turn red?

### ISSUE THREAD

**Issue by SomeDudeBrosky** [zen-browser/desktop#51]
It also is not listed as an installed extension?

![image](https://github.com/user-attachments/assets/ea188fde-0f94-444e-aa4d-cb8a4397503a)
![image](https://github.com/user-attachments/assets/6f9e61c4-52dd-420f-914e-45f6fecb875b)

**Comment by mauro-balades** [comment]
What theme do you have?

**Comment by SomeDudeBrosky** [comment]
I have the default theme that is pre installed.

**Comment by mauro-balades** [comment]
could you show me a screenshot of the theme's page?

**Comment by SomeDudeBrosky** [comment]
The “theme” I have is the color settings you configure when first installing the browser. There is nothing else installed.

**Comment by mauro-balades** [comment]
yeah but I do need to look at the themes you have activated because one of the builtin themes is broken and has that issue, I just need to confirm it was that. I tried installing all the extensions you have listed and I was not able to replicate the issue

**Comment by SomeDudeBrosky** [comment]
![image](https://github.com/user-attachments/assets/07f3cae5-b996-4fc1-aa63-f298df75af09)
In order to fix the issue, I needed to fully recompile, and after going through the steps I took I as well am unable to replicate it. I am unsure as to what may have created it.

**Comment by mauro-balades** [comment]
No idea either, ill just close it and if it appears again, please let me know!
