### ISSUE TITLE
Compact mode with expanded tabs will prevent clicking on items on the left side of websites

### ISSUE THREAD

**Issue by SpaceGoat04** [zen-browser/desktop#511]
### What happened?

As of the latest version, using compact mode with expanded tabs will result in a wider hover area than with collapsed tabs, which will result in some website buttons not being clickable, for example the button to the left of the YouTube logo, as shown in this video:

https://github.com/user-attachments/assets/1e979e93-7185-4676-9bb2-7bbcd6e98bea

Collapsed tabs don't show this behavior, making expanded tabs unusable on some websites that have clickable contents on their left side (for example the server panel from Discord). Having the same hover area as the collapsed tabs mode should fix this issue.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.28

### Severity impact

Medium

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
Will be fixed for the next release 👍

**Comment by Thanaen** [comment]
I can confirm that it's quite annoying on several sites
![zen-compact-hover-issue](https://github.com/user-attachments/assets/8217022b-48d3-48ae-a784-3b3b61c1aef4)
![zen-compact-hover-issue-2](https://github.com/user-attachments/assets/570365b8-d4d3-4199-a9b8-08c01c036f00)
