### ISSUE TITLE
Enhance Split View

### ISSUE THREAD

**Issue by wordpure** [zen-browser/desktop#512]
### What feature would you like to see?

Edge's Split screen has some useful features, and I hope Zen's Split View can achieve similar results.

1. Load links opened in this tab in the opposite tab.
	PS: This feature doesn't seem to work for GitHub!

	https://github.com/user-attachments/assets/e7ec444d-b3c2-4ab0-9d3d-37655d2c5930

2. Force links to load in split view instead of new tab.

	https://github.com/user-attachments/assets/b6c757fb-6565-4417-abeb-d6b4a2ea063b

3. Open the split view via the context menu.

	https://github.com/user-attachments/assets/bb3b74ca-d525-4e9b-8d73-315b7c1a3b18

4. Preview other tabs and open it in split-screen view.
	The search box on this page is similar to the browser address bar and can load URLs or search text.

	https://github.com/user-attachments/assets/17309c1f-ce4c-41ae-a89c-7f25fa104441

5. Quickly trigger common actions such as swapping tab positions, opening in a new tab, etc.

	https://github.com/user-attachments/assets/dd4d1129-6621-4e0e-8f94-9517f3538c91

### What platform are you seeing the problem on?

Windows

**Comment by xxKeefer** [comment]
I would like to be able to resize the splits too, maybe that's competing with the Web panel. But I find my self wanting to make it a 33%/66% split.

**Comment by wgicio** [comment]
+1000 for all of these enhancements

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/813

 ~ This is an automatic operation to better enhancements requests organization.

**Comment by DesBw** [comment]
These are amazing recommendations. 
The first and the second are especially mandatory.
