### ISSUE TITLE
when opening new tab toolbar covers the tab bar its annoying

### ISSUE THREAD

**Issue by ProbablyM-S** [zen-browser/desktop#513]
### What happened?

the solution can be the tab bar appearing over toolbar?
https://github.com/user-attachments/assets/12ebd2d0-5eab-48d9-bc6f-8947bd9fff99

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

a.28

### Severity impact

Low

### What platform are you seeing the problem on?

Linux, macOS - aarch64, macOS - Intel, Windows

**Comment by NOCanoa** [comment]
It pic is broken xD

**Comment by ProbablyM-S** [comment]
> Your pic is broken xD

thats the thing :/ its not a pic lol its a video just click on the link

**Comment by salamijason** [comment]
Heylo, looks like this post was made a while back. Are you still getting this issue? (latest ver a.17 as of this comment)

**Comment by ProbablyM-S** [comment]
Yea you can self-check by just enabling compact mode and doing what I did in the video (uh the video doesnt open anymore ig) but jsut enable compact mode open new tab and you should be able to reproduce it

**Comment by salamijason** [comment]
Yes sorry I forgot to mention I did attempt to recreate it but couldn't get the issue you were talking about. I tried resizing the window to different sizes too and there was no overlap. If you could, please send a new video that shows what you're talking about. Thank you!

**Comment by ProbablyM-S** [comment]
https://github.com/user-attachments/assets/b6cc1c78-2fb1-43bc-a006-1d31eb9859d9

**Comment by ProbablyM-S** [comment]
https://github.com/user-attachments/assets/ccaabbeb-f5ff-4bbb-bdb1-496da35646dd

**Comment by ProbablyM-S** [comment]
https://github.com/user-attachments/assets/ccaabbeb-f5ff-4bbb-bdb1-496da35646dd

**Comment by salamijason** [comment]
Okay so I tried this again and this only happens if you have these settings: 
![image](https://github.com/user-attachments/assets/40b54d3e-6d49-4506-a244-720aacfd65ad)

BUT you've clicked on ctrl+alt+t to get the toolbar to stick and not get hidden.
I believe this is intentional. It looks like this because it keeps the toolbar as an overlay that's stuck.

IF instead you want something like this where there is no overlap: 
![image](https://github.com/user-attachments/assets/eca419e2-8e8b-41b9-8ba4-741f2e481b8f)


Set your settings to: 
![image](https://github.com/user-attachments/assets/1a082b6a-6357-429d-a1bb-fe1f23eac7f3)

Please let me know if my instructions were unclear. I'd be happy to help you out.

**Comment by ProbablyM-S** [comment]
are you serious? lol
I just enabled compact mode and this isn't intentional, this just can't be intentional, its an error. And needs to be fixed.
And I did not do anything else I just have both bars hidden when you open a new tab the browser focuses on the toolbar, its the default behavior and for good The simple solution to this would be to have the tabbar above the toolbar instead of vice versa.

**Comment by salamijason** [comment]
As I mentioned previously, with your settings, the toolbar gets stuck on as an overlay because you used the shortcut. Please watch the attached recording to see what I mean.


https://github.com/user-attachments/assets/9bcba1a6-9da5-488c-a836-e4e9a12db36c

**Comment by ProbablyM-S** [comment]
haha, yea I got what you mean but that's what I am trying to tell I did not use shortcut for toolbar you are not understanding my problem neither did you see my video I literally only opened new tab and the toolbar gets focused bc thats the normal behavior cuz every normal user when opened new tab he would search on the address bar which is why its focused as the default behavior I have never used the shortcut once in my lifetime.

**Comment by salamijason** [comment]
If what you mean is the toolbar coming into focus when going to the new tab, that's default behavior. And since it's the overlay toolbar, that's just how it is.

**Comment by ProbablyM-S** [comment]
? wow.... Thats just how it is? thats it? You said thats not the case and said I am triggering it with shortcut now you are saying its intended behaivior which I said to you 3 times but you didnt listen and what about my problem?? It isnt solved... Nor even investigated. Honestly you are giving me a stroke here.... You changed now. Yet I am giving you a stroke very nice....
