### ISSUE TITLE
Publish as msix

### ISSUE THREAD

**Issue by thomassth** [zen-browser/desktop#514]
### What feature would you like to see?

Firefox has a msix installer output option that makes it easier to deploy and install, and can use the msstore update system instead of its own updater. 

Ie. Zen can be put on MS store with little effort.

### What platform are you seeing the problem on?

Windows

### Additional context

https://firefox-source-docs.mozilla.org/browser/installer/windows/installer/MSIX.html%0A%0AStore%20listing:%20https://apps.microsoft.com/detail/9nzvdkpmr9rd?hl=en-us&gl=US

**Comment by NOCanoa** [comment]
There is no plan for an official msix installer.
