### ISSUE TITLE
Zen Browser is not opening on Windows 10

### ISSUE THREAD

**Issue by sudityashrivastav** [zen-browser/desktop#515]
### What happened?

After installing the browser it is not opening. An alert cames that is "The application was unable to start correctly (0xc0000142). Click OK to close the application."

See a video below

https://github.com/user-attachments/assets/a045d88b-10c7-478e-907c-aa5467385b3d

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.28 

### Severity impact

Critical

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
The application was unable to start correctly (0xc0000142). Click OK to close the application.
```

**Comment by NOCanoa** [comment]
Did I check the compatibility list, try generic version.
