### ISSUE TITLE
[BUG] [VISUAL] Tab list takes a second to disappear when entering fullscreen

### ISSUE THREAD

**Issue by styxpilled** [zen-browser/desktop#517]
### What happened?

When entering fullscreen, the tab list takes a second to disappear. The "native" Firefox elements disappear instantly. This can also be observed on Youtube, where the tab list disappears noticeably later than the topbar, though it's less intrusive as the fullscreening process is janky on Youtube.
Screenshot taken mid-fullscreen:
![image](https://github.com/user-attachments/assets/3c638afe-5951-46f6-a332-6fd5d1e8860b)
In addition, sometimes when exiting fullscreen the tab list will take 1-2 seconds to show tabs.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.28

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by qtchaos** [comment]
https://github.com/zen-browser/desktop/blob/92959769df875f6fa457a3a526b9a6a1d92ca6b5/src/browser/base/content/zen-styles/zen-tabs/vertical-tabs.css#L17
