### ISSUE TITLE
There is no shortcut for closing tabs in sidebar mode

### ISSUE THREAD

**Issue by VikramNagwal** [zen-browser/desktop#519]
### What feature would you like to see?

We need a feature to close the current tab easily by clicking on a close icon, but it's not possible in the sidebar nav.

image: 
![image](https://github.com/user-attachments/assets/12443e32-9359-4f33-8dd2-d7ca622ed6c7)

### What platform are you seeing the problem on?

Windows

**Comment by D4ario0** [comment]
Hi Vikram, this is a random internet user. I would encourage you to adopt a mouseless navigation using Ctrl + Tab (forward) or Ctrl +Shift +Tab(backwards) to navigate between tabs and Ctrl + W to close current tab. It is much faster IMO.

**Comment by ChrisJB24** [comment]
Hi Vikram, I found this frustrating too.  My solution has been to change one of the mozilla config settings which allows you to doubleclick on the tab icon to close it.

Type "about:config" in the address bar.
Search for "browser.tabs.closeTabByDblclick"
Click the arrows icon to change the setting to "true"
Close this tab

Now you can doubleclick on the minimized tab icon to close it.  You can reopen closed tabs with "CTRL+Shift+T".
Hope this helps, Chris

**Comment by yashptel** [comment]
> Hi Vikram, this is a random internet user. I would encourage you to adopt a mouseless navigation using Ctrl + Tab (forward) or Ctrl +Shift +Tab(backwards) to navigate between tabs and Ctrl + W to close current tab and Ctrl+T for New Tab, also these shortcuts are UNIVERSAL so you could do the same whether you use Chrome, Brave or Edge. It is much faster IMO.

What if I want to close the tab without going to that tab? Or for cases where I cannot use the keyboard. It's better to have options for basic functionalities imo

**Comment by PingTKP** [comment]
You can hover your cursor to the tab you want to close and use the middle mouse button to close it.

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/811

 ~ This is an automatic operation to better enhancements requests organization.
