### ISSUE TITLE
Can't see tab icons properly on pinned tabs

### ISSUE THREAD

**Issue by NandiyaLive** [zen-browser/desktop#52]
When a tab is pinned it hides from the tabs bar. To find it we have to click the arrow button or pin another tab. And tab icons on pinned tabs are not properly displaying in the tabs bar.

![image](https://github.com/user-attachments/assets/0813170a-bca7-4b44-8324-41fc9fb3aa79)

**Comment by mauro-balades** [comment]
with in https://github.com/zen-browser/desktop/commit/9d6cf0cb6c79d03083699c2a607a4d954db81c16, thanks a lot!
