### ISSUE TITLE
Sidebar pop-out in compact mode makes important webpage components inaccessible.

### ISSUE THREAD

**Issue by LeMoonStar** [zen-browser/desktop#520]
### What happened?

While in compact mode hovering close to the left edge of a webpage makes the sidebar pop out.
Many websites, such as GitHub, YouTube etc. place important components right at that side.
This makes accessing these components impossible while in compact mode.

An Example when using GitHub:
Clicking on the Hamburger Menu or Code Tab is impossible while in Compact mode, as the Sidebar pops out way too early.

https://github.com/user-attachments/assets/c584bce6-812c-4fe8-9cd0-599ced55ea46

A possible solution is popping the sidebar out when hovering over the margin between web-content and window border.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.28

### Severity impact

Medium

### What platform are you seeing the problem on?

Linux

**Comment by kyerlasswell** [comment]
I have found this frustrating as well. I noticed if you set the side bar to be collapsed, the hover area is much more practical and allows you to reach these elements. I think if the expanded sidebar used the same hover area as the collapsed version, that would probably be okay.

**Comment by sameer1612** [comment]
Can we add a flag to disable showing sidebar on move movement in the left area. It is pretty convenient with the keyboard shortcut anyways.

**Comment by TiLopes** [comment]
I think the hover area should be the same as the top toolbar, when compact mode is enabled, where the mouse has to be outside of the page (basically all the way to the left/right for the sidebar).

**Comment by sameer1612** [comment]
> I think the hover area should be the same as the top toolbar, when compact mode is enabled, where the mouse has to be outside of the page (basically all the way to the left/right for the sidebar).

Yeah it makes sense to show the sidebar when cursor touches the edge. We anyhow have a little padding to get a decent mouse detection area. 💯

**Comment by EnmaDarei** [comment]
Yeah, this is my biggest issue with the browser. The hover area's width needs to be reduce by quite a bit.

**Comment by mauro-balades** [comment]
This is fixed for the next release 👍

**Comment by mauro-balades** [comment]
F
