### ISSUE TITLE
"Close Tabs to Right/Left" in vertical tabs

### ISSUE THREAD

**Issue by BramLeisink** [zen-browser/desktop#521]
### What happened?

It is showing "Close Tabs to Right" or "Close Tabs to Left" in the "Close Multiple Tabs" menu. This text should be changed to something like "Close Tabs Above/Below", because of the vertical tabs. I don't remember having this bug before I updated to the newest version.

![image](https://github.com/user-attachments/assets/89f2d0fa-d89d-4a3a-88e8-7ebb36a89458)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.28

### Severity impact

Low

### What platform are you seeing the problem on?

Linux

**Comment by Zykkl** [comment]
Correct me if I'm mistaken, but this seems like a small change in the localization packs, right?

**Comment by BramLeisink** [comment]
I definitely think the issue is related to the localization packs, as the text changed at the same time those packs were created. However, I don't believe it's as simple as just modifying the packs—though I could be overlooking something.

Could this be related to the issue? https://github.com/zen-browser/l10n-packs/blob/cba2da16c3aaee9d2e239204b66fef3dfececd74/en-US/browser/browser/zen-vertical-tabs.ftl

**Comment by zSoulweaver** [comment]
Haven't done much research into the topic, but the i10n repo above was a good start. It looks like Zen's i10n repo is specifically for new strings that Zen adds, it then copies the Firefox pack over the top here [scripts/download-language-packs.sh](https://github.com/zen-browser/desktop/blob/main/scripts/download-language-packs.sh).

In the Firefox pack, they actually have strings specifially in relation to vertical tabs, which you can see on [L28-L41](https://github.com/mozilla-l10n/firefox-l10n/blob/75d8ca2b3092107bd8a7203b6209b45c36c140e2/en-GB/browser/browser/tabContextMenu.ftl#L28-L41), so hopefully it would be as simple as getting Zen to use those existing localization strings, however that is outside of my knowhow for this project, but it seeeeems simple enough. I imagine the `sidebar.verticalTabs` browser config would enable them, but I'm also guessing that breaks about 10 other things with Zen.
