### ISSUE TITLE
Upload File From Clipboard

### ISSUE THREAD

**Issue by ducksquaddd** [zen-browser/desktop#522]
### What feature would you like to see?

My all time favorite feature of any browser OperaGX is the fact when I click upload file I can upload straight from clipboard.
I always try to switch to different browsers, then when I end up needing to upload something I cant just upload from clipboard which I've gotten so used to doing.

It may be niche, but I think its generally something very useful.

### What platform are you seeing the problem on?

Windows

### Additional context

I dont think feature request should have the platform thing above.

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/810

 ~ This is an automatic operation to better enhancements requests organization.
