### ISSUE TITLE
Unify Zen's and Firefox's sidebars

### ISSUE THREAD

**Issue by Jak2k** [zen-browser/desktop#523]
### What feature would you like to see?

I would like to see Firefox's and Zen's sidebar merged into one.

### What platform are you seeing the problem on?

Linux

### Additional context

![image](https://github.com/user-attachments/assets/6e76d8fc-92cb-401c-9ba2-a423d992ee1e)

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/809

 ~ This is an automatic operation to better enhancements requests organization.
