### ISSUE TITLE
Sideloading Extensions

### ISSUE THREAD

**Issue by snakebite-382** [zen-browser/desktop#524]
### What feature would you like to see?

A few years back Firefox cut support for side loading your own custom extensions, I understand the security concerns around being able to load arbitrary extensions in the browser but it would be great if there was a properly supported system for super users to create their own custom extensions and then fully install them not just as a temporary extension.

### What platform are you seeing the problem on?

Linux

### Additional context

While there is support to load temporary extensions and you can use web-ext to run an ephemeral test browser during development I would like the ability not just to temporarily test my own extensions but to fully install them without having to get them approved by mozilla.

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/808

 ~ This is an automatic operation to better enhancements requests organization.
