### ISSUE TITLE
Hierarchical Tab Groups

### ISSUE THREAD

**Issue by AmitKumarMyT** [zen-browser/desktop#525]
### What feature would you like to see?

Hierarchical Organization:
-Allow users to create nested tab groups within a main tab group. This would enable a more intuitive and organized way to manage multiple open tabs, especially for those who frequently work with a large number of tabs.
-Visual Representation: The hierarchical structure should be visually represented using a tree-like view or similar method, making it easy for users to navigate and understand the relationships between different groups.
-Drag-and-Drop Functionality: Enable users to drag and drop tabs between different groups to reorganize them easily.

### What platform are you seeing the problem on?

Linux

### Additional context

similar to ARC browser tab groups

**Comment by jakoss** [comment]
Let's just call it what it is - take this one feature from Arc browser. It is the one thing that keeps me in arc, but i love the idea, customizability and performance of zen.

**Comment by shmarts** [comment]
same here - only thing keeping me on Arc after playing around with it a couple of hours now

**Comment by guigirl42** [comment]
Isn't this just basically the same objective as _existing_ Requests  https://github.com/zen-browser/desktop/issues/114#issue-2439417495, https://github.com/zen-browser/desktop/issues/378#issue-2477931786, https://github.com/zen-browser/desktop/issues/369#issue-2477014603, & https://github.com/zen-browser/desktop/issues/231#issue-2460757535 :woman_shrugging:

**Comment by mauro-balades** [comment]
I'm going to close this as it is being way too duplicated

**Comment by iPublicis** [comment]
An importer from https://drive4ik.github.io/simple-tab-groups/.

I have a ton f things on Firefox using STG and not being able to import from it may be a block for me to move to Zen,
