### ISSUE TITLE
search tabs keyboard shorcut

### ISSUE THREAD

**Issue by kanishkave** [zen-browser/desktop#526]
### What feature would you like to see?

I would love it if the browser had something like search tabs shortcut on mac cmd + shift + a. Microsoft edge has this and it's a game changer. please take a look at the edge implementation rather than the chrome implementation. The good thing about edge is that not only the search tabs bar in centered it also look through your recent history and tabs which you recently closed also show up in the search. I think this feature will be a game changer.  

`Edge Search Tabs` 

<img width="466" alt="image" src="https://github.com/user-attachments/assets/cccb0fdd-927f-4bc8-bd35-3ea4d379ea12">

### What platform are you seeing the problem on?

macOS

**Comment by Moshyfawn** [comment]
This is possible using Firefox's native search shortcuts, which is set to `% by` default. You can focus on the search bar and type `%` followed by `Tab`, which will enable the 'Switch to Tab' mode. You can then search for the tab you want to switch to that is already open.

**Comment by logno-dev** [comment]
I don't think the `%` function quite matches the feature in Edge and Brave. As far as I can tell, the shortest route to this is to hit `ctrl + l` then `shift + 5` then `space` then you can type in your search term. Once you have a term close enough the tab you are looking for, you have to minimally hit `tab` once and then `enter`.

vs

`ctrl + shift + a` -> search term -> `enter`

It is surprising to me that this is not a widely sought out feature.

**Comment by bcastillo-2022474** [comment]
PLEASE, PLEASE, Implement this! This was actually the reason that I installed this browser for, with the hope that they had implemented this, I love firefox, but managing tabs right now is a nightmare, if you guys can implement this fzf alike feature, I will for sure go with you, is an essential feature.

**Comment by okilonet1** [comment]
PLEASE, PLEASE, Implement this!

It's a great great feature for speed in browsing

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/807

 ~ This is an automatic operation to better enhancements requests organization.
