### ISSUE TITLE
Issue with playback on crunchy roll

### ISSUE THREAD

**Issue by thelaw51** [zen-browser/desktop#528]
### What happened?

When ever i go on cruncy roll it comes up with an error that it can't play the video see below:

![image](https://github.com/user-attachments/assets/1809aefb-f12e-4254-a130-9d38a4f9836a)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.28

### Severity impact

Medium

### What platform are you seeing the problem on?

Windows

**Comment by busybox11** [comment]
Check in the settings if DRM is enabled and test it (using [Bitmovin's website](https://bitmovin.com/demos/drm/), for example) if it is working.

This sounds like a simple DRM issue from all the reports I see online with this error code.

Can't test it as I don't have Crunchyroll, but other DRM-protected content on other websites are working fine for me.

<img width="2056" alt="image" src="https://github.com/user-attachments/assets/2b130949-84f9-4572-bcd7-546e6d92c062">

**Comment by mauro-balades** [comment]
There's no DRM on windows because it's absurdly expensive, sorry
