### ISSUE TITLE
Browser freezes after changing some settings

### ISSUE THREAD

**Issue by g-ioannou** [zen-browser/desktop#529]
### What happened?

After messing around with keybindings, installing some extensions and restarting zen browser multiple times, the browser launches but is stuck on initial screen.

I've also tried installing it with flatpak but the issue remains.

![image](https://github.com/user-attachments/assets/32af4c26-46be-44d1-8b3e-312c10c0b7db)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.28

### Severity impact

High

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
No logs:

![image](https://github.com/user-attachments/assets/ed205086-10a5-4b6e-8f47-9d97a3af0b8b)
```

**Comment by DrLarck** [comment]
Same problem here (MacOS Sonoma), after tweaking the keybindings a bit, Zen is stuck on this screen

**Comment by ramiroangelb** [comment]
Same problem here, Windows 10 Pro 22H2. After changing keybindings, opened a new tab and this happened.

**Comment by espensgr** [comment]
Same here (MacOS Sonoma 14.6.1), imported stuff from chrome, changed key bindings and restarted the app, Zen stuck in limbo land.

**Comment by Ashutoshyadav01** [comment]
can i work on this issue?

**Comment by mauro-balades** [comment]
what keybindings and for what action?

**Comment by espensgr** [comment]
I just tested for toggle compact view, think it was `ctrl+<`

**Comment by mauro-balades** [comment]
THIS HAS BEE FIXED!
https://github.com/zen-browser/components/commit/d83b0ac34227389677b0e576c9f3eeee2d5f69ba

im going to release it now so that y'all can start using it again
