### ISSUE TITLE
[macOS] Install guide

### ISSUE THREAD

**Issue by SenpaiHunters** [zen-browser/desktop#53]
# macOS Installation Guide for Zen Browser

### Step 1: Download the Latest Version

1. Download the [latest Zen Browser DMG](https://github.com/zen-browser/desktop/releases/latest).
2. Once downloaded, open the DMG file. You might need to zoom out a bit to see everything.

![Open DMG](https://github.com/user-attachments/assets/d3a3a845-245e-4154-b6b2-941f4d021bee)

### Step 2: Install Zen Browser

1. Drag the Zen Browser icon to the `Applications` folder.

### Note for Developers

If you are the developer of Zen Browser, ensure you include the following icon sizes for macOS, and update the names accordingly:

- Black-16.png
- Black-32.png
- Black-64.png
- Black-128.png
- Black-256.png
- Black-512.png
- Black-1024.png

These icons serve different purposes, such as the DMG and app icon (1024), Finder icon (128), etc.

### Step 3: Bypass Gatekeeper

Upon trying to open Zen Browser, you may encounter a message indicating the file is damaged. This happens because the app does not have a valid developer signature and is using an Ad-hoc sign.

![Gatekeeper Warning](https://github.com/user-attachments/assets/298f06af-772b-460d-9e71-65f6c99e8341)

To bypass this warning:

1. Open Terminal.
2. Run one of the following commands:

   To bypass Gatekeeper for the current installed version:

   ```sh
   xattr -c '/Applications/Zen Browser.app/'
   ```

   To bypass Gatekeeper for all versions of the app:

   ```sh
   xattr -d com.apple.quarantine '/Applications/Zen Browser.app/'
   ```

3. After running the command, if successful, Terminal will return a blank line.

![Successful Command](https://github.com/user-attachments/assets/f80bc340-3032-4c49-936a-c7fc937b8ef9)

### Step 4: Open Zen Browser

1. Open Zen Browser from the Applications folder.
2. Complete the onboarding process.
3. If you use Little Snitch (LS), accept or block any connections as needed, though for a browser, it is generally not recommended to block connections other than telemetry.

### Step 5: Restart Zen Browser

At the time of writing, there seems to be a bug with Zen Browser where the menu might not display correctly on the initial start. To fix this, quit Zen Browser (`⌘Q`) and reopen it.

![Incorrect Menu](https://github.com/user-attachments/assets/ae83cf1d-5391-4396-abe7-8b02b31edc85)
![Correct Menu](https://github.com/user-attachments/assets/fb08d7f4-e961-473e-a659-16ecabf76103)

You should now have a fully functional Zen Browser on your macOS. If you need to uninstall Zen, you can use [Pearcleaner](https://github.com/alienator88/Pearcleaner).

**Comment by mauro-balades** [comment]
woah, thanks a lot for this detailed guide! Ill pin it to the repo's issues and add it to the readme.

**Comment by SenpaiHunters** [comment]
macOS flags unsigned apps from unidentified developers as potentially unsafe, hence the warning. This isn't because it considers Zen a virus, but because it doesn't recognise the developer. Running the terminal commands bypasses Gatekeeper, allowing the app to run. To avoid this, you can get an official Apple developer certificate and sign the app (although this will cost 100 USD, so for something such as this, would not exactly be viable, hence why we use terminal commands).

**Comment by mauro-balades** [comment]
that sucks :(

**Comment by emm312** [comment]
in my experience the corrupted thing can be fixed with a chmod +x on the executable itself and from there you get past the unidentified developer thing in settings

**Comment by SenpaiHunters** [comment]
> in my experience the corrupted thing can be fixed with a chmod +x on the executable itself and from there you get past the unidentified developer thing in settings

`chmod +x` is for a file to allow execution, for an app in the applications folder you need to pass `xattr -c`. As this is a dmg, `chmod +x` works less well than the method above.

**Comment by mauro-balades** [comment]
I'm wondering if I could remove the attributes on the build step before releasing or does Mac insert them once opening?

**Comment by ComfortableMilk4454** [comment]
![CleanShot 2024-07-20 at 14 47 45@2x](https://github.com/user-attachments/assets/45193b6d-8568-43a0-8d21-6e3a2d22981c)
(the first command `xattr -c '/Applications/Zen Browser.app/'` works though). any ideas on how i can fix this? macOS 14.5 here.

**Comment by mauro-balades** [comment]
It's one command or the other, not both. The command you just ran clears the attributes so it should work already. (Someone tell me if I'm wrong)

**Comment by chilikasha** [comment]
hi @mauro-balades , could you please update the icons?
<img width="296" alt="SCR-20240727-tfkr" src="https://github.com/user-attachments/assets/afdf98fb-2c86-4b79-862b-add9d56ca778">

thanks for the browser, enjoying so far!

**Comment by stairjoke** [comment]
Honestly, I would have loved to try, but the instructions to circumvent security measures are a real turn-off. I understand why, I get it intellectually, but I think its a bad decision, in my opinion.

**Comment by mauro-balades** [comment]
a bad decision to do what exactly?

**Comment by mauro-balades** [comment]
Sure, you could donate [here](https://www.patreon.com/zen_browser), but they cost 100 euros

https://developer.apple.com/support/enrollment/#:~:text=The%20Apple%20Developer%20Program%20annual,currency%20during%20the%20enrollment%20process.

**Comment by roblabla** [comment]
You can just do right click -> open on the .app, and then you'll get an option to start the app. No need to drop down to the terminal.

**Comment by foxt** [comment]
> Sure, you could donate [here](https://www.patreon.com/zen_browser), but they cost 100 euros
> 
> https://developer.apple.com/support/enrollment/#:~:text=The%20Apple%20Developer%20Program%20annual,currency%20during%20the%20enrollment%20process.

Normally when an app isn't signed you get a notification that says "This application is from an unidentified developer", not "This application is damaged". Seems like something is going wrong in your build process.

**Comment by figuernd** [comment]
Hey I was excited about Zen. I like Firefox, and care a lot about UX. I suspect a lot of users that care about UX will also be using OSX.

But few users will bother to search out this workaround. Instead of acquiring users, your marketing site is a user-journey to a dead end. You would be better off not advertising OSX support in the first place.

**Comment by proevilz** [comment]
Having to install third party software to uninstall it is a major red flag and a turn off.

**Comment by thezacharytaylor** [comment]
I didn't have this issue on the lastest? I'm running Sonoma 14.5 on a M1 Pro.

**Comment by bravecrayon** [comment]
I'm liking it, but the install instructions on the website don't indicate that we must `xattr -c` the app. Had to dig to find this issue. Hopefully enough donations can happen so that the 100€ Apple Developer account can be covered for a year.

**Comment by RobertBoes** [comment]
For the meantime, as @foxt mentioned, can the ad-hoc signature be removed? Then people can install the app as normal, they'll receive a popup, just like a lot of other open-source apps. There's no need to disable gatekeeper for this really. Either sign the app with a certificate, or not sign it.

The ad-hoc signature doesn't provide any value and having to use `xattr` to be able to use the app is just a huge no-go for less tech-savvy people.

**Comment by IronBlossom** [comment]
Hold ctrl, and right-click >> Open

You should have the option to open it.

**Comment by Doomsk** [comment]
As @foxt and @RobertBoes mentioned, I'll be waiting for a non ad-hoc signature to test the browser.

A friend suggested Zen to me and, since I didn't install Arc browser because it's Google's Chrome in all its telemetry-and-data-collection-with-no-shame mode, I was keen to new experience and UI, away from the always-the-same already established browsers.

**Comment by Kiki0fCalifornia** [comment]
> woah, thanks a lot for this detailed guide! Ill pin it to the repo's issues and add it to the readme. By the way, any idea on why you have to do the terminal thing? Does macos consider it a virus?

@mauro-balades If you could remove the ad-hoc signature—even to leave it without a signature at all—it shouldn’t be a problem. There are lots of apps I have on my mac that don’t have a signature, it is fine and there is no big workaround like this needed, it’ll just say the developer can’t be identified and on the first launch the user will need to right click to open it—something virtually any MacOS user who would find this browser in the first place will be very familiar with because most apps we download online are like that because people don’t want to pay that license.

This is why the Intel Mac version of Zen Browser does not have this issue while the Apple Silicon one does, the Intel version is unsigned whereas this version has the ad-hoc signature, which is not how Mac Apps are supposed to be distributed. Just leave the signature blank like you did for the Intel Mac release and this problem should go away, opening up the app to a lot more users.

**Comment by mauro-balades** [comment]
How could I remove it? Any guides?

**Comment by NathanielH-snek** [comment]
> How could I remove it? Any guides?

I'm currently looking into the firefox docs, will update with instructions to remove build signing soon, however it looks like you may want to sign with an official apple dev account for some features anyway. See [This](https://firefox-source-docs.mozilla.org/contributing/signing/signing_macos_build.html#signing-local-macos-builds)

**Comment by NathanielH-snek** [comment]
> # macOS Installation Guide for Zen Browser
> ## Initial Setup
> ### Step 1: Download the Latest Version
> 
>     1. Download the [latest Zen Browser DMG](https://github.com/zen-browser/desktop/releases/latest).
> 
>     2. Once downloaded, open the DMG file. You might need to zoom out a bit to see everything.
> 
> 
> ![Open DMG](https://private-user-images.githubusercontent.com/103985728/348454221-d3a3a845-245e-4154-b6b2-941f4d021bee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyOTQ2MTAsIm5iZiI6MTcyNTI5NDMxMCwicGF0aCI6Ii8xMDM5ODU3MjgvMzQ4NDU0MjIxLWQzYTNhODQ1LTI0NWUtNDE1NC1iNmIyLTk0MWY0ZDAyMWJlZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMlQxNjI1MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZGEzZjRlMTVhZmM0M2JhMTYzYzFiZTA3ZjU2MWRmY2E1YTQxNDI1ZmMwNjE4MTM2YzUyZTNkMjhjMDhkMjhhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.A9gNYlmJsKDzKUDqxtJWuP_HzRVQHj_XIkQAZZ2efr0)
> ### Step 2: Install Zen Browser
> 
>     1. Drag the Zen Browser icon to the `Applications` folder.
> 
> 
> ### Note for Developers
> 
> If you are the developer of Zen Browser, ensure you include the following icon sizes for macOS, and update the names accordingly:
> 
>     * Black-16.png
> 
>     * Black-32.png
> 
>     * Black-64.png
> 
>     * Black-128.png
> 
>     * Black-256.png
> 
>     * Black-512.png
> 
>     * Black-1024.png
> 
> 
> These icons serve different purposes, such as the DMG and app icon (1024), Finder icon (128), etc.
> ### Step 3: Bypass Gatekeeper
> 
> Upon trying to open Zen Browser, you may encounter a message indicating the file is damaged. This happens because the app does not have a valid developer signature and is using an Ad-hoc sign.
> 
> ![Gatekeeper Warning](https://private-user-images.githubusercontent.com/103985728/348454366-298f06af-772b-460d-9e71-65f6c99e8341.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyOTQ2MTAsIm5iZiI6MTcyNTI5NDMxMCwicGF0aCI6Ii8xMDM5ODU3MjgvMzQ4NDU0MzY2LTI5OGYwNmFmLTc3MmItNDYwZC05ZTcxLTY1ZjZjOTllODM0MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMlQxNjI1MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNGZlYTIyMDM4NDYwMDRmMDdhOGJkN2EwZTg3ZmZlZDUxOWM4MWU4NzEyMDk2N2I3ZWJkODQyM2EyZGRmZmZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.T09ndBgtKP0h9VsAjiOchT82BKhRUHdG5gYceSYUZj0)
> 
> To bypass this warning:
> 
>     1. Open Terminal.
> 
>     2. Run one of the following commands:
>        To bypass Gatekeeper for the current installed version:
>        ```shell
>        xattr -c '/Applications/Zen Browser.app/'
>        ```
>        
>        
>            
>              
>            
>        
>              
>            
>        
>            
>          
>        To bypass Gatekeeper for all versions of the app:
>        ```shell
>        xattr -d com.apple.quarantine '/Applications/Zen Browser.app/'
>        ```
> 
>     3. After running the command, if successful, Terminal will return a blank line.
> 
> 
> ![Successful Command](https://private-user-images.githubusercontent.com/103985728/348454635-f80bc340-3032-4c49-936a-c7fc937b8ef9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyOTQ2MTAsIm5iZiI6MTcyNTI5NDMxMCwicGF0aCI6Ii8xMDM5ODU3MjgvMzQ4NDU0NjM1LWY4MGJjMzQwLTMwMzItNGM0OS05MzZhLWM3ZmM5MzdiOGVmOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMlQxNjI1MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yN2E2NGE4ODcxOGRkZWNmMWE2NjQxODYwY2JkZWM3Yzg4M2NjOTUxYzgxYzViNzM0M2E2ZGVjYWM1ZTQyZGMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eVrYyZB6s_6CtGvpVoEw2DDJ96oCwfqp0xZ8vmgtHfw)
> ### Step 4: Open Zen Browser
> 
>     1. Open Zen Browser from the Applications folder.
> 
>     2. Complete the onboarding process.
> 
>     3. If you use Little Snitch (LS), accept or block any connections as needed, though for a browser, it is generally not recommended to block connections other than telemetry.
> 
> 
> ### Step 5: Restart Zen Browser
> 
> At the time of writing, there seems to be a bug with Zen Browser where the menu might not display correctly on the initial start. To fix this, quit Zen Browser (`⌘Q`) and reopen it.
> 
> ![Incorrect Menu](https://private-user-images.githubusercontent.com/103985728/348454113-ae83cf1d-5391-4396-abe7-8b02b31edc85.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyOTQ2MTAsIm5iZiI6MTcyNTI5NDMxMCwicGF0aCI6Ii8xMDM5ODU3MjgvMzQ4NDU0MTEzLWFlODNjZjFkLTUzOTEtNDM5Ni1hYmU3LThiMDJiMzFlZGM4NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMlQxNjI1MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMGYyMGFjNjVjYzQ5ZWNjZTQ3YjcyYTY3NGU4NDhkMWVkN2FkOWUyMzhhYjRlNDQxYjBhMDg3Zjk3MzE0NmI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BB6ZfI3haihIR3Nuta7VsiM3qbr4dNBbYmNl47CjNeI) ![Correct Menu](https://private-user-images.githubusercontent.com/103985728/348454116-fb08d7f4-e961-473e-a659-16ecabf76103.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyOTQ2MTAsIm5iZiI6MTcyNTI5NDMxMCwicGF0aCI6Ii8xMDM5ODU3MjgvMzQ4NDU0MTE2LWZiMDhkN2Y0LWU5NjEtNDczZS1hNjU5LTE2ZWNhYmY3NjEwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMlQxNjI1MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZGJmZWVmYjg0ZDE1YmVkZmFjOWNlNzI1YjRmZDBiNDU1NmNlNDc1MDNlNjJmOTJlY2M1MjA3MGE3MGU2NDIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ugdfskeSjUn9cCx_ULKS3q7z4fWlf4RiT3A4bjF7Mtg)
> 
> You should now have a fully functional Zen Browser on your macOS. If you need to uninstall Zen, you can use [Pearcleaner](https://github.com/alienator88/Pearcleaner).

BTW how do you get this nice graphical image of the app properties?

**Comment by mauro-balades** [comment]
Heya, i've finally gotten the license keys, ill release today with them included!

**Comment by HarryHeres** [comment]
> Heya, i've finally gotten the license keys, ill release today with them included!

LMK when you include them, I will update Homebrew so the `xattr`workaround is not needed anymore.

**Comment by mauro-balades** [comment]
If version 35 passes this night (ill be sleeping), then you can remove them, they are signed now

**Comment by mendelgordon** [comment]
> it looks like you may want to sign with an official apple dev account for some features anyway. See [This](https://firefox-source-docs.mozilla.org/contributing/signing/signing_macos_build.html#signing-local-macos-builds)

Thanks-that explains why iCloud passkeys aren't working in the current build, and why all Apple silicon builds are ad-hoc signed

**Comment by AlternateRT** [comment]
> If version 35's build passes this night (ill be sleeping), then you can remove them, they are signed now
@mauro-balades It looks like something has gone wrong with the signing. I just downloaded the macos-64x.dmg of a35 and I still get the "Zen is damaged .. move it to the Trash" dialog.

**Comment by mjskraju** [comment]
@mauro-balades I can confirm what @AlternateRT has mentioned above. The new Alpha build - 1.0.0-a.35 (2024-09-03) build still shows the same dreaded message on Mac. I'm on MacOS Sonoma 14.6.1

**Comment by mauro-balades** [comment]
Yes, please stop pinging me, ill look more into it... The workflow succeeded when signing the macos app so idk what's going on

**Comment by sergio-lopez93** [comment]
i actually have made all the steps you said for running it and skiping the damage problem, i used the terminal and wrote what u said etc.. but still zen browser doesnt work. 
<img width="1427" alt="image" src="https://github.com/user-attachments/assets/33652b16-d713-41b3-a502-0708796fb97c">

**Comment by mauro-balades** [comment]
im still working on it, I think I just need to notarize the dmg...

@sergio-lopez93 is there any terminal output?

**Comment by mauro-balades** [comment]
Update: Once 38 is out, I want this issue gone out of existance... It works!

**Comment by SJ50** [comment]
Just installed 39, no need of work around. Also Touch ID works with 1Password as well.

**Comment by mendelgordon** [comment]
I have 39 installed and still can't use icloud passkeys in zen - should I make a new issue?
<img width="827" alt="image" src="https://github.com/user-attachments/assets/97b104e9-c43f-44d2-8e0d-859feeba3d60">

**Comment by muffn** [comment]
> Just installed 39, no need of work around. Also Touch ID works with 1Password as well.

can't confirm, are you sure about that? Desktop App and Extension still don't sync for me, but further discussion of that is better placed here anyways probably: https://github.com/zen-browser/desktop/discussions/856

**Comment by bravecrayon** [comment]
Installed 1.0.0-a.39... seems fixed now! 👏

**Comment by nicolasdanelon** [comment]
> Installed 1.0.0-a.39... seems fixed now! 👏

confirm, works like a charm, thanks!
