### ISSUE TITLE
Esc will not de-focus the search bar

### ISSUE THREAD

**Issue by iseth** [zen-browser/desktop#530]
### What happened?

After clicking `cmd+k` or `cmd+l` to open the search bar, pressing ESC will not de-focus the bar.

There are a few people that would like to be able to completely disable the `cmd+k` for compatibility with other sites:
https://stackoverflow.com/questions/76189276/how-to-remove-disable-the-cmdk-shortcut-to-open-search-in-firefox

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.28 (64-bit)

### Severity impact

Medium, Enhancement

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by mauro-balades** [comment]
This is a firefox feature, you should report the bug to them 👍🏽

**Comment by JSGRD22** [comment]
This has been fixed in firefox 133, use this flag: `browser.urlbar.focusContentDocumentOnEsc`
