### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by cooffeeRequired** [zen-browser/desktop#531]
### What happened?

![image](https://github.com/user-attachments/assets/66cd7746-d682-4251-bf2e-6bf608ed7ffc)

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

129.0.2.3

### Severity impact

High

### What platform are you seeing the problem on?

Windows

**Comment by NOCanoa** [comment]
Soon we are just starting to implement languages, if all goes to plan there will be alot off languages available (community translated).
