### ISSUE TITLE
profiles

### ISSUE THREAD

**Issue by vulbyte** [zen-browser/desktop#532]
### What feature would you like to see?

hello!
this is a feature that as far as i'm aware only arc browser has, but is the entire reason i use the broswer,
it's the concept of "profiles" where if i switch from one profile to another it's effectively another browser in the same window; with all my client info, accounts, cookies, etcetc being completely wiped and being an entirely new instance.

### What platform are you seeing the problem on?

macOS

### Additional context

this is a killer feature for people like me who attempt to keep their personal life and professional life separate and allows me to easily separate sensitive information such as bank logins and what not into one profile, then if i'm saying doing something like streaming then i can have a seperate profile where everything is logged out and i don't have to worry about any crossing of information/sensitivity.

**Comment by cyrneko** [comment]
Zen does actually have that, the UI is being worked on. Firefox is also working on it upstream but nobody knows when they'll be finished. So, we'll see who finishes this feature first

Though, container tabs do allow you to seperate accounts, cookies etc, all within the same profile. Zen should have them enabled and default, try right-clicking the new tab button :)

**Comment by enkvadrat** [comment]
about:profiles

**Comment by RealVishy** [comment]
> ### What feature would you like to see?
> 
> hello! this is a feature that as far as i'm aware only arc browser has, but is the entire reason i use the broswer, it's the concept of "profiles" where if i switch from one profile to another it's effectively another browser in the same window; with all my client info, accounts, cookies, etcetc being completely wiped and being an entirely new instance.
> ### What platform are you seeing the problem on?
> 
> macOS
> ### Additional context
> 
> this is a killer feature for people like me who attempt to keep their personal life and professional life separate and allows me to easily separate sensitive information such as bank logins and what not into one profile, then if i'm saying doing something like streaming then i can have a seperate profile where everything is logged out and i don't have to worry about any crossing of information/sensitivity.

This is available in Zen browser by clicking on the profile button in the bottom left corner, it's the top icon available.

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/805

 ~ This is an automatic operation to better enhancements requests organization.
