### ISSUE TITLE
feat: create portableapps version

### ISSUE THREAD

**Issue by polymo1** [zen-browser/desktop#536]
### What feature would you like to see?

I am a current user of regular Firefox, and I also use Firefox from PortableApps on a USB drive to use on college computers for personal security and convenience, as I use a few extensions that are personally important.

Mozilla has given PortableApps explicit permission to package the browser under the `Mozilla Firefox` brand as a portable version, however I believe that in Zen Browser's current state, this permission would not be needed. Thus, I would appreciate it if a PortableApps version were to be packaged.

### What platform are you seeing the problem on?

Windows

### Additional context

https://portableapps.com/

https://portableapps.com/apps/internet/firefox_portable

**Comment by gunir** [comment]
PortableApps are maintained and provided by PortableApps themselves, [you can request them to add Zen using this forum](https://portableapps.com/forums/general/request_apps).

**Comment by polymo1** [comment]
Also just wanted to make sure they would have permission.

**Comment by gunir** [comment]
@mauro-balades How about giving Portableapps permissions to repack Zen into Portable, would be great for Windows browsers and we won't have to maintain a Zen Portable.

**Comment by mauro-balades** [comment]
What's portableapps

**Comment by MaggotHATE** [comment]
Considering that there's a [misleading confusion](https://github.com/zen-browser/desktop/issues/563) now on the website, having at least Portableapps version would be nice.

**Comment by polymo1** [comment]
> What's portableapps

Portable apps for windows that don't leave any user files (unless manually left by a user)

For example, if I logged into Firefox portable on one computer, unplugged the usb drive, there would be no Firefox appdata. I could then plug it back in to the same or different computer and everything was as it was.

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/804

 ~ This is an automatic operation to better enhancements requests organization.
