### ISSUE TITLE
Compact mode Actions (Except for Toggle compact mode) not working

### ISSUE THREAD

**Issue by rp1231** [zen-browser/desktop#537]
### What happened?

Compact mode Actions (Except for Toggle compact mode) not working.
The highlighted shortcuts don't do anything.....
![Screenshot 2024-08-24 050345](https://github.com/user-attachments/assets/5d54d4d2-4122-4d28-acff-3c20c7a6d8a0)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.28 (64-bit)

### Severity impact

Medium

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
You need to be on compact mode first in order to toggle them

**Comment by pret0rian** [comment]
@rp1231 Did you try to choose different keys? 
Some keyboard can't handle some key combinations!
