### ISSUE TITLE
Compact mode sidebar hiding MAC OS

### ISSUE THREAD

**Issue by WillDow42** [zen-browser/desktop#540]
### What happened?

https://github.com/user-attachments/assets/d53e3787-8263-41ec-b4ad-4bc6a7f83fb3

When app is in fullscreen dragging the mouse to the edge of the display quickly shows and then hides the sidebar, when it should show it even at the hard edge as that is where you drag the mouse to, kind of like hiding and showing the dock on Mac OS

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.28 (64-bit)

### Severity impact

Medium

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by Moshyfawn** [comment]
I'd go further and keep the sidebar open even when the cursor leaves the browser window through the left, edge if that's possible. I'd also like to see a slight delay between when the cursor hits the edge and when the sidebar opens, so that it doesn't try to open and close quickly as the cursor moves back and forth over the edge.

**Comment by WillDow42** [comment]
Honestly I kinda like the instant open and close, I hate waiting for animations to finish just to continue working. But I guess in that case I'm probably not the key user for a compact tabs style feature. It's just nice on the smaller (13") screen.

**Comment by sameer1612** [comment]
https://github.com/zen-browser/desktop/issues/520

**Comment by Moshyfawn** [comment]
> Honestly I kinda like the instant open and close

Oh, I'm talking a **very** slight delay, which should be mostly imperceptible. I just find that if I miss the edge and try to "fumble" to keep the sidebar open, it creates a somewhat jarring experience, especially if the window doesn't stretch to the edge of the screen.

**Comment by Moshyfawn** [comment]
> #520

#520 talks about the "discovery" / hover area that triggers the sidebar to open, which covers elements on the page with its current width, while in this issue, OP describes that if you hover over the edge too much to the left, the sidebar is closed.

**Comment by mauro-balades** [comment]
This is because your cursor isn't on the browser anymore, that border is done by macos and it doesn't "count" as part of it, meaning the the sidebar thinks the cursor is out

**Comment by WillDow42** [comment]
Lmfao man pulled a "not my problem" and dipped.

How come MS Edge can do it then..?

https://github.com/user-attachments/assets/d447959f-236c-4af2-8bc9-89fa78cf9d3d

**Comment by Badcosmonaut-esc** [comment]
This is still an issue on Mac. 
Just coming from Arc and this is the only functionality annoying me. Placing the mouse at the edge of the screen (yes it hits the app boarder) causes the sidebar to disappear. Worked on Arc, so surprising this can't be solved?
