### ISSUE TITLE
Search bar moves slightly when clicked/unfocused

### ISSUE THREAD

**Issue by XInTheDark** [zen-browser/desktop#541]
### What happened?

When clicking on the search bar, the search text moves downwards slightly. This appears to be due to the additional outline that appears around the search box.

Expected behaviour: the search text does not move so it's much easier to see.

https://github.com/user-attachments/assets/2180f390-1513-4dbb-a2d9-a3092729cada

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.28

### Severity impact

Low

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by Ashutoshyadav01** [comment]
I want to solve this issue can you handover this to me?

**Comment by Ashutoshyadav01** [comment]
I am still interested in  solving this issue.. can you please assign me this one?

**Comment by neurokitti** [comment]
let me know it this is still an issue
