### ISSUE TITLE
How to install on linux?

### ISSUE THREAD

**Issue by AmeerArsala** [zen-browser/desktop#542]
### What feature would you like to see?

I want to be able to install without using AppImage or Flatpak. It is too confusing. Just give me a curl link or something

### What platform are you seeing the problem on?

Linux

**Comment by NotMugil** [comment]
If you’re using Arch Linux, you can easily install it via the AUR
- [zen browser](https://aur.archlinux.org/packages/zen-browser-bin)
- [zen browser optimized](https://aur.archlinux.org/packages/zen-browser-optimized-bin)

**Comment by poopsicles** [comment]
` curl -L https://github.com/zen-browser/desktop/releases/latest/download/zen.linux-specific.tar.bz2 | tar xvj` _should_ work...but I haven't tested it yet

**Comment by NeuWasFlaggedAgain** [comment]
Hello!! I created a script to install zen. I've spent about an hour tweaking it to work on my system (debian + gnome), and put it on codeberg.

If you'd like to check it out: https://codeberg.org/neuner/zen-linux.sh or, to get started rapidly:

```sh
wget https://codeberg.org/neuner/zen-linux.sh/raw/branch/main/zen-linux.sh
chmod +x zen-linux.sh

# install zen:
./zen-linux.sh install

# create an entry on your system's desktop:
./zen-linux.sh desktop
```

if you encounter any issues please LMK!

**Comment by NeuWasFlaggedAgain** [comment]
as a video: https://youtu.be/mUgOTR-WVcU

**Comment by gxanshu** [comment]
Thank you @NeuWasFlaggedAgain. your script works for me

**Comment by NeuWasFlaggedAgain** [comment]
Glad I could help! Fingers crossed for apt/arch packages 🤞
