### ISSUE TITLE
Some extension popups are not correctly orderd

### ISSUE THREAD

**Issue by NandiyaLive** [zen-browser/desktop#55]
Clicking on search or "pop out to a new window" button will open the bookmark behind the extension. When I click below the bookmark bar it's like clicking in the web page behind the extension

![image](https://github.com/user-attachments/assets/0f32bbd3-d8cb-417d-8528-69113e491926)

**Comment by mauro-balades** [comment]
I dont fully understand what your problem is, sorry. If you could send a video or smth will help a lot, thanks

**Comment by NandiyaLive** [comment]
This happens to me when I'm using Bitwarden. So I can't provide a screen capture here.

**Comment by mauro-balades** [comment]
I understand, ill look into it. Are you having this issue with something else?

**Comment by NandiyaLive** [comment]
No issues with other extension popups. Maybe you can test it with Bitwarden too?

**Comment by mauro-balades** [comment]
Ill move it to #82
