### ISSUE TITLE
My Cursor size has become so small in 2880 x 1600, scale 150%

### ISSUE THREAD

**Issue by muchfahmiarif** [zen-browser/desktop#551]
### What happened?

My cursor size has become so small that it is invisible  in Ubuntu 22.04, Resolution 2880 x 1800 (16 : 10), Scale 150%. Cursor too very small just on Apps Zen Browser, but on other apps size cursor normal.
But if i open firefox Developer my cusor size normal

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Alpha build - 1.0.0-a.28 (2024-08-22)

### Severity impact

High

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
Do you have a mouse theme installed?

**Comment by muchfahmiarif** [comment]
@mauro-balades yes i installed from [pling](https://www.pling.com/p/1355701/)
![image](https://github.com/user-attachments/assets/6641b91e-ad4a-4ccc-8a17-609a30654285)

**Comment by JulsSkogs** [comment]
I am also experiencing this. Using Tumbleweed 20240823 with KDE Plasma 6.1.4, with Zen version 1.0.0-a.28 as well. I disabled my cursor theme and it fixed the problem, but incidentally Zen closes every time I change my cursor theme. Not smart enough to know if that's a necessity or intended consequence, but figured it was worth mentioning.

**Comment by mauro-balades** [comment]
I'll move it to https://github.com/zen-browser/desktop/issues/993#issuecomment-2334631753
