### ISSUE TITLE
Flatpak version does not match browser version

### ISSUE THREAD

**Issue by Jack-Kaller** [zen-browser/desktop#553]
### What happened?

Hello, I've juste noticed that version with `flatpak list` and `About Zen` does not match

![Capture d’écran du 2024-08-24 09-02-29](https://github.com/user-attachments/assets/ac5ad566-7d3e-4932-8b98-e1d2238de8bd)

![image](https://github.com/user-attachments/assets/6b4b2f6d-f07e-470f-a7b2-e30b708773ed)

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.28

### Severity impact

Low

### What platform are you seeing the problem on?

Linux

**Comment by dewantawsif** [comment]
Duplicate of #302

**Comment by dewantawsif** [comment]
@mauro-balades this issue can be closed
