### ISSUE TITLE
Prime video Unplayable

### ISSUE THREAD

**Issue by dhruvvk2326** [zen-browser/desktop#554]
### What happened?

When i open a video in prime its showing video unplayable i even tried to add the website address as exception in settings but it did not work
![Screenshot 2024-08-24 124447](https://github.com/user-attachments/assets/3d4c711a-185b-4547-8d09-dab4329172d0)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.28

### Severity impact

High

### What platform are you seeing the problem on?

Windows

**Comment by NathanGlasby** [comment]
This is due to DRM, see https://github.com/zen-browser/desktop/issues/313 for more info.

**Comment by dhruvvk2326** [comment]
Due to DRM
