### ISSUE TITLE
Full Screen mode does not automatically enable Compact Mode

### ISSUE THREAD

**Issue by Ram-256bit** [zen-browser/desktop#558]
### What happened?

When entering Full Screen mode, the sidebar (vertical tabs) and the top bar should automatically hide, allowing the website content to occupy the entire screen. However, the current behavior shows that both the sidebar and top bar remain visible until the user manually enables compact mode using a keyboard shortcut.

Expected Behavior:
Upon entering Full Screen mode, the sidebar (vertical tabs) and top bar should automatically hide, allowing only the website content to be displayed across the entire page.

Current Behavior:
In Full Screen mode, the sidebar and top bar remain visible until compact mode is manually activated by the user.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.28

### Severity impact

Low, Enhancement

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/801

 ~ This is an automatic operation to better enhancements requests organization.
