### ISSUE TITLE
Compact mode top toolbar doesn't appear on hover in windowed mode

### ISSUE THREAD

**Issue by FeelThePoveR** [zen-browser/desktop#559]
### What happened?

With compact mode top toolbar enabled, entering windowed mode makes the top toolbar dissapear and it stops reappearing on hover till you enter fullscreen again.

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.28

### Severity impact

Medium

### What platform are you seeing the problem on?

Windows

**Comment by kittybwained** [comment]
Have the same issue, this makes hiding the top toolbar basically unusable

**Comment by kyuuaria** [comment]
It should have a larger hover area beyond just the border

**Comment by kyuuaria** [comment]
As a workaround you can use the `Toggle Compact Mode Toolbar` shortcut or `F6`
