### ISSUE TITLE
How to resize the split windows?

### ISSUE THREAD

**Issue by lethc** [zen-browser/desktop#56]

**Comment by lethc** [comment]
or tabs 😂

**Comment by mauro-balades** [comment]
it's certainly on my plans to add support for it, ill do it once I finish workspaces (what im doing right now). 

Because I need to do a bit of research since it's displayed in a grid mode and it may depend if it's horizontal/vertical, etc. I just need to think about it a bit more

**Comment by mauro-balades** [comment]
It is not implemented yet, it will be for the future 👍🏽

**Comment by KaKi87** [comment]
Could we please be notified when it's implemented and released ? Thanks
