### ISSUE TITLE
Native PWA Support

### ISSUE THREAD

**Issue by sidsharths1245** [zen-browser/desktop#560]
### What feature would you like to see?

Native PWA support. Firefox doesn't have it by default so I was wondering if it could be added to Zen. This will be an an awesome feature.

### What platform are you seeing the problem on?

Linux

**Comment by Stem-LG** [comment]
there's already a tool for this

Link: [PWAsForFirefox](https://github.com/filips123/PWAsForFirefox/)

it requires the installation of a firefox addon and a native executable on the host os.

would be cool if it was integrated straight into zed

**Comment by devniza** [comment]
PWA is great but it's a whole other browser so your sessions and cookies are stored separately (correct me if I'm wrong). It should be possible for Zed to integrate this well.

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/800

 ~ This is an automatic operation to better enhancements requests organization.
