### ISSUE TITLE
Translation popup spam.

### ISSUE THREAD

**Issue by Arnauw** [zen-browser/desktop#561]
### What happened?

I'm getting spammed of translation popup because apparently some options are not saved.

In the menu "More Translation Settings" (when you click option next to translation)
You have this :

"Set your language and site translation preferences and manage languages downloaded for offline translation.

Always translate these languages

Never translate these languages

Never translate these sites

To add to this list, visit a site and select “Never translate this site” from the translation menu."

Whatever I add to lists here, like "never translate x" it's emptied each time I restart the app
And if I set the option directly from the popup it's the same, it's gone after a restart.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.28

### Severity impact

High

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
You need to click on "never show translation popup" in the dialog

**Comment by Arnauw** [comment]
> You need to click on "never show translation popup" in the dialog
Huh ???
![popup-cogwheel-zen](https://github.com/user-attachments/assets/440c9c0d-4cde-4b11-9dc4-e54681b2d469)
You can see this option doesn't even exist lol, and also, I know it might sound crazy but I actually want to have translation popups.
As I was doing in firefox, I want a popup once per language, and I either chose never or always translate this language and it never pops again for this language, then if I want to change things I can go into the translation settings and do that there too.


So I just tested it again on zen and you guys actually fixed one of the issue, now the translation popup actually register if you say "never translate" or "always translate", resulting in no more spam, so well played!, however the translation settings menu is completely ignored and dissociated from the popup/adress bar translation settings (aka broken).

Let me give an example.

- Let's say I go once to a Portuguese website.

Firefox : I get a popup "Translate this page?", Working ✅ 

Zen : I get a popup "Translate this page?", Working ✅ 

- I click the cogwheel inside the popup and click "Always translate Portuguese"

Firefox : Website gets translated, Working ✅ 

Zen : Website gets translated, Working ✅ 

- I go to about:preferences#general and scroll down a little to find the translation settings, like this :
![translation-menu-firefox-minified](https://github.com/user-attachments/assets/edbb8929-0b8e-404e-8643-1c396369ffe2)
And I click "Settings..." to open the menu.
(In Zen you can apparently go directly to about:preferences#translations which is nice)

Firefox : Portuguese has been added to the list of languages to auto-translate.(see screenshot)
![translation-menu-firefox-open](https://github.com/user-attachments/assets/dacfcd58-3071-416c-bb26-8b9043a13f08)
As expected, Working ✅ 

Zen : Nothing has been added to the list of languages to auto-translate.(see screenshot)
![translation-menu-zen-open](https://github.com/user-attachments/assets/0e83fa37-f483-4997-8c16-4a5ab76ec17e)
Not as expected, Not working 🟥 


So good work for fixing the popup spam, awesome !
I hope you also fix the translation settings menu soon tm.

- I add a bunch of languages to the auto-translate and the never-translate list so I'm set.

Firefox : Works as intended, you can change the translation settings directly from the options. ✅

Zen : Nothing work, the translation settings menu is completely unusable. 🟥
