### ISSUE TITLE
Some fixes needed

### ISSUE THREAD

**Issue by ThousandDemonDaggers** [zen-browser/desktop#564]
### What feature would you like to see?

I found a comment on reddit (comparing zen to librewolf) about some problems related to zen:

![Screenshot from 2024-08-24 11-54-36](https://github.com/user-attachments/assets/ceb4bc74-69b8-4e03-bac7-197ae4524467)

Are these things fixable? And if not, why not?

**Comment by kLabz** [comment]
Can you share the reddit post and/or its actual content (with links!) instead of a screenshot?

**Comment by ThousandDemonDaggers** [comment]
> Can you share the reddit post and/or its actual content (with links!) instead of a screenshot?

Sure thing. Here it is: [LINK](https://www.reddit.com/r/LibreWolf/comments/1ezumu7/comment/ljnjx2b/)

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/799

 ~ This is an automatic operation to better enhancements requests organization.
