### ISSUE TITLE
Additional browser behavior to make the experience better

### ISSUE THREAD

**Issue by sadiki-o** [zen-browser/desktop#565]
### What feature would you like to see?

Hello thank you for the nice experience and the effort, while using Zen i came across certain things i wish to optimize:
1) i would like the pinned tabs to be always visible that way a user with many tabs shouldn't have to scroll all the way to the top, and i can imagine someone having many pinned tabs so you dont want that pinned tab section to take all the space for normal tabs so you may consider having a max height or something like that.

2) i noticed something which is when you open a new tab you need to scroll to the bottom in order to see that newly opened tab, if you could scroll automatically to the new opened tab that will be a great optimization

3) It would be great if you cant make the sound button more visible in tabs
![image](https://github.com/user-attachments/assets/5e620a88-e778-4099-87f8-56bbdec995c6)

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/798

 ~ This is an automatic operation to better enhancements requests organization.
