### ISSUE TITLE
Confusion about workspaces and isolation

### ISSUE THREAD

**Issue by zynexiz** [zen-browser/desktop#566]
### What happened?

I tried using different workspaces to see if it works the same as Firefox's container tabs. But it seems that workspaces aren't isolated, logging in to a site and shift to another workspace still have the session from the other workspace. In Firefox containers these are isolated. Shouldn't workspaces do the same, or am I missing something? Without isolation, workspaces are pretty useless IMO. Firefox containers are way better to use then.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a28 (64-bit)

### Severity impact

Medium

### What platform are you seeing the problem on?

Linux

**Comment by dewantawsif** [comment]
Workspaces are used for organization not isolation. For isolation use containers or profile.

**Comment by nezzzumi** [comment]
@zynexiz I believe what you need is to define a default container for your workspace
