### ISSUE TITLE
[Linux X11]: Doesn't tile appropriately or float with other windows.

### ISSUE THREAD

**Issue by jasper-clarke** [zen-browser/desktop#568]
### What happened?

When I open zen browser it is automatically fullscreened.
I cannot switch it between floating and tiling like any other windows, it ignores all prompts to change its size.
I tried `zen-browser --window-size` and that did not even change its size.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Mozilla Zen 1.0.0-a.28

### Severity impact

Medium

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
Could you try settings `browser.sessionstore.interval` to a lower value

**Comment by ghost** [comment]
I have found at some point this issue is no longer relevant, unfortunately I cannot remember what solved the problem.
The workaround suggested by mr-cheff was not the solution though, I do know that.
