### ISSUE TITLE
“Zen Browser.app” is damaged and can’t be opened. You should move it to the Bin.

### ISSUE THREAD

**Issue by khanakia** [zen-browser/desktop#571]
### What happened?

I just downloaded the ARM version for MacOS https://www.zen-browser.app/download and it is corrupted

<img width="248" alt="Screenshot 2024-08-24 at 5 22 00 PM" src="https://github.com/user-attachments/assets/d80edde6-dc41-4dbb-960a-bdf18de7aa8b">

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

latest

### Severity impact

Critical

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by mauro-balades** [comment]
please checkout https://docs.zen-browser.app/guides/install-macos

**Comment by khanakia** [comment]
Why is there so much hassle just to install a web browser?

It should just install like any other web browser app

**Comment by n7itro** [comment]
> Why is there so much hassle just to install a web browser?

You would know that if you actually read the guide.

Apple forces developers to pay a fee of $99, or else they mislead users into believing the app is damaged. The developer of Zen has payed this fee, and is now waiting to receive this license.

**Comment by mauro-balades** [comment]
I've bought my license but apple needs 2 days till they give it to me
