### ISSUE TITLE
Make the sidebar function more like the tab bar.

### ISSUE THREAD

**Issue by CrynTox** [zen-browser/desktop#572]
### What feature would you like to see?

Currently when you make the sidebar visible it resizes the whole viewport and there's no animation which makes it stand stand out in a bad way. What would be ideal is that it goes over the viewport with a similar animation as the tabs bar.

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/796

 ~ This is an automatic operation to better enhancements requests organization.
