### ISSUE TITLE
[Sync] Firefox account automatically gets logged out

### ISSUE THREAD

**Issue by maphapthieunu** [zen-browser/desktop#573]
### What happened?

This is reproducible by adding a Firefox account to Zen Browser (latest version downloaded from the website). After a few seconds, my account automatically gets logged out.

This didn't happen on Ablaze Floorp.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.28

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by b-risk** [comment]
I'm experiencing this too, what was your solution to solve it?

**Comment by r-tokarski** [comment]
I'm also having the same issue. Zen's version is 1.0.1-a.6, Flatpak version running on OpenSUSE Tumbleweed.
