### ISSUE TITLE
Add "Restore Closed Tab" as a Keyboard Shortcut

### ISSUE THREAD

**Issue by Zam7am** [zen-browser/desktop#574]
### What feature would you like to see?

Essentially, if a tab is (by mistake) closed, being able to reopen the last closed tab via a keyboard shortcut. (eg. ctrl+z)

**Comment by Tohjuler** [comment]
You can already do this with ctrl+shift+t, but it would be nice to be able to change the shortcut.

**Comment by LICF01** [comment]
This would be very nice to be able to customize, for me ctrl+shift+t and ctrl+t cycles previous and next tab, even though I set those actions to ctrl+shift+tab, ctrl+tab and ctrl+t to new tab

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/795

 ~ This is an automatic operation to better enhancements requests organization.

**Comment by khaled-0** [comment]
The Ctrl+Shift+T shortcut isn't working for me, It does not restore closed tabs
