### ISSUE TITLE
Hide Extension Name Theme / Extension

### ISSUE THREAD

**Issue by enesbala5** [zen-browser/desktop#575]
### What feature would you like to see?

I currently use an extension for my New Tab, which causes the search box to start with "Extension Name: ..."

Would be great if we could have a theme which hides the name, or only displays it on-hover.

Thank you!

**Comment by dewantawsif** [comment]
Are you sure it's not an extension quirk? Also you should drop the extension name for debugging purpose

**Comment by enesbala5** [comment]
I am looking for a change like this;

![image](https://github.com/user-attachments/assets/02bbcea1-f0b7-483c-8d3b-bb181af6a3fd)

---

In this thread, I believe they found a way to solve it. Hope it's useful.

https://discourse.mozilla.org/t/make-addressbar-text-extension-name-of-the-extension-shorter-or-hide/28026/3

Thank you!

**Comment by NOCanoa** [comment]
that could easily be a theme, i currently cant create it : /

**Comment by enesbala5** [comment]
Yeah that was my first instinct also. I don't have the time to work on it, but hopefully is free. Thanks in advance.

**Comment by ch4og** [comment]
I created and submitted theme made for you https://github.com/zen-browser/theme-store/pull/173

**Comment by enesbala5** [comment]
@NOCanoa Thank you! That was really quick.

Appreciate it friend
