### ISSUE TITLE
Add additional "copy URL" shortcuts

### ISSUE THREAD

**Issue by ahgraber** [zen-browser/desktop#576]
### What feature would you like to see?

One of the features I use most in Arc is the 'copy URL as markdown' which allows me to copy the page title and url into markdown formatting

On mac, that default shortcut is `cmd+shift+option+v`

When I use it on Zen Browser's homepage, here is what it pastes: `[Zen Browser](https://www.zen-browser.app/)`

**Comment by enesbala5** [comment]
This is very important to users switching from Arc.

I would recommend Ctrl + Shift + C - that's the Arc default on Windows.

Hopeful we can remap it in settings.

**Comment by enkvadrat** [comment]
Ctrl + Shift + C is used to open the inspector.

**Comment by enesbala5** [comment]
Well so is Ctrl + Shift + I & F12 - maybe it's a bit redundant at this point.

**Comment by anatasiajp** [comment]
I think I can add this feature, but later.

**Comment by enesbala5** [comment]
@anatasiajp Would be much appreciated! Thank you

**Comment by enkvadrat** [comment]
Sorry Ctrl + Shift + C toggles "Pick an element for page" and the inspector

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/794

 ~ This is an automatic operation to better enhancements requests organization.
