### ISSUE TITLE
Add Pin Tab Keyboard Shortcut

### ISSUE THREAD

**Issue by enesbala5** [zen-browser/desktop#577]
### What feature would you like to see?

A feature which Arc nails is the pinned tabs one. We are 99% there in Zen - but we need a keyboard shortcut to Pin a Tab.

There are extension like this one which do the job:

https://addons.mozilla.org/en-US/firefox/addon/toggle-pin-tab/

Hope it's integrated in Zen soon

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/793

 ~ This is an automatic operation to better enhancements requests organization.
