### ISSUE TITLE
Show Next Tab / Show Previous Tab keybinds: Nothing happens

### ISSUE THREAD

**Issue by tommerty** [zen-browser/desktop#580]
### What happened?

One thing I hate about Windows is needing to use `ctrl`+`meta`+`pageup/pagedown`.

I got super excited when I saw the options for `Show Next Tab` & ` Show Previous Tab` however sadly they do not appear to be doing anything.

![Image](https://github.com/user-attachments/assets/91928b51-da5e-45f2-990f-18c4c4de344b)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.28 (64-bit)

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by rrojan** [comment]
+1. Nothing happens when pressing them.

**Comment by bw8686** [comment]
Yep, can reproduce here too.

**Comment by x140x1n** [comment]
It does work when not using arrow keys in the shortcut

**Comment by gaganchandan** [comment]
+1. It doesn't work with arrow keys, but works with other keys.

**Comment by Remiwi** [comment]
+1. From what I tried, other hotkeys don't work if you use arrow keys, either. Would love a fix

**Comment by kittybwained** [comment]
Yeah, arrow keys dont seem to work very well, but Ctrl+Alt+O for example does

**Comment by salamijason** [comment]
Next update will re-add the fixed ver of these shortcuts into the browser.
