### ISSUE TITLE
Unable to download browser languages

### ISSUE THREAD

**Issue by XcOM987** [zen-browser/desktop#581]
### What happened?

When in settings, attempting to download a new language for the browser, is met with a prompt to say it can't and suspects there to be a network issue:

![image](https://github.com/user-attachments/assets/deb2655f-b6fa-4008-8898-edbc3c7e86f8)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.28

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
Translations arent out yet. Probably for the next release
