### ISSUE TITLE
[ BUG ] Hidden Tabs and Inconsistent Tab Behavior with "Ctrl + Click" + Hotkey problems

### ISSUE THREAD

**Issue by Evren-os** [zen-browser/desktop#582]
## Description

Multiple issues have been identified in the Zen browser related to tab management and hotkey functionality:

1. **Hidden tabs when opening multiple links from default tab**
   When using "Ctrl + Click" to open multiple links from the first tab (opened by default), closing the first new tab results in only the first link being visible. Other tabs are opened but hidden from view.

2. **Inconsistent "Ctrl + W" functionality**
   The "Ctrl + W" hotkey sometimes fails to close tabs as expected.

3. **"Ctrl + Click" not always opening links in new tabs**
   On some links, using "Ctrl + Click" does not successfully open the link in a new tab.

### Issue 1: Hidden Tabs

1. Open Zen browser with the default first tab.
2. "Ctrl + Click" multiple links from this default tab to open them in new tabs.
3. Close the first newly opened tab.
4. Observe that only the first link is visible, while other tabs are hidden (but still open).

### Workaround for Issue 1

1. Open a website in the first tab.
2. Open a new tab.
3. "Ctrl + Click" multiple links from this new tab.
4. Tabs now open and remain visible as expected.

### Issue 2: Inconsistent "Ctrl + W" Functionality

1. Open multiple tabs in Zen browser.
2. Attempt to close tabs using "Ctrl + W".
3. Observe that sometimes the hotkey fails to close the tab.

### Issue 3: "Ctrl + Click" Not Opening New Tabs

1. Navigate to a webpage with multiple links.
2. "Ctrl + Click" on various links.
3. Observe that some links do not open in new tabs as expected.

## Expected Behavior

1. When opening multiple links using "Ctrl + Click" from any tab, all new tabs should remain visible and accessible, regardless of which tab is closed.
2. The "Ctrl + W" hotkey should consistently close the active tab.
3. "Ctrl + Click" should reliably open links in new tabs for all clickable links.

## Actual Behavior

1. Tabs opened from the default first tab become hidden when the first new tab is closed.
2. "Ctrl + W" sometimes fails to close tabs.
3. "Ctrl + Click" doesn't always open links in new tabs.

## Additional Information

- Video to understand the first issue : 

https://github.com/user-attachments/assets/07abcdfc-fab6-4ccf-b77d-dcc63a53ce55

Drive Link : https://drive.google.com/file/d/1XDI8KRVN68D6UDw0YltGTY0Bw34QAhcV/view?usp=sharing

- Operating System: Arch Linux

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.28

### Severity impact

Critical

### What platform are you seeing the problem on?

Linux

**Comment by Evren-os** [comment]
> i'm not too sure this is a "critical severity" bug...
I selected it by mistake

**Comment by DutchPete** [comment]
I am using the Zen flatpak version on Linux (LMDE) and have not experienced issues 2 and 3, even though I use those shortcuts a lot.

**Comment by Evren-os** [comment]
Alpha 34 doesn’t have these problems. Appreciate it, Mauro!

**Comment by Evren-os** [comment]
Alpha 34 doesn’t have these problems. Appreciate it, Mauro!

**Comment by mauro-balades** [comment]
😁👍
