### ISSUE TITLE
Can't start windows installer 

### ISSUE THREAD

**Issue by iamenews** [zen-browser/desktop#585]
### What happened?

Upon running the installer setup wizard, I get hit with this error message: 
`Windows cannot access the specified device, path, or file. You may not have the appropriate
permissions to access the item.`

Can't seem to find anything related to this in the issues. 
![image](https://github.com/user-attachments/assets/a0769aa9-f420-4fff-bc06-1de48a0b5e4e)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Optimized

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by NOCanoa** [comment]
can u try generic version?

**Comment by iamenews** [comment]
<img width="413" alt="image" src="https://github.com/user-attachments/assets/2f8b1450-9459-48e3-ae00-6d9af1e4fc2b">
hiya, same issues still with the generic version. according to the docs my computer should be able to use the regular version though.

**Comment by NOCanoa** [comment]
Next version will be out later today, let me know if it works whit that one.

**Comment by iamenews** [comment]
yep i'll check it out. Hope it gets fixed so i can try this one out!

**Comment by Suman2023** [comment]
I think it already works. Just(a minute ago) downloaded it from the website and it is working. here: 
![image](https://github.com/user-attachments/assets/6c904d73-f52f-44f4-adba-aad5b36d2480)

**Comment by iamenews** [comment]
Heya @NOCanoa Just tried the new build, it still throws the same error.

**Comment by NOCanoa** [comment]
Could I have a look at win defender , is he doing something on deleting stuff?

**Comment by iamenews** [comment]
Can't really see anything specific where this may be causing an issue, is there any setting you recommend me looking at? Could this also be because there isn't any signed cert?

**Comment by ch4og** [comment]
This looks like a problem with user's local policies, I don't think it's a browser problem

**Comment by mauro-balades** [comment]
It's possible that it's being restricted by your computer, like you are using some sort of company computer where you dont have permissions? Try running it with administrator

**Comment by iamenews** [comment]
I am using a computer that's enrolled under a policy, and I'm guessing that's the issue, but there aren't any app restrictions that I know of 
I just tried running it as administrator and yep that didn't work either 

I wonder if the issue is related to fact that this is an unsigned app

**Comment by mauro-balades** [comment]
Probably, I'll look into it but chances are you simply don't have the permissions to do it

**Comment by iamenews** [comment]
Yeah, this has never happened with anything else I've downloaded though :(

**Comment by mauro-balades** [comment]
Related to https://github.com/zen-browser/desktop/issues/37... try disabling windows defender maybe?

**Comment by iamenews** [comment]
I'll try that out, but I just got the browser working downloading it as a package. 
I do have a question though, there isn't an option to set it as my default browser - how do i go about doing that? 
![image](https://github.com/user-attachments/assets/81d6e00e-b0bd-4c8d-b0bb-070abd666c30)
(No option to browse apps from PC) 

The prompt in app also doesn't do anything.
