### ISSUE TITLE
The treshhold for the expanded tab sidebar in compact mode is too highissue #389

### ISSUE THREAD

**Issue by Eff0rtly** [zen-browser/desktop#586]
### What happened?

Reduce the effective range of the sidebar automatic pop-up just like the compact mode

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.28

### Severity impact

Medium

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
No log
```

**Comment by mauro-balades** [comment]
This is fixed for the next release

**Comment by mauro-balades** [comment]
G
