### ISSUE TITLE
Chinese IME jump to top left of the window when i type the first letter, but when i type a second letter, it jumps back to the text box.

### ISSUE THREAD

**Issue by Eff0rtly** [zen-browser/desktop#587]
### What happened?

![QQ截图20240824223828](https://github.com/user-attachments/assets/b4ee96d3-8ba5-4ceb-bc67-2751839c4cfc)
The new version of firefox has fixed the problem

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.28

### Severity impact

High

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
No log
```

**Comment by mauro-balades** [comment]
We'll just need to wait for the new firefox release 👍🏽
