### ISSUE TITLE
[BUG] Whatsapp Not Working : Asking to update browser

### ISSUE THREAD

**Issue by Evren-os** [zen-browser/desktop#59]
WhatsApp saying to update Mozilla Firefox to latest while Zen is based on the latest Firefox

![image](https://github.com/user-attachments/assets/7cd6bc07-7b2f-4dac-8ad2-55fc37089214)

**Comment by mauro-balades** [comment]
This has now been fixed! It will be applied for the next release

**Comment by mauro-balades** [comment]
Update: it works!!! You just have to update it!
