### ISSUE TITLE
Not a bug. just performance. Scrolling could be smoother

### ISSUE THREAD

**Issue by patchthecode** [zen-browser/desktop#590]
### What happened?

Load up firefox.
Load up Zen.

put them side by side.

Scroll a long scroll view with items on the page (probably some social media feed)

See firefox scrolling is buttery smooth.
See Zen scrolling is buttery smooth-ish 

Here i am testing my app, in the video below, the left side is firefox, the right side is Zen.
The video doesnt do it much justice, but firefox is mad smooth. Zen is smooth too, but you can see a difference.

https://github.com/user-attachments/assets/444848ae-5ad7-413a-8ca6-dc9de9d02c29

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.28

### Severity impact

Low

### What platform are you seeing the problem on?

macOS - aarch64

### Relevant log output

```shell
nothing
```

**Comment by NOCanoa** [comment]
can u try again whit this theme instaled https://www.zen-browser.app/themes/c6813222-6571-4ba6-8faf-58f3343324f6

**Comment by mauro-balades** [comment]
This has been fixed for the next release
