### ISSUE TITLE
Implement Peek - Preview Websites with ease

### ISSUE THREAD

**Issue by enesbala5** [zen-browser/desktop#592]
### What feature would you like to see?

One of the best features of Arc is "Peek".

![opening-a-Peek-tab-in-Arc-browser](https://github.com/user-attachments/assets/5327baa1-1f35-4611-b096-caa6e6883f42)

---

You can find it explained in detail here:
https://resources.arc.net/hc/en-us/articles/19335302900887-Peek-Preview-Sites-From-Pinned-Tabs

It would be amazing if Zen also implemented it, and with the performance improvements that this browser brings, this feature could be immensely useful.

**Comment by Tc-001** [comment]
You can get a similar effect with https://addons.mozilla.org/en-GB/firefox/addon/side-view/, although it will open it in the sidebar instead of covering the screen as peek would.

**Comment by paradoxally** [comment]
This already exists, albeit not native to Zen and it has limited free uses. 

https://maxfoc.us/

If it was implemented natively to Zen like Arc, that would be the ideal solution.

**Comment by enesbala5** [comment]
I'd rather not install an extension for something which a browser like Arc natively supports.

I think many would find it useful as well.

**Comment by enesbala5** [comment]
> You can get a similar effect with https://addons.mozilla.org/en-GB/firefox/addon/side-view/, although it will open it in the sidebar instead of covering the screen as peek would.

I just noticed that there is a "Split Link to a New Tab" function.

It would be awesome if a shortcut like "Shift + Click" triggered it - this could alleviate the issue on big screens.

On laptops, I believe Peek would be much preferred.

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/790

 ~ This is an automatic operation to better enhancements requests organization.
