### ISSUE TITLE
Console not working on macOS aarch64

### ISSUE THREAD

**Issue by Iziram** [zen-browser/desktop#593]
### What happened?

The console does not seem to be working correctly. I Tried console logs, clear and alert/prompt. Nothing happened. 
JS completions are still working.

Any function used resulted in nothing but its name appearing in the console.

![Capture d’écran 2024-08-24 à 18 42 55](https://github.com/user-attachments/assets/1010ed11-7366-456f-92bc-58f49147325b)

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.28

### Severity impact

Medium

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by mauro-balades** [comment]
Does this work everywhere or just in about: pages?

**Comment by Iziram** [comment]
This happens everywhere.

**Comment by SuperluminalKnight** [comment]
Can confirm this issue exists on Windows 11 also.
Javascript from the console is not being executed

**Comment by stellaOnEstrogen** [comment]
Bug also happens in Windows 11

![image](https://github.com/user-attachments/assets/4fb8355d-6d1e-43d2-ad0b-8b1d36d5a1ad)

**Comment by philosofonusus** [comment]
![CleanShot 2024-08-26 at 12 44 10@2x](https://github.com/user-attachments/assets/6bb803d7-5534-46a6-a59f-a04f69eefb2f)
also happens on Apple M2 Max 14.4.1 (23E224)

**Comment by mart3323** [comment]
Same in 1.0.0-a.29 (.AppImage) on Ubuntu 22.04.4 LTS
![image](https://github.com/user-attachments/assets/91bdea69-77d4-46f9-bb89-b5d654d1fa89)

**Comment by Iziram** [comment]
More informations  (i used browser console from firefox debug ( cmd + shift + J ) )

<img width="1512" alt="Capture d’écran 2024-08-26 à 13 36 33" src="https://github.com/user-attachments/assets/5fdcfda5-1f03-48ea-aa48-500a8e8bb2ae">



![utils js](https://github.com/user-attachments/assets/e34172bd-eb68-43ec-9ac4-b583853df013)


Hope this can help you @mauro-balades

**Comment by mauro-balades** [comment]
@Iziram you are a genius!!!

I recently overriden `firefox-branding.js` in order to add my own urls and stuff. I didnt realize I've removed:

```
// Number of usages of the web console.
// If this is less than 5, then pasting code into the web console is disabled
pref("devtools.selfxss.count", 5);
```

Ill add it right now, ill release it!

Thanks!
