### ISSUE TITLE
Tab bar favicon issue with dark icons

### ISSUE THREAD

**Issue by maldoinc** [zen-browser/desktop#594]
### What happened?

Tab bar favicon: 
![image](https://github.com/user-attachments/assets/d3092416-4d8e-4d4a-b90a-94b369fe2fbd)

Bookmark bar:
![image](https://github.com/user-attachments/assets/fe5f018e-eb72-4982-8386-32ea8d747bb3)

As seen above the Github icon is barely visible in the tab bar but it's fine in the bookmarks. The opposite happens in FF: Tab bar is the inverted one and bookmarks has the one that's barely visible.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.28

### Severity impact

Low

### What platform are you seeing the problem on?

Linux

**Comment by chriskirknielsen** [comment]
I have experienced this as well, and was curious if we could get the ability to rename tabs and perhaps force a background colour on the favicon?

**Comment by mauro-balades** [comment]
This is an issue with the website, not zen. I can't choose what .ico they give me. I found out that force reloading in github changes their icon
