### ISSUE TITLE
Enhance bookmarks theme

### ISSUE THREAD

**Issue by iSaluki** [zen-browser/desktop#595]
### What feature would you like to see?

Currently, the bookmarks toolbar that you can pop out uses the default firefox themeing, as shown.

![image](https://github.com/user-attachments/assets/c6afb113-14aa-4388-a1de-1030d37aa411)

This is functional, but especially when displayed alongside the rest of the browser - as I like to have it on the right with my tabs on the left - it does look misplaced.

Not necessarily as much of a priority, but adding the Zen themeing to the Bookmarks menu would be much appreciated.

Thanks

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/789

 ~ This is an automatic operation to better enhancements requests organization.
