### ISSUE TITLE
Pinned Tabs should be scoped to Workspaces

### ISSUE THREAD

**Issue by enesbala5** [zen-browser/desktop#598]
### What feature would you like to see?

This is very necessary for those who like to separate their tabs into groups. Currently, if you pin a tab, it is global, so it's displayed across workspaces.

This is different from other tabs, which are isolated to their workspace.

This creates a lot of unnecessary trouble and makes it impossible to separate your tabs properly, as they will now be with your regardless of the workspace you're in.

**Comment by guigirl42** [comment]
Pls note my https://github.com/zen-browser/desktop/issues/238#issue-2462230364

**Comment by enesbala5** [comment]
@guigirl42 I see you posted about this earlier. Should I close the issue & link to yours?

**Comment by guigirl42** [comment]
I'm a nobody, just another enthusiastic user like you, so i have no right to tell you to do _anything_, ofc.  That said, my respectful suggestion would be that the github _Issues_ section probably becomes easier to navigate if duplicate reports / requests are identified & rationalised.

**Comment by enesbala5** [comment]
Sure; definitely agree with you. 
Closing the issue now as duplicate of Issue #238
