### ISSUE TITLE
overrides.cfg file

### ISSUE THREAD

**Issue by LordMZTE** [zen-browser/desktop#599]
### What feature would you like to see?

It'd be awesome to have something like Librewolf's `librewolf.overrides.cfg`, a JS file that will be loaded at startup where one can set values for `about:config` flags declaratively. It would make it easier to set up Zen on new machines, as the file can be easily shared across devices.

### Other details

Librewolf's docs on how this works: https://librewolf.net/docs/settings/

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/787

 ~ This is an automatic operation to better enhancements requests organization.
