### ISSUE TITLE
May I ask if you have considered adding right-angle borders in the future?

### ISSUE THREAD

**Issue by SaberAIF** [zen-browser/desktop#60]
It looks like too much
![c5acb85e-8017-4550-84e1-4b82bc04576f](https://github.com/user-attachments/assets/c7fc4bd3-5b49-4a61-9dd9-eb6bdbbc6c3f)

**Comment by mauro-balades** [comment]
I am not planning on doing this however, you can always change everything to how you like by using [userChrome.css](https://www.userchrome.org/)
