### ISSUE TITLE
Allow rules to define what URL opens in what workspace

### ISSUE THREAD

**Issue by srijken** [zen-browser/desktop#600]
### What feature would you like to see?

The workspaces feature would be much more complete if it is possible to add url filters that link to certain workspaces. For instance:
- if url contains azure.com -> use work
- if url contains youtube.com -> use private

**Comment by ThibautPV** [comment]
Here is an example on Arc 
<img width="492" alt="Capture d’écran 2024-08-25 à 17 39 09" src="https://github.com/user-attachments/assets/2b7212de-d3bb-46ae-84bd-d4165225cd98">

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/786

 ~ This is an automatic operation to better enhancements requests organization.
