### ISSUE TITLE
Official Docs Site is misaligned only on Zen Browser

### ISSUE THREAD

**Issue by Z-xus** [zen-browser/desktop#602]
### What happened?

![image](https://github.com/user-attachments/assets/d04de128-2d62-40ad-86a7-102fe26585e7)
<html> tag has lesser height than it should, but this is not the case on firefox.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0

### Severity impact

Low, Enhancement

### What platform are you seeing the problem on?

Linux

**Comment by NOCanoa** [comment]
this is the browser repo, for issues related to docs [here](https://github.com/zen-browser/docs)
