### ISSUE TITLE
Workspace selector doesn't enable scrolling with many workspaces

### ISSUE THREAD

**Issue by katedickey** [zen-browser/desktop#603]
### What happened?

If you create enough workspaces that they exceed the height of your screen, a scroll bar does not appear, leaving workspaces created later to be hidden. Scroll wheel also doesn't allow you to scroll.

![Screenshot_20240824_135431](https://github.com/user-attachments/assets/4b2d43f6-171f-435f-9bc0-9d65cce27099)
![Screenshot_20240824_135449](https://github.com/user-attachments/assets/e4299542-8f2a-480c-b444-cfc49b6534c3)

Related styling issue: horizontal overflow is not handled well either.

![Screenshot_20240824_140551](https://github.com/user-attachments/assets/93372b89-01b0-4e31-a277-07cb5422d38d)
![Screenshot_20240824_140701](https://github.com/user-attachments/assets/c892aebe-db2d-47df-83ff-27dcef1c50b4)

I'd expect ellipses when it is overflowing. It also squishes the left icon which looks messy.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.28

### Severity impact

Medium

### What platform are you seeing the problem on?

Linux

**Comment by tresorama** [comment]
Same bug happens on the Workspace bar in the tabs sidebar. This should be scrollable. 

Should i open a new issue ??

<img width="1680" alt="Image" src="https://github.com/user-attachments/assets/04284f40-69d0-477c-8f3d-c46799071160" />

<img width="436" alt="Image" src="https://github.com/user-attachments/assets/75f41296-bb49-4eb6-b651-8d5864f1d483" />
