### ISSUE TITLE
Ability to rename already created workspaces

### ISSUE THREAD

**Issue by katedickey** [zen-browser/desktop#604]
### What feature would you like to see?

Add an option to the workspace menu to edit the name of a workspace after creation
![Screenshot_20240824_142039](https://github.com/user-attachments/assets/dd05378d-83d7-4dc5-a3e1-c4d9f69915bd)

**Comment by katedickey** [comment]
I have a change mostly ready for this, just working out some styling issues

**Comment by mauro-balades** [comment]
that's great!

**Comment by forteller** [comment]
Hi. I would like to ask that when renaming workspaces, hitting Enter should save the new name. Should I open a new issue for this, or is it ok to just mention it here?

Thank you so much!

**Comment by katedickey** [comment]
@forteller make a new issue for that if it doesn't already exist, this issue is long closed
