### ISSUE TITLE
Unable to sign in to Twitter

### ISSUE THREAD

**Issue by XcOM987** [zen-browser/desktop#605]
### What happened?

When attempting to sign in to twitter, just get a spinning circle, changed privacy settings and DNS settings, to no avail, works in Edge, Chrome, and Firefox.
![image](https://github.com/user-attachments/assets/ebee81ec-40c1-49a1-8c39-2eda71e91a67)

Don't see any obviously errors in the network section of developer section

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.28

### Severity impact

Medium

### What platform are you seeing the problem on?

Windows

**Comment by PixelHir** [comment]
Struggling to reproduce on Windows, clean browser, no extensions. Are you using enhanced tracking protection?

**Comment by XcOM987** [comment]
Fresh install, only extension is password manager, tried with normal tracking protection, with and without secure DNS, and using my own DNS.

**Comment by PixelHir** [comment]
Have you tried checking the JS console?

**Comment by BosadBillaHun** [comment]
I just tried to sign in after seeing this #issue. My twitter got logged in. No issues...
it's not the browser problem ig...

**Extra information**
Zen - 1.0.0-a.28 (64-bit)
Win11 with Adguard manual DNS, no VPN
I've got 9 extensions enabled

**Comment by XcOM987** [comment]
Bizzare, reset browser, tried in troubleshoot mode, same deal, maybe it's time for a reinstall of Windows

**Comment by qtchaos** [comment]
Having the same issue, disabling all of the security features in Browser Privacy section seems to fix it for me.

**Comment by XcOM987** [comment]
> Having the same issue, disabling all of the security features in Browser Privacy section seems to fix it for me.

Bingo, disabling everything in there seemed to do the trick, nice spot

**Comment by BosadBillaHun** [comment]
the new update has rolled out, check if the issue still persist
