### ISSUE TITLE
Auto Collapse Sidebar when invoked from keyboard shortcut in Compact mode.

### ISSUE THREAD

**Issue by Z-xus** [zen-browser/desktop#606]
### What happened?

I try to navigate in my browser primarily with keyboard, but when I use Ctrl+Alt+S to view and select a tab, it won't go away after selecting any tab. I expect that:

a) Either collapse sidebar on pressing Escape key.
b) Make the sidebar auto collapsible even when invoked from keyboard shortcut.

Reproducing steps:
1. Enable Zen Browser's compact mode.
2. Use Ctrl+Alt+S to display sidebar.

I think using a mouse is tedious for such a simple task.. great work with the browser btw!

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0

### Severity impact

Medium, Enhancement

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/785

 ~ This is an automatic operation to better enhancements requests organization.
