### ISSUE TITLE
Close to right right on a side bar?

### ISSUE THREAD

**Issue by KUKARAF** [zen-browser/desktop#607]
### What happened?

When you right click on a tab >> Close multiple tabs, 2 options are visible that are not quite right. 
I believe Close to the right should be called close bellow and close to the left should be called closed above

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.28 (64-bit)

### Severity impact

Low

### What platform are you seeing the problem on?

Linux

**Comment by Zykkl** [comment]
Dupe of #521
