### ISSUE TITLE
Have the ability to delete the default workspace if there is one or more other workspaces available

### ISSUE THREAD

**Issue by astro648** [zen-browser/desktop#609]
### What feature would you like to see?

I would like to see what is in the title.
If the default workspace is the only workspace available, then it should not be able to be deleted.

**Comment by Zykkl** [comment]
You can delete the current default workspace by making another workspace the default. I don't see where an improvement can be made, could you clarify?

**Comment by MaximalCats** [comment]
> You can delete the current default workspace by making another workspace the default. I don't see where an improvement can be made, could you clarify?

I think he means that the "default" title should be moved automatically to the next workspace if the default workspace is deleted.

**Comment by Zykkl** [comment]
I see, that was the only behavior I could think of. In *my* opinion, I'd leave the action of setting your default workspace to the end user, also a bit of extra safety, avoid deleting your main workspace on accident. Debatable

**Comment by MaximalCats** [comment]
> I see, that was the only behavior I could think of. In _my_ opinion, I'd leave the action of setting your default workspace to the end user, also a bit of extra safety, avoid deleting your main workspace on accident. Debatable

Maybe an option to enable this behaviour in the settings could work? Not sure though.

**Comment by astro648** [comment]
> You can delete the current default workspace by making another workspace the default. I don't see where an improvement can be made, could you clarify?

Oh, I didn't realize that. Thank you, sorry about that! Should I close this?

**Comment by Zykkl** [comment]
If that solves your issue, sure :)
We can also leave it open in case we want to further look into this feature.

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/784

 ~ This is an automatic operation to better enhancements requests organization.
