### ISSUE TITLE
Sidebar width in incognito mode not consistent outside of incognito

### ISSUE THREAD

**Issue by SilvverJav** [zen-browser/desktop#61]
Hey there, appreciate the work and effort you're putting into this project.
I gotta say, I've been loving the feel of Zen and I'm pretty excited for what's to come

Anyways, I've encountered what appears to be some sort of design bug where when using the browser in incognito mode, the size of the sidebar is a little bit wider than usual compared to a normal Zen window. Probably not intended.
Attached below is a screenshot of what it looks like normally:
![Normal](https://github.com/user-attachments/assets/2f900010-4c99-4ff8-aec6-4b8beffb7f9c)

And this is what the bar looks like in an incognito window:
![Incognito](https://github.com/user-attachments/assets/4559f1ea-f4c6-4b4a-8d50-114a7b2b4330)

I'm running the browser on Fedora 40, all AMD setup.

**Comment by mauro-balades** [comment]
hey, sorry for taking that long! It's been fixed in https://github.com/zen-browser/desktop/commit/80f8e829dfa1e5519be100c6a307df9bf4824164 and it will take place on the next release!
