### ISSUE TITLE
Add abilty to disable autofill.

### ISSUE THREAD

**Issue by cmdNiels** [zen-browser/desktop#610]
### What feature would you like to see?

I would like to see a setting to disable the autofill popup and the save credentials feature.

**Comment by qtchaos** [comment]
You can already do this in Firefox (and therefore Zen) by going to Settings > Privacy & Security, then scrolling down to the passwords section.

![image](https://github.com/user-attachments/assets/185e3c74-af6f-4726-915b-cb6e74b890c1)

**Comment by cmdNiels** [comment]
Thank you very much.

**Comment by dvogt23** [comment]
but its not matching a search for 'pass' 😆
