### ISSUE TITLE
deadzone setting for sliding parts of the browser 

### ISSUE THREAD

**Issue by adasteruete** [zen-browser/desktop#613]
### What feature would you like to see?

so the idea is u can set up a custom dead zone for the tabs bar on the left and the upper part that's hidden if you changed it to being hidden and used only upon moving the mouse closer. instead of moving the mouse to the very edge of the screen u set up a custom dead zone so the hidden parts show up when the mouse is in the zone that makes it show up.

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/783

 ~ This is an automatic operation to better enhancements requests organization.
