### ISSUE TITLE
Shortcut for opening a new tab onto the currently open tab

### ISSUE THREAD

**Issue by MaximalCats** [zen-browser/desktop#615]
### What feature would you like to see?

Title is a bit confusing, but what i mean is that, if i have a (one) tab open, i want to be able to press a shortcut that splits the current tab with a new tab (about:newtab)

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/782

 ~ This is an automatic operation to better enhancements requests organization.
