### ISSUE TITLE
Open link in new tab instead of replacing the current

### ISSUE THREAD

**Issue by Suman2023** [zen-browser/desktop#616]
### What feature would you like to see?

Can there be a checkbox in the setting to open link in new tab instead of replacing the current. It is possible if the link is clicked holding the control. Can we make that toggle-able in the settings.
It can be achieved using the config (browser.link.open_newwindow) but there is no explicit UI to do that.

Thanks for the amazing work. Enjoying my switch.

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/781

 ~ This is an automatic operation to better enhancements requests organization.
