### ISSUE TITLE
chore(visual): deleting all search content after site opened removes border-radius and margin

### ISSUE THREAD

**Issue by qtchaos** [zen-browser/desktop#617]
### What happened?

When you're on a site and decide to type something in the URL bar, the border-radius and margin seem to disappear from the right side on the search icon div.

## Examples
![image](https://github.com/user-attachments/assets/f0b4adf6-d241-4977-8a2a-169d742425ab)
![zen_example1](https://github.com/user-attachments/assets/290bb6fd-b7b5-4b6f-8b35-3922e6866c32)

## Expected behavior
![image](https://github.com/user-attachments/assets/463a297a-d426-4244-9544-7194bb96dc66)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a29

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
This has been fixed in version 37 iirc, please update it. Thanks!
