### ISSUE TITLE
License Inconsistency in README.md

### ISSUE THREAD

**Issue by thisisarnabdas** [zen-browser/desktop#62]
There is an inconsistency regarding the licensing information in the project. The README.md file mentions the MPL license, but the provided link directs to the MIT license. Additionally, there is no separate LICENSE file that explicitly states the project's license.

Please clarify which license applies to the project and update the documentation accordingly.

Thank you.

**Comment by mauro-balades** [comment]
Thanks for reporting this! It is now fixed. Sorry for taking so long, I'm in a remote place for a couple of days and I can't do much. Thanks!

**Comment by thisisarnabdas** [comment]
There is a slight error in the link.
The link should be this: https://github.com/zen-browser/desktop/blob/main/LICENSE
