### ISSUE TITLE
Keyboard shortcuts don't work after being remapped

### ISSUE THREAD

**Issue by g-ioannou** [zen-browser/desktop#622]
### What happened?

Remapped some keys and they are not working as expected.

In the attached video I try to create some grid, vertical and horizontal splits with the remapped keys. Then for some reason the setting button does not work. Then I try to create a new tab using the shortcut but all I get is flickering. After I add a new tab with the mouse the shortcut starts working. Closing tabs shortcut also doesn't work (CMD+w)

[Trying to make something happen with shortcuts video](https://streamable.com/jr5q5g)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.29

### Severity impact

Medium

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by DwieDave** [comment]
I have experienced the same bug on macOS Sonoma 14.5 with Zen Browser Version 1.0.0-a.29

I tried to remap the Split View commands and after that the new Tab isn't working anymore.
The "File" Menu Bar Item is flickering but only executing the CMD+T Shortcut when the File-Menu is opened.

When remapping to another shortcut (e.g Ctrl+Alt+T) The Ctrl is interpreted as CMD and if you then press CMD+Alt+T it works as expected.

Maybe it's also related to #376
