### ISSUE TITLE
Click and Drag on sidebar sites to reorganize.

### ISSUE THREAD

**Issue by bw8686** [zen-browser/desktop#623]
### What feature would you like to see?

I believe clicking and dragging would be a very nice addition to sidebar so you don't have to remove all sidebar sites to reorganize them.

**Comment by guigirl42** [comment]
Seems same as https://github.com/zen-browser/desktop/issues/257 :woman_shrugging:

**Comment by IAmJafeth** [comment]
Duplicate #257
