### ISSUE TITLE
Page background missing

### ISSUE THREAD

**Issue by mayank99** [zen-browser/desktop#626]
### What happened?

It seems like Zen doesn't set a `background-color` on the `html` element, which breaks any website that relies on there being a default page background. (The default rule should be `html { background-color: Canvas; }`)

| Expected | Actual |
| --- | --- |
| <img width="562" alt="" src="https://github.com/user-attachments/assets/681a2542-e17e-4f84-885e-9651e97614c9"> | <img width="562" alt="" src="https://github.com/user-attachments/assets/20c5148c-8984-4353-9c93-e0ffc5cd43f7"> |

This can be seen on a lot of websites, for example [docs.deno.com](https://docs.deno.com/) (see [screenshot](https://github.com/user-attachments/assets/bd7bfdc5-fd09-4fd5-bb08-5219fb20fe25)).

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.29

### Severity impact

High

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by mauro-balades** [comment]
![Screenshot_20240825_222523](https://github.com/user-attachments/assets/3bcb34b2-a4ce-48c7-bb08-fe685fb1ed5f)

hm... I dont seem to be able to reproduce it

**Comment by mayank99** [comment]
You might need to go into `about:addons` and enable the "Dark" theme.

**Comment by HarryHeres** [comment]
@mayank99 I was unable to reproduce this on my MBP with Dark theme set to "Enabled" on Zen version 1.0.0-a.32. Would you mind trying that version? Any extensions used?

**Comment by mayank99** [comment]
No luck on 1.0.0-a.32. I've tried it with extensions disabled and even tried it in [Safe mode](https://support.mozilla.org/en-US/kb/diagnose-firefox-issues-using-troubleshoot-mode).

It's worth noting that even the "Light" theme set in `about:addons` is missing the page background. Instead of the background being fully white, there is a tint of the theme color (crimson/pink-ish hue in my case).

<img width="947" alt="" src="https://github.com/user-attachments/assets/9145f22e-49f1-41d2-9479-0c4260c4b0e5">

**Comment by HarryHeres** [comment]
> No luck on 1.0.0-a.32. I've tried it with extensions disabled and even tried it in [Safe mode](https://support.mozilla.org/en-US/kb/diagnose-firefox-issues-using-troubleshoot-mode).
> 
> It's worth noting that even the "Light" theme set in `about:addons` is missing the page background. Instead of the background being fully white, there is a tint of the theme color (crimson/pink-ish hue in my case).

Hmm, weird. Are you running any themes/extensions?

**Comment by mayank99** [comment]
No. Like I said, the behavior is the same without any extensions/themes.

**Comment by mayank99** [comment]
Interestingly, I created a new browser profile and it works fine. It's possible that my original profile is permanently broken somehow. I have no clue why though.

Since this issue is so difficult to reproduce and I've found a workaround, I'll close it out.
