### ISSUE TITLE
Having too many tabs open sometimes results in the sidebar and website content expanding past window boundaries

### ISSUE THREAD

**Issue by tulpenkiste** [zen-browser/desktop#629]
### What happened?

I was attempting to use the browser but website content was extending past the window boundary (1920x1036).
I don't really know how else to describe it

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.28

### Severity impact

Low

### What platform are you seeing the problem on?

Linux

**Comment by IAmJafeth** [comment]
Hi @tulpenkiste 

I attempted to replicate this with 50 tabs open and I was unable to replicate it.
Could you please attach a screenshot of the problem and also specify how many tabs did you have opened when this error occurred? 

This details will help troubleshoot this error, thank you!

**Comment by Sapeiidw** [comment]
![image](https://github.com/user-attachments/assets/b3afd6f9-db03-45f7-9a40-60db827f28f6)
Like this?

**Comment by tulpenkiste** [comment]
No, I mean it expands vertically

**Comment by tulpenkiste** [comment]
Also I'm noticing I can't replicate it after upgrading so I'm going to close it (and reopen if it eventually replicates itself)
