### ISSUE TITLE
Margins not equal on MacOS

### ISSUE THREAD

**Issue by Catlilface** [zen-browser/desktop#631]
### What happened?

Tab margins are not equal by x-axis on MacOS version (screenshots)
<img width="63" alt="Screenshot 2024-08-25 at 03 06 54" src="https://github.com/user-attachments/assets/f7c50eac-dc4a-41e2-9824-1244b16b1d9b">
<img width="193" alt="Screenshot 2024-08-25 at 03 08 05" src="https://github.com/user-attachments/assets/c936cea4-d02d-487b-a776-d2c3277e94cf">

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.29

### Severity impact

Low

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by NOCanoa** [comment]
Should be fixed on latest version, u can reopen the issue if it persists.
