### ISSUE TITLE
No link to mozilla.addons after installing extention

### ISSUE THREAD

**Issue by Fuuruko** [zen-browser/desktop#635]
### What happened?

![image](https://github.com/user-attachments/assets/6d63f712-bb79-499b-8efe-dedfd2380d51)
![image](https://github.com/user-attachments/assets/39f9d001-5e9f-4336-8174-9fb9d08e14ef)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.29

### Severity impact

Low

### What platform are you seeing the problem on?

Linux

**Comment by IAmJafeth** [comment]
Hi @Fuuruko 

I can confirm the same behavior happens in Firefox, also you can use the search bar a the top in case you want to install new extensions.

![image](https://github.com/user-attachments/assets/1442138b-47e8-4c44-bcce-4b44c1b7c26c)

**Comment by mauro-balades** [comment]
You should report this to firefox, you can use the search bar to access the addons page as @IAmJafeth stated

**Comment by Fuuruko** [comment]
@IAmJafeth Year, i found that i can use search bar, it was just i never used it before because firefox has 'find more add-ons' button
