### ISSUE TITLE
Transition to tabs

### ISSUE THREAD

**Issue by andermendz** [zen-browser/desktop#638]
### What feature would you like to see?

I suggest adding a subtle transition to the tabs when clicking on them considering they increase their size, even if it's for less than a second I would look nicer, and better.

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/779

 ~ This is an automatic operation to better enhancements requests organization.
