### ISSUE TITLE
Resizing DevTools feels laggy

### ISSUE THREAD

**Issue by andermendz** [zen-browser/desktop#639]
### What happened?

Been developing and using it for my workflow, resizing the DevTools feels laggy in comparison with Firefox Developer and even with Google Chrome

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0

### Severity impact

Low

### What platform are you seeing the problem on?

Linux

**Comment by anatasiajp** [comment]
Can you install this theme and test again ? 

https://www.zen-browser.app/themes/c6813222-6571-4ba6-8faf-58f3343324f6

**Comment by andermendz** [comment]
> Can you install this theme and test again ?
> 
> [zen-browser.app/themes/c6813222-6571-4ba6-8faf-58f3343324f6](https://www.zen-browser.app/themes/c6813222-6571-4ba6-8faf-58f3343324f6)

Tried, no changes so far. Executed again with the theme applied, still very laggy DevTools.

**Comment by rrojan** [comment]
Can't repro on mine. Ubuntu, installed with flatpak.

Do you get a resize cursor when you try to resize devtools, or the normal pointy one? Ref: https://github.com/zen-browser/desktop/issues/682

**Comment by bw8686** [comment]
Can reproduce and the issue goes away if i install disable rounded corners.

**Comment by mauro-balades** [comment]
We have to do something about rounded corners...

**Comment by anatasiajp** [comment]
> We have to do something about rounded corners...

Temporarily disable it and research other solution, performance is important and it dropped Speedometer score to lower than Floorp, Firefox by 40%
