### ISSUE TITLE
Issue: Tab Bar Icons Hidden When Many Tabs are Open

### ISSUE THREAD

**Issue by Evren-os** [zen-browser/desktop#64]
**Description:**

When a large number of tabs are open, the icons in the tab bar (such as bookmarks, history, profiles, etc.) are pushed down and become inaccessible. Users cannot access these icons until they close some tabs to bring the icons back into the viewport.

**Steps to Reproduce:**

    Open a large number of tabs in the browser.
    Observe the sidebar on the left side of the screen.

**Expected Behavior:**
All sidebar icons should remain accessible regardless of the number of tabs open.

**Actual Behavior:**
Sidebar icons are pushed down and hidden when too many tabs are open, making them inaccessible.

**Screenshots:**
![image](https://github.com/user-attachments/assets/c8b92f82-a8ba-4e9f-873c-eb59502f36fb)

**Environment:**

    Browser Version: 1.0.0-a4 (64 bit)
    Operating System: Arch Linux

**Comment by mauro-balades** [comment]
This is now fixed (experimentally) in https://github.com/zen-browser/desktop/commit/a4a1aa5c438141eaa000269278f6b2d9bd44d272. It will be applied for the next release!
