### ISSUE TITLE
Appiclation error

### ISSUE THREAD

**Issue by hasandebug** [zen-browser/desktop#640]
### What happened?

I am trying to install zen but I'm getting an error name APplication error with the code (0xc0000142).

![image](https://github.com/user-attachments/assets/9413841c-a9e2-43f2-a33b-cb6c3909be9d)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0 -a2.9

### Severity impact

Low, Medium

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
Your CPU is not supported, please use the generic version from the downloads page
