### ISSUE TITLE
Add base16 framework support

### ISSUE THREAD

**Issue by PlusMinus0** [zen-browser/desktop#641]
### What feature would you like to see?

Adding native support for [base16](https://github.com/chriskempson/base16) automatically provides a access to a huge amount of [color schemes](https://github.com/chriskempson/base16-schemes-source) without having to reinvent the wheel.

This could be done either by providing a config file that can be overridden (thus enabling easy system wide pallette switching through [flavours](https://github.com/misterio77/flavours) for example) or by integrating the schemes it into the theme store (for convenience) or both.

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/778

 ~ This is an automatic operation to better enhancements requests organization.
