### ISSUE TITLE
[bug] missing icon in waybar's hyprland/window module on fresh install

### ISSUE THREAD

**Issue by nktnet1** [zen-browser/desktop#643]
### What happened?

This is what I see when opening Zen browser (missing icon):

![zen browser](https://github.com/user-attachments/assets/db083eae-a562-41d7-8c89-0c4ad4a903dc)

I had expected to see icons similar to Firefox, Chrome or Edge:

![firefox](https://github.com/user-attachments/assets/3bb0586f-6008-4fea-985f-40e1fef4940d)
![chrome](https://github.com/user-attachments/assets/65cbb747-0058-4573-94c3-356c012478c8)
![edge](https://github.com/user-attachments/assets/7558566b-523c-4301-9a63-e3942caf8f7d)

---

My waybar's hyprland/window module configuration is:
```json
    "hyprland/window": {
        "icon": true,
        "icon-size": 18,
        "format": "{}",
        "max-length": 200,
        "separate-outputs": true
    },
```

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Mozilla Zen 1.0.0-a.29

### Severity impact

Low

### What platform are you seeing the problem on?

Linux

---

There is a Zen icon visible in wofi though:

![image](https://github.com/user-attachments/assets/94c36e89-473e-4ba4-97f1-a821fa125b38)

**Comment by takase1121** [comment]
This might be relevant to #449 because Zen isn't correctly reporting it's WM class.

**Comment by nktnet1** [comment]
Issue has been resolved

![image](https://github.com/user-attachments/assets/6f81a89c-9bdf-4522-b151-b54a6bf2bd61)
