### ISSUE TITLE
Apply installed extensions to Zen Sidebar

### ISSUE THREAD

**Issue by fanesz** [zen-browser/desktop#645]
### What feature would you like to see?

I would like to see my installed extensions applied to the Zen Sidebar.
The reason is: I have the "Dark Reader" extension installed, which makes every website appear in dark mode.
Without it, my eyes burns. Thanks!

**Comment by KiKaraage** [comment]
Extensions are actually applied at Web Panels, but for some reason Dark Reader doesn't....

![image](https://github.com/user-attachments/assets/58174bf5-4711-46a3-8a91-b722164e9599)
 
At least in my Zen, the working extensions are:
- Gesturefy
- UBlock Origin
- Enhancer for Youtube
- Minimal Theme for X
- Copy Link URL
- Reddit Enhancer

I explored other extensions and [this Dark Mode addon](https://addons.mozilla.org/en-US/firefox/addon/dark-mode-by-albert-inc/) worked well, although it's mostly an invert mode - Dark Reader is much better at this.

Perhaps you can request the Dark Reader dev to improve its capability with Zen Browser?

**Comment by fanesz** [comment]
okay, thank you @KiKaraage

**Comment by fanesz** [comment]
@itstamimi yup that'll work, but I prefer zen sidebar because it's floating

![image](https://github.com/user-attachments/assets/2fc44563-3218-4fe5-a8f4-92b1eb035d28)
