### ISSUE TITLE
Bug: Side tab don't show the sticky tabs and + sign when you have many tabs open

### ISSUE THREAD

**Issue by itstamimi** [zen-browser/desktop#646]
### What happened?

If you have many tabs opened beyond the size of the side panel, you can't access the plus sign to open a new tab nor the sticky one, unlike the normal behavior in firefox. Right now, if I need to access any of these, I have to scroll through my hundreds of tabs to access them, defeating the purpose to have them.
![Screenshot_20240825_030418](https://github.com/user-attachments/assets/3839f678-bc3d-4e72-a21a-8e0eb69f2c52)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0.a28

### Severity impact

Enhancement

### What platform are you seeing the problem on?

Linux, Windows

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/776

 ~ This is an automatic operation to better enhancements requests organization.
