### ISSUE TITLE
Enpass browser extention not working 

### ISSUE THREAD

**Issue by boldlion** [zen-browser/desktop#647]
### What happened?

My password manager of choice (Enpass) works in any browser that I've thrown at it except for Zen Browser. 

The extension gives me a 403 error - seems like the problem is the browser "Browser requesting the data is not code signed."

![Screenshot 2024-08-25 at 10 09 33](https://github.com/user-attachments/assets/7b352bb2-327f-456b-ab47-49b4a8921128)

Basically, no password manager, no browser for me. In 2024, we all rely on security and having a password manager. 

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.29 (69-bit)

### Severity impact

Critical

### What platform are you seeing the problem on?

macOS - aarch64

### Relevant log output

```shell
Here's the diagnostic that I see:

browser

    code : 3
    origin : moz-extension://da3c58ca-5e04-4b30-bac3-5217b368e0fd
    path : /Applications/Zen Browser.app/Contents/MacOS/zen
    port : 49878
    server_port : 10391
```

**Comment by mathys-lopinto** [comment]
Hello,
I'm not on macOS, but in Windows/ Linux Enpass working. Can you check if, in the settings you have disable "Authorize Browser With Verified Code Signatures Only"
![Uploading image.png…]()

**Comment by boldlion** [comment]
I did have that checked in. Now, what does that mean security-wise? Because it's slightly concerning that I have to uncheck that

**Comment by mathys-lopinto** [comment]
"Browser Validity Check- When a browser extension tries to connect to the main Enpass app, we also verify its authenticity by checking its code signature i.e. browser must be code signed with relevant company’s certificate (i.e Chrome is signed by Google). If a browser is code signed and not in our whitelist, an additional confirmation is required whether it should be allowed to connect to Enpass or not. Note: Browser Validity Check is not done on Linux as code signing is not available there."

Actualy Zen is not signed, that why you have to unckeck the setting.

Source: https://support.enpass.io/docs/security-whitepaper-enpass/browser_extensions.html

**Comment by boldlion** [comment]
Thank you for that. 

Do we know what's the reason for Zen not to be signed?

**Comment by mathys-lopinto** [comment]
This must be because the signature is expensive, and even if the browser were signed, it would have to be whitelisted by Enpass. ("in our whitelist")

**Comment by boldlion** [comment]
That might it.

Unchecking that in Enpass certainly solved the problem. I can confirm that.
