### ISSUE TITLE
Keyboard Shortcut Customization for Devtool Window

### ISSUE THREAD

**Issue by niclas-j** [zen-browser/desktop#648]
### What feature would you like to see?

I would like to be able to customize the keyboard shortcut to open the devtools (inspect etc...). It would also be nice to be able to customize the shortcuts inside of the devtools.

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/775

 ~ This is an automatic operation to better enhancements requests organization.
