### ISSUE TITLE
Android version and Workspace

### ISSUE THREAD

**Issue by GunGunGun** [zen-browser/desktop#65]
Hi, thanks for making such a great web browser, it's fast, beautiful and useful! Especially Workspace, it improves my workflow by a lot being able to separate my work groups.

Currently there's a big issue with Firefox-based browsers, it's Android version being weak, I would love to have an Android version with Workspace and it's pretty much completed, it's the only feature that Firefox Android currently lacking to improve productivity.

**Comment by mauro-balades** [comment]
Hi! It makes me so happy to hear you liked it! Unfortunately, I am not planning on doing a mobile version (right now) as this is just a one map project and there's a limit to what I can do without going insane. Sorry
