### ISSUE TITLE
Problem in opening profile when expand tabs on hover is enabled

### ISSUE THREAD

**Issue by raghavsrvt** [zen-browser/desktop#652]
### What happened?

When expand tabs on hover is enabled and I want to view my profile, I click on the profile image and then after I want to for example add a profile, then the expanded tabs collapse and I have to move my cursor again to perform the operation.
![ezgif-6-ad4a5da519](https://github.com/user-attachments/assets/36a4a761-ba63-4165-ad85-1dd9ff02fb13)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Alpha build - 1.0.0-a.29 (2024-08-24) 

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
This has been fixed for the next release!
