### ISSUE TITLE
Doing Split View Horizontal & Vertical via shortcut makes tabs overlapped

### ISSUE THREAD

**Issue by KiKaraage** [zen-browser/desktop#653]
### What doesn't work?
1. Split View horizontally or vertically by shortcut `Ctrl + Alt + H` or `Ctrl + Alt + V`. When using the shortcut from scratch, the two tabs will overlapped each other and still taking full browsing area.
2. After doing (1), when changing Split View mode from Horizontal to Vertical or from Vertical to Horizontal, the tab would be split, but both tabs will still overlapped each other instead of being distributed to left and right or to top and bottom side.
3. Switching split tab modes via shortcut. (Example: After we do `Ctrl + Alt + H`, we can't use `Ctrl + Alt + V` to switch from Split View Horizontal to Split View Vertical. Changing mode can only be done by clicking the link button in URLbar)

### What does work?
- Split View Grid `Ctrl + Alt + G` works normally
- Unsplit/Close Split View `Ctrl + Alt + U`
- Doing split view horizontally or vertically **from the link button in URLbar** after performing Split View Grid via shortcut `Ctrl + Alt + G`
- Doing split view horizontally or vertically **from the link button in URLbar** after performing Split View Grid via context menu, after selecting multiple tabs. (manually)

[screen-recorder-sun-aug-25-2024-14-47-56.webm](https://github.com/user-attachments/assets/6a4b5432-4158-4d4f-8b40-7e22dd219d5b)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.29

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by bw8686** [comment]
Unable to produce, Could you provide more details on this issue?

**Comment by mauro-balades** [comment]
Fixed with https://github.com/zen-browser/components/commit/4a6a0964de071fb103794f617bf002cd7651854a, thanks!

**Comment by KiKaraage** [comment]
Still not fixed in latest Alpha (a.30)
[screen-recorder-tue-aug-27-2024-10-34-44.webm](https://github.com/user-attachments/assets/b13bfbfc-41cc-4d26-af93-01df58ddb842)
