### ISSUE TITLE
A key + mouse shortcut to quick remove a tab

### ISSUE THREAD

**Issue by MordechaiHadad** [zen-browser/desktop#654]
### What feature would you like to see?

Basically for example in discord when you `Shift` + hover over a message it will expand the usual list of buttons you have so it adds something like the delete message button, instead of clicking Right click and then clicking delete message in the context menu which is what you can currently do when zen's sidebar is collapsed. 

I propose a mouse left click plus holding whatever button for example `shift` which will show a close icon over the tab icon to indicate quick tab deletion when the sidebar is collapsed.

**Comment by h1treX** [comment]
As in every browser you can close tabs by clicking them with MOUSE3 (clicking the mouse wheel).
As e.g. notebook users may not have this available I still agree it should be added to the shortcut settings though

**Comment by MordechaiHadad** [comment]
@h1treX oh you are right, i wasn't aware of this thank you!
