### ISSUE TITLE
Zen browser crash when enter gmail acccount

### ISSUE THREAD

**Issue by Dredragon-Austin** [zen-browser/desktop#659]
### What happened?

Zen browser crash when enter gmail acccount it happend when I use another gmail account or login to another gmail account

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0

### Severity impact

Critical

### What platform are you seeing the problem on?

Windows

**Comment by NOCanoa** [comment]
More info, what page does it happen?,is it in the popout?....

**Comment by Dredragon-Austin** [comment]
> More info, what page does it happen?,is it in the popout?....

it actually when i want to use my manalorddragon@gmail account when i type it it just not responding and the i need to force quit

**Comment by mauro-balades** [comment]
So it doesn't crash, you force quit it?

**Comment by samuelsslv** [comment]
I'm having the same issue; when I start typing my email on the login screen, the screen freezes, and the only way to get out of the frozen screen is to end the browser process, which means I can't log into my email at all.

**Comment by Dredragon-Austin** [comment]
> I'm having the same issue; when I start typing my email on the login screen, the screen freezes, and the only way to get out of the frozen screen is to end the browser process, which means I can't log into my email at all.

yes you could try copy and past it the good solution

**Comment by Moffmo** [comment]
I am having the same issue - i can only type 3 letters in the email address field before it will freeze and I have to force quit.

It's for any site with a google login - youtube, gmail, google docs etc.

**Comment by spicybirsge** [comment]
same issue

**Comment by ric773** [comment]
same issue

**Comment by Dredragon-Austin** [comment]
@mr-cheff  Pls fix this issue

**Comment by nocanoa** [comment]
How does this happen for u all, been using Zen + gmail + yt for ages and never had a crash?

**Comment by Dredragon-Austin** [comment]
> How does this happen for u all, been using Zen + gmail + yt for ages and never had a crash?

Lol it might be more special issue for that may be os or computer issue i guess
