### ISSUE TITLE
Implement Mica Material into the UI on Windows

### ISSUE THREAD

**Issue by Skyyblaze** [zen-browser/desktop#66]
First of all thanks for the great work, Zen shapes up to be a fantastic Firefox fork and it's great to have a browser which puts serious thought into the UI and UX!

On that note I would like to request the implementation of Windows 11's Mica Material into the UI similar to how Edge and Chrome use it. Perhaps even Windows Acrylic or other forms or transparency could make Zen even prettier, also on other OS's like Linux or macOS where Safari also implements a great deal of transparency into its UI.

For reference here's the official link to the Mica guidelines in Windows: https://learn.microsoft.com/en-us/windows/apps/design/style/mica

It was possible to implement Mica and other forms of transparency in Firefox before with the old Windows Vista / Windows 7 Aero Glass Code which sadly has been removed since a few versions ago.

In any case I look forward to Zen's further development!

**Comment by KodusTheOnly** [comment]
+1, the Mica design looks REALLY good and i'd be really nice to see zen browser having this feature.

**Comment by Skyyblaze** [comment]
While I'm not sure how to help on the development side of things I would be more than happy to help with bug-testing whenever needed!

**Comment by mauro-balades** [comment]
with userChome.css setting the background to transparent this can be done with https://github.com/MicaForEveryone/MicaForEveryone but it's not planned anymore as it's insanely hard to do and I dont want to touch that part of firefox's source code in case it breaks anything. Ill reconsider if firefox manages to do something like this

**Comment by Fefedu973** [comment]
):

**Comment by Skyyblaze** [comment]
Any update on this now that Firefox Nightly supports Mica?

**Comment by rihards-simanovics** [comment]
> Any update on this now that Firefox Nightly supports Mica?

Hey @Skyyblaze, are you able to re-open the issue? If Firefox already has it in nightly builds we could use this issue to track the progress.

Sidenote:
btw @mr-cheff I'm from the Arc browser world! Nice to see there is an open source browser that looks just as good as Arc does. Found out today that Arc was getting deprecated in favour for some new AI browser Dia, but I lost the trust in the company after they did this...

I do a lot of web development so I'm hoping I can help in filing bug reports if I see any 😊.

**Comment by Skyyblaze** [comment]
> > Any update on this now that Firefox Nightly supports Mica?
> 
> Hey @Skyyblaze, are you able to re-open the issue? If Firefox already has it in nightly builds we could use this issue to track the progress.
> 
> Sidenote: btw @mr-cheff I'm from the Arc browser world! Nice to see there is an open source browser that looks just as good as Arc does. Found out today that Arc was getting deprecated in favour for some new AI browser Dia, but I lost the trust in the company after they did this...
> 
> I do a lot of web development so I'm hoping I can help in filing bug reports if I see any 😊.

@rihards-simanovics I don't see any way to re-open the issue, do I lack permissions?

**Comment by mr-cheffy** [comment]
Why reopen, mica is already on zen stable

**Comment by rihards-simanovics** [comment]
> Why reopen, mica is already on zen stable

Hi @mr-cheff, sorry, didn't realize that!

How do I enable it on the menu like in Arc. Searched for `mica` in the settings but it doesn't appear anywhere or is it a part of `change theme color`? Hmm, tried changing it, but it's just a simple gradient with texture. Is it part of a specific theme?

I'm running a `1.0.2-b.0 (Firefox 133.0) (64-bit)` in case it helps - says Firefox but I promise it's zen 😅.

**Comment by zaknafein99** [comment]
Hi @rihards-simanovics, there is an option in about:config, search for the value widget.windows.mica and set it to true (I think already is). But I don't see any difference

**Comment by rihards-simanovics** [comment]
> Hi @rihards-simanovics, there is an option in about:config, search for the value widget.windows.mica and set it to true (I think already is). But I don't see any difference

Hey @zaknafein99 thanks! Nice so this is the hidden flags akin to `chromium://flags` in the chromium browsers, nice! That said I'm a dummy, the mica is already enabled and it seems like the effect is so subtle that I didn't even recognize it. Now that I switched to a different wallpaper with higher contrast on Windows it does appear, though very subtly as stated earlier.

**Comment by zaknafein99** [comment]
Do you have a gradient color in zen or the default auto theme?

**Comment by rihards-simanovics** [comment]
> Do you have a gradient color in zen or the default auto theme?

I don't think Theme selection has anything to do with it, but under `Look and Feel` in settings I got `Colorful Dark Theme` selected and in the workspace this:
<details>
  <summary>Workspace 1</summary>
  <img src="https://github.com/user-attachments/assets/d81e26b8-225e-4427-a046-f91560d605a0" alt="workspace 1"/>
</details>

and this

<details>
  <summary>Workspace 2</summary>
  <img src="https://github.com/user-attachments/assets/968357bc-2194-48a8-bf8e-64f08102ab29" alt="workspace 2"/>
</details>

Whether you see Mica or not probably depends on how much contrast you got in the Windows background image like in the top left theme selection in win 11
![image](https://github.com/user-attachments/assets/98ef862a-4f7d-4ef9-a264-01f00fd1109a)

**Comment by marcselman** [comment]
The feature is apparently called Mica, but what's actually implemented is Acrylic.
Now if you have a window underneath Zen Browser you that shining through.
With Mica you should actually always see the Windows Wallpaper instead of the windows below.
Actual Mica would look nicer and is less resource-heavy.

**Comment by rihards-simanovics** [comment]
> The feature is apparently called Mica, but what's actually implemented is Acrylic. Now if you have a window underneath Zen Browser you that shining through. With Mica you should actually always see the Windows Wallpaper instead of the windows below. Actual Mica would look nicer and is less resource-heavy.

It is Mica, at least on Windows 11. I don't know if you are using Windows 10, in which case it might revert to acrylic, which is what's used there by default 🤷🏻.

![Image](https://github.com/user-attachments/assets/28130824-6caa-4bd0-8a7a-32e0123d6512)

You can see that the discord beneath the sidebar has no visual effect on the sidebar. I even tried with custom colour (light yellow) and texture added (low contrast ~20%).

**Comment by marcselman** [comment]
@rihards-simanovics 
That's really strange. For me it's rendering Acrylic.

![Image](https://github.com/user-attachments/assets/8bed9e78-f7fc-40f6-951b-7e4b5959cd97)

I'm running an up-to-date Windows 11. Other apps have normal Mica.
What theme and settings do you have in Zen?

**Comment by rihards-simanovics** [comment]
> [@rihards-simanovics](https://github.com/rihards-simanovics) That's really strange. For me it's rendering Acrylic.
> 
> ![Image](https://github.com/user-attachments/assets/8bed9e78-f7fc-40f6-951b-7e4b5959cd97)
> 
> I'm running an up-to-date Windows 11. Other apps have normal Mica. What theme and settings do you have in Zen?

Is this a new installation with a new profile? I've heard that old profiles can have weird issues like that. Check the about:config for `mica`. Also, make sure you are running the latest Zen browser build.

![Image](https://github.com/user-attachments/assets/53f83e5e-b47b-4ff2-84cd-e6316dae5449)

**Comment by marcselman** [comment]
@rihards-simanovics 
Yeah, I installed Zen just a couple of days ago. I then updated it yesterday to version 1.8.0b and noticed the Mica issue.
Now I have updated it to version 1.8.1b but the issue persists.
I've checked the `mica` and `acrylic` settings, they are on the default values. Changing them didn't help.
I also tried the Light theme which has the same issue.

In WinUI 3 Gallery all materials show up fine.
If there's any diagnostic data I can provide to help with the issue let me know.

**Comment by rihards-simanovics** [comment]
> [@rihards-simanovics](https://github.com/rihards-simanovics) Yeah, I installed Zen just a couple of days ago. I then updated it yesterday to version 1.8.0b and noticed the Mica issue. Now I have updated it to version 1.8.1b but the issue persists. I've checked the `mica` and `acrylic` settings, they are on the default values. Changing them didn't help. I also tried the Light theme which has the same issue.
> 
> In WinUI 3 Gallery all materials show up fine. If there's any diagnostic data I can provide to help with the issue let me know.

I'm not a Zen developer, so I can't fix the issue directly. I can only guide you to places where I have seen similar issues. Try making a new test profile and see if the problem exists there. if worst comes to worst, you can try to completely remove all Zen data and re-install the browser.

**Comment by rihards-simanovics** [comment]
Hey @marcselman. Ok, now that I myself have updated, I also have this issue, looking through the change log, it looks like in `1.8b` under features it has `🔥 Added support for acrylic backgrounds for windows 11 with mica support`,

To disable this go into `about:config` search for `acrylic`, and make sure to set `zen.widget.windows.acrylic` to `false`, then reboot the browser:

![Image](https://github.com/user-attachments/assets/f932010e-41e8-44e7-a520-42c116c4c25c)

**Comment by marcselman** [comment]
Hi @rihards-simanovics. Thanks. But now I have no more effect. Just black :( I'll try some more things.

Update: It looks like it only works with the light theme....

**Comment by rihards-simanovics** [comment]
To be honest I'm not sure what it can be then. I can only suggest that you wait till the next release and see if it fixes it for you. My one seems to work fine even after switching.

**Comment by heksesang** [comment]
The following things had to be true for Mica to work in my case: 
* In Zen
  * ensure that `zen.widget.windows.acrylic` is set to `false` in `about:config`
  * ensure that `widget.windows.mica` is set to `true` `about:config`
  * ensure that you have enabled _System theme — auto_ as theme.
* In Windows, ensure that _Settings_ → _Personalization_ → _Colors_ → _Show accent color on title bars and windows borders_ is disabled

When all these things are true, it works for both light and dark themes, but you **must** control the theme in Windows, through the _Settings_ → _Personalization_ → _Colors_ → _Choose your mode_ option.

**Comment by marcselman** [comment]
@heksesang 
Thanks. I finally got it working. Although I'm not sure what the issue was since I didn't really change anything from before.
