### ISSUE TITLE
CMD + L to change url

### ISSUE THREAD

**Issue by Act0r1** [zen-browser/desktop#668]
### What feature would you like to see?

it would be really cool, if i can change url by just shortcut, and in my opinion it is de-facto standard to do this in many other browsers

**Comment by ricardofrancoli** [comment]
This shortcut is working for me. Perhaps you have another setting interfering with this?

**Comment by elianiva** [comment]
can confirm it also works fine for me

**Comment by sannidhyaroy** [comment]
It's working for me as well...

**Comment by rrojan** [comment]
@Act0r1  Can you check whether you've mapped cmd+L to another shortcut by mistake in Settings -> Keyboard Shortcuts. 

I clicked on a shortcut input on the Keyboard Shortcuts tab, and pressed ctrl+w trying to close settings This accidently remapped Ctrl+W to something else so I couldn't close tabs with that shortcut for a while.

**Comment by sannidhyaroy** [comment]
> I clicked on a shortcut input on the Keyboard Shortcuts tab, and pressed ctrl+w trying to close settings This accidently remapped Ctrl+W to something else so I couldn't close tabs with that shortcut for a while.

This happened to me as well. I mapped Private Tabs to `Control + Shift + N`, then pressed `Control + W` to close the settings tab. It didn't close the tab, rather mapped that keyboard shortcut. I think this should a separate issue on its own that after one keyboard shortcut is entered, it should lose focus on the input bar and not take in another shortcut.

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/771

 ~ This is an automatic operation to better enhancements requests organization.
