### ISSUE TITLE
Fix padding in full screen

### ISSUE THREAD

**Issue by NandiyaLive** [zen-browser/desktop#67]
![image](https://github.com/user-attachments/assets/bb1e31d5-221c-423e-92d6-29f826dfe3fa)

**Comment by mauro-balades** [comment]
Hey! Thanks for reporting this. Unfortunately, I can't really work on the project for 4 days since im not at home. I just wanted to let you know that ill fix this as soon as possible

**Comment by NandiyaLive** [comment]
Sure, no problem. Take your time

**Comment by mauro-balades** [comment]
Hey, sorry for the wait! It's not fixed in https://github.com/zen-browser/desktop/commit/43460815ac946b5b365a4bfcc25f09cbe0b6e75e and will be reflected in the next release!
