### ISSUE TITLE
Toggle Picture-In-Picture Automatically

### ISSUE THREAD

**Issue by enesbala5** [zen-browser/desktop#671]
### What feature would you like to see?

A very useful Arc Feature is the automatic PIP, which is toggled after switching to another tab. Zen could greatly benefit by having the feature be available too.

I don't believe this would be difficult to implement and when paired with a toggle to turn it on/off - would be appreciated by most users.

Extra: Would be great if we can change the Keybinding for the Picture in Picture, I'd love to be able to remap it.

**Comment by n7itro** [comment]
This feature already exists in Firefox Beta, so we will wait until it becomes available in stable Firefox.
