### ISSUE TITLE
Zen Browser Image is damaged and can't be opened [MacBook Air M2]

### ISSUE THREAD

**Issue by fransancisco** [zen-browser/desktop#672]
### What happened?

Zen Browser Image is damaged and can't be opened [MacBook Air M2]

Exactly after install, when I try to open it for the first time. 

No other specific error messages.

![image](https://github.com/user-attachments/assets/dbdc064d-7288-4e7c-8e09-14657dab72ca)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

first one

### Severity impact

Critical

### What platform are you seeing the problem on?

macOS - aarch64

### Relevant log output

```shell
I have no log output.
```

**Comment by qtchaos** [comment]
https://docs.zen-browser.app/guides/install-macos#step-3-bypass-gatekeeper
