### ISSUE TITLE
Netflix streaming fails on Zen browser with automatically getting logged out

### ISSUE THREAD

**Issue by abhhipatel** [zen-browser/desktop#673]
### What happened?

When attempting to stream Netflix on the Zen browser, the video fails to load and i get logged out instantly. This issue occurs consistently.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.29 (2024-08-24)

### Severity impact

High

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by NOCanoa** [comment]
DRM , we don't have a license : /

**Comment by ch4og** [comment]
https://docs.zen-browser.app/faq#why-cant-zen-browser-play-drm-protected-content
