### ISSUE TITLE
streamimg video in f1TV 

### ISSUE THREAD

**Issue by divvyanshu25** [zen-browser/desktop#674]
### What happened?

![Screenshot 2024-08-25 at 8 06 28 PM](https://github.com/user-attachments/assets/4ff9612e-de1f-4eea-8f3e-489bbc76cb11)

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.29

### Severity impact

Critical

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by Zykkl** [comment]
Not a critical severity bug, medium, possibly high

**Comment by NOCanoa** [comment]
DRM, we don't have a license :/ 
Just use f1 multi viewer 🤫
