### ISSUE TITLE
Option to unsplit views from tab menu

### ISSUE THREAD

**Issue by hsprakash** [zen-browser/desktop#676]
### What feature would you like to see?

Right now to put tabs into split view we pick to the tabs from the tab menu and select "Split {x} tabs"

We should be able to unsplit the views from the tab menu itself without having to close one of the tabs.

**Comment by Moshyfawn** [comment]
I think this could go under #354

**Comment by NOCanoa** [comment]
when in split mode, there is a button in the url bar that allows to make it singular again.

**Comment by chriskirknielsen** [comment]
@NOCanoa Butting in to say I did not know this, thanks! To be fair, a "link" icon in an address bar does not scream "split view controls", it should be a grid icon of sorts, perhaps?

But to @hsprakash's point, this is not very clear in the UI and the ability to undo the split from the same place you created the split view should be possible, so I'd recommend this ticket remained open.

**Comment by nsina** [comment]
The “Split View” (also known as the “un-split” button) is not intuitive and lacks user experience design. The right-click context menu should be responsible for handling the “unsplit” action, as this is likely where users split their tabs (e.g., multi-selecting tabs > right-click > “Split _n_ tabs”).
Additionally, the color of the Split View button in the URL bar is faint. I have tried with various theme colors, and all of them are very faint and easily missed. Why not make the same color as the other icons?

**Comment by JacobBumgarner** [comment]
Honesty I still do not know how to unsplit tabs when in compact mode... I know we can set a shortcut, but there should be a more intuitive way to see how to do this.

**Comment by nyankittone** [comment]
@nocanoa For the life of me, I genuinely cannot find where the "unsplit" button is in the URL bar. Did its location change in some update since this issue was made?

**Comment by nyankittone** [comment]
Btw, for anyone here on Linux on a regular PC keyboard that wants to unsplit, press Alt+Ctrl+U while focused on the split tabs. This might work on macOS when using a regular PC keyboard, but I'm unsure since I don't use a Mac.

**Comment by JacobBumgarner** [comment]
@nyankittone I figured it out - on the top of each split tab, there is a *tiny* little control box that lets you drag the tab or unsplit it. On mobile rn so I can’t provide a screenshot.

**Comment by theCalcaholic** [comment]
@JacobBumgarner With that control box I can rearrange the split view, but I can't seem to unsplit the tabs.

I also didn't find any button in the URL bar that would allow me to unsplit them.

Alt+Ctrl+U, however, works (thanks @nyankittone, this was driving me mad :D).
