### ISSUE TITLE
Take screenshot tool visual bug

### ISSUE THREAD

**Issue by Iziram** [zen-browser/desktop#678]
### What happened?

When using the Screeshot tool ( context menu -> take screenshot) the optionnal buttons (Whole page or only visbible) are not rendering properly.

## Zen 1.0.0-a.29 : 
<img width="1624" alt="pb_zen_capture" src="https://github.com/user-attachments/assets/8ef9d3d5-014f-487e-b6fb-e576f6863604">

## Firefox 129.0.2 : 
<img width="1624" alt="pb_zen_firefox" src="https://github.com/user-attachments/assets/4e5d24a7-0708-4ecc-8c73-adbfa6a86e81">

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.29

### Severity impact

Low

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by qeewpi** [comment]
### What happened?

I have encountered a similar issue with the screenshot tool. When compact mode is enabled, the screenshot button view is displayed past the edge of the screen. However, when compact mode is disabled, the screenshot button view displays correctly. 

### Screenshot Tool in Compact Mode:

![image](https://github.com/user-attachments/assets/a4ffeb93-e32f-4eea-a68b-b7e24bb35c60)

### Screenshot Tool with Compact Mode Disabled:

![image](https://github.com/user-attachments/assets/bf178c56-34d2-41f4-b955-b63c1f249169)

### Steps to reproduce
1. Enable compact mode.
2. Observe that the screenshot button view is displayed past the edge of the screen.
3. Disable compact mode.
4. Observe that the screenshot button view displays correctly.

### Version
1.0.1-a.17

### What platform are you seeing the problem on?
Fedora Workstation 41

**Comment by Nerph** [comment]
I have this issue even when not using compact mode. I'm on macOS and version 1.0.1-a.19, however I'm had this issue for a long time now (so many versions).

**Comment by neurokitti** [comment]
I was unable to recreate this bug on the most recent version. if this is still an issue please reopen the issue.
