### ISSUE TITLE
Ability to resize split views just by dragging. 

### ISSUE THREAD

**Issue by hsprakash** [zen-browser/desktop#679]
### What feature would you like to see?

I generally split view 2 tabs and I would like to resize them just by dragging.

**Comment by guigirl42** [comment]
Unfortunately the OP seems to have later edited their Issue & afaict removed most of their content, but fwiw, this is what the Dev had replied: 

https://github.com/zen-browser/desktop/issues/56#issuecomment-2226958423

>it's certainly on my plans to add support for it, ill do it once I finish workspaces (what im doing right now).
>
>Because I need to do a bit of research since it's displayed in a grid mode and it may depend if it's horizontal/vertical, etc. I just need to think about it a bit more

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/768

 ~ This is an automatic operation to better enhancements requests organization.
