### ISSUE TITLE
Auto expanding tabs moving out of the way like some sortof annoying ad that you cant click away

### ISSUE THREAD

**Issue by KUKARAF** [zen-browser/desktop#680]
### What happened?

Auto Expanding tabs makes clicking on the bottom icons pretty annoying since you'd be forced to make 2 movements with the mouse. Please see the video for more info: 
[Screencast from 2024-08-25 17-52-46.webm](https://github.com/user-attachments/assets/f13e661f-25b7-477d-bdd3-2f4290c1abde)

I am unsure what a good fix for this would be nor if this should be fixed in the first place. I am not a frontend dev. 

Some ideas i've had so far: 

- grouping the bottom icons into a jumbled  mess that expands on hover 
    - perhaps something along the lines of pie launcher? ![image](https://github.com/user-attachments/assets/b0c70d17-445c-4523-98ca-a9def6deb9f5)
- going full iphone and cutting out a horizontal notch at the bottom of the window where the bottom icons live  
- leaving the bottom icons vertical irrelevant of tab expansion 

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.29 (64-bit)

### Severity impact

Low

### What platform are you seeing the problem on?

Linux

**Comment by KarimElsayad247** [comment]
I agree with the jumbled mess that expands on hover solution.

I also suggest having workspace buttons being in a jumbled mess separate from the jumbled mess of other icons

what matters thought is that stuff doesn't jump around
