### ISSUE TITLE
Private tab/container

### ISSUE THREAD

**Issue by Trzynastek** [zen-browser/desktop#681]
### What feature would you like to see?

It would be nice to have an option to create a new tab in a private container, like for example in the Floorp browser. 
Maybe even go a step further and give users ability to make history separate in each container or give them ability to change when the history should be cleared.

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/767

 ~ This is an automatic operation to better enhancements requests organization.
