### ISSUE TITLE
Cursors don't change at all like they are supposed to

### ISSUE THREAD

**Issue by rrojan** [zen-browser/desktop#682]
### What happened?

When i hover over the top edge of the devtools area, the cursor doesn't change into a resize cursor. So I can't really know if and when i'm at the right spot to be resizing my devtools.

Same for text area. When I drag the bottom-right handle, it should show a resize cursor instead.

When hovering at buttons or links the cursor is still the default one. I can't trust Zen for any frontend work just yet.

It seems the only two cursors supported right now are `text` and the normal one. The normal one doesn't respect my default cursor style on Ubuntu as well.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.28

### Severity impact

Enhancement

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/766

 ~ This is an automatic operation to better enhancements requests organization.
