### ISSUE TITLE
console.log does't print on terminal when put directly

### ISSUE THREAD

**Issue by lucaspereirasouzat** [zen-browser/desktop#683]
### What happened?

![image](https://github.com/user-attachments/assets/0d38ebd5-5c1c-442f-b03a-d0adaead823a)

Should print console.log 

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a-28

### Severity impact

Medium, High

### What platform are you seeing the problem on?

Linux

**Comment by rrojan** [comment]
`alert`, `confirm`, etc have no effect either.

**Comment by FlashAmarillo** [comment]
I tried and I'm like 😮 🤣

**Comment by Iziram** [comment]
related to #593

**Comment by mauro-balades** [comment]
Duplicate of https://github.com/zen-browser/desktop/issues/593
