### ISSUE TITLE
Add option to search and navigate through open tabs like Brave

### ISSUE THREAD

**Issue by rrojan** [zen-browser/desktop#686]
### What feature would you like to see?

On Brave, I can quickly press Ctrl+Shift+A to open this view to search and navigate to another tab. I heavily use this for easy keyboard navigation between tabs. 

![image](https://github.com/user-attachments/assets/7c7d7bb8-cd0b-486c-87e1-6291e94eb497)

It would be awesome to see something like this implemented for Zen as well

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/765

 ~ This is an automatic operation to better enhancements requests organization.
