### ISSUE TITLE
Bookmark tagging

### ISSUE THREAD

**Issue by balazser** [zen-browser/desktop#687]
### What feature would you like to see?

I would like to use the same bookmark tagging mechanism as in Firefox. My usual workflow for saving bookmarks involves pressing Ctrl+D, then pressing Tab twice to add tags. Unfortunately, I haven't been able to figure out how to enable this feature.

**Comment by abhhipatel** [comment]
This feature could streamline the process of organizing bookmarks, especially for users who rely heavily on tagging.

It would be great to explore the feasibility of implementing this feature, perhaps by adding an option in the settings that allows users to enable this shortcut for adding tags quickly.

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/764

 ~ This is an automatic operation to better enhancements requests organization.
