### ISSUE TITLE
Move tab to another window?

### ISSUE THREAD

**Issue by jimfr** [zen-browser/desktop#689]
### What feature would you like to see?

Like FireFox, I'd like the ability to move a tab to another window via the context menu.  If there's more than one window open, I'd like to be able to choose which window to which to send the tab, like FireFox does.

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/762

 ~ This is an automatic operation to better enhancements requests organization.
