### ISSUE TITLE
Some ting that identifies what container it is.

### ISSUE THREAD

**Issue by NOCanoa** [zen-browser/desktop#69]
when i chose a container (personal,back...) they have a color each, so wold it be possible making any indication that sows what container a tab is using, because now just looking at the side bar i have no idea if its in personal or bank..

**Comment by mauro-balades** [comment]
True, this should be an ez fix aswell

**Comment by mauro-balades** [comment]
![Screenshot_20240719_171935](https://github.com/user-attachments/assets/740f2e01-caae-483a-b6aa-01687aead30f)

I've implemented this, hope it's enough!
