### ISSUE TITLE
app wont run on m3 mac

### ISSUE THREAD

**Issue by bradparks** [zen-browser/desktop#693]
### What happened?

downloaded it
gives an error when running, Im on an m3 mac, and it chose non intel but fails to work

“Zen Browser” is damaged and can’t be opened. You should move it to the Trash.

downloaded today, Aug 25

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

no idea

### Severity impact

Critical

### What platform are you seeing the problem on?

macOS - aarch64

### Relevant log output

```shell
above
```

**Comment by bw8686** [comment]
Please read https://docs.zen-browser.app/guides/install-macos that should resolve your issue.

**Comment by bw8686** [comment]
Actually you could also refer to https://github.com/zen-browser/desktop/issues/53

**Comment by mauro-balades** [comment]
^^^
