### ISSUE TITLE
Unable to log into twitter

### ISSUE THREAD

**Issue by SlashScreen** [zen-browser/desktop#695]
### What happened?

For some reason, the form on x.com/login will not load properly, I have checked that it loads properly on chromium and firefox, and they work fine.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0.29 alpha

### Severity impact

Medium

### What platform are you seeing the problem on?

Windows

**Comment by Moshyfawn** [comment]
Duplicate of #630

**Comment by SlashScreen** [comment]
Ah, Okay. I searched but I didn't see this one.
