### ISSUE TITLE
"Zen browser is damaged and can't be opened" MacBook Air M1

### ISSUE THREAD

**Issue by idk2me** [zen-browser/desktop#696]
### What happened?

# My specs
- Apple silicon M1
- 8 core CPU and GPU
- 256Gb
- 16Gb RAM

Whenever you download for desktop from [main download page](https://www.zen-browser.app) you get an error that the application is damaged. 
![Screenshot 2024-08-25 at 23 07 56](https://github.com/user-attachments/assets/eee51322-f589-4995-bd3a-70628962402d)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.29

### Severity impact

Medium

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by qtchaos** [comment]
https://docs.zen-browser.app/guides/install-macos#step-3-bypass-gatekeeper
