### ISSUE TITLE
Support for gtk themes 

### ISSUE THREAD

**Issue by rznkolds** [zen-browser/desktop#697]
### What feature would you like to see?

It may be nice to bring Gtk support for Gnome and similar desktop systems, so that your project will be more compatible as a theme on linux devices.

![Screenshot from 2024-08-25 23-41-39](https://github.com/user-attachments/assets/d37b3e9e-a4be-4ef0-81dc-9d533a323628)

**Comment by SomeDudeBrosky** [comment]
As a Gnome user myself, this would be nice, however at the same time this seems to be very low priority and could possibly open a floodgate of requests for other themes for other DEs

**Comment by rznkolds** [comment]
> As a Gnome user myself, this would be nice, however at the same time this seems to be very low priority and could possibly open a floodgate of requests for other themes for other DEs

Thanks for your reply, but I already said it in general, in case this situation can be corrected.

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/760

 ~ This is an automatic operation to better enhancements requests organization.
