### ISSUE TITLE
Transition animations

### ISSUE THREAD

**Issue by Matse2005** [zen-browser/desktop#699]
### What feature would you like to see?

When toggling the tabstoolbar there isn't any transition or not visible transition, same with opening the bookmark and the sidebar. I've tried to add it with a custom theme but I can't get it to work. Maybe someone else has a fix.

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/759

 ~ This is an automatic operation to better enhancements requests organization.
