### ISSUE TITLE
Rong color on selction in a website

### ISSUE THREAD

**Issue by NOCanoa** [zen-browser/desktop#70]
![image](https://github.com/user-attachments/assets/b81572d5-f198-4420-bbeb-b85a9a7ebb7d)
self explanatory

**Comment by mauro-balades** [comment]
thanks! It was a stupid mistake :(

it has been fixed in (https://github.com/zen-browser/desktop/commit/69e352624eb77d6b9058dad145f1f5a3054a41dc), it will be visible on the next release!
