### ISSUE TITLE
Sidebar animation

### ISSUE THREAD

**Issue by markox92** [zen-browser/desktop#700]
### What feature would you like to see?

I want to see sidebar animation when opening and closing, but there must be a delay of example 500ms. So when quickly moving the mouse over the sidebar, I don't want to see the fast open and close.

https://github.com/user-attachments/assets/9d3b3d02-b75c-459d-89cc-3218b8c8a18f

**Comment by adityayaduvanshi** [comment]
Please assign this issue to me

**Comment by bw8686** [comment]
From what ive been personally told it's not possible but as far as I'm concerned it probably is if you put enough effort into it. I'm going to attempt this some time soon and see if i can make something work.

**Comment by markox92** [comment]
> From what ive been personally told it's not possible but as far as I'm concerned it probably is if you put enough effort into it. I'm going to attempt this some time soon and see if i can make something work.

Absolutely is possible, here is a demo, do not look for missing elements inside bar, as you can see there is an animation with a 1s delay

https://github.com/user-attachments/assets/9b7620d2-d637-4d3b-aa72-ce46cc34ab26

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/758

 ~ This is an automatic operation to better enhancements requests organization.
