### ISSUE TITLE
Ability to select multiple workspaces at the same time

### ISSUE THREAD

**Issue by LeMoonStar** [zen-browser/desktop#701]
### What feature would you like to see?

Sometimes users may have to switch between tabs from different workspaces frequently.
Instead of having to repeatedly switch workspaces or breaking ones finely crafted grouping, it would be a great feature to be able to select multiple workspaces at once. Having both workspaces list their tabs in the tab/sidebar, but still being separated for example by a line and a small label showing the name of the workspace.

This could nicely integrate with #499, making the selected workspaces differentiable by colour as well.

A VERY simplistic example quickly made in GIMP:
![ZenMultiWorkspaceExample](https://github.com/user-attachments/assets/2d5c1bd2-6b05-4c28-819f-7561736251c4)

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/757

 ~ This is an automatic operation to better enhancements requests organization.
