### ISSUE TITLE
force dark mode for web contents & translation in right click menu

### ISSUE THREAD

**Issue by testermania** [zen-browser/desktop#702]
### What feature would you like to see?

Would you consider adding these?

force dark mode for web contents. hsl based inversion it works well.

![pic](https://github.com/user-attachments/assets/1515f0c3-7da8-46d4-9707-f10e0537072e)

& translation in right click menu

& add option to turn off translation suggestions for all sites

& close tab icon (maybe right side of the refresh or hover icon when mouse is over it)

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/756

 ~ This is an automatic operation to better enhancements requests organization.
