### ISSUE TITLE
Cant Vertical / Horizontal Split

### ISSUE THREAD

**Issue by NotBestLord** [zen-browser/desktop#705]
### What happened?

When i use the shortcuts to split horizontally or vertically the split tabs remain full size, this does not occur when grid-splitting.

Using the split view mode button in the top right to change it to another split type (non-grid) makes both tabs resize together into the same space of the screen, leaving the left / bottom half of the screen empty.

Grid-splitting and then switching to horizontal / vertical split works normal, this will also work if - from the original broken split - i change mode to grid and then back to horizontal/vertical.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0

### Severity impact

Medium

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
This is fixed for the next release
