### ISSUE TITLE
Ability to remove icons from the lower left sidebar

### ISSUE THREAD

**Issue by rewgs** [zen-browser/desktop#706]
### What feature would you like to see?

Would love to be able to hide buttons such as expand, web sidebar, bookmarks, history, and settings, without simply hiding the sidebar entirely i.e. entering "compact mode." 

For example, I don't use bookmarks in any browser (I use Obsidian for a much more robust "bookmarking" experience)s, so it's just wasted space/visual noise for me.

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/754

 ~ This is an automatic operation to better enhancements requests organization.
