### ISSUE TITLE
3 things, after using Zen Browser for my main browser

### ISSUE THREAD

**Issue by notollyo** [zen-browser/desktop#71]
I love the concept and design of new Firefox user interface enhancement. But there are something i really wish you could change or add it in another release...

1. The zoom in animation when open Zen Browser just cringe me cause it's just like Chromium browser out there (this issues on macOS). Sometime screen splash is good when I open it for the first time but, when i closed all tabs and "command + n", it's show the splash again, keep me waiting it for many seconds.

2. I wish Zen has some auto pip when i leave tab to another tab. I found it super handy when used Arc as my main browser but switch to Zen.

3. Compact sidebar isn't that bad. But if there some toggle to expand the tab, it should be better cause i scared of everything that compact and can't show the title of those tabs i open.

Love your browser so much, i will have another suggestion for you.
![firefox](https://github.com/user-attachments/assets/a343636a-47e9-49dc-af47-081315f16f8c)
here is my icon i made for macOS icon, you can use it, cause i hate the blurry icon by default.

My English is bad so I'm sorry for this, have a nice day!

**Comment by mauro-balades** [comment]
Hello! 

1. From the next release, you can disable the watermark by setting `zen.watermark.enabled` to 
 `false` in `about:config`.
2. Sorry, but im not planning in doing the `auto pip` feature, I think there are other issues that require more of my time, but it's definitively a possibility for the future.
3. You can now enable expanded sidebar for the next release (https://github.com/zen-browser/desktop/issues/72)
