### ISSUE TITLE
Allow tab unloading

### ISSUE THREAD

**Issue by alicerunsonfedora** [zen-browser/desktop#710]
### What feature would you like to see?

Similar to #709, I'd love to be able to see a feature for unloading a tab without closing it permanently. While Firefox has a built in mechanism for automatically unloading tabs, I sometimes prefer to unload them manually.

### Other details

Ideally, I think an addition to the tab context menu to unload the tab would work well, but perhaps there could be other settings for tab unloading.

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/751

 ~ This is an automatic operation to better enhancements requests organization.
