### ISSUE TITLE
feat: RFP Support

### ISSUE THREAD

**Issue by yoghurtlee-thu** [zen-browser/desktop#713]
### What feature would you like to see?

As the title suggests, the implementation of Resist Fingerprinting (RFP) is a robust mechanism for safeguarding user privacy. In my view, integrating this feature into Zen Browser would significantly bolster its privacy protection capabilities.

Should Zen Browser already incorporate this feature, I would be genuinely delighted to learn of it :)

Best regards.

**Comment by n7itro** [comment]
Is there something missing from Firefox's `privacy.resistFingerprinting`?

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/749

 ~ This is an automatic operation to better enhancements requests organization.
