### ISSUE TITLE
No clear way to split tabs graphically or with keybindings.

### ISSUE THREAD

**Issue by SomeDudeBrosky** [zen-browser/desktop#714]
### What feature would you like to see?

Currently, there is no clear graphical way to split specific tabs. Even if you use keybindings, there is no documentation or indicator as to what they are within the browser (I had to go to Reddit in order to figure them out, and it is still unclear as to how to rearrange split tabs.) a few ways to fix this would be in the right-click menu when clicking a tab to have a "select tab" option that has the keybindings written in gray on the right (how this is usually handled in the vast majority of browsers), a tutorial at instillation informing what the shortcuts are, and a graphical overview when hovering over a tab, along with once 2 or more tabs are in a workspace for an icon to appear in the header to change the layout. Any one of these options, or even just a "shortcuts"  tab on the help section of the website would be an improvement to the current situation.

### Other details

This is the main marketed function of this browser, yet it is what gives average and even knowledgeable users the most issue.

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/748

 ~ This is an automatic operation to better enhancements requests organization.
