### ISSUE TITLE
Bookmarks are clunky.

### ISSUE THREAD

**Issue by SomeDudeBrosky** [zen-browser/desktop#716]
### What feature would you like to see?

It would be nice if when you clicked the bookmarks star button if it opened the list of your bookmarks' toolbar that would traditionally be at the top of most browsers instead of just showing folders when you open it, as the current implementation is unusual and feels out of place with the rest of the browser.

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/747

 ~ This is an automatic operation to better enhancements requests organization.
