### ISSUE TITLE
Add an easily accessible option using a checkbox to toggle the bookmarks toolbar within either 'look and feel' or 'general'

### ISSUE THREAD

**Issue by SomeDudeBrosky** [zen-browser/desktop#717]
### What feature would you like to see?

Simple issue. It is not enabled by default, and currently the only way to enable it is through a keybinding that by default is not set to anything.

**Comment by SomeDudeBrosky** [comment]
Another option would to have it toggleable through a right click menu when interacting with blank space on the top bar.

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/745
