### ISSUE TITLE
Windows found zen like a virus

### ISSUE THREAD

**Issue by peemiranda** [zen-browser/desktop#718]
### What happened?

Windows reporting trojan when installed zen

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0

### Severity impact

Critical

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
Windows reporting trojan when installed zen
```

**Comment by AceiusIO** [comment]
I assume this is because Zen's binaries aren't signed yet, not because of a critical security vulnerability

**Comment by geekyBoogiepop** [comment]
Here's additional info from Windows Defender:
![image](https://github.com/user-attachments/assets/4b26d176-bf15-4f12-9be3-bbad74403cdf)

**Comment by tbukfrc** [comment]
Yeah, I've been using Zen for about a month and this just started happening. The zen.exe file is completely gone from my computer and trying to launch from the shortcut results in a potential virus error.

Something happened in the latest update, I'm not sure what happened.

**Comment by tbukfrc** [comment]
Adding on to this, the zen.exe file is missing because Windows Defender saved me and deleted it. I don't know how much I trust this browser anymore if they're sneaking trojans into browser updates. There's no reason Wacatac should be getting flagged if it isn't actually there in the binary.

**Comment by sneexy-boi** [comment]
this is most likely a false positive, windows security is pretty sensitive and detects a good chunk of things as malicious, including some really basic stuff. agreeing with AceiusIO, most likely due to the binaries not being signed

**Comment by MG-LSJ** [comment]
Defender just removed the exe while I was using Zen. The app crashed then the zen exe was deleted. Now can't install it as defender does this again.

**Comment by extropyst** [comment]
It seems to me that it is a false positive that Windows Defender raises due to the lack of a digital signature. The problem occurs only in the installer of the "optimized" version of the latest version released, therefore the alternatives to solve it are: Use the "generic" installer, or the "optimized" one of the previous version and update from there.

**Comment by Creaous** [comment]
As someone who has worked on programming Windows apps before, I've had mine get detected as viruses for the most basic things like creating and opening files. This has a 99% chance of being a false positive due to the lack of digital signature.

**Comment by extropyst** [comment]
That's right, here is more context about it:

https://superuser.com/questions/1829864/trojanwin32-wacatac-bml-found-in-c-extend-deleted

https://cdromance.org/guides/virus-detected-trojanscript-wacatac-bml/

https://www.reddit.com/r/antivirus/comments/14bhb6u/trojanwin32wacatacbml_trojanscriptwacatacbml/?tl=es

https://www.b4x.com/android/forum/threads/b4a-false-windows-defender-alerts-trojan-script-wacatac-b-ml-in-c-users-username-appdata-local-temp-tmp7460-tmp.159302/

**Comment by mayemu** [comment]
Windows just deleted zen off my computer when trying to update as it recognized it as a trojan 
![ApplicationFrameHost_NF4cj3EROY](https://github.com/user-attachments/assets/de92a457-fff0-4d11-a591-8b92b88cf5ad)
![ApplicationFrameHost_u9Em16Q54w](https://github.com/user-attachments/assets/dd985e74-1e5f-48fd-9396-0e2d6557822d)

**Comment by extropyst** [comment]
Try the generic version:

https://github.com/zen-browser/desktop/releases/download/1.0.0-a.28/zen.installer.exe

**Comment by extropyst** [comment]
This should be the measure to take as users:

https://learn.microsoft.com/en-us/defender-xdr/m365d-autoir-report-false-positives-negatives

**Comment by Cassers** [comment]
Virus Total also detects the application as a virus, which doesn't really give much confidence.

Zip:
![image](https://github.com/user-attachments/assets/2729add3-a9e2-4752-a334-a340fa30f845)

Installer:
![image](https://github.com/user-attachments/assets/753766c0-0827-481c-a261-93a225b3c3f9)

**Comment by shaeriz** [comment]
I had the exact same problem and even Virustotal is flagging the zen.exe file, I'm pretty concerned about it now, despite I was having a great time with Zen.
![image](https://github.com/user-attachments/assets/40e76f6a-8b08-4763-85b9-faef90120120)

**Comment by extropyst** [comment]
Check this information:
https://virustotal.readme.io/docs/false-positive

and try also analyzing the file in other places like:

 https://internxt.com/virus-scanner

https://opentip.kaspersky.com/

![image](https://github.com/user-attachments/assets/19eca077-1672-4ad5-b0ab-bb1fc56b9e30)

**Comment by m-born** [comment]
Comodo Internet Security also has it as a Trojan:

![Screenshot 2024-08-26 094042](https://github.com/user-attachments/assets/91d5a80c-156b-4835-8c87-19ab801709d8)

**Comment by m-born** [comment]
zen-browser.app is done (due to lack of payment?)

![Screenshot 2024-08-26 101335](https://github.com/user-attachments/assets/ee32afe3-a3e3-42ca-abc0-1170af361dea)

**Comment by geekyBoogiepop** [comment]
It's working fine here:
![image](https://github.com/user-attachments/assets/b1de7df2-43e1-4a6c-aa0b-0d24dd53f093)

**Comment by mauro-balades** [comment]
> this is most likely a false positive, windows security is pretty sensitive and detects a good chunk of things as malicious, including some really basic stuff. agreeing with AceiusIO, most likely due to the binaries not being signed

**Comment by tbukfrc** [comment]
I would like to add that using a previous installer and updating doesn't help. The act of updating is what caused this for me. It seems to be only the latest update, but there's no way to downgrade and stay downgraded (it annoyingly forces you to update when you start the browser).

For now, I'm still using Firefox until this is resolved. As a principle, I never add a bypass to Windows Defender. It's just too risky to do that. Once Windows Defender stops quarantining it and the browser seems generally safe, I'll download it again. I just can't trust it right now, even if it is probably just a false positive.

**Comment by alvanrahimli** [comment]
> most likely due to the binaries not being signed

Why do zen doesn't have it? Is it a financial issue, or there are other constraints as well?

**Comment by mauro-balades** [comment]
I dont know where im supposed to get the signature from, if someone could guide me in the right direction would be great

**Comment by amenbr1** [comment]
@mauro-balades some places to look:
**Certum** has dedicated options for open source projects. They offer both cloud and self hosting:
(This is the international version of the website. Some of the translations may be a little off.)
https://shop.certum.eu/code-signing.html
Original Polish site is https://www.certum.pl/pl/

**Microsoft** has recently launched their Trusted Signing service through Azure (though I believe it is still in preview):
https://learn.microsoft.com/en-us/azure/trusted-signing/quickstart
https://azure.microsoft.com/en-us/pricing/details/trusted-signing/

**Comment by j-stach** [comment]
Make sure you are downloading it from www.zen-browser.app, not www.zen-browser.com, they are different projects. 
Some search engines prioritize the latter when you search for "zen browser"

**Comment by geekyBoogiepop** [comment]
> I dont know where im supposed to get the signature from, if someone could guide me in the right direction would be great

Take a look here:
[https://signpath.org/](https://signpath.org/)

**Comment by ralcaidev** [comment]
> For now, I'm still using Firefox until this is resolved. As a principle, I never add a bypass to Windows Defender. It's just too risky to do that. Once Windows Defender stops quarantining it and the browser seems generally safe, I'll download it again. I just can't trust it right now, even if it is probably just a false positive.

Same here. This plus the CDNs doesn't give me any confidence.

**Comment by jgcabotd** [comment]
Hello guys, just now I tried the browser and when I start it in a few seconds Kaspersky kill the process and detects a trojan in zen.exe.

Here I leave a screenshot that can see what happened.

![image](https://github.com/user-attachments/assets/58bc3925-9bc7-415a-ac07-8118fa354119)

**Comment by mauro-balades** [comment]
Please, let's continue here https://github.com/zen-browser/desktop/issues/37, im losing track of the issues about this topic now
