### ISSUE TITLE
[Feature Request] Collapsible Sidebar for Tab Management

### ISSUE THREAD

**Issue by Evren-os** [zen-browser/desktop#72]
## Description

As a user who appreciates the minimal and modern look of the current tab bar in Zen-Desktop, I'd like to propose a feature that maintains this aesthetic while providing additional functionality for users who prefer more traditional tab management.

## Proposed Feature

Implement a collapsible sidebar for tab management with the following characteristics:

1. A toggle button to show/hide the sidebar
2. When expanded, the sidebar displays:
   * A list of all open tabs
   * Tab names
   * Close buttons for each tab

## User Experience

1. Default View:
   * Users see the current minimal tab bar
   * A small, unobtrusive button is visible to toggle the sidebar

2. Expanded View:
   * Clicking the toggle button reveals the sidebar
   * The sidebar displays all open tabs with their names and close buttons
   * Users can interact with tabs in the sidebar (e.g., close, switch)

3. Collapsed View:
   * Clicking the toggle button again hides the sidebar
   * The interface returns to the minimal tab bar view

## Benefits

1. Maintains the zen-like, minimal default interface
2. Provides easy access to full tab information when needed
3. Accommodates users who prefer traditional tab management
4. Enhances usability without compromising the modern design

## Visual Reference

I've attached two images to illustrate the concept:

![240717_20h06m35s_screenshot](https://github.com/user-attachments/assets/d2755a5f-4929-4cf8-9536-827bf9024a45)
![240717_20h06m46s_screenshot](https://github.com/user-attachments/assets/56573772-e7c8-429c-8b32-047a422c1d03)

## Additional Considerations

* The sidebar could be customizable (e.g., position, width)
* Keyboard shortcuts could be implemented for quick sidebar toggling
* The feature could be optional and easily disabled in settings

## Potential Impact

This feature would bridge the gap between minimalist design and traditional functionality, potentially increasing user satisfaction and adoption rates.

**Comment by theMackabu** [comment]
I’m not totally suggesting it, but Arc browser expands the sidebar on hover, that could also be added as an option?

**Comment by mauro-balades** [comment]
Absolutely, a lot of people has been asking this and it's something that I like. Expect this for the next release!

**Comment by mauro-balades** [comment]
![Screenshot_20240719_232437](https://github.com/user-attachments/assets/3a4f6079-73ea-44ab-887b-2b7ae717fd42)

it's very work in progress but im still cooking on this

**Comment by mauro-balades** [comment]
Some things I do want to note is that I even though ill close this issue, ill keep working on it (I need to do some cleaning up). The sidebar can be resizeable and disabled (hide button included) in the settings. I still need to do the shortcuts thing. The close button will be displayed once hovering on it (I Could add an option to always show on active tab?). 

Thanks a lot for this suggestion! Ill keep working on it.
