### ISSUE TITLE
Can you add simplified Chinese translation?

### ISSUE THREAD

**Issue by zangbob** [zen-browser/desktop#720]
### What feature would you like to see?

In China, many people still love firefox and new software developed on it. Personally, I fell in love with ZEN the first time I ran it. I think it is more amazing than librewolf and floorp that I installed before.

The English interface may prevent many people from using it. I hope there will be a Chinese translation as soon as possible. I can't wait to recommend it to my friends.

**Comment by XInTheDark** [comment]
The Simplified Chinese translation has already been completed on Crowdin :)

**Comment by zangbob** [comment]
> The Simplified Chinese translation has already been completed on Crowdin :)

Wow... :D

Where can I download it?

**Comment by XInTheDark** [comment]
It should probably be included in the next release

**Comment by zangbob** [comment]
Looking forward to it
