### ISSUE TITLE
URL bar pill doesn't change shape when searching

### ISSUE THREAD

**Issue by notsatvrn** [zen-browser/desktop#721]
### What happened?

Some websites have additional emblems such as permissions after the HTTPS icon in the URL bar. When this occurs, the right side of the bar pill loses it's roundness so the two sections can merged into one block.

![image](https://github.com/user-attachments/assets/bc970021-5dba-4340-a945-a84144c005d8)

Unfortunately, when deleting the URL and beginning a search from a site where this occurs, the pill does not return to it's original shape.

![image](https://github.com/user-attachments/assets/1eeaf7ce-728b-445f-be7d-079c15f2df9f)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.29

### Severity impact

Low

### What platform are you seeing the problem on?

Linux

**Comment by notsatvrn** [comment]
I should also note, this behavior isn't just visible on websites with the additional permissions icon. That wasn't immediately apparent to me because on those sites it didn't have the ugly right side unrounded behavior to carry over.

**Comment by KiKaraage** [comment]
Yeeeeeees. Noticed this too.

**Comment by notsatvrn** [comment]
Working on a PR for this issue as well as some other tiny inconsistencies that bothered me.

**Comment by notsatvrn** [comment]
Tried a number of things, at this point I'm convinced the only way to fix the shape issue when the permissions box is present is to separate it from the first box or make it invisible in the extended search box. I've tried a number of CSS selectors to detect when the box is no longer visible but still present, nothing seems to be working.
