### ISSUE TITLE
Issue Bots

### ISSUE THREAD

**Issue by smultar** [zen-browser/desktop#724]
I think this repository suffers from a small bot infestation.

**Comment by notsatvrn** [comment]
Most of these accounts look previously legitimate, so whatever malware is being spread is likely being used to hijack the victim's GitHub accounts and continue to spread the malware.

**Comment by smultar** [comment]
> Most of these accounts look previously legitimate, so whatever malware is being spread is likely being used to hijack the victim's GitHub accounts and continue to spread the malware.

I have reported the accounts to GitHub to prevent further dissemination of the issue and to request a hold on the accounts until the matter is resolved. I have also examined the code they presented in a virtual machine, and it has been confirmed to contain malware. *Thanks virus total*

**Comment by mauro-balades** [comment]
I honestly dont know what to do, ill just report them until they are gone. Btw, what virus is it?
