### ISSUE TITLE
Failed installation

### ISSUE THREAD

**Issue by BlueFox1616** [zen-browser/desktop#73]
When installing the program on windows either via the zip or the installer i get this error

The code execution cannot proceed because MSVCP140.dll was not found .Reinstalling the program may fix this problem 
![Screenshot 2024-07-17 180109](https://github.com/user-attachments/assets/0d39205d-ffa1-4d1b-a9b0-43aa4d46953b)
The code execution cannot proceed because VCRUNTIME140.dll was not found .Reinstalling the program may fix this problem 
![Screenshot 2024-07-17 175939](https://github.com/user-attachments/assets/a4c704a7-fc2f-45e6-913c-3acaf62c8672)

**Comment by mauro-balades** [comment]
Yeah, but please note that it has been build with vs2022
