### ISSUE TITLE
Pop out window doesnt work

### ISSUE THREAD

**Issue by Admsher** [zen-browser/desktop#730]
### What happened?

I try to open a popup window in my zen linux version in youtube and it gives a blank page

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0 alpha

### Severity impact

Low

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
Could you send a video or something that shows this issue?

**Comment by Admsher** [comment]
[Uploading Screencast from 2024-08-27 19-28-32.webm…]()

**Comment by mauro-balades** [comment]
iirc this is an issue with firefox, it will be fixed once they update it
