### ISSUE TITLE
The website is broken

### ISSUE THREAD

**Issue by iamrgroot** [zen-browser/desktop#732]
### What happened?

https://www.zen-browser.app/

Sorry for filing a bug report, but I did not now how else to contact the Zen team. The vercel website is not working

![image](https://github.com/user-attachments/assets/249b8547-20db-4891-a9dd-c2f4bb24d75f)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0

### Severity impact

Critical

### What platform are you seeing the problem on?

Linux, macOS - aarch64, macOS - Intel, Windows

**Comment by murshid1988** [comment]
> `420: PAYMENT_REQUIRED`
> 
> Thanks @t3dotgg 😅

Went to the site after seeing his video 🤣

**Comment by jazsouf** [comment]
While they figure out the stuff with their cloud provider, here are the links to download:
MacOS: https://github.com/zen-browser/desktop/releases/latest/download/zen.macos-aarch64.dmg
MacOSIntel: https://github.com/zen-browser/desktop/releases/latest/download/zen.macos-x64.dmg
WindowsZip: https://github.com/zen-browser/desktop/releases/latest/download/zen.win-specific.zip

Base URL found here: https://github.com/zen-browser/www/blob/main/src/components/download.tsx#L11
Releases found here: https://github.com/zen-browser/www/blob/main/src/lib/releases.ts

**Comment by ch4og** [comment]
> While they figure out the stuff with their cloud provider, here are the links to download:
> 
> MacOS: https://github.com/zen-browser/desktop/releases/latest/download/zen.macos-aarch64.dmg
> 
> MacOSIntel: https://github.com/zen-browser/desktop/releases/latest/download/zen.macos-x64.dmg
> 
> WindowsZip: https://github.com/zen-browser/desktop/releases/latest/download/zen.win-specific.zip
> 
> 
> 
> Base URL found here: https://github.com/zen-browser/www/blob/main/src/components/download.tsx#L11
> 
> Releases found here: https://github.com/zen-browser/www/blob/main/src/lib/releases.ts

Why so complex way if its just here https://github.com/zen-browser/desktop/releases/tag/1.0.0-a.29

**Comment by jakob1379** [comment]
and for the nix-user: https://github.com/MarceColl/zen-browser-flake

**Comment by iamrgroot** [comment]
So, it seems downloading themes is also broken as it uses the same domain?

**Comment by NOCanoa** [comment]
Cheff is working it xD

**Comment by mauro-balades** [comment]
God that was a nightmare, it should be fixed now
