### ISSUE TITLE
Hotkey to expand sidebar

### ISSUE THREAD

**Issue by JoshuaKeegan3** [zen-browser/desktop#733]
### What feature would you like to see?

A hot key to toggle the sidebar that holds the tabs and workspaces. For clarity I'm talking about adding a hotkey with the same functionality as this button

<img width="37" alt="image" src="https://github.com/user-attachments/assets/b7346ade-a200-4622-924e-eda7cdca9a23">

**Comment by pete-willard** [comment]
I can't figure out how to do that either! I'm using alpha-30 on linux.

**Comment by TomRaaff** [comment]
There is a workaround:
Right click in your sidebar => compact mode => hide sidebar
Then go to settings => keyboard shortcuts => toggle compact mode => assign a shortkey of your liking.
This way, you'll be able to hide the sidebar, by entering compact mode.

**Comment by pete-willard** [comment]
This has been since improved and fixed. Look for `Toggle Sidebar's Width` shortcut in the `Other Zen Features` section of the keyboard shortcuts

**Comment by JoshuaKeegan3** [comment]
> This has been since improved and fixed. Look for `Toggle Sidebar's Width` shortcut in the `Other Zen Features` section of the keyboard shortcuts

This is what I was originally hoping for. 

I wonder if we could get functionality for exiting compact mode and expanding the sidebar at the same time. What I mean by this is combining two hotkeys/buttons. Exit compact mode and then expand the side bar. Last I checked binding both of them to the same key didn't work.

If this is too much of a jump for this issue we could make another.

**Comment by bliuchak** [comment]
@TomRaaff thanks for your answer!

I've tweaked it a bit to my taste. First of all in settings "Look and Feel" I choose "single sidebar". Then I enabled "compact mode" and then set "hide both" (toolbar and sidebar). To make it work I need to restart browser. After that I got clean window with (single) sidebar is hidden by default.

To make it even more perfect I'd like to achieve same experience with sidebar like in Arc - set hotkey to toggle sidebar. I set "Toggle Floating Sidebar" shortcut to "Cmd+s" (before in advance removed it's default behavior to save page).

Result: clean browser window and Cmd+s hotkey to toggle sidebar (as in Arc).

**Comment by krissh-codes** [comment]
This works fine. But unfortunately, it seems there is no transition set for the side bar width change, which makes the feel a bit jittery. But when you have the full width sidebar and toggle it on and off, the sidebar slides in and out with a smooth transition...

**Comment by biinggala** [comment]
option + B
