### ISSUE TITLE
Pressing "Bookmarks" twice in the bottom left doesn't close the bookmarks tab

### ISSUE THREAD

**Issue by mayemu** [zen-browser/desktop#74]
Pretty sure this is unintentional as when you click side view again after its open, it closes. The bookmarks icon doesn't have the same functionality

**Comment by mauro-balades** [comment]
Nice, I haven't thought about this, thanks!

**Comment by mauro-balades** [comment]
Hey, sorry for taking that long, I had to be offline for some days, anyways, it's not fixed (https://github.com/zen-browser/desktop/commit/40b652869de13aacf340bc2261baabbde591da0c) it will be reflected on the next release, thanks!
