### ISSUE TITLE
Windows Defender picked up Zen as Trojan:Script/Wacarc.B!ml

### ISSUE THREAD

**Issue by Stefanistkuhl** [zen-browser/desktop#746]
### What happened?

I just opened zen today and it crashed after windows deleted the files for it.
![image](https://github.com/user-attachments/assets/d09fa7c4-4f7e-4274-9c1a-2895f8078216)
![image](https://github.com/user-attachments/assets/a7907d4d-2c2e-427f-bf8f-52c6dc494a69)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by alexmro** [comment]
Mine (Windows 10) complains about a "PUA:Win32/Packunwan" virus inside and does not let me install it. Seems like every user gets a different surprise virus name

**Comment by mauro-balades** [comment]
Please refer to https://github.com/zen-browser/desktop/issues/37

**Comment by islemci** [comment]
Mentioned at #37, Windows is just acting stupid.
