### ISSUE TITLE
Updating the browser breaks it

### ISSUE THREAD

**Issue by diego-velez** [zen-browser/desktop#76]
When I update the browser via `Help` -> `About Zen`, the browser seems to break, meaning that I cannot open it after it automatically closes after clicking the `Restart to Update Zen` button.

When manually re-installing fresh and re-running the process from the terminal, I get the following:

```
ATTENTION: default value of option mesa_glthread overridden by environment.
~/.local/bin/zen/updater: error while loading shared libraries: libmozsqlite3.so: cannot open shared object file: No such file or directory
~/.local/bin/zen/updater: error while loading shared libraries: libmozsqlite3.so: cannot open shared object file: No such file or directory
```

I'm running the `1.0.0-a.4 (64-bit)` version on Fedora 40 Cinnamon.

**Comment by mauro-balades** [comment]
While I fix this, you can try by going into the browser's directory and run the following commands:

```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)
```



and run zen from the command line (`./zen`) this will make the update work until I try to fix the problem

**Comment by diego-velez** [comment]
It did not work, I ran `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)` on the terminal, then opened the browser from the terminal, tried to update it, and I'm still getting the same error.

**Comment by mauro-balades** [comment]
you need to run that command inside the same folder as zen's binary. I need you to confirm you did that.

**Comment by diego-velez** [comment]
That worked, my apologies.

**Comment by mauro-balades** [comment]
no problem! Ill try to fix it anyways without having to do any LD path exporting, etc
