### ISSUE TITLE
Browser Crash on Wayland

### ISSUE THREAD

**Issue by Froztmuffins** [zen-browser/desktop#77]
Crash Annotation GraphicsCriticalError: |[0][GFX1-]: Wayland protocol error: wp_linux_drm_syncobj_surface_v1#49: error 4: No Acquire point provided
 (t=15.8557) [GFX1-]: Wayland protocol error: wp_linux_drm_syncobj_surface_v1#49: error 4: No Acquire point provided

**Comment by mauro-balades** [comment]
could you try running `MOZ_ENABLE_WAYLAND=0 zen`?

**Comment by Froztmuffins** [comment]
It works, thank you

**Comment by mbledkowski** [comment]
Still an issue on flatpak. Adding `MOZ_ENABLE_WAYLAND=0` as an env variable through Flatseal, helps.
