### ISSUE TITLE
Expand side bar bugs

### ISSUE THREAD

**Issue by NOCanoa** [zen-browser/desktop#79]
### What happened?

1) when expanding side bar pined tabs dont show text
![image](https://github.com/user-attachments/assets/f0152a08-695d-4fd1-893b-00ad20dc6237)
idea put them side by syde

2)in copact mode it bugs and stays open whit no stuff
![image](https://github.com/user-attachments/assets/485052c3-4e41-473e-9599-cebcde962350)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

a0.6

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
Both of these had been fixed for the next release, thanks a lot!
