### ISSUE TITLE
Middle mouse button new tab not worki

### ISSUE THREAD

**Issue by NOCanoa** [zen-browser/desktop#80]
### What happened?

Normaly when pressing the middle mouse button it creates a new tab,but doesnt apear to work here.

but if i do middle button click next to an existing tab it works

https://github.com/user-attachments/assets/a0bfaf4c-8a51-40e0-acf3-c7d2628b229b

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

a0.6

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
Does this still happen?

**Comment by NOCanoa** [comment]
Creating new tabs with middle mouse button does not work.
