### ISSUE TITLE
Workspace deleting button bug

### ISSUE THREAD

**Issue by NOCanoa** [zen-browser/desktop#81]
### What happened?

when you select the popup for the workspace, if you click any one off them and press delete it will only delete the workspace is active in that moment, so in consequence the browser closes and it deletes the active workspace instead of the one i selected.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

a0.6

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
Fixed with https://github.com/zen-browser/desktop/commit/0dfb1986099d51ea657f516b9fb6f19e58439266, thanks!
