### ISSUE TITLE
Trying to interact with extensions that allow sidebar functionality without using the sidebar does not work, interacts with current web page instead

### ISSUE THREAD

**Issue by mayemu** [zen-browser/desktop#82]
### What happened?

Gif of this happening with Bitwarden is linked here: https://z.ribbit.li/u/zen_kYCb8AgbZo.gif as I can't find a way to embed a gif here. I believe the issue is due to Bitwarden being one of the few extensions that supports being an entire sidebar application (Sideberry and Video DownloadHelper are others for example). I could be totally wrong but I suspect this is the reason for the problem as other extensions are totally functional and Bitwarden is a very reputable extension.

But yeah, because of this I am completely unable to login and use Bitwarden. I am not sure if others have experienced this, would be nice to know if others can use Bitwarden or other extensions with sidebar support as well.

P.S. Continue the incredible work with the browser, I am continually so impressed by this project with every update seriously! You guys are crazy talented. I'm the person who made [this comment](http://z.ribbit.li/u/floorp_K0ebTaGByC.png) seeing it be implemented within less than a week and so flawlessly too made me so happy :). Hope tab hierarchy is soon! Haha

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Windows 11, Alpha build - 1.0.0-a.6 

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
Hi, im glad you are linking it so far!

I will look into this issue because it appears to only be on windows. Thanks! Expect it fixed for the next release.

**Comment by mauro-balades** [comment]
https://github.com/user-attachments/assets/2cba9a64-9ed0-4aed-b925-dfa9675fd69e

Sorry but I can't reproduce the problem. Are there any acctions you performed that could lead to this?

**Comment by mayemu** [comment]
I totally forgot about this and I'm just remembering now that I was originally able to change the bitwarden login setting from their server to self-hosted. I believe once I did that, the issue started. Here are some other things that could be of note:
- I use the betterfox user.js with the 120hz+ smooth scrolling added 
- I'm on windows 11 not 10

**Comment by mayemu** [comment]
Maybe to try and replicate you could remove bitwarden and reinstall, then try to interact with the login page after enabling self hosting?

**Comment by mayemu** [comment]
the newest update seems to have fixed this somehow? ever since it updated, i havent had this issue at all. so ill close for now, do reopen if it still occurs for others

**Comment by mauro-balades** [comment]
I did a little experiment for this update and it seemed to have fixed it

**Comment by mayemu** [comment]
hahaha thats awesome, great work!
