### ISSUE TITLE
Multi tab close wording (quality of life)

### ISSUE THREAD

**Issue by diego-velez** [zen-browser/desktop#83]
When right-clicking over a tab and going to "Close Multiple Tabs", the options that appear are:

- Close Tabs to Left
- Close Tabs to Right
- Close Other Tabs

For the first two options, it should be `Above` instead of `Left` and `Below` instead of `Right`, since the tabs are organized vertically.

**Comment by mauro-balades** [comment]
Absolutely! I haven't noticed this 😅
