### ISSUE TITLE
You can’t open the application “Zen Browser.app” because this application is not supported on this Mac.

### ISSUE THREAD

**Issue by Alexcoder5** [zen-browser/desktop#84]
### What happened?

I followed the installation guide for mac https://github.com/zen-browser/desktop/issues/53 and still can't open the app on my mac. I get an error: You can’t open the application “Zen Browser.app” because this application is not supported on this Mac.

MacBook Pro (Mid 2015)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.7

### What platform are you seeing the problem on?

macOS

**Comment by seven-of-eleven** [comment]
I had the same issue. The app in the DMG file is for Apple Silicon. It doesn't work on my Intel Mac.

**Comment by mauro-balades** [comment]
You can download for apple intel now in the downloads page!
