### ISSUE TITLE
Cannot find Flatpak

### ISSUE THREAD

**Issue by diego-velez** [zen-browser/desktop#85]
### What happened?

I execute `flatpak install flathub io.github.zen_browser` in my terminal and get the following:

```
Looking for matches…
error: Nothing matches io.github.zen_browser in remote flathub
```

I'm running Fedora 40.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

N/A

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
Looking for matches…
error: Nothing matches io.github.zen_browser in remote flathub
```

**Comment by Sophokles187** [comment]
I have the same Problem, also running Fedora 40.

**Comment by kuroki100** [comment]
the package appears to be on the test branch, i installed using this command:
`flatpak install --user https://dl.flathub.org/build-repo/119864/io.github.zen_browser.zen.flatpakref`
btw i found the command on the discord of the dev.

**Comment by mauro-balades** [comment]
It's now released! https://flathub.org/apps/io.github.zen_browser.zen
