### ISSUE TITLE
Rebase on Floorp and Mercury

### ISSUE THREAD

**Issue by ThousandDemonDaggers** [zen-browser/desktop#86]
Rebasing on Floorp and Mercury instead of Firefox will grant additional features, performance and hardening

**Comment by mauro-balades** [comment]
But it would be based on older versions of firefox and it would give me less control over the browser.

**Comment by ThousandDemonDaggers** [comment]
> But it would be based on older versions of firefox and it would give me less control over the browser.

Seems that Floorp is changing how the release model, so it might be interesting to keep an eye on this

**Comment by mauro-balades** [comment]
Isn't floorp partially closed source though?

**Comment by ThousandDemonDaggers** [comment]
> Isn't floorp partially closed source though?

No, not anymore, now it is fully open.

Source:

- [https://blog.ablaze.one/4125/2024-03-11/](https://blog.ablaze.one/4125/2024-03-11/)

- [https://github.com/Floorp-Projects/Floorp](https://github.com/Floorp-Projects/Floorp)
