### ISSUE TITLE
Can't interact with password-manager extensions 

### ISSUE THREAD

**Issue by KodusTheOnly** [zen-browser/desktop#89]
### What happened?

Installed Bitwarden extension through the Firefox Addons store, and for some reason it wont let me interact with it. While other extensions like Dark Reader it works as normal
Video below:
https://github.com/user-attachments/assets/0c95fd54-5323-4593-a605-2e758fb8822e

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.7 

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
Do you have any `userChrome.css` enabled or did you do any specific actions that leaded you to this problem? Because I dont seem to be able to reproduce.

**Comment by Thorebourne** [comment]
i was experiencing the same issue, all i did was install Bitwarden directly from the extension store on a fresh install and it just... didn't work

**Comment by KodusTheOnly** [comment]
> Do you have any `userChrome.css` enabled or did you do any specific actions that leaded you to this problem? Because I dont seem to be able to reproduce.

I did a fresh reinstall of zen yesterday, installed bitwarden, and was met with the same bug, the workaround was to press tab to select the buttons and write my email etc... Also no userChrome.css enabled
Sometimes it works as usual and sometimes it doesn't.
