### ISSUE TITLE
Cannot add new Sidebar Web Panels

### ISSUE THREAD

**Issue by over-fitted** [zen-browser/desktop#894]
### What happened?

I deleted all the original sidebar web panel icons. I then attempted to create a new web panel for spotify but nothing happens after clicking OK. 

Behavior persists when using a proper URL, just `spotify` and when pressing ok with nothing populating the field. 

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Version 1.0.0-a.29 (64-bit)

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by ch4og** [comment]
i guess your problem is the fact that it should include https://

**Comment by mauro-balades** [comment]
^^^
