### ISSUE TITLE
Zen browser does not open in Windows 11 Version 23H2 for x64-based systems (KB5041585)

### ISSUE THREAD

**Issue by abhishekjaiswar221** [zen-browser/desktop#897]
### Screenshots:
1. The desktop shortcut does not have the Z icon of Zen

![zen desktop](https://github.com/user-attachments/assets/fedf2f1d-f9b0-49d1-8f15-c709ba782b46)

2. Unable to open the browser using the desktop shortcut

![zen desktop not opening on windows 11](https://github.com/user-attachments/assets/78015c3f-1fe0-4436-a67c-e2da67581e50)

3. Unable to open the browser from the apps section

![zen private browser](https://github.com/user-attachments/assets/a89df80f-bf8a-4d84-85f0-ffb9a37b5a25)

4. Windows Security Issue

![security 1](https://github.com/user-attachments/assets/bed94e0f-1b65-4054-84c6-c9642a50b9d1)

![security 2](https://github.com/user-attachments/assets/639e78f1-e40c-45a3-b349-00d9e88cf31d)

![security 3](https://github.com/user-attachments/assets/58880474-826f-4f34-920c-cbec8abc452e)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Alpha build - 1.0.0-a.29 (2024-08-24) 

### Severity impact

Critical

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
Please follow: https://github.com/zen-browser/desktop/actions/runs/10558905630
