### ISSUE TITLE
Zen browser uninstaller is not working

### ISSUE THREAD

**Issue by abhishekjaiswar221** [zen-browser/desktop#898]
### Issue: 
- Not able to uninstall the zen browser
- No response of the uninstaller after uninstalling the browser

### Screenshot:
![zen not uninstalling](https://github.com/user-attachments/assets/7c75c155-b4cb-4a31-8972-6567bd8aef47)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Alpha build - 1.0.0-a.29 (2024-08-24) 

### Severity impact

High

### What platform are you seeing the problem on?

Windows

**Comment by ch4og** [comment]
might be related: https://github.com/zen-browser/desktop/issues/37

**Comment by mauro-balades** [comment]
Yeah, checkout that issue... windows is acting weird
