### ISSUE TITLE
Sidebar Expand Setting Incorrectly Reverts to Default After Disabling Compact Mode

### ISSUE THREAD

**Issue by talhabw** [zen-browser/desktop#899]
### What happened?

To reproduce:

1. Disable compact mode
2. Set `Expand Tabs on Hover`
3. Enable compact mode
4. Sidebar behaves as if it is set to `Expand Tabs by Default` (this is expected and not a bug)
5. Disable compact mode
6. Sidebar still behaves as if it is set to `Expand Tabs by Default` (it should be set to what it was before enabling compact mode, this is a bug)

Expected behaviour:
- It should still be set to `Expand Tabs on Hover` when compact mode is disabled again.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.29

### Severity impact

Medium

### What platform are you seeing the problem on?

Windows

**Comment by karosc** [comment]
I have a similar issue when using the expand button. Most of the time I like my tabs to be collapsed and have them expand on hover. However, sometimes I want to pin the tab sidebar as expanded for a specific workflow. I use the expand button to do that, but when collapsing the tabs, the expand on hover functionality is disabled:


https://github.com/user-attachments/assets/e3eb71c8-2fd1-4ab4-999f-4802ef96f3cd

**Comment by karosc** [comment]
my issue has been fixed in one of the recent releases (not sure which one)!
