### ISSUE TITLE
Ability to drag and drop tabs into split view

### ISSUE THREAD

**Issue by SomeDudeBrosky** [zen-browser/desktop#90]
It's really tedious how you currently select tabs for split view. It would be better to be able to just drag and drop them in and out of split view, or just generally a better way to select and deselect tabs into and out of split view,

**Comment by mauro-balades** [comment]
This issue should be discussed further. You can view and continue the discussion here: https://github.com/zen-browser/desktop/discussions/892

 ~ This is an automatic operation to better enhancements requests organization.
