### ISSUE TITLE
When switching to a tab from url bar the tab should not be displayed in the current workspace

### ISSUE THREAD

**Issue by j-chmielewski** [zen-browser/desktop#901]
### What happened?

I think that at least there should be an option for this. Changing tabs by typing keywords in the url bar and then selecting the "switch tab" option is very convenient since it searches across all workspaces and tabs. It can also be done just with keyboard, no mouse, great. But what ruins it is that the tab is then displayed in my current workspace. Now if I open some links on this site they are opened in wrong workspace. Instead I should be switched to the workspace where the tab already lives.
### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0

### Severity impact

Low

### What platform are you seeing the problem on?

Linux

**Comment by salamijason** [comment]
I just tried this and it seems to switch to the correct workspace. Can you check if you still get this issue in the latest build? 1.0.1-a.14

**Comment by salamijason** [comment]
User has not replied in a couple week. Closing the issue now. Please reopen if issue persists.
