### ISSUE TITLE
Why is there no Chinese interface

### ISSUE THREAD

**Issue by xiulou23** [zen-browser/desktop#905]
### What happened?

The question I want to feedback is not a bug, but why there is no Chinese interface. Your browser is developed based on Firefox, Firefox has a Chinese interface, why does your browser not have a Chinese interface? Is there no Chinese interface for the time being, or will there never be one in the future? I hope to be able to use the Chinese interface as soon as possible

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.29

### Severity impact

High

### What platform are you seeing the problem on?

Windows

**Comment by ch4og** [comment]
Chinese translation will be available on the next release as well as many others

**Comment by Donnnno** [comment]
https://crowdin.com/project/zen-browser

**Comment by mauro-balades** [comment]
Just a sidenote: the severity doesn't mean "how much you want it"
