### ISSUE TITLE
Let us hide the top toolbar only

### ISSUE THREAD

**Issue by migtorr** [zen-browser/desktop#907]
### What happened?

On compact mode we can only hide the top toolbar when hide sidebar is enabled. No option to hide the top toolbar only

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.29

### Severity impact

Low

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
This has been requested before, for enhancements please use discussions
