### ISSUE TITLE
Crunchyroll error

### ISSUE THREAD

**Issue by genesis224** [zen-browser/desktop#908]
### What happened?

![image](https://github.com/user-attachments/assets/a136c40a-57e7-47f7-a5c9-b0eddb3437eb)

Is there any workaround to fix this error? this works in my chrome browsers

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by ch4og** [comment]
https://docs.zen-browser.app/faq#why-cant-zen-browser-play-drm-protected-content
