### ISSUE TITLE
"Toggle Compact Mode Sidebar" keybind only works on the main window.

### ISSUE THREAD

**Issue by mambans** [zen-browser/desktop#910]
### What happened?

The key-bind "Toggle Compact Mode Sidebar" only works for the main/first window.

When opening a second window the key-bind for "Toggle Compact Mode Sidebar" does not work on that window, nothing happens when pressing the key-bind.

Version: 1.0.0-a.30

PS: Love the browser 👍 

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.30

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by salamijason** [comment]
Was not able to reproduce on version 1.0.1-a.14, could you check if you still have this issue on the latest version?

**Comment by mambans** [comment]
> Was not able to reproduce on version 1.0.1-a.14, could you check if you still have this issue on the latest version?

Hi, I can't reproduce the issue anymore. Now works like a charm 👍

**Comment by salamijason** [comment]
Epic
