### ISSUE TITLE
JavaScript is not executing in console

### ISSUE THREAD

**Issue by stellaOnEstrogen** [zen-browser/desktop#913]
### What happened?

The console does not seem to be working correctly, syntax highlighting works however execution does not.

I'm not the only one seeing this issue:
- #593 
- #636

![image](https://github.com/user-attachments/assets/4bf18a06-ecc5-44e4-8762-99a3be22491e)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.29

### Severity impact

Medium

### What platform are you seeing the problem on?

Linux, Windows

**Comment by ch4og** [comment]
fixed on a30

**Comment by stellaOnEstrogen** [comment]
> fixed on a30

Thank you so much!!
