### ISSUE TITLE
Horizontal and vertical split not working with shortcuts

### ISSUE THREAD

**Issue by Myouboku** [zen-browser/desktop#915]
### What happened?

![zen_rm7iEwoCmo](https://github.com/user-attachments/assets/1efd8acb-ffe9-403e-a387-ecf65ae1c681)

The horizontal and vertical split view isn't working using shortcuts, the grid view works fine

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.30

### Severity impact

Medium

### What platform are you seeing the problem on?

Windows

**Comment by Luquatic** [comment]
I have the same problem on MacOS

**Comment by Luquatic** [comment]
not sure if #622 has something to do with it

**Comment by Myouboku** [comment]
I haven't remapped the shortcuts, the issue is with default settings, but I'll try to remap and see if something changes

**Comment by 4NXIE7Y** [comment]
Can confirm the same issue on Windows with Zen build1.0.0-a.30.
Everything will work fine if we start the splitting process with Ctrl+Alt+G (the grid layout) initially and then proceed with the splitting process via the (image attached below) button.
![image](https://github.com/user-attachments/assets/473dd3d4-dc69-47b2-909c-f29a1115b6bf)
But if we start with Ctrl+Alt+V or Ctrl+Alt+H, this issue of the following tab becoming invisible occurs.

**Comment by mauro-balades** [comment]
Fixed for the next release! 💯
