### ISSUE TITLE
Sidebar accidentally expands when taking screenshots in compact mode

### ISSUE THREAD

**Issue by Robot-Inventor** [zen-browser/desktop#917]
### What happened?

If you try to take a screenshot with Ctrl + Shift + S when compact mode is enabled, the sidebar will be accidentally expanded. This issue occurs regardless of the key binding settings. This is not a major issue since the sidebar is automatically hidden when you start selecting areas for screenshots, but it is a little difficult to use.

![image](https://github.com/user-attachments/assets/98fd52c1-9018-42ef-9c10-5ce917ac2081)

keybind settings:

![image](https://github.com/user-attachments/assets/ea9b2fab-00f5-4f8a-b050-699ebd3baa61)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.30

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by Doc-4** [comment]
I'm getting this too
![image](https://github.com/user-attachments/assets/9200d3df-5e9e-4a15-a5d9-e3ca2cec4da5)

**Comment by salamijason** [comment]
Was able to reproduce on latest ver 1.0.1-a.14. assigned as bug. Thanks for pointing this out!

**Comment by salamijason** [comment]
Looks like this also happens in non-compact mode 

see here https://github.com/zen-browser/desktop/issues/1913

happened when expand on hover was on

**Comment by Robot-Inventor** [comment]
> happened when expand on hover was on

When this issue was first created, that option wasn’t available. After checking again, I can confirm that, as you mentioned, the same issue occurs even outside of compact mode when 'expand on hover' is enabled.

**Comment by Robot-Inventor** [comment]
This issue still occurs in 1.0.1-a.22

**Comment by neurokitti** [comment]
I tested this in the most recent version of zen twilight and I am not seeing the issue. if this issue still persists please re-open the issue.

**Comment by salamijason** [comment]
Fixed in latest beta version as well. (b.2)
