### ISSUE TITLE
Youtube UI issue

### ISSUE THREAD

**Issue by Suman2023** [zen-browser/desktop#922]
### What happened?

The interaction section of YouTube is not showing the Chips correctly.
Here: 
![image](https://github.com/user-attachments/assets/3bf8bcb6-3660-460b-8d09-838cad22cc27)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.30 (64-bit)

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by PowerzinBR** [comment]
does that happen on other browsers or it's just zen?

**Comment by TomTruyen** [comment]
I haven't had this issue myself but I can see on Zen and other browsers that the UI of YouTube is messed up sometimes. Most noticeable for me is on the discover page that the spacing between videos is inconsistent. I expect this to be YouTube messing up

**Comment by RayZ3R0** [comment]
Does this still happen on latest version? (a.14 as of this comment)

**Comment by Suman2023** [comment]
No, seems its fixed. I don't see the issue anymore
