### ISSUE TITLE
Translations don't fully work

### ISSUE THREAD

**Issue by ch4og** [zen-browser/desktop#923]
### What happened?

Some elements doesn't follow translation that is provided (for example application menu and context menus)

These strings are translated but for some reason aren't used
For example russian translated strings were added here https://github.com/zen-browser/l10n-packs/commit/eea5a41c3608f985237af799a9fb3b78b4b6d1b3 and this commit is merged, submodule of zen-browser/desktop was on higher commit when a.30 was built

![resim](https://github.com/user-attachments/assets/04e3b159-44a8-42ea-8122-3a6478073bef)
![resim](https://github.com/user-attachments/assets/d50b87a4-7574-4776-9f4b-c3127a404109)
![resim](https://github.com/user-attachments/assets/8426c1ee-b1c7-4750-94d6-492899ee8367)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.30

### Severity impact

Low

### What platform are you seeing the problem on?

Linux, Windows

**Comment by RayZ3R0** [comment]
Translation is more of a firefox feature, and yeah its buggy. Zen can't really do anything about this yet
