### ISSUE TITLE
privacy.resistFingerprinting.letterboxing Bug

### ISSUE THREAD

**Issue by KPCOFGS** [zen-browser/desktop#925]
### What happened?

When setting `privacy.resistFingerprinting.letterboxing` to true. it produces dark thick border for some reason. This thick border does not exist when setting `privacy.resistFingerprinting.letterboxing` to false. Please take a look at the following image:

![screenshot](https://github.com/user-attachments/assets/162ee16e-5f5d-4bf1-9def-240e287028d3)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.30

### Severity impact

Low

### What platform are you seeing the problem on?

Linux

**Comment by qtchaos** [comment]
What's the issue here? The point of letterboxing is to make the website believe that you're browser is smaller than it is, so it creates these "borders", if you think that they could look better, sure, but then that's more of a styling issue.

**Comment by KPCOFGS** [comment]
Ah, I see. Thank you for the clarification!
