### ISSUE TITLE
Error when building E0463

### ISSUE THREAD

**Issue by Amr-Shams** [zen-browser/desktop#929]
### What happened?

`
 DEBUG: Creating `/var/folders/4y/2jj_nmbs09b4qxtj2xts8g700000gn/T/conftestl_1dqxfv.rs` with content:
00:02:20 DEBUG: | pub extern fn hello() { println!("Hello world"); }
00:02:20 DEBUG: Executing: `/Users/amraly/.rustup/toolchains/stable-x86_64-apple-darwin/bin/rustc --crate-type staticlib --target=aarch64-apple-darwin -o /var/folders/4y/2jj_nmbs09b4qxtj2xts8g700000gn/T/conftest8j9xtxim.rlib /var/folders/4y/2jj_nmbs09b4qxtj2xts8g700000gn/T/conftestl_1dqxfv.rs`
00:02:20 DEBUG: The command returned non-zero exit status 1.
00:02:20 DEBUG: Its error output was:
00:02:20 DEBUG: | error[E0463]: can't find crate for `std`
00:02:20 DEBUG: |   |
00:02:20 DEBUG: |   = note: the `aarch64-apple-darwin` target may not be installed
00:02:20 DEBUG: |   = help: consider downloading the target with `rustup target add aarch64-apple-darwin`
00:02:20 DEBUG: |
00:02:20 DEBUG: | error: aborting due to 1 previous error
00:02:20 DEBUG: |
00:02:20 DEBUG: | For more information about this error, try `rustc --explain E0463`.
00:02:20 ERROR: Cannot compile for aarch64-apple-darwin with /Users/amraly/.rustup/toolchains/stable-x86_64-apple-darwin/bin/rustc
`

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

20.5.1

### Severity impact

Low

### What platform are you seeing the problem on?

macOS - Intel

**Comment by mauro-balades** [comment]
You need to run `npm run bootstrap` first!

**Comment by Amr-Shams** [comment]
00:00:14 DEBUG: Creating `/var/folders/4y/2jj_nmbs09b4qxtj2xts8g700000gn/T/conftest_hh48n6p.rs` with content:
00:00:14 DEBUG: | pub extern fn hello() { println!("Hello world"); }
00:00:14 DEBUG: Executing: `/Users/amraly/.rustup/toolchains/stable-x86_64-apple-darwin/bin/rustc --crate-type staticlib --target=aarch64-apple-darwin -o /var/folders/4y/2jj_nmbs09b4qxtj2xts8g700000gn/T/conftestyng5n_85.rlib /var/folders/4y/2jj_nmbs09b4qxtj2xts8g700000gn/T/conftest_hh48n6p.rs`
00:00:14 DEBUG: The command returned non-zero exit status 1.
00:00:14 DEBUG: Its error output was:
00:00:14 DEBUG: | error[E0463]: can't find crate for `std`
00:00:14 DEBUG: |   |
00:00:14 DEBUG: |   = note: the `aarch64-apple-darwin` target may not be installed
00:00:14 DEBUG: |   = help: consider downloading the target with `rustup target add aarch64-apple-darwin`
00:00:14 DEBUG: |
00:00:14 DEBUG: | error: aborting due to 1 previous error
00:00:14 DEBUG: |
00:00:14 DEBUG: | For more information about this error, try `rustc --explain E0463`.
00:00:14 ERROR: Cannot compile for aarch64-apple-darwin with /Users/amraly/.rustup/toolchains/stable-x86_64-apple-darwin/bin/rustc


i still got this error
