### ISSUE TITLE
Web Developer Console does not store client inserted code

### ISSUE THREAD

**Issue by MichaHere** [zen-browser/desktop#930]
### What happened?

When writing code in the web developer console and executing the code, the code will not be executed. The following code returns nothing in the console: `console.log("Hello world")`. Functions will also not be saved. 

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.29

### Severity impact

Low

### What platform are you seeing the problem on?

Linux

**Comment by qtchaos** [comment]
Fixed in a.30, update your browser.

**Comment by MichaHere** [comment]
Okay, thanks.
