### ISSUE TITLE
Speech Dispatcher won't open

### ISSUE THREAD

**Issue by jwoertink** [zen-browser/desktop#933]
### What happened?

When loading a page that uses  the`SpeechSynthesisUtterance` javascript, this error is shown

![Screenshot from 2024-08-26 13-12-34](https://github.com/user-attachments/assets/f2a12860-d0fe-436b-b37b-8610fbb61741)

This doesn't happen on Firefox, and I can confirm that `spd-say hi` runs in the console.

Running `1.0.0-a.28` on `Pop!_OS 22.04 LTS x86_64`.  

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.28 (64-bit)

### Severity impact

Low

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
This is an issue with firefox, please follow these instructions: https://connect.mozilla.org/t5/discussions/incomplete-support-page-for-speech-dispatcher/td-p/33985

**Comment by jwoertink** [comment]
I actually don't have any issues using it on Firefox directly. My site uses the speech dispatcher for our chat, and it works fine except in Zen. I'll give that a shot though. Thanks!

**Comment by PixsaOJ** [comment]
I was able to make it work on non Flatpak version. But Flatpak stayes the same

**Comment by robjac** [comment]
This is still an issue with the Zen Browser flatpak -- why is this ticket closed?

**Comment by jwoertink** [comment]
Yeah, using `1.11.5b (Firefox 137.0.2)` on Flatpak it still seems to not work. I've checked that `speech-dispatcher` is running too as the above article suggests

```
❯ speech-dispatcher
[Tue Apr 22 08:28:59 2025 : 723289] speechd: Speech Dispatcher 0.11.1 starting
[Tue Apr 22 08:28:59 2025 : 723316] speechd: Speech Dispatcher already running.

Speech Dispatcher already running.
```

**Comment by haiqu91** [comment]
> This is an issue with firefox, please follow these instructions: https://connect.mozilla.org/t5/discussions/incomplete-support-page-for-speech-dispatcher/td-p/33985

Flatpak version still has this problem. Just fyi.

Not a great first impression of Zen to have this thread be marked closed two years ago and yet the issue persists. The Mozilla page you are directed to puts this responsibility squarely on downstream.
