### ISSUE TITLE
Browser overflows if you have too much tabs

### ISSUE THREAD

**Issue by autriz** [zen-browser/desktop#934]
### What happened?

If you have opened tabs to the point that scrollbar shows up, and then try to shrink app on vertically, it overflows.

![image](https://github.com/user-attachments/assets/1e280a63-9de7-4ddb-8ae8-1ebca58df875)

### Possible fix
When setting tabbrowser-arrowscrollbox margin to 0, the issue disappears.

Before:
![Before image](https://github.com/user-attachments/assets/9fb0d236-2231-415c-b24c-c1ca104ddd46)

After:
![After image](https://github.com/user-attachments/assets/a059802c-e96e-4a79-8367-6deed18ba2cf)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.29

### Severity impact

Medium

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
Should be fixed for the next release 👍🏽 
Please let me know if the issue persists

**Comment by autriz** [comment]
After updating 1.0.0-a.31 the issue still persists
![Image](https://github.com/user-attachments/assets/3bd7b9be-2b3d-4dee-8d89-86621a467931)

**Comment by autriz** [comment]
@mauro-balades forgot to ping, check the comment above.
Also, is it necessary to control tab height using resize observer, and what issues appear if flexbox used instead?
