### ISSUE TITLE
Zen Uninstalled itself!

### ISSUE THREAD

**Issue by Ain-Dont-code** [zen-browser/desktop#938]
### What happened?

When I turned off my computer this moring, I tried to open Zen by the shortcut in my desktop an error menssage appear (I didn't take a screenshot) saying that: Files couldn't be found,  when I try to launch the Browser using it EXE. file it gave this error menssage:
![Captura de tela 2024-08-26 184820](https://github.com/user-attachments/assets/2ff65d13-755c-418d-9003-de2b5b2771a3)

It's in Portuguese but it says "The system couldn't find the specific files".

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.29

### Severity impact

Medium

### What platform are you seeing the problem on?

Windows

**Comment by GisTypical** [comment]
It happened to me as well, it was caused by Windows Defender.

**Comment by PowerzinBR** [comment]
Windows Defender deletes it, you will need to disable it (at least for me, it worked).
