### ISSUE TITLE
Zen theme and utilities store no longer working.

### ISSUE THREAD

**Issue by vytorrennan** [zen-browser/desktop#939]
### What happened?

After clicking the "Install Theme" button, it no longer installs. The button becomes gray after clicking it, but that is as far as it goes, it dosen't change to "Uninstall Theme" and it dosen't install. It was working fine on the previus version.

![zen_gSIHzHcgFJ](https://github.com/user-attachments/assets/26f1f31d-1485-4024-b39c-eb0da090c7d1)

The console after clicking the "Install Theme" button:

![zen_FsapxyXtrx](https://github.com/user-attachments/assets/74d6e37e-f269-444a-9921-71dbce96e72a)

It did let me uninstall the themes i had already installed, but i could not re install then after that, same problem

What i did before the theme store stopped working was:

- I updated the browser to version 1.0.0-a.30
- Created profiles two profiles (I had only the default profile before hand)

I can't tell which one of these broke the store, because i did them one after the other

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.30

### Severity impact

High

### What platform are you seeing the problem on?

Windows

**Comment by Arishawke** [comment]
This is also happening to me after updating to a.30. (Have not touched profiles myself, so I suspect it's the new update.)

**Comment by Zenwoh** [comment]
Just installed the browser for the first time here and I was about to open an issue about this as well, but on the themes repo 😅
Thankfully I saw this issue before posting mine

**Comment by mauro-balades** [comment]
The reason for this is because the website is suffering some sort of DDoS attack, it will be fixed shortly, sorry about that
