### ISSUE TITLE
Files don't open/upload on websites

### ISSUE THREAD

**Issue by KwiatekMiki** [zen-browser/desktop#940]
### What happened?

When I try to upload a file to Google Drive or open a .psd file in Photopea (reported it on https://github.com/photopea/photopea/issues/7106 before realizing it's a bug with the browser), it just doesn't do anything.

Here's me trying to upload 5 images to Google Drive in zen:

https://github.com/user-attachments/assets/0cc66ed4-e66b-4d77-96d8-f4c94fe891e7

Nothing happened.
And here's me trying to upload the same images but in Brave (same thing with Firefox, I just don't like to use it):

https://github.com/user-attachments/assets/ae5a2519-30ec-4758-914a-048c90b5c20f

Everything got uploaded.

<sub>i was trying to edit these videos in capcut online so i don't leak my messy home folder and was wondering why nothing was happening and i reminded myself about this issue that i was writing like 30 seconds ago</sub>

Drag and dropping doesn't work too... unless it's on GitHub. That's the only place where I got it working, but only with videos. Actually, nevermind, it stopped working when I tried that again. 

It only happens on Flatpak, it works with the AppImage.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.30 (only happens on the flatpak version)

### Severity impact

High

### What platform are you seeing the problem on?

Linux (more exactly Pop!_OS)

**Comment by defaltastra** [comment]
i've tried to to reproduce this and file upload seems working fine, perhaps the problem lies elswhere

**Comment by OhNoOhNOOO** [comment]
@ultravigilante what desktop environment do you use? I'm using Plasma 6 and it works fine, and OP seems to be using PopOS's Gnome fork so i'm curious if it's a DE related issue?

**Comment by KwiatekMiki** [comment]
> i've tried to to reproduce this and file upload seems working fine, perhaps the problem lies elswhere

Did you try that on Linux? Did you install it using the AppImage, Flatpak or are you using the zip file?

**Comment by ultravigilante** [comment]
> @ultravigilante what desktop environment do you use? I'm using Plasma 6 and it works fine on flatpak, and OP seems to be using PopOS's Gnome fork so i'm curious if it's a DE related issue?

I'm using Pop!_OS 22.04 LTS, Gnome 42.9

**Comment by neogeographica** [comment]
This may be because of an issue in the .desktop file. After installing the AppImage, I had to edit the ZenBrowser.desktop file that it created and add "%u" after the Exec path, so that any file arguments would get passed along.

Before:
```
Exec=/home/joel/.local/share/AppImage/ZenBrowser.AppImage
```

After:
``` 
Exec=/home/joel/.local/share/AppImage/ZenBrowser.AppImage %u
```

**Comment by KwiatekMiki** [comment]
i'm not responding to an ai

**Comment by neurokitti** [comment]
I tested this in the most recent version of zen twilight and I am not seeing the issue. if this issue still persists please re-open the issue.
