### ISSUE TITLE
Zen is terribly slow and stuttering

### ISSUE THREAD

**Issue by peedy2495** [zen-browser/desktop#948]
### What happened?

System Info:
 - Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz with 16 logical cores (multiple cores idle ;-)
 - 68GB ram; usage about 20-30%
 - swap disabled
 - Ubuntu 22.04.4 LTS (currently upgraded)
 - AppArmor stopped and it's profiles have been unloaded
 - selinux not installed
 
Tried versions:
- AppImages generic & specific
- Tarballs generic & specific

Appearance:
Zen is terribly slow and stuttering on all visited sites,

Logging:
Nor STDOUT outputs, neither redirected log outputs via --MOZ_LOG_FILE=./zen.log have any content.

-rw-r-----   1 peedy peedy    0 Aug 27 07:24 zen.log.child-10.moz_log
-rw-r-----   1 peedy peedy    0 Aug 27 07:24 zen.log.child-11.moz_log
-rw-r-----   1 peedy peedy    0 Aug 27 07:24 zen.log.child-12.moz_log
-rw-r-----   1 peedy peedy    0 Aug 27 07:24 zen.log.child-13.moz_log
-rw-r-----   1 peedy peedy    0 Aug 27 07:24 zen.log.child-14.moz_log
-rw-r-----   1 peedy peedy    0 Aug 27 07:24 zen.log.child-15.moz_log
-rw-r-----   1 peedy peedy    0 Aug 27 07:24 zen.log.child-16.moz_log
-rw-r-----   1 peedy peedy    0 Aug 27 07:24 zen.log.child-17.moz_log
-rw-r-----   1 peedy peedy    0 Aug 27 07:24 zen.log.child-18.moz_log
-rw-r-----   1 peedy peedy    0 Aug 27 07:24 zen.log.child-19.moz_log
-rw-r-----   1 peedy peedy    0 Aug 27 07:23 zen.log.child-1.moz_log
-rw-r-----   1 peedy peedy    0 Aug 27 07:24 zen.log.child-20.moz_log
-rw-r-----   1 peedy peedy    0 Aug 27 07:24 zen.log.child-21.moz_log
-rw-r-----   1 peedy peedy    0 Aug 27 07:24 zen.log.child-22.moz_log
-rw-r-----   1 peedy peedy    0 Aug 27 07:24 zen.log.child-23.moz_log
-rw-r-----   1 peedy peedy    0 Aug 27 07:24 zen.log.child-24.moz_log
-rw-r-----   1 peedy peedy    0 Aug 27 07:24 zen.log.child-25.moz_log
-rw-r-----   1 peedy peedy    0 Aug 27 07:24 zen.log.child-26.moz_log
-rw-r-----   1 peedy peedy    0 Aug 27 07:24 zen.log.child-27.moz_log
-rw-r-----   1 peedy peedy    0 Aug 27 07:24 zen.log.child-28.moz_log
-rw-r-----   1 peedy peedy    0 Aug 27 07:24 zen.log.child-29.moz_log
-rw-r-----   1 peedy peedy    0 Aug 27 07:23 zen.log.child-2.moz_log
-rw-r-----   1 peedy peedy    0 Aug 27 07:24 zen.log.child-30.moz_log
-rw-r-----   1 peedy peedy    0 Aug 27 07:24 zen.log.child-31.moz_log
-rw-r-----   1 peedy peedy    0 Aug 27 07:24 zen.log.child-32.moz_log
-rw-r-----   1 peedy peedy    0 Aug 27 07:23 zen.log.child-3.moz_log
-rw-r-----   1 peedy peedy    0 Aug 27 07:23 zen.log.child-4.moz_log
-rw-r-----   1 peedy peedy    0 Aug 27 07:23 zen.log.child-5.moz_log
-rw-r-----   1 peedy peedy    0 Aug 27 07:23 zen.log.child-6.moz_log
-rw-r-----   1 peedy peedy    0 Aug 27 07:23 zen.log.child-7.moz_log
-rw-r-----   1 peedy peedy    0 Aug 27 07:24 zen.log.child-8.moz_log
-rw-r-----   1 peedy peedy    0 Aug 27 07:24 zen.log.child-9.moz_log
-rw-r-----   1 peedy peedy    0 Aug 27 07:23 zen.log.moz_log
 

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Mozilla Zen 1.0.0-a.30 20240826130358 20240826130358

### Severity impact

Medium

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
Every log is empty
```

**Comment by niutech** [comment]
Is it due to disabled GPU acceleration (#1012)?

**Comment by mr-cheffy** [comment]
> Is it due to disabled GPU acceleration (https://github.com/zen-browser/desktop/issues/1012)?

Id say so yeah, ill close this issue and reopen if it still happens
