### ISSUE TITLE
The workspace list duplicates the data

### ISSUE THREAD

**Issue by ottopan** [zen-browser/desktop#953]
### What happened?

<img width="544" alt="图片" src="https://github.com/user-attachments/assets/8445bbef-d95d-4c52-96a7-e1ccc07a6244">

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0

### Severity impact

Medium

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by qtchaos** [comment]
Can't seem to replicate on v1.0.0-a.30 Windows
