### ISSUE TITLE
MacOS Zen - multiple profiles open being interpreted as one window

### ISSUE THREAD

**Issue by jonas-tm** [zen-browser/desktop#956]
### What happened?

DockMate as well as AltTab MacOS do not recognize multiple Profiles being opened. 
This makes switching between profiles complicated. 

In Chrome multiple profiles open are viwed as one application but switching between windows is possible.

In the following video I have 3 different profiles open but preview is always the same from on of the profiles.
https://github.com/user-attachments/assets/7edd64bd-a7e4-4509-9aa0-204b6324bac1

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.29 (64-bit)

### Severity impact

Low

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by fpigeonjr** [comment]
Yes, I would also like to distinguish Zen browser instances based on the what profile is being used. For example, I have a `personal` and `work` profiles it would be nice to tell the difference somehow or allow `meta-~` to switch between instances on Mac.

**Comment by fpigeonjr** [comment]
🤔does open in default browser questions/thoughts go here or would that be a separate issue?
