### ISSUE TITLE
Layout shift with "Expand Tabs on Hover" during Workspace selection pop-up

### ISSUE THREAD

**Issue by yvvki** [zen-browser/desktop#957]
### What happened?

When setting the sidebar into "Expand Tabs on Hover", during the workspace selection pop-up, the browser content would shifts when the cursor is outside the selection pop-up.

Reproduction:
1. Set the "Look and Feel" > "Sidebar and tabs layout" to "Expand Tabs on Hover".
2. Navigate to the workspace selection pop-up.
3. Hover the cursor on and off the pop-up selection window.
4. See the browser content shifts unexpectedly.

Expected behavior:
The browser content should remains not shifted.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.30

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by yvvki** [comment]
This issue seems to have change problem to just expanding the sidebar as per 1.0.1-a.

**Comment by ramansg** [comment]
https://github.com/user-attachments/assets/f6c52d2b-242e-4f36-91c9-8b7fef15b60b

Seems like I'm facing the same issue.

**Comment by yvvki** [comment]
This issue seems to be fixed as per 1.0.1-a.2. Closing.

**Comment by heydoyouknowme0** [comment]
I think this has come back in v1.0.1-a.3
