### ISSUE TITLE
Main Website is Inaccessible (Forbidden)

### ISSUE THREAD

**Issue by albu-ali** [zen-browser/desktop#958]
### What happened?

**Description:**

The main website of the browser is currently inaccessible, possibly due to recent security implementations that check every user. This prevents users from accessing important information and updates about the browser.

**Issue:**

- The main website of the zen browser is forbidden to visit.

**Screenshots:**
![zen-08-27_12-21](https://github.com/user-attachments/assets/0bddbd54-e7db-4152-854e-1ef4feed844a)
![2024-08-zen-20](https://github.com/user-attachments/assets/490632a2-8854-4c4d-be5a-f762324421e7)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.30 (64-bit)

### Severity impact

Critical

### What platform are you seeing the problem on?

Linux

**Comment by NOCanoa** [comment]
This is the app repo, issues related to site [here](https://github.com/zen-browser/www)
but yes it a measure to reduce traffic for now, vercel is flagging a lot off false positives, back to normal soon

**Comment by albu-ali** [comment]
@NOCanoa Sorry for the mistake (IDK that you guys open source every single bit of the project!)

Keep up the awesome work!
