### ISSUE TITLE
Self updater broke (possibly due to Vercel bot check)

### ISSUE THREAD

**Issue by vicvancooten** [zen-browser/desktop#959]
### What happened?

After the site outage today, I've noticed that the self updater broke. I assume this is due to the Vercel bot check that's in front of the website.

![image](https://github.com/user-attachments/assets/8011ceac-0d85-4ac0-9b7b-73495b7f3633)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Alpha 30

### Severity impact

Medium

### What platform are you seeing the problem on?

Windows

**Comment by pakhrom** [comment]
The https://www.zen-browser.app/ website does not open in Firefox and Zen Browser; the error code is 403.

**Comment by pakhrom** [comment]
The https://www.zen-browser.app/ website is now available to open in  Zen Browser, but not Firefox

**Comment by vicvancooten** [comment]
@pakhrom I think this may be a caching issue. Try hitting `ctrl + shift + r`. They added a DDOS protection layer, which is probably a good idea. However, as reported, this seems to break the self updater as it doesn't get past the protection. :)

**Comment by pakhrom** [comment]
@vicvancooten That solved the problem. Thanks!
