### ISSUE TITLE
Brower cannot be started if built. [linux]

### ISSUE THREAD

**Issue by Autumnlight02** [zen-browser/desktop#960]
### What happened?

I basically pulled it, ran the build and I continuesly get the following error:
![image](https://github.com/user-attachments/assets/a8a29619-24ec-4373-b1fb-f0ff04573fc0)

I ran the bootstrap command, the build command and then start

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0

### Severity impact

High

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
[autumnlight@autumnlight]npm run start

> zen-core@1.0.0 start
> cd engine && ./mach run --noprofile

 0:00.43 /var/home/autumnlight/Documents/github/personal/zen-browser/desktop/engine/obj-x86_64-pc-linux-gnu/dist/bin/zen -no-remote
JavaScript error: resource://gre/modules/ShortcutUtils.sys.mjs, line 142: TypeError: keyAttribute is null
console.info: "ZenThemeImporter: Initiating Zen theme importer"
console.info: "ZenThemeImporter: Zen theme imported"
console.info: "ZenWorkspaces: Initializing ZenWorkspaces..."
JavaScript error: chrome://browser/content/tabbrowser/tabbrowser.js, line 6064: TypeError: this.selectedBrowser is undefined
console.info: "ZenWorkspaces: ZenWorkspaces initialized"
JavaScript error: , line 0: uncaught exception: undefined
JavaScript error: , line 0: uncaught exception: undefined
JavaScript error: resource:///modules/sessionstore/SessionStore.sys.mjs, line 2749: TypeError: browser is undefined
console.info: "ZenThemeModifier: init browser layout"
console.info: "Zen CKS: Initializing shortcuts"
JavaScript error: chrome://browser/content/tabbrowser/tabbrowser.js, line 6064: TypeError: this.selectedBrowser is undefined
JavaScript error: chrome://browser/content/tabbrowser/tabbrowser.js, line 6071: TypeError: this.selectedTab is undefined
JavaScript error: resource:///modules/UrlbarInput.sys.mjs, line 3669: TypeError: this.window.gBrowser.selectedBrowser is undefined
JavaScript error: resource:///modules/ReportBrokenSite.sys.mjs, line 389: TypeError: tabbrowser.selectedBrowser is undefined
console.info: "ZenThemeModifier: set tabs max-height to" "577.6666870117188px"
JavaScript error: chrome://browser/content/tabbrowser/tabbrowser.js, line 6071: TypeError: this.selectedTab is undefined
JavaScript error: resource:///modules/UrlbarInput.sys.mjs, line 1965: TypeError: WeakMap key undefined must be an object

...  (many times the following)
Assertion failure
assert@resource:///modules/AsyncTabSwitcher.sys.mjs:505:36
preActions@resource:///modules/AsyncTabSwitcher.sys.mjs:572:10
handleEvent@resource:///modules/AsyncTabSwitcher.sys.mjs:1095:12
Assertion failure

```

**Comment by Autumnlight02** [comment]
![image](https://github.com/user-attachments/assets/d386989a-d335-4b34-9c35-2c2a84e7ca50)

**Comment by mauro-balades** [comment]
Hi, you need to run `sh scripts/update-en-US-packs.sh` and start again

**Comment by LeMoonStar** [comment]
> Hi, you need to run `sh scripts/update-en-US-packs.sh` and start again

When doing the following:
```bash
git pull
git submodule update
pnpm run init
pnpm run build
sh scripts/update-en-US-packs.sh
pnpm run start
```
The same problem occurs.

I am now re-building, having run the script before the build - Will report once I get the results.

**Comment by LeMoonStar** [comment]
I can report: running `sh scripts/update-en-US-packs.sh` after the init and before the build works.

If this isn't going to be added to the build scripts any time soon, it should probably be included in the build instructions.

**Comment by mauro-balades** [comment]
We are currently reworking the docs right now

**Comment by HarryHeres** [comment]
Can confirm that `sh sripts/update-en-US-pack.sh` needs to be run after `npm run init` and before `npm run build` in order for the browser to be able to work properly on MacOS. 

I second @LeMoonStar 's idea to include in in the build scripts.

**Comment by mauro-balades** [comment]
Or just include the update-en-US-pack to the "init" command yeah

**Comment by HarryHeres** [comment]
> Or just include the update-en-US-pack to the "init" command yeah

Yup! Want me to implement that? Would love to help out with the development :)

**Comment by LeMoonStar** [comment]
I wonder, when building, shouldn't all languages be included?

I know the download-language-packs.sh does run the update script on all languages, BUT it also changes global git configuration and should either probably not be used by anybody (except for Github actions) or be rewritten to not have such side effects.

**Comment by HarryHeres** [comment]
> I wonder, when building, shouldn't all languages be included?
> 
> I know the download-language-packs.sh does run the update script on all languages, BUT it also changes global git configuration and should either probably not be used by anybody (except for Github actions) or be rewritten to not have such side effects.

Good point
