### ISSUE TITLE
Zen just auto delete and when i install it back it lost it icon

### ISSUE THREAD

**Issue by Dredragon-Austin** [zen-browser/desktop#961]
### What happened?

So i was thought that i close my laptop but it eventually not and force to sleep mode and i don't know how but it automatic delete zen and when i dowload it back it lost it icon
![image](https://github.com/user-attachments/assets/3854cfc2-2993-465c-bd09-6413fa21d8b0)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0

### Severity impact

Medium

### What platform are you seeing the problem on?

Windows

**Comment by haripako** [comment]
It's the Windows antivirus, it deletes it, at the moment until the developer certificate is available this happens, it's a false positive
