### ISSUE TITLE
[Windows] Failed to check for updates

### ISSUE THREAD

**Issue by rblaine95** [zen-browser/desktop#966]
### What happened?

When trying to check for Zen Browser updates, it just says "Failed to check for updates"

![image](https://github.com/user-attachments/assets/4597b7b1-3fb8-4ada-9e00-e0fe2b9fc26b)

After manually upgrading from `1.0.0-a.29` to `1.0.0-a.30`, the issue is still present.

Mozilla Firefox checks for updates perfectly fine:
![image](https://github.com/user-attachments/assets/0d6be682-110f-4e6a-a92b-0e6f4ab82109)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.30

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by matdave** [comment]
I believe this is related to the website outage. It looks like bot protection was added which may be blocking the browser from performing checks.

**Comment by rblaine95** [comment]
@matdave, that makes sense, checking for updates is working now 🎉 

![image](https://github.com/user-attachments/assets/c4808ce2-8337-4b5c-8898-d11ba769f297)
