### ISSUE TITLE
Closing Pinned Tabs Removes Them from Pinned List and Changes Pinned Page After Navigation .

### ISSUE THREAD

**Issue by Aricept094** [zen-browser/desktop#970]
### What happened?

When selecting "Close Tab" on a pinned tab in Firefox, the tab is removed from the list of pinned tabs. This issue also occurs in Firefox Nightly. However, in the Arc browser, selecting "Close Tab" for a pinned tab behaves differently. In Arc, the tab remains in the list of pinned tabs but closes the page. When reopened, the tab returns to the original pinned page. Additionally, in Firefox, if a user is forwarded to a different website while on a pinned tab, the pinned tab's homepage changes to the new site. The correct behavior, as seen in Arc, should keep the original pinned webpage intact, regardless of browsing to other sites or closing the tab.

### Reproducible?

- [X] I have checked that this issue can be reproduced on Mozilla Firefox.

### Version

Alpha build - 1.0.0-a.30 (2024-08-26)

### Severity impact

Medium

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
This is intended behavior, the button "close tab" does indeed simply close the tab, if you want to submit an enhancement please refer to the discussions 👍🏽

**Comment by Aricept094** [comment]
got it
