### ISSUE TITLE
I cant install anything from the themes store

### ISSUE THREAD

**Issue by M4rti21** [zen-browser/desktop#971]
### What happened?

Everything was working fine, on the arch linux package of zen-browser, i decided to move to the flatpak version instead, so i uninstalled the arch version, remove the .zen directory from my home and installed the flatpak version, i tried to install "disable rounded corners" and "remove mute indicator" from the themes store but the button stays semi clicked like its trying to install the extension but does nothing, i've also reinstalled the arch packaged version and its not working on it either, so i think its more of a problem with the store maybe?

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.30

### Severity impact

Medium

### What platform are you seeing the problem on?

Linux

**Comment by kennytheeggman** [comment]
I am having the same problem on Windows. Tried reinstalling and the issue is still present.

**Comment by atliv** [comment]
having same problem on windows too.

**Comment by ceselder** [comment]
same problem on windows and nixos since yesterday

**Comment by toodeluna** [comment]
Same problem on Linux (EndeavorOS).

**Comment by mohvn** [comment]
> ### What happened?
> 
> Everything was working fine, on the arch linux package of zen-browser, i decided to move to the flatpak version instead, so i uninstalled the arch version, remove the .zen directory from my home and installed the flatpak version, i tried to install "disable rounded corners" and "remove mute indicator" from the themes store but the button stays semi clicked like its trying to install the extension but does nothing, i've also reinstalled the arch packaged version and its not working on it either, so i think its more of a problem with the store maybe?
> ### Reproducible?
> 
>     * [ ]  I have checked that this issue cannot be reproduced on Mozilla Firefox.
> 
> 
> ### Version
> 
> 1.0.0-a.30
> ### Severity impact
> 
> Medium
> ### What platform are you seeing the problem on?
> 
> Linux
> ### Relevant log output
> 
> _No response_

https://www.zen-browser.app/ has become the target of some DDoS attacks since yesterday. Mauro changed some things in the site's backend structure to mitigate attacks, which will probably be fixed in the next release.

https://fosstodon.org/@zenbrowser/113032388154247749

**Comment by Fartwell** [comment]
same issue on windows and macos

**Comment by Swissbite** [comment]
Same problem on Tuxedo OS 3 (Ubuntu 22.04) with flatpak. 

Logged message
```
Failed to get subsystem status for purpose
Object { rejected: true, message: 
Error: Attempt to postMessage on disconnected port
​​columnNumber: 14
​​fileName: "moz-extension://81c91c14-9773-457a-8c25-7b26f987da87/extension-utils.js"
​​lineNumber: 72
​​message: "Attempt to postMessage on disconnected port"
​​stack: "sendPortMessageWithReply/<@moz-extension://81c91c14-9773-457a-8c25-7b26f987da87/extension-utils.js:72:14\nsendPortMessageWithReply@moz-extension://81c91c14-9773-457a-8c25-7b26f987da87/extension-utils.js:58:12\n@moz-extension://81c91c14-9773-457a-8c25-7b26f987da87/extension.js:247:12\n@moz-extension://81c91c14-9773-457a-8c25-7b26f987da87/extension-utils.js:130:57\n" }
```

**Comment by M4rti21** [comment]
ok so it seems they are aware of this so i'll close the issue then :D

**Comment by Raphael-08** [comment]
same issue nixos

**Comment by mauro-balades** [comment]
The website suffered a DDoS attack which lead me to rewriting the site so that it was static. The new API will be used in zen version 31 (being released right now)

**Comment by iamalexei** [comment]
@mauro-balades Please, update the Flathub version to 1.0.0-a.31. Thank you
