### ISSUE TITLE
Google Meet - Can't see or hear participants

### ISSUE THREAD

**Issue by TomTruyen** [zen-browser/desktop#972]
### What happened?

When using Google Meet on my Mac with Zen:

1. I give permissions to use Microphone and Camera
2. My Microphone and camera work
3. I join the Google Meet
4. Everyone is shown as just their profile picture, even though they have their camera's on. Furthermore everyone is shown as "muted" which also isn't the case. If someone is sharing their screen, I can't see that either.

Expect:
Google Meet should work as it does on other browsers

Workaround:
Use a different browser for Google Meet :(

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0

### Severity impact

High

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by that-ambuj** [comment]
Could you check if this issue is also present in regular firefox browser? I've had people have a similar browser issue with google meet where they couldn't use it in firefox but it worked perfectly fine in chrome.

**Comment by TomTruyen** [comment]
I just checked. This is also an issue on Firefox. Though it can't be that this is just a feature, is there some setting or `about:config` that can be set to fix it?

**Comment by that-ambuj** [comment]
@TomTruyen Sadly, I don't have a mac anymore. I daily drive linux and windows with firefox 129(now zen browser) and It's not an issue for me. So, I can't really debug it for you. However, you can check the firefox bugzilla for this issue or create one there.

Meanwhile, use chrome/chromium just for meetings. You could also check if other options like Zoom work fine on firefox just to confirm that the issue is with firefox or google meet before creating an issue on firefox bugzilla.

**Comment by meguroyama** [comment]
As noted in this [Moz question forum](https://support.mozilla.org/bm/questions/1367141) looks like the issue is likely due to privacy / security configuration on your Firefox. It often breaks in brave too so I'd temporarily disable them just for `meet.google.com` domain.

**Comment by R4K0** [comment]
The question forum linked above seems to relate to inability to share certain windows, unrelated to this.

+1 to the issue. I am trying to migrate to Zen (from Arc) on my work laptop (Mac M2) and whenever joining the meeting, I can see the list of participants, but none of their video cams are loaded in (I just see their avatar consisting of a letter) and I cannot hear the participants. After a minute or two, Google meet drops me.

@meguroyama comment had me try adding meet.google.com to the exception list for these options:
![CleanShot 2024-09-06 at 15 42 26@2x](https://github.com/user-attachments/assets/b743604c-3dd3-41db-911c-382e02d7404e)
I also tried to disable the custom DNS resolution:
![CleanShot 2024-09-06 at 15 46 15@2x](https://github.com/user-attachments/assets/e8bbf65a-926d-42ed-907b-a0baf2a7a04a)
None of these worked.

Some of items of interest in the console:
![CleanShot 2024-09-06 at 15 45 01@2x](https://github.com/user-attachments/assets/174d6f63-5de2-4f1d-b6d4-581cd9dce7c1)
(uBlock Origin disabled at moment of screenshot)

Screenshot when I get dropped:
![CleanShot 2024-09-06 at 15 42 51@2x](https://github.com/user-attachments/assets/6846710d-760f-4523-9c68-94f7242181da)

Extensions I run:
uBlock Origin
1 Password
I still don't care about cookies

For all of the above tests, I have disabled all of my extensions to no avail.

**Comment by R4K0** [comment]
Went into about:webrtc and noticed it couldn't resolve the some of the addresses.
![CleanShot 2024-09-06 at 17 29 04@2x](https://github.com/user-attachments/assets/91e9b09e-80a5-4697-a8df-a67957944024)

After googling a bit, and going back-and-forth between issues from years ago, I took a look at `about:config` and I noticed `media.peerconnection.ice.default_address_only` setting which was set to `true` - I set it to False, and suddenly google meet started working! :) @TomTruyen, you were looking for a setting that could fix it - this potentially could be a fix for you.

**Comment by R4K0** [comment]
Looks like this change was propagated down to Zen by bundling "Betterfox" with Zen https://github.com/yokoffing/Betterfox
Line responsible for setting this preference config to true can be found here. https://github.com/zen-browser/desktop/blob/ad95eed29fe566430ff776e68e902788b3262299/src/browser/app/profile/better-fox.js#L107

**Comment by mauro-balades** [comment]
Please dont just put "1.0.0" as the version number, now I dont know when it started happening

**Comment by mauro-balades** [comment]
> Looks like this change was propagated down to Zen by bundling "Betterfox" with Zen https://github.com/yokoffing/Betterfox Line responsible for setting this preference config to true can be found here.
> 
> https://github.com/zen-browser/desktop/blob/ad95eed29fe566430ff776e68e902788b3262299/src/browser/app/profile/better-fox.js#L109

Should I remove it?
