### ISSUE TITLE
Disable autofocus url on launch

### ISSUE THREAD

**Issue by migueel15** [zen-browser/desktop#973]
### What happened?

**Description**
When opening a new instance of Zen Browser, the cursor is automatically focused on the URL bar. If a custom start page is used, this behavior causes the cursor to move to the beginning of the URL, which may not be desirable in certain setups.

**Expected Behavior**
In my particular case, my start page includes a search bar, and I would prefer the focus to be on this search bar rather than the URL bar when the browser is launched.

**Request**
Is there an option or a configuration setting available that would allow the focus to remain on the elements of the start page instead of the URL bar upon startup? If not, could this be considered for a future update?

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0

### Severity impact

Low

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
Issues are not for enhancements, please use discussions instead
