### ISSUE TITLE
Switching from workspaces close most if not all tabs

### ISSUE THREAD

**Issue by Yu2sama** [zen-browser/desktop#976]
### What happened?

When using the not default Workspace and opening several tabs, if you switch from the current Workspace to the default one, all tabs get closed (or almost all of them). This also happens in the default one but not as severe (for example when changing from Workspace A to B, some tabs will be "closed")

I also noticed that, even if they appear "closed" such tabs are still consuming ram (so maybe they are not actually closed, but not appearing)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by BearDad** [comment]
It would be interesting for you to indicate in which webpages this happens. for me atleast for now only happens with youtube. 

### **Version**
1.0.0-a.30

**Comment by Yu2sama** [comment]
So far, It has happens to me in the most websites I use, Twitter, Pinterest, Youtube and Reddit. And yeah like you said, it happens with pages that I haven't a looked at, but If I have seen its content, it doesn't close.

**Comment by BearDad** [comment]
I guess it has to do with the way pages charge when opening them in a new tab. Just checked and it also happens with github.

# !!!WARNING!!!
Upon closer inspection they seem to go into the hidden tabs menu which open when you click the right facing arrow 
![image](https://github.com/user-attachments/assets/336c5c7b-a348-46bf-8df2-d00d3c0c8121)

the functionality seems to work by hiding the tabs from one workspace when opening another workspace which in turn makes some tabs perma hidden when you haven't interacted with them.
for example i can create  a workspace in which i open youtube and middle click a video and then change to the other workspace and it will show both tabs hidden.

like so:
![image](https://github.com/user-attachments/assets/1e8c0e51-b377-4ee8-bfcc-747c64fd8b63)


but when returning to that workspace it wont reappear.

like so:
![image](https://github.com/user-attachments/assets/21cc9f87-f951-45e7-a83d-20143c134287)

**Comment by BearDad** [comment]
so effectively when reopening a closed session and changin into another workspace it should hide everything

**Comment by mauro-balades** [comment]
Workspaces dont close tabs, they hide them its a way of organization, if we close them, we wont get them back

**Comment by badjuice** [comment]
> Workspaces dont close tabs, they hide them its a way of organization, if we close them, we wont get them back

So the expected behavior is still not what's happening, right?


Also, I intuitively assumed that the hidden tabs and workspace were two separate/independent features.

Am I wrong? Did I not understand something right or fully?

**Comment by BearDad** [comment]
it indeed does not work as expected. and they are not two separate functions it uses the hidden tab functionality of firefox. and adds some kind of dynamic hide & show with an added UI element. as far as i can understand it without checking the code for it. it's a nice implementation but nonetheless has it's bugs. we gotta remember this is an alpha. tho I do expect this issue being mentioned more as time goes by and eventually getting fixed.

**Comment by badjuice** [comment]
I hope so. I will steer clear from using the feature for the time being tho. I have way too many tabs open to risk losing them all.

**Comment by GitMurf** [comment]
For me it seems workspaces are completely broken. I move tabs to a new workspace, switch to my default workspace, then when I go back to the other workspace, they are completely gone.

I have tried experimenting in a number of different ways opening new windows, closing and re-opening after different scenarios, etc. etc. and to me the Workspaces feature overall seems inconsistent and buggy.

My general workflow has been:

- Open a bunch of tabs
- Select similar tabs I want to group and move them to a new window
- Create a new workspace from that new window
- Close the workspace
- Try to go back to that workspace and the tabs are all (or mostly all) gone

**Comment by GitMurf** [comment]
> Workspaces dont close tabs, they hide them its a way of organization, if we close them, we wont get them back

This to me is a bit counter-intuitive and confusing and not the way I am use to other browsers doing workspaces. I usually use workspaces as a way to silo off tabs for different projects etc. From what it sounds like, Zen is going to always have ALL tabs or all workspaces open but just hides all the tabs that are not part of your active workspace?

I also use workspaces as a way to conserve resources (too many tabs open). But it sounds like the list of tabs will just keep growing as you create more workspaces?

**Comment by GitMurf** [comment]
Last question... is this the way the Workspaces feature is meant to work long term (all tabs always open but just hides tabs not in the workspace)? If so, unfortunately that will not work for my workflow and I will have to unfortunately go back to using Edge.

**Comment by BearDad** [comment]
@mauro-balades As said previously  it just does not work as intended. If the user has not interacted with the tab pre changing workspaces it will go into the hidden tabs forever. So they do disappear but don't close @GitMurf

**Comment by BearDad** [comment]
> Last question... is this the way the Workspaces feature is meant to work long term (all tabs always open but just hides tabs not in the workspace)? If so, unfortunately that will not work for my workflow and I will have to unfortunately go back to using Edge.

I hope it is not but all things said it would need to be implemented from 0 since Firefox got rid of tab groups on Firefox 45. I guess the hide and show things is more of a conceptual thing to test the usefulness of it and how many users want it

**Comment by GitMurf** [comment]
> So they do disappear but don't close @GitMurf

I have noticed both! I am aware of the hidden tabs (took me a while to figure it out as very counter intuitive) and sometimes they are there, other times completely closed. I think it is because I tend to open a workspace into its own window and then when I close that window my expectation is it saves the workspace as is (this is how other browsers work with workspaces). But I guess when I am doing that, it may just be closing the tabs since I have other windows open (default workspace).

**Comment by BearDad** [comment]
> > So they do disappear but don't close @GitMurf
> 
> I have noticed both! I am aware of the hidden tabs (took me a while to figure it out as very counter intuitive) and sometimes they are there, other times completely closed. I think it is because I tend to open a workspace into its own window and then when I close that window my expectation is it saves the workspace as is (this is how other browsers work with workspaces). But I guess when I am doing that, it may just be closing the tabs since I have other windows open (default workspace).

I guess it's because each window it's a different session  and since it's not a tab group perse you cannot save the state of all the windows and their different tabs. You could be in a Coding workspace let's say in both windows with different tabs. The one that will persist it's the opened one and the closed one just vanishes. This is mostly a Firefox problem and probably would be fixed with an extension(Mozilla themselves recommend them) so unless the contributors of zen do implement it from 0 I don't think it will be working as expected.

**Comment by mauro-balades** [comment]
I need like a video or something, I really can't visualise the issue, I'm sorry

**Comment by BearDad** [comment]
> I need like a video or something, I really can't visualise the issue, I'm sorry

yeah sure letme record it real quick and upload it to YT

**Comment by BearDad** [comment]
@mauro-balades Here you go. i guess something changed in last update and now the behavior is different still bugged AF but different here you have the video:
[Youtube](https://youtu.be/E8V2En8MSmQ)

**Comment by mauro-balades** [comment]
huh...

**Comment by BearDad** [comment]
> huh...

S-FOKING-TRANGE aint't that right?
