### ISSUE TITLE
Unable to install zen themes on linux

### ISSUE THREAD

**Issue by jake8655** [zen-browser/desktop#980]
### What happened?

I installed the optimized version of zen from [the aur](https://aur.archlinux.org/packages/zen-browser-optimized-bin). I tried to install some themes from the [zen theme store](https://www.zen-browser.app/themes) but the theme does not get downloaded and the button remains focused:
![image](https://github.com/user-attachments/assets/515ef22d-c78b-4065-9b9e-e87f08bbd2c6)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.29

### Severity impact

High

### What platform are you seeing the problem on?

Linux

**Comment by LautiLosio** [comment]
Read #971

Also. "Can't install themes" is not high severity...

**Comment by 0romos** [comment]
The store has an issue, it will be updated soon. Just wait.

**Comment by jake8655** [comment]
> Read #971 

Oh okay, thank you I didnt see that issue (gotta love the github issue search)

> Also. "Can't install themes" is not high severity...

I wanted to put it in medium, but the description said "major inconvenience, **but workaround exists**", thats why I decided to increase it to high severity. Sorry for the incovenience, maybe modifying that description could help future misunderstandings.

**Comment by adminy** [comment]
![image](https://github.com/user-attachments/assets/929f1671-dae8-419f-bd2a-d878c62f7d36)

same here. spiceandwolf-holo-mundo-1 seems to work with firefox, there is space in zen-browser for the logo, but not working with zen.
