### ISSUE TITLE
 Feature idea - use empty space in area with browser tabs to also move windows. 

### ISSUE THREAD

**Issue by sortofsleepy** [zen-browser/desktop#981]
### What happened?

👋 

Stumbled across this the other day and decided to give it a spin. I'm impressed so far!

Just came across one very minor UI bug + one feature idea I think would be good. Not sure if this is the right spot for this kind of bug and feedback but since the feedback button in the browser takes me to a Mozilla page I thought I would just post here. 

Feature idea - when possible, use empty tab space to also move windows
---
As far as I can tell,  only click+drag the top of the window will move the window around the screen. Floorp, when using vertical tabs, has it set up so you move the window by clicking and dragging within the empty space that contains the browser tabs. Not sure how feasible it is but I think it'd be neat if Zen could incorporate that as well.  

Definitely WAY lower priority compared to what else you folks must have on your plate but just a suggestion. 

![Screenshot 2024-08-27 135856](https://github.com/user-attachments/assets/e77546be-9cfa-4e0d-b212-07c9eeca7abc)

~Bug~
---
~I can't consistently reproduce this but I have noticed from time to time, when going to the address field to go to a new page or search, the padding between what I'm typing and the magnifying glass is non-existent and the icon background isn't fully rounded.~

~If I happen to figure out how to consistently reproduce it, I will update this or add another comment.~

Didn't realize #617 existed; +1 for reproducibility. 

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.30 (64-bit)

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by qtchaos** [comment]
Bug is same as https://github.com/zen-browser/desktop/issues/617 (means it can be reproduced!)

**Comment by sortofsleepy** [comment]
Doh! I totally didn't think to search first, my bad. Updating now.

**Comment by wangwei1073** [comment]
i also need this feature ,it is important for me!

**Comment by Shyboy-101** [comment]
This is the feature in my **D R E A M.**

**Comment by NOCanoa** [comment]
I can do it on 1.0.1-a.7 👀

**Comment by lbngoc** [comment]
Could we have this feature as an option? I am not a fan of it because I only need to click the mouse to change the active tab, but if the click isn't precise, the window moves slightly.

**Comment by jimhuds** [comment]
Agree, this can get slightly annoying with the new window snapping on MacOS
