### ISSUE TITLE
Immediate error：Not a valid Win32 application

### ISSUE THREAD

**Issue by hcymysql** [zen-browser/desktop#984]
### What happened?

![image](https://github.com/user-attachments/assets/ad93fe35-4c1f-46d5-9cc3-ee71ca498636)

win7 64

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

lastest

### Severity impact

High

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
Immediate error：Not a valid Win32 application"
```

**Comment by hcymysql** [comment]
Please release a version that supports Windows 7. After all, Windows 7 still has a market, and not everyone is willing to upgrade to Windows 11. Thank you.

**Comment by amtoaer** [comment]
https://support.mozilla.org/en-US/kb/firefox-users-windows-7-8-and-81-moving-extended-support

> [Firefox version](https://support.mozilla.org/en-US/kb/find-what-version-firefox-you-are-using) 115 will be the last supported Firefox version for users of Windows 7, Windows 8 and Windows 8.1. If you are using these versions of Windows you will be moved to the Firefox [Extended Support Release](https://www.mozilla.org/firefox/enterprise) (ESR) channel by an application update. Mozilla will provide security updates for these users until September 2024. No security updates will be provided after that date.

Firefox has officially dropped support for Windows 7. This issue is unrelated to Zen browser.
