### ISSUE TITLE
the screenshot button moves to the left across the screen in compact mode

### ISSUE THREAD

**Issue by onlyibra** [zen-browser/desktop#987]
### What happened?

the screenshot button moves to the left across the screen in compact mode
<img width="959" alt="Cuplikan layar 2024-08-28 123207" src="https://github.com/user-attachments/assets/98b99fc3-fc1a-45fb-a03d-c2affb3d4076">

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.31

### Severity impact

Medium

### What platform are you seeing the problem on?

Windows

**Comment by KotonBads** [comment]
![image](https://github.com/user-attachments/assets/397b607c-d814-42c4-ac4a-63e7f43a13e1)

also happens on linux, zen v1.0.0-a.30

**Comment by Axmdstar** [comment]
![Screenshot 2024-08-29 093659](https://github.com/user-attachments/assets/6f30e7f7-5fb5-4427-9774-1ed57126439c)

I have this bug too in my 1920x1080 laptop, it only happens in compact mode

**Comment by KotonBads** [comment]
fixed in `1.0.2-b.2`
