### ISSUE TITLE
Hotkey not working as expected: Cycle Workspaces; Toggle Sidebar

### ISSUE THREAD

**Issue by marsjane** [zen-browser/desktop#991]
### What happened?

I set hot key as follows:
![Shot 2024-08-28 at 13 42 04@2x](https://github.com/user-attachments/assets/96dbe560-161c-4b76-9763-75f7f7b06c1f)
![Shot 2024-08-28 at 13 45 09@2x](https://github.com/user-attachments/assets/4f0b856c-97ed-4c68-a3f5-c51a9456b0cc)
These two both not work as expected:
1. the Cycle workspace one totally not working, cannot switch to next workspace
2. The sidebar one, I want it to expand/unexpand the tabs, but it just toggle the bookmark sidebar, if this is what you expected, can you also provide one more hotkey for toggle expand sidebar tabs?, just like the function of the second button at the sidebar

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.31 (64-bit)

### Severity impact

Medium

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by ExistentialAlex** [comment]
Seems related to this issue which was closed: https://github.com/zen-browser/desktop/issues/733

Though a hot key wasn't provided.

**Comment by quadbyte** [comment]
Can confirm "Toggle Sidebar" is actually toggling the Bookmarks bar.

**Comment by GabrielGASB** [comment]
Same problem here, Windows 10.

**Comment by RayZ3R0** [comment]
Does this still happen on latest version? (a.14 as of this comment)

**Comment by salamijason** [comment]
No response in 2 weeks, will be closing this issue. Please reopen if issue persists.

**Comment by marsjane** [comment]
hi sir, I just try to go through some hotkeys, now I found that the key used for next workspace: Alt+CMD+E sometimes not working as expected. When I first try it, it works fine but now it just show this when I press this hotkey:
![Shot 2024-11-12 at 17 06 36@2x](https://github.com/user-attachments/assets/ed18bc22-53b2-4784-9dd2-3e2ccf41cd90)

**Comment by marsjane** [comment]
![Shot 2024-11-12 at 17 12 03@2x](https://github.com/user-attachments/assets/0df369e1-614f-4db3-aeae-04973677cae9)
I cannot reopen this issue, can you help reopen?

**Comment by marsjane** [comment]
Now I use the latest version: 1.0.1-a.19 (Firefox 132.0.1) (aarch64)

**Comment by marsjane** [comment]
np I will open another issue for this

**Comment by salamijason** [comment]
Looks like its a known issue that Mauro has on his linear already. https://github.com/zen-browser/desktop/issues/1629#issuecomment-2415227709
