### ISSUE TITLE
Some places are not localised on the browser

### ISSUE THREAD

**Issue by nazmiyigitefe** [zen-browser/desktop#994]
### What happened?

I don't know if it's about me or the project, there is some places that doesn't localised. Things that in the screenshots are not translated but the preferences page and some others are translated.

![Ekran görüntüsü 2024-08-28 102738](https://github.com/user-attachments/assets/f0888e2c-4e6b-4c73-b9d2-2891819eb620)
![Ekran görüntüsü 2024-08-28 102749](https://github.com/user-attachments/assets/8a285fb2-730e-4225-b96e-cbd859f80ec0)
![Ekran görüntüsü 2024-08-28 102802](https://github.com/user-attachments/assets/18be51ec-d300-488c-9f61-b689f1a85bb0)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.31

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by ch4og** [comment]
duplicate of https://github.com/zen-browser/desktop/issues/923
