### ISSUE TITLE
How to move the left tab to the top of the browser

### ISSUE THREAD

**Issue by shenlongde** [zen-browser/desktop#997]
### What happened?

How to move the left tab to the top of the browser

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.31

### Severity impact

Medium

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
How to move the left tab to the top of the browser
```

**Comment by ch4og** [comment]
Not a feature yet.
here is feature request discussion: https://github.com/zen-browser/desktop/discussions/889

Horizontal tabs are in progress but aren't here yet

**Comment by BrhmDev** [comment]
Use discussions for feature requests, there is one open already: https://github.com/zen-browser/desktop/discussions/889
