### ISSUE TITLE
Zen sidebar is not working on Ubuntu 24 04 

### ISSUE THREAD

**Issue by naveenc1x** [zen-browser/desktop#998]
### What happened?

When try to add url to the zen sidebar it just does not add to sidebar

[Screencast from 2024-08-28 14-24-33.webm](https://github.com/user-attachments/assets/c216bee9-26e3-4e6e-bbcf-fc65b8cd5077)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Alpha build - 1.0.0-a.30 (2024-08-26) 

### Severity impact

High

### What platform are you seeing the problem on?

Linux

**Comment by ch4og** [comment]
it should include https://

**Comment by mauro-balades** [comment]
^^^ that is correct

Next release will just add https:// automatically, people seem to get confused about it

**Comment by naveenc1x** [comment]
Got it Thanks
